### ISSUE TITLE
DK bugs generales

### ISSUE THREAD

**Issue by xefirot** [RoDNet/Bugtracker-Infinium-4.3.4#1]
Hagamos un poco de trabajo en equipo y pongamos todos los bugs de clase en un mismo tema.

Levantar a muerto (necrófago) requiere polvo de cadáver

http://i43.tinypic.com/34t5q90.jpg

**Comment by crowel** [comment]
Las siguientes habilidades de los dks apenas hacen daño.

Fiebre de Escarcha: http://es.wowhead.com/spell=59921
![wowscrnshot_070413_014132](https://f.cloud.github.com/assets/3537253/746922/a449d886-e43f-11e2-809b-8c8696fa84e7.jpg)

Peste de sangre: http://es.wowhead.com/spell=59879
![wowscrnshot_070413_014146](https://f.cloud.github.com/assets/3537253/746923/f06e07d2-e43f-11e2-9d51-20d81a64a890.jpg)

**Comment by crowel** [comment]
La maestria del dk sangre no salta.
Maestría: Escudo de sangre
http://es.wowhead.com/spell=77513

**Comment by ghost** [comment]
Crowel, el escudo solo se activa en presencia de sangre en esta versión, por si no estabas en presencia de sangre.

**Comment by crowel** [comment]
Comprobada en ambas^^ no funciona.
Gracias por el aviso.

**Comment by crowel** [comment]
Golpe letal  //  http://es.wowhead.com/spell=49998
No cura, ni el 7% de la salud, ni los 5 seg del daño recibido por entidades no jugadoras.
Ademas del daño que hace es un poco mas bajo que deberia sobre unos 3-4k menos de la media.
Es raro porque antes de la caida estaba subido jaja.
Un saludo.

**Comment by xefirot** [comment]
No mireis las skills de clases en wowhead puesto que seguramente den indicaciones de mop (mist of pandarian) y no son aplicables aqui.

**Comment by crowel** [comment]
Nose que tendra que ver, en enlace es para saber la id para que los gms se guien cuando lo reparen, otra cosa que no me estoy fijando en el daño que debe de hacer ahi sino con el DrD.

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/39

**Comment by ghost** [comment]
> Golpe letal // http://es.wowhead.com/spell=49998
> No cura, ni el 7% de la salud, ni los 5 seg del daño recibido por entidades no jugadoras.
> Ademas del daño que hace es un poco mas bajo que deberia sobre unos 3-4k menos de la media.

![golpe letal](https://f.cloud.github.com/assets/4663665/749348/10b837b0-e4a9-11e2-8ea9-8a03d0ebbe61.jpg)

Nada más dejo la descripción exacta que sale en el juego para que no se confundan xd.

**Comment by ghost** [comment]
Agrego otros bugs: #90 #89

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/131

**Comment by efectokoleos** [comment]
golpe letal arreglado, falta implementarlo

**Comment by ghost** [comment]
Arma de runa danzante (http://es.wowhead.com/spell=49028) no otorga el 20% de parada, o al menos, no figura en el en cuadro de stats.

**Comment by ghost** [comment]
Voluntad de la necrópolis (http://es.wowhead.com/spell=81164) se activa con cada golpe recibido y sin la necesidad de estar por debajo del 30% de la salud máxima. También se refresca.

**Comment by ghost** [comment]
Buenas.
Ok, escudo de sangre funciona, pero no funciona su efecto acumulativo.
Venganza (http://es.wowhead.com/spell=93099) no funciona.
Saludos.

**Comment by ghost** [comment]
Por favor, si pueden pueden poner cada bug en un reporte a parte, así no miraran el reporte y no arreglarán las cosas.
