### ISSUE TITLE
[Misión][PNJ][Tierras Altas Crepusculares] Cuatro cabezas es mejor que ninguna (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1000]
Buenas.
La misión "Cuatro cabezas es mejor que ninguna" (http://es.wowhead.com/quest=27500) no se puede completar porque falta el PNJ Za'brox (http://es.wowhead.com/npc=46017) para lotear sus 2 cabezas (http://es.wowhead.com/item=61924)(http://es.wowhead.com/item=61925).
Gracias y saludos.

**Comment by redneo** [comment]
arreglado
