### ISSUE TITLE
[Misión][PNJ][Tierras Altas Crepusculares] Encuentra a Fanny

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1001]
Buenas.
La misión "Encuentra a Fanny" (http://es.wowhead.com/quest=28378) no se puede completar porque falta el PNJ Fanny Bramal (http://es.wowhead.com/npc=48499) para rescatar.
Por lo que leí en los comentarios de wowhead, Fanny aparece cuando se vence al PNJ Brogg Tripal (http://es.wowhead.com/npc=48480), que tampoco está.
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglado!arreglado, de mala manera... pero arreglado.
