### ISSUE TITLE
[Misión][Pantano de las Penas] No les hace falta

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1003]
Buenas.
La misión "No les hace falta" (http://es.wowhead.com/quest=27599) no se puede completar porque no se pueden despojar los objetos Bolsita de Bonvapor (http://es.wowhead.com/item=61923) de los Corsarios de Chapaleos difuntos (http://es.wowhead.com/npc=46014).
Gracias y hasta luego.

**Comment by redneo** [comment]
fixed
