### ISSUE TITLE
[NPC] Puertas de Sothann, Monte Hyjal

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1005]
Faltan los NPCs. Hay un vuelo y ahi dan varias misiones.

**Comment by ghost** [comment]
Nada más por si acaso... hiciste todas las misiones de hyjal hasta ese lugar?, pregunto porque esta "blizzlike", y si no ves npcs en una zona es porque te faltan misiones (creo yo).

**Comment by Wiinter** [comment]
Tengo el logro de Monte Hyjal de 115 misiones y diría qe tengo mas de 115 completadas. Me faltan las nuevas de la 4.2.
No es problema de tener pocas misiones, segun palabras de Searum es problema de un aura.

Lo mejor es qe hace unos cuantos días se veian

**Comment by redneo** [comment]
falta de meter los auras (que asco las estoy cogiendo) para ver los npcs, lo malo, que hay un lugar que tira el server por tema de misiones, tengo que indagar en local la mision que es (sin tener que cogerla)
