### ISSUE TITLE
[Misión] Palabra de poder

### ISSUE THREAD

**Issue by lllalvarolll** [RoDNet/Bugtracker-Infinium-4.3.4#1010]
http://es.wowhead.com/quest=11942/palabras-de-poder
El NPC (Andorath http://es.wowhead.com/npc=25392) no se encuentra.
Los otros dos si están.

**Comment by redneo** [comment]
a mi ese npc si que me ha salido en su sitio, tiene un respawn de 3 minutos... vuelve a mirar porfa.
