### ISSUE TITLE
[Misión]El poder de un brujo (Gnomo)

### ISSUE THREAD

**Issue by Santaclaws** [RoDNet/Bugtracker-Infinium-4.3.4#1016]
La descripción de la misión (la cual te entrega Alamar Grimm) te pide que te acerques a unos muñecos de entrenamiento cercanos (bien marcados por el seguidor de objetivos de misiones) y les lances 5 inmolar (hechizo que él mismo te enseña)

El problema reside en que no realiza recuento alguno de tus acciones, he probado a realizar inmolar incontables veces sobre cada uno de todos los muñecos de entrenamiento que existen en la zona y sobre otras criaturas sin éxito alguno.

**Comment by redneo** [comment]
suelta y vuelve a cogerla, tendria que ir

**Comment by Santaclaws** [comment]
Sí, no sé si fue por como dices soltarla y cogerla, pero me funcionó.
