### ISSUE TITLE
[Misión]Un trabajo para el Multi robot

### ISSUE THREAD

**Issue by Santaclaws** [RoDNet/Bugtracker-Infinium-4.3.4#1017]
Te la entrega Hinkles Turboexplosión, te pide que uses uno de sus multi robots para acercarte a las pozas con géiseres tóxicos y que automáticamente debería limpiar las zonas.

El problema está en que no hay ningún Multi robot, como tampoco rastro de su spawn. Aunque te acerques a las zonas que deberías purgar tampoco se limpian, de ninguna otra manera, incompletable.

**Comment by crowel** [comment]
Enlaces porfavor, graciass.

**Comment by Santaclaws** [comment]
Enlace -> http://es.wowhead.com/quest=26205

**Comment by redneo** [comment]
creo que ya tendria que funcionar
