### ISSUE TITLE
[Misión]Desaparecido en combate

### ISSUE THREAD

**Issue by Santaclaws** [RoDNet/Bugtracker-Infinium-4.3.4#1018]
Te la entrega (creo) Jessup McCree, te pide que vayas por el poblado razaescarcha liberando a 6 demoledores capturados en las jaulas improvistas que se hallan, ninguna de las jaulas de toda la región te cumple algún demoledor liberado al romperla.

**Comment by crowel** [comment]
Enlaces.

**Comment by Santaclaws** [comment]
Enlace -> http://es.wowhead.com/quest=26284

**Comment by redneo** [comment]
arreglada
