### ISSUE TITLE
[Profesiones] Arqueologia no sube naturalmente

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1020]
Reporto que arqueologia no sube al excavar, ni 1 punto.

Solo he podido subir 16 puntos asi:

2 los subi al excavar despues de aprenderla, hace como 1 semana.

el resto (14) los he subido haciendo artefactos completos, 1 punto por objeto hecho.

Me dicen que deberia subir 75 puntos excavando, pero no sube :/. Gracias.

**Comment by Dekadencee** [comment]
Fixeado, es hasta 50
