### ISSUE TITLE
[Errores internos] Banco de Hermandad

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1021]
Al abrir las casillas 2,3 4 (de arriba hacia abajo) me cierra el juego y me pone error 132.

![log banco](https://f.cloud.github.com/assets/4790547/896083/4adf9672-fad9-11e2-8ed6-2d4b1a037322.gif)

**Comment by crowel** [comment]
A mi nunca me ocurriera el error del banco.
Pero ayer me salto 3 veces al abrirlo.
Un saludo.

**Comment by searum** [comment]
No useis addons para el banco y cosas asi porque producen wow error muchas veces e intentar borrar siempre cache antes de entrar.

No existe tal wow error sin addons, eso te lo aseguro.

Cierro!

**Comment by lamaza** [comment]
Gracias por el consejo, Borraré carbonite del wow. No creo que tenga problema si mantengo npc scan o si...?

Avisare cualquier error, gracias den uevo.
