### ISSUE TITLE
[Misión]El avance

### ISSUE THREAD

**Issue by Santaclaws** [RoDNet/Bugtracker-Infinium-4.3.4#1022]
En Frente de Peloescarcha (Dun Morogh), te piden que utilices un objeto de misión (Runa de fuego) que debe quemar unos objetivos marcados (Totem de constricción), 4 de éstos últimos en concreto, los cuales no se queman ni te completan el objetivo.

**Comment by Santaclaws** [comment]
Enlace -> http://es.wowhead.com/quest=25792

**Comment by redneo** [comment]
arreglado
