### ISSUE TITLE
[Misión][Pantano de las Penas] El Manantial (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1023]
Buenas.
La misión "El manantial" (http://es.wowhead.com/quest=27902) no se puede completar porque los PNJ Elementales de Manantial (http://es.wowhead.com/npc=46953) no dejan el objeto Mota de Manantial (http://es.wowhead.com/item=62609).
Gracias y saludos.

**Comment by redneo** [comment]
arreglado
