### ISSUE TITLE
[Misión][Pantano de las Penas] Los secretos del lodo (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1024]
Buenas.
La misión "Los secretos del lodo" (http://es.wowhead.com/quest=27876) no se puede completar porque los PNJ Pegotes de lodo traicioneros (http://es.wowhead.com/npc=46997) no dejan el objeto de misión Cieno vigorizado (http://es.wowhead.com/item=62593).
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglado
