### ISSUE TITLE
[Misión][Pantano de las Penas] Un soplo de bruma

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1025]
Buenas.
La misión "Un soplo de bruma" (http://es.wowhead.com/quest=27904) no se puede completar porque los PNJ Grell brumoso (http://es.wowhead.com/npc=46950) no dejan el objeto de misión Cristal humeante (http://es.wowhead.com/item=62749).
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglado
