### ISSUE TITLE
[Misión][Pantano de las Penas] Una entrada sonada

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1026]
Buenas.
La misión "Una entrada sonada" (http://es.wowhead.com/quest=27600) no se puede completar porque no se puede llegar al barco por medio del PNJ Pequeño Jerry el Loco (http://es.wowhead.com/npc=46245). Yo pude llegar por tener maestro jinete y una vez en el barco, los objetos de misión no están:
Mecha de mil hilos (http://es.wowhead.com/item=61921)
Pólvora extra pura (http://es.wowhead.com/item=61922)
Montón de publicaciones cuestionables (http://es.wowhead.com/item=61373)
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglado
