### ISSUE TITLE
[Misión][Pantano de las Penas] Refuerzos denegados (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1027]
Buenas.
La misión "Refuerzos dengados" (http://es.wowhead.com/quest=27843) no se puede completar porque faltan los PNJ Brujo del Rocal (http://es.wowhead.com/npc=46770).
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglado
