### ISSUE TITLE
[Misión]Tumbas de Hielo

### ISSUE THREAD

**Issue by Santaclaws** [RoDNet/Bugtracker-Infinium-4.3.4#1028]
El Sargento Bahrum te envía a liberar sus montaraces congelados en la zona del Lago de Helm, pero no tienen manera alguna de ser liberados, ni por objetos, ni por accionamiento de algún dispositivo, ni nada...

**Comment by crowel** [comment]
Enlaces?

**Comment by Santaclaws** [comment]
Te refieres a ésto?  http://es.wowhead.com/quest=25978/tumbas-de-hielo

**Comment by crowel** [comment]
Si gracias, sino te importa pon el enlace en tus demás reportes como te comente antes, para facilitar la reparación del problema, un saludo.

**Comment by Santaclaws** [comment]
Perdón por las molestias ^^ Un saludo.

**Comment by redneo** [comment]
arreglado
