### ISSUE TITLE
[Misión]La conspiración de los hierro negro

### ISSUE THREAD

**Issue by Santaclaws** [RoDNet/Bugtracker-Infinium-4.3.4#1029]
Enlace aquí: http://es.wowhead.com/quest=25997
Se encuentran los Espías Hierro Negro en el campamento (que no está marcado por un objetivo de seguimiento) y te dan completado su parte de la misión, pero no se encuentra el Capitán Beld http://es.wowhead.com/npc=6124 el cual te dropea los planes de ataque, debería estar en el sótano del campamento.

**Comment by redneo** [comment]
arreglado
