### ISSUE TITLE
Portales

### ISSUE THREAD

**Issue by sherik12** [RoDNet/Bugtracker-Infinium-4.3.4#103]
Solo hay dos portales para las zonas cataclysmo: toldbard y vashir. el resto no estan.

**Comment by crowel** [comment]
Especifica más, tus mensajes van sin info.
Son los de ventormenta?.
Los de orgrimar si estan.

**Comment by sherik12** [comment]
Sorry no habia visto el comentario. Ahora solo faltan los portales de hyal y uldum en ventormenta xD

**Comment by redneo** [comment]
Cuando caiga el server los tendreis.
