### ISSUE TITLE
[Mision]La bendicion del jefe de guerra

### ISSUE THREAD

**Issue by hairblood** [RoDNet/Bugtracker-Infinium-4.3.4#1032]
a raiz de esta ultima quest,parece que acherus ha mezclado 2 fases:la 4 y 5
estan los portales,los npc de la mision anterior que habia que matar,etc
el bug de esta questes que e la horda te dice que debes hablar con thrall:esta mision no es la correcta porque deberia mandarte a ver a garrosh.La mejor prueba de ello es que si coges la mala,cuando estes en orgrimmar desaparecen todos los npc y te señala que la entregues donde antes estaba thrall el lich

esta es la buena http://es.wowhead.com/quest=13189

**Comment by Kiritoo** [comment]
Esto esta fix
