### ISSUE TITLE
[Objetos] armas y reliquias Implacable y Sañoso

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1037]
Buen dia.

Quiero reportar que no se pueden comprar ninguna de las armas, escudos y reliquias Implacable T10. Tampoco las reliquias Sañoso T10.

---
## IMPLACABLE T10

Todas las armas en páginas 1,2,3 y (+2) escudos de la página 4.
Las Reliquias página 8 y 9.

Piden tener mínimo 7800 puntos de conquista de la temporada (ganados). Al tener esto o más, sigue pidiendo el requisito y no permite comprar los objetos.

Vendedor o Intendente de conquista: Capitán Martillo de Endecha
http://es.wowhead.com/npc=69975

---
## SAÑOSO T10

Reliquias de la página 1.

Piden 7250 puntos de honor (ganados). Al sobrepasar dicho límite, sigue pidiendo el requisito y no deja comprarlas.

Vendedor o Intendente de Honor: General Caballero T´Mayre Syres
http://es.wowhead.com/npc=52537/general-caballero-tmaire-sydes

PD: Redneo, dice Searum que si ves el reporte, que el te ayuda con el código si asi lo quieres =), pero dice tambien que tu puedes solo hehe. Buen dia!.

**Comment by crowel** [comment]
Es más quiero añadir para que conste, que no se deben tener los 7250 puntos de golpe sino que es por temporada, puedes ir gastandolos que deben contar igual como ganados una vez llegado a esa cifra.
Un saludo.

**Comment by lamaza** [comment]
Hmmm bien dicho, como cuando ves el total de puntos que has conseguido en los logros de PVP.

**Comment by ghost** [comment]
A mi ni me aparecen las armas sañosas temporada 10 xD

**Comment by Moyax** [comment]
Aqui yo puse la lista de las armas #722

**Comment by lamaza** [comment]
Cierro para seguirlo en el #722
