### ISSUE TITLE
[Misión][Pantano de las Penas] La marca de los caidos (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1038]
Buenas.
La misión "La marca de los caídos" (http://es.wowhead.com/quest=27845) no se puede completar porque no están los PNJ "Lacayo de Marea Pantanosa caído" (http://es.wowhead.com/npc=46881) para marcarlos con el objeto "Estandarte de los Caídos" (http://es.wowhead.com/item=62517).
Gracias y saludos.

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
No solo estaban en otro phase los npcs, también estaba mal la misión.
Saludos.
