### ISSUE TITLE
[Misión][Pantano de las Penas] Asalto a Rocal

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1039]
Buenas.
La misión "Asalto a Rocal" (http://es.wowhead.com/quest=27849) no se puede completar porque faltan los PNJ "Defensor de Rocal" (http://es.wowhead.com/npc=46870).
Gracias y hasta luego

**Comment by Kiritoo** [comment]
Fix, falta aplicarlo.
