### ISSUE TITLE
Paladin Represion

### ISSUE THREAD

**Issue by sherik12** [RoDNet/Bugtracker-Infinium-4.3.4#104]
- Proposito divino: una vez se activa deberia hacer que el siguiente veredicto templario fuera gratis y con  el poder de tres cargas de poder sagrado. Hasta ahi funciona correctamente. Pero una vez que se activa se puede utilizar veredicto hasta que termina el buf, duracion del buf:7segundos. 
- Escudo sacro: Salta de vez en cuando, es decir salta cuando se le da la gana y no bajo las condiciones que deberia saltar, que es cada 60s siempre y cuando la vida este por debajo del 30%. 
- Santidad de batalla: No funciona.
- Cruzada: Al igual que escudo acro salta cada vez que se le da la gana, es decir cuando matas a un objetivo que te aporta experiencia u honor salta y luego matas otro y no salta.
- Colera vengativa: Aveces activa martillo de colera y a veces no.
- Maestria: sin aprender y sin poder aprenderla.

**Comment by sherik12** [comment]
como hago, esque en wowhead me aparecen solo los de pandaren xD

**Comment by Velcositro** [comment]
Usa old.wowhead.com, en inglés, seguramente ahí salgan. Por cierto, la exp. se llama Mists of Pandaria, es más fácil decir MoP.

**Comment by sherik12** [comment]
http://old.wowhead.com/spell=86172#see-also-ability 
Pues no salen tampoco en old.wowhead.com :(

**Comment by crowel** [comment]
Ya hay 3 issues de paladines.
Este es el primero, enlazo, https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/71

**Comment by sherik12** [comment]
86172
85285
25956
31868
31884
85474
Aca estan las id de las spell perdon la demora xD estan en orden al anterior comentario.

**Comment by lamaza** [comment]
-Sello de perspicacia 
http://old.wowhead.com/spell=20165/sello-de-perspicacia

No cura los 1600 o 2000 que dice por golpe, sino que cura 400-490 por golpesito XD.

**Comment by lamaza** [comment]
El skill Guardian de los Antiguos Reyes en paladin reprensión no funciona, no sale ningún guardian, no hay daño sagrado extra, y tampoco sale ningún beneficio (buff) de daño acumulado/sagrado extra etc. No pasa nada al activarlo.

http://es.wowhead.com/spell=86698/guardian-de-los-antiguos-reyes

**Comment by lamaza** [comment]
Estamos secos de mana los paladines reprensión, no funcionan las recuperaciones periódicas :/.

Las recuperaciones periódicas de mana, tanto del Sello de perspicacia como de la bendición de poderío, son incorrectos:

http://old.wowhead.com/spell=20165/sello-de-perspicacia
http://old.wowhead.com/spell=19740  (poderio)

El sello de perspicacia habla de una recuperación del 4% del mana, y en realidad esta recuperando +4 puntos de mana por segundo. La bendición de poderio tampoco esta recuperando lo que debe, creo que es 5% del mana base y creo que sana muuucho menos que eso, para que lo miren por favor.

**Comment by lamaza** [comment]
Perdón, Poderio cuesta 5% de mana, y no recupera los 90 de mana / 5 seg.

**Comment by paellaencol** [comment]
Bendición de poderio si que esta otorgando la recuperación de mana correspondiente (véase Reg. Combate, y no Reg. Mana).

Sin embargo Sello de perspicacia no está funcionando, solo otorga 4 puntos de mana por golpe, en vez del 4%

**Comment by paellaencol** [comment]
Fanatismo: http://old.wowhead.com/spell=85696 Tu golpe de cruzado genera 3 cargas de poder sagrado por cada golpe durante los siguientes 20segundos (funciona). Requiere 3 cargas de poder sagrado, pero no consume poder sagrado (error, las consume).

http://db.mmo-champion.com/utils/talents/#k=ff3.bqj.paladin.

**Comment by sherik12** [comment]
Talento ojo por ojo (id 25988), regresa no solo el daño magico sino tambien el cuerpo a cuerpo. 

Revizar tambien sello de rectirud (id 20154) cuando se usa colera vengativa el daño es desmesurado alcanzando casi a veredicto templario y claramente sobrepasando golpe cruzado, no se si son cosas de matematicas o yo estoy mal (no soy matematico) pero seria bueno una revicion. 
![wowscrnshot_070613_213512](https://f.cloud.github.com/assets/4358923/757559/2a1a0c42-e6bb-11e2-9d81-ebba1f60e189.jpg)
![wowscrnshot_070613_213732](https://f.cloud.github.com/assets/4358923/757560/2aa22960-e6bb-11e2-959e-842f486ccb20.jpg)

**Comment by lamaza** [comment]
Spell Sello de Justicia http://old.wowhead.com/spell=20164

Bug: 
No permite el uso de sentencia.

---

Spell: Reprimenda http://es.wowhead.com/spell=96231

Bug: 
Esta dejando con CD hechizos de otras escuelas como: Sellos del paladín, martillo de justicia, guardian de los antiguos reyes, colera vengativa, escudo divino, mano de salvacion, mano de libertad, defensa recta, proteccion divina, mano de proteccion, mano de expiacion, auras del paladin, bendición de reyes y bendicion de poderio.

Creo que no me faltaron más... PD: En el ejemplo de reprimenda, castee luz divina (sagrado) y por eso digo que deja con cd 4s a otros hechizos que no son de esa escuela, me parece a mi que ese es un bug.

![wowscrnshot_070713_145730](https://f.cloud.github.com/assets/4790547/758673/bcbf9f08-e747-11e2-8b4c-89d001caa925.jpg)
![wowscrnshot_070713_145904](https://f.cloud.github.com/assets/4790547/758674/bcccebe0-e747-11e2-9bbf-8e698fb2c406.jpg)
![wowscrnshot_070713_150814](https://f.cloud.github.com/assets/4790547/758675/bcd064dc-e747-11e2-9ea0-bc045d5bdfe7.jpg)
![wowscrnshot_070713_150816](https://f.cloud.github.com/assets/4790547/758672/bc8702f6-e747-11e2-950a-c4ffd2f96868.jpg)

**Comment by lamaza** [comment]
El skill/talento Tormenta Divina tienen un problema o bug: http://old.wowhead.com/spell=53385

Afirmación: Otorga 1 carga de poder sagrado cada vez que golpeas a 4 ENEMIGOS O MÁS.

Bug: me otorga 1 carga de Poder Sagrado SI O SI, siempre que golpeo 1, 2 3 objetivos o no golpee nada.

![wowscrnshot_070713_162105](https://f.cloud.github.com/assets/4790547/758702/8f7bd106-e74c-11e2-8819-b4f32ec1e444.jpg)
![wowscrnshot_070713_162044](https://f.cloud.github.com/assets/4790547/758703/8f9135a0-e74c-11e2-8d77-dc0d5e927bb2.jpg)

**Comment by sherik12** [comment]
El sello de verdad (id 31801) cuando pone las 5 cargas sobre el objetivo no aumenta el 17% de daño con arma como poder sagrado, que deberia hacer. Ademas cuando se tiene este sello activo la probabilidad de que proposito divino (id 86172) se active es minima, lo que no deberia pasar ya que proposito divino es independiente a los sellos.

**Comment by lamaza** [comment]
Que imagenes decias que colocaste?

**Comment by ghost** [comment]
@sherik12 perdón por cerrar tu reporte, si pudieras reportar un bug por cada reporte, así no lo leeran y no arreglaran todo esto u.u.
