### ISSUE TITLE
[Misión][Pantano de las Penas] Cortar el suministro

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1040]
Buenas.
La misión "Cortar el suministro" (http://es.wowhead.com/quest=27851) no se puede completar porque faltan los objetos de misión "Suministros de Rocal"(http://es.wowhead.com/item=62516).
Gracias y hasta luego.

**Comment by Kiritoo** [comment]
Fix, falta aplicarlo.
