### ISSUE TITLE
[Misión][Tierras Devastadas] Reducir a los Colaoscura

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1042]
Buenas.
La misión "Reducir a los Colaoscura" (http://es.wowhead.com/quest=25709) no se puede completar porque el objeto "Flechas explosivas de Enohar" (http://es.wowhead.com/item=57119) no funcionan contra los PNJ "Escarbador Colaoscura" (http://es.wowhead.com/npc=42235), que vuelan muy arriba.
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglada
