### ISSUE TITLE
[Misión] (Isla Bruma de Sangre) Tajobuche

### ISSUE THREAD

**Issue by Santaclaws** [RoDNet/Bugtracker-Infinium-4.3.4#1043]
Enlace: http://es.wowhead.com/quest=9689
Problema: Al usar el fogón del pilar en llamas o el objeto de misión para invocar a Tajobuche, éste no aparece.

**Comment by Kiritoo** [comment]
Estoy probando y el dragon aparece volando, a los 15-20 segundos baja a donde la hogera.
