### ISSUE TITLE
[Hechizos - Talentos] Invocacion - Mago Rama Arcano OP

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1045]
Buenas, para denunciar este talento de la rama Arcana llamado Invocacion, que esta saltando con cualquier ataque que usan (mágico, no fisico), dándoles un beneficio considerable a cualquier mago en el pvp pve..

http://www.wowhead.com/spell=114003  No lo encontre para 4.3.4 , lo siento.
![wowscrnshot_080213_150751](https://f.cloud.github.com/assets/4790547/903645/41eb8968-fbb0-11e2-9a40-46699a8ab00b.jpg)
![wowscrnshot_080213_150502](https://f.cloud.github.com/assets/4790547/903646/41ea24b0-fbb0-11e2-8eab-d3d2c6d17886.jpg)

-Deberia saltar al lanzar silencio o interrumpir como dice, pero cualquier ataque que un mago hace, el talento le salta y se acumula casi en segundos de 13% a 52% (5 cargas) ( si es arcano), no pasa de ahi, pero hay que considerar que lo acumulan con pocos spell.

-En Escarcha la acumulacion llega hasta 40% (4 cargas), no pasa de ahi, pero el talento funciona igual de bug.

-En fuego tambien hasta 40% (4 cargas).

Otro detalle para agregar en Mago Arcano, es que el talento en vez de acumular 10% inicialmente, acumula 13% de daño.

De ahi que se notaran tanto los críticos desde pjs 85 "verdes", contra cualquier tipo de pjs armados. Yo con temple de 3451 (35,49% reduccion daño) soy un pez al lado de un recien 85 que use este talento en cualquier configuración de mago, no tanto en Fuego, pero MUY peligroso en arcano, llegandome a pegar en segundos 20k+ seguido.

Conclusiones:

1- No debe saltar con cada cosa que el caster hacer, sino solo cuando interrumpe al enemigo.

2-Deberia activarse desde 10%, y no 13% como anda en arcano.Esto por la maestria, según comprobamos: Maestria esta dando un 3% al talento en función del daño total que aumenta.

3- No se debe acumular, es decir, solo debe dar 10% de daño +. No 40% ni 52% como se puede comprobar.

![wowscrnshot_080213_144552](https://f.cloud.github.com/assets/4790547/903678/f6f652e8-fbb0-11e2-9b8f-bca1cf14c5d5.jpg)
![wowscrnshot_080213_143009](https://f.cloud.github.com/assets/4790547/903679/f70b29a2-fbb0-11e2-9f4f-46ccc7e6235f.jpg)

Creo que es todo por ahora...

**Comment by ghost** [comment]
Aquí el de cata http://cata.openwow.com/spell=84723.

**Comment by searum** [comment]
fix
