### ISSUE TITLE
Bug[Mision] 'Resistencia final' 

### ISSUE THREAD

**Issue by trolazo** [RoDNet/Bugtracker-Infinium-4.3.4#1046]
localizacion:Ciudad de Gilneas. 
Al aceptar la mision no aparece los mounstros que se deben matar, respondan lo antes posible.

**Comment by searum** [comment]
tengo que compilar para fixearlo

**Comment by camaleonon** [comment]
hola tengo el mismo problema ya llevo dos dias y nada
