### ISSUE TITLE
[Brujo] Terror de fatalidad - Guardián demoníaco

### ISSUE THREAD

**Issue by Felarof23** [RoDNet/Bugtracker-Infinium-4.3.4#1047]
El ataque de el Guardián demoníaco invocado por <a href="http://es.wowhead.com/spell=603/fatalidad"> Terror de fatalidad </a> es de 1.

![screen shot 2013-08-01 at 10 53 41 am](https://f.cloud.github.com/assets/5028343/904511/58c3deac-fbc8-11e2-924e-822bed954cce.png)

Y no estoy seguro si es correcto que este sea invocado hasta que muere el objetivo.

Saludos!

**Comment by ghost** [comment]
Sí, la maldición tiene un 20% de probabilidades de invocar al guardián cada vez que hace daño (50% con talentos).

ID del NPC: 50675

Con un equipo normalito debería hacer ~1k de daño normal según he visto en vídeos.

---

Comentarios de wowhead:

"Affliction lock and got 3300 spell dmg and this little guy hits for 350-600 and crits for ~1050-1400. Lasts for 30 sec. But if you command your pet to stay the Ebon Imp stops attack too."

**Comment by efectokoleos** [comment]
aumentado el daño a esas cantidades(350-800) y críticos de 1000-1400

**Comment by Wiinter** [comment]
Realmente no tiene daño fijo, sino que se invoca a partir del sp en ese momento y de los buffos que tengas en ese momento. Por poner un ejemplo, siendo demonologia y con el tier actual realmente harías de normal alrededor de 1k, con el efecto de metamorfia. El daño de esta pet tiene que ser como el de las demás pets del brujo, en función del brujo, no puede ser independiente.
