### ISSUE TITLE
[Misión] Encárgate personalmente (zona de inicio Goblin)

### ISSUE THREAD

**Issue by sirkaox** [RoDNet/Bugtracker-Infinium-4.3.4#1049]
Es una de las penultimas misiones antes de salir de la isla de los goblins pero no esta ninguno de los objetivos no existen e aquí el link http://es.wowhead.com/quest=14070/do-it-yourself
deberian estar esos 4 npc pero no hay nada.
![image](https://f.cloud.github.com/assets/5151500/904790/365e26c8-fbd8-11e2-9c16-e0ea6ce36bb9.png)
un video 
http://www.youtube.com/watch?v=oYWwrGnQFzc

**Comment by searum** [comment]
Si están solo que tu la has hecho más tarde y estas en otra phase ya.
