### ISSUE TITLE
[Brujo/Warlock] Algunos Bugs del brujo.

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#105]
Generales:
- Drenar vida (http://old.wowhead.com/spell=689): No cura.
- Terror de fatalidad (http://old.wowhead.com/spell=603): No tiene la probabilidad de invocar diablillos de ébano (http://old.wowhead.com/npc=50675) al hacer daño, sino que los invoca al matar al enemigo con ese terror puesto.
- Cauce de salud (http://old.wowhead.com/spell=755): Debería quitar 1% de salud, pero en vez de eso dice que falla cada tic. La sanación al demonio si funciona.
- Piedra de alma (http://es.wowhead.com/item=5232): Funciona como siempre correctamente, pero desde el parche 4.1 deja usarla sobre un objetivo muerto para revivirlo de inmediato (La nota del parche dice: Ahora la piedra de alma se puede usar en combate para resucitar a un jugador muerto marcado como objetivo.), el bug es que se puede usar sobre objetivos muertos pero en vez de revivirlos aplica el mismo efecto que con objetivos vivos. Al parecer el efecto usado en este parche es http://es.wowhead.com/spell=20707.
- Invocar Guardia apocalíptico (http://old.wowhead.com/spell=18540): Invoca a un Guardia apocalíptico (http://es.wowhead.com/npc=11859, como debe ser), pero ese guardia debería usar Descarga de fatalidad (http://old.wowhead.com/spell=85692) para atacar, en vez de eso ataca cuerpo a cuerpo.
- Invocar Infernal (http://es.wowhead.com/spell=1122): Invoca a un Infernal (supuestamente a http://es.wowhead.com/npc=89 según unos datos, pero no creo que sea ese), debería tener la habilidad Inmolación Demoníaca (http://es.wowhead.com/spell=4525) y no la tiene.

NOTA: Los 2 anteriores deberían atacar a los objetivos afectados por Terror de agonía(http://old.wowhead.com/spell=980) o Terror de fatalidad(http://old.wowhead.com/spell=603) pero atacan solo a quien se le tenga como objetivo al invocarlo o al que les pegue.

Demonología:
- Inferno (http://old.wowhead.com/spell=85105): Un bug muy menor, deja usar el hechizo y moverse después, pero no se puede usar el hechizo si ya te estás moviendo, debes pararte, usarlo y después seguir.

**Comment by Velcositro** [comment]
Actualizado y agregados un par de bugs.

**Comment by ghost** [comment]
@Velcositro perdón por cerrar tu reporte, puedes volver a reportar los bugs, pero en reportes separados?, a los devs les es más comodo que haya un bug por cada reporte.

**Comment by Velcositro** [comment]
@Lvmb Lo haré, aunque primero debo comprobar cuáles siguen bug, porque el reporte es de antes del rollback.
