### ISSUE TITLE
[NPC] Entrenador de mago - Kezan

### ISSUE THREAD

**Issue by sirkaox** [RoDNet/Bugtracker-Infinium-4.3.4#1050]
No eh podido aprender nada solo me da la una misión que solicita aprender un hechizo, el cual no tengo y necesito aprenderlo.
![image](https://f.cloud.github.com/assets/5151500/904816/290895e6-fbdb-11e2-9b74-a348ed3bb006.png)
![image](https://f.cloud.github.com/assets/5151500/904817/45d1b18a-fbdb-11e2-9b9f-72c3ce5b8a5d.png)
aca la misión http://cata.openwow.com/quest=14008

**Comment by Kiritoo** [comment]
Arreglado, falta implementar fix.
