### ISSUE TITLE
[Misión][Paramos del Poniente] Presentamos a Lou Dos Zapatos

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1051]
Buenas.
La misión "Presentamos a Lou Dos Zapatos" (http://es.wowhead.com/quest=26215) no se puede completar porque falta el PNJ "Lou Dos Zapatos" (http://es.wowhead.com/npc=42405).
Gracias y hasta luego.

**Comment by redneo** [comment]
fixed!
