### ISSUE TITLE
[Misión][Paramos del Poniente] El amanecer de un nuevo día

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1052]
Buenas.
La misión "El amanecer de un nuevo día" (http://es.wowhead.com/quest=26297) no se puede completar porque el evento de la reunion no empieza (Intente clickando el PNJ "Figura enigmatica" y nada).
Gracias y hasta luego.

**Comment by redneo** [comment]
tomatomatoma... ya me lo traduce alguien y queda perfecto!
