### ISSUE TITLE
[Misión][Las Tierras Devastadas] El amuleto de Sevine

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1053]
Buenas.
La misión "El amuleto de Sevine" (http://es.wowhead.com/quest=26168) no se puede completar porque el PNJ "Voltesal" (http://es.wowhead.com/npc=41265) no da el objeto "Amuleto de Sevine" (http://es.wowhead.com/item=10754) mediante opción de diálogo.
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglado
