### ISSUE TITLE
[Misión][Tierras Devastadas] Cubrirse las espaldas (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1054]
Buenas.
La misión "Cubrirse las espaldas" (http://es.wowhead.com/quest=26174) no se puede completar porque al clickar sobre el objeto "Planes de la Horda" (http://es.wowhead.com/object=203225), no cuenta como examinado.
Gracias y hasta luego.

**Comment by redneo** [comment]
Cuando caiga el server y limpies temporales, puede que funcione, no estoy del todo seguro
