### ISSUE TITLE
[Misión][Tierras Devastadas] La caída de Marl Gusaespina (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1055]
Buenas.
La misión "La caída de Marl Gusaespina" (http://es.wowhead.com/quest=26187/) no se puede completar porque cuando uso el objeto "Vasija demoníaca" (http://es.wowhead.com/item=57185) contra el PNJ "Marl Gusaespina" (http://es.wowhead.com/npc=42334), este no sale de su trance y se hace imposible atacarlo.
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglado!
