### ISSUE TITLE
Chaman tauren 

### ISSUE THREAD

**Issue by ignizpro** [RoDNet/Bugtracker-Infinium-4.3.4#1057]
Cuando inicio un personaje chaman tauren no te da el Pisotón de guerra que es racial 
, pero cree mas personajes para verificar si todos tenian la falla y no nadamas en los chamanes de esta raza, espero y me den alguna solución gracias

**Comment by searum** [comment]
pon un ticket ingame para que te enseñe un gm la racial

en el proximo reinicio estara arreglado
