### ISSUE TITLE
[Sacerdote] Palabra de poder: escudo

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1059]
El hechizo palabra de poder: escudo, no está escalando con el poder con hechizos

En esta imagen, me puse el escudo, sin mi abalorio puesto, llegando a 7647 de poder con hechizos, y el escudo absorbiendo 17894.
![sin abalorio](https://f.cloud.github.com/assets/4663665/905373/3ca45f0e-fc1c-11e2-850c-fd00e05e1b26.jpg)

En esta otra, tengo mi abalorio puesto y activado, más mi encantamiento torrente de poder, llego a los 9422 de poder con hechizos, y el escudo sigue absorbiendo 17894.
![con abalorio](https://f.cloud.github.com/assets/4663665/905374/3e365908-fc1c-11e2-8548-eaa99a84031e.jpg)

Enlace: http://es.wowhead.com/spell=17

Reporte relacionado: #671

**Comment by searum** [comment]
fix

**Comment by searum** [comment]
ahora si escala bien

**Comment by ghost** [comment]
Gracias <3
