### ISSUE TITLE
[Banda]Tierras de Fuego - 10 jugadores

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#106]
Hola, procedo a reportar los errores del testeo de la banda de hoy.

<h2>Banda: Tierras de Fuego // http://es.wowhead.com/zone=5723</h2>

<h2>-Errores generales:</h2>

<h2>*</h2>Ningun NPC da reputación, ni los boss dan reputación o puntos.
<h2>*</h2>Cuando una persona se cae por el acantilado al barranco y muere, no les aparece para liberar y resucitar, teniendo que usar alt+f4 para volver al juego.

<h2>-Nps con errores:</h2>

<h3>*Guardia de la avanzada despiertallamas.</h3> http://es.wowhead.com/npc=53119  No dan reputación, solo hacen -1 de daño, no se pueden despojar, no hace ninguna de sus 3 habilidades,necesita traducción.

<h3>*Montón de huevos.</h3> http://es.wowhead.com/npc=53795 Mal situados, hay poco despues de entrar a la instance, no debiendo estar ahi, hacen -1 de daño,necesita traducción.

<h3>*Heraldo del extremo ardiente.</h3> http://es.wowhead.com/npc=53375 Mal situados a la entrada, hacen -1 de daño, no hace sus habilidades,necesita traducción.

<h3>*Señor de magma.</h3> http://es.wowhead.com/npc=53115 No da reputación, no hace habilidades, solo hace -1 de daño y no se puede despojar,necesita traducción.

<h3>*Cuidador de bestias despiertallamas.</h3> http://es.wowhead.com/npc=53223 No da reputación, no usa su habilidad, solo hace -1 de daño, no se puede despojar, no deberia estar a la entrada.

<h3>*Escorpión de fuego.</h3> http://es.wowhead.com/npc=53127 No da reputación, no usa sus habilidades, solo hace -1 daño, no se puede despojar.

<h3>*Prole de tortuga de fuego.</h3> http://es.wowhead.com/npc=53096 No da reputación, no usa su habilidad, solo hace -1 de daño, no se puede despojar.

<h3>*Can del Núcleo anciano.</h3> http://es.wowhead.com/npc=53134 No da reputación, no usa sus habilidades, no ataca nisiquiera, este es uno de los que se puede despojar, no esta correctamente situado.
Este deben revisarlo ya pues con el porcentaje de caida de los epicos cuando lo despojamos el mismo npc solto estos 3 objetos:
http://es.wowhead.com/item=71361 Corcesca de odio
http://es.wowhead.com/item=71640 Collera perdida de Desmembrador
http://es.wowhead.com/item=71362 Cuchilla de obsidium

<h3>*Marea de magma.</h3> http://es.wowhead.com/npc=53141 No da reputación, no usa su habilidad, hace -1 de daño, no se puede despojar.

<h3>*Prole incandescente.</h3> http://es.wowhead.com/npc=53794 Hace -1 de daño,necesita traducción.

<h3>*Piroseñor desatado.</h3> http://es.wowhead.com/npc=53167 Hace -1 daño, no da reputación, no usa sus habilidades, no se puede despojar, necesita traducción.

<h3>*Monstruosidad llameante.</h3> http://es.wowhead.com/npc=53786 No ataca ni se mueve, necesita traducción.

<h3>*Monstruosidad llameante.</h3> http://es.wowhead.com/npc=53791 No ataca ni se mueve, no da reputacción, necesita traducción

<h3>\* "BOSS" Alysrazor.</h3> http://es.wowhead.com/npc=52530 No se puede targetear para atacarle, se anda moviendo seguido por el aire y cuando pasa por encima tuya te golpea con -Garra llameante http://es.wowhead.com/spell=99844 sin parar de volar.

<h3>*Maestro de canes despiertallamas.</h3> http://es.wowhead.com/npc=54073 No da reputación, solo hace -1 de daño, no se puede despojar, no hace su habilidad.

<h3>*Piroseñor inestable.</h3> http://es.wowhead.com/npc=53630 Salen como amistosos.

<h3>*Kar el Abrasador <Señor del Fuego></h3> http://es.wowhead.com/npc=53616 No da reputación, no hace habilidades, hace -1 daño, necesita traducción, es otro de los que se despojan.
Este tambien deberian revisarlo ya que con el porcentaje bajo nos loteo:
http://es.wowhead.com/item=71360 Aguja de dolor escarlata 

<h3>\* "BOSS" Lord Piroclasto.</h3> http://es.wowhead.com/npc=52558 Este boss no se le puede atacar nisiquiere se le puede targetear, al pasar el raton por encima aparece el nombre como enemigo pero incluso haciendolo areas debajo no ataca,
otra cosa curiosa es que al lado de el hay otro golem gigante con su mismo nombre pero amistoso y con otra apariencia, deberian mirarlo.

<h3>*Vórtice ígneo.</h3> http://es.wowhead.com/npc=53693 Este npc aparece llegando al boss Lord Piroclasto, no sabemos cuando solo sabemos que nos empezo a atacar cerca de la zona del boss, el problema es qu no se le ve y no lo podemos targetear/atacar
Lo que sabemos es que nos atacaba y no saliamos de combate, solo aparecia su nombre en el registro de combate, wowhead pone "No se conoce la ubicación de este PNJ", creo que deberia quitarse.

<h3>*Pie izquierdo.</h3> http://es.wowhead.com/npc=52577 Hace -1 de daño, necesita traducción, no hace sus habilidades.

<h3>*Rostrofuria.</h3> http://es.wowhead.com/npc=53695 Hace -1 de daño, necesita traducción,no hace todas sus habilidades solo hace "Frenesí hambriento" http://es.wowhead.com/spell=100656, la posicion-movimiento en la zona no esta correctamente,
 o estan muy juntos o se mueven de manera que vienen todos juntos y estando bien la raid seria dificil matar a tantos al mismo tiempo.

<h3>*Desmembrador.</h3> http://es.wowhead.com/npc=53694 Lo mismo que el npc anterior, este es otro tipo de perro los cuales entre unos y otros cubren mucho la zona, deberian estar más ordenados o hay alguno de mas nose cual es el fallo exactamente.

<h3>\* "BOSS" Shannox.</h3> http://es.wowhead.com/npc=53691 Hace -1 de daño, no hace sus habilidades, no da reputación, este boss se le puede usar ciclón y raices enredadoras, se deberia de mirar esto.
Al matarlo loteo y dio el logro:
http://es.wowhead.com/item=71787 Sacaentrañas
http://es.wowhead.com/item=71026 Brazales del cazador aterrador
http://es.wowhead.com/item=71022 Cáliz de inquina
Logro:Última voluntad http://es.wowhead.com/achievement=5829 hay que llevarlo a 5 lugares de tierras de fuego y aunque no lo movimos del sitio el logro salto igual.

<h3>*Arañita Telaceniza.</h3> http://es.wowhead.com/npc=53631 Hace -1 de daño, necesita traducción, no se puede despojar, no da reputación, no hace sus habilidades.

<h3>*Halcón inferno.</h3> http://es.wowhead.com/npc=53648 Hace -1 daño, necesita traducción, no se puede despojar, no da reputación, no hace sus habilidades.

<h3>\* "BOSS" Baleroc <El Guardián de la Puerta></h3> http://es.wowhead.com/npc=53494  Esta mal posicionado deberia estar un poco mas lejos de donde esta, en la posición que esta no se deberia poder pulear ya pues hay una puerta de fuego que impide pasar hasta matar a los boss restantes, esta tan cerca de la puerta que alguien con un hechizo lo puede agarrar.

Hasta aqui el reporte de nps que matamos y hasta donde pudimos avanzar.

<h2>-Otros bugs:</h2>

Quiero reportar el bug por el cual no avanzamos mas en la banda que es el siguiente, explicare con la ayuda de imagenes esto.

![wowscrnshot_070413_172251](https://f.cloud.github.com/assets/3537253/750526/f135e02e-e4ce-11e2-8af7-0ae5bd84dd52.jpg)

Donde veis la zona que tengo el raton, la guarida de la araña extrañamente al llegar ese punto inexplicablemente morimos.
Lo raro es que no sabemos porque ya que no aparece nada en el registro de combate, deberia mirarse esto.

![wowscrnshot_070413_172257](https://f.cloud.github.com/assets/3537253/750530/3ac1c8de-e4cf-11e2-96bc-802227849944.jpg)

Como se ve en la imagen aqui estamos justo despues de morir, lo más extrañó es que después de morir a los 3-5 segundos derepente reviviamos en el mismo punto.
Aqui la foto.
![wowscrnshot_070413_172351](https://f.cloud.github.com/assets/3537253/750539/60d4d430-e4cf-11e2-9684-3470beb16b28.jpg)

Tras esto a los 3 segundos algo nos volvia a matar inexplicablemente lo unico que aparecia en el registro de combate en mi caso era, crowel ha muerto.
Aqui otra foto, despues de revivir otra vez muerto y asi hasta que liberamos cuerpo.

![wowscrnshot_070413_172354](https://f.cloud.github.com/assets/3537253/750554/50feed60-e4d0-11e2-9670-5fec9a567c24.jpg)

Sentimos no poder reportar más pero lo hicimos hasta donde el juego nos lo permitio llegar.

Espero que este reporte ayude poco a poco a la reparación de esta hermosa banda.
Cualquier duda, algo que escribiera mal o me equivocara para editarlo o algun aporte más que ayude a reparar esta banda será agradecido.

Un saludo.

**Comment by Alfonn** [comment]
No es por nada, pero esta banda está cerrada y prohibida...
Al igual que las nuevas mazmorras y DS(Dragon Soul)

**Comment by ghost** [comment]
Si esta cerrada y prohibida (ahora mismo que el server esta en forma de "test" y todo lo que hagamos se borrará) ¿entonces cómo vamos a reportar?

**Comment by Alfonn** [comment]
Pregunté a dekadence si esa banda esta cerrada/prohibida y me dijo que sí, que serían abiertas cuando ellos las arreglaran. Para que veais que no me he sacado nada de la manga. Por tanto se supone que no podemos ir a no ser que nos diesen permiso.Yo sólo informo de lo que me dijeron a mí, nada más.De todas formas es un buen reporte y currado. Felicidades.

**Comment by ghost** [comment]
Ah pues bueno, yo no he visto la prohición en ningún lado, y como el server esta en modo test... y se pondrá el backup no creo que haga daño testear, @Dekadencee espero que mire el reporte y nos lo aclare.

**Comment by crowel** [comment]
Si porfavor @Dekadencee sacanos de nuestra duda, estamos reportando instances-raids.

**Comment by jaramys** [comment]
yo espero que algun dia, (lo mas pronto posible) los gm pongan las santisimas prohibiciones en la portada de la pagina, que la verdad siempre se dan problemas de que 2 personas saben que algo esta prohibido i el 99% de la poblacion ni cuenta, agan un apartado ofisal o en facebook o lo que sea por favor
