### ISSUE TITLE
Daños - Sanaciones mal.

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1060]
Bueno, este reporte es simplemente para que revisen (indirecta a @redneo) el daño y las sanaciones de los hechizos, luego de los cambios que introdujo Searum en el último reinicio.... se "fundió" todo S:

Por ejemplo, mi sacerdote siendo full sañoso llegando a los 9000 y algo de poder con hechizos con "full cds" hace solo 8k de daño con la pua al muñeco, y mis pegatas apenas llegan a los 2,7k de daño, he probado y todos los daños del sacerdote sombras estan más bajos de lo que antes ya estaban xD, y algunos hechizos curán de más.

Mi Dk, que apenas es sanguinario, haciendo golpe letal al muñeco le saco 25k sin ser critico siquiera, probé otros hechizos del DK y pegan mucho más que antes.....

**Comment by redneo** [comment]
Searum me tiene prohibido tocar daños de hechizos, ya que supuestamente, están correctos 
 :'( .

Le iré a llorar a ver que me dice xD

**Comment by ghost** [comment]
Pues el que ha corregido los daños.. simplemente odia a los sacer sombras xD, probe el war y esta pegando mucho... de nuevo.

**Comment by redneo** [comment]
Empecemos:
Spell 15407 tiene un dot de 0.2 tendria que tener 0.288 -- Priest - Mind flay 
Spell  2944 No tiene datos y tendria que tener un dot de 0.163 -- Devouring Plague
Spell 589 tendria que tener un dot de 0.161 y tiene 0.1829 -- Shadow Word: Pain
Spell 34914 tendria que tener un dot de 0.352 y tiene 0.25 -- Vampiric Touch
Spell 32379 tendria que tener un direct bonus de 0.316 y tiene 0.4296 pero aun asi, ni hace daño al que lo lanza (parece que el daño que tendria que hacer, se lo hace al objetivo) y el daño es de 4200 teniendo que ser de 10k. 
Spell 8092 Tendria que tener un direct bonus de 1.104 y tiene de 0.928 -- Mind Blast

Y así podria seguir, pero no quiero perder mucho mas tiempo en esto :S

**Comment by ghost** [comment]
xD mejor ve mi reporte de mazmorra :P

**Comment by ghost** [comment]
Si, id vosotros que conmigo no se lo toma demasiado bien...y eso que estoy en el canal quejasylloros que creó.
