### ISSUE TITLE
[Buscador de mazmorras] Salir y entrar en mazmorras

### ISSUE THREAD

**Issue by redneo** [RoDNet/Bugtracker-Infinium-4.3.4#1062]
Cuando te vas a una mazmorra con el buscador de mazmorras, no se aplica correctamente el famoso Ojito del mapa, el cual te permitía salir y volver a entrar al principio de la mazmorra.

Esta función era muy útil para entregar misiones, reparar y todas las cosas que se suelen hacer en mazmorras.

Por otra parte, no te aplica el bufo tipico de las mazmorras (no me acuerdo cual era, sorry)

**Comment by Dekadencee** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/956 lo seguimos desde ahi
