### ISSUE TITLE
Bug general de mazzmorras uno

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1065]
Al matar a un boss de mazmorra heroica, debería dar directamente los puntos de justicia a todos los miembros del grupo, esto no sucede y hay que despojar al boss para que de los puntos de justicia, además el item que tira el boss se puede agarrar directamente sin necesidad de tirar los dados.

**Comment by searum** [comment]
lo se, pero tengo que implementarlo y mientras tanto como queriais chapas pues ya las teneis.. y aun asi quejas! cierro xq ya me conozco el "bug"
