### ISSUE TITLE
Bug general de mazzmorras dos

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1066]
Bueno, sucede que al parecer, o no esta implementado o es un error... cada vez que sale un item para tirar dados, todos pueden tirar necesidad por el, se supone que hay reglas como por ejemplo, si sos tank - placas, y sale algo dps - tela solo podrías dar codicia y no necesidad, ya que eso no le sirve a un tank - placas.

**Comment by searum** [comment]
eso no es asi... tu puedes tirar need o greed pero eso depende de la persona y no de tu clase, al menos siempre que he jugado a sido asi...

de donde te crees que vienen los "ninjeos" ? ^^

**Comment by ghost** [comment]
Si quieres te puedo mostrar toda una información que explican los propios de Blizzard de como funciona el sistema de reparto de botín xD, los "ninjeos" son cuando vas a raid, y el lider  de la raid que tiene puesto maestro despojador no reparte el botín....
