### ISSUE TITLE
Bug general de mazzmorras tres

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1067]
Al querer salir de una mazmorra usando "el ojo" (ese verde que esta a la derecha), aparece un mensaje diciedo "no dispones de una ubicación de teletransporte válida", debería de llevarte al lugar donde estabas antes de entrar a la mazmorra.
![wowscrnshot_080213_164207](https://f.cloud.github.com/assets/4663665/905454/04f805e8-fc2a-11e2-8520-5bdf79e9b5ee.jpg)

**Comment by Dekadencee** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/956, seguimos desde ahí
