### ISSUE TITLE
HERMANDAD un constante mensaje de ERROR

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.3.4#107]
![wowscrnshot_070413_104018](https://f.cloud.github.com/assets/2059256/750571/0f24f870-e4d1-11e2-9f9a-5aeb3c5c96d9.jpg)

Bueno asi de simple

**Comment by Dekadencee** [comment]
Relacionado con #7, seguimos el reporte desde ahi

**Comment by Dekadencee** [comment]
Fixed

**Comment by crowel** [comment]
Hola queria comentar que en nuestra guild seguimos con el error cada vez que despojamos oro.
Un saludo.

**Comment by Dekadencee** [comment]
Ayer estaba sin actualizar el core aun, pero si pruebas ahora mismo ya no deberia dar error.

Un saludo ^^

**Comment by crowel** [comment]
Parece que continua saltando error.
![wowscrnshot_070813_191134](https://f.cloud.github.com/assets/3537253/763108/92cd8a92-e7f7-11e2-9195-d25959d1b2fd.jpg)

Saludos.
