### ISSUE TITLE
[Misión] (Infralar) Un gran cebo para una gran pesca: 26766

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1070]
No deja utilizar el objeto de la misión "Cuchillo de Mylra"(60382) con el que tienes que coger la carne de los basiliscos. No deja usarlo ni vivos ni muertos ni despojados ni sin despojar, dice que aun no puedo hacer eso.

Sin pasar esta quest no se puede seguir con la cadena para obtener la reputación y el único encantamiento de hombros para caster.

**Comment by redneo** [comment]
Funciona correctamente, cuando lo matas, lo usas el cuchillo y cuenta.
