### ISSUE TITLE
Bug[Mision] 'Resistencia final' 

### ISSUE THREAD

**Issue by camaleonon** [RoDNet/Bugtracker-Infinium-4.3.4#1071]
Bug[Mision] 'Resistencia final'
localizacion:Ciudad de Gilneas. 
Al aceptar la mision no aparece los mounstros que se deben matar, respondan lo antes posible.
ya llevo 3 dias no reponden ni nada

**Comment by searum** [comment]
y por que no pones ticket ingame para no estar 3 dias esperando? xD

Cuando vuelvas a hacerla deja la mision y vuelve a pillarla y ya te ira bien
