### ISSUE TITLE
despues de un rato de atacar los skill se bloquean 

### ISSUE THREAD

**Issue by jorgeqlo** [RoDNet/Bugtracker-Infinium-4.3.4#1072]
hola buenas ,
tengo un gravisimo problema con mi cuenta , se los cuento , cuando entro abg o hago pvp o alguna quest q requiera ocupar skill ,despues de un rato no me deja ocupar ninguna clase de skill ni el barra ni en el libro de talentos nose pero me pasa con todos los pj de mi cuenta y ya bore e instale el juego dos veces de diferente manera y sigue igual de antemano muchas gracias y suerte y ojala puedan ayudarme =)

**Comment by redneo** [comment]
he entrado con tu pj un rato en bg, a mi me iba bien... de todas formas, yo que tu borraba los macros y ponia la configuracion del chat y del resto de cosas por defecto y probaba

**Comment by hairblood** [comment]
tienes algun addon en concreto?puede que te este dando esos fallos
hasta en el ofi,los addons pueden darte algun tipo de problema
