### ISSUE TITLE
Sanacion, Golpe Letal Dk

### ISSUE THREAD

**Issue by katty09** [RoDNet/Bugtracker-Infinium-4.3.4#1073]
Debido a la baja sanación del dk sangre con golpe letal me dispuse a ser un testeo de dicha habilidad basándome en calculo de porcentajes y en la descripción de la misma en internet.

Golpe letal : Lanza un poderoso golpe que te sana un 20% del daño que has recibido durante los últimos 5 segundos (un mínimo de un 7% de tu salud máxima) y también inflige 330% de daño con arma mas 1092p. de daño a un enemigo si el ataque tiene éxito. . 

Lo que quiere decir que el heal mínimo y frecuente es de un 7% pero debería aumentar el 20% del daño que te hacen durante un lapso de 5 segundos, ejemplo si tienes vida de 141000 de vida te heleas el 7% que es 9870 aproximado que es lo
mínimo que se debe helear pero falta los 20% del daño recibido durante los últimos 5 segundos, o sea si te heleas 9870 que son los 7%  y te hacen un daño total en los 5 segundos de 30000 el 20% del daños es 6000 lo que quiere decir es que 
el heal total del dk debería ser 15870 aproximado por que el 7% que es lo mínimo que se debe helear aumenta el 20% del daño recibido en un lapso del 5 segundos
la sanación varia dependiendo del daño que te hacen durante los 5 segundos pero con un intervalo mínimo de 7%.

Procuramos ser lo mas clara, espero que logren entenderlo.

Un saludo ^^

ID: 49998
![0ynb4af](https://f.cloud.github.com/assets/4663665/911403/4b6b48ec-fdeb-11e2-8d54-a8b0e950bfc4.jpg)

**Comment by ghost** [comment]
Una cosa, la parte del daño recibido de 20%, no se suma con el 7% minimo de vida que te curas.

Si recibes daño, y el 20% de este daño es menor que el 7% de tu vida, te curaras el 7% de tu vida, ahora si el 20% del daño recibido es mayor que el 7% de tu vida, te curaras ese 20% de daño que recibiste, o sea que no se suman esas sanaciones como lo estás explicando.

Por cierto, podías poner la imagen aquí en vez de subirla a imgur :P

**Comment by katty09** [comment]
El mínimo es 7% menos de eso no se puede helear, ahora el heal siempre sera mayor al 7%  dependiendo del daño que te hacen.

**Comment by ghost** [comment]
Si, yo no dije que se iba a curar menos de ese 7% de vida, lo que yo dije fue que, lo del daño recibido y el 7% minimo no se suman como tu lo explicaste xD.

**Comment by katty09** [comment]
Segun blizz debe ser como lo explique

**Comment by ghost** [comment]
> o sea si te heleas 9870 que son los 7% y te hacen un daño total en los 5 segundos de 30000 el 20% del daños es 6000 lo que quiere decir es que
> el heal total del dk debería ser 15870 aproximado por que el 7% que es lo mínimo que se debe helear aumenta el 20% del daño recibido en un lapso del 5 segundos

Ahí dices que se suman, lo he hecho con calculadora y es un "+" xD

Y si, como acabas de decir, siempre será un heal de 7% de vida máxima a menos que el 20% del daño recibido en los 5 segundos sea mayor a esa vida de 7%, pero no es 7% de vida + 20% de daño en los 5 segundos, sino directamente los 20% de daño, a eso me referia.

**Comment by katty09** [comment]
Si, ya te he dicho que lo hicimos según blizz

**Comment by searum** [comment]
fix
