### ISSUE TITLE
[Hechizos] Buff que se acumulan y no deberian.

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#1074]
Buff que dan Agi y Str
1. Cuerno de invierno (Dk)  ........................ spell=57330
2. Grito de batalla (War)     ........................ spell=6673
3. Tótem Fuerza de la tierra  (Chaman)....... spell=65991  (8075)

Ninguno de los 3 debería acumularse con los otros. Solo debería estar 1 activo.

Buff de especializaciones que dan AP y DAP
1. Abomination's Might (DK) .....................Spell=53138
2. Trueshot Aura (Caza)............................spell=19506
3. Unleashed Rage (Chaman)....................spell=30808

Nota: No se si (Bendicion de Poderio), tambien entra aqui, en los no acumulables, debido a que si da el mismo aumento de daño, pero da regeneracion de mana de mana, lo que lo hace diferente......spell=19740 

Buff que aumentan la probabilidad de critico
1. Honor entre ladrones (Picaro).................spell=51701  (51698)
2. Desenfreno (War)..................................spell=29861

Bloodlust/ Heroism (Chaman)................spell=32182
Distorsión temporal (Mago)...................spell=80353
Histeria ancestral (Mascota rara)...........spell=90355

Aqui una imagen con varios buff acumulados y el Daño que puede llegar a hacer =P.
![dam](https://f.cloud.github.com/assets/4944904/906086/80251b7a-fc6b-11e2-91d1-77daea5f06be.png)
Faltan otros buff por anexar-.

**Comment by searum** [comment]
mmmmm Genial el reporte, muchas gracias! esto lo arreglo rapido peeeeero me gustaria que entre todos vieramos cuales son y cuales no porque tal vez te puedas confundir!

**Comment by ghost** [comment]
Mi reporte sobre Distorsión temporal. https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1031

Buen post.

**Comment by Moyax** [comment]
T_T habia tenido problemas electricos.. Hace 3 horas que tengo este comentario abierto, alfin podre subirlo. =P

De los primeros. Grito de Batalla. Es el unico que se acumula con los otros 2.

De los 2dos Buff de especializacion. Todos se acumulan + poderio unos 60 a 80% de AP mas.

De los 3ros de Critical. EL honor entre ladrones se acumula mas de 1 vez. Es decir si hay 2 picaros, ambos dan ese buff. Sumado al desenfreno del war, cosa que no deberia ocurrir, o esta el buff del picaro o el de war, no los 2.

De la ultima tanda. Se puede tirar Heroismo 2 veces, incluso teniendo el debuff de cansancio que genera, y Distorsion temporal se puede lanzar encima de Heroismo. Sino me equivoco distorcion temporal actualmente no esta generando cansansio.

**Comment by searum** [comment]
las 2 ultimas estan fix, las 2 primeras hay que discutirlo porque no estoy seguro

**Comment by Moyax** [comment]
La 2da. Esos 3 Auras de especialización Poseen el mismo efecto. 20% de AP y 10% de DAP aumentado. También el buff poderío que da los mismos % + regen de mana.

Los 1ros si que no consigo una fuente fiable de información, pero al ser aumentadores de stat y no de % tal vez deberían acumularse, aunque son similares. De que se acumulasen ese seria el unico bug que horita no lo hacen el Cuerno de invierno del dk + El toten del chamy, ya que el grito se acumula con todo.

Segun me dicen los compañeros players, "Buff similares no se acumulan" Asi como la bendicion de reyes y marca de lo salvaje.

**Comment by searum** [comment]
Yo espero a pruebas de una fuente fiable

**Comment by ghost** [comment]
Los hechizos con similares efectos deben eliminarse los unos a los otros. Cuerno de invierno+Grito de batalla por ejemplo son el mismo efecto (así como el tótem fuerza de tierra), así que nunca pueden estar puestos a la vez: Al poner uno se eliminará el otro.

Así, a la primera lista habría que añadir Rugido de Corage (ID=93435 ?). Y a la segunda lista, hay que añadir Bendición de poderio, a pesar de dar maná tiene el mismo efecto base y se deben pisar unos a otros. De todos modos, en la lista de abajo se puede ver una lista más completa de los hechizos y sus efectos, no solo de %estadísticas o agi y fuerza, si no también SP, haste...

---

http://www.wowhead.com/forums&topic=180217
Aquí la tabla con muchos de los buffs de las clases, organizados según las estadísticas que aportan. Buff con las mismas estadísticas NO deben acumularse (Cuerno de invierno+Grito de batalla por ejemplo).

**Comment by searum** [comment]
repito, darme pruebas. hoy un colega que juega en el ofi me ha dicho que eso es asi en el ofi a partir de mop y en cata si se stakean soooooooo...

**Comment by F4NT4SM4** [comment]
las auras de poder de ataque cambiaron en mop ahora dan maestria o otros efectos por eso si preguntas por esos 4 van a decir que si pueden tenerlo juntos ya que no tienen el mismo efecto en mop
son 80% poder de ataque si tuviera los 4 eso es muy over....
aqui una fuente de los buff de mop: http://es.wowhead.com/guide=1100/mists-of-pandaria-buffs-and-debuffs
se ve claramente que los buff con mismo efectos no se acumulan 
las aura de poder de ataque son ahora cuerno del invierno, grito de batalla y aura de disparo certero estos no se acumulan en mop

**Comment by Velcositro** [comment]
@searum Yo creo que la lista que dió @asman1 de wowhead es correcta, yo encontré unas listas de Cataclysm (Buffs: http://www.cannotbetamed.com/2010/10/19/raid-buffs-updated-for-cataclysm/ Debuffs: http://www.cannotbetamed.com/2010/10/19/raid-debuffs-updated-for-cataclysm/) que parece concordar y donde dice claramente que los Buffs/Debuffs en la misma categoría no se deben acumular.

**Comment by searum** [comment]
fix
