### ISSUE TITLE
¿ Retirarse? Nunca. ¿ Rendirse? A veces. (MISIÓN HUARGEN)

### ISSUE THREAD

**Issue by kiw92** [RoDNet/Bugtracker-Infinium-4.3.4#1078]
Bueno estoy en una misión huargen, el problema esque dice que tengo que hablar con Lord Darius Crowley dentro de la catedral del alba, y no está. Entonces no puedo entregarla.

Gracias, y saludos.

**Comment by searum** [comment]
pon un ticket ingame para que te la completen asi mientras se repara puedes continuar

**Comment by crowel** [comment]
Listo, cierro Issue.
