### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by brandonmg98** [RoDNet/Bugtracker-Infinium-4.3.4#108]
NO se puede atacr pues se trava el juego

**Comment by WarSxNes** [comment]
o.o? dices atacar?

Casi todo dentro estamos jugando bien. Posiblemente tengas problemas de jugabilidad por que sigues descargando en segundo plano

**Comment by Dekadencee** [comment]
Bug no valido, si se puede atacar, es un problema particular no del servidor
