### ISSUE TITLE
[Cuenta] 

### ISSUE THREAD

**Issue by Almagesto** [RoDNet/Bugtracker-Infinium-4.3.4#1080]
Tengo un problema en mi cuenta. Uno de los personajes me aparece repetido cinco veces en la pantalla de selección de personajes y no se si tiene relación, pero al entrar apenas puedo hacer nada, lanzar hechizos etc porque tengo mucho lag.

Gracias

**Comment by searum** [comment]
pues si me dices el nombre de tu pj puedo solucionartelo, de todas formas estos bugs no van al bugtracker, aqui son bugs generales y no personales :p estas cosas mejor en el foro y dando mas detalles.

lo de que al entrar tienes lag y todo eso pues ni idea, no deberias porque no hay nada de lag... sera o bien tu pc o bien tu conexion no tengo ni idea pero vamos, prueba a borrar cache

**Comment by Dekadencee** [comment]
Posteanos en el foro tus problemas ofreciendo más detalles por favor, cerramos
