### ISSUE TITLE
Feria de la luna negra: no se puede ingresar

### ISSUE THREAD

**Issue by mccelobb** [RoDNet/Bugtracker-Infinium-4.3.4#1084]
Se supone que abre hoy y que dejaria entrar a partir de las  00:01 hora del server.
No puedo entrar y son las 16:00 hora del server (arreglen que quiero ver esos abalorios epicos ;) )

**Comment by kirgar** [comment]
si vas a shatrat tienes la feria y hoy he cambiado el trinket

**Comment by hairblood** [comment]
la feria cambio en la 4.3:deberia ser en una isla con sus nuevos evento:minijuegos,arena en plan gurubashi,misiones para subir profesion,etc
http://es.wowhead.com/zone=5861

**Comment by ghost** [comment]
Raro lo de la feria... la primera vez que se abrió la fería yo fuí, y la mayoría de las cosas funcionaban bien.
