### ISSUE TITLE
Problema en la Mision El camino de los reyes

### ISSUE THREAD

**Issue by Honme** [RoDNet/Bugtracker-Infinium-4.3.4#1085]
http://es.wowhead.com/quest=13188/el-camino-de-los-reyes

Hola, tengo un problema con esta misión de los Dk's la misión consiste en que tengo que entregar una carta al Rey Varian Wrynn en Vetormenta esta misión la da el Alto Señor Darion Mograine me tele transporte a Ventormenta desde el Bastión Ébano pero cuando he llegado a Ventormenta no he encontrado ni un solo PJ o NPJ la ciudad esta totalmente desierta si me pudieran ayudar con este problema les estaría muy agradecido.

Gracias por su tiempo.

**Comment by Kiritoo** [comment]
Esto está fix.
