### ISSUE TITLE
[Pícaro] [Glifo ó Spell] Glifo de Hemorragia

### ISSUE THREAD

**Issue by FullArrow** [RoDNet/Bugtracker-Infinium-4.3.4#1086]
No aparece en www.es.wowhead.com Pero les adjunto varias fotos,
![captura](https://f.cloud.github.com/assets/5083085/907190/43267d08-fd16-11e2-9840-15cebd66c347.JPG)

El caso es que Debería infligir un 40% del daño inmediatamente anterior producido por la facultad Hemorragia. por ejemplo con unos 9k de golpe directo, debería infligir 3600 mediante el efecto periódico cada 3 s durante 24 s pero sólo inflige 3-6 puntos de daño.
![captura34](https://f.cloud.github.com/assets/5083085/907192/59d3f4ea-fd16-11e2-9f2c-ef171f872d1e.JPG)

**Comment by searum** [comment]
fix
