### ISSUE TITLE
(Bug) Maestria de chaman rayos

### ISSUE THREAD

**Issue by kirgar** [RoDNet/Bugtracker-Infinium-4.3.4#1087]
Bug maestria Sobrecarga elemental id:77222 http://es.wowhead.com/spell=77222.
Tiene un 16% de probalidad base de que salte la maestria mas un 2% por punto de maestria. Pero da igual cuanto pegue con descarga de relampagos,cadena de relampagos o rafaga lava no me salta la maestria.
La maestria consiste en que haga un 2º hechizo el mismo que lance pero sin coste de mana ni agro y que inflinge un 75% del daño normal.

**Comment by searum** [comment]
fix
