### ISSUE TITLE
[Misión][Las Tierras Devastadas] No es cualquier cuerpo (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1089]
Buenas.
La misión "No es cualquier cuerpo" (http://es.wowhead.com/quest=26161) no se puede completar porque falta el "Alijo de Machacamiedo" (http://es.wowhead.com/object=203204) que contiene el objeto "La cabeza de Loramus" (http://es.wowhead.com/item=55829). El alijo debería estar en la cueva mas al norte.
Gracias y hasta luego.

**Comment by Kiritoo** [comment]
Fix, falta aplicar.
