### ISSUE TITLE
[Sacerdote] Pecado y Castigo

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#109]
El talento pecado y castigo no hace ninguna de las dos funciones que estan en la descripción.

Enlace: http://es.wowhead.com/spell=131556
![wowscrnshot_070413_140333](https://f.cloud.github.com/assets/4663665/750628/3329ea7a-e4d4-11e2-8f7d-5f6571ad218b.jpg)

Pd: la imagen nada más la puse para que se vea la descripción completa, no me vengan ahora con que no tengo el talento puesto que ya me lo cambie xd.

**Comment by searum** [comment]
fix

**Comment by crowel** [comment]
@searum 
Hola queria comentar que este talento, usandoselo a un dummy, toque vampirico http://es.wowhead.com/spell=34914 al pasar el tiempo de la enfermedad y desaparece, aterroriza los enemigos, esto solo deberia ocurrir cuando lo disipan y no cuando se ataca el tiempo de la pegatina.
La otra parte del talento esta funcionando genial, gracias.

Un saludo.

**Comment by searum** [comment]
okey! lo ajustare ^^

**Comment by ghost** [comment]
@searum no sé si lo ajustaste, pero sigue tirando fear al acabar el efecto del dot, y no al ser disipado, además la otra parte del talento, lo de reducir el tiempo de reutilización del maligno de las sombras, solo debe suceder cuando la tortura mental hace un golpe crítico, ahora mismo lo hace sin ser golpe critico.
