### ISSUE TITLE
[Misión][Bosque del Ocaso] Una Maldición imposible de romper

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1091]
Buenas.
La misión "Una Maldición imposible de romper" (http://es.wowhead.com/quest=26720) no se puede completar porque cuando uso el objeto "Pipeta de Harris" (http://es.wowhead.com/item=60206) en el "Huargen acechante" (http://es.wowhead.com/npc=43814), no sucede nada.
Gracias y hasta luego.

**Comment by Raphaell94** [comment]
A mi tampoco me va, ayuda

**Comment by ghost** [comment]
Reparada.
