### ISSUE TITLE
[Misión][Montañas Crestagrana] En busca de la Compañía Bravo

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1092]
Buenas.
La misión En busca de la Compañía Bravo (http://es.wowhead.com/quest=26586) no se puede completar porque falta el PNJ Messner (http://es.wowhead.com/npc=43270) para entregarla.
Gracias y hasta luego.

**Comment by Kiritoo** [comment]
Fix
