### ISSUE TITLE
[Misión][Montañas Crestagrana] No tiene fin

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1093]
Buenas.
La misión "No tiene fin" (http://es.wowhead.com/quest=26616) no se puede completar porque no está el bote ni el PNJ John J. Keeshan (http://es.wowhead.com/npc=43458) para entregarla.
Gracias y hasta luego.

**Comment by Kiritoo** [comment]
Fix
