### ISSUE TITLE
[hechizos-talentos] Limpiar + actos de sacrificio Paladin Retri

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1094]
Buenas para comentar que este hechizo no ayuda en nada contra los efectos antimovimiento. No sirve y creo que es el talento que se suma al spell que no funciona.

Talento http://www.wowwiki.com/Acts_of_Sacrifice

http://www.wowhead.com/spell=4987/cleanse

**Comment by searum** [comment]
fix
