### ISSUE TITLE
[Glifos] Glifo de Proteccion Divina - Paladin

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1095]
Esta mejora del hechizo Proteccion Divina, no sirve. Cuando lo aplicas, y usas protección divina, dice que reduce 0% del daño mágico, y no es algo solo visual.

http://es.wowhead.com/spell=57022/glifo-de-proteccion-divina

**Comment by Monleon** [comment]
Es visual
