### ISSUE TITLE
[Hechizos] Escudo sacro V2. Paladin

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1096]
Buenas, según esto quedó fix.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/595

Esto es lo que acabo de probar:

El Escudo si sale al estar en 30% de salud total, pero absorve como 1k , en vez de 29k que dice mi talento...

![wowscrnshot_080413_155013](https://f.cloud.github.com/assets/4790547/907566/5d01c764-fd48-11e2-81fb-8452f6fa853c.jpg)
![wowscrnshot_080413_155019](https://f.cloud.github.com/assets/4790547/907567/5d3717b6-fd48-11e2-8148-2eab8e9d47ea.jpg)

Además, el beneficio aparece en 1 segundo y eso dura, se desaparece al instante. Debería durar 15 segs.

Conclusión: No quedó fix :/. Me avisan si cierro el tema y se reabre el otro. Gracias

**Comment by searum** [comment]
en el anterior issue dije q lo habia convertido al cata el spell porq estaba el de 335, no dije q fuera 100% :) me esperaba algun reporte mas ya que como comprenderas yo solo no puedo testear muchas cosas.

**Comment by searum** [comment]
ahora si lo he fixeado, me faltaba la formula 2.8 \* AP

**Comment by lamaza** [comment]
Estas loco!!!! fix fix fix! y dale que dale fix a todo!! Locoooooo loquillooooo haha Gracias Don Searum! :)
