### ISSUE TITLE
Ningun npc en la zona Huargen "Refugio del Ocaso"

### ISSUE THREAD

**Issue by kiw92** [RoDNet/Bugtracker-Infinium-4.3.4#1097]
Después de acabar las misiones de la ciudad de huargen te traslada al refugio del ocaso cuando entregas una quest en un tio que hay situado cerca tuya desaparecen todos y no aparece ningún npc. gracias.

**Comment by Niddpina** [comment]
buenas yo estaba con el xD  me pasa lo mismo

**Comment by Niddpina** [comment]
soy Angerfist
