### ISSUE TITLE
[Titulo] El camellero

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#11]
Al conseguir el logro no me lo ha dado.

**Comment by lamaza** [comment]
Como lo conseguiste?

**Comment by lamaza** [comment]
Perdón yde que se trata el logro, es necesario que pongas un link de DB.

**Comment by Wiinter** [comment]
ahhh es verda qe tonto. Ya lo tenía matado de la 4.0.6 que se podía matar pero no daba logro. 
Aqui teneis el link del logro qe debería dar este titulo: http://es.wowhead.com/achievement=5767

**Comment by Varga9** [comment]
Es cierto a mi me aparece el logro pero no el titulo :S

**Comment by crowel** [comment]
Un amigo tiene este título wiinter, compruebalo cuando puedas.
Saludos.

**Comment by Wiinter** [comment]
Sip lo arreglaron hace poco, yo tambien lo tengo xD
