### ISSUE TITLE
Fps bajos al estar en grupo/banda

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#110]
Bueno es simple, al estar en un grupo o banda los fps oscilan y se ponen bien, bajan, se ponen bien y así infinitamente, sales de la banda o grupo y vuelve todo a la normalidad, esto le sucede a otros también, no solo a mi.

Aclaro que esto no pasa el 100% de veces, derrepente los fps funcionan bien estando en banda o grupo, pero la mayor parte funciona mal.

También agrego que no tengo addon alguno, ya probe borrar cache, bajar calidad de graficos etc, todo lo posible y nada.

Si hace falta alguna imagen la pondre.

**Comment by WarSxNes** [comment]
aaa creo que in-game salio un mensaje que recomendaban no hacer mazzmorras o bandas por el momento xD....

**Comment by Dekadencee** [comment]
Fixed
