### ISSUE TITLE
Bugs Druida Equilibrio

### ISSUE THREAD

**Issue by edwyr** [RoDNet/Bugtracker-Infinium-4.3.4#1101]
Hola, a continuación os pongo los bugs que he ido encontrando del Druida Equilibrio en estos 4 dias que llevo jugando.

1º.- La spell "Lluvia de estrellas" no se detiene al ser inmovilizado o ralentizado el druida, esta spell deberia dejar de lanzar estrellas en cuanto pierdes el control de tu personaje, os adjunto la spell; tampoco se reinicia el cd de la spell al llegar a un eclipse (http://es.wowhead.com/spell=48505).

2º.- Cuando cambias a cualquier otra forma (feral, oso, lechucico....) la merma de movimiento o si estas clavado en el suelo se quita, esto por talentos solo deberia de pasar si escojes la rama de restauración pero ocurre también en equilibrio, nose si pasará también en la rama feral el talento es "Desenredo" y es pasivo.

3º.- La spell "Champiñón salvaje" funciona, pero no explota ("Detonación de champiñones salvajes" (http://es.wowhead.com/spell=88751/detonacion-de-champinon-salvaje)) y el champiñon no para de perseguirte en vez de quedarse donde lo pones.

4º.- La spell "Oleada de estrellas" (http://es.wowhead.com/spell=78674) está pegando alrededor de un 46% menos de lo que deberia, según Dr damage, aunque es obvio que la spell que mas pega del druida Equilibrio no puede pegar menos que cólera y ahora mismo esta pegando menos, de todas formas deberiais probarlo vosotros también.

5º.- La spell "Fuego estelar" (http://es.wowhead.com/spell=40344) (esta spell de wowhead no se corresponde con la del juego, nose porqué, aún así os la adjunto) está pegando alrededor de un 18% menos de lo que deberia, según Dr damage, de todas formas deberiais probarlo vosotros también.

Demomento no he visto mas nada así a simple vista, más adelante si encuentro algo más que sea mas minucioso intentaré reportarlo, Espero que puedan arreglarlo lo mas rapido posible, un saludo y gracias.

**Comment by searum** [comment]
De momento cierro porque hay otro reporte del 2º fallo y todo lo demas lo he arreglado. Para proximas veces trata de poner un issue por bug ! gracias
