### ISSUE TITLE
daño bajo de flecha negra

### ISSUE THREAD

**Issue by patriccio** [RoDNet/Bugtracker-Infinium-4.3.4#1102]
hola, el daño de http://es.wowhead.com/spell=3674 siendo el talento principal de la convinacion de daño del caza sv, es la que menos daño hace aki ya que a los muñecos de entrenamiento como mucho le metes de critico 3k  con pulsos de 1.5k de daño teniendo en cuenta que no poseen temple.

**Comment by searum** [comment]
ya, pero si miras la descripción el daño que hace hace incluso mas daño del que pone... ese argumento no me vale xD

**Comment by patriccio** [comment]
si tomas encuenta la descripcion es del mop . donde flecha negra dejo de ser un skill importante, a diferencia que en la 4.3.4 si lo es

**Comment by lamaza** [comment]
Sube fotos de test con muñecos y con pjs temple con log de combate y todo. Yo a los caza, los pocos que hay, los veo pegando más que bien.

**Comment by searum** [comment]
esto va bien...
