### ISSUE TITLE
escudo de mana bug

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.3.4#1103]
estes con rama de escarcha o rama de fuego te beneficias del talento de la rama de arcano absorcion de encantador (ID: 116267) que cuando se rompe el escudo de mana (ID: 56778),lanza a la gente unos metros hacia atras

**Comment by searum** [comment]
Pues asi vamos bien porque la id que me has pasado es de mop xD

bajaros el addon "idtip" ^^ asi sacais las ids correctas

**Comment by searum** [comment]
fix pero testearlo mañana

**Comment by ghost** [comment]
Ya no repele, ahora falta ajustar el daño que debe absorber y quitar el efecto de absorción de encantador.
