### ISSUE TITLE
[Talento][DK] Parásito de Sangre

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1104]
Buenas.
El talento "Parásito de Sangre" (http://es.wowhead.com/spell=49542) no funciona correctamente porque el gusano no cura a nadie al estallar (mas bien, desaparece).
También quiero agregar que el gusano es extremadamente agresivo y ataca a cualquier cosa a 20m a la redonda, ignoro si esto es normal o no.
Gracias y hasta luego.

**Comment by searum** [comment]
fix
