### ISSUE TITLE
El oculus Bug

### ISSUE THREAD

**Issue by edwyr** [RoDNet/Bugtracker-Infinium-4.3.4#1108]
Buenas, esta mañana estaba haciendo algunas mazs de rasganorte y cuando he ido a "El oculus" he podido hacer el primer nivel, matar a "Drakos el interrogador" (http://es.wowhead.com/npc=27654) pero tras matarlo me quedo en esa plataforma sin poder pasar a la siguiente, salen 3 npcs y hablo con ellos, le doy a todas las opciones pero tampoco me llevan a ningun sitio.

Espero que puedan arreglarlo, un saludo.

**Comment by redneo** [comment]
Buenas ed, me puedes poner las direcciones de wowhead de los 3 npcs que te tendrian que dar los dragones?

Gracias y un saludo

**Comment by edwyr** [comment]
Alfinal, resulta que no está bug, esque te dan un dragon en la mochila para que lo invoques y yo no me estaba dando cuenta de eso, siento haberos hecho perder el tiempo.

**Comment by Dekadencee** [comment]
No pasa nada @edwyr una confusión le puede pasar a cualquiera, cerramos
