### ISSUE TITLE
[Chamán] Escudo de Relámpagos

### ISSUE THREAD

**Issue by Navalagamella** [RoDNet/Bugtracker-Infinium-4.3.4#111]
El hechizo Escudo de Relámpagos [ http://es.wowhead.com/spell=324 ] no crea las 3 esferas que debería, por el contrario se van acumulando 1 por 1 cada vez que se lanza el hechizo, desde 1 carga hasta un máximo de 9 cargas, cuando lo que debería de hacer es solo darte 3 cargas y no acumularlas.
![sin ttulo](https://f.cloud.github.com/assets/4733643/750729/de8cb6d8-e4d7-11e2-85d4-cae6ed183ec6.png)

Edito: Al parecer es un bug visual, incluso si tienes 9 cargas como si tienes 1 carga, solo hacen daño (y se va el buff) al hacer daño 3 veces. El glifo de escudo relámpagos sigue estando bug.

**Comment by searum** [comment]
en que quedamos? esta bug o no esta bug? XD a ver si reportamos bien please... que no entiendo nada del issue.
