### ISSUE TITLE
Mision Huargen No puedes acabar con ellos solo

### ISSUE THREAD

**Issue by kirgar** [RoDNet/Bugtracker-Infinium-4.3.4#1110]
Bug Mision No puedes acabar con ellos solo. http://es.wowhead.com/quest=14348
Puedes coger los barriles y lanzarselos a las abominaciones pero cuando le tiras el barril no cuenta.
http://es.wowhead.com/npc=36231
http://es.wowhead.com/item=49202

**Comment by searum** [comment]
fix para el proximo reinicio
