### ISSUE TITLE
[Guerrero] Cargar ira

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1112]
http://es.wowhead.com/spell=100/cargar

Deberia de generar 15 de ira tras usar cargar pero no esta generando nada

**Comment by searum** [comment]
fix, tengo q compilarlo

**Comment by F4NT4SM4** [comment]
sigo sin generar esos 15 de ira :p

**Comment by searum** [comment]
recalco: fix, tengo q compilarlo no he actualizado todavia ^^ ando haciendo cositas y ayer no pude al final.
