### ISSUE TITLE
[Guerrero] Cargar rendimiento decreciente

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1113]
http://es.wowhead.com/spell=100/cargar

Cargar e Interceptar ya no tienen rendimiento decreciente en sus efectos de aturdimiento.

Info: http://us.battle.net/wow/es/game/patch-notes/4-1-0#warriors

El caso es que al usar cargar el siguiente cargar dura menos y ya a la siguiente cargar el objetivo no le afecta el stun lo que da a entender que tiene rendimiento decreciente y no deberia...

**Comment by searum** [comment]
el diminishing del cargar lo quite hace 2 dias. te estaras confundiendo en tu reporte y sera otro fallo, revisalo bien anda

**Comment by F4NT4SM4** [comment]
tambien esta reduciendo el stun del derribar de 5segundo a 1 segundo......

**Comment by searum** [comment]
ya te digo q no tiene diminishing porque se lo quite... lo de derribar es otra cosa, no tiene q ver con cargar.

**Comment by F4NT4SM4** [comment]
ok el derribar es otra cosa que se ponga 1s tras usar cargar
pero el cargar si tiene rendimiento decreciente el siguiente cargar dura menos y ala siguiente es inmune el objetivo
aqui una prueba sale inmune tras el tercer cargar :l 
![wowscrnshot_091113_092355](https://f.cloud.github.com/assets/3101842/1123113/9ac25d34-1ae9-11e3-8d5b-3288612ca5d0.jpg)
