### ISSUE TITLE
Cumbre del vortice

### ISSUE THREAD

**Issue by kirgar** [RoDNet/Bugtracker-Infinium-4.3.4#1115]
Weno cuando llegamos al 1º boss los ciclones no hacen casi nada de daño a caster pero a melee hacen mucho daño y no se quedan fijos van dando vueltas.
Cuando llevas parte de la mazmorra echa en teoria te tendria que dejar usar los ciclones de la entrada que te teletransporta pero no lo hace. El 2º boss y el 3º van bien solo aver si arreglais lo de los loot de los bosses.
Al acabar la instance deberia dar puntos de valor por ser la 1ª aleatoria heroica pero no dan los puntos de valor.
<a href="http://www.subirimagenes.net/i/130805073358278012.jpg" target="_blank" title="subir imagen"><img src="http://sia1.subirimagenes.net/img/2013/08/05/mini_130805073358278012.jpg" border="0" alt="subir imagenes" /></a>

PD: Para la proxima hare video para que se vea mejor

**Comment by efectokoleos** [comment]
ya funciona bien la instance
