### ISSUE TITLE
[HEchizos] Terror de Fatalidad Debuf brujo daño exagerado

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1117]
Creo que las fotos hablan por si solas, buena tarde o noche.

![wowscrnshot_080513_150100](https://f.cloud.github.com/assets/4790547/912971/4930970a-fe0c-11e2-9240-fe591e5d0d66.jpg)
![wowscrnshot_080513_125605](https://f.cloud.github.com/assets/4790547/912972/49318c5a-fe0c-11e2-9cf0-88f6cf37ae46.jpg)
![wowscrnshot_080513_125616](https://f.cloud.github.com/assets/4790547/912973/4933e96e-fe0c-11e2-9dfb-d34bc846ec61.jpg)
![wowscrnshot_080513_140117](https://f.cloud.github.com/assets/4790547/912974/4934729e-fe0c-11e2-907c-4a35d7e5fce6.jpg)

**Comment by searum** [comment]
las fotos no hablan por si solas, la id me la invento¿?

no creo que sea el daño de la spell loq ue este mal... la he probado y a mi me va bien..

**Comment by ghost** [comment]
ID: 603, y sí que viene en la foto xP

**Comment by lamaza** [comment]
Este searum!!! ya lo ven, nos regaña con que bajemos el idtool y no se que, y ahi sale en la foto y miralo !!!.haha

Entonces no se que afecta al daño de Terror de Fatalidad :/.

**Comment by Felarof23** [comment]
Hola como les va?, quiero apoyar, en lo que pueda, a reparar los bugs que tenemos los brujos, estos son mis numeros sin bufos, talentos y glifos, no duden en pedirme los stats que necesiten :D

![drdamage](https://f.cloud.github.com/assets/5028343/922142/1485b82c-ff1b-11e2-94e2-9e91506b960d.png)
![general](https://f.cloud.github.com/assets/5028343/922143/148193b4-ff1b-11e2-8212-b54d73ea3155.png)![distancia](https://f.cloud.github.com/assets/5028343/922141/147cf53e-ff1b-11e2-8554-245b3f0688f5.png)![hechizo](https://f.cloud.github.com/assets/5028343/922145/148b7cd0-ff1b-11e2-96fa-b85936585fba.png)
![talentos](https://f.cloud.github.com/assets/5028343/922146/1494081e-ff1b-11e2-8ec3-7c87612a307a.png)
![glifos](https://f.cloud.github.com/assets/5028343/922144/148752cc-ff1b-11e2-8b91-671e7989a158.png)

espero ayude en algo.

Saludos!

**Comment by ghost** [comment]
21k de tick me ha metido Menegrot en bg, sin crítico.

**Comment by Felarof23** [comment]
En la página del wowhead http://es.wowhead.com/spell=603/fatalidad, se puede ver lo siguiente:

3612 + ( 375% of Spell power)

Como nota de referencia, la fórmula utilizada para los daños de las spells aparece en esta página: http://www.foros.net/viewtopic.php?t=83&mforum=Valhala y seria: 

multiplicador \* (daño base + [coeficiente \* poder hechizo])

reemplazando con las cifras mostradas arriba esto nos daria:

1.56_(1957+[3.52_6076])=23,344.52, claro esta, habría que restarles las resistencias, los temples etc y sumar buffos y debuff.

Haciendo las mismas pruebas con mis actuales indicadores este es el resultado que obtengo:

1.576_(1957+[3.52_6468])= 24,724.36

la prueba la hice en un dummy sin buffos ni debuff que aumentaran el daño con hechizos y como pueden ver en la screen, el daño hecho es cercano al obtenido con la fórmula anterior, esta pasado por 4k.

![dummy](https://f.cloud.github.com/assets/5028343/1023800/f1bf2c62-0e09-11e3-9d1d-157326d82b40.png)

en la misma página del wowhead, se comenta lo siguiente:

"Agony was on for 40 seconds, and it did 72k dmg. (Under both BL and Hourglass buff)
BoD has ticked 11 times wich is equal to 175 seconds, and it did 310k dmg.
So, using a calculator, its easy to see that:
Agony: 1800 Dps
BoD: 1770 Dps "

esto sería:

310,000 / 11 = 28,181.81

También recordemos que es un tick cada 15 segundos a un solo objetivo y es perfectamente dispeleable, dejo todo esto a criterio del GM, pues es él el que tendrá la última palabra (hacerca) acerca del asunto.

Saludos!

**Comment by lamaza** [comment]
Entonces lo que están mal son las reducciones y resistencias, ya que es prácticamente el mismo daño a un muñeco que a un pj, no sé. En todo caso, se escribe acerca, sin h. haha Gracias Menegrot por toda la info.

**Comment by Felarof23** [comment]
Gracias por la correción, en seguida edito. :P

Saludos!

**Comment by Drogoth2** [comment]
Bueno yo tengo algo que añadir a todo esto https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1685

**Comment by ghost** [comment]
@lamaza eso está claro, las resistencias nunca han funcionado aquí en todo lo que llevo jugando. Cuando se arreglen medianamente las cosas y tengan algo más de tiempo ya se reporta y lo van arreglando, que es algo más complicado de fixear diría yo.

**Comment by redneo** [comment]
Fixed
