### ISSUE TITLE
[Sacerdote] Púa mental

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#112]
Al lanzar púa mental sobre un objetivo que tiene puestas las enfermadades, debe sacarlas todas (a las enfermedades), esto no sucede.

![wowscrnshot_070413_132539](https://f.cloud.github.com/assets/4663665/750741/54a9cd38-e4d8-11e2-8061-de7f2b04dff6.jpg)

Como se ve en la imagen el muñeco tiene puesto el debuff de púa mental pero sigue con las enfermedades.

**Comment by searum** [comment]
facilitame ids o nombres de las enfermedades que deberia retirar.

**Comment by crowel** [comment]
Devouring Plague http://es.wowhead.com/spell=2944
Shadow Word: Pain http://es.wowhead.com/spell=589
Vampiric Touch http://es.wowhead.com/spell=34914

Un saludo.

**Comment by ghost** [comment]
Quiero agregar (ya que sigue siendo la misma spell) que su daño esta bajo, pongo imagen con el dr.damage porque todos los demás spells estan exactamente igual que lo que dice el dr. damage.
![wowscrnshot_071813_191926](https://f.cloud.github.com/assets/4663665/823062/81028086-f000-11e2-94a1-6c41fa06daf1.jpg)

**Comment by searum** [comment]
fix

**Comment by crowel** [comment]
Perfecto! ya elimina maldiciones.
Falta ajustarle el daño, el cual está bajo.
Un saludo.

**Comment by redneo** [comment]
Daño correcto.
