### ISSUE TITLE
[Misión]El viaje final de los fuertemarea

### ISSUE THREAD

**Issue by Santaclaws** [RoDNet/Bugtracker-Infinium-4.3.4#1120]
Enlace: http://es.wowhead.com/quest=26697
Problema: No te monta en montura para hacerla, no sé si los enemigos de misión se encuentran donde deberían, porque te marca un punto del mapa y no los veo allí.

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/551?source=cc
Enlazo con repote anterior
