### ISSUE TITLE
tromba arcana [mago]

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.3.4#1122]
la tromba arcana (ID: 44425) aplica el echizo relentizar (ID: 31589) i no es asi,la tromba arcana no aplica ningun efecto de relentizar

**Comment by lamaza** [comment]
Hola, como que uno se va dando cuenta (sin ofender), que tan bug estan ciertas clases (de manera benéfica) y como esas mismas clases (player) se creen pro en el juego XD, y resulta que pocos reportan algo sobre su propia clase ;/. Me gusta la gente que reporta, y los reportes, y reportar hehe un saludo!.

**Comment by searum** [comment]
te confundes, a mi en el server no me aplica nada al lanzarlo..
