### ISSUE TITLE
[Rayo solar] Druida equilibrio

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1123]
Buenas noches

El hechizo Rayo solar del druida equilibrio http://es.wowhead.com/spell=78675/rayo-solar está silenciando aún estando a 40 metros de la ubicación elegida por el druida enemigo, cuando debería silenciar solo a los objetivos que se encuentren debajo de donde esté el "rayo solar"

Es decir, tal como está funcionando ahora, son 8segundos de silencio a todos los rivales hasta que desaparezca el debuff aplicado por el druida (cuya duración son 8seg también).

**Comment by crowel** [comment]
Acabo de testearlo el problema no esta en la distancia sino que está en el aura.
Cuando utilizas rayo solar aparece el siguiente aura en el npc / jugador.  81261
![wowscrnshot_080613_031500](https://f.cloud.github.com/assets/3537253/914371/b0c298a4-fe35-11e2-9189-b08312704d1d.jpg)

Por mucho que se aleje del rayo a pié o volando en montura el aura del rayo solar no desaparece hasta que pasa el tiempo, por lo que el problema no es la distancia.
Un saludo

**Comment by searum** [comment]
pues a mi en localhost me va genial >_<

**Comment by crowel** [comment]
Yo diria que es por db el aura del spell, no me hagas mucho caso xDD

**Comment by lamaza** [comment]
Hoy en arenas a asman y a mi un pollo nos intento matar usando este hechizo con el bug que aqui describen, que silencia a diestra y siniestra.

**Comment by searum** [comment]
fix
