### ISSUE TITLE
[Misiones] (Darkmoon Faire) Feria de la Luna Negra bugs

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1124]
Estas son algunas quest bug, que no se pueden realizar. Explicare que le pasa a cada una con imágenes.

http://www.wowhead.com/quest=29508/baby-needs-two-pair-of-shoes

Baby el caballito no aparece, pero si se pueden crear las herraduras.

![wowscrnshot_080513_184930](https://f.cloud.github.com/assets/4790547/914196/adce1be2-fe2f-11e2-9e04-e5bd6c6e76bb.jpg)

---

http://www.wowhead.com/quest=29520

No esta el sitio que pide, una especie de roca o puesto especial.
## ![wowscrnshot_080513_184944](https://f.cloud.github.com/assets/4790547/914103/f8dfc232-fe2c-11e2-93be-6d93f574ec10.jpg)

http://www.wowhead.com/quest=29438/he-shoots-he-scores

Se entra al modo "shooter" pero al intentar usar la habilidad de disparar, no pasa nada.

![wowscrnshot_080513_180915](https://f.cloud.github.com/assets/4790547/914109/1cafd454-fe2d-11e2-942d-a14f2f146bb2.jpg)

---

http://www.wowhead.com/quest=29512

No existen los tal Ferianos Heridos en ningún lado. Pero el objeto se puede curar a cualquier clase de entidad, amiga o enemiga y cura full SIEMPRE. Me tire de varias alturas y lo usaba y me curaba como imposición, solo que sin cd hehe.

![wowscrnshot_080513_182335](https://f.cloud.github.com/assets/4790547/914122/7cdb11cc-fe2d-11e2-8e54-e87b9c39ef56.jpg)

---

http://www.wowhead.com/quest=29509

Se pueden crear las ranas fritas con harina.El problema es que la olla no es un objeto para interactuar, solo esta ahi, y si usas las ranas no pasa nada, solo se gastan.

![wowscrnshot_080513_182254](https://f.cloud.github.com/assets/4790547/914157/65c59fb0-fe2e-11e2-89b3-1edfeaf2173c.jpg)

---

http://www.wowhead.com/quest=29518

Estos elementos para recoger (mineria) no existen. Aclaración: Se que el evento en sí tiene su area propia (Isla) y que no esta abierta, pero YO y solo es mi opinión, considero que tales elementos perdidos para poder realizar las quest, deberian salir asi no este en el area, no se, como que cargue todo con la feria, npcs, objetos del suelo etc.

Un saludo, y perdon pero queria ponerlas juntas para que no se mezclen con las demás quest. Bye

**Comment by hairblood** [comment]
bueno ya detalles fuera de lugar
solo faltan las limitaciones:las que son de misiones de profesion,deberian ser diarias y solo dejarte cogerla si tienes minimo la profesion a 75
la de conseguir 250 trofeos,deberia ser mensual

**Comment by redneo** [comment]
ole... esto estaba buscando... a ver si luego lo cambio y pongo las reparadas

**Comment by Compresor** [comment]
Funcionan todas
