### ISSUE TITLE
[Glifo Rayo solar] Druida equilibrio 

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1125]
Hola quiero reportar el siguiente glifo.

Glifo de Rayo solar, 54812 - 56944 No encuentro la id exacta, sino me equivoco es una de estas.

Descripción: Aumenta la duración del silencio del rayo solar 5 segundos.
![wowscrnshot_080613_032346](https://f.cloud.github.com/assets/3537253/914405/24795228-fe37-11e2-9ab2-860d51abead5.jpg)

El problema está que no aumenta esos cinco segundos, durando el rayo solar(78675) siempre los 10 segundos de tiempo base del hechizo, cuando se deberian de aumentar a 15 con el glifo.

Un saludo.

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
