### ISSUE TITLE
[Guerrero] Ira al atacar

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1126]
la ira del guerrero es muy poca esta generando 6 por golpe....
Me puse a ver unos videos de wars del offi y la ira se genera mucho mas...

http://youtu.be/jWdpG6NgldA?t=5m24s

La formula creo que esta aqui http://www.wowwiki.com/Rage
nose si es de esta version :l
P.D: cuando testeen haganlo en fury el armas tiene talentos que dan ira extra...

**Comment by searum** [comment]
Ya va bien no?

**Comment by F4NT4SM4** [comment]
me di cuenta que solo genero 6 de ira con el dummy 
con los mobs genero 30 o 40 por golpe 
y jugadores 15 o 10 de ira por hay

**Comment by searum** [comment]
No es que hace poco aplique un fix para la ira del warrior xD deberia de ir correctamente y con cargar deberia de regenerar 15 de ira tambien :p

**Comment by F4NT4SM4** [comment]
solo falta maestria en actitudes y ya la ira del war queda perfect e-e
pero como no consigo id del skill...

**Comment by searum** [comment]
tiooo bajate el idtip xD es un addon que te dice las ids de items, spells, auras... xD

**Comment by F4NT4SM4** [comment]
ya hice le reporte e-e 
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1183
