### ISSUE TITLE
tromba arcana [mago] 

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.3.4#1128]
searum me as cerrao el otro issue de la tromba arcana diciendo que me confundido
aqui tienes un video de como se relentiza solo echandole la tromba 

http://www.youtube.com/watch?v=YsEg4l11dWI&feature=youtu.be

**Comment by searum** [comment]
que si oscarin que puede ser pero la tromba arcana no es, sera otro talento o alguna movida que salta... pero tromba arcana SIN NADA MAS no suelta eso.. ya te lo digo yo... vuelvo a cerrar y cuando reportes bien con ids y demas que cuesta poco bajarse el idtip y ponerlo me posteas un issue con la id del aura que esta ralentizando y comprueba quitandote talentos y movidas...

**Comment by searum** [comment]
Es vortice abisal que salta con tromba tambien... no es que se lo saque de la manga :) si aprendemos a detectar fallos a lo mejor los arreglo antes y me ahorrais el tiempo de testeo porque yo os recuerdo que solo arreglo y no juego.

**Comment by searum** [comment]
ya esta fixeado u_U
