### ISSUE TITLE
Hunter> Bug's por doquier

### ISSUE THREAD

**Issue by Hellythium** [RoDNet/Bugtracker-Infinium-4.3.4#113]
Buenas, espero que no tomen a mal el titulo, pero es que es algo real, yo como Cazador desde hace mucho tiempo note fácilmente algunos bugs que presenta el Cazador después de la actualización, antes que nada, tengo la aprobación de algunos de mis compañeros (Miglent, Snick y Blacksipers) que presentan estos bugs, no todos, pero si la gran mayoría, muy bien empecemos y esto será largo:

A) Bug en maestría: No se si este bug lo tengan las demás clases o si solamente lo presento yo y es que no tengo la maestría, pero tampoco puedo aprenderla, aquí les dejo las imágenes: 
![wowscrnshot_070413_121259](https://f.cloud.github.com/assets/3613748/750803/c3f292ae-e4da-11e2-8ec2-4f19af397c9e.jpg)
![wowscrnshot_070413_121241](https://f.cloud.github.com/assets/3613748/750804/c452dace-e4da-11e2-8ed7-e1314fad0944.jpg)

B) Vida de las Pets notoriamente reducida: Lastimosamente no tengo imágenes de como era la vida de mi pet o las de mis compañeros antes pero todos notamos que esta esta considerablemente reducida, mi pet en especial, antes tenia 78ks de vida y ahora solo 33ks y la de Blacksnipers, no se bien cuanto tenia antes pero dice que ahora tiene solo 27ks, aquí la imagen:
![wowscrnshot_070413_121355](https://f.cloud.github.com/assets/3613748/750805/d0167866-e4da-11e2-8c62-f09966b5d517.jpg)

C) Llamada de maestro: Simplemente no funciona, al activar este spell http://es.wowhead.com/spell=53271/llamada-de-maestro#screenshots no me funciona, como lo muestran las imágenes que otros jugadores han montado en ese spell de wowhead, al activar esto saca un aura parecida a una de los paladines, pero en este casi ya no saca el aura, ni tampoco dice que el spell este activado en los cuadritos que hay al lado del minimapa pero si tiene CD y también dice que lo active, pero en ningún momento muestra claramente que esta funcionando, rueda la imagen:
![wowscrnshot_070413_121407](https://f.cloud.github.com/assets/3613748/750806/dc6c540a-e4da-11e2-9387-e85f558c6765.jpg)

D) Disparos bugs: En este caso, los tipos de disparos que son Firme, de Cobra y de Puntería, en el caso de mi rama de talentos (Puntería) y en las de mis compañeros, la velocidad de canalizamiento o de lanzamiento de estas facultades es notoriamente lenta, en esta sección espero que confíen en las imágenes del cronometro, primero montare las imágenes del tiempo que dicen demorarse cada una de estas spells: 
![wowscrnshot_070413_121555](https://f.cloud.github.com/assets/3613748/750807/f93b60b2-e4da-11e2-9498-1695ed43473c.jpg)
![wowscrnshot_070413_121502](https://f.cloud.github.com/assets/3613748/750808/f9b53ff4-e4da-11e2-9755-1230ef792bba.jpg)
![wowscrnshot_070413_121604](https://f.cloud.github.com/assets/3613748/750809/f9d44a66-e4da-11e2-98b1-3bd4ed348d69.jpg)

y ahora las imágenes del verdadero tiempo que se tardaron, en un comentario de un compañero (Blacksipers) me dice que es como si se estuviese anulando el índice de celeridad y que junto con Miglent y Snick notan que están muy lentos estos disparos, pero lastimosamente no tengo la imagen de este comentario por que en esas el server se callo, las imágenes: 
![wowscrnshot_070413_121613](https://f.cloud.github.com/assets/3613748/750814/28a714f4-e4db-11e2-96be-305101783a8f.jpg)
![wowscrnshot_070413_121508](https://f.cloud.github.com/assets/3613748/750815/28b8a098-e4db-11e2-9355-0b41683a4111.jpg)
![wowscrnshot_070413_121535](https://f.cloud.github.com/assets/3613748/750816/28bcf31e-e4db-11e2-8051-57ebbe0a2fa9.jpg)

espero que se entienda bien y sepan que no estoy mintiendo con respecto al cronometro y se que para algunos la diferencia es de unos milisegundos, pero como dije, llevo buen tiempo como cazador y al lanzar estas facultades noto considerablemente la lentitud del lanzamiento del disparo, y no solo yo si no también Blacksnipers y Miglent. Para mayor corroboración, necesita ser probado por jugadores, gente con experiencia en cazadores y/o personal del staff.

Y hasta inclusive con el spell Fuego rápido y con su debido glifo : ( http://es.wowhead.com/spell=3045/fuego-rapido y Glifo de fuego rápido, aumenta la celeridad de fuego rápido un 8% (perdón es que no me aparecía en wowhead) ) se reduce su velocidad de disparo, que lamentablemente no tome imagen de el tiempo que mostraba Disparo firme en ese momento, pero me acuerdo bien que lo señale y decía 1.25 segundos y en la imagen a continuación muestra que se tardo lo mismo: 
![wowscrnshot_070413_121639](https://f.cloud.github.com/assets/3613748/750821/35c6adc0-e4db-11e2-8382-f2d806b835fe.jpg)

E) Bombardeo: Este no es un bug perjuicioso pero aun así lo reporto, y sucede que cuando ataco con cualquier otro spell que no sea Multidisparo este talento de la rama de talentos de puntería (valga la redundancia) http://es.wowhead.com/spell=35110/bombardeo se active viendo que claramente dice que requiere que sea un ataque de Multidisparo y que además no reduce el coste de enfoque de Multidisparo que dice en wowhead, rueda la imagen: 
![wowscrnshot_070413_121652](https://f.cloud.github.com/assets/3613748/750823/3fa79782-e4db-11e2-94ba-eccb5c267891.jpg)
 Posdata: Ignoren el cronometro, era el de una de las pruebas anteriores que deje pasar XD.

F) Camuflaje: Sencillamente no funciona, al ser activado no se vuelve invisible (o casi invisible) o mas bien camuflado, la imagen: 
![wowscrnshot_070413_121713](https://f.cloud.github.com/assets/3613748/750826/5e44502c-e4db-11e2-912e-989de015514e.jpg)

G) Disparo de Cobra: El otro bug en este disparo es que cuando se lanza no aumenta el tiempo de la Picadura de serpiente y para ello tengo varias imágenes y también el apoyo de Blacksnipers, ruedan las imágenes:
![wowscrnshot_070413_121751](https://f.cloud.github.com/assets/3613748/750828/7033f242-e4db-11e2-8ba3-6c88e1970c07.jpg)
![wowscrnshot_070413_121757](https://f.cloud.github.com/assets/3613748/750830/7097a06c-e4db-11e2-9ba6-70f652d475f1.jpg)
![wowscrnshot_070413_121801](https://f.cloud.github.com/assets/3613748/750829/70988590-e4db-11e2-9281-c7a118c6205c.jpg)

H) Disparo Firme: El otro bug en este otro disparo es que no genera el enfoque que dice que debería de generar (en mi caso y/o en el de los otros 9 de enfoque por disparo) y no me lo muestra en el registro de combate ni en la pantalla sabiendo que tengo activado en la interfaz que me muestre todo lo que me dan y lo que me quitan (alud, beneficios, perjuicios, daño, etc.), dos imágenes para esto: 
![wowscrnshot_070413_122229](https://f.cloud.github.com/assets/3613748/750838/86036c2e-e4db-11e2-832d-0aced2584dc5.jpg)
![wowscrnshot_070413_122235](https://f.cloud.github.com/assets/3613748/750839/86098c62-e4db-11e2-9f65-0f86b9b8e00a.jpg)

y otra imagen, aunque creo que no se necesita, para mostrar que este disparo si debe de generar enfoque:
![wowscrnshot_070413_122238](https://f.cloud.github.com/assets/3613748/750840/8fbb4232-e4db-11e2-9fed-a309aa6168a3.jpg)

Como soy Cazador familiarizado completamente y únicamente con la rama de talentos de Puntería los bugs presentados en las otras dos ramas (Supervivencia y Bestias) los desconozco por que no se bien como funcionan, pero para las de supervivencia le he pedido ayuda a Blacksnipers para que me corrobore y aporte mas bugs del cazador presentes después de la actualización (esto será como después de las 18:00 pm por que se fue a estudiar XD) pero según tengo entendido y lo que el y Miglent me dijeron es que Disparo explosivo y disparo de cobra están pegando demasiado poco (explosivo apenas quita 1k en total de daño y cobra no se bien del todo) y llegando a este tema, el daño de los cazadores también se vio seriamente reducido, pero como que solo en el de los Hordas, por que ayer en BG estuve combatiendo contra un Ali que ni era full sanguirario y tenia mas daño realizado que yo que soy casi full sañoso, así que pido una revisión por favor a todos estos temas y espero su pronta solución, gracias por la atención prestada.

Saludos, Darkstar.

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/34 , https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/84

Un saludo.

**Comment by Navalagamella** [comment]
El bug de la maestría también me pasa a mi y soy Chamán Mejora (y putea por que es el primero de mis atributos a capear y con este bug no te da el 8% maestría base) y también le pasa a un amigo que es warrior asi que, bug general.

**Comment by Hellythium** [comment]
I) Disparo de quimera: No me realiza curación alguna tal y como lo describe esta imagen 
![wowscrnshot_070413_151037](https://f.cloud.github.com/assets/3613748/751032/f85edcf4-e4e5-11e2-9802-45745c85b6f5.jpg)
lo que me debería curar por lo menos el 5% de mi salud máxima según esto http://es.wowhead.com/spell=53209/disparo-de-quimera en el nivel 85

**Comment by Hellythium** [comment]
J) Lanzador de Trampas: me da 50 puntos de enfoque al activarlo lo cual no debería de ser asi, y además te permite lanzar las trampas en una sola activación mas no como debiera de ser, lanzador - trampa, lanzador- trampa, lanzador- trampa, imágenes
![wowscrnshot_070413_152503](https://f.cloud.github.com/assets/3613748/751101/ceaa089a-e4e8-11e2-9d97-0e23569862d5.jpg)
![wowscrnshot_070413_152508](https://f.cloud.github.com/assets/3613748/751103/ceb236e6-e4e8-11e2-8ecc-b7adce9af410.jpg)
![wowscrnshot_070413_152512](https://f.cloud.github.com/assets/3613748/751104/ceb5916a-e4e8-11e2-91e9-ff20c03c7c89.jpg)
![wowscrnshot_070413_152516](https://f.cloud.github.com/assets/3613748/751102/ceace704-e4e8-11e2-8574-a365b89ba4fc.jpg)

:

**Comment by miglent** [comment]
Creo que coloque mi comentario en el lugar equivocado.
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1500

**Comment by miglent** [comment]
Ahora un par de bugs extras de puntería:

El talento "Ataca" y el talento "Maestro tirador" están bug:
![wowscrnshot_070413_180208](https://f.cloud.github.com/assets/4936022/751497/9091d914-e4fe-11e2-9fe1-3a59a983900e.jpg)
Se activan con ataques que no deberian...
![wowscrnshot_070413_175931](https://f.cloud.github.com/assets/4936022/751498/9d302572-e4fe-11e2-9614-72e9b3634949.jpg)
![wowscrnshot_070413_175933](https://f.cloud.github.com/assets/4936022/751499/a30e2782-e4fe-11e2-8828-8f5866be722b.jpg)
y maestro tirador no permite que disparo de puntería sea instantáneo.

El talento "disparo firme mejorado" no funciona, no se activa...

El talento "marcado para morir" no funciona, no pone la marca en el objetivo:

![wowscrnshot_070413_181142](https://f.cloud.github.com/assets/4936022/751503/386f939c-e4ff-11e2-9450-2deb996318e2.jpg)
![wowscrnshot_070413_181213](https://f.cloud.github.com/assets/4936022/751506/4b2d6dc4-e4ff-11e2-9b1b-36bf05b46b35.jpg)
![wowscrnshot_070413_181220](https://f.cloud.github.com/assets/4936022/751507/4df81e5a-e4ff-11e2-9f68-4b75f11d7c2b.jpg)

El talento "inmediatez" tampoco funciona:
![wowscrnshot_070413_181435](https://f.cloud.github.com/assets/4936022/751510/89778d4e-e4ff-11e2-89b9-6dbe075bb589.jpg)
![wowscrnshot_070413_181550](https://f.cloud.github.com/assets/4936022/751514/b184c9dc-e4ff-11e2-9480-8a6a3256c4ab.jpg)
Como se ve claramente en la segunda imagen acabo de usar separacion, y en el registro no aparece que se active inmediatez, ni tampoco tengo el buff al lado del minimapa...

El talento "picadura de serpiente mejorada" no funciona, no hace el golpe inicial que deberia:
![wowscrnshot_070413_182000](https://f.cloud.github.com/assets/4936022/751528/567c0022-e500-11e2-9423-73981b5cfbf7.jpg)
![wowscrnshot_070413_181956](https://f.cloud.github.com/assets/4936022/751529/645b99fa-e500-11e2-9580-cb17b0f7aa62.jpg)

La maestría de puntería (carcaj salvaje) no está funcionando, no lo lanza nunca, solicito a algún caza puntería con recount que coloque una captura del recount donde se vea que nunca aparece el daño de carcaj salvaje, es la única forma en que se me ocurre que se pueda demostrar.

Gracias por su atención.

**Comment by sacor16** [comment]
Hola sigo yo con el cazador supervivencia

Disparo explosivo 
Se me hace muy difícil conseguir datos en wowhead ya que este ha cambiado en MOP 
![disparo explosivo](https://f.cloud.github.com/assets/4944424/751533/884027c8-e500-11e2-9605-e299e81425ee.jpg)

me parece un daño excesivamente bajo para ser la spell principal de supervivencia

Flecha negra

http://es.wowhead.com/spell=3674/flecha-negra

![flecha negra](https://f.cloud.github.com/assets/4944424/751542/eb4dba56-e500-11e2-9b47-0c98d504b4b2.png)

su daño igual es muy bajo, no le afecta http://es.wowhead.com/spell=82833 ni http://es.wowhead.com/spell=76658

picadura de serpiente 

http://es.wowhead.com/spell=118253

![picadura de serpiente](https://f.cloud.github.com/assets/4944424/751545/26d8660c-e501-11e2-9ccb-d824b52f55a9.png)

segun wowhead hace la mitad de daño y no se ve afectado por http://es.wowhead.com/spell=82833 ni http://es.wowhead.com/spell=76658

Aspecto de halcón

http://es.wowhead.com/spell=13165/aspecto-del-halcon

![aspecto de halcon](https://f.cloud.github.com/assets/4944424/751548/5eb72be4-e501-11e2-887d-5b79962519f3.png)

como se puede ver no hay cambios y no ha sido afectado por http://es.wowhead.com/spell=82684

**Comment by Hellythium** [comment]
Otra mas, en Punteria, cuando matas a un enemigo que el color de los números de su nivel no es gris, no genera los 50pts de enfoque que debería, el talento es Recuperación rápida:
![wowscrnshot_070413_190706](https://f.cloud.github.com/assets/3613748/751616/6e4a9fb8-e507-11e2-8877-2d8c99e272f5.jpg)
que requiere Matanza rápida:
![wowscrnshot_070413_190807](https://f.cloud.github.com/assets/3613748/751618/81f66e98-e507-11e2-8ec0-03665e86728d.jpg)
y aquí muestro la imagen donde mato un NPC y no me da los 50 pts de enfoque:
![wowscrnshot_070413_190758](https://f.cloud.github.com/assets/3613748/751621/ab798016-e507-11e2-9e64-341daf16d8e1.jpg)

 Posdata: Creo que en su base de datos están cruzados unas cosas por que como mostré anteriormente el lanzador de trampas genera 50 pts de enfoque y esto no, solo es un parecer mio.

**Comment by ghost** [comment]
@Hellythium perdón por cerrar tu reporte u.u, si puedes por favor crear un reporte por cada bug sería mucho mejor, reportes así no los leeran, y tampoco fixearan.
