### ISSUE TITLE
[errores internos, mazmorras?] #132 en Templo Oscuro 25n + Ayuda estoy atascado

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1133]
Hola para comentar que entramos a esta mazmorra (Templo Oscuro http://es.wowhead.com/zone=3959), y justo en el area donde se pueden usar monturas antes de unas grandes escaleras, despues de haber matado unos 2 boss, me tiro el juego y me dio error #132, luego de eso reloguee y no veia algunos bichos, pero si a mis compañeros. Creo que quede en otra fase, y ellos si veian a lo que le pegaban.

Luego avanzamos por las escaleras y me saco de nuevo #132. Despues de eso intento reloguear y sin moverme me sale error y me cierra el juego :/.

![error132illidan](https://f.cloud.github.com/assets/4790547/918991/e344f01c-febf-11e2-9acf-ba8e9d31b6f8.JPG)

Dejo el log del error que tanto me sale en ese lugar.

https://mega.co.nz/#!MgFVzbxT!A12aMSdWiGjAOMykOgTEU3Gvvgk6aXZp9kSeallC-R4

Mi pj quedó atascado, me ayudan por favor?. Gracias

**Comment by efectokoleos** [comment]
no he podido reproducir tu error, puede ser que al haber varios enemigos en pantalla te diera error de la ram o la gráfica, tus personajes ya estan fuera de bt por lo tanto cierro

**Comment by lamaza** [comment]
Me lo ha sacado Joss de ese lugar, al final note que mi pj quedó bugeado en la estancia: Despues de tanto wow error seguia en raid,, aunque todos se habian ido XD. gracias =
