### ISSUE TITLE
[ERRORES INTERNOS] Comando /GINIVITE provoca wow error.

### ISSUE THREAD

**Issue by Xscorpio** [RoDNet/Bugtracker-Infinium-4.3.4#1135]
Hoy he intentado invitar a un pj a mi hermandad y en cuanto mando la invitacion, me saca de wow y muestra wow error.

**Comment by ghost** [comment]
No he usado nunca el comando, pero no será "/GINVITE" ? creo que te has equivocado al escribirlo.

Saludos

**Comment by ghost** [comment]
Ya esta reportado #988
