### ISSUE TITLE
[Campo de batalla] Ojo de tormenta

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1136]
Hola quiero reportar el siguiente fallo de esta bg.
Ojo de la Tormenta http://es.wowhead.com/zone=3820

En la cual la bandera del centro no se puede cojer.
No hay la posibilidad de darle click.

Desconozco la id de la propía.
Un saludo.

**Comment by efectokoleos** [comment]
fixed!
