### ISSUE TITLE
[Spell > Hunter] Mastery: Wild Quiver

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1137]
Hola quiero reportar la maestría del cazador puntería.
Maestría: Carcaj salvaje http://es.wowhead.com/spell=76659
Requiere Cazador (Puntería)
Requiere nivel 80
Otorga un 16% de probabilidad de que tus ataques a distancia activen al instante un ataque a distancia extra.

La cual está saltando más veces del porcentaje de maestría.
Y que a parte de saltar mas veces, cuando salta golpea doble.
Aquí unas imagenes.
![wowscrnshot_080613_210343](https://f.cloud.github.com/assets/3537253/919556/d7b7e220-fecb-11e2-9c12-cccb4f85ec46.jpg)
![wowscrnshot_080613_210336](https://f.cloud.github.com/assets/3537253/919555/d7b76b92-fecb-11e2-9013-b42d16f8cf62.jpg)

Como se puede ver en el registro de combate como el caza enemigo todas las veces que le salta la maestría entre ataques y doble.

Edito\* Añado Screen con el Registro de combate de la siguiente arena.
![wowscrnshot_080613_211637](https://f.cloud.github.com/assets/3537253/919599/d8397d34-fecc-11e2-9581-3c8fb7191fb3.jpg)

Un saludo.

**Comment by lamaza** [comment]
Asman y yo si deciamos eso haha. Buen reporte !

**Comment by searum** [comment]
a mi me parece que va bien...
