### ISSUE TITLE
[DK] Bugs Varios de Especialización Sangre

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#114]
Golpe Letal (http://es.wowhead.com/spell=49998): No cura el mínimo del 7%/No activa el escudo de sangre (http://es.wowhead.com/spell=77513). PERO, cura de 40k a 45k de vida con fiebre de escarcha (http://es.wowhead.com/spell=59921) o peste de sangre (http://es.wowhead.com/spell=59879) sobre el objetivo, curando un total de casi 90k con las 2 Fiebres.

Sangre Vampírica (http://es.wowhead.com/spell=55233): Funciona el bonus de sanación pero no funciona el bonus de salud.

Parásito de sangre (http://es.wowhead.com/spell=49542): El gusano no sana cuando desaparece.

Escarlatina (http://es.wowhead.com/spell=81132): Cada vez que logeo al DK aparece, pero se quita a los 30s.

Mas tade edito si vuelvo a encontrar mas.

Gracias y hasta luego.

**Comment by crowel** [comment]
Aqui hay otro reporte anterior a este.
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1
Continuar en este reporte.

**Comment by ghost** [comment]
@Rhoemer90 lo de golpe letal creo que ya va, por otra parte, si pudieras poner cada bug en un reporte a parte, así no lo leeran u.u.
