### ISSUE TITLE
Funcionalidades/animaciones del pj

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1141]
Los personajes adoptan las formas permanentemente hasta el próximo relogeo. Por ejemplo, si hago /dance, mi pj se queda haciendo eso eternamente, aunque monte en montura o me ponga a comer, mi pj seguirá de pie bailando y comiendo. Actualmente, el pj deja de bailar si escribo cualquier cosa por /say, ya que eso genera otra animación distinta que elimina la anterior.

**Comment by Mhryel** [comment]
Continuamos desde https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/494

**Comment by Dekadencee** [comment]
Fixed
