### ISSUE TITLE
[Mago] Absorción de encantador (ID: 44396)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1143]
Estoy en fire desde que creé el pj, nunca he usado la rama arcana y, sin embargo, al absorber daño con mi resguardo de mago, me salta Absorción de encantador, que es un talento de la rama arcana...

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/860 No está arreglado, sigue saltando absorción de encantador.

Pasos para reproducirlo: 
1. Duelear contra chamán elemental,
2. Usar con el mago "resguardo de mago" y "escudo de maná (1463)",
3. Que el chami lance hechizos de daño fuego, ver como salta el buff.

Nota (20/12/13): No da poder con hechizos a pesar de salir el bufo.

**Comment by searum** [comment]
Y las ids? porque en el otro reporte tampoco hay ids, siempre me tengo que buscar la vida y perder tiempo en tonterias asi... Tardais 2 minutos en poneros el idtip que es un addon en el cual os salen las ids de items/spells/auras...

**Comment by searum** [comment]
este fallo continua? :S

**Comment by ghost** [comment]
Sí @searum. Hoy testeo, ya que anoche fixeaste escudo de maná, a ver si sigue.

**Comment by ghost** [comment]
@searum  Sigue, ahora salta siempre.

**Comment by searum** [comment]
creo que ya lo tengo fix, pero no lo he subido todavia asi que no deis el coñazo, si mañana sigue igual entonces avisa por aqui y reabro el issue.

**Comment by ghost** [comment]
Nota: No da poder con hechizos a pesar de salir el bufo.
