### ISSUE TITLE
[hechizos] Galopada Salvaje Huargen

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1144]
http://es.wowhead.com/spell=87840

Quiero decir, que en el caza low que me hice desde que estamos en 4.3.4 para probar la zona de los huargen y hechizos básicos, este hechizo no funciona, mi pj no hace nada y el hechizo no se activa al darle click. ESe spell me lo dió un dia Alanyss si mal no recuerdo, ya que le pedí qu eme sacara de la zona incial y me llevara a Ventormenta. 

Gracias.

**Comment by crowel** [comment]
Este hechizo requiere que aprendas la equitación a level 20 como la montura.
Nose a que nivel estaras tu actualmente.
Un saludo.

**Comment by lamaza** [comment]
osea que no deberia tener tal hechizo XD, era un lv 19 hehe. Gracias.
