### ISSUE TITLE
Bugs Druida Equilibrio - Segunda parte

### ISSUE THREAD

**Issue by edwyr** [RoDNet/Bugtracker-Infinium-4.3.4#1146]
Como ya hice en un antiguo post, os pongo los fallos que he seguido encontrando en el druida Equilibrio, siempre intentando explicaroslo mas o menos bien ;).

1º.- El talento "Euforia" (http://es.wowhead.com/spell=81062) funciona a medias, la parte que aumenta el % de posibilidades de que duplique la energia solar o lunar funciona perfecto, pero la segunda parte que dice que cuando llego a un eclipse recupero un 16% de mi mana máximo, funciona... pero mal, con mi maná he hecho los calculos y deberia de recuperar 19k de mana, y estoy recuperando 4 - 5k.

2º.- Los eclipses no van bien: aquí he encontrado dos fallos, el primero es que cuando llegas a 100 puntos deberia de activar el eclipse, pero en cambio se necesita otro ataque mas para que se active el eclipse correspondiente aclarandolo, aunque llegues a 100 puntos necesitas otro ataque mas para que el eclipse se active; el segundo fallo consiste en que el eclipse se queda "pillao", es decir, si te has quedado a mitad de un eclipse o en un eclipse y acabas el combate, se te queda el eclipse o la barrita donde se quedó "pillao" antes sin opción a poder seguir cambiando de un eclipse a otro, a noser que mueras que por lo que he visto es la única opción de que se quite.

3º.- El talento "Gracia de la naturaleza"(http://es.wowhead.com/spell=16886) funciona mal, este talento tiene dos partes: la primera hace que aumente tu celeridad 15% despues de lanzar fuego lunar, enjambre de insectos o recrecimiento durante 15 seg y teniendo un cd de 1 min, hasta ahí todo bien, pero la segunda parte dice que al llegar a un eclipse el cd de "Gracia de la naturaleza" se reinicia pudiendo así volver a tirar fuego lunar, enjambre de insectos o recrecimiento y que vuelva a saltar, pero no es así, cuando llegas al eclipse "Gracia de la naturaleza" no se reinicia, con lo que solo puedes activar 1 cada minuto, algo que hace perder mucho dps.

4º.- La spell "Fuerza de la naturaleza" (antárboles)(http://es.wowhead.com/spell=106737) hacen que los guerreros al matar a los arboles ganen "Ataque de la victoria" (http://es.wowhead.com/spell=34428) pudiendo así curarse casi por completo en arenas, bgs, etc..

5º.- La spell "Fuego lunar" (http://es.wowhead.com/spell=8921) está pegando alrededor de un 35%-40% de lo que deberia segun DrDamage, se que este addon es orientativo pero esa diferencia me parece algo excesiva, pero aun así deberiais de comprobarlo vosotros.

6º.- La spell "Fuego solar" (fuego lunar en eclipse solar) (http://es.wowhead.com/spell=93402) está pegando alrededor de un 50% de lo que deberia segun DrDamage, ya se que este addon es orientativo pero un 50% me parece excesivo, pero aun así deberiais de comprobarlo vosotros.

7º.- Por último una cosilla que ya reporté en el antiguo post pero sigue sin funcionar, y es el reinicio del cd de "Lluvia de estrellas" (http://es.wowhead.com/spell=48505) al llegar a cualquier eclipse, esto es muy importante ya que la base del daño del druida Equilibrio es esta spell .

Demomento no he encontrado mas, y si lo hago os los pondré como hasta ahora con el maximo detalle posible, espero que podais arreglarlo todo :) un saludo y gracias por la rapida correccion de la mayorias de cosas del otro post, un gran trabajo.

**Comment by crowel** [comment]
Hola edwyr me parece que no te fijaste en el comentario que te dejo @searum  en tu otro reporte, en la parte 1.

De momento cierro porque hay otro reporte del 2º fallo y todo lo demas lo he arreglado. <strong>"Para proximas veces trata de poner un issue por bug ! gracias"</strong>

Sino te importa crea los reportes individualmente para facilitar la reparación ya que es dificil que se reparen 10 de golpe estando en el mismo issue.
Lo dejo abierto unas horas mientras lo cambias, sino te importa poner de uno en uno.
Un saludo.

**Comment by edwyr** [comment]
Como no he entendido muy bien tu respuesta, y nose si has dicho que ya esta todo arreglado o que lo vuelva a poner por separado todo pues los pondré por separados todos excepto el 2º que ya esta reportado

**Comment by crowel** [comment]
No, siento que me malinterpretaras.
Lo que me queria referir es que Searum en tu otro reporte tras arreglarlo te escribio "Para proximas veces trata de poner un issue por bug! gracias"

Esto es lo que trataba de explicarte ahora, el poner cada uno individualmente ^^

**Comment by edwyr** [comment]
ah vale ;), esque la verdad no leí lo que me puso y por eso puse este así pero apartir de ahora ya los pondré bien, gracias.

**Comment by crowel** [comment]
Cierro Issue un saludo! :)
