### ISSUE TITLE
[Errores internos, Objetos] Cofre Arena Gurubashi

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1147]
Buenas, quisiera avisar, que el cofre http://www.wowhead.com/object=179697 que debe salir en medio de la Arena Gurubashi, el cual aparece cada 3 horas exactamente desde el momento en que es abierto y queda vacío, no esta apareciendo.

El objeto que deberia dar (entre otros) es http://www.wowhead.com/item=18706
pero eso es ya otra cuestión, lo importante es que aparezca el cofre, luego se dirá si lotea bien. Gracias.

**Comment by efectokoleos** [comment]
arreglado ( 1 año despues.. xd)
