### ISSUE TITLE
[hechizos] piroexplosion Mago bug? consulta

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1148]
No entiendo este daño, se que parezco loco reportando todo daño pero es que... no me conformo con lo que veo.

El pj que me lo lanzó dice que esta equipado con tier11 heroico full.

![wowscrnshot_080613_192122](https://f.cloud.github.com/assets/4790547/921511/1ab948b8-fefc-11e2-95c4-3964a4918205.jpg)

http://www.wowhead.com/spell=36277
http://www.wowdb.com/spells/11366-pyroblast

Me gustaria que me dijeran si es normal ese daño, para hacerme a la idea XD. Gracias

**Comment by ghost** [comment]
26k de prioexplosion critico? a mi me parece muy normal.

**Comment by searum** [comment]
al final voy a sancionar por reportar cosas asi... esto no es para /quejasylloros esto es para reportar bugs reales.
