### ISSUE TITLE
Respawn en marjar revolcafango

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#115]
Buenas 
En una mision [Los Desertores] el respawn de los enemigos esta muy baja ya que no pasan 30 seg y ya aparecen denuevo porfavor revisarlo cundo podais, 

Gracias

**Comment by redneo** [comment]
Me podrias decir el enlace de wowhead de los enemigos?

**Comment by frustrix** [comment]
Es tan simple como poner en google:    "wowhead Los desertore"

el problema esta en que matas a los de alrededor del que tienes que sacarle la informacion y los enemigos de alrededor aparecen y mueres porque no das a basto a sacar la informacion y seguir matando al resto
http://es.wowhead.com/quest=27287/los-desertores
