### ISSUE TITLE
Talento Euforia Druida equilibrio

### ISSUE THREAD

**Issue by edwyr** [RoDNet/Bugtracker-Infinium-4.3.4#1151]
El talento "Euforia" (http://es.wowhead.com/spell=81062) funciona a medias, la parte que aumenta el % de posibilidades de que duplique la energia solar o lunar funciona perfecto, pero la segunda parte que dice que cuando llego a un eclipse recupero un 16% de mi mana máximo, funciona... pero mal, con mi maná he hecho los calculos y deberia de recuperar 19k de mana, y estoy recuperando 4 - 5k.

Gracias y un saludo.

**Comment by edwyr** [comment]
por lo menos decir si lo vais a arreglar o no... porfavor k lleva aki 23 dias puesto

**Comment by Kiritoo** [comment]
¿Que tiene que ver que lleve 23 días para decir si se va a arreglar o no?
Hay muchos fallos como comprenderas le puede tocar a uno o otro, al igual que los que tengan prioridad se repararan antes.
Si se reporta en el bugtracker se reparara antes o despues, si quieres colaborar reparalo y envia el arreglo sino te tocara esperar hasta que se arregle, espero que está fuera la contestación que buscabas.

**Comment by edwyr** [comment]
No era lo que queria escuchar, pero si era lo que me esperaba

**Comment by searum** [comment]
Como si lleva 8 meses en el bugtracker, cuando se pueda/quiera se reparara.. Que son esas exigencias? cada dia alucino mas con vosotros..

**Comment by searum** [comment]
segun mis calculos esta dando el mana perfecto.
