### ISSUE TITLE
Talento Gracia de la naturaleza Druida Equilibrio

### ISSUE THREAD

**Issue by edwyr** [RoDNet/Bugtracker-Infinium-4.3.4#1152]
El talento "Gracia de la naturaleza"(http://es.wowhead.com/spell=16886) funciona mal, este talento tiene dos partes: la primera hace que aumente tu celeridad 15% despues de lanzar fuego lunar, enjambre de insectos o recrecimiento durante 15 seg y teniendo un cd de 1 min, hasta ahí todo bien, pero la segunda parte dice que al llegar a un eclipse el cd de "Gracia de la naturaleza" se reinicia pudiendo así volver a tirar fuego lunar, enjambre de insectos o recrecimiento y que vuelva a saltar, pero no es así, cuando llegas al eclipse "Gracia de la naturaleza" no se reinicia, con lo que solo puedes activar 1 cada minuto, algo que hace perder mucho dps.

Gracias y un saludo.

**Comment by edwyr** [comment]
a ver si podeis arreglarlo porfavor que el pollo esta hecho un poco polvo..

**Comment by searum** [comment]
si funciona.. y eso de que esta tan hecho polvo.. creo que lo he dejado bastante decente..
