### ISSUE TITLE
Antarboles activan ataque de la victoria

### ISSUE THREAD

**Issue by edwyr** [RoDNet/Bugtracker-Infinium-4.3.4#1153]
La spell "Fuerza de la naturaleza" (antárboles)(http://es.wowhead.com/spell=106737) hacen que los guerreros al matar a los arboles ganen "Ataque de la victoria" (http://es.wowhead.com/spell=34428) pudiendo así curarse casi por completo en arenas, bgs, etc..

**Comment by ghost** [comment]
Se está activando tanto con los treants  como con las copias del mago, la trampa de serpientes de los cazas etc.

**Comment by crowel** [comment]
Solo se puede usar durante los siguientes 20 s después de matar a un enemigo que aporte experiencia u honor.

Solo al matar jugadores o npcs que aporten experiencía.

Las copías no deben activarlo.

Un saludo.

**Comment by searum** [comment]
fix pero confirmarmelo
