### ISSUE TITLE
Fuego solar Druida Equilibrio

### ISSUE THREAD

**Issue by edwyr** [RoDNet/Bugtracker-Infinium-4.3.4#1155]
La spell "Fuego solar" (fuego lunar en eclipse solar) (http://es.wowhead.com/spell=93402) está pegando alrededor de un 50% de lo que deberia segun DrDamage, ya se que este addon es orientativo pero un 50% me parece excesivo, pero aun así deberiais de comprobarlo vosotros.

Gracias y un saludo.

**Comment by redneo** [comment]
Creo que arreglado, dime si el dot hace daño de más
