### ISSUE TITLE
Enjambre de insectos Druida Equilibrio

### ISSUE THREAD

**Issue by edwyr** [RoDNet/Bugtracker-Infinium-4.3.4#1162]
Ya que os estoy dando tanta vara con el druida, tambien os pongo los bugs beneficiosos pa dejarlo apunto, y resulta que enjambre de insectos está pegando alrededor de un 28% mas segun el DrDamage, como siempre es mejor que lo mireis vosotros. Un ejemplo, con mi equiipo y mis stats está pegando 2,5k por tick normal y deberia 1,8-1,9k.

Un saludo.

**Comment by ghost** [comment]
ID: 5570
