### ISSUE TITLE
[mazmorras,errores internos, Npjs] Foso de Saron 5n

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1163]
Buen dia.
A ver si me entienden la historia:

Primero hice Solo Forja de Almas (en 5n), y pase por ese portal al final de la mazmorra, a Foso de Saron.

http://es.wowhead.com/zone=4809 (forja)
http://es.wowhead.com/zone=4813 (foso)

Estando  ya en Foso de Saron, tome la quest de liberar esclavos y matar a Gorgalok(http://es.wowhead.com/quest=24498). Completé los esclavos, maté al boss gusano, y justo cuando llegue a las escalas grandes para subir a Gorgalok, había un bicho que me dejo un buff el cual esta pegando demasiado.

Clamacielos Ymirjar http://es.wowhead.com/npc=31260
Debuff Golpe Glacial  http://es.wowhead.com/spell=70292#english-comments

Pues no pensé que me mataría pero si morí debido al debuff que no se quitó. Después de estar muerto, liberé y salí en pájaro volador a buscar mi cuerpo dentro de la estancia Foso de Saron, y oh sorpresa cuando llegué y me dice que mi cuerpo no estaba allí, también me salia lo mismo en Forja de Almas. Hoy en día le echo siempre la culpa de cosas así a las fases XD.

Luego de no poder revivir así, lo hice con Dolencia del Ángel, y decidí ir a Foso de Sarón y ya no me deja entrar, no sale ningún mensaje ni nada, solo no entra el pj a la mazmorra.

Entonces este reporte lo quiero aprovechar para que miren por favor la imposibilidad de revivir y entrar a foso de sarón de nuevo, y si no es mucha molestia el daño del a habilidad debuff mencionada.

Resumen: No se puede entrar a foso de saron, debido a  que el portal de entrada a la mazmorra parece no servir de nada. Volví a hacer forja de almas en 5h (entre 2) y pudimos entrar a foso de saron por medio del portal que sale al final de la mazmorra.

![wowscrnshot_080713_190346](https://f.cloud.github.com/assets/4790547/928686/0d6e2526-ffbe-11e2-8a84-d49db8cb0c8b.jpg)

Según 1 comentario en wowhead, parece que el destino es que ese spell te mate XD.

![wowscrnshot_080713_161324](https://f.cloud.github.com/assets/4790547/928283/00f6ceee-ffb2-11e2-8fcc-7c8c018c6b5f.jpg)
![wowscrnshot_080713_161337](https://f.cloud.github.com/assets/4790547/928284/01047e04-ffb2-11e2-99b1-54f0a84a81e5.jpg)
![wowscrnshot_080713_161327](https://f.cloud.github.com/assets/4790547/928285/010e576c-ffb2-11e2-8f36-781462534b3e.jpg)

**Comment by ghost** [comment]
Una vez que acabas con el mob, come.
Quiza te tome 1 o 2 bocados, pero el spell se sale.
Saludos!

**Comment by lamaza** [comment]
Si, pero 19mil para mi es soportable, imaginate en lv 80 si no estan al tanto. No entiendo ese daño pero bueno...

**Comment by ghost** [comment]
Creo que el daño de esa spell es proporcional a la vida del personaje. Voy a tener que volver a la mazmo para confirmar esto porque no me acuerdo XD

**Comment by lamaza** [comment]
Bueno pero sea como sea, el bug mas sensible es que no se puede entrar a foso por el portal o rastrillo, per osi se puede hacer si vas desde forja de almas, ya la hice ayer con los 3 boss =).
