### ISSUE TITLE
ICC - Batalla Final (Arthas)

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#1166]
Hola, en ICC al tomar el ultimo teleport para la batalla final contra el rey exanime, 

![wowscrnshot_080713_191224](https://f.cloud.github.com/assets/4895839/928717/631e1872-ffbf-11e2-86c1-b15a6e9e2893.jpg)

todos los integrantes caen al vacio

![wowscrnshot_080713_191228](https://f.cloud.github.com/assets/4895839/928719/763a04de-ffbf-11e2-97c7-d3781d77c024.jpg)

![wowscrnshot_080713_191230](https://f.cloud.github.com/assets/4895839/928724/81e5efd2-ffbf-11e2-83fa-a11b3f5e9134.jpg)

Ayuda pls!!

**Comment by efectokoleos** [comment]
se arreglara en el proximo reinicio
