### ISSUE TITLE
[Mobs] Señor de la Plaga Tyrannus

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1167]
Buenas Devs.

http://es.wowhead.com/npc=36658

Las habilidades y todo, de este Jefe de Foso de Sarón estan ok, y su dragon tambien esta muy bien. El único problema es que no pudimos targetear a Tyranus, por ello no pudimos continuar la prueba de las 3 mazmo de corona de hielo (Forja-Foso-Camaras):

![wowscrnshot_080713_183930](https://f.cloud.github.com/assets/4790547/928722/78046778-ffbf-11e2-9b42-a3197e709113.jpg)
![wowscrnshot_080713_184007](https://f.cloud.github.com/assets/4790547/928723/781b8958-ffbf-11e2-93d5-67b6c9bda7cf.jpg)

El boss nos ataca, pero solo es un dibujo 3d que nos persigue XD, esta mas allá de nuestro poder y auras XD.

**Comment by efectokoleos** [comment]
fixed, por cierto camaras me parece k no funcionan falta meter el script pero este boss ya esta arreglado :D
