### ISSUE TITLE
[Misión]Desprestigiando a los desertores

### ISSUE THREAD

**Issue by Santaclaws** [RoDNet/Bugtracker-Infinium-4.3.4#1169]
Enlace: http://es.wowhead.com/quest=27212
Problema: Al hablar con los PNJs que deben cumplirte los objetivos no te cuentan.

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/553
Ya estaba reportado 3 veces con está.
Cierro Issue.
