### ISSUE TITLE
[Misión]Limpiar la Colina de las Brujas

### ISSUE THREAD

**Issue by Santaclaws** [RoDNet/Bugtracker-Infinium-4.3.4#1170]
Enlace: http://es.wowhead.com/quest=27190
Problema: No reconoce posición alguna en el muelle ni en los alrededores donde poder utilizar la antorcha ruinabruja para activar la quest.

**Comment by redneo** [comment]
arreglada

**Comment by erdricklol** [comment]
Ami no me va que raro.
