### ISSUE TITLE
[Misión]¡Arrasa el Puesto Cuernoatroz!

### ISSUE THREAD

**Issue by Santaclaws** [RoDNet/Bugtracker-Infinium-4.3.4#1172]
Enlace: http://es.wowhead.com/quest=27296/
Problema: Al usar la antorcha en las tiendas no te las reconoce como objetivos para su uso y no puedes quemarlas.

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/559?source=cc
Ya reportardo
