### ISSUE TITLE
Mision bug (Colinas Pardas) Plaga chamuscada

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1174]
http://es.wowhead.com/quest=12029/plaga-chamuscada
Lado: Ambos
Empieza: Mack Fearsen
Termina: Mack Fearsen
El grog no afecta a los trolls
![wowscrnshot_080813_134959](https://f.cloud.github.com/assets/5048096/931041/c917be24-0020-11e3-9632-ce42df051450.jpg)

**Comment by crowel** [comment]
Hola así es.
![wowscrnshot_080913_031256](https://f.cloud.github.com/assets/3537253/975984/11d7f17a-0683-11e3-86c3-591517c9123c.jpg)
![wowscrnshot_080913_031303](https://f.cloud.github.com/assets/3537253/975988/1f884c7a-0683-11e3-8f6c-ab1ff0f541ec.jpg)

Saludos.

**Comment by efectokoleos** [comment]
arreglada en el proximo reinicio
