### ISSUE TITLE
[Sacerdote] Glifo de Rezo de Alivio (42417) 

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1175]
Buenos días.

El glifo en cuestión debería hacer que la primer carga de Rezo de Alivio (33076) http://es.wowhead.com/spell=33076/rezo-de-alivio sanara un 60% más de lo normal (las otras 4 cargas sin embargo sanarán lo mismo que sin glifo)

El valor de sanación es el correcto en todas las cargas, sin embargo la primera carga no está dando el 60% extra de sanación que debería dar al tener el glifo puesto.

He sacado los números de spells del "idtip", es la primera vez que lo uso y no sé si habré puesto los números correctamente.

Gracias.

**Comment by efectokoleos** [comment]
arreglado falta compilar
