### ISSUE TITLE
No tientes a la suerte - TUNDRA BOREAL

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.3.4#118]
http://es.wowhead.com/quest=11913 <<<< No tientes a la suerte
http://es.wowhead.com/npc=26085 <<< EMPIEZA - TERMINA

![wowscrnshot_070413_123104](https://f.cloud.github.com/assets/2059256/751096/bf7ce0d6-e4e8-11e2-8532-12ba606f7004.jpg)

Ahi estan pero no te cuenta cuado les lanzas el fogonazo xD con la antorcha. No pasa nada no cuentan >.<

**Comment by redneo** [comment]
fixed
