### ISSUE TITLE
[ Warrior > Improved Hamstring ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#1182]
Seccionar mejorado: 
http://cata.openwow.com/spell=12668
http://www.wowwiki.com/Improved_Hamstring

Seccionar: http://es.wowhead.com/spell=1715

When reapplying Hamstring, you immobilize the target for 5 sec. This effect cannot occur more than once every 30 sec. In addition, reduces the global cooldown of your Hamstring by 0.5 sec

Bug: Al primer Seccionar te ancla al suelo, en vez de ser al 2º . Revisar el Internal CD de 30 sec, ya que creo que no se cumple.

**Comment by redneo** [comment]
Metido CD de 30 segundos a ambos puntos de talentos.
