### ISSUE TITLE
Misión: Éxodo

### ISSUE THREAD

**Issue by Anubis16** [RoDNet/Bugtracker-Infinium-4.3.4#1184]
Según la misión debo de coger un carruaje, pero parece ser que esta bug, me monto y no se mueve, y tampoco puedo bajarme al menos que me salga del juego. Gracias de antemano

**Comment by crowel** [comment]
Porfavor añade el enlace de la misión.
Un saludo.

**Comment by Anubis16** [comment]
http://es.wowhead.com/quest=24438/exodo

**Comment by redneo** [comment]
arreglada!
