### ISSUE TITLE
Misiones en general

### ISSUE THREAD

**Issue by GReaperCT** [RoDNet/Bugtracker-Infinium-4.3.4#1186]
En todas las misiones, en la guia de ayuda a la derecha, sale tanto el objetivo de la mision, y que ya esta completada y que tienes que volver

**Comment by lamaza** [comment]
Esto no es manera de reportar algo, no dice absolutamente nada. La forma es:

[Mision] XXXXXXXX

Reporto que tal mision falla por esto y lo otro.

-ID de la mision (sacada de wowhead por ejemplo, entre otras wow DB)
-Imagenes
-Despedida

Espero te sirva y aprendas =), bye.

**Comment by GReaperCT** [comment]
ok muchas gracias, y perdona esk soy nuevo en estas cosas de foro

Date: Fri, 9 Aug 2013 07:59:55 -0700
