### ISSUE TITLE
[Paladin] Mision: No temeras peligro alguno

### ISSUE THREAD

**Issue by GReaperCT** [RoDNet/Bugtracker-Infinium-4.3.4#1187]
No deja curar a la gente con el libro que te da el hermano paxton.

**Comment by crowel** [comment]
Enlaces porfavor de la mision o no se podrá arreglar.
Saludos.

**Comment by redneo** [comment]
si, pq en wowhead no me aparece.

**Comment by crowel** [comment]
http://es.wowhead.com/npc=951
GReaperCT di cual de estas es la que tienes mal ya que se repararon quizás alguna quedo sin hacer.
Un saludo.

**Comment by GReaperCT** [comment]
Es esta: http://es.wowhead.com/quest=28809

La que te da como recompensa "Jubon de cazador de lobos" 

Muchas gracias por todo y perdonar las molestis de mi falta de experiencia. Un Saludo!!

**Comment by Kiritoo** [comment]
Vale el problema esta en los npcs que estan mal, 50047 no se les puede hacer nada se arreglaran lo antes posible.
Un saludo.

**Comment by Kiritoo** [comment]
Fix
