### ISSUE TITLE
[Mago] bug de Congelacion profunda encontrado

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1188]
ya muchos magos han notado que hacen congelacion profunda sin usarlo o ser talento frost bueno me puse a testear y encontre la posible causa

todo es culpa del talento Impacto ID:12357 
le explico un poco el talento: hace que explosion de fuego aturdar a los enemigos 
bueno el caso es que cuando el enemigo esta inmune por filotormenta o entereza ligada o cualquier otro skill el stun de explosion de fuego pasa a hacer congelacion profunda haciendo daño alto dependiendo del equipo del jugador he visto unos 21k por hay

en resumen usar explosion de fuego teniendo el talento impacto activado y si el objetivo esta inmune a los stun pasa a hacer congelacion profunda

en la imagen podran ver un dk usando entereza ligada que lo hace inmune al stun y el mago usando explosion de fuego en el registro sale congelacion profunda 
![wowscrnshot_080813_195652](https://f.cloud.github.com/assets/3101842/935655/580a35fc-008b-11e3-9412-baa8e153a323.jpg)

**Comment by ghost** [comment]
Es extraño...y estás seguro de que realmente hace ese daño y no es cosa del combat log? Yo se lo achacaba al daño directo de Bomba Viva, el del último tick.

Aquí mi post de esto mismo de hace 1 mes: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/448

**Comment by F4NT4SM4** [comment]
No es cosa de combat log
es el stun de explosion de fuego actua como congelacion profunda si el enemigo esta inmune al stun hace el daño de congelacion profunda me han dado 21k y yo teniendo 3800 temple 
ese mago apenas ta sanguinario por eso no pega tanto
