### ISSUE TITLE
Bug's, al menos en MI cazador.

### ISSUE THREAD

**Issue by Eralion** [RoDNet/Bugtracker-Infinium-4.3.4#1189]
Al momento de querer abandonar para siempre una pet, y al darle click al cartelito de "Aceptar", la mascota desaparece, pero al querer usar "Domesticar Bestia", no me deja domar una nueva pet, reviso el poder que invoca a las pets al lado del jugador, y aun estaba la bestia que supuesta-mente ya había abandonado, no importa cuantas veces le de a abandonar y acepte hacerlo, la pet no se va, ninguna de las que quiero abandonar, y puedo caminar sobre el agua ._. solo paso como si nada y envés de nadar camina como si, estuviera en la tierra (tengo la carpeta cache borrada).

**Comment by searum** [comment]
Pon un ticket ingame y te atiendo a ver si podemos arreglar ese fallo
