### ISSUE TITLE
Joyeria

### ISSUE THREAD

**Issue by sherik12** [RoDNet/Bugtracker-Infinium-4.3.4#119]
La mision diaria no funciona, se hacen los tres jaspes dentados y los cuenta, pero no cuenta los jaspe dentado cortado. No es una receta distinta, solo es que tienes que ser vos quien hagas los jaspe, como las recetas de cocina.
http://es.wowhead.com/quest=25155/las-ogrozonianas-estan-de-humor

**Comment by sherik12** [comment]
La mision un regalo para lila presenta los mismos problemas xD
http://es.wowhead.com/quest=25154/un-regalo-para-lila

**Comment by sherik12** [comment]
Jajaja nunca especifico xD

**Comment by sherik12** [comment]
Hice la mision http://es.wowhead.com/quest=25156.
Yo tenia una muestra de ilustre joyero. La mision me dio 100 muestras, quede con 101, normalmente deberia dar solo unas, deberia haber quedado con 2 muestras xD

**Comment by ghost** [comment]
Esto ya esta arreglado tengo entendido.

**Comment by crowel** [comment]
Pues no, no lo está.

**Comment by ghost** [comment]
@crowel del lado de la horda ya lo probe y funcionan, del lado de la alianza lo has probado?, lo reabro entonces.

**Comment by crowel** [comment]
Tienes razón la que no funciona es la de las piedras nocturnas intemporales, mañana la reporto.
Un saludo, buenas noches^^.

**Comment by ghost** [comment]
Gracias, cierro entonces :P
