### ISSUE TITLE
[Guerrero] Heridas Profundas

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1190]
ID: 12867

Mis golpes criticos deberian de hacer sangrar al enemigo e infligir un 48% de mi daño medio de arma cuerpo a cuerpo

El problema es el daño esta haciendo muy poco 415 cada tik  y segun mi Drdamage deberia de hacer 1073 por tik
![wowscrnshot_080913_030020](https://f.cloud.github.com/assets/3101842/936848/8c25afd0-00c5-11e3-9b08-23f15337205f.jpg)

ya se que no me debo confiar mucho en Drdamage pero me parece muy poco el daño de cada tik

**Comment by searum** [comment]
fix
