### ISSUE TITLE
Puntos de justicia

### ISSUE THREAD

**Issue by kirgar** [RoDNet/Bugtracker-Infinium-4.3.4#1196]
Hoy al hacer una mazmorra matamos 2 bosses y ninguno de ellos dieron puntos de justicia pero rolear el loot si que se pudo.
<a href="http://www.subirimagenes.net/i/130809073333160579.jpg" target="_blank" title="subir imagen"><img src="http://sia1.subirimagenes.net/img/2013/08/09/mini_130809073333160579.jpg" border="0" alt="subir imagenes" /></a>

**Comment by Kiritoo** [comment]
Hola podrías poner los links de los dos bosses que no dieron los puntos para comprobarlo.
Gracias.

**Comment by kirgar** [comment]
El 1º y 2º boss de rocanegra http://es.wowhead.com/npc=39665, http://es.wowhead.com/npc=39679

**Comment by efectokoleos** [comment]
fixed
