### ISSUE TITLE
[DK] Sangre del Norte

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1197]
ID: http://es.wowhead.com/spell=54637/sangre-del-norte

Transforma las runas de sangre en runa de muerte (las runas de muerte cuenta como runa de sangre, de escarcha y profano) Permanentemente

Bien si hace eso se mantienen las runas de muerte pero el problema es que a ir a bg o teletrasportarme a otro sitio el talento deja de funcionar las runas de muerte se vuelven runas de sangre denuevo.

visualmente estan como runas de muerte solo visual pero no el efecto...

**Comment by searum** [comment]
fix
