### ISSUE TITLE
[mazmorra] ICC sobredaño

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1198]
Buenas, despues de empezar la pelea con el Rey Exanime, yo por lo menos note daños que no dejarian pasarla XD.

![wowscrnshot_080913_132848](https://f.cloud.github.com/assets/4790547/940017/468b28da-0122-11e3-93e6-38a8562ae111.jpg)

http://es.wowhead.com/npc=37698#english-comments Dice que debe pegar entre 8-10k a alguien medio armado.

![wowscrnshot_080913_132830](https://f.cloud.github.com/assets/4790547/940018/46adb094-0122-11e3-833a-ece6885bd7f3.jpg)

Esto dice que 50k....  http://es.wowhead.com/spell=70337#english-comments

**Comment by lamaza** [comment]
Según esta guia, la peste necrótica pega 10k.

http://todowow.com/ciudadela-jefes/lich-king-rey-lich-rey-exanime/

**Comment by SherBlader** [comment]
ICC es una banda

**Comment by efectokoleos** [comment]
la spell es así, en cuanto te la pone tienes k acercarte a los adds y pasarsela a ellos sino se va acumulando y al morir ira pasando a otro miembro de la raid, si no la disipas antes de 5 segundos te mete 50000

**Comment by lamaza** [comment]
Bueno, pero el golpe normal del otro bicho ese si es bug.

**Comment by efectokoleos** [comment]
no he podido reproducir tu fallo, cierro y si vuelve a pasar itnetna poner informacion mas detallada o grabalo en video XD
