### ISSUE TITLE
Spell de cazador ¡atacar!

### ISSUE THREAD

**Issue by patriccio** [RoDNet/Bugtracker-Infinium-4.3.4#1199]
hola, queria comentar que la spell ¡atacar! ID:83356 , (cuando asestas golpe critico con d.arcano , d.punteria ,d.explosivo el coste de enfoque del ataque basico de tu mascota se reduce 100% durante 12s), no se activa al aplicar critico con disparo arcano.

**Comment by Mhryel** [comment]
Repetido en https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/296
