### ISSUE TITLE
Spell Cazador BM (tigre y quimera)

### ISSUE THREAD

**Issue by patriccio** [RoDNet/Bugtracker-Infinium-4.3.4#1200]
hola, esta spell tigre y quimera ID:82899 (cada vez que te golpean cuerpo a cuerpo, el tiempo de reutilizacion de separacion se reduce al instante  4s y cuando te golpean con hechizos a distancia , el tiempo de reutilizacion de disuacion se reduce al instante 8s, estos efectos tienen un tiempo de reutilizacion de 2 s), bueno como dice la spell esto no sucede en ninguno de los 2 casos.

**Comment by searum** [comment]
fix
