### ISSUE TITLE
[Picaro] Emboscada- Daño reducido.

### ISSUE THREAD

**Issue by FullArrow** [RoDNet/Bugtracker-Infinium-4.3.4#1202]
Emboscada http://es.wowhead.com/spell=8676 (No encontré la de 4.3)

Según el DrDamage, debería inflijirle 12.7k al dummy cuando solo inflijo 7.5k (Sin mencionar que es con el efecto de [Descubrir Debilidad(rango 3)] con lo que puedo afirmar que el daño esta reducido alrededor de un 30%.
 Lo mismo sucede con los críticos, el multiplicador de golpe critico es de un 206% de daño, sin embargo, solo estoy obteniendo actualmente 15.9k de critico cuando debería ser alrededor de 26.16k Que según el DrDamage es el daño aproximado de esta facultad.
Saludos y gracias
![wowscrnshot_080913_091702](https://f.cloud.github.com/assets/5083085/938450/844ab75e-00fe-11e3-8b7b-244b01210abd.jpg)

**Comment by ghost** [comment]
Estoy leveando y efectivamente se nota bastante, ya que se mete más con puñalada que con emboscada. Puede que se deba a que no se está cumpliendo la condición de llevar dagas:
- Sin dagas: Inflinge 274% de daño con arma más 968p.
- Con dagas: Inflinge 396% de daño con arma más 1401p. 

Creo que está tomando siempre lo primero, lleves o no dagas, lo que explicaría en parte que el daño de puñalada fuera mayor (inflinge 361% de daño con arma más 1197p.) 

Todos los datos son a nivel 79, actualizaré el comentario cuando sea 85.

**Comment by searum** [comment]
creo que lo tengo fix toca probar para ajustar si a caso pero parece que si ^^

**Comment by ghost** [comment]
Gracias Searum!
