### ISSUE TITLE
[Misión][Tierras de la Peste del Este] Los héroes de Villa Darrow

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1203]
Buenas.
La misión "Los héroes de Villa Darrow" (http://es.wowhead.com/quest=27388) no se puede completar porque el PNJ Carlin Rutagrana (http://es.wowhead.com/npc=11063) no da el objeto "Crónicas ampliadas de Villa Darrow" (http://es.wowhead.com/item=13202) mediante opción de diálogo.
Gracias y hasta luego.

**Comment by Velcositro** [comment]
Venía a reportarla, sigue bug.

**Comment by redneo** [comment]
Arreglada
