### ISSUE TITLE
[Misión][Tierras de la Peste del Este] Vida en medio de la muerte

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1204]
Buenas.
La misión "Vida en medio de la muerte" (http://es.wowhead.com/quest=27421) no se puede completar porque cuando uso el objeto "Semillas de Rayne" (http://es.wowhead.com/item=61036) en cualquiera de los 3 Ziggurats, no sucede nada.
Gracias y hasta luego.

**Comment by Velcositro** [comment]
Venía a reportarla, sigue bug.
