### ISSUE TITLE
[Sacerdote] Glifo Palabra de poder: escudo

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#121]
Al tener puesto el glifo de palabra de poder escudo, debería de sanarte 20% del daño que te hagan mientras tienes puesto el hechizo palabra de poder escudo. Esto no sucede, pero también resulta que cada vez que te pones el escudo te sana 2k de vida.

Glifo: http://es.wowhead.com/item=42408
Hechizo: http://es.wowhead.com/spell=17/

**Comment by paellaencol** [comment]
Sí, está sanando 2k y escaso el glifo de palabra de poder escudo, porque es el resultado del 20% de la capacidad de absorción del hechizo palabra de poder escudo. Esto ya sucedía en el 4.0.6, y creo que era correcto. Además esta curación, producto del glifo, puede ser crítica, aunque no hace saltar "égida divina".
EL problema es que en el MoP cambiaron su uso y puede dar pie a confusiones en este aspecto, antes funcionaba tal y como ocurre ahora:

In Mists of Pandaria this glyph has been modifed. At this point it is unclear if this is only a tooltip change or if the spell is not calculated differently as a result of this change.

OLD: Glyph of Power Word: Shield
Your Power Word: Shield also heals the target for 20% of the absorption amount.

NEW: Glyph of Power Word: Shield
20% of the absorb from your Power Word: Shield spell is converted into healing.

---

Lo que esta yendo algo peor (permíteme que enlace desde otro reporte https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/43 ) es que la palabra de poder escudo este absorbiendo en torno a un 55% de la cantidad que en un principio debería absorber.

**Comment by ghost** [comment]
Según los datos proveidos por paellaencol está bien el glifo, lo cierro.
