### ISSUE TITLE
[MISION] Huargen: Resistencia Final

### ISSUE THREAD

**Issue by GReaperCT** [RoDNet/Bugtracker-Infinium-4.3.4#1212]
Hola!

-Estoy realizando la mision, y vienen solo dos oleadas de huargen y si no me da tiempo a matar los 8 que me piden, antes de que lo agan los npj no me salen mas huargen y no me deja terminar la mision.

-http://es.wowhead.com/quest=14222

Gracias y un saludo!

**Comment by Kiritoo** [comment]
Hola quiero comentar que esta misión funciona correctamente.
Es más resolvi varios tickets de gente que tras completarla para ir a ventormenta.
Los npc tienen un respawn de 5 min.
Un saludo.
