### ISSUE TITLE
[Decenso de alanegra] Faucemagma

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1216]
ID: http://es.wowhead.com/npc=41570/faucemagma 

El boss deberia de estar a la vista de todos pero se encuentra abajo en la lava y no podemos atacarlo pero cuando morimos todos es que el boss sube y podemos verlo normalmente. Pero las personas que liberaron y entraron denuevo no pueden ver el boss denuevo le aparece que esta abajo en la lava

**Comment by paellaencol** [comment]
Le falta la skill http://es.wowhead.com/spell=77971 que debe provocar a continuación que salgan http://es.wowhead.com/npc=42321

Además no está haciendo http://es.wowhead.com/spell=89773 al tanque. Faucemagma al utilizar esta spell permitirá que 2 jugadores (3 en modo 25) puedan subirse a Faucemagma (debe aparecer un icono que lo permita), quienes deberán usar la siguiente skill (creo que es esta http://es.wowhead.com/spell=79589 ) para permitir que Faucemagma suelte al tanque. En el momento que esto ocurra y durante unos segundos Faucemagma debe quedar con el debuff http://es.wowhead.com/spell=79010/punto-vulnerable.
Adjunto vídeo de esta fase:
http://www.youtube.com/watch?v=7X6TO71EnLU

Actualmente no está ocurriendo esto, al llegar a esta fase, Faucemagma recibe el debuff http://es.wowhead.com/spell=79010/punto-vulnerable y ya está.

P.D. Estas dos skills no pueden coincidir al mismo tiempo.

**Comment by F4NT4SM4** [comment]
Los parasitos aparecen la primera ves que le damos pero ya a la segunda salen unos mini infernales que no hacen nada xD

**Comment by F4NT4SM4** [comment]
cierro ya es visible el boss
