### ISSUE TITLE
Vendedor del set de honor (gladiador implacable)

### ISSUE THREAD

**Issue by sherik12** [RoDNet/Bugtracker-Infinium-4.3.4#122]
El vendedor vende solo las partes basicas, en wowhead dice que deberia vender tambien el set, dejo el link:
http://es.wowhead.com/npc=69974#sells:50-2

**Comment by ghost** [comment]
Ya esta reportado.

**Comment by redneo** [comment]
Creo que ya está arreglado si falta alguno me lo poneis en uno nuevo. Gracias
