### ISSUE TITLE
Bug diaria [Bomba va]

### ISSUE THREAD

**Issue by clc199411** [RoDNet/Bugtracker-Infinium-4.3.4#1220]
Mision diaria de Tol Barad bug que ingame se llama "¡Bomba va!" y en el enlace de wowhead sale como "¡Bombas fuera!" [http://es.wowhead.com/quest=28275]

**Comment by Kiritoo** [comment]
Hola y el fallo?
Un saludo.

**Comment by F4NT4SM4** [comment]
creo que se refiere a que la quest en el juego sale como "¡Bomba va!" y segun wowhead deberia ser "¡Bombas fuera!"

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/568?source=cc Ya reportado, seguimos del anterior.
