### ISSUE TITLE
Misión (Zul'Drak) "Paracaídas para la Cruzada Argenta"

### ISSUE THREAD

**Issue by Sheilina** [RoDNet/Bugtracker-Infinium-4.3.4#1221]
Cuando le das el paracaídas no contabiliza. 
http://es.wowhead.com/quest=12740/paracaidas-para-la-cruzada-argenta

Salu2

**Comment by ghost** [comment]
Cuando les lanzas el paracaídas (item=39615), se les pone el buff y todo pero no te cuenta para la misión.
