### ISSUE TITLE
Misión (Colinas Pardas) "Una experiencia extracorporal"

### ISSUE THREAD

**Issue by Sheilina** [RoDNet/Bugtracker-Infinium-4.3.4#1223]
La secuencia de visiones solo abarca el primer lugar y no retorna a la bola de cristal, la quest no se completa y solo puedes volver usando piedra de hogar.
http://es.wowhead.com/quest=12327

Salu2

**Comment by efectokoleos** [comment]
arreglado en el proximo reinicio
