### ISSUE TITLE
[DK] Golpe letal Daño

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1227]
ID: 49998
![wowscrnshot_081013_181725](https://f.cloud.github.com/assets/3101842/943348/02f63284-020f-11e3-9f23-7920c5298d2c.jpg)

El daño de golpe letal esta muy elevado (ojo esto los teste sin talento o glifo que afecten golpe letal) Pegue 17k y segun DrDamage deberia de pegar 12k

![wowscrnshot_081013_181653](https://f.cloud.github.com/assets/3101842/943351/3215b30a-020f-11e3-80c2-ba5c0f6ae5c2.jpg)

Pueden decir que no es gran cosa pero con glifo y talentos llego a pegar 60k al dummy sin cd y quedar en segundo de dps en raid :p

**Comment by Kiritoo** [comment]
El daño está correcto.
Sin armadura ni talentos pega lo que debe.
Cierro.
