### ISSUE TITLE
[Paladin] Sello de verdad

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.3.4#1228]
Bueno; este poder  http://es.wowhead.com/spell=31801  debería aplicar su efecto por cada ataque con poderes a un solo objetivo  y con cada ataque con arma (golpe blanco), el problema es que sólo se está aplicando por cada ataque  con arma y no con los poderes a un solo objetivo.

**Comment by searum** [comment]
fix
