### ISSUE TITLE
[Paladín] Exorcismo

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.3.4#1230]
El poder http://es.wowhead.com/spell=879 está pegando un 50% más o menos de lo que debería pegar. Esto afecta el efecto del paladín represión "El arte de la guerra" ( http://es.wowhead.com/spell=87138 ) que hace que al activarse  pegue un 100% adicional.
![wowscrnshot_081013_180713](https://f.cloud.github.com/assets/3945856/943377/eae685e2-0211-11e3-96e1-59e48a8dffb4.jpg)

En la foto se puede apreciar el daño que está  haciendo exorcismo  que es de 3740 cuando debería ser un  daño de 6615; está haciendo más o menos el 50% del daño que debería hacer.

**Comment by searum** [comment]
fix
