### ISSUE TITLE
[Paladín] Palabra de Gloria

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.3.4#1231]
La habilidad http://es.wowhead.com/spell=136494  está curando una cantidad muy inferior a lo que debería curar.
A mi, que soy pala repre Dr.Damage me marca 13k sin critico  con las 3 cargas de poder sagrado  y  está curando 5k con critico, cuando con crítico deberia curar 26k!
![wowscrnshot_081013_181523](https://f.cloud.github.com/assets/3945856/943391/ead3bf6e-0213-11e3-824d-4998dc2c0144.jpg)

**Comment by searum** [comment]
fix
