### ISSUE TITLE
[Buff] Buff Que no deben de Acumularse

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1232]
Aura de disparo certero ID:19506
Ira Desatada ID:30808
Poderio De abominacion ID:53138
Bedion de Poderio: http://es.wowhead.com/spell=19740/bendicion-de-poderio

Estos buff tienen el mismo Efecto aumenta un 20% el poder de ataque cuerpo a cuerpo y 10% el poder de ataque a distancia A los miembros de la banda o grupo que se en cuentre en un radio de 100m

Bueno estos buff no deberian de acumularse. Imaginense un mele con esos 4 buffos tendra un aumento de 80% de poder de ataque con solo esos 4 buff 

Fuente: http://www.warcrafthuntersunion.com/2009/05/list-of-what-raid-buffs-stack-and-do-not-stack/

**Comment by searum** [comment]
fix
