### ISSUE TITLE
vendedor conquita faltan armas

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#1235]
hola el vendedor de conquita de la horda http://es.wowhead.com/npc=54658/sargento-tronacuerno no vende armas a una mano de mano izquierda como espadas o mazas de las que cuestan 950 puntos.

hay armas de puños de mano izquiera por 950 pero que mi dk no puede usar estas armas^^.

haver si encuentro los link de las armas y las pongo.
un saludo

**Comment by Kiritoo** [comment]
http://eu.battle.net/wow/es/search?f=wowitem&q=Gladiador%20sa%C3%B1oso&page=2
Aqui tienes la lista, mira a partir de la pagina dos que empiezan las de T9 y dime las que faltan.

**Comment by 50megas** [comment]
hola fixx pues hay no salen las de nivel 378 que serian las que tocaria, busque hay mismos con Gladiador implacable que son las armas que vende, pero no salen nose si esque las  quitaron en el pandarias las demano izquierada o que pasa muy raro que no las encuentre.

solo salen dagas y armas de puños con ocion de mano izquierda

**Comment by Kiritoo** [comment]
Vale tu te refieres a las implacables.
http://eu.battle.net/wow/es/search?f=wowitem&sort=level&dir=d&q=Gladiador%20implacable&page=2
Mira aqui.

**Comment by 50megas** [comment]
si hay mire y e buelto a mirar pero salen todas de una mano solo nose que pasa xd

mirare por el google haver

**Comment by 50megas** [comment]
cierro no encuentro las armas ,igual las quitaron en este parche

**Comment by Kiritoo** [comment]
Yo añadi todas las que vi de este parche^^
