### ISSUE TITLE
[ Trinkets: Matrix Restabilized ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#1236]
Estabilizador de Matriz : http://es.wowhead.com/item=68994
Estabilizador de Matriz HC : http://es.wowhead.com/item=69150

Estos items no hacen el efecto que debería, puedes atacar mil veces pero nunca se activa.

Spell : http://es.wowhead.com/spell=96976
Spell HC : http://es.wowhead.com/spell=97138

Estas spells deben de tener 105 sec de CD Interno.

**Comment by efectokoleos** [comment]
arreglado
