### ISSUE TITLE
[ Trinkets: Vial of Shadows ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#1237]
Vial de Sombras:
- LFR > http://es.wowhead.com/item=77979
  Spell LFR: http://es.wowhead.com/spell=109722
- NM > http://es.wowhead.com/item=77207
  Spell NM: http://es.wowhead.com/spell=107995
- HC > http://es.wowhead.com/item=77999
  Spell HC: http://es.wowhead.com/spell=109725

Estas spells deberían tener un CD de 9 SECS  ( En el parche 4.3.2 se le nerfeó el daño brutalmente a cambio de un CD bastante más pequeño ) sin embargo saltan muy seguidas.

**Comment by efectokoleos** [comment]
arreglado
