### ISSUE TITLE
[ Hunter > Tier 13 > Beneficios ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#1238]
Tier 13 Cazador:
- http://es.wowhead.com/itemset=-497 HC
- http://es.wowhead.com/itemset=1061 NM
- http://es.wowhead.com/itemset=-478 LFR

Las spells para el Tier no se cumplen:
- 2P Bonus: http://es.wowhead.com/spell=105732

Debería dar el doble de recuperación de enfoque para Disparo firme y Cobra.
Es decir, Steady y Cobra regeneran 9p. con 2 partes del tier pasa a 18p.

Si tienes talentos en Puntería con Termination, se complementan.
Si el enemigo está por debajo del 25% recuperarás 15. de enfoque, con 2 partes del tier pasa a recuperar 30p.

---

4P Bonus: http://es.wowhead.com/spell=105921

Tu disparo arcano tiene un 40% de probabilidad de activar Cronocazador ( http://es.wowhead.com/spell=105919 ) Aumenta un 30% tu celeridad durante 15 segundos.

Puede ser activado con cualquier spell ofensiva de Cazador, y solo debería ser con:
- Disparo arcano: http://es.wowhead.com/spell=3044

No tiene CD, debiendo tener un CD Interno de 105 Segundos.

**Comment by Kiritoo** [comment]
Tier 13? Si no lo tenemos habilitado.

**Comment by lamaza** [comment]
El máximo es Tier 12. No se entiende por que dice T13?

**Comment by DatJetto** [comment]
El Tier 12 se añadió en 4.2.0, el Tier 13 en 4.3.0, actualmente tenemos hasta T12 , ya que estamos siguiendo las temporadas y los parches, para darle un sentido más blizzlike al servidor.

Cuando saquen el T13 en un futuro deberán arreglar las bonificaciones.

**Comment by Jhovanni** [comment]
Las explicaciones están muy bien hechas, pero no entiendo como ha podido probar tales objetos cuando no se tiene acceso a ellos en el servidor. De hecho el equipo que más hay acceso ahora es el 11 (a falta de que un equipo llegue a 2200 de rating en 3c3 o 5c5). Por lo cual no hay opción de saber si el tier 13 está bug o no. A menos que haya sido mediente tienda, pero creo ya quitaron esos objetos (si estaban, no se cuales eran)
