### ISSUE TITLE
[PNJ][Tierras de la Peste del Este] Capilla de la Esperanza de la Luz

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1239]
Buenas.
Quería reportar que faltan los siguientes PNJ de la zona "Capilla de la Esperanza de la Luz" en las "Tierras de la Peste del Este":

Comandante de envíos Metz (http://es.wowhead.com/npc=16212)
Smokey LaRue (http://es.wowhead.com/npc=11033)
Khaelin Alacerada (http://es.wowhead.com/npc=12617)
Georgia (http://es.wowhead.com/npc=12636)
Duque Nicholas (http://es.wowhead.com/npc=11039)
Vincent Randolph (http://es.wowhead.com/npc=47286)
Emisario Barbablanca (http://es.wowhead.com/npc=17069)
Emisario Gormok (http://es.wowhead.com/npc=17072)
Lord Raymond George (http://es.wowhead.com/npc=49856)
Gek Bocatraca (http://es.wowhead.com/npc=48704)
Gertrudis Bocatraca (http://es.wowhead.com/npc=48705)
Beezil Llavenlace (http://es.wowhead.com/npc=46022)
Rimblat Rompetierra (http://es.wowhead.com/npc=16134)
Maestro de Manada Mazadura (http://es.wowhead.com/npc=16283)
Jase Farlane (http://es.wowhead.com/npc=12941)
Examinatripas (http://es.wowhead.com/npc=47288)
Lord Maxwell Neófitus (http://es.wowhead.com/npc=11034)
Jessica Cuevas (http://es.wowhead.com/npc=16256)
Leonid Barthalomew el Venerado (http://es.wowhead.com/npc=11036)
Maestro artesano Omarion (http://es.wowhead.com/npc=16365)

Creo que eso es todo, hasta luego y gracias.

**Comment by Velcositro** [comment]
Venía a reportarlo, sigue bug.

**Comment by redneo** [comment]
El problema que uno de ellos da error 132... voy a ver si puedo meterlos todos a saco y no da error.

(Lo teneis cuando caiga el server)

**Comment by Velcositro** [comment]
Acabo de probar y sí da el error 132, me temo que tendrás que quitarlos de nuevo o probarlos de uno en uno. u.u

PD: Estaba probando a acercarme poco a poco a ver y pude ver a todos los npcs sin que me diera error, luego salí y volví, entonces noté que faltaba la tabernera. No sé si es que andan probando ya o qué... XD

**Comment by Velcositro** [comment]
Vuelvo a comentar por acá para que porfavor quites los npcs de nuevo porque ahora no puedo loguear con el pj que llevé a causa del error, gracias y disculpa las molestias.

**Comment by redneo** [comment]
creo que ahora por fin (cuando reinicie el servidor) irá correctamente

Lord Raymond George (http://es.wowhead.com/npc=49856) este era el que daba fallos

**Comment by Velcositro** [comment]
Comprobado, ya pude logear y estar por la zona sin que aparezca el error, muchas gracias.
