### ISSUE TITLE
Bug en Pumtos de vuelo

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#124]
Los Puntos de vuelo de la ALIANZA no dan vuelo:

Vega de tuercespina (Bahia del Botin)
Marjal revolcafango (Piñon de barro)

*se ira actualizando segun encuentre mas

Saludos

**Comment by frustrix** [comment]
Tierras de la peste del Este (Torre de la corona)

**Comment by Dekadencee** [comment]
¿Puedes adjuntar los ids de los npcs?

**Comment by frustrix** [comment]
estoy tratando de buscarlos, abrire un nuevo bugtracker con los ID de los npc

Saludos

**Comment by frustrix** [comment]
solucionado graciass
