### ISSUE TITLE
Mision bug ¿Es ese tu goblin?

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1240]
http://es.wowhead.com/quest=12969/es-ese-tu-goblin
Lado: Ambos
Empieza: Lok'lira la Vieja Bruja
Termina: Lok'lira la Vieja Bruja
Tienes que retar a http://es.wowhead.com/npc=30154
a combate pero le das al boton y no ocurre nada.
![wowscrnshot_081213_130458](https://f.cloud.github.com/assets/5048096/946852/1faafe9c-033f-11e3-861b-80c58b8b9b43.jpg)

**Comment by Kiritoo** [comment]
Esto esta reportado continuamos del anterior,https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/437?source=cc
Saludos.
