### ISSUE TITLE
[mazmorra] Grim Batol 5h

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1241]
El primer Boss se le puede dar ccs.

![wowscrnshot_081113_160545](https://f.cloud.github.com/assets/4790547/951138/2df5998c-039c-11e3-89f0-a79c04028a8b.jpg)

El tercer boss "maestro de algo" esta bien.

Y el cuarto boss, la dragona esa, se queda por alla abajo y nunca sube.

![wowscrnshot_081213_165137](https://f.cloud.github.com/assets/4790547/951143/4766abc2-039c-11e3-9b0e-c49660447b3b.jpg)

Al boss final Erudax wipeamos al primer intento, y al segundo intento dio wow error esa misma habilidad.

http://es.wowhead.com/spell=75664/vendaval-de-las-sombras

![wowscrnshot_081213_165638](https://f.cloud.github.com/assets/4790547/951116/d8a5c704-039b-11e3-96b3-cbafc852a3c6.jpg)
![wowscrnshot_081213_165640](https://f.cloud.github.com/assets/4790547/951117/d8be54d6-039b-11e3-9c9d-6c82490c2d7d.jpg)
![wowscrnshot_081213_165933](https://f.cloud.github.com/assets/4790547/951118/d8d5bd4c-039b-11e3-9d7b-e101e119e4ad.jpg)

**Comment by efectokoleos** [comment]
el general y el erudax estan arreglados el otro tendre k mirarlo mejor

**Comment by efectokoleos** [comment]
arreglada valiona :D en cuanto se compile estará

**Comment by lamaza** [comment]
Geniales, gracias.
