### ISSUE TITLE
[logro] La batalla del monte Hyjal

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1243]
http://es.wowhead.com/achievement=695/la-batalla-del-monte-hyjal

A pesar de que matamos al boss final, no obtuvimos el logro.

Solo 1 persona lo consiguió al recibir la espada del loot de Archimonde.

http://es.wowhead.com/npc=17968
http://es.wowhead.com/item=30902

![wowscrnshot_081113_172527](https://f.cloud.github.com/assets/4790547/951169/f8e6e678-039c-11e3-91e0-21d11fc16447.jpg)

![wowscrnshot_081113_151423](https://f.cloud.github.com/assets/4790547/951204/85d21f6c-039d-11e3-8ee3-6cc3ea062efb.jpg)
![wowscrnshot_081113_150724](https://f.cloud.github.com/assets/4790547/951205/85e8ac78-039d-11e3-8539-67319e33bf60.jpg)

Nos quedamos con las ganas haha

**Comment by SherBlader** [comment]
Pues creo haber ido en la 406 y nos dio logro cuando comerciabamos la espada (es decir, si tu no tenias el logro te pasaban la espada y te daba el logro)

**Comment by lamaza** [comment]
Tral era horda, se la paso al otro horda que estaba en la raid y no le dio logro. Agrego que lo mismo se podía hacer en lich king.

Pero si, el paso la espada por comercio, y no dio absolutamente nada de logro.

**Comment by lamaza** [comment]
Si de algo sirve, agrego que hace como 2 dias, cambie la armadura que me gane (token de tier 1) afuera de la banda, y me dieron el logro, como 1 semana después XD.

![wowscrnshot_081813_204902](https://f.cloud.github.com/assets/4790547/998629/23cc26d4-0a08-11e3-892b-bfc6395f7140.jpg)
![wowscrnshot_081813_204926](https://f.cloud.github.com/assets/4790547/998630/23e2b30e-0a08-11e3-922c-9b0cdb351b9a.jpg)
