### ISSUE TITLE
Npc Soldado Garnoth [Tol Barad]

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1245]
Buenas noches.

El npc http://es.wowhead.com/npc=48071 no se encuentra actualmente. Además este npc en cuestión debería dar a su vez las misiones diarias:
http://es.wowhead.com/quest=28662
http://es.wowhead.com/quest=28661
http://es.wowhead.com/quest=28660

El otro problema es que estas misiones nos deben redirigir a la subsección "Profundidades malditas" (en Tol Barad también), y la verja que da entrada a esta sección se haya cerrada, sin opción de poder abrirla para acceder a ella.

Adjunto imagen de la zona:

http://warcraftquests.com/clearing-the-depths-quest-wow/baradin-ghost-location/

Un saludo

**Comment by Kiritoo** [comment]
fix
