### ISSUE TITLE
[Misión] Problemas mineros (Las Islas Perdidas)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1246]
Buenas noches.

La misión http://es.wowhead.com/quest=14021/problemas-mineros no es realizable debido a que no aparece la opción de escoltar al "minero aterrorizado" ni aparecen tampoco ninguna "mena de kaja'mita"

Añado vídeo de como debería realizarse la misión:
http://www.youtube.com/watch?v=ossaDt3QuL0

Gracias

**Comment by redneo** [comment]
parcheada
