### ISSUE TITLE
[Misión] Fotografiar lo desconocido (Las Islas Perdidas)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1247]
Buenas noches.

La misión http://es.wowhead.com/quest=14031/fotografiar-lo-desconocido#english-comments no es realizable debido a que no sucede nada al utilizar la http://es.wowhead.com/item=49887 sobre las imágenes que debemos fotografiar. Además mientras utilizamos el item debería aparecernos como una canalización, actualmente solo le podemos hacer click, sin que surja ningún efecto.

Añado vídeo de como debería realizarse la misión:
http://www.youtube.com/watch?v=pmHd82Lu06w

Gracias

**Comment by redneo** [comment]
cuando caiga el server tendria que ir... me comentas si:
- las pinturas no tienen el simbolo de la camara
- No cuenta
- La camara esta por el suelo
- Puedes ver las camaras sin la mision

amos, todo lo que podria ir mal

**Comment by paellaencol** [comment]
Va perfecta!
