### ISSUE TITLE
[Joyeria] Npc Marith Lazuria

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1249]
ID: http://es.wowhead.com/npc=50482/marith-lazuria

El Npc deberia de vender ciertos bocetos de joyeria en e link de wowhead podran ver cuales

Actualmente en el servidor el npc no esta vendiendo nada

**Comment by Kiritoo** [comment]
Fix.
Tambiean añadido al de ventormenta.
