### ISSUE TITLE
[Mago] Bugs Escarcha y Fuego.

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.3.4#125]
Fuego:

1.) Pirómano: http://old.wowhead.com/spell=34295 
No aumenta la celeridad un 5%/10% cuando 3 o más objetivos están recibiendo daño fuego. (No hace nada). 

2.) Orbe de llamas: http://old.wowhead.com/spell=82731
Tiene su daño bajo, pega 250 por tick cuando debería pegar  más o menos 1800 por tick.
![wowscrnshot_070413_150153](https://f.cloud.github.com/assets/3945856/751008/c4ef86f8-e4e4-11e2-8af5-41b3a86f24cb.jpg)

3.) Poder del fuego: http://old.wowhead.com/spell=54734
Cuándo se agota el orbe no explota e inflije daño con lo dice en su descripción. De el aumento de el daño fuego 1%/2%/3% No estoy muy seguro ya que es dificil ver si esque aumenta o no.

Escarcha:

4.) Escarcha permanente: http://old.wowhead.com/spell=12571
No se aplica ningún de buff ( que reduzca la velocidad un 10% extra  y la sanación un 10%). No se aplica nada. [Edito: Tampoco sana al elemental.]
![wowscrnshot_070413_151041](https://f.cloud.github.com/assets/3945856/751031/f364ae36-e4e5-11e2-846f-311b5db033d8.jpg)

5.) Barrera de hielo: http://old.wowhead.com/spell=11426
Tiene una absorción menor a la correcta.

![wowscrnshot_070413_153053](https://f.cloud.github.com/assets/3945856/751095/bcfc0dfa-e4e8-11e2-95b7-7233ab3093c2.jpg)

Está absorviendo 8069 estando desnudo.

![wowscrnshot_070413_152943](https://f.cloud.github.com/assets/3945856/751092/94de603e-e4e8-11e2-9177-d2217a84e775.jpg)

También está absorbiendo 8069 estando sañoso.

Estando desnudo debería absorber una media de  10315.

![wowscrnshot_070413_153308](https://f.cloud.github.com/assets/3945856/751112/0628685c-e4e9-11e2-95ab-61853f33d7b0.jpg)

Y estando sañoso debería absorber una media de 17444.
![wowscrnshot_070413_153450](https://f.cloud.github.com/assets/3945856/751122/561746da-e4e9-11e2-9eed-9683aae8e26e.jpg)

En conclusíon barrera de hielo absorbe un valor fijo (incorrecto) que no se modifica con el poder con hechizos. 
Todo esto anterior hecho sin el glifo de barrera de hielo (como se puede ver en las imágenes)

6.) Glifo de barrera de hielo. (No encontré el ID)
Este glifo debería aumentar la absorción de la barrera de hielo un 30% pero no hace nada.

![wowscrnshot_070413_154651](https://f.cloud.github.com/assets/3945856/751169/ed494296-e4ea-11e2-95a6-e51a8ab291db.jpg)

![wowscrnshot_070413_154046](https://f.cloud.github.com/assets/3945856/751142/15e1fe6a-e4ea-11e2-9780-430c688138d7.jpg)

Vemos que sigue absorbiendo 8069 y que con el glifo no se ha modificado (Estando desnudo y equipado sañoso)

Cuando sabemos que ahora con este glifo debería absorber una media de 22677 estando sañoso.

![wowscrnshot_070413_154209](https://f.cloud.github.com/assets/3945856/751158/67d13858-e4ea-11e2-8ee6-1074974fdc8c.jpg)

Y una media de 13410 estando desnudo.

![wowscrnshot_070413_154500](https://f.cloud.github.com/assets/3945856/751165/b9ecb144-e4ea-11e2-8d19-1cab038f61e5.jpg)

De nuevo vemos que barrera de hielo absorbe un valor fijo (incorrecto) que no se modifica con el poder con hechizos NI con el Glifo de barrera de hielo.

7.) Orbe de pirofrío: http://old.wowhead.com/spell=84727
El orbe de llamas (http://old.wowhead.com/spell=82731) Si se trasforma en orbe de pirofrío pero ocurre el mismo problema del orbe de llamas, pega poco, pega 250 más o menos cuando debería pegar 1170 más o menos por tick.
[Edito: Si se transforma en Orbe de pirofrío]

8.) Lanza de hielo: http://old.wowhead.com/spell=30455
Está pegando menos de lo que debe ( un 50% de lo que debe pegar más o menos)

![wowscrnshot_070413_155522](https://f.cloud.github.com/assets/3945856/751191/544b58ca-e4ec-11e2-9104-e840c19a0241.jpg)

Vemos que pega 1842 cuando debe pegar una media de 3888 (sin crítico y sin que el objetivo esté congelado) pero el hecho de que pegue menos afecta el critico y el daño doblado que debe hacer cuando el enemigo está congelado.

9.) Glifo de reflejo exacto: http://www.wowhead.com/item=45739
No modifica el hechizo que lanzan los clones dependiendo de la especialización que tengamos, o sea siempre castean descarga de escarcha.

Todos los cálculos basados en Dr.Damage (como se puede ver en le imágenes) actualizado en esta verción.

Saludos, seguiré testeando.

**Comment by miglent** [comment]
Le falto incluir luminosidad arcana, no da bonificación de intelecto:
![wowscrnshot_070413_161437](https://f.cloud.github.com/assets/4936022/751239/cdbea660-e4ee-11e2-9111-b0a250cb3a90.jpg)
![wowscrnshot_070413_161444](https://f.cloud.github.com/assets/4936022/751241/d23cead0-e4ee-11e2-9d7b-22c855789853.jpg)

Escudo de mana: absorbe menos de lo que dice:
![wowscrnshot_070413_161615](https://f.cloud.github.com/assets/4936022/751246/06de8f82-e4ef-11e2-99c5-6fd64022e50a.jpg)
![wowscrnshot_070413_161619](https://f.cloud.github.com/assets/4936022/751247/0a85b2b4-e4ef-11e2-96b6-6c7950ed3b09.jpg)

El orbe de llamas si esta cambiando visualmente al de pirofrio, pero no puedo decir con certeza si se esta beneficiando de la bonificacion de maestria.
![wowscrnshot_070413_161830](https://f.cloud.github.com/assets/4936022/751259/6ad8b440-e4ef-11e2-9cef-1d625b500121.jpg)

creo que solo eso puedo aportar porque no se mucho del mago y no se me hace facil encontrar los bugs de esta clase.

**Comment by Dazand** [comment]
Gracias :)

**Comment by kaalbireth** [comment]
la piroexplocion no pega nada a la hora de ser instanteneo

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/133

**Comment by ghost** [comment]
Post con más bugs de mago:  https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/44

Buen post Dazand.

**Comment by Alfonn** [comment]
Más Bugs.

General :  
Polimorfia :  http://old.wowhead.com/spell=118 
Al recibir daño no se tranforma en su forma original.
![image](https://f.cloud.github.com/assets/3854953/753533/a233a51c-e56c-11e2-8575-9c173aef954a.png)

Armadura de Mago :  No da ese 3% de maná cada 5secs. http://old.wowhead.com/spell=6117

Yo testeo también con el DrDamage y este configura el daño que deberías hacer según el equipo que tengas (más buffos). Pues he querido testear desnudo y todas sus habilidades pegaban bien.Pruebas  :  

-El DrDamage me marcaba que pega de media 1334p de daño.Y pega bien sólo varia un poco.(Todo esto ha sido testeado con TODAS las habilidades de daño en la rama de escarcha, no sólo la de la imagen).
![image](https://f.cloud.github.com/assets/3854953/753513/27486bcc-e56b-11e2-82e4-dfa2a825c8d7.png)

(La absorción del escudo sí está mal como bien dice Dazand). 

-Lo mismo pero en la rama de fuego. Pruebas :  
Bola de fuego marca 1691p de daño. Y está bien, pega así. (Con variaciones siempre, recordad que esta cifra es de media).
![image](https://f.cloud.github.com/assets/3854953/753501/ef2b0a88-e56a-11e2-9952-e1b3b2762681.png)

En cambio con equipo el daño baja... Pruebas :  

Rama escarcha.Descarga de escarcha marca 11455 p de daño medio. En cambio con todas sus spells(cada una con su respectiva media...) baja ese daño...
![image](https://f.cloud.github.com/assets/3854953/753493/57c77bc2-e56a-11e2-9b4f-f50e634776ec.png)

Rama fuego. Bola de fuego marca 15005p de daño. En cambio con todas sus spells (cada una con su respectiva media) baja ese daño...
![image](https://f.cloud.github.com/assets/3854953/753487/376aae4e-e56a-11e2-9ef8-9d974d9849a1.png)

En conclusión creo que la escala de habilidades o alguna otra cosa hace que no peguen lo que deberían con equipo.(Porque desnudo sí pegan bien).

Un saludo, iré añadiendo más cosas.
PD : No pongo enlaces a wowhead porque pasa con todas las habilidades. Si me he equivocado en algo, porfavor decidlo ^^

**Comment by zak0ne** [comment]
En mi equipo tengo ciertos objetos que saltan de vez en cuando como puede ser: Insignia de Domino de Gladiador Sanguinario o el bordado de la capa por sastrería. Que cuando me saltan al lanzar un hechizo no me aumentan el Poder con hechizos como especifica cada una de esas habilidades, en vez de eso me aumenta el poder con hechizos de sanación cosa que los magos no utilizamos para nada.
Dejo estas imágenes para demostrarlo:

Aqui sin que ninguno de las dos habilidades haya saltado:

<img src="http://imageshack.us/a/img7/9263/78w8.jpg" alt="Image Hosted by ImageShack.us"/><br/>

Aqui con la Insignia de Dominio de Gladiador Sanguinario activada:

<img src="http://imageshack.us/a/img835/3405/4be0.jpg" alt="Image Hosted by ImageShack.us"/><br/>

Aqui con el bordado de capa activado:

<img src="http://imageshack.us/a/img221/6807/f7lv.jpg" alt="Image Hosted by ImageShack.us"/><br/>

No salta nunca los dedos de escarcha http://es.wowhead.com/spell=112965
a menos que tires el congelar con el elemental del agua y con el talento de "Conjelar mejorado".

El daño de "Descarga de escarcha" es inferior al que deberia tener, segun el DrDamage mi descarga de escarcha deberia hacer 10458 de media y no llega ni a 9k la mayora de las veces:

<img src="http://imageshack.us/a/img208/7471/ecqh.jpg" alt="Image Hosted by ImageShack.us"/><br/>

El daño de "Descarga de pirofrio" es menor del que deberia ser:

<img src="http://imageshack.us/a/img607/7597/gvzi.jpg" alt="Image Hosted by ImageShack.us"/><br/>

Y el dot que deja es ridiculo:

<img src="http://imageshack.us/a/img593/8769/htog.jpg" alt="Image Hosted by ImageShack.us"/><br/>

El daño de "Lanza de hielo" es como un 50% de lo que deberia meter:

<img src="http://imageshack.us/a/img196/1019/zlp7.jpg" alt="Image Hosted by ImageShack.us"/><br/>

Si veis algo que me haya confundido perdonadme y por favor decidmelo!

**Comment by miglent** [comment]
Una cosa sobre el dot de descarga de pirofrío: No debe existir a menos que tenga el glifo.
![wowscrnshot_070513_114345](https://f.cloud.github.com/assets/4936022/754712/2b18678a-e592-11e2-8446-bccbedb2a45e.jpg)

**Comment by Dazand** [comment]
Sobre Descarga de pirofrío http://old.wowhead.com/spell=44614 , el de buff que debe dejar es sólo uno de reducir 70% la velocidad de movimiento, luego, con un glifo (Glifo de pirofrío) dejar un DoT que pega el 3% que se puede acumular 3 veces , pero actualmente está dejando el dot (que pega poco) SIN EL GLIFO y con el glifo aumenta el daño del descarga de pirofrío 15% (que es lo correcto) pero no deja el DoT que deberia poner (de un 3% del daño) y no se puede acumular.

**Comment by zak0ne** [comment]
Aun teniendo el glifo sigue haciendo 7 de daño el dot y pegando menos de lo que marca el DrDamage.

<img src="http://imageshack.us/a/img402/6365/zuj7.jpg" alt="Image Hosted by ImageShack.us"/><br/>

<img src="http://imageshack.us/a/img407/2186/tuiv.jpg" alt="Image Hosted by ImageShack.us"/><br/>

**Comment by Alfonn** [comment]
Añado nuevo bug GENERAL :  

El escudo de maná del mago no debería repeler a los enemigos a no ser que escojas un talento en arcano que se llama ''Absorción de Encantador''. Pues el escudo de maná repele sin tener puesto dicho talento. ID escudo de maná : http://old.wowhead.com/spell=1463
Fotos : 
![image](https://f.cloud.github.com/assets/3854953/755304/d94d2e8c-e5a9-11e2-8c8e-d4193f9a7c95.png)

![image](https://f.cloud.github.com/assets/3854953/755300/b5e70490-e5a9-11e2-8171-22e1fa82bc2e.png)
![image](https://f.cloud.github.com/assets/3854953/755316/38cfe0a2-e5aa-11e2-9b0f-069815d5f9b9.png)

**Comment by Dekadencee** [comment]
Mira que os dije siempre que cada spell/bug en un reporte distinto...
Menudo lio ahora para verlo y llevarlo todo :/

**Comment by ghost** [comment]
@Dekadencee entonces mira mis reportes xd, yo los hago todos por separado :3

**Comment by Dazand** [comment]
Si quieres en éste dejo sólo un bug y hago más post con los demás bugs.

**Comment by ghost** [comment]
@Dazand yo creo que deberías de cerrar este reporte (porque ahora ya esta totalmente desordenado), y copiar y pegar cada cosa bug en un reporte a parte, solo es una sugerencia.

También, si alguien encuentra alguna cosa bug con respecto a la misma clase, pero que no tiene relación con el mismo bug que se esta reportando, debería de abrir un reporte a parte.
