### ISSUE TITLE
[misiones] (Tierras Altas Crepusculares) pajaro caido! pajaro caido!

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1250]
Reporto que esta mision aunque se autocompleta, no se puede entregar y es fundamental para abrir el portal enter Tierras Altas Crepusculares y Ventormenta.

Al llegar a la zona indicada, no hay nada, no aparece Thordun golpemartillo.
http://es.wowhead.com/npc=45172

http://es.wowhead.com/quest=27514/pajaro-caido-pajaro-caido

![wowscrnshot_081213_213706](https://f.cloud.github.com/assets/4790547/952138/463af2ec-03c1-11e3-9fa7-343543e3a587.jpg)

**Comment by redneo** [comment]
Arreglado
