### ISSUE TITLE
[objetos, hechizos] Tier 12 de inmolación - Paladin reprensión

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1251]
Buenas, para comentar que dicho conjunto ( 2 piezas) no da el beneficio de daño de fuego. Lo saque por Tienda.

![wowscrnshot_081313_123921](https://f.cloud.github.com/assets/4790547/956525/596d555c-043f-11e3-884d-d3ce43b2cd76.jpg)

![wowscrnshot_081313_123107](https://f.cloud.github.com/assets/4790547/956473/3907dfae-043e-11e3-9b56-aef80804df06.jpg)

**Comment by redneo** [comment]
Cuando se te pase la pataleta infantil nos avisas. Gracias!

**Comment by lamaza** [comment]
Hola redneo XD. Un saludo al staff, gracias por la depuración de thrash.
