### ISSUE TITLE
[Sacerdote] Palabra de poder: escudo

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1252]
Hola queria comentar hoy fijandome en la absorción de mi escudo me parece un poco excesiva.
Enlace: http://es.wowhead.com/spell=17
Os enseño unas fotos.
![wowscrnshot_081313_183840](https://f.cloud.github.com/assets/3537253/956657/f30cbed0-0441-11e3-962f-2b1809959247.jpg)
![wowscrnshot_081313_183843](https://f.cloud.github.com/assets/3537253/956658/f30d5c6e-0441-11e3-9c97-bfc3ce8f080d.jpg)

Como se ve en la primera foto la absorción que tiene mi escudo es 31065, está sanación es siempre igual salte el abalorio de poder de hechizos o salte el torrente de poder del arma, siempre 31065.

En la segunda foto enseño como él escudo en su descripción marca, 19510, por ello pienso que la absorción esta algo elevada.

Un saludo.

**Comment by ghost** [comment]
Si..a mi también me lo parece..ayer estuve haciendo pruebas con Keltanas en Elwynn, iba Disci pero estuve un par de minutos pegándole y no llegué a hacerle ni 1 punto de daño. Todo absorber refresheando los escudos. Aún así no hice muchos cálculos, no estaría mal que revisaran la fórmula.

**Comment by lamaza** [comment]
El colmo de los colmos, miren a Jesucrist, un sacer 85 horda disciplina, no sabe hacer nada mas que entrar a todas las bg y spammear este spell. Ya lo hemos perseguido entre 4 y 5 en diferentes bg, todos full CDS, es prácticamente inmortal, 2/10 muertes es decir que hicimos mucho.

**Comment by lamaza** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1431

**Comment by searum** [comment]
a ver si ya cesan los lloros
