### ISSUE TITLE
spell Cazador BM (Aliviar Mascota Mejorado)

### ISSUE THREAD

**Issue by patriccio** [RoDNet/Bugtracker-Infinium-4.3.4#1254]
Hola a los gm, queria reporta que aliviar mascota mejorado ID:19573(da un 50% de probabilidad de limpiar 1 efecto de maldicion , enfermedad , veneno , magia de la mascota con cada pulso) no limpia efectos anteriormente mencionados , agradeceria si pudieran revisar esa spell.

**Comment by Kiritoo** [comment]
Mal reportado, cierro saludos.
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
