### ISSUE TITLE
Mision Bug El despertar 

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1255]
http://es.wowhead.com/quest=24960
Raza:  No-muerto
Empieza: Custodio Caice
Termina: Custodio Caice
Los npc's que deverias ayudar no estan.
http://es.wowhead.com/npc=38895
http://es.wowhead.com/npc=49231
http://es.wowhead.com/npc=66167

**Comment by searum** [comment]
fixed
