### ISSUE TITLE
[Mision] El Levantamiento de los Lanza Negre

### ISSUE THREAD

**Issue by GenePewPew** [RoDNet/Bugtracker-Infinium-4.3.4#1256]
http://es.wowhead.com/quest=24764/el-levantamiento-de-los-lanza-negra

Luego de crear el personaje, te pide hablar con Voldreka, pero este npc no se encuentra donde deberia

**Comment by Kiritoo** [comment]
Añadir los enlaces porfavor.

**Comment by GenePewPew** [comment]
lissto

**Comment by Kiritoo** [comment]
Esto esta fix.
