### ISSUE TITLE
Druidas Equilibrio, Eclipse bug

### ISSUE THREAD

**Issue by ahira** [RoDNet/Bugtracker-Infinium-4.3.4#1258]
Buenas, vengo a reportarles un bug que, almenos mi druida, tiene con el poder eclipse de los druidas equilibrio, el problema es que tras estar jugando un rato, (aprox 30min), el poder eclipse deja de funcionar, el valor de la barra del sol y la luna deja de moverse  queda en un valor si avanzar mas por lo que queda inservible y no tira nunca ningun eclipse xq no llega a sus limites, queda quieto normal mente en el valor 13 hacia la luna (izquierda). Tengo q reloguear para q vuelva a funcionar.
Eso es todo, desde ya gracias.

**Comment by Kiritoo** [comment]
Links de los eclipses?
Saludos

**Comment by Eralion** [comment]
Es esta habilidad la posteo yo, por que mi amigo, no tenia tiempo.

http://es.wowhead.com/spell=79577/eclipse

**Comment by searum** [comment]
fix
