### ISSUE TITLE
Chaman mejora Bug!!!

### ISSUE THREAD

**Issue by Asesino150000** [RoDNet/Bugtracker-Infinium-4.3.4#1259]
Hola queria reportar un bug del chaman mejora.El caso es que pego i sano la misma cantidad que si no tuviera ropa puesta.

Un saludo

**Comment by Moyax** [comment]
Lo que pasa es lo siguiente es que el chamy no se esta beneficiabando con el poder con hechizos... Las habilidades magicas del chamy (sanaciones, choques, descargas de relampagos, etc), se  tiran como si no tubiera nada de ropa. Yo tambien hize la prueba quitandome todo el equipo y resulto que hacen el mismo daño o sanacion con o sin el equipo, osea +0 de poder de hechizos. Un ejemplo es que cuando voy a lanzar alguna sanacion, en el caso de la que mas cura, esta dice en la descripcion que sanara unos 17k, pero al usarla solo me sana 9k lo mismo que si estubiera desnudo sin nada de ropa. En la descripciones de las spell si sale como si ya me ubieran otorgado el aumento que me da el poder con hechizos, pero al usarlas los numeros no cudran.

Aqui algunas imagenes.

![wowscrnshot_081313_203726](https://f.cloud.github.com/assets/4944904/961727/9d54339e-04df-11e3-84ad-b2c996956c38.jpg)

![wowscrnshot_081313_203746](https://f.cloud.github.com/assets/4944904/961728/9d6191ba-04df-11e3-813a-0b730c8d1d4e.jpg)

![wowscrnshot_081313_202651](https://f.cloud.github.com/assets/4944904/961744/f48d32be-04df-11e3-90aa-a29ddc2ad2d2.jpg)

![wowscrnshot_081313_204443](https://f.cloud.github.com/assets/4944904/961729/9d699d2e-04df-11e3-9db2-cef14d9889bc.jpg)

**Comment by paellaencol** [comment]
Esto está ya arreglado, podeis cerrarlo?
