### ISSUE TITLE
[Sacerdote] Hechizos

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#126]
Hola quiero reportar los hechizos del sacerdote.

<h3>*Tortura mental</h3> http://es.wowhead.com/spell=15407 Esta bastante bien solo un pelin bajo.

<h3>*Explosión mental</h3> http://es.wowhead.com/spell=8092 Está bastante bajado, a la mitad más o menos.

<h3>*Abrasamiento mental</h3> http://es.wowhead.com/spell=48045 Está bastante bien solo pega un pelín de mas sus ticks.

<h3>*Toque vampírico</h3> http://es.wowhead.com/spell=34914 Está bastante bien solo pega un pelín de más sus ticks.

<h3>*Palabra de las Sombras: dolor</h3> http://es.wowhead.com/spell=589 Está bastante bien solo pega un pelín de más sus ticks.

<h3>*Peste devoradora</h3> http://es.wowhead.com/spell=2944 Sobre la media.

<h3>*Palabra de las Sombras: muerte</h3> http://es.wowhead.com/spell=32379 Pega un poco de más, no mucho.

<h3>*Palabra de poder: escudo</h3> http://es.wowhead.com/spell=17 Solo absorve 2/3 de lo que deberia.

<h3>*Sanación relámpago</h3> http://es.wowhead.com/spell=2061 En la media.

<h3>*Sanación superior</h3> http://es.wowhead.com/spell=2060 Cura un poco de más, en torno a 2k.

<h3>*Renovar</h3> http://es.wowhead.com/spell=139 Cura de más alrededor de 2k.

<h3>*Rezo de sanación</h3> http://es.wowhead.com/spell=596 Cura alrededor de 1k de más.

<h3>*Himno divino</h3> http://es.wowhead.com/spell=64843 Está bastante bien, cura un pelín de más a la media.

<h3>*Sanación conjunta</h3> http://es.wowhead.com/spell=32546 Cura sobre 1k de más.

<h3>*Penitencia</h3> http://es.wowhead.com/spell=47540  Cura sobre 1k de más y al golpear pega de menos.

<h3>*Fuego Sagrado</h3> http://es.wowhead.com/spell=14914 El golpe que hace pega alrededor de 3k de menos y sus ticks 40 puntos de menos, los ticks es lo más cercano a la media.

<h3>*Punición</h3> http://es.wowhead.com/spell=585 Pega sobre 1k de menos a la media.

Bueno esto concluye aqui si me olvido de algo espero que me lo mencioneis y si podeis añadir alguno se agradece.

Un saludo.

**Comment by ghost** [comment]
Solo dire que, como lo dijo Stormfury, el Dr. Damage no es confiable, además creo que ahora no estan fijandose en el daño, sino más bien en el funcionamiento correcto.

**Comment by crowel** [comment]
Crees que entonces el reporte no es valido?
Se que es una aproximación pero tampoco creo que ande lejos ya pues va haciendo un calculo a medida de las estadisticas de uno.

**Comment by ghost** [comment]
Bueno por mi experiencia te dire, que el Dr. Damage decia que la púa tenía que hacer 23k de daño xd (en la versión anterior), redneo dijo que se pueden ver las fórmulas del Dr. damage en unos archivos .lua que trae para hacer los calculos "a mano", no sé como verlos.
