### ISSUE TITLE
[Alquimia] Frasco de batalla

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1263]
El Frasco de batalla http://es.wowhead.com/spell=92679/frasco-de-batalla que se consigue al hacer click sobre una caldera de batalla http://es.wowhead.com/spell=92643/caldera-de-batalla no está dando ningún beneficio tras bebérsela.

http://imageshack.us/photo/my-images/9/x2x7.jpg/
<a href="http://imageshack.us/photo/my-images/9/x2x7.jpg/" target="_blank"><img src="http://imageshack.us/a/img9/2383/x2x7.th.jpg" border="0"/></a>

**Comment by Monleon** [comment]
Esto ya funciona
