### ISSUE TITLE
[hechizos] Disuacion Cazador - Spell muy benéfica

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1264]
Adjunto la prueba de que los cazadores al usar este hechizo pueden ir pegandote igualmente. Se que de todas maneras no se ve, o entiende muy bien, pero se reproduce muy facil en menos de 2 min. Saludos.

![wowscrnshot_081313_222915](https://f.cloud.github.com/assets/4790547/965804/ebbcbdcc-0533-11e3-815e-f34753d08b53.jpg)
![wowscrnshot_081313_222815](https://f.cloud.github.com/assets/4790547/965805/ebd4fa72-0533-11e3-9a66-736ecedb2ba8.jpg)
![wowscrnshot_081313_222916](https://f.cloud.github.com/assets/4790547/965806/ebea6fce-0533-11e3-9c10-479eb61ce34b.jpg)

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/291
Ya reportado.
