### ISSUE TITLE
Capilla de la Esperanza de la Luz BUG!!!!!!

### ISSUE THREAD

**Issue by Asesino150000** [RoDNet/Bugtracker-Infinium-4.3.4#1265]
Hola el bug es que cuando voy a la Capilla de la Esperanza de la Luz que esta en Tierras de la Peste del Este no hay absolutamente nadie ni siquiera el maestro de vuelo.

**Comment by lamaza** [comment]
Creo que ya estaba https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1239
Que clase es tu pj? Si es un DK recien iniciado, debes estar en otra Phase.

Sino, debieron quitar los npc, mientras arreglan el area debido a https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/161 https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/354

**Comment by Asesino150000** [comment]
No digo eso.Mi clase es un picaro y estava leveando en Tierras de la Peste del Este i fui a Capilla de la Esperanza de la Luz y no hay nadie
