### ISSUE TITLE
Mision (Gilneas) Dar esquinazo

### ISSUE THREAD

**Issue by escontreras** [RoDNet/Bugtracker-Infinium-4.3.4#1266]
la mision dar esquinazo presenta un bug debido a que el npc que ahi que eliminar no aparece aqui dejo el link wow head

http://es.wowhead.com/quest=24616/dar-esquinazo#.

**Comment by Monleon** [comment]
Las misiones de los huargens ya funcionan perfectamente de inicio a fin
