### ISSUE TITLE
Joyería , prospectar minerales

### ISSUE THREAD

**Issue by shogun1968** [RoDNet/Bugtracker-Infinium-4.3.4#1268]
Cuando un joyero intenta prospectar minerales de linch king, como saronita, titanio o cobalto, en vez de aparecer citrinos enormes, sangritas, cristales de sol, etc, aparecen armas y armaduras, con lo que no se pueden hacer las misiones diarias de joyería de Dalarán.

**Comment by efectokoleos** [comment]
prueba en el proximo reinicio

**Comment by searum** [comment]
fix
