### ISSUE TITLE
error mineria

### ISSUE THREAD

**Issue by xhide86** [RoDNet/Bugtracker-Infinium-4.3.4#1269]
Hola a todos, cada vez que uso minería no me da minerales lo que me dan son hierbas.
![wowscrnshot_081513_183032](https://f.cloud.github.com/assets/5238456/969742/8bd8f222-05c9-11e3-8c58-54ff5027c95d.jpg)
![wowscrnshot_081513_183036](https://f.cloud.github.com/assets/5238456/969743/8bf09c7e-05c9-11e3-88f2-ca2083f42881.jpg)

**Comment by efectokoleos** [comment]
fixed

**Comment by lamaza** [comment]
Que horror, menos mal fix XD. Excelentes Devs.
