### ISSUE TITLE
[Mazmorra] Cumbre de Roca Negra

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#1270]
Mazmorra: http://es.wowhead.com/zone=1583

Bug: Hay 2 puertas cerradas que deberían estar abiertas ya que no hay ninguna condición para poder abrirlas, no son puertas normales sino unas rejas que no se pueden usar, estas puertas bloquean el paso hacia varios jefes y hacia la entrada de la banda "Guarida de Alanegra", dejo una imagen con la localización de las puertas:

http://img32.imageshack.us/img32/3764/vmon.jpg

**Comment by lamaza** [comment]
Ya aqui expliqué por qué estan cerradas Velco.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1355

Se debe realizar el minieventor Estadio de Rocanegra.

PD: seria bueno que cierres este tema :/.

**Comment by Velcositro** [comment]
Vaya, no sabía sobre ese evento, aunque igual está bug, gracias por el aviso.

**Comment by efectokoleos** [comment]
cierro y seguimos en ese
