### ISSUE TITLE
[Jefe de Mazmorra](Guarida de Alanegra) Nefarian

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#1271]
Mazmorra: http://es.wowhead.com/zone=2677

Nefarian: http://es.wowhead.com/npc=11583

Bug: La 1º fase (donde empiezan a salir mobs y él es inmune hasta que se mata a todos) funciona bien, pero en la 2º fase (Cuando se mata a todos los mobs y él se transforma en Dragón) sale como amistoso y no se le puede atacar, pero si te acercas, él si ataca normalmente.

**Comment by efectokoleos** [comment]
fix
