### ISSUE TITLE
Bugs de mascotas.

### ISSUE THREAD

**Issue by Eralion** [RoDNet/Bugtracker-Infinium-4.3.4#1274]
Es la tercera vez que tuve que tamear a Arcturis, el oso espiritual de las Colinas Pardas, por que al desconectarme y volverme a conectar desaparecía, ya me paso con otras pets de clase normal (obviamente engloba a todas las pets), y espero que puedan echarle un ojo a esto, por que al final cuando te quieres desconectar lo haces pensando, ¿tendré mañana a mi mascota o desaparecerá?

**Comment by ghost** [comment]
Prueba usando el comando .save después de atraparla y desconecta y conecta, a ver si el problema persiste.

Saludos.

**Comment by Kiritoo** [comment]
Hola hoy lo reparo searum, pruebalo si te va bien.

**Comment by Dekadencee** [comment]
Supongo que como no ha vuelto a responder el error ha sido solucionado, asi que cierro
