### ISSUE TITLE
[Misión] (Las Mil Agujas) Something to Wear

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1275]
http://es.wowhead.com/quest=28125/algo-que-ponerse

Los npcs no despojan el objeto de la misión.

NPC:
http://es.wowhead.com/npc=47585
http://es.wowhead.com/npc=47630
http://es.wowhead.com/npc=47583

ITEM:
http://es.wowhead.com/item=63035

Saludos

**Comment by redneo** [comment]
arreglado
