### ISSUE TITLE
Arqueologia BUG!!!!!

### ISSUE THREAD

**Issue by Asesino150000** [RoDNet/Bugtracker-Infinium-4.3.4#1278]
Hola queria decir que aruqeologia esta bug porque ya he cojido bastantes reliquias i no me a subido sigue estando en 1p.

Gracias

**Comment by Kiritoo** [comment]
A partir de 50p no debe darte las reliquias solo los artefactos que construyes.
¿A cuanto estas?

**Comment by Dekadencee** [comment]
Fixeado
