### ISSUE TITLE
[Misión] (Tierras Inhóspitas) All's Fair in Love, War, and Archaeology

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1281]
Todo vale en el amor, la guerra y la arqueología http://es.wowhead.com/quest=27792

Los npcs Excavador del Relicario <El Relicario> http://es.wowhead.com/npc=46772

No tiran ninguno de los 4 objetos necesarios para completar la misión.

Cáliz roto http://es.wowhead.com/item=62485
Jarrón polvoriento http://es.wowhead.com/item=62486
Jeroglífico terráneo http://es.wowhead.com/item=62487
Herramienta trogg http://es.wowhead.com/item=62488

Saludos

**Comment by efectokoleos** [comment]
arreglado en el proximo reinicio
