### ISSUE TITLE
[Errores Internos] Tras morir o revivir

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1288]
Hola quiero comentar este fallo, a veces en bg tras morir o revivir de repente te salta el siguiente mensaje, como si hubiera acabado la bg y tocara salirse de ella pero no es cierto ya que lo cierras y continuas pero es confuso.
También ocurre que cuando salta este mensajes las estadisticas de la bg loquean sin poder verlas correctamente.
![wowscrnshot_073113_225536](https://f.cloud.github.com/assets/3537253/973082/39a4305e-0617-11e3-96e7-8cc87b381ff4.jpg)
![wowscrnshot_073113_225543](https://f.cloud.github.com/assets/3537253/973083/39adbff2-0617-11e3-9ea1-cea8b8e98e93.jpg)

Saludos.

**Comment by lamaza** [comment]
Y lo peor es que si no sabes ( y me paso antes) y le das salir de CBD, te deja desertor.

**Comment by Necrofilo** [comment]
Pasa cuando alguien se desconecta.

**Comment by Dekadencee** [comment]
Fixeado desde hace tiempo, se nos olvidó cerrarlo en su dia
