### ISSUE TITLE
[NPC] Viuda Vientomuerto

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1289]
Hola.
Este npc Viuda Vientomuerto http://es.wowhead.com/npc=51983
Al pasar por al lado de él no ataca, es como si no existiera.

![wowscrnshot_080313_035805](https://f.cloud.github.com/assets/3537253/973091/ad258b7c-0617-11e3-9d3d-83be53f82244.jpg)

Saludos.

**Comment by Kiritoo** [comment]
fix
