### ISSUE TITLE
Hermandades

### ISSUE THREAD

**Issue by Centinela-zz** [RoDNet/Bugtracker-Infinium-4.3.4#129]
Los pjs no salen en ninguna hermandad, ni cuando te cruzas con ellos ni cuando miras en el social, el GearScore dice que "no tienen hermandad" y de hecho no se puede modificar el tabardo de hermandad. Los permisos de la hermandad están bug, cualquiera puede degradar y ascender, incluso si son de su misma categoría.

Gracias

**Comment by Dekadencee** [comment]
Relacionado con #7 seguimos el reporte desde ahi
