### ISSUE TITLE
[NPC] Cría de rinoceronte lanudo

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1294]
Cría de rinoceronte lanudo http://es.wowhead.com/npc=25488

No se les puede atacar, ni hacerles tarjet. También aparecen como si estubieran muertos y se van arrastrando.
![wowscrnshot_080513_015224](https://f.cloud.github.com/assets/3537253/974865/04d7e204-0666-11e3-8250-be704b9320ba.jpg)
![wowscrnshot_080513_015227](https://f.cloud.github.com/assets/3537253/974866/04eeeb8e-0666-11e3-8fd2-4021d2f00785.jpg)

Saludos.

**Comment by Kiritoo** [comment]
Fix
