### ISSUE TITLE
[NPC] Caribú de marisma

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1295]
Caribú de marisma http://es.wowhead.com/npc=25680

Aparece arrastrandose como si estubiera muerto.
![wowscrnshot_080513_015615](https://f.cloud.github.com/assets/3537253/974891/e216583a-0666-11e3-85e7-621fdbabdf1b.jpg)

Saludos.

**Comment by Kiritoo** [comment]
Fix
