### ISSUE TITLE
[NPC] Bebesangre Furiarena

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1297]
Bebesangre Furiarena http://es.wowhead.com/npc=5649

Estos npcs estan en Zul´Farrak pero no atacan.
![wowscrnshot_080613_153349](https://f.cloud.github.com/assets/3537253/974917/ee8e0508-0667-11e3-8d7f-eecafe5c188c.jpg)

Saludos.

**Comment by Kiritoo** [comment]
Fix
