### ISSUE TITLE
Bug Maestria

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#13]
Bueno, no se si esto suceda con todas las clases, pero con mi druida si sucede,

al abrir mi libro de hechizos dice que tengo que aprender con mi instructor mastria
![1](https://f.cloud.github.com/assets/4895839/746705/b0d1e74c-e435-11e2-96e6-7875b1fb9e11.jpg)

En datos del personaje dice tambien que debo aprender maestria
![2](https://f.cloud.github.com/assets/4895839/746706/c14caa30-e435-11e2-86e6-afb2cd9b28a3.jpg)

Y cuando voy con mi instructor, maestria me aparece como hechizo ya aprendido anteriormente
![wowscrnshot_070313_180804](https://f.cloud.github.com/assets/4895839/746707/cec0b67a-e435-11e2-8bcd-ad93307400fd.jpg)

No he testeado si es un bug visual o no, pero ahi reporto el dato.

**Comment by Dekadencee** [comment]
Fixed
