### ISSUE TITLE
[NPC] Rastreador de nieve Grumm

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1301]
Rastreador de nieve Grumm http://es.wowhead.com/npc=25516
Este npc aparece como muerto en el suelo y no ataca.
![wowscrnshot_080813_001930](https://f.cloud.github.com/assets/3537253/975034/0e880fbc-066c-11e3-81c8-29fa43f8c20c.jpg)

Saludos.

**Comment by Kiritoo** [comment]
Este npc esta correcto no ataca a la alianza y la horda puede completar perfectamente la misión en el y cojer la siguiente.
Cierro issue.
