### ISSUE TITLE
[NPC] Zahorí de enfoque

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1304]
Zahorí de enfoque http://es.wowhead.com/npc=26816
Estes npcs aparecen como si estubieran muertos y como amistosos.
![wowscrnshot_080813_014020](https://f.cloud.github.com/assets/3537253/975392/ff3c10f8-0675-11e3-8900-47742b7e7c27.jpg)

Saludos.

**Comment by Kiritoo** [comment]
Fix
