### ISSUE TITLE
[NPC] Ogro mago Gordok

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1305]
Ogro mago Gordok http://es.wowhead.com/npc=11443

No se le puede atacar objetivo no válido.

![wowscrnshot_080813_163547](https://f.cloud.github.com/assets/3537253/975419/869afbae-0676-11e3-81c4-9bd7e575e67f.jpg)

Saludos.

**Comment by Kiritoo** [comment]
Fix
