### ISSUE TITLE
[Misión] (Cementerio de Dragones) No Place to Run

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1306]
Sin escapatoria  http://es.wowhead.com/quest=12261

No se puede usar el item en la zona designada.
![wowscrnshot_080913_021801](https://f.cloud.github.com/assets/3537253/975706/957de94e-067e-11e3-9dc4-bcffdab3d7fb.jpg)

Item: Resguardos destructivos http://es.wowhead.com/item=37445

Saludos.

**Comment by efectokoleos** [comment]
funciona correctamente
