### ISSUE TITLE
[NPC] Chamán Drakkari - Guerrero Drakkari

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1309]
*Guerrero Drakkari http://es.wowhead.com/npc=26425
*Chamán Drakkari http://es.wowhead.com/npc=26447

No se les puede atacar.
![wowscrnshot_080913_030337](https://f.cloud.github.com/assets/3537253/975957/c93f143e-0682-11e3-846b-1a6989ced442.jpg)
![wowscrnshot_080913_030515](https://f.cloud.github.com/assets/3537253/975959/c97cae48-0682-11e3-8ba1-344bbbc16f9d.jpg)

Saludos.

**Comment by Kiritoo** [comment]
Fix
