### ISSUE TITLE
[Misión] (Zul'Drak) The Champion of Anguish

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1311]
Está es la última misión del anfiteatro de zul´drak tras pasarla te dan el logro.
El campeón de angustia http://es.wowhead.com/quest=12948

El problema d está misión es que al cojerla no aparece el npc que se debe matar.
Vladof el Carnicero http://es.wowhead.com/npc=30022

Video: http://www.youtube.com/watch?v=O9IIFJWbm44  Minuto 1:10

Saludos.

**Comment by moriaar** [comment]
Esta misión sigue bug, el npc sigue sin aparecer.

**Comment by searum** [comment]
fix

**Comment by moriaar** [comment]
Lo acabo de intentar otra vez, y no va, tengo la caché borrada y sigue sin ir.

**Comment by Kiritoo** [comment]
@moriaar http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Lee esto antes de reportar en un Issue cerrado.
