### ISSUE TITLE
[Item] Libro sobre maestría en glifos

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1314]
Quiero reportar este objeto.
Libro sobre maestría en glifos http://es.wowhead.com/item=45912
El cual a veces en vez de una entrega dos recetas seguidas con un solo libro.

Aquí el caso.
![wowscrnshot_081213_033629](https://f.cloud.github.com/assets/3537253/976143/5c963d0e-0686-11e3-86a4-58815fe3ebfb.jpg)

Saludos.

**Comment by Kiritoo** [comment]
Esto no ocurre.
Saludos.
