### ISSUE TITLE
[Item] Piedra de hogar de héroe

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1316]
Piedra de hogar de héroe http://es.wowhead.com/item=68808
Uso: Te teletransporta al instante a El Tonel Dorado en Ventormenta. Solo se puede utilizar una vez.

Al usarla te quedas en el sitio.

Spell: http://es.wowhead.com/spell=96333

Saludos.

**Comment by efectokoleos** [comment]
arreglado
