### ISSUE TITLE
[NPC] Terror pesadilla

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1318]
Terror pesadilla http://es.wowhead.com/npc=40134

Estos npcs no atacan.
![wowscrnshot_081313_165246](https://f.cloud.github.com/assets/3537253/976227/3647ea24-0688-11e3-9c41-59cb2659788d.jpg)

Saludos.

**Comment by Kiritoo** [comment]
Fix
