### ISSUE TITLE
Zul' Aman: Akil' zon

### ISSUE THREAD

**Issue by Mhryel** [RoDNet/Bugtracker-Infinium-4.3.4#1319]
1er Boss: Akil' zon: http://es.wowhead.com/npc=23574

---

Dinámica:

Perturbación estática – Akil'zon charges the air around a random player, inflicting 35000 Nature damage in a 5 yard radius, and increasing Nature damage taken by 25% for 20 sec. This effect stacks up to 10 times.
Llamar relámpagos – Akil'zon unleashes a burst of electrical energy at his current target, inflicting 28500 to 31500 Nature damage.
Secuestrador Amani – Akil'zon calls an Amani Kidnapper to snatch a random player into the air.
Desplumado – While in the air, the Amani Kidnapper inflicts 4% of a players's maximum health as damage every second. The player can continue to use spells, items and abilities. Slaying the Amani Kidnapper frees the trapped player.
Águila planeadora – Akil'zon summons a flock of Soaring Eagles. They have very low health.
Descenso en picado de águila – The Soaring Eagles dive on random players, inflicting 24566 to 27151 damage. The flock swoops down less frequently as players slay the Soaring Eagles.
Tormenta eléctrica – Akil'zon immobilizes a random player in midair and creates a massive electrical storm for 8 sec. Players within 20 yards of the immobilized player are safe from the storm. Every second a player stands outside this safe distance, the storm inflicts 16000 Nature damage and increases Nature damage taken by 100% for 3 sec.

---

Secuestrador Amani: http://es.wowhead.com/npc=52638
- Invoca los pájaros pero no cogen a un jugador aleatorio para llevárselo ( Spell http://es.wowhead.com/spell=97318 )

Águila planeadora: http://es.wowhead.com/npc=24858
- Estos npc no aparecen durante el combate ( Spell de las águilas: http://es.wowhead.com/spell=44732 )

Spell: http://es.wowhead.com/spell=43657
- No es realizada.

**Comment by searum** [comment]
fix
