### ISSUE TITLE
Levantar a muerto - Death Knight

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#132]
Al usar el hechizo levantar a muerto, debe invocar un necrófago en forma de guardían, esto no sucede porque al hacer clic en el hechizo te pide "polvo de cadaver" que fue removido en el parche 4.0.3 de los vendedores.

Polvo de cadaver: http://es.wowhead.com/item=37201
Hechizo: http://es.wowhead.com/spell=46584

![wowscrnshot_070413_172744](https://f.cloud.github.com/assets/4663665/751309/7a309b5e-e4f1-11e2-924d-4c91f08b8afa.jpg)

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1

**Comment by ghost** [comment]
Ah perdón, lo cierro entonces.
