### ISSUE TITLE
Zul' Aman: Nalorakk

### ISSUE THREAD

**Issue by Mhryel** [RoDNet/Bugtracker-Infinium-4.3.4#1320]
2º Boss, Nalorakk: http://es.wowhead.com/npc=23576

---

Dinámica: 

Fase 1: ¡Dejad paso al Nalorakk!
Nalorakk begins the battle in troll form. He performs Brutal Strikes on the tank and periodically Surges toward the most distant enemy, leaving them vulnerable to additional Surges.
Golpe brutal – Nalorakk strikes his current target with a brutal attack that ignores armor, inflicting 78000 to 82000 Physical damage.
Oleada – Nalorakk charges the most distant enemy, inflicting 34125 to 35875 Physical damage. In addition, Physical damage dealt to the target increases by 500% for 20 sec.

Fase 2: Invocando a la bestia
Nalorakk transforms into a bear. In bear form he attacks the tank with two different bleed effects, Rend Flesh and Lacerating Slash. Nalorakk also lets loose with a Deafening Roar to briefly silence his enemies.
Descuartizar – Nalorakk rends the flesh of the target, inflicting 9950 Physical damage every 0.5 sec for 5 sec.
Tajo lacerante – Nalorakk slashes his current target and leaves a horrible bleeding wound, inflicting 22425 Physical damage every 3 seconds for 24 sec.
Rugido ensordecedor – Nalorakk lets loose a Deafening Roar, silencing his enemies for 2 sec.

---

Por ahora, cuando llegamos a él después de derrotar los adds del camino, no se activa.

**Comment by searum** [comment]
fix
