### ISSUE TITLE
Tier 12: Warlock

### ISSUE THREAD

**Issue by Mhryel** [RoDNet/Bugtracker-Infinium-4.3.4#1321]
El npc activado por el set de 2 piezas no tiene habilidades, pega a autattack melee, debiendo lanzar hechizos:

Diablillo ígneo: http://es.wowhead.com/npc=53491
Habilidades: 
- Explosión de llamas http://es.wowhead.com/spell=99226

La bonificación de 4 partes (http://es.wowhead.com/spell=99229) no funciona con el hechizo (http://wow.freakz.ro/spells.php?spell=1120).

**Comment by Compresor** [comment]
Beneficio de 2 partes del tier arreglado.
