### ISSUE TITLE
[Misión] El despertar: 24960

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1322]
Es la 3ª o 4ª misión de la zona de los no muertos...están casi todas bug.

http://es.wowhead.com/quest=24960/el-despertar

Los NPCs no aparecen dónde deberían. Además, he encontrado al primero arriba de la taberna, Lilian Voss pero le hablo y no se completa la parte de la misión.

**Comment by Kiritoo** [comment]
Cierro este issue ya que comentaste lo de Lilian Voss en el otro así ya consta.
Dejamos el otro por las fotos.
Un saludo.
