### ISSUE TITLE
Tier 12: Dk

### ISSUE THREAD

**Issue by Mhryel** [RoDNet/Bugtracker-Infinium-4.3.4#1324]
Versión Tanque:

Bonificación de 4 Piezas:
http://es.wowhead.com/spell=98966 
Cuando expira Arma de runa danzante ( http://es.wowhead.com/spell=49028 ) la bonificación no se activa nunca.

---

Versión Dps:

Bonus 2 Piezas: 
http://es.wowhead.com/spell=98970
Cuerno del invierno ( http://es.wowhead.com/spell=57330 ) no activa Runa humeante ( http://es.wowhead.com/spell=98971 ) 
Y no obtienes 3p. de poder rúnico cada 2 sec.

Sin embargo, se activa con cualquier ataque directo del Dk, aunque no produce ningún efecto de regeneración de Poder rúnico.

Bonus 4 Piezas: 
http://es.wowhead.com/spell=98996

Cuando golpeamos con Asolar ( http://es.wowhead.com/spell=49020 ) o Golpe de la plaga ( http://es.wowhead.com/spell=55090 ) no se inflinge al objetivo un 6% del daño como daño de fuego.

**Comment by Compresor** [comment]
Funcionan
