### ISSUE TITLE
Tier 12: Shaman

### ISSUE THREAD

**Issue by Mhryel** [RoDNet/Bugtracker-Infinium-4.3.4#1326]
Versión Dps Elemental:

Bonificación 2 Partes: 
http://es.wowhead.com/spell=99204
Descarga de relámpagos ( http://es.wowhead.com/spell=403 ) no acciona http://es.wowhead.com/spell=99202 y no reduce 4 sec el tiempo de reutilización de Totem elemental de fuego ( http://es.wowhead.com/spell=2894 )

Bonificación 4 Partes: 
http://es.wowhead.com/spell=99206
Oleada de lava ( http://es.wowhead.com/spell=77756 ) cuando salta no hace Ráfaga de lava ( http://es.wowhead.com/spell=51505 ) instantáneo.

Buff de oleada de lava instantáneo ( http://www.wowhead.com/spell=77762 o http://www.wowhead.com/spell=99207 no se cual de los 2 es )

---

Versión Dps Mejora: 

Bonus 2 Partes:
http://es.wowhead.com/spell=99209
Cuando el objetivo tiene dots de Llamas abrasadoras ( http://es.wowhead.com/spell=77657 ) no aumenta el daño de Latigazo de lava ( http://es.wowhead.com/spell=60103 )

Bonus 4 Partes:
http://es.wowhead.com/spell=99213
Cuando lanzas Golpe de tormenta sobre el objetivo ( http://es.wowhead.com/spell=17364 ) no recibe 6% de daño extra de las spells citadas.

---

Versión Restauración:

Bonus 2 Partes:
http://es.wowhead.com/spell=99190
Tu  Mareas vivas ( http://es.wowhead.com/spell=61295 ) nunca provoca Marea llameante ( http://es.wowhead.com/spell=99189 )

Bonus 4 Partes:
http://es.wowhead.com/spell=99195
Tu Sanación en cadena ( http://es.wowhead.com/spell=1064 ) elimina  Mareas vivas ( http://es.wowhead.com/spell=61295 ) no debiendo hacerlo.

**Comment by Compresor** [comment]
Funcionan
