### ISSUE TITLE
[mazmorra,raid] Baradin 10n

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1327]
Buenas:

-No hay mobs.
-Cuando Argaloth te mata, desaparece de su habitación y la puerta de abre.
- Podemos dar CC a los boss.

![wowscrnshot_081613_140922](https://f.cloud.github.com/assets/4790547/977822/a0f80b68-06ad-11e3-93cc-5393c658a374.jpg)
![wowscrnshot_081613_140917](https://f.cloud.github.com/assets/4790547/977823/a10cf410-06ad-11e3-9dbb-77b41bb49e42.jpg)
![wowscrnshot_081613_140938](https://f.cloud.github.com/assets/4790547/977824/a18eea74-06ad-11e3-9400-8074e8b57819.jpg)
![wowscrnshot_081613_140943](https://f.cloud.github.com/assets/4790547/977825/a1931d42-06ad-11e3-805e-57f13dae2e21.jpg)
![wowscrnshot_081613_141153](https://f.cloud.github.com/assets/4790547/977826/a1a9583c-06ad-11e3-8d32-90411f6c06a4.jpg)
![wowscrnshot_081613_140945](https://f.cloud.github.com/assets/4790547/977827/a1aed2f8-06ad-11e3-9d71-630ca4f5ace6.jpg)
![wowscrnshot_081613_141201](https://f.cloud.github.com/assets/4790547/977828/a1ddb2ee-06ad-11e3-8284-6de91f77b06e.jpg)
![wowscrnshot_081613_141203](https://f.cloud.github.com/assets/4790547/977829/a1e36ab8-06ad-11e3-91d0-39dc9fd2f884.jpg)
![wowscrnshot_081613_141222](https://f.cloud.github.com/assets/4790547/977830/a1e31ed2-06ad-11e3-955f-9a17b6a3179f.jpg)

**Comment by efectokoleos** [comment]
argaloth lo q hace cuando wipeas es despawnearse y reaparecer al minuto xd lo de los ccsvoya mirarlo

**Comment by lamaza** [comment]
Ah oks Koleos gracias

**Comment by efectokoleos** [comment]
a occuthar lo hemos quitado de momento, el otro ya no se puede ccear
