### ISSUE TITLE
[Mago] Fuego Habilidades bug

### ISSUE THREAD

**Issue by hotkiss** [RoDNet/Bugtracker-Infinium-4.3.4#133]
La habilidad y talento [ Impacto] No reparte el daño de fuego a sus alrededor y la Piroexplosion instantanea y el daño del tick  no ace su daño normal , Gracias

**Comment by searum** [comment]
No me vale este reporte, no hay links ni nada ni aportas datos de cuanto daño hace y deberia hacer. Curratelo un poco mas en otro issue please
