### ISSUE TITLE
Boss Descenso de Alanegra: Atrámedes

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1330]
ID: http://es.wowhead.com/npc=41442/atramedes

Al usar uno de los diez Escudos enanos antiguos http://es.wowhead.com/npc=42960 debería accionarse la spell http://es.wowhead.com/spell=77611 (la cual interrumpe el casteo de Atrámedes, y reinicia a 0 el nivel de sonido de todos los miembros de la banda). Además al usar un escudo, éste desaparece, no pudiendo volver a ser usado durante ese combate (a no ser que haya wipe).

En la actualidad no está sucediendo nada al utilizar un escudo

**Comment by efectokoleos** [comment]
ahora deberia hacer la spell
