### ISSUE TITLE
BUG misiones principales de los NO MUERTOS.

### ISSUE THREAD

**Issue by jurareporterobug** [RoDNet/Bugtracker-Infinium-4.3.4#1331]
La cosa es clara.. empiezo a jugar con un No Muerto.. voy hacia mi segunda mision .. la cual me la concede este señor...

![wowscrnshot_081713_103400](https://f.cloud.github.com/assets/5250663/981070/172a99c4-0742-11e3-8227-552a6252a74b.jpg)

me voy en busca de los 3 NPC que "supuestamente" deberian estar en el cementerio..

![wowscrnshot_081713_103515](https://f.cloud.github.com/assets/5250663/981071/2db04d60-0742-11e3-947e-931cf169dad7.jpg)
![wowscrnshot_081713_103526](https://f.cloud.github.com/assets/5250663/981072/31e410c4-0742-11e3-86e8-3238d08292b0.jpg)
![wowscrnshot_081713_103536](https://f.cloud.github.com/assets/5250663/981073/3624ba6c-0742-11e3-8b72-89bda5b7b426.jpg)

No estan ahi... creo que las misiones del hilo principal de la historia deberian estar en PRIMER PLANO en solucion de bugs porque es ESCENCIAL para el juego en si..

muchas gracias .. y espero que lean y solucionen mi peticion para bien del servidor y de sus usuarios..

AQUI EL ENLACE DE WOWHEAD

http://es.wowhead.com/quest=24960

**Comment by ghost** [comment]
Ya está reportado, se puede cerrar uno de los dos (el mio no tiene fotos), pero añado que los NPCs no sólo no aparecen dónde deberían, he encontrado al primero arriba de la taberna, Lilian Voss pero le hablo y no se completa la parte de la misión.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1322

**Comment by jurareporterobug** [comment]
Me acabo de crear un brujo no -muerto y ahora si aparecen.. no se si es problema solo del Dk .. o de todas la clases de no muerto.. parece ser que lo solucionaron.. pero no cerraron el bug aqui :+1:

**Comment by searum** [comment]
fixed
