### ISSUE TITLE
BUG misiones principales de los NO MUERTOS. parte 2

### ISSUE THREAD

**Issue by jurareporterobug** [RoDNet/Bugtracker-Infinium-4.3.4#1332]
Cuando llego a "Camposanto" me aparecen estas supuestas misiones.. las cuales no lo son ya que solamente me muestra el icono de mision.. cuando hablo con ellos no tienen absolutamente nada..

![wowscrnshot_081713_105337](https://f.cloud.github.com/assets/5250663/981108/fe3665da-0744-11e3-8aba-3a7be654e71f.jpg)
![wowscrnshot_081713_105342](https://f.cloud.github.com/assets/5250663/981109/fe598a10-0744-11e3-8b4b-1ee609f864f1.jpg)
![wowscrnshot_081713_105347](https://f.cloud.github.com/assets/5250663/981110/fe7cc142-0744-11e3-8c56-b8f866f3a674.jpg)
![wowscrnshot_081713_105350](https://f.cloud.github.com/assets/5250663/981111/fe8c1066-0744-11e3-9d94-f5a2259cdc65.jpg)
![wowscrnshot_081713_105353](https://f.cloud.github.com/assets/5250663/981112/fe8c7b64-0744-11e3-8fd1-a7492f6034c7.jpg)
![wowscrnshot_081713_105408](https://f.cloud.github.com/assets/5250663/981113/fe9734c8-0744-11e3-93cd-76e3a5455ce2.jpg)

ESPERO QUE SOLUCIONEN ESTO.. MUCHAS GRACIAS

**Comment by Kiritoo** [comment]
Hola @jurareporterobug  estan bien los reportes con fotos y tal pero te importaría añadir enlaces de las misiones y los npcs de wowhead.
Graciass.

**Comment by jurareporterobug** [comment]
Te digo la verdad ... no se el nombre de todas esas misiones bugueadas.. directamente son todas las de camposanto

**Comment by jurareporterobug** [comment]
ademas.. si soy mago.. no deberia aparecerme ninguna mision de otra clase.. solamente la del mago y una que otra de la cabaña de la ultima foto

**Comment by jurareporterobug** [comment]
ademas en wowhead .. esta actualizado a "mist of pandaria" asi que tmpoco te puedo poner esos enlaces ya q las misiones fueron modificadas.

**Comment by Kiritoo** [comment]
Hola lo primero refiriendote a eres mago y dices que no te deberian salir misiones de otra clase no te salen yo no veo que puedas cojer mision en el instructor de picaros.
Y en wowhead hay una seccion antigua para cojer las ids de las misión además añadir que muchas de ellas por no decir casi todas las misiones tienen la misma id.
Saludos.

**Comment by jurareporterobug** [comment]
claro que no puedo cojer la mision de instructor de picaros.. pero que hace entonces esa exclamasion en amarillo.. no deberia estar si no da una mision para mi PJ

**Comment by jurareporterobug** [comment]
he jugado al servidor oficial.. y en ese no aparecen signos de exclamacion arriba de alguien que no te da una mision

**Comment by Kiritoo** [comment]
Cierto es que no debe salir esa exclamacion, pero tampoco es verdad que te aparece la misión de otra clase, solo te sale una exclamación.

**Comment by jurareporterobug** [comment]
en vez de perder tiempo en una discucion absurda.. podrian ponerse a trabajar en la resolucion de bugs,, ya les di una idea.. eso es lo que necesitan.. el bug lo van a encontrar solo

**Comment by searum** [comment]
Si quieres exigir algo te recomiendo jugar en este servidor: http://us.battle.net/wow/es/ ya que a nosotros no nos pagan por trabajar ;)

**Comment by jurareporterobug** [comment]
No entiendo para que abren una seccion de BUGS .. si no les gusta que la gente comente que los hay.. yo no exijo nada .. solamente colaboro...

**Comment by jurareporterobug** [comment]
me gustaria colaborar con su servidor
en el tema de resolucion de bugs

**Comment by searum** [comment]
Pues es que el tema de "podrian ponerse a trabajar en la resolucion de bugs" ya lo conocemos de sobra, ahi tienes 440 bugs abiertos y 906 cerrados en un mes y poco... Y como comprenderas no hace mucha gracia que alguien te hable asi.

Si quieres colaborar reparando bugs perfecto, que conocimientos tienes?

**Comment by jurareporterobug** [comment]
hablando de programacion nada!! pero hablo de colaborar manejando a las personas que hagan reclamos sobre bugs.. eso me gustaria..

**Comment by jurareporterobug** [comment]
o simplemente desde este pequeño lugar , comentarles y subir bugs para que ustedes si pueden lo reparen

**Comment by jurareporterobug** [comment]
no quise ofender a nadie.. disculpen si me hice mal entender.. solo quiero colaborar.. sino no perderia mi tiempo subiendo los bugs

**Comment by searum** [comment]
reportando bugs ayudas pero trata de intentar tener paciencia porque te recuerdo que es un servidor de wow donde hay miles de quests, miles de npcs, miles de spells y nosotros tratamos de ir arreglando todo pero tampoco somos maquinas y tenemos nuestra vida, si te dicen que pongas los enlaces a las quests y tal es porque asi el tiempo que invertimos en ir al juego a mirar dichos bugs lo podemos invertir en arreglar otra quest si ya disponemos de los datos necesarios no tenemos ni que entrar al juego a mirar que le pasa, como funciona, que tenemos que arreglar... no se si me entiendes ^^

**Comment by lamaza** [comment]
manera correcta de usar el BT:

-1 issue por bug: -X objeto no sirve - x mision no sirve - X montura no sirve - x evento no sirve.
-Tratar de no generar polémica en los temas.
-Cada issue o reporte deberia contener: -Problema -IDs del problema involucradas -Fotos o video -Concluciones o saludos o lo que quieras.
-Un título bien descriptivo y objetivo.

Las ids de hechizos,objetos y otras cosas (y deben ser de Cataclysm, no de pandaren) las sacas con el addon de idtip (http://www.curse.com/addons/wow/spellid/538476 ) y de wowhead.com.

En el caso de este NPJ Isabella (magos), deberia de dar las siguientes 2 quest:

http://es.wowhead.com/npc=2124/isabella

http://es.wowhead.com/quest=24965
http://es.wowhead.com/quest=28651

Eso es todo =) Saludos GMs /Devs.

Bye =)

**Comment by searum** [comment]
fixed
