### ISSUE TITLE
[Castillo Colmilloscuro] Barón Ashbury

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1334]
ID: http://es.wowhead.com/npc=46962/baron-ashbury

El boss tras usar Asfixiar nos deja 1p de vida es normal inmediatamente despues de usar Asfixiar deberia de usar Ejecucion pospuesta que nos cura 10% cada segundo

Bueno el caso es que Tras usar Asfixiar y tener 1p de vida el boss nos da una cachetada y morimos :l no sigue la secuencia ps Asfixiar - Ejecucion Pospuesta en ves eso hace es Asfixiar - Cachetada - Ejecucion Pospuesta

ID skill: 
Asfixiar: http://es.wowhead.com/spell=93423
Ejecucion Pospuesta: http://es.wowhead.com/spell=93468

**Comment by efectokoleos** [comment]
fixed
