### ISSUE TITLE
BUG Mision del Hermano Paxton (Humanos) "No temerás peligro alguno"

### ISSUE THREAD

**Issue by jurareporterobug** [RoDNet/Bugtracker-Infinium-4.3.4#1337]
Es una de las misiones de la zona inicial cuando te creas un humano.. supuestamente debes hablar con el "hermano paxton" y este te dara un libro sagrado.. con el cual reviviras a los soldados caidos en combate..

![wowscrnshot_081713_113033](https://f.cloud.github.com/assets/5250663/981174/ff17962c-0749-11e3-893c-63d8f3eb4dd6.jpg)
![wowscrnshot_081713_113026](https://f.cloud.github.com/assets/5250663/981175/ff18c79a-0749-11e3-9f0c-f78773bc0b2c.jpg)
![wowscrnshot_081713_113052](https://f.cloud.github.com/assets/5250663/981176/ff232636-0749-11e3-8fa8-739a8cf49682.jpg)
![wowscrnshot_081713_113048](https://f.cloud.github.com/assets/5250663/981177/ff285e1c-0749-11e3-96cc-fb4aab7c2717.jpg)

http://es.wowhead.com/quest=28813

1- APENSA HABLAS CON EL HERMANO PAXTON , ESTE DA POR ACEPTADA LA MISION... EN NINGUN MOMENTO ACEPTE NADA..
2- EL HUD DE MISIONES MUESTRA 0/4 DE SOLDADOS REVIVIDOS.. Y DEBAJO DICE "VUELVE CON EL HERMANO PAXTON"
3- NO PUEDES REVIVIR A NINGUN SOLDADO.. NI SIQUIERA CAMBIA EL ICONO DEL MOUSE CUANDO PASAS POR ENCIMA DEL CAIDO.
4- SI VUELVES A HABLAR CON EL HERMANO PAXTON , ESTE TE CONTESTA CUALQUIER COSA...

ESPERO QUE AYUDE ... MUCHAS GRACIAS..

**Comment by Kiritoo** [comment]
Fix
