### ISSUE TITLE
Tier 12: Mage

### ISSUE THREAD

**Issue by Mhryel** [RoDNet/Bugtracker-Infinium-4.3.4#1338]
Bonus 2 Partes:
http://es.wowhead.com/spell=99061
Tus ataques invocan un npc invisible ( debería verse como tus reflejos exactos de mago ) 
Spell de reflejo exacto :http://es.wowhead.com/spell=99063  Esta spell invoca http://es.wowhead.com/npc=53438 y debe tener la habilidad Bola de fuego ( http://es.wowhead.com/spell=99062 ). Actualmente pega cuerpo a cuerpo.

**Comment by redneo** [comment]
Parcialmente arreglado, en el server ptr va bien, solo tira una bola de fuego, pero va mas o menos bien. 

En Infinium, no se como saldrá ya que cambie la skin del npc para poderse ver.... a ver cuando se reinicie el server.
