### ISSUE TITLE
Misiones Bug: Mil agujas

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#134]
Mision: Liberalos

Hay que liverar a 10 presos pero cuando les abres las puertas no se liveran y no se completa la mision

Mision: ¡Detras de ti!

Hay que ponerse un disfraz y hablar con tres elites y a la que se dan la espalda matarlos pero no se puede dialogar con ellos

**Comment by SherBlader** [comment]
Recomendable linkear las misiones y capturas de pantalla.

**Comment by frustrix** [comment]
Misiones capturas:

![wowscrnshot_070513_235351](https://f.cloud.github.com/assets/4893907/755703/e0a19c2c-e5bd-11e2-944c-371bfd06dd52.jpg)

-Liberalos!

![wowscrnshot_070513_235431](https://f.cloud.github.com/assets/4893907/755704/efac6814-e5bd-11e2-8591-5763f086b245.jpg)

-Detras de ti!

![wowscrnshot_070513_235513](https://f.cloud.github.com/assets/4893907/755706/0d762506-e5be-11e2-91b0-dbba343f4557.jpg)

Mision: Libera a los lechigados

Hay que desatar a los bichillos que hay atrapados en el suelo y no se puede no hay opcion

Mision: libera a Cuorevaja

Hay que desatar a cueorevaja pero no hay opcion ni metodo

*Las fotos a continuacion

![wowscrnshot_070513_234559](https://f.cloud.github.com/assets/4893907/755707/38160312-e5be-11e2-8bad-9ca5e1569c1e.jpg)

![wowscrnshot_070513_234336](https://f.cloud.github.com/assets/4893907/755710/531764c6-e5be-11e2-9062-ce815ac0923f.jpg)

![wowscrnshot_070513_235351](https://f.cloud.github.com/assets/4893907/755713/6922b1f8-e5be-11e2-8f23-348cd4743904.jpg)

![wowscrnshot_070513_234615](https://f.cloud.github.com/assets/4893907/755714/7546791a-e5be-11e2-8d41-1f99175c94e2.jpg)

**Comment by frustrix** [comment]
Cuando mueres puedes caminar como los dk por el agua(lo se en fantasma puedes andar por el agua pero esto es al resucitar)

Foto:

![Uploading WoWScrnShot_070513_235607.jpg . . .]()

**Comment by frustrix** [comment]
![wowscrnshot_070513_235607](https://f.cloud.github.com/assets/4893907/755733/7dcf5bbe-e5bf-11e2-8549-03d40abfd303.jpg)

**Comment by frustrix** [comment]
Zona: Barcodromo 

algunos NPC y tripulantes son hostiles y no puedes coger las misiones a menos que los mates a todos pero 1 solo  de este lvl es complicado matar a todos a la vez por lo cual no se pueden coger las misiones y completarlas adecuadamente es muy dificil

![wowscrnshot_070613_001602](https://f.cloud.github.com/assets/4893907/755752/f68df4ba-e5c0-11e2-8414-26a827cb46df.jpg)

si miras al fondo veras que hay mision pero esta lleno de tripulantes hostiles:

![wowscrnshot_070613_001959](https://f.cloud.github.com/assets/4893907/755756/29687234-e5c1-11e2-935a-de7a032a15db.jpg)

**Comment by frustrix** [comment]
mision: Pelea en el bar

hay que comprar una botella y darle en la cabeza a uno con ella pero no vende nadie la botella ni tabernera ni nada

![wowscrnshot_070613_003310](https://f.cloud.github.com/assets/4893907/755789/0e366c62-e5c3-11e2-9bcf-238d27488d5f.jpg)
![wowscrnshot_070613_003324](https://f.cloud.github.com/assets/4893907/755791/1610f844-e5c3-11e2-80ed-6422ec1e7bd3.jpg)

**Comment by frustrix** [comment]
mision: Todo el mundo se muere por un Helado

Hay que enganchar con un supuesto cable a los empleados muertos pero no se puede hacer ya que no te dan ni cable ni opcion para hacerlo

![wowscrnshot_070613_004710](https://f.cloud.github.com/assets/4893907/755816/325cb842-e5c5-11e2-9b89-217c3d03697f.jpg)
![wowscrnshot_070613_005015](https://f.cloud.github.com/assets/4893907/755817/4b13ad28-e5c5-11e2-9adb-d689b24b7f80.jpg)

**Comment by frustrix** [comment]
Mision:Congelar las tuberias

Hay que congelar 4 tuberias con un aparato que te dan,
el aparato actua y en teoria los congela pero no cuentan y no puedes completar la mision 

![wowscrnshot_070613_005725](https://f.cloud.github.com/assets/4893907/755834/7946d570-e5c6-11e2-97d5-b548860fd078.jpg)

![wowscrnshot_070613_005912](https://f.cloud.github.com/assets/4893907/755835/8c7fa626-e5c6-11e2-9d60-5e7220403883.jpg)

**Comment by frustrix** [comment]
Mision : ve con zherin!

![wowscrnshot_070713_202717](https://f.cloud.github.com/assets/4893907/758454/4c537212-e733-11e2-9937-6fa6bede2377.jpg)

hay que darle una pequeña paliza sin llegar a matarle pero no reacciona y no cumples la mision por mucho que te dejes pegar no reaciona ver vida en foto

![wowscrnshot_070713_202738](https://f.cloud.github.com/assets/4893907/758455/63a2e196-e733-11e2-98df-e8da6d04d75e.jpg)

**Comment by frustrix** [comment]
mision: Toca el cuerno

![wowscrnshot_070713_203923](https://f.cloud.github.com/assets/4893907/758465/a5a1c9a8-e734-11e2-903e-2a6ecb763318.jpg)

hay que tocar el cuerno y que aparezca un elemental de aire para matarlo pero no aparece

![Uploading WoWScrnShot_070713_203911.jpg . . .]()

**Comment by frustrix** [comment]
![wowscrnshot_070713_203911](https://f.cloud.github.com/assets/4893907/758468/cd1f9136-e734-11e2-8ce9-4c6f029a053f.jpg)

**Comment by frustrix** [comment]
Mision: Rodea las carretas... eh, las barcas

![wowscrnshot_070713_210401](https://f.cloud.github.com/assets/4893907/758501/1d0bfa74-e738-11e2-8268-ae404b02f23d.jpg)

hay que montar en un barco y pilotarlo para undir unas barquitas pero no te mandan alli ya que es automatico

![wowscrnshot_070713_210351](https://f.cloud.github.com/assets/4893907/758504/457a26ac-e738-11e2-8982-29c46057f674.jpg)

Enlace youtube de lo que hay que hacer en la mision
http://www.youtube.com/watch?v=1WK_OfbVJ6E

**Comment by frustrix** [comment]
![wowscrnshot_070713_211014](https://f.cloud.github.com/assets/4893907/758514/06037df6-e739-11e2-922b-0b8ae378ae03.jpg)

mezer quitaclavos no te lleva a ningun lado porque me lo preguntareis

**Comment by ghost** [comment]
@frustrix podrías reportar de nuevo, poniendo cada misión bug en un reporte a parte?, para facilitarle la vida a los devs y que puedan arreglarte las misiones, muchas gracias.
