### ISSUE TITLE
Bug Chaman Maestria

### ISSUE THREAD

**Issue by kirgar** [RoDNet/Bugtracker-Infinium-4.3.4#1340]
Maestria Sobrecarga Elemental id:77222 http://es.wowhead.com/spell=77222

La Maestria se activa con rafaga de lava pero con descarga de relampagos o cadena de relampagos no y deberia activarse. La rafaga de lava solo se refleja en el daño no se ve la doble rafaga de lava os pongo 1 video de como se veria la maestria del chaman rayos.
http://www.youtube.com/watch?v=9U4grZrHlPI

**Comment by searum** [comment]
fix falta aplicarlo
