### ISSUE TITLE
[Zul´Aman] Npc que pegan poco

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1341]
Los siguientes Npc estan pegando como si fueran de nivel low (500-700) cada golpe. pude tankear 20 npc al mismo tiempo sin que me bajaran un 10%

Npc: 
http://es.wowhead.com/npc=24043
http://es.wowhead.com/npc=24180
http://es.wowhead.com/npc=24175
http://es.wowhead.com/npc=24179
http://es.wowhead.com/npc=24549
es.wowhead.com/npc=23584
http://es.wowhead.com/npc=23580
http://es.wowhead.com/npc=23597
http://es.wowhead.com/npc=52958
http://es.wowhead.com/npc=24374
http://es.wowhead.com/npc=23597

**Comment by Mhryel** [comment]
Se conoce que hay un problema con la armadura, que reduce más de lo que debe, quizá en parte sea por eso.

**Comment by redneo** [comment]
No. Era un problema de estadísticaS. Creo que se solucionó.
