### ISSUE TITLE
Bug Colera Totemica

### ISSUE THREAD

**Issue by kirgar** [RoDNet/Bugtracker-Infinium-4.3.4#1342]
Bug el Talento Colera Totemica id:77746 http://es.wowhead.com/spell=77747/colera-ardiente
El Talento Colera totemica pone el bufo de poder de hechizos pero no sube el poder de hechizos aunque este el totem de fuego puesto.
<a href="http://www.subirimagenes.net/i/130817073542550891.jpg" target="_blank" title="subir imagen"><img src="http://sia1.subirimagenes.net/img/2013/08/17/mini_130817073542550891.jpg" border="0" alt="subir imagenes" /></a>
<a href="http://www.subirimagenes.net/i/13081707382537902.jpg" target="_blank" title="subir imagen"><img src="http://sia1.subirimagenes.net/img/2013/08/17/mini_13081707382537902.jpg" border="0" alt="subir imagenes" /></a>
Cuando pones los cuatro totems y lo sustituyes por uno o te eliminan 1 totem ya no esta el buffo de la colera totemica.
<a href="http://www.subirimagenes.net/i/130817074056134991.jpg" target="_blank" title="subir imagen"><img src="http://sia1.subirimagenes.net/img/2013/08/17/mini_130817074056134991.jpg" border="0" alt="subir imagenes" /></a>
<a href="http://www.subirimagenes.net/i/130817074124868273.jpg" target="_blank" title="subir imagen"><img src="http://sia1.subirimagenes.net/img/2013/08/17/mini_130817074124868273.jpg" border="0" alt="subir imagenes" /></a>

**Comment by searum** [comment]
fix
