### ISSUE TITLE
[Decenso de alanegra] Sistema de defensa Omnitron

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1344]
Los Golem deberian de turnarse cada cierto tiempo el caso es que los 4 golem estan siempre activados y logicamente 4 boss vs 10.... es wipe

Los golem tienen energia que los activa y desactiva dependiendo de cuanta tengan: 

   100 puntos = Golem recién activado
    50 puntos = Se activa un nuevo golem
    45 puntos = El golem activa su escudo
    25 puntos = Se desactiva el escudo del golem
    0 puntos = El golem se desactiva, se convierte en piedra y no puede ser marcado

El caso es que al llegar a 0 de energia nunca se desactivan se quedan hay combatiendo...

ID de boss: 
Electron: http://es.wowhead.com/npc=42179#
Arcanotron: http://es.wowhead.com/npc=42166
Magmatron: http://es.wowhead.com/npc=42178
Toxitron:http://es.wowhead.com/npc=42180

ID de Energia: http://es.wowhead.com/spell=78740
ID de apagar golem: http://es.wowhead.com/spell=78746

**Comment by efectokoleos** [comment]
fixed!
