### ISSUE TITLE
Bug filones de cobre

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1346]
http://es.wowhead.com/object=1731/filon-de-cobre
Las piedras ahi puestas tienen un rate de drop basico del juego oficial
Pero yo he mineado mas de 90 filones y no he recibido ni una sola piedra.
Y asi es imposible subir al principio ingenieria ya que necesitas piedras desde el principio.

**Comment by Kiritoo** [comment]
Fix
