### ISSUE TITLE
Logro de Hermandad

### ISSUE THREAD

**Issue by kirgar** [RoDNet/Bugtracker-Infinium-4.3.4#1347]
Hemos hecho Cumbre Roca Negra 4 miembros de la misma hermandad y nos a dado solo el logro de haberla hecho nosotros pero no el de hermandad y tampoco dan reputacion los bosses.
<a href="http://www.subirimagenes.net/i/130818025637598861.jpg" target="_blank" title="subir imagen"><img src="http://sia1.subirimagenes.net/img/2013/08/18/mini_130818025637598861.jpg" border="0" alt="subir imagenes" /></a>

**Comment by Kiritoo** [comment]
Hola Kirgar puedes añadir el id del logro que debería daros.
Y también la cantidad de reputación y el tipo de reputación que deberían dar los boss más las ids.

Muchas gracias, saludos.

**Comment by kirgar** [comment]
Reputacion de hermandad: http://es.wowhead.com/achievement=5794#comments
Logro de hermandad cumbre roca negra:http://es.wowhead.com/achievement=5052/hermandad-en-cumbre-de-roca-negra-inferior#criteria-of
id de bosses: 
http://es.wowhead.com/npc=9568#screenshots
http://es.wowhead.com/npc=9196
http://es.wowhead.com/npc=9236
http://es.wowhead.com/npc=9237
http://es.wowhead.com/npc=10596/madre-telabrasada
http://es.wowhead.com/npc=10584
http://es.wowhead.com/npc=9736
http://es.wowhead.com/npc=10220
http://es.wowhead.com/npc=10268

En cuanto a que cantidad de puntos deberian dar no sabria decirlo a nivel bajo cuanto dan.
Pero las reputaciones en mazzmorra no es solo esta no dan ninguna aunque haya 3 de la misma hermandad

**Comment by searum** [comment]
repetido y poca informacion
