### ISSUE TITLE
Logro Jenkins

### ISSUE THREAD

**Issue by kirgar** [RoDNet/Bugtracker-Infinium-4.3.4#1348]
Bueno ivamos hacer el logro Leeeeeeeroy! pero al darle a los huevos para que salieran los dragoncitos pal logro no salian.
Logro Leeeeeroy!: http://es.wowhead.com/achievement=2188/leeeeeeeeeeeeeroy
Cria de El Grajero: http://es.wowhead.com/npc=10161
<a href="http://www.subirimagenes.net/i/130818025955479223.jpg" target="_blank" title="subir imagen"><img src="http://sia1.subirimagenes.net/img/2013/08/18/mini_130818025955479223.jpg" border="0" alt="subir imagenes" /></a>
<a href="http://www.subirimagenes.net/i/130818030025181890.jpg" target="_blank" title="subir imagen"><img src="http://sia1.subirimagenes.net/img/2013/08/18/mini_130818030025181890.jpg" border="0" alt="subir imagenes" /></a>

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/701?source=cc
Ya reportado, cierro issue.
Gracias por el reporte.
