### ISSUE TITLE
BUG "La Carta Escarlata" No Funciona

### ISSUE THREAD

**Issue by jurareporterobug** [RoDNet/Bugtracker-Infinium-4.3.4#1349]
Hola chicos aca le traigo otro bug que encontre en una mision .. se trata de "La carta escarlata" en esta mision hay que encontrar a una prisionera que esta arriba en lo alto de esa torre... cuando le hablamos a esa chica aparece un guardia .. el cual no podemos atacar ni hablar y este comienza a charlar con la chica e intenta matarla.. y esa chica reacciona con un poder magico y pulveriza a este guardia.. y ahi termina esa mision.. por lo menos estaria bueno darla por terminada y que nos de la recompenza original.. 

MUCHAS GRACIAS.. A CONTINUACION LES DEJO FOTOS Y EL LINK DE LA MISION EN WOWHEAD.

![wowscrnshot_081813_020145](https://f.cloud.github.com/assets/5250663/982088/f79104e0-07c3-11e3-8b05-01b5ce2f361d.jpg)
![wowscrnshot_081813_020151](https://f.cloud.github.com/assets/5250663/982089/f7968cda-07c3-11e3-9e74-9e0b6f293e11.jpg)
![wowscrnshot_081813_020159](https://f.cloud.github.com/assets/5250663/982090/f798a61e-07c3-11e3-8bbe-54e29693ed66.jpg)

http://es.wowhead.com/quest=24979#comments

**Comment by Kiritoo** [comment]
Fix, falta aplicarlo.
