### ISSUE TITLE
Cumbres gemelas (campo de batalla)

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.3.4#135]
el buff de rabiar sigue estando activo una vez lo cojes i puedes renovarte el bufo todas las veces que quieras por que no desaparece.

http://subefotos.com/ver/?f984368de31ab29a80af13f29564863eo.jpg#codigos

las banderas hay ratos que no se pueden cojer,sale la tuerca para robar la bandera pero no te da la bandera para salir corriendo.ya habiamos metido dos banderas antes de bugearse

http://subefotos.com/ver/?10d89bc967acdbe038518122f59db1c8o.jpg#codigos

donde salen las estadisticas de daño i nombres de los jugadores que estan en la bg no aparece nada,esto pasa en todas las bgs i no siempre unas veces sale i otras no.

lo mismo pasa con el contador de banderas i tiempo restante unas veces sale i otras no sale

las puertas de la base no aparecen i mientras esta en tiempo de preparacion te puedes salir de la base

**Comment by Kiritoo** [comment]
"el buff de rabiar sigue estando activo una vez lo cojes i puedes renovarte el bufo todas las veces que quieras por que no desaparece."

Se acaba de fixear el sprint del lado horda que se podia cojer continuo.
