### ISSUE TITLE
BUG "PNJ" "Gordo" No funciona

### ISSUE THREAD

**Issue by jurareporterobug** [RoDNet/Bugtracker-Infinium-4.3.4#1350]
Aqui encontre otro bug .. este pnj deberia vendernos cierta mercancia y ademas repararnos la armadura.. como pueden ver en wowhead la data de este pnj

espero que sirva, muchas gracias 

![wowscrnshot_081813_021037](https://f.cloud.github.com/assets/5250663/982093/0401e31a-07c5-11e3-9435-2afb5b629376.jpg)

http://es.wowhead.com/npc=10666#sells

**Comment by Kiritoo** [comment]
Fix
