### ISSUE TITLE
BUG "100 Años De Soledad" No Funciona

### ISSUE THREAD

**Issue by jurareporterobug** [RoDNet/Bugtracker-Infinium-4.3.4#1352]
En esta mision supuestamente debes debilitar a un murloc y usar una soga para atraparlo y luego llevarlo con un anciano solitario como mascota
no puedas atraparlo nunca con la soga..ahi esta el bug.. imposible finalizar la mision

http://es.wowhead.com/quest=24974

![wowscrnshot_081813_022444](https://f.cloud.github.com/assets/5250663/982104/bf647450-07c6-11e3-877d-a4c45edb2d0a.jpg)

**Comment by lamaza** [comment]
Increible la referencia a Macondo.
http://bimg2.mlstatic.com/cien-anos-de-soledad-gabriel-garcia-marquez_MLA-F-123243241_8115.jpg

**Comment by jurareporterobug** [comment]
jajaa estos del wow son muy cultos :P

**Comment by ghost** [comment]
Ya está reportado, se puede cerrar.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1323
