### ISSUE TITLE
BUG "La Variedad Es La Sal De La Muerte" No Funciona

### ISSUE THREAD

**Issue by jurareporterobug** [RoDNet/Bugtracker-Infinium-4.3.4#1353]
En esta mision debes recojer ciertos elementos... de los cuales el primer elemento es este gusano.. que no te lo deja agarrar.. de ahi en mas.. la mision no puede continuar..

![wowscrnshot_081813_022901](https://f.cloud.github.com/assets/5250663/982107/5c964096-07c7-11e3-8faa-f59d37725122.jpg)

http://es.wowhead.com/quest=24976

**Comment by ghost** [comment]
Está reportado ya...mírate los reportes antes de postear para no dar trabajo doble. Además, yo también estoy leveando un no muerto asíque la mayoría serán repetidas.

Y procura hacer el título algo más organizado, se entiende que todo lo que postees aquí sera un bug así que no hace falta que pongas BUG. En su lugar, pon de qué tipo como los demás, yo suelo poner [Misión] Nombre : ID.

Saludos!

**Comment by jurareporterobug** [comment]
okaa , anotando consejos :D

**Comment by ghost** [comment]
:D 

Ahora que ya sabes que hay varios repetidos, dale a Close y así se eliminan de la lista de bugs abiertos, así no están dobles.

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1325?source=cc 
Ya reportamos seguimos desde el primer reporte.
Saludos.
