### ISSUE TITLE
[Vendedor] (Monturas Goblin): Kall Valemil <Vendedor de triciclos>

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#1354]
Vendedor: http://es.wowhead.com/npc=48510

Bug: Permite a cualquiera comprar las monturas, solo debería permitirselo a los Goblin, las demás razas tienen que ser exaltados con el Cártel Pantoque (http://es.wowhead.com/faction=1133).

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
