### ISSUE TITLE
[mazmorras,npj] rencor abisal Karahzan

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1356]
http://es.wowhead.com/npc=15689#abilities

Este boss es inmortal, lo que le bajas, el se lo cura en 1 segundo. Es el boss final, da logro.

El problema esta en sus habilidades, no se ven. Ninguno de los portales y sobretodo el que lo cura http://es.wowhead.com/spell=30467, son cosas invisibles, no sabemos dodne esta para alejarlo.

![wowscrnshot_081813_152147](https://f.cloud.github.com/assets/4790547/983176/e81c416e-0845-11e3-8e04-0121ca83fed6.jpg)

**Comment by hairblood** [comment]
se supone que deberian estar en la entrada de la sala

**Comment by Mhryel** [comment]
1 - No es el boss final, el Boss final es Príncipe Malchezarr: http://es.wowhead.com/npc=15690
2 - Ese boss no debe dar logro, Malchezaar Sí.

**Comment by lamaza** [comment]
Tienes razón, y al final creo que no se puede llegar debido a https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1357

**Comment by efectokoleos** [comment]
puf el tablerito me da k va a ser un reto scriptarlo xd pero bueno habra k ponerse con ello, k es mi instance favorita XD
