### ISSUE TITLE
[Mazmorra] Zul'Gurub

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#136]
La Mazmorra Zul'Gurub Tiene una serie de bugs, de los cuales nombrare los que pude hallar.
http://es.wowhead.com/zone=1977

Los mobs hacen -1 de daño
![wowscrnshot_070413_164516](https://f.cloud.github.com/assets/4895839/751513/a28be99c-e4ff-11e2-8956-6364dba2a9a9.jpg)

![wowscrnshot_070413_164531](https://f.cloud.github.com/assets/4895839/751518/f1c0c9a6-e4ff-11e2-8875-c20115326921.jpg)

Con suerte -2
![wowscrnshot_070413_164836](https://f.cloud.github.com/assets/4895839/751519/05966a76-e500-11e2-88eb-de4abed580a7.jpg)

Incluso los bosses hacen -1 de daño (http://es.wowhead.com/npc=52059)
![wowscrnshot_070413_171837](https://f.cloud.github.com/assets/4895839/751526/3be4dc5c-e500-11e2-879a-d68c448af8b5.jpg)

Caen Epicos, lo que hace estos boss piñata y cualquiera se puede aprovechar para ganar epicos
![wowscrnshot_070413_173808](https://f.cloud.github.com/assets/4895839/751532/789e6dc0-e500-11e2-8e50-6499c3c84ed2.jpg)

Hay una especie de barrera que no se deberia dejar cruzar, sin embargo se puede cruzar
![wowscrnshot_070413_172541](https://f.cloud.github.com/assets/4895839/751534/913bada2-e500-11e2-8dd4-8b648c4e94cf.jpg)

Otro epico de un mob piñata
![wowscrnshot_070413_174141](https://f.cloud.github.com/assets/4895839/751535/ac108d5a-e500-11e2-8482-4c1a55d601d4.jpg)

El daño de -1 y -2 sucede con todos los bosses (http://es.wowhead.com/npc=52155)
![wowscrnshot_070413_180213](https://f.cloud.github.com/assets/4895839/751540/e0350840-e500-11e2-8d25-2917ad364562.jpg)

Esos mobs (desconozco su nombre) le pegan a la pet, y no pueden ser atacados
![wowscrnshot_070413_174854](https://f.cloud.github.com/assets/4895839/751544/026c682c-e501-11e2-89f0-4807cc4d7ea4.jpg)

Muchos mobs que hay en la maz no me golpean:
![wowscrnshot_070413_175440](https://f.cloud.github.com/assets/4895839/751546/28e49146-e501-11e2-8ba2-7d19b6594b1d.jpg)

Hasta ahi pude llegar con la maz, algunos bosses no estaban, pero lo importante es corregir esto de primero ya que se pueden aprovechar de boss piñata, ya luego hare un post mas a fondo de la maz.

**Comment by efectokoleos** [comment]
esta instance es otra de las reformadas por blizzard en la cata, por lo tanto esta cerrada por falta de scripts, cierro ticket
