### ISSUE TITLE
Boss Zul'Aman: Halazzi

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1360]
Buenas tardes.

Este boss tiene la vida muy muy baja, apenas 600k, cuando debería tener 4,149,700
http://es.wowhead.com/npc=23577#encounter

Le faltan todas las skills que debería usar. Bueno lo de todas lo pongo entre comillas, ya que solo se puede ver la primera fase de este boss, porque no cambia de forma de lince a forma de troll:
(aquí he intentado buscar el hechizo que debería hacer el boss para transformarse, pero he encontrado 4 distintas, una ha de ser la correcta :S ) 
http://es.wowhead.com/spell=43145 http://es.wowhead.com/spell=43271  http://es.wowhead.com/spell=43311 http://es.wowhead.com/spell=43143

Por último, este boss no se puede matar, ya que se queda continuamente con 1 punto de vida, haciéndolo inmortal, y además siguiendo en forma de lince.

Pongo finalmente una guia de este boss, con las fases especificadas y las skills con número de ID, que debería de usar y en que momento:

http://www.guiaswow.com/cataclysm/guia-zulaman-zul-aman-heroico.html

Además adjunto video:
http://www.youtube.com/watch?v=8WBMAd6zNZE

Un saludo

**Comment by efectokoleos** [comment]
totalmente reescrito por mi, ahora debería estar como en el parche 4.2
