### ISSUE TITLE
[Castillo Colmillo oscuro] No se puede Avanzar del primer boss

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1362]
Tras matar el boss el npc deberia de abrir la puerta para poder avanzar cosa que no esta haciendo...

ID: http://es.wowhead.com/npc=47862

![wowscrnshot_081913_153929](https://f.cloud.github.com/assets/3101842/989576/4cb1415c-0917-11e3-8b2a-1a4a2da83494.jpg)

nose si hay un npc para cada faccion

**Comment by SherBlader** [comment]
en efecto debe ser ese huargen (o por lo menos asi lo hice yo) tal vez no lo tienen activado porque hay un boss mas adelante que cuando se mata, tira el server (fui con bofur alguna vez)

**Comment by Mhryel** [comment]
Seguimos desde: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1394
