### ISSUE TITLE
[bug con mordida espantosa]

### ISSUE THREAD

**Issue by ramdres026** [RoDNet/Bugtracker-Infinium-4.3.4#1363]
hay bug con mordida en los hombres lobos, y ya realice todas las misiones con esta raza. si pueden quitarme esa mordida para seguir leviando el nombre de mi pj es Wolfverin. gracias

**Comment by aerz** [comment]
Porfavor detalla con mas información tu reporte especificando las misiones y otro tipo de errores de funcionamiento en las misiones.

Un saludo, cierro y esperamos ver el reporte completo para ponernos con ello.
