### ISSUE TITLE
Intendente clan faucedraco

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#1364]
El intendente del clan Faucedraco (http://es.wowhead.com/faction=1172/clan-faucedraco) no enseña los objetos azules ni morados ni el arcanum, simplemente te dice una frase y ya esta, no se le puede comprar nada. Adjunto una foto:
![image](https://f.cloud.github.com/assets/3939699/993025/aeb3e9fa-098e-11e3-90b2-e482f96010d7.png)

**Comment by Kiritoo** [comment]
Arreglado, falta implementar fix.
