### ISSUE TITLE
[Chaman] Escudo de Tierra

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1372]
ID: 974

El escudo de tierra cura al jugador cada ves que lo golpean Este efecto solo puede tener lugar una vez cada pocos segundos.

El bug es que no esta funcionando el cd interno y gracias a eso podemos curarnos facilmente en bg y al acabarse restablecemos escudo con eso he durado alto en bg :l

segun las notas del parche el cd interno es de 3,5 s

**Comment by searum** [comment]
fix

**Comment by Wiinter** [comment]
Perdona, pero he estado buscando en las notas del parche sobre el cd interno del Escudo de Tierra y no lo encuentro. En que notas está, me podrías pasar el link o decirme la versión que es? Es simplemente curiosidad, porque me ha parecido extraño ese cd interno.

**Comment by F4NT4SM4** [comment]
Escudo de agua se le redujo el cd interno a 3,5 s para estar iguales a los otros escudos eso da a entender que el escudo de tierra tiene el cd interno a 3,5s 

El tiempo de reutilización interno de Escudo de agua se ha reducido a 3,5 s para que se ajuste a otros escudos. Se ha reducido un 50% la cantidad de maná restaurada cuando Escudo de agua hace proc.
