### ISSUE TITLE
NPC bug e imposibilidad de subir Encantamiento.

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#1376]
Este NPC:

http://es.wowhead.com/npc=16583#teaches-recipe

Debería de vender

http://es.wowhead.com/item=25845#comments

También debería vender más items pero no da la opción de comprar, solo aprender herrería por lo que no puedo fabricar esa vara y seguir subiendo encantamiento.

**Comment by Kiritoo** [comment]
Este objeto http://es.wowhead.com/item=25845 que comentas lo hace un herrero.
Una vez te la cree el herrero cojes y la fabricas con tu encantamiento.
http://es.wowhead.com/item=25849 El cual aprendes por receta o en el instructor y creas este objeto http://es.wowhead.com/item=22463 que te sirve para seguir subiendo encantamiento.
Esto está funcionando correctamente ya lo mire.
