### ISSUE TITLE
[mazmorra, npj] The Prophet Skeram - Anh Quiraj 

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1377]
http://www.wowhead.com/npc=15263/the-prophet-skeram

Cuando llegamos al boss, este nos persigue y nos pega, pero nosotros no podemos hacer nada, y luego de 5 o 6 segundos tira ese spell y se reinicia.
Es el primer boss y no se le puede pegar, no pasamos de ahí puesto que no deja pasar.

![wowscrnshot_082013_162630](https://f.cloud.github.com/assets/4790547/997373/5bf55b98-09e0-11e3-8fcc-d0a2bd0b723f.jpg)
![wowscrnshot_082013_162846](https://f.cloud.github.com/assets/4790547/997374/5c1e4b20-09e0-11e3-83a9-3209bddf9538.jpg)

**Comment by efectokoleos** [comment]
arreglado en la proxima compilacion
