### ISSUE TITLE
[Misión] Un cargamento preciado: 14242 [Goglin Brujo]

### ISSUE THREAD

**Issue by RaulioWoW** [RoDNet/Bugtracker-Infinium-4.3.4#1379]
En las islas perdidas cuando acepto la misión, no hay forma de subir al girocoptero, he visto videos en youtube en donde lo hacen automaticamente, el cual no es el caso, ya intente borrar cache, morir, reiniciar y sin resultados.Siempre paso lo mismo, el girocoptero se levanta a unos centimetros del suelo pero no logro montarlo.
ó]
![wowscrnshot_082013_225128](https://f.cloud.github.com/assets/5274637/998573/75627cc0-0a06-11e3-867d-3d08b80b58b1.jpg)

**Comment by RaulioWoW** [comment]
Adjunto esto: http://es.wowhead.com/quest=14242

**Comment by Kiritoo** [comment]
Continuamos del https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1315?source=cc
Saludos

**Comment by RaulioWoW** [comment]
Muchas gracias! Un saludo
