### ISSUE TITLE
[Mazmorra] Zul'Aman Cerrada

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#138]
Cuando intente hacer esta mazmorra habia una puerta grande en la entrada que no dejaba seguir, y trate de hablar con npcs y nada, la puerta no se abrio.

![wowscrnshot_070413_185540](https://f.cloud.github.com/assets/4895839/751599/531320d6-e506-11e2-8574-f262fea46c8d.jpg)

**Comment by crowel** [comment]
Hola el motivo de que no se abra la puerta es este.

Vol'jin http://es.wowhead.com/npc=52924
![as](https://f.cloud.github.com/assets/3537253/755272/890bab84-e5a8-11e2-8e2e-80b2d1b37b2d.jpg)

Hay que hablar con el y darle a la opción de Nosotros estamos listos para abrir las puertas, opción que aparece pero que no se le puede dar click.
Tras darle, Vol´jin avanzaria hasta el gon de un poco mas adelante y golpeandolo, al mismo tiempo que lo golpea él, las puertas se abririan.
![wowscrnshot_070513_210121](https://f.cloud.github.com/assets/3537253/755261/e95a03b0-e5a7-11e2-888c-8778ebea2e90.jpg)

Bueno hasta aqui el reporte jeje, estaria bien arreglar esto de la opción para poder abrir la puerta y testear la instancia.

Un saludo.

**Comment by efectokoleos** [comment]
esta cerrada, ya que blizzard reformó esta isntance en la 4.3.0, por lo tanto no esta scriptada, cierro

**Comment by ghost** [comment]
En realidad fue en la 4.1 xd.
