### ISSUE TITLE
bug habilidad feral 

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#1381]
la habilidad http://es.wowhead.com/spell=52610,hace la animacion bien,pero noda el daño extra de los golpes blacos.

esto ya fue reportado y arreglado en #674, pero nose si llego a funcionar, yo nuca lo vi,a dia de hoy no funciona.

un saludo

**Comment by lamaza** [comment]
Ya dijeron que fix feo , close this =). Pasa que de pronto a veces se guardan los fix para una gran compilación y entonces no se aplican al momento exacto.

**Comment by 50megas** [comment]
ok pos lo cierro ,como pasaron 17 dias pense que no lo habian arreclado bien o algo
