### ISSUE TITLE
bug mision [Echeyakee]

### ISSUE THREAD

**Issue by ramdres026** [RoDNet/Bugtracker-Infinium-4.3.4#1382]
le doy click en el lugar u no aparece echeyakee

**Comment by Kiritoo** [comment]
Falto de información el reporte añade links porfavor.

**Comment by Kiritoo** [comment]
Cierro por falta de informacion

**Comment by yosalve** [comment]
Nombre: Echeyakee
Link: http://es.wowhead.com/quest=881
Objetivo: Toca el cuerno en la guarida de Echeyakee para invocarlo. Mátalo o subyúgalo.

Problema: al usar el item (http://es.wowhead.com/item=10327) en la zona marcada por la misión, no está saliendo el npc (http://es.wowhead.com/npc=3475) objetivo de la búsqueda.
