### ISSUE TITLE
[Puntos de justicia] Bosses Castillo de Colmillo Oscuro

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1383]
Buenas tardes.

Los bosses de Castillo de Colmillo Oscuro http://es.wowhead.com/zone=209/castillo-de-colmillo-oscuro#drops:mode=heroico no estan dando 70 puntos de justicia cada uno al ser derrotados:

http://es.wowhead.com/npc=3887
http://es.wowhead.com/npc=46962
http://es.wowhead.com/npc=4278
http://es.wowhead.com/npc=46963
http://es.wowhead.com/npc=46964

Gracias

**Comment by searum** [comment]
fix
