### ISSUE TITLE
Mision Bug " Buscar a Neltharaku"

### ISSUE THREAD

**Issue by francopo12345** [RoDNet/Bugtracker-Infinium-4.3.4#1387]
La misión de "Buscar a Neltharaku" no se completa encuentro a Neltharaku pero no la completa.. si la repararan seria de gran ayuda ya borre la cache como 5 veces y nada! Desde ya Gracias

**Comment by Kiritoo** [comment]
Falta de información al reporte.
Añade links, saludos.

**Comment by francopo12345** [comment]
http://es.wowhead.com/quest=10811/seek-out-neltharaku            Esa es la mision

**Comment by redneo** [comment]
arreglada
