### ISSUE TITLE
Mision Buscar a Neltharaku

### ISSUE THREAD

**Issue by brunoexeb** [RoDNet/Bugtracker-Infinium-4.3.4#1388]
esta es la mision para obtener el draco ala avisal de montura... y encuentro al draco... pero no me completa la mision... solo me habla ayuda por favor... aca un link de la quest y de la cadena de misiones

http://es.wowhead.com/quest=10811/seek-out-neltharaku

**Comment by Kiritoo** [comment]
No reportar si ya esta reportado porfavor, https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1387.
Cierro issue.
