### ISSUE TITLE
Misiones en borean tundra

### ISSUE THREAD

**Issue by sleepyhouse** [RoDNet/Bugtracker-Infinium-4.3.4#1389]
REvisando las misiones encontre esta que esta bugeada

www.wowhead.com/quest=11796

Lo que pasa con ella, es cuando te acercas el avion para quemarlo, no se quema ni se completa la mision.

**Comment by lamaza** [comment]
Ponle el titulo mas o menos asi: [misiones] "Nombre de la mision".Gracias.
