### ISSUE TITLE
Totem Marea de Maná CHAMAN

### ISSUE THREAD

**Issue by Cantadal** [RoDNet/Bugtracker-Infinium-4.3.4#1390]
El totem al sacarlo deberia dar mana por lo menos la mitad de la barra y en cambio no da nada de mana.

**Comment by Kiritoo** [comment]
Mmm nombre del hechizo y la id?

**Comment by Cantadal** [comment]
Nombre: Tótem Marea de maná Id: http://es.wowhead.com/spell=16190/totem-marea-de-mana

**Comment by searum** [comment]
Y donde dice que de mana? porque llevo buscando un buen rato informacion y no encuentro nada... cierro hasta que abras un issue en condiciones y aportando informacion.
