### ISSUE TITLE
Npc Durmiente de piedra (Castillo de Colmillo Oscuro)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1393]
Buenas noches

Los npcs http://es.wowhead.com/npc=3870/durmiente-de-piedra no pueden ser tarjeteados ni por tanto atacados.
La única manera de escapar de ellos, es entrar en alguna zona cubierta del castillo donde no nos persiguen

http://imageshack.us/photo/my-images/546/j8bu.jpg/

<a href="http://imageshack.us/photo/my-images/546/j8bu.jpg/" target="_blank"><img src="http://imageshack.us/a/img546/3503/j8bu.th.jpg" border="0"/></a>

Un saludo

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
