### ISSUE TITLE
[Castillo Colmillo oscuro] No es posible ir al último boss

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1394]
Buenas noches

De la misma manera que sucede en https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1362 (pudimos avanzar gracias a Aerz que nos abrió la puerta enseguida):

Tras matar al boss Lord Walden http://es.wowhead.com/npc=46963 el npc http://es.wowhead.com/npc=47294 (para la horda), o el npc http://es.wowhead.com/npc=47006 (para la alianza), deberían abrir la puerta que queda detrás de Lord Walden.

http://img203.imageshack.us/img203/5002/q0z7.jpg

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/203/q0z7.jpg/'><img src='http://img203.imageshack.us/img203/5002/q0z7.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

P.D. Tengo el presentimiento que esto esta sucediendo por venir a esta mazmorra con alianzas y hordas mezclados en el mismo grupo.

**Comment by paellaencol** [comment]
Como sugerencia y para dar menos trabajo: estas puertas podrían permanecer abiertas, ya que obligatoriamente deberíamos matar al boss anterior para poder ir al siguiente, por el hecho de que están contiguos a la puerta

**Comment by searum** [comment]
fix
