### ISSUE TITLE
[Bastion de Baradin] Argaloth

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1397]
El boss Argaloth le esta afectando atraccion letal asi que facilmente cortarmo cast a cualquier hechizo del boss y deberia de ser inmune 

Atraccion letal: http://es.wowhead.com/spell=49576/atraccion-letal
Boss:  http://es.wowhead.com/npc=47120/argaloth

**Comment by efectokoleos** [comment]
arreglado en el proximo reinicio
