### ISSUE TITLE
Mi deposito de vacio, o mi pj tan bug D: XD

### ISSUE THREAD

**Issue by salydell** [RoDNet/Bugtracker-Infinium-4.3.4#1398]
Pues bueno despues de que me recuperaron los items nombrados en este tema
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/780
los recoji del correo, y todo bien, pero como guardo demaciado cosas decidi volverlas aacomodar en el deposito, asi que las fui ingresando esas y otras prendas que esta ves si no recuerdo exactamente cuales eran D: bueno mientras ingresaba objetos me salio un mensaje de "No hay suficiente espacio en el deposito del vacio para ingresar el item" cuando no estaba ni la mitad de lleno, me parecio curioso deslogue y al reentrar otra ves esta vacio con solo un puñado de items (no todos) y que mo puedo sacar o mover o ingresar mas (si metes uno nuevo desaparce D:)
si es una molestia que esto pasara recien se me habia resuelto uno pero enserio no se que paso (de nuevo me pueden recuperar lo perdido) y que hago, para que algo asi no se repita :S o por que me paso esto D: o que hago nunca usar mas el deposito XD ?¡ o solo tengo pesima suerte

**Comment by aerz** [comment]
-.- 
El problema actual lo tenemos en el depósito de vació para la alianza. Por ahora no lo utilices hasta que no veas cambios en el depósito de vació en nuestro Changelog (cada 15 días) para asi evitar los errores de este estilo.
Estamos revisando todo este tema ya que ademas lanza wowerror al usarlo de vez en cuando.

Un saludo y gracias por el reporte. Trataremos de avisarte lo antes posible.

**Comment by salydell** [comment]
ok muchas gracias por la pronta respuesta no lo usare asta que vea que esta reparado :P XD y pues gracias por la pronta respuesta y si es pesado XD pero pues es lo que me paso en fin gracias y sigan asi XD

**Comment by aerz** [comment]
Nada, esperamos poder realizar alguna implementación acerca de este tema cuanto antes.
Por ahora dejo este reporte abierto para tenerlo en cuenta.

Un saludo.

**Comment by Dekadencee** [comment]
Fixed
