### ISSUE TITLE
consulta

### ISSUE THREAD

**Issue by shogun1968** [RoDNet/Bugtracker-Infinium-4.3.4#1399]
Aunque he solicitado la consulta desde el juego, al no obtener respuesta la pongo aquí también, Un horda llamado Lamaza me dice que no puedo usar mi equipo "sañoso" hecho por mi pj herrero y que si lo uso me va a denunciar. Quería saber si eso es verdad y si es así, por que se puede hacer el equipo y no lo bloquean, como pasa con las joyas "sañosas". Hasta su contestación, seguiré usando el equipo, ya que es el único que tengo y no encuentro en ningún sitio que diga que no se puede utilizar. Espero su contestación, ya que no es mi intención infringir ninguna norma del servidor. Muchas gracias.

**Comment by Kiritoo** [comment]
Usar ese equipo lleva consigo la retirada del mismo, si no lo utilizas lo puedes tener ya que actualemente no se puede usar en la version 4.2, cuando cambie la temporada a la 11 se podrá usar.
Una cosa que quiero añadir que el bugtracker está "solo" para fallos con el juego, para todo lo demás la web.
Un saludo.
