### ISSUE TITLE
Exploracion

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#14]
Todo lo qe tenías explorado lo tienes qe volver a explorar aunqe el logro ya lo tengas marcado.

**Comment by lamaza** [comment]
En realidad no es asi, los logros quedaron, solo que las zonas vuelven a estar como cubiertas ya que hubieron cambios ciber geográficos en el juego. Y respecto a eso no veo problema.

No hay que volver a explorar nada, los logros los tienes ahi o no?

**Comment by Wiinter** [comment]
Ya es lo me refería, pero a mi me gusta poder consultar los nombres de los sitios, porque la mayoria no me acuerdo xD

**Comment by SherBlader** [comment]
con el addon carbonite los puedes ver.

**Comment by Wiinter** [comment]
Ya pero sin él no xD
