### ISSUE TITLE
Maestria

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#140]
Buenas, la maestría ya aparece aprendida en el libro de hechizos, pero no funciona.
Por ejemplo con el dk cuando hago golpe letal, el escudo de sangre no hace absorción alguna.

http://es.wowhead.com/spell=77513/maestria-escudo-de-sangre

Y tambien me pasa con otros pjs de otras clases que no me funciona maestria

**Comment by Dekadencee** [comment]
Fixed
