### ISSUE TITLE
Talento Sacerdote sagrado [Oleada de luz] ID: 88690

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1400]
Descripción: Al utilizar punición (585), sanar (2050), sanación superior (2060), sanación relámpago (2061), o sanación conjunta (32546), tienes un 6% de posibilidades que tu siguiente sanación relámpago (2061) sea instantánea y no cueste maná.

Problema: este proceso no salta con ninguna de las habilidades detalladas

Gracias

**Comment by searum** [comment]
fix
