### ISSUE TITLE
Hechizo Sacerdote Sagrado: Palabra sagrada: Santuario [ID:88685]

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1401]
La sanación Palabra sagrada: Santuario, únicamente está haciendo, a dia de hoy, el efecto visual del área en el suelo. Sin embargo dicha área no está curando nada.

Aclaro que la única manera de tener acceso a esta cura es estando bajo el estado del Chakra: Santuario (81206)

Gracias

**Comment by searum** [comment]
fix falta aplicarlo
