### ISSUE TITLE
Talento Sacerdote sagrado [Chakra] ID: 14751 (especialización Santuario)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1402]
Mediante el talento Chakra (14751), debería hacer que al activar esta facultad y posteriormente utilizar uno de los siguiente hechizos: Rezo de alivio (33076) o Rezo de Sanación (596). Deberíamos imbuirnos en estado de Chakra: Santuario (81206)

Problema: solo podemos entrar en estado de Chakra: santuario (81206), mediante Rezo de Sanación (596). Utilizando Rezo de alivio (33076) no sucede nada

Gracias.

**Comment by searum** [comment]
fix
