### ISSUE TITLE
Hechizo Sacerdote Sagrado: Chakra: Serenidad [ID:81208]

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1403]
Buenos días.

Solo un pequeño detalle que no funciona de este hechizo (todo el resto de procesos que debería hacer y/o activar este hechizo funcionan perfectamente).

Estando bajo el estado del Chakra: Serenidad, debería suceder lo siguiente:

Descripción: Probabilidad de efecto crítico de tus hechizos de sanación directa aumentada un 10% (hasta aquí funciona), y provoca que tus sanaciones directas reinicien la duración de tu Renovar en tu objetivo (problema).

Problema: al utilizar cualquier sanación directa sobre un objetivo beneficiado por nuestra sanación periódica Renovar (139), Renovar debería refrescarse sobre este objetivo con la duración completa inicial (es decir 12segundos)

Esto no está sucediendo.

Adjunto vídeo donde muestra lo que debe suceder:

http://www.youtube.com/watch?v=Cv-FWbcvW4A

(visualizad entre el 2:30 y el 2:38)

P.D. Edito que el vídeo es de un parche anterior a la 4.3.4, con el parche actual Renovar debería refrescarse con cualquier sanación directa (en el vídeo solo sucede con una en específico)

Gracias

**Comment by searum** [comment]
fix
