### ISSUE TITLE
falta arma implacable sin los 7200

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#1404]
hola, haveis puesto armas implacables sin necesidad de los 7200 puntos ganados,en el npc http://es.wowhead.com/npc=54658/sargento-tronacuerno pero este no vende http://es.wowhead.com/item=70223/mazo-de-gladiador-implacable sin los 7200,si pueden ponerla ya que para chami y pala heal no hay otra.

gracias

**Comment by crowel** [comment]
Hola quiero comentarte que las armas implacables con necesidad de 7800 puntos solo son las de una mano y dos.
Las armas arrojadizas, varitas, arcos, mano izquierda etcc... no requieren puntos de temporada.
Que falte un arma es otra cosa xD

**Comment by crowel** [comment]
http://eu.battle.net/wow/es/blog/10024970/

Mirate esto

**Comment by 50megas** [comment]
aaaa yo creia que las pudieron por el bug ese que havia,que ganabas 7200 y no podias comprar tampoco,ok pos cierro
