### ISSUE TITLE
[NPC] Thol'embaar <El Incinerador>

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1405]
Este NPC esta duplicado.

http://es.wowhead.com/npc=40107

![wowscrnshot_081313_204410](https://f.cloud.github.com/assets/3537253/1008881/a803b7d2-0b2f-11e3-8ad3-c592f3ee5228.jpg)

Un saludo.

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
