### ISSUE TITLE
[ Bastión Violeta > Ícoron ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#1407]
Este boss no puede morir, se queda a 1 de vida tras suceder sus fases:
http://es.wowhead.com/npc=29313

![wowscrnshot_082213_154051](https://f.cloud.github.com/assets/2728817/1009027/fc6c708c-0b31-11e3-94e5-35b62eec8962.jpg)

**Comment by feniix97** [comment]
Un bug q se formo de seguro cuando lo atacaron tuvieron mala suerte debieron esperar a que saliera de esa cárcel, inténtenlo mañana el boss esta perfectamente hasta conseguí su logro de deshidratación de lo bien que  funciona, cierren tema.
