### ISSUE TITLE
Toque de sanación over

### ISSUE THREAD

**Issue by kaalbireth** [RoDNet/Bugtracker-Infinium-4.3.4#141]
![wowscrnshot_070413_191926](https://f.cloud.github.com/assets/4935390/751746/b2af651a-e513-11e2-8990-1b9c81d9cdb2.jpg)

**Comment by ghost** [comment]
Con que así se llama tu dudu xd
Dejo enlace de Toque de Sanación: http://es.wowhead.com/spell=5185

**Comment by kaalbireth** [comment]
e.e si olvide dejar el enlace de la skill xd.
