### ISSUE TITLE
[Misión] (Infralar)Something that Burns

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1410]
Algo que arda http://es.wowhead.com/quest=27135

El objeto El Corazón Ardiente http://es.wowhead.com/item=60837

Para invocar a Dientemagma <Elemental de fuego del iniciado Minaoro>
http://es.wowhead.com/npc=45099

Actualmente no funciona lo usas en la poza y aparece este mensaje:
"Requiere charco de sangre de El Reguero De Sangre" En rojo.

![wowscrnshot_081413_021426](https://f.cloud.github.com/assets/3537253/1009140/f2a4a0b8-0b33-11e3-8054-ff98f9c212df.jpg)

Un saludo.

**Comment by redneo** [comment]
Funciona correctamente
