### ISSUE TITLE
[Misión] (Infralar) All Our Friends Are Dead

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1411]
Todos nuestros amigos están muertos http://es.wowhead.com/quest=26248

Al utilizar el Tótem de espíritu http://es.wowhead.com/item=58167
Sobre los Miembro del equipo asesinado, no ocurre nada.

![wowscrnshot_081413_024432](https://f.cloud.github.com/assets/3537253/1009187/d73da7ec-0b34-11e3-8b2c-465f039a7628.jpg)
![wowscrnshot_081413_024436](https://f.cloud.github.com/assets/3537253/1009188/d74ee5c0-0b34-11e3-92d8-aece4816703f.jpg)

Video:http://www.youtube.com/watch?v=lsAC-IHiSMs

Un saludo.

**Comment by redneo** [comment]
Funciona correctamente
