### ISSUE TITLE
buscar a neltharaku

### ISSUE THREAD

**Issue by mizaky** [RoDNet/Bugtracker-Infinium-4.3.4#1417]
mision que  se encuentra en valle sombraluna  es un hilo de quest para poder tener la montura del draco abisal pero lo q pasa es q no completa esta (  buscar a neltaharaku  ) no completa el hilo de quest y no se puede obtener la montura

**Comment by aerz** [comment]
Completa mas tu reporte. Añade imágenes, explicaciones de como debería funcionar, etc. Fijate bien en los demás reportes y realiza uno mas correcto.
Esperamos ver uno mas completo.

Cierro Issue. Un saludo.
