### ISSUE TITLE
[Spell > Priest] Mind Spike

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1419]
Púa mental http://es.wowhead.com/spell=73510

La función más importante de este hechizo no está funcionando.
![pua mental](https://f.cloud.github.com/assets/3537253/1009648/fbcaaff4-0b3b-11e3-8fd1-7aa11544aad2.jpg)

La parte de "Púa mental tambiém aumenta un 30% la probabilidad de golpe crítico de tu siguiente explosion mental" Se acumula 3 veces."

Sabiendo esto con 3 acumulaciones deberiamos de tener un 90% de probabilidad de pegar un golpe crítico lo mas seguro con explosion mental.

El problema esta que tenemos tanta posibilidad con una aplicación que es un 30% que teniendo 3 aplicaciones que es un 90%.
No estan saliendo críticos apenas con las 3 aplicaciones.

Un saludo.

**Comment by searum** [comment]
fix falta aplicarlo
