### ISSUE TITLE
[NPC] Vigía de la pirámide

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1421]
Vigía de la pirámide http://es.wowhead.com/npc=47810
No se puede targetear pero el si que ataca.
![wowscrnshot_081413_152056](https://f.cloud.github.com/assets/3537253/1009823/3b7245f6-0b3f-11e3-99fa-19ff353f7122.jpg)
![wowscrnshot_081413_152100](https://f.cloud.github.com/assets/3537253/1009824/3ba6cdda-0b3f-11e3-8f5b-df36a76d612e.jpg)

Un saludo.

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
