### ISSUE TITLE
[Misión] (Uldum) Tailgunner!

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1424]
¡Armacola! http://es.wowhead.com/quest=27905

Hola me parece que está quest esta autocomple mientras se arregla pero quiero comentar que una vez se completa y se aparece en la presa no está el npc donde se debe entregar la misión ni el avion.
Harrison Jones http://es.wowhead.com/npc=48082

![wowscrnshot_081413_163802](https://f.cloud.github.com/assets/3537253/1010054/f5b1ecde-0b42-11e3-8d4f-d2009cec6e27.jpg)

Un saludo.

**Comment by redneo** [comment]
Arreglada
