### ISSUE TITLE
[Misión] (Uldum) Hacking the Wibson

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1428]
Piratear el Wibson http://es.wowhead.com/quest=27778

No se puede piratear la unidad central wibson
Unidad central Wibson http://es.wowhead.com/npc=46715

![wowscrnshot_081413_180013](https://f.cloud.github.com/assets/3537253/1010355/71cb3612-0b49-11e3-882b-fc98682b7d8e.jpg)

Video: http://www.youtube.com/watch?v=Rk7F1w_kZzo

Un saludo.

**Comment by redneo** [comment]
Esta no estoy seguro de que esté reparada
