### ISSUE TITLE
[Sacerdote] Égida divina

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1429]
ID: http://es.wowhead.com/spell=47515/egida-divina

![wowscrnshot_082213_171050](https://f.cloud.github.com/assets/3101842/1012638/c3954f08-0b73-11e3-88d2-18bd645921b0.jpg)

El talento deberia de activarse solo al realizar una sanacion critica o con rezo de sanacion. El caso es que se esta activando con cualquier sanacion siendo critica o no

Por favor revisen esto rapido que ya hay muchas quejas de sacer por culpa de sus absorciones :l

**Comment by paellaencol** [comment]
Añado el reporte que hice sobre este talento https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/727

Después de este reporte arreglaron alguna cosa, pero otra se estropeó:

El primer punto sigue fallando:

Funciona demasiado, es decir, salta con cualquier cura. Cuando debería funcionar únicamente con sanaciones críticas, o con cualquier tipo de sanación (crítica o no) proveniente de Rezo de sanación (596). Del valor total de la sanación que haga saltar el proceso, un 30% de esa cantidad total será añadida como escudo en forma de Égida divina (47515).

Y el segundo funciona a medias, es decir, las sanaciones críticas y todos los rezos de sanación deberían apilar el efecto del escudo de égida divina. Esto no está sucediendo, en lugar de esto lo que hace es resetear las cargas. Por ejemplo: si haces un crítico de una sanación y te salta 9k de égida divina como escudo, y luego utilizas un rezo de sanación (ID: 596), y el consiguiente valor de égida divina que salta en esta cura es de 2k, en vez de sumar ambas y quedarse en 11k de égida divina, la primera carga desaparece y únicamente se nos queda la primera (problema). Esto es muy importante ya que es la única posibilidad que tiene un sacerdote disciplina como healer de raid en PVE

P.D: irónicamente si que se acumula égida divina con las sanaciones no críticas y que no sean rezo de sanación, es decir con las que no debería haber saltado

Un saludo

**Comment by searum** [comment]
fix falta aplicarlo
