### ISSUE TITLE
Bandera de cumbres gemelas bug.

### ISSUE THREAD

**Issue by kaalbireth** [RoDNet/Bugtracker-Infinium-4.3.4#143]
como ven la bandera horda no se puede agarrar
![wowscrnshot_070413_191400](https://f.cloud.github.com/assets/4935390/751753/80a54ca0-e514-11e2-93f8-ebdaa21b8edd.jpg)

**Comment by Dekadencee** [comment]
Reporte repetido #135, lo seguimos desde ahi
