### ISSUE TITLE
[Sacerdote] Palabra de poder: escudo

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1431]
ID: http://es.wowhead.com/spell=17/palabra-de-poder-escudo

![wowscrnshot_082213_171847](https://f.cloud.github.com/assets/3101842/1012707/25c7ee00-0b75-11e3-863d-8c3369421cf6.jpg)

Segun la descripcion del hechizo y Drdamage deberia de absorber 8313p
pero estoy absobiendo 11942. 11942-8313= 3629 estoy absorviendo 3629 demas

![wowscrnshot_082213_171849](https://f.cloud.github.com/assets/3101842/1012782/95de76a4-0b76-11e3-844c-0b693f2b4f9b.jpg)

Testee sin talentos ni glifos ni equipo...

**Comment by paellaencol** [comment]
.

**Comment by searum** [comment]
a ver si ya cesan los lloros
