### ISSUE TITLE
[Guerrero] Ejecutar

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#1432]
Esta skill no está consumiendo más que 10 p. de ira cuando debería de poder consumir hasta 30 p. y hacer mucho más daño.

Tampoco hace el daño bien, un poco más que gastando 10 p.

ID: http://es.wowhead.com/spell=5308#.

PD: la ID es la de MoP en el cual la skill ya no funciona igual.

**Comment by Kiritoo** [comment]
Esto esta arreglado.
