### ISSUE TITLE
[Misión] Bird Down! Bird Down!

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1435]
¡Pájaro caído! ¡Pájaro caído! http://www.wowhead.com/quest=27514

No está el npc en el cual se entrega la quest.

![wowscrnshot_081513_025301](https://f.cloud.github.com/assets/3537253/1015433/2eaaa3ea-0bda-11e3-91b0-27974d8bb2b2.jpg)

Un saludo.

**Comment by Kiritoo** [comment]
Ya reportado antes, cierro.
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1250
