### ISSUE TITLE
[Misión] (Tierras Altas Crepusculares) The Lost Brother

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1437]
El hermano perdido http://es.wowhead.com/quest=28233

El npc a entregar no esta.
Bahrum Forjamartillo http://es.wowhead.com/npc=48053

![wowscrnshot_081513_031154](https://f.cloud.github.com/assets/3537253/1015537/4ee342e0-0bdd-11e3-8396-a73e12f3c5c1.jpg)

Video:http://www.youtube.com/watch?v=sZ_pgy2j_3Q  Minuto 0:10

Un saludo.

**Comment by Kiritoo** [comment]
Arreglada cuando se reinicie.
