### ISSUE TITLE
[Misión] (Tierras Altas Crepusculares) The Fighting Spirit

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1438]
El espíritu de la lucha http://es.wowhead.com/quest=27810

No se puede realizar, no se puede retar al Jinete de grifos, no tiene gossip.
Jinete de grifos Mullan derrotado http://es.wowhead.com/npc=46813

![wowscrnshot_081513_031319](https://f.cloud.github.com/assets/3537253/1015546/bdafcb8a-0bdd-11e3-9f4d-cc8ec7be46f4.jpg)

Video:http://www.youtube.com/watch?v=CFgtF4N7kQw

Un saludo.

**Comment by Kiritoo** [comment]
Arreglada cuando se reinicie.
