### ISSUE TITLE
[Misión] (Tierras Altas Crepusculares) The Crucible of Carnage

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1439]
El Crisol de Matanza

Hola quiero reportar las siguientes misiones del crisol de matanza.
Las cuales ahora invocan los boss al cojerlas por que lo arreglo redneo.
El problema está en que estan autocompletables las 4 últimas, invoca al boss pero se pueden entregar directamente.

El Crisol de Matanza: ¡el mortal Faucedraco!
http://es.wowhead.com/quest=27864

El Crisol de Matanza: ¡la creación de Calder!
http://es.wowhead.com/quest=27866

El Crisol de Matanza: ¡el duque del destripamiento!
http://es.wowhead.com/quest=27867

El Crisol de Matanza: ¡el terror Crepuscular!
http://es.wowhead.com/quest=27868

(Está que voi poner, nose si ocurre lo mismo ya que yo las hice con el alianza y solo se puede hacer la horda, se debe comprobar)
El Crisol de Matanza: ¡el perverso Martillo Salvaje!
http://es.wowhead.com/quest=27865

Aqui las screens.
![wowscrnshot_081513_032202](https://f.cloud.github.com/assets/3537253/1015572/b4a22ec4-0bde-11e3-858d-169d531049f9.jpg)
![wowscrnshot_081513_032210](https://f.cloud.github.com/assets/3537253/1015573/b4b0b6ce-0bde-11e3-9369-115d6f8b9314.jpg)
![wowscrnshot_081513_032221](https://f.cloud.github.com/assets/3537253/1015574/b4ba536e-0bde-11e3-98af-03ea96314d2d.jpg)
![wowscrnshot_081513_032230](https://f.cloud.github.com/assets/3537253/1015575/b4b9fd2e-0bde-11e3-97bc-0624f5304ee2.jpg)

Un saludo.

**Comment by Kiritoo** [comment]
Esto está arreglado.
