### ISSUE TITLE
Dalaran solo con un portal

### ISSUE THREAD

**Issue by Hellythium** [RoDNet/Bugtracker-Infinium-4.3.4#144]
Buenas, es para informar que Dalaran esta solo con un portal que es el de hacia Orgrimmar, en caso de la horda, imágenes a continuación
![wowscrnshot_070413_204826](https://f.cloud.github.com/assets/3613748/751758/6e2cf7a2-e515-11e2-9921-2af1628cfb85.jpg)
![wowscrnshot_070413_205021](https://f.cloud.github.com/assets/3613748/751759/6e37f094-e515-11e2-88c0-8fe29dba249e.jpg)
![wowscrnshot_070413_205031](https://f.cloud.github.com/assets/3613748/751762/6e42fb1a-e515-11e2-9287-7861f5d6a412.jpg)
![wowscrnshot_070413_205018](https://f.cloud.github.com/assets/3613748/751760/6e3aed4e-e515-11e2-8ad0-172e9ede17bc.jpg)
![wowscrnshot_070413_205023](https://f.cloud.github.com/assets/3613748/751761/6e3fdcd2-e515-11e2-9172-a2fc1f9e7c56.jpg)

Saludos, Darkstar.

:

**Comment by SherBlader** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/38

**Comment by Alfonn** [comment]
Acabo de poner la explicación en otro reporte... Está como debe de estar.. #38 .
