### ISSUE TITLE
[Misión] (Tierras Altas Crepusculares) The Scent of Battle

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1440]
El olor de la batalla http://es.wowhead.com/quest=27811

No se pueden entregar los grifos.
![wowscrnshot_081513_032444](https://f.cloud.github.com/assets/3537253/1015627/e5d6e9d8-0be0-11e3-9c2b-9ef295fd3691.jpg)

Video: http://www.youtube.com/watch?v=Q0KMJukK1ys

Un saludo.

**Comment by Kiritoo** [comment]
Arreglada cuando se reinicie.
