### ISSUE TITLE
[Misión] (Tierras Altas Crepusculares) Call in the Artillery

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1442]
Que venga la artillería http://es.wowhead.com/quest=27497

Está misión no se puede realizar porque al llegar al punto designado(los edificios) a marcar no se puede usar la bengala y no se puede completar los objetivos.

Bengala de artillería http://es.wowhead.com/item=61367

![wowscrnshot_081513_033136](https://f.cloud.github.com/assets/3537253/1015653/fc7f980a-0be1-11e3-93bc-aeb84b7c287b.jpg)

Un saludo.

**Comment by ghost** [comment]
Reparada.
