### ISSUE TITLE
[Misión] (Tierras Altas Crepusculares) My Sister, Fanny

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1443]
Mi hermana, Fanny http://es.wowhead.com/quest=28369

Está misión no se puede entregar porque al llegar al npc donde se entrega no sale la opción.

Fanny Bramal http://es.wowhead.com/npc=48013

![wowscrnshot_081513_122737](https://f.cloud.github.com/assets/3537253/1015659/65027564-0be2-11e3-880a-9793ff564fe2.jpg)

Un saludo.

**Comment by Kiritoo** [comment]
Arreglada cuando se reinicie.
