### ISSUE TITLE
mision dk [En reino de las sombras]

### ISSUE THREAD

**Issue by ramdres026** [RoDNet/Bugtracker-Infinium-4.3.4#1445]
esta mision para los dk no esta funcionando, cuando uno va a entregar la mision no se completa

**Comment by Kiritoo** [comment]
IDS?

**Comment by mildanxiety** [comment]
Yo también estuve intentando completar esta misión y no funciona, estaría bueno que la reparen, gracias

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
