### ISSUE TITLE
[Guerrero] Rajar,Desgarrar, Embate

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#145]
El ataque de Rajar esta pegando 1 
http://es.wowhead.com/spell=56909/rajar

Desgarrar pega muy poco 140 a un muñeco
http://es.wowhead.com/spell=12054/desgarra

El embate lo utilizo una ves y el objetivo recibe 2 embate hasta aveces 3
segun mi recount
http://es.wowhead.com/spell=1464/embate

**Comment by redneo** [comment]
rajar arreglado

Los otros a ver si me bajo el drd y veo el daño que tendria que hacer....

**Comment by F4NT4SM4** [comment]
Desgarrar y Rajar van bien pero el embate sigue pegando 2 veces o 3 xD
