### ISSUE TITLE
[Brujo] Conflagrar: 17962

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1450]
http://wow.freakz.ro/spells.php?spell=17962
Descripción: Hace un 60% del daño periódico de inmolar instantaneamente.

Problema: Actualmente está haciendo un daño bajísimo, unos 500 o así.

**Comment by Drogoth2** [comment]
Yo os comparto la opinión de asman, de hecho os traigo un par de fotos. La primera aparece el daño de conflagrar que es de apenas 250, y la segunda la pongo con el dr damage para que veáis los parámetros.

Aquí os dejo el enlace para que veáis el hechizo en wowhead: http://es.wowhead.com/spell=17962/conflagrar

![wowscrnshot_082913_132410](https://f.cloud.github.com/assets/3939699/1049217/4fcbedae-109e-11e3-9aaf-86653724a1c3.jpg)

![wowscrnshot_082913_132429](https://f.cloud.github.com/assets/3939699/1049219/566779ee-109e-11e3-9bf6-5959060e4082.jpg)

**Comment by searum** [comment]
fix
