### ISSUE TITLE
Humo en los Ojos

### ISSUE THREAD

**Issue by Eralion** [RoDNet/Bugtracker-Infinium-4.3.4#1451]
Esta mision en Uldum esta bug, quemas los montones de heno en Tol vir, y no te los cuentan.

Link:http://es.wowhead.com/quest=27923/humo-en-los-ojos

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1416
Comprobad antes de reportar pls.
