### ISSUE TITLE
[Logro] Veterano de la Horda

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1454]
ID: http://es.wowhead.com/achievement=5325/veterano-de-la-horda

Al ganar 75 deberia de darme el logro con las recompenzas:
El titulo de Veterano de la Horda: http://es.wowhead.com/title=194
Montura Terrestre: http://es.wowhead.com/item=70910

He ganado 220 Campos de batalla ya deberia de tener el logro desde hace tiempo pero nada esta bug

Con estas clases de logro y recompenzas animarian mas a la gente a hacer bg :p

**Comment by 50megas** [comment]
creo que no son bgs normales,sino las cdb puntuadas que tanto espero las pongan^^

un saludo

**Comment by F4NT4SM4** [comment]
poniendolo asi intonce nunca tendremos la montura y logro jajaja cierro intonce
