### ISSUE TITLE
[logros] Heroic: The Nexus Guild Run

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1455]
Como ya comentaron anteriormente (https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/971 https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1395 , no se obtienen algunos logros de hermandad yendn en grupo con miembros actualmente.

Pongo el ejemplo, de que hoy hicimos esta mazmorra y nos quedó ID, pero no nos dieron logro de hermandad.

![wowscrnshot_082313_094122](https://f.cloud.github.com/assets/4790547/1019864/e3085816-0c55-11e3-84aa-d8cece9e6b89.jpg)
![wowscrnshot_082313_094108](https://f.cloud.github.com/assets/4790547/1019865/e321edee-0c55-11e3-9ac1-ffe29e6a3e96.jpg)

Saludos, y buen trabajo en el BT Gms.

**Comment by SherBlader** [comment]
creo que tenian que haber ido 4 para que les diera el logro (4 de la misma hermandad para mazmorra)
para bandas creo que son 8 de la misma hermandad.. (creo, no estoy seguro, pero mas o menos asi funciona)

**Comment by lamaza** [comment]
Grupo de Guild son de 3 categorias: 3 miembros, 4 miembros y 5 miembros. De acuerdo a eso se afecta la experiencia ganada. Por eso linkee los issue similares, para que los leyeran...

"Hay una excepción a la norma del 80% que son las mazmorras de 5 jugadores, basta con que 3 de los 5 miembros pertenezcan a la misma hermandad para ganar experiencia y logros de hermandad."

http://eu.battle.net/wow/es/blog/9999050/

**Comment by searum** [comment]
esto va en logros en general de hermandad, cierro
