### ISSUE TITLE
[Mazmorra, NPJ] Capitan Cocinitas : Minas de la Muerte 5n

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1456]
http://es.wowhead.com/npc=47739/capitan-cocinitas

El Boss Capitán Cocinitas aparece en la cubierta del barco, pero es un npj amistoso y nos lleno de comida el piso. Nos persigue hasta que salgamos de la mazmo, aventándonos todo tipo de vegetales y cosas.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/262

Nunca hizo nada más, no lo pudimos matar.

![wowscrnshot_081913_122518](https://f.cloud.github.com/assets/4790547/1019881/d6ca3866-0c56-11e3-97f0-4e8c9e0675d5.jpg)

**Comment by JoakRoD** [comment]
Ya sí que se puede matar.
