### ISSUE TITLE
(Mago) Misiles Arcanos

### ISSUE THREAD

**Issue by yongkuon** [RoDNet/Bugtracker-Infinium-4.3.4#1457]
Este hechizo no se activa nunca, no me es posible tirar misiles arcanos con el mago

**Comment by yongkuon** [comment]
El error estaba en los muñecos de entrenamiento de orgrimmar, me decia estar de espaldas cuando no era asi. Al salir de orgrimmar y tirar explosion arcana, los misiles se activaron. No era un problema del hechizo.

**Comment by Wiinter** [comment]
Cierra el issue :)
