### ISSUE TITLE
Bug's en los Dk's,

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#1459]
Aquí pondré todos los bug's que e visto en los dk's hasta este momento.

Profano:
1ro. Las pestes infligen muy poco daño, ejemplo claro las Dot's dicen hacer tanto daño y hacen 10,20,máximo 200 de daño.

2do. La mascota esta bug... Este se divide en partes

```
 - Cada vez que te pones montura,desaparece la pet.

 - Como desaparece la pet por la montura,la barra de habilidades desaparece y se pierde lo arreglado.

 - La mascota no inflige nada de daño aun teniendo el talento Infusión de sombras y Transformación oscura su daño sigue siendo 20,30 máximo 100.

 - La mascota no da el stun natural que tiene llamado Roer.
```

 3ro. El talento Fatalidad súbita a veces se buguea y no permite lanzar la espiral gratis que proporciona. 

  4to. Presencia profana mejorada no le proporciona a la presencia sangre y escarcha un aumento de velocidad,ni de regeneración rúnica.

  5to. El golpe necrotico no absorbe 4263p. de curación si no 1p.

Escarcha: 
No la e probado completa y solo poseo el siguiente bug.

   1ro. La habilidad Sangre del norte convierte las runas de sangre en muerte pero solo cuentan como de sangre,no como profanas, ni de escarcha.

Sangre: 
Esta igual no la e probado totalmente.

```
 1ro. La habilidad trasnfusion de runa no cura 10% de vida si no 5%.

  2do. La habilidad Simulación oscura no le da al dk la habilidad de hacer la replica del hechizo usado por el enemigo jugador.
```

Saludos.

**Comment by 50megas** [comment]
hay que meter un bug por repote y con enlaces de wowhead,yo voi a probar el daño de las enfermedades que creo que esta muy bajas en profano y si eso lo reporto

un saludo

**Comment by Kiritoo** [comment]
Cierro porfavor añade un issue por bug, si encuentras alguno ya reportado no lo añadas porfavor.
Saludos.
