### ISSUE TITLE
[Trinkets - SP] Daño - Sanación con hechizos

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1461]
Bueno, esto estuvo arreglado antes, pero hoy me he fijado y está bug, no sé desde cuando pero han vuelto algunos bugs que estaban arreglados y que afectaban al poder con hechizos como el de Luminosidad Arcana (https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1272) y este de los abalorios PvP.

Lo que ocurre:

Al activar el trinket, en la estadísticas del PJ aparece una nueva descripción llamada "Sanación con hechizos", justo debajo de "Daño con hechizos" y sólo se aumenta el spell en la estadística de la sanación, y no en la de daño.

Lo que debería ocurrir: 

No debería desglosarse el SP en 2, daño y sanación, ya que deberíamos tener la misma cantidad para ambos siempre y el spell del abalorio debería añadirse tanto al daño como a la sanación.

**Comment by crowel** [comment]
![wowscrnshot_082413_164656](https://f.cloud.github.com/assets/3537253/1020856/9880e836-0ccc-11e3-92dd-a0519c5092c1.jpg)

Asi es el sp vuelve a tener por separado daño y sanación cuando ambos deben estar en poder de hechizos.
A veces si aparecen juntos, al usar el abalorio y de vez en cuando se separan :(

**Comment by 50megas** [comment]
#1380

**Comment by searum** [comment]
fix falta aplicarlo
