### ISSUE TITLE
[Misión] (Vallefresno) Carcajes vacíos: 13615

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1463]
No hay flechas (item=45004) por ningún lado.

es.wowhead.com/quest=13615/carcajes-vacios‎

**Comment by iBrianAR** [comment]
Recuerdo este simple bug por verlo recientemente.

<hr>

• <strong>Nombre</strong>: <a href="http://es.wowhead.com/quest=13615">Carcajes vacíos</a>
• <strong>Enlace</strong>: <a href="http://es.wowhead.com/quest=13615">http://es.wowhead.com/quest=13615</a>
• <strong>Descripción</strong>: <a href="http://es.wowhead.com/npc=33284">Truun</a>, en la Empalizada de Mor'shan quiere que recojas 10 flechas útiles en la región del Lago Cielo Estrellado.
• <strong>Problema</strong>: No hay <a href="http://es.wowhead.com/item=45004">flechas útiles</a> ubicadas en los sitios indicados.
• <strong>Observaciones</strong>: Recorrí bastante el lugar para comprobar si existen "<i>flechas útiles</i>" spawneadas, pero por lo visto no hay ninguna.

<hr>

**Comment by Kiritoo** [comment]
Fix
