### ISSUE TITLE
[NPC] Kadrak: 8582

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1465]
No está en su posición, por lo que no se pueden hacer todas las misiones que te mandan a hablar con él. Bueno, a decir verdad he tenido que dejar todas y cada una de las misiones que he cogido de la zona...

http://es.wowhead.com/npc=8582/kadrak

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
