### ISSUE TITLE
[Misión] (Vallefresno) Responsabilidad de Demonio: 13806

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1467]
No se puede hacer click en los portales para desactivarlos.

http://es.wowhead.com/quest=13806/responsabilidad-de-demonio

**Comment by iBrianAR** [comment]
Exactamente como dice asman1. No se puede hacer clic para desactivar los portales, asimismo evitando completar la misión.

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

Cuando caiga el server tiene que haber dos tipos de piedras juntas, para mision horda y mision alianza
