### ISSUE TITLE
[Misión] Un jarro de agua fría: 25

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1469]
No se puede entregar una vez completada. Además te manda a un poblado distinto del que debería para tampoco poder entregarla cuando llegues.

es.wowhead.com/quest=25/un-jarro-de-agua-fria‎

**Comment by redneo** [comment]
A mi me la entrega bien y los dos npcs que se pueden entregar estan en su sitio...

**Comment by paellaencol** [comment]
Te deja entregarla al "Capitán Tarkan" http://es.wowhead.com/npc=34559 ? Aunque el npc está en su sitio e incluso da la opción de completarla no te deja completarla, valga la redundancia
