### ISSUE TITLE
¿Y donde estan mis llaves? (creo que tambien en plural)

### ISSUE THREAD

**Issue by Hellythium** [RoDNet/Bugtracker-Infinium-4.3.4#147]
Buenas, aquí Darkstar reportando otro error, algo critico en algunos casos por que hay teníamos llaves que son muy difíciles de conseguir para abrir mazmorras y otras cosas, a lo que me refiero es que la bolsa para las llaves a desaparecido del sitio de donde debería de estar, rueda la imagen:
![wowscrnshot_070413_210223](https://f.cloud.github.com/assets/3613748/751788/494215b0-e517-11e2-9826-2402f72d0b4c.jpg)

**Comment by Hellythium** [comment]
mala foto, no me aparece el puntero, pero la bolsa de las llaves debería de estar entre ''Asistencia al cliente'' y la bolsa que por defecto abre F4, en mi caso ''Agujero portátil''.

**Comment by ghost** [comment]
http://us.battle.net/wow/es/forum/topic/2548789981 por favor, leer las notas de los parches antes de abrir reportes :) (una recomendación nada más).
