### ISSUE TITLE
[Hechizos/Talentos][DK] Escudo de Sangre

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1471]
Buenas.
Quería reportar que el escudo de sangre (http://es.wowhead.com/spell=77513) no funciona correctamente porque no se acumula cada vez que se usa el Golpe Letal y parece que tambien los puntos de maestría no afectan la cantidad de absorción.
Gracias y hasta luego.

**Comment by searum** [comment]
Te confundes, en ningun momento dice que se acumule cada vez que se usa... Yo al menos no lo veo

**Comment by ghost** [comment]
Está en las notas del parche 4.0.6
http://eu.battle.net/wow/es/game/patch-notes/4-0-6
"Si se usa Golpe letal mientras ya está activo Escudo de sangre, la nueva absorción se acumulará con la vieja en vez de reemplazarla."
Me olvidé de poner la fuente, mil disculpas.
Gracias!

**Comment by searum** [comment]
Seguimos en las mismas, estamos en 4.3.4 y han pasado otras versiones, no se si han habido cambios pero por lo que se de la spell eso no es asi, revisarlo y yo encantado lo pongo :p

**Comment by Velcositro** [comment]
Revisé cada nota entre los parches 4.0.6 y 4.3.4, se cambió en el 4.0.6 tal como dice Rhoemer ("Si se usa Golpe letal mientras ya está activo Escudo de sangre, la nueva absorción se acumulará con la vieja en vez de reemplazarla.") y después ya no se cambió más, por lo tanto debería acumularse y no reemplazarse.

Edito: Quisiera recordar que el máximo que se puede acumular el escudo es a la vida total del DK que lo usa, que solo debe funcionar en presencia de sangre (http://eu.battle.net/wow/es/game/patch-notes/4-1-0#deathknights) y que el escudo solo absorve daño físico.

**Comment by searum** [comment]
fix
