### ISSUE TITLE
[Bastion de baradin] Argaloth

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1475]
ID: http://es.wowhead.com/npc=47120/argaloth

El lot de argaloth esta bug siempre tira las piernas tier de mago ya van siendo 3 veces que lo hacemos y solo tira eso 
deberia de tirar 2 epico de los 135 epicos que puede dar

**Comment by searum** [comment]
fix
