### ISSUE TITLE
[Bastion de baradin] Occu´thar

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1476]
id: http://es.wowhead.com/npc=52363/occuthar

El boss actuamente le afecta cc es decir stun, congelar y hechizos asi.

el boss no esta tirando ningun lot lo matamos 1 ves y no solto nada deberia de tirar 2 epicos de los 151 epicos que se puede despojar

**Comment by ghost** [comment]
También le afectan silencios, por lo que se interrumpen sus mecánicas de los ojos, llamas etc. Todo se puede interrumpir con stuns y silencios.

**Comment by efectokoleos** [comment]
arreglado

**Comment by lamaza** [comment]
No que lo iban a quitar...
