### ISSUE TITLE
[Bastion del Crespuculo] Feludius

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1477]
id: http://es.wowhead.com/npc=43687/feludius

El hechizo Helar del boss http://es.wowhead.com/spell=82746
Inflige daño de Escarcha masivo a todos los enemigos cercanos, con una reducción masiva de daño al distanciarse del taumaturgo. Los enemigos empapados quedarán congelados y sufrirán daño extra.

El boss lanza daño de escarcha a todos los enemigos cercanos pero este daño deberia de reducirse miesntra mas lejos estemos de el. El caso es que no se esta reducciendo el daño por la distancia que estemos del boss y como nos pego a todos el daño directo sin reducir por la distancia wipeamos....

**Comment by efectokoleos** [comment]
arreglado
