### ISSUE TITLE
mision dk [El camino de los reyes] bug

### ISSUE THREAD

**Issue by ramdres026** [RoDNet/Bugtracker-Infinium-4.3.4#1478]
no se encuentra el rey Varian en ventormenta

**Comment by Kiritoo** [comment]
Hola ese no es el fallo realmente sino que no podias ver los npcs(ninguno) no solo el rey, por un aura de la zona de los dks hace un rato le puse un fix al portal para eliminar ese aura para cuando cojas el portal a la ciudad puedas ver los npcs, ahora hay que revisar si tras entregar la mision en el rey desaparecen los npcs.
Si es asi comentarlo.
Cierro, saludos.
