### ISSUE TITLE
Arenas

### ISSUE THREAD

**Issue by sherik12** [RoDNet/Bugtracker-Infinium-4.3.4#148]
Probando las arenas encuentro que la decirculo de valor esta bug carga la arena pero no lanza la batalla, queda en preambulo y ademas con las puertas abiertas xD
![wowscrnshot_070413_210955](https://f.cloud.github.com/assets/4358923/751798/be0d8608-e518-11e2-88fa-7c08b5d44add.jpg)

**Comment by F4NT4SM4** [comment]
recordaba que jugaba en un server que servia mas o menos esa arenas
uno conmineza abajo en el subterraneo hay unos acensores que nos hacia subir a la arena cuando conmenzaba y empezabamos a matarnos algo asi recuerdo xD
