### ISSUE TITLE
Traducción y arreglo misiones huarguen.

### ISSUE THREAD

**Issue by ArixStark** [RoDNet/Bugtracker-Infinium-4.3.4#1484]
Casi todas las misiones fallan en el OfferRewardText, y wowhead no ofrece traducción alguna.
Misión: 
-¡A cal y canto! -------ID: 14078
-Aquí pasa algo ------ID: 14091
-La hora del caos ----ID: 14093
-Evacúa la Plaza de los Mercaderes -----ID: 14098
-Recuperar los suministros -----ID: 14094
-Órdenes reales ---- ID:14099
-Alguien te sigue la pista ----ID: 14275 (falta completamente el texto de completado)
-Disparo firme -----ID :14276 (quest de cazador) (falta completamente el texto de completado)
-Ya que estás en ello ----ID: 24930
-Viejas divisiones -----ID: 14157
-El tejado de la prisión -----ID: 28850
-Por los pelos -----ID: 14154
-Hermanos enfrentados -----ID: 26129
-El arsenal del Señor rebelde -----ID: 14159 (a parte de la traducción, esta quest se supone que está disponible solo después de "Hermanos enfrentados", pero la puedes coger sin hacer la otra.)
-Desde las sombras -----ID: 14204
-Mensaje para Cringris -----ID: 14214
-Salvar a Krennan Aranas -----ID: 14293
-Hora de reagruparse -----ID: 14294
-Sacrificios -----ID: 14212
-Sangre y cenizas -----ID: 14218
-¿Rendirse? Nunca. ¿Retirarse? A veces -----ID: 14221
-Resistencia final ----ID: 14222 (los guardias pegan mucho y matan a los npcs necesarios. Una vez muerto, al reaparecer, no se ven, ya que los guardias parece que peguen a la nada.)

**Comment by searum** [comment]
Ya tengo todo fixeado, excepto los complete text que has puesto que no existen.. en ningun lado he conseguido los datos ni en sniffs
