### ISSUE TITLE
server of al parecer por una micion

### ISSUE THREAD

**Issue by celenox** [RoDNet/Bugtracker-Infinium-4.3.4#1485]
jajaj estaba hay jodiendo por una micioncita y al parecer como que el server se jodio...!

**Comment by F4NT4SM4** [comment]
pasate por aqui http://www.reignofdarkness.net/wow/noticia/62/

**Comment by Kiritoo** [comment]
Estamos haciendo un mantenimiento, pasate por la noticia de la web que comenta @F4NT4SM4 
Saludos.

**Comment by lamaza** [comment]
La página esta caida. A quien pueda interesar: https://twitter.com/RoD_Network
