### ISSUE TITLE
[hechizos] Seal of Justice - Paladin

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1487]
Buenas, http://old.wowhead.com/spell=20164

Hace un par de semanas, dicho hechizo estaba funcionando lo más de bien después de que lo habían fixeado. Mas o menos hace 10 días o algo así dejó de dar el efecto de ralentización con cada golpe, y ahora no sirve para nada :/, solo para tirar sentencia.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/590

**Comment by searum** [comment]
fix, falta aplicar

**Comment by lamaza** [comment]
Gracias. Quedo bien!.
