### ISSUE TITLE
[Misión] (Tierras de la Peste del Este) Las bestias cadáver

### ISSUE THREAD

**Issue by deswolfdaza** [RoDNet/Bugtracker-Infinium-4.3.4#1488]
coloco los pozos de luz argenta alrededor de las bestias cadaveres pero no me cuentan.
cuando coloco los pozos lo unico q hacen es acercarse a los mobs y seguirme cuando me muevo :S

http://es.wowhead.com/quest=27530#comments

**Comment by Velcositro** [comment]
Venía a reportarla, sigue bug.

**Comment by redneo** [comment]
Fixeada, aunque no como me gustaria.
