### ISSUE TITLE
[Misión] Las bestias cadáver

### ISSUE THREAD

**Issue by deswolfdaza** [RoDNet/Bugtracker-Infinium-4.3.4#1489]
coloco los pozos de luz de las bestias cadaveres pero no me las cuentan como destruidas.
los pozos me siguen si me muevo y se acercan a los mobs q me atacan

http://es.wowhead.com/quest=27530#comments

**Comment by Mhryel** [comment]
Doble reporte https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1488
