### ISSUE TITLE
Piroguardia Brasadivino

### ISSUE THREAD

**Issue by Eralion** [RoDNet/Bugtracker-Infinium-4.3.4#1491]
Buenas, con un amigo nos fuimos a intentar a hacer Cumbres Roca Negra, queríamos pasar para ir a la Guardia de Ala Negra. pasamos la primera zona donde se desbloquea una puerta, seguimos hasta la Sala de Vínculos donde esta este NPC, y matamos a todos los orcos que allí habían. el boss no puede ser herido, se mueve y ataca pero nosotros no podemos hacerle ningún daño, ni utilizando el pedestal de la sala.

http://es.wowhead.com/npc=9816#comments

**Comment by lamaza** [comment]
Claro, es que antes de los parches, solo llegabas al boss y le dabas sin activarlo ni nada. Ahora hay que activarlo, aqui están los pasos. https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1312 

De todas maneras no llegarán hasta Alanegra porque falta 1 evento (El Estadio RocaNegra) para abrir un par de puertas en esta mazmorra, que por cierto ya esta reportado. Usen el buscador de issues.

Cerrar por favor.

**Comment by efectokoleos** [comment]
cierro
