### ISSUE TITLE
[Bomba de Humo] Picaro

### ISSUE THREAD

**Issue by Vic2tor** [RoDNet/Bugtracker-Infinium-4.3.4#1492]
Bueno no se si es en mi picaro o en de los de mas, pero lo que pasa esque cuando uso la habilidad de [Bomba de Humo] que supuestamente no me pueden atacar solo con ataques con areas.
Pues al utilizarlo recibo felchazos, bolazos y espadazos.
por favor intentar arreglarlo.
Att: Blueblood.

**Comment by hairblood** [comment]
no es asi tal cual:tiene que estar uno con el debuff y el otro no:si los 2 tienen el debuf te podra pegar.
Prueba que alguno duele contigo y te ataque de lejos mientras estas dentro de la bomba,veras que no podra

**Comment by Vic2tor** [comment]
Aqui estoy haciendo la prueba con un compañero (Cazador), probando si esta o no esta bug, el esta a un distancia alejada y luego se acerco para probar si aun me seguia targeteando y sin duda depues de esos 5s habia seguido disparado y la pet igual.
![wowscrnshot_082613_151428](https://f.cloud.github.com/assets/5310615/1025908/bd367498-0e52-11e3-8883-9e341eba5af9.jpg)

**Comment by ghost** [comment]
Se ve que ambos tenéis el debuff xD, no tomaste ninguna otra imagen?

**Comment by searum** [comment]
Esta mas que comprobado que no está bug. Si estan dentro de la bomba de humo te puede pegar y si estan fuera no. Solo con ataques a distancia no pueden pegarte... Dentro de la bomba de humo pueden pegarte con todo. Y si, si funciona correctamente porque lo acabo de probar yo mismo con 3 wows xD
