### ISSUE TITLE
Mastery: Shield Discipline 

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1494]
Abro de nuevo, que en el anterior reporté mal la ID

La Maestría del sacerdote disciplina (aquí tengo dudas, ya que en la vista previa de talentos el IDtip me dice que la ID es:77484; sin embargo en el libro de hechizos el IDtip me dice ID:86475) no está funcionando desde hace unos días.

Pese a llevar equipo con maestria, y que visualmente marca como que tu maestría está escalando, esto no sucede. Es decir hay dos problemas:
-Ni funciona la maestría base
-Ni funciona la maestría añadida por equipo

Gracias.

**Comment by orcca** [comment]
A mi sacer le pasa lo mismo marca que tendría que tener una absorción de 25k el escudo le sale de 17k cuando lo lanzas, no pone bien la mestria y ahora te pasa a sombras y que te encuentras? que el escudo del sacer dps es de 16k? enga ome no me jodas 1k menos de heal a dps? dura dos golpes en bg..

**Comment by paellaencol** [comment]
A ver, correcto no es, ahora mismo tienes un escudo a pelo, solo en base a tu sp, ni la maestria está funcionando (tampoco la base) ni el multiplicador de disciplinas gemelas https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1727

De todas maneras por lo menos ahora la forma del escudo a pelo ya es la correcta

**Comment by efectokoleos** [comment]
arreglado
