### ISSUE TITLE
[Sacerdote] Palabra de poder escudo ID:17 fórmula 4.3.4

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1495]
Buenos días.

Antes que nada, me gustaría publicar aquí la fórmula que debería tener este hechizo de absorción, ya que desde que se implementó este parche, la sanación de éste ha ido variando por semanas.

La fórmula para el parche 4.3.4 es la siguiente:

8136 (de absorción base) + (0.87 x Poder con hechizos)

A esto hay que multiplicarle diversos modificadores si se llevan los talentos correctos puestos.
Estos serian

x1.06 via "Disciplinas gemelas" ID: 47588
x1.2 via "Palabra de poder mejorada: escudo" ID: 14768
x1.2 via "Maestría: escudo de disciplina" ID: 77484 https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1494 (esto como maestría base). Cada punto de maestría otorgaría un multiplicador de 1.025 extra

Un saludo, y espero despejar dudas con este tema

P.D. La fórmula se puede encontrar por google, de todas maneras pongo el enlace desde donde lo he obtenido:

http://elitistjerks.com/f77/t127522-4_3_discipline_priest_compendium/

Gracias.

**Comment by paellaencol** [comment]
Añado un detalle más que no expuse anteriormente.

El escudo, al igual que el resto de hechizos de sanación se puede ver mejorada vía "Árcangel" (81700), si se lleva el talento "Árcangel" (87151).

Árcangel otorga un multiplicador de 1,03; 1.06; 1,09; 1.12 o 1,15 (dependiendo de las cargas de "Evangelización" (81661)  que se tuvieran en el momento de activar Árcangel)

**Comment by searum** [comment]
la formula esta la correcta, sobre lo de arcangel haz otro issue please.. vamos, 1 issue por bug y arcangel aunque mejore el escudo no es el escudo :p

**Comment by paellaencol** [comment]
Searum, si no es mucha molestia, podrías decirme cual es la fórmula que estais utilizando para esta spell? Porque aún contando que disciplinas gemelas está bug https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1727 y la maestría tambien https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1494 me sigue absorbiendo de menos.

Con mis 8122 de poder con hechizos, y sin contar las spell que están bug me saldría:

8136 (base) + (0.87x8122) x 1.2 (via "Palabra de poder mejorada: escudo" ID: 14768)= 18242
sin embargo está absorbiendo 17625 puntos actualmente

P.D. creo que el multiplicador de 0.87 está actualmente algo bajo, tal vez en 0.80 y poco, porque acabo de probar esta misma spell en la rama sagrada y también me da de menos.

P.D.2

Si quieres y como veo que está cerrado, abro un nuevo reporte con estos datos, o seguimos con el actual.

**Comment by paellaencol** [comment]
Uh, y con esto ya acabo. No, no tenía razón con lo del Árcangel, no hace falta que lo reporte. Sin embargo, vuelvo a poner la fórmula que utiliza un sacerdote del oficial con el escudo (está en el último mensaje):
http://eu.battle.net/wow/en/forum/topic/1751686636

**Comment by ghost** [comment]
@paellaencol abre otro reporte, los cerrados no se leen, y está bug. Mi sacer esta al nivel 14 y absorbe 9816 xDDD

**Comment by paellaencol** [comment]
Ahora lo volveré a reportar. Tu escudo está absorbiendo más de la mitad que el mío con casi 9k de poder con hechizos.

P.D. Así podrás solearte mazmorras.
