### ISSUE TITLE
[ Warlock > Fear ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#1496]
Miedo: http://es.wowhead.com/spell=5782

El efecto de miedo del brujo actualmente necesita muchísimo daño para romperse, haciendo este efecto más similar a un Stun que a un CC, ya que pueden bajar más del 50% de tu vida durante el estador de Fear.

**Comment by searum** [comment]
yo no lo veo q sea asi...

pd: eres un lloron.

**Comment by lamaza** [comment]
Pides respeto y no respetas a los jugadores, gracias Searum.
