### ISSUE TITLE
Brujo-invocar demonio

### ISSUE THREAD

**Issue by MadScientist96** [RoDNet/Bugtracker-Infinium-4.3.4#1497]
El problema esta en que el hechizo invocar demonio del brujo no aparece al conectarte, cuando entras, lo arrastras del libro de hechizos a la barra de acción, pero luego cuando t desconectas desaparece.
No es un bug muy importante pero si pueden arreglarlo facilmente se lo agradezco.
Gracias

**Comment by Kiritoo** [comment]
Probaste a ponerlos de uno en uno, ir arrastrando los iconos de las pets a la barra, en vez de el de invocar?
Saludos.

**Comment by MadScientist96** [comment]
asi si que funciona muchas gracias
