### ISSUE TITLE
Intendente de los Martillo Salvaje

### ISSUE THREAD

**Issue by Heredill** [RoDNet/Bugtracker-Infinium-4.3.4#1498]
El intendente de la facción no tiene opción para vender ningún objeto.

**Comment by Kiritoo** [comment]
Fix

**Comment by Heredill** [comment]
Disculpa amigo tengo logro exaltado, no puedo comprar, solo sale el icono de vendedor pero al clickarlo no me presenta los objetos.

**Comment by Kiritoo** [comment]
Te comento falta aplicarlo.
Saludos.
