### ISSUE TITLE
[DK] Instructor reinciar talentos

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#150]
Los instructores de los dk no me dan la opcion de reiniciar talentos

**Comment by ghost** [comment]
Y los devs son adivinos y saben cuales son los npcs xd

Aquí los dejo: 
http://es.wowhead.com/npc=29196/lord-thorval
http://es.wowhead.com/npc=29195/lady-alistra
http://es.wowhead.com/npc=29194/amalthazad

No tienen opción de reiniciar talentos, ni de aprender doble especialización, y Lord Thorval ni tiene para aprender los hechizos.

**Comment by redneo** [comment]
Arreglados los 3 que has puesto.
