### ISSUE TITLE
[Paladin] Sentencia

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1500]
ID: 20271
Sentencia esta pegando 2 veces
me refiero a que lanzo una sentencia y al objetivo le llegan 2

es como el embate del war que antes hacia 2 o el escudo del sacer que cura 2 veces :p

**Comment by ghost** [comment]
Has comprobado que sean sólo 2? a mi los paladines me hacen daño de 4 en 4 y de lejos xD

**Comment by F4NT4SM4** [comment]
Si son 2 se ve como si fueran 4 pero las otras 2 que sobran es por sello de mando

**Comment by searum** [comment]
esto no tiene sentido, dependera del sello.. cierro porque los sellos estan reportados.
