### ISSUE TITLE
[Paladin] Sello de verdad

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1501]
ID: http://es.wowhead.com/spell=31801/sello-de-verdad

Desatar la energia de este sello infligira 97p de daño de daño sagrado (ojo estoy testeando sin equipo y talento) aumentado un 20% por cada aplicacion de censura

el bug es que no se esta aumentando el daño por las acumulaciones de censura

Tire sentencia pege 97p.... ahora acumulo 5 aplicaciones de censura y tiro denuevo sentencia sigo pegando 97p deberia de aumentar 20% por cada acumulacion que deberia siendo 100%  97+97= 194

**Comment by searum** [comment]
fix
