### ISSUE TITLE
[Quest] Felendren el desterrado

### ISSUE THREAD

**Issue by Shiira** [RoDNet/Bugtracker-Infinium-4.3.4#1502]
Quest: http://es.wowhead.com/quest=8335/felendren-el-desterrado

Antes de comenzar con el reporte, advierto que soy primeriza con la raza Elfo de sangre, he buscado en wowhead, aparentemente tiene que aparecer en una de las plataformas, pero no logro encontrarlo.

Puedo completar los 2 primeros requisitos, pero el npc que dropea http://es.wowhead.com/item=20799, que es http://es.wowhead.com/npc=15367 no parece que esté.

Gracias y disculpad si realmente está, llevo buscandolo 20 minutos por toda la isla.

**Comment by redneo** [comment]
Está en lo MÁS alto de una plataforma donde dice wowhead.

En academia Falendren.

Te cierro el ticket, si no lo encuentras lo vuelves a abrir, gracias por participar de RoD

**Comment by Shiira** [comment]
Gracias redneo, mis disculpas por las molestias del ticket
