### ISSUE TITLE
Bug en textura.

### ISSUE THREAD

**Issue by Vic2tor** [RoDNet/Bugtracker-Infinium-4.3.4#1503]
Hola muy buenas, estaba en Vega tuercespina haciendo misiones y derrepente me veo con escudos y espadas flotantes... y claramente me salia que era una bestia (Sale el nombre de la bestia) , pero lo mano es que no me dejaba targatearlo.
![wowscrnshot_082713_112759](https://f.cloud.github.com/assets/5310615/1033451/a2581b32-0efb-11e3-9753-ff344756ea26.jpg)

![wowscrnshot_082713_112904](https://f.cloud.github.com/assets/5310615/1033452/b20d7838-0efb-11e3-92d7-ec737f7c4ede.jpg)

**Comment by ghost** [comment]
Yo también tomé screens, pero no sabía que era. Menos mal que eres cazador y se ve xD

**Comment by efectokoleos** [comment]
en el proximo reinicio estará arreglado, estaba puesto para k los dinosaurios volaran xd
