### ISSUE TITLE
[Guerrero] Bug visual de ira

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#1504]
Al darte algun buff que aplique regeneración de maná la ira empieza a subir todo el rato pero en realidad no estas ganando ira entonces te aparece que tienes 100 pero no sabes cuanta tienes en realidad. Los hechizos que lo bugean son por ejemplo:

Bendición de poderío: spell=19740
Tótem Fuente de maná: spell=24854

**Comment by F4NT4SM4** [comment]
este bug visual pasa con todas las clases que no usan mana
DK: poder runico
war: ira
etc...

**Comment by Kiritoo** [comment]
Arreglado bug visual, falta compilar. Si veis que falla en algun aspecto, ira, energia, enfoque.. avisad
