### ISSUE TITLE
[Brujo] Talento Fuego de alma mejorado

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#1505]
Veréis el problema de este talento es que debería aumentar el daño de fuego y sombras durante 10sg un 8% después de usar fuego de alma. Se puede ver aquí.

![wowscrnshot_082713_151812](https://f.cloud.github.com/assets/3939699/1034574/248ba9a6-0f1b-11e3-8794-06e98f2713e7.jpg)

Sin embargo como se puede ver en la imagen no salta. 

![wowscrnshot_082713_152036](https://f.cloud.github.com/assets/3939699/1034584/6aa809fc-0f1b-11e3-8359-49060c37e568.jpg)

Un saludo y gracias

**Comment by searum** [comment]
fix
