### ISSUE TITLE
[Misión] El Agua Bendita de la Claridad: 26433

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1506]
Al despojar la fuente (object=759) no da el ítem que pide la misión item=58811

Además, el NPC que da esta misión, la da doble. Es la misma misión aparentemente, ya que pide el mismo objeto. Aún así, el principio de la descripción es distinto.

http://es.wowhead.com/quest=26433/el-agua-bendita-de-la-claridad

**Comment by redneo** [comment]
No soltaban el item al 100% ya está cambiado.
