### ISSUE TITLE
[Infralar] Aeonaxx y Xariona

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#151]
Aeonaxx   http://es.wowhead.com/npc=50062/aeonaxx
Xariona     http://es.wowhead.com/npc=50061/xariona

Dos PNJs rares en el mismo lugar en infralar, con poca vida, poco nivel, no se les puede pegar y siempre estan ahi los dos

Capturas:

Aeonaxx
![wowscrnshot_070413_215134](https://f.cloud.github.com/assets/4895839/751876/a231f972-e51e-11e2-8296-cc4487bd3b5f.jpg)

Xariona
![wowscrnshot_070413_215129](https://f.cloud.github.com/assets/4895839/751877/a9ab892a-e51e-11e2-9c46-6899c9fa8ee1.jpg)

Como ven, ambos dracos estan ahi juntos y siempre estan ahi, no deberia ser asi ya que son rares.

**Comment by WarSxNes** [comment]
lol pides mucho Lvmb hihihi no creo que sea tan facil esa animacion para que la puedan arreglar.
Y eso que yo le pedi a redneo que arreglara las quest de Harrison Jones en ULDUM cuando estabamos en 4.0.6a

Esta muchisimo mas sencillita... las animaciones del PAVO :P

https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1012?source=cc <<< el pavo !gluber!
http://www.youtube.com/watch?v=2d0BtFzXiko <<<< ahi les dejo el video

> Y por cierto que habra que ver, si no estan bug ... QQ... voy a llorar

http://www.youtube.com/watch?v=2T1YjljjVuQ <<< esta de Harrison Jones lol se recuenda de la pelicula xD

**Comment by ghost** [comment]
@WarSxNes si, seguro que no será facil, pero se puede internarlo, ¿no? :)

**Comment by WarSxNes** [comment]
Eso si :+1:  pero que primero sean las de Harrison Jones xD..... le daria un gran credito al server xD ver todas las animaciones xD de la historia.

Lo que me facina son los cohetes de tecnologia goblin lol con la sonrisota  hahaha...

> por cierto cambie el link del video para dejarles uno con todo y audio xD
> http://www.youtube.com/watch?v=QYA2PUMg4sM <<< y este es otro con todas las de Harrison Jones vs el Nazi Goblin y sus hombres.

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/79
