### ISSUE TITLE
[Misión] (Hyjal) In the Rear With the Gear

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1510]
En retaguardia con los suministros http://es.wowhead.com/quest=25234

Suministros Crepusculares http://es.wowhead.com/object=202652
Los gobs no existen/no se ven por lo que no se puede realizar la misión.

Tampoco se pueden conseguir los suministros mediante los npcs
Proveditor Crepuscular http://es.wowhead.com/npc=39438
Porque no estan/no se ven.

Un saludo

**Comment by Kiritoo** [comment]
Fix, falta aplicarlo.
