### ISSUE TITLE
[Misión] (Hyjal) End of the Supply Line

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1511]
Fin de la línea de suministros http://es.wowhead.com/quest=25233

Proveditor Crepuscular http://es.wowhead.com/npc=39436

No estan o no se ven, por lo cual no se puede matarlos para completar.

Un saludo

**Comment by Kiritoo** [comment]
Fix, falta aplicarlo.
