### ISSUE TITLE
[Misión] (Hyjal) A Bird in Hand

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1515]
Pájaro en mano http://es.wowhead.com/quest=25731

Hola está misión funcionaba en la 406 ahora cuando se apaga la señal de fuego no aparece marion alagusano para capturarla y interrogarla.

Marion Alagusano http://es.wowhead.com/npc=41112

Video: http://www.youtube.com/watch?v=V3x9gTAzgSk

Saludos.

**Comment by redneo** [comment]
creo que está reparada, cuando caiga el server... me cierras el ticket si es asi.

**Comment by crowel** [comment]
Hola ya funciona pero cuando aparece marion alagusano al apagar la señal de fuego, sale uno en vez de dos.
Un saludo.
