### ISSUE TITLE
[Infralar] Portales

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#152]
Bueno, en infralar en el templo de la tierra, que es donde uno aparece cuando agarra el portal para infralar, a la hora de devolverme para orgrimmar no encontre los portales, y luego mire los otros portales y me di cuenta que no habia ninguno, nisiquiera el de ventor.

![wowscrnshot_070413_215450](https://f.cloud.github.com/assets/4895839/751885/6843c082-e51f-11e2-8b02-39bcc91bc8ee.jpg)

Deberian estar los portales para la capital de cada faccion, no?

**Comment by WarSxNes** [comment]
**_COMENTARIO:_** no se si con el cambio se reiniciaron algunas quest.... Pero has intentado hacer las quest para abrir los portales?

Si eres horda con Mr. Tablero te da las quest llamas **(Heroe's Call:)** que incia la cadena de quest hacia todas las zonas, incluyendo una quest que se llama creo (el llamamiento) bueno eso en el lado ali. y asi comienzas a abrir los portales de uno por uno.

Quien sabe a lo mejor aqui en 4.3.4 tienen algun aura y no los puedes ver.
O simplemente estan bug y no estan xD.....
Ooo!! puede ser que en esta version; Ventisca los ahiga retirado =)

**Comment by ghost** [comment]
@WarSxNes si retiran los portales.. ¿cómo sales de infralar? xd, y no, no me digas piedra hogar, porque en infralar puedes poner tu piedra hogar xd.

Lo de las misiones no sé la verdad si se resetearon, pero yo las tenía todas hechas y no puedo ver los portales.

**Comment by redneo** [comment]
Cuando caiga el server tendrian que estar, no pudiendo coger el portal de la faccion contraria y creo que solo si tienes la reputacion subida usar el portal al trono.
