### ISSUE TITLE
[Misión] Vuelo a Muerohelecho: 26701

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1522]
Cuando hablas con el NPC para volar, no ocurre nada especial, es un maestro de vuelo cmoo cualquier otro que te lleva a las rutas que conoces, no a donde te manda la misión.

http://es.wowhead.com/quest=26701/vuelo-a-murohelecho

**Comment by redneo** [comment]
arreglada
