### ISSUE TITLE
[DK] Espiral de la Muerte

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1523]
ID: http://es.wowhead.com/spell=47541/espiral-de-la-muerte

La espiral de la muerte cura a los objetivos no-muertos amistoso. Los dk usamos exanimenato para convertirnos en no-muertos y curarnos lo que dure el exanimenato

El bug es que me esta curando sin activar el exanimenato puedo estar curandome siempre con tal que tenga poder runico es decir nunca me matarian en 1v1...

**Comment by ghost** [comment]
Espero que se arregle pronto y sea fácil meter la condition al spell :S

**Comment by searum** [comment]
fix
