### ISSUE TITLE
perdida de mascotas

### ISSUE THREAD

**Issue by shogun1968** [RoDNet/Bugtracker-Infinium-4.3.4#1527]
Tengo un cazador y constantemente pierdo la mascota y no la puedo recuperar. He domado varias y con todas me pasa lo mismo, al cabo de un rato, desaparecen y no aparecen cuando las llamo. Por si sirve de ayuda, sobre todo me  ha pasado en Hyjal. Muchas gracias

**Comment by searum** [comment]
ta fix
