### ISSUE TITLE
boss de exhibicionismo luna genta atacando  

### ISSUE THREAD

**Issue by bubble1580** [RoDNet/Bugtracker-Infinium-4.3.4#1528]
![wowscrnshot_082713_194036](https://f.cloud.github.com/assets/5325644/1039122/8723e018-0f77-11e3-814d-1a4ff9167c2b.jpg)

**Comment by redneo** [comment]
Muy grafico el reporte, pero no lo entiendo...

**Comment by ghost** [comment]
Ese Boss está encadenado. Es como si fuera una pieza de museo, para que veas lo que te vas a encontrar dentro de la mazmorra. Sin embargo, por lo que se ve en la foto, el boss está libre de ataduras y es hostil, mientras que debería permanecer totalmente estático gracias al debuff que tiene.

**Comment by redneo** [comment]
arreglado!
