### ISSUE TITLE
Buscar a Neltharaku Bug!!!!

### ISSUE THREAD

**Issue by Asesino150000** [RoDNet/Bugtracker-Infinium-4.3.4#1529]
Hola queria decirles que la mision Buscar a Nerltharaku esta bug.El caso es qu ehay que completarsela a un dragon que esta volando i no nos deja completarla.

Gracias.

http://es.wowhead.com/quest=10811/buscar-a-neltharaku

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1387?source=cc
Ya reportada porfavor comprobar que no este creado ya antes de reportar.
Saludos.
