### ISSUE TITLE
[BUG dk] 118 dks en mi cuenta

### ISSUE THREAD

**Issue by tirador** [RoDNet/Bugtracker-Infinium-4.3.4#153]
BUenas como dice el titulo tengo 118 dks en mi cuenta, k comparto con mi mago pero grande fue mi sorpresa al ver tantos dks me lo areglarian porfavor. aki ta una imagen. 
![wowscrnshot_070413_174721](https://f.cloud.github.com/assets/4945398/751940/5ac455e4-e523-11e2-834c-120c0e913443.jpg)

**Comment by tirador** [comment]
ojo por si acaso no toke a ninguno ni los logee si kiera ni borre ninguno de esos dks porfavor areglenmelo.. gracias

**Comment by ghost** [comment]
A mi se me arreglo eso, por si acaso entra en tu dk (cualquiera) y cambia los talentos para que desaparesca tu pet, y luego cierra el wow borra cache y vuelve a entrar, tal vez funcione.

**Comment by 50megas** [comment]
ami seme quito solo, creo que  despues de logear con el dk

**Comment by ghost** [comment]
Este tipo de bugs ya estan solucionados tengo entendido, y sino, se solucionan solos.
