### ISSUE TITLE
Pérdida de pets del cazador y spell Disuasión bug

### ISSUE THREAD

**Issue by 3du42d0** [RoDNet/Bugtracker-Infinium-4.3.4#1532]
eso, que cuando tameas una mascota al rato montas y desmontas y no está o se queda peleando con algún mob y al llamarla o retirarla no se puede, también pierden sus talentos, no sabría decir que es lo que lo provoca, tal vez al dejarlas en el establo y luego retirarlas lo pierdan no estoy seguro.
Lo otro es la spell llamada Disuasión  (spell=19263) que al utilizarla te permite seguir atacando al enemigo

**Comment by ghost** [comment]
a ver...has hecho 2 issues iguales. Has reportado dos cosas distintas en cada issue. Has reportado dos cosas que ya están reportadas.

Intenta leer las normas y no dar trabajo extra a los GMs. Te pongo unos consejos:
1. Reporta sólo una cosa en cada issue.
2. Antes de hacerlo, asegúrate de que no está ya reportado (este mismo está 3 reportes debajo tuya..no sólo no está en otra página, es que solo tienes que bajar la mirada xD). Puedes usar el buscador que hay arriba para esto.

Puedes cerrar tus dos issues dándole a Close, así podrás ahorrar más trabajo a los GMs, se agradece la intención.
