### ISSUE TITLE
Error con mi pj

### ISSUE THREAD

**Issue by arieldariop** [RoDNet/Bugtracker-Infinium-4.3.4#1533]
![wowscrnshot_082813_123945](https://f.cloud.github.com/assets/5331321/1043209/b6ed28b8-0ff9-11e3-93ff-7d9cb4e36449.jpg)

Este es mi pj, parece como si estuviera borracho xD Le sale como humo color dorado, después de tomar un brebaje para una misión la cual está bugeada en Loch Modan. Sinceramente no me acuerdo el nombre de la misión, sólo me acuerdo que tenía que ocultarme con un arbusto, rociar un murloc con el brebaje, pero sólo te rocias a vos mismo. Mi pj está así desde entonces xD. Favor de arreglarlo

**Comment by Kiritoo** [comment]
Pon ticket in game.
