### ISSUE TITLE
	 El Anfiteatro de la Angustia: ¡Korrak el Sanguinario!

### ISSUE THREAD

**Issue by bubble1580** [RoDNet/Bugtracker-Infinium-4.3.4#1536]
http://es.wowhead.com/quest=12948

El Ultimo Elite De esta misiones

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1311 Ya reportado, porfavor lo repito como siempre antes de reportar mirar si ya esta creado.
