### ISSUE TITLE
hola

### ISSUE THREAD

**Issue by bubble1580** [RoDNet/Bugtracker-Infinium-4.3.4#1538]
El poder llamdo Rajar  Inflije 1/2 de daño . y me dice que tiene que infligir 567 y soy lv 81

**Comment by Kiritoo** [comment]
Como te dije en los demas reportes, esto ya esta reportado.
Tambien quiero comentar que se debe añadir un título correcto especificando bien el reporte y añadir el enlace o la id del hechizo, mision o npc a reparar. Sino se te cerrara el reporte.
