### ISSUE TITLE
Bonus 4 piezas pvp sacerdote healer

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1539]
Buenas noches.

Antes que nada decir que es una pena que se hayan borrado los reportes de bug de la 4.0.6, porque este problema ya estuvo reportado y arreglado completamente por un GM. 

Al utilizar palabra de poder escudo (ID:17) sobre nosotros mismos, el sacerdote debería ser inmune (temporalmente) durante los siguientes 4 segundos a cualquier efecto de ralentización de movimiento (aunque ya estuvieran presentes antes de aplicarse el escudo), es decir debería poder moverse durante esos 4 segundos al 100% de su velocidad.
Y de hecho si funcionara, nos aparecería un buffo sobre nosotros mismos durante esos 4 segundos haciéndonos inmune a efectos de ralentización. Siento no poder poner la ID de ese buffo porque al no funcionar la bonificación este buffo ya no salta, y en el wowhead ya no existe al poner el Pandaria (cambiaron de bonificación).

Este bonus existe en el set sanguinario, sañoso, implacable y cataclísmico.
Por poner un ejemplo pongo IDs de diferentes partes de este set:
(64798) (70612) (70305)

Pongo capturas de pantalla que hice para reportar el bug en el anterior bugtracker:

http://imageshack.us/a/img94/2162/wowscrnshot060913131938.jpg

<a href="http://imageshack.us/photo/my-images/23/wowscrnshot060913131938.jpg/" target="_blank"><img src="http://imageshack.us/a/img23/2162/wowscrnshot060913131938.th.jpg" border="0"/></a>

http://imageshack.us/a/img812/8846/wowscrnshot060913132037.jpg

<a href="http://imageshack.us/photo/my-images/812/wowscrnshot060913132037.jpg/" target="_blank"><img src="http://imageshack.us/a/img812/8846/wowscrnshot060913132037.th.jpg" border="0"/></a>

Como se observa sigo estando ralentizado pese a acabar de aplicarme sobre mi mismo la Palabra de Poder: Escudo (17)

Muchas gracias y un saludo.

P.D. Creo recordar que fue Bofur quien reparó esto en el anterior parche.

**Comment by redneo** [comment]
Y Bofur lo volvió a arreglar :D
