### ISSUE TITLE
linda bestia para CAZADOR [sugerencia]

### ISSUE THREAD

**Issue by tirador** [RoDNet/Bugtracker-Infinium-4.3.4#154]
BUENAS curiosamente vi en un cyber en un server k juegan unos feos de ahy k hay una linda pete como bestia y se la puede domar para  [cazador] el nombre es el siguiente  [flame cat form] seria bueno si la pusieran para provar k no aga caer el server de ser asi k se kede es una buena pete se los aseguro.. aki tengo imagenes
![wowscrnshot_070413_233458](https://f.cloud.github.com/assets/4945398/751954/19976fe6-e525-11e2-80b5-dec2e6c18e57.jpg)
![wowscrnshot_070413_233513](https://f.cloud.github.com/assets/4945398/751955/22a9f36a-e525-11e2-976c-8f6324607ac5.jpg)
![wowscrnshot_070413_233525](https://f.cloud.github.com/assets/4945398/751956/28628ea2-e525-11e2-9492-a0796c614f15.jpg)

**Comment by ghost** [comment]
Yo flipo con la gente...a ver, esto es un BUGTRACKER, aquí se reportan de forma ordenada, coherente y con el mínimo de faltas de ortografía bugs que puedan aparecer en el servidor y que afecten a la jugabilidad para solventarlos. Además, este es un servidor blizzlike, no añadirán cosas como la que propones por muy "way" que pueda ser el gato en llamas, la raza cazador de demonios, o delfines asesinos voladores llameantes que regalan horytoz pzpz.

Siento ponerme así de borde pero esque se ve cada post que no veas..y el staff no hace por atajar cosas como esta que solo les dan pérdidas de tiempo por buena que pueda ser la intención.

Si de verdad quieres ayudar y tener una comunidad y server de más calidad, te recomiendo que empieces leyendo las normas e información básicas y el título de cada sección.

Saludos.
