### ISSUE TITLE
bugg golpe mortal y fuerza irresistible

### ISSUE THREAD

**Issue by rdany19** [RoDNet/Bugtracker-Infinium-4.3.4#1541]
golpe mortal no enfurece casi nunca en un duelo de prueba pege 18 golpes mortales y saltaron 0 

fuerza irresistible da un 25% mas de daño con golpe mortal cuando usas cargar
tas usar cargar no se activa el buff 

gracias

**Comment by Kiritoo** [comment]
Hola dany debes añadir enlaces y solo un reporte por bug.
Dejo esto abierto hasta que lo cambies sino se cerrara.
Saludos.

**Comment by F4NT4SM4** [comment]
Golpe mortal activa enfurecer al ser critico y funciona

Fuerza irresistible si esta bug: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/592

**Comment by Mhryel** [comment]
Seguimos desde https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/592
