### ISSUE TITLE
[Campo de Batalla: Isla de la conquista] Bombas de seforio enormes

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1544]
Relacionado con: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1543
(de hecho el funcionamiento es idéntico, solo cambian daño e ids)

En la bg Isla de la conquista (zone:4710) las Bombas de seforio enormes http://es.wowhead.com/item=47030 no funcionan.

Explico el funcionamiento, estas bombas se pueden recoger en la base de la facción enemiga (funciona)

(a partir de aquí no funciona) Luego se utilizan para poner junto a la puerta de la facción enemiga, colocar una bomba activa la siguiente spell http://es.wowhead.com/spell=66674 tras 10 segundos, si no es desactivada, provocará http://es.wowhead.com/spell=66672 Esta habilidad hace 500 de daño de fuego a los pjs, y 6500 de daño de asedio a la puerta. Además interrumpirá a cualquier jugador que intente en ese momento desactivar alguna otra bomba que se encuentre presente en ese instante.
Estas bombas se benefician del daño si se tiene en poder la refinería http://es.wowhead.com/maps?data=4710:356252 (da el siguiente buffo: http://es.wowhead.com/spell=68722 ); y la cantera http://es.wowhead.com/maps?data=4710:646838 (buffo: http://www.wowhead.com/spell=68722 )

Añado que cualquier jugador de la facción contraria podrá desactivarla durante los 10segundos siguientes a la colocación de la bomba.

Por último, solo se podrá cargar con una bomba de seforio por jugador (funciona) y de cada stack de bombas solo 3 jugadores podrán coger una bomba cada uno, luego dicho stack desaparecerá, y no volverá a hacer presencia hasta dentro de 1minuto (respawn)

Al morir el portador de la bomba, si dicha bomba aún se lleva en el inventario, desaparecerá http://es.wowhead.com/spell=68377 (funciona)

En fin, son muchas cosas, gracias por la paciencia.

**Comment by searum** [comment]
fix
