### ISSUE TITLE
no se puede fijar hogar

### ISSUE THREAD

**Issue by xhide86** [RoDNet/Bugtracker-Infinium-4.3.4#1545]
buenas hablo con el tabernero para fijar el hogar pero no me sale esa opción, es el que se encuentra en tranquillien.

![wowscrnshot_082913_155233](https://f.cloud.github.com/assets/5238456/1050028/2b78af9a-10b3-11e3-9970-06713cceb165.jpg)

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
