### ISSUE TITLE
Mision 'No son mejores que los zombies'

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1548]
Resulta que tengo que encontrarme con un hombre llamado Darnell, pero este hombre no esta, lo he buscado por todos los sitios pero no esta. El mapa lo marca donde esta pero ahi no esta.
![wowscrnshot_082913_161234](https://f.cloud.github.com/assets/5339370/1050184/b19780a4-10b5-11e3-98fa-98272952624e.jpg)

**Comment by Kiritoo** [comment]
fix
