### ISSUE TITLE
[Sacerdote] Apariciones sombrias

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#155]
Las apariciones sombrias no funcionan, aparece un mini golem y se pone a atacar en "modo normal" por así decirlo, cuando debería salir una copia exacta de mi, y debería de caminar hasta el objetivo y al tocarlo explotar y causarle daño.

Enlace: http://es.wowhead.com/spell=78203

![wowscrnshot_070413_155917](https://f.cloud.github.com/assets/4663665/751995/94cdd3e6-e528-11e2-90ef-62189edaceb2.jpg)

**Comment by searum** [comment]
fix!

**Comment by ghost** [comment]
@searum ahora no aparece nada xd.

**Comment by redneo** [comment]
ya aparecen...
