### ISSUE TITLE
[NPCs] Faltan NPCS en el Intercambiador de la Cohetepista de Orgrimmar

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1550]
Faltan los siguiente npcs: 
http://es.wowhead.com/npc=35088
http://es.wowhead.com/npc=35087
http://es.wowhead.com/npc=35091
http://es.wowhead.com/npc=35085

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
