### ISSUE TITLE
[Misión] Fuente renovable

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1552]
No está el npc (Balboa) para ponerle las cargas y recoger los trozos. Me imagino qe las minas tampoco funcionarán bien, pero en esto ya estoy especulando.

Aqui dejo el link de la misión: es.wowhead.com/quest=14250

**Comment by redneo** [comment]
Esta Balboa, y misión arreglada.
