### ISSUE TITLE
[NPCs] Faltan NPCs en la Cohetepista del Norte

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1554]
Faltan los siguientes npcs:

http://es.wowhead.com/npc=35867
http://es.wowhead.com/npc=36676
http://es.wowhead.com/npc=37064

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.

El primero y tercero estan correctamente y visibles.
http://es.wowhead.com/npc=36676 Puse bien este.

**Comment by Wiinter** [comment]
Buenas, el primero y el terceron no son visibles. Puede qe con el Gm los veas, pero si eres un player no.

**Comment by Kiritoo** [comment]
Debes de pensar que no lo compruebo sin el gm, o si le miro si tiene auras? ...
