### ISSUE TITLE
[NPC] Falta Sorata Hilafuego en el Intercambiador de la Cohetepista del Norte

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1556]
Aqui dejo el link del NPC:
http://es.wowhead.com/npc=36210

**Comment by redneo** [comment]
Está, pero con un aura que no se le puede ver, para que misión se necesita?

**Comment by Wiinter** [comment]
Es para esta misión http://es.wowhead.com/quest=14345. Yo no lo consigo ver

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
