### ISSUE TITLE
[Misión] Necesitamos a Tictac

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1557]
No está tictac para destruir los pilares

Aqui dejo el link de la misión: http://es.wowhead.com/quest=14485

**Comment by redneo** [comment]
He puesto que salga tictac cuando lanzas la bengala cerca de los pilares, falta que cuente como objetivo de misión, pero me tengo que ir al meeeedico.... luego a ver si me acuerdo y la termino.

Edito:  A los 5 segundos de no estar en combate cuenta como killcredit.
