### ISSUE TITLE
[Misión] (Sierra Espolón) Estamos aquí para una cosa , o dos...

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1560]
Está el vagón pero no puedes interactuar con él.

Aqui dejo el link: http://es.wowhead.com/quest=25945

**Comment by paellaencol** [comment]
Wiinter una pregunta, como consigues que en tablón de Orgrimmar te sigan apareciendo misiones de nivel bajo con el título "Orden del jefe de guerra..."?
Porque al nivel 85 ya te desaparecen, aunque no las tengas hechas ni cogidas.

**Comment by Wiinter** [comment]
Yo es qe las tengo hechas desde antes de la entrada de la 4.3. Por eso las tengo. A mi ahora mismo tampoco me salen mas misiones de nivel bajo, puede qe sea un bug qe deberíamos reportar

**Comment by redneo** [comment]
Parcheada.
