### ISSUE TITLE
Todas las misiones de hyjal

### ISSUE THREAD

**Issue by sleepyhouse** [RoDNet/Bugtracker-Infinium-4.3.4#1561]
El 90% de las misiones de hyjal no funcionan. Ni para que pongo los links.

**Comment by Kiritoo** [comment]
... Eso es mentira llevo probadas 80/110 hechas correctamente, te parece un 90% que no funciona?
Ridiculo, mejor que te ahorres los reportes de este tipo.
Quizas estes acostumbrado en otros servidores a no llevar un orden y a cojerlas en cualquier lado en cualquier momento.
