### ISSUE TITLE
[Misión] Infestado de espías

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1562]
Tiras la bomba pero no se puede ver ningun espía. Diría qe no hay ningun espía o qe la bomba de humo no los desemascara.

Aqui está el link de la misión: http://es.wowhead.com/quest=26076

**Comment by redneo** [comment]
Cuando caiga el server tendrian que salir correctamente, con su nivel. abres un nuevo BT si los matan los npcs o si el aura que tienen no te permite verlos.
