### ISSUE TITLE
Campos de Batalla Puntuados

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#1563]
Los Campos de Batalla Puntuados son los que puedes hacer entre una misma facción y dan conquista en vez de honor, se necesita dos grupos de 5 cada uno para poder hacerlas, pero está bug y al ser dos grupos de 5, señalas a su líder, le das a iniciar juego de guerra pero está gris y dice "Debes seleccionar a un líder de otro grupo para poder iniciar un juego de guerra".
Con lo cuál no se pueden hacer.

**Comment by F4NT4SM4** [comment]
creo que te refieres a juegos de Guerra añadido en el parche 4.2 http://eu.battle.net/wow/es/blog/9977443/

los campos de batalla puntuados son 10vs10

**Comment by Wiinter** [comment]
Los juegos de guerra es por asi decirlo, un sitio para practicar. Los campos de batalla puntuados es diferente y son parecidos a las arenas, con sus puntuaciones y sus puntos semanales.

**Comment by F4NT4SM4** [comment]
seria bueno que lo implementara bg entre hermandades por competicion :c

**Comment by searum** [comment]
apenas hay gente para una aleatoria normal y siempre estais llorando como para molestarnos de momento en implementar esto... xD lo dejo pero vamos, es algo que tenemos pensado implementar aunque no lo haremos ahora.

**Comment by searum** [comment]
fix
