### ISSUE TITLE
[DK - Urgente] Pilar de Escarcha: 51271

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1564]
http://es.wowhead.com/spell=51271/pilar-de-escarcha

Bueno, tras ver varios DKs en BGs y duelos en escarcha (cosa bastante extraña) y ver que eran inmunes a ralentizaciones, stuns, CCs y demás, me picaba mucho la curiosidad. Ningún dk me respondía hasta ahora cuando le preguntaba por algo tan extraño, pero ya se saben las razones de porqué tanto frost de repente:

Tiene relación directa con este glifo: http://es.wowhead.com/spell=58635/glifo-de-pilar-de-escarcha

El cual añade una 2ª mecánica que debería clavarte al suelo durante su duración y hacerte inmune a los efectos de pérdida de control del pj. 

Lo que está pasando, es que no te clava, y los DKs son inmunes a los efectos de pérdida de control y de ralentización (incluyendo roots) durante toda la duración y continúan moviéndose a su velocidad normal. Si aprovechas y tiras todos los trinkets de daño y escudo anti magia, es una máquina imparable completamente durante 20s de duración del buff.

**Comment by searum** [comment]
fix
