### ISSUE TITLE
[Cazador] Disuasión: 19263

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1565]
Creo que ya fixearon lo de seguir disparando mientras estaba activa, no sé si ya se ha aplicado o no el cambio, pero ahora está fallando otra cosa: Al usar disuasión, el cazador pierde su aspecto y lo tiene que volver a lanzar al acabar disuasión.

**Comment by searum** [comment]
no estaba aplicado hace 5 dias xD
