### ISSUE TITLE
[Guerrero Armas] CD Interno Seccionar mejorado

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1566]
Siguiendo con el mismo problema reportado en: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1182

Queria reportar también, que efectivamente, esta habilidad no tiene CD interno, cuando el efecto "Seccionar mejorado" (23694) no debería producirse más de una vez cada 30segundos si se lleva el talento "Seccionar mejorado" (12668)

Esto, y sumado al bug reportado anteriormente, hace que no se pueda huir contra un guerrero, ya que te puede dejar clavado en el suelo todo el tiempo que quiera usando esta habilidad

P.D. "Seccionar mejorado" solo se debería aplicar al usar por segunda vez "Seccionar" (1715) sobre un objetivo que ya padezca este efecto.

Gracias

**Comment by redneo** [comment]
Arreglado y puesto el comentario en el 1182
