### ISSUE TITLE
[Portal] Portal a tierras devastadas

### ISSUE THREAD

**Issue by deswolfdaza** [RoDNet/Bugtracker-Infinium-4.3.4#1567]
los portales q estan el silithus para ir a tierras devastadas no me funcionan, como hago para ir a terrallende?

**Comment by redneo** [comment]
Arreglado

**Comment by Wiinter** [comment]
También puedes encontrar portales a tierras devastadas en las capitales de la Horda o de la Alianza, si también lo preguntabas
