### ISSUE TITLE
[Misión] Sable de hielo de cuna de invierno

### ISSUE THREAD

**Issue by didiii** [RoDNet/Bugtracker-Infinium-4.3.4#1568]
Para conseguir esta montura, hay que ir a Cuna de Invierno para hablar con Rivern Ventogélido, el cual se encuentra al norte, sobre una gran roca. Este personaje nos mandará en total 1 misión y otra misión especial formada por 20 misiones diarias. Vamos a explicarlo:

La primera misión es Juventud, divino tesoro. Esta misión consiste en coger 8 cachorros de dientes de sabre y entregárselos a Rivern.( esta se autocompleta sola)

La segunda misión es la más complicada, y se llama Crecen tan deprisa. Para esta misión nos pedirán varios componentes:
80 monedas de oro.
20 Paños rúnicos.
20 Cueros bastos.
20 Bigotes de cachorro de cuna de invierno.
Para conseguir los bigotes, Rivern nos dará un cachorro de cuna de invierno que posteriormente se convertirá en nuestra montura. Este cachorro nos ofrecerá una misión diaria, que consistirá en alimentarla o enseñarla a cazar en Cuna de Invierno.

El problema es que el cachorro te da las misiones pero es imposible completarlas aunque las hagas, por favor me gustaria que lo arreglaran si es posible ya que es una montura muy bonita. Gracias

**Comment by redneo** [comment]
Las misiones que son imposible completar, cuales son???

**Comment by didiii** [comment]
Hola, pues están en Ingles y son las siguientes:
- 'Borrowing' from the winterfall
-  A Cub's Cravings
- Hunting Practice
- Cub´s First Toy

2013/8/30 redneo notifications@github.com

**Comment by redneo** [comment]
http://www.wowhead.com/quest=29037 'Borrowing' from the winterfall, se pueden pillar los objetos, pero no cuenta cuando se lo lanzas.
http://www.wowhead.com/quest=29035 pasa lo mismo, los items se pueden coseguir, pero te lo lanzas a ti mismo.
http://www.wowhead.com/quest=29040 Puedes conseguir los items, pero no cuenta como objetivo de mision cuando se lo tiras.
http://es.wowhead.com/quest=29038 seria facil de parchear...

Para empezar, el npc, da 4 misiones a la vez, cosa que solo tendria que ser una al día...

**Comment by redneo** [comment]
Arregladas las 4 misiones, puestas que solo se pueda pillar una al dia, cuando caiga el server...

**Comment by lamaza** [comment]
Yo en lich king cuando consegui la montura, eran 2 por dia. Pero no eran diarias, sino que las podias hacer todo lo que quisieras, solo que eran 2 misiones y daban muy poca repu, asi era muy dificil ser exaltado, pero posible. No se si ahora cambió la cosa.
