### ISSUE TITLE
Misión: (Vallefresno) Bañado en luz.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1569]
En esta misión de Vallefresno, Orendil Hojagrande te da un objeto y tienes que usarlo en una zona iluminada del Lago Falathim. 
No sé si lo que está mal es el objeto o la zona en sí, pero el caso es que cuando llegas al claro donde está “la luz de Elune” no se completa la misión.

Aquí dejo el link de la misión en cuestión: http://es.wowhead.com/quest=13642
El objeto que te dan: http://es.wowhead.com/item=45065
El objeto que deberías crear en el sitio: http://es.wowhead.com/item=45066

**Comment by ghost** [comment]
Reparada.
