### ISSUE TITLE
Buscador de mazzmorra heroica aleatoria

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#157]
Es simple, la recompensa que debería de dar tendrían que ser 70 puntos de valor y no 70 puntos de justicia como se ve en la imagen.

![wowscrnshot_070413_093703](https://f.cloud.github.com/assets/4663665/752055/bf2e28ba-e52e-11e2-9d6b-0d73a813e82e.jpg)

**Comment by WarSxNes** [comment]
:+1:

**Comment by ghost** [comment]
Bug cerrado por estar imcompleto/información mal, veré si luego me da ganas y abro otro mejor xd.
