### ISSUE TITLE
Misión: (Sierra Espolón) No les mires a los ojos.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1574]
En esta misión de Sierra Espolón,  Boog "El hombre que susurraba a los engranajes" te pide que le consigas 10 Menas de hierro azur. En principio, te deberían aparecer las menas y que pudieras despojarlas. Las menas están, pero no deja despojarlas ni clickear sobre ellas.

Aquí dejo el link de la misión en cuestión: http://es.wowhead.com/quest=25642
El contenedor que debería dar la mena: http://es.wowhead.com/object=203132
La mena: http://es.wowhead.com/item=55174

**Comment by redneo** [comment]
Arreglada, dentro de la mina, hay unas cuantas.
