### ISSUE TITLE
Misión: (Sierra Espolón) ¡Requisar el dirigible!

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1575]
En esta misión de Sierra Espolón,  Boog "El hombre que susurraba a los engranajes" te pide que te subas al dirigible de la horda para impedir que asalten el Bastión Cortaviento. El caso es que el zepelín en cuestión no asoma nunca, y busqué por el Risco Cortaviento para ver si estaba parado en algún lado y tampoco lo vi.

Aquí dejo el link de la misión en cuestión: http://es.wowhead.com/quest=25652
El objeto al que te tienes que subir que no está: http://es.wowhead.com/npc=41009

**Comment by redneo** [comment]
Parcheada
