### ISSUE TITLE
Misión: Liberar a las hermanas.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1576]
En esta misión de Sierra Espolón, Lord Merobarbecho te pide que liberes a los rehenes del Risco Cortaviento. Para poder liberarlos, debes usar unas llaves que te darán al morir los hordas que hay por allí. Los hordas son muy amables y tras matarlos te dan generosamente una llave. El problema viene a la hora de usarlas, ya que la jaula se abre pero los rehenes no te cuentan para misión.

Aquí dejo el link de la misión en cuestión: http://es.wowhead.com/quest=25662

**Comment by redneo** [comment]
Cuando caiga el server tendria que funcionar, hazmelo saber si no es así
