### ISSUE TITLE
[Profesiones][Alquimia] Transmutar: Veraoro

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1578]
Buenas.
Quería reportar que la habilidad Transmutar: Veraoro (http://es.wowhead.com/spell=80243) de alquimia al parecer no reinicia su tiempo de reutilización a la medianoche como dice en el juego. Quizá se reinicia pasado un día y no a la medianoche, en ese caso edito el post.
Muchas gracias por la atención y hasta luego.

**Comment by Monleon** [comment]
Seguimos desde https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3036
