### ISSUE TITLE
Misión: El legado arcano.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1579]
En esta misión de Sierra Espolón, el Arcanista Valdurian te pide que uses la Prisión de Altonato con 5 Espíritus Altonato. Simplemente, se le tira el objeto que te han dado a un enemigo, éste muere y puedes despojar la cápsula que le tiraste.
Funciona bien lo de tirar la cápsula, mata al enemigo. El problema viene a la hora de despojarlo, ya que no te deja hacerlo.

También hay un pequeño bug, que consiste en que si tiras la cápsula cuando el enemigo ya estaba muerto y te acercas, morirás tú.
Por otro lado, tanto el Hechicero Altonato como el Ciudadano Altonato están con el nombre en inglés (Highborne Sorcerer y Highborne Citizen, respectivamente).

Aquí está el link de la misión en cuestión: http://es.wowhead.com/quest=25766
El ítem que te facilitan para hacerla: http://es.wowhead.com/item=55972
Y los enemigos sobre los que usarlo:
Charlatán Altonato http://es.wowhead.com/npc=34931
Hechicero Altonato http://es.wowhead.com/npc=34932
Ciudadano Altonato http://es.wowhead.com/npc=34938

**Comment by redneo** [comment]
Reparada, los nombres siguen en inglés, funciona en npcs 34938, y la caja, sigue matando (mucho)
