### ISSUE TITLE
[Chamán] Glifo Tótem de Sanación

### ISSUE THREAD

**Issue by Navalagamella** [RoDNet/Bugtracker-Infinium-4.3.4#158]
Cuando aprendes el glifo Tótem de Sanación [http://es.wowhead.com/spell=55456] además de curarte debería otorgar 195p de resistencia a la escarcha, fuego y naturaleza (no un 10% como pone en wowhead).
Lo que debería suceder es sanar y otorgar el mismo buff que el Tótem de Resistencias [http://old.wowhead.com/spell=8184].

**Comment by searum** [comment]
fix
