### ISSUE TITLE
[PNJ][Tierras Altas Crepusculares] Craw MacGraw

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1580]
Buenas.
El PNJ Craw MacGraw (http://es.wowhead.com/npc=49386), intendende del Clan Martillo Salvaje, no muestra los objetos para comprar.
Desde ya gracias y hasta luego.

**Comment by redneo** [comment]
A mi si que me los muestra, por cierto, borrados los arcanum duplicados de vendedores.
