### ISSUE TITLE
[Misión] Truenódromo: ¡El Enormus! : 25513

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1584]
Se está autocompletando sin matar a Enormus.

http://es.wowhead.com/quest=25067/truenodromo-el-enormus

Todas las misiones que da se pueden coger a la vez, y ninguna se puede hacer salvo las 2 que he reportado y que se autocompletan.

**Comment by redneo** [comment]
Ya salen en orden... voy a ver si puedo hacer que salgan los npcs...

**Comment by redneo** [comment]
Arreglado, sin textos, sin magias los npcs...
