### ISSUE TITLE
[Misión] Carroña de carroñeros: 25111

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1585]
Pasa exactamente lo mismo que con https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1582

http://es.wowhead.com/quest=25111/carrona-de-carroneros

**Comment by redneo** [comment]
Y la siguiente pasa lo mismo, con tu permiso, cierro los tickets, ya que mas o menos se puede hacer... podría hacerlo más elaborado, pero por el momento, prefiero arreglar cosas que no van a retocar cosas que medio van.

No te lo tomes a mal, me parece estupendo que me pongas los textos y demás...

**Comment by ghost** [comment]
Okey, gracias por los fixes :)
