### ISSUE TITLE
[Trinket - Low] Cuerno del traidor: 63633

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1586]
El espíritu se invoca, pero hace un daño de 1p. Tampoco dice sus frases, algunas de ellas son:

"I did it for my clan!"
"Who are you to judge me?"
"Release me from this torment!" 
"Have I not paid enough yet for my sins?"

http://es.wowhead.com/item=63633

**Comment by redneo** [comment]
Ya invoca al npc, hace algo más de daño y grita las frases.
