### ISSUE TITLE
Misión: La gnoma infiltrada.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1589]
En esta misión de Sierra Espolón, el Capitán de Exploradores Barus nos pide que vayamos a ver a Minx. Cuando llegamos al sitio donde debería estar, falta el NPC y la cadena no se puede seguir.

Aquí dejo el link de la misión en cuestión: http://es.wowhead.com/quest=25875
Este es el NPC que debería estar: http://es.wowhead.com/npc=41434

**Comment by redneo** [comment]
Ya aparece.
