### ISSUE TITLE
Misión: Planear el sabotaje.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1590]
En esta misión de Sierra Espolón, la Maestra Exploradora Yvonia nos pide que utilicemos los controladores de bomba goblin para destruir bombas de petróleo. El problema es que no se puede matar a los goblins para destruir las bombas, ya que, aunque están los NPCs, no se pueden fijar ni matar.

Aquí dejo el link de la misión en cuestión: http://es.wowhead.com/quest=25878
Este es el NPC que no se puede matar: http://es.wowhead.com/npc=41437
Este es el objeto que debería dar: http://es.wowhead.com/item=56140

**Comment by redneo** [comment]
El npc ya se le puede tarjetear
