### ISSUE TITLE
Ítem: Llave de jaula de la Horda.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1591]
Este ítem es requerido en la misión de “Liberar a las hermanas”. El problema es que este ítem lo siguen dando los NPCs aunque no se tenga la misión.

Este es el ítem que no deberían dar sin la misión: http://es.wowhead.com/item=55200
Y este es el NPC que lo da: http://es.wowhead.com/npc=41062

**Comment by lamaza** [comment]
Yo no veo entonces cual es el problema? Si se puede completar.

**Comment by Inmershus** [comment]
Es un bug el hecho de que dé el objeto sin tener que darlo.

**Comment by redneo** [comment]
Ya lo da solo si tienes la misión.
