### ISSUE TITLE
NPC: Oficial Jankie.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1592]
Este NPC es el primer NPC de la alianza que nos encontramos en la parte de arriba de Desolace. Es requerido para las misiones de “Ayuda para Desolace” y para “Se busca héroe: ¡Desolace!”, pero no está visible ni se le puede hacer target.

Este es el NPC que falta: http://es.wowhead.com/npc=36410

**Comment by redneo** [comment]
Npc puesto, aunque supongo que tendria que tener un aura que solo lo viera la alianza, como el que está en frente, que es horda... (no lo veras)
