### ISSUE TITLE
Misión: ¡Salva a los niños!

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1593]
En esta misión de Sierra Espolón,  tenemos que usar un silbato que nos da el Maestro Thal'darah y rescatar a unos NPCs. El problema es que el hipogrifo no funciona, es decir, no te deja montarte en él y rescatar a los NPCs.

Aquí dejo el link de la misión en cuestión: http://es.wowhead.com/quest=25889
Y este es el objeto que invoca el hipogrifo: http://es.wowhead.com/item=56168
Y este es el hipogrifo: http://es.wowhead.com/npc=41529

**Comment by redneo** [comment]
Ya se puede hacer la misión, con varios fallos:

No vuela, No agarra a los Druidas, El soltarlos te da como rescatados, con lo cual es fácil de hacer.

A falta de pan, así se queda la misión, sorry.
