### ISSUE TITLE
Bug de las tabernas.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1594]
El problema es que cuando entras en alguna taberna, muchas veces no se te ponen las “zzz” en el nivel, es decir, no estás en descansado. He adjuntado una foto con lo que pasa (estoy en taberna con ese personaje y sin descansado).

PD.: No sé si sólo pasa en determinadas tabernas, en todas o si es un error mío, pido disculpas si no era aquí donde tenía que postear esto.
![wowscrnshot_083013_181731](https://f.cloud.github.com/assets/5342568/1059080/9217a2b6-1193-11e3-9177-0ea12af3281a.jpg)

**Comment by ghost** [comment]
Sí, aquí se postean los bugs. En cuanto al reporte, creo que es cosa de algunas tabernas específicas, yo he pasado por muchas y en la mayoría me ponen bonus de descansado.

**Comment by redneo** [comment]
Ummm si encontrais alguna, decid cual y es facilmente arreglable.

**Comment by Inmershus** [comment]
Bueno, ahí puse la Pensión la Cebada de Thelsamar, en Loch Modan.
Otra puede ser la Posada Orgullo de León de Villadorada, en el Bosque de Elwynn.
Si encuentro más aviso :)

**Comment by ghost** [comment]
Creo que es mejor hacer un reporte por cada posada. Yo ya he reportado varias también.

**Comment by Kiritoo** [comment]
Cierro este mensaje.
Id reportando las tabernas que encontreis por separado y las vamos arreglando.
Saludos.
