### ISSUE TITLE
Misión 'La semilla del miedo' (No-muerto)

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1596]
Hola buenas. Resulta que te pide que asustes a unos renacuajos de nivel 1 y que para ello lo único que tienes que hacer es acercarte a ellos y con eso bastará. Pero lo que pasa es que cuando te acercas a ellos ninguno se asusta, no pasa nada. Espero que se solucione pronto. Gracias y saludoss.

**Comment by ghost** [comment]
Ya está reportada, se puede cerrar el reporte.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1345
