### ISSUE TITLE
Mision Sospechosos habituales.

### ISSUE THREAD

**Issue by Huardruid** [RoDNet/Bugtracker-Infinium-4.3.4#1597]
Cuando hablas con los trabajadores del muelle es como si hablaras con todos los que hay a su alrededor, y cuenta por 2

EDIT: no te deja completar la mision y los trabajadores siempre estan de rodillas

Link de la mision:
http://es.wowhead.com/quest=26997/sospechosos-habituales
Link de npc
http://es.wowhead.com/npc=29152/trabajador-del-muelle-de-ventormenta
Imagen
<a href="http://imgur.com/5wQGUZV"><img src="http://i.imgur.com/5wQGUZV.jpg" title="Hosted by imgur.com" /></a>

**Comment by redneo** [comment]
He puesto un Anduin en la sala del trono, ya que el tipo no te sigue...
