### ISSUE TITLE
Adepto y Atracador Filo Ardiente.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1599]
Hay 2 NPCs en Desolace cuyo nombre aparece en inglés, me refiero al Adepto Filo Ardiente y al Atracador Filo Ardiente (Burning Blade Adept y Burning Blade Reaver, respectivamente).
Los links son:
Adepto Filo Ardiente: http://es.wowhead.com/npc=4665
Atracador Filo Ardiente: http://es.wowhead.com/npc=4664

**Comment by Dekadencee** [comment]
Solucionado
