### ISSUE TITLE
Druida equilibrio

### ISSUE THREAD

**Issue by sherik12** [RoDNet/Bugtracker-Infinium-4.3.4#16]
No funciona eclipse de ningun tipo

**Comment by crowel** [comment]
Hola siento desmentirlo funcionan ambos.

Solar
![wowscrnshot_070413_024503](https://f.cloud.github.com/assets/3537253/746974/1d4160e4-e443-11e2-9d3f-dfd570dc81f0.jpg)

Lunar
![wowscrnshot_070413_024545](https://f.cloud.github.com/assets/3537253/746976/279b48b6-e443-11e2-9741-fa9ef3914490.jpg)

<h3>Tambien quiero añadir unos testeos de los ataques del druida equilibrio, comprobando al mismo tiempo con el DrD- Dr Damage.</h3>

*Cólera: http://es.wowhead.com/spell=5176  Hace casi 3k de daño menos a la media que deberia hacer.

*Fuego lunar: http://es.wowhead.com/spell=8921 Hace menos daño tanto el golpe principal, como sus ticks.

*Fuego estelar:  http://es.wowhead.com/spell=2912  Hace unos 2k menos de la media.

*Enjambre de insectos: http://es.wowhead.com/spell=5570 Hace un poco mas de daño del que deberia sus ticks.

*Oleada de estrellas: http://es.wowhead.com/spell=78674  Hace la mitad del daño que deberia.

*Tifón:  http://es.wowhead.com/spell=132469  Hace un poco más de daño que deberia.

*Huracán: http://es.wowhead.com/spell=16914 Se ve bastante bien, pega un pelín de más, 200p.

*Forma de lechúcico lunar: http://es.wowhead.com/spell=24858  Completamente bug, 
-Cambio a Forma de lechúcico lunar, lo que aumenta un 10% el daño que infliges con hechizos Arcanos y de Naturaleza y reduce un 15% todo el daño recibido. El druida no puede lanzar hechizos de sanación durante el cambio de forma. Lo unico que si funciona de esta especificación es "El druida no puede lanzar hechizos de sanación durante el cambio de forma". ya que al usarlo se saca la forma de lechucido jaja.

Espero que mis reportes ayuden.
Un saludo.

**Comment by crowel** [comment]
Quiero añadir que mi druida marca +0,20% en la celeridad de hechizosy parece que no soy el único.
![wowscrnshot_070513_033052](https://f.cloud.github.com/assets/3537253/751734/be0f15c8-e512-11e2-98e7-77834152da8d.jpg)

Como se puede apreciar en la imagen tengo 1135 (+8,86%) con lo cual mas la celeridad base del druida sin equipo supongo que tendria que tener un 9% de celeridad y tengo 0,20%

Intente quitandome set, relogueando, borrando cache, cambiando talentos y nada debe ser otro tipo de problema.
Espero que lo miren ya que tampoco funciona la celeridad y estadisticas de la forma de lechucido lunar.

Un saludo.

**Comment by villarta91** [comment]
Aprovecho este post yo también ;D

RAYO SOLAR http://es.wowhead.com/spell=78675 Afecta también al tamaturgo al lanzarlo y durante el tiempo que dura el efecto, cuando debería afectar solo a los enemigos debajo del hechizo
![wowscrnshot_070513_110403](https://f.cloud.github.com/assets/3321483/752790/4f9340ac-e552-11e2-921b-773b30e5837f.jpg)

**Comment by crowel** [comment]
@sherik12  Acabo de mover los dos reportes a dos Issues separados, cierra este si lo ves conveniente.
Un saludo.
