### ISSUE TITLE
[Orgrimmar]

### ISSUE THREAD

**Issue by AdriAzu** [RoDNet/Bugtracker-Infinium-4.3.4#160]
Los vendedores del T11 (en la 4.0.6) ahora deberían vender otro mas avanzado, creo recordar que es el t12

**Comment by Huardruid** [comment]
Creo que Bofur ya lo ha arreglado

**Comment by Wiinter** [comment]
Ha arreglado los sets pvps pero no los pves

**Comment by xefirot** [comment]
Cambia a poder ser el titulo por npcs set pve, asi nos servirá tanto para la horda como la alianza.

Vendedores de Ventormenta
Faldren Labravalle - Venta de objetos nivel 397 por valor, únicamente falta que vendra los tier 13 del modo normal y heroico.

Magathe Toneplata - Vende objetos nivel 378 pero debería venderlos por justicia y sigue vendiendo por valor. Además de que también le falta los tier 12.

Toren Landow - Vende objetos 346 y 359. Los 359 los sigue vendiendo por valor y carece de las piezas de tier 11.

**Comment by redneo** [comment]
Ambos arreglados
