### ISSUE TITLE
[MOB] Coloso Volantón Gorishi: 38305

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1601]
Este mob está repetido por 3 veces, por lo que se hace imposible matarle, al recibir el triple de daño.

http://es.wowhead.com/npc=38305/coloso-volanton-gorishi

Necesario para: http://es.wowhead.com/quest=24692

**Comment by redneo** [comment]
Ya solo hay uno.
