### ISSUE TITLE
[Misión] Perturbar sus refuerzos

### ISSUE THREAD

**Issue by deswolfdaza** [RoDNet/Bugtracker-Infinium-4.3.4#1602]
he recogido las runas necesarias (8) 4 para cada portal pero el portal no da ninguna interaccion, me dice q requiero cebo explosivo q lo tengo el el bolso pero nada no hace nada :S

http://es.wowhead.com/quest=10144/perturbar-sus-refuerzos

**Comment by redneo** [comment]
Funciona correctamente. Una vez que tienes las runas, puedes activar las puertas, lo cual cuenta como objetivo de misión.
