### ISSUE TITLE
Hunter>Disparo de Puntería.

### ISSUE THREAD

**Issue by Hellythium** [RoDNet/Bugtracker-Infinium-4.3.4#1604]
Buenas, es para informar que la spell ''Disparo de Puntería'' (que lastimosamente no encuentro la ID correcta de esta spell en Wowhead de Cataclysm, solo aparece de MoP) esta pegando exageradamente bajo, bueno no tan exageradamente bajo pero si esta quitando aproximadamente un 50 a un 65% menos de su daño debido según su informe de spell en el juego, muestro la imagen de lo que debe de quitar y de lo que esta quitando:

![wowscrnshot_083013_190132](https://f.cloud.github.com/assets/3613748/1061370/d308c28a-11d1-11e3-9f11-f3460a152c5f.jpg)
![wowscrnshot_083013_191220](https://f.cloud.github.com/assets/3613748/1061374/083364b0-11d2-11e3-838d-ebb4247839d6.jpg)
![wowscrnshot_083013_190211](https://f.cloud.github.com/assets/3613748/1061375/08355d9c-11d2-11e3-8e6e-0e9010b2eeb3.jpg)

Según la información de la spell debo de quitar 160% de daño con mi arma a distancia mas 9250 puntos de daño (y esto sin tener activado abalorios y sin tener buffos y más), ý según mis cálculos debo de quitar 7971,2 (4982x1,6 ósea 160% de daño normal infligido con mi arma) + 9250 = 17221,2 de daño normal mas o menos y haciendo mas cálculos 34442.4 de daño en golpe critico mas o menos, repito, sin tener buffos, hechizos, racial ni abalorios activos, pero como se muestra en las imágenes estoy pegando aproximadamente el 55% del daño normal y en golpe critico estoy pegando aproximadamente lo que debo de pegar en golpe normal, y eso que es en PvE, ósea que mi daño se reduciría considerablemente en PvP, y según mi pensamiento, para este spell, siendo el más poderosos del cazador puntería, aparte de Disparo de Quimera, me parece que su daño es ridículo a la hora de la batalla, eso es todo mi informe por ahora, espero que lo logren reparar pronto.

Nuevamente, gracias por su atención prestada y espero que solucionen estos dos grandes inconvenientes del cazador.

Saludos, Darkstar.

**Comment by ghost** [comment]
Buenas, te recomiendo que hagas otro reporte aparte para reportar lo de las pets y que al testear los daños, uses al muñeco de nivel 85, no al boss heróico xD.

**Comment by Kiritoo** [comment]
Solo un reporte por bug, modificalo porfavor.

**Comment by Hellythium** [comment]
Bueno, ya hare la separación, pero creo que lo del muñeco no es mucho problema, por que la otra vez, el jueves, estaba haciendo una mazmorra heroica de lvl 70 (de Terrallende) y en lugar de quitar mas estaba pegando críticos de 12ks y normales de 6-7ks, asi que por lo del muñeco no creo que sea mucho problema.
Añado que la mazmorra la estaba realizando junto a Lamaza y tenia el buffo de Bendición de Reyes, así que por eso no entiendo por que quitaba tan poquito.

**Comment by searum** [comment]
fix

**Comment by Hellythium** [comment]
Ya esta arreglado, gracias Searum.
