### ISSUE TITLE
NPC: Elissa Dumas.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1605]
Este NPC, en principio debería enseñar los mismos portales que el resto de instructores de magos, pero cuando hablamos con ella no enseña ni uno solo.

El ID del NPC es: http://es.wowhead.com/npc=4165

**Comment by redneo** [comment]
A ver ahora si los vende, ya que no tengo ningun mago alianza...

**Comment by Inmershus** [comment]
Jajaja yo la verdad es que dudé bastante, porque yo venía de lich y esperaba que esa me enseñara el de Darnassus, y pensé que igual en cata sólo enseñaba portales el de ventormenta xD

**Comment by Inmershus** [comment]
Pueees... no, sigue sin vender ni un solo portal xD

**Comment by Kiritoo** [comment]
Fix, falta aplicar.
