### ISSUE TITLE
Centinela de Darnassus.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1606]
Me he estado paseando un buen rato buscando un guardia de Darnassus que me pudiera decir donde se encontraba el instructor de primeros auxilios, el caso es que ninguna de las Centinelas de Darnassus da indicaciones acerca del instructor de clase, el banco, la taberna, las profesiones... etc etc.

La ID de las centinelas es: http://es.wowhead.com/npc=4262

**Comment by redneo** [comment]
A ver si ahora estan un poco más trabajadores.
