### ISSUE TITLE
Misión de Pesca de Darnassus: Abastecerse.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1608]
Esta misión de pesca (en inglés Stocking up) que da Astaia está completamente en inglés.

Aquí dejo el link de la misión en cuestión: http://www.wowhead.com/quest=29323

**Comment by redneo** [comment]
Todas las misiones, npc y cosas por el estilo mayor de la 406 estan en inglés... proximamente se meteran maás traducciones, ya se os dirá algo cuando esten.
