### ISSUE TITLE
Ítem: Pellejo de yeti perfecto.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1610]
Este objeto inicia una misión para aquellos jugadores que sean hordas. El caso es que también da el objeto a los alianzas, opción que en principio no debería poder hacerse.

El objeto es: http://es.wowhead.com/item=55167

**Comment by redneo** [comment]
Dificil de controlar eso, por el momento lo dejo tal cual ya que seria complicarse muchisimo que lo soltara solo para una facción (aun siendo posible). De todas formas no te deja coger la misión.
