### ISSUE TITLE
Misión: Fuerzas de la naturaleza: avispas.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1611]
En esta misión de Feralas, la Cuidadora Tessina te da un ítem de reclamo de avispas. Según he mirado por wowhead, no hay ninguna misión que dé ese NPC que se llame "Fuerzas de la naturaleza: avispas", sino "Fuerzas de la naturaleza: fuegos fatuos". Además, cuando usas el objeto que te han dado en un fuego fatuo que se encuentre por Feralas no cuenta en la misión.

Aquí dejo el link de la misión en cuestión (la que creo que es, ya que la otra no parece existir): http://es.wowhead.com/quest=25407
Los fuegos fatuos son: http://es.wowhead.com/npc=40079

**Comment by redneo** [comment]
http://www.wowhead.com/quest=25407 Wisp==Avispa==Fuego fatuo (Grande, muy grande quien lo tradujo)

Ya está arreglada.
