### ISSUE TITLE
Misión: ¡Escolta a OOX-22/FE!

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1612]
En esta misión de Feralas, nos piden que escoltemos a un pollo mecánico hasta un lugar seguro. El caso es que al coger la misión el pollo no se mueve del sitio y no se puede hacer la escolta.

Aquí dejo el link de la misión de escolta: http://es.wowhead.com/quest=25476
Este es el pollo mecánico que no se mueve: http://es.wowhead.com/npc=7807

**Comment by searum** [comment]
fix
