### ISSUE TITLE
Misión: A vueltas con los gigantes machacados.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1613]
En esta misión de Feralas, Zorbin Hipnoviento te da un objeto que debes usar con los Zancaorillas. Al usar el objeto, el NPC deja de ser élite y se vuelve un NPC normal, siendo posible matarlo en solitario.
El problema es que cuando usamos el objeto con el NPC, el Zancaorillas pasa a llamarse Zancaorillas machacado y su nivel aparece como calavera (yo era nivel 38, así que más de nivel 47 era) y es imposible matarlo (a nivel bajo).

Aquí está el link de la misión: http://es.wowhead.com/quest=25465
El objeto con el que poder reducirlos: http://es.wowhead.com/item=18904
El Zancaorillas antes de ser "reducido": http://es.wowhead.com/npc=5359
Y el Zancaorillas "reducido": http://es.wowhead.com/npc=14603

**Comment by redneo** [comment]
http://wowpedia.org/Zapped_Shore_Strider ese npc tiene que tener ese nivel, aunque claramente, la misión es de nivel más bajo... 

Lo pongo al nivel del no encogido.

**Comment by Inmershus** [comment]
Joder, pues qué cosa más rara si quieres hacer la misión, porque la misión se queda gris a nivel 46 o.o
