### ISSUE TITLE
Problema con reputacion en faccion Ramkahen

### ISSUE THREAD

**Issue by escontreras** [RoDNet/Bugtracker-Infinium-4.3.4#1614]
Hola gms, quisiera reportar un bug con la faccion Ramkahen aqui el link de la faccion: http://es.wowhead.com/faction=1173/ramkahen

el problema es que llegue a honorable:8292.... y de ahi no pasa entregue como 10 misiones que perdi porque no me dieron reputacio y ahi se quedo

**Comment by Kiritoo** [comment]
Porque quizas esas 10 misiones no deben de dar reputacón en ramkahen.
Sino especificas que misiones no podemos ayudar, aunque tambien tu puedes mirar en wowhead si esas 10 misiones dan o no dan ya que hay unas cuantas en uldum que no dan raputación de su propía zona.
Saludos.

**Comment by escontreras** [comment]
no anote la misiones pero las misiones con esa faccion son la de las esfinges si las entrego ahi tiene que ser de esa faccion

**Comment by Kiritoo** [comment]
Pues si no especificas no se puede comprobar.

**Comment by escontreras** [comment]
Otro modo de comprobar es que ayer pense que tenia un limite diario o no se misione bug entonces me puse el tabardo de esa faccion y hicimos aleatoria y mientras matabamos mobs y el boss no me dio nada de punton sobre la faccion se supone que el tabardo es para eso obviamente era un mazmorra lvl 85

**Comment by Kiritoo** [comment]
Tu ya estas ahora reportando otra cosa, si tienes problemas con el tabardo es aparte tu estas reportando las misiones aqui.
Si quieres que reparemos cierta reputacion de recompensa de las misiones debes de especificar cuales ya que nosotros no somos adivinos, cierro reporte por falta de info.
Respecto a lo del tabardo, solo un bug por reporte y siempre antes comprobando si está creado.
Saludos.
