### ISSUE TITLE
Talento Dedos de Escarcha MAGO no funciona

### ISSUE THREAD

**Issue by Cantadal** [RoDNet/Bugtracker-Infinium-4.3.4#1616]
El Talento del mago escarcha con id http://es.wowhead.com/spell=44544/dedos-de-escarcha no se activa nunca, no acumula ni se activa. Simplemente no funciona. Gracias

**Comment by paellaencol** [comment]
La ID del talento es 83074

Esta saltando, pero únicamente con la "nova de escarcha" (122), y con el "Congelar" (aquí debe de tener un 100% de posibilidades con el talento activado) de la mascota (33395).

Y además está saltando al ser golpeado llevando puesta la "armadura de escarcha" (7302), y si el objetivo enemigo tiene nuestro debuff de "enfriado" (7321). En esta parte tengo dudas que deba saltar, ya que el talento dice "efectos de enfriamiento ofensivos" (comprobad por favor, desconozco si es correcto, ya que esto es defensivo).

Pero también debería tener la probabilidad de saltar al utilizar "descarga de escarcha" (116); Cono de frio (120); "lanza de hielo" (30455) y Orbe de pirofrio (este al hacer varios ataques en poco tiempo tiene una alta probabilidad de hacer saltar este buffo) (tengo dudas acerca de si esta ID es la correcta 82731) y no sucede actualmente

---

Además al saltarnos el buffo de "Dedos de escarcha" (44544) la lanza de hielo (30455) debería hacer 4 veces más de daño, ya que el buffo de dedos de escarcha dice que tus hechizo "lanza de hielo" actue como si el objetivo estuviera congelado (cuando el objetivo está congelado, lanza de hielo cuadruplica el daño). Además mientras tengamos activo este buffo "lanza de hielo" hará aún un 25% más de daño. 
[La parte de este talento que concierne a "congelación profunda" (44572) funciona correctamente. Pero ojo! debería consumirnos una carga de "dedos de escarcha" y no lo hace]
Aclaro: que solo hay dos habilidades que consuman las cargas de dedos de escarcha, y son "lanza de hielo" y "congelación profunda", el resto no deben consumirlas

---

Qué está sucediendo actualmente? Que con el buffo de dedos de escarcha, la lanza de hielo o no hace daño (ni siquiera salta 0, inmune, fallo o resistir), o hace el daño normal que haría como si "dedos de escarcha" no estuviera activo.

**Comment by searum** [comment]
fix
