### ISSUE TITLE
Arqueología bug

### ISSUE THREAD

**Issue by escontreras** [RoDNet/Bugtracker-Infinium-4.3.4#1617]
Hola gms, les vengo a preguntar sobre la profesion de arqueologia que ustedes dicen que esta completamente funcional pero segun este video: http://www.youtube.com/watch?feature=player_embedded&v=Cj_4xPEkp2I ... Sale que da puntos en las profesion por recolectar fragmentos y a mi solo me da puntos cuando armo el objeto asi ya es demasiado dificil subir podrian revisar este bug por favor... Gracias

**Comment by ghost** [comment]
A esto ya te respondió Searum, cito:

"Claro que va bien amigo, eso que dices que es un "bug" es así, arqueología da puntos por recolectar hasta que tienes 50 de nivel de habilidad... Una vez superados esos 50 ya solo puedes subir haciendo objetos como dices :)

En el video se aprecia como el nivel de habilidad lo tiene a 1..."

**Comment by lamaza** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1020

Yo ya lo habia reportado, no se porque no lo arreglan o no lo mencionan :/

**Comment by escontreras** [comment]
Yo se que solo sube hasta 50 puntos en la profesion pero yo la llevo en 7 y es porque arme 3 objetos osea no sube ni desde 1 ni nada solo armando

**Comment by Dekadencee** [comment]
Fixeado
