### ISSUE TITLE
Chamán bugs

### ISSUE THREAD

**Issue by Navalagamella** [RoDNet/Bugtracker-Infinium-4.3.4#162]
Ya he reportado unos cuantos pero creo que mejor tenerlos organizados y no por ahí sueltos.

Arma Vorágine: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/116

Glifo Tótem de Sanación: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/158

Desatar elementos: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/117

Escudo de Relámpagos: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/111 - Es un bug visual muy molesto.

El poder de hechizos siendo chamán mejora no funciona o es un bug visual por que en aparece que tengo 0 de poder de hechizos. Al ser chamán mejora no tengo ni intelecto ni poder de hechizos, pero la habilidad Presura Mental [http://es.wowhead.com/spell=30814] parece ser que es el conflicto por que siendo chamán con cualquier otra especialización que no sea mejora (restauración y elemental) si que aparece el poder con hechizos.
Adjunto una imagen con la verdadera descripción de Presura Mental por que es diferente a la de wowhead. [http://sia1.subirimagenes.net/img/2013/07/05/13070502272557942.jpg]

Glifos:
Glifo Lobo Ártico [http://old.wowhead.com/spell=58135]: No hace nada, sigues teniendo la misma forma
Glifo Nova de Fuego [http://es.wowhead.com/item=41530]: No aumenta el rango
Glifo Escudo de Relámpagos [No he encontrado el verdadero glifo ni en wowhead ni en oldwowhead, pero creo que es este http://es.wowhead.com/item=71155]: El glifo lo que hace es que no te quitan las cargas de Escudo de Relámpagos al ser golpeado, pero no es así, pierdes las cargas y desaparece por no tener más.

Talentos rama Mejora:
Espíritu feral [http://old.wowhead.com/spell=51533]: Los lobos hacen muy poco daño, de 450 a 600 de daño con el glifo incluido cada lobo [http://www.wowhead.com/item=45771] en el cataclysm lo que hace es aumentar el poder de ataque de los lobos un 30% de nuestro poder de ataque; "As of patch 3.2.0, Spirit Wolves receive 35% of the shaman's armor, 30% of the shaman's attack power, 100% of the shaman's hit rating, and 30% of the shaman's stamina" el glifo aumenta un 30% más de poder de ataque (un 60% en total), y tengo 9582 de poder de ataque y los lobos no llegan ni a 1k de daño crítico. La curación tendría que ser un 150% del daño que hacen.

Poder congelado [http://es.wowhead.com/spell=63374]: El aumento de daño cuando el objetivo está afectado por choque de escarcha está bien, pero NO CONGELA al objetivo cuando está a más de 5m de distancia.

Talentos rama Restauración:
Despertar ancestral [http://es.wowhead.com/spell=51558]: No cura nada

Tótem de Enlace de Espíritu [http://es.wowhead.com/spell=98008]: No hace nada

**Comment by Navalagamella** [comment]
Arreglado el de cólera totémica.
El bug de escudo de relámpagos es un bug visual.

**Comment by ghost** [comment]
@Navalagamella perdón por cerrar tu reporte, puedes poner cada bug en un reporte separad?, muchas gracias.
