### ISSUE TITLE
Hechizos: Teletransporte, Portal e Invocar demonio.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1624]
Tengo tanto un mago como un brujo, y me pasa exactamente lo mismo con los dos. A partir de cataclismo, todas las invocaciones del brujo se aglutinan en un "Invocar demonio" y cuando haces click en esa habilidad te despliega un menú con todos los diablillos que tienes. Con el "Teletransporte" del mago pasa lo mismo, pero con los lugares a los que ir.
El problema es que cuando tú sacas ese menú a tu barra de acciones, al desconectarte y volver a conectarte desaparece y tienes que volver a sacarla.
No he encontrado por wowhead la skin de "Invocar demonio" ni la de "Teletransporte", así que dejo fotos.

Del Teletransporte:
![wowscrnshot_083113_154006](https://f.cloud.github.com/assets/5342568/1062352/e37adfba-1242-11e3-8813-b47f5873fbae.jpg)
![wowscrnshot_083113_154011](https://f.cloud.github.com/assets/5342568/1062353/ee9011b8-1242-11e3-831e-3797be44fe1c.jpg)

Y del Invocar demonio:
![wowscrnshot_083113_154141](https://f.cloud.github.com/assets/5342568/1062357/156dee4a-1243-11e3-80f1-ea260af00e21.jpg)
![wowscrnshot_083113_153805](https://f.cloud.github.com/assets/5342568/1062349/a1114204-1242-11e3-9603-bec006e20478.jpg)

No tengo fotos de la habilidad de hacer portales (que imagino que estarán agrupados exactamente igual) porque no tengo el nivel suficiente para aprenderlos, pero creo que pasará el mismo problema que con estas otras dos habilidades.
EDITO: Ahora que soy nivel 42 corroboro mi teoría xD
![wowscrnshot_083113_164258](https://f.cloud.github.com/assets/5342568/1062419/a6ce4df0-124b-11e3-8b67-2c8667fdd249.jpg)

**Comment by ghost** [comment]
Está diseñado así, el problema es que se eliminan de la barra de acciones. A mi me ocurre igual cuando aprendo un nivel más avanzado de una profesión y relogeo.

Para arreglarlo les harán falta las IDs, puedes usar el addon IDtip para ello.

**Comment by Inmershus** [comment]
Sí, si evidentemente tiene solución: volver a como estaba en lich y sacarte todos los portales, teletransportes y demonios a lo largo de la barra de acción xD
Pero claro, si posteándolo alguien lo puede arreglar, pues se postea, que no cuesta nada.

**Comment by searum** [comment]
fix
