### ISSUE TITLE
Mision: ¿ es ese tu goblin?

### ISSUE THREAD

**Issue by didiii** [RoDNet/Bugtracker-Infinium-4.3.4#1626]
Hola la mision es la siguiente: http://es.wowhead.com/quest=12969

El fallo es que no te deja desafiarla, le das y no pasa nada.

**Comment by WarSxNes** [comment]
Lol hihih las misiones de los Hijos de Hodir omg xD a empezar de Nuevo.... si no mal recuerdo es una cadena de 31 o 35 quest

http://www.wowwiki.com/Sons_of_Hodir <<<< son 35 quest, Mas las que tienes que hacer antes para coger la quest inicial... Haber si le pueden echar un OjO a toda la cadena xD. _(y si no pues echenlen los dos)_

**Comment by Kiritoo** [comment]
Esto está fix.
