### ISSUE TITLE
No me deja entrar al wow

### ISSUE THREAD

**Issue by MadScientist96** [RoDNet/Bugtracker-Infinium-4.3.4#1627]
Llevo jugando en este servidor hara 1 mes y nunca e tenido ningun problema para entrar pero hoy a partir de las 4 e intentado entrar y no me dejaba me salia o has sido desconectado del servidor o imposible conectar, he probado a desactivar el firewall de windows y he vuelto a instalarlo pero nada de eso a funcionado, por favor podrian decirme como solucionarlo, gracias

PD:tengo otro ordenador que utiliza la misma wifi y tambien le ocurre lo mismo cuando intento entrar

**Comment by Eressear** [comment]
Nada estamos muchisimos así. Tambien hay varios hilos en los foros. Dicen que están esperando a Searum para reiniciarlo o algo así entendí.
