### ISSUE TITLE
No me deja entrar en el WoW.

### ISSUE THREAD

**Issue by maxmontro** [RoDNet/Bugtracker-Infinium-4.3.4#1628]
Hoy. A las 17:30 estaba jugando, se me ha bloqueado el ordenador y he tenido que cerrarlo. Al abrirlo y reiniciar la partida, no me dejaba registrarme en el WoW.
PJ: PriceSoul. Elfo de la noche Paladin. LVL 29.

**Comment by Eressear** [comment]
Nada estamos muchisimos así. Tambien hay varios hilos en los foros. Dicen que están esperando a Searum para reiniciarlo o algo así entendí.

**Comment by Kiritoo** [comment]
Maxmontro el bugtracker es para errores del juego, bugs, para todo lo demás la web.
Saludos.
