### ISSUE TITLE
Codicia/Desencantar

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#163]
Buenos días.

Al estar en grupo y banda y hacer una tirada por codicia o desencantar nos sucede que:

-Muestra el valor de la tirada nada más darle a codicia o desencantar, aunque no haya tirado nadie más aún (debería de hacerlo cuando hayan tirado todos, o se acabe el tiempo para hacerlo)
-El resultado de una tirada por desencantar/codicia siempre es 128.

Gracias!

**Comment by ghost** [comment]
Sigue bug, anexo imagen
![wowscrnshot_080213_153944](https://f.cloud.github.com/assets/4663665/905407/d20bb98c-fc23-11e2-8836-14d7542b52f2.jpg)

**Comment by redneo** [comment]
Pero creo que luego hace bien la tirada

**Comment by paellaencol** [comment]
Si.
