### ISSUE TITLE
NPC: Emisaria Valustraa.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1631]
Este NPC localizado en Darnassus es un instructor de magos muy peculiar: enseña doble especialización, te resetea los talentos pero no te enseña habilidades.

Aquí dejo el link del NPC: http://es.wowhead.com/npc=17105

**Comment by Kiritoo** [comment]
Actualmente los instructores de magos en darknassus estan en la siguiente posición:
![wowscrnshot_091313_215443](https://f.cloud.github.com/assets/5061022/1141163/7fd45a1a-1cae-11e3-8c38-24d7937f1aa8.jpg)

Este quedo obsoleto, cierro.
Saludos.
