### ISSUE TITLE
NPC: Representante de la Feria de la Luna Negra Alianza.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1632]
Aunque sé que la Feria de la Luna Negra no está aun activa, me he fijado que está el NPC de la horda en Villadorada (que sólo debería aparecer en Mulgore), mientras que el NPC de la alianza ni siquiera está (no sé si está en Mulgore).

El link del NPC de la horda (Representante de la Feria de la Luna Negra) es: http://es.wowhead.com/npc=55396
EL link del NPC de la alianza es: http://es.wowhead.com/npc=54345

**Comment by Kiritoo** [comment]
Fix, falta aplicarlo.
