### ISSUE TITLE
[Horda NPC] Misiones del Tablón de mando del jefe de guerra

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1635]
Buenas tardes. 

Los tablones de anuncios de la horda ("object") bajo el nombre "Tablón de mando del jefe de guerra" no dan misiones de nivel bajo (inferior a cataclysm) una vez se es ya nivel 85, cuando deberían seguir dándolas.

Pongo desde el wowhead los enlaces de cada uno de estos tablones: Orgrimmar, Entrañas, Cima del Trueno, y Ciudad de Lunargenta

-Orgrimmar: Object 206109 y 206116 (ambos son idénticos y dan las mismas misiones)

http://es.wowhead.com/object=206109#starts:0+3+1+2

-Cima del Trueno: Object 207323 (este objeto también debería dar las mismas misiones que dan sus "parientes" de Orgrimmar)

-Entrañas: Object 207324

http://es.wowhead.com/object=207324#starts:0+3+1+2

-Ciudad de Lunargenta: Object 207325

http://es.wowhead.com/object=207325#starts:0+3+1+2

Gracias.

**Comment by redneo** [comment]
arreglado esos y los alianzas.

**Comment by paellaencol** [comment]
Gracias!

Una cosilla, solo falta que de esta http://es.wowhead.com/quest=28496/orden-del-jefe-de-guerra-azshara el resto las da todas ya.
