### ISSUE TITLE
Riendas de Poseidus

### ISSUE THREAD

**Issue by karmmero** [RoDNet/Bugtracker-Infinium-4.3.4#1636]
Poseidus, en Vash´jir, suelta la montura "caballito de mar subyugado". El problema es que al tratar de usarla, no deja invocarla en el agua, que es su cometido.

Link de la montura: http://es.wowhead.com/spell=98718#taught-by-item

**Comment by TFK13** [comment]
para que no lo pasen por alto por falta de pruebas , aquí les dejo yo unas imágenes:

![caballito de mar 1](https://f.cloud.github.com/assets/5740100/1375281/2e299196-3a7f-11e3-9697-ee318983cddc.jpg)
![caballito de mar 2](https://f.cloud.github.com/assets/5740100/1375285/3c056cf4-3a7f-11e3-9efe-e3c5a8d2b8ca.jpg)

Gracias por su revisión.

Un cordial saludo

Att: Budha

**Comment by Monleon** [comment]
Pruebalo porque diria que ya deja
