### ISSUE TITLE
[Sacerdote] Égida divina 47515

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1638]
Buenos días.

Ahora Égida divina ya está saltando con las sanaciones corr(ectas, es decir críticas y cualquiera producida por Rezo de Sanación (596)

Sin embargo, no se están acumulando los escudos producidos por égida divina, en lugar de esto los resetean.
Explico: si hacemos una cura crítica de 30k nos saltará durante 15segundos una "Égida divina" proporcional a está curación. El problema es que si durante esos 15 segundos hacemos una curación crítica de 5k, o un Rezo de sanación por valor de 6k, nos desaparecerá la "Égida divina" anterior que habíamos hecho con una cura de 30k, y nos la pisará una "Égida divina" mucho más pequeña.

En resumen, "Égida divina" debe stackearse el valor (hasta un máximo de en torno a un 40% de la salud del sacerdote) y no resetear el valor de absorción.

Adjunto vídeo explicativo:

http://www.youtube.com/watch?v=523XMJwz6YM

Visualizad únicamente el segmento comprendido entre el 6:20 y el 6:50

Gracias

**Comment by ghost** [comment]
http://wow.freakz.ro/spells.php?spell=47515

**Comment by ghost** [comment]
Añado otro problema de esta spell: La égida se la está poniendo al sacerdote, no a su objetivo.

**Comment by efectokoleos** [comment]
arreglado
