### ISSUE TITLE
Abalorio de poder con hechizo pvp

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1639]
Buenos días.

No sé si sucederá con todos los abalorios, pero por lo menos con el sañoso de poder con hechizos ocurre (70578).

"Cuando infinges daño o sanas a un objetivo tienes una probabilidad de obtener 1077p. de poder con hechizos durante 20seg"

Problema: solo se está activando el abalorio al inflingir daño con hechizos, pero no al utilizar hechizos de ayuda (curación)

**Comment by redneo** [comment]
Arreglado ese abalorio.
