### ISSUE TITLE
Bugs druida

### ISSUE THREAD

**Issue by Devilcray** [RoDNet/Bugtracker-Infinium-4.3.4#164]
Bien en las primeras imagenes se puede ver que cuando activo instintos de supervivencia me pega bastante mas de lo que deberias, cuando deberia ser al contrario.

Lo siguiente es que se me queda un debuff que pone Venganza, lo mas curioso que pone que aumenta el poder de ataque y en tanto por ciento me pone 0 jejeje aqui van los links de las imagenes

https://imageshack.com/scaled/large/41/gltk.jpg
https://imageshack.com/scaled/large/402/jdnq.jpg
https://imageshack.com/scaled/large/841/l1h4.jpg

**Comment by searum** [comment]
esto esta fixxx
