### ISSUE TITLE
[Guerrero Armas]  Talento Seccionar mejorado (12668)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1640]
Siguiendo de: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1566 y https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1182

Ahora ya se cumple el CD interno de 30segundos.

Sin embargo el efecto "Seccionar mejorado" (23694) se le está aplicando al objetivo al utilizar por primera vez la facultad "Seccionar" (1715), cuando sólo se debería aplicar al utilizar por segunda vez la facultad "Seccionar" sobre un objetivo que ya padezca el efecto "Seccionar".

En resumen, el primer "Seccionar" actualmente te está anclando en el suelo, cuando esto debería producirse en el segundo "Seccionar".

Gracias

**Comment by redneo** [comment]
El problema viene que primero le mete el seccionar 1715 y luego el mejorado, con lo cual cuenta que tiene el seccionar siempre, habria que cambiar el orden de como aplica la spell a que primero metiera el mejorado 23694 y luego el normal 1715, con eso se solucionaria.

Tal y como está ahora aplica 1715 y como lo tiene aplicado, por narices te aplica 23694.

No se si me he explicado bien :S

**Comment by F4NT4SM4** [comment]
que wea ya no sirve para nada el seccionar mejorado no importa cuantas veces le de no sale me han cagado el war ya era suficiente con el diminishing del cargar que me arruina el derribar ahora tambien me quitan seccionar mejorado como wea voy hacer war armas sin cc ¬¬
sin mencionar que tambien tengo maestria en actitudes bug y no puedo usar macros ¬¬

**Comment by lamaza** [comment]
tan dramático y con lo "raro o sospechosos" que estan los war y su dmg.

**Comment by F4NT4SM4** [comment]
chekea esto https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1074
hay 4 buff que no deben acumularse esos 4 dan 20% poder de ataque un total de 80%+Abalorio de fuerza 2000+ war fury Deseo de muerte aumenta un 20% el daño+ temeridad siempre daras critico

**Comment by searum** [comment]
fix
