### ISSUE TITLE
Mobs no desollables Rasganorte

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#1641]
Ningún animal de rasganorte es desollable, el pj hace la acción de desollar pero no aparece ninguna barra y nunca termina con lo cual a los peleteros nos es imposible subir la profesión.

**Comment by Kiritoo** [comment]
Añade ids de los npcs que encuentres o no podemos hacer nada.
Saludos.

**Comment by foxmclaud** [comment]
¿Me estas tomando el pelo? ¿que quieres que te ponga los 500 ids de los npcs que hay en rasganorte?, porque para ponerte uno o dos que son los que he intentado desollar y que falle el resto me da a mi que es algo mas gordo. Y si, he probado a desollar en todas las zonas.
