### ISSUE TITLE
Mision 'Habla con Sevren'

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1642]
Hola a todos. Resulta que en esta misión tienes que entregar un objeto llamo 'Restos de Devlin', evidentemente ese objeto para entregarlo te lo tienen que dar en cuanto aceptes la misión. El problema esta en que este objeto no te lo dan y como consecuencia no se puede completar la misión. Les dejo aquí el enlace de la misión:

http://es.wowhead.com/quest=25005/habla-con-sevren

Espero que lo arreglen pronto, saludos.

**Comment by efectokoleos** [comment]
arreglada
