### ISSUE TITLE
[Draenei] Racial

### ISSUE THREAD

**Issue by shials** [RoDNet/Bugtracker-Infinium-4.3.4#165]
http://es.wowhead.com/spell=59544/ofrenda-de-los-naaru Cura 4 puntos, de critico 8 puntos.
![wowscrnshot_070513_123100](https://f.cloud.github.com/assets/4938203/753156/f1519136-e55d-11e2-831e-1054773868f2.jpg)
![wowscrnshot_070513_123057](https://f.cloud.github.com/assets/4938203/753158/00932984-e55e-11e2-9496-9eee409cfeb5.jpg)

**Comment by redneo** [comment]
Arreglado

**Comment by shials** [comment]
Sigue curando 4 y 8 puntos Redneo.

**Comment by crowel** [comment]
Quizas se deba esperar al reinicio aunque no aseguro nada, un saludo.

**Comment by shials** [comment]
Nada que ver , sigue curando 4 y 8 puntos :)

**Comment by redneo** [comment]
Menos a los paladines, aun estando todos los ofrenda de los naaru con el mismo %

**Comment by shials** [comment]
Solucionado el problema de la racial con Draeneis Hunters.

**Comment by searum** [comment]
y con el resto?
