### ISSUE TITLE
Mision 'tu nuevo yo' (goblin)

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1650]
Te dice que compres 3 objetos pero cuando va a comprarlos a sus respectivos mercaderes no puedes. Solucionenlo porfavor y gracias.

**Comment by paellaencol** [comment]
http://es.wowhead.com/quest=14109/tu-nuevo-yo

http://es.wowhead.com/item=47045
http://es.wowhead.com/item=47046
http://es.wowhead.com/item=47047

Mira a ver en tu registro de misiones que no tengas esta misión repetida. La mayoría de problemas relacionados con esta misión es por esto.

**Comment by redneo** [comment]
hay dos misiones iguales, que llevan al mismo lado, una funciona a la perfeccion, prueba a encontrarla.

**Comment by sisu091** [comment]
Verdad, ya encontré la que funcionaba, graciaaass.
