### ISSUE TITLE
Acechadora Negra bug

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#1651]
En la mazmorra de terrallende "La Sotiénaga" no se encuentra el ultimo boss "Acechadora Negra" en la dificultad Heroica, en normal todo correcto.

**Comment by redneo** [comment]
id del npc para la proxima

http://es.wowhead.com/npc=17882

Y totalmente de acuerdo, alguna linea de la programacion le hace invisible a los players en modo heroico, aun estando ahi...

**Comment by foxmclaud** [comment]
Cierto se me olvido el id del npc, muchas gracias, y ya que se mira no estaría demás mirar las reputaciones de la maz, pues no dan con ninguno.

**Comment by efectokoleos** [comment]
arreglado
