### ISSUE TITLE
NPC: Torren Mandicuadrada.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1652]
Este NPC que se encuentra en Thelsamar (Loch Modan) tiene un interrogante de misión amarillo en la cabeza, a pesar de que no da misiones.

El enlace del NPC es: http://es.wowhead.com/npc=1153

**Comment by redneo** [comment]
Termina 7 misiones 
http://www.wowhead.com/search?q=explorer%27s+league+document y una más, va correctamente, lo que a lo mejor no tendria que ponerse la ?

**Comment by Inmershus** [comment]
Sí, si terminar sí termina, pero quería referirme a eso, al ? de la cabeza que le sigue saliendo pese a que no tengas ninguna misión.
