### ISSUE TITLE
NPC: Morick Cerveoscura

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1653]
Este NPC enemigo se encuentra por Loch Modan. El problema que tiene es que mete golpes físicos de 700 siendo tan sólo nivel 13, lo cual hace difícil o imposible (a no ser que lo mantengas continuamente en fear, en stun o alguna cosa así) de matar a nivel bajo. Creo que está bug por el hecho de quitar tantísimo (a nivel 10-17, que es cuando uno está leveando por esa zona, se tienen unos 200 o 250 de vida) con esos golpes.

El link de este NPC es: http://es.wowhead.com/npc=45369

**Comment by Kiritoo** [comment]
A mi me parece normal siendo un npc Raro.

**Comment by Inmershus** [comment]
Los NPCs raros quitan más que los normales y tienen algo más vida, pero no son Chuck Norris xD

**Comment by redneo** [comment]
Cambiado
