### ISSUE TITLE
NPC: Huarguerrero Roca Negra.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1654]
Estos NPCs enemigos se encuentran por Montañas Crestagrana. El problema que tienen estos NPCs es que meten golpes físicos de 900 siendo tan sólo nivel 16, lo cual hace difícil o imposible de matar a nivel bajo (básicamente, porque si te tocan te matan de un golpe), y más aun siendo élites como son. Creo que está bug por el hecho de quitar tantísimo con esos golpes ya que, pese a que son élites, no son dioses.

El link de estos NPCs es: http://es.wowhead.com/npc=43340

**Comment by redneo** [comment]
de 400 que me metia a 42...
