### ISSUE TITLE
NPC: Lady Jaina Valiente.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1655]
Este NPC se encuentra en Theramore (Marjal Revolcafango) y, pese a que da la misión de "Prueba de traición", no funciona todo lo bien que debería.
En principio, cuando coges la misión, Jaina debería darte (sólo cuando tengas la misión) la opción de teletransportarte a Ventormenta. 
El problema es que cuando le dices que te teletransporte a Ventormenta no funciona.

El ID de Jaina es: http://es.wowhead.com/npc=4968
Y el ID de la misión: http://es.wowhead.com/quest=27240

**Comment by redneo** [comment]
Arreglado
