### ISSUE TITLE
Zona: Nueva Thalanaar

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1656]
El problema con esta subzona de Feralas es que no se ve ni un solo NPC cuando llegas allí, independientemente de la misión que tuvieses para entregar allí. Un MJ me confirmó que los NPCs sí que están, pero que yo (y todo el que pase por allí, imagino) por lo visto estoy en otra capa que no me deja ver a ningún NPC.

No sé qué enlaces poner de este tipo de reporte, pero puedo buscar alguno si se precisa.

**Comment by redneo** [comment]
he puesto en su fase a los npcs que he visto.
