### ISSUE TITLE
NPCs: Místico y Atracador Zarpaleña.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1658]
El problema de estos dos NPCs de Feralas es que no se les puede pegar, ni acercándote a ellos (como reporté con otro NPC) ni haciendo áreas.

El enlace del Atracador Zarpaleña es: http://es.wowhead.com/npc=5255
El enlace del Místico Zarpaleña es: http://es.wowhead.com/npc=5254

**Comment by redneo** [comment]
Arreglado
