### ISSUE TITLE
[NPC]Caminasol Atohmo <Instructor de paladines>

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#166]
Hola con mi paladín este instructor comprobe que no funcionaba, con el que no se puede interactuar
Caminasol Atohmo <Instructor de paladines>
http://es.wowhead.com/npc=44725

![wowscrnshot_070513_124932](https://f.cloud.github.com/assets/3537253/753238/5026ca7a-e561-11e2-8c65-843c5fbf9731.jpg)

Un saludo.

**Comment by redneo** [comment]
No puedo ponerlo bien sin romperme los cuernos, lo dejamos pa otro momento, ya que el resto si que va

**Comment by crowel** [comment]
Fix
