### ISSUE TITLE
Misión: Un aroma irresistible para Lar'korwi.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1660]
En esta misión de Cráter de Un'Goro, Torwa Abrecaminos nos pide que nos acerquemos a los nidos de los raptores y que cuando aparezcan las hembras de raptor a defender los huevos, los matemos y cojamos un objeto. El problema es que cuando te acercas a los nidos de raptor no aparecen estos NPCs a los que matar.

El link de la misión en cuestión es: http://es.wowhead.com/quest=24732
Y el NPC que debería salir es: http://es.wowhead.com/npc=9683
EL objeto que debe dar es: http://es.wowhead.com/item=11509

**Comment by redneo** [comment]
El item lo sueltan http://es.wowhead.com/npc=9683 a un 100% de esos npcs, hay 4 spawneados. Se puede hacer la misión.

**Comment by Inmershus** [comment]
Pero eso no es así, tendría que haber un NPC por cada huevo que esté disponible en el juego (a los cuales no se les puede hacer click para que aparezca el NPC).
