### ISSUE TITLE
¿WTF? ¿Loros y topos?

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1661]
Hoy, por casualidad he decidido matar un loro en Cráter de Un'Goro. Lo gracioso es que me ha permitido despojarlo (este NPC jamás y en ninguna circunstancia da nada) y me ha dado dos objetos de misión (que nada tienen que ver con los loros).
Posteriormente, en Forjaz me ha ocurrido exactamente lo mismo con un topo, incluso me han dado los mismos dos objetos que me dio el loro, así que decidí echar foto: 

![wowscrnshot_083113_162653](https://f.cloud.github.com/assets/5342568/1064711/39845348-134a-11e3-85c1-82bab1c51a40.jpg)

Los links de los NPCs que dan lo que no deberían dar son:
Topo Largacola: http://es.wowhead.com/npc=48972
Loro: http://es.wowhead.com/npc=9600

**Comment by redneo** [comment]
Arreglado.
