### ISSUE TITLE
Misión: Superpegajoso.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1664]
En esta misión de Cráter de un'Goro, Tara te pide que uses un objeto sobre un NPC para así sacar un objeto.
El problema es que el objeto puede ser usado indiscriminadamente contra cualquier cosa, que cuenta para la misión igual.

Aquí está el link de la misión en cuestión: http://es.wowhead.com/quest=24737
Este es el objeto que te proporcionan: http://es.wowhead.com/item=50742
Estos son los NPCs sobre los que puede usarse:
- http://es.wowhead.com/npc=6527
- http://es.wowhead.com/npc=6519
- http://es.wowhead.com/npc=6518
- http://es.wowhead.com/npc=6517

Y esto es lo que deben dar: http://es.wowhead.com/item=11834

**Comment by redneo** [comment]
Arreglado
