### ISSUE TITLE
Misión: Gormashh el glutinoso.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1665]
En esta misión de Cráter de un'Goro, Tara te pide que uses un objeto sobre un NPC para así sacar un objeto. El problema es que el objeto puede ser usado indiscriminadamente contra cualquier cosa, que cuenta para la misión igual.

Aquí está el link de la misión en cuestión: http://es.wowhead.com/quest=24699
Este es el objeto que te proporcionan: http://es.wowhead.com/item=50746
Este es el único NPC sobre el que puede usarse: http://es.wowhead.com/npc=38307
Y esto es lo que deben dar: http://es.wowhead.com/item=50374

**Comment by redneo** [comment]
Arreglado.
