### ISSUE TITLE
Misión: Un poco de ayuda de mis amigos.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1666]
En esta misión de Crater de un'Goro, nos piden que escoltemos a Ringo a un lugar seguro. El problema es que el NPC no se mueve de su sitio y es imposible completar la escolta.

Aquí está el link de la misión: http://es.wowhead.com/quest=24735

**Comment by redneo** [comment]
Se completa sola.
