### ISSUE TITLE
Misión: El buscafósiles 3000.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1667]
En esta misión de Cráter de un'Goro, Chispik Minamal nos pide que usemos su Buscafósiles 3000 para encontrar un fósil grande.
El problema es que el objeto que te da no marca la dirección en la que se encuentra el fósil y es imposible completarla.

Aquí está el link de la misión: http://es.wowhead.com/quest=24708
Este es el objeto que te proporcionan: http://es.wowhead.com/item=50405
Y este es el objeto que deberíamos obtener para poder completarla: http://es.wowhead.com/item=50407

**Comment by redneo** [comment]
El gob para sacar el item está spawneado, en el dibujito de unos huesos que hay un poco mas al sur de "Camino del Terror".

Funciona correctamente, lo que pone incorrecto es donde está el túmulo.

http://es.wowhead.com/object=202165 esa es su direccion.
