### ISSUE TITLE
Misión: Aquí yace Dadanga.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1668]
Esta misión se encuentra en el Refugio Marshall (Cráter de un'Goro). Para coger la misión, tenemos que hablar con una tumba, que nos pedirá 10 brotes sangrepétalo. 
El problema es que no deja coger la misión, ni tampoco entregarla. Además, es posible coger los brotes sin tener la misión cogida.

Esta es la misión: http://es.wowhead.com/quest=24702
Este (o esto) es quien da la misión: http://es.wowhead.com/object=202135
Y estos son los brotes que se deberían poder coger sólo con la misión: http://es.wowhead.com/item=11315

**Comment by redneo** [comment]
Esta mision es muy rara, ya que es la tipica que te pone un bufo mientras estes en ungoro, con lo cual, los items, te los tendrian que dar sin mision, lo que no veo por ningun lado es que sea repetitiva (que supongo que tendria que serlo) de todas formas, ya la da y se puede entregar si tienes los 10 items.
