### ISSUE TITLE
Misión: Transportadas por las olas.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1669]
En esta misión de Cráter de un'Goro, Garl Garratormenta te pide que uses un objeto sobre unas esporas. El problema es que el objeto se puede usar con cualquier npc, ya sea de misión o no.

Esta es la misión en cuestión: http://es.wowhead.com/quest=24686
Este es el objeto que te proporcionan: http://es.wowhead.com/item=50441
Este es el NPC contra el que se tendría que poder usar: http://es.wowhead.com/npc=38202
Y esto es lo que se debería obtener al usar el objeto: http://es.wowhead.com/item=50253

**Comment by redneo** [comment]
Arreglado.
