### ISSUE TITLE
[Hyjal] Falta grifo volador fantasmal, tras liberar para recuperar cuerpo en instance

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#167]
Hola reporto este bug, que nose si exactamente es realmente, ayer testeamos firelands y cuando nos mataron liberamos y ocurrio esto.

![wowscrnshot_070413_172446](https://f.cloud.github.com/assets/3537253/753248/cf5caa94-e561-11e2-8f25-e175c0215e83.jpg)

Como se ve en la imagen salimos fuera y sin el grifo volador fantasmal para poder llegar hasta nuestro cuerpo, teniendo que hacer majas subiendo montañas para poder recuperarlo dentro de la raid jajaja.

Un saludo.

**Comment by redneo** [comment]
Soy la ostiaaaaaaa...

**Comment by crowel** [comment]
Jajaja muy buena fieraa ^^
Gracias.

**Comment by crowel** [comment]
Hola siento reabrir el Issue pero tras el cambio en la DB ocurre lo mismo en hyjal.
Un saludo.
@redneo 

Edit: No puedo abrirlo el issue xD
