### ISSUE TITLE
Misión: Difícil de recolectar.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1670]
En esta misión del Cráter de un'Goro, Tara te pide que recojas flores de miera.
El problema es que, como dice la misión, son tan difíciles de recolectar estas flores que no hay.

Esta es la misión de la que hablo: http://es.wowhead.com/quest=24700
Este es el contenedor que debería poder dar la flor: http://es.wowhead.com/object=201975
Y esta es la flor: http://es.wowhead.com/item=50258

**Comment by redneo** [comment]
Si que están, suelen estar bajo el agua.
