### ISSUE TITLE
Misión: Hacia el norte.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#1671]
En esta misión del Cráter de un'Goro, Garl Garratormenta te pide que vayas a ver a Ithis Guardaluna. El problema es que cuando llegas donde te indica el mapa, ves el interrogante pero no al NPC.

Esta es la misión: http://es.wowhead.com/quest=24689
Y este es el NPC que se debería poder ver: http://es.wowhead.com/npc=38263

**Comment by redneo** [comment]
Arreglados
