### ISSUE TITLE
[hechizos] Inquisicion - Paladin

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1672]
Las ID salen en las imágenes.

Ahi muestro como mi daño sigue siendo el mismo, antes y despues del uso de Inquisición con 3 cargas.

![wowscrnshot_090113_220504](https://f.cloud.github.com/assets/4790547/1065228/349fb60a-137d-11e3-9ad4-4f25237fcd77.jpg)
![wowscrnshot_090113_220512](https://f.cloud.github.com/assets/4790547/1065229/34a2f1b2-137d-11e3-89ee-16cc6341cf1b.jpg)
![wowscrnshot_090113_220320](https://f.cloud.github.com/assets/4790547/1065227/349c687e-137d-11e3-9219-a90f75c71288.jpg)

Bug: No aumenta el daño sagrado.

**Comment by F4NT4SM4** [comment]
Aumenta el daño sagrado es decir de los ataques que son tipo sagrado pero no el daño que se muestra en las estadisticas....

**Comment by lamaza** [comment]
En la imagen se ve como enfoco Sello de rectitud, y como el daño sagrado es el mismo antes y despues. Tambien lo comprobé con martillo de colera, y colera sagrada, y los daños no cambian en 1 solo punto.

**Comment by searum** [comment]
no sale visualmente pero si pegas mas... fijate pegando golpes blancos por ejemplo con el sello y fijate en el daño que haces xD
