### ISSUE TITLE
[objetos, reputacion] Tabardo de Ramkahen

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1673]
Hola, para informar que dicha reputación no me sube al matar cosas en mazmorras, teniendolo puesto. De hecho, no se si algún tabardo este cumpliendo dicha función...

![wowscrnshot_090113_224037](https://f.cloud.github.com/assets/4790547/1065278/82dda8e6-1381-11e3-92f9-072e6d0c2504.jpg)

**Comment by redneo** [comment]
Si que da con ese tabardo, comprobado... no se que tiene que ver la image, pero es bonita, si...

El problema mas bien viene de mazmoras que no dan reputacion, podias decir cuales.

Caverna Rocanegra por ejemplo SI que sube reputacion.

**Comment by lamaza** [comment]
Ok red, lo mirare mas atentamente. BBye!

van bien los tabardos.
