### ISSUE TITLE
[hechizos] Control pet - Cazador

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1674]
A mi cazador (nivel 30) le pasa que no puede controlar mascotas, pues ocurre el famoso bug de perdida de dichas criaturas tras caidas o reloguear.
Revisando vi que mi habilidad de controlar mascotas esta por ser aprendida, esto paso hoy despues de 1 caida y que se me perdio el perro genérico y un tigre que habia capturado.

![wowscrnshot_090213_001840](https://f.cloud.github.com/assets/4790547/1065470/d9cd55b2-138f-11e3-87fe-82867d186e3c.jpg)

Fui al instructor pero no me enseña dicha habilidad pasiva.

**Comment by searum** [comment]
Pon un ticket ingame y que te lo enseñe un gm
