### ISSUE TITLE
WoW error al ingresar miembros

### ISSUE THREAD

**Issue by 3du42d0** [RoDNet/Bugtracker-Infinium-4.3.4#1675]
Hola, cuando alguien quiere agregar a un nuevo miembro a su hermandad, muchas veces salta wow error y no es que me pase a mi nada más, a varios les pasa lo mismo,no ocurre siempre pero varias veces si.

**Comment by ghost** [comment]
Has abieto dos issues con el mismo problema. Además, ya está reportado https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/988

Puedes cerrar ambos issues, saludos!
