### ISSUE TITLE
[Brujo] Talento Parasitar Alma Efecto de Reposición

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#1677]
Este talento aparte del efecto de sanación (el de sanación si funciona), debería reponer un 4% del maná total instantáneamente y además activar el efecto de reposición que da un 1% de maná máximo cada 10sg. Esto se puede ver en la descripción:

![wowscrnshot_090213_122347](https://f.cloud.github.com/assets/3939699/1066773/e8814912-13ba-11e3-903d-0b7fcf6a75ca.jpg)

En esta foto se puede apreciar que no se regenera ni el 4% ni salta reposición.

![wowscrnshot_090213_123304](https://f.cloud.github.com/assets/3939699/1066784/1a924708-13bb-11e3-8ac2-c01bcfe0b5b9.jpg)

Un saludo y gracias

**Comment by ghost** [comment]
ID: 30295

Aquí está http://cata.openwow.com/spell=30295

**Comment by searum** [comment]
fix
