### ISSUE TITLE
Hemorragia bug.

### ISSUE THREAD

**Issue by migue226** [RoDNet/Bugtracker-Infinium-4.3.4#168]
Hola quisiera notificar que Hemorragia y Ruptura del Pícaro están bug, su daño esta nerf.

http://www.subirimagenes.com/fondosycapturas-wowscrnshot070513080-8523940.html

Como pueden ver en la foto vemos que el daño periódico que hace Hemorragia es de 2 puntos, y el daño de Ruptura(puestos los 5 puntos de combo) no llega a 1k.

Espero haber aportado, saludos!

**Comment by searum** [comment]
esto esta fixxx
