### ISSUE TITLE
Misiòn: Pìntalo de negro

### ISSUE THREAD

**Issue by iratxemola** [RoDNet/Bugtracker-Infinium-4.3.4#1681]
Esta misiòn consiste en conseguir un corazòn de diamante negro matando a unos esclavos de piedra obsidiana. El problema es que llevo 2 dias matandolos a todos varias veces y no consigo el corazòn de diamante negro , por eso opino y aseguro que es un bug . Gracias :) (pj:Rasca)

**Comment by redneo** [comment]
Hola Rasca.

Si te fijas la mayoria de la gente pone información de wowhead en los demás tickets, para hacer mucho más rápido el arreglo de los mismos.

En este caso, la misión http://es.wowhead.com/quest=27945 te pide el item http://es.wowhead.com/item=62796 que lo tendrian que dropear los npcs http://es.wowhead.com/npc=47226 a un 4%.

Y efectivamente no lo soltaban. Ahora lo hacen a un 20%
