### ISSUE TITLE
Mision 'La llegada del jefe de guerra' (No muerto)

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1682]
Te pide que esperes a el Jefe de Guerra Garrosh Grito Infernal que tiene que venir pero nunca llega, aquí esta el link de la misión:
http://es.wowhead.com/quest=26965/la-llegada-del-jefe-de-guerra#.

Saludos y gracias.

**Comment by redneo** [comment]
Arreglada, abre otro ticket si no ves al jefe de guerra tras coger la mision.
