### ISSUE TITLE
Problema con los NPCS en el Alto Mando Renegado (Bosque de Argénteos)

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1683]
En este lugar están los soldados y el Gran Ejecutor Mortuus, el resto de los NPCS no están y aquí tengo la prueba de donde deberían estar. Saludos y gracias.

![wowscrnshot_090213_192106](https://f.cloud.github.com/assets/5339370/1068686/c7086ca2-13f6-11e3-9fdc-6767399a01da.jpg)
![wowscrnshot_090213_192120](https://f.cloud.github.com/assets/5339370/1068689/cd8300b0-13f6-11e3-95ee-b9375e2fda01.jpg)
![wowscrnshot_090213_192135](https://f.cloud.github.com/assets/5339370/1068690/cd9fd8c0-13f6-11e3-8122-673f005dfaf7.jpg)
![wowscrnshot_090213_192143](https://f.cloud.github.com/assets/5339370/1068691/cdad6fd0-13f6-11e3-9f40-937ef1b731f3.jpg)

**Comment by redneo** [comment]
Fixed
