### ISSUE TITLE
El hechizo 'invocar demonio' no se mantiene en la barra de acción.

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1684]
Lo que ocurre es que tu dejas el hechizo ahí en la barra de acción y si te desconectas y luego te vuelves a conectar el hechizo ha desaparecido y tienes que volverlo a poner. Y para que nos vamos a engañar, es un poco incomodo la verdad. Ademas también pasa lo mismo con el demonio al que invocas:  tu lo invocas y si luego te desconectas y después te vuelves a conectar es como si no lo hubieses invocado. Espero que se solucione pronto, saludos y gracias.

**Comment by searum** [comment]
Ya lo se pero puedes sacar los iconos de las pets y ponerlos en las barras ^^ no es el fix pero hasta que demos con el problema puedes usarlo. Cierro porque tenemos constancia de este bug y no es un bug prioritario.
