### ISSUE TITLE
[Brujo] Hechizo Terror de Fatalidad Daño Exagerado

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#1685]
Bueno vengo a comentar lo del daño de Terror de Fatalidad porque ya me parece excesivo. Para esta comprobación voy a usar la rama de aflicción para que se vea bien todo esto.

Lo primero el enlace de wowhead http://es.wowhead.com/spell=603/fatalidad

Lo segundo voy a poner los parámetros de mi brujo y ahora procederé a la explicación:

![wowscrnshot_090213_194319](https://f.cloud.github.com/assets/3939699/1068703/2eee3a90-13f7-11e3-91ce-4dbf6d6497b4.jpg)

![wowscrnshot_090213_194322](https://f.cloud.github.com/assets/3939699/1068708/363f8d44-13f7-11e3-8ca1-e623bf4de502.jpg)

![wowscrnshot_090213_195007](https://f.cloud.github.com/assets/3939699/1068724/215d22d2-13f8-11e3-966a-f4a8cbdc70a3.jpg)

Bien con estos datos vamos a ver la formula dada según wowhead que sería:

3612+ (375% del poder con hechizos) sustituyendo los valores en esta fórmula yo obtengo lo siguiente 3612+(375% de 7547) = 31913,25

También con la siguiente fórmula posteada obtengo lo siguiente

multiplicador \* (daño base + [coeficiente \* poder hechizo]) = 1.559_(1957+(3,52_7547)) = 44466,48

OJO!!! El daño dado tanto en una fórmula como en otra es el total de todos los ticks, lógicamente sin tener en cuenta ningún efecto, simplemente este hechizo sin buffos, sin resistencias, etc.

Es más incluso si usamos el Dr. Damage se puede ver que en total debería hacer 57639 (tened en cuenta que es orientativo y no exacto). Os adjunto la foto.

![wowscrnshot_090213_195908](https://f.cloud.github.com/assets/3939699/1068756/6303645c-13f9-11e3-836e-af3f80675621.jpg)

Bueno todo lo anterior ha sido en cuanto a teoría, ahora os enseño lo que pasa en la práctica. A continuación os muestro el daño de un tick y de un tick con crítico.

![wowscrnshot_090213_200431](https://f.cloud.github.com/assets/3939699/1068776/3bdcc2f0-13fa-11e3-8091-fa315057f773.jpg)

![wowscrnshot_090213_200112](https://f.cloud.github.com/assets/3939699/1068771/ead58824-13f9-11e3-9d63-d99922242f7e.jpg)

Os invito a echar cuentas 4 ticks a 36000 cada uno = 144000 (sin contar críticos).

Creo que eso supera con creces los daños anteriormente expuestos, si volvéis a ver las fotos veréis una cosa muy curiosa, el daño del Dr. Damage por tick es de 13389,5.

Creo que queda más que demostrado el daño brutal de Terror de Fatalidad. Es muy raro que un brujo en su rotación incluya Terror de Fatalidad antes que Terror de Agonía en PVP.

Por si queda alguna duda os enseño una foto con todo lo que me puede saltar en el combo.

![wowscrnshot_090213_201720](https://f.cloud.github.com/assets/3939699/1068808/f3bc71bc-13fb-11e3-92de-2931badf07ed.jpg)

Esto ha sido sin critico usando el combo normal de un brujo aflicción. Para los que no lo veáis sólo he echado un poseer para que abrazo de las sombras solo tenga la primera acumulación).

Conclusión: A mi parecer y según las pruebas adjuntadas el daño está altísimo.

Un saludo y gracias por adelantado.

Nota: Se que es un post largo pero era la única forma de mostrar todo.

**Comment by lamaza** [comment]
Gracias por brindarnos mas luces sobre este tema, que importante si es.

**Comment by F4NT4SM4** [comment]
yo aporto una imagen de un brujo dandome 64k yo con 4100 temple xD
![wowscrnshot_082913_174437](https://f.cloud.github.com/assets/3101842/1070639/45b84c7c-145e-11e3-8075-e577f82af272.jpg)

**Comment by redneo** [comment]
Fixed
