### ISSUE TITLE
Mision 'Alimenta al hambriento y al desesperado'

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1686]
Te pide que alimentes a 20 personas con un estofado que previamente tu tienes. debes colocar este estofado cerca de 20 personas sin hogar y automáticamente se te ira completando la misión. El problema es que aunque tu pongas el estofado cerca o encima de la cbeza de esas personas la mision no se completa. Espero que se solucione, gracias y saludos.`

http://es.wowhead.com/quest=26271/alimenta-al-hambriento-y-al-desesperado

**Comment by redneo** [comment]
Arreglada
