### ISSUE TITLE
Mision 'En defensa de los paramos de poniente'

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1687]
Pide recuperar las ordenes del ataque gnoll pero es imposible recuperarlas porque los npcs de la alianza matan a los gnolls y por tanto en imposible conseguirlo porque no te da tiempo a matarles. Espero que se solucione, gracias y saludos.

http://es.wowhead.com/quest=26286

**Comment by redneo** [comment]
Los npcs 501 tienen el mayor porcentaje de soltarlos, y hay muchos en las playas.... se puede completar la mision.
