### ISSUE TITLE
Mision 'La brigada de los paramos de poniente'

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1688]
lo que ocurre en esta mision es que los gnolls aparecen de repente y como consecuencia los npcs de la alianza van a por ellos y tardan menos de 3 segundos en matarlos. por lo tanto es imposible completar la mision. Espero que se solucione, gracias y saludos.

http://es.wowhead.com/quest=26287

**Comment by redneo** [comment]
Hay cientos de Gnolls por todos lados, se puede completar la misión.
