### ISSUE TITLE
Boss Bug El Arcatraz

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#1689]
El último boss se encuentra bug, empieza el evento correctamente y saca al primer jefe, pero después de matarlo no continua hablando con lo cual no aparece el siguiente tanto en normal como en heroica.

El npc que los llama es: http://es.wowhead.com/npc=20904

**Comment by lamaza** [comment]
Y como pasaste la puerta que estaba bug? 

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/376

**Comment by foxmclaud** [comment]
Especifica puerta bug, porque si hubieses echo la maz no lo preguntarías.

**Comment by redneo** [comment]
Las puertas las arregle hace un algo de tiempo.

**Comment by lamaza** [comment]
Gracias Redneo.

Hago este reporte con IDS y la foto por si es feo el camino haha.

http://www.wowwiki.com/Warden_Mellichar
http://es.wowhead.com/npc=20904#english-comments

En los comentarios estan los npc como posibilidades de que sean invocados, y en total son como 4 o 5 npcs que hay que matar para detener al boss y luego el logro http://es.wowhead.com/achievement=681/heroico-el-arcatraz.

Evento:
1- http://es.wowhead.com/npc=20905 o http://es.wowhead.com/npc=20906
2- http://es.wowhead.com/npc=20977 (Dice que ayuda, no se si al jugador o al boss)
3- http://es.wowhead.com/npc=20908 o http://es.wowhead.com/npc=20909
4- http://es.wowhead.com/npc=20910 o http://es.wowhead.com/npc=20911
5-  http://es.wowhead.com/npc=20912 (El cuál dicen que saca un clon durante la pelea)

![wowscrnshot_090913_142644](https://f.cloud.github.com/assets/4790547/1109765/e93c785a-1986-11e3-8ff4-cf0a5f09304a.jpg)

Luego de que dice esas palabras no pasa nada, no invoca nada.

**Comment by efectokoleos** [comment]
necesita reescribirse la instance..k pereza xd
