### ISSUE TITLE
Glifos bugs Pícaro. 

### ISSUE THREAD

**Issue by migue226** [RoDNet/Bugtracker-Infinium-4.3.4#169]
Buenas quisiera reportar glifos bugs que al menos hasta ahora voy encontrando.

El primero es Ceguera
ID: http://es.wowhead.com/spell=2094

http://www.subirimagenes.com/fondosycapturas-wowscrnshot070513081-8523957.html

http://www.subirimagenes.com/fondosycapturas-wowscrnshot070513081-8523961.html

Gubia: 
ID: http://es.wowhead.com/spell=1776

http://www.subirimagenes.com/fondosycapturas-wowscrnshot070513081-8523962.html

http://www.subirimagenes.com/fondosycapturas-wowscrnshot070513081-8523963.html

Estos son los que he encontrado, Saludos.

**Comment by searum** [comment]
fixed
