### ISSUE TITLE
[Abalorio] Desesperación Plomiza

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#1692]
Abalorio modo heróico: http://es.wowhead.com/item=56347

Bug: El efecto se activa aunque no tengas menos del 35% de salud. Supongo que el equivalente para el modo normal (http://es.wowhead.com/item=55816) también podría tener el mismo bug. El Cd interno si funciona correctamente.

**Comment by efectokoleos** [comment]
arreglado
