### ISSUE TITLE
Bug Warrior

### ISSUE THREAD

**Issue by kalamx** [RoDNet/Bugtracker-Infinium-4.3.4#1693]
Bueno quisas no sepa explicarlo bien, asi que de todos modos dejare unas fotos.

Ayer domingo, estaba en un goro, me tope con un ali y bueno queria hacer pvp y logicamente el otro tambien, me sorprendio el daño impresionante que me metio. pense en ese momento, ok falle a mis abilidades. de nuevo correteo y de nuevo, casi oneshot en mi. ese entonses era nivel 54 y el ali 53.

ahora, hace rato que soy 62 casi 63 me lo volvi a encontrar ese mismo ali, otra ves misma situacion, oneshot, practicamente no duro la pelea mas de 3 segundos. me pregunte como pudo pasar esto, el ali otra ves de nuevo, one shot pelea que no duro 4 segundos de nuevo. 

me puse a investigar los registors de la pelea, daños de 2500 por golpe y daños de DoT  mas altos que el mio siendo que el ali era ya 61.

despues de un rato pensando como pudo suceder, si estaba bug alguna spell que el uso siendo mas over o un bug beneficioso que uso. bueno, la sorpresa es esta, literalmente si uso un bug beneficioso pero no intencional por parte de el, si no parte mia. ( es decir, solito me estaba dando en la madre ) 

unas imagenes del porque explica. 

http://img585.imageshack.us/img585/8152/fx6t.jpg

http://img197.imageshack.us/img197/7392/fjpg.jpg

http://img703.imageshack.us/img703/1736/a6x7.jpg

Pongo esto ya que en verdad, en PVP es una desgracia eh simplemente sin gracia de jugar asi. en PVP y posiblemente en ratos de PVE.

**Comment by redneo** [comment]
Perdona que no entienda nada de nada... Tu supongo que eres un guerrero, y el otro... Guerrero tambien?

**Comment by SherBlader** [comment]
a niveles bajos y con cds se puede cargar a alguien del mismo nivel muy rapido.

**Comment by kalamx** [comment]
no, como indica las imagenes, es un ejemplo. son NPCs que no tiran abilidades que tengo en ese momento. sobre el ali, era paladin, un paladin no hacen esos debuff.

**Comment by searum** [comment]
No entiendo nada...
