### ISSUE TITLE
Mision 'Los secretos de la torre'

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1694]
Te pide que entres en una torre llena de npcs elite, pero tienes la ayuda de una poción de invisibilidad. Esta mision tiene 2 problemas a arreglar: 
1- La pocion no se puede usar, desconozco el porque pero no te deja usarla cuando pulsas sobre ella.
2-El hombre al que tienes que encontrar en la torre llamado Helix Rompengranajes no esta.
Espero que se solucione pronto, gracias y saludoss. 

http://es.wowhead.com/quest=26290/los-secretos-de-la-torre#.

**Comment by redneo** [comment]
La poción se puede usar dentro de la torre sobre ti.

Arreglado que al acercarte a Helix te cuente. Habria que hacer que hablaran...

De todas formas suelta y vuelve a coger la misión por si acaso.

**Comment by sisu091** [comment]
Siento decir que los errores no se han corregido. La poción se sigue sin poder usar dentro y ademas Helix no esta dentro del castillo. He abandonado y vuelto a aceptar la misión varias veces pero nada, los errores temo decir que persisten.

**Comment by redneo** [comment]
cuando te tarjeteas a ti mismo si que puede usarse la botella, pero repito, dentro de la torre

**Comment by sisu091** [comment]
Yo me meto dentro de la torre y hago lo que dices pero da igual, la botella no hace nada. Y sigo insistiendo, Helix Rompengranajes no esta en ninguna parte de la torre. Arreglenlo de verdad por favor. Gracias.

**Comment by phamtomix** [comment]
Hola la mision sigue bug..! La pocion cuando te la pones no te hace invicible te da el buff pero no hace nada.l! al subir a la torre salen los NPC que deberian hablar pero negros..! y si me acerco mucho muero automaticamente
