### ISSUE TITLE
Error en la mision de los elfos nocturnos "toque rejuvenecedor"

### ISSUE THREAD

**Issue by Wempakon** [RoDNet/Bugtracker-Infinium-4.3.4#1695]
te dice que te compres la habilidad toque rejuvenecedor y que cures a un centinela herido, he curado a todos y cada uno de los centinelas y no me ha contado ninguno

**Comment by redneo** [comment]
Direccion de wowhead de la misión? 
Algún dato esclarecedor para saber de que va la misión???

**Comment by Kiritoo** [comment]
Arreglada
