### ISSUE TITLE
Corona de Hielo - Cadena Caballeros de la Espada del Ebano

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#1698]
Por parte de la alianza la primera misión de la cadena "Pura diversión" (http://es.wowhead.com/quest=12887) que la da Thassarian en el rompecielos (http://es.wowhead.com/npc=29799) se encuentra bug.

Dicho npc proporciona el objeto necesario, llegamos a donde esta el ojo (tiene un bug gráfico que se cuela hacia el suelo mas cercano) quedando un ojo invisible donde debería de estar, y al matarlo este no cuenta para la misión (además de que quita mucha vida, incluso para un 85).

**Comment by redneo** [comment]
Arreglada
