### ISSUE TITLE
misiones Bug: Laderas de trabalomas

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#170]
misiones bug 
Botanica Basica:

no se inicia la mision son oleadas de zombies en un minijuego y no se inicia

Cuidar el jardin:

no se inicia la mision son oleadas de zombies en un minijuego y no se inicia

*estas misiones son varias al terminar estas te dan mas oleadas para hacer son unas 5 o 6 misiones en total y te dan de recompensa un compañero 

![wowscrnshot_070513_133301](https://f.cloud.github.com/assets/4893907/753401/0bddfc5c-e567-11e2-95e6-dab4bacb4093.jpg)

![wowscrnshot_070513_133310](https://f.cloud.github.com/assets/4893907/753404/1596e2a4-e567-11e2-8688-1d38e733855c.jpg)

**Comment by redneo** [comment]
muy dificil de solucionar.... se pueden poner autocompletables para sacar la mascota... esa linda flor.

**Comment by frustrix** [comment]
Prefiero que no lo arreglen y nadie tenga el girasol, ya que los compañeros se deben de conseguir por algo no por dar un boton, tiene que tener su dificultad. si no quieren arreglarlo porque es sumamente dificil pues que no lo hagan y cuando puedan calentarse la cabeza que lo hagan.

porque seguro que no es tan facil de arreglar eso lo se, y ahora los programadores tienen cosas mas importantes que hacer 

Dejenlo sin arreglar no lo pongan AUTOCOMPLETAR 

*mas de uno dira que soy un hdp pero es lo que hay o se consigue con la dificultad que conlleva las misiones o no se consigue el compañero

saludos

**Comment by ghost** [comment]
Pues migrando un pj de otro server donde la misión se autocompleta ya tienes el girasol xd.

**Comment by frustrix** [comment]
pues bien por ti

**Comment by frustrix** [comment]
asi se reconocen a los mancos ;)

**Comment by ghost** [comment]
No sabía que los "pros" se reconocen haciendo misiones de plantas xd, gracias por informarmelo.

**Comment by frustrix** [comment]
no, a los pros no se les reconoce por hacer misiones de plantes mas bien se reconoce a mancos pidiendo que les pongas las misiones Autocompletar para no esforzarse en hacerlas ya que no son capaces ;)

**Comment by Compresor** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by Kiritoo** [comment]
Mal reportado, https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2215
