### ISSUE TITLE
Se teletransporta a Orgrimar

### ISSUE THREAD

**Issue by MadScientist96** [RoDNet/Bugtracker-Infinium-4.3.4#1703]
Soy chaman nivel 80 y el problema es que se me teletransporta todo el rato al Valle de la Fuerza de Orgrimar, antes tambien me pasaba pero estos ultimos dias se teletransporta constantemente cada media hora aproximadamente, puede que el problema este en el hechizo de regreso asral del chaman.
Espero que puedan hacer algo porque asi no se puede jugar muchas gracias

**Comment by juaks** [comment]
Esto ya no pasa no? Podéis cerrarlo
