### ISSUE TITLE
[Guerrero] Daño de arma (golpe blanco) ID: 6603

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1704]
Buenos días.

La mayoria de skills del guerrero dependen fundamentalmente de algún tipo de coeficiente de daño de arma, más luego aparte una cifra de daño extra.

¿Qué está ocurriendo? Que los golpes blancos del guerrero están pegando de más. Para probarlo estoy utilizando un guerrero con muy poco equipo, y blandiendo el arma (itemID:56130), y estándo en actitud defensiva, donde no tengo ningún coeficiente multiplicador de daño extra.

El resultado es el siguiente: los golpes blancos (atacar automáticamente [spellID:6603]) están pegando de más.

http://img163.imageshack.us/img163/8997/tfxb.jpg
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/163/tfxb.jpg/'><img src='http://img163.imageshack.us/img163/8997/tfxb.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

P.D. si en efecto se puede demostrar que el daño de arma está subido, entonces habría que revisar todas las skills que dependan de esto, porque en la actualidad el guerrero es una verdadera máquina de matar, está muchos niveles por encima del resto de clases hoy en dia.

**Comment by elmiriox15** [comment]
Según he probado con mi guerrero (sin ningún multiplicador de daño ni talentos que aumenten ni nada) he visto que el daño está bien, según el juego pega entre 2686-3167 y está pegando eso, a no ser que esté bug y se vea reflejado la subida de daño en las estadísticas cosa que dudo.

**Comment by cibernaco** [comment]
Pues mira, según tu foto el daño es correcto, el golpe blanco que has dado es casi lo máximo que puedes dar sin ser critico según esa foto que pones, es decir siendo crítico aún podrías pegar más, ya que usas el DrDamage al menos configuratelo, y quitale el descuento de armadura.

Un saludo.

**Comment by Kiritoo** [comment]
Esto funciona correctamente.
