### ISSUE TITLE
[Guerrero] Valor de daño: Golpe Mortal  ID:12294

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1705]
Buenos días

En mi caso el daño de golpe Mortal (ID:12294) testandolo con el arma (itemID:2480), está pegando más de lo que debería.

http://img32.imageshack.us/img32/7589/tez6.jpg
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/32/tez6.jpg/'><img src='http://img32.imageshack.us/img32/7589/tez6.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img546.imageshack.us/img546/9160/dndm.jpg
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/546/dndm.jpg/'><img src='http://img546.imageshack.us/img546/9160/dndm.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

**Comment by searum** [comment]
fix
