### ISSUE TITLE
Palabra de gloria, Paladin

### ISSUE THREAD

**Issue by meybon** [RoDNet/Bugtracker-Infinium-4.3.4#1706]
Buenas,el problema es con el hechizo palabra de gloria y el glifo de la gran palabra.

Al parecer el bug es debido al glifo de la gran palabra, reduce la sanacion un 50% pero durante los 6 segundos siguientes te sana por ticks el resto de la sanacion reducida antes.

http://es.wowhead.com/spell=136494  es el de palabra de gloria, el del glifo no lo encuentro en wow head, es Glifo de la gran palabra, tipo sublime pero no lo encuento xD

El problema es que el glifo se activa aunque no tengas el glifo en cuestion activado o simplemente aprendido. Sin el glifo puesto cura aproximadamente el 50% de una cura normal y se activan los ticks, asi que creo que sera por eso.

Gracias de antemano y saludos: Meybon.

**Comment by Kiritoo** [comment]
Hola añade el enlace a wowhead para saber el id.

**Comment by Wiinter** [comment]
El problema de este Glifo es que en Mist Of Pandaria a variado entonces no sabemos si es la misma id o no.

**Comment by Velcositro** [comment]
Encontré el ID por ustedes (de nada XD), es: 93466, Lo cambiaron por Glifo de Protector del inocente (http://es.wowhead.com/spell=93466) en MoP.

Fuente: http://www.mmo-champion.com/threads/854320 que me llevó a http://wowpedia.org/Glyph_of_the_Long_Word

**Comment by Wiinter** [comment]
Gracias Velco xD

**Comment by meybon** [comment]
Gracias xD y por cierto, me alegro de verte xD

**Comment by lamaza** [comment]
Ah con razón el hechizo ese cura una porqueria, y eso sin hablar de los stat de la spell, que cuando quiere cura un critico 10k+ y la mayoria del tiempo cura 8k y hasta 3k con 3 cargas de poder sagrado.

**Comment by searum** [comment]
fix
