### ISSUE TITLE
Bug dk

### ISSUE THREAD

**Issue by genis59** [RoDNet/Bugtracker-Infinium-4.3.4#1711]
No me deja salir de Archeus. No me deja usar el telport que va al otro piso y no puedo usar las monturas para bajar a la brecha, ayudenme, gracias

**Comment by Kiritoo** [comment]
Porfavor pon un ticket ingame para que un gm lo revise.
Saludos.

**Comment by genis59** [comment]
Vale ya he puesto ticket pero no contesta, el servicio esta on? Hay algun GM conectado?
