### ISSUE TITLE
[Brujos] Demonios/Mascotas/Pets del Brujo

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#1712]
Es verdad que ya se arregló el hecho de que al montar no se vaya la montura pero aún sigue bug un detalle sobre eso, que a mi por lo menos me parece importante:

Al invocar o al montar y desmontar el demonio pierde la configuración, osea que si le había activado cierta habilidad para que la use automáticamente tendré que hacerlo de nuevo, si había cambiado la posición de una habilidad en su barra volverá a su lugar, si lo había puesto en agresivo volverá a ser pasivo la próxima vez, etc.

Aparte de eso pero como consecuencia del mismo bug el nombre del demonio cambia, osea que básicamente se invoca un demonio distinto cada vez, cuando debería ser el mismo siempre para cada brujo, tal y como pasa con las mascotas del cazador.

Dejo los IDs de cada demonio y de su hechizo de invocación por si acaso es necesario, pero creo que no porque no tiene que ver con eso directamente sino con lo que hace que se guarden esas preferencias:

Los Hechizos:
*Invocar Diablillo (http://es.wowhead.com/spell=688)
*Invocar Abisario (http://es.wowhead.com/spell=697)
*Invocar Manáfago (http://es.wowhead.com/spell=691)
*Invocar Súcubo (http://es.wowhead.com/spell=712)
*Invocar Guardia Vil (http://es.wowhead.com/spell=30146)

Los Npcs:
*Diablillo (http://es.wowhead.com/npc=416)
*Abisario (http://es.wowhead.com/npc=1860)
*Manáfago (http://es.wowhead.com/npc=417)
*Súcubo (http://es.wowhead.com/npc=1863)
*Guardia Vil (http://es.wowhead.com/npc=17252)

Espero haberme explicado bien y que puedan encontrar un tiempito y una solución para repararlo. Gracias de antemano.

**Comment by searum** [comment]
Si, el fallo es porque hice un pequeño apaño hasta que tenga resuelto el problema 100% blizzlike, era simplemente para salir del paso... mejor eso que nada :)

Ya lo arreglaré cuando haya tiempo porque considero esto no tan importante como otros bugs.

Saludos!

**Comment by Velcositro** [comment]
Ah ok, bueno gracias, esperaré con ansias el momento.

**Comment by searum** [comment]
bueno venga no esperes con ansias que lo he fixeado ya :d

**Comment by Velcositro** [comment]
¡Por la Dama Oscura! ¿de verdad? XD, muchas gracias, supongo que aún no está implementado en el server, pero puedo esperar pacientemente a que se ponga.
