### ISSUE TITLE
Los npcs del ato mando renegado (Bosque de argenteos) no estan

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1717]
Todos los comerciantes no están. El maestro de vuelo no te da la opción para poder volar. El Jefe Garrosh grito infernal no esta tampoco y por lo tanto, no puedes continuar con la serie de misiones. Gracias y saludoss.

**Comment by sisu091** [comment]
Esta ya arreglada? Si no  se arregla no puedo continuar jugando...

**Comment by Kiritoo** [comment]
Si no esta el mensaje cerrado no esta reparado ya que se comunica en cada mensaje cuando se reparan.
Eso de que si no se arregla no puedes seguir jugando me parece una estupidez sinceramente :D

**Comment by sisu091** [comment]
Pues que no te lo parezca, porque si no están no puedo seguir con la serie de misiones que es lo que a mi me interesa.

**Comment by Kiritoo** [comment]
Pues a esperar se ha dicho y si quieres que lo reparemos añade los ids de los npcs que faltan o su correspondiente enlace a wowhead.

**Comment by sisu091** [comment]
Perfecto, el mas importante que falta es este: 
-Jefe de guerra Garrosh Grito infernal http://es.wowhead.com/npc=44629
El resto son los comerciantes que hay en la parte de arriba del alto mando renegado. No me se sus nombres, solo se que son comerciantes.
Gracias.

**Comment by sisu091** [comment]
Por cierto que casi se me olvida, la habilidad de volar del maestro de vuelo de este mismo lugar no funciona, no puedes volar. El npc es este: http://es.wowhead.com/npc=44825/cuidador-de-murcielagos-cresaliento
Gracias.

**Comment by Kiritoo** [comment]
Fix, falta aplicarlo.
