### ISSUE TITLE
Barra de energia de picaro y ruptura del arrojadizo

### ISSUE THREAD

**Issue by cojidrin** [RoDNet/Bugtracker-Infinium-4.3.4#1719]
Cuando estas en combate contra entorno la regeneración de la energía no corresponde con la que realmente es y aunque no tengas nada de energía ves la barra llena.

Al usar abanico de cuchillos te quita duracion en tu arrojadizo y al 6 o 7º abanico de cuchillos ya lo tienes roto

**Comment by Kiritoo** [comment]
Arreglado bug visual, falta compilar. Si veis que falla en algun aspecto, ira, energia, enfoque.. avisad.
Lo del abanico ya esta reportado.
