### ISSUE TITLE
Celeridad

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#172]
Buenas, fijandome algunos de los indices, noto que celeridad anda muy raro: Al quitar equipo con celeridad, esta aumenta o se queda en el mismo porcentaje.
Tampoco el porcentaje del índice se refleja en el porcentaje total:
Con mi DK:
![wowscrnshot_070513_092608](https://f.cloud.github.com/assets/4582987/753645/10f10914-e571-11e2-929a-1269e27c08e1.jpg)
Con mi Pícaro:
![wowscrnshot_070513_094357](https://f.cloud.github.com/assets/4582987/753646/1626e944-e571-11e2-8d6d-487751345f57.jpg)

Esto no solamente aparece en la solapa de "Cuerpo a cuerpo" sino también en "Hechizo" y "A Distancia". A la mayoría de jugadores a los que le pregunté me dijeron que les funciona bien y/o que quizá era un bug visual, sin embargo me encontré con alguien tenía el porcentaje en negativo.
Edit: Reforjando los items del DK me encuentro con que puedo llegar a negativo:
![wowscrnshot_070513_101524](https://f.cloud.github.com/assets/4582987/753776/1a46dffc-e576-11e2-8d22-2c646f955a4f.jpg)

Bueno eso eso todo, si tengo algo que agregar luego edito el post.
Gracias y hasta luego.

**Comment by Moyax** [comment]
Yo tengo un problema parecido al usar la habilidad de Herboristeria sangre de vida, no recibo el beneficio de 480 de celeridad que deberia dar :P

**Comment by ghost** [comment]
Moyax, haz otro reporte, eso ya es problema de la habilidad, no de la celeridad.

Por otra parte confirmo que hay un bug con la celeridad (en el apartado de hechizos), independientemente si el equipo esta reforjado o no, si te sacas y pones algunas partes que tengan celeridad, la celeridad varía, algunas veces aumenta, otras baja, y otras queda igual.... este bug de la celeridad y el bug de reforjas no pasaba los primeros días de la actualización.

**Comment by crowel** [comment]
Parece que la celeridad en vez de subir se baja.
JeJeJe.

**Comment by ghost** [comment]
Olvidé aclarar que Foto1 y Foto2 son 2 personajes diferentes, Foto1 y Foto 3 son el mismo pj.

**Comment by ghost** [comment]
Ok, hoy 10 de julio, los índices se muestran correctamente. En el rogue la celeridad no aumenta el índice de reg. de energía (se queda en 10.00 por segundo) pero ese ya es otro tema.
Cierro el tema y muchísimas gracias!
