### ISSUE TITLE
[Brujo] Mana pool de las mascotas

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1725]
Buenas noches.

Las mascotas del brujo en la actualidad están teniendo una barra de maná especialmente subida (más de 400k de maná)

http://es.wowhead.com/npc=17252
http://es.wowhead.com/npc=1863
http://es.wowhead.com/npc=417
http://es.wowhead.com/npc=1860
http://es.wowhead.com/npc=416

**Comment by Wiinter** [comment]
Diría qe hace días qe lo arreglaron. Ahora mismo mis pets tienen el mana correcto.

**Comment by Wiinter** [comment]
Cierra el post porque ya está bien.

**Comment by Wiinter** [comment]
Ha vuelto a ocurrir lo del mana?

**Comment by paellaencol** [comment]
Si, además estan regenerando muchísimo mana. Luego añado fotos

**Comment by paellaencol** [comment]
Cuando me di cuenta estaba así:
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/208/y7gx.jpg/'><img src='http://img208.imageshack.us/img208/5892/y7gx.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>
http://img208.imageshack.us/img208/5892/y7gx.jpg

Y a los pocos segundos le había subido ya la cantidad de maná disponible pese a que estuvo spammeando un hechizo:
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/196/vpg2.jpg/'><img src='http://img196.imageshack.us/img196/5554/vpg2.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>
http://img196.imageshack.us/img196/5554/vpg2.jpg
