### ISSUE TITLE
Hechizo Sacerdote Sagrado: Palabra sagrada: Santuario [ID:88685]

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1726]
Buenas noches

Reportado y posteriormente arreglado en https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1401 

El problema es que se ha fastidiado hoy mismo, otra vez vuelve a hacer la animación de la curación, pero no cura nada, únicamente es visual el área

Gracias

**Comment by paellaencol** [comment]
Uh, el problema es mas raro de lo que me pensaba. Sólo está curando si se está en el extremo del perímetro, casi fuera del área. Si se está en una zona más centrada, no cura...

**Comment by paellaencol** [comment]
Respecto a lo descrito en el anterior comentario. El problema de que solo te sana en el perímetro del área, sólo le sucede al sacerdote, el resto de miembros  del grupo se curan perfectamente incluso estando en el epicentro.

**Comment by searum** [comment]
vale no sufras, ya lo arregle ^^
