### ISSUE TITLE
[Sacerdote] Talento Disciplinas Gemelas ID:47588

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1727]
Buenas noches.

Con los 3 puntos de 3 puestos en este talento. Deberíamos tener un 6% de sanación aumentada, y un 6% de daño aumentado.

Problema: no está dando ese 6% a Palabra de poder: Escudo (id:17), cuando debería darlo, ya que es un coeficiente más a multiplicar de esta spell.

**Comment by efectokoleos** [comment]
fixed
