### ISSUE TITLE
Problema con Transfigurar.

### ISSUE THREAD

**Issue by Vic2tor** [RoDNet/Bugtracker-Infinium-4.3.4#1728]
Bueno, tengo un problema o es un problema del juego que antes podia tranfigurar un arco a un arma de fuego, bueno, me compro el arco soñoso y queria cambiarle el aspecto ami arco ya que no me gusta aun arma que me encanta y no me deja, le doy aplicar y no me deja, no salta ni error y que no puedo.
![wowscrnshot_090313_224759](https://f.cloud.github.com/assets/5310615/1076062/0aafa9a8-14dc-11e3-8b28-2170b544454c.jpg)
![wowscrnshot_090313_224828](https://f.cloud.github.com/assets/5310615/1076063/0aac7670-14dc-11e3-93d6-ca984af990fe.jpg)
![wowscrnshot_090313_224845](https://f.cloud.github.com/assets/5310615/1076064/0ab26d8c-14dc-11e3-9cc6-eb508d24122f.jpg)

Lo que pasa que cuando me pongo una ballesta si me deja ponerle la skin (trnsfigurar) a un arma de fuego, y si es un bug o un problema me gustaria que lo arreglaran ya que me gusta la skin del arma de fuego.

**Comment by hairblood** [comment]
puede ser que esa version del sañoso da error por no existir en el 4.3 ¿te deja transfigurar otros arcos sin contar el sañoso?

**Comment by Wiinter** [comment]
En esta version creo qe solo se puede transfigurar objetos que sean del mismo tipo. Por ejemplo si tu quieres transfigurar una daga solo puedes con otra daga, no puedes con una espada. Antiguamente con la transfiguración adaptada que pusieron en la 4.0.6, a veces si se podía pero en la 4.3.4 no, porque es la blizzlike. Habrá que esperar hasta entrados en Mist Of Pandaria que es cuando te permiten hacer eso qe tu pides.

Espero haberme explicado bien. Y espero no haberme equivocado que estás cosas son muy delicadas y cada version cambian mucho los pequeños detalles

**Comment by Vic2tor** [comment]
Vale, gracias :)

**Comment by Velcositro** [comment]
Debo decir que lo que dice @Wiinter es verdad en parte, porque los arcos, ballestas y armas de fuego siempre se han podido transfigurar entre ellos desde que se puso la transfiguración por 1º vez en el 4.3. En MoP lo que añadieron fue la posibilidad de cambiar entre espadas/mazas/hachas y bastones/armas de asta (Solo para las clases que puedan usar ambas armas, osea que un brujo o mago tampoco puede transfigurar armas de asta).
