### ISSUE TITLE
(Trol) Foso de pruebas (24768)

### ISSUE THREAD

**Issue by jorgegalinmor** [RoDNet/Bugtracker-Infinium-4.3.4#1729]
Como debería funcionar:
En esta misión, de las primeras de la cadena inicial de los trols, al hablar con el carcelero y pulsar en la opción que te sale, se te debería completar el objetivo de hablar con él y además, este ir a abrir la puerta de la jaula del naga para que le mates.

Bug:
Al darle a la opción no pasa nada

**Comment by redneo** [comment]
Arreglada
