### ISSUE TITLE
Bugs paladin holy

### ISSUE THREAD

**Issue by ultimantis** [RoDNet/Bugtracker-Infinium-4.3.4#173]
Buenas, dejo aqui los bugs que he podido encontrar en el pala holy por ahora.

Maestría (id:76669): Debería acumularse con cada curación pero no lo hace.

Habilidades:

Señal de luz (id:53652): No cura nada al que tenga la señal de luz puesta.

Radiancia sagrada (id:82327): Debería seguir curando unos 3 segundos despues de haberse lanzado pero no lo hace.

Guardián de los antiguos reyes (id:86669): Debería repartir un 10% de las seguientes 5 curas a los objetivos amistosos cercanos pero no hace nada de nada.

Choque sagrado (id:25912): Cura el doble de los que debería.

Sello de perspicacia (id:20165): Debería otorgar 4% de mana base de vez en cuando al pegar en cuerpo a cuerpo pero no funciona.

Talentos sagrado:

Protector del inocente (id:94289): Solo debería curarte cuando sanas a otro objetivo amistoso pero te cura aunque la cura sea a ti mismo.

Acusar (no encontré la id): Debería impedir que el objetivo afectado por exorcismo pueda efectuar golpes críticos durante 6s pero el efecto no se aplica en el objetivo.

Torre de radiancia (id:85512): Debería dar una carga de poder sagrado solo al sanar al objetivo de tu señal de luz con luz divina o destello de luz y dar 1 carga de poder sagrado pero da 2.
Tambien otorga 2 cargas al usar el choque sagrado aparte de la carga que da y luz sagrada tambien da 2 cargas y no deberia.

Talentos protección:

Gloria eterna (no encontré la id): Solo debería funcionar una vez antes de que las cargas se agoten pero funciona varias veces seguidas.

Bueno por ahora creo que ya está.
Un saludo y gracias por el trabajo :)

**Comment by crowel** [comment]
Enlazo https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/71

**Comment by shials** [comment]
![wowscrnshot_070513_171723](https://f.cloud.github.com/assets/4938203/754366/56298a82-e586-11e2-8930-3e53db0e1e60.jpg)
http://es.wowhead.com/spell=86669 No sale el Guardian

**Comment by paellaencol** [comment]
Gloria eterna sí que estaba funcionando correctamente antes. http://old.wowhead.com/spell=87164 
Tenía un porcentaje de probabilidad de activarse y no consumir cargas de poder sagrado, no siempre se activaba (lógicamente)

Ahora por desgracia después de la última caída dejó de funcionar.

->La curación de señal de luz ya funciona perfectamente!

**Comment by ultimantis** [comment]
El problema de la gloria eterna es que solo debe no gastar las cargas una vez y despues deben gastarse siempre, osea no debe poder usarse tan seguido como estaba.

un saludo

**Comment by ghost** [comment]
@ultimantis perdón por cerrar tu reporte, puedes reportar cada bug en un reporte a parte?, así es más comoco para los devs arreglar los bugs, muchas gracias.
