### ISSUE TITLE
NPC Evol Dedos (Maestro de Brujos de 'Costa del naufragio') no está.

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1730]
En el mapa te marca que si que esta pero he buscado por todas partes, por los lados encima e incluso debajo del barco (XD) pero no esta. Debe ser un bug o algo. Espero que se solucione pronto, gracias.

**Comment by ghost** [comment]
Pon la ID del NPC para que lo puedan arreglar...Búscala en Wowhead

**Comment by sisu091** [comment]
http://es.wowhead.com/npc=38513/evol-dedos

El personaje es este, pero sale en la zona equivocada. El fallo esta en este personaje de la Costa del naufragio, no de donde marca la pagina de wow head.
