### ISSUE TITLE
Primer boss de Cumbres del Vórtice tira el server

### ISSUE THREAD

**Issue by edwyr** [RoDNet/Bugtracker-Infinium-4.3.4#1731]
Hoy hemos estamos haciendo cumbres y al darle al primer boss se caia el server, tarda unos 2 o 3 seg desde k se le da, lo hemos comprobado 2 veces por si habia sido casualidad y era el boss, para que lo sepais y arregleis.

**Comment by efectokoleos** [comment]
fix
