### ISSUE TITLE
Objetos que se compran con honor bugs

### ISSUE THREAD

**Issue by 3du42d0** [RoDNet/Bugtracker-Infinium-4.3.4#1732]
Bueno algunos objetos que tienes que comprar con honor te piden "7250 puntos de honor en esta temporada" cuando el máximo por día es 4000 y eso de temporada no va. y hay otros como por ejemplo en mi caso la pechera de malla del cazador, que me pide 700 pts y a la hora de comprar con 4000 pts mios me dice que no tengo los objetos necesarios para la compra

**Comment by searum** [comment]
fix
