### ISSUE TITLE
Faltan NPCS (Mirador Salvaje, Las islas perdidas)

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1733]
Faltan los npcs de los mercaderes de comida y bebida y los de reparación. No descarto que falten mas así que les pido por favor que revisen bien. Gracias y saludos.

**Comment by efectokoleos** [comment]
pon enlaces a wowhead de los npcs k faltan porfavor

**Comment by sisu091** [comment]
Perdon, me he equivocado, estan todos los npcs, es que no me salian antes no se porque pero si estan. Gracias
