### ISSUE TITLE
Personaje muy, pero que muy atascado.

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1734]
Estaba haciendo la misión de 'la venganza del jefe de guerra' con mi goblin y hay que hacerla sobre un barco. Lo que me paso fue que me caí del barco y no hay ninguna forma de poder subirme para poder volver a empezar la misión. Lo he intentado con saltos, lo he intentado con la facultad del cinturón cohete de los goblins... pero nada, no puedo. Es la única misión que tenia así que si no la completo no puedo seguir con la serie de misiones. Encima, como es una misión que cogí dentro del barco, ahora que estoy fuera de el si no entro no puedo ni cogerla ni hacerla. PORFAVOR OS PIDO QUE ME AYUDEIS, PORFAVOR. GRACIAS Y SALUDOS.

**Comment by ghost** [comment]
Y cual es el bug? Esto no es asistencia técnica, pon un ticket en el juego para que te ayuden! xD

Suerte!

**Comment by sisu091** [comment]
Ya lo he puesto, pero que pasa? que no hay ningun MJ hoy o que?
