### ISSUE TITLE
[Misión] Las Mil Agujas - ¡Muerte a todos los tramperos!

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1738]
Los tramperos crepusculares(http://es.wowhead.com/npc=47479) no sueltan el loot de la misión, red de trampero (http://es.wowhead.com/item=62924)

Aqui está el link de la mision: http://es.wowhead.com/quest=28087

**Comment by redneo** [comment]
Ya lo sueltan.
