### ISSUE TITLE
[Spell] Nervios de Acero - Sangre del norte

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#174]
Hola quiero reportar estas dos especialidades de la rama escarcha del caballero de la muerte.

<h4>*Sangre del norte</h4>http://es.wowhead.com/spell=54637
-Especificación: Transforma tus runas de sangre en runas de muerte de forma permanente. Las runas de muerte cuentan como runas de sangre, de escarcha o profanas.
-Problema:Las runas de sangre si que se transforman en runas de muerte, el problema viene tras gastar esas runas, cuando pasa su tiempo de reutilización no vuelven a ser runas de muerte, sino que pasan a ser de sangre de nuevo.
Esto esta mal ya que deben volver a ser runas de muerte constantemente.

<h4>*Nervios de acero</h4>http://old.wowhead.com/spell=50138
-Especificación:Increases your chance to hit with one-handed melee weapons by 3% and increases the damage done by your off-hand weapon by 25%.
-Problema:La 2ª parte que aumenta el daño del arma funciona, sin embargo el talento no aumenta los 3% de golpe, gon los 3 puntos en el talento.

Un saludo.

**Comment by crowel** [comment]
Añado a https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1

**Comment by ghost** [comment]
Te gane con el primero xd #89 y también ya lo puse en el primer reporte de DK.

**Comment by crowel** [comment]
^^

**Comment by searum** [comment]
fix
