### ISSUE TITLE
[Misión] Las Mil Agujas Juntos de nuevo

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1740]
No aparece el npc para entregarle la quest, que es el Valiente Viento Libre(http://es.wowhead.com/npc=45278). He estado esperando unos minutos a ver si era problema de que lo habían matado pero no. Porque en los comentarios de wowhead se puede leer qe tiene un respawn de pocos segundos

**Comment by redneo** [comment]
Ya está puesto
