### ISSUE TITLE
[Misión] Algo que ponerse

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1741]
Los mobs de la zona del Martillo Crepuscular no sueltan el item de la mision.

Aqui dejo el link de la misión: http://es.wowhead.com/quest=28125

**Comment by Kiritoo** [comment]
Como en el otro reporte.
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1275?source=cc

**Comment by Wiinter** [comment]
Lo siento
