### ISSUE TITLE
Bufo de Mil Agujas

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1745]
Creo qe este bug no está reportado o almenos no lo he conseguido encontrar.

La cosa es qe cuando llegas a la Zona de Mil Agujas te debería poner un buffo el cual te permitiese Nadar bajo el agua y además te permitiese nadar más rapido.

**Comment by ghost** [comment]
Creo que el buff es este: http://www.wowhead.com/spell=75651

De un comentario verde de Wowhead:

Los jugadores que quieran hacer misiones aquí necesitan empezar con:
- Horda:
  Warchief's Command: Thousand Needles! (Orgrimmar o Thunder Bluff)
  To the Summit (Ferelas)
  To the Summit (Dustwallow Marsh)
- Alianza
  Hero's Call: Thousand Needles! (Darnassus o Exodar)
  To New Thalanaar (Dustwallow Marsh)
  To New Thalanaar (Ferelas)

Sobre todo si quieren tener el bufo de "Speedbarge Diving"

**Comment by Kiritoo** [comment]
El buffo lo consigues tras hacer la cadena y hacer la mision correspondiente.
Saludos.
