### ISSUE TITLE
[NPCS] Reputación Clan Faucedraco

### ISSUE THREAD

**Issue by zak0ne** [RoDNet/Bugtracker-Infinium-4.3.4#1749]
El intendente del Clan Faucedraco "Grot Soplomuerte" http://es.wowhead.com/npc=49387 no funciona correctamente, cuando le clickas para poder comprar los objetos de reputación, solo te dice : "Sirve a los Faucedraco y serás generosamente recompensado". Impidiendo así comprar cualquier objeto que pudiera vender.

**Comment by Kiritoo** [comment]
Fix, falta aplicarlo.
