### ISSUE TITLE
[problemas con el ejecutable de RoD]  ReignOfDarkness.exe

### ISSUE THREAD

**Issue by tirador** [RoDNet/Bugtracker-Infinium-4.3.4#175]
MIREN TENGO problemas con el ReignOfDarkness.exe de 4.3.4 k pesa 9.98mb ago click me slae ejecutar ejecuto entro con mi cuenta y cuando trato de usar una spells ni monturas se keda cargando y nunca lo lanza pero cuando entro con el generico pues no pasa nada juego normal. ese problema lo tengo yo es general.. 
![wowscrnshot_070513_104003](https://f.cloud.github.com/assets/4945398/754204/55964ff6-e581-11e2-9691-2cf88779d278.jpg)
![wowscrnshot_070513_104010](https://f.cloud.github.com/assets/4945398/754208/65cc952e-e581-11e2-8246-0d45abbcc0dd.jpg)
![wowscrnshot_070513_104021](https://f.cloud.github.com/assets/4945398/754212/775c0360-e581-11e2-9303-adcca738af48.jpg)
![wowscrnshot_070513_104034](https://f.cloud.github.com/assets/4945398/754216/80d2d360-e581-11e2-93e4-b7b58262ea15.jpg)

**Comment by Alfonn** [comment]
Yo no lo tengo..

**Comment by Dekadencee** [comment]
Es un problema individual, ami me funciona correctamente :/
