### ISSUE TITLE
Hechizo 'Galopada salvaje' (Huargen) 'Corcel vil' no funcionan.

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1754]
Tengo el nivel 20, el nivel necesario para poder ponerse estos dos hechizos pero aun asi no me deja usarlos nunca. SI el hechizo de corcel vil no funciona supongo que tampoco funcionaran los hechizos de monturas, es una suposicion. Espero que se arregle pronto. Gracias.

**Comment by Kiritoo** [comment]
Aprendiste equitacion?

**Comment by sisu091** [comment]
Ahora que lo pienso no. vale, el problema de lo del corcel vil solucionado. Para galopada salvaje tengo que aprender equitacion?

**Comment by Kiritoo** [comment]
Claro
