### ISSUE TITLE
[Mision] La carga del Valeroso : 13714

### ISSUE THREAD

**Issue by navolic** [RoDNet/Bugtracker-Infinium-4.3.4#1758]
El problema viene después de terminar la misión [A la altura del desafío] http://es.wowhead.com/quest=13672 , que la empieza el npc=33625,  después de que se completa la misión la que sigue no aparece :
[La carga del Valeroso] 

http://es.wowhead.com/quest=13714 (Forjaz)
Empieza: Lana Martillotenaz npc=33312
Termina: Lana Martillotenaz  npc=33312

http://es.wowhead.com/quest=13715 (Gnomeregan)
Empieza: Ambrose Chisparrayo npc=33335
Termina: Ambrose Chisparrayo npc=33335

http://es.wowhead.com/quest=13716 ( El Exodar)
Empieza: Colosos npc=33593
Termina: Colosos npc=33593

http://es.wowhead.com/quest=13717 (Darnassus)
Empieza: Jaelyne Unicanto npc=33592
Termina: Jaelyne Unicanto npc=33592

http://es.wowhead.com/quest=13718 (Ventormenta)
Empieza: Mariscal Jacob Alerius npc=33225
Termina: Mariscal Jacob Alerius npc=33225

**Comment by redneo** [comment]
A mi tras esa me ha dado el desafio del aspirante que es la que tiene que dar, vuelve a intentarlo.

**Comment by navolic** [comment]
soy worgen cuando cojo las  misiones recuerda que los worgen nunca fueron a las cruzada asi que no hay un campeón que represente gilneas :s
