### ISSUE TITLE
Error Fatal: Banco de  Hermandad

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#176]
Buenas, al iniciar el banco de la Hermandad (juego de Tronos) al meterme en la 4 pestaña me a saltado el siguiente error:

![1](https://f.cloud.github.com/assets/4893907/754230/005e17de-e582-11e2-99d6-667903f6ae3f.png)

**Comment by ghost** [comment]
A mi me ocurre al darle al banco de hermandad simplemente, no llego a ver los objetos ni nada.

**Comment by ghost** [comment]
@frustrix supongo que ya no te pasa (a mi nunca me ha pasado en mi hermandad), si me dices que te sigue pasando reabro el reporte.

**Comment by ghost** [comment]
@Lvmb Esta misma mañana me ha ocurrido, sólo ocurre a veces...

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1021
Cierro Issue.
