### ISSUE TITLE
[Misión] Cementerio de Dragones Sobre unas alas rubí: 12498

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1760]
La parte de matar a los 30 mobs está bien, pero la de matar al gran necroseñor Antiok  no. Tienes que matar un mob que es como su mascota/montura (npc=28018), y luego debería salir él, lo matas y ya te da el item que pide la misión (item=38305).

Además, el objeto con el que supuestamente hay que hacer la misión (item=38302) tampco funciona.

http://es.wowhead.com/quest=12498/sobre-unas-alas-rubi

**Comment by redneo** [comment]
Si que lo da, tienes que ir montado en el dragon como dice la mision.

**Comment by redneo** [comment]
El dragon puede ser montado donde estan el npc que has de matar.
