### ISSUE TITLE
Armas sañosas

### ISSUE THREAD

**Issue by didiii** [RoDNet/Bugtracker-Infinium-4.3.4#1766]
El caso es que te pide haber ganado 7250 d honor en la temporada para poder comprarlas, he ganado ya mas que suficiente y sigue sin dejarme. Como  a mi le pasa a todo el mundo, por favor arregladlo pronto . Gracias

**Comment by ghost** [comment]
Ya está reportado, fíjate antes de hacer nuevos reportes. A ver si pueden arreglarlo pronto...

Se puede cerrar este issue, saludoos!
