### ISSUE TITLE
[Misión] Cementerio de Dragones La acusación: 12273

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1768]
Al usar la vara (item=37438) sobre los objetivos, se le pone el Buff "Forzado", pero los objetivos nunca hablan antes de morir, por lo que no se completa la misión.

http://es.wowhead.com/quest=12273/la-acusacion

**Comment by redneo** [comment]
Arreglada cuando caiga el server, me lo confirmas.
