### ISSUE TITLE
no puedo entrar co mi cuenta me sale que no se a podido obtener la lista de personajes,y e probado con otra cuenta y si que entra

### ISSUE THREAD

**Issue by vansay** [RoDNet/Bugtracker-Infinium-4.3.4#177]

**Comment by WarSxNes** [comment]
eeee!!! este es para reporte de bugs... problemas de coneccion en el foro xD....

---

Pero igual te puedo dar una mano. Simple algunas preguntas te hare.
- Estas escribiendo bien el User Name y el Password?
  
  > te hago la pregunta por que, tu mismo lo has dicho. con una entra y con la otra no.
- Si. se te olvido el Password creo que lo puedes cambiarlo en el foro.
- Intenta lo siguiente. Dentro de la carpeta de instalacion de WoW. encontraras 2 carpetas llamadas WTF y CACHE. Son las primeras y estan a la vista OJO no borres nada mas; _(no hay pierde estan entre las primeras que veras)_. Borra todo el contenido dentro de esas dos carpetas, pero sin borrar las carpetas.

> Un consejo puede ser que tu teclado este fallando y no te des cuenta cuando escribes el password por que solo te aparece *******\* en lugar de lo que escribes. ABRE un bloque de notas o archivo de texto *.txt y escribe tu User Name y luego el password, y luego un solo COPY/PASTE y nos cuentas que pasa.

**Comment by Dekadencee** [comment]
El login lo está realizando correctamente, el problema es al cargar sus pjs, tengo entendido que esto es debido a las pets.

**Comment by WarSxNes** [comment]
Si te refieres a las del Cazador? xD Tengo un PJ caza y entre los mios y no tengo problemas.

---

> Yo el problema de las pets lo arreglo de 2 formas.
> - borrando: Cache y WTF y luego depositar las pets en el establo cierro wow, borrar cache y wtf, y luego saco la pet que quiero usar.
> - cambiandole el nombre a la carpeta donde esta instalado wow. Por default se llama "World of Warcraft" solo lo cambio a "wow" etc. y listo. Esta solucion la dan en los foro de Ventisca en Bnet.
