### ISSUE TITLE
[Misión] Creo que tiene hambre

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1771]
Sacas a la prole de colazote delante de un murlok muerto y no se lo come. Solamente va a atacar a otros mobs

Aqui dejo el link: http://es.wowhead.com/quest=26321

**Comment by ghost** [comment]
ya reportado, se puede cerrar: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1479

**Comment by Wiinter** [comment]
Gracias :)
