### ISSUE TITLE
[Cazador] Varios Bugs con la pet.

### ISSUE THREAD

**Issue by neoacadio** [RoDNet/Bugtracker-Infinium-4.3.4#1772]
Buenas, os comento, mi pet esta bastante bug, empezare diciendo que siempre que entro al juego debo colocarme la habilida de sacarla por que la ponga donde la ponga siempre que me salgo se borra. 

Otro bug esque muchas veces que entro al juego tengo una pet sacada y al intentar retirarla me dice que no hay mascota, pero si intento sacar otra me dice que si que esta, debo suicidarme para que se vaya esa pet y poder llamar a otra. Y el ultimo es que la pet se pone automaticamente en pasiva simepre, cuando me monto a caballo, cuando la saco, siempre.

Espero que se puedan arreglar Un Saludo!

**Comment by sisu091** [comment]
Con respecto al hechizo de invocar la pet, lo que deberias hacer es sacar el hechizo de aquella pet que valla a sacar. No saques el hizo que agrupa los hechizos de invocar a las pets.

**Comment by neoacadio** [comment]
Si, eso si me funciona, pero el resto sigue bug

**Comment by sisu091** [comment]
Pues tienes que esperar a que lo arreglen, esperemos que no tarden mucho ni con este ni con los otros bugs que hay por aqui...Saludos

**Comment by Corialis** [comment]
Hola, yo tengo el mismo problema de que me aparece una mascota afuera cada vez que inicio sesión. Si te sirve de algo el dato, cada vez que me subo a la montura y me vuelvo a bajar la barra de pet reaparece, y ya puedo retirar.

Un saludo!

**Comment by searum** [comment]
solo falta lo de que se pone en pasiva, luego lo miro el resto esta fix..
