### ISSUE TITLE
[Sacerdote] varios bugs en los talentos de sagrado

### ISSUE THREAD

**Issue by ruben312** [RoDNet/Bugtracker-Infinium-4.3.4#1774]
Buenas, me subí un priest con la única idea de ser sagrado, tanto en pve como en pvp, pero al comprobar los talentos me di cuenta de que le fallan dos bastante importantes, el primero es oleada de luz que permite una cura instantánea y gratis de maná de vez en cuando, lo que aumenta muchísimo la movilidad y supervivencia en pvp, el segundo es una skill llamada palabra sagrada: santuario, se trata de una cura en área muy buena en pve que al parecer no cura nada, como no es una build muy usual no creo que hayáis tenido constancia de estos fallos por reportes, por eso, si no es algo muy complicado de solucionar os lo agradecería muchísimo, ya que sino tengo un pj medio inútil ya que ni disci ni sahdow me gustan nada.

**Comment by Kiritoo** [comment]
Hola porfavor reporta solo un bug por cada reporte y añade los correspondientes enlaces o ids de wowhead para que lo podamos reparar.
Cierro issue por falta de información, saludos.

**Comment by paellaencol** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1400 https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1726
