### ISSUE TITLE
[Sacerdote Sagrado] Algunos detalles acerca de "Pozo de Luz" ID: 724

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1779]
Antes que nada decir que funciona bastante bien este hechizo. Pero hay un par de detalles que me gustaría comentar:
1. Este hechizo no debería generar ningún tipo de amenaza. Es decir en ningún momento un mob irá a atacar este pozo, ya que su tabla de amenaza debe ser siempre 0. Esto es útil, ya que debido al largo CD que tiene, se utiliza mayormente antes de atacar a un boss (incluso colocándolo bajo los pies del boss sin ser aún llamado, no debe generar amenaza) para ganarle algún minuto al CD.
   Problema: en la actualidad está generando muchísima amenaza, incluso en ocasiones está funcionando como taunt, haciéndole perder el aggro al tanque.
2. Por causas desconocidas hay ocasiones en las que algún miembro de la raid no puede hacer click en el pozo, ni siquiera le aparece la opción en gris. También ocurre que a veces sí que puedes hacer click al principio del combate, pero que luego a los pocos segundos, a algún miembro de la raid (desconozco el porqué) ya no le deja clickearlo. Edito: y sin embargo posteriormente al pasar unos cuantos segundos más le deja volver a clickar

Gracias

**Comment by paellaencol** [comment]
Un problema más que se me pasó por alto.

Actualmente el pozo de luz tiene 1 punto de vida. Sin embargo viendo las notas del parche me encuentro con esto:

4.0.6:  Lightwell's health has been increased by 50% (for PvP purposes).

En esta página del foro oficial http://us.battle.net/wow/en/forum/topic/1965987399 se habla del cambio del 50% extra de vida al pozo. Y se menciona en varias ocasiones que la vida total que tiene el pozo ahora es 45mil puntos de salud.

En resumen: actualmente tiene 1 punto de vida, cuando debería tener 45.000

**Comment by paellaencol** [comment]
Falla la salud del pozo, deberia tener 45.000 ahora solo tiene 1 punto de vida

**Comment by Kiritoo** [comment]
Porfavor Jesucrist abre un Issue nuevo.
Gracias.
