### ISSUE TITLE
Los intedentes, los npc , las misiones de recoleccion y los elites plateados

### ISSUE THREAD

**Issue by Lyord** [RoDNet/Bugtracker-Infinium-4.3.4#178]
Los intendentes de las facciones de cataclysm (martillo salvaje, therazane , etc) no venden sus cosas aunque tengas la facción en exaltado, solo te saludan.
![wowscrnshot_070513_102851](https://f.cloud.github.com/assets/4944084/754291/f8edd2d0-e583-11e2-9a84-ed1a16b9584e.jpg)

Los npc de venta de los lugares de cataclysm tampoco te venden nada pero estos son diferentes a los intendentes (y no se si ocurre tambien con los npc de otros lugares)
![wowscrnshot_070513_103422](https://f.cloud.github.com/assets/4944084/754308/b4a2452e-e584-11e2-8514-4577290d8c1f.jpg)

Las misiones de recoleccion todas estan bug (recojer cosas como barriles o flores o algo parecido que te pida un npc) simplemente no aparece lo que debes de recojer ni iluminado ni nada (de esto si no puedo poner imagen por que no se vera nada)

Los elites plateados aparecen como amigo y con poca vida, no les puedes pegar (ojo todo esto no ocurre solo en tierras altas crepusculares, tambien en todos los lugares)
![wowscrnshot_070513_103758](https://f.cloud.github.com/assets/4944084/754320/45733f68-e585-11e2-9042-71a5d29375e8.jpg)

**Comment by redneo** [comment]
si me pones las ids de los que son, encantado de poner lo que venden.

**Comment by lamaza** [comment]
Los elite plateados de Uldum, pegan mas de 40k por golpe, es eso normal?

**Comment by Lyord** [comment]
:S ni idea

**Comment by lamaza** [comment]
Aqui mencionaste uno de los "bug"por asi decirlos sensibles, el que no se vea nada en el piso referente a misiones:
objetos, plantas, restos e incluso npjs para salvar etc.

lo puse en comillas ya que no se si realmente es un bug, o es que los gms no han puesto esos datos en esta emulación.

Que nos aclare esto redneo por favor, un ejemplo es con la mision de cadenas para tener portal de T A Crepusculares hacia ventormenta, hay que recoger items para terminar dicha misión.

Nos dejaste una solución provisional....

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/195

**Comment by Dekadencee** [comment]
El emulador está provocando un error grave en la visibilidad de npcs, objetos y players, estamos intentando arreglarlo, no es que falten datos, es que a veces se ven y otras veces no, viene de TrinityCore

**Comment by ghost** [comment]
@Lyord creo que la parte de mobs plateados y misiones de recolección se han solucionado, lo de los intendentes puedes crear otro reporte con enlaces a ellos?, muchas gracias.
