### ISSUE TITLE
Fallo al quedarse quieto

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#1780]
No es un fallo importante pero si que es pesado y molesta. Cuando paras he intentas montarte en montura (por ejemplo) te sale un recuadro con el mensaje "No conseguido", con lo cual tienes que dar un paso hacia donde quieras para después poderte montar en la montura, pasa también al utilizar objetos de misión que se encuentran por el mapa y al hacer profesiones.

**Comment by ghost** [comment]
ya está reportado, se puede cerrar :)
