### ISSUE TITLE
terremoto: 61882 bug 

### ISSUE THREAD

**Issue by MadScientist96** [RoDNet/Bugtracker-Infinium-4.3.4#1781]
Hola soy chaman elemental y me he dado cuenta de que el hechizo terremoto no funciona, es decir no les quita vida, tambien me he enterado de muchas personas que tampoco les funciona, podrian solucionar este bug, muchas gracias.

**Comment by ghost** [comment]
Buenas, cuando pongas un post procura poner la ID del hechizo para que los GMs lo puedan arreglar. También ayuda mucho que pongas un título más apropiado para tener todo más organizado: 

[Chamán] Terremoto: 61882

Ahí te he dejado la ID también, puedes editar tu post para que quede mejor.

Saludos!

**Comment by searum** [comment]
fix
