### ISSUE TITLE
Barcos Ventormenta

### ISSUE THREAD

**Issue by neoacadio** [RoDNet/Bugtracker-Infinium-4.3.4#1782]
Buenas, abro par areportar que los barcos de Rasganorte y los de otra isla llegan practicamente al mismo tiempo y si estas montado en uno se te queda pillado el personaje al estar los dos barcos en el mismo sitio a la vez.

**Comment by Dekadencee** [comment]
Repetido: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1298

Seguimos desde ahí
