### ISSUE TITLE
Videos Bug.

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1783]
Esto pasa con dos personajes:
-Huargen: en el momento en el que completas la mision que te convierte en huargen debe aparecer este video: http://www.youtube.com/watch?v=55YgwyDkvYU pero no sale. Te salta la pantalla de cargando y cuando ya ha terminado el juego continua

-Goblin: Cuando completas la ultima mision de Kezan, que es subir a un barco, debe aparecer este trailer http://www.youtube.com/watch?v=8_SpD9ngmDY pero pasa igual que con el huargen. Salta la pantalla de cargando y esta se quita cuando ya ha terminado.

Gracias.

**Comment by Dekadencee** [comment]
Los videos funcionan perfectamente, parece ser un error de tu cliente
