### ISSUE TITLE
[Mazmorra: Minas de la muerte (Hc)] Boss: Helix Rompengranajes

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1785]
El boss http://es.wowhead.com/npc=47296/helix-rompengranajes no es seleccionable, lo que impide la realización de este encuentro (al menos en modo heroico) y por ende proseguir en esta mazmorra.

Este problema surge en la segunda fase, ya que en la primera Helix está montado sobre un "Patán inútil" http://es.wowhead.com/npc=47297
-Tras morir el "Patán inútil", Helix debería bajar de la montura (esto sucede) y poder ser seleccionable para acabar con él (esto no ocurre al no ser seleccionable).

Gracias

**Comment by paellaencol** [comment]
Enlazo también desde https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/262

**Comment by efectokoleos** [comment]
si la verdad k deadmines tenemos un largo trabajo k hacer ahi xd

**Comment by redneo** [comment]
Ya se le puede tarjetear.
