### ISSUE TITLE
Bug del poder del guerrero "Rajar

### ISSUE THREAD

**Issue by Niiqqito** [RoDNet/Bugtracker-Infinium-4.3.4#1789]
Buenas, quisiera pedirles que arreglen el bug de este poder.

http://tinypic.com/r/15qyph2/5

Ahi, como lo muestra la imagen, el raja hace 1 de daño, ni mas ni menos (2 si es critico xD)

Espero que puedan arreglarlo en la brevedad !

Saludos y gracias.

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1165?source=cc

Ya reportado, porfavor comprobar si estan reportados antes.
Gracias por el reporte.
