### ISSUE TITLE
[Uldum] Portales

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#179]
Buenas, pues los portales que habian para orgrimmar y ventormenta ya no estan, que estaban en ramkahen.

![wowscrnshot_070513_101153](https://f.cloud.github.com/assets/4895839/754331/7903c7a8-e585-11e2-871e-cdfe5d255fd9.jpg)

Ya no hay como volver a la capital.

**Comment by redneo** [comment]
Siento decirte que ahí no tendría que haber portales al a capital, si hay alguien que haya estado en el oficial me lo corrobore..

**Comment by ghost** [comment]
http://us.battle.net/wow/en/forum/topic/2140184275

"There is no portal back to Orgrimmar or Stormwind from Uldum, and there is none back from Hyjal or Vashj'ir; portals back are from Deepholme, Twilight Highlands, and Tol Barad, and Hellfire Peninsula next to the dark portal."

**Comment by SherBlader** [comment]
Por lo que pude leer en uldum no debe haber portales de vuelta a orgrimar

**Comment by ghost** [comment]
Exacto.
