### ISSUE TITLE
[DK] Bug's generalizados de las 3 ramas.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#1790]
Bueno como me dijeron los gm's en otro post que sin id's no podían hacer nada nada bueno sera ponerlas en este.

1.Golpe Necrotico: (spell=73975)

Un golpe despiadado que inflige un 150% de daño con arma, absorbe los siguientes 100p. de sanación que reciba el objetivo [100 por cada 100p. de poder de ataque] y nubla la mente del objetivo, lo que ralentiza su velocidad de lanzamiento un 50% [25% contra jugadores]. Dura 10 s.

Eso debería hacer cosa que no,absorbe tan solo un 1p. de curación y no reduce 25% el lanzamiento de hechizos.

2.Mascota: 

```
         A. Levantar muerto: (spell=46584)
```

La mascota desaparece al usar montura de cualquier tipo y luego hay que volverla a invocar y sale con la barra desacomodada.

  B. Infusión de Sombras: (spell=49572)

El buf que se le produce a el necrofago por este talento no desaparece al usar Transformación oscura (spell=63560)

C. El daño de la mascota es mínimo,ni con grifo de necrofago que aumenta su aguante y su fuerza el 15% que posea el dk,ni mucho menos cuando se usa Transformación oscura aumenta, saca a un enemigo Player,mod,boss entre 200 y 300 de daño.

D. La habilidad Roer (spell=47481) de la mascota no la utiliza al igual que cuando tiene la Transformación oscura no usa Golpe monstruoso (spell=91797)

E. La habilidad Saltar (spell=47482) de la mascota debería saltar al objetivo seleccionado interrumpiendo casteo y inmovilizándolos por 2s cosa que no hace,al igual que su habilidad contraria al usar Transformación oscura Ataque desgarbado (spell=91802) tampoco realiza la misma función.

3.Daño por enfermedades: 

```
      A.  Fiebre de Escarcha: (spell=55095) 
```

Proporciona un daño de  150p. [+ 15.8% de tu poder de ataque] de daño de Escarcha cada 3 s... Cosa que no hace ni teniendo el talento en profano que aumenta el daño de las enfermedades 30%.

```
       B.  Peste de sangre (spell=55078)
```

Proporciona un daño de 178p. [+ 15.8% de tu poder de ataque] de daño de las Sombras cada 3 s... Cosa que como la otra no se realiza en efecto ni teniendo el talento de 30% de enfermedades aumentado.

 4.Venganza: (spell=93099) Un bug al cambiar de talentos primarios a secundarios o viceversa: 

Cada vez que recibes daño, ganas un 2% del daño no mitigado como poder de ataque durante 20 s... Puedes cambiar talentos de sangre a escarcha y se mantiene ese buf.

 5.Golpe purulento: (spell=85948)

Un ataque instantáneo que inflige un 200% de daño con arma más 487 p. y aumenta la duración de tus efectos Peste de sangre, Fiebre de Escarcha y Cadenas de hielo en el objetivo hasta 6 s.... El bug es que este ataque no extiende la duración de ninguna de las habilidades mencionadas.

 6.Importante: Maestría: Hoja terrorífica: (spell=77515)

Aumenta todo el daño de las Sombras infligido un 20%... No aumenta el daño de las sombras infligido.

 7.Importante: Maestría: Corazón congelado: (spell=77514)

Aumenta todo el daño de escarcha infligido un 20%... No aumenta el daño de escarcha infligido.

Me pareció mejor reunir todos los bugs que les e encontrado,ya que muchos de estos no están aquí y un post por cada uno es algo un poco tedioso,bueno saludos.

**Comment by Kiritoo** [comment]
Hola gracias pro añadir los ids pero como te comente en el mensaje.
"Cierro porfavor añade un issue por bug, si encuentras alguno ya reportado no lo añadas porfavor.
Saludos."

Solo un issue por bug, debes de ponerlos separados los reportes y no reportar todos de golpe ni bugs que ya esten reportados lo siento.
Vete haciendo copy-paste y ponlos separados como todo el mundo porfavor.
Gracias.

**Comment by Kiritoo** [comment]
Ah y refiriendome a "Me pareció mejor reunir todos los bugs que les e encontrado,ya que muchos de estos no están aquí y un post por cada uno es algo un poco tedioso,bueno saludos." lo que comentaste.
Tedioso es que no se van reparar los 7 de golpe ya que lleva su tiempo asi que debes añadirlo por separado.
