### ISSUE TITLE
[Misión] Ciudad de Gilneas Retrasando lo inevitable

### ISSUE THREAD

**Issue by moriaar** [RoDNet/Bugtracker-Infinium-4.3.4#1792]
En la misión Retrasando lo inevitable, has de subirte a un murciélago para completarla, el murciélago está, pero no hay forma de subirse en él:

http://es.wowhead.com/quest=24920/retrasando-lo-inevitable#english-comments

**Comment by basilisk23** [comment]
muy cierto, yo también voy hay pero no se puede subir a el murciélago

**Comment by searum** [comment]
fix
