### ISSUE TITLE
[Misión] Vuelo de reconocimiento: 12671

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1795]
La máquina no vuela, va por el suelo, agua y atraviesa texturas y se mueve MUY lenta. No tiene la ruta bien. Los mobs van atacando a la máquina cuando pasa cerca.

http://es.wowhead.com/quest=12671/vuelo-de-reconocimiento

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1310?source=cc
Ya reportado fijaros antes de reportar.
