### ISSUE TITLE
[Npc] Intendente clan faucedraco: Glot Soplomuerte 

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1796]
El intendente del clan Faucedraco "Glot Soplomuerte" (http://es.wowhead.com/npc=49387) únicamente nos está dando la misión diaria, cuando también debería ofrecernos comprarle los objetos de reputación con el clan Faucedraco (http://es.wowhead.com/faction=1172/clan-faucedraco)

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1364

**Comment by Kiritoo** [comment]
fix se reparo hace un rato, cierro.
