### ISSUE TITLE
mobs bugg

### ISSUE THREAD

**Issue by Ramsses434** [RoDNet/Bugtracker-Infinium-4.3.4#1797]
algunos mobs al atacarlos dice que evadio no te hacen daño y no les puedes hacer daño y te persiguen todo el camino dejandote en combate

**Comment by ghost** [comment]
Sí..la única solución que te queda es alt+f4 >.< No tiene pinta de ser fácil de resolver.

**Comment by Ramsses434** [comment]
ok thx
