### ISSUE TITLE
[D

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1798]

**Comment by searum** [comment]
joder colega que parte de raices = roots no entiendes? :9

http://db.mmo-champion.com/s/96429

Disentanglement
Allows the druid to clear all roots when Shapeshifting in addition to snares.

Ahora en español

# ID - 96429 Desenredo (Pasivo)

Description: Permite al druida eliminar todas las raíces y efectos de frenado al cambiar de forma.

EFFECT del aura ID - 122 Nova de Escarcha:

Aura Id 26 (SPELL_AURA_MOD_ROOT)
Effect Mechanic = (MECHANIC_ROOT)

Por tanto segun lo que yo entiendo quita TODAS las raices y recalco todas cuando dice :+1: 

druid to clear ALL roots o druida eliminar TODAS las raíces

**Comment by F4NT4SM4** [comment]
creo que se refiere a que el talento Desenredo solo deberia de servir con los druidas restauracion ya que en esta version solo ellos pueden tenerlo los ferales y equilibrio se lo quitaron

**Comment by searum** [comment]
el otro fallo fue un fallo mio que meti codigo donde no debia pero ya esta..

**Comment by ghost** [comment]
@searum Relaja tio xD Roots son todas las cosas que te clavan al suelo (raíces de druida, nova de escarcha, congelar, clavar...) Como tu bien dices, hay un talento que los druidas RESTAURACIÓN pueden cogerse (o no cogérselo), que les permite quitarse todas las roots y tal también, ahí también cobra sentido lo que dices de mechanic_root y eso. El bug, es que TODOS los druidas pueden quitarse la mecánica de roots sin tener el talento.

Espero que se entienda así :3 y muchas gracias por todos los fixes!

**Comment by searum** [comment]
relaja tu.. tengo que volver a citar

" searum commented 7 hours ago

el otro fallo fue un fallo mio que meti codigo donde no debia pero ya esta.."

que parece que no quedo claro.. ^^

**Comment by ghost** [comment]
@searum Lo he testeado y sigue bug, esto es lo que hemos hecho:

Aqui queda manifiesto el importante trastorno mental que tienes jajajajaja tristísimoo!
