### ISSUE TITLE
Buscador de Hermandades

### ISSUE THREAD

**Issue by thebigfer94** [RoDNet/Bugtracker-Infinium-4.3.4#18]
No funciona Para nada El Buscador de Hermandades.

![wowscrnshot_070313_172113](https://f.cloud.github.com/assets/4934365/746781/3386543c-e438-11e2-9cb6-e6bd95beb2c2.jpg)

**Comment by Dekadencee** [comment]
Si funciona, testeado, el problema es que los lideres de la guild deben apuntar su hermandad al buscador para que os salgan resultados.

Gracias por reportar.
