### ISSUE TITLE
NPC's de Poblado Oomlot (Las Islas Perdidas) faltan.

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1801]
Todos y absolutamente todos los npc's de dicho poblado no estan. Esta totalmente vacio este poblado. Uno de los personajes mas caracteristicos y ademas de mision es este: http://es.wowhead.com/npc=38647
les pido que aparte de arreglar dicho pnj arreglen el resto.
Gracias.

**Comment by Kiritoo** [comment]
Esto se esta arreglando.
