### ISSUE TITLE
Portales de viaje del Alto Mando Renegado (Bosque de Argénteos)

### ISSUE THREAD

**Issue by sisu091** [RoDNet/Bugtracker-Infinium-4.3.4#1806]
los portales de viaje que hay puestos, concretamente 2 no funcionan, por mucho que les des no te llevan a ningún sitio. Gracias y saludoss.

![wowscrnshot_090813_030834](https://f.cloud.github.com/assets/5339370/1102479/d7e7c2ee-1823-11e3-9378-f716be305506.jpg)

**Comment by redneo** [comment]
Esos portales son de adorno!!!!
