### ISSUE TITLE
Pechera sañosa- Set Cazador

### ISSUE THREAD

**Issue by Corialis** [RoDNet/Bugtracker-Infinium-4.3.4#1807]
La pechera sañosa del set de cazador no puede ser comprada. Figura que su precio es de 700 puntos de honor (en vez de 2200), y que para comprarla se requieren un total de 7250 puntos de honor en la temporada (el mismo problema que tienen las armas). Les dejo unas capturas para que puedan verlo.

http://tinypic.com/r/1zwf8t5/5

http://tinypic.com/r/28au68o/5

**Comment by Kiritoo** [comment]
Fix falta aplicar.
