### ISSUE TITLE
[Misión] (Hyjal) Prepping the Soil

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1808]
Preparando el terreno  http://es.wowhead.com/quest=25502

No se puede realizar al utilizar el guardallamas no se puede defender porque no ocurre nada ni cuenta como activado.

Video: http://www.youtube.com/watch?v=YiZEcx5CjnA

**Comment by searum** [comment]
fix

**Comment by crowel** [comment]
Hola queria comentar que está misión sigue sin funcionar, el guardallamas si cuenta como activado pero luego no cuenta como defendido.
He esperado en los 6 guardallamas y nada no cuenta.
Un saludo.
