### ISSUE TITLE
[Boss Baradin] Alizabal

### ISSUE THREAD

**Issue by cojidrin** [RoDNet/Bugtracker-Infinium-4.3.4#181]
Acabamos de testearlo con un gm y he estado viendo videos y usando:
http://www.worldofwarcraft.spagamers.com/Guias-Bastion-de-Baradin/guia-de-alizabal-la-senora-del-odio.html

http://www.youtube.com/watch?v=y4qntcce3aY

He visto dos cosas que el tiempo entre danza de hojas [http://es.wowhead.com/spell=105784] es como unos 50 segundos mientras que en RoD no paraba de castearlo todo al rato y además hacia las dos fases a la vez usando Odio hirviente [http://es.wowhead.com/spell=105067] a la vez que gira en danza de hojas, cosa que no deberia hacer ya que para sobrevivir a Odio hirviente necesita estar toda la raid junta en menos de 6m y si esta girando te obliga a separarte por lo que cada vez que usa odio hirviente muere un jugador

**Comment by crowel** [comment]
Buen reporte, es justo exacto el fallo que tiene mas luego que le falta el enrage.
Con esto deberia de quedar el boss perfecto.
Tras reparar esto seguiremos probando si podemos ver algo no apreciado que este mal.

**Comment by Savian123** [comment]
Pues no se...el odio hirviente lo tira en la misma fase de taunts , en el cual el boss Ensarta a uno de los 2 tanques aumentando un 500% (Sino recuerdo mal ) el daño fisico recibido durante la duracion del stun...  otro bug de Baradin son los Mobs 
![seora del odio](https://f.cloud.github.com/assets/4934124/754741/53e8a1c4-e593-11e2-8351-db005cc3c3ed.jpg) Aparte de falta de traducción que tampoco es tan importante , pegan 1 de daño y no usan ninguna habilidad 
http://es.wowhead.com/npc=56350/discipulo-de-odio#abilities
y el boss Alizabal testeado por nosotros 
![boss player](https://f.cloud.github.com/assets/4934124/754750/b339df08-e593-11e2-8c41-ed66a1eb21f2.jpg)
 es como un jugador al cual le entran tanto los aturdimientos , como las polimorfias como las congelaciones con el anillo de escarcha

**Comment by efectokoleos** [comment]
el enrage ya está arreglado, lo demás despues lo revisaré mejor

**Comment by crowel** [comment]
Quiero añadir unos reportes personales, ya pues hace un momento volvimos a testearlo despues de hacerlo con el gm.

1º
Los giros, la danza, parece que fuera la de tuetano ademas de gritar lo mismo que el con su misma voz, el giro parece muy bestia, pero el daño es bajo quita 5000 mas o menos y deberia quitar 12500.
http://es.wowhead.com/spell=105784 Danza de hojas

2º
Odio hirviente no se reparte el daño entre el grupo, nos pusimos todos en el mismo punto para comprobarlo y cuando nos golpeó, nos golpeo a todos una barbaridad sin repartir el daño.
http://es.wowhead.com/spell=105067 Odio hirviente

![wowscrnshot_070513_203027](https://f.cloud.github.com/assets/3537253/755159/94d4b222-e5a2-11e2-866f-936532ab9322.jpg)

3º
Ensartar hace la mitad de daño que deberia y también debe aumentar 150% el daño cosa que me parece raro que lo haga peganto tan poco, si esta funcionando deberia comprobarse entonces el problema.
http://es.wowhead.com/spell=104936  Ensartar

4º
El boss tras pasado el tiempo marcado no entra en furia.
http://es.wowhead.com/spell=47008 Rabia

Esos creo que son los fallos del boss actualmente.

Un saludo.

**Comment by efectokoleos** [comment]
cierro ticket, ya que cuadno volvamos a ponerlo estara al 100%
