### ISSUE TITLE
[Misión] (Hyjal) Tortolla's Revenge

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1810]
La venganza de Tortolla http://es.wowhead.com/quest=25843

Tortolla http://www.wowhead.com/npc=41504

Que deberia estar en el camino, no se encuentra alli al lado del portal con lo cual no se puede entregar.

Un saludo.

**Comment by Kiritoo** [comment]
Arreglada by Redneo
