### ISSUE TITLE
[Cocina] Festines de Cataclysm

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1811]
No funcionan los festines ni el de dragón (http://es.wowhead.com/spell=88011) ni el de marisco (http://es.wowhead.com/spell=88036).

Los puedes invocar pero si le das click no puedes comer y por consiguiente no te da el buffo de bien alimentado

**Comment by redneo** [comment]
Los de rasganorte funcionan???

**Comment by Wiinter** [comment]
Los de rasga no lo se, no los he probado

**Comment by Monleon** [comment]
Seguimos desde https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2893
