### ISSUE TITLE
Bancal del Magister Heroico

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#1812]
No se puede entrar al bancal del magister en la modalidad 5h debido a que no se puede completar duro de matar http://es.wowhead.com/quest=29685 ya que el npc al que se entrega la misión no se encuentra http://es.wowhead.com/npc=55007#ends

**Comment by efectokoleos** [comment]
arreglado en el proximo reinicio
