### ISSUE TITLE
[Misión] Las Mil Agujas - Precisión de pirata en aumento

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1814]
Hablas con Griznak (http://es.wowhead.com/npc=40727) y no te da el bote para apagar los fuegos.

Aqui dejo el link: http://es.wowhead.com/quest=25533

**Comment by redneo** [comment]
Ostras creo q la arreglé

**Comment by Wiinter** [comment]
La misión ya funciona bien, menos a la hora de completarla. Porque no se completa en ningun sitio ni ningun npc específico. Sino que cuando acabas la mision te sale en la pantalla para completarla.
En este vídeo se puede ver lo qe digo.
http://www.youtube.com/watch?v=OBhoq9CdJIk

**Comment by Wiinter** [comment]
Hay un problemilla otra vez, y es que no se puede coger la misión y decir que la misión es autoentregable.

**Comment by Kiritoo** [comment]
Porfavor pasa por aqui.
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
No comentar en Issues cerrados, se debe de crear uno nuevo para cuando surgen nuevos errores.

**Comment by Wiinter** [comment]
Es qe no eran errores nuevos xD. Pero ahora mismo creo uno y disculpa, no volverá a ocurrir
