### ISSUE TITLE
[NPC] Las Mil Agujas - Valiente Viento Libre

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1815]
Despues de hacer la misión Jefes Tótem: Isha Hacha Oscura (http://es.wowhead.com/quest=27315) no continua con la siguiente misión de esa cadena de quests.
La siguiente misión sería Jefes Tótem Ancestro Pezuña Tempestuosa (http://es.wowhead.com/quest=27319)

Aqui dejo el link del npc (http://es.wowhead.com/npc=45278)

**Comment by redneo** [comment]
Arregladas las dos cadenas de misiones, horda y alianza (el orden)
