### ISSUE TITLE
[DK - Urgente] Pilar de Escarcha: 51271

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1816]
Sigue bug, y los hay aprovechándose en arenas.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1564

---

Los DKs escarcha, al usar la habilidad Pilar de escarcha (ID=51271), se vuelven inmunes a todos los derribos y similares (como ralentizaciones) durante toda su duración (20 segundos), y pueden seguir moviéndose y atacando con total naturalidad.

Hasta ahí todo bien. 

Además, hay un glifo (spell=58635) que añade a lo anterior una inmunidad contra todos los efectos que provocan pérdida de control de tu personaje (miedo, ceguera, porrazo, polimorfia, anillo de escarcha, arrepentimiento y un largo etc), pero que a cambio también te congela en el sitio sin que puedas moverte mientras la facultad está activa.

El bug está en que los DKs que usan pilar de escarcha NO son clavados en el sitio y sin embargo tienen ambas inmunidades, tanto a ralentizaciones y derribos (el hechizo "a pelo"), como a pérdidas de control del pj (efecto añadido de glifo) y repito, SIN CLAVARSE.

El resultado son DKs que pueden empalmar un inmune de 26 segundos a TODO lo que afecte al movimiento y control del pj, dando tiempo sobrado a bajarse a alguien en arenas.
- Si estás seguro de que los DKs que usan glifo son clavados al suelo durante 20s, puede que lo que esté bug sea la habilidad Pilar de escarcha (ID=51271) que está dando el efecto positivo del glifo sin llevarlo puesto.

Todo esto sería más fácil si alguno de los muchos dks bugeros que van en frost se prestaran a ayudar...pero claro, parece que no les interesa.

**Comment by lamaza** [comment]
hola viejo, fotos? video? Esto va en denuncias del foro XD. Aqui es para reportar bugs, no pjs.

**Comment by Kiritoo** [comment]
Lamaza segun veo Asman está  reportando un hechizo/talento que sigue bug, Pilar de escarcha, no un pj.
Si te fijas https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1564 Está cerrado por lo que supongo que creo de nuevo este reporte, para avisar, que es lo que debe hacer.
Saludos.

**Comment by searum** [comment]
Pues asman explicate mejor porque en el reporte pusiste claramente que el bug era con el glifo que no te clavaba al suelo, ahora te clava y no se que es lo que esta bug segun tu asi que si puedes explicarmelo te lo agradeceria! :D

**Comment by ghost** [comment]
@searum ok, modifico este reporte de la manera más clara posible, pero no te quejes si me queda muy extenso jajaja

**Comment by searum** [comment]
jajaja asmancito comprueba ahora si ya esta bien ^^

**Comment by ghost** [comment]
Los DKs SIN GLIFO esta funcionando como debe, les afecta stun y ccs.

Falta probar con glifo.

**Comment by searum** [comment]
con glifo debe de funcionar como debe tambien xD

**Comment by ghost** [comment]
Arreglado, gracias searum :)
