### ISSUE TITLE
[Misión] (Hyjal) The Strength of Tortolla

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1817]
La fuerza de Tortolla http://es.wowhead.com/quest=25915

Se debe escoltar a un hijo de tortolla hasta el cristal el cual se debe examinar, al cojar la misión no aparece el hijo y si vas andando hasta el cristal no se cumple el objetivo de misión haciendo imposible completar.

Quiero comentar que está misión es el comienzo de una cadena de 7 misiones muy importante para hacer las de hyjal.
Llevo 95 / 115 completadas.

Aqui un video: http://www.youtube.com/watch?v=Kt-T1jycNOw

Gracias

**Comment by redneo** [comment]
Arreglada
