### ISSUE TITLE
[Guerrero] Ataque de la victoria

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#1819]
El ataque de la victoria (spell=34428) se está activando con las culebras de la trampa de culebras (spell=34600) cuando no debería.

**Comment by ghost** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1153

treants, copias del mago, trampa de serpientes de los cazas...

**Comment by Kiritoo** [comment]
Seguimos deste el #1153 gracias por tu reporte
