### ISSUE TITLE
me matan los muñecos de entrenamiento

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#182]
no es broma jeje,los muñecos de ogrimar me atacan y pegan y matan, sobre todo cuando me tiro http://es.wowhead.com/spell=51723 con esta habilidad me atacan siempre ,moviendo de sitio para matarme,tambien 1 vez pegandoa  mele y dejando sangrados me aleje a unos 10 llardas y zas me mataron

**Comment by redneo** [comment]
los de donde?????

**Comment by 50megas** [comment]
ogrimar

**Comment by redneo** [comment]
es la habilidad la que hace que te ataquen... increible!

**Comment by redneo** [comment]
Encontrado el fallo, cuando lanzas http://es.wowhead.com/spell=51723 automaticamente a quien le des, se pone a lanzar http://es.wowhead.com/spell=51690

Por la base de datos no hay nada, es fallo de programacion.

**Comment by 50megas** [comment]
hola la habilidad http://es.wowhead.com/spell=26679 tambien activa http://es.wowhead.com/spell=51690 

un saludo

**Comment by 50megas** [comment]
ya esta areclado parece
