### ISSUE TITLE
PROBLEMA CON LA MISION "EL YUGO DEBILITADO" DE LOS NO-MUERTOS

### ISSUE THREAD

**Issue by negrosombra** [RoDNet/Bugtracker-Infinium-4.3.4#1821]
Hola soy el usuario negrosombra mi personaje es Darkta un brujo no muerto.
En la mision se supone que debia hablar con una sacerdotisa llamada:""sacerdotisa de la sombra malia" pero al parecer no quiere hablar.
Por favor podrian solucionarlo

**Comment by efectokoleos** [comment]
ya posteado https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1804

**Comment by negrosombra** [comment]
si ese es mi problema no aparece el dialogo para conversar podrian solucionarlo
