### ISSUE TITLE
[Misión] (Cuenca de Sholazar) Seguimos destilando

### ISSUE THREAD

**Issue by Creamfour** [RoDNet/Bugtracker-Infinium-4.3.4#1822]
Al coger la misión, se tiene que hablar con el NPC de al lado (McManus ''Chispa''), pero éste no da el diálogo para empezar la misión.

**Comment by ghost** [comment]
Hay que poner la ID de la misión. Yo creo que hice sin problemas las misiones ayer.

**Comment by Creamfour** [comment]
Pues se habrán bugeado cuando las he hecho yo

**Comment by Kiritoo** [comment]
Está misión funciona bien.
