### ISSUE TITLE
Transfiguración Bug

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#1823]
Las armas que no tienen estadísticas como fuerza, agilidad, golpe crítico, etc.
(como http://es.wowhead.com/item=8190) no deja transfigurarlas

**Comment by Velcositro** [comment]
No es un bug, una de las reglas oficiales de la transfiguración es que no se pueden transfigurar objetos sin estadísticas, aunque sea de calidad "verde" (con algunas excepciones, como las réplicas que venden sin estadísticas exclusivamente para transfigurar).

**Comment by elmiriox15** [comment]
No, pero en el oficial si se podía en este parche, por eso digo que es un bug, un amigo del oficial tiene transfigurado esta espada (item=9372/sulthraze-la-azotadora) y no tiene estadísticas.

**Comment by Kiritoo** [comment]
Y tu amigo en que versión está?, 5.3

**Comment by elmiriox15** [comment]
Pero él ya lo había hecho en la 4.3.4 cuando jugó al oficial en ese tiempo, y si le dejaba transfigurar esa arma sin estadísticas
