### ISSUE TITLE
Cavernas del Tiempo: Batalla del Monte Hyjal

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#1824]
Funciona todo perfecto hasta que llegamos a Archimonde, wipeamos la primera vez y se quedo atascado en las montañas como si hubiese una pared invisible. Al wipear otra vez se desbloqueo. Lo matamos y no suelta el logro. Cuando se empezó a despojar a uno de los miembros (que gano la espada) si que le salto el logro al recibirla.

Como es lógico debería de habernos saltado a todos.

**Comment by lamaza** [comment]
Hola, primero decirte que asi no se reporta.

Segundo, arribita hay un buscador, úsalo mas a menudo para no repetir temas.

 Tercero, yo ya lo habia reportado. Y el logro si se puede conseguir.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1243

**Comment by Kiritoo** [comment]
Ya reportado cierro.
