### ISSUE TITLE
[errores internos] abrir banco de hermandad

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1825]
http://pastebin.com/J4R31tYc

Cuando abro algunas pestañas, a  veces me sucede este error, y sigue pasando aunque borre CACHE.

Esta vez me ha pasado, por abrir la pestaña #1,#2 y luego al irme directo a la pestaña #5 y ahora cuando logueo el pj y abro el banco de hermandad, me cierra el wow directamente.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1526

**Comment by Kiritoo** [comment]
Continuamos de https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1526

**Comment by lamaza** [comment]
Dale ,solo queria poner mas evidencia.
