### ISSUE TITLE
La fuga de Durnholde Heroico

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#1826]
Despues de derrotar al segundo jefe, cuando Thrall monta en el caballo, por el camino hay guardas, al llegar a los primeros una de ellos se queda pillado esquivando todos los ataques y Thrall no le hace nada.

![wowscrnshot_090913_115038](https://f.cloud.github.com/assets/1721489/1105974/2f6ffeec-1936-11e3-8e26-5ed4b466a6c2.jpg)

**Comment by Kiritoo** [comment]
Tienes que añadir enlaces de los npc, misiones, items... etc del fallo que estes reportando.
Añadir ids no cuesta nada.

**Comment by Corialis** [comment]
Yo acabo de terminar esa mazmorra lo más bien. A lo mejor tuviste mala suerte xD.

**Comment by foxmclaud** [comment]
No he añadido enlaces de id debido a que el npc en cuestión lo comparte con otros muchos y dándolo no especificaría cual de ellos es el que falla, sino el conjunto de todos ellos, y no todos fallan.

**Comment by Kiritoo** [comment]
?
http://es.wowhead.com/npc=17815
Solo hay 1 id... además que este reporte está falto de información.

**Comment by foxmclaud** [comment]
Exactamente como tu has dicho, hay solo un id de npc, pero si hay 50 npcs iguales ¿de que sirve reportarlo si es 1 de ellos el que ha fallado? Para eso he especificado donde ocurre dicho problema. Que sí que no esta demás el id, pero ¿a que no te soluciona cual es exactamente el que no funciona bien?

**Comment by Kiritoo** [comment]
.. Si no añades el id no puedo ir hasta los npcs, si no añades el link de la mazmorra con el nombre la tengo que buscar... Tan dificil es reportar las cosas como dios manda.
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Haz como te de la gana pero te aviso que como no lo pongas como se debe en tus próximos  Issues van a ser cerrados

**Comment by redneo** [comment]
En normal la acabo de arreglar y la he hecho sin problemas en heroico.
