### ISSUE TITLE
Misión --> (Sima Ígnea) "Enemigos por debajo"

### ISSUE THREAD

**Issue by negrosombra** [RoDNet/Bugtracker-Infinium-4.3.4#1829]
Hola. en esa mision se supone que debo hablar con kurjack en sigma ignea (la mazmorra de orgrimar) pero no esta.
lo pueden arreglar porfa
gracias.

**Comment by ghost** [comment]
Cuando reportes algo pon siempre la ID para que lo puedan arreglar. Puedes usar Wowhead para ello. 

Saludoos!

**Comment by negrosombra** [comment]
soy negrosombra

**Comment by Kiritoo** [comment]
Y yo soy yo.

http://es.wowhead.com/quest=26865/enemigos-debajo

Necesitamos id de la quest no tu nick, jaja.

**Comment by redneo** [comment]
Puesto el npc http://es.wowhead.com/npc=44217
