### ISSUE TITLE
daño de piroexplocion instantánea bajo.

### ISSUE THREAD

**Issue by kaalbireth** [RoDNet/Bugtracker-Infinium-4.3.4#183]
![wowscrnshot_070413_153643](https://f.cloud.github.com/assets/4935390/754655/30ed4a74-e590-11e2-9e83-554bd579b80e.jpg)

como se ve en la foto recién tiraba la piroexplocion instantanea y no hacia nada de daño.

**Comment by Alfonn** [comment]
Ya está reportado. https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/44

**Comment by Dekadencee** [comment]
Duplicado, seguimos desde #44
