### ISSUE TITLE
[NPC] Las Mil Agujas - Valiente Viento Libre

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1831]
El Valiente no da algunas quests en orden y por tanto he llegado a un punto qe se ha saltado dos misiones y no puedo ni continuar ni coger las que han qedado atrás.

Paso de esta mision: http://es.wowhead.com/quest=27324 a esta http://es.wowhead.com/quest=27328

Saltándose estas dos:
http://es.wowhead.com/quest=27321
http://es.wowhead.com/quest=27326

**Comment by redneo** [comment]
Ordenadas todas las misiones de Las Mil Agujas

**Comment by Wiinter** [comment]
Ahora no da la siguiente mision: http://es.wowhead.com/quest=27358

**Comment by redneo** [comment]
tras completar las misiones 
http://es.wowhead.com/quest=27321
http://es.wowhead.com/quest=27326
http://es.wowhead.com/quest=27328

La dan, cualquiera de ellas
