### ISSUE TITLE
Mision Bug: Los Baldíos del Sur - Una linea en el suelo-24546

### ISSUE THREAD

**Issue by Bariloche123** [RoDNet/Bugtracker-Infinium-4.3.4#1835]
Activo las banderas pero nada sucede.

**Comment by redneo** [comment]
http://es.wowhead.com/quest=24546

Tanto cuesta poner el enlace de wowhead, para que solo necesite hacer click para ver la mision?

A ver si se termina la web y pongo una guia de como poner los reportes de las cosas.

Arreglada
