### ISSUE TITLE
Mision Bug: Los Baldíos del Sur - El cambio de Gar'dul-24591

### ISSUE THREAD

**Issue by Bariloche123** [RoDNet/Bugtracker-Infinium-4.3.4#1836]
Subo a la torre y nada sucede...

**Comment by redneo** [comment]
http://es.wowhead.com/quest=24591

El npc 37811 ahora está movido en lo alto de la torre y completa la misión. Tendria que ponerse waypoints, pero tardaria mucho.

**Comment by redneo** [comment]
Suelta y vuelve a coger la mision
