### ISSUE TITLE
Bug con ganancia de reputacion

### ISSUE THREAD

**Issue by escontreras** [RoDNet/Bugtracker-Infinium-4.3.4#1838]
Buenas tardes gms de RoD, quisera venir a reportar unos bug que me he encontrado con la ganancia de reputacion gracias a los tabardos 

"tabardo de la hermandad renombrado" : http://es.wowhead.com/item=69210/tabardo-de-hermandad-renombrado

"tabardo de Ramkahen"  : http://es.wowhead.com/item=65904/tabardo-de-ramkahen

con el primer tabardo por mas que hago bg no me sube la reputacion con mi hermandad y con el segundo cada vez que hago aleatoria me lo pongo pero no me da reputacion ni matando mobs ni boss'

Me despido espero que lo puedan solucionar gracias :D

**Comment by Wiinter** [comment]
Una pequeña puntualización, el tabardo lo unico qe hace es augmentar la reputación ganada. En bg no se gana reputación con la hermadad, se gana con las diferentes facciones de las bgs. Te pondré un ejemplo: Las misiones de Tol'barad al completarse te dan reputacion con los de Guardianes de Baradin(Creo que se escribe asi esa facción, no lo se seguro) y también con la hermandad. Entonces lo que haría el tabardo de la guild es augmentarte esa reputación que da.

Espero haberte aclarado la confusión y espero no haberme equivocado yo

**Comment by escontreras** [comment]
ok eso lo entiendo entonces, pero y lo de la reputacion con ramkahen?

**Comment by Wiinter** [comment]
Está bug xD

**Comment by Monleon** [comment]
Para que te de reputación dentro de una mazmorra, quítate el tabardo y vuelvelo a equipar una vez dentro
