### ISSUE TITLE
[Raid Bug] Dragon Soul [ Alma de Dragon ]

### ISSUE THREAD

**Issue by Savian123** [RoDNet/Bugtracker-Infinium-4.3.4#184]
Bueno como jugadores interesados en jugar en RoD y con muchas ganas de poder hacer tanto PvE como PvP fuimos a testear la raid , para empezar 
![wow ds](https://f.cloud.github.com/assets/4934124/754651/ddc2ef98-e58f-11e2-898d-c50cc91d7c09.jpg) todos... pero todos los Mobs pegan 1 de daño... y carecen de habilidades que pongo a continuacion 
http://www.wowhead.com/npc=57158/earthen-destroyer#abilities:mode=normal10
Aparte tienen todos un Drop de epicos de 100% 
Otro de los bugs que nos encontramos ... es que los dragones no saben volar y aun pudiendo targetearlos no puedes pegarles ....
![wow ds piatas](https://f.cloud.github.com/assets/4934124/754660/5dab4b9c-e590-11e2-8aea-24c91694ea1d.jpg)
Aparte estan los mobs en el suelo todos apilonados y molestando ...
Otro de los grandes fallos que encontramos fue el 1er boss... 
![1er boss](https://f.cloud.github.com/assets/4934124/754671/b29d9c72-e590-11e2-9ec2-0dcf65251fd7.jpg)
Tiene poco mas de 400 de vida... con lo cual le matas de 1 golpe cuando deberia ser asi el encuentro 
http://es.wowhead.com/npc=55265#encounter
tener estas habilidades 
http://es.wowhead.com/npc=55265#abilities
y finalmente tener la siguiente vida en los diferentes Modos de juego
10  36,000,000
10H 42,946,000
LFR=Buscador de banda   76,500,000
25  102,000,000
25H 180,404,192

Finalmente nos encontramos con 
![wow dragones bug para ir a bosses](https://f.cloud.github.com/assets/4934124/754711/258ef7de-e592-11e2-9330-f5b93ad1f2de.jpg)
los dragones que te llevan a los bosses Ignoto Bug sin poder usarse con lo cual alli se termino nuestro testeo de la Raid 
y con Ultraxion en el suelo targeteable pero no se le podia pegar 
![ultraxion bug](https://f.cloud.github.com/assets/4934124/754716/47807ef8-e592-11e2-99a1-570e3d87e5ea.jpg)

**Comment by efectokoleos** [comment]
esta raid deberia estar cerrada porke esta claro k no esta scriptada ni na simplemente hay spawns para ver lo que nos vamos a encontrar a la hora de scriptarla ^^ un saludo y cierro
