### ISSUE TITLE
[Cazador] Glifo de disparo mortal

### ISSUE THREAD

**Issue by Vic2tor** [RoDNet/Bugtracker-Infinium-4.3.4#1840]
Este habilidad se activa cuando el enemigo tiene un 20% de salud, en la cual sirve para rematar.
Con este Glifo me proporciona que cuando no lo mato con el 1º Disparo mortal, me otorca un 2º Disparo mortal, instantaneo, no tengo que esperar 10s para que se me recarge mi Disparo mortal.
Me gustaria que lo arreglaran ya que a un gran glifo, que ahora esta muerto de risa.
![wowscrnshot_091013_125116](https://f.cloud.github.com/assets/5310615/1113849/6c6af8c4-1a08-11e3-8b54-edcd1b3c2090.jpg)

**Comment by searum** [comment]
fix

**Comment by Jhovanni** [comment]
Hay ya varios reportes de este glifo, y casi todos han sido cerrados diciendo 'fix', pero el bug sigue y nunca ha estado solucionado.
