### ISSUE TITLE
Mision Laderas de Trabalomas - "Una posibilidad de luchar"

### ISSUE THREAD

**Issue by negrosombra** [RoDNet/Bugtracker-Infinium-4.3.4#1841]
Hola soy negrosombra.
Hay un problema con esta mision, se supone que con una varita que me dio una elfa de sangre llamada "Consejera Nochealba" esa varita se lo debo conjurar a los "cervato de colina" estan en el mapa de "laderas de Trabalomas"
pueden arreglarlo gracias.

**Comment by Wiinter** [comment]
Pon la id de wowhead, asi los gms podrán arreglarla más facilmente

**Comment by negrosombra** [comment]
y que hago como lo escribo porfavor me lo explican

**Comment by Wiinter** [comment]
Miras vas a la página web http://es.wowhead.com/ Entonces buscas ahi tu misión poniendo el nombre de la misión en la barra de búsqueda.
Entonces cuando encuentres tu misión, en la barra de direcciones verás qe pondrá es.wowhead.com/quest=123088098. Pues este último número es la id de la misión, que es lo qe necesitan los gms.

Espero haberme explicado lo suficientemente bien, cualquier duda pregunta de nuevo :)

**Comment by negrosombra** [comment]
solo la ultima cosa donde pongo el ultimo numero. ose como lo tengo que hacer o colocar
Y GRACIAS POR LA INFORMACION!!!!!

**Comment by Kiritoo** [comment]
Si te digo la verdad la gente que nos pone ese último numero solo nos fastidia un poco al hacernos buscarlo, sobre todo en caso de las misiones ya que luego tenemos que buscarlo nosotros y leer la especificación doble trabajo.
Si puedes pon asi http://es.wowhead.com/quest=xxxxx
Gracias

**Comment by negrosombra** [comment]
hola soy yo de nuevo mira agradezco tu ayuda y yo no quiero seguirte
molestandote o jodiendo ni nada. yo intente en colocar que mi personaje
dijese la suiguente frase
/http://es.wowhead.com/quest=28616http://es.wowhead.com/quest=28616#screenshots
(con
el http) lo puse y no pasa nada.
gracias por todo

**Comment by redneo** [comment]
http://es.wowhead.com/quest=28495

**Comment by negrosombra** [comment]
agradezco tu pasiencia con migo, que me tengas que aguantarme pero no lo
logro entender nada, mira lo puse en asi Decir:
http://es.wowhead.com/quest=28495 y nada sigue igual
la verdad no logro entender donde va esto o aquello. porfavor porfavor
podrias explicarlo como si estuvieras hablando con un niño de 3 años paso
por paso porva.
Y ENSERIO AGRADEZCO TU PASIENCIA CON MIGO Y EN SERIO AGRADEZCO TU AYUDA

2013/9/11 redneo notifications@github.com

**Comment by negrosombra** [comment]
tengo una mejor idea si tienes un personaje de la horda buscame mi
personaje es un no-muerto brujo llamado Darkta, me buscas en el juego.
estare conectado a la 1pm en horario de montevideo uruguay. te parece
 buena idea OK

**Comment by redneo** [comment]
arreglado, puede que haya que esperar que caiga el server, pero me ha funcionado bien
