### ISSUE TITLE
[Objeto] Condensador electrostático

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1842]
Buenas. Se trata de este objeto: http://es.wowhead.com/item=67494

Creo que no funciona, he podido extraer más de 100 minas con ese objeto en el inventario y no ha soltado ni un aire. No sé si es que la probabilidad es mínima o que no funciona.

Saludos.

**Comment by Monleon** [comment]
Funciona correctamente
