### ISSUE TITLE
[Misión] (Las Cumbres Tormentosas) La ultima de su raza

### ISSUE THREAD

**Issue by didiii** [RoDNet/Bugtracker-Infinium-4.3.4#1844]
La misin consiste en entrar a una cueva y liberar a una osa. Resulta que todo va bien hasta que liberas a la osa, ella sale de la cueva pero no te lo da por valido y no te cuenta la mision. simplemente la osa desaparece
En cumbres tormentosas
http://es.wowhead.com/quest=12983/la-ultima-de-su-raza

**Comment by Kiritoo** [comment]
Enlaces? Lugar de la misión?
Porfavor modifica el reporte, gracias.

**Comment by didiii** [comment]
Ya esta modificado, perdon

**Comment by redneo** [comment]
A mi me ha contado correctamente cuando ha llegado al poblado... vuelve a probarla a ver...

Una cosa... yo que tu limpiaba el camino antes de cogerla.

**Comment by didiii** [comment]
Esque aunque en la cueva no haya nadie desaparece nada mas salir, y los mobs tambien desaparecen y aparecen por eso no se muy bien los que hay

**Comment by didiii** [comment]
He vuelto a probar 5 veces  y todas ellas me desaparecía la osa nada mas salir de la cueva

**Comment by redneo** [comment]
arreglada
