### ISSUE TITLE
quest de Gilneas Dar esquinazo

### ISSUE THREAD

**Issue by shogun1968** [RoDNet/Bugtracker-Infinium-4.3.4#1845]
Hola, estoy intentando hacer la cadena de quest de Gilneas y no puedo hacer una misión que se llama "dar esquinazo", ya que tiene que salir una forestal y tirarme una trampa y he recorrido todo el mapa y no sale. tengo entendido que debería salir al bajar  por el camino que va hacia el norte. Les agradecería que comprobasen si funciona bien o soy yo el que no da con ello y me informasen para poder continuar con el pj llamado "doberman". Perdonen las molestias y muchas gracias.

**Comment by Kiritoo** [comment]
Cual es el enlace de la mision?
Saludos.

**Comment by shogun1968** [comment]
No se bien lo que me pides, no tengo mucha idea de esto, pero a ver si te sirve con esto que he averiguado, es la quest 24616

el enlace de la misión, para verlo por internet, si es lo que me pides, es http://es.wowhead.com/quest=24616

perdona las molestias y muchas gracias por la atención. 

Date: Tue, 10 Sep 2013 14:10:58 -0700

**Comment by searum** [comment]
fix
