### ISSUE TITLE
[Pícaro] Abanico de cuchillos

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1846]
La habilidad Abanico de cuchillos (http://es.wowhead.com/spell=51723) hace que el Arma arrojadiza pierda 1 punto de durabilidad cada vez que se usa y afecta a algún pj u NPC.

Gracias.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/830

Según Searum está reportado, pero no lo he encontrado ni buscando por arma arrojadiza, ni por la ID del spell.

**Comment by searum** [comment]
que no hace falta que lo reportes que me conozco el bug y no es de spell...
