### ISSUE TITLE
[Guerrero] Bug visual ira al cambiar de actitudes

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1847]
Buenas. Al cambiar de actitudes con la barra de ira, por ejemplo, a 100/100, la barra debería bajar a 0/100. 

En verdad sí lo hace, pero visualmente se sigue viendo ese 100/100 y es muy molesto porque piensas que tienes 100 de ira y haces cualquier spell y ya te dice: "No tengo suficiente ira."

Un saludo y gracias.

**Comment by F4NT4SM4** [comment]
En realidad deberia de dejar 25 de ira por un hechizo pasivo de protec que por cierto esta bug...
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1183

**Comment by ghost** [comment]
Pues doble bug a arreglar... y la verdad jode bastante a la movilidad del guerrero ya que te cambias de actitud de batalla a defensiva para hacer Intervenir o a rabiosa para hacer Interceptar y te ves con el mensajito de "No tengo suficiente ira".

**Comment by Monleon** [comment]
Diria que esto ya no sucede, al quedar arreglado el pasivo de Maestria en actitudes.
