### ISSUE TITLE
[Cumbre del Vórtice] Altairus

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1848]
Lo que haces es que saca demasiados tornados, cosa que te hace imposible moverte y sobrevivir porque cualquier tornado te pilla. Diría que hay más tornados de los que debería haver.

Aqui esta el link del npc : es.wowhead.com/npc=43873
Aqui la spell: http://es.wowhead.com/spell=88314

**Comment by searum** [comment]
fix
