### ISSUE TITLE
[Guerrero - Talento] Maestría táctica

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1849]
Pues eso, el talento no funciona. Debería dejarte con 25/50 de ira al cambiar de actitud pero te deja a 0 (y además está el bug visual que te hace creer que tienes lo que tenías en la anterior actitud, pero en realidad no tienes nada).

Este talento esta en la rama de armas en la segunda fila. No encuentro la ID ya que en Mists of Pandaria ya no existe el talento.

Un saludo y gracias.

**Comment by F4NT4SM4** [comment]
el talento aumenta un 25/50 de la ira que se mantiene gracias a Mestria en actitudes (hechizo de protec) pero esta bug https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1183

**Comment by Kiritoo** [comment]
Seguimos el reporte anterior.
