### ISSUE TITLE
[Diaria de cocina: Entrañas] Caracoles para llevar

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1851]
No es posible realizar http://es.wowhead.com/quest=29333/caracoles-para-llevar debido a la ausencia de http://es.wowhead.com/item=69918 en el "Lago Aguasclaras" http://db.wowraider.net/z/162/es/

**Comment by redneo** [comment]
este es el npc, y si que funciona correctamente.
http://es.wowhead.com/npc=53526

**Comment by paellaencol** [comment]
Cierto, el nombre está en inglés, normal que no encontrase nada haciendo /target en castellano

P.D. /target Brightwater Snail

Gracias.
