### ISSUE TITLE
[Guerrero] Ejecutar

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1852]
ID:5308
![wowscrnshot_091013_232432](https://f.cloud.github.com/assets/3101842/1120192/098b8104-1a96-11e3-90f6-453cc69b7184.jpg)
El ejecutar inflije 5141p de daño fisico y consume 20 de ira extra para infligir un maximo de 10261p de daño extra es decir si tenemoas de 30 de ira (la que pide el ejecutar normal y el 20 extra) se nos aumenta un 10261p de daño al ataque

el caso es que no esta realizando el segundo efecto de 20 de ira extra siempre ataca con el daño basico...

**Comment by ghost** [comment]
Ya está reportado https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1432

Saludoos!

**Comment by Kiritoo** [comment]
Cierro seguimos en el anterior.
Saludos.
