### ISSUE TITLE
[Glifo - Guerrero] Glifo de Ira Rabiosa

### ISSUE THREAD

**Issue by andresheca** [RoDNet/Bugtracker-Infinium-4.3.4#1853]
Buenas, 
El glifo con id=43396
http://es.wowhead.com/item=43396 //Este es distinto porque en MOP cambia.
http://db.mmo-champion.com/s/58096/glyph-of-berserker-rage/ //Datos del spell (Cata)
No está funcionando, debería de generar 5 puntos de ira al usar Ira rabiosa
http://es.wowhead.com/spell=18499
http://db.mmo-champion.com/s/18499/berserker-rage/
Y no genera nada de ira.
¡Un saludo!

**Comment by searum** [comment]
fix
