### ISSUE TITLE
[Misión] (Las Mil Agujas) El maestro de vuelo Crepuscular

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1855]
No puedes montarte en Cuorevaja y por tanto tampoco puedes eliminar al maestro de vuelo Crepuscular Richtofen.

Aqui dejo el link de la misión: http://es.wowhead.com/quest=28098

**Comment by redneo** [comment]
Arreglado cuando caiga el server.
