### ISSUE TITLE
[Alquimia] Piedras filosofales

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1856]
Al hacer las piedras de alquimista, la profesión debería subir 5 puntos tal y como indica en su nombre en el menú de la profesión. Sin embargo está subiendo 2 puntos (por los rates).

Supongo que pasará con todas las piedras igual, yo sólo he podido hacer la de mercurio.

es.wowhead.com/item=68776/piedra-de-alquimista-de-mercurio

**Comment by Monleon** [comment]
Sí, eso es porque actualmente todo está dando x2 (seguimos desde otro reporte, hay varios acerca de lo mismo)
