### ISSUE TITLE
[hechizos - Talento] Sellos de Mando - Paladin

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1857]
Talento: Sellos de Mando id 85126 (actualizado con id)

Bug: Solo golpea a 1 objetivo, y NO a todos los objetivos cuerpo a cuerpo como deberia ser.

![wowscrnshot_091013_183438](https://f.cloud.github.com/assets/4790547/1122861/1d1e5fb2-1ae5-11e3-9aac-0e5ce00237cd.jpg)

**Comment by searum** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1955
