### ISSUE TITLE
desbaneadme ya joder

### ISSUE THREAD

**Issue by rdany19** [RoDNet/Bugtracker-Infinium-4.3.4#1858]
me baneasteis de broma y se os a olvidado desbanearme ya joder kiero jugar

**Comment by Kiritoo** [comment]
Este no es el lugar para esto..
Tenemos web, aqui solo fallos del juego.

**Comment by searum** [comment]
ah fue de broma? yo creo que me sobraron hueveresss jeje.

pd: el ban no se levanta, la proxima vez que vayas a vacilar piensatelo dos veces. (es permanente)

**Comment by rdany19** [comment]
vale muchas gracias

**Comment by searum** [comment]
Gracias a ti por comportarte asi y ganarte el ban a pulso, en realidad ni queria ponertelo pero tu me obligaste.

**Comment by rdany19** [comment]
a vale no importa yo pensaba ke como todos gastabais broma no pensaba ke alguien se la tomase asi y todos riendose pero bueno ya veo como es

**Comment by searum** [comment]
Venga, no te hagas el inocente ahora porque sabes muy bien como han sido las cosas y que te has puesto farruquito... Todo acto tiene sus consecuencias para bien o para mal

**Comment by rdany19** [comment]
madre mia pero si gasto bromas con joss y se rie y todos los gms tu eres distinto no pasa nada si ya se akien hablarle y a kien no.

**Comment by searum** [comment]
Directamente no te tomes confianzas que no te han dado. Estas baneado de IP y cuenta, espero no verte mas por el servidor ya que gente como tu prefiero no tenerla aqui.

**Comment by Dekadencee** [comment]
Las faltas de respeto son sancionadas con ban permanente, y más si es hacia un miembro del staff deberías de saberlo, que un gm te lo permita (que mal hecho por su parte) no quiere decir que tengas derecho a hacerlo con todos...

**Comment by rdany19** [comment]
dios... tio no puedes acerme esto me traje un monton de gente al servidor por una broma me vas a acer esa putada ?

**Comment by rdany19** [comment]
vale... gracias por todo

**Comment by rdany19** [comment]
me traje a este server gente porke me lo dijeron y por una broma me vais adejar baneado para siempre?

**Comment by rdany19** [comment]
no seais asi porfavor, kiero jugar a este server y todo el mundo ta con bromas porfavor desbaneadme tened piedad

**Comment by rdany19** [comment]
porfavor searum perdoname, porfavor te lo pido soy casi nuevo en el server y eso no lo sabia me hacia un poco ke a lo mejor te lo tomabas a mal pero no asi...

**Comment by rdany19** [comment]
me banearon en el otro servidor para venir a este y por una broma banearme. La gente se pasa

**Comment by rdany19** [comment]
porfavor dadme otra oportunidad no kiero dejar de jugar a wow joder hay 1000000 de servidores pero kiero jugar en este por el amor de dios ya casi se me saltan las lagrimas.....

**Comment by searum** [comment]
La oportunidad te la di hasta que me dijiste que no tenia huevos 3 veces, a la tercera te fuiste. Como te digo, la proxima vez piensate las cosas antes de hacerlas no tengo culpa de que seas asi y cojas el brazo cuando te dan la mano.

El problema es tuyo y no mio, como te dije antes no queria ni banearte pero al final me cansaste.

**Comment by Kiritoo** [comment]
¿Que tipo de bromas te permito yo? La verdad no me parece bien ese comentario @rdany19 Si me hubieras echo asi a mi tambien hubieras estado baneado..

**Comment by rdany19** [comment]
tienes razon, gracias por todo y para la proxima si llega algun dia habre cambiado. gracias por todo y cuiden a invalid guild name ya ke migro aki del otro servidor.

gracias por todo y mucha suerte con el servidor

**Comment by rdany19** [comment]
almenos desbaneadme la ip ke me levee un pj

**Comment by Dekadencee** [comment]
Cuidadito con las palabras, solo te digo eso... la proxima vez que faltes el respeto te quedas también sin cuenta de github por enterao

**Comment by rdany19** [comment]
tienes razon

**Comment by rdany19** [comment]
aunke la cuenta de github me da igual

**Comment by Dekadencee** [comment]
Anda que menudo cancer tiene la tuya en su familia chico, enserio deja ya de molestar... que no sabes más que ladrar y es que encima sigues insultando, deja a la gente trabajar y olvídanos un poco...

**Comment by Dekadencee** [comment]
No tengo razón no dany, te estas pasando tres pueblos ya...

**Comment by Dekadencee** [comment]
Si has encontrado otro server mejor que este vé a el, yo no te puedo quitar un ban por insultar a mi equipo...

**Comment by rdany19** [comment]
ya borre el mensaje

**Comment by Dekadencee** [comment]
Si, pero nos ha llegado a todos al email y de ahí no se borra... si es que así no vas a ningún sitio y tu lo sabes

**Comment by rdany19** [comment]
pero eske no tienes huevos es un insulto? madre mia como estan las cabezas

**Comment by rdany19** [comment]
no vengais a murcia ke os pegan

**Comment by rdany19** [comment]
lo siento, es la rabia y la impotencia de mis gilipollezes

**Comment by Dekadencee** [comment]
Hombre decirle a una persona que no tiene huevos, bajo mi punto de vista es llamarla "Acojonada" es decir que se achanta fácil, si eso no es un insulto... en cual caso me parece a mí que has dado con la persona menos indicada para decir eso, sin contar de que has estado erre que erre tras los 3 avisos ganándote el ban y supongo que habrá cosas que tanto tú como Searum os habeis ahorrado, tu porque no te interesa decirlo y Searum porque pasa olímpicamente del tema...

Respecto a las amenazas, en fin, como que nos da igual un poco, yo seguiré pisando Murcia y las provincias que me de la gana y te aseguro que no me toca nadie...

En fin @rdany19, tengo trabajo y la verdad que yo no voy a hacer nada respecto a este tema porque el baneo no me corresponde pero yo creo que deberías pulir un poco tu educación a la hora de dirigirte a los demás, se te expulsó de Reign of Darkness Network, pero no se acabó el mundo y mucho menos creo que la familia de la gente que se molesta por que juguéis gratis y esté todo en orden se merezca un cáncer...

Por adelantado te recomiendo que te busques otro servidor, no creo que Searum te retire el baneo, si antes estaba crudo, ahora ya está demasiado complicado, de todas formas cuando se conecte el te dirá supongo.

**Comment by rdany19** [comment]
loooll jajajajaj no digo ke os pegen en murcia eske en murcia halban asi,
madre mia tio

**Comment by rdany19** [comment]
cosas como os pensais ke os decia ke no piseis murcia las sacais de
contexto, pero bueno a lo hecho pecho

**Comment by searum** [comment]
No es suficiente ya con el circo?

**Comment by rdany19** [comment]
si ya basta de pelear por algo que todos sabemos como va ha acabar

2013/9/11 searum notifications@github.com
