### ISSUE TITLE
[Diaria de cocina: Cima del Trueno] Salvado de maíz

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1859]
Buenos días

No es posible llevar a cabo la misión http://es.wowhead.com/quest=29364 ya que al hacer click sobre http://es.wowhead.com/object=208880/granos-de-maiz nuestro personaje se queda golpeando el cuenco cual cavernícola, cuando únicamente deberíamos hacerle click (y esperar el segundo de rigor) y se nos completaría una de las 6 que nos pide.

Adjunto vídeo: http://www.youtube.com/watch?v=AbzUZDUpHNc

Viene de: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/335

**Comment by Kiritoo** [comment]
Sigue sin funcionar?¿

**Comment by paellaencol** [comment]
Sí. De las 15 diarias nuevas de cocina de la horda, es la única que falla

**Comment by Wiinter** [comment]
La he completado hoy. Lleva fixeada una semana. Si no te va prueba de borrar caché.

#335

**Comment by Kiritoo** [comment]
Genial wiint gracias por confirmar es que la arregle el otro día me extrañaba por eso.
Saludos.

**Comment by paellaencol** [comment]
Gracias
Borrar cache wins!
