### ISSUE TITLE
[hechizos] machaque colosal

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1860]
Buenas,

Quisiera pedir el  favor que se revise esta habilidad del war, ya que sumando lo siguiente que resulta en total ser excesivo:

curacion
dps
defensas

No le da a nadie para matar 1 war 1x1. Como dije, tendria yo que usar 3 imposiciones de manos para si quiera llegar a bajarlo un poco.

Por eso les pido que miren el Machaque Colosal y nos informen de eso (suficiente tenemos con el hender armadura :/)... Dice que a los jugadores deberia reducirle la armadura a 50% durante 6 segs. y parece que esta haciendo la misma reducción de 100% a bichos en pjs.
![wowscrnshot_091113_095147](https://f.cloud.github.com/assets/4790547/1123619/64af4a8c-1af2-11e3-8898-0c946cd71983.jpg)

---

Probando con Elmiriox, aqui estan los daños y lo que mi pj aguanta...

![wowscrnshot_091113_101956](https://f.cloud.github.com/assets/4790547/1123877/cf21ce8c-1af5-11e3-82c9-a6d5e3e1a0e1.jpg)

![wowscrnshot_091113_102002](https://f.cloud.github.com/assets/4790547/1123884/e4ff2c5e-1af5-11e3-903f-dcd0a404597e.jpg)

![wowscrnshot_091113_102007](https://f.cloud.github.com/assets/4790547/1123886/e9cb1478-1af5-11e3-9ded-84be6236d895.jpg)

Mi pj

![wowscrnshot_091113_102238](https://f.cloud.github.com/assets/4790547/1123894/08920538-1af6-11e3-8286-de4b7471dd18.jpg)
![wowscrnshot_091113_102237](https://f.cloud.github.com/assets/4790547/1123895/08acf5aa-1af6-11e3-8da2-9e2cc393be6b.jpg)

**Comment by searum** [comment]
si es muy posible, en el 406 tengo el script es cuestion de moverlo y probar :) luego lo hago!

**Comment by lamaza** [comment]
Gracia Fefesito.

**Comment by searum** [comment]
ya deberia de ir bien

**Comment by searum** [comment]
fix
