### ISSUE TITLE
[Guerrero] Aullido Perforador: 12323

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1861]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/996

Actualmente está sacando de sigilo, no se quedó del todo bien.

ID: 1784 , hay que poner que Aullido perforador (ID: 12323) NO saque de sigilo.

**Comment by F4NT4SM4** [comment]
y que cuando un picaro use esfumar se cure media vida con reposicion o en bg se va a comer, arenas esfumar y su heler lo cura completo informaos bien
notas del parche 4.0.6: Sigilo ya no se interrumpe cuando los enemigos usan Grito desmoralizador o Rugido desmoralizador. esto se agrego por el talento del war armas que nos reduce el coste de ira 100% de esos 2 skill pero no dice nada de aullido perforador ya que este cuesta 10 de ira usarlo y no hay ningun talento que lo le reduzca la ira 100%

**Comment by ghost** [comment]
A qué viene eso? lol. Los cry a blizzard que lo diseñó así. En el post que referencio arriba viene toda la "discusión" sobre la spell y se decidió dejarla Blizzlike, ya que es más probable que se hayan equivocado en las notas del parche que en el desarrollo del juego durante todo cata incluído hasta MoP.

**Comment by F4NT4SM4** [comment]
osea basas tu reporte suponiendo que en que blizzard se equivoco en las notas del parche claro....
teneis alguna prueba de que aullidor perforador no deba sacar sigilo?

**Comment by F4NT4SM4** [comment]
Fuente: http://eu.battle.net/wow/es/forum/topic/1549443379
Aullido Perforador saca sigilo ya que no es spameable por que cuesta ira
los otros 2 gritos no cuesta ira por el talento por lo tanto no sakan sigilo por que son spameable

en el otro post que pones searum lo iva a poner como dices por que nadie se molesto en buscar fuente solo con decir que se equivocaron en las notas del parche los de blizzard es suficiente prueba por favor....

**Comment by F4NT4SM4** [comment]
y si no te gusta cry a blizzard yo solo defiendo el war como mi main :c

**Comment by ghost** [comment]
¿Te has molestado en leer eso que tu mismo has puesto antes de llenar el issue de comentarios? Eso que has mandado es una duda de ANTES del parche en el que se decía que, SEGÚN SU INTERPRETACIÓN DE LAS NOTAS, aullido perforador sacaría de sigilo porque no especificaba nada. La realidad es que cuando se aplicó el parche, NO sacaba de sigilo en todo cataclysm.

Toma:

http://www.arenajunkies.com/topic/189827-piercing-howl-doesnt-remove-stealth/

http://www.threadmeters.com/wow/v-22zJ/stealth_not_broken_by_piercing_howl_bug/

http://us.battle.net/wow/en/forum/topic/2065608725

http://us.battle.net/wow/en/forum/topic/2057525832

http://us.battle.net/wow/en/forum/topic/2059015915

En este tendrás que leer menos, sólo el primer comentario:

http://eu.battle.net/wow/en/forum/topic/3888362141

"Will piercing howl break stealth in MoP? 
This mechanic was removed in cataclysm, no reason was given.

I think it's lame that rogues have a guaranteed opener on warriors unless you get lucky with thunder clap or bladestorm."

Espero que ya eso te parezcan suficientes pruebas. Esto no es una guerra de defender clases, si no de arreglarlas, jugamos a un blizzlike.

Ya sabes quien se tiene que informar y a dónde el cry :D

**Comment by searum** [comment]
fix
