### ISSUE TITLE
[Guerrero] Control de inquina

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1862]
Se trata de la habilidad pasiva de la rama de armas. Su descripción dice que proporciona 1 de ira cada 3s mientras estás en combate, pero no funciona. Lo he comprobado porque me quedé en combate una vez y no podía salir del mismo, tenía la ira en 45 y por muchos segundos que pasasen no subía.

No he encontrado la ID puesto que en MoP ya no existe esa habilidad.

Gracias y un saludo.

**Comment by F4NT4SM4** [comment]
id : 12296 me parece que si funciona por lo menos el efecto de 1 de ira cada 3s

**Comment by ghost** [comment]
Vale acabo de comprobarlo otra vez y si funciona... Lo siento, quizás la primera vez que lo comprobé se me bugeo la ira visualmente.
