### ISSUE TITLE
[Mision] Machacando al enemigo

### ISSUE THREAD

**Issue by Huardruid** [RoDNet/Bugtracker-Infinium-4.3.4#1863]
ID de la quest:10078
Link wow head: http://es.wowhead.com/quest=10078/machacando-al-enemigo
Al intentar quemar el lanza cuchillos funciona bien pero cuando lo haces no cuenta para la mision

**Comment by ghost** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/514

**Comment by aerz** [comment]
Gracias asman por fijarte ^^

Fixeado. Un saludo.
