### ISSUE TITLE
[Portal] Teletransporte a Vashj'ir

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1864]
El portal de teletransporte a Vashj'ir de Ventormenta no funciona.

Creo que la spell ligada al portal es esta: http://es.wowhead.com/spell=85040

Un saludo y gracias.

**Comment by Wiinter** [comment]
Has hecho la misión previa del Llamamiento a las Armas de Vash'ir que tienes en el tablón?
Sino la has hecho, esa es la razón por la que no te funciona.

**Comment by ghost** [comment]
Ah, no lo sabía, gracias :D
