### ISSUE TITLE
problemas port ventormenta - huargen 

### ISSUE THREAD

**Issue by basilisk23** [RoDNet/Bugtracker-Infinium-4.3.4#1865]
tengo un huargen lvl 19 (kichimaru)  el cual cuando tomo el portal a ventor llega pero no se ve ningún npc, ni personajes  y ya e terminado todas las misiones de gilneas.
alguna forma de como solucionarlo ??

**Comment by aerz** [comment]
Este no es lugar para quejarse de un problema concreto. Errores como este se solucionan directamente ingame y con la ayuda de los Maestros de Juego conectados.

Escribe un ticket para que te ayuden.

Cierro, un saludo.
