### ISSUE TITLE
Item: Bolsa de cosas brillantes

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1866]
La Bolsa de cosas brillantes http://es.wowhead.com/item=67414 se otorga al jugador como recompensa al realizar cualquier misión diaria de pesca del cataclysm.

El problema de este objeto es que hay ocasiones en las cuales la bolsa no contiene nada.

**Comment by aerz** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/560

Este bug ya fue reportado con mas detalle y solucionado.
Recomendamos siempre utilizar el buscador del bugtracker para buscar si ya fue reportado.

Cierro, un saludo.
