### ISSUE TITLE
[Diaria de pesca: Entrañas] Terror en la charca

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1867]
Pese a que la misión http://es.wowhead.com/quest=29319 no está bug, las probabilidades de pescar un Renacuajo carnívoro gigante http://es.wowhead.com/item=69905#fished-in son bajísimas. He tardado media hora para pescar 8, y lo achaco al azar el hecho que consiguera alguno, ya que mientrastanto he obtenido armas, chatarra, y múltiples objetos de otras misiones (algunos objetos obtenidos son pedidos por otras misiones de pesca).

Adjunto vídeo, donde se observa que las posibilidades de conseguir un "renacuajo" teniendo la misión son cercanas al 100%

http://www.youtube.com/watch?v=mh6tRSCBsZA

P.D. Huelga decir que para hacer las misiones diarias de pesca no hace falta tener un gran nivel de esta profesión, son realizables desde nivel 1

Gracias.

**Comment by redneo** [comment]
Tenia un loot de un 10% SIEMPRE, lo he cambiado a 50% si tienes la misión, acortará los tiempos.
