### ISSUE TITLE
Error Nova de Fuego

### ISSUE THREAD

**Issue by gusnasoto** [RoDNet/Bugtracker-Infinium-4.3.4#187]
Buenas,
Estaba comprobando que al poner totem abrasador, y lanzar la spell
http://es.wowhead.com/spell=1535/nova-de-fuego (nova de fuego) no llega a lanzarla.
Un saludo,
Ungar

**Comment by searum** [comment]
anda leete la descripción de la spell.. eso era en 406 xD
