### ISSUE TITLE
[Guerrero] Ataque de la victoria

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1870]
Ataque de la victoria provoca "Heridas profundas" al guerrero que lo usa.

Ataque de la victoria: http://es.wowhead.com/spell=34428

Heridas profundas: http://es.wowhead.com/spell=115767

No sé si las IDs funcionaran ya que son de MoP.

Un saludo y gracias.

**Comment by F4NT4SM4** [comment]
Si el ataque de victoria es critico un 48% del daño le haces al objetivo con heridas profundas durante 6s

**Comment by ghost** [comment]
No hablo de heridas profundas al objetivo, si no a ti mismo.

**Comment by searum** [comment]
probarlo bien, yo lo he probado y no me aplica nada a mi... :s

**Comment by ghost** [comment]
Me acabo de dar cuenta de que sólo es con críticos. A ver si a vosotros os pasa lo mismo.

**Comment by Kiritoo** [comment]
Es lo que te dijo Fantasma, @byob01 
"Si el ataque de victoria es critico un 48% del daño le haces al objetivo con heridas profundas durante 6s."
Lo que está ocurriendo al parecer es que se está aplicando al guerrero que usa este ataque crítico, lo que no se es si también hace efecto a la criatura-jugador cuando se utiliza.

**Comment by lamaza** [comment]
Si me lo ha hecho , si n un war me lo tira...

**Comment by searum** [comment]
bueno sea lo que sea le puse un check para que no te lo tire a ti y ya esta fix
