### ISSUE TITLE
Mision (Laderas de Trabalomas) apocalipsis pico tormenta

### ISSUE THREAD

**Issue by negrosombra** [RoDNet/Bugtracker-Infinium-4.3.4#1871]
hola soy negrosombra estoy atrancado se supone que deva haber un video que muestra lo que le pasa al pico tormenta.
aqui esta el link http://es.wowhead.com/quest=28616
gracias

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

Parcheada para que la complete cuando la coges
