### ISSUE TITLE
[Mision] (Tanaris) Intentando matar a un puñado de bichos. 24953

### ISSUE THREAD

**Issue by Bariloche123** [RoDNet/Bugtracker-Infinium-4.3.4#1872]
El npc no da el dialogo para montar en la maquina.

**Comment by Kiritoo** [comment]
Enlace de la misión?

**Comment by Bariloche123** [comment]
Para algo deje la id xD    http://es.wowhead.com/quest=24953

**Comment by redneo** [comment]
Arreglado, tiene truco, pero no he logrado hacer que salgan las feromonas...
