### ISSUE TITLE
Intendente de Hijos De Odir Bug (npc=32540)

### ISSUE THREAD

**Issue by 3du42d0** [RoDNet/Bugtracker-Infinium-4.3.4#1873]
Al intendente no le aparecen las monturas del mamut de hielo (item=43958) ni la del Gran mamut de hielo (item=43961) para comprarlas, siendo aún exaltados.

**Comment by Wiinter** [comment]
Aunqe seas exaltado hay qe hacer primero una cadena de misiones previa.

**Comment by redneo** [comment]
Si que las vende, tienes que hacer las misiones para que no te odien, y poder verles.
