### ISSUE TITLE
Error en "El abrazo de una hija"

### ISSUE THREAD

**Issue by ZhorusFoxs** [RoDNet/Bugtracker-Infinium-4.3.4#1876]
la mision no se puede completar debido a que el npc (lillian voss) que deberia de seguirte,no lo hace,nisiquiera aparece,y por eso no se puede completar,anque vallas donde te manden,sin ella,no se termina nunca la mision

**Comment by Kiritoo** [comment]
Está misión la reparé hace dos días voi a comprobarlo.

**Comment by Kiritoo** [comment]
Cierto luego la vuelvo aplicar y añadir enlaces a wowhead!!

**Comment by Kiritoo** [comment]
Fix, falta reiniciar o que se caiga el servidor.
