### ISSUE TITLE
[Profesiones] Descubrimientos de ingeniería

### ISSUE THREAD

**Issue by josselyn** [RoDNet/Bugtracker-Infinium-4.3.4#1878]
Acabo de subir ingeniería a 525 y no tengo ninguno de los descubrimientos que deberían de aprenderse conforme subes la profesión, según esta guía http://www.guiaswow.com/ingenieria/que-son-descubrimientos-ingenieria.html haciendo el machacapollos derrotado tienes un 100% de aprender uno, pero yo ya hice 2 y no me da nada, tambien hice 25 mira de rayos x gnómica que aún esta en amarillo y nada.

Estos son los descubrimientos de ingeniería:

Asesino de cartón: http://es.wowhead.com/spell=84425
Tragamaná Z50: http://www.wowhead.com/spell=82201
Muelles de sinapsis: http://es.wowhead.com/spell=82175
Inyector de sanación: http://es.wowhead.com/spell=82200
Campo de invisibilidad: http://es.wowhead.com/spell=84424
Escudo de plasma: http://es.wowhead.com/spell=84427
Atontador Tazik: http://es.wowhead.com/spell=82180
Placas de desvío: http://es.wowhead.com/spell=82177

**Comment by redneo** [comment]
Spell 60893,
82175,
82175,
82177,
82177,
82177,
82180,
82180,
82180,
82200,
82200,
82200,
82201,
82201,
82201,
84424,
84424,
84424,
84425,
84425,
84425,
84427,
84427,
84427,
94000,
94711,
95215,
95710,
95825 

Que no se enseñaban correctamente, metidos.
