### ISSUE TITLE
[Mision] (Marjal Revolcafango) Limpiar la colina de las brujas

### ISSUE THREAD

**Issue by Bariloche123** [RoDNet/Bugtracker-Infinium-4.3.4#1884]
http://es.wowhead.com/quest=27190
Pongo la antorcha y nada sucede

**Comment by redneo** [comment]
Si que sucede, sale un npc, http://es.wowhead.com/npc=23864, el cual tienes que matar... sale al otro lado del rio.

**Comment by ghost** [comment]
@redneo estoy aquí porque la iba a reportar también. Lo cierto es que el npc que sale no se ve, estará volando por arriba o algo, el caso es que hasta que no crucé al otro lado del rio (y lo hice solo porque leí tu comentario), no pasó nada. A los 2 o 3 segundos tenía la gárgola atacándome.

**Comment by Kiritoo** [comment]
Asman, reporte nuevo, los cerraros estan cerrados.
Crea uno y enlaza, gracias.
Saludos.
