### ISSUE TITLE
[Guerrero] Machaque Colosal

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1886]
ID:http://es.wowhead.com/spell=86346/machaque-colosal

Reduce la Armadura 50% A los jugadores y 100% a los npc
El bug es que esta reduciendo tambien un 50% a los npc y deberia de ser un 100%

![wowscrnshot_091213_165345](https://f.cloud.github.com/assets/3101842/1134985/c57cca1e-1c01-11e3-81a3-1e621d489609.jpg)

**Comment by searum** [comment]
fix
