### ISSUE TITLE
[Glifo - Mago] Polimorfia

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1887]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/835

Funciona bien lo de eliminar DoTs y dejar debuffs. El problema es que cuando se rompe la polimorfia (ID: 118), también está eliminando los DoTs.

Intuyo que ocurrirá igual con Ceguera.

Pasos para reproducirlo:
1. Lanzar polimorfia.
2. Lanzar DoT como bomba viva
3. La polimorfia se romperá por el daño y desaparecerá, pero también lo hará bomba viva.

**Comment by searum** [comment]
fix
