### ISSUE TITLE
[Misión] (Hyjal) Prepping the Soil 

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1888]
Hola queria comentar que está misión sigue sin funcionar, el guardallamas si cuenta como activado pero luego no cuenta como defendido.
He esperado en los 6 guardallamas y nada no cuenta.
Un saludo.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1808

**Comment by redneo** [comment]
A mi si que me ha contado pasados los 60 segundos del bufo que te pone tras activarlo.
