### ISSUE TITLE
[DK] Sabañones

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1889]
Sabañones ID: 50040 
Descripcion Las víctimas de tu enfermedad Fiebre de Escarcha quedan heladas, lo que reduce su velocidad de movimiento un 50% durante 10 s, y tus Cadenas de hielo inmovilizan a los objetivos durante 3 s.

Fiebre de escarcha: 59921
Deberia de relentizar al objetivo con cualquier skill que aplique fiebre de escarcha 

Cadenas de hielo: 45524
al utilizar cadenas de hielo deberia de inmovilizar al objetivo durante 3s como dice el talento

**Comment by searum** [comment]
fix
