### ISSUE TITLE
[hechizo] Flajelo y vapulear Druida

### ISSUE THREAD

**Issue by didiii** [RoDNet/Bugtracker-Infinium-4.3.4#1891]
El caso es que los ataques no hacen ninguna clase de daño, les lanzas y no inflingen daño a nadie
http://es.wowhead.com/spell=48562/flagelo
http://es.wowhead.com/spell=77758/vapulear

**Comment by ghost** [comment]
Sólo una spell o reporte por cada issue. Explica cada hechizo como debería funcionar y la fórmula a ser posible para que puedan fixearlo.

Saludoos!
