### ISSUE TITLE
[Gnomo] Artista del escape

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1892]
Buenas, he visto en otro post que la pasiva racial del gnomo "Artista del escape" estaba bug y no salía en el libro de hechizos.

Supuestamente está arreglado (según el post) pero a mi sigue sin salirme en el libro de hechizos.

http://es.wowhead.com/spell=20589

Un saludo y gracias.

(aquí el susodicho post anterior https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/10 )

**Comment by searum** [comment]
fixxxxxxx :D pero solo es al crear el pj asi que pide por ticket que te lo enseñen :)
