### ISSUE TITLE
[Sacerdote] Alarido psíquico ID: 8122 ha dejado de funcionar

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1893]
Buenas tardes.

Seré escueto, el problema que ocurre con la spell: 8122 es que no funciona, en el registro de combate sale como lanzada pero no afecta a nadie (ni siquiera salta inmune, o resistir, o fallo). Con un poco de suerte de diez alaridos lanzados, igual uno surge efecto. Menciono esto porque a base de probar y desconectarme de casualidad uno surgió efecto, pero solo a un npc, cuando esto es una habilidad de área.

Enlazo con un reporte cerrado de esta habilidad, que se arregló muy bien en su momento, y está bastante mejor explicada y más detalladamente https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1493

Un saludo.

**Comment by searum** [comment]
ya esta fix xD luego lo subo :D es que toquetee los radios de alcance de las spells en general :)

**Comment by paellaencol** [comment]
Gracias. +1 a celeridad

**Comment by searum** [comment]
voy sobrao de haste ya sabes
