### ISSUE TITLE
[Bug global] Áreas

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#1894]
Bueno el caso es que CUALQUIER skill de uso en área no hacen nada tanto daño como debuffs tipo alarido del sacerdote.

**Comment by searum** [comment]
> _< pues dime las ids de CUALQUIER skill 

Ando arreglando cosas internas... y puede que se jodan otras cosas pero si no especificais no se puede arreglar =)
