### ISSUE TITLE
[hechizos] Sello de Verdad

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1896]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1501

No me parece que quedó fix, a menos que me corrijan y me digan que aún no se ha compilado e implementado.

![wowscrnshot_091313_170428](https://f.cloud.github.com/assets/4790547/1141968/ad42af3a-1cc0-11e3-9a2f-22630506a1ae.jpg)

**Comment by searum** [comment]
no se a que te refieres, si es a la censura entonces si que esta fix... teneis que dar un poco de tiempo para que los apliquemos joder que sois unos cagaprisas xd pero acabo de comprobarlo en infinium y en localhost y me funciona perfecto
