### ISSUE TITLE
[hechizos] Sello de Justicia

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1897]
De nuevo reportando este sellito que funciona y luego o funcional mal o deja de funcionar:

Dice que  CON CADA golpe CaC deberia de dejarle lenteado al oponente, es decir, en una pelea contra alguien seria lenteado de manera indefinida si no me interrumpen los golpes ni se activa nada para mejorar el movimiento o evadir el CC.

Lo que pasa es que NO se aplica con CADA golpe Cuerpo a Cuerpo, sino de vez en cuando con los ataques fisico, ni Golpe de Cruzado ni Sentencia lo activan (que antes si lo hacia, al menos Sentencia).

![wowscrnshot_091313_171227](https://f.cloud.github.com/assets/4790547/1142007/990d0410-1cc1-11e3-883a-056704342e06.jpg)

Además, esta haciendo 66.6% (6 dps)de daño sagrado del 100% (9 dps) que deberia hacer.

**Comment by searum** [comment]
Pues estas equivocado. Antes estaba mal, antes lo aplicaba la sentencia (que no es cuerpo a cuerpo) ahora si tiras golpe cruzado, tormenta divina, pegas a melee, etc funciona a la perfeccion.

Sinceramente no se a que viene esto porque antes era cuando estaba bug xd

La sentencia no desata este sello ni lo aplica ni nada de nada de nada :)
