### ISSUE TITLE
[Ulduar] Algalon el Observador

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1898]
Fuimos hasta la sala de Algalon y entramos. Empezó a hablar Brann Barbabronce, entonces apareció Algalon y ahi se acabó el encuentro. Algalon se quedó en medio, como un pasmarote. Él no nos atacaba ni nosotros podíamos a él.

Aqui dejo el link del jefe en cuestión: http://es.wowhead.com/npc=32871

**Comment by efectokoleos** [comment]
arreglado
