### ISSUE TITLE
[hechizos] Golpe de Escarcha

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1899]
http://www.wowhead.com/spell=49143/frost-strike#comments

A mi sinceramente me parece excesivo el daño y no se a que se debe... De hecho esos criticos y daño alto son muy comunes contra el dk frost.

![wowscrnshot_091113_092134](https://f.cloud.github.com/assets/4790547/1142318/05007cb6-1ccb-11e3-81bd-770ca726bc89.jpg)

![wowscrnshot_091113_092150](https://f.cloud.github.com/assets/4790547/1142327/24af7d14-1ccb-11e3-949f-a8a5f2fd59c5.jpg)

**Comment by Kiritoo** [comment]
Este hechizo funciona correctamente, probado sin talentos ni armadura.
