### ISSUE TITLE
Monturas de Brujo

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#190]
Las monturas de brujo se pueden aprender por todos los instructores de brujo  con cualquier clase, por si todavía creían que lo habían visto todo en wow, vean lo siguiente xd

Corcel nefasto: http://es.wowhead.com/spell=23161
Corcel vil: http://es.wowhead.com/spell=5784

![wowscrnshot_070513_134522](https://f.cloud.github.com/assets/4663665/755144/de189350-e5a1-11e2-9903-d7df6275488f.jpg)

**Comment by Velcositro** [comment]
Deberían arreglar esto antes del Rollback, que luego vemos Paladines, Sacerdotes y demás clases no aptas montando estas bestias viles que solo nosotros los brujos podemos dominar.

Pero en serio, es un feo bug que cualquiera pueda usar nuestras monturas exclusivas aunque no dé ninguna ventaja real. Por favor arreglenlo.

**Comment by ghost** [comment]
@Velcositro esta imagen va dedicada a ti xd, por cierto /summon @redneo (había dicho que lo arregló pero el bug sigue ahí como se ve en la imagen que puse ahora, aprendi la montura hoy).
![wowscrnshot_070813_155918](https://f.cloud.github.com/assets/4663665/764496/8d3925d0-e812-11e2-9f30-b3257ef0233f.jpg)

**Comment by Velcositro** [comment]
Gracias XD, bonita imagen, no niego que los sacerdotes de las sombras tienen estilo y les queda bien, pero no cualquiera debería poder domar a estos corceles demoníacos provenientes de Xoroth, seguramente tu sacerdote terminará chamuscado con las marcas de sus cascos (Para el que no entienda: que recibirá una patada del caballo).

**Comment by ghost** [comment]
Jaja xd, claro lo entiendo, a ver si redneo mira el reporte para saber si puede arreglar esto.
