### ISSUE TITLE
[hechizos] Explosion Ahuyante

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1900]
Según Wowhead, la fórmula a mi no me reproduce ese ataque tan alto...

http://es.wowhead.com/spell=49184/explosion-aullante#english-comments

Golpea al objetivo con un viento helado, lo que inflige [(1.16) \* ((450 + (Attack power \* 0.738)))] p. de daño de Escarcha a ese enemigo 

He intentado esto (teniendo en cuenta algún buff o burst): [(1.16) \* ((450 + (15000\* 0.738)))] = 13363.2

Lo de la imagen ni siquiera fue crítico, no se como se maneja este spell, solo me gustaria que lo miraran y me dijeran su punto de vista, gracias.

![wowscrnshot_091113_092208](https://f.cloud.github.com/assets/4790547/1142350/5ca28b66-1ccc-11e3-93f2-7ca361af3ef6.jpg)

No se si es algo general en el DPS de los DK frost o que... Gracias

**Comment by ghost** [comment]
Y también ten en cuenta tu temple... Esa skill esta muy over. Yo he llegado a ver en el recount que el 70% del daño de un DK en una BG es practicamente de explosión aullante.

Lo mejor sería que un DK con el drdamage confirmara la fórmula para la versión 4.3.4 y ver si es correcta.

**Comment by lamaza** [comment]
4 mil de temple tengo. En este momento lo he probado con 1 dk AFUERa de ventormenta, y tanto este poder como el Golpe de Escarcha https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1899, nos parecieron "fix" (5k,7k, 10k, 11k). Pero según me dijo aquel dk, en BG le metian altos dmg. No se si estos spell sean OPeizados en BG o que, hay que mirarlo un poquitin.

**Comment by lamaza** [comment]
Dicen quee tambien puede ser por la acumulacion bugeada y excesiva de Poder de Ataque por varios buff.

**Comment by ghost** [comment]
Si solo ocurre en bg entonces es probable que sea porque se juntan muchas auras...

**Comment by lamaza** [comment]
A mi en bg NADA me esta haciendo pegar esos daños y tambien se me acumulan cosas. Debe ser algo del dk.

**Comment by searum** [comment]
esa formula sacada de wowhead no es valida porque es de mop

**Comment by searum** [comment]
fix
