### ISSUE TITLE
MISION (Tierras del Interior) Pisotear al ritmo

### ISSUE THREAD

**Issue by negrosombra** [RoDNet/Bugtracker-Infinium-4.3.4#1901]
Hola soy negrosombra este es el link de la mision http://es.wowhead.com/quest=26240/pisotear-al-ritmo
se supone que debo darle musica con los tambores a los trol pero el marcador no los cuenta estara bugeado.
podrian repararlo gracias

**Comment by redneo** [comment]
Arreglada, cuando caiga el server tomará efecto.
