### ISSUE TITLE
Equitacion oficial nivel 40

### ISSUE THREAD

**Issue by negrosombra** [RoDNet/Bugtracker-Infinium-4.3.4#1902]
hola soy negrosombra tengo un problema, resulta que ya llege a ser nivel 40 ya aprendi la parte que dice jinete oficial y cuanto quise comprar mi caballo de nivel 40 de esqueleto (http://es.wowhead.com/item=18791) me dice que no puedo porque  si ya tengo el oficial jinete porque?
gracias y espero que lo arreglen

**Comment by ghost** [comment]
Creo que con reloguear se arregla

**Comment by negrosombra** [comment]
tamos ya se resolvio solo gracias

2013/9/13 byob01 notifications@github.com
