### ISSUE TITLE
[Mago] Descarga de pirofrío ID:44614

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1903]
El problema que tiene este hechizo es que al lanzarlo está dejando un dot de daño períodico que ya no debería dejar (lo cambiaron en el parche 4.0.1).

La otra parte de este hechizo, el debuff de efecto de ralentización, sí que funciona perfectamente, pero únicamente debería dejar esto, no un DoT.

Cataclysm Patch 4.0.1 (2010-10-12): No longer causes additional damage over 9 sec.

**Comment by searum** [comment]
fix
