### ISSUE TITLE
[hechizos] Vaina de Luz

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1905]
Hola! ID 53503

Debido a que este spell no funciona, el paladin no tiene poder con hechizos como se debe.

![wowscrnshot_091313_211446](https://f.cloud.github.com/assets/4790547/1142753/e8eb0bf4-1ced-11e3-8080-b13dd72d277d.jpg)

**Comment by searum** [comment]
fixxxx :D
