### ISSUE TITLE
[hechizos] Presura Mental

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1906]
Hola! ID 30814

Debido a que este spell no funciona, el chaman no tiene el poder con hechizos como se debe, además provoca un bug visual, es decir que en los stat te aparece aumentado el poder con hechizos, pero al usar cualquier poder sigue siendo el efecto por el piso, como ir desnudo XD.

![wowscrnshot_091313_211508](https://f.cloud.github.com/assets/4790547/1142759/3324f022-1cee-11e3-9ad2-3087b6339a43.jpg)

**Comment by searum** [comment]
fixxx

**Comment by lamaza** [comment]
Creo que le pusiste picante exxxtra? hehe gracias por los fixes.
