### ISSUE TITLE
[Brujo] Talento Fuego de alma mejorado sigue sin funcionar

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#1907]
El Talento de Fuego de alma del brujo sigue sin funcionar. No salta cuando se usa fuego de alma. No se si es porque aun no se ha aplicado o porque. Os dejo la imagen y en enlace con el antiguo post.

![wowscrnshot_091413_125946](https://f.cloud.github.com/assets/3939699/1143262/e2571550-1d2c-11e3-9e83-e0d301464572.jpg)

Aquí te dejo el enlace al otro post: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1505

Un saludo y gracias

**Comment by ghost** [comment]
ID: 18120 si no me equivoco, cuando vea un lock online lo reviso.

http://cata.openwow.com/spell=18120

**Comment by Wiinter** [comment]
Evil dales marge para que compilen y esas cosillas xD. Me consejo es dejar 4 o 5 días, sino se vuelve a postear.

**Comment by searum** [comment]
he empezado ya las clases y no tengo tanto tiempo como antes, arreglo cosillas pero no subo todo del tiron... lo tengo hecho a la espera de subirlo xD
