### ISSUE TITLE
Otro bug del pala reprension "Largo brazo de la ley"

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#191]
Es otro de los bug que han surgido en el paladin reprension. Este talento te permite que al lanzar la sentencia a mas de 15m de distancia, otorgarte 45% de velocidad de movimiento durante 4 segundos. Actualmente no otorga dicho beneficio.

**Comment by lamaza** [comment]
Gracias por reportar, pero podrias la próxima vez ponerlo en el tema de paladin reprensión , en vez de estar creando tantos temas para lo mismo.

**Comment by lamaza** [comment]
Y si esta otorgando el beneficio, solo que a veces si, y a veces no.

http://old.wowhead.com/spell=87172/largo-brazo-de-la-ley

**Comment by paellaencol** [comment]
Seguro que no funciona? He estado probando al pala un buen rato y siempre le ha saltado.
