### ISSUE TITLE
[Druida feral] Destripar ID: 1079

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1910]
Buenas tardes.

Este DoT del feral, está haciendo aproximadamente el doble de daño. Probado con un feral verde, y con el debuff al mob de "destrozar" (33876) que aumenta los efectos de sangrado un 30% de daño extra. Pues aún así, está haciendo casi el doble, de 3k y poco que debería hacer, está haciendo unos 59xx (esto testeado con 5 puntos de combo lógicamente).

**Comment by paellaencol** [comment]
Probado con 5 puntos de combo, y con otro feral diferente del anterior:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/443/zxik.jpg/'><img src='http://img443.imageshack.us/img443/883/zxik.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img443.imageshack.us/img443/883/zxik.jpg

Lo más señalable:  en mi caso una habilidad (en el supuesto que no hubiese ningun tick critico) que debería hacer 25k, está haciendo 45k.

**Comment by crowel** [comment]
Hola quiero comentar también está habilidad.
Descripción:
![destripar 1](https://f.cloud.github.com/assets/3537253/1145202/03d01420-1dfa-11e3-9a26-e90216eb13cc.jpg)
Como se puede comprobar con 1 punto de daño debe de hacer 3418 daño durante 16 segundos.

Aqui el registro de combate de cada tick de la habilidad durante 16 sec, con 1 punto de combo.
![destripar 2](https://f.cloud.github.com/assets/3537253/1145205/36973104-1dfa-11e3-84a5-bb4e211593ae.jpg)

Como se puede ver en el registro está habilidad está haciendo 4416 de tick normal y 9096 de daño crítico con ¡un solo punto de combo!  Cuando debería de hacer 3418 durante 16 segundos, no cada tick.

Espero que la revisen.

Saludos.

**Comment by searum** [comment]
fix
