### ISSUE TITLE
[Druida feral] Mordedura feroz ID: 22568

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1911]
El problema del remate es que con 5 puntos de combo está haciendo el doble de daño de lo que debería.

ID:22568

He de decir, que hay ocasiones en las que si que hace el daño correcto, pero a veces esta habilidad se sale de madre, y hace mucho más de lo que debería.

**Comment by lamaza** [comment]
http://es.wowhead.com/spell=22568/mordedura-feroz#english-comments

**Comment by paellaencol** [comment]
Esto no es normal, ya no estamos hablando del doble de daño, sino del cuadruple:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/849/gpiy.jpg/'><img src='http://img849.imageshack.us/img849/3341/gpiy.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img849.imageshack.us/img849/3341/gpiy.jpg

100k de daño con equipo verde

**Comment by redneo** [comment]
creo que arreglado, comentadme en uno nuevo.

**Comment by paellaencol** [comment]
Creo que se ha salido aún más de madre
