### ISSUE TITLE
[Druida feral] Arañazo ID: 1822

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1912]
Esta habilidad, tiene el daño un pelín subido. Probado con un druida verde, que debería hacer en torno a 21xx de daño, cuando está haciendo unos 3k.

**Comment by paellaencol** [comment]
Probado con otro druida feral, aún más verde:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/266/qbt7.jpg/'><img src='http://img266.imageshack.us/img266/6034/qbt7.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img266.imageshack.us/img266/6034/qbt7.jpg

**Comment by crowel** [comment]
Arañazo lo veo muy subido.
Con mi druida pego entre 7k golpe normal y 14k crítico al dummy.
En la descripción del hechizo me dice que debo pegar solo 1542 daño de sangrado.
![araazo](https://f.cloud.github.com/assets/3537253/1145189/fa8d1850-1df8-11e3-9b88-b96c0c8efcdd.jpg)

Bien ahora nos vamos fijar en la 2ª parte de la habilidad.
"más 7709 de daño de sangrado extra durante 15 sec otorga un punto de combo"

Esto esta fatal si debo pegar esa cantidad durante los 15 sec, actualmente estoy dando 3133 cada 4 sec que golpea el tic, 4 golpes de 3133 un total de 12532 cuando deberia golpear 7709.

Espero que esto sirva.

Un saludo.

**Comment by redneo** [comment]
Arreglado

**Comment by paellaencol** [comment]
El daño inicial está arreglado, pero los dots siguen pegando de más igual que antes.
