### ISSUE TITLE
[DK] Peste de sangre (spell=55078)

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#1915]
Proporciona un daño de 178p. [+ 15.8% de tu poder de ataque] de daño de las Sombras cada 3 s... Cosa que como la otra no se realiza en efecto ni teniendo el talento de 30% de enfermedades aumentado.

**Comment by searum** [comment]
fix, lo del talento es cosa a parte reportalo a parte please ^^
