### ISSUE TITLE
[DK] Golpe purulento: (spell=85948)

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#1916]
Un ataque instantáneo que inflige un 200% de daño con arma más 487 p. y aumenta la duración de tus efectos Peste de sangre, Fiebre de Escarcha y Cadenas de hielo en el objetivo hasta 6 s.... El bug es que este ataque no extiende la duración de ninguna de las habilidades mencionadas.

**Comment by searum** [comment]
fix
