### ISSUE TITLE
[DK] Levantar muerto: (spell=46584)

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#1918]
El daño de la mascota es mínimo,ni con grifo de necrofago que aumenta su aguante y su fuerza el 15% de la que posea el dk,ni mucho menos cuando se usa Transformación oscura aumenta, saca a un enemigo Player,mod,boss entre 200 y 300 de daño.

**Comment by searum** [comment]
No tiene nada que ver la spell con la pet. El daño en general de las mascotas debe de ser revisado y abrire un label de issues solo para pets.

Cierro porque esto sinceramente aqui no pinta nada y esta mal descrito ya que una pet no es una spell ni mucho menos ^^
