### ISSUE TITLE
[Banda - Boss] Baradín 10 n

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#192]
Pequeña prueba de Bastión de Baradín

---1er boss (Occu´thar)
http://es.wowhead.com/npc=52363

No hace nada, osea permanece quieto para recibir dps.

Se le puede poner cualquier estado (como si fuera humanoide), incluso ahuyentar el mal(sale caminando por ahi con fear) de los paladines, arrepentimiento y stun.

El loot (botín) me parece que esta mal tambien, nos dió mas de 4 items épicos de gladiador (temp. 10).

------2do boss (Alizabal)
http://es.wowhead.com/npc=55869

El bug mas notable  esta en sus habilidades, las usa sin algún orden, ni periodicidad establecida. Por ejemplo la danza de las espadas que hace queda como ataque "básico" despues del primer uso y se queda haciendo eso hasta que morimos.

Ootro de sus ataques, que hace apróximadamente 80% daño del total de la salud del que sea marcado, deberia repartirse entre los miembros cercanos de la banda, pero no es asi, y le pega el mismo daño a cada pj, osea Wipe.

Otro bug que encontré , es que al tener el agro y hacer que me siga por la estancia (probando el nuevo sist. mapeo), el boss me seguia, pero en el punto medio donde hay como un round point, si me alejo rapido, el boss no sabe dar la vuelta y se queda mirandome a lo lejos, aunque si me acerco al boss lo suficiente, este aprende a dar la vuelta.

No lo pudimos matar por el DPS tan exagerado y desscontrolado que hacia.

--------el 3er boss (Argaloth) 
http://es.wowhead.com/npc=47120

Este no esta usando correctamente las habilidades ( en 4.0.6 si lo estaban):
La lluvia de meteoros no esta bien.

Su ataque básico es de 13k, deberia ser mayor, lo he "tankeado" en mi paladin reprensión.

---

Agrego este tema para que no se les olvide.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/181

**Comment by lamaza** [comment]
Sobre Argaloth, agrego que No usa la otra habilidad "Tajo meteórico"
Sobre el loot, es correcto que siga dando items de gladiador sañoso (Temp. 9), eso para que nos sirve...?

En pocas `palabras, hay que revisar completamente la estancia y los boss sobretodo, 1 x 1.

**Comment by crowel** [comment]
Pues si leveas y todavia no tienes equipo, te tira sañoso y t11 que te viene muy bien recien llegado al 85 mas los puntos.

**Comment by lamaza** [comment]
Hola crowel, en 85 podemos usar Por ejm: mediante herreria el set de pirium sañoso...

El loot en sí es acertado, solo que mi comentario iba por el lado de la opinión general, de que debieron actualizar el boss XD.

**Comment by sherik12** [comment]
Lmaza si revizas la guia de mazmorras hecha por Blizzard te daras cuenta que el lot esta bien, segura dando t9 y t11 xD

**Comment by lamaza** [comment]
-1 haha

De todas maneras, sigamos probando, que la estancia la implementaron hoy, y ya ven los bugs que hay... Quien sabe si más.

**Comment by efectokoleos** [comment]
el boss argaloth esta arreglado al 100%, cierro y ya posteais cuando implementemos los otros 2 bosses
