### ISSUE TITLE
[DK] Venganza: (spell=93099) 

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#1923]
Un bug al cambiar de talentos primarios a secundarios o viceversa:

Cada vez que recibes daño, ganas un 2% del daño no mitigado como poder de ataque durante 20 s... Puedes cambiar talentos de sangre a escarcha y se mantiene ese buf.

**Comment by F4NT4SM4** [comment]
al recibir daño creo que se quita el buf

**Comment by searum** [comment]
fix
