### ISSUE TITLE
[Mazmorra] Castillo Colmilloscuro

### ISSUE THREAD

**Issue by redneo** [RoDNet/Bugtracker-Infinium-4.3.4#1927]
Tras matar al npc http://es.wowhead.com/npc=46963 Se tendría que abrir la puerta que hay en esa misma sala y la siguiente antes del último jefe. Ahora mismo no lo hace, lo puse que se pudieran clickear.

Las puertas que tendria que abrir son: 18971 y  18972

El último boss http://es.wowhead.com/npc=46964 Cuando muere, hace que tire el servidor.

**Comment by paellaencol** [comment]
Enlazo desde un problema previo que tuvimos respecto a la última puerta:
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1394
