### ISSUE TITLE
[Montura Fenix Oscuro]

### ISSUE THREAD

**Issue by Birrita** [RoDNet/Bugtracker-Infinium-4.3.4#1928]
Hola, mi problema es que ayer mirando de curioso q hay en la tienda de hermandad...descubro que por 2.7k se podia comprar la montura del Fenix Oscuro...no pedia ningun otro reqisito que el oro y ser Artesano jinete...tenia ambas cosas y dije...lo compro...

En sintesis no lo deja usar...lo podes "tomar" aparece con las demas monturas pero no te deja usarlo de montura...mi duda es...lo podre usar? me devuelven el oro? se puede hacer algo?
 la cuenta es: Paravicear
nick de pj : Cerveza

Desde ya muchas gracias

**Comment by aerz** [comment]
Doble reporte, cierro este mas antiguo.
