### ISSUE TITLE
[Montura Fenix Oscuro]

### ISSUE THREAD

**Issue by Birrita** [RoDNet/Bugtracker-Infinium-4.3.4#1929]
Perdon, no sabia q habia q poner en una categoria...xD creo qe aqui corresponde..

Hola, mi problema es que ayer mirando de curioso q hay en la tienda de hermandad...descubro que por 2.7k se podia comprar la montura del Fenix Oscuro...no pedia ningun otro reqisito que el oro y ser Artesano jinete...tenia ambas cosas y dije...lo compro...

En sintesis no lo deja usar...lo podes "tomar" aparece con las demas monturas pero no te deja usarlo de montura...mi duda es...lo podre usar? me devuelven el oro? se puede hacer algo?
 la cuenta es: Paravicear
nick de pj : Cerveza

Desde ya muchas gracias

**Comment by lamaza** [comment]
Más bien como dije antes, el bug de http://es.wowhead.com/item=63125 es que lo puedas comprar sin tener el logro de hermandad http://es.wowhead.com/achievement=4988  ni ser exaltado con la hermandad... Mi guild es de nivel bajo (5 o 6) y todo nos ha pedido requisito hasta ahora.
