### ISSUE TITLE
Sacerdote

### ISSUE THREAD

**Issue by sherik12** [RoDNet/Bugtracker-Infinium-4.3.4#193]
Disciplina: 
Alma debilitada: no desaparece en ocaciones, lo que provoca que no se puede utilizar de nuevo palabra de poer:escudo. Id 6788
Maestria: sale aprendida pero no funnciona: 86475

**Comment by paellaencol** [comment]
Si llevas el talento "Fuerza del alma" se buguea "Alma debilitada" y no desaparece

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/41

**Comment by searum** [comment]
fix
