### ISSUE TITLE
[Buscador de mazmorras] recompensas

### ISSUE THREAD

**Issue by redneo** [RoDNet/Bugtracker-Infinium-4.3.4#1931]
Cuando usas el buscador de mazmorras y haces la mazmorra, no da la recompensa que deveria, no da nada.

Lo he probado con mazmorra normal cata (140 puntos de justicia y oro), nos salio el nucleo petreo, matamos a todos, y no dio recompensa ninguna.

Un saludo

**Comment by Wiinter** [comment]
Con las mazmorras heroicas tampoco da la recompensa de puntos de valor

**Comment by Dekadencee** [comment]
Fixeado

**Comment by Wiinter** [comment]
Sigue sin darlo correctamente
