### ISSUE TITLE
[Misión] Las Cadenas de Anub'ar

### ISSUE THREAD

**Issue by deswolfdaza** [RoDNet/Bugtracker-Infinium-4.3.4#1934]
http://es.wowhead.com/quest=12064/las-cadenas-de-los-anubar

son 3 fragmentos de llaves Anok'ra, Tivax y Sinok

logro conseguir 2 fragmentos solamente, ya q el mob anok'ra no lo encuentro (Tivax esta dos veces)

estan dentro de las 3 chozas grandes (creo q deberia ser una para cada uno) pero tivax esta en dos de ellas

**Comment by Kiritoo** [comment]
Que no lo encuentres no significa que no este.
Tivax esta dos veces como se ve en wowhead.
Si te fijas bien y buscas bien lo encontraras.
Saludos.
