### ISSUE TITLE
[Druida feral] Triturar ID: 5221

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1935]
Buenas noches.

Esta habilidad como algunas otras del druida feral tiene el daño aumentado, está haciendo más de lo que debería:

-Imagen usada sin efectos de sangrado previos:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/571/sku4.jpg/'><img src='http://img571.imageshack.us/img571/6660/sku4.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img571.imageshack.us/img571/6660/sku4.jpg

-Imagen usada con efectos de sangrado sobre el objetivo:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/196/r4rv.jpg/'><img src='http://img196.imageshack.us/img196/7849/r4rv.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img196.imageshack.us/img196/7849/r4rv.jpg

Y como se puede observar, en ambas imágenes está haciendo un daño notablemente superior a la media.

Gracias

**Comment by searum** [comment]
mmmm hace aproximadamente 1k5 de daño mas del que pone en el DrDamage... pero es que esta tirando con la formula correcta de blizz asi que no se si fiarme del DrDamage en este caso o no =)

**Comment by Kiritoo** [comment]
Estoy comprobando sin armadura ni talentos y el daño no está aumentado.
