### ISSUE TITLE
[Druida restauración] Desenredo ID: 96429

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1936]
Aunque esta habilidad pasiva sí que está funcionando como debe, sólo debería funcionar para los druidas en la rama de talentos de restauración.

El problema es que los druidas ferales, aunque no tienen esta habilidad pasiva en el libro de hechizos (lógicamente), les está funcionando como si fueran healers. 

Esta habilidad es exclusiva de los healers, ningún otro tipo de druida debe poder eliminar los efectos de frenado o raices simplemente cambiando de forma.

**Comment by ghost** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1798

**Comment by searum** [comment]
okEY fallo mio q no lo subi pero lo tenia fixeado jajaja
