### ISSUE TITLE
Rey exánime

### ISSUE THREAD

**Issue by xhide86** [RoDNet/Bugtracker-Infinium-4.3.4#1938]
Muy buenas tengo que terminar la quest "el ojo de Acherus" hablando con el Rey Exánime y no se puede.

![wowscrnshot_091513_112550](https://f.cloud.github.com/assets/5238456/1145021/6aaaa144-1de9-11e3-8386-eede02579132.jpg)

**Comment by Kiritoo** [comment]
Esta misión va perfectamente nose que hiciste.
Dejala y vuelve a hacerla, saludos.
