### ISSUE TITLE
Misión (Las Cumbres Tormentosas) "La última de su raza"

### ISSUE THREAD

**Issue by karmmero** [RoDNet/Bugtracker-Infinium-4.3.4#1939]
En esta misión hay que montarse en una Matriarca Faucehielo Herida, pero al llegar al final del recorrido desaparece y no permite completar la misión.

![wowscrnshot_091513_115052](https://f.cloud.github.com/assets/5354896/1145040/60578ed4-1dec-11e3-8079-7d8e1e82c861.jpg)

**Comment by Kiritoo** [comment]
Y el enlace de la misión?

**Comment by didiii** [comment]
Lo reporte yo hace unos días  y me dijo el gm que a el le funcionaba pero llevo probando vsrios días y no funciona.
Aqui te dejo el enlace de la mision http://es.wowhead.com/quest=12983/la-ultima-de-su-raza

**Comment by redneo** [comment]
arreglada
