### ISSUE TITLE
[Buscador de mazmorras] Volar

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#194]
Si estas en una montura voladora y entras dentro de una mazmorra mediante buscador de mazmorras puedes volar sin montura, cual buguero con un flyhack.

**Comment by lamaza** [comment]
Deberias poner un video o imagenes, ya que no hay ID de algo verificable.

**Comment by Wiinter** [comment]
Yo creo qe no hace falta video, y se puede verificar si lo comprueba uno mismo.

**Comment by lamaza** [comment]
Mas que nada las pruebas son para ayudar a los gms, recuerda que no están arreglando 1 par de cositas verificables, sino cientos, y no faltan los que vienen a reportar cualquier cosa. Bueno ya sabes el por qué.Tambien creo que falta mas información para reproducir el bug... Digo, por si acaso:

Si pasa en todas las mazmorras
El lvl de tu pj
Que tipo de busqueda de mazmorra iniciaste

**Comment by lamaza** [comment]
Y si solo es por buscador o de cualquier forma de ingreso a mazmorra (portal, cajón, invocación grupal, yendo solo o en compañia etc.)

**Comment by Dekadencee** [comment]
Fixed
