### ISSUE TITLE
[Clases:Druida] Magullar

### ISSUE THREAD

**Issue by Savian123** [RoDNet/Bugtracker-Infinium-4.3.4#1940]
Bueno como viene a saberse el druida feral esta bug... en daño sobretodo en gato lo que ami no me importa mucho ya que yo siempre he preferido el oso y lo uso mas en PvE que en PvP , resulta que una de las habilidades de aggro del oso esta bug... como dice el titulo es Magullar.

![magullar2](https://f.cloud.github.com/assets/4934124/1145379/ef9ac1c6-1e0d-11e3-9e55-87c5796efe2b.JPG)

En la anterior imagen se ve el daño real que hace , incluso con cargas de lacerar en el objetivo 

![magullar](https://f.cloud.github.com/assets/4934124/1145382/0c20e2bc-1e0e-11e3-9c8d-cbe894cbef97.JPG)

Este es el daño que debería hacer mínimo sin sangrado

Si os puede ayudar... 

http://db.mmo-champion.com/s/6807/maul/

**Comment by Wiinter** [comment]
Lo que necesitan sobretodo es la id del hechizo, en este caso magullar.

**Comment by Kiritoo** [comment]
Más que la id nos vendría bien que se pusieran los enlaces para muchas veces leer las descripciones o el funcionamiento de los mismos y no tener que buscar nosotros.

**Comment by lamaza** [comment]
http://es.wowhead.com/spell=6807/magullar
http://es.wow.wikia.com/wiki/Magullar
http://foros.therealfiction.com/showthread.php/2074-6807-Magullar

**Comment by searum** [comment]
fix
