### ISSUE TITLE
[Druida feral] Mordedura feroz ID: 22568

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1941]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1911

Hola vuelvo a abrir el issue de este hechizo reparado hace un rato.

Esta pegando aun más que antes.
Con 2 puntos de combo debería pegar 3953-4260 de daño segun la descripción.
Acabo de pegar con mi druida con 2 puntos de combo 16k de normal y 32k crítico esto es una sobrada.

Un saludo.

**Comment by ghost** [comment]
Hombre, a mi esto no me parece muy normal: http://oi41.tinypic.com/98r05e.jpg

60k en total

**Comment by searum** [comment]
lo he "nerfeado" temporalmente, es decir no es la formula correcta 100% pero se acerca demasiado (o eso me parecio).

Tratare de fixearlo bien bien pero de momento para que no se metan esas burradas lo subo asi y cierro que ya conozco el bug :)

**Comment by lamaza** [comment]
Searum Gracias por lo que haces y gracias al staff por manejar las cosas tan bien y sobre todo la igualdad en el juego.
