### ISSUE TITLE
[Druida feral] Arañazo ID: 1822

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1942]
Buenos días.

Viene de aquí: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1912

El daño instantáneo al utilizar arañazo ya está corregido, pero sigue fallando la segunda parte, los dots posteriores que deja utilizar está habilidad.

**Comment by searum** [comment]
Lo he bajado un poco de momento pero no cierro porque no se bien cuanto debe de hacer.. A ver vosotros que jugais si me ayudais a dejarlo bien ^^

**Comment by paellaencol** [comment]
:S El daño inicial sigue bien, pero ahora se ha quedado los dots algo bajos, en torno a un 40% de lo que debería hacer. Con 10600 de ap debería hacer 2k de daño periódico.

De todas maneras que escriba alguien más aquí y comente la situación

**Comment by searum** [comment]
claro a ver, yo lo he bajado para que no lloreis en pvp XD acabo de decirloo! necesito que me echeis un cable para sacar cuanto tiene que ser exactamente no para que sigais llorando >_<

**Comment by ghost** [comment]
@searum  Fórmulas:

AP \* 0.147 + 56 daño de tipo sangrado y un daño adicional de sangrado de 56 \* 3 + AP \* 0.441 durante 9 segundos. Da un punto de combo.

http://wow.freakz.ro/spells.php?spell=1822

**Comment by Kiritoo** [comment]
Ajustados los dots de arañazo al daño correcto que deben hacer.
