### ISSUE TITLE
[Druida feral] Destrozar ID: 33876

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1943]
La habilidad destrozar del druida feral también está haciendo más daño del que debería:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/826/goxm.jpg/'><img src='http://img826.imageshack.us/img826/1746/goxm.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img826.imageshack.us/img826/1746/goxm.jpg

14k el crítico, y 7k el normal estoy haciendo con este druida, cuando debería moverse en unos números más bajos con esta habilidad

**Comment by searum** [comment]
fix
