### ISSUE TITLE
[Druida feral] Flagelo ID:62078

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1944]
La habilidad flagelo inflinge un 340% de daño a los enemigos cercanos.

Utilizado sin llevar arma alguna, hace más daño de lo que debe:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/15/whlu.jpg/'><img src='http://img15.imageshack.us/img15/2139/whlu.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img15.imageshack.us/img15/2139/whlu.jpg

Esta vez empuñando un bastón:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/837/kztr.jpg/'><img src='http://img837.imageshack.us/img837/5700/kztr.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img837.imageshack.us/img837/5700/kztr.jpg

En ambos ejemplos se observa que hace más daño de lo que debería.

**Comment by Kiritoo** [comment]
Acabo de probarlo sin armadura y va perfecto, a continuación con un bastón y también funciona bien.
