### ISSUE TITLE
Poder de ataque

### ISSUE THREAD

**Issue by bagnamar** [RoDNet/Bugtracker-Infinium-4.3.4#1945]
El poder de ataque que se consigue de manera directa de objetos o enchants no se aplica, es decir, pongamos que tengo 100 ap y me equipo un item que me de 50 ap de manera directa seguire teniendo 100ap.

En la primera imagen se puede ver mi ap con un amuleto que debe otorgar 42ap, en la segunda se ve que sin el amuleto mi ap no varia, es decir el amuleto no da ap.
![wowscrnshot_091413_152242](https://f.cloud.github.com/assets/5291731/1145779/f20540fc-1e2c-11e3-837c-be20a30738fd.jpg)
![wowscrnshot_091413_152253](https://f.cloud.github.com/assets/5291731/1145780/09704804-1e2d-11e3-9bf4-56348207ca4a.jpg)

En estas imagenes se puede ver que el ap otorgado de manera directa por enchants tampoco se aplica, solo varia el ap otorgado mediante la fuerza (362x2=724)
8732-724=8008
![wowscrnshot_091513_192432](https://f.cloud.github.com/assets/5291731/1145762/e7f6cc62-1e2b-11e3-96ec-f8f8cd239bd5.jpg)
![wowscrnshot_091513_192438](https://f.cloud.github.com/assets/5291731/1145763/f4adff48-1e2b-11e3-81ca-9dcfcbf6b6cc.jpg)

**Comment by searum** [comment]
fix
