### ISSUE TITLE
[Paladín] Palabra de gloria

### ISSUE THREAD

**Issue by bagnamar** [RoDNet/Bugtracker-Infinium-4.3.4#1948]
Este hechizo (ID: 85673) debe curar según las cargas de poder sagrado que tenga el paladín en ese momento.

El problema es que cura lo mismo con equipo (ap) que sin él, cuando según la descripción misma deberia curar mas, esto con equipo sp no pasa, es decir cura lo que pone en la descripción. Imagino que le pasa lo mismo que le pasaba a exorcismo.
![wowscrnshot_091413_091006](https://f.cloud.github.com/assets/5291731/1145856/a3b3038e-1e32-11e3-9f23-e1bb8ca9049e.jpg)
![wowscrnshot_091413_091237](https://f.cloud.github.com/assets/5291731/1145857/b777ae56-1e32-11e3-867b-d6b1d7b2ba21.jpg)

**Comment by searum** [comment]
fix
