### ISSUE TITLE
[Paladín] Martillo de cólera.

### ISSUE THREAD

**Issue by bagnamar** [RoDNet/Bugtracker-Infinium-4.3.4#1949]
Este hechizo (ID: 24275) causa un daño considerable a objetivos con menos de 20% de vida o mientras este activa cólera vengativa (ID: 31884) siempre que se haya invertido un punto en el talento cólera santificada (ID: 53375).

El problema es: el daño infligido por el ataque sin llevar nada de equipo es similar al que da en la descripcón del hechizo pero cuando llevas equipo ap (con sp no pasa) pega aproximadamente 1k mas de lo que pegaba sin equipo, cuando deberia pegar bastante mas segun la descripción misma. Este bug es similar a lo que le pasaba a exorcismo.
![wowscrnshot_091413_100411](https://f.cloud.github.com/assets/5291731/1145887/db8a157a-1e34-11e3-9d8e-aae7f82d77fa.jpg)
![wowscrnshot_091413_100659](https://f.cloud.github.com/assets/5291731/1145891/0714f764-1e35-11e3-9260-0b1dc4325c5c.jpg)

**Comment by searum** [comment]
fix
