### ISSUE TITLE
Portales Tierras Altas Crepusculares

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#195]
Según wowwiki, debería de haber un portal para volver a Orgrimmar en Puerto Faucedraco y un portal para volver a Ventormenta en Bancalto, claro después de completar la cadena de misiones... pero como estan bug y hay otras prioridades, no creo que haga mal que se puedan usar sin haberlas completado :)

http://www.wowpedia.org/Twilight_Highlands

"The portals to and from Twilight Highlands unlock after players complete a short quest chain after reaching the Twilight Highlands, concluding with The Way is Open for the Alliance in Highbank and Traitor's Bait for the Horde in Orgrimmar."

**Comment by lamaza** [comment]
Creo que esto tambien tiene que ver con que ya no hay portales en Dalarán. Ya todo se hará con montura voladora, seria como pedir portales de las capitales en Feralas, Cuna del Invierno, Darnasus, Bahia del Botín, etc etc. Ya volvemos a usar las capitales y además de eso, las monturas y los portales de los magos, es por eso que no aparecen mas portales que los debidos.

**Comment by ghost** [comment]
????? Tierras altas crepusculares es una zona Cataclysm....

**Comment by lamaza** [comment]
No hay portal a capitales desde las "nuevas zonas de cataclysm", porque son zonas que ya no importan (históricamente) en este parche como tal. Es una modificación hecha como preparación para MoP. Deberias revisar las notas de cada parche , donde y por qué quitaron portales... No es algo bugeado. E insisto, los quitaron (presiento) por la misma razón que los de Dalarán a otros lugares.

Parche 4.1.0

-Se han vuelto a abrir los portales para ir a las capitales en Dalaran y en la Ciudad de Shattrath.

Y si aún no esta claro, pasate por 

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/144

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/38

**Comment by ghost** [comment]
> Deberias revisar las notas de cada parche , donde y por qué quitaron portales...

Para mi si esta clarisimo, mostras reportes e información sobre Dalaran. Ya puse información de Wow wiki y en otro reporte puse un comentario de los foros de blizz donde dice que SI hay portal para ir a Orgrimmar y Ventormenta en Tierras Altas Crepusculares e Infralar.

Te lo pongo aquí para que lo veas (por cierto el post es del 2011 cuando el ofi estaba en cata todavía).

http://us.battle.net/wow/en/forum/topic/2140184275

"There is no portal back to Orgrimmar or Stormwind from Uldum, and there is none back from Hyjal or Vashj'ir; portals back are from Deepholme, Twilight Highlands, and Tol Barad, and Hellfire Peninsula next to the dark portal."

Si puedes dejar algún enlace que confirme lo que dices, (sobre las zonas que te acabo de mencionar), sería bueno que lo pongas, y por si acaso ya busque aquí y nada de lo que dices sobre zonas cata esta http://eu.battle.net/wow/es/game/patch-notes/4-3

**Comment by lamaza** [comment]
El portal deberia desbloquearse al terminar la cadena de misiones http://www.wowhead.com/quest=27341

Hasta que punto se puede llegar en la cadena?.

**Comment by lamaza** [comment]
Y perdon lo otro =)

**Comment by ghost** [comment]
Para Tierras Altas, la cadena llega a una misión en Bahía de Pantoque que esta bug, y ya no se puede seguir http://es.wowhead.com/quest=26337 u.u

**Comment by lamaza** [comment]
En el lado Alianza (supongo que tambien horda), la cadena llega hasta la misión "Las raices la curaran", debido al bug general en el server de que no se ve ningún item en el suelo que necesite ser recolectado por misiones:

http://es.wowhead.com/quest=27515

Supongo que cuando monten dicha información de items faltantes, se podrá continuar la cadena y obtener el portal sin problemas.

Por otro lado yo pregunto... Estas haciendo las misiones para el lado horda, que cadena estas haciendo? Pregunto esto, ya que la que yo comencé (Alianza), transcurre totalmente en TACrep, y te veo en otro lado y no entiendo mucho por qué XD.

**Comment by ghost** [comment]
Hago la cadena de misiones para ir a Tierras altas, que se agarra en el cartel, como dije arriba, me quede en esta misión http://es.wowhead.com/quest=26337, el npc no funciona para atacarle.
Para ir a tierras altas las cadenas de misiones de la horda y de la alianza son distintas.

Me ves en el otro lado? o.O por cierto, no se que es TACrep xd.

**Comment by lamaza** [comment]
Osea que debes hacer doble portal...
Yo en Ali hice la cadena completa hace 1 semana y desbloqueé bien el portal a las T. A. Crepusculares. 
Hoy inicié la cadena para sacar el portal de TACrep a Ventor pero no pude por el error mencionado. Lo que tu tienes es 1 misión bug, y no que el portal este bug. Xd

**Comment by redneo** [comment]
Puestos los portales, se pueden usar sin necesidad de haber completado la cadena.... por ahora

**Comment by ghost** [comment]
@redneo muchas gracias redneo :D
