### ISSUE TITLE
[Paladín] Consagración

### ISSUE THREAD

**Issue by bagnamar** [RoDNet/Bugtracker-Infinium-4.3.4#1950]
Este hechizo (ID: 26573) crea un área justo debajo del paladín que daña a los enemigos durante 12 segundos.
El problema es que al terminar esos primeros 12 segundos vuelve a aparecer otra área de 12 segundos como si se hubiera lanzado el hechizo de nuevo.

Pd: el hechizo tiene 25 segundos de cd

**Comment by searum** [comment]
segun tengo entendido son 10 segundos no 12 y ya esta fix.

**Comment by bagnamar** [comment]
Cuando estaba escribiendo me pareció ver 12  pero tienes razón son 10 segundos, perdona la confusión i gracias por los arreglos x)
