### ISSUE TITLE
[Paladín represión] Guardián de los antiguos reyes.

### ISSUE THREAD

**Issue by bagnamar** [RoDNet/Bugtracker-Infinium-4.3.4#1951]
Este hechizo (ID: 86150) funciona de manera distinta segun la especialización de talentos que se haya escogido.

El de represión invoca al guardián durante 30 segundos, mientras esté activo cada ataque del paladín (hechizos incuidos) y del guardián dan al paladín una acumulación de poder antiguo (ID: 86700) cada acumulación de estas aumentan la fuerza total del paladín 1%, cuando pasan los 30 segundos o matan al guardián se libera furia antigua (pongo la ID con el enlace a wowhead nose si es correcta http://es.wowhead.com/spell=86704/furia-antigua) que inflige daño por cada acumulación de poder antiguo, dividiendo este daño entre los objetivos a 10 metros del guardián.

El problema es que los ataques del paladín no dan ninguna acumalación de poder antiguo haciendo que como maximo sólo se puedan llegar a unas 13 acumulaciones (con los ataques del guardián).

Otro problema es que los ataques del guardián están infligiendo 1 de daño, estos ataques deben tener un daño aproximado de unos 2k.

**Comment by lamaza** [comment]
![wowscrnshot_092113_181526](https://f.cloud.github.com/assets/4790547/1186656/f00f8456-2313-11e3-88ee-7f501c0bbbc7.jpg)
