### ISSUE TITLE
[Pícaro] Bomba de humo: 76577

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1952]
Actualmente no está sacando de sigilo a los enemigos. Funciona bien el resto, sólo hay que añadir que al recibir el debuff de la bomba de humo, saque de sigilo a los enemigos que estén dentro de la zona de la bomba, tanto cuando el pícaro lanza la bomba y estaban dentro del radio, o cuando existe la bomba y otro enemigo entra en sigilo.

http://www.wowhead.com/spell=76577/smoke-bomb#comments

**Comment by Kiritoo** [comment]
Fix

**Comment by Kiritoo** [comment]
Reabro, toca meterlo por core para especificar solo los enemigos.

**Comment by ghost** [comment]
Exacto, esta afectando tanto a enemigos como a amigos e incluso al propio pícaro. Además, se queda el debufo de bomba de humo aunque no estés dentro.

**Comment by searum** [comment]
fix
