### ISSUE TITLE
[Paladín represión] Maestría (mano de luz)

### ISSUE THREAD

**Issue by bagnamar** [RoDNet/Bugtracker-Infinium-4.3.4#1953]
La maestria del paladín represión hace que golpe del cruzado (ID: 35395), tormenta divina (ID:53385) y veredicto del templario (ID:85256) peguen un % del daño infligido como daño sagrado extra.
El problema esta en que con "x" cantidad de maestria debe infligir un % determinado:

En la imagen se ve que con 9,98 puntos de maestría, el daño extra (mano de luz) debe ser un 21% del daño de golpe cruzado, si nos fijamos se ve como golpe cruzado ha hecho un daño de 10.700, y mano de luz hace un daño de 209, un 1,95% del daño infligido por golpe cruzado.
![wowscrnshot_091513_030557](https://f.cloud.github.com/assets/5291731/1146029/47377da2-1e40-11e3-859a-362670b2d200.jpg)

En la siguiente imagen i la misma maestría, por lo tanto 21% de daño extra vemos como tormenta divina ha hecho un daño de 20920 en total mientras la maestría hace 501 de daño, un 2,4% del daño infligido por tormenta divina
![wowscrnshot_091513_031120](https://f.cloud.github.com/assets/5291731/1146039/c3a3f334-1e40-11e3-8dac-d42466d77fd8.jpg)

En las siguientes 2 imagenes vemos que nunca se activa con veredicto del templario cuando deberia hacerlo.
![wowscrnshot_091513_031040](https://f.cloud.github.com/assets/5291731/1146049/b24424be-1e41-11e3-94b8-d837929d0121.jpg)
![wowscrnshot_091513_031110](https://f.cloud.github.com/assets/5291731/1146051/c1b4a766-1e41-11e3-977f-7b1a0771f87b.jpg)

**Comment by searum** [comment]
fix!
