### ISSUE TITLE
[Misión] (Foso de Saron) Reforjar la espada (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1954]
Buenas.
La misión Reforjar la espada (http://es.wowhead.com/quest=24461) no se puede completar porque una vez que reuno los objetos y quiero usarlos en los yunques que hay en el area (dentro del Foso de Saron), por mas que me ponga enfrente, me dice "requiere el yunque de maestro de forja".
Gracias y hasta luego.

**Comment by redneo** [comment]
Cuando caiga el server se podra reforjar.

Sigo sin saber pq coño no se puede entrar por la puerta normal a Foso de Saron.
