### ISSUE TITLE
[Paladín represión] Sellos de mando.

### ISSUE THREAD

**Issue by bagnamar** [RoDNet/Bugtracker-Infinium-4.3.4#1955]
Este talento (ID: 85126) de la rama de represión inflige un 7% del daño con arma cada vez que salte: sello de verdad (ID:31801), sello de justicia (ID:20164) y sello de rectitud (ID:20154). Además hace que sello de rectitud, pegue a todos los enemigos que esten rango cuerpo a cuerpo.

El problema es que no hace que sello de rectitud pegue a los enemigos rango cuerpo a cuerpo.
El otro problema es que esta inligiendo ese 7% con cualquier ataque, y solo debe hacerlo cuando saltan los sellos anteriormente mencionados.
Los hechizos con los que salta y no debe son los siguientes: Exorcismo (ID:879), tormenta divina (ID 53385), sentencia (ID:20271), martillo de cólera (ID:24275), cólera sagrada (ID: 2821), maestría (mano de luz) http://es.wowhead.com/spell=76672/maestria-mano-de-luz, golpe de cruzado (ID: 35395) y veredicto del templario (ID:85256).

Exorcismo
![wowscrnshot_091513_024938](https://f.cloud.github.com/assets/5291731/1146138/506c460c-1e48-11e3-9727-0e8e9b8a3498.jpg)

Aquí se ve como sellos de mando pega x9, pega a los 3 muñecos por el sello de rectitud (como debe ser), otras 3 veces por mano de luz (maestría) y otras 3 veces por la tormenta divina.
![wowscrnshot_091513_031120](https://f.cloud.github.com/assets/5291731/1146143/d8a7d2a2-1e48-11e3-9f37-f9e43136130a.jpg)

Sentencia
![wowscrnshot_091513_024933](https://f.cloud.github.com/assets/5291731/1146150/29f57ec0-1e49-11e3-84d2-1666d3f48227.jpg)

Martillo de cólera
![wowscrnshot_091513_024941](https://f.cloud.github.com/assets/5291731/1146154/596c8e14-1e49-11e3-8327-81e776db3ccf.jpg)

Cólera sagrada
![wowscrnshot_091513_024953](https://f.cloud.github.com/assets/5291731/1146158/8b633b8e-1e49-11e3-9aa7-05d3de852abf.jpg)

Aqui vemos que pega x2, uno es de golpe de cruzado y el otro por mano de luz
![wowscrnshot_091513_030557](https://f.cloud.github.com/assets/5291731/1146169/2cd3b8c2-1e4a-11e3-99ff-dd65c9071d07.jpg)

Pega x2, uno del sello de rectitud (como debe ser) i le otro por el veredicto del templario
![wowscrnshot_091513_031040](https://f.cloud.github.com/assets/5291731/1146178/7add03fc-1e4a-11e3-9833-9445cc09db24.jpg)

**Comment by searum** [comment]
repetido aunque me gusta mas este reporte asi que cerrare los otros.

la proxima vez usa el buscador antes ^^ gracias

**Comment by bagnamar** [comment]
Lo haré, y gracias a ti por dejar el mio xD

**Comment by searum** [comment]
hombre lo que es activarse se activa con esto:

  04 Successful attack by Spell that use melee weapon
  06 Successful Ranged attack(and wand spell cast)
  08 Successful Ranged attack by Spell that use ranged weapon
  12 Successful ??? spell cast
  16 Successful damage from harmful spell cast (каст дамажащего спелла)

Por lo que yo creo que esta bien.

Lo del sello de rectitud ya lo he fixeado.
