### ISSUE TITLE
[Paladín protección] Escudo sagrado.

### ISSUE THREAD

**Issue by bagnamar** [RoDNet/Bugtracker-Infinium-4.3.4#1957]
Al activar este hechizo (ID:20925) deberia aumentar un 20% la cantidad bloqueada por el escudo del paladín (requiere escudo para ser activado).

El problema esta en que al activarlo tienes el bufo conforme aumenta 20% la cantidad bloqueada pero esta cantidad no aumenta.

En la primera imagen 2 golpes recibidos, en la segunda 2 bloqueados sin bufo y en la tercera 2 bloqueados con bufo, como se puede ver la cantidad que se bloquea es la misma con bufo o sin. (el bufo es el escudo entre rojo y amarillo)
![wowscrnshot_091513_035313](https://f.cloud.github.com/assets/5291731/1146268/02de2ecc-1e53-11e3-987a-12f28613b2f4.jpg)
![wowscrnshot_091513_035241](https://f.cloud.github.com/assets/5291731/1146270/3d997c42-1e53-11e3-94ac-ed29c9f50cba.jpg)
![wowscrnshot_091513_035323](https://f.cloud.github.com/assets/5291731/1146271/50f0ab30-1e53-11e3-8aa3-e6ee5b13938d.jpg)

**Comment by searum** [comment]
fix?

**Comment by bagnamar** [comment]
no, sigue sin funcionar
