### ISSUE TITLE
Mazmorra: Trono de las Mareas (HC)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1958]
Quería comentar unos cuantos detalles que nos sucedieron en esta mazmorra http://es.wowhead.com/zone=5004/trono-de-las-mareas

-Primero antes de poder llegar al primer jefe http://es.wowhead.com/npc=40586#encounter estuvimos bastante tiempo (casi 10min) esperando que la naga que hay nada más subir el elevador, nos abriera la puerta (de tanto tiempo que estuvimos esperando casi desmontamos grupo en el momento que le dió por abrir). Creo que el nombre que recibe esto es "evento de lady naz'jar"

-Después de tirar al primer boss y antes de llegar al segundo http://es.wowhead.com/npc=40765 debería habernos salido una cinemática (aunque esto no es grave, nos dio que pensar que algo estaba sucediendo mal aquí)
[Nota: este boss es piñata]

-Pero el problema más grave nos surgió tras volver a bajar por elevador y regresar a los dos caminos, donde antes habían unos tentáculos que nos obstruían el paso. Al haber sido derrotado los dos primeros jefes, estos tentáculos deberían haber desaparecido y por tanto permitirnos el paso para llegar a los últimos jefes: la dupla http://es.wowhead.com/npc=40788 y http://es.wowhead.com/npc=40825; y por último el jefe final http://es.wowhead.com/npc=42172

P.D. este último boss http://es.wowhead.com/npc=42172 supongo que sigue sin ser realizable, ya que en la tercera fase (que es cuando aparece) no se puede tarjetear. No sé si esta parte ya se pudo arreglar, no pudimos comprobarlo ya que no desaparecieron los tentáculos.

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/38/zl4j.jpg/'><img src='http://img38.imageshack.us/img38/5890/zl4j.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img38.imageshack.us/img38/5890/zl4j.jpg

Desconozco si estos problemas también suceden en la modalidad "normal"

**Comment by redneo** [comment]
para que los tentaculos desaparezcan y salga la cinemática, tienes que activar (en este caso desactivar) las defensas. Estas están situadas en la habitación del primer boss (lady Naz'jar), al lado de la puerta de salida.

**Comment by paellaencol** [comment]
Cierto, error nuestro.

Cierro y enlazo un par de problemas que tuvimos en esta mazmorra: 
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2109 https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2110
