### ISSUE TITLE
[Paladín protección] Defensor candente.

### ISSUE THREAD

**Issue by bagnamar** [RoDNet/Bugtracker-Infinium-4.3.4#1959]
Al activar este hechizo (ID:31850) reduce todo el daño recibido un 20% durante 10 segundos, además si el paladín recibe un golpe mortal durante esos 10 segundos, ese golpe en lugar de matarle le cura un 15% de su salud maxima.

El problema esta en que el golpe que te va a matar te mata sin importar que lo tengas activo.

**Comment by searum** [comment]
fix
