### ISSUE TITLE
[Objeto] La última reliquia de Argus

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#196]
Buenas, creo que ya es hora de que arreglen tan bonito objeto de arqueologia :).

No funcionaba en 4.0.6 y tampoco en este parche...

Deberia de generar una teletransportación semi ramdon, y al usarlo, carga la barra de TP y al final solo salen lucecitas y sigo en el mismo lugar :/.

http://es.wowhead.com/item=64457/la-ultima-reliquia-de-argus

**Comment by Kiritoo** [comment]
Arreglado, el cambio será aplicado en el reino en la próxima compilación.
