### ISSUE TITLE
[Paladín protección] Custodiado por la luz.

### ISSUE THREAD

**Issue by bagnamar** [RoDNet/Bugtracker-Infinium-4.3.4#1960]
Este talento (ID:85646) a nivel 2 aumenta la sanacion realizada por palabra de gloria cuando se usa para sanarse a uno mismo un 10%, además toda sobresanación creará un escudo protector que absorberá la misma cantidad sobresanada durante 6s.

El problema esta en que cuando recibes una sobresanación mediante palabra de gloria se activa el bufo que absorberia la cantidad sobresanada, pero es visual ya que no se absorbe nada.

En la siguiente imagen se ve como estoy recibiendo daño apesar de tener el bufo activo.
![wowscrnshot_091513_040008](https://f.cloud.github.com/assets/5291731/1146398/0dee0bb6-1e5d-11e3-85af-ad823009610c.jpg)

**Comment by searum** [comment]
avisa si ya funciona que le meti un fix pero no se si va correctamente... cierro y si sigue yendo mal reabro

**Comment by bagnamar** [comment]
Sigue sin funcionar.

**Comment by searum** [comment]
fix
