### ISSUE TITLE
[Paladín protección] Escudo vengador.

### ISSUE THREAD

**Issue by bagnamar** [RoDNet/Bugtracker-Infinium-4.3.4#1961]
Este hechizo (ID:31935) pega demas, no mucho, pero prefiero postearlo.
![wowscrnshot_091513_033636](https://f.cloud.github.com/assets/5291731/1146404/96f5bd04-1e5e-11e3-91b8-01fc9b85fee4.jpg)

**Comment by Savian123** [comment]
Añade que el Glifo de Escudo Atontador esta bug... y se activa con todos los ataques

**Comment by Kiritoo** [comment]
Savian cada reporte en 1 issue.
No más de uno en cada, gracias.

**Comment by bagnamar** [comment]
Eso que comentas no ocurre savian.

**Comment by bagnamar** [comment]
Vale, te habia entendido mal, si ocurre el efecto que mencionas. 
No lo habia reportado porque nunca habia usado ese glifo.
