### ISSUE TITLE
[Paladín protección] Escudo del honrado.

### ISSUE THREAD

**Issue by bagnamar** [RoDNet/Bugtracker-Infinium-4.3.4#1962]
Este hechizo (ID:53600) consume todas las cargas de poder sagrado para infligir daño según las cargas que se hayan consumido.

El problema es que no tiene en cuenta el equipo a la hora de hacer daño, pega lo mismo lleves equipo o no, es decir, con equipo, pega lo que marcaba cuando ibas desnudo. (Similar a lo que pasaba con exorcismo).
![wowscrnshot_091513_034433](https://f.cloud.github.com/assets/5291731/1146445/fb35bd02-1e61-11e3-9801-3806f778f28b.jpg)
![wowscrnshot_091513_032156](https://f.cloud.github.com/assets/5291731/1146448/19c5dedc-1e62-11e3-8699-7481060d4b92.jpg)
![wowscrnshot_091513_032208](https://f.cloud.github.com/assets/5291731/1146450/2e1b2ebe-1e62-11e3-9de6-98318b34c9ed.jpg)
![wowscrnshot_091513_032223](https://f.cloud.github.com/assets/5291731/1146452/44a93234-1e62-11e3-9976-4e3a4366579f.jpg)

**Comment by searum** [comment]
fix
