### ISSUE TITLE
[Paladín protección] Martillo del honrado.

### ISSUE THREAD

**Issue by bagnamar** [RoDNet/Bugtracker-Infinium-4.3.4#1963]
Este hechizo (ID:53595) inflige 30% del daño con arma al objetivo actual y crea una ola de luz que golpea a todos los enemigos en un radio de 8 metros del objetivo.

El problema es que el daño de la ola de luz es el mismo lleves equipo o no, pega lo mismo al ir desnudo que al llevar equipo. (similar a exorcismo).

En las imágenes el daño de la ola se aprecia en el muñeco de la derecha.
![wowscrnshot_091513_034150](https://f.cloud.github.com/assets/5291731/1146482/70be3624-1e64-11e3-9fa0-91227b760c9a.jpg)
![wowscrnshot_091513_034301](https://f.cloud.github.com/assets/5291731/1146484/822be6ae-1e64-11e3-8217-fda0ee92669e.jpg)

**Comment by searum** [comment]
fix

**Comment by bagnamar** [comment]
Buenas, me acabo de dar cuenta que este hechizo ahora esta pegando mas de lo que debería (la ola de luz), en la descripción pone 2,6k y está pegando entre 3,9k y 4,3.

**Comment by Kiritoo** [comment]
Bagnamar, como siempre avisamos si encuentras un error nuevo tras la reapación, crea nuevo Issue, gracias.
Voi a crear por la tarde un post en el foro de como realizar los reportes quien no la siga cerraremos los Issues.
Saludos.

**Comment by bagnamar** [comment]
Esto ultimo no lo sabia, disculpas. x)
