### ISSUE TITLE
[Mago] Armadura de escarcha.

### ISSUE THREAD

**Issue by bagnamar** [RoDNet/Bugtracker-Infinium-4.3.4#1964]
Al estar activo este hechizo (ID:7302) reduce un 15% el daño físico recibido. Si un enemigo golpea al mago, su movimiento puede verse ralentizado un 30% y el tiempo entre sus ataques aumentado un 20% durante 5s.

El problema es que este hechizo te ralentiza aunque seas immune a este efecto.

En la imagen estoy con mano de libertad (ID:1044) que concede immunidad a impedimientos del movimiento, y me afecta de todas maneras.
![wowscrnshot_091513_171404](https://f.cloud.github.com/assets/5291731/1146507/133fb46a-1e68-11e3-9f76-48ebeec908d8.jpg)

Pd: actualmente el hechizo salta siempre que golpean al mago, no estoy seguro pero según entiendo de la descripción eso solo debería ser aveces.

En cuanto a la reducción del 15% esta funcionando.
![wowscrnshot_091913_164321](https://f.cloud.github.com/assets/5291731/1173576/436a2f42-213a-11e3-83fe-c97216dffc0c.jpg)
![wowscrnshot_091913_164347](https://f.cloud.github.com/assets/5291731/1173578/4e34ef3e-213a-11e3-8b62-e3598e9f0997.jpg)
(del recount ni caso que no me había dado cuenta que estaba ahí)

**Comment by ghost** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/917

**Comment by searum** [comment]
tiene un 100% de posibilidades de saltar.. la verdad es que desconozco si tiene un cooldown interno, si podeis decirme yo se lo pongo encantado :)

**Comment by ghost** [comment]
No, no tiene cd interno. Lo que puede que tenga es un %determinado de probabilidades de afectar al enemigo, pero por mas que busco no encuentro nada (con tu comentario no se si te refieres a que lo tiene así en el server o a que la spell tiene un 100% blizzlike)

Por otro lado, en la 3.3.5 también tenía DR, pero ahora no xD.

Podrías mirar si está reduciendo el daño físico recibido en un 15%? por que he probado contra algunos guardias y...me pegan lo mismo con la armadura que sin ella.

**Comment by F4NT4SM4** [comment]
En mop es 100 la probabilidad de saltar pero en cata dice en el buff:Tiene una Probabilidad de relentizar al enemigo....

**Comment by searum** [comment]
Asman, 100% blizzlike segun los datos que tengo del 4.3.4 y 4.0.6a

**Comment by ghost** [comment]
Entonces sólo falta:
- Que @F4NT4SM4 diga una fuente, el dice que debe tener un % de probabilidades de aplicar el debuff en vez de un 100%, pero yo como dice @searum diría que es un 100% por videos y demás, y tampoco he encontrado nada.
- Que no se aplique a objetivos inmunes a ralentizaciones como el paladín con mano de libertad.
- Chequear la reducción del 15% del daño físico, ya que según mis testeos no la está dando.
- Añadir que afecte a daño físico a distancia, como armas arrojadizas (pícaros y guerreros, lanzamiento mortal etc), sentencias de paladín de escuela física/melee, aunque sean lanzadas a distancia, y cazadores (lo que también hace que ganen enfoque más despacio); de acuerdo a las notas del parche 4.1: "The attack speed slow from the Chilled proc is now 20%, down from 25%, but it also affects ranged attack speed."

**Comment by searum** [comment]
asman, solo salta con ataques a melee... una cosa es que afecte al ranged attack speed y otra que salte con ranged, segun el proc de la spell solo es a melee

**Comment by F4NT4SM4** [comment]
La descripcion del hechizo dice que tiene una probabilidad de relentizar al enemigo pero joda me puse a ver unos videos y esa probabilidad parece 99.9% siempre....

**Comment by ghost** [comment]
Sí, tienes razón, el ataque físico a distancia como el del cazador no hace que coja el debuff, lo que quiere decir eso es que si un caza te ataca a melee y coge el debuff, su velocidad de ataque a distancia será reducida, no lo que yo decía.

Pero hay ciertas spells que aun lanzadas a distancia deben meter el debuff, como las sentencias y lanzamiento heroico (lanzamiento heroico NO, según las notas del parche 3.0.8 pone que no debe hacerlo saltar y no hay pruebas de que lo haga): 

http://us.battle.net/wow/en/forum/topic/2267591085

http://eu.battle.net/wow/en/forum/topic/1840304628

**Comment by bagnamar** [comment]
Actualmente al lanzar sentencia se me mete el debuff.

**Comment by ghost** [comment]
Va perfecto pues, solo queda evitar que se aplique a los inmunes. Reducción de daño testeada, gracias Bagnamar.

**Comment by bagnamar** [comment]
Asman, ya he editado mas arriba que si funciona la reduccion 15%.

**Comment by searum** [comment]
Entonces en realidad el problema no es el escudo, el escudo va perfect.. en todo caso es mano de libertad lo que no va bien no? xD Pero probarlo please! que ahora si que tengo menos tiempo y no puedo andar probando cosillas xD

**Comment by bagnamar** [comment]
Mano de libertad funciona a la perfección con todos los demás hechizos lanzados por jugadores, donde no funciona del todo bien es con las ralentizaciones de mobs, pero eso ya va aparte.
Creí que el problema estaba en la armadura por que vs jugadores es lo único que atraviesa la immunidad, y ahora que lo pienso quizás tenga algo que ver que es el paladín el que ataca, es decir que no es un efecto lanzado directamente por un jugador, sino que el paladín lo activa de manera indirecta.

Nota: si has atacado anteriormente y tienes el debuff, al usar mano de libertad se te quita, pero cuando atacas y estas bajo los efectos de mano de libertad es cuando te afecta ignorandola.

**Comment by searum** [comment]
entonces está claro que no existe ningún bug en esto XD

cierro y si encontrais un bug reportar ese bug, pero lo que se reporta aqui esta todo bien xD
