### ISSUE TITLE
[Mision] Nos está ocultando algo

### ISSUE THREAD

**Issue by neoacadio** [RoDNet/Bugtracker-Infinium-4.3.4#1966]
Esta mision esta bug por varias cosas, la primera esque el principe no te sigue(pero ni en esta ni en ninguna de las de seguir) y la parte mas importante esque cuando llegas al sitio donde debes revisar los papeles no puedes hacer nada lo cual impide que completes dicha mision.

**Comment by Kiritoo** [comment]
IDs de la misión, o lo mejor sería el enlace directamente.
Gracias.

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

Cierro ticket
