### ISSUE TITLE
[Mision] La madre del Ternero

### ISSUE THREAD

**Issue by neoacadio** [RoDNet/Bugtracker-Infinium-4.3.4#1967]
Esta mision esta bug por que cuando llegas al altar ensangrentado no ocurre nada, ni se compelta ni luchas con nadie ni nada.

**Comment by Kiritoo** [comment]
IDs de la misión, o lo mejor sería el enlace directamente.
Gracias.

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/ 

Cierro ticket.
