### ISSUE TITLE
e hecho lo de las carpetas y sigo igual que antes no obtiene la lista de personajes ,( ayudarme ) que llevo  3 dias sin jugar xd

### ISSUE THREAD

**Issue by vansay** [RoDNet/Bugtracker-Infinium-4.3.4#197]

**Comment by lamaza** [comment]
Que falta de respeto esto tambien, ve y reportalo en el foro que para eso esta man, pide ayuda por allí. El bugtracker es para cosas directamente in game y de la programación, y no problemas entre la parte de software tuya y algo del servidor.

**Comment by vansay** [comment]
usted perdone pero no era mi intención faltar al respeto a nadie

**Comment by Dekadencee** [comment]
Ya debería estar solucionado, si el problema persiste, ponte en contacto con nosotros vía foro
