### ISSUE TITLE
BUG " APRENDER NUEVAS TECNICAS "

### ISSUE THREAD

**Issue by shurax** [RoDNet/Bugtracker-Infinium-4.3.4#1976]
Buena al parecer esta mision antes tenia un bug y toda lo sigue teniendo porque estoy intentando hacerla y nada que se completa y mucha gente le pasa lo mismo no se si solo es a la clase de los elfos de la noche o no pero si saben de algo por favor ayudenme.!

**Comment by ghost** [comment]
Pon la ID de la misión para que la puedan arreglar, además de como funciona y como debería funcionar.

**Comment by shurax** [comment]
no se cual es el ID de la mision pero ahi coloco una imagen del juego donde especifica todo lo de la mision y bueno la mision trata que debes de utilizar un poder en mi caso se llama "Cargar" por ser gerrero en un muñeco de entrenamiento y con utilizarlo deberia completarse la mision pero lo uso y la mision no se completa

![wowscrnshot_091613_162503](https://f.cloud.github.com/assets/5471552/1152683/5163e144-1f12-11e3-9caa-cb18673e8521.jpg)

PD: tambien e probado en otros reinos con un elfo de la noche y sucede lo mismo

**Comment by shurax** [comment]
Ella es la que me da la mision "aprender nuevas tecnicas"

![wowscrnshot_091613_163501](https://f.cloud.github.com/assets/5471552/1152753/abfc618e-1f13-11e3-9c14-f651893b877f.jpg)

**Comment by redneo** [comment]
Ostras mas sencillo es poner la mision http://es.wowhead.com/quest=26945 no cuenta el cargar sobre los muñecos.

De todas formas, a mi si que me ha contado perfectamente
