### ISSUE TITLE
[Druida Feral] Talento: Presteza feral (ID:24866)

### ISSUE THREAD

**Issue by Cacafuti** [RoDNet/Bugtracker-Infinium-4.3.4#1978]
La primera parte del talento funciona pero la segunda que dice que al activar Carrerilla se quitan todos los efectos de ralentizar, el cual no funciona.

**Comment by ghost** [comment]
.

**Comment by lamaza** [comment]
No vayas a pensar que debe quitar STUN que no es asi.

**Comment by searum** [comment]
me temo que si que son roots tambien ^^ pero no STUN como recalca lamaza

fix.
