### ISSUE TITLE
[Druida Feral] Talento: Estampida (ID:78892)

### ISSUE THREAD

**Issue by Cacafuti** [RoDNet/Bugtracker-Infinium-4.3.4#1979]
La parte de Carga feral oso funciona pero la parte de Carga feral felina no funciona que
consiste en cuando haces Carga feral felina se activa la posivilidad de poder hacer Destrozar sin sigilo y sin importar que este detras del jugador, y que ademas no cueste energia cuando tiene 2 puntos de talento. La parte de , da igual estar detras del objetivo y de que no cueste energia no funcionan.

**Comment by ghost** [comment]
Doble, se puede cerrar. 

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2352
