### ISSUE TITLE
[hechizos] Selfless Healer

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#1981]
Ahora el hechizo no va... Nunca se aplica (autobuff) al curar a otros y antes iba PERFECTO.

![wowscrnshot_091613_151337](https://f.cloud.github.com/assets/4790547/1152407/9f571a8e-1f0c-11e3-9e99-05a120758e44.jpg)

**Comment by searum** [comment]
bueno relajate chico que no se acaba el mundo.

**Comment by searum** [comment]
fix... y una cosa te digo, no hay nada que me joda mas que los comentarios como el tuyo asi que si vas a reportar REPORTA EL FALLO pero no me interesa que llores ni que intentes dar pena y mucho menos que recalques PERFECTO... y te lo digo de buen rollo para futuras ocasiones porque entre este issue y varios como los de Dragon y Asman... ya me estoy empezando a cansar
