### ISSUE TITLE
Receta ingeniería (Mira de precisión)

### ISSUE THREAD

**Issue by Creamfour** [RoDNet/Bugtracker-Infinium-4.3.4#1984]
Al hacer la misión de ingeniería para conseguir ''Ingeniero gnómico'', te pide un objeto llamado ''Mira de precisión'' (4407), pero el instructor ya no lo enseña, así que se tiene que buscar una receta ''Esquema: mira de precisión'' (13310) pero aparece que ya no es posible de conseguir. ¿Entonces como consiguen los ingenieros actualmente ''Ingeniero gnómico''?

**Comment by redneo** [comment]
Ya la enseñan.
