### ISSUE TITLE
[Brujo] Cauce de Salud

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1985]
Aqui esta el link del hechizo: es.wowhead.com/spell=755

Con 126k de vida cada tick de cauce de vida me está sacando 7k. 
Segun la spell dice que te quita el 1% de tu salud y le transfiere un 6% de la salud máxima del demonio.
Por tanto en mi caso debería quitarme alredor de 1k por tick.
Diría que la confusión ha estado es que has puesto que quite un 6%  y ponga un 6%.

**Comment by searum** [comment]
fix
