### ISSUE TITLE
[Incompleto] Corcel vil

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#1986]
Bueno, se que se hizo una limpieza a toda la gente que tenía la montura, pero por bg estoy viendo a muchas personas con ella puesta, y me refiero a pjs que no son brujos obviamente. Así que algún fallo tendrá que haber, a ver si alguien asoma la patita y lo cuenta.

**Comment by redneo** [comment]
136 personas con el corcel vil sin ser brujos, manda narices. Procedo al borrado de dicha spell, arreglar los entrenadores de brujo y puede que alguna sorpresa a esa gente que sabiendo que no son brujos, tienen spells de brujos.
