### ISSUE TITLE
[Misión] (Hyjal) Signed in Blood

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#1988]
Firmado con sangre http://es.wowhead.com/quest=25274
Hola esta misión está bug y no se puede continuar la cadena y llegar a las ultimas quest hyjal sin pasarla.
Al cojerla debemos de ir junto a unos npcs "recluta Crepuscular" y usar el objeto provisto en la misión tras atraerlo para conseguir  
Papeles de reclutamiento Crepusculares.

Problema: No estan los npcs, al menos visibles.
Importante!!: Ponerle condition al objeto de misión.
Porra http://es.wowhead.com/item=52683 Probarlo.

Video:http://www.youtube.com/watch?v=_2Kc-oLuRI8

Un saludo.

**Comment by redneo** [comment]
Arreglada, como dice la mision, tienes que alejarlos.
