### ISSUE TITLE
bug Luminosidad Arcana

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#199]
este habilidad no funciona como deveria,el fallo es que no da el 6% de poder con hechizos

**Comment by lamaza** [comment]
agrego http://old.wowhead.com/spell=1459/luminosidad-arcana

**Comment by Alfonn** [comment]
Ya reportado https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/125 .
