### ISSUE TITLE
Talento paladín reprensión, Santidad de batalla  (id=25956)

### ISSUE THREAD

**Issue by meybon** [RoDNet/Bugtracker-Infinium-4.3.4#1990]
Saludos:

Talento rama reprensión del paladín. 4º linea 2º hechizo

El talento en cuestión (Santidad de batalla) no funciona, la celeridad no afecta a los golpes como golpe de cruzado que siempre tiene invariablemente 4.5 seg de reutilizacion.

Meybon.

**Comment by searum** [comment]
repetido, usa el buscador
