### ISSUE TITLE
[Misión] Baldíos del Sur - La redención del guerrero

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1992]
Recoges las armas y vas a darselas a los prisioneros pero no sucede nada.

Aqui dejo el link de la mision:http://es.wowhead.com/quest=24512

**Comment by redneo** [comment]
Reparada, me gustaria hacer funcionar la cuerda para bajar... pero me han liado en el juego.
