### ISSUE TITLE
[Prueba del Cruzado] Npcs que no se les puede atacar

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#1995]
Un problema qe hay es que los bosses se qedan al lado de la puerta sin poder salir y entonces no les podemos pegar ni nada. Es como si hubiese una especie de pared invisible. El unico qe no le pasa es a Lord Jaraxuss que como sale del medio no hay problema y Anub'Arak porque está abajo de ToC.

El segundo problema es que cuando salen los primeros bosses, las bestias de Rasganorte, Gormok el Empalador (http://es.wowhead.com/npc=34796) saca unos adds que no se puede atacar pero si te atacan entonces te dejan en combate. Son unas especias de ratas mineras que no he conseguido encontrar su id.

Aqui dejo el link de la banda : http://es.wowhead.com/zone=4722

**Comment by redneo** [comment]
Vale, creo que el problema viene de los maps, ya que aun borrando la puerta, de ahi no pasan. Creo que se podia cambiar en la configuración para que ignorase los maps en ciertos mapas (redundancia) en este caso seria el 649, a ver si lo puedo probar en local o en el server test.

El otro fallo, creo que no es tal, que no se les tendria que poder atacar, pero si que tendrian que desaparecer al morir el boss npcs: http://www.wowhead.com/npc=34800

**Comment by efectokoleos** [comment]
fixed
