### ISSUE TITLE
[Bastion de baradin] Occu´thar

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#1997]
ID: http://es.wowhead.com/npc=52363/occuthar

Bug: Al boss se le puede cortar cast
facilmente le cortamos cast sombras abrasadoras y con 1 tanke se podria tankear el boss normalmente son 2 que se turnan

**Comment by redneo** [comment]
Ya no se le puede cortar (teoricamente) me lo probais a ver si es correcto?
