### ISSUE TITLE
habilidades de picaro

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.3.4#2]
el glifo de hemorragia añade un sangrado a hemorragia,este sangrado esta haciendo 3 puntos de daño.

el talento impetu mortal se activa el icono de los buff pero no reinicia el tiempo de reponerse/hacer picadillo ni tampoco aplica en las estadisticas el % de critico aumentado que da el talento.

el talento golpes despiadados no esta funcionando,no te da los 25 puntos de energia al usar remates.

**Comment by crowel** [comment]
La puñalada hace más daño del que tiene que hacer.
http://es.wowhead.com/spell=53/
