### ISSUE TITLE
grito de guerra (campo de batalla)

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.3.4#20]
no estan las puertas? avance asta el cementerio antes de empezar la bg i cuando llegava al cementerio me volvia a meter en la base

http://subefotos.com/ver/?a98d1f30684588f79741e70d692e88eeo.jpg#codigos

**Comment by lamaza** [comment]
Solo te paso a ti XD, seguro que no activaste algo en el picaro?

**Comment by Dekadencee** [comment]
Es debido a un error interno del emulador que hace que a veces no se vean los gameobjects/players/npcs, estamos con ello.
