### ISSUE TITLE
[Sacerdote] Palabra de las Sombras: muerte

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#200]
Hay dos bugs con este hechizo.
Primero: cuando el objetivo tiene 25% de vida o menos, el daño que le causa la plabra de sombras: muerte se triplica. Esto no sucede con objetivos pvp ni pve.

Segundo: el talento masoquismo debe de regenerar 10% de mana total cada vez que me hago daño con palabra de las sombras: muerte. Esto tampoco sucede.

Plabra de las sombras: muerte: http://es.wowhead.com/spell=32379/
Masoquismo rango1: http://old.wowhead.com/spell=88994
Masoquismo rango2: http://old.wowhead.com/spell=88995

Pd: pongo el talento masoquismo en este reporte, porque solo no funciona la parte del hechizo palabra de las sombras: muerte, así que supongo que lo bug en realidad sea el hechizo.

También pongo un reporte relacionado con este hechizo #156

**Comment by searum** [comment]
fix

**Comment by ghost** [comment]
Ya esta arreglado.
