### ISSUE TITLE
[Misión] (Corona de Hielo) Templar la hoja (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2000]
Buenas.
La misión Templar la hoja (http://es.wowhead.com/quest=24476) no se puede completar porque cuando uso la Quel'Delar reforjada (http://es.wowhead.com/item=49920) en el crisol de almas, aparece una barra de progreso, pero no recibo a cambio la Quel'Delar templada (http://es.wowhead.com/item=49750).
Gracias!

**Comment by redneo** [comment]
Lo he estado probando, hay un problema con la visibilidad.... si lo usas muy pegado a la antorcha, no te cuenta, ya que no ves teoricamente al npc al que hay que lanzarla.

Lo he puesto volando un poco mas arriba, tendria que funcionar (a mi me lo ha hecho) o si no, subido al lado del portal seguro que te deja lanzarlo bien.
