### ISSUE TITLE
Reporte Horda [Portales Bug o faltantes]

### ISSUE THREAD

**Issue by rhaenyra** [RoDNet/Bugtracker-Infinium-4.3.4#2005]
Bastión de ébano - Portal hacia Orgrimmar bug.
Dalaran - Faltan portales: Lunargenta, Entrañas, Cima del trueno.
Tierras Altas crepusculares - Falta el portal a Orgrimmar.

Gracias de antemano.

**Comment by Wiinter** [comment]
El portal de tierras crepusculares tienes primero que hacer una serie de misiones en el puerto de fuacedraco para activarlo.

**Comment by Kiritoo** [comment]
En dalaran ya no estan todos los portales a todas las ciudades como antes, en 4.3.4 no.
El del bastion del ebano si hiciste la mision de remendejo y cojer la de ir al rey se te activa, antes no.
Debes completar las misiones requeridas antes de tomar ciertos portales.
Saludos, cierro issue.
