### ISSUE TITLE
Me sucedió un bug en Equitación

### ISSUE THREAD

**Issue by rhaenyra** [RoDNet/Bugtracker-Infinium-4.3.4#2009]
Sucede que tras migrar mi personaje, compré la equitación hasta la ultima pero aún así  en el libro de hechizos sale que debo comprarla y peor, el maestro no me enseña nada. Saludos.

**Comment by Kiritoo** [comment]
Reloguea

**Comment by rhaenyra** [comment]
Gracias! Funcionó.
