### ISSUE TITLE
[Misión] El fin de los desertores: 11134

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2010]
El NPC 23941 no está, por lo que no se puede realizar la misión.

La misión va de capturarlo. Cuando llega a un cuarto de vida, empieza a decir estos textos:

" ¡Me rindo! ¡Guarda tu espada! "
" Iré contigo. Tan solo perdona a mis hombres. Son buenos chicos que simplemente han cometido un error..."

http://es.wowhead.com/quest=11134

**Comment by redneo** [comment]
esto...

La misión es la http://es.wowhead.com/quest=27213 o la http://es.wowhead.com/quest=11134

Si es la segunda está obsoleta, no se podria coger, es más ni tiene quien la de.

De todas formas, le he puesto en su phase correcta, cuenta matandolo.
