### ISSUE TITLE
[Misión] (Hyjal) Twilight Training

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2017]
Entrenamiento Crepuscular http://es.wowhead.com/quest=25291

No está el npc donde se entrega la misión, tampoco estan todos los npcs del campamento, aunque creo que realmente estan invisibles porque la interrogante si aparece.

Instructora Mylva http://es.wowhead.com/npc=39413

Un saludo.

**Comment by redneo** [comment]
Arreglado
