### ISSUE TITLE
¿Se podría habilitar para crear el parche de tanque que hacen los peleteros?

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#2018]
Armadura para pierna de pellejo de draco  id 71720.
Añade 145p de aguante y 55p de ind. equivar

Este item fue añadido en el parche 4.2.0 segun wow head. (fuente: http://es.wowhead.com/item=71720/armadura-para-pierna-de-pellejo-de-draco#taught-by-item)
Y me preguntaba si se podria habilitar para poder crearlo, ya que actualmente cuando se intenta crear el item aparace un mensaje que dice que no esta permitido para mi, en otras palabras esta bloqueado. 

Muchas gracias de antemano.

**Comment by searum** [comment]
esto no va aqui, se habilitara en el siguiente season como todos los items
