### ISSUE TITLE
[Misión] (Hyjal) Walking the Dog

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2020]
-Nombre: Paseando al perro
-Enlace: http://es.wowhead.com/quest=25294
-Descripción:Reúne 5 piezas de carne de basilisco carbonizada y alimenta al engendro de Arderos. 
-Problema: El basilisco http://es.wowhead.com/npc=39658 no despoja el objeto de misión Carne de basilisco carbonizada http://es.wowhead.com/item=52708
-Observaciones: Creo que no lo lo despoja o tiene el drop muy bajo porque mate a todos los de la zona y no tiraron ni una vez el objeto.

Un saludo.

**Comment by redneo** [comment]
Si que lo sueltan aun sin tener la misión, he cambiado de phase a muchos basiliscos, a lo mejor el problema era ese.
