### ISSUE TITLE
[Misión] (Hyjal) Gather the Intelligence

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2021]
-Nombre: Reúne información
-Enlace: http://es.wowhead.com/quest=25296#.
-Descripción:Obtén el comunicado Crepuscular y los planes de batalla de Hyjal. 
-Problema:No estan el comunicado ni los planes para recojerlos. http://es.wowhead.com/object=202968 http://es.wowhead.com/object=202969
-Observaciones: Donde se cojen los planos de batalla al norte, no esta ningun npc en el poblado vigilia de la batalla, seguro que ocurre que estan invisibles como los otros.

Un saludo.

**Comment by redneo** [comment]
poco a poco voy poniendo a todo lo que veo en su phase, pero me parece MUY raro que tantos npcs y gobs tengan una phase especifica.
