### ISSUE TITLE
[Misión] (Los Baldíos del Norte) Entrega de caravana de El Cruce

### ISSUE THREAD

**Issue by iBrianAR** [RoDNet/Bugtracker-Infinium-4.3.4#2022]
• <strong>Nombre</strong>: <a href="http://es.wowhead.com/quest=13975">Entrega de caravana de El Cruce</a>
• <strong>Enlace</strong>: <a href="http://es.wowhead.com/quest=13975">http://es.wowhead.com/quest=13975</a>
• <strong>Descripción</strong>: Habla con <a href="http://es.wowhead.com/npc=34578">Rocco Azotaespinillas</a> en la Granja de Grol'dom y escolta su caravana hasta El Cruce.
• <strong>Problema</strong>: Al hablar con Rocco Azotaespenillas no te da la posibilidad de escoltar su caravana hasta El Cruce.
• <strong>Observaciones</strong>: Por lo visto no hay script en Rocco Azotaespenillas, o eso creo, ya que no aparece ninguna opción para iniciar a escoltar su caravana.

**Comment by searum** [comment]
asi da gusto ! muchas gracias por seguir el modelo de reporte

**Comment by iBrianAR** [comment]
De nada Searum, sigan así. ¡Los admiro!

**Comment by redneo** [comment]
Lo he puesto que se pueda hacer, no sale la animación de la caravana, pero te lleva allí y cuenta como completada.
