### ISSUE TITLE
[Misión] (Los Baldíos del Norte) Cueste lo que cueste

### ISSUE THREAD

**Issue by iBrianAR** [RoDNet/Bugtracker-Infinium-4.3.4#2023]
• <strong>Nombre</strong>: <a href="http://es.wowhead.com/quest=13963">Cueste lo que cueste</a>
• <strong>Enlace</strong>: <a href="http://es.wowhead.com/quest=13963>http://es.wowhead.com/quest=13963</a>
• <strong>Descripción</strong>: Interroga al prisionero <strong>Crines de Acero de las inmediaciones</strong>. Si está inconsciente, Togrik puede encargarse de despertarlo.
• <strong>Problema</strong>: No se puede interrogar a <i>Crines de Acero de las inmediaciones</i>.
• <strong>Observaciones</strong>: No hay opción a interrogar a <i>Crines de Acero de las inmediaciones</i>.

**Comment by redneo** [comment]
Arreglado casi casi Blizlike :D
