### ISSUE TITLE
[Misión][Las cámaras de Reflexión] Las cámaras de Reflexión (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2024]
Hola.
La misión "Las cámaras de Reflexión" (http://es.wowhead.com/quest=24480) no se puede completar porque el PNJ Quel'Delar (http://es.wowhead.com/npc=37158) no aparece al acercarse al pedestal de Agonía de Escarcha con el objeto de misión Quel'Delar templada (http://es.wowhead.com/item=49766) en el inventario.
Muchas gracias!

**Comment by Kiritoo** [comment]
Hola pasa por aqui para futuros reportes.
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Saludos.

**Comment by redneo** [comment]
Arreglado, ya quedan menos misiones para terminar la cadena!
