### ISSUE TITLE
[Mago] Armadura de Escarcha

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2025]
ID:7302
Los atacantes tienen una probabilidad de ser relentizado un 30%
bug: Siempre esta aplicando la relentizacion al atacante y deberia de ser una probabilidad

**Comment by Kiritoo** [comment]
Reporte mal creado.
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Editalo o lo cierro, saludos.

**Comment by ghost** [comment]
Se puede cerrar:
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1964

**Comment by Kiritoo** [comment]
@F4NT4SM4 Reportes dobles no porfavor mira el enlace que puse hace un momento, cierro.
