### ISSUE TITLE
[Sacerdote sagrado] Pozo de luz

### ISSUE THREAD

**Issue by ruben312** [RoDNet/Bugtracker-Infinium-4.3.4#2027]
Esta skill indispensable en pvp no funciona bien ya que se puede matar al pozo de luz de un golpe cuando debería ser invencible

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
