### ISSUE TITLE
BUG DE DRAGONES EN INFRALAR

### ISSUE THREAD

**Issue by Workiin** [RoDNet/Bugtracker-Infinium-4.3.4#203]
Los dragones elites raros  Xariona y Aeonaxx se encuentran ahi parados alfrente de la salida de templo de la tierra, no se les puedes atacar ni nada y solo esta quietos
![bug](https://f.cloud.github.com/assets/4934379/755500/f9f387ea-e5b2-11e2-937e-0f87fcb31be4.PNG)

**Comment by shials** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/151 Ya está reportado aquí

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/79 Y aquí antes de ese.

**Comment by Dekadencee** [comment]
Reporte repetido, lo seguimos desde #79
