### ISSUE TITLE
[Mision] Cubrirse las espaldas

### ISSUE THREAD

**Issue by Bariloche123** [RoDNet/Bugtracker-Infinium-4.3.4#2031]
Le hago click al pergamino pero no carga nada y nada sucede. ID: 25695

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

Espera que caiga el server y borra la carpeta cache dentro del wow
