### ISSUE TITLE
[Misión] (Hyjal) Walking the Dog

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2032]
-Nombre: Paseando al perro
-Enlace: http://es.wowhead.com/quest=25294
-Descripción:Reúne 5 piezas de carne de basilisco carbonizada y alimenta al engendro de Arderos.
-Problema: Al alimentar al perro http://es.wowhead.com/npc=39659 con Carne de basilisco carbonizada http://es.wowhead.com/item=52708 no cuenta en la misión.
-Observaciones: http://es.wowhead.com/search?q=engendro+de+arderos#spells

Un saludo.

**Comment by redneo** [comment]
Arreglada, creo que ya se puede sacar el logro de las misiones en hyjal, pero intentare arreglar las que falten

**Comment by paellaencol** [comment]
Gracias! 115/115 ya
