### ISSUE TITLE
[Misión] (Hyjal) Grudge Match

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2034]
-Nombre: ¡Pelea!
-Enlace: http://es.wowhead.com/quest=25496
-Descripción:Desafía a Gromm'ko en el Trono de los Elegidos en Hyjal. 
-Problema: No se puede retar Gromm'ko http://es.wowhead.com/npc=40409
-Observaciones: Video http://www.youtube.com/watch?v=3ZU3OWQ0qwc

Un saludo.

**Comment by paellaencol** [comment]
Ya funciona
