### ISSUE TITLE
[Sacerdote] Alarido psíquico ID: 8122

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2035]
Buenos días.

Linkeo desde un reporte ya cerrado y posteriormente arreglado. Esta spell se ha estropeado hoy mismo, le están sucediendo los mismos problemas que tenía aqui:

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1493

Gracias

**Comment by searum** [comment]
en realidad yo no arregle este bug abro el otro reporte cierro este

**Comment by paellaencol** [comment]
Diría que arreglado de nuevo, creo que el problema fue probarlo contra los dummys, que contra esos funcionaba antes también. En fin nada grave
