### ISSUE TITLE
[Misión] Tierras Devastadas - Eres Rakh'likh

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2036]
No esta Razelikh en lo alto de la montaña. 

Aqui esta el link de la misión: http://es.wowhead.com/quest=25701

**Comment by Kiritoo** [comment]
Mal reportado.
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
