### ISSUE TITLE
[Misión] Tierras Devastadas - A algunas personas sencillamente hay que matarlas

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2037]
No está el Prospector Jefe Hondo que hay qe matar. Además de que no te puedes convertir con la caja para que te vean los demás como uno de ellos.

Aqui está el link de la misión: http://es.wowhead.com/quest=25681

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
