### ISSUE TITLE
Portales Monte Hyjal

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#204]
A partir del parche 4.2 se introducen portales para ir desde Monte Hyjal a Orgrimmar y Ventormenta

Official alliance mini-icon Portal to Stormwind City at Nordrassil (right side, outside of inn) 
Official horde mini-icon Portal to Orgrimmar at Nordrassil (left side, outside of inn) 

Fuentes:
http://www.wowwiki.com/Mount_Hyjal
http://www.wowhead.com/forums&topic=203146/portals

Pd: los comentarios del enlace de wowhead indican que se hicieron en la versión 4.3.4 y ahí afirman que hay portales para ir Ventormenta y Orgrimmar desde Monte Hyjal, Tierras Altas Crepusculares e Infralar, antes de que venga a decirme que se quitaron para el lanzamiento de mop.

**Comment by lamaza** [comment]
Tienes razón pero ahora lo que me pregunto es, hasta que punto se pueden hacer las quest man?. Gracias por esa persistencia =)

**Comment by ghost** [comment]
Pues eso ya no sé S:, en la versión anterior las cadena de misiones de Uldum, Hyjal e Infralar estaban todas arregladas, pero aqui si que no sé u.u

**Comment by redneo** [comment]
Cuando caiga el server lo teneis.
