### ISSUE TITLE
[Brujo] Bug debido al Talento de Diablillo potenciado

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#2040]
Veréis el caso es que este talento te da la probabilidad de sacar un fuego de alma instantáneo si tienes al diablillo en combate. El bug consiste en que este fuego de alma se puede lanzar repetidas veces durante los 8s que marca cuando en realidad cuando lo lances se debería disipar. Es decir, sólo debería poder lanzarse un fuego de alma instantaneo cada vez que salta.

No he encontrado al id en wowhead así que os dejo esta:http://cata.openwow.com/spell=47221

Aquí os dejo las fotos con la descripción y la foto de lo que pasa.

![wowscrnshot_091913_183242](https://f.cloud.github.com/assets/3939699/1174550/5e6a1136-2149-11e3-961d-18cb92b72daf.jpg)

![wowscrnshot_091913_183350](https://f.cloud.github.com/assets/3939699/1174551/668a0b1e-2149-11e3-811e-fb718bb838b5.jpg)

Un saludo y gracias

**Comment by Kiritoo** [comment]
Mal editado.
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by bagnamar** [comment]
No se fixx, pero a mi me parece bien repotado..
Quizas no sigue al pie de la letra tu guia, pero tiene descripcion, problema, enlace e imagenes con la descripcion..
Creo que estas siendo demasiado estricto con este reporte.

**Comment by Kiritoo** [comment]
Mira ves este reporte verdad https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2047
Haber si aprendemos a seguir una plantilla, que parece que no sabemos.
:(
