### ISSUE TITLE
[Bastion de Baradin] Occu'thar

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2041]
Ahora mismo entre medio de cada habilidad esta casteando Sombras abrasadoras, que lo que hace es dejarte un debuff de augmento de daño de las sombras de un 100%.  Por ejemplo ahora lo que haces es, tira sombras abrasadoras, tira fuego enfocado, vuelve con sombras abrasadoras, tira ojos, y vuelve con sombras abrasadoras. Aunqe vayas con 2 tanks, no les da tiempo a quitarse el debuff. 
Segun he podido leer y ver en diferentes vídeos y guías, lo que haces es poner las Sombras Abrasdoras --> Fuego enfocado --> Ojos. Así con el cambio de tanke, te da a que se te vaya el debuff, del augmenteo del daño.

Occu'thar = http://es.wowhead.com/npc=52363#encounter
Fuego enfocado = http://es.wowhead.com/spell=96884
Sombras abrasadoras = http://es.wowhead.com/spell=96913
Mirada de Occu'thar = http://es.wowhead.com/spell=96942

Espero haberme explicado bien, cualquier cosa no dudéis en preguntar.

**Comment by Ceslick** [comment]
Completando la información de Wiinter, actualmente tira unas 5-6 sombras abrasadoras antes de utilizar los ojos

**Comment by efectokoleos** [comment]
modificados los timer, ahora lanzara sombras cada 12 segundos, fuego enfocado 18 y ojos 33 segundos
