### ISSUE TITLE
[DK] Explosion Aullante

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2042]
ID: 49184
El skill lo nefearon esta pegando casi igual como si no tuviera ropa

![wowscrnshot_091913_120502](https://f.cloud.github.com/assets/3101842/1174575/b0f62b56-2149-11e3-9eb9-03a3534eaf7f.jpg)
![wowscrnshot_091913_120627](https://f.cloud.github.com/assets/3101842/1174583/cbf2a6d2-2149-11e3-9c08-98184b45c1ff.jpg)

Miesntra leia el skill me di cuenta de otro bug el objetivo recibe el daño principal miesntra que el resto que esten cerca solo reciben un 50% del daño de explosion aullante por ejemplo si pegara 10k al tarjet al resto que esten cerca le pegaria 5k

**Comment by Kiritoo** [comment]
Mal reportado, cierro.
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Nose para que hacemos una plantilla a seguir..
Tendre que seguir cerrando Issues o los editais o se crean de nuevo.
