### ISSUE TITLE
[DK] Explosion Aullante

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2045]
Nombre: Explosion Aullante
ID:49184
Descripcion: Golpea al Objetivo con Viento helado, Lo que inflije 6631p de daño de escarcha a ese enemigo y 3316p de daño de escarcha al resto de los enemigos en un radio de 10m

Problema:El hechizo esta pegando como si no tuviera nada de equipo. testee sin equipo pega 2k con equipo sigue pegando 2k

2do Problema: el objetivo recibe el daño principal miesntra que el resto que esten en un radio de 10m reciben la mitad de ese daño esto no esta sucediendo el resto de jugadores que esten cerca tambien reciben el daño como si fueran el tarjet

![wowscrnshot_091913_120502](https://f.cloud.github.com/assets/3101842/1174811/1bfe7bf2-214e-11e3-90b0-0ec7776c2e1a.jpg)

![wowscrnshot_091913_120627](https://f.cloud.github.com/assets/3101842/1174812/283b6f1a-214e-11e3-805f-b892c2ec2713.jpg)

**Comment by feniix97** [comment]
Seguimos esperando el fixeo de la explosión aullante por su daño nerfeado hace mas de dos meses y aun nada.
cuando se le podrá aumentar el daño? ya esperamos mas que mucho.

**Comment by feniix97** [comment]
Ojala ya se repare no puede ser que quite igual o menos que el toque helado del dk siendo escarcha, hoy lo probé y quita 3k,aun esta nerfeado pero al menos tiene 1k mas de daño,casi iguala el toque helado  :(

**Comment by feniix97** [comment]
si le aumentan el daño 6k mas el daño de explosión aullante al fin podría usarse y dejaría de estar bug.

**Comment by ghost** [comment]
Dejad el chateo por aquí. No se trata de aumentar el daño o disminuirlo, si no de arreglar la fórmula. Además, ya hay bastantes dks frost aprovechando el bug de la empuñadura como para que ahora peguen más con explosión...no lo veo tan urgente.

Fórmulas:
((1322 + 214) / 2) + (AP \* 0.44)p. de daño escarcha al objetivo y (0.5 \* (((1322 + 214) / 2) + (AP \* 0.44))) p. de daño escarcha a todos los demás enemigos en 10 yardas.

**Comment by Dekadencee** [comment]
@asman1 yo creo que la moderación, si se están reparando bugs (que estas totalmente equivocado, deja de repartir cosas que no son por el bugtracker o tendré que empezar a borrar tus comentarios) y lo que es prioritario o no, es cosa nuestra.

El spell estoy mirándolo actualmente, falla el primer efecto del daño al target, el segundo esta funcionando bien, ahora subo el fix.

Un saludo ^^

**Comment by ghost** [comment]
Como bien dije arriba, puse que <strong>YO</strong> no lo veía tan urgente (hay bastantes razones para pensarlo así), vosotros tendréis vuestra propia visión como es normal. Y no dije reparación de bugs (que obviamente los hay y también son necesarios), si no de bugs de clases, y en 1 mes y 3 días de estos fixes no había habido nada, es algo objetivo no subjetivo, sólo hay que ver el changelog.

De todos modos, soy el primero que se alegra de que se vayan fixeando los fallos de clases y que se hayan vuelto a retomar esta clase de fixeos, buen trabajo.

**Comment by Kiritoo** [comment]
Fix
