### ISSUE TITLE
[Misión](Las cámaras de Reflexión) - Las cámaras de Reflexión (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2049]
Buenas.
# Nombre: Las cámaras de Reflexión (lado Alianza)
# Enlace: http://es.wowhead.com/quest=24480
# Descripción: Lleva la Quel'Delar templada al Reposo de la Espada en las Cámaras de Reflexión.
# Problema: Aparece el PNJ Quel'delar (http://es.wowhead.com/npc=37158) pero por alguna razón no le puedo pegar para despojar Quel'Delar subyugada (http://es.wowhead.com/item=50254).
# Observaciones: Supuestamente la espada aparece al acercarse a Agonía de Escarcha durante el evento, combatir con ella antes de termine el mismo y que aparezcan los 2 bosses con los mobs. Probé con liquidar a los bosses y a los mobs primero, pero pasa algo raro con la mazmo que se resetea la pelea y vuelve a empezar haciendo imposible la tarea de despejar.

Gracias y hasta luego.

**Comment by redneo** [comment]
Arreglado, la espada sale al principio, se le puede atacar y lotear.
