### ISSUE TITLE
No se puede equipar mas de una cartera de ventormenta

### ISSUE THREAD

**Issue by isma1977** [RoDNet/Bugtracker-Infinium-4.3.4#205]
no es posible equipar ni transportar mas de una cartera de ventormenta, esto lo probé en varios personajes de diferentes niveles y razas.

**Comment by Varga9** [comment]
eso es normal, son objetos unicos, y por tanto solo puedes tener uno, a mi también me a pasado y me lo advirtieron.
la solución es comprar otros diferentes que no tengas, o comprarselos a alguien que haga bolsas

**Comment by isma1977** [comment]
gracias por el dato, aunque no me agrado mucho la noticia, pero bueno ahora mejorara el negocio de los sastres XD

**Comment by Dekadencee** [comment]
No es bug, realmente debe ser así, el bug estaba en la 406a

PD:

Aunque la noticia no sea de agrado para algunos, para mi si es de agrado saber que las cosas funcionan como deben, y para vosotros debería ser lo mismo...

No me gusta la actitud de que mientras se le pueda sacar provecho un error sea bienvenido, yo hace ya mucho tiempo que no juego a ningún game, pero amí me gustaba que cuantos menos errores mejor, me daba igual si fixeaban cosas a mi favor o en mi contra, me divertía jugando limpiamente...

**Comment by isma1977** [comment]
solo aclarar que no es que me guste aprovecharme de los errores, ahora parezco una mala persona hasta para mi mismo, simplemente que desde que comencé a jugar siempre funciono del mismo modo que creía el correcto y ahora me entero que no es así, si hubiera sabido que no estaba jugando limpio me hubiera quedado sin escribir nada evitando ponerme en tan penosa posición. 

a mi también me gusta jugar limpio aunque no lo parezca al leer esto.

**Comment by ghost** [comment]
@Dekadencee El problema, al menos en mi caso, es que las bolsas que me disteis con la migración eran así, todas iguales y por tanto ahora no puedo equiparlas. Por tanto, la raíz del problema son los objetos dados con las migraciones en esta ocasión.

**Comment by crowel** [comment]
Yo tengo las mismas mochilas de la migración @Lvmb y no puedo cojerlas del correo.
