### ISSUE TITLE
[Chaman-Mejora] Bug visual en el Poder con Hechizos

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#2052]
Buenas, no se muy bien como explicarlo, pero... Resulta ser que daño y me curo casi lo mismo que si tubiera o no ropa puesta (con mi chaman-mejora), con las habilidades que usan Poder con hechizos (Sp). La diferecia aveces es nula. 

Lo mas estraño es que, si miran mis estadísticas en las fotos de mas abajo verán que tengo casi 6k de Sp (con ropa). Incluso las habilidades que usan Sp, se puede leer en su descripción que obtienen ese aumento, pero al usarlas... Es como si no tubiera o hacen caso omiso de eso. 

Muchas gracias por leer el post. 

Cadena de Relampagos. Sin ropa
![c1](https://f.cloud.github.com/assets/4944904/1177226/f2c940a4-217b-11e3-9ef6-cf9c84f38284.jpg)

Cadena de Relampagos. Con ropa
![r1](https://f.cloud.github.com/assets/4944904/1177227/f2cdbdaa-217b-11e3-9edf-fcaf642f0cbf.jpg)

Rafaga de lava Sin ropa
![c2](https://f.cloud.github.com/assets/4944904/1177229/05eb28d2-217c-11e3-872c-7ab94161c557.jpg)

Rafaga de lava con ropa
![r2](https://f.cloud.github.com/assets/4944904/1177230/06054118-217c-11e3-8180-796ec2234eb3.jpg)

Ola de sanacion superior sin ropa
![c3](https://f.cloud.github.com/assets/4944904/1177237/19424168-217c-11e3-823a-7fb0367897ce.jpg)

Ola de sanacion superior con ropa
![r3](https://f.cloud.github.com/assets/4944904/1177238/1947ca66-217c-11e3-8dc1-bbf584682756.jpg)

Sanacion en cadena sin ropa
![c4](https://f.cloud.github.com/assets/4944904/1177240/2d62c122-217c-11e3-96af-59ad19f87581.jpg)

Sanacion en cadena con ropa
![r4](https://f.cloud.github.com/assets/4944904/1177241/2d638a80-217c-11e3-9310-d0f376085489.jpg)

Choque de tierra sin ropa
![c5](https://f.cloud.github.com/assets/4944904/1177243/3c92a658-217c-11e3-99f1-3e387793ff31.jpg)

Choque de tierra con ropa
![r5](https://f.cloud.github.com/assets/4944904/1177244/3cb1bfe8-217c-11e3-963d-8fd5c498083e.jpg)

Choque de llamas sin ropa. (id: 8050)
![c6](https://f.cloud.github.com/assets/4944904/1177246/4e72a0da-217c-11e3-9d45-8645a7fa0f18.jpg)

Choque de llamas con ropa. (id: 8050)
![r6](https://f.cloud.github.com/assets/4944904/1177247/4e8f8be6-217c-11e3-9019-54b5f79ff242.jpg)

Choque de escarcha sin ropa
![c7](https://f.cloud.github.com/assets/4944904/1177258/75db815a-217c-11e3-9175-4b43983281ca.jpg)

Choque de escarcha con ropa
![r7](https://f.cloud.github.com/assets/4944904/1177259/75fb64fc-217c-11e3-8c5a-e3641049597a.jpg)

Nova de fuego sin ropa
![c8](https://f.cloud.github.com/assets/4944904/1177264/88386534-217c-11e3-8ebf-923ae8201929.jpg)

Nova de fuego con ropa
![r8](https://f.cloud.github.com/assets/4944904/1177265/883f4368-217c-11e3-877b-350a206fe75b.jpg)

**Comment by lamaza** [comment]
Espero puedan reparar el chamy :) https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1906

**Comment by Kiritoo** [comment]
Esto lleva arreglado mucho tiempo.
