### ISSUE TITLE
[Druida] Quita Ralentizar (Cambia formas)

### ISSUE THREAD

**Issue by harusen** [RoDNet/Bugtracker-Infinium-4.3.4#2054]
Hola quiero escribir que estando jugando con mi feral he notado que al cambiar de forma no me quitaba los ralentizars, al comentarlo habia gente q decia q solo se los quitaban los heals, esto es erroneo, los heals se quitan inmovilizados, pero los slows te los quitas al cambiar de forma.  En la descripción de cambia formas lo pone (no me lo estoy inventando) 

enlace de Wowhead de la descripción del cambiaformas   http://www.wowhead.com/spell=40120

cita a pagina oficial del wow

respuesta del segundo usuario de la pregunta 3

http://eu.battle.net/wow/es/forum/topic/1776517947

ahi se explica (inmovilizados no, ralentizars Si)

Muchas gracias por su atención

**Comment by ghost** [comment]
Buenas, sólo un reporte por issue.

Cómo reportar un bug:

http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
