### ISSUE TITLE
Error en items de monedas

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#2056]
Algunas monedas que dan en algunas bolsas como Premio de cocina de Dalaran o Sello de Campeón al cogerlas de la bolsa se te quedan en el inventario como un item en lugar de contártelas en la pestaña de monedas.

PD: creo que esto no puede ponerse una ID ya que es un error interno.

**Comment by searum** [comment]
http://old.wowhead.com/currencies

Con sus respectivas ids de currencies.

Y no, no es un error interno, es un error de currencies. (al menos yo no lo veo como interno). En realidad estarán usando los antiguos sistemas del TBC, WotLK que eran items en vez de monedas como ahora.

Facilitando las ids de las bolsas seria mucho mas facil ^^

**Comment by elmiriox15** [comment]
Premio de cocina de Dalaran currency=81
Sello de Campeón currency=241

Seguramente haya más pero yo solo he visto estas por ahora.

**Comment by searum** [comment]
Facilitando las ids de las bolsas seria mucho mas facil ^^

**Comment by elmiriox15** [comment]
Bolsa de especias: http://es.wowhead.com/item=44113
Monedero de Campeón: http://es.wowhead.com/item=45724
