### ISSUE TITLE
[NPC] Belbi Tiratrastos

### ISSUE THREAD

**Issue by didiii** [RoDNet/Bugtracker-Infinium-4.3.4#2057]
http://es.wowhead.com/npc=23710/belbi-tiratrastos#.

El problema es que no deja ver las cosas que vende, le das click y no aparece nada

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.

**Comment by lamaza** [comment]
En la alianza si que deja ver lo que vende.

**Comment by didiii** [comment]
ya lo fixeaste
