### ISSUE TITLE
[Logro] Fiesta de la Ceveza - Abajo los Hierro Negro

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2059]
http://es.wowhead.com/achievement=1186

Vienen a atacar unos enanos a la feria de la cerveza cada media hora y dejan una misión(http://www.wowhead.com/quest=12192) en el centro de la plaza, para poder conseguir el logro.

No está la misión (http://www.wowhead.com/quest=12192)y tampoco los enanos atacan al poblado.

**Comment by lamaza** [comment]
http://www.youtube.com/watch?v=fYTmmSFFefk

**Comment by redneo** [comment]
La mision se puede conseguir
