### ISSUE TITLE
[Banda] Funciones de banda 

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#206]
Cuando un jugador selecciona la funcion de la que va a ir en la banda, no se ve reflejada en su nombre.

![wowscrnshot_070513_160535](https://f.cloud.github.com/assets/4895839/755612/d53d34fa-e5b7-11e2-88c2-a9c19def4405.jpg)

Deberia estar la funcion al lado del nombre.

**Comment by Dekadencee** [comment]
Te refieres al lado de los nombres que se reflejan en Grupo 1, Grupo 2... ?

**Comment by SherBlader** [comment]
si, esos nombres.

de los dos grupos, casi todos se colocaron funcion, y al lado de su nombre no se veia ni la espadita pequeña ni el escudo pequeño ni la cruz pequeñita

**Comment by ghost** [comment]
Sigue sin funcionar, deberían de aparecer los iconos de cada función al lado de los nombres.

**Comment by Dekadencee** [comment]
Fixed
