### ISSUE TITLE
[Druida] Cambia formas

### ISSUE THREAD

**Issue by harusen** [RoDNet/Bugtracker-Infinium-4.3.4#2060]
Perdon antes cerre el post que hice por desconocimiento de como funciona lo vuelvo a poner y q alguien borre el otro

Hola quiero escribir que estaba jugando con mi feral y he notado que al cambiar de forma no me quitaba los ralentizars, al comentarlo habia gente q decia q solo se los quitaban los heals, esto es erroneo, los heals se quitan inmovilizados, pero los slows te los quitas al cambiar de forma. En la descripción de cambia formas lo pone (no me lo estoy inventando)
ademas he probado q los helas tampoco se quitan el ralentizar.

enlace de Wowhead de la descripción del cambiaformas http://www.wowhead.com/spell=40120  http://es.wowhead.com/spell=768

cita a pagina oficial del wow

respuesta del segundo usuario de la pregunta 3

http://eu.battle.net/wow/es/forum/topic/1776517947

ahi se explica (inmovilizados no, ralentizars Si)

Muchas gracias por su atención

**Comment by lamaza** [comment]
Esto es lo que he encontrado yo: 

---

4.0.6

http://us.battle.net/wow/en/game/patch-notes/4-0-6

Restoration
Disentanglement (new specialization): Causes shapeshifting to remove roots in addition to snares.

---

4.1

http://us.battle.net/wow/en/blog/2356431#druids

Feral Swiftness now also causes Dash and Stampeding Roar to have a 50/100% chance to instantly remove all movement impairing effects from the affected targets when used.

**Comment by harusen** [comment]
Vale eso también, pero http://es.wowhead.com/spell=768 cambio forma quita ralentizar, lo pone en la misma descripción de la habilidad joder.

**Comment by lamaza** [comment]
Pero lo de wowhead es de pandaria. 

Dejo esto igual, http://www.wowwiki.com/Feral_Swiftness.

**Comment by harusen** [comment]
OH Dios, métete en el juego y lee la put***\* descripción de la habilidad antes de hablar de lo que no sabes.....

Por comentarios como este la gente se cree q el druida no se quita las ralentizaciones, poniendolo en la descripcion in-game

**Comment by Cacafuti** [comment]
Harusen tiene razon, los ralentizar se devén poder quitar , lo pone en las descripciones de todas las formas.

**Comment by Oscarin** [comment]
hace dos semanas estube diciendo a varios druidas ferales que se estavan beneficiando del talento 96429 y hubo mucha gente k empezo a lamarme noob i mas cosas... nose como lo arian pero sucedia,quiza sea al cambiar talentos de heler a feral,pero el druida feral no se quita decargas de escarcha que relentizan o nova de escarcha tan solo cambiando formas... para eso estan los cds.

hice una captura de en el juego con la descripcion de la spell por que en wowhead esta la descripcion de pandaria
http://subefotos.com/ver/?178eca1583ec45d4a2654e48b930ea41o.jpg

**Comment by lamaza** [comment]
http://www.wowwiki.com/Druid

For all forms, the following applies:
Shapeshifting also breaks all movement-impairing effects (like Slow or Hamstring) except the 3-second daze that can proc when one is attacked from behind by a melee attack.

A pesar de la groceria y estupidez  de Harusen haciendo reclamos, el cambiar de forma si debe quitar ralentizaciones, solo eso.

**Comment by searum** [comment]
cuando os aclareis y dejeis de discutir como crios me decis que cojones pasa y lo arreglo pero lo que no podeis hacer es seguir mareandome cada dia con 1 cosa, sabeis perfectamente que yo no juego...

**Comment by druidaaaaa** [comment]
Bueno con respecto a lo que menciona harusen se refiere a que el talento desenredo esta 50% bien ya que antes los druidas ferales podían quitarse todo me refiero a frenados realentizaciones, cuando eso solo lo puede hacer un druida restauración, no se que le hicieron pero lo arreglaron al 50% ya que ahora los ferales ya no se pueden quitar espinas y eso esta bien pero los restauración están jodida mente mal ya que los pueden detener con tótem de chaman el destrozar de druida te realentiza y no te lo quitas ni cambiando d forma. 

y a lo que pelean arriba el druida cambiando de forma ya sea feral, caster , o resto. se quita realentizaciones pero no frenados como por ejemplo raíces enredadoras o cuando t congela el piso un mago

**Comment by druidaaaaa** [comment]
porfa searum checalo por que a los restauración nos sirve de mucho. y mas cuando ves pj alianzas tirando rayo solar bug spell=78675 pero tu eres el jefe suerte ojala lo arreglen

**Comment by harusen** [comment]
bueno quiza haya juzgado mal a lamaza, pensaba q no ibas a entrar en razon sorry xD

Es como yo digo y lamaza afirma. Un feral y un balance se quitan ralentizaciones, tanto de magos (descarga de escarcha, ralentizar, heridas infectadas...pero No Raices, ni Novas)

Simplemente porque la spell de cambio de forma lo pone y asi debe ser

El heal tiene una pasiva por ser heal, Desenrredo que quita ademas de lo ya mencionado, raices novas, seccionar mejorado ( es decir todo las habilidades que Fijan al Suelo (comunmente llamadas raices))

por lo que Druidaaaaaaaa estas equivocado ferales tmb nos quitamos ralentizar, mira la descripcion ingame de forma del oso y lo veras.

y Oscarim  que tengamos habilidades q nos quiten ralentizar, que las tenemos, no significa q no tengamos mas formas de quitarlos, te digo lo mismo q a druidaaaaaaaa   mira in-game la descripcion de forma de oso, ahi pone q te quitas ralentizars estando en CUALQUIER rama del Druida.

grax por prestar atencion al post y siento si he ofendido a alguien.

**Comment by lamaza** [comment]
El druida antes de cata, se quitaba todo siendo cualquier spec. Ahora solo se quitan los ralentizar al cambiar de forma. 

Cual es el bug? Que no esta quitando los llamados" movement-impairing effects" al usarlo.

**Comment by Cacafuti** [comment]
El bug es que el druida en general no se puede quitar el ralentizar combiando de forma, ni feral ni resto ni nada, eso es lo que esta bug y es lo que Harusen pide, que arreglen los cambios de forma, ya esta nada mas. El bug esta bien claro, y en el juego lo pone, que al cambiar de forma , los ralentizar desaparecen, y ya esta no hay que darle mas vueltas.

**Comment by harusen** [comment]
amen

**Comment by lamaza** [comment]
eso ya lo habia dicho yo XD

**Comment by druidaaaaa** [comment]
listo xfin lamaza haces esto mas dificil esperemos que searum lo arregle pronto ya k la horda lo necesita

**Comment by ghost** [comment]
Wow, vaya discusión, pensaba que esto estaba más que aclarado con Searum xD vaya lío le habéis montado.
- Shapeshift base (feral/pollo): Elimina ralentizaciones, y NO roots.
- Shapeshift en restauración con el talento Desenredo: Elimina ralentizaciones Y roots.

**Comment by harusen** [comment]
bueno, yo creo q ya esta aclarado del todo.

-nos quitamos slows con cambio forma. fin

para cuando lo arreglan? xD

**Comment by searum** [comment]
para cuando a mi me de la gana! :)

fix. XD

**Comment by lamaza** [comment]
Gracias!
