### ISSUE TITLE
[joyeria] engarce de joyero

### ISSUE THREAD

**Issue by ruben312** [RoDNet/Bugtracker-Infinium-4.3.4#2063]
este ítem necesario para acabar de subir la profesión lo deberían de vender los instructores o vendedores de suministros, pero no lo hacen.

**Comment by searum** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by redneo** [comment]
Ni una id ni un enlace ni nada. Cierro sin arreglar
