### ISSUE TITLE
[Mago] Hechizos que se silencian inexplicablemente

### ISSUE THREAD

**Issue by moriaar** [RoDNet/Bugtracker-Infinium-4.3.4#2064]
El mago, al menos el mago arcano, cuando está casteando un hechizo y recibe daño, se silencia inexplicablemente, la mayoría de las veces no puedo usar un hechizo como explosión arcana porque nada más que me atacan se corta el lanzamiento lo cual es un gran fallo.

Da igual si tengo o no tengo puesta la burbuja, se silencia, y también da igual si es un golpe con hechizo o de cerca.

**Comment by lamaza** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/ 

Leete eso ya que no sabes reportar.
