### ISSUE TITLE
[Mago] Cooldowns que duran más de la cuenta

### ISSUE THREAD

**Issue by moriaar** [RoDNet/Bugtracker-Infinium-4.3.4#2065]
Me pasa con el mago arcano y desde que active el talento de ralentización con explosión arcana. Cuando al usar Explosión Arcana se ralentiza al objetivo automáticamente por el talento, el Cooldown de todos los hechizos dura más, aunque en el juego te señale que el hechizo vuelve a estar operativo, la realidad es que hasta pasado un par de segundos más no puedes a volver a usarlo, pero no sólo el hechizo que acabas de utilizar, sino cualquier hechizo.

**Comment by lamaza** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

Leete eso, ya que no tienes idea de como se reporta :/

**Comment by ghost** [comment]
Creo que es un problema general con la rama arcana, yo soy fuego y me pasa igual con los hechizos de Crear refrigerio, se supone q tarda 2.8s en castearse, pero no te deja hacer nada cuando acabas si no dejas un margen, por lo que el tiempo de casteo "real y oculto" es de 3.

**Comment by Monleon** [comment]
Ese gcd interno ya no debería seguir existiendo
