### ISSUE TITLE
Misión "El Drakkensryd"

### ISSUE THREAD

**Issue by karmmero** [RoDNet/Bugtracker-Infinium-4.3.4#2066]
En esta misión hay que montar sobre un draco y usar el arpón (el objeto de la misión) sobre los jinetes de dracos. El problema es que al intentar montar, no lo hace y caes al vacio. Tampoco funciona si consigues matar normalmente a los objetivos.

link de la misión: http://es.wowhead.com/quest=12886/el-drakkensryd

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

Puse killcredits al rededor de la zona
