### ISSUE TITLE
Pérdida de Escudo

### ISSUE THREAD

**Issue by Centinela-zz** [RoDNet/Bugtracker-Infinium-4.3.4#207]
Me ha desaparecido el escudo en la actualización del servidor.

Tenía el escudo "Akmin-Kurai, El escudo de dominio" (la Versión heroica). Lo conseguí a través de donaciones. La ID es 65023.

Gracias por todo de antemano.

**Comment by 50megas** [comment]
¿miraste en el correo? ami todo lo que me desaparecio me llego por correo

**Comment by lamaza** [comment]
No se preocupen, harán roll back a como estábamos en 4.0.6, si algo desaparece después de eso, ahí si preocupense.

**Comment by Centinela-zz** [comment]
Sí, tengo el correo más que revisado. Por cierto, también tengo un ticket ingame. Lo mismo el sistema de tickets tampoco funciona porque no me han contestado ni borrado el ticket tampoco. PD: mi pj es Caesar

**Comment by ghost** [comment]
Tengo entendido que Dekadence ya te lo dio.
