### ISSUE TITLE
[DK] Sabañones

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2070]
Nombre: Sabañones
ID:50040/50041

Descripcion: Las victimas de tu fiebre de escarcha quedan congeladas, lo que reduce su velocidad de movimiento en un 50% durante 10s, y tus cadenas de hielo inmovilizan a los objetivos durante 3s 

Problema:Cadenas de hielo solo esta inmovilizando el objetivo 1.5s deberian de ser 3s en rango 2. El rango 1 funciona perfect

2do Problema: Fiebre de escarcha no esta reduciendo la velocidad de movimiento solo esta funcionando con toque helado y deberia de funcionar tambien con Explosion aullante (con glifo que aplica fiebre de escarcha), Brote que aplica fiebre de escarcha, Cadenas de hielo y Pestilencia que propaga fiebre de escarcha. esto pasa en el rango 1 y rango 2

Fiebre de Escarcha: 59921
Explosion aullante: 49184
Brote: 77575
Pestilencia: 50842
Cadenas de hielo:45524

**Comment by searum** [comment]
si fueras mas preciso a la hora de reportar en vez de tener que abrir un reporte por rango de talento, si sabes que un talento tiene 3 rangos dame las ids de los 3 rangos o 2 o los que sean asi terminamos antes y no perdemos el tiempo ni tu reportando ni yo leyendo 20 veces XD

http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by searum** [comment]
fix
