### ISSUE TITLE
[DK] Huesos Quebradizos

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2071]
Nombre: Huesos Quebradizos
ID:81327/81328
Descripcion: Tu fuerza aumenta un 2%/4% y tu fiebre de escarcha congela los huesos de sus victimas, lo que aumenta el daño fisico que reciben un 4%

Problema:El debuff que aumenta el daño fisico recibido deberia de aplicarse al enfermar al objetivo con fiebre de escarcha solo esta funcionando con toque helado y deberia de funcionar tambien con Explosion aullante (glifo de fiebre de escarcha) Brote y Pestilencia ya que estos tambien enferman a los objetivos con fiebre de escarcha

Fiebre de Escarcha: 59921
Explosion aullante: 49184
Brote: 77575
Pestilencia: 50842
Cadenas de hielo:45524

**Comment by searum** [comment]
fix
