### ISSUE TITLE
[DK] Profanacion

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2073]
Nombre: Profanacion
ID:55666/55667
Descripcion: Tu golpe de peste, golpe de la plaga y Golpe necrotico profanan el suelo en un radio de 7m alrededor del objetivo. Los enemigos dentro de la zona se relentizan un 50% Mienstra permanecen sobre suelo profanado. No se activa contra objetivos inmunes a los efectos de relentizacion dura 20s.

Problema: Solo esta aplicando el efecto con Golpe de peste y Golpe de la plaga deberia de tambien funcionar con golpe necrotico lo cual no esta haciendo...

Golpe Necrotico: 73975

**Comment by searum** [comment]
fix
