### ISSUE TITLE
[misiones - cerveza] Traga y Tira

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#2077]
http://es.wowhead.com/quest=12022

La presente misión no la podemos hacer, el npc http://es.wowhead.com/npc=27215 no nos la da y no esta tampoco el robot http://es.wowhead.com/npc=24108 del evento.

![wowscrnshot_092113_181407](https://f.cloud.github.com/assets/4790547/1186654/daa29220-2313-11e3-807c-ae0b33bb1969.jpg)

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

Esta mision funciona correctamente, vi como la estaban haciendo unos cuantos personajes... (vale, falta el npc) pero si que la da.

**Comment by lamaza** [comment]
Como la vamos a hacer en la Alianza, si ni siquiera la dan :/. Y nunca antes la hice.

**Comment by redneo** [comment]
![wowscrnshot_092313_082445](https://f.cloud.github.com/assets/1163425/1189588/f4362b06-2418-11e3-9c00-6d9aa476b92f.jpg)

Pj sin misiones por ningun lado.

**Comment by redneo** [comment]
y si, en la base de datos la marca como que ya la has hecho.
