### ISSUE TITLE
[misiones - cerveza] La cerveza temible de Cerveza Temible

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#2078]
http://es.wowhead.com/quest=12491#english-comments

El objeto http://es.wowhead.com/item=38280 al ser clickeado no hace nada, no nos da la misión.

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

me remito al post anterior... y mi pregunta es... no la tendrás hecha de otras ediciones?¿

**Comment by lamaza** [comment]
Nop.
