### ISSUE TITLE
talento picaro bug

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#208]
el talento del picaro http://es.wowhead.com/spell=58423 no salta nunca,deveria de dar 25 de energia con un 20% de posivilidades en los remates finales

un saludo

**Comment by hairblood** [comment]
verificado:no sirve dicho talento ni con 1 ni con 5
osea nunca te da los 25 energia

**Comment by 50megas** [comment]
parece que esta solucionado
