### ISSUE TITLE
[Paladin-Retribucion] Palabra de Gloria

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#2082]
Buenas. Quiero reportar que la spell "Palabra de Gloria" Id= 85673.Realiza las sanaciones un poco alteradas. 

Caso 1 con 3 cargas de poder sagrado.

Si la usas en ti te sana la mitad (9k)

![3 cargas](https://f.cloud.github.com/assets/4944904/1186741/654f1fd6-2320-11e3-9e53-2715f50a2f8b.jpg)

... y si la usas en otro player cura normal (20-22)k, esto con las 3 cargas de poder sagrado.

![3 cargas otros](https://f.cloud.github.com/assets/4944904/1186744/74441a82-2320-11e3-9278-f979569bd412.jpg)

Caso 2

Si tienes activado propósito divino (El talento que te permite que tu próxima habilidad que use poder sagrado se use como si tuvieras 3 cargas). Sana normal, ya sea que la uses en ti o la uses en otro player. (20-22)k.

Caso 3

Si tienes 2 carga de poder sagrado, y se activa el propósito divino. Te curas (30k)

![2 cargas proposito](https://f.cloud.github.com/assets/4944904/1186749/aa76f8ae-2320-11e3-9fcb-84f7201f4287.jpg)

...y si llegas a curar a otro player... Realizas una SUPER SANANCION con critical de hasta 160k... Pero en general sana de (60-70)k sin critical. Si salta critical puedes tener a tu compa en arenas full cada 10 seg, cosa no muy buena cierto.

![2 cargas proposito a otro](https://f.cloud.github.com/assets/4944904/1186750/b50b567a-2320-11e3-9044-5b4834b179bb.jpg)

Nota 1: Eh probado curando a todas las clases bajo esos efectos y siempre salen esas SUPER SANACIONES. 

Nota 2: Como verán todos los datos son sin criticos... Eh sacados curas mientras testeaba el caso 3 de hasta 160k con critical a otros players y desde de hasta unos 60k a mi mismo. Sin las alas... Si me pongo las alas saquen ustedes mismos sus conclusiones.. 30% mas de sanacion. Mas que cualquier heal, incluso mas que con imposición.

Nota 3 (OJO AQUÍ): Propósito divino no pone full tu barra de cargas sagradas (momentáneamente mientras dura el efecto, o utilizas una habilidad que consuma el poder sagrado). Sino que te permite seguir generando poder sagrado mientras tienes el efecto, cosa que no debería (No pone tu barra al tope, pero si puedes usar tus spell como si tubieras 3 cargas), mientras te permite seguir generando poder sagrado. Lo que también sugiere que dicha spell también presenta irregularidades.. 

Nota 4: El unico spell que se beneficia del caso 3 es Palabra de gloria. He Probado con veredicto templario a ver si pegaba mas y no, también con inquisición a ver si duraba mas tiempo y no. Solo le afecta a Palabra de gloria Id: 85673

Nota 5: Me eh puesto equipo de heal en retry y me cure con 3 cargas sin proposito divinio.. Me curo 22-24k. Al parecer el SP afecta la palabra.. Pero como no se la formula de la spell no puedo dar mas detalles, aunque me han dicho que en retry la formula incluye AP... (No confirmado)

POSIBLE CAUSA

Mi opinión referente al caso 3
(2 cargas de poder sagrado+ Propósito divino)

Como yo lo veo, las cargas se están sumando. En otras palabras lo poco que sano con 2 cargas y lo que curo normal con el propósito, me están cuadrando en los cálculos. Y también eso me explica porque le estoy sanando tanto a otros players.

Lo único que no me cuadra es porque me curo ami mismo la mitad que a ellos, con las 3 cargas y si curo lo mismo tanto a ellos como ami, con el propósito divino activado.

Muchas gracias por su atención.

**Comment by bagnamar** [comment]
El talento sanación desinteresada (ID:85804) hace que se aumente un 50% la sanación de palabra de gloria a aliados. 

Una cosa que quiero aclarar es que en el caso 2 si solo tienes proposito divino activo sin ninguna carga de poder sagrado, curas 20k aprox a un aliado, pero a ti te curas 10k (actua exactamente como si tubieras 3 cargas), en cambio cuando tienes el proposito y 1 sola carga, a ti te cura 20k y al aliado 40k, en ningun caso cura lo mismo al paladin que al aliado.

Segun mis testeos:

Hacia uno mismo: 
10k aprox 3 cargas o proposito divino
20k aprox proposito + una carga 
30k aprox proposito divino + 2 cargas,

Hacia aliado: 
20k aprox 3 cargas o proposito divino
40k aprox proposito+ una carga
60k aprox proposito + 2 cargas

Mi conclusion es:
1. El talento de sanación desinteresada esta bug i ace que se cure 100%+ en lugar de 50%+ a un aliado.
2. Al tener una carga + proposito divino, la carga actua como 3 cargas que sumadas al proposito hacen un total de 6 cargas. En cuanto a 2 cargas + proposito, lo mismo, cada una de esas 2 cargas actua como 3 que sumandolas al proposito hacen un total de 9.
3. En cuanto a palabra de gloria en si por aplicacion de carga, cura menos de lo que deberia (en la descripcion sale 4,4k por carga y cura unos 3k aprox) pero como la cura se realiza con 9 cargas (apartir de los 3k aprox) y hacia aliados esa cura es doble, es cuando salen esas cifras.

**Comment by bagnamar** [comment]
Confirmo que efectivamente el talento sanacion desinteresada esta bug, debe aumentar la sanacion de palabra de gloria a aliados 25% (rango 1) y 50% (rango 2). Actualmente aumenta esta sanacion 50% y 100%.
Quizas este talento bug debe ir en otro issue y mejor reportado pero pongo esto aqui por que forma parte del bug que se reporta.

**Comment by searum** [comment]
fix gracias a bagnamar porque si por ti fuera moya no me enteraba de nada xD
