### ISSUE TITLE
[Paladin] Destello de Luz

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2084]
Nombre: Destello de luz
ID:19750
Descripcion: Una sanacion rapida y costosa que sana a un objetivo amistoso 10513p  

Problema: El casteo se esta cortando constantemente por los jugadores hasta con un dot de destripar me cortar cast.

**Comment by searum** [comment]
era el talento ojo por ojo
