### ISSUE TITLE
[Paladin] Luz Divina

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2085]
Nombre: Luz Divina
ID: 82326
Descripcion: Una sanacion que sana a un objetivo amistoso 16085p.Buena para periodos de mucho daño

Problema: El casteo se esta cortando constantemente por los jugadores hasta con un dot de destripar me cortar cast.

**Comment by searum** [comment]
A ver tio, si es un bug generalizado de spells de casteo... Ponlo todo junto no me hagas mirar spell por spell.

Juntalo todo en uno y cierra los que has abierto con lo mismo please..

Ademas de que das muy poca información, seguramente sea por algun talento pero como no se ni que spec tienes ni nada...

**Comment by searum** [comment]
era el talento ojo por ojo
