### ISSUE TITLE
[Paladin] Señal de la Luz

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2086]
Nombre: Señal de la luz
ID:53563
Descripcion: El objetivo se convierte en una señal de la luz para todos los jugadores en un radio de 60m. Tu palabra de Gloria, Choque Sagrado, Destello de luz, Luz de alba y luz divina Tambien sanaran a la señal de la luz  un 50% de la cantidad sanada. Luz Sagrada sanara un 100% de la cantidad. solo un objetivo puedes ser la señal de la luz a la vez dura 5 min.

Problema: Todo funciona bien menos Choque sagrado deberia tambien de curar un 50% de la cantidad sanada a la señal de la luz y no lo esta haciendo.

Choque Sagrado:20473

**Comment by searum** [comment]
esto a mi me funciona
