### ISSUE TITLE
[DK] Parasito de Sangre

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2088]
Nombre: Parasito de sangre
ID Parasito de sangre: http://es.wowhead.com/npc=42850
ID Atracarse de sangre: es.wowhead.com/spell=81277/
Descripcion: El gusano de sangre se atiborra de la sangre succionada a sus enemigos, lo que le da una probabilidad aumentada de reventar para sanar a los aliados cercanos. el buff cura un 10% de la salud maxima del gusano tras reventar se acumula hasta 10 veces

Problema: Tras reventar el gusano no esta curando nada.
Observacioones: Esta curando por los ataques cuerpo a cuerpo que realiza, Me parece que tiene el daño muy poco 50p a un muñeco,

Informacion adicional de wowhead:
Here's what I got about this spell.

```
Bloodworms have aprox 35% of your current health when summoned.
The worms explode on death, or when their 20-second lifespan ends. However, they won't pop if they are out of combat.
You can have many worms at the same time (never had more than 4 at the same time, and having more than two is quite rare), but one hit can't summon multiple worms.
This needs further testing, but I believe the worm's explosion heals the whole raid for X*10% of its life when it died, X being the number of stacks of Blood Gorged when the worm is killed.
Each time the worm hits, he gets a stack of Blood Gorged, wich determines the amount healed by his explosion. There is no stack limit.
My worms hit for around 200 damage ; I have 4K attack power.
The worms have an attack speed around 1.35 seconds per hit.
Usually, these worms stack around 5 stacks of Blood Gorged before dying.
The worms' heal can be critical.
```

**Comment by ghost** [comment]
Ok entonces el gusano debería hacer el 5% de daño del DK? o hace 200 de daño sin ninguna fórmula?

**Comment by F4NT4SM4** [comment]
estube buscando y no conseguir nada eso fue lo unico q vi :l

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Enlace: Enlace necesario a http://es.wowhead.com o http://old.wowhead.com, no solo el ID.

**Comment by searum** [comment]
fix
