### ISSUE TITLE
[DK] Escudo de Sangre

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2089]
Nombre: Escudo de Sangre
ID:77513
Descripcion: Cada vez que te sanas con golpe letal miesntras estas en precensia de sangre, ganas un 50% de la cantidad sanada (con maestria base) como escudo de absorcion de daño. cada puntos de maestria aumenta el escudo un 6.25% extra

Problema: me curo 9888 con maestria base 50% tengo un 4944 de absorcion bien pero
aumente mi maesria a 10.25 ahora hago una absorcion de 64% el escudo pasaria a absorber unos 6328 pero estoy absorbiendo 4958. En ves de absorber 12.50% mas estoy absorbiendo la misma cantidad pero sumando un 12.50 me imagino que es eso 4944-4958 son 14 de diferencia pienso yo. yo de estas cosas nose mucho a si que capas me equivoque en el problema y sea otro

**Comment by searum** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1471
