### ISSUE TITLE
[Sacerdote] Maligno de las Sombras

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#209]
El único inconveniente que tiene el maligno de las sombras, es que no aparece la barra de acciones para poder controlarlo.

Enlace: http://es.wowhead.com/spell=34433

![wowscrnshot_070513_182920](https://f.cloud.github.com/assets/4663665/755788/fbd564ba-e5c2-11e2-8729-7599dbb932bc.jpg)

**Comment by ghost** [comment]
Buenas.

Que yo sepa el maligno de las sombras nunca ha tenido una barra de poderes... Ya que sólo hace autoatack xD A parte dura 15sec, para qué quieres una barra de poderes? Ya que ataca a tu objetivo o a los objetivos cercanos para darte mana. 

Un saludo.

**Comment by ghost** [comment]
El maligno de las sombras si tiene barra de poderes porque es un "esbirro", no un "guardian", la barra de poderes nada más sirve para hacer que ataque al objetivo que quieres, algunas veces "se vuelve loco" y se va para cualquier lado menos hacia tu objetivo xd.

**Comment by ghost** [comment]
Vale, si, tienes razón, lo acabo de mirar en una imagen en google xD Pues nunca me había fijado en que debería haber una barra :S

**Comment by crowel** [comment]
Tambien tiene un problema que se puede reutilizar antes del tiempo que marca.

**Comment by ghost** [comment]
Si puedes dar mas detalles sobre se problema crowel, hay un talento llamado pecado y castigo que reduce el cd de maligno de las sombras... tal vez sea eso aunque no lo creo porque no funcionaba el talento la última vez que lo probe.

**Comment by ghost** [comment]
Por que cerraste esto redneo? S: sigue bug.
