### ISSUE TITLE
Hunter Bestias Disparo de Cobra se interrumpe solo

### ISSUE THREAD

**Issue by 3du42d0** [RoDNet/Bugtracker-Infinium-4.3.4#2090]
Hola quería informar que el disparo de cobra en la rama bestias suele interrumpirse mucho sin motivo lógico en una rotación, sucede más seguido cuando en la rotación se incluye enfocar fuego.

**Comment by searum** [comment]
Reporta bien si vas a reportar algo, molestate en investigar el fallo.

He probado con un hunter BM y me va perfectamente, no hay ningun fallo en esa rama. Prueba a quitarte talentos que tengas en otras ramas y ver si sigue cortandose el casteo, si al añadirte X talento se te corta entonces ya sabemos donde esta el fallo. Vienes, lo reportas y lo arreglo.
