### ISSUE TITLE
[Errores de clase/pjs] Cazador- llamar a la pet

### ISSUE THREAD

**Issue by Edwuard** [RoDNet/Bugtracker-Infinium-4.3.4#2091]
resulta que al crear un cazador la pet aparece al lado pero no aparece su barra de skill, cuando relogeas la pet desaparece y al llamarla no aparece nunca mas... empese con un humano cazador y no puedo llamar a la pet pues al hacerlo esta no aparece...

saludos

**Comment by Monleon** [comment]
Al crear un hunter hay que abandonarla, borrar caché,  capturar otra y ya se soluciona el problema
