### ISSUE TITLE
[misión] Bosque Canción Eterna - Sed insaciable

### ISSUE THREAD

**Issue by BeverManuel** [RoDNet/Bugtracker-Infinium-4.3.4#2092]
<hr>

• <strong>Nombre: </strong>: <a href="http://es.wowhead.com/quest=8346">Sed insaciable</a>
• <strong>Enlace: </strong>: <a href="http://es.wowhead.com/quest=8346">http://es.wowhead.com/quest=8346</a>
• <strong>Descripción:</strong>: Habla con <a href="http://es.wowhead.com/npc=15297">Arcanista Helion</a> en Bosque Canción Eterna, busca a criaturas con maná y desata tu Torrente Arcano sobre ellas.
• <strong>Problema: </strong>: Al utilizar el Torrente Arcano sobre las criaturas de maná no se completa la misión.

<hr>

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Misiones: Si el reporte es una misión especificaremos en el título, Misión seguido de la zona donde se realiza la misión y el nombre de la misma.

**Comment by redneo** [comment]
A mi si que me ha funcionado perfectamente, eres alguna clase "extraña" lo he probado con un sacerdote recien creado
