### ISSUE TITLE
Mision NPC Ephram "Ombligo" Puestaluna El Cabo de Tuercespina

### ISSUE THREAD

**Issue by vayronluxx** [RoDNet/Bugtracker-Infinium-4.3.4#2093]
El npc http://es.wowhead.com/npc=43377/ephram-ombligo-puestaluna
Ephram "Ombligo" Puestaluna aparece como aliado y no se lo puede atacar y la mision http://es.wowhead.com/quest=26595/matar-y-recaudar  Matar y recaudar te pide de que lo mates.

Aqui les dejo una foto para que lo vean . http://www.subirimagenes.net/i/130922082905207536.jpg

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

Arregkadi
