### ISSUE TITLE
[DK] Atraccion Letal

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2094]
Nombre: Atraccion Letal
ID: http://es.wowhead.com/spell=49576
Descripcion: Reune Energia Profana que rodea y vincula toda materia, lo que acerca al objetivo hacia el caballero de la muerte y obliga al enemigo a atacar al caballero de la muerte durante 3s

Notas del parche 4.0.6:Atracción letal requiere un radio mínimo de 8 metros contra otros jugadores, pero esto no figuraba en la descripción. La descripción se ha actualizado.

Problema: Para usar atraccion letal contra jugadores requiere un radio minimo de 8 metros esto no esta sucediendo puedo usarla estando menos de 8 metros

**Comment by kingtonix** [comment]
Si tienes el glifo puedes usarlo en menos metros :I

**Comment by F4NT4SM4** [comment]
el glifo aumenta la distancia q puedes usar atraccion letal ¬¬
