### ISSUE TITLE
[misión] Sed insaciable

### ISSUE THREAD

**Issue by BeverManuel** [RoDNet/Bugtracker-Infinium-4.3.4#2095]
<hr>

• <strong>Nombre</strong>: <a href="http://es.wowhead.com/quest=8346/sed-insaciable">Sed insaciable</a>
• <strong>Enlace</strong>: <a href="http://es.wowhead.com/quest=8346/sed-insaciable">http://es.wowhead.com/quest=8346/sed-insaciable</a>
• <strong>Descripción</strong>:Busca a criaturas con maná (<a href="http://es.wowhead.com/npc=15274">Vermis de maná</a>) y desata tu <a href="http://es.wowhead.com/spell=80483">Torrente Arcano </a> sobre ellas.
• <strong>Problema</strong>: Al utilizar el Torrente arcano sobre las Vermis de maná no pasa nada de nada.
• <strong>NPC que da la misión</strong>: <a href="http://es.wowhead.com/npc=15297"> Arcanista Helion </a>

<hr>

**Comment by Kiritoo** [comment]
reportada dos veces cierro este.
