### ISSUE TITLE
Mascota Espiritu (Aliviar espíritu)

### ISSUE THREAD

**Issue by patriccio** [RoDNet/Bugtracker-Infinium-4.3.4#2096]
hola a los gm , queria reporta la habilidad de la mascota espiritu http://es.wowhead.com/spell=90361, esta dando una curacion my baja , ya que da pulsos de  500 . cosa que es baja en comparacion a lo que especifica la spell.

**Comment by Kiritoo** [comment]
Continuamos https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2264?source=cc Mejor reportado.
