### ISSUE TITLE
[Misión] ¡Fiesta de la Cerveza! (no aparece a los goblins)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2097]
La misión que abre el festival de la cerveza http://es.wowhead.com/quest=11446 no es seleccionable (ni tan solo aparece) a los personajes de raza goblin.
Es decir, aparece el npc que te la da http://es.wowhead.com/npc=19175 pero te da misiones del evento del peregrino y del de halloween.

Este problema impide poder tener acceso a diarias de este evento como: http://es.wowhead.com/quest=12192 o poder acceder a logros como "Abajo los Hierro negro" http://es.wowhead.com/achievement=1186

P.D. Este problema solo me ha surgido con un personaje de raza goblin, con el resto de razas he podido realizar todo lo detallado anteriormente sin problemas.

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

Arreglado
