### ISSUE TITLE
[Ulduar] Leviatán de llamas

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2098]
http://es.wowhead.com/npc=33113

Supuestamente el leviatán tiene dos modos de juego el normal o el difícil todo depende de la cantidad de torres "gordas" que dejes en pie. Hay un total de 4 torres y cada uno le otorga un buffo al boss.

El problema es el siguiente, hemos destruido las torres para probar el modo normal, ya que para probar es mejor hacerlo fácil, y despues de matar a los adds y llamar al boss. Al intentarle atacar pone Evadir siempre que se le intenta atacar.

Tengo una teoría de porque se produce el problema, aunque puede ser algo descabellada. La teoría es la siguiente, al llamar el boss empieza a hablar como al comienzo de cada encuentro de los bosses. Entonces mientras sale, habla y entonces en ese momento diría que se le puede pegar pero cuando acaba el discurso, evade todo lo que le eches. Es como si el discurso lo dejase bloqueado, no te ataca ni te deja atacarle pero si te sigue.

Igual la solución podría estar en dejar al boss detrás de la barrera sin que nadie le pueda atacar hasta que se acabe el discurso y entonces cuando acabe que salga y se le pueda atacar.

Espero haber sido claro en mi larga explicación. Cualquier duda o aporte comentad.

**Comment by efectokoleos** [comment]
dime se keda detras de la puerta de luz no?

**Comment by lamaza** [comment]
yo lo mate hace 1 semana y nos dio logros y loot y todo.

**Comment by Wiinter** [comment]
No no, no se qeda atrás de la puerta. Pues lamaza a mi ya van dos veces que voy y me pone evadir.

**Comment by efectokoleos** [comment]
no consigo reproducir el error, si puedes poner imagenes o un video seria de mucha ayuda

**Comment by Wiinter** [comment]
Cuando volvamos ya haré fotos

**Comment by Wiinter** [comment]
@lamaza dime como mataste al Leviathan rompiste las 4 torres?

**Comment by Wiinter** [comment]
Defeated
