### ISSUE TITLE
[Druida Feral] Estadistica: Celeridad

### ISSUE THREAD

**Issue by Cacafuti** [RoDNet/Bugtracker-Infinium-4.3.4#2099]
De primero lo siento por no poner id ya que nose esto que id puede tener.

El problema de esto es que para los druidas ferales la celeridad no aumenta la regeneración de energia. 
Ejemplo:
![wowscrnshot_091913_170516](https://f.cloud.github.com/assets/5468786/1188709/320e5c26-23e4-11e3-839c-73eab442dee0.jpg)
![wowscrnshot_091913_170528](https://f.cloud.github.com/assets/5468786/1188710/3b1949b6-23e4-11e3-9571-86836658a212.jpg)
La regeneración de energía no varia, sin importar la celeridad que tengas, yo creia que era un bug visual, pero lo he calculado y regenera de la misma manera, por eso queria que lo arreglasen ya que asi la celeridad solo nos aporta un 50% de sus beneficios.
Saludos y gracias

**Comment by ghost** [comment]
Supongo que también ocurrirá a los picaros no? la mecánica es la misma para ambas clases. Será un fallo en la celeridad en general.

**Comment by Cacafuti** [comment]
no , lo raro es eso , que a los picaros si les funciona y a los ferales no.

**Comment by Monleon** [comment]
Arreglado, falta compilar. Aunque en principio no os aparecerá la mejora en las estadísticas.
