### ISSUE TITLE
druida feral, bugs

### ISSUE THREAD

**Issue by Srgatonegro** [RoDNet/Bugtracker-Infinium-4.3.4#210]
por aca gatonegro xd...
primero q nada saludos al staff y gracias por el parche nuevo...

Estadisticas

El dps ahora es casi nulo, por un bug q ya era presente en el rod 4.0 pero aca aumento xd... trata sobre la agilidad...

Agilidad: que debe dar 2 puntos de poder de ataque por cada uno de agilidad, en vez de eso da 0,997 puntos de poder de ataque por cada de agilidad, menos de 1 (daño reducido en un 51% + o -) 

Celeridad: tambien me hace mucho ruido visual, pues si mal no recuerdo, con exactamente el equipo q llevo q se me acumulan 482 de celeridad, solia ser algo asi como 11%, aca me dice -0.41% y a veces 0.08%, no tengo la mas minima idea de xq varia, pero los dos estan mal...

Regeneracion de energia: no se ve afectada por nada, solo estan los 10.00 de base, y tengas 500 o 0 de celeridad, sigue siendo 10.00, esto esta directamente relacionado con el bug de arriba de celeridad. 

pues hablando de estadisticas creo q el resto va normal.

Habilidades o spells

Carga feral (felino) http://es.wowhead.com/spell=79830/carga-feral-felino 
1. Al usarlo me saca de acecho(sigilo) no deberia ser
2. Cuando se usa no deja al pj detras del enemigo
  NOTA: si me dicen q no sabian q esto es un bug, es xq en el anterior parche tambien estaba bug pero jamas me anime a sentarme a reportar nada XD.

Rugido salvaje http://es.wowhead.com/spell=52610/rugido-salvaje
No funciona para nada, lo unico q hace es consumir los puntos de combo

bueno me parece q el resto de las spell van normales tambien, dios ahora los talentos E_E

Talentos

http://es.wowhead.com/spell=81022/estampida
Estampida: el talento salta cuando debe... pero es completamente inutil xq no cumple con su funcion xD, no hace nada; no me deja usar devastar fuera de sigilo, y  en todo caso, si lo arreglan, pendiente por favor con otro bug q tenia en la 4.0, xq dice q "permite usar devastar en cualquier posicion respecto al enemigo y la misma facultad cuesta 100% menos de energia" en el anterior parche, el talento saltaba, pero requeria usarlo por la espalda y si quitaba los puntos de energia 

y probe toooodos los otros de feral, y funcionan perfecto, uno de los q me benficio es el siguiente 

corazon de lo salvaje; (el link q sale en wowhead es del 5.3 y el talento cambia un buen, por eso dejo la descripcion) "aumenta tu intelecto un 6%, ademas mientras estes en forma de oso aumenta tu aguante un 6%, y mientras estes en forma felina tu poder de ataque aumenta un 10%"... no hace nada de lo q dice xD, completamente inutil...

faltaria testear los talentos de heal, se q el heleo va over xq me he dado cuenta, pero no conozco lo suficiente los talentos para decir a ciencia cierta donde esta el error... de todos modos creo q por alli han dejado otro post una dudu de la ali deadgirl o algo asi xD...

este pasivo 

http://old.wowhead.com/spell=84735
Agresion: aumenta un 5% mas de lo q deberia, osea un 30%

la maestria del oso no va 
http://old.wowhead.com/spell=62606

esta se activa, si salta, pero solo absorve 1p de daño fisico xD

http://old.wowhead.com/spell=84840/venganza
venganza: la venganza se activa, pero lleva algo extraño, hace tanto tiempo q no lo veia q no recuerdo si es natural, q baje el poder de ataque ganado mediante el daño inflingido, por ejemplo si una spell me pega 200 gano 10 de ap si otra me pega 4000 gano 200 de ap, peeero, si otra me vuelve a pegar q se yo... 100 vuelvo a ganar 5 de ap, no se deberia quedar en el valor mas alto? otra cosa es, q se mantiene activa despues de cambiar de forma, asi incluso cambie a talentos de healer, si no la quito, no se va.

**Comment by ghost** [comment]
@Srgatonegro si puedes reportar cada bug en un reporte a parte, para facilitar el arreglo de los mismos, muchas gracias.
