### ISSUE TITLE
[Guerrero] Vendaje de Batalla

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2100]
Nombre: Vendaje de Batalla
ID:84579/84580 
Link: http://wow.freakz.ro/spells.php?spell=84580
Descripcion: Aumenta las sanaciones recibidas un 3% / 6% y la eficacia de tus facultades de autosanacion un 10% / 20% extra

Problema: No esta aumentando las autosanaciones en un 10%/20% mas bien las esta aumentando en un 3% / 6% y deberia de ser asi
3% / 6% las sanaciones que recibas de otros jugadores
10% / 20% las autosanaciones: Regeneracion Iracunda, Mania Sangrienta, Segundo Aliento y Ataque de victoria

Regeneracion Iracunda: 55694
Mania Sangrienta:16487 / 16489 / 16492
Ataque de victoria: 34428
Segundo Aliento: 29834/ 29838

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Enlace: Enlace necesario a http://es.wowhead.com o http://old.wowhead.com, no solo el ID.

**Comment by ghost** [comment]
http://wow.freakz.ro/spells.php?spell=84580

**Comment by searum** [comment]
fix
