### ISSUE TITLE
[DK] Golpe Letal

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2102]
Nombre: Golpe Letal
ID:http://es.wowhead.com/spell=49998/golpe-letal
Descripcion: Lanza un poderoso golpe que te sana un 20% del daño que has sufrido durante los ultimos 5s (un minimo de 7% de tu salud maxima) y tambien inflije un 150% de daño con arma mas 497p de daño aun enemigo si el ataque tiene exito

Notas del parche 4.3.0: Ahora Golpe letal sana al caballero de la Muerte aunque el ataque falle, se esquive o se pare. Como consecuencia de este cambio, Golpe letal ya no reembolsa su coste si no consigue alcanzar a su objetivo, ya que el caballero de la Muerte recibirá de todos modos el efecto de sanación.

Problema: Golpe letal deberia de curarme aun si falle, esquiven o paren mi ataque. No me esta curando :l

**Comment by searum** [comment]
fix
