### ISSUE TITLE
[Trol] NPC: Morakki <Capitán de la Avanzada> -  Durotar - Islas del Eco - 67.8, 74.2

### ISSUE THREAD

**Issue by L0rdHad35** [RoDNet/Bugtracker-Infinium-4.3.4#2103]
Desde que comence a jugar como un Troll Cazador en las Islas del Eco, Morakki Capitan de la Avanzada http://es.wowhead.com/npc=38442 en el campamento Lanza Negra a pesar de q tiene la marca de entregar una Quest nunca lo hace.

**Comment by Wiinter** [comment]
Hay qe reportar cada mision por separado :)

**Comment by L0rdHad35** [comment]
Listo las separe!

**Comment by Wiinter** [comment]
Pon el nombre de la misión y la zona donde se encuentra en los titulos de los reportes

**Comment by L0rdHad35** [comment]
Happy?

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

QUe se parezca a esto un reporte no cuesta tanto.
