### ISSUE TITLE
[Brujo] Resguardo Abisal

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#2104]
Este escudo es propio del brujo destrucción. Al colocar el talento transforma resguardo contra las sombras en resguardo abisal para protegerse de cualquier daño con hechizos sea del tipo que sea.

Lo que sucede es que este escudo no absorbe nada, es decir, absorbe una pequeña cantidad de daño del primer golpe pero nada más, no absorbe el daño total que debería. En mi caso, como se ve en la foto, sería aproximadamente de 10k. Hasta que no absorbiera esa cantidad no se debería disipar y lógicamente tampoco recibir daño con hechizos.

La Id y la fórmula para ver cuanto absorbe es la siguiente: http://es.wowhead.com/spell=91713/resguardo-abisal

Aquí os adjunto unas fotos.

![wowscrnshot_092313_131647](https://f.cloud.github.com/assets/3939699/1190943/c454e5b0-2442-11e3-948f-575b7690f5ae.jpg)

![wowscrnshot_092313_131826](https://f.cloud.github.com/assets/3939699/1190944/cb711f80-2442-11e3-84ae-ca7235538386.jpg)

En esta última foto se puede ver en el registro de combate como absorbe solo parte del daño del primer golpe y luego ya nada.

![wowscrnshot_092313_132800](https://f.cloud.github.com/assets/3939699/1190964/57777448-2443-11e3-9e4d-00ddeff9ff57.jpg)

Un saludo y gracias

**Comment by searum** [comment]
fix
