### ISSUE TITLE
[Brujo] Protección Abisal

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#2105]
Este talento propio del brujo destrucción tampoco se activa. Para obtenerlo primero tendríamos que haber absorbido daño con Resguardo Abisal (este hechizo esta reportado aquí, os pongo el enlace porque esto no puede darse si Resguardo Abisal no funciona https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2104).

El caso es que si tienes el talento puesto al haber absorbido daño con resguardo abisal debería saltar Protección Abisal que tendría que reducir el daño con hechizos un 15% con 1 ptos de talento o un 30% con 2 ptos de talento durante 12sg.

La id no la he encontrado pero os dejo fotos del talento con la descripción. Si alguien encuentra la id por favor que la aporte.

![wowscrnshot_092313_134359](https://f.cloud.github.com/assets/3939699/1191032/7405ff56-2445-11e3-9305-dd0420287a32.jpg)

Un saludo y gracias

**Comment by Wiinter** [comment]
Id : 30299

**Comment by Kiritoo** [comment]
Enlace: Enlace necesario a http://es.wowhead.com o http://old.wowhead.com, no solo el ID.
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by Wiinter** [comment]
No hay enlace ni en wowhead ni old.wowhead por eso no lo hemos puesto. Si pones la id qe te marca el IDTIP ambas páginas pone qe no se encuentra el hechizo

**Comment by Drogoth2** [comment]
Como ha dicho wiinter no viene el enlace en wowhead lo he buscado y no aparece. Solo puedes sacar el de MoP y no es igual que en cata.

**Comment by Drogoth2** [comment]
Pero fixx eso es Resguardo abisal, no protección abisal que es lo que estoy posteando aquí. El de Resguardo abisal esta posteado aquí https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2104

**Comment by Kiritoo** [comment]
http://cata.openwow.com/search=Nether+Protection
http://wow.freakz.ro/spells.php?spell=30299&name=nether-protection
http://wow.freakz.ro/spells.php?spell=30301&name=nether-protection

**Comment by Drogoth2** [comment]
Ese es, el del freakz :)

**Comment by searum** [comment]
fix
