### ISSUE TITLE
[Troll] Mision: Joven y salvaje - Durotar - Islas del Eco - 63.4, 95.2

### ISSUE THREAD

**Issue by L0rdHad35** [RoDNet/Bugtracker-Infinium-4.3.4#2106]
En la mision Joven y Salvaje entregada por Kijara: http://es.wowhead.com/quest=24626/joven-y-salvaje#comments, el garrapresta que hay q capturar ya esta entregado en la Isla justo detras del NPC q entrega la mision y por lo tanto la segunda parte que es montar otro garrapresta y entregarlo no se puede hacer!

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

QUe se parezca a esto un reporte no cuesta tanto.
