### ISSUE TITLE
[Mision] Las fallas de distorsion

### ISSUE THREAD

**Issue by Bariloche123** [RoDNet/Bugtracker-Infinium-4.3.4#2107]
Uso el item y nada sucede, mato a los npc del lugar y no dropean el item  ID: 10278

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

QUe se parezca a esto un reporte no cuesta tanto.
