### ISSUE TITLE
[Dk - Escarcha] Impactos Dobles + Daño subido

### ISSUE THREAD

**Issue by nicerdicer** [RoDNet/Bugtracker-Infinium-4.3.4#2108]
![dkbug1](https://f.cloud.github.com/assets/4660334/1192345/772de894-2461-11e3-8cba-7df47f5a941c.jpg)
![dkbug2](https://f.cloud.github.com/assets/4660334/1192363/97a62c62-2461-11e3-82cf-29288ddb7f24.jpg)
![dkbug3](https://f.cloud.github.com/assets/4660334/1192366/9ee5dc2a-2461-11e3-90d0-b885156492fa.jpg)
![dkbug4](https://f.cloud.github.com/assets/4660334/1192385/ed1cd40c-2461-11e3-9145-d72198e46165.jpg)

Se reporta en este post que el DK con talentos de escarcha usando doble empuñadura, con las facultadesq ue implican ataques cuerpo a cuerpo, el arma de mano izquierda golpea dos veces generando el doble de daño con mano izquierda con cada facultad. Esto ha sido probado con [Asolar]ID49020 - [Golpe de Escarcha]ID49143 - [Golpe Letal]ID49998, asi como en golpes blancos donde la mano izquierda seguia efectuando dos golpes seguidos dentro del mismo ciclo.
A la vista esta en los Screens como en todas las habilidades cuenta en el registro de combate 2 lecturas por daño de mano izquierda, menos en la ultima lectura del daño por Melee blanco en la que el ataque con mano izquierda falla y en el registro aparecen dos lecturas simultaneas de ''El ataque no alcanza al objetivo''

He presentado tambien la lectura del Dr.Damage para que se aprecie que el daño tampoco el es correcto, ni en las facultades ni en el golpe blanco.

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Enlace: Enlace necesario a http://es.wowhead.com o http://old.wowhead.com, no solo el ID.

**Comment by ghost** [comment]
- Asolar: http://cata.openwow.com/spell=49020
- Golpe de escarcha: http://cata.openwow.com/spell=49143
- Golpe letal: http://cata.openwow.com/spell=49998

**Comment by nicerdicer** [comment]
Se agradece el dato!

**Comment by paellaencol** [comment]
Se ha vuelto a fastidiar:

http://img13.imageshack.us/img13/4287/62t9.jpg
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/13/62t9.jpg/'><img src='http://img13.imageshack.us/img13/4287/62t9.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>
