### ISSUE TITLE
[Trono de las mareas 5HC] Géiser de Lady Nazjar

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2109]
Descripción: El boss Lady Naz'jar http://es.wowhead.com/npc=40586 utiliza de vez en cuando la spell "invocar geiser" http://es.wowhead.com/spell=75722/invocar-geiser#used-by-npc. Además este geiser http://es.wowhead.com/npc=40597 al ser creado provoca esto:

Invoca un géiser en la ubicación de un jugador aleatorio. Tras 5 s, el géiser entra en erupción e inflige 23750 to 26250 p. de daño de Escarcha y derriba a todos los enemigos en un radio de 5 m del área objetivo. (Modo normal) (150.000 en heroico)

Hasta aquí todo bien.

Problema: el Géiser http://es.wowhead.com/npc=40597 aparte de esto está haciendo daño físico desde debajo de las texturas, no puede ser tarjeteado, ni se le puede inflingir daño, además te mete en combate (y a pegarte) antes incluso de iniciar el boss Lady Naz'jar, y solo se puede huir del daño físico del geiser mediante la muerte del personaje. 
No debería pasar nada de esto, únicamente debe de aparecer cuando lady nazjar utilice http://es.wowhead.com/spell=75722/invocar-geiser#used-by-npc , hacer su skill propia tras 5 segundos (ojo! remarco lo de 5seg, ya que ha llegado a veces a hacerlo instantáneo), y posteriormente desaparecer al inflingir el daño.

Gracias!

**Comment by efectokoleos** [comment]
arreglado
