### ISSUE TITLE
[Mazmorra]Pozo de la Eternidad

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#211]
Hola quiero reportar un fallo de esta instance.

Pozo de la Eternidad http://es.wowhead.com/zone=5788

Esta instance no podemos entrar a testear porque aparece el siguiente mensaje.
![wowscrnshot_070613_014830](https://f.cloud.github.com/assets/3537253/755917/2333546c-e5ce-11e2-9f4d-fc3f37ee5f72.jpg)

"Para acceder al nivel de dificultad Heroico, debes tener nivel 85."

Segun parece está cerrada, este mensaje aparece tanto desde el buscador como llendo recorriendo el mapa y entrando por la entrada a la instance.
Si no es así y pueden revisarlo para entrar a testearlo se agradeceria.

Un saludo.

PD. Sin esta no se puede entrar ni hacer las dos restantes, sin el logro necesario.
-Hora del Crepúsculo http://es.wowhead.com/zone=5844#english-comments
-Fin de los Días http://es.wowhead.com/zone=5789#english-comments

**Comment by efectokoleos** [comment]
las instances estan cerradas xd
