### ISSUE TITLE
[Trono de las mareas 5HC] NPC "Zapador ignoto" en jefe "Ozumat"

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2110]
Buenas noches

Al llegar al último jefe de Trono de las mareas, debemos de pasar por dos fases durante este encuentro, antes de poder llegar a la tercera donde nos enfrentaremos directamente con Ozumat http://www.wowhead.com/npc=42172

El problema reside en la segunda fase, donde nos empiezan a salir adds de distintos tipos. Uno de esos adds son los "zapadores ignotos" http://es.wowhead.com/npc=44752  Los cuales segun la descripción que nos aporta la guía de mazmorras, dice que la fase 2 concluye con la muerte de los tres "zapadores ignotos".
Lo que nos sucede es que estos zapadores aparecen por encima del techo de la estancia, lo que hace imposible poder atacarlos, ya que están a una distancia muy lejana.
Estos adds deberían aparecer a la altura del suelo como hacen el resto de adds de distinto tipo.
Como se aprecia en la imagen, al estar tan lejos, y no ser atacables la fase 2 no concluye nunca, haciendo imposible acabar este boss:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/109/glls.jpg/'><img src='http://img109.imageshack.us/img109/2997/glls.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

P.S. como no pudimos vernos las caras directamente con ozumat, no puedo afirmar si el bug por el cual Ozumat no aparecía se reparó https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/955

**Comment by Monleon** [comment]
Arreglado el problema de los adds.
