### ISSUE TITLE
[Druida Feral Gato] Spell: Rugido salvaje (ID:52610)

### ISSUE THREAD

**Issue by Cacafuti** [RoDNet/Bugtracker-Infinium-4.3.4#2113]
Nombre: Rugido salvaje
Enlace: http://es.wowhead.com/spell=52610

Descripción: 
Remate que aumenta el daño físico infligido un 80%. Eficaz solo bajo forma felina. Se prolonga con cada punto de combo:

  1 p.: 18 s.
  2 p.: 24 s.
  3 p.: 30 s.
  4 p.: 36 s.
  5 p.: 42 s.

Problema: El hechizo no se activa

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by Cacafuti** [comment]
asi¿?

**Comment by Kiritoo** [comment]
Ahora esta mejor ^^

**Comment by searum** [comment]
funciona perfectamente..

Problema: El hechizo no se activa

se activa a la perfeccion xd
