### ISSUE TITLE
[Druida Restauración ] Talento racial: Desenredo (ID: 96429)

### ISSUE THREAD

**Issue by Cacafuti** [RoDNet/Bugtracker-Infinium-4.3.4#2114]
Nombre: Desenredo
Enlace: http://es.wowhead.com/spell=96429 (es el del pandarian , pero no se que otro poner)
Descripción: El cambio de forma ahora elimina las raíces.
Problema: El hechizo no elimina las raíces.
Observaciones: Tampoco elimina las ralentizaciones.

**Comment by Kiritoo** [comment]
http://www.curse.com/addons/wow/spellid
Te recomiendo este addon es el que yo y muchos utilizamos, siempre sabras la id correcta.
Fijate de buscar la versión del addon de nuestra versión del servidor.
Saludos.

**Comment by Cacafuti** [comment]
Gracias ^^

**Comment by ghost** [comment]
El bug de las ralentizaciones es del cambio de forma, no de desenredo. Sólo aclaro xP.

**Comment by Cacafuti** [comment]
ya pero esque desenredo tampoco va igualmente, deveria quitar las raices y no lo hace-

**Comment by searum** [comment]
fix
