### ISSUE TITLE
[Druida Restauración ] Talento: Revitalizar (ID: 48539)

### ISSUE THREAD

**Issue by Cacafuti** [RoDNet/Bugtracker-Infinium-4.3.4#2115]
Nombre: Revitalizar

Enlace: http://es.wowhead.com/spell=48544 ( es el enlaze del pandarian, no se que otro poner)

Descripción: Cuando realizas una sanación periódica con tus hechizos Rejuvenecimiento o Flor de vida, tienes un 20% de probabilidad de regenerar al instante un 2% de tu maná total. Este efecto no puede darse más de una vez cada 12 s.

Observaciones: No funciona ni con 1 punto ni con 2

**Comment by searum** [comment]
fix
