### ISSUE TITLE
[Druida Spell ] Augurio de claridad (ID: 16864)

### ISSUE THREAD

**Issue by Cacafuti** [RoDNet/Bugtracker-Infinium-4.3.4#2116]
Nombre: Augurio de claridad
Enlace: http://es.wowhead.com/spell=16864
Descripción: Tus ataques automáticos tienen una pequeña probabilidad de hacer que entres en estado de Lanzamiento libre.

El estado de Lanzamiento libre reduce un 100% el coste de maná, ira o energía de tu siguiente hechizo no instantáneo dañino, de sanación o facultad feral ofensiva.

Problema: Cuando esta en gato el hechizo se activa pero no funciona , sigues gastando energia.
Observaciones: Es muy molesto ya que el hechizo esta activado y hace que te de la opcion de lanzar el hechizo pero  luego no puedes tirarlo ya que no tienes energia.

**Comment by searum** [comment]
funciona perfectamente eh
