### ISSUE TITLE
[Guerrero] Arremetida enfurecida Id:85288

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2117]
Enlace desde wowhead (ya no funciona igual, pero he visto que estais pidiendo que lo enlacemos http://es.wowhead.com/spell=85288/arremetida-enfurecida )

Descripción: Una poderosa arremetida que inflige un 151% de daño con ambas armas de combate cuerpo a cuerpo. Solo se puede utilizar mientras se está enfurecido.

http://imageshack.us/photo/my-images/20/w3k8.jpg/

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/20/w3k8.jpg/'><img src='http://img20.imageshack.us/img20/1282/w3k8.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

Problema: al ser un ataque que depende del daño de arma está pegando de más. La fórmula creo que es la correcta, o parecida, pero como el daño de arma está subido https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1704 este problema está afectando también a este ataque, haciendo que pegue más de lo que debería.

**Comment by ghost** [comment]
http://cata.openwow.com/spell=85288

**Comment by Kiritoo** [comment]
Funciona como debería.
