### ISSUE TITLE
[Druida] Maestría Oso (Defensor Salvaje)

### ISSUE THREAD

**Issue by harusen** [RoDNet/Bugtracker-Infinium-4.3.4#2118]
Maestría Defensor salvaje ID 86470 

Debe absorber daño equivalente a un 35% de tu poder de ataque + 4% por punto de maestría cuando se activa.

Problema, Cuando se activa pone q absorbe 1p de daño.

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by harusen** [comment]
si me has puesto ese post por no poner enlace, esta habilidad se transformo en pandaria, x lo q no encuentro un enlace. Como lo pongo?

**Comment by ghost** [comment]
También por no poner la ID.

http://cata.openwow.com/

Ahí puedes buscar las spells de cataclysm y las IDs.

Saludoos!

**Comment by harusen** [comment]
no es una spell es una maestria, asik como pongo la id, con el addon idtip no aparece ni el la pag q me has linkeado tampoco

**Comment by ghost** [comment]
Seguro? A mi si me aparece mi maestría con el IDtip.

**Comment by harusen** [comment]
seguro, lo he intentado ya varias veces y no me sale nada, si alguien puede que pnga la id gracias

**Comment by harusen** [comment]
Hola, me puede decir alguien como va este bug?, si se tiene ya alguna solucion?
grax

**Comment by paellaencol** [comment]
Debe absorber <b>solo un golpe de daño físico</b>.  Si el druida tiene un escudo en un momento dado de 10k,  el escudo expirará al próximo golpe físico recibido (sea de 10k o de 1k)
