### ISSUE TITLE
[Druida] Venganza

### ISSUE THREAD

**Issue by harusen** [RoDNet/Bugtracker-Infinium-4.3.4#2119]
Venganza ID 84840, aunq en el buff pone 76691 de ID

Venganza: Obtienes 5% del daño recibido como poder de ataque. hasta un 10% de tu salud máxima

Problema, este poder de ataque es acumulativo hasta el 10% de tu vida, sin embargo con cada golpe que te dan se esta reseteando,

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by harusen** [comment]
si me has puesto ese post por no poner enlace, esta habilidad se transformo en pandaria, x lo q no encuentro un enlace. Como lo pongo?

**Comment by searum** [comment]
addon: idtip

**Comment by harusen** [comment]
Se ha solucionado o se prevee q se pueda solucionar este bug?
grax.

**Comment by searum** [comment]
fix
