### ISSUE TITLE
[Picaro] Hemorragia

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2122]
Nombre: Hemorragia
ID:http://es.wowhead.com/spell=16511/hemorragia

Descripcion: Un golpe instantáneo que inflige un 216% de daño con arma (un 313% si se lleva equipada una daga), lo que provoca qle el objetivo reciba un 30% de daño extra por efectos de sangrado durante 1 minute. Otorga 1 p. de combo.

Problema: Tiene el daño un poco elevado, lo testee con mi picaro solo set sangui (ni gemas, enchanter, buff nada) pego 12k deberia de pegar menos ya que puñalada pega 14k estando el daño asi no hace falta usar puñalada sale mas rentable hemorragia full spam...
Observaciones: he visto en arenas picaros que ni usan puñalada solo spam hemorragia y algunas emboscadas pero hemorragia queda en 1ro daño con gran diferencia al segundo segun mi recount, Se supone que hemorragia es para aplicar debuff y luego usar full puñalada por que pega mas pero el daño esta casi igual...

**Comment by ghost** [comment]
Madre mía tio..deberías dejar de hacer comentarios tan contundentes sin tener ni idea de lo que hablas, no es la primera vez que lo veo.

Pícaro en cata, para PvP hay dos posibles arboles de talentos en suti: 
- Backstab: Usa puñalada como principal habilidad de daño y puntos de combo.
- Hemospam: NO usa puñalada, se basa en SPAMM de hemorragia, ya que el coste de energía es menor, da mas movilidad al no tener que estar tras tu objetivo, el daño que se pierde merece la pena, y deja un DoT que no interrumpe tu gubia e impide a otras clases hacer restealth. Esta es la build que llevan la mayoría de los pícaros, también en el server, ya que da más movilidad y más aguante por los talentos de recuperación, que te dan más heal y regeneración de energía.

NO puedes decir que el daño de hemorragia está alto basándote en que hace casi lo mismo que puñalada, rofl, ¿y si es puñalada lo que está bajo como pasaba con emboscada?. Ojo, no digo que no lo esté como para poner la mano en el fuego, pero por dios...pon algo de pruebas para contrastarlo, yo sinceramente opino de primera mano que los picaros tienen el daño en general MUY bajo:

http://youtu.be/JLiLRF11cNk?t=3m24s

El vídeo es de la 4.2, aun así no para de sacarle 10k con hemorragia!, tiene build hemospam al dk que por cierto va equipado con el set élite de la temporada, ticks de 2.5k e incluso 5k en críticos cuerpo a cuerpo. Para que lo tengas a modo de referencia, mi rogue va full sañoso engemado y con suerte le saco 700 de crítico a los dks en cuerpo a cuerpo.

**Comment by patriccio** [comment]
asman, my buena explicación del asunto de la hemorragia, pero demosle a f4ant4s el derecho de la duda,uno nunca sabe como van las cosas con algunas spell aqui.

saludos

**Comment by F4NT4SM4** [comment]
Hemospam: Cuesta menos energia y no es necesario estar de espalda no hace tanto daño como puñalada pero como es spameable lo compensa
Puñalada: no es spameable ya que cuesta 60 energia(con glifo y talento no me eh fijado) y hay que estar de espalda
se supone que como puñalada cuesta mas deberia de pegar mas que hemo y estan pegando casi igual no tiene logica intonce usar puñalada
ya vi los 21k de ¨Emboscada¨
lo maximo que vi de hemo fue 10k

**Comment by ghost** [comment]
A ver...son 2 builds distintas, tampoco puedes decir que hemo está bug porque puñalada es mejor de base y punto. Sí, puñalada tiene un daño directo mayor, un 48% más de daño con arma que hemorragia y 1200 puntos de daño más extra, pero ese no es el caso, la build de puñalada es viable sencillamente porque los puntos que quitas de "Aceleración" de la build de hemospam (que aumentan tu velocidad de movimiento y sanación) van a parar a mejorar puñalada para que tenga más probabilidad de crítico y haga un daño mucho mayor.

Por eso es mejor puñalada que hemorragia, porque coges los puntos de talentos para mejorarlo y porque no tienes aguante para hacer un daño sostenido con hemorragia, sino burst. No porque cueste más energía.

Puñalada tendrá sentido usarla si mi build es backstab, no si es hemospam.

**Comment by F4NT4SM4** [comment]
osea ese 48% mas de daño que hemorragia y 1200 puntos de daño mas extra solo hace que la diferencia sea 2k?
el talento aumenta el critico yo me refiero a daño que se me hace raro que no tenga tanta diferencia
que un gm confirme si el daño ta bien o verifica la formula tu y cierro post

**Comment by ghost** [comment]
Sisi, me parece bien que se testee, puede que hemo esté subido, o puñalada baja, algo se arreglará seguro. 

Edit: Testear también el daño periódico de hemorragia, porque estoy seguro de que es menor al que debe, teniendo en cuenta que está aumentado en un 30% por el propio buff de hemorragia.

Saludos!

**Comment by searum** [comment]
No perdona, Testear también no. Testear vosotros y yo arreglo. XD no confundas!

**Comment by F4NT4SM4** [comment]
yo testee veo el daño muy subido para una skill que es spameable y drdamage señala que esta muy elevado pero como no es 100 confiable...
que tesste asman para asegurar :c

**Comment by searum** [comment]
fix
