### ISSUE TITLE
[Bastión de Baradin] Occu'thar

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2123]
Occu'thar = http://es.wowhead.com/npc=52363#encounter
Fuego enfocado = http://es.wowhead.com/spell=96884
Sombras abrasadoras = http://es.wowhead.com/spell=96913
Ojos de Occu'thar =  http://es.wowhead.com/spell=96920/ojos-de-occuthar 

El boss tira Sombras abrasadores cada 12s sobre los tanques y les pone el debuff de daño de las Sombras augmentado un 100%. Entonces en la raid tienen que haber dos tanques para irse cambiando el boss para que no tengan el debuff.

El problema es que ahora tira Sombras abrasadoras cada 12 segundos y el debuff de Sombras abrasadores no se quita hasta al cabo de 30 segundos. Entonces aunque cambiemos de tank, cuando le vuelve a tocar al tank del principio solo han pasado 24s y se vuelve a comer otra acumulación, sino muere al instante poco le falta. 

Propongo mínimo poner que el lanzamiento de las sombras abrasadoras lo tire cada 15 o 16 segundos y por tanto da tiempo a que se les vaya el debuff a los tankes.

**Comment by efectokoleos** [comment]
he estado viendo varios videos y he reajustado los timer para hacerlo mas blizz

**Comment by Wiinter** [comment]
Espero probarlo hoy y te digo como va :D

Gracias por la rapidez

**Comment by Wiinter** [comment]
Nos tira los ojos y antes de que pasen los 10s de los ojos nos tira fuego enfocado. Si dejara 4 o 5s para separarse, iría bien.

**Comment by efectokoleos** [comment]
cambiado a 10 segundos el tiempo del fuego, ahora si quedaria como el ofi

**Comment by Wiinter** [comment]
En cuanto lo probemos te vuelvo a comentar, aunque creo que esta bien ya estará perfecto aunqe no lo podamos matar xD

**Comment by Wiinter** [comment]
Nos ha metido Fuego enfocado cuando aun no habíamos recibido el daño de los ojos. Ha matado a toda la raid menos los tankes.

**Comment by efectokoleos** [comment]
http://www.youtube.com/watch?v=KgQEgge3A6s segun ese video lo tira justo 10 segundos despues, los ojos no deben explotar ya que si no la raid wipeara

**Comment by Wiinter** [comment]
explotan los de los tankes

**Comment by paellaencol** [comment]
No se si este vídeo pueda resultar de ayuda

http://www.youtube.com/watch?v=GHPexQVI8I0

Me ha parecido cuanto menos interesante

**Comment by Wiinter** [comment]
El area la tira antes de qe "exploten " los ojos, antes de qe pasen los 10s. Estas matando ojos y te tienes qe separar porque sino te mata el area. Te separas y mueres por los ojos.

**Comment by paellaencol** [comment]
Sería posible revisar el intervalo de 10segundos que debe haber entre estas dos skills? 
 "Ojos de Occu'thar" http://es.wowhead.com/spell=96920/ojos-de-occuthar y Sombras abrasadoras http://es.wowhead.com/spell=96913

Ojos de Occu'thar
¡Occu'thar invoca una horda de sus ojos para sembrar la destrucción! Los ojos se pegan a los jugadores, lo que inflige 8775 to 9225 p. de daño de las Sombras cada 1 s. Tras 10 s, los ojos explotan, lo que provoca la Destrucción de Occu'thar.

En resumen Destrucción de Occu'thar http://es.wowhead.com/spell=96968/ y  Sombras abrasadoras http://es.wowhead.com/spell=96913 deben coincidir en el tiempo, ya que su intervalo es el mismo. Claro que si se matan los ojos a tiempo no debería producirse Destrucción de Occu'thar

P.D. Wiinter, mira a ver si puedes cambiar el post inicial, ya que diría que la habilidad que castea para activar los ojos es "Ojos de Occu'thar" http://es.wowhead.com/spell=96920/ojos-de-occuthar  y no Mirada de Occu'thar = http://es.wowhead.com/spell=96942. Y es "Ojos de Occu'thar" la que debe respetar los 10segundos de pausa.

**Comment by Wiinter** [comment]
Tienes razón, ahora mismo actualizo el post.
Lo de las sombras abrasadoras no me he fijado, diría que no depende de los ojos. Y es por eso que no lo hace 10 segundos después de castear Ojos de Occu'thar

**Comment by Wiinter** [comment]
Ahora mismo está metiendo dos areas muy seguidas. Hay veces qe hay dos areas activas a la vez

**Comment by Kiritoo** [comment]
Fix
