### ISSUE TITLE
[Mision] (Monte hyjal) Vuelo en las Tierras de Fuego

### ISSUE THREAD

**Issue by Albertiktik** [RoDNet/Bugtracker-Infinium-4.3.4#2124]
Vuelo en las Tierras de Fuego

http://www.wowhead.com/quest=25523

Consigue y equipa una flamanza Crepuscular del estante de detrás de Farden. Monta en uno de los guardianes de Aviana y vuela hasta una bandera de guardián en el saliente de abajo. ¡Pulsa el botón Aletear para agitar las alas de tu montura! 

El problema es que cuando coges Guardián de Aviana (http://www.wowhead.com/npc=39710) la habilidad aletear (http://www.wowhead.com/npc=39710) no te impulsa ni nada y acabas estrellandote contra el suelo, con lo cual no puedes visitar la bandera de guardián que es lo que te pide para completar la mision.

Cuando entras por el portal que lleva a esta mision el personaje vuela sin montura ni nada, he llegado asi a la bandera pero de todas formas no me completa la mision.

**Comment by paellaencol** [comment]
esta cadena de misiones creo que la pusieron autocompletable

**Comment by Albertiktik** [comment]
Pues yo la he intentado hacer hoy y no se ha autocompletado nada...

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1524
