### ISSUE TITLE
[Guerrero] Golpe heroico Id: 78

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2125]
Enlace desde wowhead: http://www.wowhead.com/spell=78

La fórmula para este parche es 0.6 x AP

Sin embargo en la imagen se aprecia como recibo un golpe de 29k de daño, teniendo en cuenta que este ataque tiene 3 segundos de CD, y tengo un 40% de reduccion de daño via temple, más un 20% extra via talentos, más un 40% de daño físico reducido por armadura (que contra un guerrero en este caso sería solo de un 20%). Pues aún así recibí ese impacto.

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/13/uj90.jpg/'><img src='http://img13.imageshack.us/img13/4169/uj90.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

La verdad, me llamó mucho la atención, ya que se necesitan 25k de poder de ataque para inflingirle ese daño a un dummy, y siendo contra un jugador que te reduce el daño inflingido en más de un 60% pues todavía se necesita más AP.

**Comment by ghost** [comment]
Bueno, es una bg. Los bufos están bug (se acumulan los bufos que aumentan el AP) y también podría llevar rabiar de bg, puede que tenga que ver. Aún así, no estaría mal revisar las fórmulas porque los guerreros tienen un daño que no tiene ninguna otra clase ahora mismo. ¿Podrías testear Sed de sangre?

Fórmula precisa: 8 + 0.6*AP

**Comment by paellaencol** [comment]
Recuerdo además ver como al acabar la bg, los dos primeros en dps fueron guerreros, y el primer pj no guerrero estuvo a un millon y medio del primero (guerrero)

**Comment by elmiriox15** [comment]
Asmas te responderé a lo de Sed de Sangre, según el juego está haciendo el daño correcto, pone que pega 10k y está pegando 10k, así que esa skill no debería pegar de más.
