### ISSUE TITLE
[Guerrero] [Talento] Precisión

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#2126]
Nombre: Precisión
ID: http://cata.openwow.com/spell=29592
Descripción: Aumenta un 3% tu probabilidad de golpear con tus ataques y aumenta un 40% el daño de ataque automático.
Problema: El 3% de golpe no se ve reflejado en las estadísticas, pero creo que si lo da, pero el 40% de daño de autoataque no lo da, probe en armas con una espada de 1 mano e inflige 3k, luego en furia con el 40% del pasivo y hace el mismo.

**Comment by ghost** [comment]
¿Puede ser que esté activo aun sin tener el talento? ¿y que cuando lo actives no tengas beneficio extra porque ya lo tenías activado?

No te lo tomes a mal, ha pasado con muchos talentos y glifos, y los warr meten toñas interesantes, también tengo uno xD

Sólo por testear.

**Comment by elmiriox15** [comment]
Mmmmm puede ser, no había pensado en eso.

**Comment by searum** [comment]
fix

**Comment by ghost** [comment]
Gracias Searum, era bug visual finalmente o no funcionaba?

**Comment by elmiriox15** [comment]
Searum, ya no da el 3% ese de golpe.
