### ISSUE TITLE
[Hechizos/Talentos] Pícaro - Aluvión de Acero (Combate)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2129]
Buenas.
• Nombre: Aluvión de Acero (Combate)
• Enlace: http://cata.openwow.com/spell=13877
• Descripción: Permite que todos tus ataques golpeen a un enemigo cercano extra pero reduce tu regeneración de energía mientras está activo. Utilízalo solo cuando luches contra más de un enemigo.
• Problema: No golpea a ningún enemigo cercano extra.
Gracias.

**Comment by searum** [comment]
fix
