### ISSUE TITLE
Movimiento al desmontar

### ISSUE THREAD

**Issue by raulfergis** [RoDNet/Bugtracker-Infinium-4.3.4#213]
Cuando desmontas te quedas en movimiento y tienes que moverte para poder realizar cualquier acción, esto impide hablar con cualquier Npc o farmear de forma instantánea teniendo que hacer lo explicado al principio.

**Comment by ghost** [comment]
Si, es extremadamente molesto xd.

**Comment by lamaza** [comment]
Tampoco permite usar spell o items

**Comment by ghost** [comment]
Ni desconectarte xD Tienes que moverte para desconectarte.

**Comment by ghost** [comment]
Basicamente, cualquier acción que no se pueda realizar en movimiento, no la puedes hacer al desmontar xd.
