### ISSUE TITLE
[Abalorio] Artefacto de Khaz'goroth

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#2130]
Nombre: Artefacto de Khaz'goroth
ID: http://es.wowhead.com/item=68972
Descripción:  Tus golpes críticos cuerpo a cuerpo otorgan Poder titánico, lo que te permite cargar este artefacto. Poder titánico se acumula hasta 5 veces y dura 30 s.

 Consume todo el Poder titánico para aumentar 508 p. tu golpe crítico, tu celeridad o tu maestría por cada Poder titánico acumulado y dura 15 s. El artefacto siempre elegirá el índice más elevado de los tres.

Problema: se acumula las 5 cargas pero al usarlo no pasa nada solo se gasta su cd y punto.
Observaciones: está compartiendo el cd con los abalorios de PvP de activación cuando no debería

PD: según wowhead si debería pero en los vídeos del oficial los utilizan a la vez en una misma macro.

Por favor si puedieran arreglarlo pronto se los agradecería ya que es un item comprado en la tienda.

**Comment by searum** [comment]
fix, falta test ingame.
