### ISSUE TITLE
[Hechizos/Talentos] Pícaro - Golpe Revelador (Combate)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2131]
Buenas.
• Nombre: Golpe Revelador 
• Enlace: http://wow.freakz.ro/spells.php?spell=84617
• Descripción: Un golpe instantáneo que inflige un 125% de daño con arma y expone las debilidades del objetivo. Aumenta un 35% la efectividad de tu siguiente remate ofensivo sobre el objetivo. Otorga 1 p. de combo.
• Problema: El efecto desaparece cuando un compañero de grupo/banda usa una habilidad contra el objetivo, potenciando esta en vez de la del pícaro.
• Observaciones: La descripción que tenía en el juego no concordaba con la del wowhead, asi que puse el enlace de wowfreakz que era la mas parecida.
Muchas gracias.

**Comment by searum** [comment]
fix
