### ISSUE TITLE
[Items/Objetos] Formulario de socio del Club de la "Cerveza del Mes"

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2132]
Buenas.
• Nombre: Formulario de socio del Club de la "Cerveza del Mes"
• Enlace: http://es.wowhead.com/item=37736 o http://es.wowhead.com/item=37571
• Descripción: Este objeto inicia una misión
• Problema: Este objeto no inicia ninguna misión
• Observaciones: Debería dar la misión Club de la Cerveza del Mes (Alianza)(http://es.wowhead.com/quest=12278); el objeto se lo compré al PNJ Belbi Tiratrastos (http://es.wowhead.com/npc=23710); el objeto lo compré siendo huargen.
Gracias y hasta luego.

**Comment by paellaencol** [comment]
A ver si te ocurre eso por culpa de tu raza (que a los goblins antes les pasaba).

Sin embargo, probado de hace una hora, no he tenido ningún problema con el objeto de misión que compras.

**Comment by ghost** [comment]
En ese caso, agrego que lo compré siendo huargen.
Gracias.

**Comment by lamaza** [comment]
Yo siendo humano y tampoco me da la misión, mal para los alis =(

**Comment by redneo** [comment]
Arreglado

**Comment by lamaza** [comment]
Graciasª!!!!!!!!!!!!!!!!!!!!!!!!
