### ISSUE TITLE
Hechizo (Mago) - Hechizos de casteo

### ISSUE THREAD

**Issue by moriaar** [RoDNet/Bugtracker-Infinium-4.3.4#2134]
Nombre: Cualquier hechizo de casteo (Explosión arcana, Descarga de pirofrío, Descarga de fuego, etc.)

Enlace: http://es.wowhead.com/spell=3110/descarga-de-fuego
http://es.wowhead.com/spell=44614/descarga-de-pirofrio
http://es.wowhead.com/spell=30451/explosion-arcana

Descripción: Son hechizos que requieren un tiempo de casteo antes de ser lanzados.

Problema: No los he puesto todos porque sería muy largo, pero es un problema en cualquier hechizo de casteo de los magos, mientras están casteando, al recibir un daño, el casteo se detiene, como si lo hubieran silenciado.

Observación: Tengo un amigo Sacerdote y, según me ha comentado, a él también le sucede, puede que sea un problema de los personajes casters.

**Comment by ghost** [comment]
Con mi mago fuego no me pasa...sólo me ha pasado en ocasiones muy puntuales casteando evocación en arenas. Se lo achacaba a Bomba viva, pero estuve testeando y sólo le interrumpí el casteo una vez a un sacer :S supongo que el bug no es de los casteos del mago, si no de otras habilidades que están provocando interrupciones y no deberían, o incluso de algún talento.

**Comment by Wiinter** [comment]
Debe ser cosa de magos, de casters no. Almenos no de brujos.

**Comment by redneo** [comment]
Que especializacion de talentos teneis con ambos magos?

**Comment by moriaar** [comment]
Mago Arcano, me pasa y me sigue pasando, y es una desventaja porque sólo puedo usar hechizos instantáneos, los otros son rápidamente silenciados sin explicación.

**Comment by searum** [comment]
esto necesito un reporte con el talento que lo provoca... algun mago arcano que testee a castear mientras va colocando talentos 1 a 1 y que me diga con cual le sucede y lo arreglo... cierro este reporte
