### ISSUE TITLE
[Hechizos/Talentos] Pícaro - Precisión (Combate)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2135]
Buenas.
• Nombre: Precisión (Combate) Rango 3
• Enlace: http://cata.openwow.com/spell=13843 
• Descripción: Aumenta tu probabilidad de golpear con armas y ataques con venenos un 6%
• Problema: No se ve un aumento en la probabilidad de golpe en la información del personaje.
• Observaciones: Puede que sea un bug visual
Gracias!

**Comment by searum** [comment]
si q va
