### ISSUE TITLE
Talento (Mago) - Vórtice Abisal (Arcano)

### ISSUE THREAD

**Issue by moriaar** [RoDNet/Bugtracker-Infinium-4.3.4#2136]
Nombre: Vórtice Abisal

Enlace: En wowhead lo han borrado de la BBDD, pero aún se puede ver aquí: http://old.wowhead.com/search?q=nether+vortex#talents

Lo más parecido es esto: http://es.wowhead.com/spell=86209/nether-vortex#comments Ahí aparece como Glifo, pero en la v4.3.4 es un talento.

Descripción: Según el talento, cada vez que uso Explosión Arcana, automáticamente se aplica el hechizo de Ralentizar en el objetivo, si no hay otro hechizo de Ralentizar ya aplicado.

Problema: En lugar de aplicarse al objetivo, se aplica al jugador que lanza el hechizo, es decir, a ti mismo.

**Comment by searum** [comment]
fix
