### ISSUE TITLE
Engarce de Joyero

### ISSUE THREAD

**Issue by Sagittariu5** [RoDNet/Bugtracker-Infinium-4.3.4#2137]
Pues no lo venden en ningún lado ya lo he comprobado y sería de gran ayuda para subir la Joyería porque lo otro te pide demasiadas cosas y quita tiempo.

http://es.wowhead.com/item=52188/engarce-de-joyero

**Comment by ghost** [comment]
Buenas.
Si eres alianza lo puedes conseguir en tierras altas crepusculares, en la parte donde están todos los vendedores de profesiones.
Hasta luego.
