### ISSUE TITLE
Glifo de Socorro oscuro (Caballero de la Muerte)

### ISSUE THREAD

**Issue by Lorkien** [RoDNet/Bugtracker-Infinium-4.3.4#2138]
hola el glifo de socorro oscuro no funciona simplemente no funciona no hace nada aunque deveria curarme un 20% de la vida despues de matar a un horda al usar golpe letal.

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by searum** [comment]
fix
