### ISSUE TITLE
[Misión] Cubrirse las espaldas

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2139]
Danos pruebas de ello en vez de tanta habladuria bocas.

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

Prueba a borrar cache e intentarlo de nuevo.
