### ISSUE TITLE
Pérdida de objetos al cambiar de versión

### ISSUE THREAD

**Issue by kevinilo** [RoDNet/Bugtracker-Infinium-4.3.4#214]
Os quiero informar que al cambiar de versión se me han eliminado muchos objetos. Las 3 ultimas bolsas se me han ido, junto con los objetos que llevaban. Es muy posible que no sea el único al que le ha pasado.

https://f.cloud.github.com/assets/4630033/753008/a47a957e-e558-11e2-9437-6d58a9c826d8.jpg

**Comment by 50megas** [comment]
Mira el correo , ami me aparecieron hay

**Comment by ghost** [comment]
Creo que luego del rollback ya se solucionó.
