### ISSUE TITLE
[Brujo] Armadura vil: 28176

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2143]
http://wow.freakz.ro/spells.php?spell=28176
- Descripción: Este hechizo aumenta 637 p el poder con hechizos y hace que reciba un 3% de sanación de cualquier daño que inflinja contra un objetivo. Debe sumar dicha cantidad de spell al poder con hechizos.
- Problema: Está aumentando sólo el daño con hechizos, y no la sanación. Es decir, en las estadísticas normales del pj debe aparecer por defecto sólo la línea "Poder con hechizos" que es una cantidad extra que se añade tanto a tus hechizos de daño como de sanación. El problema es que esos 637p de la armadura, no se están añadiendo al poder con hechizos como debería, sino que se está añadiendo al DAÑO CON HECHIZOS. Esto provoca que la opción de "Poder con hechizos" del resumen del pj, desaparezca y se desglose en dos: "Daño con hechizos" y "Sanación con hechizos", debido a que se han dado valores diferentes para cada cosa y no es posible englobarlo dentro de lo standar (poder con hechizos). 

Resumiendo la explicación: El bug es que la armadura no está dando sanación con hechizos, sino sólo daño.
- Observaciones: Era el típico bug que salía antes con los trinkets de caster, que hacía que el poder con hechizos se desglosara en dos, sanación y daño, y sólo aumentaba una de las estadísticas.

<strong>Actualización, edito:</strong> Ahora es una habilidad totalmente inútil, ni sana al hacer daño ni da poder ni sanación con hechizos.

**Comment by Wiinter** [comment]
Creo qe te estas equivocando o puede qe no. Voy a dar mi versión y me dices si acierto o no. Cuando pones la armadura vil me imagino qe no te augmenta la sanacion por eso pones lo de la sanación por hechizos. Pero es qe las sanaciones que recibe el brujo no va por sanación por hechizos sino por porcentaje de vida. Entonces cuanta más vida tienes más te curas, no cuanta más poder con hechizos mas te curas.

Espero haberme explicado y espero no haberla cagado con el comentario.

**Comment by nicerdicer** [comment]
Y tampoco Wiinter, el % de sanación que ofrece Armadura Vil es del daño que le infligues al objetivo, es decir, si das un Tick de 2500 de daño por Aflicción Inestable (por ejemplo) te curarás un % de ese daño por Armadura Vil. Si es eso a lo que se refiere Asman, juraria que funciona bien.

SALUDOS!!

**Comment by ghost** [comment]
Lo intentaré explicar mejor arriba que veo que hay dudas jajaj

**Comment by Wiinter** [comment]
Si, como lo has explicado antes ya te he entendido, como lo que me estás diciendo. Pero es que aunqe no salga la sanación con hechizos, no pasa nada, porque el brujo no necesita sanación con hechizos. No la utiliza.

Espero no equivocarme

**Comment by ghost** [comment]
El bug está ahí de todos modos. Se lo que quieres decir, pero creo que hay algunas spells como cosecha de almas que sí que se benefician del poder con hechizos/sanación. Arreglando el bug nos aseguramos de que no haya malas funcionalidades.

**Comment by Wiinter** [comment]
Si, en esto último estoy de acuerdo. Mejor asegurarse

**Comment by Kiritoo** [comment]
Fix  ya otorga el sp
