### ISSUE TITLE
[Brujo] Pandemia (Rango 1)

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2144]
http://wow.freakz.ro/spells.php?spell=85099

Reduce el gcd de todos las maldiciones y aterrar. Además que tienes el 50% de refrescar aflicción inestable con drenar alma si un objetivo está por debajo de 25%.

El problema es que no refresca aflicción inestable con drenar alma, es como si tuviera una posibilidad de un 0%. Pero esto solo ocurre si tienes un punto de talento en este talento porque si tienes dos, cuando tienes un 100% de probabilidad de resfrescar, funciona bien.

**Comment by nicerdicer** [comment]
No has nombrado que lo que refresca Aflicción Inestable es Drenar Alma... si no tiras Drenar alma.... no se va a reiniciar nunca, a parte estar al loro de que lo tiras cuando el objetivo esta a 25% de vida o menos, y esa parte funciona bien, a mi al menos Drenar Alma contra objetivos a 25% o menos si que me reinicia la Inestable.

**Comment by Cacafuti** [comment]
Esta foto dice todo lo contrario http://d3j5vwomefv46c.cloudfront.net/photos/large/759341357.jpg?1366248496

**Comment by Wiinter** [comment]
Se te reinicia afliccion inestable si tienes los dos puntitos de pandemia si tienes uno no. He casteado 10 veces drenar alma a un objetivo por debajo del 25% y no se refresca aflicción. Te lo puede decir @Drogoth2 que lo he probado con su paladin

**Comment by searum** [comment]
fix
