### ISSUE TITLE
[objeto] Formulario de socio del club de la cerveza

### ISSUE THREAD

**Issue by didiii** [RoDNet/Bugtracker-Infinium-4.3.4#2146]
http://es.wowhead.com/item=37571/formulario-de-socio-del-club-de-la-cerveza-del-mes

La cosa es que en la alianza lo compras y no incica mision ni nada, le das y no te da la mision.

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2132

http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
