### ISSUE TITLE
Objeto: Engarce de Joyero.

### ISSUE THREAD

**Issue by Inmershus** [RoDNet/Bugtracker-Infinium-4.3.4#2148]
Para subir joyería es necesario (si no para todas, para la gran mayoría de recetas) un objeto que se llama Engarce de joyero. Este objeto se compra en la gran mayoría de NPCs de Suministros de Joyería.

El problema es que he mirado en varios vendedores (Dalaran, Ventormenta y Orgrimmar, pero imagino que si no está en esos tres que son las grandes capitales, no estará en el resto de NPCs que deberían venderlo).
El objeto se vende por unidades ilimitadas, es decir, no es que alguien lo haya comprado y como está agotado a mí no me sale. No es necesario ningún requisito para que aparezca el objeto ni nada por el estilo.

El link del objeto que falta es: http://es.wowhead.com/item=52188

PD: sé que ha sido reportado en el post de abajo, pero me ha parecido buena idea poner más detalles del problema.

**Comment by Monleon** [comment]
Reparado
