### ISSUE TITLE
[Spell]Guardián de los antiguos reyes

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#215]
Hola quiero volver a abrir un aporte en la habilidad del paladín
Guardián de los antiguos reyes - http://es.wowhead.com/spell=86669

Esto anteriormente ya lo habia reportado en https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/71

El problema que antes fallaba en las sanaciones esta habilidad, el problema de ahora es que directamente no aparece el guardian, esto empezo a fallar ayer tras las reparaciones del paladín.

Un saludo.

**Comment by searum** [comment]
fix
