### ISSUE TITLE
[Talento > Priest] Pain and Suffering

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2151]
Nombre: Dolor y sufrimiento
http://cata.openwow.com/spell=47581
Your Mind Flay has a 60% chance to refresh the duration of your Shadow Word: Pain on the target, and reduces the damage you take from your own Shadow Word: Death by 40%.

Problema: Nunca refresca la duración de Shadow Word: Death
http://cata.openwow.com/spell=32379

Un saludo.

**Comment by searum** [comment]
funciona..no tiene que refrescar esa duración xd
