### ISSUE TITLE
[Talento > Priest]  Improved Devouring Plague

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2153]
Nombre: Peste devoradora mejorada
http://cata.openwow.com/spell=63626
Your Devouring Plague instantly deals damage equal to 30% of its total periodic effect.

Problema: Debe de hacer 30% del daño total periodico un golpe al usarla que esta pegando de menos.
Devouring Plague http://cata.openwow.com/spell=2944

Un saludo.

**Comment by searum** [comment]
fix
