### ISSUE TITLE
Mascotas Rares y Espiritu, sin aparecer

### ISSUE THREAD

**Issue by patriccio** [RoDNet/Bugtracker-Infinium-4.3.4#2154]
Hola a los GM. agradeceria si pudieran revisar la aparicion de algunas mascotas del cazador , que estan al nivel 85, que no aparecen hace tiempo ya y que como estan las cosas que cuesta bastante leviar una pet, ellas son 

Colmillo de Jade: npc=49822
Reptafantasmas: npc=50051
Karoma <El Espíritu Lobo>: npc=50138 ( aparecio en el parche 4.0.3)
Ankha: npc=54318
Ban'thalos: npc=54320
Magria: npc=54319
esas son las principales y que aparecieron entre los parches 4.03.y 4.2.0, los demas espiritu de rasganorte estan todas. attd gracias

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Editalo.

**Comment by patriccio** [comment]
tendria que hacer un post de todos por separado ?

**Comment by SherBlader** [comment]
Tambien hay que saber que estas mascotas tienen cierto tipo de ''Respawn'', la unica forma de saber si no aparecen diria yo que es estar 1 dia esperando a que salga la pet, si no sale, ahi si.

**Comment by patriccio** [comment]
en eso estoy claro ,ya  que se las hora de respawn , y las unbicaciones lo, que pasa es que antes salian pero despues de un reinicio de db que hicieron no aparecieron mas.
