### ISSUE TITLE
Mascota rare (Colmillo de Jade) 

### ISSUE THREAD

**Issue by patriccio** [RoDNet/Bugtracker-Infinium-4.3.4#2155]
hola, a los gm, 
 Colmillo de Jade. http://es.wowhead.com/npc=49822
ubicacion: Infralar 
bug: hace meses que no aparece en su lugar , que muestra el wowhead, en su lugar aparece un arcon  o basija de nivel bajo.

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
