### ISSUE TITLE
Bestia Espiritu (Ban'thalos)

### ISSUE THREAD

**Issue by patriccio** [RoDNet/Bugtracker-Infinium-4.3.4#2156]
Ban'thalos : http://es.wowhead.com/npc=54320
ubicacion: Monte Hyjal
Problema: hace meses que no aparece en las coordenadas 26.6, 60.2 (santuario de malorne) su respanw es de 6 a 17horas.

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
