### ISSUE TITLE
[Guerrero] Glifo de Machaque Colosal

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2158]
Nombre: Glifo de Machaque Colosal
ID:http://es.wowhead.com/spell=89003

Descripcion: Tu Machaque colosal también le aplica el efecto de Hender armadura a tu objetivo.

Problema: No esta aplicando el efecto de herder de armadura.

Hender de armadura:7386

**Comment by Kiritoo** [comment]
Fix
