### ISSUE TITLE
[DK] Glifo de Golpe letal

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2159]
Nombre: Glifo de Golpe letal
ID: http://cata.openwow.com/spell=59337

Descripcion: El daño de tu Golpe letal aumentan un 2% (hasta un maximo 40%) por cada 5 p. de poder runico que tengas. Este efecto no consume poder runico.

Problema: siempre esta aumentando un 40% el daño de golpe letal deberia de ir aumentando un 2% por cada 5 de poder runico

**Comment by searum** [comment]
fix
