### ISSUE TITLE
[Mago] Talento : Masa Crítica.

### ISSUE THREAD

**Issue by Alfonn** [RoDNet/Bugtracker-Infinium-4.3.4#216]
Masa crítica : http://old.wowhead.com/spell=12873

Como bien dice la descripción (además de todo lo demás) Piroexplosión (http://old.wowhead.com/spell=92315) y Agostar(http://old.wowhead.com/spell=2948) deberían dejar en el objetivo masa crítica durante 30secs. Esto lo hace con Agostar : 

![image](https://f.cloud.github.com/assets/3854953/756893/4d671790-e651-11e2-8665-b93dffa542ed.png)

Pero en cambio con Piroexplosión no lo hace : 

![image](https://f.cloud.github.com/assets/3854953/756894/79f852ba-e651-11e2-94af-fbc3ea9ce0db.png)

**Comment by ghost** [comment]
Esto ya se puede cerrar, está solucionado.
