### ISSUE TITLE
[Decenso de alanegra] Sistema de defensa Imnitron

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#2162]
Nombre: Sistema de defensa Imnitron
ID: 
Arcanotron: http://es.wowhead.com/npc=42166
Electron: http://es.wowhead.com/npc=42179
Magmatron: http://es.wowhead.com/npc=42178
Toxitron: http://es.wowhead.com/npc=42180

Descripcion: Al matar estos boss aparece un cofre con el lot 

Problema: Tras matar los boss no aparece el cofre y nos quedamos sin lot...
![wowscrnshot_092513_164935](https://f.cloud.github.com/assets/3101842/1223149/6b31eb3e-270f-11e3-8ac3-4eef5da0a4ef.jpg)

**Comment by efectokoleos** [comment]
mm que yo sepa no hay ningun cofre, si no que son los bosses los que dan loot..

**Comment by F4NT4SM4** [comment]
mmm creo recordar que habia un cofre bueno si no hay los boss tampoco estan dando lot :l
