### ISSUE TITLE
[Mision] Entierra a esas cucarachas!

### ISSUE THREAD

**Issue by Bariloche123** [RoDNet/Bugtracker-Infinium-4.3.4#2168]
Pongo la bomba en los sumideros y nada sucede. ID: 11608

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by Wiinter** [comment]
Está también funciona, la hice ayer.
