### ISSUE TITLE
Cambio de Faccion

### ISSUE THREAD

**Issue by proezas** [RoDNet/Bugtracker-Infinium-4.3.4#2172]
Buenas hace unos dias done y cambie de faccion a mi unico personaje a la alianza ,  para mi sorpresa me desaparecieron cosas que no tendrian que haber desaparecido al efectuar un cambio de faccion que nombrare acontinuacion.
Otra de las muchas cosas fue al seleccionar la raza en el libro de echizo de las raciales tambien desaparecieron cosas que tendrian que haberse añadido por racial del hombre lobo.
-Perdidas: Oro , recetas aprendidas, monedas de profesion , logros de exploracion , logros de hermandad (eso no se si se resetea pero de resetearse los logros se tendrian que haber reseteado la reputacion tambien cosa que eso permanece tal y como la tenia en la orda.) , honor de bg , algunas de las reputaciones y seguramente mas cosas que se me escapan de la mala hostia... de haber donado para gastarme el dinero y perder la mitad de las cosas importantes de mi personaje que si revisan soy viejo en el servidor.... y bueno e mandado tiquets ingame para hablar con gm pero tampoco es que me solucionen nada.. ni tan siquiera las  habilidades de las raciales del hombre lobo como cambio de forma , sprint y demas.
Gracias,

**Comment by Kiritoo** [comment]
Crea un mensaje en el foro de la web esto es para reportar fallos del juego  no incidencias.
Cierro.
