### ISSUE TITLE
Bug elemental mag@

### ISSUE THREAD

**Issue by Buuffyy** [RoDNet/Bugtracker-Infinium-4.3.4#2173]
A ver resulta que al invocar a mi elemental de agua, sale ardiendo y rojo y se le va quitando vida y muere, entonces yo no puedo invocar a mi elemental por que solo invocarlo pasa un tiempo y muere....

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
