### ISSUE TITLE
[Mision] Viaje en alfombra magica

### ISSUE THREAD

**Issue by Bariloche123** [RoDNet/Bugtracker-Infinium-4.3.4#2174]
Le hablo al npc Yanni(ID:25459) me monta en la alfombra y me desmonta al instante y no completa la mision(ID:11636)

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

Ya reportado. https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1721

**Comment by Wiinter** [comment]
Si se completa la misión, la hice ayer.
