### ISSUE TITLE
[Armería] Ira (Visual)

### ISSUE THREAD

**Issue by iBrianAR** [RoDNet/Bugtracker-Infinium-4.3.4#2182]
Hola. ¿Cómo andan?

Es una estupidez que reporte esto, pero sos errores visuales que a mi me molestan, digo... un servidor tan bueno no puede tener estos errores y hay que reportarlos así los arreglan y así el servidor vaya progresando más y más :]

Acá la imagen lo dice todo:

<img src="http://img196.imageshack.us/img196/4194/p82e.jpg"></img>

**Comment by ghost** [comment]
La armería no está al 100% actualmente. Tampoco da los valores reales de los atributos, dudo que tengas 660 de poder de ataque, ¿verdad? Es sólo a modo orientativo, para ver el equipo, talentos y equipo de arenas. 

Antes se veían los glifos también, pero ahora se muestran las ranuras vacías.

Ya lo irán mejorando poco a poco junto a la web :)

Saludos!

**Comment by Kiritoo** [comment]
Los reportes de la web en el foro porfavor.
Saludos.
