### ISSUE TITLE
[Misión] (Zul'Drak) The Champion of Anguish

### ISSUE THREAD

**Issue by moriaar** [RoDNet/Bugtracker-Infinium-4.3.4#2183]
Está es la última misión del anfiteatro de zul´drak tras pasarla te dan el logro.
El campeón de angustia http://es.wowhead.com/quest=12948

El problema d está misión es que al cojerla no aparece el npc que se debe matar.
Vladof el Carnicero http://es.wowhead.com/npc=30022

Video: http://www.youtube.com/watch?v=O9IIFJWbm44 Minuto 1:10

Un gm dijo que la arreglaron y cerró una antigua issue, pero yo fui a hacerla y sigue sin ir, eso sí, al aceptar la misión el personaje entra en combate automáticamente.

**Comment by searum** [comment]
vale ahora si esta fix
