### ISSUE TITLE
[Misión][Infralar]Escolta intensiva

### ISSUE THREAD

**Issue by minidemo** [RoDNet/Bugtracker-Infinium-4.3.4#2184]
http://www.wowhead.com/quest=26632
Esta es la tercera quest de una cadena de 6 en la que supuestamente has de escoltar unas catapultas y  ni deja hablar con el npc para que comience el evento de quest ni nada de nada, y prácticamente has de hacer todas las quests de infralar si quieres que te salte la cadena de therazane

**Comment by ghost** [comment]
Ya reportado. https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1082
