### ISSUE TITLE
Bug La batalla por glineas BG

### ISSUE THREAD

**Issue by mxniox1234** [RoDNet/Bugtracker-Infinium-4.3.4#2187]
Nombre: Mxniox (pj)
Buenas 
Les quería comentar de un inconveniente con mi pj siempre que me meto en la bg anteriormente dicha en el titulo (batalla por glineas) inmediatamente me aparese wow error y no me deja ni salir de la bg ni mover el pj 
Después me toca poner un ticket para que un mj me asesore 
Algunas veses el mj me tele trasporta a "ventormenta" y en verdad me invoca a el camino de la muerte donde ahy no puedo utilizar ninguna clase de hechizos,piedra de hogar, monturas etc 
Ya me ha pasado varias veses quisiera que arreglaran el bug anterior mente dicho para facilitar la jugabilidad sin inconveniencias de bug 
De ante mano muchas gracias

**Comment by ghost** [comment]
has hecho el post dos veces, además, no es un bug general si no me equivoco, sino un problema con tu pj proque no he oido eso antes...Creo que lo propio sería que cerrases tus dos reportes y abrieras un post en el foro en soporte técnico.

**Comment by Kiritoo** [comment]
Hola como te comenta Asman creo que debes abrir un post en el foro en el area correcta, para que  ye ayuden ya que no es un error del juego.
Saludos.
