### ISSUE TITLE
Menas y Hierbas zona cataclysm

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#219]
Hola quiero hacer un reporte un poco mas completo de las menas y hierbas en las zonas del cata.

<h4>*Uldum - http://es.wowhead.com/zone=5034</h4>

-Menas:Hay muy pocas, casi se cuentan con las manos, deben añadirse más.
-Hierbas:Pasa lo mismo que con las menas.

*Debería haber:
-Depósito de pirita: http://es.wowhead.com/object=202737
-Filón de elementium: http://es.wowhead.com/object=202738
-Filón de elementium rico: http://es.wowhead.com/object=202741
-Colátigo: http://es.wowhead.com/object=202752
-Flor de ceniza: http://es.wowhead.com/object=202747

<h4>*Hyjal - http://es.wowhead.com/zone=616</h4>

-Menas:No hay menas, encontramos 3 juntas en el mismo punto
-Hierbas: Aqui si que hay algunas pero aun faltan por poner.

*Debería haber:
-Depósito de obsidium: http://es.wowhead.com/object=202736
-Flor de ceniza: http://es.wowhead.com/object=202747
-Velo de Azshara: http://es.wowhead.com/object=202749
-Viñaviento: http://es.wowhead.com/object=202748

<h4>*Infralar - http://es.wowhead.com/zone=5042</h4>

-Menas:No encontramos ni la primera jaja.
-Hierbas:No encontramos ni la primera ^^

*Debería haber:
-Depósito de obsidium: http://es.wowhead.com/object=202736
-Depósito de obsidium rico: http://es.wowhead.com/object=202739
-Filón de elementium: http://es.wowhead.com/object=202738
-Filón de elementium rico: http://es.wowhead.com/object=202741
-Flor de corazón: http://es.wowhead.com/object=202750
-Flor de ceniza: http://es.wowhead.com/object=202747

<h4>*Tierras altas crepusculares - http://es.wowhead.com/zone=4922</h4>

-Menas:No hay menas.
-Hierbas:Tampoco encontramos hierbas.

*Debería haber:
-Depósito de pirita: http://es.wowhead.com/object=202737
-Filón de elementium: http://es.wowhead.com/object=202738
-Filón de elementium rico: http://es.wowhead.com/object=202741
-Flor de ceniza: http://es.wowhead.com/object=202747
-Jazmín Crepuscular: http://es.wowhead.com/object=202751

<h4>*Vashj'ir - http://es.wowhead.com/zone=5146</h4>

_INFO_:Esta zona no podemos testarla, no va el portal a Vashj´ir de Orgrimmar.
-Menas:?
-Hierbas:?

*Debería haber:
-Depósito de obsidium: http://es.wowhead.com/object=202736
-Velo de Azshara: http://es.wowhead.com/object=202749
-Viñaviento: http://es.wowhead.com/object=202748

<h4>*Península de Tol Barad - http://es.wowhead.com/zone=5389</h4>

-Menas:No hay ni una decena.
-Hierbas:Lo mismo.

*Debería haber:
-Depósito de pirita rico: http://es.wowhead.com/object=202740
-Filón de elementium: http://es.wowhead.com/object=202738
-Filón de elementium rico: http://es.wowhead.com/object=202741
-Flor de ceniza: http://es.wowhead.com/object=202747
-Velo de Azshara: http://es.wowhead.com/object=202749

Y quiero añadir, estos reportes que no estaban completos, https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/12 https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/31

Espero que este reporte sirva para implementar los filones restantes y las plantas.
Nosé quien me dijo que la cantidad de plantas-filones aumentaba al igual que la poblacion en el oficial, pero nose si el emulador hace esto, no creo.
Pienso que se deberian añadir cuando se pueda.

Muchas gracias, un saludo.

**Comment by crowel** [comment]
@Lvmb Añadido! ^^

**Comment by chipi666** [comment]
Hola tengo días tratando de subir minería y e encontrado muy pocos filones de cobre y estaño pero con respecto a plata y hierro son muy escasos en las zonas donde correspondería que hubiera por ejemplo ferelas.

http://es.wowhead.com/object=1733/filon-de-plata
http://es.wowhead.com/object=1735/deposito-de-hierro

Yo se que todavía estamos en pruebas dejo la nota para que se revise este dato que no solo filones de zonas cataclysmo son las que faltan si no las demás zonas ahí faltantes, saludos....

**Comment by crowel** [comment]
Hola quiero añadir que hay ciertas menas en particular en tierras crepusculares que tienen tiempo de reaparición demasiado rapido.
Tambien me gustaria si puede ser que se le añadiera el label al reporte ya que es algo fastidioso que siga sin haber menas y plantas como deberian.
Gracias y un saludo.

**Comment by Kiritoo** [comment]
Arreglado, falta implementar fix.
