### ISSUE TITLE
Misión (Gilneas) - Recuperar lo que es nuestro

### ISSUE THREAD

**Issue by Bluediamon** [RoDNet/Bugtracker-Infinium-4.3.4#2193]
Nombre: Recuperar lo que es nuestro

Enlace: http://es.wowhead.com/quest=24646

Descripción: Sopla el cuerno de Tal'doren en la Cabaña de la Espesura y recupera el artefacto misterioso de su interior.

Problema: Al entrar a la cabaña no está el contenedor Arca desgastada (http://es.wowhead.com/object=201939) el cual contiene el objeto de la misión Artefacto misterioso (http://es.wowhead.com/item=50086).

Observaciones: El objeto provisto de ésta misión Cuerno de Tal'doren
(http://es.wowhead.com/item=50134) no invoca al npc Tobias Mantoniebla, el cual debería de distraer a las npc Forestales Oscuras, cabe mencionar que ésta misión es el inicio de una cadena y al no poder completarse hace imposible poder avanzar en el juego.

**Comment by Kiritoo** [comment]
Actualmente si se puede completar ya que el objeto está en la cabaña, lo del item de misión si es verdad que no esta funcionando y se debe de mirar.
Saludos.

**Comment by harveyuchiha** [comment]
Actualmente y segun varios jugadores me han dicho ke si se espera un tiempo determinado el objeto en cuestion de la mision aparece, pero ya llevo mas de 3 horas esperando y nada, y pues segun veo es bug del server, no estoy criticando su buena accion y resultados en el server solo kiero saber cuando lo pueden arreglar y si de no ser asi hacer esa mision ke se acabe apenas se coja y continuar con la historia

gracias de antemano espero respuesta y pronta solucion n.n

**Comment by Monleon** [comment]
Las misiones de los huargens ya funcionan perfectamente de inicio a fin
