### ISSUE TITLE
[Rayo solar] Druida equilibrio

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2194]
Buenas tardes
El hechizo Rayo solar del druida equilibrio http://es.wowhead.com/spell=78675/rayo-solar está silenciando aún estando a 40 metros de la ubicación elegida por el druida enemigo, cuando debería silenciar solo a los objetivos que se encuentren debajo de donde esté el "rayo solar"

Es decir, tal como está funcionando ahora, son 8segundos de silencio a todos los rivales hasta que desaparezca el debuff aplicado por el druida (cuya duración son 8seg también).

Añado, que ha vuelto a suceder el problema que se había resuelto eficazmente aquí:

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1123

Añado imagenes:

http://www.reignofdarkness.net/wow/forums/19-denuncias-a-jugadores/124-uso-de-rayo-solar-por-parte-de-udyr/

**Comment by crowel** [comment]
![wowscrnshot_092813_214204](https://f.cloud.github.com/assets/3537253/1233545/b3c6ae56-2931-11e3-88da-8a9e1e396911.jpg)

Imagen de ayer, fijaros lo que me aparte y me seguia silenciando.

**Comment by redneo** [comment]
arreglado
