### ISSUE TITLE
[Sacerdote] Palabra de poder escudo ID:17

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2195]
Buenos tardes.

Enlace: http://es.wowhead.com/spell=17/palabra-de-poder-escudo

Antes que nada, me gustaría publicar aquí la fórmula que debería tener este hechizo de absorción, ya que desde que se implementó este parche, la sanación de éste ha ido variando por semanas.

La fórmula para el parche 4.3.4 es la siguiente:

8136 (de absorción base) + (0.87 x Poder con hechizos)

A esto hay que multiplicarle diversos modificadores si se llevan los talentos correctos puestos.
Estos serian

x1.06 via "Disciplinas gemelas" ID: 47588 https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1727
x1.2 via "Palabra de poder mejorada: escudo" ID: 14768
x1.2 via "Maestría: escudo de disciplina" ID: 77484 https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1494 (esto como maestría base). Cada punto de maestría otorgaría un multiplicador de 1.025 extra

Aparte de que hay dos multiplicadores que no funcionan, que he enlazado con sendos reportes del bugtracker: "Disciplinas gemelas" y "Maestría: escudo de disciplina". La fórmula tampoco es la correcta

En los siguiente ejemplos voy a obviar los multiplicadores que están bug y no funcionan, y voy a quedarme con la parte que en teoría va correctamente.

-En la primera imagen tengo 801 de poder con hechizos.
Aplicando la fórmula [8136 + (0.87x801)] x1.2 via "Palabra de poder mejorada: escudo" ID: 14768= 10599

Sin embargo en la imagen sale 10538 (saldo negativo de 61)
<a href="http://imageshack.us/photo/my-images/534/jm22.jpg/" target="_blank"><img src="http://imageshack.us/a/img534/8941/jm22.th.jpg" border="0"/></a>
http://imageshack.us/a/img534/8941/jm22.jpg

-En la segunda imagen se observa como este problema escala con el equipo, haciendo que el poder con hechizos no escale bien (valga la redundancia).
Ejemplo: 8691 de poder con hechizos.
Aplicando la fórmula [8136 + (0.87x8691)] x1.2=18837

Sin embargo en la imagen absorbe 18176 (saldo negativo de 661)

<a href="http://imageshack.us/photo/my-images/856/1d1r.jpg/" target="_blank"><img src="http://imageshack.us/a/img856/4113/1d1r.th.jpg" border="0"/></a>

http://imageshack.us/a/img856/4113/1d1r.jpg

En resumen, hay que revisar el multiplicador de 0.87x poder con hechizos, y el resto de multiplicadores (que no vienen al tema, ya que forman parte de otro reporte)

---

Por último añado un enlace a la página web desde donde he sacado la formula: http://elitistjerks.com/f77/t127522-4_3_discipline_priest_compendium/#Spell_Coefficients_and_Formulas

Gracias por la paciencia!

**Comment by ghost** [comment]
Actualmente está dando una cantidad mínima fija o algo...Sacer al nivel 14 absorbe 9816, a partir de ahí va absorbiendo un poco más por el poco poder de hechizos que consiga.

**Comment by lamaza** [comment]
a nivel 14 un twink haria como 100-200 de daño full equipado por críticos. Cuando vas a bajar 9k?

**Comment by efectokoleos** [comment]
arreglada la absorcion
