### ISSUE TITLE
Montura Mamut Bug!!

### ISSUE THREAD

**Issue by imcanar** [RoDNet/Bugtracker-Infinium-4.3.4#2196]
Los mercaderes de la montura del mamut estan bugeados le das a expulsar y no se bajan y no puedes llevar a pasajeros en el mamut.

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

Bonito logo por cierto.

**Comment by Kiritoo** [comment]
Arreglada la función de expulsar pasajeros, falta compilar.
