### ISSUE TITLE
Problemas con mis profesiones

### ISSUE THREAD

**Issue by Creamfour** [RoDNet/Bugtracker-Infinium-4.3.4#2197]
Hace unos días se me bloqueó el libro de profesiones, y ahora no puedo ni usar las profesiones secundarias ni la nueva primaria que acabo de aprender, hablé con Nervo y cuando contactó con Searum me dijo que planteara el problema aquí, en el bugtracker, así que este es el problema:
![Uploading WoWScrnShot_093013_035724.jpg . . .]()

**Comment by Creamfour** [comment]
![wowscrnshot_093013_035724](https://f.cloud.github.com/assets/5413400/1234428/21ed34bc-2974-11e3-9a85-eda9d367788d.jpg)

**Comment by redneo** [comment]
Te tendria que poder dejar, para otra ya sabes que coger dos especializaciones de la misma profesión te chafa el pj.
