### ISSUE TITLE
mision bug

### ISSUE THREAD

**Issue by ronnondex** [RoDNet/Bugtracker-Infinium-4.3.4#2198]
la mision de la cadena de los hijos de hodir de matar a 10 protodracos con la lanza esta bugueada xq me tira de la montura al interactuar     

gracias

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by redneo** [comment]
se pusieron killcredits para esa mision y como dice fixx ojead como se tienen que postear minimamente los bugs!
