### ISSUE TITLE
Varios Bugs

### ISSUE THREAD

**Issue by Devilcray** [RoDNet/Bugtracker-Infinium-4.3.4#22]
Buenas noches, he estado "testeando" un poquito el parche antes de ir a dormir y he visto lo siguiente.

1- El buscador de mazmorras de este parche no funciona.
2- Cuando "creas" una piedra hogar en un tabernero el servidor se cae.
3- Los brujos cuando usan drenar vida no se curan y hacen un daño pésimo.
4- Cuando sacas cualquier cosa del banco de la guild te salta Wow Error (Comprobado por varias personas por si era problema de mi PC y le pasan lo mismo).

Por el momento es lo único que he encontrado, espero poder encontrar mas cosas para comunicarlo y así mejorar el rendimiento del servidor, muchas gracias y gran trabajo!

**Comment by Dekadencee** [comment]
2- Fixeado, seguimos trabajando

**Comment by Dekadencee** [comment]
El 4 no puedo confirmarlo, ami me funciona correctamente, es posible que sea problema de tu guild

**Comment by Dekadencee** [comment]
1- Los buscadores están funcionando correctamente, ¿donde está el error?

**Comment by Devilcray** [comment]
El buscador lo probé ayer y no me añadía a la cola, hablo del buscado de las mazmorras de este nuevo parche no del anterior, puede ser fallo mio por alguna cosa, no se xD

**Comment by Devilcray** [comment]
El 4 era problema de mi guild, ya esta arreglado, muchas gracias

**Comment by ghost** [comment]
"Buscador de mazmorras del nuevo parche"? no te refieres al Buscador de BANDAS? xd.

**Comment by Devilcray** [comment]
Es probable que sea el de bandas, sorry llevo unos dias empanao jajaja

**Comment by ghost** [comment]
Si puedes volver a comprobar los bugs @Devilcray y también pon un bug por reporte, si en un reporte hay bugs mezclados los devs no lo leeran.
