### ISSUE TITLE
[Mago]Teletransporte y portales

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#220]
Hola quiero añadir este bug.

Usando el teletransporte del mago no funciona a estas ubicaciones.

<h5>-Teletransporte a: Tol Barad:</h5>

http://es.wowhead.com/spell=88344
http://es.wowhead.com/spell=88342
Segun veo hay dos IDs distintas, me parece que el de la horda es el 1º, soy horda, nosé si en la alianza ocurre también.

<h5>-Teletransporte a: Cima del Trueno:</h5>

http://es.wowhead.com/spell=3566

Tras usar y castear el hechizo no ocurre nada, te quedas en el sitio.

<h5>-Portales de mago:</h5>

Quiero añadir que hay veces que no se pueden tomar los portales que crean los magos ( rara vez ) pero ya me ocurrio 3 veces, que yo sepa esto le ocurre a la gente del grupo/banda, no al propio mago.
Aun nose el problema exacto, no se aprecia.

Un saludo.

**Comment by Alfonn** [comment]
En la alianza ocurre igual, ''Teletransporte a : Tol Barad'' no funciona pero tampoco funciona Teletransporte a: Forjaz''(http://old.wowhead.com/spell=3562) que sería el que coincide con Cima del Trueno en la Horda. Saludos.

**Comment by lamaza** [comment]
Y otro bug de mago, que lo escuché pero no lo ví, es que al hacer translación frente a una pared o muro, el mago la transpasa, alguien puede probar?

**Comment by Alfonn** [comment]
Ese bug es falso , no se pueden atravesar paredes/muros.

**Comment by crowel** [comment]
Si que es cierto un amigo estaba en la puerta de baradin y uso trasladarse para entrar y aparecio por el otro lado del edificio, jaja precisamente ahora estamos al skype y nos estamos riendo xD

**Comment by lamaza** [comment]
Monten fotos o algo para reparar tremendo bug entonces. Yo no soy mago!

**Comment by Alfonn** [comment]
Claro, eso es otro bug diferente... Las puertas si se pueden traspasar (pero ese bug ya aviso que el 98,99% de los servidores lo tienen).Asi que es mejor centrarse en otras cosas.

**Comment by crowel** [comment]
El de tolbarad ya funciona tras los cambios de hoy.

Falta -Teletransporte a: Cima del Trueno:

http://es.wowhead.com/spell=3566

**Comment by searum** [comment]
esto funciona.
