### ISSUE TITLE
[Cazador] Radio de las trampas

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2200]
Buenas tardes.

Descripción:
El cazador es una clase que cuenta con la posibilidad de colocar trampas como forma de maximizar su juego. Las trampas que puede colocar son las siguientes:

http://es.wowhead.com/spell=1499 Trampa congelante.
http://es.wowhead.com/spell=34600 Trampa con culebras.
http://es.wowhead.com/spell=13809 Trampa de hielo.
http://es.wowhead.com/spell=13813 Trampa explosiva.
http://es.wowhead.com/spell=13795 Trampa de inmolación.

Todas estas trampas deberían tener un radio de activación de 2 metros.

-Problema: estas trampas se están activando estando a 5 metros del radio (y no a 2) de donde está ubicada (para poder obtener este cálculo he pedido que el cazador se pusiera inmediatamente encima de la trampa). Para poder comprobarlo me he ayudado del addon RangeDisplay http://www.curse.com/addons/wow/range-display

En la primera imagen se observa donde está situada la trampa
<img src="http://imageshack.us/a/img845/8329/6lg8.jpg" alt="Image Hosted by ImageShack.us"/><br/>

http://imageshack.us/a/img845/8329/6lg8.jpg

En la segunda imagen estoy todavía en un radio superior a 5 metros (justo en el límite):
<img src="http://imageshack.us/a/img404/4664/1rl4.jpg" alt="Image Hosted by ImageShack.us"/><br/>
http://imageshack.us/a/img404/4664/1rl4.jpg

Por último en esta tercera imagen, he llegado al radio de 5 metros de distancia y me ha saltado ya la trampa
<img src="http://imageshack.us/a/img822/6434/3d6l.jpg" alt="Image Hosted by ImageShack.us"/><br/>
http://imageshack.us/a/img822/6434/3d6l.jpg

Añado además, un par de imágenes extra:

<img src="http://imageshack.us/a/img689/3005/4u6j.jpg" alt="Image Hosted by ImageShack.us"/><br/>
http://imageshack.us/a/img689/3005/4u6j.jpg

<img src="http://imageshack.us/a/img196/8413/2p3l.jpg" alt="Image Hosted by ImageShack.us"/><br/>
http://imageshack.us/a/img196/8413/2p3l.jpg

**Comment by F4NT4SM4** [comment]
uno intenta esquivarlas pero nos congela y quedamos wtf pero ni la he pisado ._.

**Comment by searum** [comment]
pegaros con jetto the cry master

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/707

**Comment by paellaencol** [comment]
Si antes de reportarlo, busqué a ver si alguien lo había hecho anteriormente. Y me extrañó mucho que lo único que encontrara apuntase en la dirección opuesta.

Es por eso que me bajé un addon que mide la distancias para poder comprobarlo in situ. De hecho, llegué a pensar que alguien lo reparara a raíz de ese reporte, y se confundiera poniéndole 4 metros al radio.

**Comment by searum** [comment]
Nop, es mas yo he probado y muchas veces tienes que estar pegado a la trampa para que esta salte y otras a lo mejor solo tienes que pasar por delante sin estar a 2 m... Va un pelin raro pero tampoco es para montar ni tu issue ni el de jetto porque va asi desde que el wow es wow en todas partes xD

**Comment by cojidrin** [comment]
Yo te digo que siendo mele es imposible pegarte con un caza sin que te salte la trampa, aunque la rodees y pases a 5m de ella salta...

**Comment by redneo** [comment]
Segun base de datos:

Trampa congelante (gob id 2561) Radio 5 yardas
Trampa de culebras (Gob id 183957) Radio 5 Yardas
Trampa de hielo (Gob 164639) Radio 5 Yardas
Trampa explosiva (Gob 164839) Radio 5 Yardas
Trampa de inmolacion (Gob 164638) Radio 5 Yardas.

**Comment by F4NT4SM4** [comment]
segun wow head 2 metros siendo mele no podemos esquivar las trampas almenos que la rodeemos 6 metros hay se pierde tiempo miesntra el caza se aleja..... D:

**Comment by paellaencol** [comment]
Según lo que indica wowhead, y teniendo en cuenta que el radio, como dice searum y se puede ver en los patchnotes que no ha habido ningún cambio, ha permanecido intacto desde la aplicación de esta habilidad:

Trampa congelante Effect    Drop Trap (2561)
Radius: 2 yards

Trampa de culebras Effect   Drop Trap (183957)
Radius: 2 yards

Trampa de hielo Effect  Drop Trap (164639)
Radius: 2 yards

Trampa explosiva Effect Drop Trap (164839)
Radius: 2 yards

Trampa de inmolacion Effect Drop Trap (164638)
Radius: 2 yards

**Comment by redneo** [comment]
cambiado a dos metros.

**Comment by Sagittariu5** [comment]
Reabran la Issue
