### ISSUE TITLE
[Bug] Deposito de Vacio

### ISSUE THREAD

**Issue by Felarof23** [RoDNet/Bugtracker-Infinium-4.3.4#2201]
Hace un par de días artículos de mi deposito de vacio desaparecieron (no, no los retire, ni los regresé a mis bolsas comunes :P ) , hice una prueba con un collar y lo primero que noté es que no ocurre con los objetos que se colocan en la primer columna.

Saludos!

**Comment by Felarof23** [comment]
issue #495

**Comment by searum** [comment]
es un bug conocido, es solo visual los items se guardan cuando lo reparemos os apareceran. cierro porque hay otro reporte de esto ya
