### ISSUE TITLE
[Brujo] Coste de los hechizos de las pets

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2202]
Todas las pets necesitan mana para castear sus ataques.

Hace un mes o asi, las pets contaban con una mana de alrededor de 400k. El problema del mana abusivo fue subsanado pero creo que produjo otro error y es que el coste de algunos hechizos de algunas pets sigue subido como si tuvieras esa cantidad ingente de mana. Entonces la pet gasta mas mana de lo que puede suministrar. Por ejemplo cuando el manafago hace mordedura de las sombras, cada mordedura cuesta 12k de mana y el solo tiene 60k por tanto pega 2 bocados y aun teniendo cd de 6s se tiene qe esperar mas de 20s a que pueda poner otro.

Ahora paso a poner los enlaces de los hechizos que cuestan demasiado mana. En el enlace se puede ver el mana qe debería tener.
Manáfago
Mordedura de las sombras (http://cata.openwow.com/spell=54049)
Devorar Magia (http://cata.openwow.com/spell=19505)
Súcubo
Latigazo doloroso(http://cata.openwow.com/spell=7814)
Abisario
Consumir Sombras(http://cata.openwow.com/spell=17767)
Sufrimiento(http://cata.openwow.com/spell=17735)
Diablillo
Carbonizar magia(http://cata.openwow.com/spell=89808)
El guardia vil no puedo comprovar cuales están mal, porque no soy demo. Si tengo tiempo cambio de talentos y miro a ver como están.

**Comment by paellaencol** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1725
