### ISSUE TITLE
[Arenas] Llamar a arena

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2204]

**Comment by searum** [comment]
ratings de equipos y personales similares? el queue de arenas esta perfectamente el codigo no le pasa nada...

**Comment by ghost** [comment]
S

**Comment by Wiinter** [comment]
Las llamadas de las arenas es un sistema complejo que se basa en el indice de equipo y personal y en un indice oculto, el cual no se puede reiniciar. Este indice oculto seguramente será el principal culpable de que no te llame de forma normal. 
A varios de nuestra hermandad les ha pasado lo mismo y es porque teniamos altos indices ocultos por estar en los indices altos de las arenas. Diría que no se le puede hacer nada a este problema. Como mucho se podría reducir el tiempo de espera de 10 min a 5 min.

**Comment by ghost** [comment]
E
