### ISSUE TITLE
Misión (Entrañas) ¿Hace un lucio?

### ISSUE THREAD

**Issue by likaion** [RoDNet/Bugtracker-Infinium-4.3.4#2207]
Nombre: ¿Hace un lucio?

Enlace: http://es.wowhead.com/quest=29320

Descripción: Desentierra un gusano de cadáver en el patio de las Ruinas de Lordaeron y úsalo como cebo para pescar un lucio alimentado con cadáveres. Los lucios alimentados con cadáveres pueden pescarse en el Lago Aguasclaras, al noreste de Entrañas.

Problema: Para poder pescar el lucio alimentado con cadáveres necesitas antes desenterrar un gusano de cadáver. En principio, estos gusanos se encuentran en las tumbas de Lordaeron (afueras de Entrañas). Tendrían que estar en estos túmulos (http://es.wowhead.com/object=208828), pero no se pueden clicar. Adjunto foto

![wowscrnshot_093013_213421](https://f.cloud.github.com/assets/3774192/1240362/8291dd04-2a0a-11e3-856a-dbdca51fa3dc.jpg)

**Comment by likaion** [comment]
Actualizo. Veo ahora que hay otro report sobre esta quest (https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/427), pero el usuario que lo creó lo cerró sin recibir respuesta. Mantengo entonces este issue abierto.

**Comment by paellaencol** [comment]
Como curiosidad, que igual te ayude. Yo he llegado a pescar esos lucios http://es.wowhead.com/item=69909 aquí http://es.wowhead.com/item=69905#fished-in sin tener la quest, ni por supuesto el cebo http://es.wowhead.com/object=208828

**Comment by Wiinter** [comment]
No hace falta conseguir el gusano para pescar el lucio. Puedes ir directamente al lago y te saldrá sin necesidad de ningún gusano. 
Cerré el post porque Redneo lo arregló asi.

**Comment by likaion** [comment]
Sí... ya pensé que quizás pescando sin el cebo funcionaría, pero como lo probé un rato y no iba decidí postearlo. Ahora lo he vuelto a probar... tarda un rato pero acaba apareciendo el lucio.

Gracias por responder, compañeros :)

Cierre definitivo del report :)
