### ISSUE TITLE
Bug - Montura fenix oscuro

### ISSUE THREAD

**Issue by gusnasoto** [RoDNet/Bugtracker-Infinium-4.3.4#2210]
Hola buenas, tengo la montura del Fénix Oscuro pero no puedo invocarla, ni idea porque puede ser
http://es.wowhead.com/item=63125/riendas-del-fenix-oscuro
Un saludo y gracias

**Comment by Compresor** [comment]
Para poder montarlo requiere tener ciertos logros de Hermandad
