### ISSUE TITLE
Problemas con quest o npc de la cerveza

### ISSUE THREAD

**Issue by escontreras** [RoDNet/Bugtracker-Infinium-4.3.4#2212]
la mision grita por los cebadiz : http://es.wowhead.com/quest=11293/grita-por-los-cebadiz#. 

La completo en mi montura pero no me la deja entregar el npc me sale el boton completar pero en gris y la he intentado hacer varias veces

la mision Historia de una ida y una vuelta : http://es.wowhead.com/quest=11122/historia-de-una-ida-y-una-vuelta

No se puede hacer de ningun modo ya que no activa la montura no la podrian colocar por autocompletar solo porque es de evento y influye para conseguir el titulo ya que da las monedas de la cerveza

Me despido, Saludos cordiales a todos la gente de RoD

**Comment by lamaza** [comment]
Así  no se reportan las cosas. Busca las instrucciones de como hacerlo correctamente.

Misión #1 si se puede hacer con los CEBATRUENOS.

misión #2 ya esta reportada, usa el buscador la próxima vez. https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2062

Close this =).
