### ISSUE TITLE
Profundidades de Roca Negra

### ISSUE THREAD

**Issue by Heredill** [RoDNet/Bugtracker-Infinium-4.3.4#2214]
El boss del (alto justiciero piedrasiniestra) circulo de la ley no funciona, ya que debería enviar dos o tres oleadas de mobs y lo que hace es enviar una sola oleada y luego empezar a atacar a los jugadores cosa que no debería hacer.

**Comment by efectokoleos** [comment]
lo mismo te digo que en el otro post
