### ISSUE TITLE
[Misión] (Hyjal) A Champion's Collar

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2217]
Una collera de campeón 
http://es.wowhead.com/quest=25494

Obtén el pellejo de basilisco con pinchos de la matriarca Escamaespina. 

No está el npc o está invisible.
Matriarca Escamaespina http://es.wowhead.com/npc=40403

Un saludo.

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

reparado
