### ISSUE TITLE
[pj] no aparecen misiones en mapa

### ISSUE THREAD

**Issue by didiii** [RoDNet/Bugtracker-Infinium-4.3.4#2218]
Hola tengo un problema con mi pj Wolfar, no me aparecen en el mapa las misiones ni donde se localizan ni los numeros ni nada, ademas en el registro de misiones tampoco me aparee el minimapa en cada mision

**Comment by ghost** [comment]
Es un problema con tu personaje, no un bug general. Cierra issue y abre un post en el foro o pon ticket.

**Comment by didiii** [comment]
Puse ticket y no me lo pudoeron solucionar me dijeron que lo pusiera en el bugtracker
