### ISSUE TITLE
no aparece el personaje de sigue el girocoptero

### ISSUE THREAD

**Issue by angleheadsuli25** [RoDNet/Bugtracker-Infinium-4.3.4#2219]
Hola buen dia, tengo un problemita con una quest, se llama ¡Sigue al girocoptero!, en las montañas crestagranas en dun morog, no aparece el personaje para entregar la quest y el problema es que no libera las demas misiones

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
