### ISSUE TITLE
[hechizos] sentencias iluminadas

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#2220]
Bug: El hechizo(talento) no cura lo que dice.

En mi arbol de talentos pone que debe curar 4560, y realmente me esta sanando 2800 o 2900.

![wowscrnshot_100213_090548](https://f.cloud.github.com/assets/4790547/1258878/e2c4c180-2bce-11e3-9001-f0521cce81b3.jpg)

Solo me ha faltado el enlace, y eso que ya no existe en wowhead.

http://www.wowwiki.com/Enlightened_Judgements

http://wowpedia.org/Enlightened_Judgements

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by lamaza** [comment]
Reabrir por favor. @fixx

**Comment by searum** [comment]
sois unos tikismikis... la formula la hace bien no hay nada que cambiar
