### ISSUE TITLE
[Misión] Cumbres Tormentosas - Alcanzar a Brann

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2222]
El enlace de la misión es: http://es.wowhead.com/quest=12920

Al summonear a Bran te debería dejar hablar con él y completar la quest.

Al summonearlo, hablas con él, sale el gossip para hacer click, pero no te marca como si hubieses hablado con él. Por tanto no se puede completar la quest

**Comment by redneo** [comment]
fixed
