### ISSUE TITLE
[NPC] Falta Npc Dirkee (32500)

### ISSUE THREAD

**Issue by neoacadio** [RoDNet/Bugtracker-Infinium-4.3.4#2226]
Buenas, llevo una semana buscando a este NPC que deberia soltar de botin una receta de ingenieria aparte de que su muerte cuenta para el logro "Congelado" He estado toda la semana buscandole usando Npc Scan a distintas horas y me parece muy raro que no lo encuentre cuando he encontrado todos los demas rares despues de algun dia. Con este como digo llevo una semana y no lo veo, incluso he ido despues de reinicios de servidor y nada, no esta.

Es este: http://es.wowhead.com/npc=32500 

A ver si lo podeis arreglar que es el ultimo que me falta jeje.

**Comment by redneo** [comment]
Está
