### ISSUE TITLE
[Guerrero] Ataque de la victoria

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2227]
Enlace del hechizo: http://wow.freakz.ro/spells.php?spell=34428

Ataca al instante al objetivo, lo que inflige 1246 (+ 56% of Attack power) p. de daño y te sana un 20% de tu salud máxima.
Solo se puede usar durante los siguientes 20 s después de matar a un enemigo que aporte experiencia u honor.

El problema es que está realizando sanaciones críticas cuando esta sanación siempre debería ser la misma, a no ser qe varie nuestra salud máxima. Por tanto la sanación de Ataque de la victoria tiene un porcentaje de crítico que no debería tener. Este ataque tiene que tener un valor fijo de sananación que solo depende de nuestra salud máxima, valga la redundancia. Por ejemplo:
Lo que sucede ahora es que si tengo una salud máxima de 123k, puede ser que me salte un crítico de sanación de 110k, y lo que me debería saltar siempre, sino varío mi vida, serían 24,6k. Cabe decir que en el ejemplo no estoy contando con el glifo de Golpe de Victoria ni con el Talento de la rama de Armas "Vendaje de Batalla" que me augmentan la sanación.

Una cosa que he podido observar es que cuando realiza la cura sin critico siempre es el mismo valor y por tanto el correcto. Cuando hace la sanacion critica nunca es el mismo valor critico cada vez que te sale.

Espero que me haya explicado correctamente, cualquier duda no dudeis en contestar.

**Comment by ghost** [comment]
Gracias por reportarlo...Aclaro para que no haya dudas.

Ataque de victoria puede ser crítico (daño), lo que no debe ser crítico es su sanación, al estar basada en un porcentaje determinado de vida.

**Comment by elmiriox15** [comment]
¿Donde encontraste que no pueda ser crítico?
Por más que busco no veo ningún sitio donde lo ponga.
Si pudieras poner algún enlace o algo para aclararlo al 100%.

**Comment by ghost** [comment]
Elmiriox, los datos basados en porcentajes exactos de sanaciones no son críticos, en todos lados se da por hecho, yo también busqué y no se cuestiona nada. El <strong>daño</strong> de esa habilidad puede ser crítico, la sanación no, al igual que los pícaros no tienen críticos en el HoT de reposición, los magos en cauterizar y algunos más, tan sólo porque son basados en porcentajes exactos, siento no poder darte enlaces.

**Comment by Wiinter** [comment]
No es que lo tenga que poner explicitamente en ningun sitio, es que la propia habilidad ya te lo da a entender si te dice que tiene que ser siempre el 20% de la vida. Es lo qe dice Asman, es como los tics reposición, armadura vil, etc.. es la cura que es y es siempre la misma mientras no cambie tu vida.

**Comment by elmiriox15** [comment]
Vale yo lo decía porque siempre que he jugado Cataclysm podía salir crítico, pero un amigo del oficial me dijo que no puede.
Con lo cual esta bug y puede salir crítico.

**Comment by searum** [comment]
fix
