### ISSUE TITLE
[Banda] Trono de los Cuatro Vientos

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2229]
Justo en la plataforma de entrada esta el teleport de aire que te lleva a Al'Akir, el último boss. No te debería dejar a no ser que hayas matado al Enclave del aire primero.

Los puentes de viento para pasar entre los bosses del enclave no van. Solo va el de retorno de Neshir a Anzhal.

Neshir castea Viento Escalofriante(http://es.wowhead.com/spell=84645) y le hace daño a la raid entera y solo debería a los que estan a 90 metros a su alrededor.

Anshal tira la habilidad Vientos Fulminadores(http://es.wowhead.com/spell=85576) aunque tenga enemigos cerca, en su misma plataforma.

Al matar al cónclave te debería desbloquear Al'Akir y permitirte atacarle.
No me he podido fijar con mucho detalle porque ha sido un wipe al momento, diría que había más habilidades bug pero no las he podido detectar porque no me ha dado tiempo.

Aqui dejo los enlaces de los bosses:
http://es.wowhead.com/zone=5638
http://es.wowhead.com/npc=45870 -->Anshal
http://es.wowhead.com/npc=45871 -->Nezir
http://es.wowhead.com/npc=45872 --> Rohash
http://es.wowhead.com/npc=46753 --> Al'Akir

**Comment by Compresor** [comment]
Conclave funcional.
