### ISSUE TITLE
[Mazmorra] Cámaras de Piedra - Sjonnir el Afilador

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2232]
http://es.wowhead.com/npc=27978

Los trogs que saca no se pueden matar y debería dejar matarlos. Además que debería sacar una babosas cuando llega al 50% de vida y al entrar en contacto con el boss deberían transformarse. Saca muy pocos adds
Enlaces de los adds:
http://es.wowhead.com/npc=27978 --> Enano
http://es.wowhead.com/npc=27979 --> Trogg
http://es.wowhead.com/npc=27981 --> Babosas

**Comment by Kiritoo** [comment]
Fix
