### ISSUE TITLE
fallo en herreria

### ISSUE THREAD

**Issue by Elcuevas** [RoDNet/Bugtracker-Infinium-4.3.4#2234]
hola
los pergaminis de nivel 515 no funcionan
pone que el hechizo no esta disponible para ti
pueden ayudarme
mi personaje es  Elcuevas
gracias

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
