### ISSUE TITLE
Zona de inicio huargen (refugio del ocaso)

### ISSUE THREAD

**Issue by franky91** [RoDNet/Bugtracker-Infinium-4.3.4#2235]
Buenas, despues de haber salido de la Ciudad de Gilneas, me ha ocurrido que no he podido interactuar con el intructor de picaros, y tampoco me dan mision en tal sitio, tampoco he podido comprar, vender o reparar objetos en Refugio del Ocaso. Gracias por su atención.

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
