### ISSUE TITLE
[Mago Frost] Dedos de escarcha

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2237]
Buenas noches.

He esperado unos días tras ver que este talento (y efecto) ha aparecido en el changelog como reparado.

De todas maneras comentaré el problema de nuevo, https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1616 sigue con los mismos problemas detallados en el reporte.

Si fuera un fix que estuviera por implementar a la espera de un reinicio del servidor, por favor cerradme este reporte.

Gracias

**Comment by ghost** [comment]
Quizás no hayan compilado, aunque ya hace días que se agregó al changelog..Puede que no se haya solucionado o se haya quedado atrás como lo de aullido perforador. https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1996

**Comment by ghost** [comment]
Esto sigue sin funcionar. En los combates suena como si saltase el bufo, pero no se activa, es sólo el sonido.

Congelación profunda no está consumiendo la carga de Dedos de escarcha que debería.

**Comment by Santateresa** [comment]
He estado probando el hechizo (18/10/2013) y aun no esta fixeado ni mucho menos, dedos de escarcha hace que lanza de hielo y congelación profunda actúen como si el objetivo estuviese congelado, lo que para congelacion profunda significa que gastaría una carga en el stun, lo cual está funcionando correctamente, el problema viene con el daño de lanza de hielo, el cual es el hechizo clave en el daño del mago frost, los dedos de escarcha se supone que al gastar cada una de las cargas con lanza el objetivo debería recibir daño no solo como si estuviese congelado, si no a demás un 25% mas por el bufo que le da de daño a lanza de hielo el tener dedos de escarcha, bueno pues no solo no ganas la bonificación del 25% de daño, si no que a demás lanza de hielo hace el mismo daño que si el objetivo estuviese sin congelar, es decir tenerlos y no tenerlos es lo mismo vas a hacer el daño base con lanza de hielo y la diferencia es bestial, con 7581 de poder con hechizos hago 4300 de daño medio con lanza de hielo a objetivos sin temple, con el objetivo congelado el daño aumenta a 11000, con dedos de escarcha debería ser estos 11000 de estar congelado más el 25% del bufo de los dedos de escarcha, el resultado... 4300 puntos de daño exactamente igual que si el objetivo estuviese sin congelar. Más importante aun, el talento congelar mejorado da al hechizo congelar del elemental el 100% de probabilidad de otorgarte 2 cargas de dedos de escarcha, lo que traducido en 2 lanzas de hielo sería un daño igual a dos veces 11000+25% de media sin critico, pero... sorpresa la mía cuando resulta que la primera carga de dedos de escarcha gastada con lanza no solo no hace el daño que debería si no que...NI SIQUIERA HACE DAÑO!!! y la segunda lanza hace los 4300 de daño como si la tirases sin mas, es decir el mago frost está perdiendo como poco 22000 de daño cada 15 segundos eso sin contar que la mayoría de los impactos con congalación son criticos ni el 25% mas del bufo lo que daría una barbaridad de daño, por favor arreglen esto de verdad, se que es difícil pero sin ello los magos frost estamos vendidos en cuanto a dps y en pvp contra otras clases se nota muchísimo este daño extra que a demás es sin castear lo que da muchisima ventaja.
Muchas gracias por la atención y mucha suerte con ello, un saludo.

**Comment by ghost** [comment]
Pues a mi congelación profunda no me consume la carga de dedos de escarcha que gano al congelar con el elemental.

La verdad que un mago frost sin dedos de escarcha..es como poner a un guerrero a atacar con arco xD

**Comment by Santateresa** [comment]
Por dios no den por fix dedos de escarcha lleva meses igual y no es posible hacer un daño competente sin esa habilidad, dejo un vídeo d como deberían funcionar en el wow oficial y del daño que debería hacer el combo congelar con el elemental mientras castea descarga de escarcha + lanza de hielo aprovechando las 2 cargas de dedos de escarcha que te otorga la habilidad de congelar del elemental, en el oficial pasa esto...http://www.youtube.com/watch?v=kHDHFgEEoMc
(minuto 3:00)
En reign of darkness pasa que lanzas la descarga de escarcha y si esa hace daño, pero la lanza de hielo hace cero! directamente es como si no la tirases no sale ni daño al lanzarla lo único que haces es el idiota al ganarte 1.5 segundos de cd interno por haberla tirado pero el enemigo recibe cero de daño, a demás descarga de escarcha te consume una carga de los dedos de escarcha lo cual no debería pasar impidiendo que ataques con otra lanza de hielo que se beneficiaría del bonus de la segunda carga de dedos de escarcha, para dar datos, en el oficial en muñecos un pj con equipo del parche 4.0.6 está haciendo 31494 de daño critico al muñeco con descarga de escarcha, mas 23693 de lanza de hielo en el primer casteo gastando una carga de dedos de escarcha de las 2 que le da el elemental, y 31456 de descarga de escarcha mas 23401 de daño de la lanza y acaba con otra lanza de 23385 porque tenía otra carga mas de dedos de escarcha que le ha saltado, pero eso ya es aleatorio y depende de si te sale la carga o no, a lo que voy es que en 11 segundos ha hecho 133429 puntos de daño.
¿Cuanto daño hace un mago frost con la misma combinación de ataques en reign of darkness? les invito a probarlo, yo lo he hecho y aquí están mis resultados en el mejor de los casos, hay que decir a demás, que estamos en un parche superior al vídeo y que mi mago tiene más equipo que el del video del oficial, es decir en principio debería hacer más daño el mío, bien pues en el mejor de los casos mi daño es de... descarga de escarcha 32952 (bien de daño pero me resta una carga de dedos de escarcha que no debería restar) + 0 lanza de hielo (ni siquiera aparece cifra, como si no hubiese tirado nada, eso si el cd interno por tirarla me lo llevo y la carga de dedos de escarcha la consume, es decir me ha valido para perder un segundo y medio sin poder hacer ninguna habilidad, hacer cero de daño, el recount ni cuenta como que haya sido lanzada y encima me resta una carga de dedos, ¿que tipo de ventaja tiene lanza de hielo?) siguiente descarga de escarcha hace 33242 de daño y lanza de hielo 4610 es decir, el mismo daño que si no tuviese dedos de escarcha porque claro no los tengo se los ha comido la descarga de escarcha el primero (que no debería quitarlo) y la lanza el segundo (encima para ni tan siquiera hacer daño) con lo cual haciendo el recuento y suponiendo que las 2 lanzas de hielo finales son criticas nos quedamos conque he hecho...84634 puntos de daño suponiendo que me ha salido todo crítico lo cual es harto difícil ya que sin dedos de escarcha lanza de hielo no actúa como si el objetivo estuviese congelado y no gana el bono de crítico de trizar, es decir que lo normal es hacer incluso mucho menos daño.
Por favor, tienen una clase que hace la mitad de daño que debería, intenten fixear al menos dedos de escarcha, gracias de antemano y mucha suerte con los fixeos que entiendo que es difícil.

**Comment by Santateresa** [comment]
Eso sin hablar de si veis el vídeo completo.... el daño que hace el orbe de pirofrío y el comportamiento que tiene, las veces que le salta dedos de escarcha sin que sea por el congelar del elemental, digamos que entre todo un mago frost en el wow oficial estaría haciendo el triple de daño usando todos los cds de los que dispone que un mago frost en nuestro servidor, mientras otras clases hacen daños bastante superiores al que deben, por favor arreglen poco a poco el mago frost porque no se puede jugar con el, al menos los dedos de escarcha, el resto de spells que van mal en el frost son útiles pero no vitales como esta.

**Comment by paellaencol** [comment]
Me olvidé comentar que las cargas de<b>"dedos de escarcha"</b> sólo se deberían consumir con <b>"lanza de hielo"</b> o con <b>"congelación profunda"</b>.
<b>Ninguna otra habilidad</b> usada debería poder consumirlas, ni verse afectáda por ellas (en la actualidad <b>"Descarga de escarcha"</b> las está consumiendo)

**Comment by ghost** [comment]
? que descarga de escarcha no consume dedos de escarcha? como que no? :C ya no se puede hacer shatter combo sólo con dedos de escarcha sin que tu objetivo esté realmente congelado? Parece que me he quedado anticuado con el frost T_T

**Comment by paellaencol** [comment]
http://wow.freakz.ro/spells.php?spell=83074
y buffo: http://wow.freakz.ro/spells.php?spell=44544

**Comment by Santateresa** [comment]
no consume carga la descarga de escarcha asman, pero en realidad da igual porque ahora el daño lo hace lanza de hielo, entonces si descarga también se aprovecha de ello sería demasiado daño, pero se pueden hacer combos en plan congelar con el elemental y castear descarga de escarcha mas lanza con lo que descarga aprovecha la congelación para el trizar y la lanza se lleva el dedo de escarcha, el resultado es un palo bastante notable como se ve en el video.
