### ISSUE TITLE
(Cazador Bestia) Disparo de cobra

### ISSUE THREAD

**Issue by patriccio** [RoDNet/Bugtracker-Infinium-4.3.4#2239]
hola a los gm.
Disparo de cobra: http://es.wowhead.com/spell=77767
Discripcion: Inflige un 77% de daño con arma en forma de daño de Naturaleza y aumenta la duración de tu Picadura de serpiente sobre el objetivo 6 s. Genera 14 p. de enfoque.

Se puede utilizar en movimiento.
Probrema: lo que sucede solo en la rama bestia ya que en supervivencia y punteria funciona , es que cuando uno castea disparo de cobra la mayoria de las veces aparece como interumpido cosa que es raro ya que uno no lo lanza en movimiento sucede en pve que uno esta totalmente estatico, para que decir en pvp.

**Comment by searum** [comment]
Esto es problema de algun talento, hazme el favor de borrarte talentos e ir probando poniendo 1 a 1 hasta que se interrumpa. Prueba varias veces con 1 mismo talento y vas poniendo otros talentos si no se interrumpe ^^

Cuando lo tengas me lo posteas y lo arreglo rapido

**Comment by Wiinter** [comment]
No será por el problema este #2348 ?
