### ISSUE TITLE
Subastador Fitch

### ISSUE THREAD

**Issue by shials** [RoDNet/Bugtracker-Infinium-4.3.4#224]
http://es.wowhead.com/npc=8719/subastador-fitch
No deja abrir la subasta.
![wowscrnshot_070613_214527](https://f.cloud.github.com/assets/4938203/757176/3aabf278-e675-11e2-8de3-43b51cb6b67f.jpg)

**Comment by Navalagamella** [comment]
Pasa lo mismo con un subastador en la horda. Serán... ¿hermanos? http://es.wowhead.com/npc=44866

**Comment by crowel** [comment]
Este npc al igual que el de la horda dan misiones, solo necesita traducción su misión por lo demas se puede cerrar el issue.
Un saludo.

**Comment by redneo** [comment]
fixed
