### ISSUE TITLE
cabalgar vashj'ir

### ISSUE THREAD

**Issue by melcalla** [RoDNet/Bugtracker-Infinium-4.3.4#2241]
http://es.wowhead.com/npc=41248#starts

la misión para coger el caballito de mar y hacer accesible la parte de vashj'ir no esta y es una parte muy bonita para levear y para hacer reputacion en anillo de la tierra.

y completamente inacesible sin la montura,

porcierto el portal tampoco funciona,

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
