### ISSUE TITLE
[Mision-Infralar] Reactiva los ensamblajes

### ISSUE THREAD

**Issue by c0iba** [RoDNet/Bugtracker-Infinium-4.3.4#2242]
Nombre: Reactiva los ensamblajes
Enlace: http://es.wowhead.com/quest=26762
Descripción: Reactiva 5 ensamblajes de guerra desactivados. 
Problema: los NPCs " Mistico rocaguja" ( http://es.wowhead.com/npc=43995 ) aparecen muertos pero con vida, osea, que estan muertos pero les puedes pegar. se supone que matandolos liveran al "ensamblaje de guerra desactivado" ( http://es.wowhead.com/npc=43984 ) pero no ocurre nada porque aparentemente nacen muertos

**Comment by redneo** [comment]
Arreglada - Duplicado
