### ISSUE TITLE
Cuando la ciencia ataca, Azshara

### ISSUE THREAD

**Issue by daviloko** [RoDNet/Bugtracker-Infinium-4.3.4#2244]
http://es.wowhead.com/quest=14308 no funciona el item de apagar el fuego.

**Comment by Wiinter** [comment]
Sigue las pautas de posteo del foro, sino te van a cerrar el issue

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
