### ISSUE TITLE
[Mazmorra] Foso de Saron

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2245]
No puedes entrar por la entrada de Foso de Saron de las Cámaras Heladas (Donde esta la piedra de invocación y la entrada a las otras 2 mazmorras). En cambio, si puedes entrar desde forja.

Te debería dejar entrar si tienes los logros de Forja de matar a los bosses, sino no. En mi caso, los tengo pero no me deja entar.

Enlace de los logros: 
Para entrar en normal:http://es.wowhead.com/achievement=4516
Para entrar en heroico: http://es.wowhead.com/achievement=4519

**Comment by efectokoleos** [comment]
si el problema de k no te deja entrar pro la puerta normal no sabemos k coño le pasa xd

**Comment by Wiinter** [comment]
Jajajajajajajajajajajajaja, pero es cosa mía o le pasa a más gente?. Una cosa no puedes poner el portal que hay en forja de almas qe te lleva a foso? Ese funciona de coña xD

**Comment by efectokoleos** [comment]
a todos ni con gm on ni nada xd si fuera el portal no habria problema pero es un areatrigger k parece estar bien pero no se k falla xD

**Comment by Kiritoo** [comment]
A mi me deja entrar perfectamente, cualquier cosa abrir de nuevo un reporte.
