### ISSUE TITLE
[Guerrero] Golpe Heroico

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#2246]
Nombre: Golpe Heroico (Heroic Strike)
ID: http://cata.openwow.com/spell=78
Descripcion: Un ataque que inflige al instante X p. de daño físico. Un buen ataque para momentos de ira sobrante.
Fallo: aparte del daño subido puesto ya en otro issue (unos 800 de daño más o menos)
está ignorando todo tipo de reducciones de daño, por ejemplo con el boss Ícoron de El Bastión Violeta (http://es.wowhead.com/npc=29313) tiene una habilidad que reduce un 99% el daño recibido.
Funciona bien le hago 100 crítico, pero al usar golpe heroico no se ve reducido por el efecto, le sigue haciendo 7k sin crítico.

**Comment by nicerdicer** [comment]
A ver si el problema va a ser en la propia reducción de daño del boss, es mas provable que el problema sea ese que el hecho de una una habilidad ingnore una defensa solo parcialmente... seria cosa de probarlo con otros PJs

**Comment by elmiriox15** [comment]
No, ya lo he probado con otras cosas tipo Dispersión del Sacerdote Sombras y no me reduce el daño de Golpe Heroico, lo único que lo está reduciendo es el Temple.

**Comment by efectokoleos** [comment]
estamos preparando un emulador totalmente nuevo, en el que varios errores quedarán arreglado, incluyendo este, voy a ir cerrando los reportes que funcionen en el nuevo emu, ya que no vamos a dar mas soporte al actual, porque esta lleno errores internos al ser tan viejo y al haber estado tan toqueteado por distinta gente que despues ha dejao todo el codigo ahi causando errores sin parar xd
