### ISSUE TITLE
Misión Bug: ''Por un puñado de esquirlas''

### ISSUE THREAD

**Issue by lucasnates** [RoDNet/Bugtracker-Infinium-4.3.4#2247]
Hola soy Razzers, Paladín y tengo el siguiente problema:
En la Isla de Caminante del Sol (donde nacemos los elfos de sangre) la misión; Por un puñado de esquirlas, esta bug ya que eh matado bastantes vermis de maná y ninguno me ha soltado ninguna esquirla arcana. Espero que les ayude este ticket,
un salu2.

Razzers.

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
