### ISSUE TITLE
Mision bug [Recuperar lo que es nuestro]

### ISSUE THREAD

**Issue by silfo** [RoDNet/Bugtracker-Infinium-4.3.4#2248]
No logro completar la misión http://es.wowhead.com/quest=24646/recuperar-lo-que-es-nuestro cuando toco el cuerno de la mision

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
