### ISSUE TITLE
Cumbres Tormentosas

### ISSUE THREAD

**Issue by hell37** [RoDNet/Bugtracker-Infinium-4.3.4#225]
http://es.wowhead.com/quest=13424 esta misión diaria esta bug, los npc osos del foso no se pueden atacar ademas de que los rinos de cumbres tormentosas aparecen muertos moviendose 
![wowscrnshot_070613_155855](https://f.cloud.github.com/assets/4789611/757256/ad6e9996-e67f-11e2-9caa-57af2afe9ea7.jpg)

**Comment by Kiritoo** [comment]
Fix tanto la quest como los osos rhinos que estaban muertos.
