### ISSUE TITLE
[Misión] Donde hay patrón...

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2250]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/670

No funciona.

Edito: Extraño...al dejar las dos misiones me apareció el marco de la pet. No sé si fue al dejar las misiones o al salir de Zul'drak

**Comment by redneo** [comment]
si que funciona... tienes que buscar bien los fragmentos.

**Comment by ghost** [comment]
el problema no son los fragmentos, sino la pet que no sale la barra de acciones ni el esbirro.
