### ISSUE TITLE
Mascota de Cazador (Colmillo de Jade) 

### ISSUE THREAD

**Issue by patriccio** [RoDNet/Bugtracker-Infinium-4.3.4#2251]
hola, a los gm,
Colmillo de Jade. http://es.wowhead.com/npc=49822
ubicacion: Profundidades Desmoronadas (Infralar)
bug: hace meses que no aparece en su lugar , que muestra el wowhead. colocaron que lo habian fixeado pero sigue sin aparecer

**Comment by Kiritoo** [comment]
Hola coloque se fixeara pero que faltaba aplicarlo
