### ISSUE TITLE
[Misión] Joven y salvaje

### ISSUE THREAD

**Issue by alexmilion** [RoDNet/Bugtracker-Infinium-4.3.4#2254]
La misión consiste en atrapar a Garrapresta con el Lazo garrasangre, pero este objeto no tiene efecto alguno al utilizarlo cuando estas cerca del objetivo.

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
