### ISSUE TITLE
Bug al aprender la especialización ingeniería gnomica.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#2255]
Al aprender la ingeniería gnomica (spell=20220) se ocasiona un bug en el libro de hechizos que no permite elegir ninguna otra profesion ni deja olvidar la especialización,aquí esta el ejemplo visual de dicho bug

Asi le aparece a algunas personas:
http://www.subirimagenes.com/otros-wowscrnshot091113143-8615115.html

A mi después de que me ayudo hace mucho tiempo la mj Anha,ella me la borro completa la ingeniería que tenia en 525 pero después de borrarme la profesión y la especialización,curiosamente me sale esto,me dijo que esperara pero han pasado 3 semanas y sigo sin profesión
http://www.subirimagenes.com/otros-wowscrnshot100513175-8646085.html

Gracias por su atención.

**Comment by Creamfour** [comment]
yo tengo el mismo problema que tienes en la primera imagen, así que si alguien puede echar una mano lo agradecería!

**Comment by kingtonix** [comment]
Pues nos toca esperar Cream o como dicen los MJ's "Tener paciencia" porque yo tengo 1 mes ya y sigo esperando alegremente (Sarcasmo en el alegremente).

**Comment by redneo** [comment]
Si no hubierais pillado la mision de la otra especializacion... arreglado

**Comment by Creamfour** [comment]
¿Perdona?
