### ISSUE TITLE
Bug Worgen

### ISSUE THREAD

**Issue by carlos1515** [RoDNet/Bugtracker-Infinium-4.3.4#2256]
Estaba jugando con un pj worgen cuando recien llegado a ventormenta llego a villa dorada y no hay nadie... porfa necesito saber porque ocurre eso

![captura de pantalla 2013-10-05 a la s 17 40 22](https://f.cloud.github.com/assets/5619961/1275831/ed83d288-2e11-11e3-8488-22a870320c23.png)
![captura de pantalla 2013-10-05 a la s 17 59 09](https://f.cloud.github.com/assets/5619961/1275832/ed84d4da-2e11-11e3-93b3-510cae5fd0fb.png)

**Comment by searum** [comment]
pon un ticket ingame y di que te hagan un .unaura all xD
