### ISSUE TITLE
Llamada del maestro

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#2257]
Llamada del maestro no está funcionando como debería. Si bien libera de los enraizamientos de druidas, picaros, dk y otros; contra aquellos del mago no lo hace (no hablo de la congelación del mago, sino de sus enraizamientos como Nova escarcha).

Por no se puede estar lejos del mago, y magovscaza, está muy desequilibrado.

Am, no se como iría una prueba de foto en eso así que no la puse

**Comment by elmiriox15** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
