### ISSUE TITLE
[Misión - Uldum] En el buen camino 27196

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2260]
http://es.wowhead.com/quest=27196/en-el-buen-camino

Descripción: Acompaña a Harrison Jones a la Cámara de las Estrellas.

Problema: el NPC ni se mueve.

**Comment by redneo** [comment]
pero hablas con el que está abajo y cuenta, creo yo

**Comment by ghost** [comment]
Con cuál? está el NPC que da la misión y nada, al lado hay 2 robots y no pasa nada al hacerles click tampoco.

Edito: Vale sí, si entras en la cámara y hablas con el tío y le das a la misión puedes entregarla, al igual que la siguiente. La de "Prepárate" ya no se autocompleta y hay que matar unos esqueletos que al parecer están bug y solo aparecen cuando estás muy cerca...

Es un poco incordio, ya que ninguna de las misiones te marca dónde se hacen.

**Comment by redneo** [comment]
Los esqueletos aparecen al acercarte a los esqueletos que hay tirados. Cierro ticket
