### ISSUE TITLE
[Hechizo-Cazador]Llamada del maestro

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#2262]
Nombre: Llamada del maestro
Enlace: http://es.wowhead.com/spell=53271/llamada-de-maestro
Descripción: Tu mascota intenta eliminar todos los efectos de reducción de movimiento y de raíces sobre sí misma y su objetivo y provoca que ambos se vuelvan inmunes a tales efectos durante 4 s.
Problema:  La habilidad no está funcionando con los enraizamientos del mago (al menos con ellos lo he visto). Hablo de habilidades como nova de escarcha, no la Congelación profunda que es un stun y ese claramente no se debe de poder quitar más que con tricket.
Observaciones: Con otros hechizos y dibuff de alentamiento si funciona, como el caso de la enfermedad de escarcha del DK, cosas del picaro y druida, etc. Es con los hechizos del mago que no libera.

**Comment by Jhovanni** [comment]
Observaciòn 2: Para aclarar un poco mejor la explicación. De igual manera, al estar con el bufo de Llamada del maestro, un mago puede enraizar al cazador como si no tuviese esa inmunidad encima. Tambien me han dicho que sucede lo mismo con el Seccionar del guerrero, aunque no he tenido oportunidad de probarlo directamente con ellos, pues es con el mago con el cual sucede más a menudo (pues tienen más enraizamientos y más seguidos).

**Comment by Jhovanni** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3538

**Comment by Kiritoo** [comment]
Arreglado.
