### ISSUE TITLE
[Talento-Cazador]Instrucción de francotirador

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#2263]
Nombre: Instrucción de francotirador
Enlace: http://es.wowhead.com/spell=53302/instruccion-de-francotirador
Descripción: Aumenta un 5% la probabilidad de golpe crítico de tu facultad Disparo mortal y tras permanecer quieto durante 6 s, tu Disparo firme y Disparo de cobra infligen un 2% más de daño durante 15 s.
Problema:  El buff no se activa, nunca

**Comment by Jhovanni** [comment]
El talento no sirve en absoluto, no se activa el bufo de daño adicional, ni tampoco aumenta el porcentaje de crítico de disparo mortal (esa parte cuestra probarla pues no se puede ante el muñeco, pero se puede hacer matando muchos mobs)

**Comment by searum** [comment]
pues a mi me funciona
