### ISSUE TITLE
[Hechizo-Bestia espíritu-Cazador]Aliviar espíritu

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#2264]
Nombre: Aliviar espíritu
Enlace: http://es.wowhead.com/spell=90361/aliviar-espiritu
Descripción: La bestia espíritu sana al objetivo amistoso actual [1371 + ((Ranged attack power \* 0.35) \* 0.5)] p. más [527 + ((Ranged attack power \* 0.35) \* 0.335)] p. extra durante 10 s.
Problema:  La sanación es demasiado baja, demasiado. Todo depende del equipo claro. Para dar una idea, la sanación total con un equipo medio (digamos partes de sañoso con sanguinario), ronda en los 20-23k en total: un primer tick de 5-6k y otros de 2-3k. Mientras ahora la sanación total no pasa de 3k: primer tick de 1.8k y los restantes de 475 más o menos.

**Comment by paellaencol** [comment]
Cuidado que esa fórmula es del MoP, y cambiaron los porcentajes a casi todas por no decir todas las sanaciones y ataques.

**Comment by ghost** [comment]
Fórmula cata 4.3.4: 1237 + ((RAP \* 0.35) \* 0.5) más 475 + ((RAP \* 0.35) \* 0.335) durante 10 segundos.

http://wow.freakz.ro/spells.php?spell=90361

De ahí que los restantes sean exactamente de 475, es porque no está teniendo en cuenta el resto de la fórmula.

**Comment by Kiritoo** [comment]
Fix
