### ISSUE TITLE
[Hechizos/Talentos][Ciudadela de la Corona de Hielo] Fuerza de Wrynn

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2265]
Buenas.
• Nombre: Fuerza de Wrynn
• Enlace: http://es.wowhead.com/spell=73828
• Descripción: El Rey de Ventormenta te presta su fuerza y aumenta la salud total, la sanación realizada, la absorción de daño y el daño infligido un 30%.
• Problema: El Buff no afecta Worgens.
Gracias!!

**Comment by efectokoleos** [comment]
el buf si mal no recuerdo lo quitaron en la 4.0.1

**Comment by ghost** [comment]
Ni idea :(
Hay un comentario en inglés hecho durante el Pandarian diciendo que se puede poner o quitar hablando con el rey Varian: http://www.wowhead.com/spell=73828#comments:id=1780208

**Comment by Kiritoo** [comment]
Esto funciona correctamente en ambos bandos.
