### ISSUE TITLE
[Mazmorra] Minas de la muerte (Normal)

### ISSUE THREAD

**Issue by Albertiktik** [RoDNet/Bugtracker-Infinium-4.3.4#2266]
Estoy intentando hacer los logros de las mazmorras y me he ido a Minas de la muerte en su version normal y despues de matar al primer boss de esta mazmorra Glubtok (http://www.wowhead.com/npc=47162) no se abren las puertas detras que tiene detras y no me deja continuar.

**Comment by Kiritoo** [comment]
Acabo de probarlo y funciona perfectamente, le das a la palanca y se abre la puerta.
