### ISSUE TITLE
Cadena de Misiones de los huargen  El Roble Quejumbroso

### ISSUE THREAD

**Issue by orcco** [RoDNet/Bugtracker-Infinium-4.3.4#2267]
El npc no se encuentra donde indica, no puedes terminar la cadena y volver a ser humano y transformarte cuando quieras.

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
