### ISSUE TITLE
Hechizo [Caballero de la muerte] - Explosion ahullante

### ISSUE THREAD

**Issue by Lorkien** [RoDNet/Bugtracker-Infinium-4.3.4#2268]
Nombre - Explosion ahullante

Link - http://es.wowhead.com/spell=49184/explosion-aullante

Descripcion - Golpe al enemigo con un viento helado, lo que inflige 6281p. de daño de Escarcha a ese enemigo y 3140 p. de daño de Escarcha al resto de enemigos en un radio de 10m.

Problema: El daño de este hechizo es muy reducido de 2160 o un poco mas con cds a  los npc ademas inflige el mismo daño a todos los enemigos en un radio de 10 metros incluido atu objetivo.

Observaciones: Comparandolos con la descripcion del hechizo en el juego el daño es muy inferior.

**Comment by Lorkien** [comment]
Aqui una captura de pantalla del daño en el registro de combate.
- http://imageshack.us/photo/my-images/59/oqvh.jpg/

**Comment by ghost** [comment]
Fórmulas:
((1322 + 214) / 2) + (AP \* 0.44)p. de daño escarcha al objetivo y (0.5 \* (((1322 + 214) / 2) + (AP \* 0.44))) p. de daño escarcha a todos los demás enemigos en 10 yardas.

http://wow.freakz.ro/spells.php?spell=49184

**Comment by ghost** [comment]
Ya estaba reportado: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2045
