### ISSUE TITLE
[hechizo-druida] rugido salbaje 52610

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#2269]
Nombre: rugido salvaje
Enlace: http://es.wowhead.com/spell=52610/rugido-salvaje
Descripcion: remate que consume los puntos de combo en cualquier objetivo cercano para aumentar un 80% el daño infligido con ataques automaticos,solo se puede itilizar en forma felina.
Se prolonga por cada punto de combo:
1p-22s
2p-27s
3p-32s
4p37s
5p-42s
Problema: esta aumentado 80% todo el daño ,cuando solo deveria aumentar el 80% de los golpes blancos o automaticos

**Comment by ghost** [comment]
http://wow.freakz.ro/spells.php?spell=52610

**Comment by ghost** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2113
