### ISSUE TITLE
[hechizo-picaro] preparacion 14185

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#2270]
Nombre: Preparacion
Enlace: http://es.wowhead.com/spell=14185
Descipcion: Cuando se activa, esta facultad elimina inmediatamente el tiempo de reutilizacion de tus facultades sprint, esfumarse  y paso de las sombras.
Problema: funcina bien salvo que , resetea tambien evasion 5277 enlace: http://es.wowhead.com/spell=5277

**Comment by Creamfour** [comment]
Ya está bien que reinicie evasión, lee:

Preparación
Instante    5 min de reutilización
Requiere Pícaro
Requiere nivel 68
Cuando se activa, esta facultad elimina inmediatamente el tiempo de reutilización de tus facultades Sprint, Esfumarse, Evasión y Desguarnecer (con glifo). 

 El que resetee evasión no es bug, simplemente funciona así y de hecho, hay macros para tirarse evasión y sprint antes de usar preparación para no derrochar los CDs.

**Comment by 50megas** [comment]
evasion no aparece en la descricion del hechizo, ni del glifo.

descripicion preparacion en el juego:
Cuando se activa, esta facultad elimina inmediatamente el tiempo de reutilizacion de tus facultades sprint, esfumarse y paso de las sombras.

descripcion de glifo en el juego:
tu facultad preparacion tambien reinicia istantaneamente el tiempo de reutilizacion de pata, desguarnecer y bomba de humo

creo que sale evasion en el enlace ,por que wowhead esta en el parche 5. mirare si encuentro un enlace de la 4.3.5

havilidad: http://wow.freakz.ro/spells.php?spell=14185

**Comment by Creamfour** [comment]
Si entras en cualquier servidor de la 3.3.5a, verás que preparación también reinicia evasión, el que en Cataclysm hayan implementado el hechizo reponerse, no quiere decir que vayan a quitar la evasión reseteada por preparación...

**Comment by 50megas** [comment]
notas del parche 4.0.6 : http://us.battle.net/wow/es/game/patch-notes/4-0-6

dice: Preparación ya no reinicia el tiempo de reutilización de Evasión.

**Comment by 50megas** [comment]
parece que funciona bien ya
