### ISSUE TITLE
[Control de masas] 

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2273]
Had.

**Comment by paellaencol** [comment]
Seguro? mira que lo he probado y nada, lo que si he visto son lagazos que hace que un jugador se teletransporte 20 metros, pero nada más

**Comment by ghost** [comment]
Sí, seguro.

**Comment by Lorkien** [comment]
asman yo lo que e visto es atravesar texturas con grito desmoralizador del war en concreto bajar un war del cementerio horda de warsong lanzar grito desmoralizador y salir corriendo atravesar las texturas y acabar arriba del cementerio horda.

**Comment by ghost** [comment]
R
