### ISSUE TITLE
[talento-picaro] golpes despiadados 58423

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#2275]
Nombre: golpes despiadados 
Enlace: http://es.wowhead.com/spell=58423
Descripcion: tus remates tienen un 20% de probabilidades por cada punto de combo de restaurar 25p. de energia
Problema: esta funcionado, pero algunos remates dan 25 otros 50 y otros nada,

remates que funcional mal:
- ruptura 1943 :  esta dando 0p. de enegia, deveria dar 25p. 
- golpe en los riñones 408 : esta dando 2x25p. de energia, deverian ser 25p.

remates que funcionan bien:
- hacer picadillo 5171 : esta dando los 25p. este va bien
- exponer armadura 8647 : esta dando los 25p. esta bien
- envenenar 32645 : esta dando los 25p. esta bien
- lanzamiento mortal 26679 : esta dando los 25p. esta bien

**Comment by searum** [comment]
fix
