### ISSUE TITLE
[Misión Sacer] Bosque Canción Eterna - Sanar a los heridos.

### ISSUE THREAD

**Issue by Neyza** [RoDNet/Bugtracker-Infinium-4.3.4#2276]
Descripción: "Aprende Sanación Relámpago y practica sanando a 5 avanzados heridos"

Problema: Los avanzados heridos están completamente sanos, no hace falta reanimarlos, así que cuando les lanzo sanación relámpago no cuentan en la misión.

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
