### ISSUE TITLE
[Banda] Naxxramas

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2277]
http://es.wowhead.com/zone=3456

Vas matando los bosses de los diversos arrabales pillas los portales de teleport y te llevan al principio. En esto consiste la primera parte de Naxxramas y despues al acabar vas a Sapphiron y Kel'Thuzad aunque no es necesario primero acabar los arrabales para matar a Sapphiron y Kel'Thuzad.

Los arrabales Militar, Arácnido y de la Plaga funcionan bien, pero el de los Ensamblajes tiene un gran problema que jode la raid entera. El único problema es Gluth (http://es.wowhead.com/npc=15932). Empieza el evento, saca zombies etc... lo matas, da el loot pero no termina el evento.
 Por consiguiente las puertas no se abren. Si sales de la raid por cualquier cosa, no puedes volver a entrar porque te dice qe está sucediendo un encuentro, no puedes invitar a más gente y si alguien se ha caido y aparece en el cementerio se tiene qe fastidiar.

Kel'Thuzad(http://es.wowhead.com/npc=15990) el único problema que tiene es qe no empieza el evento.

**Comment by efectokoleos** [comment]
el gluth arreglado

**Comment by feniix97** [comment]
Kel' thuzad funciona perfectamente solo tenes q esperar 5 minutos limpiando su cámaras de los esbirros no muertos q la rodean y luego el atacara perfectamente, ya  la hice antes como en otras ocasiones y funciona perfectamente.

**Comment by Wiinter** [comment]
Pues cuando fuimos nosotros, no estaban los no muertos que dices, por eso lo postee. Hay 10 personas testigos de esto. Pueden ser que lo hayan arreglado y no lo han dicho :)
Gracias por el aporte

**Comment by Kiritoo** [comment]
Esto funciona correctamente.

**Comment by juaks** [comment]
Ayer nos pasó lo mismo, al matar a Gluth es como que no acaba el evento y no se abre la puerta para Thaddius (http://es.wowhead.com/npc=15928)
