### ISSUE TITLE
[Talento-Cazador]Toxicología

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#2278]
Nombre: Instrucción de francotirador
Enlace: http://es.wowhead.com/spell=82833/toxicologia
Descripción: Aumenta el daño crítico periódico de Picadura de serpiente y Flecha negra un 100%.
Problema: No funciona literalmente. Al tener esos talentos el daño crítico de picadura de serpiente y flecha negra debe de ser 300%, pero sigue estando en 200%, como si no se tuviesen esos talentos.

**Comment by paellaencol** [comment]
No se si estaré en lo cierto, pero hay más clases que tienen un talento parecido con su misma utilidad (especialmente daño mágico). De normal el multiplicador por crítico del daño mágico es de un 150%, este tipo de talentos lo que hacen es convertir ese multiplicador en 200%.

No tengo un cazador para probarlo, pero intenta ir en supervivencia sin esos talentos y mira si el multiplicador por crítico es de 150%, o de 200% ya de base. Si el multiplicador sin talentos es del 150%, es que funciona bien

**Comment by Jhovanni** [comment]
Bueno, para aclarar.
Cuando un golpe es crítico, el daño total es 200%, es decir: el doble del daño de un golpe normal.
El talento Toxicología aumenta 100% el daño periódico de los críticos de picadura de serpiente y flecha negra; por lo tanto:
100% de daño base + 100% golpe crítico + 100% bono Toxicología = 300% de daño.
Eso es lo que debería ser, pero el talento no funciona.

El multiplicador de daño crítico no es 150%, con revisar tus golpes en combate te darás cuenta, o igual al ver las mecánicas de evaluación de daño de diseño de juego en la página de BlattleNet.
Aclaro para que no sea cerrado el reporte. Gracias, igual ayuda para dejar mejor aclaradas las cosas.

**Comment by paellaencol** [comment]
El daño mágico (no físico) tiene un multiplicador de base por crítico del 150%. Sin embargo siempre suele haber un talento, o un pasivo, o un pasivo por especialización en rama de talentos, que hace que ese multiplicador por crítico se eleve del 150% al 200%.

Por ejemplo, el DK tiene un pasivo que hace que el daño mágico crítico inflinja un 200%, el sacerdote tiene un talento que hace que el daño de sombras crítico haga un 200% (sin ese talento, o usando ataques de la rama sagrada, los críticos tienen solo el valor de 150%).

Por eso te digo, porque no tengo un cazador, que la mejor manera de probar si funciona esto, es que veas in situ el coeficiente de multiplicador de daño crítico sin ese talento, y luego viendo qué multiplicador de crítico tienen esos ataques con ese talento. Si sigue siendo el mismo, es que en efecto ese talento no funciona.

**Comment by Jhovanni** [comment]
Ok, me ha puesto a investigar tu respuesta.
En inicio de Wow, las clases de daño físico (en aquél entonces si había mucha diferencia de quienes hacían físico y quien no), el daño en críticos era 200% del daño base, mientras que el daño elemental era 150%.
Con el tiempo fueron eliminando tales situaciones, dejando que sean los chamanes mejora, lo pícaros y los sanadores quienes obtenga 150% de crítico; mientras ya no sucede así con otras clases.

Probando el disparo explosivo, así como disparo de quimera y disparo de cobra; los cuales son los 3 daño elemental. Al suceder un crítico, hacen daño de 200%.
En caso de que el daño crítico de picadura de serpiente sea 150%, entonces igual la habilidad está mal, pues en cualquier rama los daños períodicos críticos están haciendo 200%. Así o: está mal la habilidad porque todas las ramas tienen el beneficio sin usar el talento, o porque el talento simplemente no sirve al usarlo.
En cuanto a experiencia personal, el daño crítico de picadura de serpiente siempre lo he visto en 200%, al igual que con las otras habilidades (no sabía sobre los pícaros,  chamanes y sanadores); incluso cuando jugué en el Oficial. De cualquier manera, de una u otra forma está mal ese talento; y de cualquiera de los dos casos sería bueno arreglarlo. Pues o estamos en ventaja los cazadores, o estamos en desventaja.

**Comment by Jhovanni** [comment]
X cierto, aclaro que las pruebas del disparo explosivo, quimera y cobra las ha hecho contra el muñeco. Al menos las recientes.
Sería bueno aclarar eso: para no jugar a favor ni en contra.

**Comment by searum** [comment]
fix
