### ISSUE TITLE
[Banda] Núcleo de magma

### ISSUE THREAD

**Issue by navolic** [RoDNet/Bugtracker-Infinium-4.3.4#2281]
http://es.wowhead.com/zone=2717

básicamente toda la banda esta perfecta sin ningún problema excepto con el ultimo boss que es el mas importante (Ragnaros) http://es.wowhead.com/npc=11502 y que básicamente lo debería invocar el Mayordomo Executus http://es.wowhead.com/npc=12018 cosa que solo sale hablando pero no aparece Ragnaros y me quedo esperando como 30 min y nada.

y otra cosa que quiero que revisara que es pueda a parecer [Esencia del Señor del Fuego] http://es.wowhead.com/item=19017 un item necesario para una misión importante cosa que seria ridículo que no saliera :B 

y díganme si sirve la misión para crear la sulfuras de Ragnaros esta muy buena esa arma y seria una lastima que no saliera

**Comment by ghost** [comment]
Que raro, yo lo hice el 1° de octubre y funcionaba :S
¿Has hecho los bosses en orden?

**Comment by Monleon** [comment]
Puede invocarse correctamente
