### ISSUE TITLE
[Aullido de Terror] Brujo

### ISSUE THREAD

**Issue by nicerdicer** [RoDNet/Bugtracker-Infinium-4.3.4#2283]
Reporto que [Aullido de Terror]http://wow.freakz.ro/spells.php?spell=5484 Se elimina con el primer tick de cualquier tipo de daño, habitualmente, el daño periodico (Aflicción) no anula el efecto en su totalidad con el daño que inflige, sin embargo, en este caso si lo hace, cuando la duracion debe ser de 5 segundos, esta dura solo 1 apenas limitando los CCs del Brujo.

GRACIAS.

**Comment by ghost** [comment]
Como debe funcionar:
- Se rompe 100% con cualquier daño directo. 
- Probabilidad de romperlo con daño indirecto/DoTs hasta el 10% de la vida total. 
- Se rompe 100% después de pasar el 10% de la vida total.

Vida total= vida del pj antes de ponerse bufos.

**Comment by nicerdicer** [comment]
vamos, que va mal xD por que en 1 segundo no quito un 10% de vida total de un pj con 130K de vida minimo (que viene a ser un full sañoso normal) y a todo esto sumando la reduccion de daño por algunos talentos y temple.

dura vida la del brujo xD

**Comment by ghost** [comment]
Yo lo ponía como dato para el fix. 

De todos modos, no hace falta que le bajes un 10%, con que le lances poseer o una bola de sombras instantánea se rompe, o con que haya un cafre de los típicos por al lado y le pegue.

**Comment by nicerdicer** [comment]
Hombre ya, pero com que no es lo mismo... en un 1v1, o en un entorno mas controlado como una arena pues... parece que no pero va bien para el tema de quitear meles, la verdad se echa de menos que esa facultad funcione bien. Se agradece el dato As.

**Comment by sprin69** [comment]
otra cosa k tmb falla d aulido d terror es k rango k tiene el hechizo es 0m entonces a no ser k esten justo encima tuya y tu sin moverte no les afecta este hechizo.

creo k con el sacer pasa =

**Comment by ghost** [comment]
Sí, está bug eso también, no afecta muchas veces aunque estén muuuy pegados. Creo que es por el rango, sino serán las pendientes o obstáculos del terreno o algo...Va fatal.

**Comment by searum** [comment]
fix
