### ISSUE TITLE
[hechizo-sacerdote] maligno de las sombras 34433

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#2289]
Nombre: maligno de las sombras
Enlace: http://es.wowhead.com/spell=34433
Descripcion: Crea a un maligno de las Sombras que ataca al objetivo. El taumaturgo recibe un 3% de maná cada vez que el maligno de las Sombras ataca.
Problema: esta dando el doble de mana, da el 3% 2 veces por cada golpe
Screenshots:
<a href="http://tinypic.com?ref=2akmy35" target="_blank"><img src="http://i39.tinypic.com/2akmy35.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by Kiritoo** [comment]
Esto está arreglado, cualquier cosa avisar por aquí.
Cierro.
