### ISSUE TITLE
Instructor de paladines en el Campamento Narache (Tauren) no enseña

### ISSUE THREAD

**Issue by QuinoaPaladin** [RoDNet/Bugtracker-Infinium-4.3.4#229]
El instructor da misiones que no se pueden hacer porque no enseña habilidades.

**Comment by frustrix** [comment]
![wowscrnshot_070813_213028](https://f.cloud.github.com/assets/4893907/763810/0136cc0c-e805-11e2-8b82-f99dd8f265e3.jpg)

El Instructor no enseña las facultades las misiones las da y tal pero no te enseña nada

saludos

**Comment by crowel** [comment]
Fix
