### ISSUE TITLE
[talento-sacerdote] extasis 47536

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#2290]
Nombre: extasis
Enlace: http://wow.freakz.ro/spells.php?spell=47537
Descripcion: cuando tu palabra de poder: escudo adsorve el daño maximo o se disipa recuperas al istante un 7% de tu mana maximo. esto solo ocurre una vez cada 12 segundos (7% con los 3 puntos de talentos)
Problema: no respeta el cd de los 12 segundos, devuelve el mana siempre

**Comment by Creamfour** [comment]
Y algo más tiene que haber, porque en este server el maná de los disci es infinito, yo recuerdo cuando jugué este parche en el ofi, el maná del sacer disci duraba, pero tampoco era gran cosa como para estarse con maná full todo el rato vs 2 DPSs.
 Aparte de eso, un disci es para hacer partidas rápidas, y están aguantando como si fueran un boss de mazmorra, casi.

**Comment by 50megas** [comment]
ya si ami me pasa lo mismo en arenas,por eso entre con el sacer para hecharle un vistazo rapido y ya le vi 2 bug y los reporte,haver si mañana lo testeo a fondo

**Comment by Creamfour** [comment]
El caso es que los que juegan disciplina de main, se van a callar los bugs que les están beneficiando y solo reportaran los que les van mal a su contra haha...

**Comment by paellaencol** [comment]
La ID de rango 3 es http://wow.freakz.ro/spells.php?spell=47537

cámbialo si puedes, en el reporte aparece la de rango 2

**Comment by efectokoleos** [comment]
fix
