### ISSUE TITLE
[Misión][Darnassus] Un viejo favorito

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2292]
Buenas.
• Nombre: Un viejo favorito
• Enlace: http://es.wowhead.com/quest=29359
• Descripción: Consigue 8 arenques kaldorei pescando en la Aldea Rut'theran. 
• Problema: No se puede pescar nada en la Aldea Rut'theran ni en los alrededores.
Gracias!

**Comment by Kiritoo** [comment]
Fix
