### ISSUE TITLE
Maestría Sacerdote Disciplina

### ISSUE THREAD

**Issue by kaseO** [RoDNet/Bugtracker-Infinium-4.3.4#2295]
Como pone en el título, el problema es que la maestría no va bien, sólo funciona la maestría base, es decir, 8 puntos de maestria.

Maestría: http://es.wowhead.com/spell=77484 (no sé si es esta exactamente por eso de que el wowhead cambia de parche y tal).

La cosa es que por mucha maestria que lleves, el escudo siempre va a absorver lo que viene de serie con la maestría base de 8 puntos. El disciplina se basa en la absorción de daño y sin su maestría pierde mucho potencial.

Adjunto algunal fotos demostrando que no aumenta la absorción con la maestría.

Foto sin maestria(base de 8 puntos): http://subefotos.com/ver/?7132fe76f7885dfb8f3b77570abbd743o.jpg

Foto con la maestría aumentada: http://subefotos.com/ver/?2da7e7c07b846d559452f3471f7e9309o.jpg
Para los que penseis que con el abalorio o la poción puede variar algo, pongo los links de la poción y el abalorio que utilicé para que se vea que solo dan maestría.
Abalorio: http://es.wowhead.com/item=58183
Poción: http://es.wowhead.com/item=58148

Un saludo.

**Comment by paellaencol** [comment]
En realidad es un bug visual, ni siquiera funciona la maestría base, aunque en las estadísticas te aparezca que la tienes.

De hecho si quieres comprobarlo, cambiate a sombras o sagrado con el talento de escudo mejorado (disciplinas gemelas no, que no funciona) y verás que absorbe el escudo lo mismo, la única variación que verás será en base al poder con hechizos (que en disciplina al tener más intelecto, tienes un poco más), y será mínima.t

Échale un vistazo a esto:
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1727
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2195
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1494

**Comment by lamaza** [comment]
Lo que hay que ver!, quieres absorver entonces 30, 50k? XD

**Comment by Creamfour** [comment]
El disciplina no se basa en la absorción, sino en la celeridad... Por eso de que un disci tiene que ser de combate rápido.

**Comment by kaseO** [comment]
lamaza, quiero absorver lo que tengo k absorver, ni mas ni menos y punto.

**Comment by orcca** [comment]
en heal el mio es de 17k y el de dps es de 16k eso es correcto?..
