### ISSUE TITLE
Bug profesiones

### ISSUE THREAD

**Issue by uralin** [RoDNet/Bugtracker-Infinium-4.3.4#2297]
Bueno pues mi problema es este.

http://imageshack.us/a/img69/8025/hb1o.jpg

Puse ticket me dijeron que lo pusiera aquí,pero vamos yo creo que esto no es un bug general,como puede ser misiones,talentos etc etc.

Como se ve en la imagen solo se me ve bien Alquimia ,las demas profesiones me salen mal.

Gracias y un saludo.

**Comment by ghost** [comment]
No eres el único al que le pasa, ya hay más reportes de esto en el bugtracker porque les dijeron lo mismo, así que supongo que sí que es un bug general al olvidar las profesiones.

**Comment by redneo** [comment]
Vale, desde cuando te pasa eso, que misiones hiciste antes de eso, cuales son tus profesiones principales?

El problema es, creo que hay alguna mision que te da un spell de otra profesion, tengo que averiguar la spell que es y la profesion, logicamente.

**Comment by uralin** [comment]
Pues si quieres que te diga la verdad no se desde cuando me pasa,me di cuenta hoy que quería subir pesca y no podía por que no me sale la habilidad.

Las principales son alquimia y herborista.

**Comment by uralin** [comment]
Ahora que me acuerdo hice las misiones de maestro trasmutación,en frascos y elixeres

**Comment by redneo** [comment]
Es pq tienes las 3 especialidades. A partir de ahora solo se puede coger una, te borro la de frascos y elixires, dejandote solo la de transmutacion.

**Comment by redneo** [comment]
Cierro el bt, quien tenga mas problemas por intentar aprender dobles especializaciones, ponga un bt nuevo.
