### ISSUE TITLE
[Mision] (Infralar) Vendaval violento

### ISSUE THREAD

**Issue by Albertiktik** [RoDNet/Bugtracker-Infinium-4.3.4#2299]
Vendaval violento

http://www.wowhead.com/quest=26426

Encuentra a Felsen el Duradero y sigue sus instrucciones hasta la entrada de las Profundidades Desmoronadas.

-Encuentra a Felsen el Duradero
-Encuentra la entrada a las Profundidades Desmoronadas

Cuando llegas donde esta Felsen (http://www.wowhead.com/npc=42468) no puedes hablar con el ni hace nada cuando lo seleccionas, y al entrar en las profundidades desmoronadas tampoco te cuenta para la mision.

**Comment by redneo** [comment]
duplicado - arreglado
