### ISSUE TITLE
Vuelo en Dalaran

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#23]
Se puede volar libremente en dalaran (no deberia)

![wowscrnshot_070313_183806](https://f.cloud.github.com/assets/4895839/746810/bac877b2-e439-11e2-9561-6adab71d17e1.jpg)

**Comment by redneo** [comment]
Me dicen que tiene que ser asi en el cata... antes era cuando estaba mal...

**Comment by Dekadencee** [comment]
Exacto, en cataclysm se permite utilizar las monturas voladoras, la 406a es la que estaba bug
