### ISSUE TITLE
Mision DK Bug.Imposible seguir leveandolo.

### ISSUE THREAD

**Issue by Kagome** [RoDNet/Bugtracker-Infinium-4.3.4#230]
En esta mision del DK es imposible Seguir.! Dejo unas umagenes para que vean que estan Bugs los cañones. Comprueven si las demás tambien andan bug,por que al no poder proseguir no se como seguirá la cosa.
![wowscrnshot_070713_052002](https://f.cloud.github.com/assets/4942077/757531/0b819008-e6b5-11e2-9a28-63b4e441e4aa.jpg)
![wowscrnshot_070713_052012](https://f.cloud.github.com/assets/4942077/757532/0c0b0b44-e6b5-11e2-9461-fa1337e213fc.jpg)
![wowscrnshot_070713_052027](https://f.cloud.github.com/assets/4942077/757533/0d19022a-e6b5-11e2-9cb4-62dede4b03db.jpg)

**Comment by F4NT4SM4** [comment]
cuando yo hice esa mision no eran esos cañones que usaba xD
a lo mejor no estan los cañones que deberian de estar y piensas qe son esos

**Comment by redneo** [comment]
Ya se pueden usar los cañones (creo)

**Comment by crowel** [comment]
Funcionando
