### ISSUE TITLE
[Misión] Fiordo Aquilonal - Las hermanas caídas

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2304]
http://es.wowhead.com/quest=11314

Con el collar que te dan liberas a las ninfas.

Usas el collar(http://es.wowhead.com/item=33606) sobre las ninfas y no se liberan

**Comment by redneo** [comment]
Fixed

**Comment by Wiinter** [comment]
Se tiene qe caer el server para que vaya?
