### ISSUE TITLE
[Misión] Fiordo Aquilonal - Prueba en el mar

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2305]
http://es.wowhead.com/quest=11170

Coges el murcielago de Camille y lanzas los viales de peste (http://es.wowhead.com/item=33349) sobre los barcos llenos de reservistas pero no te cuentan.

No te cuentan como infectados aunque tires los viales encima de ellos.

**Comment by redneo** [comment]
fix
