### ISSUE TITLE
[Misión] Fiordo Aquilonal - La magnetita

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2307]
http://es.wowhead.com/quest=11366

Vas con la muestra de runas (http://es.wowhead.com/item=33819) para comparar con la tablilla que hay en las rocas.

Vas con la muestra de runas hasta el lugar indicado, la usas pero no completa la misión.

**Comment by redneo** [comment]
arreglado
