### ISSUE TITLE
[hechizos] Sed de Sangre

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#2309]
Buenas,

Quisiera reportar que esta skill esta haciendo daños muy elevados a lo normal (10k), me refiero a que no hay lógica alguna en spammear 15, 20k+ cada 3 segundos contra un pj full temple 4k+ en fín.

![sed](https://f.cloud.github.com/assets/4790547/1316522/fa8dfd52-3297-11e3-9b05-bdb2c0c58824.JPG)

Descripción del problema: Estabamos en bg 1x1, en lanzó el machaque y algunos spell y en 3 segundos me dejo en el 5% de vida mas o menos. Luego me tire burbuja y sali corriendo a curarme, cuando volvió a tirarme la S de S y me seguia quitando los daños astronómicos.

Según la fórmula aqui enseñada, deberia pegarme entre 7000 y 10000 normalmente:

AP \* 0'82 (Según armería el AP de Aniquilación war fury es de 9992.) En la fórmula me deja como resultado: 8193 dps. Suponiendo que tuviese algún trincket o más AP en ese momento:

http://www.reignofdarkness.net/wow/character/1/16094

14.000 x 0.82 = 11480 dps.

No concuerdan las cifras con las fotos donde ya habia activado sus cosas y luego me fui a curarme y los daños seguian siendo elevados.

La verdad no estoy del todo convencido si es esta skill la que falla por el lado del daño y del crítico, o si es que el war tiene aún el machaque colosal bug y lo esta dejando permanente ó que se yo.

ID: 23881

http://www.wowhead.com/spell=23881/bloodthirst#comments
http://www.wowwiki.com/Bloodthirst

![wowscrnshot_101013_150022](https://f.cloud.github.com/assets/4790547/1309932/bcf40636-31e7-11e3-944e-a5aff0d8bf2f.jpg)
![wowscrnshot_101013_150034](https://f.cloud.github.com/assets/4790547/1309936/bd08fef6-31e7-11e3-9228-aeeb3c3d54dc.jpg)

Despues de curarme y haber resistido en menos de 5% con burbuja:
![wowscrnshot_101013_150003](https://f.cloud.github.com/assets/4790547/1309933/bcf78f68-31e7-11e3-983a-1070164aa73a.jpg)

Al menos podrian probar en el juego sin descartar las cosas asi como asi...

Ayudame @fixx

**Comment by Wiinter** [comment]
No es por nada pero te van a cerrar el post por mal reportado. Tienes que seguir las pautas que puso fixx en el foro. 
-Enlace de lo que quieras postear
-Descripcion de la spell
-Problema
-Observaciones y demás cosas
Te aconsejo qe lo cambies rapido asi no lo tendrás qe volver a hacer. No vale con solo poner la id, tienes qe poner el enlace a wowhead u otros. Además como sabes que hace más daño de lo normal? Con tus fotos no aportas nada, podría ser que hubiera activado los cds.

**Comment by elmiriox15** [comment]
Te confirmo yo que el daño es el correcto, según el daño de la skill ingame esta haciendo unos 50 ptos menos de lo que pone pero asi esta genial.

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by ghost** [comment]
Por si quieres hacer un reporte en condiciones, esta es la fórmula para que lo testees: AP \* 0'82

**Comment by elmiriox15** [comment]
Bien, por fin encuentro la fórmula, porque en Openwow no la vi y wowhead es diferente.
