### ISSUE TITLE
portal a uldum bug

### ISSUE THREAD

**Issue by maxib** [RoDNet/Bugtracker-Infinium-4.3.4#2310]
quisiera que arreglaran el portal a uldum es muy necesario ese portal por que esta muy lejos y necesito ir pero se tarda demasiado en ir si lo arreglaran es urgente graxias

**Comment by lamaza** [comment]
No se tú, pero el portal desde Ventormenta a Uldum esta funcionando perfectamente al 100%.

**Comment by Wiinter** [comment]
No te va porque no has hecho la misión del Tablón de Orgri o Ventormenta que se llama ¡Llamamiento a las armas: Uldum!. Tienes que hacer la cadena para poder ir por los portales.

**Comment by kingtonix** [comment]
Es cierto lo que dice Maxib,muchos de los portales de la horda no sirven,los alianzas si,pero los hordas no,como el de uldum por ejemplo.

**Comment by redneo** [comment]
Tienes que hacer las cadenas de misiones para que funcionen con los de Uldum, Monte Hyjal, Infralar.

Los de Tierras altas los puedes coger sin haber hecho la cadena de misiones, ya que la misma aun no funciona. El de Vashj'ir no funciona directamente, ya que toda la zona necesita de un arreglo total.
