### ISSUE TITLE
Abalorio Estabilizador de matriz (TIENDA)

### ISSUE THREAD

**Issue by 3du42d0** [RoDNet/Bugtracker-Infinium-4.3.4#2311]
Hola ayer me gasté mis tan sufridos 500Cr comprando el abalorio estabilizador de matriz (item=68994) y es que no anda el efecto, no se activa nunca lo he probado por media hora y nada, sólo te aporta los +406 de agilidad, pero nada con el efecto de aumentar 1624p de Crítico, Celeridad o Maestría según tu stat más alta. ojalá lo puedan fixear porque es algo que está en la tienda para comprar y es decepcionante gastarte todo lo juntado en algo que no funciona. Gracias.

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
