### ISSUE TITLE
[Druida feral] Destripar ID: 1079

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2313]
No se si el problema persiste debido a que no se pudo subir aún el arreglo, de todas maneras, como han pasado ya unos días lo vuelvo a subir:

(viene de https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1910 )

Link de la habilidad (con valores actualizados a la 4.3): http://wow.freakz.ro/spells.php?spell=1079

Descripción: Rip      Cat Form
30 Energy       Melee range
Instant cast  
Finishing move that causes Bleed damage over time. Damage increases per combo point and by your attack power:
1 point: (56 + 4 \* 1 + 0.0207 \* AP) \* 8 damage over 16 seconds.
2 points: (56 + 4 \* 2 + 0.0414 \* AP) \* 8 damage over 16 seconds.
3 points: (56 + 4 \* 3 + 0.0621 \* AP) \* 8 damage over 16 seconds.
4 points: (56 + 4 \* 4 + 0.0828 \* AP) \* 8 damage over 16 seconds.
5 points: (56 + 4 \* 5 + 0.1035 \* AP) \* 8 damage over 16 seconds.

Problema: el daño está bastante más subido
Con 5 puntos de combo:
http://img21.imageshack.us/img21/9308/4l4o.jpg
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/21/4l4o.jpg/'><img src='http://img21.imageshack.us/img21/9308/4l4o.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

**Comment by Wiinter** [comment]
Te aconsejo que acompañes la foto con otra foto mostrando el recount o algo porque un daño te salga mas alto que la media no tiene mucho de si. Con el recount puedes demostrar que la media esta subida que es al final lo que tiene sentido. Espero haber sido de ayuda

P.D: Podría ser que aun no esté implementado porque Searum se ha ido de vacaciones unos días y creo que desde se fué no han vuelto a compilar el core

**Comment by Dekadencee** [comment]
Fixed

**Comment by paellaencol** [comment]
Lo acabo de probar y está haciendo aún más daño que antes

**Comment by Kiritoo** [comment]
Emmm me da que no, ya que no se compilo es imposible que haga más daño que antes.

**Comment by paellaencol** [comment]
De veras es, este druida sigue con el mismo equipo que cuando lo puse. Por ejemplo la descripción que me da el propio wow me marca 16548 puntos de daño durante 16seg (lo cual me parece bajo).

Haré una breve descripción de la fórmula completa:

Tomemos la fórmula (a pelo, sin multiplicadores posteriores) --> 5 points: (56 + 4 \* 5 + 0.1035 \* AP) \* 8 damage over 16 seconds.

Mi poder de ataque son 14768, aplicando la fórmula sale 1778 el tick de daño, es decir 14309 durante 8 segundos.

Bien, ahora a esta fórmula hay que añadirle dos multiplicadores, el primero es el propio debuff de destrozar que aumenta un 30% el daño por sangrado http://wow.freakz.ro/spells.php?spell=33876 y después hay que añadirle la maestría http://wow.freakz.ro/spells.php?spell=86470 (que en mi caso y con mi equipo es un multiplicador de x1,28).
Por tanto si multiplicamos el valor inicial de 14309 x1,3 x1,28= 23811 durante 8segundos (es decir 2976 el tick normal)

---

Sin embargo estoy viendo lo siguiente:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/19/phra.jpg/'><img src='http://img19.imageshack.us/img19/3405/phra.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img19.imageshack.us/img19/3405/phra.jpg

**Comment by Dekadencee** [comment]
Aún no está compilado el fix, desconocemos el porqué de la variación, porque no se han realizado cambios hasta la siguiente compilación.

Tras la compilación (viendo en el server info la fecha de hoy o posterior) nos comentas a ver si se ha resuelto.

Un saludo
