### ISSUE TITLE
[Misión] Colinas Pardas - Plaga chamuscada

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2314]
http://es.wowhead.com/quest=12038

Tiras al Grok (http://es.wowhead.com/item=35908) y deberías quemarlos

Le tiras el Grok a los trols pero no te los marca como quemados

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1174?source=cc
