### ISSUE TITLE
[Spell > Hunter] Lock and Load

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2318]
Nombre: Bloquear y cargar
![bloquear cargar](https://f.cloud.github.com/assets/3537253/1315376/ec302f4e-3285-11e3-9350-4965fdc69562.jpg)
Problema: Este talento, cuando se activa los siguientes 2 disparos explosivos no deben de costar enfoque ni tener tiempo de reutilización, actualmente el segundo de los disparos siempre está costando enfoque y no deberia, impidiendo lanzar el segundo cuando no se tiene enfoque.
Observación: Disparo explosivo http://es.wowhead.com/spell=53301

Un saludo.

**Comment by Jhovanni** [comment]
Hoy he podido comprobar l oque ya antes me había dicho Crowel, pero a mi no me pasaba y hasta lo habíamos hablado.
Luego de los cambios de ayer (creo que hicieron), como resultado tengo lo que menciona Crowel, el segundo disparo explosivo está costando enfoque.
Aparte, he visto una disminución de daño x segundo, alrededor de unos 100dps —no más que eso—. Pero no sé en qué parte está esa disminución, sería genial pudiesen darle una checada los gms porque perdí puntos con ese rollback que no pude volver a otbener, disparo explosivo gratis y dps —bonito miércoles jeje—.

**Comment by crowel** [comment]
Me estoy fijando bien y no es que se cobre mucho el disparo, sino que se estan cobrando unos 10puntos por cada disparo explosivo.
