### ISSUE TITLE
[Brujo] Armadura Vil en la rama de Destrucción

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#2319]
Nombre: Hechizo Armadura Vil

Enlace: http://wow.freakz.ro/spells.php?spell=28176

Lo que está pasando con este hechizo del brujo es que en la rama de destrucción no sana la cantidad debida, es decir, yo tengo potenciado armadura vil de tal forma que me debería devolver un 6% de cualquier daño con hechizos que haga ya sea inmolar, llama vil, maldiciones, etc. Esto en la rama de destrucción no esta pasando, sin embargo, en la rama de aflicción por ejemplo si se sana con esto.

Conclusión la rama de destrucción pierde la sanación derivada de este hechizo cosa que en otras no pasa, lo que es raro.

Pongo imágenes para que lo podáis ver, usando como ejemplo inmolar y llama vil.

![wowscrnshot_101113_174212](https://f.cloud.github.com/assets/3939699/1315838/1cba871c-328c-11e3-9c99-43785a8365b6.jpg)

![wowscrnshot_101113_174231](https://f.cloud.github.com/assets/3939699/1315841/2526375c-328c-11e3-808a-f47d61886fe5.jpg)

![wowscrnshot_101113_174234](https://f.cloud.github.com/assets/3939699/1315846/36727322-328c-11e3-968b-a1b9bcdc2648.jpg)

![wowscrnshot_101113_174259](https://f.cloud.github.com/assets/3939699/1315850/40d2472a-328c-11e3-844e-1ff3a91f5120.jpg)

Un saludo

**Comment by ghost** [comment]
Bastante importante esto. Cuando llegue lo testeo porque CREO que a mi si que me está dando sanaciones.

**Comment by Drogoth2** [comment]
Yo lo he comprobado en afli y si me lo da pero en destrucción no me lo da con nada

**Comment by ghost** [comment]
A mí me está sanando. El problema debe ser del talento que potencia la armadura, es decir, égida demoníaca (id: 30143)

Edito: Pues no, a mi me sigue sanando con égida demoníaca también xD

**Comment by Drogoth2** [comment]
Ese talento también lo llevo en aflicción y repito que me sana, pero en destrucción sigo igual no me da nada. De hecho me acabo de poner a mirarlo y me he encontrado con otra sorpresa no me da ni siquiera el poder con hechizos de 638 ni en la rama de aflicción ni en la rama de destrucción.

Adjunto imágenes para que lo veáis mirad los daños y veréis que no varían (voy a usar llama vil en las dos ramas para que se vea que en destrucción no sana y que en ninguna de las dos ramas me da el poder con hechizos):

En destrucción sin armadura vil

![wowscrnshot_101913_193531](https://f.cloud.github.com/assets/3939699/1366791/e2d50716-38e4-11e3-822a-625cb3e82b11.jpg)

En destrucción con armadura vil

![wowscrnshot_101913_193558](https://f.cloud.github.com/assets/3939699/1366792/efd39950-38e4-11e3-9198-165eef40befb.jpg)

En aflicción sin armadura vil

![wowscrnshot_101913_193054](https://f.cloud.github.com/assets/3939699/1366787/8bd2d3bc-38e4-11e3-98c5-a42b56f10759.jpg)

En aflicción con armadura vil

![wowscrnshot_101913_193433](https://f.cloud.github.com/assets/3939699/1366789/c255e4b0-38e4-11e3-9c00-dd7b9becacd5.jpg)

Yo no se si esto les pasará a todos los brujos o sólo a mi pero las pruebas están ahí. De todas formas me gustaría que algún brujo más lo mirara y me dijera algo.

Gracias por las molestias y un saludo

**Comment by ghost** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2143  Por si quieres añadir algo al reporte general de todas las clases.

**Comment by Wiinter** [comment]
Esto se puede cerrar, además qe no le sanaba pq no produce overheal armadura vil y es por eso qe no sale.
