### ISSUE TITLE
No deja hacer misión en Campamento de Entrenamiento Lanza Negra (Trol)

### ISSUE THREAD

**Issue by QuinoaPaladin** [RoDNet/Bugtracker-Infinium-4.3.4#232]
Cuando vas haciendo misiones llegas a una en la que se te pide hablar con un carcelero y luchar con un cautivo,pero cuando hablas con el carcelero no pasa nada,no te deja pelear.

**Comment by crowel** [comment]
Que reporte más completo jeje.

**Comment by efectokoleos** [comment]
reporte incompleto lee como postear los bugs
