### ISSUE TITLE
[Druida] Regeneración frenética

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#2320]
Nombre: Regeneración frenética

Descripción: Aumenta la salud máxima un 30%, aumenta la salud un 30% (si se está por debajo de ese valor) y convierte hasta hasta 10 puntos de ira por segundo en salud durante 20 s. Cada punto de ira se convierte en un 0.30% de la salud máxima.

Fallo: está aumentando el 30% de salud siempre, no es necesario tener menos de un 30% de salud.

ID: http://cata.openwow.com/spell=22842

**Comment by Wiinter** [comment]
Creo qe no vas mal encaminado. He estado haciendo unas pruebas con un druida y con mi amigo @Drogoth2 para ver como funcionaba la spell en questión. Las conclusiones que he sacado:
-Con 104k de salud máxima al tirarme la spell pasaba a 135200 de salud maxima.
-Si estoy por debajo del 30% de mi salud màxima, 135200 \* 0,3 = 40560, no me augmenta la salud un 30% de la salud máxima (40560). Creo qe aqui es donde te has confundido. Cuando dicen salud es que te curas el 30% de tu salud maxima y esto, como he dicho antes, no está ocurriendo, no te curas con una sola cura 40k si estas por debajo del 30%.
-La sanacion periódica que recibe por la conversion de puntos de ira es correcta. Por cada punto de ira te lo convierte en un 0.3% de salud máxima (135200*0.003=4056). Si tienes mas de 10, te coge solo 10 y si tienes menos pues te coge los qe tengas. Por tanto diría que esta parte es correcta.

Conclusión que he sacado, que la primera parte de la spell va bien, la segunda no y la tercera si. También me he podido fijar que el oso gana muchisima ira con un simple ataque, gana alrededor de 60 puntos de mana por un ataque. Puede que la regeneración de ira sea lo qe no funcione bien, pero Regeneracion Iracunda no tiene el fallo qe tu pones o almenos yo no lo he podido comprovar. Y como he dicho anteriormente Evilknight estaba de testigo por si le quereis preguntar.

Un saludo

**Comment by nicerdicer** [comment]
Ingame ya se lo comenté a Miriox, que la facultad no dice ''Aumenta la salud máxima un 30%, aumenta la salud un 30%'' si no que ''Aumenta la salud máxima un 30%. Aumenta la salud un 30%'' que ahi haya un punto y no una coma en realidad dice mucho, por que te separa dos acciones diferentes en una misma facultad, es decir, no requiere estar a 30% de salud para que te aumente ese 30% extra del que habla la primera parte, sino que ese 30% te lo aumenta siempre y en el caso de que estés a 30% de salud (restante) te lo aumenta igual en forma de aguante de reserva, un ejemplo, es el Berrido de Convocación del warrior, el cual independientemente de la vida que te quede, te aumenta un (no me acuerdo cuanto) el aguante proporcionandote una minima supervivencia temporal... Almenos asi lo entiendo yo leyendo la facultad y probandolo con mi druida.

Otro asunto es lo que ha deducido Wiinter que es completamente cierto, la transformación de daño en Ira del druida en forma de Oso es flipante, por un golpe cualquiera la ira llega a 50 puntos facilisimamente, de forma que mientras que el druida reciba daño o genere Ira mientras dure regeneracion frenetica, este se va a curar irremediablemente.

SALUDOS.

**Comment by searum** [comment]
fix
