### ISSUE TITLE
[Brujo] Bug beneficioso en la rama de destrucción

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#2321]
Bueno este post es un poco largo porque creo que esta pasando en función de un talento, paso a explicarme.

En la rama de destrucción se tiene este talento http://cata.openwow.com/spell=30295 (el cual ya esta reportado aquí puesto que no regenera el mana https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1677).

Bien sabiendo esto si veis la descripción que a continuación aparece, ese talento solo debería de sanar un 4% con el uso de los hechizos de Descarga de Caos, Fuego de alma y Quemadura de las sombras; pero no con conflagrar e incinerar.

Es decir, conflagrar e incinerar están otorgando una sanación que no deberían ya que estos hechizos solo deberían sanar en presencia de armadura vil (que en destrucción no va bien https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2319).

Conclusión este talento esta afectando al brujo destrucción de forma importante debido a lo siguiente:
1. No se otorga el efecto de reposición el cual es una gran baza ya que hace que el brujo destrucción, que se sana menos que en otra rama, tarde más en perder mana y por lo tanto tenga que usar menos transfusión de vida. Como ya he dicho, esto esta en otro post.
2. Este talento solo otorga la sanación indicada con los hechizos indicados arriba, jamás con conflagrar e incinerar.

Conclusión: el Talento de Parasitar alma está dando un bug beneficioso de sanación pero por otra parte no da el maná que debería. A mi juicio es un talento bastante importante para el brujo en la rama de destrucción.

Paso a enseñaros unas fotos para que veais lo que ocurre:

![wowscrnshot_101113_175329](https://f.cloud.github.com/assets/3939699/1315977/5c010016-328e-11e3-8044-9277f4df0797.jpg)

Usando conflagrar 

![wowscrnshot_101113_180143](https://f.cloud.github.com/assets/3939699/1315989/813b490e-328e-11e3-9d5e-f1b4a3fd44ca.jpg)

Usando incinerar 

![wowscrnshot_101113_180155](https://f.cloud.github.com/assets/3939699/1315991/899c8d42-328e-11e3-9ade-e2bf4c861924.jpg)

Espero que haya quedado todo claro y sirva de ayuda.

Un saludo y gracias

**Comment by ghost** [comment]
Hay que dejar claro que amén de los bugs de este talento, la armadura sí que debe otorgar sanación con TODOS los hechizos dañinos.

**Comment by Drogoth2** [comment]
Al recuperar mana me dura mas por lo que usare menos transfusión de vida para recuperarlo y por tanto perderé menos vida al no usar la transfusion. 

He hay la aclaración asman

**Comment by Kiritoo** [comment]
Fixeada la sanación falta ajustar el mana, seguimos desde aqui #1677
