### ISSUE TITLE
[C

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2322]
[En.

**Comment by Wiinter** [comment]
Una pregunta, este ticket no debería estar solo en Mascotas como los demás hechizos de pets? Me imagino Asman que tu no tendrás mucho qe ver con las etiquetas, es mas bien una pregunta al responsable. Porque si esta la etiqueta así tiene que cambiar muchas mas que estarán mal.

**Comment by Jhovanni** [comment]
Me gustaría hubiese una explicación en que se basa para decir que hace más del daño que debería. No digo que esté equivocado en su afirmación, pero no hay sustentabilidad en la misma.
¿Cuanto es el daño que considera, o en base a datos demuestra, que debe de ser? Sobre todo hay mucha charla sobre eso en los canales globales porque comparan lo que hace una mascota en bestias con respecto en las otras ramas, y definitivamente tomando eso como base, la mascota hará más en bestias.
Para dar una idea, una mascota en SV/MM tiene un daño de 820-870 (con el equipo que tengo), mientras que en bestias, con el mismo equipo su daño llega a 2310. Lo cual hace la gran diferencia, aparte de los talentos de mascota que hacen que mordedura (y las otras habilidades básicas de mascota) inflinja el doble de daño.
