### ISSUE TITLE
[Misión] Zul'Drak - Donde hay patrón...

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2325]
http://es.wowhead.com/quest=12673

Te conviertes en Necrofago, tomas bajo control a un geist y le ordenas recoger cristales

El problema es que lo puedes controlar pero a la hora de ordenarle que recoja los cristales la spell no va.

**Comment by redneo** [comment]
Si que va... prueba mejor, la hice hace una semana o menos.

**Comment by Wiinter** [comment]
Hago al geist de añublo mi pet y le doy a la opción de Cosechar cristal de añublo y me pone que Aun no puede hacer eso

**Comment by Wiinter** [comment]
Vale, la complete pero solo funciona con algunos cristales
