### ISSUE TITLE
[Misión] Zul'Drak - La venganza del Rey de la Tormenta

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2326]
http://es.wowhead.com/quest=12919

Te montas encima de Gymer y empiezas a matar con sus habilidades a los npcs que te marca.

No te deja montar en Gymer, entonces no puedes matar a los mobs que te marca.

**Comment by redneo** [comment]
Id de Gymer???

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
