### ISSUE TITLE
[Misión] Zul'Drak - Patrulla trol

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2327]
http://es.wowhead.com/quest=12596

Tienes que completar 4 diarias de 4 npcs.

Si haces las diarias solo se completa, las diarias del capitán Grondel. Las demás por mucho que las hagas no te cuentan.

**Comment by redneo** [comment]
Podias poner las ids de las otras...

**Comment by Wiinter** [comment]
Capitán Brandon:
http://es.wowhead.com/quest=12588
http://es.wowhead.com/quest=12564
http://es.wowhead.com/quest=12502

Capitán Rupert:
http://es.wowhead.com/quest=12509
http://es.wowhead.com/quest=12568
http://es.wowhead.com/quest=12591

Capitán Grondel:
http://es.wowhead.com/quest=12519
http://es.wowhead.com/quest=12585
http://es.wowhead.com/quest=12594

Alquimista Finklestein
http://es.wowhead.com/quest=12541

**Comment by redneo** [comment]
ya funciona
