### ISSUE TITLE
[Feria de la Luna Negra] Portal en Villadorada.

### ISSUE THREAD

**Issue by Alfonn** [RoDNet/Bugtracker-Infinium-4.3.4#233]
No están ni los npcs ni el portal hacia la feria de la luna negra.

![image](https://f.cloud.github.com/assets/3854953/757814/60cdb9e6-e6f2-11e2-9718-98be60adabfa.png)

**Comment by frustrix** [comment]
Lo confirmo

**Comment by crowel** [comment]
Añadido campamento en Villadorada.
