### ISSUE TITLE
[Misión] Zul'Drak - Arriba la cola

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2330]
http://es.wowhead.com/quest=13549

Le tiras un dardo duermes al leopardo o oso y interactuas con ellos y miras si es macho o hembra.

Le tiras el dardo y no se duerme. Cuando se "duermen", una remota posibilidad, te vas a acercar y te atacan sin poder siquiera hablar con ellos.

**Comment by redneo** [comment]
Creo que solucionado cuando caiga el server... me lo compruebas.

**Comment by ghost** [comment]
Funciona

**Comment by Wiinter** [comment]
Sip, perfectamente :)
