### ISSUE TITLE
[Misión: Los baldíos del norte] Recogida de caravana de El Cruce

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2333]
Enlace: es.wowhead.com/quest=13949/recogida-de-caravana-de-el-cruce

Descripción: Habla con Halga Ojosangre en la Avanzada del Puente para escoltar la caravana de El Cruce hasta la Granja de Grol'dom. 

Problema: nos debería aparecer una caravana, en la cual montarnos, y mediante la utilización del item http://es.wowhead.com/item=46714 (este objeto sí que nos lo dan, pese a que no aparece el kodo) proteger la caravana.
El kodo en el cual deberíamos montarnos, creo que es este http://es.wowhead.com/npc=34430/lead-caravan-kodo y tal vez el problema sea que no se está produciendo la siguiente spell http://es.wowhead.com/spell=65494#used-by-npc
Finalmente, tenemos que entregar la misión a este personaje http://es.wowhead.com/npc=5907 una vez la diligencia ha llegado a su destino.

Observaciones: http://www.youtube.com/watch?v=rrB0DcZlCls

**Comment by redneo** [comment]
Arreglado sin los disparos. (cuando caiga el server)
