### ISSUE TITLE
[NPC Los baldíos del norte] Kadrak

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2334]
Enlace: http://es.wowhead.com/npc=8582#ends

Problema: Falta el npc http://es.wowhead.com/npc=8582#ends que debería encontrarse en la "Empalizada de Mor'shan"

Nota: no confundir con estos dos http://es.wowhead.com/npc=33837 http://es.wowhead.com/npc=34006 que se encuentran en Vallfresno

Problemas relacionados: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2047

**Comment by ghost** [comment]
Ya estaba reportado, y supuestamente solucionado.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1465

**Comment by redneo** [comment]
Ya esta arreglada. Aparece si tienes la mision http://es.wowhead.com/quest=28876 o http://es.wowhead.com/quest=28493
