### ISSUE TITLE
1º mision de druida elfo esta bug(toque de rejuvenecimiento, Aldrassil-Teldrassil)

### ISSUE THREAD

**Issue by Wesera** [RoDNet/Bugtracker-Infinium-4.3.4#2336]
La 1º misión de druida elfo de la noche esta bug curo a las centinelas heridas pero no pasa nada no me cuenta como realiada sigue ah para realizarlas ya llevo curandolas varias veces por favor ayuda gracias.
La mision se llama toque de rejuvenecimiento en aldrassil, teldrassil

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
