### ISSUE TITLE
[Guerrero] Furia enfilada

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#2337]
Nombre: Furia enfilada

Descripción: Cuando utilizas doble empuñadura con armas de una mano,infliges un  20% de daño extra y golpeas con Embate con ambas armas.

Fallo: está funcionando con solo llevar un arma de una mano cuando debería ser llevando las dos.

Observaciones: se puede bugear para aumentar el 20% el daño y usar doble embate si se pone un arma de dos manos junto con otra de una mano.

ID: http://es.wowhead.com/spell=81099

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
