### ISSUE TITLE
[Guerrero] Venganza

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2338]
http://wow.freakz.ro/spells.php?spell=93098 --> Venganza
http://wow.freakz.ro/spells.php?spell=76691 -->Bufo de venganza

Cada vez que recibes daño, ganas un 5% del daño recibido como poder de ataque, hasta un máximo del 10% de tu salud

La habilidad va como quiere, no sube los puntos concorde al daño recibido. A veces un ataque no te da venganza y otro demasiada y así.

**Comment by searum** [comment]
fix
