### ISSUE TITLE
[Misión: Vallefresno] Cabeza de redención

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2339]
Enlace: http://es.wowhead.com/quest=13842/cabeza-de-redencion

Descripción: Habla con Durak en Mina del Hachazo. Tras hablar con él, mátale y consigue http://es.wowhead.com/item=60638

Problema: Durak http://es.wowhead.com/npc=44414#drops no da la opción de iniciar una conversación de misión, y por tanto no se convierte en hostil, y no podemos matarle.

Vídeo: http://www.youtube.com/watch?v=DppP60DRd2c Minuto 3:30-4:30

**Comment by redneo** [comment]
Arreglado
