### ISSUE TITLE
[Misión: Sierra Espolón] Cenizas a las cenizas

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2341]
Enlace: http://es.wowhead.com/quest=26010

Enlace del objeto de misión: http://es.wowhead.com/item=56473

Descripción: Utiliza el lanzallamas Krom'gar para destruir 8 tiendas de Fuerte del Norte. 

Problema: Al utilizar el Lanzallamas Krom'gar sobre las tiendas de Fuerte del Norte, no cuenta como quemada.

Observaciones: hay que mantener el casteo completo de 8segundos para que contabilice la quema, no vale con un casteo parcial.
Pese a que actualmente no se puede realizar, las tiendas de Fuerte del Norte sí que aparecen en color brillante (para indicarnos que forman parte de la misión)

Vídeo: http://www.youtube.com/watch?v=5mvTd0h8fH4

**Comment by redneo** [comment]
Arreglada, dejala y vuelvela a coger
