### ISSUE TITLE
[Con

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2342]
Descripc

**Comment by elmiriox15** [comment]
En arenas hay de esos buffos? jeje varios años haciendo arenas y ahora me entero xD.

**Comment by ghost** [comment]
Sí, al tiempo sa

**Comment by elmiriox15** [comment]
No, esos si pero decía los buffos de 30% daño, velocidad, vida.

Pero al parecer leí mal, esos no están jeje.
