### ISSUE TITLE
[Brujo] Quemar alma - Invocar demonio

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2343]
Enlace de quemar alma: http://wow.freakz.ro/spells.php?spell=74434

<strong>Descripción:</strong> Consume un fragmento de alma, lo que revela el poder oculto de tus hechizos. Esto potencia algunos de tus hechizos.

<strong>Descripción de Quemar alma para invocar demonio:</strong> Reduce el tiempo de invocación a 0 segundos, es decir, lo hace instantáneo.

<strong>Problema:</strong> Está dando la invocación instantánea, pero el efecto de quemar alma no desaparece, por lo que puedes obtener doble beneficio.

**Comment by Wiinter** [comment]
Ya pasaba cuando lo arreglaron, incluso Searum lo dijo que no supo como arreglarlo. La cosa es que se consume con las demás habilidades menos con los demonios, algo muy extraño.

**Comment by Kiritoo** [comment]
Fix, al usar cualquiera de las invocaciones desaparecerá Quemar Alma.
También reparado y no mencionado aqui fuego de alma que se podía lanzar instantaneo durante los 15 segundos que duraba Quemar Alma todas las veces que quisiera (Me dio tiempo a lanzar 10 instantaneas durante esos 15 segundos... me parece raro que ningun brujo se diera cuenta).

**Comment by Wiinter** [comment]
Pensaba que lo de fuego de alma estaba reparado. Y que solo continuaba bug lo de invocar las pets.

**Comment by ghost** [comment]
@fixx eso esta reportado, y no solo una vez, sino 2.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2885

y en el repote de toodas las clases que parece que ya se ha olvidado. Edito yborro el enlace al reporte desde aquí para no alargar el reporte.
