### ISSUE TITLE
[Misión: Sierra Espolón] El principio del fin

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2344]
Enlace: es.wowhead.com/quest=26074/el-principio-del-fin

Descripción: Lleva el globo aerostático Krom'gar hasta Los Fangados, en Sierra Espolón. 
Enlace del globo: http://es.wowhead.com/npc=42030

Problema: En teoria deberíamos poder escoltar la bomba http://es.wowhead.com/npc=42030 hasta los fangados, pero el globo no nos lleva hasta allí.

Observaciones: a no ser que tengas montura voladora, y siendo esta una misión de nivel muy bajo, no puedes acceder al globo.

**Comment by Wiinter** [comment]
Antes estaba el globo en un lago y podías acceder desde una elevacion que podías subir con montura terrestre, te subías y te completaba la misión.

**Comment by redneo** [comment]
Es otra mision Wiinter, ya está arreglada.
