### ISSUE TITLE
[Spell > Hunter] Aspect of the Fox

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2348]
Nombre: Aspecto del zorro
http://cata.openwow.com/spell=82661

Aspect of the Fox
Instant
Requires level 83
The Hunter takes on the aspects of a fox, allowing G him:her; to shoot Steady Shot and Cobra Shot while moving and causing G him:her; to gain Focus whenever G he:she; receives a melee attack.

Problema: Actualmente cuando se activa este aspecto del cazador y un melee, sea npc, pet, jugador y te ataque cuerpo a cuerpo te interrumpe todos los casteos que posee el cazador, como disparo de cobra o firme, Asustar bestia..etc.

Observaciones: Esto solo ocurre al activar este aspecto, el cual es un aspecto imprescindible del cazador para atacar en movimiento.

Un saludo.

**Comment by Sagittariu5** [comment]
Muchas gracias espero puedan arreglar esto muy pronto :D 
 Les adjunto un video para comprobar el problema

http://www.youtube.com/watch?v=s9RPmMz1DL0

Saludos :dart:

**Comment by searum** [comment]
fix
