### ISSUE TITLE
BUG visual equipamento

### ISSUE THREAD

**Issue by punkska** [RoDNet/Bugtracker-Infinium-4.3.4#2349]
tengo el problema que cuando inspecciono a los demas al ver su ropa aparecen los stats y casi inmediatamente desaparecen y hasta que no lo vuelva a marcar el objeto no se ve cuadno lo hago se vuelve a desmarcar y asi sucesivamente. ATT: Pitcarn

**Comment by ghost** [comment]
A mi me pasa algo parecido, cuando inspecciono a alguien, a los pocos segundos desaparece todo su equipo y arriba, en el resumen del personaje donde pone el nombre y la rama de talentos, se pone la de otro pj cercano. Por ejemplo: 

"Mago restauración" en el caso de que esté inspeccionando a un mago y cerca haya un druida restauración. Los objetos desaparecen, y los árboles de talentos que muestra son la del pj Mago pero con el reparto de puntos del druida o del otro pj cercano.

Es bastante molesto xD.

**Comment by Monleon** [comment]
Esto solo sucede al llevar addons de un parche distinto al  actual
