### ISSUE TITLE
Feria de la luna negra

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#235]
La mision: Comandante de tronque

Cuando aciertas una diana te teletransporta a ventormenta

![wowscrnshot_070713_125135](https://f.cloud.github.com/assets/4893907/757818/666200a0-e6f3-11e2-95cd-603cd3b80146.jpg)

Mision: Dispara y marca

Te montas en el cañon y cuando estas llegando para saltar se teletransporta a ventormenta

Mision: La feria de la luna negra

No esta el npc para completar la mision

**Comment by Varga9** [comment]
como as llegado a luna negra para coger las misiones??, el portal no funciona

**Comment by frustrix** [comment]
El portal de la horda si funciona los de la ali no....... soy ali y me doy todo el viaje asta Mulgore xd

**Comment by ghost** [comment]
Lo de la diana pasa lo mismo en la horda, te teletransporta a orgrimmar.

**Comment by frustrix** [comment]
pero vosotros estais mas cerca de ogri a mulgore estais a tiro de piedra xd
en el bosque de elwynn donde deveria estar el de los alis no esta xd

**Comment by frustrix** [comment]
El fallo no esta en las misiones esta en el "LUGAR"  las misiones las he podido realizar correctamente
esceptuando la de la bala de cañon que no me da tiempo me teletransporta

Cierro tikect
