### ISSUE TITLE
[Druida Feral] Talento: Estampida (ID:78892)

### ISSUE THREAD

**Issue by Cacafuti21** [RoDNet/Bugtracker-Infinium-4.3.4#2352]
http://cata.openwow.com/spell=78892

La parte de Carga feral oso funciona pero la parte de Carga feral felina no funciona que
consiste en cuando haces Carga feral felina se activa la posibilidad de poder hacer Destrozar sin sigilo y sin importar que este detrás del jugador, y que ademas no cueste energía cuando tiene 2 puntos de talento. La parte de , da igual estar detrás del objetivo y de que no cueste energía no funcionan.

**Comment by Kiritoo** [comment]
Fix
