### ISSUE TITLE
[Druida Feral] Habilidad: Arañazo (ID:1822)

### ISSUE THREAD

**Issue by Cacafuti21** [RoDNet/Bugtracker-Infinium-4.3.4#2353]
http://cata.openwow.com/spell=1822

Ha Arañazo no le afecta la habilidad de maestria ya que lo he tasteado y no sube el daño de sangrado que no supera ni los 4k.

**Comment by ghost** [comment]
Ya está reportado, se puede cerrar.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1942
