### ISSUE TITLE
[Misión] Cementerio de Dragones - ¡Viva Roanauk!

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2354]
http://es.wowhead.com/quest=12140/viva-roanauk

Hablas con el npc y mantienes una conversacoin y lo inicias como miembro

Vas hasta Roanauk hablas el primer gossip pero despues no te deja continuar y por tanto no te deja iniciarlo

**Comment by redneo** [comment]
Arreglada
