### ISSUE TITLE
[Misión] Cementerio de Dragones - Difícil de tragar

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2355]
http://es.wowhead.com/quest=12049

Debilitas al gusano y le tiras las cargas (http://es.wowhead.com/item=36732) y explota y te da la carga

Lo debilitas, le tiras la carga pero no pasa nada.

**Comment by redneo** [comment]
Teoricamente arreglado cuando caiga el server. Confirmas y cierras??

**Comment by Wiinter** [comment]
Lo he dejado a menos de 20% de vida, le tiro la carga pero no explota. Entonces no puedo coger la carne chamuscada. He borrado caché y he esperado a que se cayera el server.

**Comment by redneo** [comment]
Arreglado
