### ISSUE TITLE
Bugs del Brujo 

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#236]
Muy buenas a todos:

Traigo algunos bugs del brujo importantes:

ARMADURA VIL: no aumenta el poder con hechizos ni devuelve el 6% de sanación del daño infligido con cualquier hechizo.

La comprobación la he hecho con todos los hechizos, en las imágenes se ve el ejemplo con el hechizo de llama vil.

![wowscrnshot_070713_131904](https://f.cloud.github.com/assets/3939699/757842/5931a60c-e6f7-11e2-95cb-baee0c9202cd.jpg)
![wowscrnshot_070713_131859](https://f.cloud.github.com/assets/3939699/757843/593168ae-e6f7-11e2-9de7-38376cf8ba0d.jpg)

Imagen de daño con Armadura vil

![con arm vil](https://f.cloud.github.com/assets/3939699/757844/6374cc5c-e6f7-11e2-8064-65e591a776df.jpg)

Imagen de daño sin Armadura vil

![sin arm vil](https://f.cloud.github.com/assets/3939699/757846/7ace59d6-e6f7-11e2-878a-e504089ffdf1.jpg)

DEMONIOS O PETS: las mascotas del brujo tienen dos bugs importantes, el daño que hacen es bajisimo y además la vida que tienen no deberia ser tan baja, minimo el manáfago debería rondar los 90k de vida. Esto pasa con todas las mascotas ya sea diablillo, sucubo, abisario o manáfago.

![vida y dao del manafago](https://f.cloud.github.com/assets/3939699/757853/288d171a-e6f8-11e2-84c8-1b27a294cd50.jpg)

INCINERAR: este es un bug beneficioso importante, el brujo solo se sana esa cantidad cuando usa quemadura de las sombras, fuego de alma o descarga de caos (teniendo el talento de parasitar alma puesto lógicamente).

![talentos](https://f.cloud.github.com/assets/3939699/757864/f3f9ab34-e6f8-11e2-9cf2-60ceef1e505b.jpg)
![sanacion incinerar](https://f.cloud.github.com/assets/3939699/757865/fcf24b4c-e6f8-11e2-8af0-e3f196d45176.jpg)

TALENTO DE PARASITAR ALMA: el efecto de reposición que debería darse no salta, es decir no recupera maná. 

![talentos](https://f.cloud.github.com/assets/3939699/757869/3dfff49a-e6f9-11e2-8bbc-8a0eb3c1ebd4.jpg)

Espero que el aporte sirva, si veo más fallos los iré posteando.

Un saludo y gracias por adelantado.

**Comment by Wiinter** [comment]
Quiero aportar que en la rama Aflicción, el talento Succionar vida (Tienes un 50% de posibilidades que te sanes un 2% de tu salud total con corrupción) Funciona bien con Corrupcion, pero también funciona con las demás. 
Me explico, con los demás hechizos en el tiempo también me puedo curar a través de ese talento, y no debería ser asi.

A mi me pasa igual qe a evil y me imagino qe a los demás brujos, que la armadura vil no da ni stats ni vida.

**Comment by Drogoth2** [comment]
Bien ahora he encontrado otro más, el talento de secuelas no funciona bien. Digo esto porque las secuelas se deberían poner sólo con conflagrar y lluvia de fuego para atontar y ahora resulta que se pone con llama vil y con fuego de alma pero hay no queda la cosa resulta que también me afecta a mi al lanzar el hechizo (cosa que no debería pasar nunca).

Dejo aquí las imagenes.

![wowscrnshot_071113_120442](https://f.cloud.github.com/assets/3939699/780950/d503cfb8-ea11-11e2-8fdf-0532ec98e4a0.jpg)
![wowscrnshot_071113_120159](https://f.cloud.github.com/assets/3939699/780951/d502615a-ea11-11e2-8c9c-a9e961ac3db1.jpg)

**Comment by Drogoth2** [comment]
Otro añadido al problema de las pets del brujo, cuando coges una montura y después te desmontas la mascota que lleves desaparece y hay que volver a invocarla.

También acabo de ver que al utilizar quemar alma el hechizo fuego de alma se puede usar repetidas veces de forma instantánea cuando sólo debería ser una.

**Comment by searum** [comment]
tanto os cuesta hacer un reporte por cada bug? es que a mi me resulta mas incomodo tener una lista entera... prefiero ir 1 por 1 arreglando lo que me de la gana, os aviso porque yo normalmente de reportes con tanto bug mezclado no hago ni caso.

**Comment by Felarof23** [comment]
Ok, Gracias por el aviso :) esperamos ansiosos los fixes
Saludos!

**Comment by ghost** [comment]
@Drogoth2 como dijo searum, si puedes poner cada bug en un reporte a parte.
