### ISSUE TITLE
[Misión] (Infralar) Underground Economy (Diaria)

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2366]
Nombre: Economía subterránea
Enlace: http://es.wowhead.com/quest=27048
Descripción: Usa tictacs de Ricket para reunir 3 cristales de alabastro profundo, 3 cristales de celestina profunda, 3 cristales de amatista profunda y 3 cristales de granate profundo. 
Problema: Al usar la bomba sobre las rocas no aparecen los cristales que hay que reunir.
Un saludo.

**Comment by redneo** [comment]
Estaban tirados por el suelo... los he borrado, ahora tienes que utilizar la bomba, ver como revienta y recoger los pedazos.
