### ISSUE TITLE
[Misión] (Infralar) Reactivate the Constructs

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2367]
Nombre: Reactiva los ensamblajes
Enlace: http://es.wowhead.com/quest=26762
Descripción: Reactiva 5 ensamblajes de guerra desactivados. 
Problema: No se pueden reactivar los ensamblajes.

Un saludo.

**Comment by redneo** [comment]
Fixed
