### ISSUE TITLE
[Misión] (Infralar) Violent Gale

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2368]
Nombre: Vendaval violento
Enlace: http://es.wowhead.com/quest=26426
Descripción: Encuentra a Felsen el Duradero y sigue sus instrucciones hasta la entrada de las Profundidades Desmoronadas. 
Problema: Al acercarte a Felsen no cuenta como encontrado, ni al llegar a la entrada de la cueva cuenta.
Observaciones: Felsen el Duradero http://es.wowhead.com/npc=42468

Un saludo.

**Comment by redneo** [comment]
Arreglada, cuando caiga el server.

La primera parte, creo que se puede hacer.
