### ISSUE TITLE
[Paladín] Testeo

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#237]
Hola quiero reportar el daño de los ataques del paladín.
Testeado con un único objeto.
Espada: Zin'rokh, Destructora de Mundos http://es.wowhead.com/item=64377/zinrokh-destructora-de-mundos

<h5>Atacar automaticamente</h5>

-Daño: 1800-2963
-Media DrD: 1817 (1492-2142)

<h5>Golpe de Cruzado - http://es.wowhead.com/spell=35395</h5>

-Daño: 3099-4150
-Media DrD: 3144 (2574-3713)

<h5>Exorcismo - http://es.wowhead.com/spell=879</h5>

-Daño: 2617-2855
-Media DrD: 3103 (2964-3242)

<h5>Cólera Sagrada - http://es.wowhead.com/spell=119072</h5>

-Daño: 2408
-Media DrD: 2466 (2465-2466)

<h5>Consagración - http://es.wowhead.com/spell=26573</h5>

-Daño:211
-Media DrD: 1125 (1120-1130) 10x~112.5

<h5>Sentencia - http://es.wowhead.com/spell=20271</h5>

-Daño:212
-Media DrD: 195 (195-195)

<h5>Veredicto del templario - http://es.wowhead.com/spell=85256</h5>

*1 Carga
-Daño:816-1146
-Media DrD:672 (550-794)

*2 cargas
-Daño:2528-8106
-Media DrD:2016 (1650-2381)

*3 cargas
-Daño:3215-8071
-Media DrD:5262 (4309-6215)

<h5>Tormenta divina - http://es.wowhead.com/spell=58127</h5>

-Daño:2733-3792
-Media DrD:2272 (1866-2677)

Bueno hasta aqui el testeo, si se necesita alguna más avisad.
P.D donde pongo daño, no esta ninguno crítico, solo golpes normales, y va del menor que me salio al mayor.
Un saludo.

**Comment by redneo** [comment]
No está del todo mal, ninguna ni muy over ni miy baja, muchas gracias por el aporte, quieres que retoque algun daño en especial?

**Comment by crowel** [comment]
Hola aqui estamos para reportar lo haga falta^^
Pues la verdad no se ve tan mal en general.
Creo que se deberia mirar lo del daño y las cargas del Veredicto del templario - http://es.wowhead.com/spell=85256

Un saludo y gracias por tu tiempo y trabajo.

**Comment by crowel** [comment]
_Hechizos de sanación_ Sin armadura/arma

<h5>Choque Sagrado - http://es.wowhead.com/spell=25912</h5>

-Curación:4331-4590
-Media DrD: 4445 (4269-4621)

<h5>Destello de Luz - http://es.wowhead.com/spell=19750</h5>

-Curación:7148-7675
-Media DrD: 7864 (7417-8311)

<h5>Luz Sagrada - http://es.wowhead.com/spell=635</h5>

-Curación:4342-4735
-Media DrD: 4994 (4726-5262)

<h5>Luz divina - http://es.wowhead.com/spell=82326</h5>

-Curación:11272-12360
-Media DrD: 13319 (12606-14031)

<h5>Radiancia Sagrada - http://es.wowhead.com/spell=82327</h5>

-Curación:2751-3056 Ticks No lo sé, no los hace.
-Media DrD: 3026 (2726-3326) 3x~559.7

<h5>Palabra de gloria - http://es.wowhead.com/spell=85673</h5>

*1 Carga
-Curación:3300-3600
-Media DrD: 3360 (3217-3505)

*2 Cargas
-Curación:3350-7100
-Media DrD: 6720 (6435-7004)

*3 Cargas
-Curación:10170-14384
-Media DrD: 10079 (9652-10506)

Está todo correctamente, solo luz divina y luz sagrada estan un pelín bajos.

Un saludo.

**Comment by Moyax** [comment]
mmm... Exorsismo esta bajo y Martillo de colera nuestro remate.. Hace cosquilas. T_T exorsismo pega la mitad que de lo que hacia antes. A los mismos mobs que les sacaba 6 - 6,5 k con el a hora les saco 3.25 k. Ambos sin critico. Y Martillo de cólera no pega lo que dice. 
![martillo](https://f.cloud.github.com/assets/4944904/758573/fdba4174-e73e-11e2-8b33-2a854e1412fc.png)

Como se puede apreciar en la imagen La descripcion dice que pega casi 9k pero cuando lo lanzas pega 2.7k menos. Si lo usamos con todos nuestros Aumentos de daño no pasamos los 10-11k  T_T

**Comment by Moyax** [comment]
mmm otra cosa que no me habia fijado... Cuando me pongo inquisicion con mi pala Martillo de colera pega lo que dice.. Inquisicion me aumenta el daño sagrado 30%... Esto quiere decir que Martillo de colera tiene 30% de daño menos.

**Comment by paellaencol** [comment]
Hay un pequeño problema con la cantidad de daño y sanación (me atrevería a decir que no es algo propio del paladín, sino de todas las clases en general).

La sanación y el daño base de prácticamente todas las habilidades, sin llevar nada equipado, están ajustadas perfectamente. Sin embargo al llevar el equipo puesto se descontrolan la mayoría de habilidades, algunas a la baja y otras al alza.

**Comment by crowel** [comment]
Cierto muy bien visto, es lo que le comentaba a redneo, ademas que no es en todas las habilidades, por ejemplo en las de sanación del paladin heal, ocurre en choque sagrado, luz sagrada y radiancia sagrada.
Estoy esperando que se conecte de nuevo para hablarlo con él.
Pero si esto pasa indiferentemente de la clase.
Un saludo^^.

**Comment by paellaencol** [comment]
Sí, es decir. Por ejemplo sin llevar nada equipado, luz sagrada cura un poco menos de lo que debe, sin embargo al ponernos el equipo pasa a hacer el doble de lo que debería, y supongo que cuando empecemos a tener equipo 403 este desfase puede ir a más.

**Comment by redneo** [comment]
Spell 635, 25914, 82327, 85673 Ajustados, voy a ver alguno más.

Spells 879, 2812,36946 ajustados

**Comment by redneo** [comment]
Paella... eso es por la base de datos, si pruebas los 7 spells que he puesto, veras que estan ajustados casi al dedillo con o sin ropa...

**Comment by paellaencol** [comment]
La cantidad de las sanaciones ya van perfectamente!
Únicamente Palabra de Gloria http://es.wowhead.com/spell=85673 se ha quedado un pelín baja, pero nada grave (1k o 1,5k).
La única sanación que falta, y no creo que sea solo un problema del ajuste sino de la dinámica de funcionamiento,es Luz del alba http://es.wowhead.com/spell=85222/luz-del-alba
Es decir, la cura sobre el paladín no está escalando correctamente (sin equipo cura más, y con equipo la cura escala muy poco, prácticamente lo mismo que desnudo), y al resto le está sanando una cantidad fija (600) sin importar el número de cargas de poder sagrado utilizadas.

Gracias por el curro de estas semanas!

**Comment by paellaencol** [comment]
Redneo, estuve probando la spell de luz del alba 85222 después del último cambio, y la cantidad de sanación ya es la correcta, lo que le falla ahora es la utilización.

Después de estar probando esta curación con distinto número de cargas de poder sagrado, he obtenido que:
-Con 1 carga: sano al resto con valor de 1 carga, a mi con valor a 2
-Con 2 cargas: sano al resto de pjs con valor de 1 carga, a mi con valor a 3
-Con 3 cargas: sano al resto con valor de 1 carga, a mi con valor a 4 (aunque parezca increíble lo es, me sana con una carga de más)

Gracias por la paciencia con esta spell!

**Comment by redneo** [comment]
Eso no lo puedo tocar peellaencol (vaya nombrecito) Dekadence, searum o algun otro seguro que tardan 0,2 en arreglarlo :D

**Comment by crowel** [comment]
Cierro tema, ya pues tras el cambio de db se cambiaron las cosas.
Si se necesita reportar de nuevo comunicarmelo.
Un saludo.
