### ISSUE TITLE
[Guerrero] Ejecutar

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#2371]
Nombre: Ejecutar

Descripción: Intenta rematar a un enemigo herido, lo que inflige X p. de daño físico y consume hasta 20 p de ira extra para infligir un máximo de X p. de daño extra. Solo se puede utilizar sobre enemigos que tengan menos del 20% de salud.

Fallo: Está consumiendo únicamente 10 p de ira con lo que su daño es bajo.

Observaciones: Está haciendo más daño del que debería con 10 p. de ira, en mi caso hace unos 5413 y a un enemigo sin armadura le hace 9831.

ID: http://cata.openwow.com/spell=5308

**Comment by Wiinter** [comment]
#1432 hiciste tu mismo el reporte.

**Comment by elmiriox15** [comment]
Bueno, pero es que fue hace tiempo y no han contestado siquiera :/
