### ISSUE TITLE
[Guerrero] Salto heroico

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#2373]
Nombre: Salto heroico

Descripción: Salta en el aire hacia una ubicación fijada y se estampa con una fuerza destructiva que inflige X p. de daño a todos los enemigos en un radio de 8 m.

Fallo: Permite saltar hacia ubicaciones no permitidas como a algún techo o pared.

Observaciones: Se puede utilizar de forma beneficiosa para subir a sitio inaccesibles para otros jugadore, o bien para ir a sitios de forma rápida sin ser así.

ID: http://es.wowhead.com/spell=6544#.

**Comment by searum** [comment]
fix
