### ISSUE TITLE
[Misión] Zul'Drak - Traición

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2374]
http://es.wowhead.com/quest=12713

Hablamos con drakuru en Voltarus y te teletransporta al tejado. Entonces te deja matarlo con la ayuda de unos trols que puedes controlar.

No te teletransporta hasta el tejado. Entonces no lo puedes matar.

**Comment by redneo** [comment]
que gossip sale solo si tienes esa mision?????

**Comment by Wiinter** [comment]
![wowscrnshot_101713_135025](https://f.cloud.github.com/assets/3757460/1351350/75ee90c2-3722-11e3-82d5-b841dd0f4c10.jpg)

**Comment by redneo** [comment]
Fixed!
