### ISSUE TITLE
[NPCs] Terrallende - Raros Élites no tienen Spawn

### ISSUE THREAD

**Issue by Gurh** [RoDNet/Bugtracker-Infinium-4.3.4#2376]
Buenas, subo los élites que faltan en terrallende pues ninguno tiene activado el spawn y sirven para logros.

Un raro es un NPC con nombre propio que suelta un botín mayor de lo normal (Items azules). Suele estar y spawnear en distintas zonas al ser único pero siempre en movimiento por su región.

~~~~Valle Sombraluna~~~~

Collidus el Vigía: http://es.wowhead.com/npc=18694

**Comment by Wiinter** [comment]
No es por chafarte el post, pero hace 2 semanas o asi, completé el logro entero y estaban todos los élites. Incluso podría aventurme a decir que estan bug porque spawneando a veces los 3 a la vez. Usar el NPCScan te hace la vida más fácil para sacar este logro.

**Comment by lupakobayashi** [comment]
De hecho, puede ser que Collidus the Warp Watcher ( http://www.wowhead.com/npc=18694/collidus-the-warp-watcher ) no haga spawn. Estuve buscándolo por más de 5 días, usando NPCscan en sus zonas de spawn  y zonas adyacentes pero nunca apareció. Incluso si estuviese en tiempo de respawn, luego del reinicio de hoy debería haber aparecido pero nada. El resto de rare mobs para el logro Bloody rare ( http://www.wowhead.com/achievement=1312 )  hacen spawn en sus zonas correspondientes

**Comment by lexintor** [comment]
Los de terra no estan yo pase por las zonas y no

**Comment by juaks** [comment]
Puede ser que Collidus no aparezca porque tiene un respawn de 8h, pero yo llevo buscándolo días y no aparece.
Los demás rares si que se pueden matar.

**Comment by Monleon** [comment]
Collidus se encuentra.
