### ISSUE TITLE
Mision Bugueada en Nagrand - Terallende

### ISSUE THREAD

**Issue by oscurodani** [RoDNet/Bugtracker-Infinium-4.3.4#2377]
En Nagrand - Terallende hay una misión bug la cual es de un hilo que la verdad no interesa mucho perder, la misión se llama: ¡Tráeme el huevo! Link de wowhead: http://es.wowhead.com/quest=10111

Explicación: Una vez que te subes al árbol coges el huevo sale el pajaro ese feo negro que te tiene que dar la garra para completar la misión, el pájaro sale bien, se le ataca al pájaro y no entras en combate y dice:  objetivo no valido ....... 

Espero que esta peque contribución sea para ir solucionando uno de los tanto bugs en misiones y así mejorar el server

**Comment by redneo** [comment]
Cuando llega a su posicion final, el pajaro puede ser atacado normalmente. Comprobado.
