### ISSUE TITLE
[GameObject] Nagrand - Tablón de anuncios de Telaar

### ISSUE THREAD

**Issue by Gurh** [RoDNet/Bugtracker-Infinium-4.3.4#2378]
Este tablón debería de dar dos misiones.
1. Misión -> Se busca: Giselda la Vieja bruja -> http://es.wowhead.com/quest=9936
2. Misión -> Se busca: Zorbo el Consejero -> http://es.wowhead.com/quest=9940

Al pulsar encima del tablón no se activa, no abre ninguna conversación ni puedes coger las misiones ni nada.

Tablón de anuncios de Telaar -> http://es.wowhead.com/object=182393

**Comment by oscurodani** [comment]
Eso me ha pasado a mi ja....!!!

**Comment by Wiinter** [comment]
Para coger las misiones del Tablón tienes que ser mínimo Neutral con esa facción. Almenos en el bando Horda es asi con los Mag'har
