### ISSUE TITLE
Problema con misión de instructor de guerrero (Orco)

### ISSUE THREAD

**Issue by QuinoaPaladin** [RoDNet/Bugtracker-Infinium-4.3.4#238]
El instructor de guerreros te enseña carga y te da la misión de utilizarla con un muñeco de entrenamiento pero por mucho que lo utilices con los muñecos no puedes terminar la misión porque no cuenta (incluso con enemigos).

**Comment by crowel** [comment]
Link de la misión para ayudar la reparación.
Un saludo.

**Comment by QuinoaPaladin** [comment]
http://es.wowhead.com/quest=25147

**Comment by redneo** [comment]
arreglada
