### ISSUE TITLE
[Npc Orgrimmar] Drukma (instructor de mascotas)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2380]
Enlace: http://es.wowhead.com/npc=47771/drukma

Descripción: Este intendente es el nuevo instructor de mascotas del cataclysm en Orgrimmar. Es quien permite olvidar talentos a las mascotas de los cazadores

Problema: Pese a que sí te da la opción de abrir conversación para olvidar los talentos de la mascota, no sucede nada más. Es decir, solo aparece la conversación, pero no reinicia los talentos

**Comment by Kiritoo** [comment]
Arreglado cuando se caiga el server, si encontrais alguno mas que no reinicia los talentos avisar y lo arreglo.
