### ISSUE TITLE
[Misión] Marjal Revolcafango - A la cima

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2381]
Enlace: http://es.wowhead.com/quest=25478

Descripción: Pide prestado un jinete del viento a Dyslix Kami-Kaze y habla con Kanati Nube Gris en Cima Tramo Oeste en Feralas. 

Problema: da la opción de pedirle prestado el jinete del viento a Dyslix Kami-Kaze http://es.wowhead.com/npc=40358 pero no sucede nada más.

Observaciones: Tal vez guarde alguna relación con https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1702

**Comment by redneo** [comment]
Creo que arreglada... te lleva y tendria que darte el killcredit de la mision
