### ISSUE TITLE
La matanza de straholme bugeada

### ISSUE THREAD

**Issue by feniix97** [RoDNet/Bugtracker-Infinium-4.3.4#2382]
Mazmorra:http://es.wowhead.com/zone=4100/la-matanza-de-stratholme
Pnj arthas:http://es.wowhead.com/npc=26499
Bug: al terminar de discutir con uther, hay que seguir a arthas hasta stralhome pero el problema es q se cae del piso al tratar de ir ala ciudad imposibilitando hablar con el y continuar la mazmorra.

**Comment by redneo** [comment]
Todos los npcs se caen del piso :S no se si será problema de mapas.

**Comment by efectokoleos** [comment]
dime se cae arthas cuando va corriendo?

**Comment by feniix97** [comment]
Si arthas se cae cuando empieza a ir a stralhome

**Comment by efectokoleos** [comment]
deberia estar arreglado en la próxima compilacion

**Comment by feniix97** [comment]
Que paso con el fixeo de la mazmorra? al final dejaron incompleto el tema y sigue igual de bug a pesar de decirnos x el general q estaría arreglada hace semanas

**Comment by Monleon** [comment]
Ya funciona correctamente
