### ISSUE TITLE
El ojo dela eternidad bugeada

### ISSUE THREAD

**Issue by feniix97** [RoDNet/Bugtracker-Infinium-4.3.4#2383]
Mazmorra:http://es.wowhead.com/zone=4500/
Jefe:http://es.wowhead.com/npc=28859
Bug: al llegar al 50%, Malygos se va volando lentamente  Se vuelve no targeteable e imposibilita atacarlo sin poder hacer nada.

**Comment by Wiinter** [comment]
Has probado de matar los adds que salen?

**Comment by redneo** [comment]
La he hecho varias veces y va bien.
