### ISSUE TITLE
arqueologia

### ISSUE THREAD

**Issue by melcalla** [RoDNet/Bugtracker-Infinium-4.3.4#2385]
dan puntos por completar pieza no por coger pieza

**Comment by Wiinter** [comment]
A partir del nivel 50 solo te dan puntos por completar artefactos,  no por coger piezas.

**Comment by paellaencol** [comment]
No, no los está dando ni a niveles 1-49.

Además, supongo que esto será porque los rates estan x2 en profesiones, al completar un artefacto sólo está dando 2 puntos, cuando por uno común ya debería de dar 5.

**Comment by Dekadencee** [comment]
Fixeado
