### ISSUE TITLE
[Priest - Shadow] Problema con Spell Fear

### ISSUE THREAD

**Issue by oscurodani** [RoDNet/Bugtracker-Infinium-4.3.4#2389]
Buenas os comento que la Spell o Skill Fear falla en que una vez que la lanzas los mobs o jugadores no comienzan andar o correr simplemente los deja quietos como si estuvieran un Stun

Espero que esta contribución sirva para arreglar algo mas en este maravilloso server.

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

De todos modos, creo que te refieres a esto: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2273
