### ISSUE TITLE
[Spell > Druida] Savage Roar

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2392]
Rugido salvaje
![bug druida](https://f.cloud.github.com/assets/3537253/1345356/65bc9396-368e-11e3-9949-203d2ac4f072.jpg)

http://wow.freakz.ro/spells.php?spell=52610

Problema: Está aumentando un 80% todo el daño, cosa que no debería ya que los druidas llevan activo este buffo todo el tiempo y solo deberia ser el 80% con los automaticos.
Observaciones: Estan pegando casi el doble con todo, cuando lo tienen activado.

Un saludo.

**Comment by ghost** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2113

**Comment by redneo** [comment]
Deshabilitado hasta reparación.

**Comment by Malabestia** [comment]
Buenas! Sólo quería saber cómo va la reparación de la spell. Ya van unos cuantos días y no hay visos de que se vuelva a habilitar. ¿?

Mil gracias por todo !

**Comment by ghost** [comment]
No hay visos de fixeos para ningun bug de spells...nadie sabe qué pasa, pero ya van casi 4 semanas sin un fix, y cada vez hay más.

**Comment by paellaencol** [comment]
Lo añado aquí ya que ha sido implementado de nuevo

---

Ejemplo:
Véase ese 80% más de daño gratis que está recibiendo con todo:
1. Destrozar y flagelos de furia <b> sin rugido </b>:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/707/d39h.jpg/'><img src='http://img707.imageshack.us/img707/1946/d39h.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img707.imageshack.us/img707/1946/d39h.jpg
1. Destrozar y flagelos de furia <b> con rugido </b>:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/593/w2w6.jpg/'><img src='http://img593.imageshack.us/img593/3959/w2w6.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>
http://img593.imageshack.us/img593/3959/w2w6.jpg

**Comment by Kiritoo** [comment]
Deshabilitado hasta reparación.

**Comment by searum** [comment]
fix..asi que como @fixx lo deshabilito.. lo va a volver a habilitar por guapete :)
