### ISSUE TITLE
[Misión] Cementerio de Dragones - Medios para un fin

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2394]
http://es.wowhead.com/quest=12240

Sueltas el pote de termintas(http://es.wowhead.com/item=37300) y debería salir el supervisor Kaleiki y lo mates y te completa la misión.

Sueltas el pote de termitas pero no aparece el supervisor Kaleiki.

**Comment by redneo** [comment]
Arreglado
