### ISSUE TITLE
[Misión] Cementerio de Dragones - Tortura al torturador

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2395]
http://es.wowhead.com/quest=12252

Tienes qe torturarle para sacarle información, entonces le tienes qe dar 5 veces con el hierro qe te da la misión(http://es.wowhead.com/item=37314) y despues matarlo.

No funciona la parte de torturarlo con el hierro 5 veces para qe de la información.

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
