### ISSUE TITLE
[Ingeniería] Propulsiones de nitro

### ISSUE THREAD

**Issue by Creamfour** [RoDNet/Bugtracker-Infinium-4.3.4#2397]
Buenas, los propulsores de nitro, incorporados en el cinturón en esta versión de Cataclysm, no está dando el 100% del funcionamiento.

 ID: http://es.wowhead.com/spell=55016/

Cuento lo que ocurre, en Cataclysm, estos propulsores tienen que tener 3 resultados posibles:

 1- Funcionan correctamente y sale el sprint.
 2- Explotan y sales volando, con lo que si no tienes paracaídas mueres en la caída.
 3- Explotan y te quitan 75% de la salud total (si estás a 75% de salud o menos te mata).

El caso es que solo están funcionando las 2 primeras probabilidades, lo que hace mucho más cómodo el uso de este sprint en BG o en cualquier parte, si se necesitan pruebas de peso, dejo aquí 2 posts aleatorios del oficial, donde se puede ver que es la versión de Cataclsym porque nombran prefesiones 525.

Primer post, el más claro:
http://eu.battle.net/wow/es/forum/topic/2098161691

Segundo post, un lio pero pone que te baja 75% de salud (pone 3/4):
http://eu.battle.net/wow/es/forum/topic/2226273154

Espero que se arregle esto pronto, quiero ver a gente explotar :)

**Comment by redneo** [comment]
http://www.wowhead.com/spell=94794

Lo veras.
