### ISSUE TITLE
[Misión] Cementerio de Dragones - Caída en desgracia

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2398]
http://es.wowhead.com/quest=12274

Vestida como una sacerdote, haces sonar la campana y despues vas a hablar con el sumo abad.

Hacer sonar la campana va bien, pero cuando hablas con el sumo abad no te completa la misión.

**Comment by redneo** [comment]
Arreglada
