### ISSUE TITLE
[Spell > Chaman]  Water Shield

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2401]
Escudo de agua
![escudo de agua](https://f.cloud.github.com/assets/3537253/1356172/802915da-3772-11e3-85f9-9653aa341f87.jpg)
http://cata.openwow.com/spell=52127
http://wow.freakz.ro/spells.php?spell=52127

Problema: No funciona la prímera parte del spell, no restaura el mana cada 5 segundos.
Observaciones: La segunda parte del spell funciona bien.

Un saludo.

**Comment by paellaencol** [comment]
Visualmente (hoja de personaje) sí que da esos 531p. de mp5 (con el escudo mejorado). Es un bug visual, o ya funciona?

**Comment by crowel** [comment]
Funciona :)
