### ISSUE TITLE
[Spell > Chaman]  Focused Insight

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#2402]
<b>RESUMEN A TODO LO SIGUIENTE: La siguiente cura realizada tras haber usado un golpe de choque deberia reducirse un 75% del coste de mana del choque que son 4000.
Esto no esta ocurriendo.</b>

Perspicacia Enfocada
![perspicacia enfocada](https://f.cloud.github.com/assets/3537253/1356234/ab76c6d2-3773-11e3-8836-714b2a9f2491.jpg)
http://cata.openwow.com/spell=77796
http://wow.freakz.ro/spells.php?spell=77796

Como dice la descripción tras lanzar un hechizo de choque mi siguente sanación reducira el coste de mana un 75% del coste del choque, en resumen.

Problema:
Para mi prueba utilizo el siguiente choque.

Earth Shock /Choque de tierra http://cata.openwow.com/spell=8042
![choque de tierra](https://f.cloud.github.com/assets/3537253/1356256/1c18441a-3774-11e3-8d00-369f958a1378.jpg)
El cual tiene un coste de mana de 4200 puntos, con lo cual un 75% de su coste serian unos 3000 puntos de mana que tendrían que reducirse a la siguiente sanación que realize por el talento Perspicacia enfocada.

La sanacion que utilizo en la prueba.

Healing Surge /Oleada de sanación http://cata.openwow.com/spell=8004
![oleada de sanacion](https://f.cloud.github.com/assets/3537253/1356291/c19aa4c8-3774-11e3-9163-d0ae3caa1296.jpg)
Que tiene un coste de 6072 puntos de mana, la cual con el talento perspicacia enfocada debe de quedar  en:
6072-3000= 3072 puntos de mana, que era aproximadamente el 75% del coste del choque que se aplica a la siguiente sanación realizada.

Ahora bien y aqui viene el problema, cuando utilizo el choque y me fijo en el coste del siguiente hechizo de curación.

![pers](https://f.cloud.github.com/assets/3537253/1356316/64039b98-3775-11e3-8306-52773bccd277.jpg)
Activo el buffo utilizando un hechizo de choque y cuando me voi a fijar en mi cura.

![pss](https://f.cloud.github.com/assets/3537253/1356370/4ebd02e6-3776-11e3-8c19-8675294e1505.jpg)

¡¡¡ 6144 MANAA !!! FLIPAA en vez de reducirme los 3000 puntos de mana del coste del choque me aumenta el propio coste de mi hechizo de curación a 6144 cuando el hechizo en si tiene un coste de 6072.

Espero que se me entienda bien la explicación porque esto no ocurre solo con esta cura sino con todas, en vez de reducir el coste, ¡¡ nos lo aumenta !! este es uno de los gran problemas por los que no podemos ganar mana los chamanes heal y nos quedamos secos, me llevo un rato reportar esto.

Observaciones: La 2ª parte del talento que aumenta un 30% la siguiente sanación funciona bien.

Un saludo.

**Comment by efectokoleos** [comment]
arreglado
