### ISSUE TITLE
[Festival de Halloween] Bugs y arreglos.

### ISSUE THREAD

**Issue by redneo** [RoDNet/Bugtracker-Infinium-4.3.4#2404]
Para evitar mil BT diferentes vamos a poner aqui todo lo que este bien y todo lo que se vaya arreglando del festival de Halloween.
- Spawns de GObs y NPCs arreglado en gran medida
- Arregladas misiones: 
  http://es.wowhead.com/quest=29376
  http://es.wowhead.com/quest=29377
  http://es.wowhead.com/quest=29075
  http://es.wowhead.com/quest=29371
- Stats el jinete sin cabeza arregladas. Ya es nivel 85 y la vida ronda los 1859000 asi como la cabeza del mismo que tiene una vida de 371.000
- http://es.wowhead.com/npc=53760 Spawneado
- Loot de items http://es.wowhead.com/item=54516 y http://es.wowhead.com/item=37586 reparado
- Items mascaras de los Huargen: http://es.wowhead.com/item=49215, http://es.wowhead.com/item=49215 arreglados, con lo cual ya los venden (cuando caiga el server).
- Cubos de caramelos faltantes de la Horda en Reinos del Este colocados.
- Cubos de caramelos faltantes de la ALIANZA en Reinos del Este colocados.
- Varitas que no funcionaban, ya lo hacen, teoricamente cambiando el aura dependiendo del genero del personaje.
- Item http://www.wowhead.com/item=33808 cambiado por http://es.wowhead.com/item=71326
- Npcs 23537 spawneados para la realización la mision http://es.wowhead.com/quest=11360/ y creo que versión horda
- Npc 51934 colocado para realizar misiones ALIANZA
- Npc http://es.wowhead.com/npc=52497 Alianza situado para la venta de mascaras.
- NPC http://es.wowhead.com/npc=53728 Alianza situado para la venta de items de halloween.
- NPC http://es.wowhead.com/npc=53763#. colocado cerca de entrañas.
- NPC http://es.wowhead.com/npc=15309 movido a Entrañas.
- NPC 37558, para mision de entrañas y ventormenta http://www.wowhead.com/quest=29375 arreglado y spawneado.
- NPC http://es.wowhead.com/npc=54141 colocado en taberna de Orgrimmar
- NPC http://es.wowhead.com/npc=53949 spawneado en ventormenta
- NPC http://es.wowhead.com/npc=52548 puesto en las afueras de ventormenta.
- Cubos de caramelos de la horda en Kalimdor colocados.
- Arreglado Mascota Familiar felino
- NPCs http://www.wowhead.com/npc=53756 y http://www.wowhead.com/npc=53702 puestos para la venta de varitas.
- Terminado de poner los cubos de caramelos alianza que faltaban y testados respecto a la foto de crowel.
- Misiones http://es.wowhead.com/quest=11219 http://es.wowhead.com/quest=11131 arregladas, 20% de que al apagar un fuego cuente.
- Cadena de mision http://es.wowhead.com/quest=29392 arreglada y testada, en la horda tendria que funcionar.

**Comment by Kleinn** [comment]
Varita sacralizada: Aleatorio
http://es.wowhead.com/item=20413
Esta varita no funciona.

**Comment by crowel** [comment]
(Alianza)
Gertrude Hondopantano http://es.wowhead.com/npc=52548

Este npc necesario para la misión, ¡Bombas fétidas al por mayor! http://es.wowhead.com/quest=29054
debe de entregar una escoba voladora con la cual se debe ir a entrañas y lanzar bombas fetidas sobre entrañas y no las esta entregando las escobas.

**Comment by Wiinter** [comment]
Los cubos de caramelos aunque los hayas hechos los años anteriores, te deberían volver a dejar cogerlos. Te deberían dejar cogerlo una vez al año.

**Comment by Wiinter** [comment]
No está la calabaza de la Caverna Tenebrosa en Profundidades Abisales en Vash'ir (Horda)

**Comment by paellaencol** [comment]
Como recompensa tras acabar con el jinete, puede caer la siguiente espada "Sable siniestro de El Jinete" http://es.wowhead.com/item=71325 , el problema es que actualmente está tirando la versión de nivel 70 TBC "La espada de El jinete" http://es.wowhead.com/item=38175

**Comment by RaulioWoW** [comment]
hola, actualmente las misiones para la alianza  http://es.wowhead.com/quest=29054  y   http://es.wowhead.com/quest=29144  no estan funcionando, podrian por favor ver ese tema? Algunos afirman que funcionaron un par de veces, pero ya no lo hacen, saludos.
