### ISSUE TITLE
Dedos de escarcha-Mago frost

### ISSUE THREAD

**Issue by Santateresa** [RoDNet/Bugtracker-Infinium-4.3.4#2405]
He estado probando el hechizo (18/10/2013) y aun no esta fixeado ni mucho menos, dedos de escarcha hace que lanza de hielo y congelación profunda actúen como si el objetivo estuviese congelado, lo que para congelacion profunda significa que gastaría una carga en el stun, lo cual está funcionando correctamente, el problema viene con el daño de lanza de hielo, el cual es el hechizo clave en el daño del mago frost, los dedos de escarcha se supone que al gastar cada una de las cargas con lanza el objetivo debería recibir daño no solo como si estuviese congelado, si no a demás un 25% mas por el bufo que le da de daño a lanza de hielo el tener dedos de escarcha, bueno pues no solo no ganas la bonificación del 25% de daño, si no que a demás lanza de hielo hace el mismo daño que si el objetivo estuviese sin congelar, es decir tenerlos y no tenerlos es lo mismo vas a hacer el daño base con lanza de hielo y la diferencia es bestial, con 7581 de poder con hechizos hago 4300 de daño medio con lanza de hielo a objetivos sin temple, con el objetivo congelado el daño aumenta a 11000, con dedos de escarcha debería ser estos 11000 de estar congelado más el 25% del bufo de los dedos de escarcha, el resultado... 4300 puntos de daño exactamente igual que si el objetivo estuviese sin congelar. Más importante aun, el talento congelar mejorado da al hechizo congelar del elemental el 100% de probabilidad de otorgarte 2 cargas de dedos de escarcha, lo que traducido en 2 lanzas de hielo sería un daño igual a dos veces 11000+25% de media sin critico, pero... sorpresa la mía cuando resulta que la primera carga de dedos de escarcha gastada con lanza no solo no hace el daño que debería si no que...NI SIQUIERA HACE DAÑO!!! y la segunda lanza hace los 4300 de daño como si la tirases sin mas, es decir el mago frost está perdiendo como poco 22000 de daño cada 15 segundos eso sin contar que la mayoría de los impactos con congalación son criticos ni el 25% mas del bufo lo que daría una barbaridad de daño, por favor arreglen esto de verdad, se que es difícil pero sin ello los magos frost estamos vendidos en cuanto a dps y en pvp contra otras clases se nota muchísimo este daño extra que a demás es sin castear lo que da muchisima ventaja.
Muchas gracias por la atención y mucha suerte con ello, un saludo.

**Comment by Wiinter** [comment]
#2237

**Comment by Sagittariu5** [comment]
Pues a mi me han metido 18k con Descarga de escarcha teniendo 4k de temple no están tan mal tampoco :)

**Comment by paellaencol** [comment]
Bueno, más bien seria repasar la descripción que di aquí; https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1616

**Comment by Santateresa** [comment]
descarga de escarcha está bien oscar si el problema es lanza de hielo con dedos de escarcha, que es daño sin castear, descarga de escarcha es un casteo de 2 segundos que para pvp es un suicidio hacer eso, es interrumpible de mil maneras

**Comment by Kiritoo** [comment]
Seguimos del 2237
