### ISSUE TITLE
hola ...!!

### ISSUE THREAD

**Issue by mikichu** [RoDNet/Bugtracker-Infinium-4.3.4#2407]
Buenas tardes .. quiero hacerle saber el PNJ de esta misión  [El Roble Quejumbroso] no se encuentra en el lugar especifico no se si me pueden ayudar con eso ya q necesito completar las misiones del gilneas xfa.....
Me despido esperando su respuesta ..

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
