### ISSUE TITLE
[Sacerdote] Palabra de poder: barrera

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#241]
Hola.
Palabra de poder: barrera 
http://es.wowhead.com/spell=62618

El problema de esta habilidad es que al utilizarlo y meterte dentro, sin tener el glifo puesto te aparece como si lo tuvieras.
![wowscrnshot_070613_165725](https://f.cloud.github.com/assets/3537253/758090/95a74254-e710-11e2-9448-98d65bb62839.jpg)

![wowscrnshot_070613_171248](https://f.cloud.github.com/assets/3537253/758091/a8f1a304-e710-11e2-8ddf-4b7b430d2987.jpg)

http://www.wowwiki.com/Glyph_of_Power_Word:_Barrier
Pongo enlace del glifo en wowwiki ya que no encuentro ni en wowhead ni en old.wowhead el que tenemos en la versión.

Un saludo.

**Comment by searum** [comment]
fix
