### ISSUE TITLE
Fenix Oscuro Bug

### ISSUE THREAD

**Issue by plopxer** [RoDNet/Bugtracker-Infinium-4.3.4#2413]
Buenas gms.. les queria Exponer el caso de que la montura de el Fenix oscuro 
la cual se compra con la guild.. Esta bug..
la puedes comprar y todo pero no se puede usar al intentar usarla te da aviso de aun no puedes usar esto 
porfavor Arreglenla lo mas pronto posible me gusta mucho esa montura

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
