### ISSUE TITLE
Reputacion ala Abysal bug

### ISSUE THREAD

**Issue by plopxer** [RoDNet/Bugtracker-Infinium-4.3.4#2414]
gms la presente Nota es para darles aviso de que La Reputacion con ala abysal esta bug hasta ahora parece ser solo con los draneis y gnomos.
al lelgar a exaltado no Podemos comprar la montura de los dracos..
los npcs aparecen Agresivos

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
