### ISSUE TITLE
[Halloween](Logro) Rabia C.H.U.C.H.E.G.

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#2415]
Logro: http://es.wowhead.com/achievement=1261

Bug: Con mi Pj Velcositro el logro me sale con el contador en 10/10 (supongo que de eventos anteriores porque al parecer antes el objetivo era 50 y no 10) y sin embargo no me aparece como completado, quisiera que me dieran el logro en mi Pj o que me reiniciaran el contador para poder completarlo.

Había puesto un ticket y me dijeron que lo pusiera aquí y que lo arreglarían lo más pronto posible. Gracias de antemano.

**Comment by crowel** [comment]
Es de tu pj, el logro se hace perfectamente.
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2404

**Comment by Velcositro** [comment]
@crowel Gracias por aclararlo, entonces solo queda esperar a que me lo arreglen.

**Comment by redneo** [comment]
teoricamente arreglado a ti y a todos los que tenian mas de 9.

**Comment by Velcositro** [comment]
@redneo Entré y pude completarlo, muchas gracias.
