### ISSUE TITLE
Sholazar Basin Misiones

### ISSUE THREAD

**Issue by sleepyhouse** [RoDNet/Bugtracker-Infinium-4.3.4#2416]

**Comment by sleepyhouse** [comment]
http://www.wowhead.com/quest=12589

Dispara la pistola, pero ya no completa la mision.

http://www.wowhead.com/quest=12644/

Al npc que hay que hablarle para que se complete la mision ya no te deja, osea que es incompletable.

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
