### ISSUE TITLE
[Arenas]Puntos de conquista

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#242]
Hola quiero comentar que los puntos de conquista al ganar arena me parecen un poco elevados.
Estabamos testeando y tras ganar nos fijamos que nos daban x230 por victoria.
Cosa que me parece extraña y más con los rates que tenemos actualmente pero vete tú a saber jejeje.

![wowscrnshot_070613_171448](https://f.cloud.github.com/assets/3537253/758098/81e4d8d4-e711-11e2-9273-948a6db7e788.jpg)
![wowscrnshot_070613_172019](https://f.cloud.github.com/assets/3537253/758099/8b4cdfa2-e711-11e2-97ea-0d0fe78c48b7.jpg)

Un saludo.

**Comment by lamaza** [comment]
Cuantos deberian dar entonces? quede en las mismas.

**Comment by ghost** [comment]
Según las notas del parche 4.1 deberían de ser 180 puntos.
http://eu.battle.net/wow/es/blog/9984237/

> Se ha regulado la cantidad de puntos de conquista que se obtienen al ganar arenas. Ahora los jugadores >recibirán 180 puntos de conquista por una victoria hasta alcanzar el límite semanal, independientemente del >índice y del emparejamiento.

Busque en las notas del parche 4.2 y 4.3 a ver si cambiaron eso, y no.
