### ISSUE TITLE
[Tier 11 Heler/Paladin ] Beneficio por 4 piezas

### ISSUE THREAD

**Issue by Ceslick** [RoDNet/Bugtracker-Infinium-4.3.4#2421]
Descripción:
Bonificación de conjunto
Tener puestos mas objetos de este conjunto le aplicará una bonificación a tu personaje.
2 piezas: Aumenta un 5% la probabilidad de golpe crítico de tu hechizo Luz Sagrada.
4 piezas: Otorga 540 p. de espíritu durante 6 s tras lanzar Choque Sagrado.

Bug:El beneficio de 4 piezas del tier 11(http://es.wowhead.com/itemset=933) funciona mal, el buffo Radiante(http://es.wowhead.com/spell=90313) solo deberia de saltar con Choque sagrado(http://es.wowhead.com/spell=20473) pero esta saltando con todas las sanaciones (incluido impsición de manos)

![captura de pantalla 2013-10-19 a las 18 44 17](https://f.cloud.github.com/assets/5348961/1366658/6e9c1620-38dd-11e3-8aa6-5f8b24b8a571.png)

![captura de pantalla 2013-10-19 a las 18 44 18](https://f.cloud.github.com/assets/5348961/1366677/a0939e82-38dd-11e3-80e9-36f28c31acbf.png)

**Comment by Kiritoo** [comment]
Esto esta arreglado.

**Comment by Kiritoo** [comment]
Vale este es el T11, el arreglado es el T12, reabro y lo revisamos.

**Comment by efectokoleos** [comment]
arreglado
