### ISSUE TITLE
[Tier 11 DPS/Paladin]Beneficio 4 piezas

### ISSUE THREAD

**Issue by Ceslick** [RoDNet/Bugtracker-Infinium-4.3.4#2422]
Descripción:
Bonificación de conjunto

2 piezas: Aumenta un 10% el daño infligido por tu facultad Veredicto del templario.
4 piezas: La duración de tu facultad Inquisición se calcula como si tuvieses un Poder Sagrado extra.

Bug:El beneficio de 4 piezas del Tier 11 DPS del Paladin(http://es.wowhead.com/itemset=932) no funciona actualmente. La cuarta pieza deberia de calcular el tiempo de inquisición(http://es.wowhead.com/spell=84963) con 1 carga más de poder sagrado(buffo:http://es.wowhead.com/spell=90299) pero no cuenta esa carga extra, solo usa las que tienes.

![captura de pantalla 2013-10-19 a las 18 42 06](https://f.cloud.github.com/assets/5348961/1366725/0452e700-38e0-11e3-8c54-42f20fd489cd.png)
![captura de pantalla 2013-10-19 a las 18 42 42](https://f.cloud.github.com/assets/5348961/1366724/043c6962-38e0-11e3-9144-667424e9c71d.png)

**Comment by efectokoleos** [comment]
arreglado
