### ISSUE TITLE
Mision (Un'goro), Un aroma irresistible para Lar'korwi

### ISSUE THREAD

**Issue by kalarjan** [RoDNet/Bugtracker-Infinium-4.3.4#2425]
Nombre: Un aroma irresistible para Lar'korwi.
Descripción: Tengo que conseguir glándulas de feromonas que las dan las hembras al acercarme a sus huevos.
Problema: Por mucho que me acerque a los huevos no sale ninguna hembra que me ataque como deberia pasar.

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by Inmershus** [comment]
Esto ya lo reporté yo, pero me dijeron que habían puesto 4 npcs y que la quest se podía hacer, pese a que no se haría así.

**Comment by ghost** [comment]
Exacto, hay NPCs que te permiten hacer la misión.
