### ISSUE TITLE
Misión(Páramos de Poniente) Una visión del pasado

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#2426]
Nombre: Una visión del pasado

Descripción: Entra en la Ladronera de los Defias y sigue a los vagabundos hasta la mazmorra de las Minas de la Muerte. Entra en la misma y utiliza el quemador de incienso para ver el pasado.

Fallo: al entrar en la mazmorra y usar el objeto necesario dice que no es la zona donde se usa, cuando sí lo es.

Observaciones: quizá el bug es del item y no de la quest.

ID Quest: http://es.wowhead.com/quest=26320
ID Item: http://es.wowhead.com/item=58147

**Comment by Kiritoo** [comment]
Fix
