### ISSUE TITLE
[hechizos] palabra de gloria + proposito divino = cura over

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#2427]
Primero que nada quiero decir que este bug se usa al combinar 2 hechizos + las cargas sagradas del paladin de 0 a 2. Con 3 cargas el bug no funciona ( no se reproduce).

Segundo decir que ya en el juego el paladin meybon sabia del bug y no lo reportó y yo que ni tenia idea, me ha dicho que yo lo usaba, pero me puse a probar con los muñecos y si funcionó.

IDs: 

86172 proposito divino http://es.wowhead.com/spell=86172/
85673 palabra de gloria http://es.wowhead.com/spell=85673/

---

Primer  paso

Tener 0, 1 o 2 cargas de poder sagrado.

Segundo paso

Hacer que te salte proposito divino (pegando)

tercer paso

Usar palabra de gloria con el propositivo divino y la cantidad de  cargas dichas.

Como yo veo la situacion:

Cuando me curo usando palabra de gloria con 1 carga, me sana mas o menos 5k, con 2 cargas es 10k y con 3 cargas 15k.

Pero cuando se utiliza mediante el bug de los hechizos, es como si cada carga valiera por 3 asi:

Curando con bug

0  cargas = sana 15k

1 carga= sana 30k

2 cargas= sana entre 40 y 60k

3 cargas = 10k (Lol! si, 10k)

Efectos criticos me han mostrado sanaciones de más de 80k.

Estas sanaciones para que se sepa tambien, son posibles con el paladin reprension pero siemprey  cuand oeste low health 25%) o por ahi, eso si apoyandose en alas y con 3 cargas. (obviamente sin el bug).

Entonces para resumir, al reproducir el fallo, la palabra de gloria cuenta de 0 - 1 y 2 cargas como si fuesen en realidad:

0 = 3 cargas
1= 6 cargas
2= 9 cargas

**Comment by Wiinter** [comment]
Si quieres denunciar a alguien no lo pongas aqui, ese tipo de comentarios sobran en el bugtracker.

**Comment by meybon** [comment]
increible xD no hay ni un solo pala con 2 dedos de frente que no sepa de esto o que tiene 4 kilometros de cara para no admitirlo, has visto a otro pala que no sea yo diciendo como funcionaba el bug? no sabias nada,... no lo reporte cierto, ni tenia ganas ni abusaba de ello, tenia la esperanza que uno de los ke abusais de ello todo el rato tuvieseis dignidad para hacerlo, quieres que me baneen por ello? pues que baneen a todos los guerreros que se callaron la ira y el golpe de la victoria tambien y al resto de paladines que se lo callaron empezando por ti.
tu abusas de ello, yo no, y tu te jactaste de decir hoy que eso es normal que me fuese a mirar guias que eso iba bien y blablabla, ahora ya esta bug? porque ahora si? porque aprovechas para acusarme? increible lo patetico que eres.
si tienes problemas conmigo me lo dices ami no vayas haciendo bobadas por aqui o por el general que madre mia chaval cada dia te luces mas.

**Comment by Fragis** [comment]
En el fondo es todo un halago esa acusacion, porque Mey no bugea ni diciendoselo, lo cual refleja la rabia que te da la facilidad con la que te mata, así que Mey alegrate, de todos los Paladines has sido tu al que han intentado derrocar. /clap

**Comment by lamaza** [comment]
Para mi es 1 don nadie XD, al igual que los que vinieron a defenderlo aqui.

**Comment by Ceslick** [comment]
El bug tracker no es ni para denuncia ni para discutir. Lamaza si quieres denunciar hazlo en el foro si esque tienes pruebas

**Comment by Dekadencee** [comment]
Tenemos el spell medio fixeado, ahora en cuanto vuelva mi equipo de cenar, lo terminamos.
Ya hemos localizado el error de la cura over, y lo del glifo ya lo hemos arreglado para que solo salte con el glifo.

Un saludo ^^

**Comment by Dekadencee** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2511
Fixeado ^^
