### ISSUE TITLE
Sacerdote - Fuego Interno

### ISSUE THREAD

**Issue by Fragis** [RoDNet/Bugtracker-Infinium-4.3.4#2428]
Cuando se activa fuego interno, aumenta con normalidad los parametros de SP (532 o algo asi) Lo que pasa es que si lo desactivas malualmente o activas Voluntad interna, el daño por hechizos se reduce en 1064 y la sanacion en 532, con lo cual la sanacion vuelve a su estado normal y el daño con hechizos merma 532.

Si despues de eso activas otra vez Fuego Interno, la sanacion sube 532 y el daño con hechizos aumenta 1596 (mas o menos ) con lo cual el daño esta aumentado 532 mas que la sanacion.

Spell = 588

**Comment by Wiinter** [comment]
Fragis pon esto en tu post : http://wow.freakz.ro/spells.php?spell=588

**Comment by paellaencol** [comment]
Iba a reportar esto hace ya bastante tiempo, pero luego me di cuenta que al primer proceso del arma o del abalorio que te aumente el poder con hechizos este déficit/incremento se corrige. Por lo tanto este problema solo dura unos pocos segundos, y ni siquiera renta que alguien intente hacer esto para bugearlo y aumentar su daño con hechizos, ya que perdería mas tiempo con los GCD que lo que ganaría en daño.

**Comment by efectokoleos** [comment]
entonces esta bug o que hago? xd

**Comment by paellaencol** [comment]
No sé si ya habréis tocado algo, pero el problema está solucionado.

**Comment by efectokoleos** [comment]
cierro pues
