### ISSUE TITLE
Mision: [Darnassus]  El Roble Quejumbroso

### ISSUE THREAD

**Issue by dcmuerte** [RoDNet/Bugtracker-Infinium-4.3.4#2429]
Nombre: El Roble Quejumbroso

Descripcion: Gwen y Cringris están en la ciudad, en el Roble Quejumbroso. Deberías pasar por allí. Coge el portal que está bajo el árbol que queda al norte de aquí y después busca el Roble Quejumbroso en la zona norte de la ciudad.

Fallo: El npc al que tienes que entregar la mision no esta.

ID Quest:http://www.wowhead.com/npc=48736

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
