### ISSUE TITLE
[DK-Sangre]Golpe letal

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#2430]
http://wow.freakz.ro/spells.php?spell=49998-->Golpe letal (sin talentos ni glifo)
Con el talento de golpe letal mejorado aumenta el daño un 120%, por lo que el daño total de golpe letal es 270%, y mas o menos con mi equipo
![image](https://f.cloud.github.com/assets/3939699/1368398/4238f778-399c-11e3-917a-c4c5d07672b0.png), debe pegar 15,795. Sin embargo (y esto nose porque aparece), en la descripcion pone que debe pegar un 330% y, ese 60% de mas no lo encuentro del porque, pero bueno, el caso esque pego 24k como se puede ver.
![image](https://f.cloud.github.com/assets/3939699/1368407/c381f870-399c-11e3-9878-5a4c25296f6c.png)

**Comment by searum** [comment]
fix
