### ISSUE TITLE
Error de Herreria

### ISSUE THREAD

**Issue by perrak21** [RoDNet/Bugtracker-Infinium-4.3.4#2431]
http://es.wowhead.com/skill=164#recipes:600+16+1

He visto un post con el mismo problema pero no hay solucion.
Me sale un error al intentar crear guanteletes de pirium sañoso y el ornamentado sañoso y lo mismo con el cinturon y las botas.
Para poder subir herreria necesito hacer esos objetos pero me dice:
Este hechizo no esta disponible para ti.
Quisiera saber si hay solucion.
Gracias

**Comment by elmiriox15** [comment]
No es un error, están bloqueados todo tipo de items de profesión de nivel 377 porque no son de esta temporada.

**Comment by perrak21** [comment]
ok thx
