### ISSUE TITLE
Misión Infralar - Sin capitán ni tripulación

### ISSUE THREAD

**Issue by oscurodani** [RoDNet/Bugtracker-Infinium-4.3.4#2433]
La misión seria Sin capitán ni tripulación link wowhead: http://es.wowhead.com/quest=26427#.

Problemas sobre los objetos que necesitas para completar la misión es lo siguiente: 1- objeto requerido Botella de Whisky 2- objeto requerido Bobina de cuerda.

Subes al barco te pones a buscar los objetos uno se trata que esta en la bodega y el otro esta en la punta del barco. Dicho problema es que no se mueven con el barco se quedan flotando en el aire. Si los intentas coger...... te caes de la montura aparte de que no coges el objeto y mueres.....

Imagen de los objetos flotando: http://www.subirimagenes.net/i/131021024507906717.jpg

Espero que sea de ayuda.

**Comment by redneo** [comment]
Estan puestos por el suelo, cerca de los npcs que tienes que rescatar en una mision posterior.
