### ISSUE TITLE
[Brujo] Pandemia

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2438]
http://wow.freakz.ro/spells.php?spell=85099 -> Rango 1(50% que refresque)
http://wow.freakz.ro/spells.php?spell=85100 -> Rango 2(100% que refresque)

Your Drain Soul has a 100% chance to refresh the duration of your Unstable Affliction spell when dealing damage on targets below 25% health.

El problema es que no refresca afflicción inestable. Debe resfrescarlos cada vez que hace un tick porque es cuando hace daño, no al caster

**Comment by nicerdicer** [comment]
Me parece que ese talento el funcionamiento real es mas bien similar a Aflicción eterna, es decir renueva el efecto en el momento que entra Drenar Alma... Aun que de no ser asi, casi es preferible mi versión que el hecho de que se renueve con cada tick de daño, puesto que Inestable inflige mas daño conforme pasa el tiempo, si se renueva todo el rato el daño seria todo el rato como el del segundo 1... Pero que vamos no se hecha de menos, si tienes una buena rotación, Afliccion Inestable y Poseer no se deberian ir nunca... por que Drenar Alma despues de todo estas obligado/a a cortarlo para renovar Poseer y con este renovar tambien Abrazo de las Sombras y Corrupción, asi que realmente beneficia el hecho de que Drenar Alma actue al primer contacto y no al primer tick, de ser asi apuesto que Inestable la perderiamos mas de 1 y mas de 2 veces, ya que tiene muy poca cadencia...

Un Saludo!!

**Comment by Wiinter** [comment]
Mi rotación está hecha de tal forma que no me importa qe se renueven los ticks porque los daños se efectuan cada 3 segundos díria, entonces siempre le hace daño y siempre se beneficia de los ultimos buffos qe tenga. Aunqe tambien puede ser malo, eso depende de cada uno. 
Nicer simplemente me ciño a lo que pone en el talento, cuando hace daño refresca, y eso no lo hace, pero gracias por tu aportación. Si descubres que no tiene que ser asi, ponlo, porque puede ser que me haya equivocado.

**Comment by ghost** [comment]
Ahora ni siquiera reinicia la duración, no ocurre nada al tirar drenar alma ni al hacer el tick de daño.

**Comment by searum** [comment]
fix
