### ISSUE TITLE
Cubo de caramelos Inexistente. (Halloween)

### ISSUE THREAD

**Issue by TFK13** [RoDNet/Bugtracker-Infinium-4.3.4#2439]
Hola, aquí les dejo unas fotos:

http://imageshack.us/photo/my-images/849/03vc.jpg/

http://imageshack.us/photo/my-images/809/49ah.jpg/

Solo falta ese cubo, para poder completar todos los logros íntegros, Gracias de antemano.

Un cordial saludo

Att: Budha

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2404
