### ISSUE TITLE
Misión [Dun Morogh] Las artes del pícaro

### ISSUE THREAD

**Issue by Micloroch** [RoDNet/Bugtracker-Infinium-4.3.4#2440]
Nombre :Las artes del pícaro

Enlace:  http://es.wowhead.com/quest=26207/las-artes-del-picaro

Descripción : Hay que golpear tres muñecos de prueba con el esvicerar del pícaro.

Problema : Al golpear al muñeco de pruebas no te cuenta en la misión.

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
