### ISSUE TITLE
Paladin, Glifo de la gran palabra

### ISSUE THREAD

**Issue by meybon** [RoDNet/Bugtracker-Infinium-4.3.4#2443]
#1706 Este bug estaba arreglado y ha aparecido otra vez. No pongo ids en este ya que al ser repetido esta en otro post todo explicado y tal.

**Comment by Drogoth2** [comment]
Este bug ha reaparecido y, ahora las curas del paladin con palabra de gloria vuelven a ser inferiores (aún mas) de lo que eran antes.

**Comment by Dekadencee** [comment]
Fixeado
