### ISSUE TITLE
[Banda: Bastión Crepuscular] Puertas de acceso al Consejo de Ascendientes

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2445]
Enlace de la estancia: http://es.wowhead.com/zone=5334
Enlace de bosses del segundo encuentro: http://es.wowhead.com/npc=45992 http://es.wowhead.com/npc=45993
Enlace del último boss del consejo del tercer encuentro http://es.wowhead.com/npc=43735/monstruosidad-de-elementium

Descripción de nuestro problema: Tras haber acabado con los dos bosses del segundo encuentro, nos dirigimos al tercero, donde murimos. Al liberar e intentar volver a entrar para resucitar y seguir intentando derrotar a este boss, nos encontramos con un primer problema: no se puede entrar a la estancia porque "está sucediendo un encuentro".
Al dia siguiente al entrar con un GM ya se podía entrar correctamente a la estancia, pero sucedió otro problema. Las puertas de acceso al tercer boss estaban cerradas.
Curiosidades mientras sucedía este problema: nada más poder volver a entrar aparecieron los diálogos iniciales de entrada; al llegar a la camára del primer boss, aparecieron los diálogos del primer jefe, y lo mismo ocurrió al llegar al segundo.

Tal vez guarde alguna relación con: 
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2412
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2411
y más que probablemente con https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1989

Creo que debe ser un problema interno de las ids que aceptas al registrarte en una estancia de banda.

**Comment by Wiinter** [comment]
Lo mismo nos ha pasado hoy.

**Comment by paellaencol** [comment]
Con fecha de 29/10 al tirarlo a la primera no nos ha dado ni loot, ni ha contado para el logro.

Además antes de iniciar el jefe nadie que no estuviera dentro de la estancia en ese momento le permitia entrar, les ocurria lo mismo que la semana pasada "está sucediendo un encuentro", cuando nadie de nosotros estaba en combate, nos ha tocado tirarlo con 9

P.S. Las skills de los bosses funcionan bastante bien, todos los npcs hacen sus habilidades, es entretenido.

**Comment by Wiinter** [comment]
Entonces puede ser problema de que el encuentro de Valiona y Theralion no acaba correctamente

**Comment by paellaencol** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2980

**Comment by searum** [comment]
esto deberia de estar mas que resuelto
