### ISSUE TITLE
[Glifo-Cazador]Glifo de disparo mortal

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#2446]
Nombre: Glifo de disparo mortal
Enlace: http://wow.freakz.ro/spells.php?spell=63067
Descripción: Si Disparo mortal no mata al objetivo, el tiempo de reutilización se reinicia instantáneamente pero no se puede reiniciar más de una vez cada 6 sinstantáneamente pero no se puede reiniciar más de una vez cada 6 s.
Problema: El glifo no sirve.
Observación: Había el reporte antes, y se menciona que ya ha sido reparado, pero el glifo sigue sin funcionar.

**Comment by ghost** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1840

**Comment by Kiritoo** [comment]
Arreglado falta compilar.
