### ISSUE TITLE
[Glifo-Cazador]Glifo de asustar bestia

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#2447]
Nombre: Glifo de asustar bestia
Enlace: http://wow.freakz.ro/spells.php?spell=57902&name=glyph-of-scare-beast
Descripción: Reduce el retroceso sufrido por ataques mientras lanzas Asustar bestia
Problema: No reduce retroceso alguno, de hecho la misma habilidad Asustar bestias tienen un retroceso muy grande al recibir golpes, de tal manera que un simple golpe de una mascota y de un druida corta todo el casteo, sin hacer retroceso alguno, simplemente lo corta. En ese sentido el glifo es inútil pues no ayuda en nada a la ya de por sí dañada habilidad Asustar bestia.
Observación: Sucede lo mismo con as habilidades de casteo del cazador: disparo de cobra, disparo firme. Las cuales son cortadas por un golpe de cuerpo a cuerpo, sin haber retroceso, simplemente son cortadas.

**Comment by Sagittariu5** [comment]
Ese y el de revivir que lo reduce 100% son indispensables lastima que no funcionen :(

**Comment by Jhovanni** [comment]
Cierro issue, los casteos han mejorado luego del arreglo que hicieron en retrocesos
