### ISSUE TITLE
[Talento-Cazador]Espadas reflejantes

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#2448]
Nombre: Glifo de disparo mortal
Enlace: http://wow.freakz.ro/spells.php?spell=83495
Descripción: Al ser atacado con un hechizo mientras estás en Disuasión, tienes un 100% de probabilidad de reflejarlo contra el atacante.
Problema: No funciona, los hechizos al estar en disuasion teniendo estos talentos, son desviados, pero no son reflejados hacia el caster.

**Comment by ghost** [comment]
Extraño...a mi me reflejaban y no hará más de un mes de ello. Se habrá vuelto a bugear..

**Comment by paellaencol** [comment]
Hace un par de días me reflejaron un hechizo también a mi

**Comment by Jhovanni** [comment]
Pues yo he estado jugando con supervivencia y no había reflejo. Sobre todo se me hizo muy visual contra magos y brujos pues sus hechizos se desviaban en vez de reflejarse. Ahora he quitado el talento hace unos cuatro días, probaré de nuevo por si algún cambio se ha hecho.

**Comment by Kiritoo** [comment]
Esto está funcionando, si encuentras algún fallo en concreto se más especifico.
Saludos, cierro.
