### ISSUE TITLE
[Hechizo-Cazador]Disparo firme/de cobra, Asustar bestia

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#2449]
Nombre: Glifo de disparo mortal
Enlace:
http://es.wowhead.com/spell=56641/
http://es.wowhead.com/spell=77767
Descripción: (El problema no tiene que ver con las descripciones de las habilidades, por lo cual no las anoto)
Problema: Estas habilidades son cortadas al recibir un golpe cuerpo a cuerpo, no reciben retroceso, son cortadas directamente aún cuando el golpe sea recibido cási al final del casteo.
Observación: Las otras habilidades de casteo del cazador (Disparo de puntería, Revivir mascota, Retirar mascota) no las he probado en combate, por lo cual no se si sucede lo mismo. Es muy probable que es problema sea que la cantidad de retroceso sufrida al recibir golpes sea muy alta, por lo cual interrumpe el casteo totalmente (lo cual sucede a menudo en jugador contra jugador), por lo cual lo que habría que arreglar sea el porcentaje de retroceso que se sufre al recibir golpes. En ésa línea, el Glifo de Asustar bestia quedaría solucionado al mismo tiempo muy posiblemente (reportado en https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2447)

**Comment by ghost** [comment]
Searum dijo que probablemente se debiera a algún talento, más que a un problema de retrocesos en el casteo en general, pero no sé, cuestion de ir probando talento por talento si no es por lo que expones arriba.

**Comment by Jhovanni** [comment]
Pues hice pruebas con un cazador, y nos pasa lo mismo en las tres ramas. Probaré sin talento alguno, para confirmar definitivamente, pero como ya he probado con las tres ramas y la combinación de talentos no ha sido la misma, es poco probable que sea un talento en específico. Para que fuese un talento tendría que ser de los iniciales, y el único que había compartido en esas tres builds de prueba es el primer talento de supervivencia, el cual aumenta el aguante.

**Comment by Sagittariu5** [comment]
Sucede en todas las ramas :p probado, por cierto creo que deberíamos probar SV porque creo que está haciendo un daño excesivo me metieron 40k llevando 12 piezas impla es decir más de 4k de temple. :d

Edito: son todos las spells casteables que posee el cazador  que sufren de este problema.

**Comment by searum** [comment]
mal reportado no me entero de nada.

**Comment by Wiinter** [comment]
Searum es el fixeo que has realizado aqui #2348 

Por tanto, fix!
