### ISSUE TITLE
Reforjas

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#245]
Primero pongo esto, este bug que explicare a continuación, NO me sucedía los primeros días que el server pasó a la versión 4.3.4, creo que este problema apareció luego de las primeras correcciones implementadas.

Bueno, basicamente reforjar el equipo no te da los stats correctamente, o si los hace, al reloguear te cambia algunos stats, este errror ya sucedía en la versión anterior.

La única forma de evitar que tu pj se quede "para siempre" con los stats mal puestos es quitar todas las reforjas que hiciste, quitarte todo el set, reloguear y tendras los stats normales como deberías tener.

Para la prueba, reforje todo lo que podía a celeridad y lo hice sin talentos.

Aclaro que este bug NO es VISUAL.

En esta imagen, tengo mis stats "basicos" como debería, sin set.
![wowscrnshot_070713_105044](https://f.cloud.github.com/assets/4663665/758168/8ec0f270-e718-11e2-8974-670254594b4c.jpg)

Aquí, me he puesto todo mi set (sin reforjas).
![wowscrnshot_070713_105218](https://f.cloud.github.com/assets/4663665/758170/a1ae3c1c-e718-11e2-8e51-bdc50de5aba5.jpg)

Aquí, tengo el set con las reforjas recien hechas
![wowscrnshot_070713_105403](https://f.cloud.github.com/assets/4663665/758172/b0aa4e68-e718-11e2-80eb-9ce100f44b36.jpg)

Reloguee (con todo mi set reforjado puesto).
![wowscrnshot_070713_105422](https://f.cloud.github.com/assets/4663665/758177/f25d9496-e718-11e2-98a6-a6426a49f085.jpg)

Ahora me quito todo mi set, y se puede apreciar que los stats varian a la primera imagen.
![wowscrnshot_070713_111424](https://f.cloud.github.com/assets/4663665/758178/02c9a7b6-e719-11e2-89f5-26192a1ecb15.jpg)

Luego de reloguear (sin tener el set puesto), volvi a tener mis stats normales como la primera imagen, y me puse todo el set (reforjado).
![wowscrnshot_070713_111454](https://f.cloud.github.com/assets/4663665/758180/34a30750-e719-11e2-9a8a-7f0d9713f29e.jpg)

**Comment by Alfonn** [comment]
Buen reporte, pero ya está aquí aunque con menos información , https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/221 .

**Comment by ghost** [comment]
Gracias Alfonn, pero igual dejo este reporte abierto, está mejor que ese feo reporte xd.

**Comment by Dekadencee** [comment]
Seguimos desde el reporte anterior, gracias por la información añadida #221
