### ISSUE TITLE
Drop de perla  negra  para  subir encantamiento

### ISSUE THREAD

**Issue by sufurazo** [RoDNet/Bugtracker-Infinium-4.3.4#2451]
Según el wowhead se  encuentra en  las  almejas  de boca grande y habré abierto  mas  de 200 y nada solo salen perlas de oro e iridiscente.Sin la perla negra nadie podrá hacer la vara de  veraplata que se necesita para subir encantamiento.

**Comment by redneo** [comment]
Podias ponerme al menos la direccion de wowhead de la perla para poder mirarlo?

**Comment by melcalla** [comment]
no esta bug , y los rates estan bien, en tanaris limpia toda la costa , gigantes , cangrejos , y tortugas y sale

**Comment by sufurazo** [comment]
ok ya la tengo,  gracias por vuestra colaboración
