### ISSUE TITLE
[Misión] Corona de Hielo - Nuevos reclutas

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2454]
http://es.wowhead.com/quest=13143

Tienes que llevar a un acechador agil(http://es.wowhead.com/npc=30894) hasta el alto del Sufrimiento, mediante la utilizacion de el sigilo de la Espada de Évano, que te permite controlarlo.

No hay ningun acechador agil por la zona, por tanto no lo puedes llevar.

**Comment by redneo** [comment]
arreglada hace dias.
