### ISSUE TITLE
El Bastión Violeta - Boss bug

### ISSUE THREAD

**Issue by Kleinn** [RoDNet/Bugtracker-Infinium-4.3.4#2455]
El boss del bastión violeta "Ícotron" no se puede matar, ya que cuando llega a uno de vida hace como que muere, pero sigue atacado. Tú no le puedes atacar a él diciendo que es un objetivo no válido.

**Comment by paellaencol** [comment]
http://es.wowhead.com/zone=4415/
http://es.wowhead.com/npc=29313

**Comment by Kiritoo** [comment]
Ya reportado.
