### ISSUE TITLE
VALLE sombraluna-La Clave de Condenación. La carga de Ar'tor

### ISSUE THREAD

**Issue by conqueron** [RoDNet/Bugtracker-Infinium-4.3.4#2457]
LA  mision  La Clave de Condenación. La carga de Ar'tor
esta bug el NCP Ar'tor no me da la mision y no aparece el CRIP de la mision 
porfavor ayuda.

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
