### ISSUE TITLE
[Cazador-Hechizo]Disparo de puntería

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#2459]
Nombre: Disparo de puntería
Enlace: http://wow.freakz.ro/spells.php?spell=82928
Problema: El daño que está haciendo la habilidad es demasiado bajo, demasiado. Alrededor de 6k únicamente, cuando es uno de las habilidades más poderosas del cazador, y por lo mismo tardada en castear y con alto costo de enfoque.
Observación: Al pegarle al muñeco la cantidad que el disparo hace es de 14-16k en normal, y 28-32k cuando es crítico, lo cual sería el daño correcto (con bufos y eso). Pero ya en pvp el daño se nerfea mucho, los golpes normales quedan en 4-6k y los criticos ni siquieran hacen el 200% de ese daño base. Por mucho que un jugador tenga temple, la reducción del daño es enorme. Aún juntando todo el tempe y armadura que quiera el oponente, es imposible que la reducción de daño sea tanta.

**Comment by Jhovanni** [comment]
Como observación adicional, el problema me parece ser del temple que está absorviendo de más en ciertas habilidades. En pve, el disparo de puntería hace 15.k en normal, y el doble en critico (como debería de ser). Pero en PVP la reducción es demasiada, a lo mucho llega a 6k, y eso ante tela, ante placas con equipo sañoso y un poco más, con suerte hace 4k.

**Comment by Sagittariu5** [comment]
Te amo Jhovanni <3

**Comment by ghost** [comment]
Dejo las fórmulas correctas y contrastadas para 4.3.4. : 

Un poderoso disparo de puntería que hace 160% de daño de arma a distancia más [(RAP \* 0.724)+776].

http://web.archive.org/web/20120512062508/http://www.wowhead.com/spell=19434
http://db.mmo-champion.com/s/19434
- Datos del RAWR , son un poco raros, pero bueno:
  DamageBase = (combatFactors.AvgRwWeaponDmgUnhasted + (StatS.RangedAttackPower \* 0.724f) + 776) \* 1.60f + 100;
- Datos del DrDamage:
  ["Data"] = { 0.73, 0.11, ["weaponDamage"] = 1.32, ["PPL_start"] = 10, ["PPL"] = 0.4 },
  [0] = { School = { "Physical", "Ranged", "Shot" }, APBonus = 0.724, BleedExtra = true, },

Fuente: Bugtracker de Molten. 
Fórmula <strong>verificada y validada </strong>

**Comment by searum** [comment]
fix
