### ISSUE TITLE
El item Esencia de Rubí da caida del servidor

### ISSUE THREAD

**Issue by makidavid** [RoDNet/Bugtracker-Infinium-4.3.4#246]
Pues como he dicho, este item, que se encuentra en el nexo, da caida del servidor fuera del nexo, agradeceria saber por qué y cuando estará solucionado :D

**Comment by redneo** [comment]
http://es.wowhead.com/item=37860
http://es.wowhead.com/spell=49462 
http://es.wowhead.com/spell=49461
http://es.wowhead.com/spell=49345

PONER ENLACES POR DIOS!!!!!!

Arreglado

**Comment by makidavid** [comment]
Perdona, es la primera vez que reporto así y no sabía como era :-)
