### ISSUE TITLE
[Banda: Bastión de Baradin] Argaloth

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2460]
Enlace del boss: http://www.wowhead.com/npc=47120/

Problema: desde hoy mismo está haciendo más de 150k de daño físico (golpes blancos) a los tanques (más de 300k al resto de jugadores)

http://img7.imageshack.us/img7/7549/1trj.jpg
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/7/1trj.jpg/'><img src='http://img7.imageshack.us/img7/7549/1trj.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

**Comment by Sagittariu5** [comment]
Lo confirmo anoche mismo nos dispusimos a realizar la raid ninguno de los dos bosses está completamente blizzlike creo que alguien con conocimientos podría ayudar D:

**Comment by redneo** [comment]
Arreglado este y halfus, si estais interesados puedo poner el daño que me hace sin ropa de tank.
