### ISSUE TITLE
Banco de la hermandad - wow error

### ISSUE THREAD

**Issue by Kleinn** [RoDNet/Bugtracker-Infinium-4.3.4#2463]
Cada vez que me meto en el banco de la hermandad me echa del wow, he hablado con  otra gente y no sólo me pasa a mi. Antes sólo me pasaba con la 2ª pestaña, ahora no me deja ni abrirlo.

**Comment by Sagittariu5** [comment]
Creo que te borrarán el post pero si lo toman en cuenta deberían saber que esa no es la única cosa relacionada al wow error cuando invitas a gente a la hermandad también sucede.

Y Kleinn este error ya es muy  viejo solo que a las personas le sucede con diferente frecuencia

**Comment by Rametep** [comment]
a mi me pasa continuamente. a veces me saca del juego y otroas no, pero siempre estoy cayendome del juego por culpa de ese wow error.

**Comment by Dekadencee** [comment]
Repetido: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1526

Lo seguimos desde ahí
