### ISSUE TITLE
[Mago] Congelación profunda

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#2464]
Nombre: Congelación profunda (Mago Escarcha)

Descripción: Aturde al objetivo durante 5 s. Solo se puede utilizar en objetivos congelados. Inflige de X a X p. de daño a los objetivos inmunes de forma permanente al aturdimiento.

Fallo: está siendo lanzada de manera pasiva por cualquier tipo de caster al atacar con hechizos a alguien inmune a los aturdimientos.

ID: http://es.wowhead.com/spell=44572

**Comment by F4NT4SM4** [comment]
hechizos magicos que dan stun si el objetivo es inmune por filotormenta, entereza de hielo etc
recibe daño con congelacion profunda
los hechizos magicos que he visto tener este bug es: Conflagar (brujo), Impacto (mago) y el druida equilibrio pero nose cual skill exactamente

**Comment by ghost** [comment]
wow, enserio lo tiran otras clases también?
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1188

**Comment by F4NT4SM4** [comment]
yo que quiero tirar full cd de lo lindo y filotormenta y me matan en 4s puro congelacion profunda 20k

**Comment by Kiritoo** [comment]
fix
