### ISSUE TITLE
[Misión] El milagro de Aessina

### ISSUE THREAD

**Issue by ismaelklepasky** [RoDNet/Bugtracker-Infinium-4.3.4#2469]
No existe hamuul tótem de runa

**Comment by ghost** [comment]
Modifica el reporte y haz uno en condiciones siguiendo las siguientes pautas:

http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
