### ISSUE TITLE
Problemas con vendedores de Bancalto

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#247]
Los vendedores del Bancalto, la fortaleza de la alianza que se encuentra en las tierras altas crepusculares, que venden items para realizar ciertas recetas no venden nada...  Su ventana de ventas se encuentra vacía. Por ejemplo:  Casandra Downs la vendedora de articulos para alquimia e inscripcion que vende,  ojo de ogro en conserva y mandíbula blanqueada. No tiene nada que vender con lo cual no se puede realizar ciertas recetas.

**Comment by redneo** [comment]
NPC http://es.wowhead.com/npc=49703 no vende nada, ahora si que vende... PONED ENLACES SI QUEREIS QUE SE REPAREN LAS COSAS RAPIDAMENTE!
