### ISSUE TITLE
TEMPLO OSCURO

### ISSUE THREAD

**Issue by conqueron** [RoDNet/Bugtracker-Infinium-4.3.4#2470]
PROBLEMA: varias criaturas que estan dentro de la masmorra no se les puede hacer click, no tienen vida.

ILLIDAN se bugea en la FASE 2 no se le puede pegar.

**Comment by melcalla** [comment]
al menos pasastes a la fase dos ami ni se activo

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by JoakRoD** [comment]
Se buguea por demasiado dps. Cierro.
