### ISSUE TITLE
[Paladin] El arte de la Guerra

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2471]
http://wow.freakz.ro/spells.php?spell=87138

Tus ataques automaticos tiene un 20% de posibilidades de hacer que tu siguiente Exorcismo sea instantaneo, gratis y que inflija un 100% de daño adicional.

El problema es que no es gratis, y además su coste es muy superior al normal. Por tanto, como te salte dos veces muy seguidas te qedas sin mana.

**Comment by meybon** [comment]
Para esto me preguntaste tanto no? xDD
Efectivamente, aunque no lo he probado tranquilamente diria que hay algunas veces que si es gratis, otras no, esto generalmente pasa cuando tienes poco mana que no te deja tirarlo si no tienes mas de 8k de mana, pero tampoco es siempre, son cosas como escudo sacro que aveces no salta en todo un combate.
Resumiendo, unas veces es gratis otras no, depende de como tenga el dia xD

**Comment by Kiritoo** [comment]
Funcionando correctamente, no gasta mana.

**Comment by Wiinter** [comment]
A veces funciona, a veces no.

**Comment by ghost** [comment]
Si es verdad que solo funciona a veces, no lo reportes aquí, hazlo en el reporte de todos los hechizos para que lo lean y lo vuelvan a añadir.

**Comment by Wiinter** [comment]
Buena idea, voy
