### ISSUE TITLE
[Mago] [Mision] Crecen tan de prisa

### ISSUE THREAD

**Issue by Mi6uelxD** [RoDNet/Bugtracker-Infinium-4.3.4#2472]
Hola a quien corresponda tengo terminada la mision de "Crecen tan deprisa" 
termine las diaria k te da el raptor y tengo los elementos completos
los dientes, el paño, el dinero y el objeto para invocarlo,
 por concluir a el pj que me dio la mision para completar y al abrir 
platica y Concluir no me da el Botón "completar"

espero aver sido claro

esperando su respuesta 

De antemano gracias

 Mi nick es Mi6uelxD y mi personaje es MiguelxD

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
