### ISSUE TITLE
Mision Diaria de cocina de ventormenta

### ISSUE THREAD

**Issue by Rametep** [RoDNet/Bugtracker-Infinium-4.3.4#2474]
la mision diaria de cocina de ventormenta de la sidra del rey no da experiencia, asi que esta bug y aqui la reporto para su reparacion.

Gracias por todo

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
