### ISSUE TITLE
[Talento-Cazador]T.N.T.

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#2475]
Nombre: T.N.T.
Enlace: http://wow.freakz.ro/spells.php?spell=56336
Descripción: Cuando inflinges daño periódico con Trampa de inmolación, Trampa explosiva o Flecha negra tienes un 20% de activar Bloquear y cargar.
Problema: Flecha negra activa Bloquear y carga aún cuando no se tenga el talento T.N.T. tomado, por lo tanto es un bug beneficioso para los cazadores.
Observación: Hay que aclarar que tampoco es que cambie mucho la dinámica del juego, pues debido a talentos en la rama supervivencia que no sirve, de cualquier manera sobran esos talentos y hay que colocarlos en algún lado. Sin embargo, de arreglar los bugs que no sirven, entonces si sería muy desequilibrante tener T.N.T. sin tener que gastar talentos en el. Por ahora igual se tiene que tomar ese talento o alguno bug, pues se requieren talentos gastados para llegar al fondo de la rama.

**Comment by redneo** [comment]
Lo he estado probando y en un buen rato no me ha saltado teniendo flecha negra y sin tener el talento.

**Comment by Jhovanni** [comment]
Redneo me parece raro que no te salte pues si lo hace. Lo único que hay que hacer es tener supervivencia y tener el talento Bloquear y cargar previamente.

**Comment by searum** [comment]
fix
