### ISSUE TITLE
[Descenso de Alanegra] Maloriak

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2476]
http://es.wowhead.com/npc=41378

Si te mata la primera vez y vuelves a hacerle un try. El daño que hace es desorbitante, casi mata al tank de un toque.

Cuando entra en la fase dos y tira chorros de lava(http://es.wowhead.com/spell=78095), su daño no es de entre 30 y 40k sino que como te pille has muerto y además el area ocupa mas de 3 yardas.

Me aventuraría a decir que el daño a melee lo tiene algo subido, pero no estoy seguro, y es por eso que cuando entra en la segunda fase, al augmentar su daño, es algo difícil poder controlarlo durante unos cuantos segundos.

**Comment by paellaencol** [comment]
El daño de golpe blanco de Maloriak sí que es cierto que está subido.
El daño de chorros de lava http://es.wowhead.com/spell=78095 también está más alto de lo que debería.

Aun así, este boss es realizable, pero hay que sudar tinta para tirarlo.

Añado un problema más, hoy lo hemos tirado, y solo ha despojado oro, no ha dado ningún item.

**Comment by Wiinter** [comment]
Nosotros lo hemos dejado a 1 millon por culpa del chorro, y le hemos dado un segundo try y el tanke no aguantaba los golpes blancos iniciales. Tengo qe recalcar que tenía ecos de luz de 100k por tik.

Gracias por el aporte Paellaencol

**Comment by paellaencol** [comment]
Además chorros de lava http://es.wowhead.com/spell=78095  está lanzando (elevando violentamente) hacía el techo de la plataforma al tanque, cuando no debería, ya que le está ocasionando un daño por caída superior al 60% de su vida

**Comment by Monleon** [comment]
Seguimos desde https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3239
