### ISSUE TITLE
[Descenso de Alanegra] Atremedes

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2477]
http://es.wowhead.com/npc=41442

Cuando castea Llamas abrasadoras (http://es.wowhead.com/spell=77657), que llena no toda la sala de llamas, estas no se las puede cortar con los tambores. Además Atremedes no destruye los tambores por mucho que los uses nunca desaparecen.
Los tambores producen Fragor resonador(http://es.wowhead.com/spell=77611) que además producen sobre Atremedes un debuff que te permiten hacerle mas daño (http://es.wowhead.com/spell=77717)

**Comment by paellaencol** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1330

Tampoco se puede resetear el nivel de sonido clicando uno de los diez Escudos enanos antiguos http://es.wowhead.com/npc=42960

P.D. EN la fase de suelo el boss debería hacer periódicamente la habilidad "Impulso de sónar" http://es.wowhead.com/spell=77675 (nunca la hace)

Y en fase aérea tampoco hace "Impulso de sónar" la diferencia es que este circulito al caer se debe convertir además en "Bomba de sónar" http://es.wowhead.com/spell=92553

Dejo como referencia: http://www.guiaswow.com/descenso-de-alanegra/guia-atramedes.html

**Comment by Wiinter** [comment]
Gracias por el aporte Paellaencol
