### ISSUE TITLE
[Talento-Cazador]Disparo firme mejorado

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#2478]
Nombre:Disparo firme mejorado
Enlace: http://wow.freakz.ro/spells.php?spell=53224
Descripción:Cuando lanzas Disparo firme dos veces seguidas, tu velocidad de ataque a distancia será aumentada 15% durante 8 segundos.
Problema: La habilidad se activa, pero sucede muy rara ocasión y como al tirar 4 o 5 disparos firmes seguidos, y no es seguro.
Observación: Me parece que el problema está en que el talento considera los ataques automáticos del cazador (así como los adicionales por la maestría) como hechizos intermedios, por lo tanto el sistema considera que no fueron dos Disparos firmes seguidos. Así, el talento se está activando cuando se lanzan los dos disparos firmes entre la brecha de los disparos automáticos; me parece ese es el error. Ahora bien, no puedo asegurar eso pues la brecha es muy pequeña y junto con los disparos producidos por la maestría, cuesta comprobarlo.

**Comment by searum** [comment]
fix
