### ISSUE TITLE
[NPC-Tabernero]Posada de Lunargenta

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#2479]
Nombre:Tabernera Jonvia/Velandra
Enlace: http://es.wowhead.com/npc=17630
http://es.wowhead.com/npc=16618
Descripción:--- No requieren explicación, son taberneros normales
Problema: Estos NPC no ofrecen la posibilidad de establecer tu posada en dicho lugar.
Observación: Si, se que no es un bug importante. Pero sigue siendo un bug que ya no se tendrá que reportar :). Además, a mi me gustaría poner mi piedra hogar ahí, y no en Orgrimmar.

**Comment by redneo** [comment]
Arreglada.
