### ISSUE TITLE
[Druida] Testeo

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#248]
Hola en está ocasión voi a testear los hechizos del druida.
Lo voi hacer completamente sin armadura y arma.

_Hechizos de daño_

<h5>Cólera - http://es.wowhead.com/spell=5176</h5>

-Daño:1017-1129
-Media DrD: 1174 (1112-1235)

<h5>Tifón - http://es.wowhead.com/spell=61391</h5>

-Daño:1523
-Media DrD: 1511 (1510-1511)

<h5>Lluvia de estrellas - http://es.wowhead.com/spell=48505</h5>

-Daño:604-671
-Media DrD: 6350 (5920-6780) 9x~635

<h5>Oleada de estrellas - http://es.wowhead.com/spell=78674</h5>

-Daño:1330-1664
-Media DrD: 1628 (1406-1850)

<h5>Fuego lunar - http://es.wowhead.com/spell=8921</h5>

-Daño:263 - Ticks  135
-Media DrD: 257 (234-280) 6x~153.2

<h5>Fuego estelar - http://es.wowhead.com/spell=2912</h5>

-Daño:1378-1647
-Media DrD: 1626 (1469-1783)

<h5>Enjambre de insectos - http://es.wowhead.com/spell=5570</h5>

-Daño:Ticks 218
-Media DrD: 1275 (1272-1278) 6x~212.5

<h5>Huracán - http://es.wowhead.com/spell=16914</h5>

-Daño:Ticks 342
-Media DrD: 3515 (3510-3520) 10x~351.5

<h5>Champiñón salvaje - http://es.wowhead.com/spell=88747</h5>

-Daño:901-1055
-Media DrD: 1073 (980-1165)

///////////////////////////////////////////////////////////////////////////////////////////////////////////

_Hechizos de curación_

<h5>Nutrir - http://es.wowhead.com/spell=50464</h5>

-Curación:2538-2876
-Media DrD: 2747 (2543-2950)

<h5>Rejuvenecimiento - http://es.wowhead.com/spell=774</h5>

-Curación:1367
-Media DrD: 5526 (5524-5528) 4x~1381.5

<h5>Recrecimiento - http://es.wowhead.com/spell=8936</h5>

-Curación:3485-3667 Ticks 391
-Media DrD: 3772 (3567-3977) 3x~380.5

<h5>Flor de vida - http://es.wowhead.com/spell=33763</h5>

*1 Acumulación
-Curación:1930 Ticks 243
-Media DrD: 1970 (1969-1970) 10x~241.4

*2 Acumulaciones
-Curación:3860 Ticks 486
-Media DrD: No la pongo porque en el DrDamage solo aparece x1 y x2 con 2 no.

*3 Acumulaciones
-Curación:5793 Ticks 729
-Media DrD: 10x~724.2

<h5>Crecimiento salvaje - http://es.wowhead.com/spell=48438</h5>

-Curación: Ticks 345-808  Empieza sanando mas al lanzarlo y va bajando cada tick.
-Media DrD: 3938 (3934-3941) 7x~562.5

<h5>Alivio presto - http://es.wowhead.com/spell=18562</h5>

-Curación:15434
-Media DrD: 8523 (8522-8523)

<h5>Toque de sanación - http://es.wowhead.com/spell=27527</h5>

-Curación:11932-13190
-Media DrD: 12359 (11350-13367)

Bueno aquí concluye mi reporte del testeo realizado al druida.
No hay mucho que decir, por lo general esta todo correcto o un poquito bajo o un poquito alto pero apenas algo notable.
Solo diria que resalta Alivio presto que esta curando casi el doble.
Por lo demas decir que si alguna spell de alguien despues de testear esto cura exageradamente o pega, más de la cuenta toca testear talentos.
Ya pues testeando todo esto asi sin talentos y armadura se ve correcto.

Un saludo.

**Comment by Alfonn** [comment]
Muy buen reporte, pero Crowel.. Si todo está bien sin talentos ni ropa, ¿porqué lo pones aquí? Aquí debemos poner todo aquello que NO funcione bien ...

Un saludo.

**Comment by crowel** [comment]
Como comprenderas esto es una guia de lo que estan realizando las habilidades del druida, si esta todo bien, esto facilita el arreglo de otras cosas por partes de los gms y no centrarse en esto precisamente.
Ademas que se debe ajustar el alivio presto.
Aun asi gracias por tu comentario.

**Comment by crowel** [comment]
Cierro tema, ya pues tras el cambio de db se cambiaron las cosas.
Si se necesita reportar de nuevo comunicarmelo.
Un saludo.
