### ISSUE TITLE
el portalde ventormenta  a uldum no funciona

### ISSUE THREAD

**Issue by maxib** [RoDNet/Bugtracker-Infinium-4.3.4#2480]
cuando quise hacer la mision de se busca heroe uldum me pidio que valla a tanaris y cuando fui y hable con el npc me quiso dar otra mision y me decia que no cumplia con los requisitos y yo era lvl 85 asi que no puedo usar el portal a uldum que siendo herborista me resulta muy practico ya que tardo como 30 minutos en llegar hasta alla

**Comment by ghost** [comment]
Se ha bugeado...a mi también me dice que no cumplo los requisitos, ahora no sólo no se puede usar el portal sino que tampoco se puede hacer ninguna misión de uldum porque los npcs no te las dan...otra zona inútil para el leveo 83-85.

**Comment by redneo** [comment]
Alianza/horda¿?

**Comment by ghost** [comment]
Alianza, y por favor, dejad de cerrarme reportes sin solucionarlos como el del dragón esmeralda https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1760. No te discuto que tenga que estar montado en él para que se pueda completar la misión pero esque lo que no se puede es montar en el dragón. Al menos no cuando yo la hice con todos mis pjs.

**Comment by redneo** [comment]
Ya te la tendria que dar, si no te la da, dimelo y te borro la mision anterior 28558 de la base de datos (en otro BT porfas)
