### ISSUE TITLE
Talento poder congelado del chaman

### ISSUE THREAD

**Issue by lks06** [RoDNet/Bugtracker-Infinium-4.3.4#2481]
![2 2](https://f.cloud.github.com/assets/3086718/1405039/25f10aea-3d18-11e3-802a-41102abb7ed1.jpg)

Este talento no paraliza al objetio

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
