### ISSUE TITLE
Reputacion con El Anillo de la Tierra

### ISSUE THREAD

**Issue by Yoshyy** [RoDNet/Bugtracker-Infinium-4.3.4#2483]
Buenas, no se puede aumentar reputación con el Anillo de la Tierra (Therazane), los npcs no dan misiones ni se puede conseguir el tabardo, es decir, imposible aumentar reputación con ellos, gracias

**Comment by redneo** [comment]
Sigue la cadena de misiones ya veras como te llevas una sorpresa

**Comment by Wiinter** [comment]
Anillo de Tierra y Therazane son dos repus diferentes.
