### ISSUE TITLE
[Mision][Infralar]Llévalo con la clamatierras

### ISSUE THREAD

**Issue by asassin1993** [RoDNet/Bugtracker-Infinium-4.3.4#2487]
Bueno soi nuevo en esto y no se si estara bien puesto.

Error de la mision: No puede hablar con Sílex Mantomena para empezar la mision y llevarlo a donde deberia.

Link de la mision: http://es.wowhead.com/quest=26413

**Comment by redneo** [comment]
Arreglada.
