### ISSUE TITLE
[OBJETO] Engarce de Joyero (OBJETO MISSING)

### ISSUE THREAD

**Issue by Malabestia** [RoDNet/Bugtracker-Infinium-4.3.4#2488]
Engarce de Joyero

http://es.wowhead.com/item=52188

Componente de Joyería Necesario para subir profesión a partir de 460 aprox. 

Según la descripción de wowhead. (http://es.wowhead.com/item=52188#sold-by) Debería venderlo los principales "Jewelery supplies vendor" de las capitales. En Orgri Marith Lazuria, En Ventor Terrance Denman. 

Sin embargo, este artículo no se encuentra disponible en ningún vendedor de los que he visitado. He estado en Orgri, Dalarán y Entrañas. No he tenido ocasión de crear un Ali para comprobar si está disponible en alguna de las capitales de la Alianza. 

Resulta necesario para subir Joyería a partir de 460 aprox que es cuando tus recetas de joyas se vuelven verdes y grises... No lo vende nadie. 

Gracias por todo y un saludo

**Comment by asassin1993** [comment]
En ventormenta no se encuentra en el vendedor y en las demas capitales tampoco esta por reportar esto hoy y tube una urgencia me ganaste xD

**Comment by Malabestia** [comment]
;)
Yo ahora mismo no tengo posibilidad de mirarlo ya que no estoy conectado, pero me han comentado qeu es posible que los NPC's de Tierras Altas Crepusculares lo vendan. Si tienes oportunidad Asassin, echa un vistazo a ver si el NPC "Oslow Pliny" http://es.wowhead.com/npc=49707 los tuviera

Muchas gracias y un saludo!
