### ISSUE TITLE
[Paladin] Torre de Radancia Talento

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#249]
http://es.wowhead.com/spell=85512/torre-de-radiancia

El talento solo deberia de generar una cargar de poder Sagrado si estas sanando directamente al objetivo que tiene señal de la luz con luz divina o destello de luz
bien hace eso pero cuando utilizo choque sagrado, torre radancia o cualquier otro hechizo de curacion tambien le hace efecto el talento lo cual hace que hasta me llene las 3 cargas de poder sagrado de un solo choque sagrado
solo debe de funcionar con luz divida y destello de luz

**Comment by lamaza** [comment]
Men, te hago la recomendación y es sin molestar, haz un post solo de testeo de talentos, para que redneo los pueda tener claro, y no un hilo cada vez que encuetras algo,, trata de recopilar mas y esto quizá pueda arreglarse u ordenarse algún dia con mayor prontitud.

**Comment by ghost** [comment]
@lamaza Esto fue lo que dijo Dekadence en un reporte donde justamente todos ponian sus cosas en un lugar xd:
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/125

> Mira que os dije siempre que cada spell/bug en un reporte distinto...
> Menudo lio ahora para verlo y llevarlo todo :/

Además, Manri (redneo), también ya dijo que es mejor que cada bug en un reporte a parte
http://www.reignofdarkness.net/wow/foros/t2006/

Por mi parte, github tiene un lindo sistema de "etiquetas" para poner en una sección todo lo relacionado a cosa, creo que se deberían de habilitar las etiquetas y hacer secciones para cada clase del juego, así se evita crear un reporte con muchos bugs dentro.

**Comment by crowel** [comment]
Pienso como Lvm en las etiquetas, de activarlas estaria todo mas ordenado a la hora de fixear y buscar bugs en el bugtracker para ver si estan repetidos.
Un saludo.

**Comment by lamaza** [comment]
Bueno, al menos aprendi algo de ustedes XD. Osea que perdemos el tiempo haciendo un solo post de paladin reprensión?

**Comment by searum** [comment]
fix
