### ISSUE TITLE
[Misión] Corona de Hielo - Necesitarás un grifo 

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2498]
http://es.wowhead.com/quest=12814

Matas al jinete y en el loot te da un grifo temporal y lo entregas.

Vas a buscar el grifo pero son amistosos pero el jinete no entonces te pega pero tu no  puedes pegarle a el.

**Comment by redneo** [comment]
Arreglada hace dias
