### ISSUE TITLE
batalla de gilneas (campo de batalla)

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.3.4#25]
no hay puerta cuando empiezas las bg.

http://subefotos.com/ver/?77a4bfa58690cfdd2bc8e30a8cb89d65o.jpg#codigos

i no se pueden capturar las banderas 

http://subefotos.com/ver/?48cd440ec21b9f0d82072d9d66a66ca2o.jpg#codigos

**Comment by sherik12** [comment]
Los cementerios no funcionan aun teniendo la base bajo control
