### ISSUE TITLE
[Paladin] Santidad de Batalla

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#250]
http://es.wowhead.com/spell=25956/santidad-de-batalla
el talento deberia de hacer que los efecto de celeridad reduzcan las reutilizacion de Golpe del cruzado http://es.wowhead.com/spell=35395/golpe-de-cruzado
y Tormenta divina http://es.wowhead.com/spell=53385/tormenta-divina

Reforjer full celeridad y utilize sentencia para que un talento me diera 9% mas de celeridad y la reutilizacion no bajaa para nada en los hechizos

**Comment by searum** [comment]
confirmame que sigue sin funcionar..

**Comment by F4NT4SM4** [comment]
tengo 18% celeridad en mi pala y la reutilizacion sigue siendo igual 4.5s 
sigue bug...

**Comment by lamaza** [comment]
Por qué cerraste? Ya funciona?¿

**Comment by F4NT4SM4** [comment]
nah pero en esta version preferible evitar la celeridad con el pala ir full fuerza/maestria despues de llenar el cap

**Comment by sprin69** [comment]
yo tengo un pala y creo k es mejor full celeridad ya hay una skill k cada golpe del cruzado t pone 3 cargas y ocon el mio ara mismo voya full critico y como max pegas 10-13k asi k no se hasta k punto t compensa el critico o la celeridad

**Comment by F4NT4SM4** [comment]
la celeridad para que te reduzca valiosos segundo en golpe del cruzado necesitas alta y solo seria bueno con ansias o heroismo
o un compa dk que te aumenta la celeridad con el buff
pero para 1v1 voy maestria que aumenta el daño sagrado de algunas skill
y como el talento esta bug de nada sirve la celeridad

**Comment by sprin69** [comment]
t sirve como compañero un dk un sacer o un lock el cd es 4,5 sec full celeridad no tengo ni idea d a cuanto se kedaria pero a lo mejor donde ahora das 4 golpes si funciona el talento y vas con celeridad en vez d cuatro puedes dar 5 kien sabe si kizas es mas k lo arreglen como el k no kiere la cosa y si no convence pues seguimos = xD

**Comment by searum** [comment]
fix
