### ISSUE TITLE
[Chaman] Chaman Mejora necesita una revisión A Fondo

### ISSUE THREAD

**Issue by harusen** [RoDNet/Bugtracker-Infinium-4.3.4#2501]
Buenas, 

Actualmente el chaman mejora esta fatal.

El 80% de los ataques estan pegando la mitad o menos de lo que indica la spell, escudod erelampagos, golpe tormenta, arma lengua de fuego, desatar elementos, las curas q ponen que deerian ser de 15K son de 9K etc....   la lista es enorme.

Pido por favor que le metan un repaso a fondo, xq de verdad lo necesita, de más está decir que hay un monton de bugs en los talentos, como poder congelado.

Muchas gracias por su atención

**Comment by Wiinter** [comment]
Para cada cosa bug haz un reporte a parte. No vale con decir que le hagan un repaso a todo

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
