### ISSUE TITLE
[Druida] y [Guerrero]

### ISSUE THREAD

**Issue by harusen** [RoDNet/Bugtracker-Infinium-4.3.4#2502]
Buenas, 

Problema:

Hace unos días desactivaron el      Rugido Salvaje     ID 52610 ya que daba un 80% de daño global al daño, y esto no debería ser asi.

Desde hace Mucho tiempo el      Ataque de la victoria      del guerreros ID 34428 cada vez que mata algo (alguna serpiente de una trampa o cosas asi), q no aporta honor pueden usar este ataque y actualmente les esta sanando mas del 60% de su vida, Pero  solo deberia activarse cuando se mata a un Jugador que aporte Honor y hasta un Max del 20% de la vida max del jugador.

Pues bien, xq los druidas nos quedamos sin rugido salvaje y los guerreros no se quedan sin golpe de la victoria?

O todos o ninguno pienso yo no?  Muchas gracias

**Comment by elmiriox15** [comment]
Si fuera por esa regla de tres, desaparecerían muchas skills de las clases jeje, y el ataque de la victoria no sana siempre +60%, y puede llegar a sanar un 36% de manera oficial.

**Comment by harusen** [comment]
Pues por esta regla de 3, el druida se queda sin skill y el guerrero no, no me parece para nada justo, xq este bug convierte en inmortal a los guerreros, xq el druida si, y el warrior no? 
Por favor una explicacion racional, no un no xq si 
Muchas gracias

**Comment by ghost** [comment]
Esto no es un foro de debate, es un bugtracker para reportar bugs, y ambos están ya reportados. Esto no debería estar aquí, si no en el foro-apartado sugerencias como mucho.

Los druidas también son inmortales cuando se regeneran la vida en forma de oso y no se ha desactivado, eso es el equivalente a la cura del warr en mi opinión. Pero este no es lugar para iniciar un debate.

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
