### ISSUE TITLE
[Druida] Arañazo

### ISSUE THREAD

**Issue by harusen** [RoDNet/Bugtracker-Infinium-4.3.4#2503]
ID Arañazo   1822

Problema: Los dots que esta pegando no están acumulando maestría

Formula: 56_3 + AP_ 0.441   Y a esto añadirle la maestría del Feral 

ID 86470 Garras Tajantes, que aumenta todo daño procedente de sangrados( en mi caso 44% con 14.09 de maestría)

http://wow.freakz.ro/spells.php?spell=1822

El daño que esta haciendo (en mi caso, AP 13088) es 1139 con cada tick, sin embargo a ese daño faltaría sumarle la maestría (44% en mi caso) por lo que debería pegar 1640 por tick.

Muchas gracias.

**Comment by ghost** [comment]
Ya está reportado

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1942 y https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2353
