### ISSUE TITLE
Los huargen no pueden salir 

### ISSUE THREAD

**Issue by Rickylix** [RoDNet/Bugtracker-Infinium-4.3.4#2504]
hay una mision llamada "Sacrificios" en Gilneas, es totalmente imprescindible para poder salir de Gilneas y jugar con un huargen pero en esa mision hay unos fantasmas en el recorrido del caballo que te matan de 2 golpes y hay 3.He conseguido terminar el recorrido varias veces pero cuando no tenía la mision y no me parece una coincidencia.
Me gustaría que este error se solucionara
Gracias.

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by sirkaox** [comment]
Ya habían dicho que tanto Wargen, DK's, y goblin, tenian que hacer ticket para que los sacaran de su lugar de nacimiento, o como se le llame.
espero siga siendo así, pero si arreglan la misión que mejor.

**Comment by ivanlm90** [comment]
Mi hermano y yo lo conseguimos!! Tras 5 o 6 intentos y después de morir varias veces conseguimos completar la misión lanzando antorchas como locos pero lo conseguimos.

**Comment by Monleon** [comment]
Las misiones de los huargens ya funcionan perfectamente de inicio a fin.
