### ISSUE TITLE
[NPC] Kezzik el Asediador <Equipo de Gladiador despiadado y vengativo>

### ISSUE THREAD

**Issue by sirkaox** [RoDNet/Bugtracker-Infinium-4.3.4#2506]
Mas que un bug, es la ausencia de algunos items, en mi caso, las armas Gladiador Vengativo, las cuales debería vender pero simplemente no las tiene, solo tiene las armaduras, mas no las armas.
![image](https://f.cloud.github.com/assets/5151500/1413983/f01f65fc-3e60-11e3-847a-b84174f33c69.png)
![image](https://f.cloud.github.com/assets/5151500/1413984/052f854e-3e61-11e3-9f70-a2d0b48e24e2.png)

Aquí lo que debería vender http://es.wowhead.com/npc=54650.

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2465
