### ISSUE TITLE
[Misión] Corona de Hielo - Venganza para los vargul

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2507]
http://es.wowhead.com/quest=13059

Retas al señor feudal y sus dos guerreros con la espada (http://es.wowhead.com/item=42928)y los matas.

Te acercas y te atacan, además que no les puedes retar con la espada.

**Comment by redneo** [comment]
Hay un punto que si que te deja retarlos perfectamente. Atina a encontrarlo
