### ISSUE TITLE
Mil Agujas: Misiones Bug

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#251]
Mision: El blandon antiguo

![wowscrnshot_070713_201028](https://f.cloud.github.com/assets/4893907/758438/29611f58-e732-11e2-915b-495ff8a8ed7b.jpg)

![wowscrnshot_070713_202034](https://f.cloud.github.com/assets/4893907/758447/6395a3a6-e732-11e2-8894-8157e001df4e.jpg)

Hay que encender un blandon con una antorcha y recoger la llama sacra pero no se enciende el blandon ni la antorcha hace el efecto de encender

![wowscrnshot_070713_200633](https://f.cloud.github.com/assets/4893907/758446/582f4030-e732-11e2-9c5f-2c327baffa6e.jpg)

**Comment by frustrix** [comment]
Ver Bugtacker #134

**Comment by crowel** [comment]
fix
