### ISSUE TITLE
-NPC- ¡Armacola!

### ISSUE THREAD

**Issue by DemexD** [RoDNet/Bugtracker-Infinium-4.3.4#2510]
El bug se encuentra al momento de ir a cobrar la mision, uno es teletransportado al lugar (ya que la mision directamente es salteada) en cuestion el npc que seria "Harrison Jones" no aparece en el lugar

http://prntscr.com/200wy7

La imagen de arriba muestra el lugar donde teoricamente deberia estar pero no hay nada

**Comment by redneo** [comment]
A mi me aparece bien Harrison Jones en su lugar tras acabar la mision, la cual no has puesto el enlace.
