### ISSUE TITLE
Paladín reprensión: Palabra de gloria 

### ISSUE THREAD

**Issue by meybon** [RoDNet/Bugtracker-Infinium-4.3.4#2511]
Tras el "arreglo" esta es la situación:

 http://es.wowhead.com/spell=86172/   Propósito
 http://es.wowhead.com/spell=85673/   Palabra de gloria

He hecho unas tablas sobre todas las situaciones de cura de la spell, con mi equipo pvp y sin absolutamente equipo y con el arma: http://es.wowhead.com/item=2521/

Ambos sin poderio o reyes que al aumentar estadísticas aumentaría la sanación

Con equipo:
http://subefotos.com/ver/?da1c8a8df308e59214e7be426864f3eeo.jpg

Se me olvido 0 cargas y propósito, 4.7k y deberia 14k.

Sin equipo:
http://subefotos.com/ver/?b4d1ef57425a478d96642936475a20cao.jpg

0 cargas y proposito 3.4k debería 6.8k

Formula de Palabra de Gloria
http://subefotos.com/ver/?64b381a12a16e782b20488174a42071bo.jpg

Observaciones: 
Con proposito activado tendria que curar siempre lo que cura palabra con 3 cargas de poder sagrado y como se muestra no coincide nunca,

Tambien destacar que sin equipo las curas superan lo que deberia de curar y pasa al contrario con equipo asique debe de estar escalando mal por estadisticas.

Por ultimo el extraño caso de 3 cargas y proposito que con equipo cura 2,9k.

**Comment by erdricklol** [comment]
Pero es que al curarte sana como si tuviera el glifo aun sin tenerlo.A lo mejor disminuye la sanación por eso? por que a nivel bajo no cura casi nada.

**Comment by meybon** [comment]
Si pero el problema que queria que se viese claro es que proposito, que deberia de curar siempre lo mismo porque cura como si tuvieses 3 cargas, nunca cura lo mismo.

**Comment by Dekadencee** [comment]
-> Todo esto teniendo en cuenta el glifo que vuelve a saltar como si lo tuvieses.
Issue #2443 

Fixeado

**Comment by Dekadencee** [comment]
Fixeado por completo:
- La cura periódica solo se aplicará si tienes el glifo.
- La curación se multiplica dependiendo de los puntos de poder sagrado.
- Al saltar el aura de Propósito divino te podrás curar como si tuvieras 3 puntos de poder sagrado.
- Con los talentos Sanación Desinteresada obtendrás el bonus del + 25% o 50% dependiendo del rango que tengas siempre que cures a unidades amigas (no a ti mismo).

Estos son los únicos errores que hemos encontrado y reparado, un saludo ^^
