### ISSUE TITLE
Misión (Tierras de la Peste del Este) Una sorpresa especial

### ISSUE THREAD

**Issue by likaion** [RoDNet/Bugtracker-Infinium-4.3.4#2512]
Nombre:Una sorpresa especial

Enlace: http://es.wowhead.com/quest=28650

Descripción: El caballero Comandante Puño de Peste te ha ordenado que ejecutes a Gally Tiñebulto, un prisionero de El Alba Argenta dentro de la prisión de los alrededores.

Gally Tiñebulto matado

Llegamos aquí, arrasamos el lugar y nos encaminamos hasta la casa de la prisión. No esperábamos encontrarnos con lo que vimos ahí, <nombre>. Parece que la Cruzada ha estado verdaderamente ocupada. Todo aquello está lleno de prisioneros de El Alba Argenta. La mayoría de ellos ya estaban muertos cuando llegamos, pero algunos pocos aún respiraban.

Estuve a punto de ir allí y acabar con el resto, pero creo que eres tú quien se merece este honor. Sobre todo hay un goblin muy valiente, cuya ejecución creo que disfrutarás de lo lindo.

Problema: Tengo un dk y al llegar a esta misión de la serie, el npc 'Caballero Comandante Puño de Peste' no me dió la quest... me salió el error: 'no cumples los requisitos para este misión' . Ahora ya no me aparece ni la exclamación para poder intentarlo otra vez. ¿Alguien sabe qué puede estar pasando? 

P.D.: He puesto un comentario en un report ya hecho  (https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/480), pero al estar cerrado no sé si lo revisarán y por esto creo este nuevo. 

Adjunto foto:

![sorpresa](https://f.cloud.github.com/assets/3774192/1415673/1d42e94a-3f16-11e3-8700-0103eb1243c0.jpg)

**Comment by likaion** [comment]
Actualizo incidente; gracias a la ayuda del MJ Ragebones, conseguí volver a "pillar" la quest. Por desgracia, ahora el problema es que no me aparece el npc que tengo que matar: Gally Tiñebulto (http://es.wowhead.com/npc=49356). 

Nombre:Una sorpresa especial

Enlace: http://es.wowhead.com/quest=28650

Descripción: El caballero Comandante Puño de Peste te ha ordenado que ejecutes a Gally Tiñebulto, un prisionero de El Alba Argenta dentro de la prisión de los alrededores.

Gally Tiñebulto  matado

P.D.: Si creen necesario que abra otro incidente en lugar de actualizar éste, me comentan.

![npc_not found](https://f.cloud.github.com/assets/3774192/1423895/db8cefd8-4013-11e3-9156-137ca7492e36.jpg)

**Comment by redneo** [comment]
Es problema de llevar un goblin:

El npc está puesto, y tiene el mismo script que los de al lado, tendria que funcionar, pero no lo puedo probar hasta que caiga el server.

**Comment by likaion** [comment]
Gracias por la respuesta, Redneo.

He vuelto a entrar y ahora sí que aparece el npc 'Gally Tiñebulto'; está al lado de 'Yazmina cuerno de roble'. Como se puede apreciar en la foto de mi post anterior, antes no estaba ahí.

El tema es que sólo puedo seleccionarlo, ni hablar con él, ni matarlo. Adjunto captura.

![gally tiebulto](https://f.cloud.github.com/assets/3774192/1472097/627b8946-45fa-11e3-984f-581327248fd5.jpg)

P.D.: Siento mucho todo el "coñazo" que estoy dando con esta quest, pero si no se soluciona no puedo avanzar con mi caballero de la muerte. Gracias :)
