### ISSUE TITLE
[Guerrero] Glifo de Machaque colosal

### ISSUE THREAD

**Issue by iBrianAR** [RoDNet/Bugtracker-Infinium-4.3.4#2513]
<hr>

• <strong>Nombre</strong>: <a href="http://es.wowhead.com/item=63481">Glifo de Machaque colosal</a>
• <strong>Enlace</strong>: <a href="http://es.wowhead.com/item=63481">http://es.wowhead.com/item=63481</a>
• <strong>Descripción</strong>: <a href="http://es.wowhead.com/spell=89003">Tu Machaque colosal también le aplica el efecto de Hender armadura a tu objetivo.</a>
• <strong>Problema</strong>: No aplica el efecto de Hender armadura al objetivo.

Captura de pantalla:
<img src="http://img69.imageshack.us/img69/2173/fm9w.jpg" />

<hr>

**Comment by ghost** [comment]
Ya estaba reportado: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2158
