### ISSUE TITLE
Camaras de los Origenes - No dan justicia los boses

### ISSUE THREAD

**Issue by cuspyg** [RoDNet/Bugtracker-Infinium-4.3.4#2517]
Hola, pues lo dicho la mazmorra Camara de los origenes tiene varios fallos:
- Los camellos del evento del boss Terracundo Path no se pueden montar, salen como enemigos.
- Los bosses no dan puntos de justicia.
- En el combate con Ammunae, al atacar las esporas o ciertas veces al boss, a la party entera nos crasheo el wow ( las 3 veces que lo hicimos), auque misteriosamente aparecio el boss muerto al reconectar.

Gracias. Soy Morden Paladin Tauren 85. SALUDOS.

**Comment by Wiinter** [comment]
El boss te crashea, nos pasa a todos xD No os asusteis, salió muerto porque con las pegatas que dejaisteis antes del crash lo mataron

**Comment by searum** [comment]
el crash ese se llama wow error y si no me decis cuando pasa... lo demas fix
