### ISSUE TITLE
[Banda: Bastión Crepuscular] Halfus Rompevermis (10n)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2519]
Enlace: http://es.wowhead.com/npc=44600/

Problema: está haciendo 200k de golpe blanco. Al tanque le hace instant kill nada más tauntearlo

**Comment by Drogoth2** [comment]
En 10 Normal eso es mentira paellaencol, yo lo he tanqueado y no me a pegado esos golpes blancos en la vida. A lo mejor esque os metisteis en 10H y hay si que pega esos ostiones, pero tanto halfus como los dracos.

**Comment by paellaencol** [comment]
No, no me estoy inventando nada, y sí, se diferenciar entre 10n y 10h, y aunque hubiera sido 10h, esos golpes tampoco serían apropiados.

Y sí, también se de sobra que fuisteis ayer y lo pudisteis tirar, pero nosotros fuimos anoche, y nos sucedió eso siempre, de hecho reinciamos la estancia un par de veces por si era un bug casual, pero tampoco, seguía haciendo sus 200k en su primer golpe.

Aunque no tengo la captura del golpe que le dio al tanque, colgaré la mía.

http://img543.imageshack.us/img543/5696/3j2z.jpg
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/543/3j2z.jpg/'><img src='http://img543.imageshack.us/img543/5696/3j2z.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

P.S. No lo mató al tanque con el primer golpe, le salvó el CTC, lo hizo con el segundo.

Le está pasando igual que a https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2460

**Comment by Drogoth2** [comment]
Jesucrist alomejor estoy un poco ciego pero hay pone que fuisteis en hero no en normal

**Comment by paellaencol** [comment]
No puedes ver si está en normal o en heroico, ya que el logotipo de un addon te tapa la dificultad de la banda.

De todas maneras está en normal, fíjate en la vida del jefe 32M. De haber estado en modo heroico su salud hubiera sido de 51,535,200

**Comment by paellaencol** [comment]
Ya que estamos con Halfus reportaré más bugs que vi la semana pasada cuando aún se podía hacer.

Rugido furioso http://es.wowhead.com/spell=83710 habilidad que adquiere el boss al quedar por debajo del 50% de salud. Problema: la castea pero no la deja terminar, la corta el mismo. La interrumpe el mismo, ya que enseguida empieza a castear otra spell http://es.wowhead.com/spell=38627 "Nova de las Sombras" (ésta si que funciona correctamente, y además debe ser interrumpible por el resto de jugadores)

**Comment by paellaencol** [comment]
npc Protobehemoth http://es.wowhead.com/npc=44687 

Descripción: Este npc al cual no se le puede atacar irá ganando más habilidades en función de qué dracos esten disponibles esa semana, no obstante a su vez irá recibiendo debuffs a medida que vayamos liberando a estos dracos:

-Habilidad base, sólo cuando el dragon "Celador del tiempo" http://es.wowhead.com/npc=44797 está inactivo (inactivo=no se puede despertar esa semana):
"bola de fuego" http://es.wowhead.com/spell=21162 (ataque sobre jugadores aleatorios)

-Habilidad que gana cuando las "Crías esmeralda huérfanas" http://es.wowhead.com/npc=44641 son activables esa semana: 
"aliento agostador" http://es.wowhead.com/spell=83855

-Debuff que se le aplica al Protobehemoth cuando las "Crías esmeralda huérfanas" http://es.wowhead.com/npc=44641 se liberan (salen al combate):
"veneno atrófico" http://es.wowhead.com/spell=83609 (los ataques del protobehemoth hacen menos daño)

-Habilidad que gana cuando el "Celador del tiempo" http://es.wowhead.com/npc=44797 es activable esa semana: 
"tromba de bolas de fuego" http://es.wowhead.com/spell=83721 

.-Debuff que se le aplica al Protobehemoth cuando el "Celador del tiempo" http://es.wowhead.com/npc=44797 es liberado (sale al combate):
"Dilatación temporal" http://es.wowhead.com/spell=83601 Distorsiona el flujo temporal alrededor del objetivo, lo que provoca que las acciones hostiles sucedan en cámara lenta. Esto provoca que el Protobehemoth lance sus ataques a cámara lenta, lo que permite a los jugadores poder evitar con mayor facilidad los ataques del Protobehemoth (esto se traduce en que transcurre un mayor tiempo desde que señala dónde va a efectuar el ataque, hasta cuando finalmente lo efectua)

---

Problema: nada de esto ocurre
http://www.guiaswow.com/el-bastion-del-crepusculo/guia-halfus-partevermis-wyrmbreaker.html

**Comment by Drogoth2** [comment]
Pues jesucrist nosotros estuvimos por la tarde y nunca nos metio esos golpes de 200k, alomejor pasa como con maloriak que si no lo matas a la primera, la segunda vez se cheta y pega bastante mas.

**Comment by paellaencol** [comment]
Primer intento, 200k de golpe. Sé lo que estoy reportando, y sé que vosotros lo hicisteis unas horas antes sin tener ningún percance. Por eso reiniciamos varias veces la estancia por si era un bug puntual.

Si me estuviera inventando todo esto, no estaría perdiendo el tiempo creando un reporte, créeme

**Comment by redneo** [comment]
Arreglado, si estais interesados puedo poner el daño que me hace sin ropa de tank.

Sigo diciendo que este boss necesita una remodelación total, ya que hace las cosas cuando no tiene que hacerlas.

**Comment by Wiinter** [comment]
Cuanta pupa te hace sin ropa de tanke?
