### ISSUE TITLE
Daño de la racial del Goblin

### ISSUE THREAD

**Issue by Navalagamella** [RoDNet/Bugtracker-Infinium-4.3.4#252]
Hace un daño absurdo [http://es.wowhead.com/spell=69041], parece que no se ve afectado ni por el poder de hechizos ni por el poder de ataque.
![wowscrnshot_070713_202342](https://f.cloud.github.com/assets/4733643/758450/be2d2474-e732-11e2-86e2-e118eff39ff2.jpg)

**Comment by redneo** [comment]
arreglado
