### ISSUE TITLE
[Misión] Tierras Devastadas - Eres Rakh'likh, demonio

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2522]
http://es.wowhead.com/quest=25701

Vas al norte del Alto y te encuentras un npc,Ujier que te teletransporta a la cima del Alto de los Rapiñadores. Matas a Razelikh, y sellas su alma mediante el cuchillo(http://es.wowhead.com/item=56012)

No está el Ujier que te teletransporta a la cima ni tampoco Razelikh en la cima.

**Comment by redneo** [comment]
Ha costado, MUCHO, pero arreglada, hay que tener en cuenta que hay que dejar al primer demonio con un 30% de vida o menos para que transforme al demonio.

Video de como va:
http://www.youtube.com/watch?v=tCs6R3TCm50
