### ISSUE TITLE
[Misión]La Batalla por la Ciudad de Gilneas

### ISSUE THREAD

**Issue by titoalfon** [RoDNet/Bugtracker-Infinium-4.3.4#2523]
La misión "La batalla por la ciudad de Gilneas" (http://es.wowhead.com/quest=24904), no empieza. Se supone que debe empezar al hablar con Krennan Aranas, pero no es así. Cuando hablas con él se abre un diálogo en el que pone: "Ya es hora de recuperar la Ciudad de Gilneas". Pulsas en el botón de "Adiós" y eso es todo.

**Comment by Kiritoo** [comment]
Actualmente se puede ir a la ciudad y entregar igualmente, está misión necesita un gran trabajo en hacer el script y como no es prioritario está así de momento.
Dejo el Issue abierto para que conste, gracias.
Saludos.

**Comment by jm90** [comment]
pero se puede hacer la quest?, ya que estoy batallando para hacerla, no la logro completar

**Comment by Kiritoo** [comment]
Si, vete a entregarla directa.

**Comment by Monleon** [comment]
Las misiones de los huargens ya funcionan perfectamente de inicio a fin
