### ISSUE TITLE
arqueologia

### ISSUE THREAD

**Issue by melcalla** [RoDNet/Bugtracker-Infinium-4.3.4#2524]
no funciona como deveria. completas objetos y te da puntos,  no picando , una locura de subirla.

**Comment by melcalla** [comment]
es la 3 vez que lo renuevo y voy a seguir renovandolo

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2385?source=cc
