### ISSUE TITLE
El Roble quejumbroso 

### ISSUE THREAD

**Issue by asorel** [RoDNet/Bugtracker-Infinium-4.3.4#2525]
En esa misión falta el npc Genn Cringris en el Roble Quejumbroso, en Darnassus 
es crucial para la misión ya que se debe hablar con el para  entregarla.
http://es.wowhead.com/quest=28517
![wowscrnshot_103013_195731](https://f.cloud.github.com/assets/5818133/1442117/fb571fba-41b6-11e3-88ac-d3e34e23664c.jpg)

**Comment by redneo** [comment]
Arreglado
