### ISSUE TITLE
Aszhara nivel de Nagas

### ISSUE THREAD

**Issue by Hallyne** [RoDNet/Bugtracker-Infinium-4.3.4#2528]
En Aszhara se encuentran los Nagas/Mirmidon Latigo de Ira, con nivel 12 pero una vez que los matas su drop es de items de nivel 45 a nivel 50 Aprox. 
![wowscrnshot_103113_203855](https://f.cloud.github.com/assets/5523277/1450898/9b66937a-4287-11e3-93f0-ba48991ca4c9.jpg)

**Comment by redneo** [comment]
Quitado el loot.

En wowhead dice que no tienen loot
