### ISSUE TITLE
Recuperar lo que es nuestro(gilneas)

### ISSUE THREAD

**Issue by edgar520** [RoDNet/Bugtracker-Infinium-4.3.4#2529]
Buenas la cosa es que hay una mision en gilneas que esta bug se llama 'Recuperar lo que es nuestro' y dice que hay que tocar un cuerno para poder coger un cofre dentro de la casa pero uno toca el cuerno y no pasa nada si pueden hacer algo por esa mision se les agradeceria ya que sin esa mision no se puede continuar leveando

**Comment by Monleon** [comment]
Las misiones de los huargens ya funcionan perfectamente de inicio a fin
