### ISSUE TITLE
[Banda: Bastión Crepuscular] Halfus Rompevermis (10n)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2530]
Enlace: http://es.wowhead.com/npc=44600/

Problema que encontrado en este boss:

Rugido furioso http://es.wowhead.com/spell=83710 habilidad que adquiere el boss al quedar por debajo del 50% de salud. Problema: la castea pero no la deja terminar, la corta el mismo. La interrumpe el mismo, ya que enseguida empieza a castear otra spell http://es.wowhead.com/spell=38627 "Nova de las Sombras" (ésta si que funciona correctamente, y además debe ser interrumpible por el resto de jugadores)
Además "Rugido furioso" actualmente está teniendo retroceso, no debería tenerlo.

**Comment by Monleon** [comment]
Funciona
