### ISSUE TITLE
[Banda: Bastión Crepuscular] Valiona y Theralion

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2531]
Enlaces: http://es.wowhead.com/npc=45993 http://es.wowhead.com/npc=45992

Problema: no dan loot, o por lo menos en dos semanas no lo han dado. Además algo sucede que tras acabar este encuentro nadie puede volver a entrar en esta estancia con esta ID, les sale "esta sucediendo un encuentro". Además si se intenta abandonar y se vuelve al día siguiente, las puertas de acceso al tercer boss te aparecen cerradas. https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2445

---

Voy ahora con los problemas de las habilidades (ambas de Valiona):
1. "Desmayo" http://es.wowhead.com/spell=86788 La periodicidad con la que hace esta habilidad es correcta, además la efectua también.
   El problema radica en que no cumple con su efecto:

"El Desmayo absorbe 50000 p. de sanación del objetivo. Cuando se disipa o expira, inflige 204750 to 215250 p. de daño de las Sombras a los enemigos en un radio de 8 m; el daño se divide entre todos los afectados por Desmayo."

Ojo! Remarco la parte donde dice que "se divide el daño entre todos los objetivos en un radio de 8m" sino seria instant kill.
1. "Meteorito crepuscular" http://es.wowhead.com/spell=86013 Al igual que el anterior funciona bien la periodicidad, y además hace la habilidad.
   El problema esta vez es que actualmente no está compartiendo el daño entre todos los aliados en un radio de 6metros del objetivo, sino que le está haciendo ese daño a todos los aliados en un radio de 6m del jugador afectado.
   Descripción:
   "Inflige 117000 to 123000 p. de daño de las Sombras a los enemigos en un radio de 6 m. El daño se divide entre los enemigos cercanos."

Remarco, lo de dividir el daño.

Gracias

**Comment by Wiinter** [comment]
Jesucrist quien fue el último que cayó Valiona o Theralion?

**Comment by paellaencol** [comment]
Pues empezamos el combate en Valiona y lo acabamos en Theralion. Es la mejor manera para evitar la skill de incendiar la sala

**Comment by redneo** [comment]
Dio oro al morir? o salia la bolsita vacia, no salia la bolsa, dimque que pasaba realmente a ver si es un fallo de base de datos.

Desmayo lo puedo poner que vaya en cualquier momento, lo que pasa que no me fio que reparta daño.

De meteorito he encontrado el fallo, y se como arreglarlo, a ver si encuentro a alguien que me lo pueda aplicar, quedando así Valiona y Theralion 100% funcional.

**Comment by paellaencol** [comment]
No dio nada al morir, simplemente no era looteable (ya que no había nada que lotear ni siquiera oro), lo mismo que nos sucedió con el concilio

**Comment by paellaencol** [comment]
Cierro, va perfecta.

**Comment by paellaencol** [comment]
Si bien el encuentro fue perfectamente, nos volvió a pasar que Theralion no dio loot.
1. Empezamos en Valiona
2. Sale Theralion
3. Cae Theralion

¿Lo reabro mejor?

**Comment by paellaencol** [comment]
Desde hace unos días entrar al reino crepuscular da wowerror a quien entra.

**Comment by paellaencol** [comment]
Hoy sí ha dado loot.

<del>Sin embargo creo que son las spells "Realidad cambiante" http://es.wowhead.com/spell=93055 y Destruccion deslumbrante http://es.wowhead.com/spell=86408 las que dan wow error a los afectados</del>

**Comment by Wiinter** [comment]
Cuando has entrado en Reino Crepuscular os sigue dando wowerror verdad?

**Comment by paellaencol** [comment]
No, ya no. El encuentro transcurrió con normalidad
