### ISSUE TITLE
[Banda: Bastión Crepuscular] Logro: "El Bastión del Crepúsculo" e impedimento de acceder a modo heroico

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2532]
Enlace: http://es.wowhead.com/achievement=4850

Descripción: obvia, mátalos a todos.

Problema: no está contando la muerte del consejo de ascendientes http://es.wowhead.com/npc=43735

Esto en sí no debería tener mayor problema, únicamente un logro que no funciona y ya está.
Ahora bien, sin ese logro no se puede acceder al modo heroico de la banda, lo cual sí es un problema bastante mayor.

Observaciones: posible causa del problema https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2445

**Comment by redneo** [comment]
Acabo de matarlo y si que me ha contado :S

**Comment by paellaencol** [comment]
Esto nos ocurrió además dos veces seguidas, la primera este martes (último día de id), y la segunda el miércoles (primer dia de ID). En ninguno de las dos muertes dio loot ni logro.

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/20/se8o.jpg/'><img src='http://img20.imageshack.us/img20/581/se8o.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img20.imageshack.us/img20/581/se8o.jpg

Una pregunta, hoy que lo has tirado te ha dado loot? Si la respuesta es afirmativa, posiblemente el bug sea que: si ha dado loot, el bug está en que sin loot no hay logro

Guarda alguna similitud con https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1243 ? Sin loot no hay logro?

**Comment by redneo** [comment]
No, no guarda simillitud...

Lo mate, me dio oro y loot correctamente, a parte del logro. Lo mate con un pj gm, sin el gm, que teoricamente es igual que cualquier pj :S

**Comment by paellaencol** [comment]
Una duda que me ha surgido al decir que lo mataste con un pj gm.

¿Primero tuviste que bajarle al 25% a Ignacius y Felludius, luego hacer lo mismo con Arion y Terrastra, para posteriormente acabar matando a la Monstruosidad?
O directamente con hacer instant kill a Ignacius ya te contó?

**Comment by paellaencol** [comment]
Nos ha vuelto a pasar, ni loot ni logro:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/845/0vaw.jpg/'><img src='http://img845.imageshack.us/img845/7127/0vaw.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img845.imageshack.us/img845/7127/0vaw.jpg

**Comment by Necrofilo** [comment]
Si, hasta la fecha a mi tampoco me ha dado el logro, y solo nos falta el de éste boss para poder empezar hard mode.

**Comment by Kiritoo** [comment]
Arreglado y ahora entregará el loot siempre.
Falta compilar
