### ISSUE TITLE
[spell-carga feral(felino)+ abalanzarse]druida 

### ISSUE THREAD

**Issue by jeos-zz** [RoDNet/Bugtracker-Infinium-4.3.4#2533]
http://es.wowhead.com/spell=79830/
descricion:Provoca que saltes tras un enemigo, lo que lo atonta durante 3s.

abalanzarse
http://es.wowhead.com/search?q=abalanzarse#abilities

descripcion:Te abalanzas sobre el objetivo, lo que lo aturde durante 4s e inflige 4578p.(+31.8% of attack power)p. de daño de sangrado durante 18s. Hay que acechar. Otorga 1p. de combo.

problema: al usarse cargar el druida sale de acecho y por esta razón no se logra aplicar abalanzarce

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by jeos-zz** [comment]
por que no responden a los informes sobre bug?

**Comment by ghost** [comment]
Porque parece que no hay nadie arreglando los bugs de spell actualmente...hace más de 1 mes que no hay ni un fix de spells ni habilidades, además, varios de esos fixeos de hace más de un mes ni se han aplicado o no se han llegado a arreglar aunque los pusieran como solucionados...

De todos modos, hay muchos reportes más antiguos que este, incluso con 4 meses y ahí siguen sin respuesta. Los que se supone son más urgentes o más sencillos y afectan más a la jugabilidad se van arreglando antes.

**Comment by searum** [comment]
fix
