### ISSUE TITLE
[Misión] Peque necesita un par de zapatos - La feria de la luna negra  (29508)

### ISSUE THREAD

**Issue by RaulioWoW** [RoDNet/Bugtracker-Infinium-4.3.4#2534]
Misión: http://es.wowhead.com/quest=29508/

Descripción: Quizás haya visto a mi yegua, Peque, cerca de los vagones. Tira del carro que transporta algunos animales de nuestro Zoo de Singularidades.

Es una dura trabajadora. ¡No veas cómo gasta las herraduras! Ya es hora de ponerle unas nuevas. Ya he comprado todos los materiales necesarios.

Lo único que necesitas es darles forma en un yunque y ponérselas en las pezuñas a Peque. Es un trabajo rápido y te aportará algunos vales. ¿Te parece? 

Problema: Al culminar la misión y colocar  las herraduras a peque, no te la cuenta como terminada y no es posible entregarla. Por favor vean este problema ya que a muchos nos vendria bien para poder subir un poco mas herreria, ya que en el server es una de las profesiones que mas estä costando subir. Lo he hecho 3 veces para corroborar esto, y definitivamente la quest esta bug . Un saludo

**Comment by redneo** [comment]
Arreglada
