### ISSUE TITLE
NPC:Gran capataz Hola'mahi <Intendente de armaduras de legado>

### ISSUE THREAD

**Issue by patriccio** [RoDNet/Bugtracker-Infinium-4.3.4#2535]
hola a los gm,
npc: http://es.wowhead.com/npc=12795
probrema: no vende el set cazador Brutal Gladiator's Pursuit( http://es.wowhead.com/transmog-set=717)

**Comment by Sagittariu5** [comment]
Sería bueno que lo implementaran en la alianza también.

**Comment by Monleon** [comment]
Añadido
