### ISSUE TITLE
Bancal del Magister Modo Heroico dice para mas de 65 y un 85 no deja??

### ISSUE THREAD

**Issue by Cantadal** [RoDNet/Bugtracker-Infinium-4.3.4#2536]
Quiero hacer el bancal del magister en modo Heroico, en Queldanas y dice que no es posible hacerla para level inferior a 65, yo tengo level 85. gracias

**Comment by c0iba** [comment]
para hacer bancal en hero tienes que hacer una saga de quest para que te la desbloquee. http://es.wowhead.com/quest=29682/ . hace un mes intente hacerlas y una de ellas estaba bug. suerte.

**Comment by redneo** [comment]
La mision 11492 que es la que pedia entrar, ya no existe, he quitado el requerimiento de la mision para poder entrar.
