### ISSUE TITLE
Feria de la Luna Negra: Mision peque necesita unos nuevos zapatos

### ISSUE THREAD

**Issue by cuspyg** [RoDNet/Bugtracker-Infinium-4.3.4#2537]
En la misión de la feria de herrería, hay que hacer unas herraduras para un caballo llamado Peque, pero al intentar ponerlas usa el objeto ( se consume), pero no cuenta como completado. Una pena, ya que, esos 5 puntillos de herrería vendrían de lujo.

Gracias.

**Comment by redneo** [comment]
direccion de wowhead de la mision¿?¿?¿?¿?

**Comment by redneo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2534

Duplicado
