### ISSUE TITLE
[Items/Objetos] Festín de marisco magnífico

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2538]
Buenas!
• Nombre: Festín de marisco magnífico
• Enlace: http://es.wowhead.com/item=62290
• Descripción: Uso: ¡Saca un festín de marisco para alimentar a todo tu grupo o banda!
• Problema: Al hacer click no funciona para nadie del grupo/banda. Debería dar un buff especifico para cada clase dependiendo de la funcion (tanque, dps o heal) despues de estar 10 seg. comiendo.
Gracias!

**Comment by Wiinter** [comment]
#1811
