### ISSUE TITLE
Misión: La ventaja del pícaro

### ISSUE THREAD

**Issue by Shymast** [RoDNet/Bugtracker-Infinium-4.3.4#2541]
No aumentan las cantidades de veces que practicaste y queda 3/0. No se puede avanzar.

**Comment by redneo** [comment]
http://es.wowhead.com/quest=26946

Sueltala y vuelve a coger la mision.

**Comment by Taysuke** [comment]
Yo tengo este mismo problema, pero aun soltando la misión y volviendo a cogerla, el bug sigue sin solucionarse, lo he intentado numerosas veces e incluso borrado la carpeta "Cache" antes por si ese fuese el problema y no da resultados. ¿Alguna idea?
