### ISSUE TITLE
[NPC/Misión] Sauranok el Místico

### ISSUE THREAD

**Issue by moriaar** [RoDNet/Bugtracker-Infinium-4.3.4#2542]
Este NPC no está, o al menos, no está en el sitio que te indica la misión http://es.wowhead.com/quest=28909/

Se supone que está al lado de Garrosh Grito Infernal pero ahí no está.

Aquí está el NPC:

http://www.wowhead.com/npc=42637

**Comment by redneo** [comment]
Tendria que salir

**Comment by paellaencol** [comment]
Abro un reporte de nuevo, ya que sigue faltando https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2950

**Comment by redneo** [comment]
Sigo diciendo que esa mision es parte de una cadena MUY larga de misiones que te llevan a Tierras altas en el lado Horda.

He visto que alguien se ha animado a ir reportando las del principio (Ahora no encuentro el ticket :S)
