### ISSUE TITLE
[Misión]Aldrassil: Toque de rejuvenecimiento.

### ISSUE THREAD

**Issue by Kitsune1love** [RoDNet/Bugtracker-Infinium-4.3.4#2543]
Hay que usar Rejuvenecimiento con Centinelas Heridas pero no las cura, no se puede hacer más misiones en Aldrassil si no se hace esta misión antes.

EDITADO:
- Zona: Aldrassil
- Nivel: 5
- Clase: Druida
  La misión la da Mardan Fuerterroble, las centinelas que hay que curar están en el recibidor de Aldrassil, agachadas y les falta algo de vida, se les puede tirar el hechizo pero no te cuenta como que la hayas curado.
  ![wowscrnshot_110313_101121](https://f.cloud.github.com/assets/5839532/1460725/2b9228f6-4468-11e3-8165-0e0fd8e771db.jpg)

**Comment by Kitsune1love** [comment]
Ya...no pude ponerte la dirección de wowhead porque no la encontré, vuelvo
a la ciudad y te saco una imagen y la descripción de la misión.

**Comment by redneo** [comment]
Ponme algun dato de la misión, direccion de wowhead de la misma, quien la da, la direccion de los centinelas... algo, pq por Toque de rejuvenecimiento no me sale nada en wowhead.

**Comment by redneo** [comment]
Arreglada, deja la mision y vuelve a cogerla, te contara al sanar un centinela
