### ISSUE TITLE
[Misión][Isla de Quel'Danas] Thalorien Buscalba (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2544]
Buenas.
• Nombre: Thalorien Buscalba
• Enlace: http://es.wowhead.com/quest=24535
• Descripción: Visita los restos de Thalorien Buscalba y obtén su bendición para blandir Quel'Delar. 
• Problema: No están los Restos de Thalorien Buscalba (http://es.wowhead.com/npc=37552) en La Cicatriz Muerta, por lo tanto no se puede continuar la misión.
• Observaciones: Según los comentarios del wowhead, al hablar con los restos aparece el PNJ Thalorien Buscalba (http://es.wowhead.com/npc=37205), lo ayudas a matar adds y te da la misión como completa.
Gracias y hasta luego.

**Comment by Wiinter** [comment]
Para la horda tampoco funciona : http://es.wowhead.com/quest=24563

**Comment by ghost** [comment]
Bueno, hoy 7 de agosto fui a ver y están los restos y el fantasma. Solo falta la interacción con los jugadores y listo :D
Nos vemos!
