### ISSUE TITLE
Misiones de la Feria bug

### ISSUE THREAD

**Issue by Szajil** [RoDNet/Bugtracker-Infinium-4.3.4#2545]
las misiones "Objetivo : tortuga" , "La bala humana",  y  "Estandartes por doquier" no van 
"Estandartes por doquier" http://es.wowhead.com/quest=29520/ despues de hacer el estandarte, lo planta pero no se ve y no da por completada.....
"La bala humana" http://es.wowhead.com/quest=29436 no te lanza lejos y no te deja desplegar alitas....
 "Objetivo : tortuga" http://es.wowhead.com/quest=29455 lanza los aros pero ninguno llega a la tortuga...y he probado muchisimas veces

**Comment by redneo** [comment]
Estandartes por doquier, creo que la arreglé ayer, hasta el proximo mes no la probais :S
