### ISSUE TITLE
[Guerrero] No ataca

### ISSUE THREAD

**Issue by Inraad** [RoDNet/Bugtracker-Infinium-4.3.4#2546]
Acabo de empezar con un Orco Guerrero, y no puedo ni atacar automáticamente sin utilizar la habilidad específica, es decir, si paso el ratón, por encima de un enemigo el cursor se pone como una mano no como una espada y por tanto al darle boton derecho para que ataque no hace nada. 
![bug no ataca](https://f.cloud.github.com/assets/5843187/1460918/cea3c3ee-447f-11e3-96ae-18bdcc632359.jpg)

**Comment by DatJetto** [comment]
CREO, pero solo CREO, que es por que no has activado la facultad de Actitud de Batalla.

Otro motivo puede ser que el pnj sea neutral y no le puedas pegar, pero dudo de lo 2º.
