### ISSUE TITLE
[Guerrero] Bug Cargar 

### ISSUE THREAD

**Issue by Inraad** [RoDNet/Bugtracker-Infinium-4.3.4#2547]
A niveles iniciales no puedo usar cargar, me dice que no estoy en actitud de batalla, lo cual no tiene sentido cuando es la única actitud disponible al inicio 

Edito:

Ha sido un fallo mio, que estaba un poco torpe antes por lo que se vé, perdonad las molestias y no se como se borra el post.

![bug cargar](https://f.cloud.github.com/assets/5843187/1460923/1e064786-4480-11e3-9831-048e91735fec.jpg)

**Comment by Ceslick** [comment]
Por lo que veo no tienes ni la actitud activada

**Comment by Inraad** [comment]
Cierto, perdonad ha sido un fallo mio estaba torpe esta mañana

**Comment by Wiinter** [comment]
Si te fijas debajo de donde pones un comentario pone "Comment" y al lado " Comment&Close" pues le das ahi y lo cierras y es como si lo hubieras borrado.

**Comment by Inraad** [comment]
Ok, gracias
