### ISSUE TITLE
[Sacerdote] Disipar magia

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#255]
En la rama sombras, al usar disipar magia, no hace absolutamente nada, ni siquiera el efecto de disipar.

Si funciona en las ramas Disciplina y Sagrado

Enlace: http://www.wowhead.com/spell=528/

Descripción dentro del juego:
![disipar](https://f.cloud.github.com/assets/4663665/758482/23803278-e736-11e2-94d3-f7038a430d2e.jpg)

**Comment by searum** [comment]
funciona perfectamente

**Comment by ghost** [comment]
Efectivamente ya funciona bien... gracias por arreglarlo si fuiste tu xd.
