### ISSUE TITLE
mision bug en infralar

### ISSUE THREAD

**Issue by kentar** [RoDNet/Bugtracker-Infinium-4.3.4#2551]
pues como dice el titulo en infralar ay una mision bug que te corta la cadena para poder  acceder al portal que te lleva hacia los therezanes la mision se llama vendaval violento y aunque te sale como completada al hacer los objetivos que te pide no puedes entregarla y hacer otras misiones de ahi

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by redneo** [comment]
Npc que tendrias que entregar http://es.wowhead.com/npc=42467 la mision http://es.wowhead.com/quest=26426

Tendria que haber cerrado el post por falta de datos.

Arreglado
