### ISSUE TITLE
Falta de objetos en los vendedores de joyeria

### ISSUE THREAD

**Issue by mccelobb** [RoDNet/Bugtracker-Infinium-4.3.4#2552]
http://es.wowhead.com/npc=44583 no esta vendiendo http://es.wowhead.com/item=52188 ni http://es.wowhead.com/item=20815
Screenshots:
![wowscrnshot_110313_151713](https://f.cloud.github.com/assets/3194580/1461408/2f83b8aa-44ac-11e3-8895-2c55a4f88f32.jpg)
![wowscrnshot_110313_151709](https://f.cloud.github.com/assets/3194580/1461409/2f83c444-44ac-11e3-8e3a-6f406ed7a0a0.jpg)
![wowscrnshot_110313_151704](https://f.cloud.github.com/assets/3194580/1461410/2f83f7f2-44ac-11e3-9cee-11704fd5669e.jpg)
![wowscrnshot_110313_151716](https://f.cloud.github.com/assets/3194580/1461411/2f843f28-44ac-11e3-9196-5ffef5c9a07f.jpg)
![wowscrnshot_110313_151717](https://f.cloud.github.com/assets/3194580/1461413/2fd07942-44ac-11e3-853e-309296b9b7a8.jpg)
![wowscrnshot_110313_151658](https://f.cloud.github.com/assets/3194580/1461414/2fd0799c-44ac-11e3-90bd-dd533b02eaa3.jpg)
![wowscrnshot_110313_151711](https://f.cloud.github.com/assets/3194580/1461412/2fd01f1a-44ac-11e3-84d4-c253c5b6041e.jpg)
![wowscrnshot_110313_151706](https://f.cloud.github.com/assets/3194580/1461415/303812b4-44ac-11e3-9ad9-ec2e1da9b153.jpg)
![wowscrnshot_110313_151700](https://f.cloud.github.com/assets/3194580/1461416/3038a8c8-44ac-11e3-8e8f-0b5cc59fddc0.jpg)

**Comment by mccelobb** [comment]
Mrd salieron todas desordenadas xD

**Comment by redneo** [comment]
arreglado, mira en la ultima pagina
