### ISSUE TITLE
Palabra de gloria, Paladin sagrado

### ISSUE THREAD

**Issue by meybon** [RoDNet/Bugtracker-Infinium-4.3.4#2553]
http://es.wowhead.com/spell=85673/

Esta curando alrededor de 4-5k mas con 1, 2 o 3 cargas, podría no ser mucho pero a esto hay que sumarle el bug del glifo gran palabra que hace curarte un 50% de la cura por ticks.

El glifo como ya se sabe no va prácticamente en nada a como debería.
Debería reducir la sanación un 50% y aun así se cura mas de lo que debe. Ademas ese 50% que reduce lo debería cura los segundos siguientes por ticks, que eso si lo hace pero no bien porque no cura el 50% integro.

Resumiendo. con 3 cargas pone que debería curar 20k (al estar el glifo tendrían que ser 10k) y cura 25k mas 3 ticks de 1.6k y aveces de 3k.

Esto hace que se tenga una cura de 10k (5k + 4,8k o 6.2k (si salta el tick alto)) extra con indiferencia de las cargas que tienes, en todas cura 4-5k mas y los ticks lo mismo.

Issue #2443 , como se ve todos los problemas son por el glifo este que esta siempre aunque no lo tengas.

**Comment by Ceslick** [comment]
¿Has hecho la prueba de la cura sin talentos? Porque hay varios que aumentan la sanación como conviccion (que salta con cada critico y aumente la sanacion hasta un 9%) o el de protección que tambien aumenta un tanto %.

Ya decia yo que habia muchos palas helers en la horda ultimamente XD

**Comment by kaseO** [comment]
Solo como dato doy que 45 min en una arena contra un paladin heal con 0 de mana toda la arena porque estaba quemandole, y no muere!!! es imposible matarlos, si no podeis arreglarlo podriais desabilitar palabra de gloria, igual que al druida le quitasteis Rugido salvage, o al druida balance el Rayo solar, spells basicas en respectivas clases.

**Comment by meybon** [comment]
El problema de todo ha sido volver a poner un bug que ya estaba arreglado, es lo principal. Al hacer eso se han cargado las curas en las 3 ramas.

**Comment by crowel** [comment]
![wowscrnshot_110413_222819](https://f.cloud.github.com/assets/3537253/1469216/05cba844-459f-11e3-8587-31aeba514472.jpg)

Foto de una sanación realizada con palabra de gloria 1 carga.
Fijaros el registro de combate.

**Comment by crowel** [comment]
A los paladines actualmente no le hace falta castear sus curas.

**Comment by meybon** [comment]
A esos 42k sumarle los ticks que son cosa de 5k mas

**Comment by kaseO** [comment]
Imposible bajarse a un paladin en arenas, esta super op.

**Comment by Fragis** [comment]
Castear sus curas? es que no les hace falta ni tener mana...

**Comment by meybon** [comment]
Mas que deshabilitar la spell que oye, es el glifo que estaba arreglado y volvió a aparecer el que causa todos los problemas de curas overs en heal y nerf en repre, estaba arreglado asi que creo que no sera muy difícil volverlo a poner bien, creo.

**Comment by kaseO** [comment]
con 0 de mana durante 45 min se levantan enteritos y sin castear, osea que tenemos a heals que sin mana y sin castear se levantan enteros y a sus compañeros tambien...

**Comment by meybon** [comment]
El post esta hecho, no hagamos un debate de algo que no tiene discursion que asi fijo que no hacen caso, punto.

**Comment by Ceslick** [comment]
Crowel, no se de donde te sacas esos 45 k de una sola carga critica, yo con buffos,talentos,etc... como máximo de una carga 19k. Los 50 k criticos vienen cuando son las 3 cargas.

**Comment by Dekadencee** [comment]
Fixeado: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2511
