### ISSUE TITLE
Mazmorra: El Núcleo Pétreo (Hc)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2554]
Enlace: http://es.wowhead.com/zone=5088/

Problema: ninguno de los 4 bosses está tirando puntos de justicia.

Observaciones: en general la mazmorra ha quedado bastante bien scripteada.

Edito: ojo! a los bosses les está afectando cualquier tipo de control de masas 
http://es.wowhead.com/npc=43438
http://es.wowhead.com/npc=43214
http://es.wowhead.com/npc=42188
http://es.wowhead.com/npc=42333

**Comment by searum** [comment]
fix
