### ISSUE TITLE
[NPC] Huargen arrasador

### ISSUE THREAD

**Issue by Gurh** [RoDNet/Bugtracker-Infinium-4.3.4#2557]
Buenas, al hacer la quest "Evacúa la plaza de los mercaderes" debes ir abriendo puertas, de las que sale un mercader y a veces un huargen al que debes matar y cuenta también para la quest "La hora del caos".

El problema es que el huargen que sale no es un objetivo atacable, al intentar atacarle no deja.

Foto-> http://i39.tinypic.com/mk7uwn.png

Evacúa la plaza de los mercaderes: http://es.wowhead.com/quest=14098

La hora del caos: http://es.wowhead.com/quest=14093

NPC Huargen arrasador: http://es.wowhead.com/npc=35660#objective-of

**Comment by redneo** [comment]
Arreglado
