### ISSUE TITLE
Energía del Rogue

### ISSUE THREAD

**Issue by Darkerux** [RoDNet/Bugtracker-Infinium-4.3.4#2563]
La energía tras usar habilidades sube automáticamente al 100%,lo que molesta mucho en PBE y en PvP debido a que no saber correctamente la energía que llevas,lo que molesta demasiado,soluciónenlo.

**Comment by ghost** [comment]
Ya está reportado, fijate antes de reportar las cosas:

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1719
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1504

El problema es el mismo en ambos posts en realidad.
