### ISSUE TITLE
misiones: tierra inquieta y toque de rejuvenecimiento 

### ISSUE THREAD

**Issue by cento46** [RoDNet/Bugtracker-Infinium-4.3.4#2564]
ola tengo un error de bugs en dos misiones:
tierra inquieta. que realizo lo de los tambores pero no surge ningún efecto.
la otra es.
toque de rejuvenecimiento. que lo realizo y tampoco surge nada 
( realizaros si que los realiza pero no contabiliza nada)

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
