### ISSUE TITLE
[Logro] Lo tenía en la mano (Arqueologia) 

### ISSUE THREAD

**Issue by RaulioWoW** [RoDNet/Bugtracker-Infinium-4.3.4#2565]
Logro: http://es.wowhead.com/achievement=4854/

Encuentra un artefacto poco común.
Requisitos

```
Encuentra un artefacto poco común.
```

Ganancias

```
Deberías obtener el título "Profesor agregado"
```

Problema: Ya van 2 artefactos pocos comunes que encuentro y no me toma el logro, por lo tanto tampoco me da el titulo que deberia otrorgar. 
Un saludo!

**Comment by Dreadwolver** [comment]
a mi igual me susedio tengo un artefacto de los elfos de la noche

**Comment by Dekadencee** [comment]
Fixed
