### ISSUE TITLE
Sabotaje!

### ISSUE THREAD

**Issue by erdricklol** [RoDNet/Bugtracker-Infinium-4.3.4#2566]
Esta misión no funciona.Cuando intentas utilizar el item no ocurre nada, no deja utilizarlo or mas clicks que le des al item no va la misión.

Prueba: http://i.imgur.com/imvY77s.jpg

Saludos.

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
