### ISSUE TITLE
Palabra de Gloria.

### ISSUE THREAD

**Issue by erdricklol** [RoDNet/Bugtracker-Infinium-4.3.4#2568]
Hola, vengo a postear un bug del paladín que resulta que cuando lanzas Palabra de Gloria sana lo que debería hasta ahí bien pero sana también con efecto periodico sin glifo.

No sé muy bien lo que cura esta spell pero me dá que cura como si tuvieras el glifo de Gran Palabra ya que cura muy poquito a mi nivel solo me ha llegado a curar unos 400-450 puntos de vida a 3 cargas de poder sagrado.

Pruebas: http://i.imgur.com/jWfoDyv.jpg

Saludos.

**Comment by meybon** [comment]
Ya que tiene que ver con un post mio enlazo con otro post si no te importa para que esten "unidos", Saludos.
Issue #2511
