### ISSUE TITLE
[Paladín Reprensión] Exorcismo.

### ISSUE THREAD

**Issue by erdricklol** [RoDNet/Bugtracker-Infinium-4.3.4#2569]
El Id de este hechizo creo que es este: 122032 pero es de wowhead.

http://es.wowhead.com/spell=122032/exorcismo, aqui pongo el enlace de la habilidad pero siendo de wowhead no sé si servirá.

Explicación del la descripción del hechizo: Inflige daño sagrado a distancia,Lanzarlo lleva mucho tiempo,así que evita lanzarlo cuerpo a cuerpo.

El hechizo en sí hace el daño que dice pero aparte de eso tiene algo mal.Que al usar este hechizo cuando hace daño deja un debuff que hace daño periodico cosa que no debería de suceder.

Aqui dejo una foto del debuff que deja al usarlo, espero que así valga el post.

Screen: http://i.imgur.com/COY1pH9.jpg

Saludos y suerte,

**Comment by ghost** [comment]
tienes que poner el enlace a la habilidad y el ID, además de como debería funcionar.

http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by erdricklol** [comment]
Actualizado,dime si hay algo erróneo para corregirlo y si ese no es el id dime alguna pagina que sea de cata o tenga enlaces de eso yo siempre lo saco todo de wowhead las id pero la descripción la puse del propio juego.

Saludos.

**Comment by ghost** [comment]
Wowhead está actualizado para MoP, la nueva expansión. Es mejor poner los enlaces de cata.openwow.com o de wow.freakz.ro

En cuanto a la ID, hay un addon llamado IDtip que se pone en la carpeta addons de la carpeta world of warcraft y te muestra el ID de todas las habilidades, talentos y bufos del juego cuando pones el ratón encima, junto a la descripción.

Además, tampoco hace falta que subas las fotos a un servidor externo como imgur.com, con arrastrar la imagen a tu reporte (si estás en modo edición) la foto se subirá automáticamente a github y se podrá visualizar directamente sin necesidad de ir a otras páginas ni clickar enlaces.

Saludos! :)

**Comment by erdricklol** [comment]
Vale lo cambiaré todo cuando tenga tiempo.Saludos.

**Comment by Dekadencee** [comment]
Debería estar fixeado, necesita testeo, tras la próxima compilación y restart comprobadlo, recordad que en el server info debe aparecer una fecha de compilación del rodemu superior a la de este comentario.

Un saludo ^^
