### ISSUE TITLE
[DK] Cadenas de Hielo y Sabañones

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#257]
Sabañones rango 2: Las víctimas de tu enfermedad Fiebre de Escarcha quedan heladas, lo que reduce su velocidad de movimiento un 50% durante 10 s, y tus Cadenas de hielo inmovilizan a los objetivos durante 3 s.
Enlace: http://es.wowhead.com/spell=50041

Cadenas de hielo: Encadena al objetivo con cadenas heladas, lo que reduce un 60% su velocidad de movimiento durante 8 s. También infecta al objetivo con Fiebre de Escarcha.
Enlace: http://es.wowhead.com/spell=45524

Fiebre de escarcha: http://es.wowhead.com/spell=55095

Primer problema: cadenas de hielo NO inmovilizan al objetivo (teniendo el talento sabañones).

Segundo problema: como dice la descripción, cadenas de hielo infectan al objetivo con Fiebre de Escarcha, lo que sucede es que Fiebre de Escarcha ROMPE las cadenas de hielo al hacer daño, lo cual no debería de suceder.

**Comment by searum** [comment]
fix
