### ISSUE TITLE
NPC Bastión fauces de madera: Drizle, Kernda y otros

### ISSUE THREAD

**Issue by Plicket** [RoDNet/Bugtracker-Infinium-4.3.4#2571]
1. El npc http://www.wowhead.com/npc=47556 para terminar la misión http://www.wowhead.com/quest=28362 no se encuentra en Felwood.
2. La misión iniciada por http://www.wowhead.com/item=20741 , http://www.wowhead.com/quest=8470, después de cumplir los requisitos de ser neutral con la reputación Bastión fauces de madera, entras a la cueva entre felwood, moonglade y wintergrasp pero no encuentras a nadie a quién entregar la misión, teniendo que ser http://www.wowhead.com/npc=11558.

**Comment by redneo** [comment]
Arreglado
