### ISSUE TITLE
[Misión] Corona de Hielo - Emperajamientos

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2572]
http://es.wowhead.com/quest=13147

Vas al orbe de Dominio para que te de el acechador ágil, y entonces con él, provocas 5 peleas tirandole piedras a los trabajadores.

No va el orbe que te da el acechador.

**Comment by redneo** [comment]
Ya va el orbe

**Comment by Wiinter** [comment]
Ahora el problema es que el acechador lo ve todo el mundo y te ataca todo el mundo cuando debería ser amistosos. Además sus habilidades de lanzar la roca no funciona bien y no te cuenta para la misión.

Abrelo de nuevo red si puedes.
