### ISSUE TITLE
[Misión] Corona de Hielo - Abundante Generosidad

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2573]
http://es.wowhead.com/quest=13146

Vas al orbe y coges tu acechador ágil y entonces mueves las bombas hasta las abominaciones y haces explotar la bomba.

Vas al orbe y no te da el acechador.

**Comment by redneo** [comment]
cual es el orbe???

**Comment by redneo** [comment]
Ya funciona el orbe cuando caiga el server.

**Comment by Wiinter** [comment]
Ahora el problema es que el acechador lo ve todo el mundo y te ataca todo el mundo cuando debería ser amistoso. Además sus habilidades de coger la bomba y llevarla a una abominacion no van, la bomba no se mueve de sitio..

Abrelo de nuevo red si puedes.
