### ISSUE TITLE
[Misión] Cuenca de Sholazar - Fuerza secreta de los corazon Frenetico

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2574]
http://es.wowhead.com/quest=12760

Puedes hacer la mision perfectamente pero a la hora de ir a completarla, no esta el npc que te completa la misión.
Chamán Jakjek (http://es.wowhead.com/npc=28106)

**Comment by redneo** [comment]
arreglado
