### ISSUE TITLE
Npc: Svala Tumbapena (Pináculo de Utgarde)

### ISSUE THREAD

**Issue by Plicket** [RoDNet/Bugtracker-Infinium-4.3.4#2575]
En la mazmorra El Pináculo de Utgarde, la 1ra jefe..., http://es.wowhead.com/npc=26668 después de matar a los enemigos cerca (sentados), ella se convierte, pero no es posible de atacar, se queda neutral. Por lo tanto, el logro no se consigue... Esto fue en normal, ya que en heroico si lo logré...

**Comment by Wiinter** [comment]
No me hagas mucho caso, pero diria que el primer jefe que te encuentras en Pináculo.

**Comment by juaks** [comment]
Este boss funciona correctamente.

**Comment by Wiinter** [comment]
Incluso puedes sacar el logro.
