### ISSUE TITLE
[Misión] Monte Hyjal (Arboleda de Aessina) - El milagro de Aessina

### ISSUE THREAD

**Issue by Borkaz-zz** [RoDNet/Bugtracker-Infinium-4.3.4#2577]
El milagro de Aessina

Enlace: http://es.wowhead.com/quest=25372/

En esta misión tenemos que llevar el Corazón del Bosque (http://es.wowhead.com/item=56057) a un NPC llamado Hamuul Tótem de Runa (http://es.wowhead.com/npc=52838). El problema viene cuando este NPC no se encuentra dónde debería, delante de la fuente, para recibirnos y completar la misión.

**Comment by redneo** [comment]
![wowscrnshot_111213_083941](https://f.cloud.github.com/assets/1163425/1519832/a56d19ae-4b6d-11e3-87fe-8ee59c1f01d9.jpg)

Si que está
