### ISSUE TITLE
[Misión] Las Mil Agujas - La bruja anciana

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2578]
http://es.wowhead.com/quest=28140

Tienes que desactivar un controlador.

Vas al controlador pero no puedes desactivarlo.

**Comment by Wiinter** [comment]
He estado probando varias veces, y no se como completarla. No me va de ninguna forma de la que he probado, con traje sin él. Llendo a la zona, salir y volver a entrar. Borrando cache. Si me puedes ayudar @redneo , te estaría agredecido

**Comment by redneo** [comment]
Ya, seguro que va teniendo el traje en la zona.

**Comment by Wiinter** [comment]
Red hoy lo he vuelto a intentar despues de que se cayera el server y no he conseguido hacer qe me complete, a ver si me puedes ayudar.

**Comment by Wiinter** [comment]
No se puede completar. No la puedes completar. Te marca como libertado y te marca la quest como completada pero no la puedes completar en ningun sitio. Diria qe es autocompletable y asi te permite completar la sigueiente que te da al completar esta.

**Comment by redneo** [comment]
¿?

Nivel: 45
Requiere nivel 38
Lado: Ambos
Empieza: Lakota Son del Viento
Compartible
Dificultad: 38  41  43  48  55
Añadido en el parche 5.3.0

a ver si leemos un poco mas los logs cuando terminamos las misiones.
