### ISSUE TITLE
Paladin reprension, Veredicto del templario

### ISSUE THREAD

**Issue by meybon** [RoDNet/Bugtracker-Infinium-4.3.4#2579]
http://es.wowhead.com/spell=85256/

De vez en cuando, veredicto solo cuesta 1 carga, sin tener propósito claro esta, usas veredicto pero solo te consume una carga dejando 2 sin consumir.

**Comment by sprin69** [comment]
creo k tmb pega d menos

**Comment by searum** [comment]
esto va bien
