### ISSUE TITLE
[DK] Frío hambriento

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#258]
Como se ve en la descripción, congela durante 10 sec, el problema es que, cualquier enfermedad que haga daño al objetivo ROMPE el hielo, y esto NO debería de suceder según la descripción.

Enlace: http://es.wowhead.com/spell=53570/

Descripción dentro del juego:

![frio hambriento](https://f.cloud.github.com/assets/4663665/758515/345c0ce0-e739-11e2-9d08-c6d639e30aba.png)

**Comment by searum** [comment]
fix
