### ISSUE TITLE
[Dk] Doble empuñadura.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#2585]
Bueno esto es algo que estuve revisando detenidamente desde hace tiempo ya que muchas personas usan el dk escarcha y no querían soltar información.

Lo que ocurre con el dk y la doble empuñadura (Dos armas de una mano) es que esta pegando 2 veces con el arma de mano izquierda cuando debería ser tan solo 1 vez,,, Para ser mas especifico ocurre lo siguiente "El dk da 1 golpe de mano derecha y 2 de mano izquierda" cuando debería ser 1 y 1... Aquí la foto que demuestra eso:

http://s2.subirimagenes.com/otros/8686937wowscrnshot110613193.jpg

**Comment by Kiritoo** [comment]
Link del talento? Con su respectiva id.

**Comment by ghost** [comment]
http://wow.freakz.ro/spells.php?spell=65661

Por cierto, ya estaba reportado https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2108

**Comment by ghost** [comment]
En el reporte definitivo de clases aparece como FIXEADO. Se puede cerrar, no? junto a este https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2108

**Comment by Kiritoo** [comment]
Fix falta reinicio.
