### ISSUE TITLE
[Reputaciones]

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2587]
http:/

**Comment by Wiinter** [comment]
A mi hasta hace poco me restaban de unos y me subían de otros. Ahora igual me pasa igual que a ti, ya lo probaré y te cuento.

**Comment by redneo** [comment]
Probad a ir sin NINGUN tabardo

**Comment by ghost** [comment]
<i>Yo iba sin ningún tabardo</i>. MIENTO, iba con el de ventormenta, cuando testee posteo qué pasa.
