### ISSUE TITLE
[Mision] Atacamos!

### ISSUE THREAD

**Issue by Bariloche123** [RoDNet/Bugtracker-Infinium-4.3.4#2589]
No hay forma de hacer la mision, estan muertos donde indica.Y el que entrega la quest, no se mueve.. ID: 11592

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
