### ISSUE TITLE
Bug en el numero de Premios de Dalaran y Sello de campeon. Tengo 400 de c/u

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#259]
![premios de mas](https://f.cloud.github.com/assets/4944904/758519/c5db72fa-e739-11e2-9572-e47fed6a8f1d.png)

No debería tener tantos... No soy el unico con este problema o "beneficio" eh visto a varios pj comprando las monturas y demás del torneo argenta con los sellos del campeón. Realmente deberia tener solo 5 pero luego que actualizaron me aparecieron 400 de cada uno.

**Comment by ghost** [comment]
Lo mismo me paso a mi con los sellos de campeón.

**Comment by crowel** [comment]
Y las muestras de joyeria.

**Comment by Moyax** [comment]
mmm con lo de joyeria no se, como no soy joyero. Crowed tienen muestras de mas?

**Comment by crowel** [comment]
yo 1100, tras la actualizacion más 100 muestras por cada vez que se hace misión.

**Comment by ghost** [comment]
Yo tras la actualización tengo 3000 muestras de joyería xd.

**Comment by lamaza** [comment]
bueno, me retracto

**Comment by crowel** [comment]
@lamaza Se un poco mas humilde y si encuentras un reporte repetido comparte el primer enlace "pienso yo", puede que el no lo viera o se quisiera referir a otro tipo de reporte.
Otra cosa tu también creaste un reporte de baradin ya habiendo uno antes de alizabal y "decidiste" crear otro sin que nadie te dijera nada al respecto, es más, se te añadio el enlace al issue anterior sin comentarios como este, y más aún que ni añadiste el enlace al issue anterior.
Este foro no es para discutir asi que lo dejare aquí, hai que ser un poco más compasible y sobre todo humilde.
Adiós.

**Comment by lamaza** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/8

**Comment by ghost** [comment]
Ya no estan las monedas del bug.
