### ISSUE TITLE
voluntad centrada - sacerdote disciplina

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.3.4#2590]
la spell 45243 se esta activando mucho mas de lo que debe,se debe de activar cuando te meten un golpe mayor al 10% de la vida del sacerdote osea unos 13k de daño o asi dependiendo de la vida del sacerdote i como se ve en la foto el npc me pega 600 de daño i se activa por que si.esto hace que el sacerdote tenga 2k de temple extra cada dos por tres.

http://subefotos.com/ver/?8762ccf9ec4811dd6ee98f5322dbcc1co.jpg#codigos

**Comment by Wiinter** [comment]
Pon la id del spell asi mejor : http://wow.freakz.ro/spells.php?spell=45243

**Comment by ghost** [comment]
Podrías poner pruebas? no me parece muy fiable esto. Dice daño de 10% además de golpes críticos no periódicos, lo cual no sé si se ha tenido en cuenta, porque en la foto <strong>no</strong> se está activando el talento por los 600 de daño que recibes al contrario de como comentas, sino que el buff está a 3 segundos de desaparecer (osea, lleva 5 segundos gastados ya).

**Comment by paellaencol** [comment]
Antes de reportar fíjate bien en leer el talento.
Especialmente la segunda parte del talento, aquella que dice <b>"O recibas un golpe crítico de cualquier ataque no periódico"</b> Es decir, un mob de nivel uno, te hace un crítico de 2 de daño y te debe saltar voluntad centrada. Por tanto el talento y la facultad funcionan a la perfección

De hecho fíjate en el Proc Flags:
- Taken damage from melee auto attack hit
- Taken damage by Spell that use melee weapon
- Taken damage from ranged auto attack
- Taken damage by Spell that use ranged weapon
- Taken Negative spell hit
- Taken Negative Magic spell hit

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/841/neob.jpg/'><img src='http://img841.imageshack.us/img841/7593/neob.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a> 
http://img841.imageshack.us/img841/7593/neob.jpg

P.S. Ya te he visto en bgs que te estás aprovechando del bug de punición-contricción, además en tu captura de pantalla lo demuestra aún mas que vas con esos talentos puestos. Supongo que sabrás que está más que bug (y además bastante gordo), imagino que lo reportarás también.

**Comment by Oscarin** [comment]
en este video se ve como la voluntad salta asta 7 veces seguidas como minimo,a lo que dice ese de que me a visto en bg como mucho me habra visto este mes acer varias bgs i eso que tengo mas de un año el sacer cosa  que uso para acer mazmorras con mi familia no acer bgs con el sacer pero viendo que que lo que mas abunda son sacerdotes,dks,cazas i guerreros me puse a jugar con el sacer aver k esta bug para reportar por que de los echizos que se benefician pocos los reportan i no solo contriccion,
tenia pensado averlo puesto en este post pero me imaginaria k saldria alguno diciendome que tenia que haver echo otro ussue diferente como el primer comentario que dice que tenia que aver puesto la direcion esa.
que yo sepa todos estos echizos de este tipo tienen un tiempo interno de reutilizacion i pasa como el mago fuego que puede tener activa la velocidad llameante si tienes un heal curandote durante un buen rato activa,yo hice la prueba en una mazmorra de nivel bajo i me la corri entera de puerta asta el final con la velocidad llameante activa,con la voluntad parece que pasa lo mismo si te pegan 5 o 6 tios en una bg puedes tener los 2k de temple activos durante un buen rato

 http://www.youtube.com/watch?v=nRjCUwfpw3k&feature=youtu.be

parece que se ve mal el video en hd todavia espero que sea por averlo subido aoramismo i si mañana se ve mal lo vuelvo a subir

**Comment by paellaencol** [comment]
A ver. En el vídeo que has puesto se observa que funciona perfectamente, se te está activando en los golpes críticos recibidos.
No supongas que tiene cd interno cuando no lo tiene. Si lo tuviera blizzard te lo hubiera detallado, como en las habilidades que sí lo tiene, y además previamente te especifica de ello.

P.D. fíjate en la primera palabra que aparece en el talento: <b>Siempre </b>

**Comment by ghost** [comment]
Bueno yo creo que toca leer las cosas bien antes de reportar. De todos modos, parece que oscarin tiene razón, cuando se ha tirado el escudo le ha saltado 2 bufos de voluntad interna sin que le dieran ataques críticos, por lo que parece que sí hay bug...

En cuanto a lo de cds internos y demás...queda claro que no, creo que la descripción del talento está bastante clara y aporta todo lo necesario para su fixeo.

**Comment by Oscarin** [comment]
sino? como el escudo,que te pones a picar bases con el puesto i no te interrumpen el cojer las bases valla tela

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
