### ISSUE TITLE
[NPC Desolace] Furien

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2591]
Enlace: http://es.wowhead.com/npc=35286/#ends

Problema: no se encuentra el susodicho npc, necesario para poder entregar La orden del Jefe de Guerra: ¡Desolace! http://es.wowhead.com/quest=28548

**Comment by paellaencol** [comment]
Guarda relación con https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1592
Al npc de la alianza lo podemos ver los hordas, cuando no deberíamos. Pero es que los hordas no podemos ver al nuestro.

**Comment by redneo** [comment]
Ya se tendria que ver y el de la alianza tambien.
