### ISSUE TITLE
A

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2592]

**Comment by paellaencol** [comment]
DoT ticks do NOT break capping, and they never did.

http://us.battle.net/wow/en/forum/topic/2878770151

**Comment by paellaencol** [comment]
No, a no ser que infrinjan también daño instantáneo (peste devoradora mejorada)

P.d. las canalizaciones tipo "tortura mental" tampoco rompen

Esto está funcionando bien

**Comment by ghost** [comment]
Borro y edito entonces
