### ISSUE TITLE
[Misión] Desolace - Adopción prematura

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2593]
Enlace: http://es.wowhead.com/quest=14246

Descripción: al colocar un "huevo de aguilón" http://es.wowhead.com/item=49014 deberíamos poder defenderlo de dos tipos diferentes de mobs http://www.wowhead.com/npc=35811 http://www.wowhead.com/npc=35750 (ambos aparecerán e intentarán atacar al huevo). Tras haber muertos los asaltantes, un aguilón desafiante http://es.wowhead.com/npc=35752 aparecerá llevándose consigo al huevo, con lo que por tanto esta misión estará completada

Problema: nada de esto sucede, además el huevo tiene vida propia y ataca mobs.

Observaciones: adjunto vídeo http://www.youtube.com/watch?v=50S_7XXxs-s

**Comment by redneo** [comment]
arreglado
