### ISSUE TITLE
aullido de terror

### ISSUE THREAD

**Issue by sprin69** [RoDNet/Bugtracker-Infinium-4.3.4#2594]
este hechizo no funciona correctamente se rompe el hechizo con 1 golpe y en realidad aguanta un daño minimo no se cuanto es

**Comment by nicerdicer** [comment]
Bueno, iba a reabrir este problema, pero ya que lo has hecho tu, #2283
[Aullido de Terror] Brujo Hechizos/Talentos 

ahi esta mi reporte sobre esta habilidad que ya va teniendo cierta antigüedad... y sigue sin solucionarse.

**Comment by ghost** [comment]
Ya reportado, se puede cerrar...

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
