### ISSUE TITLE
sucubo

### ISSUE THREAD

**Issue by sprin69** [RoDNet/Bugtracker-Infinium-4.3.4#2595]
weno este pet de warlock no funciona correctamente lo k le ocurre es k cuando le mandas k atake a alguien el hechizo seduccion solo ataka una vez aunke lo tengas en automatico .
Cuando tienes la pet en pasivo es cuando pasa esto en defensivo si funciona

**Comment by nicerdicer** [comment]
puedo asegurarte que la sucubo funciona bien, yo la uso constantemente en el pvp muy habitualmente en agresiva y realiza las 3 seducciones correctamente.

**Comment by Wiinter** [comment]
Funciona bien. Además de estar mal reportado

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
