### ISSUE TITLE
manafago

### ISSUE THREAD

**Issue by sprin69** [RoDNet/Bugtracker-Infinium-4.3.4#2596]
weno el silencio d este pet no funciona correctamente.

silencia 3 segundos si no corta casteo si corta casteo silencia 6 el fallo es k no silencia 6 sec solo silencia 3 aunke corte casteo

**Comment by ghost** [comment]
Ya está reportado, fíjate antes de reportar, y ya que lo haces hazlo siguiendo las reglas.

http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
