### ISSUE TITLE
Reporte definitivo sobre hechizos de clases.

### ISSUE THREAD

**Issue by redneo** [RoDNet/Bugtracker-Infinium-4.3.4#2597]
Con la intención de tenerlo todo en un mismo post y que este mismo no sea de chateo me gustaria que en este mismo se expusieran los hechizos, talentos, glifos y cosas por el estilo de cada clase que no funciona o funcionan mal.

---

<h3>Cazador:</h3>

---
- Supervivencía:
- Puntería:
- Mascotas:

---

<h3>Paladin:</h3>

---
- Sagrado:
- Reprensión: 
  - <strong> Búsqueda de la justicia:</strong> http://es.wowhead.com/spell=26023/ http://es.wowhead.com/spell=26023/ No da cargas al recibir un efecto de aturdimiento, miedo o immovilizacion #2581 
- Protección: 
  - <strong>Defensor candente</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1959 Al activar este hechizo http://wow.freakz.ro/spells.php?spell=31850 reduce todo el daño recibido un 20% durante 10 segundos (funciona), además si el paladín recibe un golpe mortal durante esos 10 segundos, ese golpe en lugar de matarle sacrifica al "defensor candente" y le cura un 15% de su salud maxima. El problema esta en que el golpe que te va a matar te mata sin importar que lo tengas activo.
    (aunque aparece como fix, no se ha podido reparar bien)
- Glifos:

---

<h3>Mago:</h3>

---
- Generales:
  - <strong> Orbe de llamas</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2205 No se beneficia bien de las estadísticas del mago, tampoco tiene en cuenta los talentos y no se comporta como debe.
  - <strong>Anillo de escarcha</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2386 No congela como debe y <strong> no tiene drs añadidos</strong>.
  - <strong>Absorción de encantador</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1143 Salta sin tener el talento puesto, tal cual explico en el issue.
- Fuego:
- Escarcha:
  - <strong>Dedos de escarcha</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2237 no funciona, no salta como debe, ni da los beneficios que debe.
  - <strong>Orbe de pirofrío</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2205 se beneficia mal de las estadísticas y no se comporta como debe.
  - <strong>Elemental de agua</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2387 No se beneficia bien de las estadísticas del mago.
  - <strong>Barrera de hielo</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1449 Absorbe un 30% de más de base, como si se llevara el glifo.
- Arcano:
  - <strong>GCD</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2065 Algunos hechizos añaden un gcd oculto que te impide castear durante un corto periodo de tiempo. También ocurre en todas las ramas con las habilidades: crear refrigerio, crear gema de maná.
    · <strong>Corte de casteos</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2134 Los hechizos de rama arcana de casteo se interrumpen con el daño.
- Glifos:
  - <strong>Glifo de pirofrío</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2350 No se acumulan los DoT, sigue dejando ralentización.
  - <strong>Glifo de armadura de escarcha</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2391 no existe ningún inscriptor que lo tenga.
  - <strong>Glifo de reflejo exacto</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/307 Las copias no lanzan otros hechizos.

---

<h3>Guerrero:</h3> 

---
- Hechizos:

· <strong>Golpe Heroico: </strong> http://cata.openwow.com/spell=78 No contempla las reducciones de daño, excepto las del temple. #2246 #2125 

· <strong>Ejecutar</strong> http://es.wowhead.com/spell=5308.No consume ira, por tanto no augmenta el daño en funcion de la ira consumida. #1432 

· <strong>Reflejo de hechizos</strong> http://cata.openwow.com/spell=23920 Está reflejando hechizos AoE y no los que van al guerrero #2526 

· <strong>Salto Heroico</strong> http://es.wowhead.com/spell=6544#. Te permite subir a sitios donde no debería. #2373 

· <strong>Aullido Perforador</strong> http://wow.freakz.ro/spells.php?spell=12323 Saca del sigilo. #1996 
- Armas:

· <strong>Seccionar mejorado</strong> http://cata.openwow.com/spell=12668 https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1640 Se está aplicando el efecto de "seccionar mejorado" al utilizar tan solo un "seccionar", cuando debería producirse al utilizar "seccionar" por segunda vez sobre un objetivo que ya padezca el perjuicio de "seccionar"
- Furia:

· <strong>Furia Enfilada</strong> Funciona si solo llevas una de una mano y se buguea y haces más daño si llevas una mano y otra de dos manos. #2337 
· <strong>Arremetida Enfurecida</strong> http://es.wowhead.com/spell=85288/ Pega de más #2117 
· <strong>Segundo aliento</strong>(https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2690): Esta saltando con algunos buffos, con los propios del warrior no
- Protección: 

· <strong>Venganza</strong> http://wow.freakz.ro/spells.php?spell=93098 Va como quiere, no genera un 5% del daño recibido en poder de ataque. A veces genera más, a veces menos, a veces te llena toda la venganza. #2338 

· <strong>Maestria en Actitudes:</strong> http://wow.freakz.ro/spells.php?spell=12678. No conservo los 25 de ira al cambiar de actitud. #2074 
- Glifo: 

· <strong>Glifo de Machaque Colosal:</strong> http://es.wowhead.com/spell=89003. No esta aplicando el efecto de herder de armadura. #2158 

---

<h3>Brujo:</h3>

---
- Hechizos:
  - <strong>Quemar alma</strong>: http://wow.freakz.ro/spells.php?spell=74434. No se consume si invocas los demonios y te permite castear otra habilidad beneficiosa. #2343 
  - <strong>Invocar Infernal</strong>: http://wow.freakz.ro/spells.php?spell=1122. Hace sus hablidades pero no está pegando a quien tiene el Terror de Fatalidad. Además su habilidad está haciendo muy poco daño, unicamente esta haciendo el daño base #579 --> <strong>Descarga de fatalidad </strong>http://wow.freakz.ro/spells.php?spell=85692 Está haciendo el daño base, no esta contando el poder con hechizos.
  - <strong>Invocar Guardia Apocaliptico:</strong> Solo pega a melee, no hace sus habilidades. #578
  - <strong>Guardia Demoniaco del Terror de Fatalidad </strong> http://es.wowhead.com/npc=50675 El demonio invocado hace 1 punto de daño a mele #1047 
  - <strong>Aullido de Terror:</strong> http://es.wowhead.com/spell=5484 Soporta un cierto daño periodico antes de ser eliminado por este, en cambio el mas minimo daño (directo o periodico) presente en el objetivo, cancela el efecto al instante.  #2283
  - <strong>Armadura vil:</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3072 No da la sanación
- Destrucción: 
  - <strong>Sombras y llamas</strong>: http://cata.openwow.com/spell=17801 No está poniendo el buffo con Incinerar #2420 
  - <strong> Parasitar alma </strong>: http://cata.openwow.com/spell=30295 Sana un 6% de tu salud maxima con Conflagar e Incinerar y no debería. No regenera el 4% de mana ni salta Reposicion que genera un 1% de mana cada 10 segundos. #1677 #2321 
- Demonología:
      - <b>Infierno</b> #2836 No permite castear Llamas Infernales en movimiento, cuando deberia poderse. En cambio, si se activa y luego te mueves se mantiene, aun que desaparece la barra de canalización http://wow.freakz.ro/spells.php?spell=85105.
- Affliccion: 
  - <strong>Pandemia: </strong>http://wow.freakz.ro/spells.php?spell=85099, http://wow.freakz.ro/spells.php?spell=85100.No refresca aflicción inestrable cada vez que Drenar Alma inflinge daño. #2438 
  - <strong>Poseer</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2651 No está curando como debe cuando el daño infligido es crítico. Hace un daño fijo, aunque escala con el poder con hechizos.
  - <strong> Aflicción inestable</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2656 Hace justo la mitad de daño.
- Mascotas:
  - Coste de los hechizos de las mascotas, hay varias mascotas que no tiene el valor fijo de coste de mana de sus hechizos y entonces cogen en porcentaje el mana máximo bug de antes, que era totalmente desorbitado.  #2202
  - <strong>Manáfago: </strong> 
    - <strong> Inteligencia vil </strong>http://wow.freakz.ro/spells.php?spell=54424. El buffo solo funciona para la pet, no lo da al resto del grupo o banda. #2562 
    - <strong>Mordedura de las Sombras:</strong> http://wow.freakz.ro/spells.php?spell=54049. No pega lo que debería, pega menos de la mitad de lo que debería. El aspecto de augmento de daño segun los dots funciona. #2013 
    - <strong> Bloqueo de hechizo </strong> http://wow.freakz.ro/spells.php?spell=19647 Cuando interrumpe el casteo, no silencia, simplemente lo interrumpe #912 
- Glifos:
  - <strong>Glifo  de Enlace de Alma.</strong> http://www.wowhead.com/item=45789# No da el 5% extra de daño transferido a la moscota. #2521 
  - <strong> Glifo de Ojo de Kilrogg </strong> http://es.wowhead.com/item=58081 Debería augmentar la velocidad en un 50% y permitirle volar en las zonas que se pueda. #582

---

<h3>Pícaro:</h3>

---
- Generales:

· <strong>Energía:</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1719 https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1504 La energía del pícaro sufre un bug visual (igual que la ira) cuando se tienen bufos que aumentan la regeneración de maná.
· <strong>Arma arrojadiza - Abanico de cuchillos</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1846 Cuando daña algún objetivo, el arma arrojadiza pierde 1p por cada objetivo dañado. (Issue cerrado, pero no arreglado).
· <strong>Bomba de humo</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1952 No saca a los enemigos de sigilo.
· <strong>Hacer picadillo</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2567 Usar la habilidad está sacando de sigilo.
· <strong>Exponer armadura:</strong> Usar la habilidad está sacando de sigilo.
· <strong>Preparación</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2270 Está reiniciando el CD de evasión.
- Asesinato:

· <strong>Talento Exponer armadura</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2403 No devuelve los puntos de talento al usar la habilidad.
- Sutileza:

· <strong>Vena sangrienta</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1678 Gubia se sigue rompiendo por los sangrados del pícaro. Revisar bonus de daño del 16% cuando el objetivo sufre un sangrado.

· <strong>Golpes despiadados</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2275 Algunos remates dan 25 otros 50 y otros nada. En el post viene la info. para cada habilidad.
- Combate:

· <strong>Precisión</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2135 No aumenta la probabilidad de golpear con armas y ataques con venenos un 6%.
· <strong>Golpe revelador</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2131 El debufo desaparece si cualquier otro aliado hace daño a tu objetivo.

---

<h3> Druida</h3>

---
- General:

· <strong>Celeridad - Gato</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2099 La celeridad no está aumentando la regeneración de energía.
- Feral:

· <strong> Armas de asta </strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2284 Están dando más DPS del que deberían a los ferales.
· <strong>Líder de la manada</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2390 Está sanando cada 6s con cualquier ataque, no sólo con los críticos a melee en forma de gato u oso.
· <STRONG>Venganza</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2119 Debería ser acumulativo hasta el 10% de la vida del druida, sin embargo con cada golpe que te dan se esta reseteando. Debe cancelarse al entrar en forma de gato.
· <strong> Rugido salvaje</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2392 Sigue aumentando el daño en general, no sólo el 80% con ataques automáticos.
· <strong> Defensor salvaje </strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2118 Absorbe 1p de daño. Obviamente tampoco tiene en cuenta la maestría.
·<Strong> Flagelo </strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1944 Hace más daño del que debe sin llevar arma (testear si llevando arma también).
·<strong> Estampida </strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2352 La parte del hechizo que dice "da igual estar detrás del objetivo y de que no cueste energía" no funciona.
- Restauración

· <strong>Revitalizar</strong>#2609: Deberia hacer que cada vez que lanzo o renuevo Flor de vida(33763), otorgue Reposición (esto no ocurre)http://wow.freakz.ro/spells.php?spell=48544
- Glifos

· <strong>Glifo de Recrecimiento</strong>#2608: El daño a un objetivo sanado con Recrecimiento(8936) que se encuentre a 50% de salud o menos resetea el efecto periodico de Recrecimiento (Esto no ocurre) http://wow.freakz.ro/spells.php?spell=54743&name=glyph-of-regrowth
· <strong>Glifo de rayo solar</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1125 No aumenta la duración del rayo solar.

---

<h3>Chamán:</h3>

---
- Restauración:
  - <strong>Perspicacia enfocada</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2402 En vez de reducir el coste de maná considerablemente, lo está aumentando ligeramente.

<b>Sanación Ancestral</b> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3171 Aunque aumenta la salud del objetivo sanado (con cualquier cura), por el chamán, por valor de un 10% de la curación hecha, éste buff (105284) debería acumularse hasta un tope del 10% de la salud total del aliado sanado. Actualmente en vez de acumularse, se pisa sustituyéndolo por otro buff de incluso menor valor.

 -<b>Aguas purificadoras</b> La sanación de "Limpiar Espíritu" es bajísima (un tercio de lo que debería) además esta sanacion deberia tener un cd interno de 6seg, y no lo tiene https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2956

 -<b>Desatar vida</b> Tras usar la spell "Desatar elementos" no sucede el efecto "Desatar vida" (ni el buff, ni la curación) https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3131
- Glifos
  - <strong>Glifo de Escudo de Relámpagos. #2400</strong> 
  - <b>Glifo Tótem Corriente de Sanación</b> El tótem Corriente de Sanación, con su correspondiente glifo, deberían dar 195puntos de resistencia a las escuelas de magia de Fuego, Naturaleza y Escarcha a todo miembro del grupo o banda a 30m del tótem https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2926

---

<h3>Sacerdote:</h3>

---
- Hechizos:
- Sombra: 
  <b>Orbe de las Sombras </b> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3169 Problema: consumir un orbe de las sombras no está potenciando con un 24% extra a explosión mental http://wow.freakz.ro/spells.php?spell=8092&name=mind-blast o pua mental http://wow.freakz.ro/spells.php?spell=73510&name=mind-spike
- Disciplina:
- Sagrado
- Glifos
  · <strong>Glifo de rezo de alivio</strong> #1175 La primera carga de rezo de alivio debería tener un beneficio del 60% (multiplicador de x1,60)
  
  · <b>Glifo de palabra de poder: escudo </b> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2814 Tu Palabra de poder: escudo debería además curar al objetivo con valor al 20% de la cantidad total de absorción (no lo hace)

---

<h3>Caballero de la muerte</h3>

---
- Hechizos:

· <strong>Presencia escarcha:</strong> http://wow.freakz.ro/spells.php?spell=48266 Esta reteniendo la velocidad de carga de runas de profano. #2678
· <strong>Presencia profano:</strong> http://wow.freakz.ro/spells.php?spell=48265 No aumenta la velocidad de carga de runas. #2679
· <strong>Golpe con runa:</strong> http://wow.freakz.ro/spells.php?spell=56815 Se esta esquivando y parando dicho ataque. #2796 
- Sangre:
  ·  <strong>Aroma a sangre:</strong> http://es.wowhead.com/spell=49509 Con tener 1 punto en dicho talento se acumula 3 cargas como si tuvieras los 3 puntos. #2763 

· <strong>Golpe letal:</strong> http://es.wowhead.com/spell=49998/golpe-letal  Golpe letal deberia de curarme aun si falle, esquiven o paren el ataque. #2102

· <strong>Parasito de sangre:</strong> http://es.wowhead.com/npc=42850 Tras reventar el gusano no esta curando nada y no hace el 5% de daño del dk. #2088

· <strong>Arma de runa danzante:</strong> http://wow.freakz.ro/spells.php?spell=49028 No aumenta 20% la probabilidad de parar. #2851 

· <strong>Arma de runa danzante:</strong> http://wow.freakz.ro/spells.php?spell=49028 No realiza los ataques que hace el dk. #2852

· (Maestria): <strong>Escudo de Sangre:</strong> http://es.wowhead.com/spell=77513 El aumentar la maestría no aumenta la cantidad de absorción en base a lo que te curas. #2089

· <strong>Escudo de sangre:</strong>  http://es.wowhead.com/spell=77513  Cada vez que se use el ataque debería acumularse la absorción de daño hasta un máximo de la misma vida del dk. #1471

· <strong>Escarlatina:</strong>  http://wow.freakz.ro/spells.php?spell=81132 Al colocar 2 puntos de talentos no reduce el daño 10%. #2640 
- Escarcha:

· <strong>Explosión aullante:</strong>  http://es.wowhead.com/spell=49184/explosion-aullante  El daño de este hechizo es muy reducido de 2160 o un poco mas con cds a los npc ademas inflige el mismo daño a todos los enemigos en un radio de 10 metros incluido a tu objetivo. #2268

 · <strong>Nervios de Acero Helado</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2707 Al ver la información del personaje, hay un aumento de daño en el arma de la mano izquierda, pero el índice de golpe sigue siendo el mismo. 

 · <strong>Sangre del Norte:</strong> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/990 Las runas vuelven a ser de sangre cuando pasas por una pantalla de carga (cruzar portal; ir por barco; ir a bg/arena; summon; entrar a una mazmo). Por lo tanto hay que relogear si vas a bg o volver a activar los talentos para que aparezcan las runas de muerte.(http://es.wowhead.com/spell=54637)
- Profano:

· <strong>Virulencia:</strong> http://wow.freakz.ro/spells.php?spell=49568&name=virulence No aumenta el daño de tus enfermedades Fiebre de escarcha (59921) y peste en la sangre (59879). #2599
- Mascota: 

· Spells mascota: La mascota no posee la barra para realizar las habilidades. #2211

· (Gargola) <strong>Golpe de gargola:</strong> http://wow.freakz.ro/spells.php?spell=69520&name=gargoyle-strike  Su daño es muy reducido y no se basa en el 40% de la Ap del dk. #2601

· <strong>Infusión de sombras:</strong>  http://wow.freakz.ro/spells.php?spell=91342  No esta aumentando el 6% del daño del necrofago.
- Glifos:

· <strong>Glifo de levantar muerto:</strong>  http://wow.freakz.ro/spells.php?spell=58686&name=glyph-of-raise-dead No esta recibiendo el 40% de fuerza y aguante.#2600

· <strong>Glifo de escudo oseo:</strong> http://wow.freakz.ro/spells.php?spell=58673&name=glyph-of-bone-shield Problema no esta aumentando el 15% de la velocidad de movimiento. #2602

· <strong>Glifo de golpe letal:</strong> http://cata.openwow.com/spell=59337  siempre esta aumentando un 40% el daño de golpe letal deberia de ir aumentando un 2% por cada 5 de poder runico. #2159

· <strong>Glifo de socorro oscuro:</strong> http://es.wowhead.com/item=68793 No se esta activando el efecto el glifo. #2795 

· <strong>Glifo de toque helado:</strong> http://wow.freakz.ro/spells.php?spell=58631 No aumenta 20% el daño de fiebre de escarcha #2797

**Comment by Kiritoo** [comment]
<strong> Los bugs de clases, añadidos en está lista que no esten reportados en un issue individual, no serán reparados.</strong>
Un saludo.

**Comment by DatJetto** [comment]
- Hunter: 
- DETERRENCE: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/291 De vuelta, pueden pegarte físicamente con él activado e incluso stunearte.
- MASTER MARKSMAN: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2719 Los Stacks adicionales rompen el Aimed Shot instantáneo.
- AIMED SHOT ( Instantáneo y Gratis, Proc de Fire! )  http://www.wowhead.com/spell=82928  Daño bajo junto a su versión casteada.
- RAPID KILLING https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2721 Daño ridículo
- RAPID RECUPERATION https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2722 Doble regeneración de enfoque.
- EXPLOSIVE SHOT: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2772 Daño alto

**Comment by paellaencol** [comment]
Sacerdote disciplina: <b>Contricción</b> Lo añado de nuevo, ya que aunque con Punición quedó bien, con Fuego sagrado no funciona (con fuego sagrado debería activarse desde la 4.3)
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2812

**Comment by paellaencol** [comment]
Paladín reprensión: <b>Arrepentimiento</b> Debería desaparecer cuando el objetivo de "Arrepentimiento" recibe daño (excepto Censura), independientemente de que éste tenga algún efecto de absorción o no.
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2862

**Comment by kingtonix** [comment]
Caballero de la muerte:

· [Dk] Pesteador de ebano:  http://wow.freakz.ro/spells.php?spell=51160 No esta aumentando 8% el daño mágico que recibe el objetivo. #3034 

· [Dk] Pesteador de ebano:  http://wow.freakz.ro/spells.php?spell=51160 reduce el daño que realiza Fiebre de escarcha {59921}. #3033

**Comment by paellaencol** [comment]
Chamán Restauración:

<b>Sanación Ancestral</b> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3171 Aunque aumenta la salud del objetivo sanado (con cualquier cura), por el chamán, por valor de un 10% de la curación hecha, éste buff (105284) debería acumularse hasta un tope del 10% de la salud total del aliado sanado. Actualmente en vez de acumularse, se pisa sustituyéndolo por otro buff de incluso menor valor.

**Comment by feniix97** [comment]
Dk profano esbirro bug y nerfeado:#3179

 el esbirro del dk en modo profano sigue estando bug,sus ataques  especiales están nerfeados y son esquivados o parados siempre x los jugadores sin importar que.
incluyendo los glifos que no le afectan o talentos q no aumentan su daño, siempre esta quitando 100 como máximo a los jugadores con sus ataques básicos.

**Comment by feniix97** [comment]
Muerte y descomposición del dk:#3180

esta quitando unos 900 puntos de daño como mucho en modo profano y menos en las otras ramas. el daño esta aun mas nerfeado que como estaba antes.

**Comment by paellaencol** [comment]
Chamán elemental: <b>Flujos de lava</b> No aumenta la celeridad del chamán al ser dispeleado su choque de llamas https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3295

**Comment by paellaencol** [comment]
Paladín talento: <b>Gloria eterna</b>
Descripción: Tu <b>palabra de gloria</b> http://wow.freakz.ro/spells.php?spell=85673 tiene un 30% de probabilidad de no consumir <b>Poder Sagrado </b> http://wow.freakz.ro/spells.php?spell=85247

Problema: en la actualidad no existe la probabilidad del 30% de no ser consumidas las cargas

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3309
