### ISSUE TITLE
Bug en los portales de Ventormenta (Infralar, Hyjal, Uldum, Vash'jir y Tierras Altas Crepusculares)

### ISSUE THREAD

**Issue by nacheitor** [RoDNet/Bugtracker-Infinium-4.3.4#2598]
No se porque me deja acceder a estos portales, ya que me salen bugs (excepto Tol Barad) pensé que tendria que ver la carpeta cache, pero en mi carpeta del wow no hay carpeta cache. Espero que me lo puedan solucionar, me sale al cliquear el portal : "Something bad happened, and we want to display a custom message"

![image](https://f.cloud.github.com/assets/5895705/1506674/8769433c-493e-11e3-83f2-e6efe1f2e5d4.png)

**Comment by redneo** [comment]
TIenes que hacer la cadena de misiones respectiva para poder usar esos portales, menos tolbarad y Tierras altas crepusculares.
