### ISSUE TITLE
[DK] Virulencia

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#2599]
Nombre; Virulencia.
Talento rama profano
ID: 49568
Link: http://wow.freakz.ro/spells.php?spell=49568&name=virulence

Aumenta 10% el daño de tus enfermedades por cada punto de talento hasta un máximo de 30% por 3 talentos.

Problema: No aumenta el daño de tus enfermedades Fiebre de escarcha (59921) y peste en la sangre (59879)

**Comment by searum** [comment]
fix
