### ISSUE TITLE
NPC - Osborne el Nocturno <Instructor de pícaros> BUG

### ISSUE THREAD

**Issue by thebigfer94** [RoDNet/Bugtracker-Infinium-4.3.4#26]
El NPC Osborne el Nocturno <Instructor de pícaros>
http://es.wowhead.com/npc=918

Es un Instructor de Picaros, y esta bug ya que yo soy Guerrero y me da la opcion de Aprender HEchizos y aprender mi especializacion de Talentos. 

![wowscrnshot_070313_172602](https://f.cloud.github.com/assets/4934365/746832/51c9b1e4-e43a-11e2-87eb-08b5f4ae0825.jpg)
![wowscrnshot_070313_172605](https://f.cloud.github.com/assets/4934365/746831/51c95db6-e43a-11e2-9ba8-5342b597387c.jpg)
![wowscrnshot_070313_172612](https://f.cloud.github.com/assets/4934365/746833/534a9c68-e43a-11e2-8829-afd41964c793.jpg)
![wowscrnshot_070313_172615](https://f.cloud.github.com/assets/4934365/746834/54790b74-e43a-11e2-80eb-5d414034ab8f.jpg)

**Comment by SherBlader** [comment]
Me pasa lo mismo con la instructora de druidas que esta en orgrimmar

**Comment by SherBlader** [comment]
pero con la de dalaran no pasa eso :3
