### ISSUE TITLE
[DK] Glifo de escudo oseo.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#2602]
Nombre: Glifo de escudo oseo.
ID: 58673
Link: http://wow.freakz.ro/spells.php?spell=58673&name=glyph-of-bone-shield

Aumenta tu velocidad de movimiento un 15% cuando tu escudo oseo esta activado.

Problema no esta aumentando el 15% de la velocidad de movimiento.

**Comment by efectokoleos** [comment]
1 año despues de probarlo veo k funciona por lo k cierro
