### ISSUE TITLE
CAZADOR: Bug muy grave en la experiencia en las pet y su tamaño

### ISSUE THREAD

**Issue by bignitro** [RoDNet/Bugtracker-Infinium-4.3.4#2605]
Buenas gente. Hos escribo esto por que me e dado cuenta ke cuando e terminado todas mis misiones con el (HUNTER) y estoy al nivel 85 y mi pet (ejem) esta al nivel 83, me obligan a levear en otras zonas donde pueda matar a modd para levear  a la pet  de nuestro nivel. Mirando la cantidad de EXP ke dan a la pet  ke es 128 de exp,  y la cantidad total de la barra de es la pet es de 458k de exp, resulta ke un poco imposible para levearla y hacer el daño ke deberia hacer.
Si es nesesario ¿pridiais firaros un poco mas y poner la cantidad junta de exp para ke una pet de un hunter se pueda levear con mas rapided y no tardar media vidad? por que para llenar esa barra es muy agotador y hos lo puedo decir por ke la pet ke tengo capturadas me encanta pero las tengo ke tirar por la no levearlas de lo ke se tarda en levearlas y eso no le gustaria a cualkier hunter de este server ke es perfecto.
A parte de eso algunas pet son demasiado pequeñas como ( ejem. Demonosarurio, Can Nucleo, Silítido, ) ke cuando les tiras colera de bestias se ponen en el tamaño origuilan.

Gracias por todo y aki hos dejo. Atentamente NITRO nos wemos

**Comment by ghost** [comment]
Buenas, borra uno de los dos reportes, has hecho 2 iguales.

Edita uno de ellos y escribe bien porque hay que leer 50 veces una misma oración para entender algo con tantos fallos de ortografía y de escritura, cuanto más fácil lo hagas a los gms más facilidades para que lo arreglen.

Saludos!
