### ISSUE TITLE
hechizo (druida feral) Abalanzarse

### ISSUE THREAD

**Issue by toxicity93** [RoDNet/Bugtracker-Infinium-4.3.4#2606]
Nombre: Abalanzarse 
Enlace: http://es.wowhead.com/spell=9005/
Descripcion: Te abalanzas sobre el objetivo, lo que lo aturde durante 3seg e inflige XXXXp. de daño de sangrado durante 19seg. Hay que acechar. Otorga X p. de combo
MEJORA: +1seg aturdimiento
Problema: El hechizo solo aturde 1 seg
Observasiones: creo que tampoco hace el daño en el tiempo

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by efectokoleos** [comment]
este hechizo funciona correctamente

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, no daremos mas soporte al actual
