### ISSUE TITLE
Druida [Resguardo de Naturaleza]

### ISSUE THREAD

**Issue by nicerdicer** [RoDNet/Bugtracker-Infinium-4.3.4#2607]
Talento [Resguardo de Naturaleza]: Debe lanzar automaticamente y sin coste de mana un Rejuvenecimiento(774) sobre mi mismo cuando recibo daño estando a 50% de salud o menos. (Esto no ocurre) http://wow.freakz.ro/spells.php?spell=33882
![restobug](https://f.cloud.github.com/assets/4660334/1507729/9d7a174e-49a4-11e3-9770-e4a6fbdcfb7f.jpg)
Como vemos en el screen, mi vida esta a menos del 50% y en mi lista de buffs no esta Rejuvenecimiento.

**Comment by Dekadencee** [comment]
Fixed
