### ISSUE TITLE
Druida; [Glifo de Recrecimiento]

### ISSUE THREAD

**Issue by nicerdicer** [RoDNet/Bugtracker-Infinium-4.3.4#2608]
[Glifo de Recrecimiento]: El daño a un objetivo sanado con Recrecimiento(8936) que se encuentre a 50% de salud o menos resetea el efecto periodico de Recrecimiento (Esto no ocurre) http://wow.freakz.ro/spells.php?spell=54743&name=glyph-of-regrowth
![restobug2](https://f.cloud.github.com/assets/4660334/1507732/09c22e32-49a5-11e3-885a-cd668f4bcb16.jpg)
Como vemos en el Screen, recibo daño con la salud a menos del 50% y el dot de recrecimiento esta a 1s de terminar, y de hecho, termina... cuando deberia resetearse.

**Comment by efectokoleos** [comment]
arreglado
