### ISSUE TITLE
Druida [Revitalizar]

### ISSUE THREAD

**Issue by nicerdicer** [RoDNet/Bugtracker-Infinium-4.3.4#2609]
Talento [Revitalizar]: Deberia hacer que cada vez que lanzo o renuevo Flor de vida(33763), otorgue Reposición (esto no ocurre)http://wow.freakz.ro/spells.php?spell=48544
![wowscrnshot_111013_021746](https://f.cloud.github.com/assets/4660334/1507742/0d06958c-49a6-11e3-9b2c-862402bef9eb.jpg)
Vemos que en el momento en el que Flore de vida es lanzada, en mi lista de buffs solo aparece, Flor de Vida, pero no reposición.

**Comment by Kiritoo** [comment]
Fix
