### ISSUE TITLE
Druida [Don de la madre Tierra]

### ISSUE THREAD

**Issue by nicerdicer** [RoDNet/Bugtracker-Infinium-4.3.4#2610]
Talento [Don de la madre tierra]: Debe provocar que Rejuvenecimiento sane un 15% de su sanacion total en el tiempo de forma instantanea (No funciona) http://wow.freakz.ro/spells.php?spell=51180
![wowscrnshot_111013_021815](https://f.cloud.github.com/assets/4660334/1507744/675337a2-49a6-11e3-88cc-1e5edf153860.jpg)
Rejuvenecimiento es lanzado y no aparece sanación instantanea de ningún tipo en el momento que el beneficio entra.

**Comment by searum** [comment]
fix
