### ISSUE TITLE
Quets Huarguen No puedes acabar con ellos solo 

### ISSUE THREAD

**Issue by jesusjimen** [RoDNet/Bugtracker-Infinium-4.3.4#2612]
quest 14348 le lanzas el barril de polvora y aveces no ocurre nada  otras si explota pero tienes que estar un rato para buscar bariles y andar tirandoselos

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
