### ISSUE TITLE
Misión Huargens La Batalla por la Ciudad de Gilneas

### ISSUE THREAD

**Issue by alxfla** [RoDNet/Bugtracker-Infinium-4.3.4#2614]
Hola soy cazador y no se como hacer para salir de esa mision, necesito un gm gracias de antemano

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by Kiritoo** [comment]
Tienes que ir a la ciudad a entregarla en la posada mira en wowhead.
