### ISSUE TITLE
DE

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2616]
http:/

**Comment by paellaencol** [comment]
Asman repasa el vídeo, especialmente, fíjate en el minuto 0:06 recibe dos ataques teniendo un escudo de absorción y le salta voluntad centrada. Fíjate que le salta voluntad centrada tras haber absorbido ataques de 1k de daño, cuando los que estaba recibiendo hasta entonces eran de 500. Por tanto esos dos ataques recibidos de 1k han sido críticos, y por tanto ha saltado el proceso de voluntad centrada.

Otra cosa más, en el reporte de combate cuando recibes un golpe crítico teniendo un escudo de absorción no te lo dice, simplemente pone la palabra "absorbido", en ningún momento indica la palabra "crítico" si ese golpe no desvanece el escudo

Además debes de saber que tener un escudo no te hace inmune a efectos críticos. En el vídeo se ve, recibe un efecto crítico teniendo un escudo y el proceso salta. Es decir totalmente correcto.

P.D. Si aún te quedan dudas y quieres testearlo bien, pulleas a un grupo de mobs sin tener ningun escudo de absorción, y ahí te quedará mas claro.

**Comment by ghost** [comment]
Cua

**Comment by paellaencol** [comment]
no

P.D. otro ejemplo, minuto 0.04

**Comment by ghost** [comment]
Des
