### ISSUE TITLE
[Misión] Feralas - El poder de los Quebrantarrocas

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2617]
Enlace: http://es.wowhead.com/quest=25329/

Descripción: debería suceder lo siguiente al entrar en la arena de la masacre http://www.youtube.com/watch?v=jusYkAPQsC4

Problema: actualmente solo aparecen los ogros y la bola del mundo, y la misión no se puede completar.

Si esta cinemática fuera dificil de implementar, por lo menos podría ser completable la misión con solo pisar la arena, y no tener que esperar a que se complete cuando acabe la cinemática

**Comment by redneo** [comment]
La medio implemente a mi manera, y tendria que salir chogall, es mas, hace una semana pase por alli y si que salia... Puede que sea problema de respawn, le voy a cambiar el respawn a chogall

![wowscrnshot_111213_080815](https://f.cloud.github.com/assets/1163425/1519696/7972bc36-4b69-11e3-99ae-de8b43d1b1c9.jpg)

Como ves si que esta, habla y tendria que contar la mision. Puede que no estuviera cuando llegaste, le he cambiado el respawn a 60 segundos.
