### ISSUE TITLE
Misión, Teldrassil: Instrucción del Forestal [Instructora de Cazadores]

### ISSUE THREAD

**Issue by Shymast** [RoDNet/Bugtracker-Infinium-4.3.4#2618]
Nombre: Instrucción del Forestal
Enlace: http://es.wowhead.com/quest=26947/
Descripción: Alcanza el nivel 3 para aprender prende Disparo firme. Busca un muñeco de entrenamiento al sureste de Aldrassil y practica Disparo firme 5 veces. 
Problema: Cuando a nivel bajo, tomé la quest no contaba la cantidad de veces que había probado el ataque. 
Observaciones: Ya me pasó con otra clase y no pude continuar, cree un cazador para seguir y me pasó lo mismo. Ahora continué con otras misiones pero así no puedo seguir aprendiendo otras skills. 

Saludos.-

**Comment by redneo** [comment]
cuando caiga el server, sueltas y coges la mision y tendria que ir
