### ISSUE TITLE
[Misión][Bosque de Terokkar] El código final

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2619]
Buenas.
• Nombre: El código final
• Enlace: http://es.wowhead.com/quest=10446
• Descripción: El teniente Meridiano quiere que uses el código final para detonar la bomba de maná. Informa después a Jenai Susurrestelar del Bastión Allerian en el Bosque de Terokkar. 
• Problema: Al detonar la bomba de maná con el código final (http://www.wowhead.com/item=29912) la misión no cuenta como completa.
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglado
