### ISSUE TITLE
[Mazmorra Heroica] Minas de la Muerte.

### ISSUE THREAD

**Issue by Alfonn** [RoDNet/Bugtracker-Infinium-4.3.4#262]
Aquí pondré todo el testeo de esta mazmorra.

1)Secuaz Ogro(http://es.wowhead.com/npc=48230/secuaz-ogro) no ataca y no realiza sus habilidades.
-Habilidades: Gancho(http://es.wowhead.com/spell=91045) y Motivación de ogro(http://es.wowhead.com/spell=92747).

2)Guardaespaldas Ogro(http://es.wowhead.com/npc=48262/guardaespaldas-ogro) No realiza sus habilidades.
-Habilidades: Capón(http://es.wowhead.com/spell=91050) y Frenesí(http://es.wowhead.com/spell=91053).

-->1er BOSS->Glubtok, funciona correctamente.

3)Sobrestante Goblin(http://es.wowhead.com/npc=48279/sobrestante-goblin) No realiza sus habilidades.
-Habilidades: Grito Amenazante(http://es.wowhead.com/spell=91034) y Motivar(http://es.wowhead.com/spell=91036).

4)Lacayo Patán(http://es.wowhead.com/npc=48445/lacayo-patan) No realiza sus habilidades.
-Habilidades: Enfurecer(http://es.wowhead.com/spell=8599) y Hacha a la cabeza(http://es.wowhead.com/spell=90098).

--> 2ndo BOSS->Patán inútil(http://es.wowhead.com/npc=47297/patan-inutil)/Helix Rompengranajes(http://es.wowhead.com/npc=47296/helix-rompengranajes).
Este encuentro no se desarrolla como debe ser, en la primera fase, regular, pero en la segunda que es cuándo Helix Rompengranajes baja , este no baja y por tanto no se le puede matar(directamente desaparece). Aparte de esto también no realizan algunas de sus habilidades.
-Habilidades Patán Inútil : Cargar(http://es.wowhead.com/spell=88288).
-Habilidades Helix Rompengranajes : Bomba de pecho(http://es.wowhead.com/spell=88352) Además este boss deja bombas en el suelo que al pisarlas hacen daño, pues estas no hacen dicho daño.

5)Convocador Defias(http://es.wowhead.com/npc=48418/convocador-defias)no realiza sus habilidades.
Habilidades: Escudo del convocador(http://es.wowhead.com/spell=92001) ,Fuego Sagrado(http://es.wowhead.com/spell=91004) y Fuerza Renegada(http://es.wowhead.com/spell=90047).

6)Sobrestante Defias(http://es.wowhead.com/npc=48421/sobrestante-defias)Funciona perfectamente.
-->3er BOSS->Siegaenemigos 5000(http://es.wowhead.com/npc=43778/siegaenemigos-5000) No realiza todas sus habilidades.
Habilidades: Barrido de cosecha(http://es.wowhead.com/spell=88521) ,Golpe de segador(http://es.wowhead.com/spell=88490) ,Restricciones de seguridad desconectadas(http://es.wowhead.com/spell=88522). Los mobs que invoca este boss son amistosos.

7)Dépota Defias(http://es.wowhead.com/npc=48502/despota-defias) no realiza sus habilidades.
Habilidades: Baño de sangre(http://es.wowhead.com/spell=90925) ,Cargar(http://es.wowhead.com/spell=90928) y Temeridad(http://es.wowhead.com/spell=90929).

8)Zahorí de sangre Defias(http://es.wowhead.com/npc=48417/zahori-de-sangre-defias)no realiza sus habilidades.
Habilidades: Descarga de sangre(http://es.wowhead.com/spell=90938) ,Lavado de sangre(http://es.wowhead.com/spell=90946) y Zona de ira(http://es.wowhead.com/spell=90932).

9)Guardia de las sombras Defias(http://es.wowhead.com/npc=49852/guardia-de-las-sombras-defias) no realiza sus habilidades.
Habilidades : Camuflaje(http://es.wowhead.com/spell=90954) ,Hojas giratorias(http://es.wowhead.com/spell=90960) ,paso de las sombras(http://es.wowhead.com/spell=90956) y Evasión(http://es.wowhead.com/spell=90958).

10)Pirata Defias(http://es.wowhead.com/npc=48522/pirata-defias)no realiza su habilidad.
Habilidad: Mella con salto(http://es.wowhead.com/spell=90905)

-->4º BOSS->Almirante Rasgagruñido(http://es.wowhead.com/npc=47626/almirante-rasgagrunido)No realiza algunas de sus habilidades.
Habilidades : Flagelo(http://es.wowhead.com/spell=88839) y A la yugular(http://es.wowhead.com/spell=88836). En cuanto al encuentro se realiza perfectamente.

Ya no pude testear más. ¿Razón? Justo 15s despues de matar a este boss el servidor se cayó repetidas veces y los demás bosses no aparecieron , por tanto no sé si es un bug constante o solo se nos bugeó a nosotros por la caida...
Supuestamente ''Capitán''Cocinitas (http://es.wowhead.com/npc=47739/capitan-cocinitas) y Vanessa VanCleef(http://es.wowhead.com/npc=49541/vanessa-vancleef) Deberían aparecer , el capitán cocinitas detrás de Almirante Rasgagruñido y después de capitán cocinitas , Vanessa VanCleef.

Un Saludo. Si me equivoqué en algo comentadlo!

**Comment by crowel** [comment]
Si, luego las añado aquí es que ayer me lié reportando las clases jeje.

**Comment by Alfonn** [comment]
Vale, gracias a @crowel y a @Lvmb . Como ya expresé yo no pude testear los 2 últimos jefes.

Un saludo.

**Comment by Savian123** [comment]
Cocinitas aparece al entrar en el camarote del capitan , se va hacia la cubierta pone un caldero y empieza el combate , cocinitas va arrojando comida la podrida deja una area que inflige daño periodico a los jugadores cercanos y la que tiene buen estado da buffo de celeridad a los que la ingieren. Vanessa VanCleef no aparece hasta que lees una extraña nota que deberia aparecer en el suelo una vez derrotado cocinitas . En ese momento aparecera y envenenara a todo el grupo dejandolos aturdidos en una pesadilla lucida . Pasados unos segundos el grupo entero es transportado a la fundicion donde deberan liberarse de las cadenas pulsando en las tuercas que hay , una vez liberados debereis hacer la ruta hacia la cubierta del barco , enfrentandoos de nuevo a los Anteriores Bosses para empezar el ogro llenara la habitacion de fuego que debereis ir esquivando ... Todo esto teniendo velocidad reducida los primeros segundos y vision algo nublada hasta derrotar al ultimo de los Bosses Rasgagruñido . Despues de derrotar al ogro la pesadilla cambiara y aparecera Helix junto a un monton de arañas
debereis evitar ataques en zona para no atraer a las arañas y matar rapidamente a este. Una vez eliminado podreis proseguir , esta vez entramos en la pesadilla del Siegaenemigos que igual que en el tipico castillo de supermario tendreis que recorrer el camino esquivando unas filas giratorias de bolas electricas que infligen 50% de tu salud total cada vez que te tocan . Finalmente encontramos al "Boss" de la pesadilla lo derrotamos y se abre la ultima puerta , en esta fase nos daran un buffo de sprint,  deberas salvar a toda la familia Harrison, que seran atacados por 3 Huargen a la vez cada vez que derrotes un grupo de huargen se te dara una carga extra de sprint con lo cual acabaras con 3 acumulaciones despues de salvar a todos. Y ya para terminar llegas a la cubierta atacas a Vanessa y empieza el combate , Vanessa invoca repetidamente secuaces que se deben ir matando , cada cierto % que se le baje el boss decidira hacer estallar unas cargas explosivas del barco , debereis coger las cuerdas que aparecen (un total de 5) para asi evitar la explosion que en teoria deberia mataros de 1 golpe a no ser que useis habilidades de paladin como escudo divino o cubo de mago . Despues de cada explosion el fuego permanecera asique tendreis una area mas reducida para derrotar al boss , el resto es todo el rato lo mismo hasta derrotarla . 

Espero que os sirva la explicacion ^^ atentamente Kvothe

**Comment by efectokoleos** [comment]
probar ahora k estan implementadas
