### ISSUE TITLE
[ Mago > Nova de Escarcha ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2621]
Hoy os traigo un bug que descubrí mientras estaba en BG y resulta que Llamada de Maestro del cazador no elimina Nova de Escarcha del Mago. 

Lo curioso es que a nuestra pet si se le elimina dicho efecto, pero a nosotros nos dura impidiendo el cómodo uso de nuestras habilidades en movimiento y dando ventaja al grupo enemigo.

En este Vídeo mi maga VS Pegasus ( Gracias por la colaboración ) vemos como al estar Él y su Lobo congelados sólo se le quita al lobo, mientras que él está congelado en el sitio.

http://www.youtube.com/watch?v=GvrmD29GvdA&feature=youtu.be

http://es.wowhead.com/spell=122

**Comment by paellaencol** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2262
