### ISSUE TITLE
[Misión][PNJ] Visión de los muertos

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2622]
Buenas.
• Nombre: Visión de los muertos
• Enlace: http://es.wowhead.com/quest=10252
• Descripción: Nitrin, en la Armería Abandonada, en Nagrand, quiere que le lleves 1 globo ocular de gronn montés, 1 pico de vientorroc superior perfecto y 1 grasa de uñagrieta envejecido. 
• Problema: El problema está en conseguir la grasa de uñagrieta envejecido, ya que no hay ningún Uñagrieta envejecido a la vista (http://es.wowhead.com/npc=17133)
• Observaciones: Según los comentarios del wowhead, este PNJ comparte respawn con Ciclón viviente (http://es.wowhead.com/npc=17160) y matando algunos hay posibilidades de que aparezcan, pero ya di varias vueltas por Nagrand esperando por algunos y al parecer el respawn esta bug.
Gracias y hasta luego!

**Comment by redneo** [comment]
Cuando caiga el server tendria que ir, sin compartir respawn... hay como 15
