### ISSUE TITLE
[Misión][Montañas Filospada] Grulloc tiene dos calaveras

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2623]
Buenas.
• Nombre: Grulloc tiene dos calaveras
• Enlace: http://es.wowhead.com/quest=10995
• Descripción: Consigue la calavera de dragón de Grulloc.
• Problema: La calavera de dragón (http://es.wowhead.com/object=185567) que contiene la calavera (http://es.wowhead.com/item=32379) no está por ningún lado.
• Observaciones: Debería estar justo al lado del PNJ Grulloc (http://es.wowhead.com/npc=20216)
Gracias por todo.

**Comment by redneo** [comment]
Tendria que salir cuando muere, creo, como no lo puedo probar sin tirar el server, cuando le bajas un poco de vida la saca en su espalda.
