### ISSUE TITLE
[Misión][Montañas Filospada] Susurros del Dios Cuervo

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2624]
Buenas.
• Nombre: Susurros del Dios Cuervo
• Enlace: http://es.wowhead.com/quest=10607
• Descripción: Mata al arakkoa Grishna para poder entender la palabra del Cuervo durante 2 minutos. Mientras estés bajo los efectos del hechizo, podrás encontrar y recibir la profecía de los cuatro santuarios. 
• Problema: Los arakkoas Grishna no dan ninguno de los buffs para recibir las profecías de los totems/santuarios. Los santuarios a activar son: La Primera Profecía (http://es.wowhead.com/object=184950) La Segunda Profecía (http://es.wowhead.com/object=184967) La Tercera Profecía (http://es.wowhead.com/object=184968) y La Cuarta Profecía (http://es.wowhead.com/object=184969)
• Observaciones: Según un comentario del wowhead, el primer "buff" te lo da al matar el 1er arakkoa Grishna y es Atracción de almas (http://es.wowhead.com/spell=37475) y luego de matar 5 arakkoas mas, da el "buff" Entender lengua de los cuervos (http://es.wowhead.com/spell=37642) que sirve para leer las profecías de los santuarios.
Gracias y hasta luego!

**Comment by redneo** [comment]
Cuando caiga el server los cuervos te dan el bufo, y no se si al activar los santuarios te contará, me lo dices en uno nuevo

**Comment by ghost** [comment]
Funciona perfecto, muchas gracias!
