### ISSUE TITLE
[Misión] El Levantamiento de los Lanza Negra (Guerrero)

### ISSUE THREAD

**Issue by ShadowChronos** [RoDNet/Bugtracker-Infinium-4.3.4#2626]
Enlace: http://es.wowhead.com/quest=24607

Descripcion: Reunirse con Nortet en el campamento Lanza Negra en Islas del Eco.

Problema: El campamento Lanza Negra se encuentra en Islas del Eco, pero el NPC Nortet no aparece donde dice la misión.

Gracias.

**Comment by redneo** [comment]
puesto
