### ISSUE TITLE
[Misión][Montañas Filospada] Gorgrom el Comedragones (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2627]
Buenas.
• Nombre: Gorgrom el Comedragones
• Enlace: http://es.wowhead.com/quest=10802
• Descripción: Consigue 3 Tótems repelentes de los ogros Peña'mok. Después, utiliza la trampa de Sablecrín en el altar de Gorgrom para invocar y matar a Gorgrom el Comedragones.
• Problema: No deja usar los Tótems repelentes (http://es.wowhead.com/item=31754) para completar la misión. Aparece la leyenda "Requiere el cadáver de Gorgrom" aún estando sobre el.
Gracias!

**Comment by redneo** [comment]
Ya cuenta al usar los totems estando cerca del altar donde lo invocaste.

Edit. SUelta y vuelve a coger la mision
