### ISSUE TITLE
[ Mascotas Espíritu > Aliviar Espíritu ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2628]
http://es.wowhead.com/spell=90361

Esta spell está curando alrededor de 500 cada tick, cuando debería curar alrededor de 3k por pulsación.

Cabe destacar que se realizan 2 tipos de cura, una principal ( más sanación directa ) y el HoT , recuerdo en la anterior versión 4.0.6 que la sanación directa podía provocar críticos de unos 8k mientras que las pulsaciones eran de alrededor de 3k ( sin crítico , ya que estas no pueden hacer crítico )

**Comment by ghost** [comment]
Esto ya está reportado https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2264
