### ISSUE TITLE
[Misión][Montañas Filospada] El exorcismo de los árboles

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2629]
Buenas.
• Nombre: El exorcismo de los árboles
• Enlace: http://es.wowhead.com/quest=10830
• Descripción: Consigue 5 orbes de Grishnath y 5 plumas nacientes atroces y después combínalos para crear plumas de exorcismo. Utiliza las plumas para realizar el exorcismo y matar a 5 espíritus koi-koi de los hojabarba del Bosque del Cuervo. 
• Problema: No se pueden coger los orbes Grishnath (http://es.wowhead.com/item=31495) del contenedor "Orbe de Grishnath" (http://es.wowhead.com/object=182941)
Gracias!

**Comment by redneo** [comment]
A mi ahora si que me salen para lotear, sera tema de temporales???
