### ISSUE TITLE
[Misión] [Fiordo Aquilonal] El yeti de al lado

### ISSUE THREAD

**Issue by Kaveesa** [RoDNet/Bugtracker-Infinium-4.3.4#2630]
Nombre: El yeti del al lado
Enlace: http://es.wowhead.com/quest=11284
Problema: Despues de unir las 4 carnes sacadas de los carneros, unirlas, y ponersela al lado, Modorro, el mob, no se mueve y no puedes atacarlo.

**Comment by redneo** [comment]
reparada
