### ISSUE TITLE
[Misión][Montañas Filospada/Bosque de Terokkar] Incluso los gronn tienen confalones

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2632]
Buenas.
• Nombre: Incluso los gronn tienen confalones
• Enlace: http://es.wowhead.com/quest=10997
• Descripción: Consigue el confalón de Slaag. 
• Problema: El PNJ Slaag (http://es.wowhead.com/npc=22199) no deja el contenedor (http://es.wowhead.com/object=185574) para despojar el Confalón de Slaag (http://es.wowhead.com/item=32382) cuando se lo mata.
Gracias!

**Comment by redneo** [comment]
Creo que reparado.

**Comment by ghost** [comment]
No me funciona D: Lo probé luego del reinicio y no deja nada.
Gracias!
