### ISSUE TITLE
Misión No-muertos La verdad de la tumba quest=24961 Camposanto

### ISSUE THREAD

**Issue by jesusjimen** [RoDNet/Bugtracker-Infinium-4.3.4#2633]
Problema :hablas con la npc http://es.wowhead.com/npc=38910 y con  el espejo en el inventario y no ocurre nada no completa la misión
descripción: Muéstrale a Lilian su reflejo
Link de la misión: http://es.wowhead.com/quest=24961/

**Comment by redneo** [comment]
Arreglada

**Comment by ghost** [comment]
Y
