### ISSUE TITLE
[Misión][Montañas Filospada] Enfrentamiento (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2634]
Buenas.
• Nombre: Enfrentamiento
• Enlace: http://es.wowhead.com/quest=10806
• Descripción: Utiliza el sello de Sablecrín en el altar de Goc y mata a Goc. 
• Problema: Goc (http://es.wowhead.com/npc=20555) aparece como amistoso. 
• Observaciones: Al principio vi que no estaba, luego volví mas tarde y apareció caminando alrededor del altar.
Gracias!

**Comment by redneo** [comment]
Arreglado
