### ISSUE TITLE
[Misión] Mil Agujas - Silencia los cañones

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2635]
http://es.wowhead.com/quest=25586#.

Coges el barquillo, y con el cañon destruyes los cañones del acantilado que hay en los riscos del este.

Griznak(http://es.wowhead.com/npc=40727) no te da el barco para poder lanzar bolazos a los cañones. Con las misiones anteriores si te lo da, pero con esta no.

**Comment by redneo** [comment]
Mira que eres... en una mision te dan un sombrerito que te hace el mismo efecto.

De todas formas no va, pero me tienes que decir la id del spell del barco que tiene que afectar a los cañones :package: 

edito: http://es.wowhead.com/quest=25562

Terminación
Recompensas
Podrás elegir una de estas recompensas:
Leotardos del Barcódromo  
Guantes de hundepiratas
Brazales de abrazo de oso  
Espaldares varoniles
También recibirás: 50

<h2><b>Barco fluvial</b></h2>

**Comment by Wiinter** [comment]
Mira segun este video http://www.youtube.com/watch?v=RJIROJs_nUo, el barco solo sirve de transporte. Y vas a los cañones tu mismo y los destruyes

**Comment by redneo** [comment]
aps, cierto, creia que era con el barco :S

**Comment by redneo** [comment]
arreglado
