### ISSUE TITLE
[Misión][Montañas Filospada] ¡Fuego a discreción!

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2636]
Buenas.
• Nombre: ¡Fuego a discreción!
• Enlace: http://es.wowhead.com/quest=10911
• Descripción: Usa la munición naturalizada para controlar los cañones viles de la Puerta de la Muerte. Úsalos para destruir el portal de distorsión del sur y el portal de distorsión del norte. 
• Problema: Al usar el cañon vil contra los portales de distorsión, no sucede nada y no cuenta como completo (hay que usarlo 7 veces según el tooltip). También los demonios que salen del portal se cuelgan y dejan al personaje en combate.
Gracias!

**Comment by redneo** [comment]
arreglado

**Comment by ghost** [comment]
Sigo sin poder completarla :/, quizá estoy haciendo algo mal: capturo el cañon vil, hago que me siga hasta donde está el edificio con el cristal verde arriba, uso la habilidad "artillería en el portal de distorsión" del cañon 7 veces pero sigue sin contar.
Muchas gracias!
