### ISSUE TITLE
[Misión][Valle Sombraluna] ¡Infernales por los aires! (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2637]
Buenas.
• Nombre: ¡Infernales por los aires!
• Enlace: http://es.wowhead.com/quest=10564
• Descripción: Acciona la bomba vil cuando estés en el glifo verde, en Bastión de la Legión. Informa al comandante del aire Nuainn en Bastión Martillo Salvaje cuando hayas completado tu misión. 
• Problema: La misión se puede hacer, pero no puedo entregarla porque falta que se complete la parte de "Vuelve con: Comandante del aire Nuainn en Bastión Martillo Salvaje, Valle Sombraluna", aun estando al lado del PNJ comandante del aire Nuainn (http://es.wowhead.com/npc=21357).
Gracias!

**Comment by redneo** [comment]
Arreglado, deja la mision y vuelve a cogerla.
