### ISSUE TITLE
Bug general en las animaciones.

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#2638]
Hay un bug general con las animaciones de nadar, ataques automáticos, montar, etc.

Al abrir el mapa (en cataclysm pusieron una animación al mapa) este bugea las demás animaciones haciendo ver la pose de lanzar un hechizo sobre la montura de manera infinita, estar de pie en el agua al estar quieto y no verse la animación que hace la raza al estar en ataque automático, he aquí unos ejemplo:

Mapa:
![wowscrnshot_111213_223740](https://f.cloud.github.com/assets/5053304/1526887/b2e0fef6-4beb-11e3-9055-88fbb7ed79c8.jpg)

Nadar:
![wowscrnshot_111213_224208](https://f.cloud.github.com/assets/5053304/1526890/c9a71044-4beb-11e3-8fc0-1ebeef4210c0.jpg)

Ataques automáticos:
![wowscrnshot_111213_224304](https://f.cloud.github.com/assets/5053304/1526899/f3dcd5c4-4beb-11e3-9fb5-cb270c85cddc.jpg)

Montura:
![wowscrnshot_111213_224344](https://f.cloud.github.com/assets/5053304/1526903/03781764-4bec-11e3-94e7-a54fafb3e9fe.jpg)

Ahora pondré cómo deberían verse.

Nadar:
![wowscrnshot_111213_224456](https://f.cloud.github.com/assets/5053304/1526917/30f559cc-4bec-11e3-92b2-715878f838cf.jpg)

Ataques automáticos:
![wowscrnshot_111213_224533](https://f.cloud.github.com/assets/5053304/1526940/7b376746-4bec-11e3-90ab-bd4020320c62.jpg)

Montura:
![wowscrnshot_111213_224427](https://f.cloud.github.com/assets/5053304/1526943/843ac248-4bec-11e3-9dca-ae5a583d71dc.jpg)

**Comment by ghost** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/494 https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1141

**Comment by ghost** [comment]
Tampoco se pueden cancelar las animaciones de /baile y de /miedo.

**Comment by Dekadencee** [comment]
Fixeada la animacion del mapa y supongo que el bug que proboca en el resto de las animaciones
