### ISSUE TITLE
[Guerrero] (Talento furia) Precisión

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#2639]
Nombre: Precisión

Descripción: Aumenta un 3% la probabilidad de golpear con tus ataques y aumenta un 40% el daño de ataque automático.

Fallo: el 3% de golpe no lo está dando y el 40% de daño automático tampoco.

Observaciones: ya lo reporte hace varios meses y contestaron que ya estaba fix pero desde entonces no hace nada de nada.

ID: http://cata.openwow.com/spell=29592

**Comment by efectokoleos** [comment]
arreglado falta compilar
