### ISSUE TITLE
[Dk] Escarlatina.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#2640]
Nombre: Escarlatina.
Talento rama sangre
ID: 81132
Link: http://wow.freakz.ro/spells.php?spell=81132

Causa que tu peste en la sangre infecte a los enemigos con escarlatina,lo que reduce el daño físico que infligen un 10%.

Problema: No reduce el 10% de dicho talento.

**Comment by efectokoleos** [comment]
arreglado
