### ISSUE TITLE
[PNJ][Valle de Sombraluna] Espíritu de Ar'tor

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2641]
Buenas.
• Nombre: Espíritu de Ar'tor
• Enlace: http://es.wowhead.com/npc=21318
• Problema: El PNJ no está. Debería aparecer luego de completar la misión Cárceles de cristal demoníacas (http://es.wowhead.com/quest=10528) para seguir la cadena de misiones con Lohn'goron, arco del corazón roto (http://es.wowhead.com/quest=10537)
Gracias!

**Comment by redneo** [comment]
Colocado
