### ISSUE TITLE
[Misión][Valle de Sombraluna] Presagistas de Sombraluna

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2642]
Buenas.
• Nombre: Presagistas de Sombraluna
• Enlace: http://es.wowhead.com/quest=10643
• Descripción: Zorus el Justiciero en el Bastión Martillo Salvaje, en el Valle Sombraluna, quiere que mates a 12 presagistas de Sombraluna. 
• Problema: No se pueden atacar a los presagistas de Sombraluna (http://es.wowhead.com/npc=21795), sale la leyenda "Objetivo no valido"
Gracias!

**Comment by redneo** [comment]
Arreglado
