### ISSUE TITLE
[Misión][Valle de Sombraluna] Adivinación: la clava de Sanguino

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2643]
Buenas.
• Nombre: Adivinación: la clava de Sanguino
• Enlace: http://es.wowhead.com/quest=10636
• Descripción: El espíritu Sombraluna ancestral en El Altar de las Sombras, al sureste del Valle Sombraluna, quiere que consigas la clava de Sanguino. 
• Problema: No están los PNJ Jinete fantasmal de Karabor (http://es.wowhead.com/npc=21784) para poder Despojar la clava de Sanguino (http://es.wowhead.com/item=30800)
• Observaciones: Se los tiene que poder ver con los Expectróculos (http://es.wowhead.com/item=30719) solamente.
Gracias y saludos!

**Comment by redneo** [comment]
Arreglado
