### ISSUE TITLE
[Misión][Tormenta Abisal] Abjuradora Belmara

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2645]
Buenas.
• Nombre: Abjuradora Belmara
• Enlace: http://es.wowhead.com/quest=10305
• Descripción: Encuentra las dependencias de la abjuradora Belmara en el Pasaje del Zahorí y devuelve el libro a la estantería. A continuación, habla con el custodio Valemuerte en el Poblado Kirin'Var. 
• Problema: Al dejar el Libro provisto para la misión (http://es.wowhead.com/item=28336) en el estante, la misión no cuenta como completa.
• Observaciones: Aparece el fantasma de dicho PNJ contento, pero no cuenta como completa.
Gracias!

**Comment by redneo** [comment]
TAMBIEN!!!!!!
