### ISSUE TITLE
[Misión][Tormenta Abisal] Conjurador Luminrath

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2646]
Buenas.
• Nombre: Conjurador Luminrath
• Enlace: http://es.wowhead.com/quest=10306
• Descripción: Encuentra las dependencias del conjurador Luminrath, en el Pasaje del Zahorí y devuelve la capa a su vestidor. A continuación, habla con el custodio Valemuerte en el Poblado Kirin'Var. 
• Problema: Al dejar la capa (http://es.wowhead.com/item=28352) en el vestidor, la misión no cuenta como completa.
• Observaciones: Aparece el fantasma de dicho PNJ contento, pero no cuenta como completa.
Gracias!!

**Comment by redneo** [comment]
y tambien me ha contado!

**Comment by ghost** [comment]
Juro que cuando las probé el miércoles, no me contaban D:
Ahora pude hacer todas menos esta, uso el objeto delante del vestidor, aparece el fantasma, pero no cuenta como completa Y_Y
Gracias!!
