### ISSUE TITLE
[Misión][Tormenta Abisal] Mago de batalla Dathric

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2647]
Buenas.
• Nombre: Mago de batalla Dathric
• Enlace: http://es.wowhead.com/quest=10182
• Descripción: Encuentra las dependencias del mago de batalla Dathric en el Pasaje del Zahorí y devuelve la espada al expositor. A continuación habla con el custodio Valemuerte en el Poblado Kirin'Var. 
• Problema: Al dejar la espada de la misión en su lugar (http://es.wowhead.com/item=28351), la misión no cuenta como completa
• Observaciones: Aparece el fantasma de dicho PNJ contento, pero no cuenta como completa.
Gracias y hasta luego!

**Comment by redneo** [comment]
Lo mismo que la anteriro, a mi si que me ha contado
