### ISSUE TITLE
[Misión][Tormenta Abisal] Cohlien Tejescarcha

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2648]
Buenas.
• Nombre: Cohlien Tejescarcha
• Enlace: http://es.wowhead.com/quest=10307
• Descripción: Encuentra las dependencias de Cohlien Tejescarcha, en el Pasaje del Zahorí y devuelve el sombrero a su baúl. A continuación, habla con el custodio Valemuerte en el Poblado Kirin'Var. 
• Problema: Al dejar el sombrero (http://es.wowhead.com/item=28353) en el baúl, la misión no cuenta como completa.
• Observaciones: Aparece el fantasma de dicho PNJ contento, pero no cuenta como completa.
Gracias!

**Comment by redneo** [comment]
A mi si que me ha contado en cuanto a salido el gnomo :S
