### ISSUE TITLE
[Misión][Tormenta Abisal] Una sospecha latente

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2649]
Buenas.
• Nombre: Una sospecha latente
• Enlace: http://es.wowhead.com/quest=10314
• Descripción: Consigue 10 restos repugnantes de los espíritus malignos del Patio de la Capilla del Poblado Kirin'Var y llévaselos al custodio Valemuerte. 
• Problema: Los PNJ Alma atormentada (http://es.wowhead.com/npc=20512) y Ciudadano atormentado (http://es.wowhead.com/npc=21065) no dejan el objeto de misión Restos repugnantes (http://es.wowhead.com/item=2933) al matarlos.
• Observaciones: Solo los fantasmas Kirin'var (http://es.wowhead.com/npc=20480) dejan el objeto, pero hay pocos y el drop es bajo.
Muchas gracias!

**Comment by redneo** [comment]
Arreglado, los npc que dices, no tendrian que soltarlo (fantasmas Kirin'var) lo he puesto a los otros dos al 100%
