### ISSUE TITLE
[Misión] [Islas del Eco] Joven y Salvaje

### ISSUE THREAD

**Issue by ShadowChronos** [RoDNet/Bugtracker-Infinium-4.3.4#2650]
Enlace: http://es.wowhead.com/quest=24626/

Descripcion: Capturar a Garrapresta y llévalo de vuelta al cercado próximo al Bastión Lanza Negra.

Problema: El raptor se encuentra quieto a unos pasos de donde se acepta la mision para capturarlo, pero al marcarlo como objetivo y usar el objeto de mision para montarlo, no sucede nada. El raptor deberia deambular por la isla y al usar el objeto, montarlo y tener que llevarlo hasta el Bastión Lanza Negra.

**Comment by redneo** [comment]
Arreglada
