### ISSUE TITLE
[ Quest > Lycanthoth the Corruptor ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2652]
http://www.wowhead.com/quest=25273

La quest es perfectamente completable, el problema es que no se puede entregar, ya que al matarlo aparece Espíritu de Lo' Gosh, y este no debería aparecer por lo cual no le podemos entregar la quest.

El npc que debería aparecer para Entregar la quest es: 
http://www.wowhead.com/npc=39627

Esta cadena de quest al estar bug imposibilita realizar otras 30 y tantas quest.

**Comment by Kiritoo** [comment]
Usaste el totem para invocarlo?

**Comment by DatJetto** [comment]
El tótem es de otra quest, la cual ya terminé antes de esta, por lo cual si no las haces a la vez la cadena se corta, todo vino por que me quedó una  quest sin coger, pero igualmente el lobo que aparece está mal, debería aparecer Goldrinn y no lo hace. Sale Lo' Gosh que es el de la quest Horda.

**Comment by redneo** [comment]
Arreglado
