### ISSUE TITLE
Sholazar Basin Mision

### ISSUE THREAD

**Issue by sleepyhouse** [RoDNet/Bugtracker-Infinium-4.3.4#2653]
http://www.wowhead.com/quest=12540/

La mision se completa al hablarle a un murloc. No se puede completar, porque el murloc no da la opcion para ello. Y sigue una cadena muy grande de misiones. El murloc esta en la orilla del rio

**Comment by redneo** [comment]
hay un cocodrilo en la isla de al lado que has de matar.
