### ISSUE TITLE
[Guerrero] (Talento furia) Trance de batalla

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#2655]
Nombre: Trance de batalla

Descripción: Tus ataques Sed de sangre, Golpe mortal y Embate con escudo tienen una probabilidad de hacer que tu siguiente facultad especial que consuma más de 5 p. de ira no cueste ira.

Fallo: está saltando con cualquier ataque, aunque creo que la probabilidad está más baja.

Observaciones: rara vez pasa pero se bugea visualmente y se queda el buff ahí pero en realidad no lo tienes.

ID del buff: http://cata.openwow.com/spell=12964

ID del talento:
Rango 1: http://cata.openwow.com/spell=12322
Rango 2: http://cata.openwow.com/spell=85741
Rango 3: http://cata.openwow.com/spell=85742

**Comment by DatJetto** [comment]
un 5% es una probabilidad muy baja, de manera que hay un 95% de proc que no salte, es decir, saltará con 5 de cada 100 ataques.

**Comment by searum** [comment]
fix
