### ISSUE TITLE
BUG MAGUE- TALENTO CONO FRIO MEJORADO

### ISSUE THREAD

**Issue by godiegreenstar** [RoDNet/Bugtracker-Infinium-4.3.4#2657]
Pues lo he estado testeando con todos los mobs de la zona y no congela a ninguno, aun no he probado con jugadores, pero vamos, que es un mini fallo :).

Os ayudare tanto como pueda con los bugs !

**Comment by Ceslick** [comment]
En jugadores si que funciona

**Comment by godiegreenstar** [comment]
Pues bueno, añadimos que a mobs no funciona ^^, también puede ser util para levear.
Gracias!

**Comment by ghost** [comment]
Pues empieza por leerte esto: http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

Y por BAJAR LAS MAYÚSCULAS PORQUE PARECE QUE ESTÁS GRITANDO TODO EL RATO, ¿Y NO ES ASÍ VERDAD?

Gracias xP

Añado que tampoco congela a los muñecos de ventormenta/ogrimmar.
