### ISSUE TITLE
BUG QUEST- JUGANDO CON FUEGO VIL

### ISSUE THREAD

**Issue by godiegreenstar** [RoDNet/Bugtracker-Infinium-4.3.4#2658]
Para hacer esta mision se necesita un item para absorver fuego vil, pues en ves de necesitar cojer de diferentes fuegos viles, esta bug y puedes cojer del mismo fuego vil spameando el objeto hasta completarla.
Os ayudare tanto como pueda con los bugs !, y si algo no es un bug hacermelo saber porfavor.
Att: Neferpitou

**Comment by Kiritoo** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
