### ISSUE TITLE
BUG QUEST- LLUVIA DE DIVERSION

### ISSUE THREAD

**Issue by godiegreenstar** [RoDNet/Bugtracker-Infinium-4.3.4#2659]
La mision consiste en disparar un item desde una torre(Torre del hachazo), y solamente hay 3 torres en el pueblo, he probado de todas las torres y siempre dice " REQUIERE TORRE DEL HACHAZO" supongo que esta bug ya que he probado de diversos lugares.

**Comment by Kiritoo** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
