### ISSUE TITLE
Algo raro... hablar lenguaje demoniaco xd.

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#266]
Buenas, hice un duelo con un brujo demonología, sucede que... cuando escribía algo (estando en el duelo), lo que decía salía en lenguaje... ¡demoniaco!, y eso que nunca supe hablarlo xd.
![wowscrnshot_070713_134113](https://f.cloud.github.com/assets/4663665/758911/dcb38f14-e764-11e2-8067-dbbe1282f3fc.jpg)

No sé también si sea un hechizo del brujo.. si alguien me lo puede confirmar.

**Comment by F4NT4SM4** [comment]
es por el debuff el segundo de la derecha hace que hablas en demoniaco y tardes mas en castear es un skill del brujo

**Comment by ghost** [comment]
Gracias Dragon, lo cierro entonces.

**Comment by ghost** [comment]
Por las dudas, también ocurre cuando estás en forma de metamorfosis.
