### ISSUE TITLE
[Warrior/Spell] Ataque de la victoria

### ISSUE THREAD

**Issue by Ceslick** [RoDNet/Bugtracker-Infinium-4.3.4#2663]
Nombre: Ataque de la Victoria(http://wow.freakz.ro/spells.php?spell=34428)

Descripción:Ataca al instante al objetivo, lo que inflige AP \* 56 / 100 p. de daño y te sana un 20% de tu salud máxima. Solo se puede usar durante los siguientes 20 segundos después de matar a un enemigo que aporte experiencia u honor.

Problema: Se esta activando con las cobras de los hunters, y supongo que sera igual con otros semejantes como las copias del mago o los arboles de los druida equilibrio

![captura de pantalla 2013-11-13 a las 22 57 12](https://f.cloud.github.com/assets/5348961/1536120/402b9c36-4cae-11e3-970d-45f8db67b0b8.png)
(No es la mejor de las imagenes pero cumple su cometido XD)

**Comment by Ceslick** [comment]
No lo he visto en el post recopilatorio asi que lo he posteado, si esta repetido avisar

**Comment by conqueron** [comment]
si eso es vedad el war ahora se cura con todo lo que matas
incluso si matar con ese mismo poder que antes no susedia

**Comment by Wiinter** [comment]
Matando pets tambien

**Comment by searum** [comment]
fix
