### ISSUE TITLE
[Druida restauración] Desenredo ID: 96429

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2664]
Enlace: http://wow.freakz.ro/spells.php?spell=96429

Descripción: Permite al druida eliminar todas las raíces y efectos de frenado al cambiar de forma.

Problema: Este talento es un beneficio pasivo por elegir la rama de <b>restauración</b>, y actualmente <b>todos los druidas (ferales y equilibrio)</b> se están quitando raices (roots) al cambiar de forma (pese a no tener esta facultad pasiva). El problema obviamente es que solo debería quitarse roots al cambiar de forma el druida <b>restauración</b>, <b>el resto no</b>, y además supone un beneficio inmenso.

Imagen (ver registro de combate, cambios de forma): 

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/854/wu39.jpg/'><img src='http://img854.imageshack.us/img854/9700/wu39.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img854.imageshack.us/img854/9700/wu39.jpg

P.D.Se acaba de fastidiar, esto antes estuvo correctamente reparado https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1936

**Comment by Dekadencee** [comment]
Fixed

**Comment by meybon** [comment]
En otras ramas debe quitar reduccion de movimiento al cambiar de forma, como venenos y esas cosas, ahora no quita nada.

**Comment by paellaencol** [comment]
Perdón, perdón. Se me olvidó mencionar una cosa y además es un fallo gordo mío, que me perdonen los druidas <b>equilibrio</b>.

Los druidas <b>equilibrio</b> sí que pueden quitarse los roots gracias al talento http://wow.freakz.ro/spells.php?spell=24858&name=moonkin-form <b>Pero sólo se las podrán quitar entrando o saliendo de forma de lechúcico lunar</b> http://wow.freakz.ro/spells.php?spell=24905&name=moonkin-form . Por ejemplo de forma de viaje a forma humanoides sólo se quitarían las ralentizaciones pero no los roots; sin embargo cambiar de forma humanoide a forma de lechúcico, y viceversa, debería eliminar tanto las ralentizaciones como los roots

Patch 4.0.6 (8-Feb-2011): Entering or leaving a shapeshift no longer cancels root effects. It continues to cancel movement slowing effects.; Moonkin Form now grants 15% damage reduction instead of increased armor. <b>In addition, shapeshifting in or out of this form now breaks roots</b> http://www.wowwiki.com/Moonkin_Form

En castellano: http://us.battle.net/wow/es/game/patch-notes/4-0-6
Ahora Forma de lechúcico reduce el daño un 15% en vez de aumentar la armadura. Además, ahora cambiar de forma, activando o desactivándola, rompe las raíces. <b>Hay que tener en cuenta que esto no se indica en la descripción.</b>

P.D. Espero no haber metido la pata, que ya de por sí hay pocos druidas equilibrio en pvp como para fastidiarles más.

**Comment by meybon** [comment]
Lo pone en el mismo cambio de forma, Lo que no debe quitar son cosas que te anclen al suelo, congelaciones raíces y cosas por el estilo, pero las ralentizaciones si las tiene que quitar porque en la barra de las formas cuando te pones encima de cualquiera lo pone al final en todas.
"El cambio de forma libera al taumaturgo de los efectos de reducción de movimiento". esto literal lo pone en equilibrio y feral también en todas las formas.

**Comment by Kiritoo** [comment]
Esta habilidad funciona perfectamente asi que cierro Issue.
Si el cambio de forma no elimina ralentizaciones se debe reportar aparte ya que no tiene que ver con está habilidad.
Saludos.
