### ISSUE TITLE
[BG's]Exceso de honor de recompenza

### ISSUE THREAD

**Issue by Keough** [RoDNet/Bugtracker-Infinium-4.3.4#2667]
Bueno, pensaba que alguien se iba adelantar en reportar, pero en vista que nadie lo hace, coloco este post sobre el problema de bgs.
El día 13/11/2013 hubo un reinicio en el server por bugs fixeados por deka, después de eso las BG's (todas) comenzaron a dar honor en exceso.
Por cada derrota da algo de 4.200 honor.
Por cada victoria da creo 10.000 de honor
El punto es que ganen o pierdan llegan al límite de 4k y pueden sacar varias piezas, y pese a saber eso los players están mandando como locos y comprando todo a su paso, la verdad es que aborrece ver eso ya que hubieron algunas BG's en las que solo se dejaban ganar para hacerlo rápido y ganen honor.
Ojala exista alguna reprimenda para estos players, gracias por todo, hasta la próxima.

**Comment by Keough** [comment]
No publico foto porque no estoy entrando a BG's y es imposible que algún player se atreva a negarlo. Gracias

**Comment by Dekadencee** [comment]
Si, soy consciente de ello, nos ponemos con ello ahora mismo, gracias por el reporte ^^
Respecto a los jugadores, por supuesto, si me pasáis una lista, empezamos a aplicar sanciones.

Un saludo ^^

**Comment by paellaencol** [comment]
También surgió anoche otro problema grande, los jugadores tienen plena movilidad de su personaje pese a estar en stun, fear, roots etc.

**Comment by Dekadencee** [comment]
@paellaencol: Eso ya esta corregido, y lo de las BG's creo que también, pero se está compilando.

Cabe aclarar que el error no ha sido nuestro: https://github.com/TrinityCore/TrinityCore/issues/10433 se ha producido por una de las actualizaciónes con TrinityCore.

La solución a todo esto, será hacer un pequeño roolback de items y currencies del backup, el resto de datos no serán afectados.

Un saludo ^^

**Comment by Drogoth2** [comment]
![image](https://f.cloud.github.com/assets/3939699/1539904/4134139e-4d15-11e3-8ed6-8f40525ecd79.png)
![image](https://f.cloud.github.com/assets/3939699/1539953/261cdd06-4d16-11e3-94f7-02110190db90.png)
Bueno estos son los resultados tras el arreglo que has hecho dekadence, perdiendo la bg ganamos 44 puntos de honor y, por cada muerte 1 de honor

**Comment by Dekadencee** [comment]
Lo que quiere decir que ya están en correcto funcionamiento ¿no?
¿Alguien tiene algo que objetar del estado actual de las recompensas de BG?

**Comment by paellaencol** [comment]
Si, es lo que debería dar con los rates x1. Lo que ocurre es desde que pusisteis el parche decidisteis subir los rates de honor a x3

**Comment by Dekadencee** [comment]
Lo de los rates x1 ha sido cosa mia con el fin de testear, ahora lo devuelvo a su correspondiente x3.
Gracias a todos por la colaboración en los testeos y por la paciencia esperando el arreglo.

Fixed! ^^
