### ISSUE TITLE
Errores aparecidos tras la actualización del 14/11/2013 0:00h

### ISSUE THREAD

**Issue by Dekadencee** [RoDNet/Bugtracker-Infinium-4.3.4#2668]
Abrimos este reporte para que listéis todos los errores aparecidos tras este mantenimiento, no para bugs generales, si no bugs que antes no estaban y ahora han aparecido.

Iremos resolviéndolos a lo largo del día de hoy.

**Comment by paellaencol** [comment]
<b>Glifo de palabra de poder escudo</b> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2101 Antes estaba bug y curaba dos veces en vez de una, ahora está bug pero al contrario, no cura ni una

**Comment by paellaencol** [comment]
Druida feral: <b>Flagelos de furia </b> https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2670 No respeta el CD interno

**Comment by Gurh** [comment]
Misiones DK: 

[La hojarruna blasonada] - Link: http://es.wowhead.com/quest=12619 

No se completa al usarla en la forja. 
Item: http://es.wowhead.com/item=38607

[La muerte viene de arriba] - Link: http://es.wowhead.com/quest=12641

Al coger el ojo de acherus, la velocidad de movimiento es muy reducida y no tiene los hechizos. 
Ojo: http://es.wowhead.com/npc=28511

**Comment by redneo** [comment]
He limpiado los fallos arreglados asi como los comentarios para dejarlo más limpio.

**Comment by ghost** [comment]
Los objetos de leveo que se compran al vendedor de hermandad (por ejemplo Yelmo de valor pulido http://es.wowhead.com/item=61931/) se ligan al alma en vez de ligarse a la cuenta.
Gracias!

**Comment by meybon** [comment]
Paladin heal: [Velocidad de la luz]  debe aumentar un % tu velocidad al usar protección divina. Problema, esta aumentando también con escudo divino.  Issue #2696 

~~Paladin general: [Abstinencia] Al usar imposición de manos, mano de protección y escudo divino, te debería de poner al usar cada una un debuff de 1 min llamado abstinencia que no te debería dejar usar otra de esas 3. Problema, no aparece el debuff y puedes usar las 3 seguidas. Issue #2695~~

**Comment by Wiinter** [comment]
<strong>Dots/Hots:</strong> Celeridad, se come tiks porque no duran los hechizos lo qe deberían #2697

**Comment by DatJetto** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2719

**Comment by meybon** [comment]
@nicerdicer Lo digo mas que nada porque lo pone en el mismo cambio de forma, Lo que no debe quitar son cosas que te anclen al suelo, congelaciones raíces y cosas por el estilo, pero las ralentizaciones si las tiene que quitar porque en la barra de las formas cuando te pones encima de cualquiera lo pone al final en todas.
"El cambio de forma libera al taumaturgo de los efectos de reducción de movimiento". Lo pone en equilibrio y feral tambien en todas las formas.

**Comment by paellaencol** [comment]
Druida equilibrio: <b>Oleada de estrellas </b>https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2775  Ya no está dando 15 puntos de energía lunar o solar al lanzarlo
