### ISSUE TITLE
[Druida feral] Flagelos de furia (ID: 80553)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2670]
Enlace: http://wow.freakz.ro/spells.php?spell=80553

Descripción: Cuando lanzas ataques automáticos bajo forma felina o de oso tienes un 15% de probabilidad de provocar un Flagelo de Furia que inflinje un 310% del daño con arma. Este efecto no puede tener lugar más de una vez cada 3 segundos.

Problema: no está respetando el cd interno de 3seg.

En la imagen se aprecia como ha saltado en 2 ataques automáticos consecutivos (1seg de margen)

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/706/g1n8.jpg/'><img src='http://img706.imageshack.us/img706/7674/g1n8.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img706.imageshack.us/img706/7674/g1n8.jpg

Observaciones: le está afectando además la spell <b>rugido salvaje</b> (ID:52610) cuando no debería

**Comment by searum** [comment]
fix
