### ISSUE TITLE
[Druida feral] Rugido salvaje (ID:52610)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2671]
Enlace: http://wow.freakz.ro/spells.php?spell=52610

Descripción: Remate que consume los puntos de combo de cualquier objetivo cercano para aumentar un 80% el daño inflingido con ataques automáticos. Solo se puede utilizar en forma felina. Se prolonga por cada punto de combo.

Problema: está aumentando un 80% a todos los ataques del druida, no solo los golpes blancos. Ahora mismo el druida está haciendo casi el doble del daño de lo que debería con todo.

**Comment by paellaencol** [comment]
Ejemplo:
Véase ese 80% más de daño gratis que está recibiendo con todo:
1. Destrozar y flagelos de furia <b> sin rugido </b>:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/707/d39h.jpg/'><img src='http://img707.imageshack.us/img707/1946/d39h.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img707.imageshack.us/img707/1946/d39h.jpg
1. Destrozar y flagelos de furia <b> con rugido </b>:

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/593/w2w6.jpg/'><img src='http://img593.imageshack.us/img593/3959/w2w6.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>
http://img593.imageshack.us/img593/3959/w2w6.jpg

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2392

**Comment by Kiritoo** [comment]
Aparecía como arreglado que tras testear se comprobo que no funcionaba.
