### ISSUE TITLE
Mision (Tierras altas crepusculares), Furia desatada

### ISSUE THREAD

**Issue by kalarjan** [RoDNet/Bugtracker-Infinium-4.3.4#2673]
Nombre: Furia desatada.
Descripción: El draco de Narkrral, Torth, sobrevivió al ataque fallido contra bramal y ahora la criatura se ha liberado de su antiguo dueño. 
Torth quiere vengarse de los faucedraco y ya arrasó Garganta de sangre una vez. Seguira volviendo hasta que lo destuyamos de una vez por todas. Ha llegado la horade usar la cadena del Demonio.
El antiguo nido de Torth es una pequeña caverna en las colinas, al oeste, que hemos convertido en un pequeño campamento llamado "La Garganta".
Reúnete conmigo en La Garganta y acabaremos con torth.
Problema: El npc no suelta la cadena, ni esta en el sitio que debería estar ni ella ni el dragón.

**Comment by Gurh** [comment]
Link de la misión: http://es.wowhead.com/quest=28133 (Misión)

Torth: http://es.wowhead.com/npc=47669 (Npc que falta)
Zaela: http://es.wowhead.com/npc=47671 (Npc que falta)

**Comment by redneo** [comment]
Arreglado, gracias por la ayuda Gurh
