### ISSUE TITLE
[Mision][Vega Tuercespina]

### ISSUE THREAD

**Issue by godiegreenstar** [RoDNet/Bugtracker-Infinium-4.3.4#2674]
La mision de llama Un patron inusual.

En la mision hay que utilizar un objeto para invocar un elemental y derrotarlo y quedarte con su corazon.

El fallo es que al utilizar el objeto no pasa nada, no aparece nadie, el objeto se utiliza pero no aparece ningun elemental.

Link wowhead: http://www.wowhead.com/quest=9457/

Imagen del lugar; 

![wowscrnshot_111413_221404](https://f.cloud.github.com/assets/5931642/1545681/1f80bff8-4d7a-11e3-972f-14d6de99dc6e.jpg)

**Comment by redneo** [comment]
Arreglado... antes salia, pero segun en la imagen a tu derecha a unos metros. Ahora sale en el altar y hace spells.
