### ISSUE TITLE
Bugs 

### ISSUE THREAD

**Issue by edgar520** [RoDNet/Bugtracker-Infinium-4.3.4#2675]
Hola.! tengo una mision en montañas crestagrama que se llama No tiene fin y esta bug se trata que al aceptarla uno tiene que ir al muelle y ahy deberia haber un barco y uno sube y lo llevan a otro lado del lago pero la acepto y voy y el barco no esta, si pudieran arreglar el bug se los agradeceria.

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
