### ISSUE TITLE
[Mago Frost] Barrera de hielo (ID: 11426)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2676]
Enlace: http://cata.openwow.com/spell=11426

Descripción: Instantly shields you, absorbing damage. Lasts 1 min. While the shield holds, spellcasting will not be delayed by damage.

Problema: está absorbiendo una cantidad fija de daño (infimísima) 8k, y además no está escalando con el poder con hechizos, absorbe como si tuvieras 0.

**Comment by Dekadencee** [comment]
Fixed

**Comment by paellaencol** [comment]
Me sigue absorbiendo 8069 puntos con o sin ropa :S
