### ISSUE TITLE
[Mision]Cargar

### ISSUE THREAD

**Issue by FullMetalX** [RoDNet/Bugtracker-Infinium-4.3.4#2677]
Lo que pasa es que cuando Practico cargar en un muñeco de entrenamiento no se completa el objetivo
Aqui una imagen
![wow 2013-11-14 06-07-34-52](https://f.cloud.github.com/assets/5943702/1546794/e604815c-4d8c-11e3-859c-d6e631bf5c58.png)

**Comment by Kiritoo** [comment]
Repetido, seguimos de https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3329
