### ISSUE TITLE
[Dk] Presencia profana.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#2679]
Nombre: Presencia profana.
ID: 48265
Link: http://wow.freakz.ro/spells.php?spell=48265

Velocidad de ataque y regeneriacion de runas aumentadas un 10%. Velocidad de movimiento aumentada un 15%, Tiempo de reutilizacion global reducido 0.5s.

Problema: No aumenta la velocidad de carga de runas.

En este ejemplo se ve como profano tiene la misma velocidad de carga que presencia sangre cosa que no debería ya que debería tener un 10% menos de tiempo de carga.

Presencia profano: http://www.subirimagenes.com/otros-wowscrnshot111413201-8697363.html

Presencia sangre: http://www.subirimagenes.com/otros-wowscrnshot111413201-8697365.html

**Comment by searum** [comment]
fix
