### ISSUE TITLE
[Dk] Escudo de sangre.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#2680]
Nombre: Escudo de sangre.
Talento: Rama sangre.
ID: 77513
Link: http://es.wowhead.com/spell=77513

Cada vez que te sanas con Golpe letal mientras estás en Presencia de sangre, ganas un % de la cantidad sanada como escudo de absorción de daño físico.

Problema: Se esta activando en presencia escarcha,pero no en sangre.

http://www.subirimagenes.com/otros-wowscrnshot111413200-8697381.html

**Comment by efectokoleos** [comment]
fix
