### ISSUE TITLE
[Misiones: Huarguen] Fallos y Mordedura

### ISSUE THREAD

**Issue by Gurh** [RoDNet/Bugtracker-Infinium-4.3.4#2681]
-----MORDEDURA-----

Cuando sale el video y sales "Encarcelado" en la madera como huarguen convertido, la mordedura no debería estar, impide que te transformes.

Herida de mordedura espantosa: http://es.wowhead.com/spell=76642

-----MISIONES-----

[¡Salva a los niños!] - Link: http://es.wowhead.com/quest=14368

Cuando hablas con ellos y los rescatas no te cuentan.

Cinthya: http://es.wowhead.com/npc=36287
Ashley: http://es.wowhead.com/npc=36288
James: http://es.wowhead.com/npc=36289

[El ettin hambriento] - Link: http://es.wowhead.com/quest=14416

Se completa sin hacer nada.

[Recuperar lo que es nuestro] - Link: http://es.wowhead.com/quest=24646/

El cuerno no invoca a nadie para distraer las forestales.

Cuerno de Tal'doren: http://es.wowhead.com/item=50134

[Rodea a los renegados] - Link: http://es.wowhead.com/quest=24677

Al hablar con Lord Hewell no te da ningun caballo.

Lord Hewell: http://es.wowhead.com/npc=38764

[La batalla por la ciudad de gilneas] - Link: http://es.wowhead.com/quest=24904

Es la que peor está, cuando la inicias entras en la ciudad y vas al objetivo, pero no puedes llegar, las barricadas de la primera fase de la misión "Sacrificios" sigue ahí al igual que muchos huarguens y no puedes llegar. Es como una mezcla de Phase.

[Hasta las rodillas] - Link: http://es.wowhead.com/quest=24678

La antorcha no espanta a las alimañas.

Antorcha medio quemada: http://es.wowhead.com/item=50220

[Rompen olas de cambio] - Link: http://es.wowhead.com/quest=26385

Cuando vas a costa oscura allí no se encuentra el npc, no puedes entregar.

**Comment by Monleon** [comment]
Las misiones de los huargens ya funcionan perfectamente de inicio a fin
