### ISSUE TITLE
[Misiones: Goblin] Fallos y WoW Error

### ISSUE THREAD

**Issue by Gurh** [RoDNet/Bugtracker-Infinium-4.3.4#2682]
-----WoW Error-----

Cada vez que coges algun item, una misión, o completas..

Te salta este WoW Error: http://es.tinypic.com/view.php?pic=9t0e8h&s=5#.UoYN5Ce1gYo

-----MISIONES-----

[Cargar] - Link: http://es.wowhead.com/quest=14013

Cuando lo haces a un muñeco no cuenta como completada.

[Tu nuevo yo] - Link: http://es.wowhead.com/quest=14109

Szabo no te vende el "Atuendo pistonudo".

NPC: http://es.wowhead.com/npc=35128
Item: http://es.wowhead.com/item=47046#objective-of

Gappy Dienteplata no te vende "Cadena de oro lustrosa".

NPC: http://es.wowhead.com/npc=35126
Item: http://es.wowhead.com/item=47045

Missa Mercadillo no te vende "Gafas de sol chulas".

NPC: http://es.wowhead.com/npc=35130
Item: http://es.wowhead.com/item=47047

**Comment by Kiritoo** [comment]
Estoy revisando este reporte.
[Cargar] - Link: http://es.wowhead.com/quest=14013 <b>Arreglada</b>

**Comment by Kiritoo** [comment]
Cada vez que coges algun item, una misión, o completas..
Te salta este WoW Error: http://es.tinypic.com/view.php?pic=9t0e8h&s=5#.UoYN5Ce1gYo <b>Arreglado</b>

**Comment by Kiritoo** [comment]
[Tu nuevo yo] - Link: http://es.wowhead.com/quest=14109 <b>Arreglada</b> 
Falta compilar.
