### ISSUE TITLE
[Mago-Frost]-Barrera de hielo

### ISSUE THREAD

**Issue by Santateresa** [RoDNet/Bugtracker-Infinium-4.3.4#2683]
Desde el último changelog del server se han visto afectada habilidades del mago frost y aunque a día 15/11/2013 dicen estar fixeadas en la web, no hay más que meterse y probar con un mago frost que esto no es así, la barrera de hielo absorbe 8000 puntos de daño, algo ridículo
Espero se solucionen los problemas ya que el mago frost lleva meses con el daño bajo a causa del bug en dedos de escarcha y ahora a demás sin defensa

**Comment by ghost** [comment]
Reportado, se puede cerrar https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2676
