### ISSUE TITLE
[Mago] Reflejo exacto

### ISSUE THREAD

**Issue by Santateresa** [RoDNet/Bugtracker-Infinium-4.3.4#2684]
Al igual que con barrera de hielo del mago frost este hechizo ha dejado de funcionar correctamente desde el último mantenimiento, a día 15/11/2013 y a pesar de poner que está fixeado lo cierto es que al castearlo no pasa absolutamente nada, no salen las copias directamente es como no tener esa spell.
Espero vuelva a la normalidad lo antes posible

**Comment by Dekadencee** [comment]
¿Seguro que no salen? A mi me funciona perfectamente :/

Ten en cuenta que cuando veas algo en el changelog, el .server info te de una hora superior al momento en el que confirmo el fixeo.

**Comment by paellaencol** [comment]
Sí, las copias ya funcionan bien.

Aunque deberían castear cada una de ellas "descarga de escarcha" de seguido, ahora mismo tienen una cadencia de 3segundos entre casteo y casteo.
