### ISSUE TITLE
[Sacerdote Sombras] Tortura mental ID: 15407

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2687]
Enlace: http://wow.freakz.ro/spells.php?spell=15407

Descripción: Ofusca la mente del objetivo con energía de las sombras, lo que inflinge (0.864x Poder con hechizos) de daño de las sombras durante 3segundos (reducible por celeridad) y ralentiza su velocidad de movimiento un 50%.

Problema: esta habilidad canalizada, es un hechizo de 3 ticks, en vez de eso está haciendo únicamente 2 ticks en pvp (sin haber padecido de retroceso alguno), el último tick ni lo hace, perdiendo por tanto un 33% del daño de esta habilidad.

---

Segundo problema:

Además hay problemas con el clipping, que desde la llegada del parche 4.1 no debería de por qué haberlos ya:

 Patch 4.1.0 (26-Apr-2011): Mind Flay should no longer lose a tick of damage when the last tick is clipped by another Mind Flay cast. http://www.wowwiki.com/Mind_Flay

Por si no ha quedado claro lo que es el clipping y como debería funcionar con "Tortura mental" <b> Mind flay</b> añado una página web aclaratoria http://www.howtopriest.com/viewtopic.php?f=19&t=1279

"When you clip a normal mind flay, the new mind flay will have 4 ticks. The rest of the previous one plus 3 additional ones for the new cast. So you don't clip after the 2nd tick, but instead you clip before the last tick. It might be after the 2nd tick, or it might be after the 3rd tick."

Problema: si clippeas con el tick, la próxima tortura mental no recibe ese tick extra de la anterior, te quedas con los ticks base, y además has perdido un tick de daño de la anterior canalización.

**Comment by efectokoleos** [comment]
arreglado

**Comment by Wiinter** [comment]
El que has arreglado?, porque el primer problema tiene pinta de ser cosa de la Celeridad que afecta a todos las clases. #2697 Y si lo arreglas y despues arreglas la celeridad algo malo pasará xD

**Comment by paellaencol** [comment]
El primer problema es únicamente pvp que hace 2 ticks, en pve sí que hace 3.

Lo que si guarda relación con lo de la celeridad que has enlazado es el clipping.

**Comment by efectokoleos** [comment]
falta compilar hombre xd

**Comment by Wiinter** [comment]
Yo no lo decía por compilar. Lo decía por lo del clipping que dice @paellaencol
