### ISSUE TITLE
[Sacerdote Disciplina] Escudo reflectante ID: 33202

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2688]
Enlace: http://wow.freakz.ro/spells.php?spell=33202

Descripción: Reflecta el 45% del daño que amortiguas con tu Palabra de poder: Escudo hacia el atacante. Este hechizo no genera amenaza.

Problema: pese a que sí esta reflejando bien la cantidad de daño, no obstante lo que no debería de hacer es reflejar esa cantidad por triplicado que es lo que está sucediendo ahora.

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/809/6l0v.jpg/'><img src='http://img809.imageshack.us/img809/8053/6l0v.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img809.imageshack.us/img809/8053/6l0v.jpg

**Comment by ghost** [comment]
El glifo de palabra de poder escudo inutilizaba el talento también, por lo demás antes funcionaba bien.

**Comment by paellaencol** [comment]
Sería posible deshabilitar este talento como se hizo con el rugido del druida?
Está concediendo una grandísima ventaja en combate, y cada vez se ven más sacerdote que nunca habían tenido puesto este talento, llevándolo ahora.

**Comment by efectokoleos** [comment]
ya esta arreglado
