### ISSUE TITLE
[Warrior/Armas] Maestría Táctica 

### ISSUE THREAD

**Issue by Ceslick** [RoDNet/Bugtracker-Infinium-4.3.4#2689]
Nombre: Maestría Táctica (http://wow.freakz.ro/spells.php?spell=12676)
![captura de pantalla 2013-11-15 a las 18](https://f.cloud.github.com/assets/5348961/1551692/113b42e4-4e18-11e3-9bb2-b57f73cf944c.jpg)

Descripción: Retienes hasta 50 p extra de tu ira cuando cambias de actitud

Problema: No retiene nada de ira, por lo cual al cambiar a actitud defensiva no se puede desarmar al mismo instante(cosa util contra otros armas por la filo o otros melee) o la incapacidad de hacer el stance dance.

Observaciones: Tambien hay un bug visual, cuando cambias de actitud se te queda la misma ira en la barra pero en realidad no tienes nada

**Comment by conqueron** [comment]
si el bug visula aveces cambias y tu puedes mirar que tienes 100 de ira cuando en realidad no tienes nada de ira. eso pasa cuando cambias de actitud.

**Comment by Kiritoo** [comment]
Fix, pruebalo cuando puedas.
El tema de la ira visual llena continua lo seguimos de este issue.
#1504 
Saludos
