### ISSUE TITLE
[Warrior/Armas] Segundo aliento

### ISSUE THREAD

**Issue by Ceslick** [RoDNet/Bugtracker-Infinium-4.3.4#2690]
Nombre: Segundo Aliento(http://wow.freakz.ro/spells.php?spell=29838)
Descripción: Cada vez que recibes un golpe con un efecto de aturdimiento o inmovilizador, generas 20 p de ira y un 6% de tu salud total durante 10 s.
![captura de pantalla 2013-11-15 a las 20](https://f.cloud.github.com/assets/5348961/1552995/aa30dba8-4e2c-11e3-8b3b-a3237accd137.jpg)
Problema: Salta con algunos buffos como poderio o proposito oscuro. 

Observaciones: Con los gritos de batalla y orden; e ira rabiosa no salta así que el propio warrior no puede echarselo a si mismo

**Comment by Kiritoo** [comment]
Hola no conseguimos reproducir el fallo cuando te refieres que "Problema: Salta con algunos buffos como poderio o proposito oscuro. ". No nos salta con ninguno de esos dos buffos.
Podrias ser mas exacto, gracias.
