### ISSUE TITLE
[Warrior/Glifos]Machaque colosal

### ISSUE THREAD

**Issue by Ceslick** [RoDNet/Bugtracker-Infinium-4.3.4#2691]
Nombre: Glifo de machaque colosal
Descripción: Tu machaque colosal también le aplica el efecto de hender armadura a tu objetivo.

Problema: No esta aplicando el efecto de hender armadura

**Comment by ghost** [comment]
Ya está reportado, fijaos antes de reportar plis

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2158
