### ISSUE TITLE
Portales

### ISSUE THREAD

**Issue by lexintor** [RoDNet/Bugtracker-Infinium-4.3.4#2692]
Los portales de  Ogrimmar hacia cataclism no funcionan 

No estan todos los portales en la zona Horda de Dalaran

**Comment by Ceslick** [comment]
Para poder usar los portales del cata necesitas coger las misiones de ``Orden de jefe de guerra: X sitio´´.

**Comment by lexintor** [comment]
gracias es verdad ;)

**Comment by ghost** [comment]
Se puede cerrar
