### ISSUE TITLE
[Paladin] Abstinencia

### ISSUE THREAD

**Issue by meybon** [RoDNet/Bugtracker-Infinium-4.3.4#2695]
Al usar imposición de manos, mano de protección y escudo divino, te debería de poner al usar cada una, un debuff de 1 min llamado abstinencia que no te debería dejar usar otra de esas 3.

Problema: no aparece el debuff y puedes usar las 3 seguidas.

http://es.wowhead.com/spell=1022/    mano de protección
http://es.wowhead.com/spell=642/     escudo divino
http://es.wowhead.com/spell=633/     imposición

**Comment by paellaencol** [comment]
Abstinencia http://es.wowhead.com/spell=25771

**Comment by Kiritoo** [comment]
Fix
