### ISSUE TITLE
[Paladin sagrado] velocidad de la luz

### ISSUE THREAD

**Issue by meybon** [RoDNet/Bugtracker-Infinium-4.3.4#2696]
http://es.wowhead.com/spell=85499/
Talento de heal que debe aumentar un %  tu velocidad al usar protección divina. http://es.wowhead.com/spell=498/

Problema, esta aumentando también con escudo divino.
http://es.wowhead.com/spell=642/

**Comment by Kiritoo** [comment]
Fix
