### ISSUE TITLE
[Dots/Hofs] Celeridad

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2697]
Hace unos días me dí cuenta que Corrupción y Aflicción inestable no duraban el tiempo adecuado sino que acaban antes. Gracias al aporte de Paellaencol, sabemos que no solo es cosa del Brujo Aflicción, sino que son mas clases. Entonces el problema podría radicar en la celeridad, por el tipo de error que está produciendo.
Como todos sabemos, la celeridad cuando llega a un cierto cap, proporciona un tik extra en el mismo tiempo de duración. Creemos que las habilidades estan contabilizadas por tiks y no por tiempo, por tanto cuando acaba de hacer los tiks termina y debería acabar cuando finalice su tiempo.

Los hechizos afectados por este problema son todos aquellos que tengan un daño periodico.

Aqui podemos ver cuando se le añaden los ticks extras a los dots del Brujo (http://www.mmo-champion.com/threads/812087-Hasted-DoT-s-and-Clipping), incluso te explica el Clipping que diría qe no esta ocurriendo.
Aqui explican como poder obtener el cap de cada DoT o HoT (http://www.mmo-champion.com/threads/712942-Guide-Channelled-Spell-amp-DoT-Mechanics-in-Cataclysm?highlight=Hasted+DoT%27s+Clipping)

**Comment by sprin69** [comment]
esto tmb pasa con aflicción inestable dura 2 o 3 segundos d menos

**Comment by paellaencol** [comment]
Sí, no es la única habilidad que se come un tick en función de la celeridad. También ocurre con las sanaciones en el tiempo como el "Renovar" del sacerdote o los hots del Druida. Es un fallo global a todas las clases.

Actualmente la celeridad está ayudando a que los ticks vayan más rapido (lo cual es lógico), pero está dando los mismos ticks, a cambio de disminuir la duración del buff/debuff.

Como debería ser? Las clases tienen una serie de caps en función de la celeridad, creo que el primer cap está en 12,5% de celeridad, lo cual te da un tick extra al DoT o al HoT, sin que esto afecte a la duración total del buff/debuff.

No se si ha quedado bastante claro, podrías reformular tu reporte incluyendo esto y el resto de hechizos en el tiempo? ;)

**Comment by Wiinter** [comment]
Eso de que le pasaba a las demás clases no lo sabía, ahora lo añadiré. 
En el brujo por ejemplo me he dado cuenta que Aflicción inestable tampoco dura lo que debe, en cambio los terrores van correctamente.
Lo de los caps de Celeridad diría, porque creo qe lo leí en algun sitio, que no todas las habilidades dan un tik extra en los mismos caps, pero ahora lo buscaré y lo confirmo. 
@paellaencol Añado Renovar, al reporte y a la espera que alguien más confirme cuales más no funcionan bien.

**Comment by paellaencol** [comment]
Toque vampírico (sacerdote sombras) http://wow.freakz.ro/spells.php?spell=34914&name=vampiric-touch

**Comment by paellaencol** [comment]
Sacerdote: Peste devoradora http://wow.freakz.ro/spells.php?spell=2944&name=devouring-plague
Sacerdote: Palabra de las sombras: dolor http://wow.freakz.ro/spells.php?spell=589&name=shadow-word-pain

**Comment by ghost** [comment]
Serán todos los hechizos, @paellaencol tiene razón. Supongo que podréis añadir los de mago fire e incluso los de caza, ya que parece fallo de celeridad más que de otra cosa.

**Comment by Necrofilo** [comment]
Si, añade la celeridad del mago fuego, no está añadiendo los ticks extra de la combustión, que es lo mejor del fire :(

**Comment by Kiritoo** [comment]
Los ticks extra son por parte de la celeridad, aumenta la velocidad de casteo actualmente pero no aumenta los ticks extra que debería otorgar la estadistica celeridad.

**Comment by sprin69** [comment]
este problema es comun a todas las clases incluso al rogue k deberia aumentarle la regeneracion d energia

**Comment by Wiinter** [comment]
La regeneracion de energia por parte de Celeridad es una cosa totalmente diferente a la que se está tratanto aqui

**Comment by sprin69** [comment]
si tiene k ver xk la regeneracion d energia es un beneficio extra como puede ser un tic mas en una pegatina
