### ISSUE TITLE
El item de ingenieria

### ISSUE THREAD

**Issue by sleepyhouse** [RoDNet/Bugtracker-Infinium-4.3.4#2699]
http://www.wowhead.com/item=67494/#comments

El item que creamos los ingenieros no da las propias volatiles cuando se hace mineria, herbalism, o skinning. Lo probe el dia de hoy con mi ingeniero con 498 de skill. Saque alrededor de 1000 diferentes Elementium ores/Obsidium ores con solo 4 volatiles de aire.

Porfavor arreglenlo si pueden n.n

**Comment by Monleon** [comment]
Esto funciona
