### ISSUE TITLE
Isabel Jones <Vendedora de bocetos de joyería> bug

### ISSUE THREAD

**Issue by thebigfer94** [RoDNet/Bugtracker-Infinium-4.3.4#27]
Isabel Jones <Vendedora de bocetos de joyería> 
http://es.wowhead.com/npc=50480

Problema:
El Npc te da la opcion de tomar la mision de Joyero. 
Deberia de darlos a los joyeros con un nivel de puntos + de 450 en joyeria.

No deberia de estar funcionan de esta manera, ya que cualquier personaje que no es joyero y no es mas de 450 puede coger esta mision.

![wowscrnshot_070313_175027](https://f.cloud.github.com/assets/4934365/746861/74636456-e43b-11e2-95e0-c6f6d63d7207.jpg)

**Comment by Dekadencee** [comment]
Fixeado, gracias por el reporte
