### ISSUE TITLE
[Items/Objetos] Cajón de Carne

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2705]
Buenas.
• Nombre: Cajón de Carne
• Enlace: http://es.wowhead.com/item=33857
• Descripción: "En su mayoría carne y lo que hubiese por ahí."
• Problema: Está vacío. Debería salir algo de esto http://es.wowhead.com/item=33857#contains pero ya es la tercera vez que me sale vacío.
• Observaciones: Recompensa de las diarias de cocina del PNJ El Rokk (http://es.wowhead.com/npc=24393)
Gracias y saludos!

**Comment by redneo** [comment]
Arreglado
