### ISSUE TITLE
[Items/Objetos] Barrica de pescado

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2706]
Buenas.
• Nombre: Barrica de pescado
• Enlace: http://es.wowhead.com/item=33844
• Descripción: "Tiene una etiqueta con un aviso: No disparar."
• Problema: Está vacío. Debería salir algo de esto http://es.wowhead.com/item=33844#contains. 
• Observaciones: Recompensa de las diarias de cocina del PNJ El Rokk (http://es.wowhead.com/npc=24393)
Gracias!

**Comment by redneo** [comment]
Arreglado
