### ISSUE TITLE
[Hechizos/Talentos][DK] Nervios de Acero Helado

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2707]
Buenas.
• Nombre: Nervios de Acero Helado
• Enlace: Rango 1 (http://cata.openwow.com/spell=49226) Rango 2 (http://cata.openwow.com/spell=50137) Rango 3 (http://cata.openwow.com/spell=50138)
• Descripción: Rango 3: Aumenta la probabilidad de golpear con armas cuerpo a cuerpo de una mano un 3% y aumenta el daño inflingido por tus armas de mano izquierda un 25%.
• Problema: Al ver la información del personaje, hay un aumento de daño en el arma de la mano izquierda, pero el índice de golpe sigue siendo el mismo. 
• Observaciones: ¿Bug visual quizá?
Gracias y hasta luego.

**Comment by searum** [comment]
visual
