### ISSUE TITLE
[Misión][Darnassus/Costa Oscura] Rompen olas de cambio (Huargen)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2708]
Buenas.
• Nombre: Rompen olas de cambio
• Enlace: http://es.wowhead.com/quest=26385
• Descripción: Habla con Vesprystus en el Poblado Rut'theran para contratar un vuelo hasta Lor'danel. 
• Problema: No está el PNJ Dentaria Claro de Plata (http://es.wowhead.com/npc=32973) para entregar la misión.
• Observaciones: El PNJ también se necesita para la misión "Se busca héroe: ¡Costa Oscura!" (http://es.wowhead.com/quest=28490)
Gracias y hasta luego!

**Comment by redneo** [comment]
arreglado
