### ISSUE TITLE
[Misión][Costa Oscura] Sabor a mero

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2709]
Buenas.
• Nombre: Sabor a mero
• Enlace: http://es.wowhead.com/quest=13537
• Descripción: Usa tu habilidad para la pesca para obtener 4 meros de Costa Oscura. 
• Problema: Estuve pescando 10 minutos y no pude conseguir ningún mero de Costa Oscura (http://es.wowhead.com/item=12238).
• Observaciones: Según los comentarios de Wowhead, se pueden pescar a lo largo de Costa Oscura con una habilidad igual o superior a 60 en la profesión Pesca.
Gracias y saludos!

**Comment by redneo** [comment]
estaba a un 8% lo he puesto a 40% si tienes la mision, tendria que ir.
