### ISSUE TITLE
[Misión][Costa Oscura] Un océano poco profundo

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2710]
Buenas.
• Nombre: Un océano poco profundo
• Enlace: http://es.wowhead.com/quest=13560
• Descripción: Gorbold Mano de Acero de Lor'danel quiere que hables con Gary para recibir más instrucciones. 
• Problema: Al usar la consola que está al lado de Gary (http://es.wowhead.com/npc=34205) para controlar el robot "Aventurero imprudente", este no tiene ningún comando para atraer a los murlocs ni para autodestruirse y matarlos (50 en total).
• Observaciones: Intenté atacar a los murlocs sin el robot y tampoco cuenta (hay que matarlos con el robot cebo sí o sí).
Gracias!

**Comment by redneo** [comment]
Arreglada
