### ISSUE TITLE
[Misión][Costa Oscura] La ira de los Ancestros

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2711]
Buenas.
• Nombre: La ira de los Ancestros
• Enlace: http://es.wowhead.com/quest=13514
• Descripción: Utiliza a un protector vengativo para matar a 30 trols Rompelanzas y destruir 6 edificios Rompelanzas. 
• Problema: No se pueden usar ningúno de los Protectores vengativos de la zona para terminar la misión. Tampoco puedo atacar cuerpo a cuerpo a los Campeones Rompelanzas (http://es.wowhead.com/npc=32858), sale la leyenda "No puedes atacar a este objetivo".
Gracias!!

**Comment by redneo** [comment]
Arreglada, creo que los npc se pueden pegar ya.
