### ISSUE TITLE
[Misión][Costa Oscura] Suministros de guerra

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2712]
Buenas.
• Nombre: Suministros de guerra
• Enlace: http://es.wowhead.com/quest=13509
• Descripción: Destruye 12 armamentos Rompelanzas. 
• Problema: Cuando uso el objeto Antorcha de centinela (http://es.wowhead.com/item=44999) se quema el PJ y no los Armamentos de Rompelanzas.
• Observaciones: Me aparece el buff "Prender fuego a los suministros de los Rompelanzas" (http://es.wowhead.com/spell=62624) y mi personaje se prende fuego.
Gracias!

**Comment by redneo** [comment]
Arreglado
