### ISSUE TITLE
[Misión][Costa Oscura] Conexiones Preocupantes

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2713]
Buenas.
• Nombre: Conexiones Preocupantes
• Enlace: http://es.wowhead.com/quest=13591
• Descripción: Lleva la misiva de Grito Infernal a la forestal Glynda Nal'Shea a Lor'danel. 
• Problema: No está el PNJ Forestal Glynda Nal'Shea (http://es.wowhead.com/npc=32971) para entregar la misión.
Gracias y hasta luego.

**Comment by redneo** [comment]
sale si tienes el anterior BT, pero lo he puesto que si tienes esa mision, puedas hacer las otras
