### ISSUE TITLE
[Misión][Costa Oscura] Una cata repugnante

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2714]
Buenas.
• Nombre: Una cata repugnante
• Enlace: http://es.wowhead.com/quest=13527
• Descripción: Recoge una muestra de un cadáver de oso en descomposición al este de la caja mecánica 413.
• Problema: No puedo despojar la muestra (http://es.wowhead.com/item=44911) del oso en descomposición que marca el mapa (http://es.wowhead.com/npc=32975).
Gracias!

**Comment by redneo** [comment]
Arreglada
