### ISSUE TITLE
[Misión][Costa Oscura] Poder sobre las olas

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2715]
Buenas.
• Nombre: Poder sobre las olas
• Enlace: http://es.wowhead.com/quest=13523
• Descripción: Utiliza el orbe de Elune en los restos de 6 espíritus de mareas iracundos. 
• Problema: Cuando uso el orbe provisto (http://es.wowhead.com/item=44975) contra los espíritus iracundos (http://es.wowhead.com/npc=32890), funciona y aparecen espíritus tranquilos (http://es.wowhead.com/npc=32937) pero no cuenta para completar la misión.
Gracias y hasta luego.

**Comment by redneo** [comment]
Arreglado
