### ISSUE TITLE
[Misión][Costa Oscura] Materiales de ritual

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2716]
Buenas.
• Nombre: Materiales de ritual
• Enlace: http://es.wowhead.com/quest=13566
• Descripción: Consigue 3 bigotes de Acechalunas, 3 mechones de pelo de cierva jaspeada y 3 pelajes de oso cardo. 
• Problema: No se puede conseguir ninguno de los objetos de los PNJ. Bigotes (http://es.wowhead.com/item=44969) de los Acechalunas (http://es.wowhead.com/npc=33127), Mechón de pelo (http://es.wowhead.com/item=45027) de cierva jaspeada (http://es.wowhead.com/npc=33313) y Pelaje (http://es.wowhead.com/item=45885) de oso cardo (http://es.wowhead.com/npc=33978).
• Observaciones: Según los comentarios de Wowhead, hay que despojar a los animales pero sin matarlos, es decir, aparece el ícono para despojar cuando los seleccionas.
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglado
