### ISSUE TITLE
[Misión][Costa Oscura] Eliminar por segunda vez

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2717]
Buenas.
• Nombre: Eliminar por segunda vez
• Enlace: http://es.wowhead.com/quest=13565
• Descripción: Utiliza la raíz petrificada para resucitar a 6 ents marchitos y matar a Lady Janira, la líder naga. 
• Problema: El objeto de misión Raíz petrificada (http://es.wowhead.com/item=45911) no funciona correctamente, ya que resucita a un ent sin la necesidad del cuerpo de un explorador Escama Oscura (http://es.wowhead.com/npc=33206) y no cuenta como completo.
Gracias y hasta luego!

**Comment by redneo** [comment]
Arreglada
