### ISSUE TITLE
[Misión][Costa Oscura] El retorno de Zarpadura

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2718]
Buenas.
• Nombre: El retorno de Zarpadura
• Enlace: http://es.wowhead.com/quest=13599
• Descripción: Vuelve con Volcor y con Zarpadura a Lor'danel. 
• Problema: No está el PNJ Serendia Susurrárbol (http://es.wowhead.com/npc=32972) para entregar la misión.
Gracias!

**Comment by redneo** [comment]
arreglado
