### ISSUE TITLE
[ Hunter > Master Marksman ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2719]
Maestro Tirador:
http://es.wowhead.com/spell=34487

Cuando lanzas Disparo firme tienes un 60% de probabilidad de ganar el efecto de Maestro Tirador, que dura 30 s. Tras alcanzar 5 acumulaciones, el tiempo de lanzamiento y el coste de enfoque de tu siguiente Disparo de puntería se reducen un 100% durante 10 s.

Bug tras la actualización:

Cuando lanzamos disparo firme se van aplicando los bufos de Preparen apunten ( http://es.wowhead.com/spell=82925 ) Acumulándose hasta 5, el problema es que cuando FIRE! salta, si lanzas un disparo firme y acumula Maestro Tirador el efecto Fire! desaparece, debiendo poder stackearse, también pasa cuando lanzas CUALQUIER OTRO DISPARO que no sea Aimed Shot, el proc se elimina.

Es decir, puedo tener el PROC FIRE! y a la vez Stacks de Master Marksman.

Fire!: http://es.wowhead.com/spell=82926

**Comment by Wiinter** [comment]
Tienes qe ponerlo en este #2668, el otro es para los bugs qe ya habían antes

**Comment by searum** [comment]
fix
