### ISSUE TITLE
[Montura] Mamut tundra viajero (post vuelto a crear)

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#272]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/54

En vista a ese post (ahi esta todo) esta confirmado que los pasajeros del mamut SI se pueden expulsar, por lo que otros compañeros o amigos se pueden subir.
(la vez pasada el reporte fue cerrado pensando que no se podian bajar, pero en efecto si se pueden expulsar.)

**Comment by ghost** [comment]
#218 repetido.
