### ISSUE TITLE
Bug Quest "Directo a las fauces"

### ISSUE THREAD

**Issue by gusnasoto** [RoDNet/Bugtracker-Infinium-4.3.4#2720]
Buenas, no hay más quest en hyjal para subir mas de level 81. La única activa es esta en hyjal. Pero no deja atravesar la puerta, le pueden echar un ojo plis ;)
Gracias

**Comment by redneo** [comment]
IDs de las misiones, fallos que dan, etc, etc 
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
