### ISSUE TITLE
[ Spells > Rapid Killing ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2721]
http://wow.freakz.ro/spells.php?spell=35099&name=rapid-killing

Cuando obtenemos este beneficio, nuestro AIMED SHOT hace un 200% menos de daño.

![wowscrnshot_111613_114723](https://f.cloud.github.com/assets/2728817/1556104/b6bcde46-4eac-11e3-8eff-df9a29c6c96b.jpg)

CON RAPID KILLING

![wowscrnshot_111613_114731](https://f.cloud.github.com/assets/2728817/1556105/bdcf1e2e-4eac-11e3-8757-0714f087fda4.jpg)

SIN RAPID KILLING 

Las pruebas están realizadas al mismo NPC con los mismos bufos.

Salta con cualquier objetivo que mates, debiendo solo saltar con objetivos que aporten Experiencia ( Para el nivel 85 creo que es lvl 77 en adelante ) u Honor ( Otros Jugadores )

**Comment by paellaencol** [comment]
Además está saltando contra objetivos que no aportan ni experiencia ni honor

**Comment by DatJetto** [comment]
Cierto, gracias, que se me olvidó añadirlo :)

**Comment by searum** [comment]
fix
