### ISSUE TITLE
[ Spell > Rapid recuperation ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2722]
http://es.wowhead.com/spell=53232

Cuando ganas el aura de matanza rápida obtienes 2 cargas de +50 y +50 de foco es decir 100 de foco.
- matanza rápida http://wow.freakz.ro/spells.php?spell=35099&name=rapid-killing

![wowscrnshot_111613_114723](https://f.cloud.github.com/assets/2728817/1556108/38b6e252-4ead-11e3-8e90-0f5837ecf0e6.jpg)

debería ser SOLO 1 carga de +50 de foco.

**Comment by searum** [comment]
fix
