### ISSUE TITLE
[Paladin] Fanatismo

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#2729]
Al usar el talento Fanatismo en la descripcion pone que no consume cargas de poder sagrado, sin embargo al utilizalo si las consume y por tanto se pierde un ataque de veredicto del templario.
![image](https://f.cloud.github.com/assets/3939699/1556531/f4471940-4ed7-11e3-8e92-335ee9d46710.png)
Lo pongo asi porque no he encontrado la id del talento

**Comment by Kiritoo** [comment]
Decargate el addon  Idtip para saber todas las ids, espero a que edites el reporte para no cerrarlo.
Saludos.

**Comment by Drogoth2** [comment]
http://wow.freakz.ro/spells.php?spell=85696 --> wow freak. aqui os dejo la id del talento fanatismo

**Comment by searum** [comment]
fix
