### ISSUE TITLE
[Paladin] Santidad de batalla 

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#2730]
http://wow.freakz.ro/spells.php?spell=25956 -->freakz.ro
Bueno pues lo que pasa esque no funciona, no reduce el tiempo de golpe de cruzado aunque lleves celeridad

**Comment by Kiritoo** [comment]
Ya reportado, no reportes cosas que ya esten reportadas por otras personas.
