### ISSUE TITLE
[Misión][Costa Oscura] La última oleada de supervivientes

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2733]
Buenas.
• Nombre: La última oleada de supervivientes
• Enlace: http://es.wowhead.com/quest=13518
• Descripción: Localiza a los refugiados de Auberdine que hayan sobrevivido. 
• Problema: No está ninguno de los PNJ a localizar. Los PNJ son:
Cerellean Zarpablanca http://es.wowhead.com/npc=33093
Gershala Susurro Nocturno http://es.wowhead.com/npc=32911
Shaldyn http://es.wowhead.com/npc=33095
Volcor http://es.wowhead.com/npc=33094
• Observaciones: Comentario del wowhead "Los cuerpos están en la playa tirados cerca del agua, hay que acercarse e interactuar para que cuente."
Gracias y hasta luego!

**Comment by redneo** [comment]
Arreglada cuando caiga el server
