### ISSUE TITLE
[Misión][Costa Oscura] Sonsacando a los espíritus

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2734]
Buenas.
• Nombre: Sonsacando a los espíritus
• Enlace: http://es.wowhead.com/quest=13547
• Descripción: Sonsaca a los espíritus de Thundris Tejevientos, Elissa Brisa Estelar, Taldan y Caylais Plumalunar. 
• Problema: No se puede interactuar con ninguno de los PNJ. Los PNJ son:
Thundris Tejevientos http://es.wowhead.com/npc=33001
Centinela Elissa Brisa Estelar http://es.wowhead.com/npc=33033
Taldan http://es.wowhead.com/npc=33035
Caylais Plumalunar http://es.wowhead.com/npc=33037
Gracias y hasta luego!

**Comment by redneo** [comment]
Arreglado cuando caiga el servere
