### ISSUE TITLE
[Misión][Costa Oscura] El vínculo del ritual

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2735]
Buenas.
• Nombre: El vínculo del ritual
• Enlace: http://es.wowhead.com/quest=13569
• Descripción: Respira el incienso delante del vigilante Karithus y, después, elige la bendición del gran espíritu del venado, el gran espíritu del oso cardo o el gran espíritu Acechalunas.
• Problema: Cuando uso el incienso que está delande del PNJ Vigilante Karithus (http://es.wowhead.com/npc=33048) no sucede nada y no puedo obtener así las bendiciones de los espíritus.
Gracias!

**Comment by redneo** [comment]
Arreglado cuando caiga el server
