### ISSUE TITLE
[Misión][Costa Oscura] A contraviento

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2736]
Buenas.
• Nombre: A contraviento
• Enlace: http://es.wowhead.com/quest=13542
• Descripción: Utiliza la Poza de la Luna de las Ruinas de Auberdine para destruir 8 conjuntos de brazales de ciclón demenciado. 
• Problema: No puedo usar la Poza de la Luna de la zona para destruir los brazales de ciclón (http://es.wowhead.com/item=44868/), sale la leyenda "Requiere Poza de la Luna de Auberdine"
Gracias y hasta luego!

**Comment by redneo** [comment]
Arreglado cuando caiga el server
