### ISSUE TITLE
[Misión][Costa Oscura] El Sueño Esmeralda

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2737]
Buenas.
• Nombre: El Sueño Esmeralda
• Enlace: http://es.wowhead.com/quest=13586
• Descripción: Atraviesa el portal pesadilla en la Caverna Rompetierra y habla con Thessera. 
• Problema: Luego de usar el portal pesadilla en la caverna, entro en otra fase pero no está en PNJ Thessera por ningún lado (http://es.wowhead.com/npc=33166).
Gracias.

**Comment by redneo** [comment]
Arreglada cuando caiga el server, y la siguiente.
