### ISSUE TITLE
[Misión][Costa Oscura] Sosegando a los elementos

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2738]
Buenas.
• Nombre: Sosegando a los elementos
• Enlace: http://es.wowhead.com/quest=13580
• Descripción: Coloca el tótem reconfortante cargado en la cima del arrecife que hay cerca de La Playa Llameante y protégelo hasta que se complete el ritual. 
• Problema: No me deja usar el tótem provisto (http://es.wowhead.com/item=46546) debajo de la piedra de llamas. Sale la leyenda "Requiere piedra de llamas en la Playa Llameante"
• Observaciones: Según el wowhead, hay que defender el tótem de unos PNJ y luego la cuenta como completa.
Gracias!!

**Comment by redneo** [comment]
Arreglado cuando caiga el server.
