### ISSUE TITLE
[Misión][Costa Oscura] El señor de la guerra Escama Oscura

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2739]
Buenas.
• Nombre: El señor de la guerra Escama Oscura
• Enlace: http://es.wowhead.com/quest=13899
• Descripción: Mata al señor de la guerra Espinas de ira dentro de Nazj'vel. 
• Problema: No cuenta al vencer al PNJ Señor de la guerra Espinas de ira (http://es.wowhead.com/npc=34423).
• Observaciones: Según los comentarios de wowhead, al vencer al PNJ queda en 1% de vida y se vuelve amistoso, así le entregas la misión y comienza La ofrenda a Azshara (http://es.wowhead.com/quest=13900).
Gracias y hasta luego.

**Comment by redneo** [comment]
Arreglada
