### ISSUE TITLE
[Sacerdote] Bug daño con hechizos - By Keltanas

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#274]
Bueno, como él no lo ha hecho, me veo en la obligación de hacer un copy & paste de lo que reporto en el foro xd

Aquí el enlace al foro donde lo hizo http://www.reignofdarkness.net/wow/foros/t1994/

> Hi bueno aca reporto esto q le paso al sacerdote ya q veo muchos lo notaron su daño bajo.
> bueno como quizas no sepan pero las mejoras de poder de hechizo como abalorios o encantamientos de profesiones que aumenten su poder con hechizos solo lo aumenta en su sanacion.en daño lo vuevle nulo.
> 
> aca pongo las fotos para q puedan hacer algo los gms:
> 
> foto sin activar abalorio:
> ![primero](https://f.cloud.github.com/assets/4663665/759538/d01de9c2-e78f-11e2-94f4-235cd37b22c2.jpg)
> 
> foto activando abalorio sin el aumento del daño:
> ![segundo](https://f.cloud.github.com/assets/4663665/759535/b7994c52-e78f-11e2-8b7f-4a986297ac6e.jpg)
> 
> esto aplica no solo en los abalorios sino en mis profesiones,de sastre y encanamiento no aumenta su daño en nada. 

Ahora, un aporte mio:

La "sanación con hechizos" solo se hace visible cuando se activa un abalorio/encantamiento o buff que suba el poder de ataque con hechizos o intelecto.

El encantamiento torrente de poder es lo único que si sube el daño con hechizos.

**Comment by Alfonn** [comment]
Pasa lo mismo con el mago, y creo que con todos los casters DPS.

Screens de Mago:
![image](https://f.cloud.github.com/assets/3854953/761969/2f5c13d8-e7df-11e2-840b-feaf6a93c6ae.png)
![image](https://f.cloud.github.com/assets/3854953/761972/3977f468-e7df-11e2-9789-d86212a45eed.png)

Un saludo.

**Comment by searum** [comment]
fiiiiiiiiiiiiiix
