### ISSUE TITLE
[Misión][Costa Oscura] La terminal de los titanes

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2741]
Buenas.
• Nombre: La terminal de los titanes
• Enlace: http://es.wowhead.com/quest=13918
• Descripción: Utiliza el detector de artefactos enterrados en la playa cerca de la Excavación de Tripirrem para localizar 5 fragmentos de aparato antiguo. Combínalos para crear el dispositivo ranurado antiguo. 
• Problema: No deja usar el detector provisto (http://es.wowhead.com/item=46388) en la zona marcada. Sale la leyenda "Requiere playa de Excavación de Tripirrem"
Gracias!

**Comment by redneo** [comment]
Arreglada cuando caiga el server
