### ISSUE TITLE
[Misión][Costa Oscura] Un nuevo hogar

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2742]
Buenas.
• Nombre: Un nuevo hogar
• Enlace: http://es.wowhead.com/quest=13910
• Descripción: Construye un cobertizo de múrloc en el emplazamiento marcado por Groff con una bandera en la orilla cercana. 
• Problema: Uso el objeto de misión Mansionador móvil múrloc maravilloso (http://es.wowhead.com/quest=13910) donde está el estandarte, pero no sucede nada y no se puede completar.
Muchas gracias.

**Comment by redneo** [comment]
Arreglado, no como me gustaria, pero no ha quedado mal, como siempre, cuando caiga el server.
