### ISSUE TITLE
[Misión][Costa Oscura] Las semillas de la vida

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2743]
Buenas.
• Nombre: Las semillas de la vida
• Enlace: http://es.wowhead.com/quest=13882
• Descripción: Reúne una Semilla de la tierra, una Semilla del mar y una Semilla del cielo. 
• Problema: No se puede conseguir la semilla de la tierra (http://es.wowhead.com/item=46354) ni la semilla del cielo (http://es.wowhead.com/item=46355). La semilla de la tierra debería entregarla el PNJ Onus (http://es.wowhead.com/npc=33072) y la semilla del cielo se consigue atrapando a un Fuego fatuo de Costa Oscura (http://es.wowhead.com/npc=34306).
Gracias!!

**Comment by redneo** [comment]
Arreglado
