### ISSUE TITLE
[Misión][Costa Oscura] Un disparo, una baja

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2744]
Buenas.
• Nombre: Un disparo, una baja
• Enlace: http://es.wowhead.com/quest=5713
• Descripción: Protege a la centinela Aynasha y luego ve a Vallefresno, a la Atalaya de Maestra, y habla con Onaeya. 
• Problema: No sucede nada. 
• Observaciones: Según un comentario de Wowhead "van viniendo Rastreadores (http://es.wowhead.com/npc=11713) de 2 en 2. Primero vienen 2, y si eres de lvl demasiado alto quizá los mates muy pronto. Espera que vendrán más, luego vienen otros 2, los matas y siges esperando. No os impacienteis, entonces vienen otros con Marosh (http://es.wowhead.com/npc=11714), tras matarle la quest finaliza." La misión aparece en el server como "Un tiro, un muerto".
Gracias!!

**Comment by redneo** [comment]
Arreglada cuando caiga el server :D
