### ISSUE TITLE
baba de elemental

### ISSUE THREAD

**Issue by shogun1968** [RoDNet/Bugtracker-Infinium-4.3.4#2745]
Desde el roll back , no tiran babas los elementales de cataclismo, por lo que no se puede completar la misión diaria de joyería de Ventormenta.

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by shogun1968** [comment]
vale, no se como se hace correctamente, así que pueden olvidar este reporte y cerrarlo.

**Comment by ghost** [comment]
Sólo hay que leer ese enlace que te puse hijo, si todos tiraramos la toalla así de fácil..

**Comment by shogun1968** [comment]
Muy señor mio, tengo casi 46 años (de ahí la cifra situada detrás del nombre), trabajo doce horas diarias de media fuera de casa y cuando llego, bastante cansado, me apetece jugar un rato para relajarme. Espero que me sabrá perdonar si no me encuentro con ánimos de ponerme a buscar por internet   lo que es un NPC, lo que es el enlace necesario y demás cosas que no conozco de antemano. Seguro que habrá alguien mas capacitado que yo que lo reportará en su momento. No me mal interprete, quiero aprovechar para agradecerles su labor, que me parece estupenda y aprovecho la circunstancia para felicitarles por el server, que me parece genial. Muchas gracias.

**Comment by DatJetto** [comment]
Yo te lo pongo chiquillo :)
- Baba Elemental: http://es.wowhead.com/item=52506

Objetivo de:
- Alianza: http://es.wowhead.com/quest=25156
- Horda: http://es.wowhead.com/quest=25162

Botín de:
- http://es.wowhead.com/item=52506#dropped-by

**Comment by paellaencol** [comment]
Sí que sueltan el objeto de misión, pero tienen un % de tirarlo muy muy bajo. Por ejemplo el mob más común de todos, los elementales de la entrada de hyjal http://es.wowhead.com/npc=40229 deberían tener un porcentaje de casi la mitad, y actualmente és probable que estén en torno a un 10%.

**Comment by shogun1968** [comment]
Muchas gracias por los enlaces, DatJetto. En cuanto al %, no te puedo decir paellaencol. Lo que si se, es que me he tirado cuatro días, una hora cada día, intentando sacarlas y no lo he conseguido.

**Comment by Compresor** [comment]
En 5 minutos farmeando elementales se pueden sacar.
