### ISSUE TITLE
Npc Dalaran - Mago acabado

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2749]
Enlace: http://es.wowhead.com/npc=32516#comments

Descripción: tras haber hecho una cadena de misiones:
"¿Dónde se esconde Hemet Nesingwary?
Bienvenido a la Cuenca de Sholazar
Necesitar un motor, coger un motor
Desventura de Ventura y Cía.
Tener una parte, dar una parte
Bórrale esa sonrisa de la cara
Domina el sable aterrador: convertirse en depredador
Domina el rinoceronte: la prueba
Algunos hacen limonada y otros hacen licores
Seguimos destilando
La prueba de la cata"

El npc "mago acabado" nos debería poder dar la misión "Objetos perdidos de Flechero" http://es.wowhead.com/quest=13571#comments. Ya que con esta misión es la única manera de conseguir la receta del "kungaloosh" http://es.wowhead.com/item=39644/#english-comments

**Comment by Wiinter** [comment]
Creo qe para hacer esa mision tienes qe tener minimo 375 de cocina, puede ser eso?
