### ISSUE TITLE
Algunos bugs Pícaro especialización Combate

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#275]
Buenas, a medida que voy encontrando bugs, voy editando el post, por ahora tengo:

Presición (http://www.wowhead.com/spell=13705 [Habilidad removida en Mists of Pandaria]: No funciona 
Golpe Revelador (http://es.wowhead.com/spell=84617): Se aplica correctamente en el objetivo, pero si un compañero de grupo/banda utiliza alguna habilidad dañina, desaparece.
Aluvión de Acero (http://es.wowhead.com/spell=13877): No funcionan ninguno de los 2 efectos.
Vitalidad (http://es.wowhead.com/spell=61329): No funciona el bonus de regen. de energía.

Ok, gracias y hasta luego.

**Comment by searum** [comment]
Te agradeceria hacer 1 reporte por bug. Cierro
