### ISSUE TITLE
premios de cocina bug 

### ISSUE THREAD

**Issue by lexintor** [RoDNet/Bugtracker-Infinium-4.3.4#2754]
la recompensa de las misiones de cocina diarias de dalaran dan premios y unos de estos premios es un distintivos de cocina de dalaran que bienn en la recompensa de estas misiones se quedan en el inventario y no se puede usar para nada

**Comment by ghost** [comment]
Si, al parecer se bugean los que vienen en las bolsas de especias al completar las diarias de cocina de dalaran (http://es.wowhead.com/item=44113).
El premio de cocina (http://es.wowhead.com/item=43016), debería acumularse junto a los que están en la pestaña de monedas (http://www.wowhead.com/currency=81).
Saludos!
