### ISSUE TITLE
[ NPC > Lillehoff ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2755]
http://es.wowhead.com/npc=32540

Este npc debería vender tras ser exaltados con hijos de hodir los mamuts correspondientes:

Alianza: 
http://es.wowhead.com/item=43958
http://es.wowhead.com/item=43961

Horda: 
http://es.wowhead.com/item=44080
http://es.wowhead.com/item=44086

**Comment by Wiinter** [comment]
No solo tras ser exaltado, sino tambien al haber completado la cadena de misiones de los Hijos de Hodir

**Comment by DatJetto** [comment]
Bueno, eso era obvio.

**Comment by Compresor** [comment]
Ya están los objetos
