### ISSUE TITLE
[Alquimia] Transmutaciones

### ISSUE THREAD

**Issue by BlackDeathh** [RoDNet/Bugtracker-Infinium-4.3.4#2756]
Bueno en resumen las transmutaciones de veraoro, pirium y elementos vivos (las de cata vamos) se supone que tienen un cd de 1 dia reiniciandose a medianoche pero el problema es que al principio si dice que es asi y despues de un tiempo cambian a ser 4 dias enteros (he esperado los 4 y hasta que han pasado no me ha dejado hacer nada).
Tambien pasa al reves con las transmutaciones de wotlk las de elementos eternos concretamente, tambien tienen 1 dia de cd pero despues de un rato o si te desconectas se reinicia al instante.

Un saludo

**Comment by Monleon** [comment]
Seguimos desde https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3036
