### ISSUE TITLE
[Misión] Tormenta Abisal - Cristales de gema de sangre

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2758]
http://es.wowhead.com/quest=10204

Matas aun magister Furia de Sol(http://es.wowhead.com/npc=18855) y te da un fragmento de gema de sangre(http://es.wowhead.com/item=28452). Y lo utilizas cerca de los cristales grandes qe hay.

El problema es que los magister no dan los fragmentos.

**Comment by ghost** [comment]
Arreglada.
