### ISSUE TITLE
Talento [Gloria Eterna] Paladin

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#276]
Buenos días.

Quisiera comentarles el estado del talento Gloria eterna http://old.wowhead.com/spell=87164  (rama de protección, primer tier) http://db.mmo-champion.com/utils/talents/#k=f3D.bqj.paladin.

Este talento durante las primeras horas de vida del parche estuvo funcionando. Es decir tenia una posibilidad que después de gastar [Palabra de gloria] http://es.wowhead.com/spell=85673 no consumiera nuestras cargas existentes de poder sagrado.
Actualmente las consume siempre.

Gracias.

**Comment by lamaza** [comment]
![wowscrnshot_090113_230631](https://f.cloud.github.com/assets/4790547/1065333/38454d9e-1385-11e3-9564-b93f13786a17.jpg)
Hoy sigue sin funcionar :/

**Comment by Dekadencee** [comment]
Fixed

**Comment by paellaencol** [comment]
Abro un post nuevo, sigue fallando

**Comment by paellaencol** [comment]
Lo explico mejor en un post nuevo, que ya le he cogido el truco a esto de reportar

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3309
