### ISSUE TITLE
[Misión] Tormenta Abisal - Criaturas de los Ecodomos

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2760]
http://es.wowhead.com/quest=10427

Bajas su salud por debajo del 20%, usas el marcador y entonces los duermes.

El problema es que bajas su vida al 20%, usas el marcador, los duermes pero no se marca en la mision.

**Comment by ghost** [comment]
Arreglada.
