### ISSUE TITLE
[Misión] Tormenta Abisal - ¡Atracadores viles, no gracias!

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2761]
http://es.wowhead.com/quest=10855

Hay que pillar 5 unidades de gas condesando de los mekingenieros y entonces se lo das a un atracador vil y entonces te deja hacer la siguiente mision.

Consigues las 5 unidades y se las das al atracador vil, pero no sucede nada mas.

**Comment by ghost** [comment]
Arreglada.
