### ISSUE TITLE
Mago - Misiles Arcanos 

### ISSUE THREAD

**Issue by bart576** [RoDNet/Bugtracker-Infinium-4.3.4#2767]
Al tener el hechizo Misiles Arcanos activo, si usas más hechizos y vuelve a saltar se te quita en vez de resetear los 20segundos que tienes para usarlo.
Gracias

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by Kiritoo** [comment]
Arreglado.
