### ISSUE TITLE
[Paladín] Bendiciones

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#277]
Un mismo paladín puede poner reyes y poderío en un mismo objetivo. Cuando debería solamente poderse poner reyes o poderío.

Bendición de reyes(http://es.wowhead.com/spell=20217)
Bendición de poderío(http://es.wowhead.com/spell=19740)

**Comment by crowel** [comment]
Parece que ya está bien wiinter, me pongo una y se me quita la otra.
Saludos! ;)

**Comment by Wiinter** [comment]
Ok, pues cierro
