### ISSUE TITLE
[ Achievements > Just Another day in Tol Barad ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2770]
Alianza: http://es.wowhead.com/achievement=5718
Horda: http://es.wowhead.com/achievement=5719

En el caso de la ALIANZA ( no sé como estará en la HORDA ) pero he conseguido realizar todas las misiones y no me ha dado el logro.

![wowscrnshot_111913_121745](https://f.cloud.github.com/assets/2728817/1572544/e9ee9060-511e-11e3-82f0-46a6293a8abd.jpg)

![wowscrnshot_111913_143155](https://f.cloud.github.com/assets/2728817/1572546/f9de3c6e-511e-11e3-8920-bb30bc052323.jpg)

**Comment by Wiinter** [comment]
En la horda totalmente funcional
