### ISSUE TITLE
[ Spells > Brittle Bones ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2771]
Huesos Quebradizos: http://wow.freakz.ro/spells.php?spell=81328&name=brittle-bones

Deja este Debuff en el enemigo con Fiebre de Escarcha: 
http://wow.freakz.ro/spells.php?spell=81326&name=brittle-bones

Pero cuando acaba fiebre de escarcha no se va y tienes 4% de daño físico para siempre.
![wowscrnshot_111913_142219](https://f.cloud.github.com/assets/2728817/1572579/beea6dac-511f-11e3-9a63-30e214c21aa8.jpg)

**Comment by elmiriox15** [comment]
Pasa lo mismo con el Frenesí sangriento, no encuento la id :S

**Comment by searum** [comment]
fix
