### ISSUE TITLE
[ Hunter > Explosive Shot ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2772]
Disparo explosivo: 
http://es.wowhead.com/spell=53301

Este disparo está escalando mal, actualmente el tooltip marca aproximadamente 5k y realiza ticks de 6,7 - 7k

**Comment by ghost** [comment]
[(372+0.273_RAP)-(449+0.273_RAP)]*Mastery

Fuente: Bugtacker de Molten, es la fórmula que tienen implantada.

**Comment by Jhovanni** [comment]
Me parece habría que revisar mejor, porque comparando con videos del oficial veo el daño estable.

**Comment by ghost** [comment]
Grom, a ver si puedes subir screens con tu caza y hacer unos cálculos para poner más pruebas plis, a mi también me parece que está subido.

**Comment by searum** [comment]
tiene la formula correcta
