### ISSUE TITLE
[ Spells > Bloody Frenzy ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2774]
Frenesí sangriento: http://wow.freakz.ro/spells.php?spell=29859&name=blood-frenzy

Deja el debuff: http://wow.freakz.ro/spells.php?spell=30070&name=blood-frenzy

El cual no se elimina al terminar el efecto de sangrado.

**Comment by searum** [comment]
darme los efectos de sangrado ^^

**Comment by Compresor** [comment]
Sangrados: 
Heridas profundas --> http://wow.freakz.ro/spells.php?spell=12867
Desgarrar --> http://wow.freakz.ro/spells.php?spell=772

**Comment by Kiritoo** [comment]
Arreglado.
