### ISSUE TITLE
[Druida equilibrio] Oleada de estrellas ID: 78674

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2775]
Enlace: http://wow.freakz.ro/spells.php?spell=78674

Descripción: hechizo de daño geoarcano (naturaleza-arcano) que genera 15 puntos de energía lunar o solar, dependiendo de lo que te convenga más (si estamos en eclipse solar, nos dará energía lunar, y viceversa)

Problema: da esos 15 puntos de energía cuando quiere. Además cuando los da siempre son de energía solar, cuando debería de ser en función de lo que más nos interesara.
Es decir, si acabamos de entrar en eclipse solar nos debe de dar energía lunar para acercanos al eclipse lunar lo más rápido posible, y viceversa.
Aunque con una pequeña puntualización, la primera vez que usemos "Oleada de estrellas" nos dará siempre energía solar. Esto sólo debe producirse cuando iniciamos combate por primera vez y la barra de "energía lunar-solar" está aún a 0; luego ya nos dará energía solar o lunar dependiendo de lo que más nos interese (explicado anteriormente)

2ºProblema: además la primera vez que lanzas oleada de estrellas al entrar en combate, está dando instant eclipse solar. En vez de dar solo 15 puntos de ENERGÍA solar

**Comment by Dazand** [comment]
#3798

**Comment by efectokoleos** [comment]
arreglado
