### ISSUE TITLE
[Druida equilibrio] Gracia de la naturaleza 

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2776]
Enlace: http://wow.freakz.ro/spells.php?spell=61346

Descripción: Ganas un 15% de celeridad con hechizos después de lanzar "Fuego lunar", "Recrecimiento" o "Enjambre de insectos" lo que dura 15segundos. Este efecto tiene un tiempo de reutilización de 1minuto (hasta aquí funciona). Cuando obtienes Eclipse lunar o solar, el tiempo de reutilización de "Gracia de la naturaleza" se reinicia instantáneamente (es decir el próximo "Fuego lunar", "Recrecimiento" o "Enjambre de insectos" te otorgaría de nuevo este buffo durante 15segundos más. Esto sí que no funciona)

Enlazo desde el reporte desde el que se reparó hace unos meses y está más detallado https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1152
El problema es que ahora ha dejado de funcionar, ya no reinicia el CD interno de "Gracia de la naturaleza" al obtener un eclipse, únicamente está saltando a cada minuto (es decir la primera parte del talento funciona, la segunda no)

**Comment by searum** [comment]
fix
