### ISSUE TITLE
(Gnomo) Problema con misión "A la superficie"

### ISSUE THREAD

**Issue by QuinoaPaladin** [RoDNet/Bugtracker-Infinium-4.3.4#278]
La misión "A la superficie" de los gnomos (http://es.wowhead.com/quest=27674/a-la-superficie) tiene el teletransportador bugueado y no se puede utilizar.

**Comment by crowel** [comment]
Está misión funciona, tras entregarla el propio NPC te teletransporta a la superficie.
Un saludo.
