### ISSUE TITLE
[Misión][Costa Oscura] El ojo de todas las tormentas

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2781]
Buenas.
• Nombre: El ojo de todas las tormentas
• Enlace: http://es.wowhead.com/quest=13588
• Descripción: Monta en Thessera para derrotar a 12 jinetes Crepusculares y destruye el Portal Crepuscular. 
• Problema: No está el PNJ Thessera para montar y hacer la misión (http://es.wowhead.com/npc=34401). Tampoco hay suficientes Jinetes Crepusculares (http://es.wowhead.com/npc=34282).
Gracias!!

**Comment by Smiithx** [comment]
tengo el mismo problema.
Añado un link de como debería realizarse esta misión: https://www.youtube.com/watch?v=HwCf-e_DDYc&feature=youtu.be
