### ISSUE TITLE
[Misión][Costa Oscura] El señor de la guerra Escama Oscura 2

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2784]
Buenas.
• Nombre: El señor de la guerra Escama Oscura
• Enlace: http://es.wowhead.com/quest=13899
• Descripción: Mata al señor de la guerra Espinas de ira dentro de Nazj'vel. 
• Problema: Molesto de vuelta con esta misión porque me expliqué mal la primera vez xD. Al parecer hay que vencer al PNJ Señor de la guerra Espinas de ira (http://es.wowhead.com/npc=34423), y luego su cuerpo sirve para entregar esta misma misión y seguir la cadena con La ofrenda a Azshara (http://es.wowhead.com/quest=13900), pero no se puede.
Gracias y disculpen las molestias!

**Comment by redneo** [comment]
Se pone neutral en cuanto le dejas al 20% de vida y si, realmente has de matarle para que de la mision :S no se si puedo hacer que de misiones muerto.

**Comment by ghost** [comment]
Perfecto, así está bien.
Muchísimas gracias!
