### ISSUE TITLE
[Cazador-Hechizo] Disparo de puntería y su coste

### ISSUE THREAD

**Issue by Vitoretto** [RoDNet/Bugtracker-Infinium-4.3.4#2787]
El hechizo señala que cuesta 50 puntos de enfoque para utilizarlo, pero gasta 50 puntos de enfoque para castearlo y después al dispararlo vuelve a gastar 50 puntos de enfoque, 100 en total que es la totalidad de enfoque de un cazador debería señalarse que va a costar 100 en total, o arreglar el segundo coste de enfoque.

**Comment by DatJetto** [comment]
Disparo de puntería funciona perfectamente, no cosume enfoque al empezar a castearlo.

**Comment by Kiritoo** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
