### ISSUE TITLE
[ Hunter > Pet's > Damage ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2788]
Los ataques básicos de la pet están realizando un daño del doble de lo que debería.
He de aclarar que cuando hablamos de mascotas del cazador entendemos 2 tipos de ataque principalmente:
- Ataque automático : Realizado al pegar cuerpo a cuerpo ( Este daño es correcto actualmente )
- Ataque básico : Realizado por las facultades básicas de las mascotas, a conocer estas 3:

Mordedura: http://es.wowhead.com/spell=17253
Zarpa: http://es.wowhead.com/spell=16827
Bofetada: http://es.wowhead.com/spell=49966

Este es el daño que es sobrepasado.

Con mi Cazador en Puntería; el tooltip ( nada de addons ) marca 1,5k de daño por Mordedura ( En este caso un lobo lvl 85 ) ( Estas facultades aumentan su daño dependiendo de los atributos del cazador ) Sin Embargo, mi mascota daña de 4,3k

Esto en un cazador bestias con su maestría y demás bufos lo convierte en un bug devastador.

Con un Cangrejo lvl 80 la Zarpa marca 1,4k y el daño que realiza es 4k

Con un Gorila de lvl 80 Bofetada marca 1,4k de daño y pega de 4k

**Comment by ghost** [comment]
Al fiin! Gracias Grom! https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2322

**Comment by redneo** [comment]
ajustado todo lo que he podido en superviviencia a lo que me dice el tooltip
