### ISSUE TITLE
[ Hunter > Pet > Catching ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2789]
Cuando capturamos una mascota, debería subir directamente a nivel del cazador ( Esto ocurre desde el parche 4.1 ) en vez de estar 3 niveles por debajo.

Patch Note:
- Tame Beast now tames pets to match the hunter's level, rather than 3 levels below.

Actualmente al capturar una mascota Si el cazador es lvl 85 y la mascota está por debajo de lvl 80, esta sube automáticamente al 80, debiendo subir hasta nivel 85.

Actualmente al capturar una mascota por encima de lvl 80 ( Estando el cazador al 85 ) la mascota se queda al nivel que la capturaste ( 81 - 85 ).

Este bug es algo molesto ya que hemos de perder tiempo leveando nuestras mascotas, de nuevo, en vez de tenerlas listas para combatir.

**Comment by Jhovanni** [comment]
Hay que agregar que aparte de tener que levearlas, el asunto de la experiencia que ganan cuando el cazador ya es nivel 85 es muy poco, po rlo cual cuesta más levear una mascota 5 niveles que un cazador los mismo cinco nivels del 80-85

**Comment by chechewas** [comment]
La verdad es que se lleva una buena cantidad de tiempo levear la mascota...

**Comment by Kiritoo** [comment]
Arreglado, pendiente de compilar.
