### ISSUE TITLE
(Gnomo) Problema con misión "La lucha continua"

### ISSUE THREAD

**Issue by QuinoaPaladin** [RoDNet/Bugtracker-Infinium-4.3.4#279]
Cuando te dan la misión (http://es.wowhead.com/quest=26208/la-lucha-continua) y te dicen de utilizar la holomesa no puedes hacerlo porque no puedes interaccionar con la mesa,no se puede terminar.

**Comment by crowel** [comment]
Está misión funciona perfectamente, no hay que interactuar con la plataforma.
Una vez cojes la misión empieza el evento.
Un saludo.
