### ISSUE TITLE
[ Hunter > Camouflaje V.3 ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2791]
Camuflaje: 
http://es.wowhead.com/spell=51753

Cuando un personaje se acerca cuerpo a cuerpo ( 5 metros o menos ) no puede atacar al cazador con camuflaje, ha de usar algún área. 

Esto no debería pasar y debería poder atacar cuerpo a cuerpo al cazador ( Solo con PJ's con NPC funciona correctamente ya que no deben vernos )

Por otra parte, cuando un pícaro usa Distraer el camuflaje del cazador se elimina, no debiendo ser así.

http://www.wowhead.com/spell=1725/#. Distract

**Comment by ghost** [comment]
Hay otro bug, Mandar la pet a atacar debe romper inmediatamente el camuflaje, incluso antes de que la pet comience a moverse.

Actualmente hay cazadores que se quedan en camuflaje y mandan la pet a atacar y permanecen un tiempo en camuflaje, no se si les saca al tiempo o sencillamente se lo quitan ellos para que no sea tan descarado.

Puede que el bug sea distraer, no camuflage, hay que probar si rompe Sigilo también.

**Comment by DatJetto** [comment]
No, Distraer no rompe sigilo, el bug es de camuflaje.
Y sí cierto, lo incluí en el viejo reporte del V.2 
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/812 

Pero con todo lo que puse, el pobre searum se hartó de trabajar.

**Comment by searum** [comment]
tienes que pegarle a melee.
