### ISSUE TITLE
[Dk] Glifo de socorro oscuro.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#2795]
Nombre: Glifo de socorro oscuro.
ID: 68793
Link: http://es.wowhead.com/item=68793

Tras matar a un enemigo que otorgue experiencia u honor, tu próximo Golpe letal en Presencia de escarcha o Presencia profana en los próximos 15s no costará runas y restaurará al menos un 20% de tu salud máxima.

Problema:Eso no esta ocurriendo,no se activa el efecto de este glifo y por ende no se cura ese 20%.

**Comment by searum** [comment]
fix
