### ISSUE TITLE
[Dk] Golpe con runa.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#2796]
Nombre: Golpe con runa.
ID: 56815
Link: http://wow.freakz.ro/spells.php?spell=56815

Golpea al objetivo y le inflige un 180% de daño con arma mas 2654p. Solo es usable en presencia sangre después de esquivar o parar un ataque. Este ataque no se puede esquivar, bloquear ni parar.

Problema: Tal como dice "Este ataque no se puede esquivar,bloquear,ni parar" y actualmente si lo están esquivando.

**Comment by F4NT4SM4** [comment]
Solo se puede usar en Precensia sangre O despues de esquivar o parar un ataque es decir en precensia sangre siempre deberia de dejarte usarlo en las otras precensia hace falta esquivar o parar y no esta dejando...

**Comment by DatJetto** [comment]
No, Dragøn, SOLO en presencia de sangre pero primero has de PARAR o ESQUIVAR, en las otras presencias aunque Esquivaras o Pararas no se activaría.

**Comment by F4NT4SM4** [comment]
Only usable while in Blood Presence, or for 10 seconds after the Death Knight dodges or parries

Traduccion:
Solo se puede usar mientras está en Presencia de sangre o durante 10 segundos después de que el Caballero de la Muerte esquiva o paradas

deberia de dejar usarlo en precensia sangre siempre y cuando tenga el poder runico que pide 
y para usarlas en otra precensia requiere esquivar o parar

**Comment by Compresor** [comment]
Arreglado
