### ISSUE TITLE
[Dk] Glifo de toque helado.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#2797]
Nombre: Glifo de toque helado.
ID: 58631
Link:  http://wow.freakz.ro/spells.php?spell=58631

Aumenta 20% el daño de tu fiebre de escarcha.

Problema: No lo esta haciendo.

**Comment by efectokoleos** [comment]
lo mismo, probado y funciona cierro
