### ISSUE TITLE
[I

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2798]
https://

**Comment by Sagittariu5** [comment]
Es decir, por ejm si me pongo el enchant de 50 de maestra de la capa y luego me pongo encima la base de tejido flexible lo que me da el paracaídas, ¿No se tendrían que reemplazar una con la otra, no?

**Comment by ghost** [comment]
Exacto.

**Comment by Jhovanni** [comment]
Pues solo quiero decir que la base de tejido flexible si debe de borrar el encantamiento anterior, no lo hacía en Woltk, pero a partir de Cata si, no de esa forma el otro que has mencionado.

**Comment by ghost** [comment]
Seg

**Comment by Jhovanni** [comment]
Cierto, el lugar donde había visto sobre el fix es de los preliminares de la versión. Por lo cual entonces apoyo el reporte y no debe quitar el encantamiento anterior.
