### ISSUE TITLE
[Mago] Barrera de hielo

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#2799]
http://www.wowhead.com/spell=11426
Está absorbiendo 8k y segun la fórmula con 7669 de poder con hechizos como tengo yo, (sin el glifo puesto), deberia absorberme bastante mas de 8k, como unos 18 o por ahi segun mis calculos

**Comment by ghost** [comment]
Ya está reportado https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2676
