### ISSUE TITLE
NPC Ithurian Lanzablanca bug

### ISSUE THREAD

**Issue by thebigfer94** [RoDNet/Bugtracker-Infinium-4.3.4#28]
El Npc Ithurian Lanzablanca
http://es.wowhead.com/npc=46180

PROBLEMA:

Este NPC Ya no deberia de estar ahi ya que fue eliminado en la 4.3.4 y lo unico que hace es confundir a los personajes. Ya que este NPC no deberia de Transfigurar.

![wowscrnshot_070313_174919](https://f.cloud.github.com/assets/4934365/746868/ce6cb178-e43b-11e2-8e44-55feb8d21a3d.jpg)

**Comment by Dekadencee** [comment]
Fixed
