### ISSUE TITLE
[Hunter > Chimera Shot]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#280]
Disparo de quimera
- http://es.wowhead.com/spell=53209
- Fórmula:  100% Daño con arma a distancia + (RAP*0.932)

Bugs: 
- Daño bajo, aproximadamente la mitad del daño.

![wowscrnshot_071113_200222](https://f.cloud.github.com/assets/2728817/783718/344299e8-ea56-11e2-9304-124bb065a8bf.jpg)

Aquí vemos como hacemos un Critical damage de 14.7k cuando de crítico debería realizar aprox 44k

**Comment by miglent** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/113

**Comment by crowel** [comment]
Sigue con los mismos errores esta habilidad.

**Comment by Hellythium** [comment]
también con picadura de serpiente combinada con disparo de cobra, este no aumenta el tiempo de picadura de serpiente en 6 segundos http://es.wowhead.com/spell=77767/disparo-de-cobra

**Comment by crowel** [comment]
Queria comentar que está habilidad ya cura y reinicia picadura, pero sigue haciendo la mitad del daño.

Saludos.

**Comment by searum** [comment]
ya lo puse mas o menos bien
