### ISSUE TITLE
[Druida equilibrio] Forma de lechúcico lunar ID:24858

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2801]
Enlace: http://wow.freakz.ro/spells.php?spell=24858&name=moonkin-form

Los druidas <b>equilibrio</b> sí que pueden quitarse los roots gracias al talento http://wow.freakz.ro/spells.php?spell=24858&name=moonkin-form <b>Pero sólo se las podrán quitar entrando o saliendo de forma de lechúcico lunar</b> http://wow.freakz.ro/spells.php?spell=24905&name=moonkin-form . Por ejemplo de forma de viaje a forma humanoides sólo se quitarían las ralentizaciones pero no los roots; sin embargo cambiar de forma humanoide a forma de lechúcico, y viceversa, debería eliminar tanto las ralentizaciones como los roots

Patch 4.0.6 (8-Feb-2011): Entering or leaving a shapeshift no longer cancels root effects. It continues to cancel movement slowing effects.; Moonkin Form now grants 15% damage reduction instead of increased armor. <b>In addition, shapeshifting in or out of this form now breaks roots</b> http://www.wowwiki.com/Moonkin_Form

En castellano: http://us.battle.net/wow/es/game/patch-notes/4-0-6
Ahora Forma de lechúcico reduce el daño un 15% en vez de aumentar la armadura. Además, ahora cambiar de forma, activando o desactivándola, rompe las raíces. <b>Hay que tener en cuenta que esto no se indica en la descripción.</b>

Problema: actualmente entrar o salir de forma de Lechúcico lunar no está quitando ni roots ni ralentizamientos.

Añado una vez más para evitar confusiones, sólo pueden quitarse los roots y los ralentizamientos al entrar o salir de forma de Lechúcico lunar; al cambiar entre otro tipo de formas distintas, que no involucren la forma de lechúcico lunar, sólo debe eliminar ralentizamientos, pero no roots.

**Comment by ghost** [comment]
Has puesto ni roots ni raíces, creo que te refieres a "ni roots ni ralentizaciones", después lo has puesto bien.

**Comment by Necrofilo** [comment]
Estaría bien arreglar lo que está sucediendo con el druida balance, ya que se le hace imposible escapar de un mele por el simple hecho de no poderse quitar las ralentizaciones al cambiar de forma.

**Comment by searum** [comment]
osea tanto rollo para:

Problema: actualmente entrar o salir de forma de Lechúcico lunar no está quitando ni roots ni ralentizamientos.

RESUMIR! que no necesito tanto rollo...

fix!
