### ISSUE TITLE
Warlock Demonology

### ISSUE THREAD

**Issue by sleepyhouse** [RoDNet/Bugtracker-Infinium-4.3.4#2802]
He estado jugando el Warlock demonology y me he fijado en varios bugs.

El primero: El Felguard no regenera mana como se supone y el talento de Mana Feed, no le da al felguard la mana necesaria.

El ataque LEgion Strike del Felguard tampoco hace el daño correcto.

Felstorm dice que hace weapon damage, y lo unico que hace es muy poquito daño.

Cuando el demonio se muere, hay un talento para que lo revivas de nuevo, y cuando lo haces el demonio ya no trae el bufo de Demonic Pact, por lo que hay que reloguear.

**Comment by Kiritoo** [comment]
Hola, lee esto o tendré que cerrar el reporte.
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Saludos.
