### ISSUE TITLE
la regeneracion frenetica del druida no cura esta bug urgente

### ISSUE THREAD

**Issue by maxib** [RoDNet/Bugtracker-Infinium-4.3.4#2804]
en arenas uso regeneracion frenetica y no cura nada ,es vital para un druida esta habilidad estando bug se nos complica es una gran desventaja si lo pudueran arreglar

**Comment by Kiritoo** [comment]
Cura perfectamente, intercambia ira por salud, seguramente ese es el problema y lo usas sin ira.
Cierro el Reporte por crearlo mal, lee esto  https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Si encuentras un fallo lo especificas bien y lo vuelves a reportar como ahi explica.
Saludos.
