### ISSUE TITLE
[ Reducción de daño por Armadura ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2807]
http://www.youtube.com/watch?v=O5wcvKq7Uck&feature=youtu.be

Yandros y yo estamos probando la funcionalidad de la armadura en el servidor, en las varias pruebas que hemos realizado, Yandros ( Sacerdote ) ha estado desnudo y a continuación se ha puesto unas gafas de ingeniería.

Disparo de puntería es el mejor disparo físico del cazador, hemos probado a lanzarlo y desnudo ha rondado 16k, a continuación con las Gafas de ingeniería el daño ronda de 14 - 15k , con solo 3,75% de armadura la reducción es de casi 2k también hemos de tener en cuenta que el daño del disparo está algo bajo, pero la reducción de armadura es brutal, también hemos de tener en cuenta que usa TELA, si ponemos una pieza de placas, esos 14k pasan a 11 - 12k.

![wowscrnshot_112213_115132](https://f.cloud.github.com/assets/2728817/1599996/3905f6ce-5364-11e3-9529-3c56b70086ad.jpg)

Sospecho de las características de Armadura y Temple, debido a que hace unos días de este mismo disparo hice 4k a un Dk en BG, lo cual me parece ridículo.

**Comment by ghost** [comment]
Sí, creo que el temple y la armadura no están muy ajustados...

**Comment by Jhovanni** [comment]
Es asunto de la armadura, reduce mucho.

**Comment by Jhovanni** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3539

**Comment by Kiritoo** [comment]
Arreglado, pendiente de compilar.
