### ISSUE TITLE
[Brujo - Maldición de las lenguas]

### ISSUE THREAD

**Issue by Santateresa** [RoDNet/Bugtracker-Infinium-4.3.4#2808]
Hola buenos días, he encontrado este bug en el hechizo de mi brujo Maldición de las lenguas el cual funciona correctamente excepto por la duración, debería durar 30 segundos como pone en la descripción del spell sin embargo solo dura 13, imagino que es algo fácil de cambiar y que se deberá a un error por haberlo confundido con la duración de otro spell.
Un saludo y gracias por su trabajo

**Comment by DatJetto** [comment]
http://wow.freakz.ro/spells.php?spell=1714&name=curse-of-tongues

No estoy muy seguro, pero hay habilidades que en JcJ reducen y el JcE su duración es mayor, aunque no lo explicite; Como polimorfia, Porrazo,Hex y demás.

**Comment by Santateresa** [comment]
nop, esta dura 30 segundos en pvp y en pve al igual que maldición de agotamiento, la cual dura los 30 segundos como debería

**Comment by ghost** [comment]
No, está durando lo que debe, tiene duración reducida para PvP como comentan arriba. Es el mismo caso que polimofia y porrazo.

De hecho, tengo serias dudas de que agotamiento deba durar 30s, creo que es agotamiento la que está bug, luego os confirmo.

Edito: Maldición de agotamiento sí que debe durar 30s de acuerdo con las patchnotes:

Patch 4.0.1 (12-Oct-2010): Now slows movement by 50% and lasts 30 seconds (Previously 30% for 12 seconds).
Patch 4.0.6 (8-Feb-2011): Curse of Exhaustion now reduces movement speed by 30%, down from 50%. Its range has been increased to 40 yards, up from 30.

Todo funcionando como debe por tanto.

**Comment by Santateresa** [comment]
Vale es cierto, he estado mirando los parches del wow y es verdad k esta reducido a la mitad la duración, me extrañaba mucho porque en la woltk no lo estaba y elementos o agotamiento no tienen reducción tampoco, cierro el post, gracias asman y dattjeto por la información
