### ISSUE TITLE
[Hunter > Steady Shot]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#281]
Disparo firme:
Fórmula:  100% Daño con arma a distancia + (RAP*0.218) 
http://es.wowhead.com/spell=56641
- Tiempo de casteo alargado.
  Actualmente se castea en 2.5 sec base, cuando debería ser 2 sec base. 

Si vamos a los datos de la spell veremos que efectivamente el tiempo está en 2 sec, pero desde la información base a la práctica en el servidor existe un delay de 0.5 sec, de manera que habrá que poner el tiempo base de casteo en 1.5 sec para que los jugadores casteen correctamente disparo firme.

![wowscrnshot_071113_200149](https://f.cloud.github.com/assets/2728817/783756/dcdc80e6-ea56-11e2-99e9-74be245e2840.jpg)

Tiempo de casteo en 2.43 con talentos de celeridad. cuando debería ser inferior a 2 sec.

**Comment by miglent** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/113

**Comment by crowel** [comment]
Mmm quiero añadir que usandolo justo cuando se lanza se para casi durante un segundo la regeneracion de enfoque, es normal¿? xD

Respecto a la velocidad de lanzamiento en la especificacion marca 1,93 pero al lanzarlo marca 2.40 en la barra de casteo.

**Comment by Hellythium** [comment]
Bueno, cabe también que cuando te toca un enemigo, mientras casteas esta hechizo que es algo muy lento, este se interrumpe, lo cual no debería de ser así, sino que se debería de retrasar el canalizamiento pero en lugar de eso se interrumpe, lo mismo para con cobra

**Comment by crowel** [comment]
Ya regenera foco, tiempo de caste todavia muy largo y referente al daño pega un poco de más pero está cerca de la media.

Un saludo.

**Comment by searum** [comment]
tanto el daño como la velocidad BASE como tu dices jetto estan bien, que cada vez q leo un reporte tuyo me echo unas buenas risas porque es que.. pfff yo sinceramente no se de donde sacas que se castea de base a 2.5 xD pero bueno...
