### ISSUE TITLE
[Chaman] Tótem de nexo terrestre

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2810]
Enlace: http://es.wowhead.com/spell=2484/

Descripción: Summons an Earthbind Totem with 5 health at the feet of the caster for 45 seconds that slows the movement speed of enemies within 10 yards.

Problema: el tótem se mueve junto con el chamán, debería estar estático. El tótem no puede ser atacable actualmente, salta la palabra "evadir"

Edito: esto está fallando desde ayer.

**Comment by paellaencol** [comment]
Y lo que es peor, no puede ser atacado, al intentar hacerlo salta la palabra "evadir", lo que obliga a comerse el debuff de reducción de movimiento del 50% durante la duración de todo el combate contra el chaman

**Comment by ghost** [comment]
No se si habrán cambiado algo, pero yo juraría que se puede matar el tótem ya.

**Comment by paellaencol** [comment]
Pero sigue moviéndose junto al chamán

**Comment by Kiritoo** [comment]
Arreglado.
