### ISSUE TITLE
Hechizo (Chaman) Lobo Fantasmal

### ISSUE THREAD

**Issue by toxicity93** [RoDNet/Bugtracker-Infinium-4.3.4#2811]
Nombre: Lobo Fantasmal
Enlace: http://es.wowhead.com/spell=2645
Descripcion: Convierte al chamán en lobo fantasmal, lo que aumenta su velocidad un 30%
Problema: al tener el talento "ligereza ancetral" que aumenta la velocidad base 15% activamos lobo fantasmal y solo aumenta la velocidad hasta 130% de velocidad base, cuando en realidad deberia hacerlo hasta 145%. Espero averme explicado bien

**Comment by paellaencol** [comment]
Descripción del talento de ligereza ancestral

Ancestral Swiftness    Rank 2
Reduces the cast time of your Ghost Wolf spell by 2 sec and increases movement speed by 15%. <b>This does not stack with other movement speed increasing effects.</b>

Descripción de lobo fantasmal:

Turns the Shaman into a Ghost Wolf, <b>increasing speed by 30%</b>. As a Ghost Wolf, the Shaman is less hindered by effects that would reduce movement speed.

El talento de ligereza ancestral ya te dice que ese aumento no se acumula con otros efectos que aumenten tu velocidad.

**Comment by toxicity93** [comment]
Ancestral Swiftness Rank 2: increases movement speed by 15%(velocidad basica)(115%)
Descripción de lobo fantasmal: increasing speed by 30% (basic+30%= 145%)
Ademas no leo en ninguna parte que no se acumule!.
Observación: As a Ghost Wolf, the Shaman is less hindered by effects that would reduce movement speed. NO CUMPLE

**Comment by searum** [comment]
no se acumula
