### ISSUE TITLE
[Sacerdote Disciplina] Contricción

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2812]
Enlace: http://wow.freakz.ro/spells.php?spell=81749

When you deal damage with Smite or Holy Fire, you instantly heal a nearby low health friendly target within 15 yards from the enemy target equal to 100% of the damage dealt.

If the Priest is healed through Atonement, the effect is reduced in half.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/37

---

Veamos ahora los problemas que tiene, contricción debería saltar al golpear con Punición http://wow.freakz.ro/spells.php?spell=585&name=smite y al golpear con Fuego sagrado http://wow.freakz.ro/spells.php?spell=14914&name=holy-fire

Problemas con punición: no está curando a un objetivo sino a todos, sólo debería curar al jugador aliado con la salud más baja en un radio de 15 metros del jugador atacado con punición.
El rango de 15 metros lo respeta (bien), pero en vez de curar al aliado con la salud más baja los está curando a todos (mal).

Problemas con Fuego sagrado: no está curando casi nunca al atacar a un enemigo; hay que repasar el rango de 15 metros porque parece ser que es bastante inferior en estos momentos; a veces cura a todos en vez de a uno solo; cuando cura lo está haciendo con un valor de sanación muy bajo y además prácticamente fijo (en torno a menos de la mitad de lo que debería).

Recuerdo que la sanación recibida debe ser igual al 100% del daño realizado (si el ataque ha sido crítico la sanación tendrá el valor igual al daño crítico causado también, esto solo funciona con punición). Aunque si el objetivo tiene talentos que le aumenten la sanación recibida, esta sanación se verá afectada también (esto sólo funciona con punición). Recuerdo también que si el jugador beneficiado es el sacerdote la cantidad de sanación recibida sera la mitad.

Y por último añadir que este talento se engloba en la categoría de "smart heals", sanaciones inteligentes que curan siempre al miembro con la salud más baja y no al que tenga la salud más alta.

P.D. sé que tiene que ser dificil de arreglar este talento

**Comment by ghost** [comment]
Buen reporte, aunque como dices debe ser difícil y, además, no se suele usar que yo sepa.

**Comment by paellaencol** [comment]
En PVE tiene bastante utilidad, piensa que aparte de ser healer serías además medio dps, y con el resto de talentos Tren de pensamiento, arcángel, evangelización lo convierten en una via muy interesante para curar.

**Comment by DatJetto** [comment]
Discrepo, curas a 1 objetivo y encima es Aleatorio dependiendo de la salud de los aliados, y le curas una sanación mínima, sería mejor curar normal antes de que un dps muriera.

**Comment by paellaencol** [comment]
When you deal damage with Smite or Holy Fire, you instantly heal <b>a nearby low health friendly target</b> within 15 yards from the enemy target <b> equal to 100% of the damage dealt</b>.

Más o menos eso ya queda claro, cura en función de la salud de los aliados, si hay un jugador con un 90% de vida, y otro con un 60%, curará al de 60%. La mecánica de las "smart heals" (sanaciones inteligentes) ya existía antes del cataclysm, esto no es nada nuevo. Además la curación que produce es superior a la que se puede obtener con "sanar". Pero hablar de todo esto ya sería salirse del tema y entrar en un debate si es mejor un sacerdote con estos talentos o sin ellos.

La mecánica del talento la he expuesto en el primer mensaje y con la intención de no ver sacerdotes disciplina que abusan de puniciones para curar a todo aliado, en vez de a solo un objetivo.

**Comment by efectokoleos** [comment]
arreglado

**Comment by paellaencol** [comment]
He estado probándolo, y con punición me atrevería a decir que funciona ya perfecto, tengo que probar lo de las smart heals, pero creo que va bien.

El problema ahora es con el otro ataque con el que debería saltar el proceso: Fuego sagrado http://wow.freakz.ro/spells.php?spell=14914&name=holy-fire que no está funcionando, no cura al inflingir daño
