### ISSUE TITLE
[Rogue sutileza] Talento: Honor entre ladrones

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#2813]
Spell ''Honor entre ladrones''

Descripción: http://cata.openwow.com/spell=51698

Honor Among Thieves
Rank 1
Instant
Increases the critical strike chance of all party and raid members by 5%. When any player in your party or raid critically hits with a spell or ability, you have a 33% chance to gain a combo point on your current target. This effect cannot occur more than once every 4 seconds.

TRADUCCIÓN:
Aumenta un 5% la probabilidad de golpe crítico cuerpo a cuerpo de todos los miembros del grupo o banda. Cuando alguien de tu grupo o banda asesta un golpe crítico con un hechizo o facultad, tienes un 33% de probabilidad de de ganar un punto de combo en tu objetivo actual. Este efecto no puede tener lugar más de una vez cada 4s.

Resumen: aparte de aumentar un 5% Pro.crit., tiene 33% de pro. de al asestar critico tú o tu compañero añadir 1 punto de combo a tu objetivo (CD de 4s.).

Problema: NUNCA da punto de combo extra aún así teniendo un 33% de probabilidad (con rango 2 = 66% y rango 3 = 100%).

**Comment by paellaencol** [comment]
Añado, la obtención de un punto de combo vía este talento no rompe el sigilo.

**Comment by Necrofilo** [comment]
Gracias por el aporte :P

**Comment by searum** [comment]
fix
