### ISSUE TITLE
[Sacerdote] Glifo de Palabra de poder: escudo ID:55672/56160

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2814]
Nombre: Glifo de Palabra de poder: escudo
ID:http://wow.freakz.ro/spells.php?spell=55672
Descripcion: Tu Palabra de poder: escudo además cura al objetivo con valor al 20% de la cantidad total de absorción.

Al aplicar el escudo a un personaje, este debería recibir una sanación con valor al 20% de la cantidad total de absorción del escudo.

P.ej. si el escudo es de 25k, debería recibir el escudo y además una sanación vía glifo de 5k

Problema: no está sanando ese 20%, es decir no funciona el glifo.

**Comment by ghost** [comment]
Referencio el issue para que se cierre cuando corresponda https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2101

**Comment by paellaencol** [comment]
http://wow.freakz.ro/spells.php?spell=56160&name=glyph-of-power-word-shield

**Comment by efectokoleos** [comment]
arreglado
