### ISSUE TITLE
No me funciona el huevo

### ISSUE THREAD

**Issue by Szajil** [RoDNet/Bugtracker-Infinium-4.3.4#2815]
Compré hace mas de una semana el "huevo misterioso" http://es.wowhead.com/item=39878/ de los oraculos...lo tuve en la mochila 3 o 4 dias y luego casi una semana enel banco y aun no me salio nada.....

**Comment by DatJetto** [comment]
Tienes que guardarlo en tu mochila, y creo que es por tiempo de juego. En 4.0.6 había un bug que tenía que estar en la mochila principal y jugar durante 7 días pra que se abriera.

**Comment by Drogoth2** [comment]
Todos los huevos que he tenido yo se abrieron estando una semana en el banco

**Comment by Szajil** [comment]
Si mirais la descripcion dice "Duración: 3 días (tiempo real)l\* llevo mucho mas tiempo con el...
