### ISSUE TITLE
[ Dungeon > Cámaras de Reflexión ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2816]
http://es.wowhead.com/zone=4820

El evento funciona bien hasta que llegamos a la oleada 5/10 donde uno de los 2 bosses de la primera fase sale a luchar contra nosotros y al matarlo las oleada siguiente ( debería ser la 6 ) no se produce y se reinicia el encuentro

**Comment by juaks** [comment]
Esta parte funciona perfectamente (al menos en modo normal).
