### ISSUE TITLE
Intelecto no da SP

### ISSUE THREAD

**Issue by meybon** [RoDNet/Bugtracker-Infinium-4.3.4#2819]
El intelecto no esta dando poder con hechizos, pense que solo era para mi druida pollo pero no esta dando a ninguna clase: magos, sacers....
solo tienes la bonificacion que te da el arma, el intelecto ya  no aumenta sp. Si esta dando mana.

**Comment by paellaencol** [comment]
Y las estadísticas de índice de golpe se han disparado, están dando más de lo que deberían en valor porcentual (aunque no sé si esto último es un bug visual o real)

**Comment by ghost** [comment]
Sí, el %hit está x2 aparentemente..
