### ISSUE TITLE
[ Hunter > Cobra Shot ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#282]
Disparo de cobra:
http://es.wowhead.com/spell=77767

Fórmula: 100% Daño con arma a distancia ( RAP*0.217)

Tiene los mismos fallos que disparo firme
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/281

![wowscrnshot_071113_201200](https://f.cloud.github.com/assets/2728817/783737/84d2d4ea-ea56-11e2-8c85-2a17894ba0ea.jpg)
![wowscrnshot_071113_201235](https://f.cloud.github.com/assets/2728817/783743/aba3b094-ea56-11e2-8509-b5e6c8783514.jpg)

Aquí vemos como está un poco por debajo de la media.

**Comment by miglent** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/113

**Comment by searum** [comment]
fix
