### ISSUE TITLE
[Rogue asesinato] Talento: Ímpetu mortal.

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#2820]
Spell ''Ímpetu mortal'': http://cata.openwow.com/spell=79122

Descripción: http://cata.openwow.com/spell=79122

Deadly Momentum
Rank 2
Instant
After killing an opponent that yields experience or honor, the critical strike chance of your next ability within 15 sec is increased by 40% and your Slice and Dice and Recuperate abilities are refreshed to their original duration.

TRADUCCIÓN:
Rango 2/2
Tras haber matado a un oponente que aporte experiencia u honor, la probabilidad de golpe crítico de tu siguiente facultad aumenta un 40% durante 15s y se restablece la duración de tus facultades Hacer picadillo y Reponerse.

Problema: No está restableciendo la duración de ''Hacer picadillo'' y ''Reponerse''.

**Comment by searum** [comment]
fix
