### ISSUE TITLE
[Rogue asesinato] Talento: Porra (problema con combate).

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#2821]
Spell ''Porra''

Descripción: http://cata.openwow.com/spell=79123

Blackjack
Rank 1
Instant
Even after your Sap wears off, its effects linger on enemies, reducing their damage done by 35% (70% rank 2) for 8 sec.

TRADUCCIÓN:
Rango 1
Incluso después de que Porrazo desaparezca, sus efectos persistirán sobre los enemigos, lo que reducirá el daño que inflijan un 35% (70% con rango 2/2) durante 8s.

Problema: al acabar el efecto de porrazo y afectar ''Porra'', está metiendo al rogue en combate.

**Comment by searum** [comment]
fix
