### ISSUE TITLE
[Rogue] estadísticas (celeridad).

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#2822]
Estadística: celeridad (rogue).

Descripción: Aumenta la velocidad de ataque y la regeneración de energia.

Problema: No está aumentando la regeneración de energía.

Demostración:
Imagen 1: Reg. energía con pantalones (aportan 215p. de celeridad).
http://kn3.net/3839F1A4D72JPG.html

Imagen 2: estadísticas de los pantalones demostrando los 215p. de celeridad.
http://kn3.net/41AD3C6AF98JPG.html

Imagen 3: Reg. energía al quitarme los pantalones restando 215p. de celeridad.
http://kn3.net/4021FEE4D7CJPG.html

Como se ve, la regeneración de energía no varía, la celeridad no está cumpliendo la función de aumentar la regeneración de energía.

**Comment by Wiinter** [comment]
Deber ser igual que la celeridad del feral, seguro que si arreglan uno, arreglan el otro

**Comment by Monleon** [comment]
Cuando se compile funcionará (aunque de momento no visualmente)
