### ISSUE TITLE
[Rogue sutileza] Glifo: Glifo de Hemorragia.

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#2824]
Glifo: Glifo de Hemorragia.

Descripción: http://cata.openwow.com/item=42967

Glyph of Hemorrhage
Major Glyph
Classes: Rogue
Requires Level 29
Item Level 29
Use: Permanently teaches you this glyph.
Your Hemorrhage ability also causes the target to bleed, dealing 40% of the direct strike's damage over 24 sec.

Glifo primordial
Tu facultad Hemorragia también hace que el objetivo sangre, lo que inflige un 40% del daño del golpe directo durante 24s.

Problema: arreglaron el daño del DoT, pero no está contando como sangrado y eso está perjudicando al talento ''Vena sangrienta'' (Vena sangrienta aumenta 16% el daño que infliges a objetivos afectados por un efecto de sangrado).

**Comment by searum** [comment]
fix
