### ISSUE TITLE
[Minas de la Muerte] Buff de ''secuaz ogro''

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#2825]
ID spell: http://es.wowhead.com/spell=92747/

Los adds de ''Minas de la Muerte'' modo heroico, dejan un buff en la party que reduce 100% el tiempo entre ataques cuerpo a cuerpo (tiene que durar hasta que el ogro deja de gritar).

Problema: Nunca desaparece ese buff, incluso al salir de la mazmorra sigue estando.

Imagen del buff: http://kn3.net/3786E108E9AJPG.html

**Comment by ghost** [comment]
Intentaste morir?

**Comment by Necrofilo** [comment]
El caso es que tiene que desaparecer el buff al morir el secuaz ogro y no lo hace.

**Comment by Dekadencee** [comment]
Fixed
