### ISSUE TITLE
Evento: Generosidad del Peregrino

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2826]
Oficialmente hoy se iniciaba el evento del Peregrino http://www.guiaswow.com/eventos/guia-evento-generosidad-del-peregrino.html el problema es que se ha iniciado el de la cerveza, en vez de éste.

**Comment by redneo** [comment]
Ya está. Lo he puesto que inicie un dia despues y lo he iniciado a mano, con lo cual a lo largo de hoy si no se cae el server estará, esperemos que no tenga muchos fallos.
