### ISSUE TITLE
[Rogue sutileza] Talento: Vena sangrienta.

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#2827]
Talento: Vena sangrienta.

Descripción: http://cata.openwow.com/spell=79147

Sanguinary Vein
Rank 2
Instant
Increases your damage dealt to targets with a Bleed effect on them by 16% and gives your Bleed effects a 100% chance to not break your Gouge.

Rango 2/2
Aumenta un 16% el daño que infliges a los objetivos afectados por un efecto de sangrado y tus efectos de sangrado tienen un 100% de probabilidad de no anular Gubia.

Problema: Los sangrados están anulando ''Gubia''.
Spell Gubia: http://cata.openwow.com/spell=1776

**Comment by ghost** [comment]
Lo mismo te digo, ya reportado https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1678
