### ISSUE TITLE
[Mago] Spell: Invisibilidad.

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#2829]
ID: 66

Descripción: http://cata.openwow.com/spell=66

Invisibility
16% of base mana
Instant 3 min cooldown
Requires level 78
?s54354[Instantly makes the caster invisible, reducing all threat.][Fades the caster to invisibility over 3 sec, reducing threat each second.]?s56366[ You move 40% faster while invisible.][] The effect is cancelled if you perform any actions. Lasts 20 sec.

TRADUCCIÓN:
El taumaturgo comienza a desvanecerse durante 3s, lo que reduce la amenaza cada segundo. El efecto se anulará si realizas cualquier tipo de acción. Dura 20s.

Problema: Al usar ''Invisibilidad'', tanto el mago como el resto de los jugadores o NPCs cercanos entran en combate (los rogues no pueden zapear al mago, los adds van a pegar al mago, etc.).

**Comment by ghost** [comment]
Ya está reportado noob, mira antes de reportar xP https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2111

Dale a Close.

**Comment by Necrofilo** [comment]
Asman pancho xD
