### ISSUE TITLE
[Hunter > Aimed Shot]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#283]
Disparo de puntería
http://es.wowhead.com/spell=19434

¡Disparo de puntería! ( Master Marksman )
http://www.wowhead.com/spell=82928

Ambos llevan la misma fórmula.
- Fórmula:  ( 160% daño con arma a distancia + (RAP*0.924) )
- Daño muy bajo.
- Cast time alargado. 

Esta spell debe de ser casteada en 2.9 sec, y como comento en el post de Disparo firme, actualmente es casteada en 3.4 sec base, por el 0.5 delay, se debe de scriptear a 2.4 sec de lanzamiento para que aumente a 2.9.

![wowscrnshot_071113_200214](https://f.cloud.github.com/assets/2728817/783700/e00bab76-ea55-11e2-911d-462f9bb6270a.jpg)

Aquí se ve un max Crit de 20k cuando debería realizar 31k aprox.

**Comment by miglent** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/113

**Comment by searum** [comment]
fix
