### ISSUE TITLE
Problema de cuenta

### ISSUE THREAD

**Issue by Mikeryublack** [RoDNet/Bugtracker-Infinium-4.3.4#2830]
Buenas, ayer cuando estaba jugando me invocaron para ir a una mazmorra, al aceptar la invocación salio la pantalla de carga pero esta no terminaba de cargar, al intentar cerrar el juego se bloqueaba y no me dejaba salir de la ventana del wow.

Apague el ordenador y volvi a entrar luego en mi cuenta, pero volvia a salir la pantalla de carga al entrar con mi personaje y no cargaba, 

Tras 5 o 6 intentos me decidi por reinstalar el juego, le dedico mi particion D del disco duro solo al wow, la formatee y a reinstalar, al ejecutar el exe ``ReignOfDarkness´´
se pone la ventanita pequeña a descargar datos de juego, pero cuando llega a la 3ª barra azul de carga se para y sale un mensaje diciendo que los datos de juego no se pueden descargar.

enfin, cuando iba a ir a mi primera mazmorra decente me quede sin juego,

¿alguna solución?

Saludos y gracias.

**Comment by DatJetto** [comment]
Te han hechado una maldición para que no juegues al wow, cubre tu ordenador de una variedad exhuberante de aromas y plantas curativas, en 15 días podrás volver a jugar.

**Comment by ghost** [comment]
Esto no es ayuda técnica, sino bugtracker xD

Pide ayuda aquí https://www.reignofdarkness.net/wow/forums/13-ayuda-tecnica/

Suertee! (:

**Comment by Mikeryublack** [comment]
Gracias asman, no sabia donde ponerlo
