### ISSUE TITLE
[Items/Objetos][Generosiad del Peregrino] Libro de cocina generoso

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2833]
Buenas.
• Nombre: Libro de cocina generoso
• Enlace: http://es.wowhead.com/item=46809
• Descripción: "La colección imprescindible de recetas de la Generosidad del Peregrino."
• Problema: No importa cuantas veces lo compre, siempre está vacío.
Gracias!!

**Comment by redneo** [comment]
esto... lo arreglé esta mañana :S

**Comment by Ceslick** [comment]
A mi me las ha dado todas, y eso que ya las tenia aprendidas

**Comment by redneo** [comment]
epic fail mia, pq arregle solo el de la horda, el de la ali, es otro item. Arreglado
