### ISSUE TITLE
[Brujo; Demonologia] Pacto Demoníaco

### ISSUE THREAD

**Issue by nicerdicer** [RoDNet/Bugtracker-Infinium-4.3.4#2835]
El talento [Pacto Demoniaco 47236] http://wow.freakz.ro/spells.php?spell=47236
Debe añadir 2% de poder con hechizos al brujo invocador y al resto de la party/raid, No da el SP ni si quiera aparece el bufo. Y los 10% de SP de base por parte del talento tampoco los cuenta.
![wowscrnshot_112413_234250](https://f.cloud.github.com/assets/4660334/1609800/0e80fed8-555a-11e3-820a-4eea8d61485a.jpg)

**Comment by ghost** [comment]
Creo que lo has malinterpretado o yo no entiendo bien la explicación, aclaro por si acaso:

Debe aumentar un 2% el daño con hechizos del brujo. Y además, cuando tienes un demonio invocado, se debe poner un buff tanto a ti como al demonio y todo el grupo / raid, que aumenta un 10% el poder con hechizos.

Por tanto, el brujo recibe un 12% de aumento de SP con este talento y suponiendo que tenga un demonio invocado, el resto de la raid un 10% por el bufo.

**Comment by Necrofilo** [comment]
El druida resto en forma de árbol tendría que lanzar recrecimiento instantaneo en movimiento, pero solo lo está haciendo si se queda quieto (por si es el mismo caso).

**Comment by Wiinter** [comment]
Necro creo qe te has colado de reporte

**Comment by nicerdicer** [comment]
Si bueno, la explicación de @asman1 seria bastante mas acertada dado el caso, ami se me ha pasado lo de que el 10% afectara tambien al grupo/raid, pero para el caso es el mismo, no funciona ni el 2 ni el 10%... xD y ese fallo para un brujo demon es garrafal!!

**Comment by searum** [comment]
fix
