### ISSUE TITLE
[Brujo; Demonologia] Infierno

### ISSUE THREAD

**Issue by nicerdicer** [RoDNet/Bugtracker-Infinium-4.3.4#2836]
El talento [Infierno 85105] http://wow.freakz.ro/spells.php?spell=85105
Debe permitir castear [Llamas Infernales] ID1949 en movimiento, esto no ocurre. En cambio, si se activa y luego te mueves se mantiene, aun que desaparece la barra de canalización.
![wowscrnshot_112413_235055](https://f.cloud.github.com/assets/4660334/1609817/8056feee-555b-11e3-895d-7bd32de24f0a.jpg)
Como se ve en el Screen no me lo permite castear en movimiento.

**Comment by searum** [comment]
fix
