### ISSUE TITLE
[Brujo; Demonologia] Mano de Gul'dan

### ISSUE THREAD

**Issue by nicerdicer** [RoDNet/Bugtracker-Infinium-4.3.4#2837]
El hechizo [Mano de Gul'dan]ID 71521 esta haciendo bastante menos daño del que le corresponderia http://wow.freakz.ro/spells.php?spell=71521
Daño normal con comparación por Dr.Damage. 7537 cuando deberia ser de 11.4K
![wowscrnshot_112513_000335](https://f.cloud.github.com/assets/4660334/1609855/0d1c20b0-555d-11e3-9b05-c4572e19e87a.jpg)

Daño Cririco con comparación por Dr.Damage 14K cuando deberia ser de 20K
![wowscrnshot_112513_000447](https://f.cloud.github.com/assets/4660334/1609858/2a7d3720-555d-11e3-941b-fa4e3b0f91df.jpg)

**Comment by DatJetto** [comment]
En tu tooltip ( que es de lo que más te debes fiar ) marca 9,7 y 8,6 debido a que se te activan Proc's, realiza la prueba sin partes de Sets que puedan interferir en aumentos de daño debido a encantamientos para sacar un resultado más fiable.

**Comment by nicerdicer** [comment]
Hmbre, no puedo colgar 5 screens con lo mismo en un mismo, post pero basicamente, en todos los casos, el daño rondaba esas cifras... que colagara esos screens con Procs activados, pues bueno, casualidad... pero Dr.damage tiene en cuenta esas variables, ya que tras pasarse los procesos el daño medio y critico que muestra baja, el tooltip sin embargo no tiene encuenta muchos multiplicadores, suelen ser mas orientativos que otra cosa (aun no he visto jamas que un ataque hiciera lo que especifican los tooltips la verdad). 
Aun que, el caso es el mismo, con set o sin el, el daño continua siendo bastante bajo para 7.5K intelecto que gasto con mi lock.

**Comment by Kiritoo** [comment]
Arreglado
