### ISSUE TITLE
[Objetos Battle.net] Ligados al alma.

### ISSUE THREAD

**Issue by obamakurosaki** [RoDNet/Bugtracker-Infinium-4.3.4#2839]
Hola buenas, 

el problema que tengo es que al intentar enviar la capucha y capa de Battle.net, me pone un mensaje con letras rojas donde me dice que los objetos están ligados a mi alma y no se pueden transferir. Los he comprado en el Npc que comercia con objetos de hermandad tipo tabardos, banderas, equipo, etc. 
Mi personaje principal es Lendrik y el otro personaje es Cranius.

Un saludo y gracias.

**Comment by Monleon** [comment]
Diria que esto ya no ocurre
