### ISSUE TITLE
[ Hunter > Camuflaje ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#284]
-Camuflaje http://es.wowhead.com/spell=51753

Descripción:

Te camuflas, mezclándote con tu entorno, lo que evitará que puedan seleccionaros como objetivo de ataques a distancia a tu mascota y a ti. También reduce el alcance al que pueden detectarte las criaturas enemigas y os proporcionará sigilo mientras no os mováis.

Puedes colocar trampas bajo este efecto, pero CUALQUIER DAÑO que inflijáis tú o tu mascota cancelará el efecto.

---

Cuando lanzas estas spells se elimina el aura de camuflaje, no debiendo ser así

2 - Empezar a Castear Spells:

Disparo de puntería: 
http://es.wowhead.com/spell=19434

Disparo firme:
http://es.wowhead.com/spell=56641

Disparo de cobra:
http://es.wowhead.com/spell=77767

Retirar mascota: 
http://es.wowhead.com/spell=2641

( Dato: En los disparos, el camuflaje debería quitarse cuando la flecha impacta sobre el objetivo, no cuando empiezas a castear de manera que casteas Disparo firme camuflado y cuando la flecha impacta al obetivo ahí si se elimina el camuflaje )

3 - Cuando la pet pone un buff de área como:
- Rugido de valor: http://es.wowhead.com/spell=93435
- Aullido furioso: http://es.wowhead.com/spell=24604
- http://es.wowhead.com/spell=53517
- http://www.wowhead.com/spell=53480
- http://old.wowhead.com/spell=53434

El camuflaje tanto para ti como para la pet se va, no debiendo irse.

4 - Cuando le pegan a tu pet, el camuflaje de tu pet ha de irse, el del cazador no, sin embargo, cuando la pet o yo hacemos daño, ahí si ha de quitarse para ambos.

5 - Cuando pones Marca del cazador sobre el objetivo: http://es.wowhead.com/spell=1130

6 - Cuando un pícaro lanza Distraer en el área donde te encuentras: http://www.wowhead.com/spell=1725

9 - Lanzar Bengala: http://es.wowhead.com/spell=1543
Video que explica el funcionamiento de camuflaje:

http://www.youtube.com/watch?v=tDBQjFzdqd0

**Comment by miglent** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/113

**Comment by searum** [comment]
fix
