### ISSUE TITLE
Logro evento:riesgo del peregrino bug (ALIANZA)

### ISSUE THREAD

**Issue by feniix97** [RoDNet/Bugtracker-Infinium-4.3.4#2840]
Logro:http://es.wowhead.com/achievement=3580
Bug: Mientras llevas puesto un vestido, toga o atuendo de peregrino, hay que sentarse en la mesa generosa de cada una de las capitales enemigas.
cuenta todas las ciudades menos entrañas para la alianza.

**Comment by redneo** [comment]
Vale, tenia mal la zona...

Lo he puesto que pida que estes en claros de tirisfal, ya que las mesas estan en claros, no en entrañas, peeeeero no se si hace falta que se reinicie el servidor o no lo coge bien. De todas formas como las sillas se mueven (algunas) si solo os falta ese logro, os montais en una silla, os acercais a Entrañas (pasado el foso y entrando en la primera puerta, cuando te sale el carte de Entrañas, territorio de la horda) os volveis a sentar y si que cuenta.

Espero que cuando caiga el server no haya que hacer eso.
