### ISSUE TITLE
Logro evento peregrino:compartir es querer (ALIANZA)

### ISSUE THREAD

**Issue by feniix97** [RoDNet/Bugtracker-Infinium-4.3.4#2841]
Logro:http://es.wowhead.com/achievement=3558/#criteria-of
Bug: al pasar un plato en cada una de las mesas generosas no te cuenta cada plato sin importar cuantas veces lo intentes.

**Comment by Szajil** [comment]
NO cuenta en entrañas "http://es.wowhead.com/achievement=3557" tampoco para la horda. Por otro lado...http://es.wowhead.com/achievement=3558 no funciona.

**Comment by redneo** [comment]
Arreglado, al menos con la alianza, con la horda pasará lo mismo ya que son los mismos requerimientos.
