### ISSUE TITLE
Misiones diarias Uldum

### ISSUE THREAD

**Issue by lexintor** [RoDNet/Bugtracker-Infinium-4.3.4#2843]
Esta http://es.wowhead.com/quest=28736 esta mal 

y esta no esta http://es.wowhead.com/quest=28250

**Comment by Kiritoo** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
