### ISSUE TITLE
LOGROS BUG DEL LOGRO GENEROSIDAD

### ISSUE THREAD

**Issue by geminis87** [RoDNet/Bugtracker-Infinium-4.3.4#2844]
Buenas las misiones "compartir es querer" esta totalmente bug ya que en ninguna ciudad deja realizarla y "panza del peregrino" te deja realizar en las 3 capitales de 4 menos en entrañas que tampoco deja, haber si podeis mirarlas antes de que acabe el evento gracias

**Comment by redneo** [comment]
reporte duplicado.... 

mirate https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2840
