### ISSUE TITLE
salva a los niños 

### ISSUE THREAD

**Issue by kayn111** [RoDNet/Bugtracker-Infinium-4.3.4#2845]
buenas pues la misión de salva a los niños de gilneas esta bugg por que por mucho que hablo con ellos como que los e salvado no cuenta

**Comment by Kiritoo** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
