### ISSUE TITLE
hechizo (cazador) Fingir muerte

### ISSUE THREAD

**Issue by toxicity93** [RoDNet/Bugtracker-Infinium-4.3.4#2847]
Nombre: Fingir muerte
Enlace: http://es.wowhead.com/spell=5384
Descripción: Finges estar muerto, lo que hace que los enemigos te ignoren. Dura hasta 6 min.
Problema: esta habilidad deberia SOLO fingir su muerte...pero ademas de eso, a los enemigos, les quita la seleccion del cazador.

**Comment by elmiriox15** [comment]
Eso que dices es la ira, el enfoque funciona igual que la energía del pícaro.

**Comment by Necrofilo** [comment]
1º: Toxicity93, si un hunter usa fingir muerte, te quita tanto el target como el foco (cosa que está correcta).
2º: Elmiriox creo que lo que dices no tiene nada que ver con este reporte xD

**Comment by Sagittariu5** [comment]
No te debería quitar tú target, basta con ver videos del ofi

Edito: http://www.youtube.com/watch?v=0axnbeleyl0 (ver minuto 1:10)

**Comment by elmiriox15** [comment]
Lo que yo comenté fue hace unas horas y este reporte era sobre el enfoque del hunter, ahora está totalmente editado xD.

**Comment by Necrofilo** [comment]
Oscarguns me refiero a que si tu eres el hunter y usas fingir muerte, a tu enemigo si te tiene seleccionado o en foco se le quita.

**Comment by Sagittariu5** [comment]
Esa parte está bien pensaba que se refería a que el cazador mismo perdía el target al fingir muerte

**Comment by DatJetto** [comment]
Fingir muerte, como bien dice el post y su tooltip, al usar esta facultad tus enemigos te ignoran, de manera que toda selección se elimina, tanto de Target como de Foco. Además existen otros problemas como que la barra de enfoque se pone a 0 tras hacerlo y al ''levantarte'' a veces se recupera y a veces no. Cabe destacar que esta habilidad no cuesta enfoque.

Otro problema es que a veces se bugea y no muestra su Cooldown, parece que está lista para usarla pero al pulsarla te dice que no está lista.
