### ISSUE TITLE
NPC venta equipo PvP viejo | Tormenta Abisal --> Área 52 

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#285]
Buenas, os explico, los npc que venden equipo pvp antiguo(classic, burning, lich king) no venden correctamente dichos items. El único que los vende bien del todo es 

Ahora procedo a poner los nombres y los enlaces de los que no venden nada de nada xD

Krixel Silbapellizco <Malla y placas clásicas de la Alianza>
http://es.wowhead.com/npc=23396

Leeni "Sonrisa" Menuda <Malla y placas clásicas de la Horda>
http://es.wowhead.com/npc=54648

Tini Menudilla <Tela y cuero clásicos de la Horda>
http://es.wowhead.com/npc=58152

Este está bien aunque debería vender los item por oro en vez de por honor:

Gran Zokk Llave Dinamométrica <Armas clásicas>
http://es.wowhead.com/npc=54649

Y por último el más importante de todos, el cual sólo vende equipo vengativo xD
Kezzik el Asediador <Equipo de Gladiador despiadado y vengativo>
http://es.wowhead.com/npc=54650

PD: No pongo fotos porque me parece tontería, ya que o no venden nada o venden parte...

Un saludo

**Comment by Dekadencee** [comment]
Fixed:
Grex Bullecerebros, aunque el texto que hay entre <> no aparece correctamente
http://es.wowhead.com/npc=40209

Lo borro de issue para no perdernos, falta lo demás paciencia

**Comment by crowel** [comment]
Acabo de revisar todos los npcs y todos tienen su loot.
Quiero comentar que el npc que comentabas Deka ya tiene su texto <>
El único fallo en los npcs la traducción de los nombres de 3 de ellos.
Cierro issue, cualquier cosa lo reabrimos.
Un saludo.
