### ISSUE TITLE
[Dk] Arma de runa danzante.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#2851]
Nombre: Arma de runa danzante
Talento rama sangre.
ID: 49028
Link:  http://wow.freakz.ro/spells.php?spell=49028

Invoca una segunda arma de runas que lucha sola durante 12 s y emula los ataques del caballero de la Muerte. El arma de runas también contribuye a la defensa de su dueño, lo que le otorga un 20% extra de probabilidad de parar mientras esté activa.

Problema: No aumenta 20% la probabilidad de parar.

**Comment by searum** [comment]
fix
