### ISSUE TITLE
[Sacerdote] Palabra de las sombras: muerte ID:32379

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2858]
Enlace: http://wow.freakz.ro/spells.php?spell=32379

Descripción: Una palabra de vínculo oscuro que inflinge X p. de daño de las sombras al objetivo. Inflinge el triple de daño a los objetivos con menos del 25% de salud.

If the target is not killed by Shadow Word: Death, the caster takes damage equal to the damage inflicted upon the target. (esta parte funciona bien, mejor obviarla)

Problema: desde hoy mismo ya no hace el triple de daño a los objetivos con menos o igual del 25% de salud, además ha dejado de funcionar el glifo de palabra de las sombras:muerte https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2859, y el talento "fundir mente" que la mejora (ID:33371) https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2860

Nota: hasta hoy mismo esta habilidad, el talento y el glifo mencionados funcionaban perfectamente según su descripción.

**Comment by efectokoleos** [comment]
prueba en el proximoreinicio
