### ISSUE TITLE
[ Hunter > Master Marksman ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#286]
Maestro Tirador:
http://es.wowhead.com/spell=34487

Cuando lanzas Disparo firme tienes un 60% de probabilidad de ganar el efecto de Maestro Tirador, que dura 30 s. Tras alcanzar 5 acumulaciones, el tiempo de lanzamiento y el coste de enfoque de tu siguiente Disparo de puntería se reducen un 100% durante 10 s.

Bug: 

Cuando lanzamos disparo firme se van aplicando los bufos de Preparen apunten ( http://es.wowhead.com/spell=82925 ) Acumulándose hasta 5, el problema es que deberían ser 4 y el 5 es ¡Fuego! ( Fire! ) el cual debe activar Disparo de puntería instant pero esto no pasa.

Fire!: http://es.wowhead.com/spell=82926

El hechizo: Aimed shot: http://es.wowhead.com/spell=19434 pasa a convertirse en
 Aimed shot instantáneo: http://www.wowhead.com/spell=82928

**Comment by miglent** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/113
