### ISSUE TITLE
Mago [Lanza de hielo +Dedos de escarcha]

### ISSUE THREAD

**Issue by Mikelodeon** [RoDNet/Bugtracker-Infinium-4.3.4#2863]
Hola!

Cuando se activan dedos de escarcha y lanzas el hechizo "Lanza de Hielo" la primera lanza no hace ningun daño, y tampoco sale reflejado. Y en las pocas veces que impacta y hace daño, no es daño critico, es el daño que hace un lanza de hielo en objetivos no congelados.

**Comment by ghost** [comment]
Dedos de escarcha no funciona, y la lanza tampoco. Ya está reportado.

http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
