### ISSUE TITLE
Viaje en alfombra magica

### ISSUE THREAD

**Issue by Avenger3** [RoDNet/Bugtracker-Infinium-4.3.4#2864]
la quest de tundra boreal en rasganorte de viaje en alfombra voladora, cuando hablas con yanni sale la alfombra pero no te deja subir y desaparece, con lo qual no te deja hacer la quest.
un saludo y gracias.

**Comment by Kiritoo** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
