### ISSUE TITLE
Viaje en alfombra magica

### ISSUE THREAD

**Issue by Avenger3** [RoDNet/Bugtracker-Infinium-4.3.4#2865]
la quest no funciona la alfombra voladora al hablar con yanni en tundra boreal en rasganorte, con lo cuant no te deja hacer la mision porque desaparece la alfombra.

un saludo y gracias.

**Comment by Kiritoo** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
