### ISSUE TITLE
[Sacerdote Sombras] Orbe de las sombras ID:95740

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2867]
Enlace: http://wow.freakz.ro/spells.php?spell=95740

ID de los orbes: http://wow.freakz.ro/spells.php?spell=77487

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/513/np29.jpg/'><img src='http://img513.imageshack.us/img513/8471/np29.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

Descripción (según mi equipo y talentos, el % de cada descripción depende del equipo de cada jugador):
Tienes un 18% de probabilidad de que tus hechizos "Palabra de las Sombras: dolor" y "Tortura mental" te otorguen un Orbe de las Sombras cada vez que inflinjan daño (esto funciona)
<b>Lanzar "explosión mental" o "pua mental" consume todos los Orbes de las Sombras (funciona), lo que aumenta el daño de este hechizo un 24% por cada Orbe de las Sombras (esto no funciona)</b>, y otorga un 24% más de daño a tus hechizos periódicos durante 15seg (esto funciona). Puedes tener un máximo de 3 orbes 

Problema: al consumir un orbe de las sombras (en mi caso) lanzando explosión mental o púa mental, cualquiera de estas debería tener un multiplicador de x1,24

al consumir dos orbes de las sombras (en mi caso) lanzando explosión mental o púa mental, cualquiera de estas debería tener un multiplicador de x1,48

al consumir tres orbes de las sombras (en mi caso) lanzando explosión mental o púa mental, cualquiera de estas debería tener un multiplicador de x1,72

Sin embargo no obtengo ningún multiplicador de daño al consumir estos orbes

Nota: esto hasta ayer funcionaba también. Además, desde ayer también aparece una animación sobre la barra de hechizos donde está "explosión mental" y "Púa mental" al conseguir un orbe de las sombras. Antes, cuando no existía esta animación, los orbes funcionaban.

**Comment by paellaencol** [comment]
Daño de explosión mental sin orbes: 15291
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/854/gh95.jpg/'><img src='http://img854.imageshack.us/img854/4298/gh95.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>
http://img854.imageshack.us/img854/4298/gh95.jpg

Daño de explosión mental con 3 orbes: 15321, y 30589 (crítico)

imagen que muestra que tengo 3 orbes (donde a priori debería tener un multiplicador, según mi equipo, de x1,72)
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/833/lcxq.jpg/'><img src='http://img833.imageshack.us/img833/8172/lcxq.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

y daño que estoy haciendo en realidad (sin obtener ningún multiplicador):

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/46/2vo5.jpg/'><img src='http://img46.imageshack.us/img46/771/2vo5.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img46.imageshack.us/img46/771/2vo5.jpg

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/824/fmcm.jpg/'><img src='http://img824.imageshack.us/img824/5825/fmcm.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img824.imageshack.us/img824/5825/fmcm.jpg

**Comment by searum** [comment]
fix

**Comment by paellaencol** [comment]
Abro en un nuevo post, sigue ocurriendo lo mismo que antes.
