### ISSUE TITLE
[Sacerdote Sombras] Sombras dominadas ID:78228

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2868]
Enlace: http://wow.freakz.ro/spells.php?spell=78228 (rango 2/2)

Descripción: Aumenta un 8% tu probabilidad de obtener un Orbe de las Sombras cuando inflinges daño con Tortura mental y Palabra de las Sombras: dolor (comprobar esto, ya que con ese % de tan solo un 8% me resulta muy difícil de obtener a mi), y tienes un 100% de probabilidad de obtener un orbe de las Sombras cuando recibes un golpe crítico de cualquier ataque (esto sí que es seguro que no funciona)

Problema: deberías tener un 100% de posibilidades de obtener un orbe de las sombras cuando recibes un golpe crítico de cualquier tipo (directo, físico, sangrado, dots mágicos, etc...). El problema es que no se obtienen.

Nota: hasta ayer esto funcionaba.

**Comment by DatJetto** [comment]
es un 8%, de 100 ataques saltarían 8 orbes. Son pocos, pero la cosa es que cada tick tiene 8% de manera que cuantos más ticks, más % tienes de sacar.

**Comment by paellaencol** [comment]
Si, más o menos. Sin el talento son un 10% de probabilidades, con el talento un 18%.
El problema es que es muy difícil de comprobar porque a los dummys no les entra ni los dots magicos, ni los canalizados
