### ISSUE TITLE
[ Hunter > Improved Steady Shot ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#287]
Disparo firme mejorado

 http://es.wowhead.com/spell=53224

Al lanzar Disparo firme dos veces seguidas, tu velocidad de ataque a distancia aumentará un 15% Durante 8 sec

A veces esta spell no se activa aunque lances 2 disparos firmes seguidos. Quizá la bugee la maestría del cazador puntería, picadura de serpiente o no se..

**Comment by miglent** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/113

**Comment by jaramys** [comment]
mmhm, me parece que tambien sucede si ases un ataque basico entre cada disparo firme, no se si esto deva ser asi, supongo que no, ya que en todo caso tendrias que dejar de atacar automaticamente,

**Comment by searum** [comment]
funciona perfectamente acabo de probarlo en localhost y en infinium y me va en ambos
