### ISSUE TITLE
diarias d tol barad (horda)

### ISSUE THREAD

**Issue by sprin69** [RoDNet/Bugtracker-Infinium-4.3.4#2870]
weno solo decir k en la horda solo se pueden cojer 6 misiones diarias en la alianza esta to2 correcto

**Comment by paellaencol** [comment]
Creo que 6 diarias es lo máximo posible en la península de tol barad, es cuestión de probabilidad que cada dia te den unas distintas. Lo que si seria un bug es que te las diesen todas

**Comment by sprin69** [comment]
el bug esta en la ali entonces xk se pueden cojer todas

**Comment by DatJetto** [comment]
No, en la Alianza uno de los npc te da 3 quest, que rotan por día y los otros 3 npc te dan 1.
