### ISSUE TITLE
tier 12 sacerdote healer

### ISSUE THREAD

**Issue by melcalla** [RoDNet/Bugtracker-Infinium-4.3.4#2877]
sale el efecto de regenerar 2 de mana de base , pero no la acción , en realidad solo regenera uno punto a secas.

**Comment by paellaencol** [comment]
Creo que te refieres al primer bonus del t12
http://es.wowhead.com/spell=99134/
Lanzar tus hechizos Sanación relámpago, Sanar, Sanación superior y Rezo de alivio hace que regeneres un 2% de tu maná de base cada 5 s durante 15 s.

ID del efecto: http://es.wowhead.com/spell=99132/ "Fuego divino"
Fuego divino
Regenerando un 2% de tu maná de base cada 5 s.
15 segundos restantes

**Comment by melcalla** [comment]
exacto es lo que me referia

**Comment by evangelion2009** [comment]
La cifra concreta que regeneraria independientemente de que seas disciplina o sagrado(ya que toma de referencia tu mana de base sin equipo ni nada) seria 410 por tick actualmente sigue igual dando solo 2Puntos de mana por tick.
