### ISSUE TITLE
[Misión][Cabo de Tuercespina] Tu primer día como pirata

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2879]
Buenas.
• Nombre: Tu primer día como pirata
• Enlace: http://es.wowhead.com/quest=26631
• Descripción: Lleva tus papeles al capitán Sinquilla. 
• Problema: No me dejó tomar la misión. Sale la leyenda "Esta misión no está disponible para tu raza" siendo worgen. La quise volver a tomar pero ya no estaba el "!" sobre el PNJ que la entrega (http://es.wowhead.com/npc=43504)
Gracias y hasta luego!

**Comment by redneo** [comment]
Ya te tendria que dejar cogerla, lo malo que hay un pequeño fallo despues (al menos con mi pj) y es que aun teniendo el bufo de pirateria, no te deja interactuar con los velasangre ya que los tengo odiados. Prueba a ver si tu tienes mas suerte.
