### ISSUE TITLE
[Hunter > Careful Aim]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#288]
-Afinar la puntería 

Aumenta un 60% la probabilidad de golpe crítico de Disparo firme y Disparo de puntería contra los objetivos con más de un 80% de salud.

( Cabe destacar que esta spell no aumenta tu crítico desde el x% que tengas hasta el 60% sino que lo suma, de manera que si tenemos 20% de crítico con nuestro personaje y el objetivo está por encima o igual al 80% de salud, obtendremos 20% + 60 % , haciendo un 80% de crítico )

http://es.wowhead.com/spell=34483

Bug: No tiene ningún efecto.

**Comment by miglent** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/113
