### ISSUE TITLE
[Brujo] [Talento] Semilla de corrupción: 86664

### ISSUE THREAD

**Issue by Felarof23** [RoDNet/Bugtracker-Infinium-4.3.4#2880]
El bug consiste en que no se está aplicando el efecto del talento a semilla de corrupción (id:27243), el cual debe aplicar corrupción a todos los enemigos afectado por la detonación.

![screen shot 2013-11-29 at 10 41 51 am](https://f.cloud.github.com/assets/5028343/1646259/bf75a662-5915-11e3-9b97-4719c89df213.png)

**Comment by searum** [comment]
fix

**Comment by Felarof23** [comment]
Perdón si soy aguafiestas pero aún no se activa el talento con Quemar Alma, por cierto, muchas gracias por todos los demás fix.

Saludos!

**Comment by Kiritoo** [comment]
Felarof23 Si algun fix no quedo solucionado completamente abrir un Issue nuevo.
Gracias.

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
