### ISSUE TITLE
[Brujo] [Talento] Mal fario: 85479

### ISSUE THREAD

**Issue by Felarof23** [RoDNet/Bugtracker-Infinium-4.3.4#2881]
No se esta aplicando el efecto del talento a la maldición de elementos (id:1490) el cual debería afectar a un máximo de 15 enemigos en 40m al rededor del enemigo maldito. 

![screen shot 2013-11-29 at 10 42 22 am](https://f.cloud.github.com/assets/5028343/1646286/819d6996-5916-11e3-9a01-d95d7a6f7c2f.png)

**Comment by searum** [comment]
fix
