### ISSUE TITLE
[ Hunter > Focus Bar ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2883]
Buenas, estos días me he percatado de que en BG o Mazmorras la barra de enfoque de los cazadores se vuelve totalmente loca, no mostrando los datos correctamente, recargándose instantáneamente y bajando mucho más de lo que debe al usar un disparo, esto es meramente visual, pero afecta muchísimo al rendimiento, ya que no sabes cuanto enfoque tienes para gastar y si puedes tirar habilidades o no.

Aquí dejo una prueba grabada donde vemos como el enfoque sube y baja al lanzar habilidades aún siendo gratuitas.

http://www.youtube.com/watch?v=hI4yuIoS38Q&feature=youtu.be

EDIT: ![wowscrnshot_113013_205438](https://f.cloud.github.com/assets/2728817/1650298/fa4d5b42-5a7b-11e3-9ed6-c2ec1312ce0d.jpg)

Añado una screen donde al estar sin morir ni nada, mi regeneración de enfoque se lanza por los aires hasta 73p por segundo wtf.

El bug viene concretamente de bufos que incrementan la regeneración de maná cada X segundos como Tótem fuente de maná y Bendición de Poderío.

**Comment by ghost** [comment]
Es por le bug de mp5, el aumento de regeneración es sólo visual, por lo que no podrás lanzar hechizos con el supuesto enfoque. Hace imposible saber cuánto enfoque tienes realmente

**Comment by cibernaco** [comment]
Este bug normalmente sucede por que interfieren los items o hechizos, o totems que regeneran mana.

**Comment by Kiritoo** [comment]
Arreglado bug visual, falta compilar. Si veis que falla en algun aspecto, ira, energia, enfoque.. avisad
