### ISSUE TITLE
[ Hunter > Lock and Load ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2884]
Bloquear y Cargar http://es.wowhead.com/spell=56343

Cuando atrapas a un objetivo con Trampa congelante o Trampa de hielo y cuando tu Flecha negra inflige daño tienes un 100% y un 20% de probabilidad respectivamente de que tus 2 siguientes Disparos explosivos no cuesten enfoque y no activen tiempo de reutilización.

Bug 1: Tu flecha negra en el primer tick ya activa lock and load siempre.
           Flecha negra: http://es.wowhead.com/spell=3674

Bug2: A veces, los disparos explosivos ''gratuitos'' no son gratuitos, cuestan enfoque ( Solo ocurre que cuesten enfoque, el tiempo de reutilización es respetado ) Generalmente, el 2º disparo explosivo es el que cuesta enfoque, el 1º funciona bien.

**Comment by cibernaco** [comment]
Primero de todo decir que no es tal y como esta reportado este error, de hecho el funcionamiento que tiene es totalmente correcto (casi). Para ello primero hace falta que se mire la descripción del hechizo ingame, es decir, la de la versión 4.3.4 y no esa que has descrito que es sacada de wowhead y por lo tanto está actualizada a una versión posterior, concreta mente a la 5.0.5.

A ver T.N.T tiene un 20% de posibilidades de activar Bloquear y Cargar "cada vez que hace daño periodico" (es decir tiene un 20% de posibilidades de activarse cada 2s durante 10 segundos. No solo al lanzarlo como ocurre directamente con las trampas y Bloquear y Cargar, de ahí la limitación a que solo se pueda activar Bloquear y Cargar 1 vez cada 10 segundos. En resumidas cuentas eso nos deja que con la trampa la probabilidad es del 100% siempre (aunque se "limpien" el daño periódico) y que con Flecha Negra es más que probable que se active el 100% de las veces (a no ser que se "limpien" evitando así el daño periódico.)

Bueno me he vuelto loco buscando vídeos que os dejen un ejemplo del funcionamiento correcto, pero no he conseguido encontrar ninguno en el que al menos una sola vez no se active en los 15 segundos siguientes tras disparar flecha negra, si alguno encuentra un vídeo donde se "falle" la activación como mucho tras 20 segundos de haber lanzado flecha negra que lo suba, mientras os dejo unos cuantos vídeos para que veáis que la probabilidad real de que se active es del 99.9% (dejo el 0.1% libre para no afirmar que es un 100%). Por cierto si conseguís ver la descripción de los hechizos y talentos en ingles os quedara mucho más claro ya que la traducción es un poco.... La única manera de que no se activara sería no poner puntos de talento directamente en T.N.T. y solo ponerlos en Bloquear y Cargar.

http://www.youtube.com/watch?v=FGXRRsb81Dk
http://www.youtube.com/watch?v=bbpSOoM3vUc
http://www.youtube.com/watch?v=TcbYZAcZAhY
http://www.youtube.com/watch?v=3X2hJS1bSJs

Pongo los cuatro primeros prácticamente, pero he visto más de 20 y en ninguno he visto que se falle.

Las diferencias reales entre este servidor y el oficial, es que aquí siempre salta 1,6s después de haber lanzado flecha negra, osea que la pequeña posibilidad de fallarlo queda eliminada, pero por ende también está eliminada la posibilidad de que se active 2 veces con un solo disparo o trampa ya que el efecto de la trampa y de la flecha duran 20 segundos (suficiente para saltarnos la restricción de que no se puede repetir dentro de los mismos 10 segundos), con lo cual realmente está equilibrado, son las gallinas que entran por las que salen.

Y el segundo disparo, cuesta enfoque solo si espameas el disparo, si dejas que el primer disparo haga su tic correspondiente, (1 segundo) el segundo disparo no cuesta enfoque nunca.

**Comment by DatJetto** [comment]
Mi rotación de Lock And Load es  
- Explosivo > Cobra / Arcano > Explosivo - Cobra / Arcano > Explosivo, 
  No spameo los 3 explosivos, ya que eso es desperdiciarlos.

**Comment by paellaencol** [comment]
@cibernaco Creo que DatJetto no se refiere a la probabilidad que tiene cada tick en activar el proceso, sino que en el primero siempre sea 100%.

**Comment by cibernaco** [comment]
Si si, estoy de acuerdo en que siempre se activa en el primero, a lo que me refiero es a que en la practica al final es lo mismo, da igual que se active en el primer tick que en el ultimo, por experiencia propia te digo que si tocan el primer tick para que no sea 100% lo único que van a conseguir es que la probabilidad sea del 20% por disparo y no por daño, a si que es mejor dejarlo como está, que es a la practica "lo mismo", al final se activa y tienes los dos disparos.

 DatJetto, a mi no me consume enfoque nunca el primer disparo, tenga enfoque o no lo tenga en ese momento, debe de ser otra cosa (buffo o algo parecido, lo que altera que el explosivo "gratuito" cueste enfoque)

**Comment by paellaencol** [comment]
Hombre, contra un healer a la práctica no es lo mismo, sino un bug bastante beneficioso, ya que la fecha sólo le daría tiempo a hacer un tick

**Comment by Jhovanni** [comment]
En cuanto al primer parte del bug reportado, no siempre he visto que flecha negra active Bloquear y Cargar al abrir con ella; eso es en mi experiencia.
Los disparos explosivos adicionales en sí no es que cuesten el enfoque total, sino que te cobran 10 puntos de enfoque, y si juntas eso con el bug visual del enfoque suele suceder que pareciese que te está cobrando los 40 totales.
Y con respecto a no colocar T.N.T., como solución para no activar Bloquear y Cargar al primer golpe de Flecha negra, la idea es inviable pues dicho talento está bug (como ya he reportado por ahí), y se activa aún cuando no gastes puntos en colocarlo.

**Comment by searum** [comment]
fix
