### ISSUE TITLE
[Brujo] Proposito Oscuro, Daño Conflagrar, Quemar alma + Fuego de alma

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#2885]
Se que alguno me va a decir que reporte por separado las tres cosas. Pero curiosamente el fallo de estas tres cosas (que antes funcionaban bien, salvo por el proposito oscuro con el matiz que se reporto https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2856) viene de hace un día. No se si es por el arreglo que se ha metido de piedra de salud o que, pero estoy convencido de que ha sido por alguna cosa así. Pero estas cosas me parecen bastante importantes para el brujo. No se si se podrá recuperar la configuración de antes de esto o si habrá que arreglarlo de cero. 

Paso a explicaros lo que pasa y os pongo enlaces.

-Proposito oscuro: http://wow.freakz.ro/spells.php?spell=80398

Problema: solo se pone en el objetivo amistoso al jugador que lo lanza no por lo que no le da la celeridad.

![wowscrnshot_112913_215350](https://f.cloud.github.com/assets/3939699/1647284/4db620be-5939-11e3-9114-38743046e35f.jpg)

-Conflagrar: http://es.wowhead.com/spell=17962/conflagrar

Problema: el daño esta bajisimo, pega solo 200 ptos. Esto ya se reporto y se soluciono os dejo el enlace con todo aquí https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1450

![wowscrnshot_112913_215256](https://f.cloud.github.com/assets/3939699/1647295/0a8212d4-593a-11e3-82ba-066afa92b85d.jpg)

-Quemar alma + Fuego de alma: http://es.wowhead.com/spell=74434

Problema: quemar alma esta haciendo que puedas lanzar todos los fuegos de alma de forma instantánea mientras está activo, cuando al lanzar solo uno instantaneo se debería desactivar esto.

![wowscrnshot_112913_215400](https://f.cloud.github.com/assets/3939699/1647297/1bd13eca-593a-11e3-9c97-45e459b6dc8b.jpg)

Un saludo y gracias.

**Comment by ghost** [comment]
Evilknight, puse un post en consultas porque veía fixes en el changelog que no estaban en el bugtracker como el bufo de entereza del sacer y Deka me respondió:

Por lo visto están deshaciendo casi todos los fixes, ya que se los pasaban otros desarrolladores y los metían aquí sin ningún control. En consecuencia, muchos no están bien fixeados, no están optimizados, o tienen datos de WOTLK, por esa razón están re-escribiendo se supone todos los fixes, de ahí que vuelvan a surgir bugs viejos y que salgan bugs nuevos.

Aun así, lo que no termino de entender es que cosas que antes funcionaban a la perfección, AHORA estén con datos de la wotlk como el toque vampírico.

Pero bueno, supongo que será darle tiempo como siempre e ir reportando todo de nuevo...

Lo de propósito oscuro ya lo reporté yo, cambié el post para el nuevo bug...puedes borrarlo de aquí si quieres :)

**Comment by ghost** [comment]
Quemar alma + fuego de alma fixeado.

**Comment by Drogoth2** [comment]
Haber si en poco tiempo esta el brujo reparado porque yo tengo ganas de poder jugarlo estando con todo bien. En fin poco a poco

**Comment by Dekadencee** [comment]
Una prueba de la reescritura @asman1, es la estabilidad, antes se caía varias veces al día, ahora es raro ver una caída, 1 cada 3 días actualmente y subiendo aún rendimiento y estabilidad del emulador...

**Comment by searum** [comment]
fix
