### ISSUE TITLE
[ NPC > Custodio Movra ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2887]
http://es.wowhead.com/npc=39878

Este npc debería vender cosas, sin embargo solo nos ofrece el poder poner nuestra Piedra de Hogar allí.

![wowscrnshot_113013_160933](https://f.cloud.github.com/assets/2728817/1648949/a404833c-59d1-11e3-990c-7b40112db9dd.jpg)

**Comment by redneo** [comment]
Alguien arregló el tema del caballito de mar?
