### ISSUE TITLE
[Misión Cumbres Tormentosas] Corazón Helado

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2888]
Enlace: http://es.wowhead.com/quest=12856/

Descripción: la verdad es que no hace falta que describa mucho, ya que la mecánica de la misión va perfectamente. Lo único es que tiene un problema, que no cuenta al liberar ni a las Prisioneras Brunnhildar http://es.wowhead.com/npc=29639/ ni al montar sobre el Protodraco liberado http://es.wowhead.com/npc=29709/#objective-of (antes de poder montarte sobre él, el protodraco recibe otro nombre "Protodraco cautivo" http://es.wowhead.com/npc=29708 )

Por lo demás la misión va perfecta, el problema es que simplemente no cuenta.

**Comment by redneo** [comment]
Esta mision tiene su chispa...

Tienes que montarte en el protodraco, liberar a las Prisioneras, creo que puedes llevar dos a la vez, no me hagas mucho caso, prueba con una que seguro va. Una vez las tengas, ve hacia donde te dieron la mision con el protodraco. Llegará un momento que el draco ser irá solo ya que como dice la mision has de rescatarlas.

Pruebalo y me dices.

**Comment by DatJetto** [comment]
Yo la hice no hace mucho y cogía a 3 Prisioneras perfectamente y las llevas al campamento y te cuenta.

**Comment by paellaencol** [comment]
uuuh, estaba saliendo en todas las direcciones menos en la que tocaba. Gracias a ambos
