### ISSUE TITLE
[ Interrupción de Casteos para las Clases ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#2889]
Actualmente cuando recibes un golpe cuerpo a cuerpo, si estás lanzando un hechizo este se corta, sin más, aunque no tengas restricción de rango. 
ESTO NUNCA DEBE PASAR, debido a que las clases Caster se quedan totalmente vulnerables frente a las unidades que alcancen el cuerpo a cuerpo.

No sé si habrá que retocar hechizo por hechizo o simplemente se hace para todos.

Igualmente quiero que colaboremos todos para poner los hechizos que se cortan actualmente y no deben hacerlo, ya que muchos usuarios están aprovechando estos bugs.

Para el Cazador: 
- Disparo Firme: http://es.wowhead.com/spell=56641
- Disparo de Cobra: http://es.wowhead.com/spell=77767
- Disparo de Puntería: http://es.wowhead.com/spell=19434
- Asustar Bestia: http://es.wowhead.com/spell=1513

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2348?source=cc
