### ISSUE TITLE
[Hunter > Termination]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#289]
-Remate

Tus facultades Disparo firme y Disparo de cobra otorgan 6 p. de enfoque extra al utilizarlas contra objetivos con un 25% de salud o menos.

http://www.wowhead.com/spell=83490

Bug: Al estar el objetivo al  25% de salud o menos, estos disparos no otorgan 15p de foco por Disp. Firme o Disp. Cobra, en su lugar Disparo Firme y Cobra otorgan +9 y +9 de enfoque, es decir 18p independientes, cuando debería ser una única reposición de +15.

**Comment by miglent** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/113

**Comment by Hellythium** [comment]
También lo reporte

**Comment by searum** [comment]
fix
