### ISSUE TITLE
[Crash] Feria de la luna negra: logro  Disparo presuroso

### ISSUE THREAD

**Issue by RaulioWoW** [RoDNet/Bugtracker-Infinium-4.3.4#2890]
hola, cada vez que completo el logro Disparo presuroso de la mision: dispara y marca! se tumba el server, yo lo he hecho 4 veces y eso sin mencionar las otras veces que alguien mas lo habra hecho porque en varias ocasiones ha caido el server. No estoy seguro si es la quest en si, o el logro : Calculo que es el logro, ya que la ultima vez pude hacer la quest sin problemas, pero antes ese logro no me lo daba. Saludos

Logro: http://es.wowhead.com/achievement=6022/

Mision: http://es.wowhead.com/quest=29438/

**Comment by redneo** [comment]
ya no salta el crash, pero tampoco el logro...
