### ISSUE TITLE
[Paladin Reprensión] Exorcismo

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#2891]
Exorcismo --> http://wow.freakz.ro/spells.php?spell=879
El arte de la guerra --> http://wow.freakz.ro/spells.php?spell=87138

El problema es que pego menos de lo que debería cuando se activa el talento el arte de la guerra. Estoy pegando alrededor de 9,3k con exorcismo casteandolo:
![image](https://f.cloud.github.com/assets/3939699/1650601/8888e7d6-5a9b-11e3-94d4-1074e996adf7.png)
Y cuando se me activa el talento, no aumenta su daño un 100% porque deberia pegar entorno a los 18,600k y es mentira, estoy pegando 17k como se puede ver:
![image](https://f.cloud.github.com/assets/3939699/1650602/b25e08de-5a9b-11e3-86b9-1bbf6a8bd6f6.png)
Por lo tanto el hechizo no esta pegando el 100% de daño extra que deberia y, por tanto si llevas puesto el glifo de exorcismo no llega a acer el 20% del daño en 6seg.

**Comment by F4NT4SM4** [comment]
el daño suele variar pega 1k menos o 1k mas eso es normal no siempre pega específicamente una cantidad exacta :s

**Comment by Drogoth2** [comment]
Puede variar un poco, pero si tiene que aumentar un 100% y pego 9k, lo minimo esque meta 18k

**Comment by F4NT4SM4** [comment]
esos 9k pudo haber sido un 8k o siempre metes 9k y no varia ese daño?

**Comment by Drogoth2** [comment]
Al muñeco siempre son 9k ahora mismo.

**Comment by F4NT4SM4** [comment]
si es como dices que mete 9k siempre intonce si que lo revisen a ver si esta bien o no :p

**Comment by sprin69** [comment]
se t ha olvidao poner x aki tmb k cuesta mana y al ser instantaneo no deberia costar mana

**Comment by meybon** [comment]
No se le olvido, esta reportado ya lo de que aveces cuesta mana. Issue #2471

**Comment by searum** [comment]
venga tronco y me la vas a liar por 1k de daño?
