### ISSUE TITLE
[Sacerdote Sombras] Pecado y castigo ID: 87100/87204 Diminishing returns

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2892]
ID del talento: http://wow.freakz.ro/spells.php?spell=87100&name=sin-and-punishment

Descripción: Cuando tu Toque Vampírico http://wow.freakz.ro/spells.php?spell=34914&name=vampiric-touch es disipado, el que lo haya disipado y todos los enemigos en un radio cercano de 6 metros tienen un 100% de probabilidad de aterrorizarse durante 3seg.

When your Mind Flay critically hits, the cooldown of your Shadowfiend is reduced by 10 sec.

Funcionan ambas cosas bien.

Problema: desde el parche 4.2 el efecto de "Horror" de "Pecado y castigo" ID del efecto (debuff): http://wow.freakz.ro/spells.php?spell=87204 no debería tener DR

Patch 4.2.0 (28-Jun-2011): This talent's backlash fear effect no longer has diminishing returns.
http://eu.battle.net/wow/en/game/patch-notes/4-2-0

Es decir, al disiparlo por primera vez, quien lo disipe sufrirá 3seg de Horror.
Al disiparlo por segunda vez, quien lo disipe sufrirá 3seg de Horror.
Al disiparlo por tercera vez, quien lo disipe sufrirá 3seg de Horror.
(y así sucesivamente)

**Comment by Monleon** [comment]
Ahora sí que sí. Arreglado
