### ISSUE TITLE
[Cocina] Festines de Cataclysm

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2893]
Enlace de los festines:
Festín de dragón a la parrilla http://es.wowhead.com/spell=88011
Festín de marisco magnífico http://es.wowhead.com/spell=88036 

Problema: hace unos meses tras sacar el festín ni siquiera se podía hacer click sobre el, ahora ya se puede, y de hecho al hacerlo, como es lógico, te aparecen dos buffs (uno de comer y otro de beber).
Sin embargo al pasar 10seg comiendo debería darte un buffo con valor a 60/90 de aguante y 60/90 de otra estadística útil para ti (esto es lo que falla, ya que no ocurre).

Esta estadística útil será:
Esquiva en el caso de Paladines, Guerreros y DKs en especialización de tanque
Agilidad en el caso de todas las clases que vayan con agilidad, incluido el druida Oso
Intelecto para casters y healers.
Fuerza en el caso de los dps que vayan equipados con Fuerza

**Comment by redneo** [comment]
solo tendria que dar esos tres bufos?

Por ejemplo, en tankes no daria fuerza, o en guerreros dps
O sacerdotes sanacion espiritu

**Comment by paellaencol** [comment]
Si, se me olvidó añadir que los dps que dependen de la fuerza, les da Fuerza.

En total son cuatro posibles buffos: esquivar, fuerza, agilidad e intelecto
