### ISSUE TITLE
[Sacerdote] Palabra de poder escudo ID:17

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2894]
Desde hace unas horas, está absorbiendo solo 8136, no está contando ni la maestría ni los talentos que lo mejoran.

Enlace: http://wow.freakz.ro/spells.php?spell=17

Debería tener la siguiente formula:

8136 (de absorción base) + (0.87 x Poder con hechizos)

A esto hay que multiplicarle diversos modificadores (actualmente no funciona ninguno de estos) si se llevan los talentos correctos puestos.
Estos serian

x1.06 via "Disciplinas gemelas" ID: 47588 
x1.2 via "Palabra de poder mejorada: escudo" ID: 14768
x1.2 via "Maestría: escudo de disciplina" ID: 77484 (esto como maestría base). Cada punto de maestría otorgaría un multiplicador de 1.025 extra

**Comment by Kiritoo** [comment]
Disculpad la molestía lo desabilitamos el script porque crasheaba, cuando compilemos estara funcionando de nuevo.
Saludos.
