### ISSUE TITLE
[Sacerdote] Mastery: Shield Discipline

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2895]
Enlace: http://wow.freakz.ro/spells.php?spell=77484

Descripción: Increases the potency of all your damage absorption spells by 20%. Each point of Mastery increases the potency of absorbs by an additional 2.5%.

Problema: no está funcionando ni la maestría base desde hace unas horas

**Comment by Kiritoo** [comment]
Esto debería funcionar al igual que el escudo.
