### ISSUE TITLE
[Sacerdote] Talento Disciplinas Gemelas ID:47588

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2896]
Enlace: http://wow.freakz.ro/spells.php?spell=47588

Con los 3 puntos de 3 puestos en este talento. Deberíamos tener un 6% de sanación aumentada, y un 6% de daño aumentado.

Problema: no está dando ese 6% a Palabra de poder: Escudo (id:17), cuando debería darlo, ya que es un coeficiente más a multiplicar de esta spell. Ha fallado desde hace unas horas

**Comment by Kiritoo** [comment]
Esto debería funcionar al igual que el escudo.
