### ISSUE TITLE
[Sacerdote disciplina] Palabra de poder mejorada: escudo

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2897]
Enlace: http://wow.freakz.ro/spells.php?spell=14768

Descripción: Improved Power Word: Shield      Rank 2
Increases the damage absorbed by your Power Word: Shield by 20%.

Problema: al igual que el resto de talentos, fórmulas y multiplicadores de "palabra de poder:escudo" han dejado de funcionar recientemente, en este caso no mejora ese 20% al escudo.

**Comment by Kiritoo** [comment]
Esto debería funcionar al igual que el escudo.
