### ISSUE TITLE
Talento [Fuerza del Alma] Sacerdote disciplina

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2898]
Enlace: http://wow.freakz.ro/spells.php?spell=89489

Descripción:
Cuando sanas a un objetivo con tus hechizos Sanar, Sanación superior o Sanación relámpago, la duración del perjuicio Alma debilitada sobre el objetivo se reduce 4s.

Además, cuando lanzas Enfoque interno te vuelves inmune a los efectos de Silencio, Interrumpir y Disipar durante 5s. (Esto funciona perfectamente)

Problema:
1. Sólo debería reducirse la duración del perjuicio Alma debilitada (por valor a 4seg) sanas a un objetivo con tus hechizos Sanar, Sanación superior o Sanación relámpago (esto funciona bien). Sin embargo también lo está haciendo al sanarlo con "Penitencia" (47540), Rezo de sanación (596) y Nova Sagrada (15237)
2. También debería reducirse 4s. el debuff de "Alma debilitada" cuando otro sacerdote con este talento cura a un objetivo que tenga este debuff (aunque no se lo haya aplicado el mismo) con los siguientes hechizos Sanar, Sanación superior o Sanación relámpago. (Esto creo que es de la 4.1, antes funcionaba bien)

Nota: Hasta ayer esto funcionaba bien

**Comment by Kiritoo** [comment]
Idem que los demás talentos del escudo.
