### ISSUE TITLE
[Hunter > Rapid Recovery]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#290]
-Recuperación Rápida

Ganas 12p de foco cada 3sec cuando activas fuego rápido y 50p de foco al obtener Matanza rápida

Recup Rápida. http://es.wowhead.com/spell=53232

Bug: Cuando obtienes matanza rápida no recuperas los 50p. de foco.
Matanza rápida: http://old.wowhead.com/spell=34949

Trap launcher se beneficia de Rapid Recovery, al usar el lanzador te restaura 50p de foco, no debiendo ser así.

**Comment by miglent** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/113

**Comment by Hellythium** [comment]
Creo que eso ya lo reporte

**Comment by searum** [comment]
ya lo tengo fix
