### ISSUE TITLE
[Hunter > Deterrence ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#291]
Disuasión

http://es.wowhead.com/spell=19263

Cuando se activa, tienes un 100% de que los ataques cuerpo a cuerpo, a distancia fallen y los hechizos se desvíen. Además, reduce un 30% todo el daño recibido. Mientras Disuasión está activo, no puedes atacar. Dura 5 s.

Bug: Los golpes cuerpo a cuerpo no fallan, te impactan

Nota: Revisar la reducción de daño 30%.
El 30% de daño reducido se aplica A TODOS LOS DAÑOS ( incluído daño por caída )

Mientras estás en Deterrence puedes lanzar facultades ofensivas, esto no debería suceder, debería aplicarse un aura de Pacify en esos 5 segundos.

Cuando deterrence está activo NO SE TE PUEDE APLICAR NINGÚN DAÑO ya sea Spell , Físico a melee o Físico a distancia. TAMPOCO PUEDEN AÑADIRTE DEBUFFS como picadura de serpiente, palabra de las sombras dolor, Bomba viva. SOLO PUEDE HACERTE DAÑO LO QUE TENGAS PUESTO COMO DEBUFF.
Tampoco pueden stunearte, ni hacer péridida de control del personaje, ya que sería esquivado o desviado.

**Comment by miglent** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/113

**Comment by ghost** [comment]
Tampoco está desviando los hechizos. Actualmente, es como si no se usara la habilidad, es una mera animación, aunque habría que comprobar lo del 30%

Edito: Ahora sí que desvía, e incluso he visto el mensaje "Reflejado" algunas veces.

**Comment by ghost** [comment]
Pues a mi me sale "desviado" cada vez que intento dañarle a los cazas @asman1

**Comment by lamaza** [comment]
Yo he visto que este hechizo ya anda bien. Cuando un cazador lo usa, todo (casi) lo que yo uso (fisico o magico) sale que  lo evade. El único beneficio es que nos pueden atacar usando esto.

**Comment by searum** [comment]
fix

**Comment by lamaza** [comment]
Gracias Sea!

**Comment by Jhovanni** [comment]
Bueno, aclarando un poco hay que decir que el hecho que te pongas Disuación no significa que no te llegará nigún nuevo daño. Es un poco tonto porque la habilidad dice que tienes 100% de esquivar y "todos" los golpes, pero aún así en el modo oficial si entran golpes de clases cuerpo a cuerpo.
Es un tema confuso que se ha tratado bastante en el oficial, llamando a Disuación una coladera y realmente lo es, pero en el oficial así funciona (hay una explicación por ahí de los desarrolladores que dice que aparte de porcentaje de esquivar y otros, hay unos índices más en el cálculo de fórmula para decidir si un golpe es recibido, y así quedó el asunto).
El enlace de wowhead ha sido actualizado y ahora la habilidad dice que no recibirás ni un sólo daño adicional, cuando en cataclismo hablaba de índices de esquivar y otros. Por lo tanto el fix vino en Pandarian, mientras que en cataclismo ciertos golpes aún pueden pasar, son pocos, pero los hay. Aclarando, dichos golpes no pueden ser hechizos de mago, sacer, brujo y cosas así, pues eso sólo dependen en la fórmula para calcular la desición del golpe del índice de esquivar.
Bueno, quedó bastante confuso el asunto, y exactamente igual quedó la explicación que dió Blizzard sobre el asunto en "Café con los desarrolladores".

**Comment by ghost** [comment]
Negativo. Hay hechizos que sí pueden entrar del brujo como Descarga de Caos, la razón es que dicha spell atraviesa todas las absorciones excepto los inmunes como cubo de hielo y escudo divino (lo pone en su descripción). Deterrence no es una inmunidad, tan sólo dice que 'paras' todos los ataques. De hecho, no es un tema tan confuso, la razón de que entren algunos golpes es que hay ciertos ataques que no se pueden esquivar ni parar ni bloquear: Los que vienen de sigilo. Un rogue siempre podrá darte con sus openers (garrote, golpe bajo, emboscada) aunque tengas disuasión puesta. Además, si te meten golpe bajo tendrás un stun de 2s durante los cuales no podrás parar, esquivar ni bloquear (ya que al estar aturdido no puedes) y te podrá entrar todo el daño físico cuerpo a cuerpo. Son todo mecánicas.
