### ISSUE TITLE
[Hechizos/Talentos][DK] Muerte y Descomposición

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2910]
Buenas.
• Nombre: Muerte y Descomposición
• Enlace: http://es.wowhead.com/spell=43265
• Descripción: Corrompe el suelo que selecciona el caballero de la Muerte, lo que inflige X de daño de las Sombras cada segundo a los objetivos que permanecen en el área durante 10 s. Esta facultad produce una gran cantidad de amenaza.
• Problema: No está haciendo daño sobre el area seleccionada, sino que hace daño en un radio de 5m alrededor del DK, como si fuese una especie de aura o algo así.
• Observaciones: En resumen, se puede utilizar en cualquier lugar pero solamente va a afectar a los objetivos alrededor del DK. No sé si solamente me pasa a mi o es en general, cualquier cosa avisen y cierro el tema.
Gracias y hasta luego!

**Comment by searum** [comment]
fix
