### ISSUE TITLE
[PNJ][Cavernas de Brazanegra] PNJs Alianza de Mazmorra Cavernas de Brazanegra

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2911]
Buenas.
Faltan los siguientes PNJ que dan misiones en la mazmorra Cavernas de Brazanegra (http://es.wowhead.com/zone=719):
- Centinela practicante Issara (http://es.wowhead.com/npc=33261)
- Centinela Aluwyn (http://es.wowhead.com/npc=33260)
- Relwyn Sombrestrella (http://es.wowhead.com/npc=33258)
- Ashelan Bosquenorte (http://es.wowhead.com/npc=33256)

Gracias y hasta luego!

**Comment by Kiritoo** [comment]
Arreglado falta reiniciar.
