### ISSUE TITLE
Personaje Bug o atascado

### ISSUE THREAD

**Issue by skaidio** [RoDNet/Bugtracker-Infinium-4.3.4#2913]
Hola quería informar sobre un personaje de la cuenta Alysa que se encuentra atascado o bugeado entremedio de los 2 oceanos cuando tomo un barco y el barco la dejo tirada en medio del oceano muerta y sin poder revivirla ni desbloquearla. Intente muchos métodos pero ninguno funciono, si algún GM puede destrabarla se lo agradeceria. Saludos

**Comment by redneo** [comment]
movido a dalaran
