### ISSUE TITLE
[Brujo] Cauce de salud

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#2914]
http://wow.freakz.ro/spells.php?spell=755

Te quita un 1% de vida y restaura un 6% de salud a la pet. 

Esta sacando más de un 1% de salud máxima.

**Comment by ghost** [comment]
Además hace críticos en la sanación de la pet, y no debería al ser un % de la vida de esta.

**Comment by searum** [comment]
fix
