### ISSUE TITLE
[Estancias] Nivel de Objeto

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#292]
Las estancian requieren que tengas un nivel de objeto para poder entrar en ellas 
con esto los jugadores que recien esten 85 no entren de una a Tierras de fuego o alma del dragon los obligaria a sacar minimo set de profeccion y hacer mazmorra para poder sacar nivel de objeto  y entrar en las estancias fuertes

Coloco los niveles de objeto que piden las estancias:

Tierras de fuego Requiere nivel de objeto 355
Alma de Dragón Requiere nivel de objeto 365
Bastión de Baradin Requiere nivel de objeto 329
Descenso de Alanegra Requiere nivel de objeto 342
El Bastión del Crepúsculo Requiere nivel de objeto 342
Trono de los Cuatro Vientos Requiere nivel de objeto 342

Nivel de objeto de las mazmorra:

Cámaras de los Orígenes Requiere nivel de objeto 305
Cavernas Roca Negra Requiere nivel de objeto 226
Ciudad Perdida de los Tol'vir Requiere nivel de objeto 272
El Núcleo Pétreo Requiere nivel de objeto 272
Fin de los Días Requiere nivel de objeto 353
Grim Batol Requiere nivel de objeto 272
Hora del Crepúsculo Requiere nivel de objeto 353
La Cumbre del Vórtice Requiere nivel de objeto 272
Pozo de la Eternidad Requiere nivel de objeto 353
Trono de las Mareas Requiere nivel de objeto 226
Zul'Aman Requiere nivel de objeto 346
Zul'Gurub Requiere nivel de objeto 346

Fuente: http://eu.battle.net/wow/es/zone/#expansion=3&type=raids

**Comment by crowel** [comment]
Genial me parece la idea de poner bien los requerimientos de banda y mazmorra, de esta manera formentando el pve al maximo ya que mucha gente seguramente preferiria pasar sin hacer mazmorras y ir directamente a raid.
Un saludo :)

**Comment by paellaencol** [comment]
Correcto, además para las mazmorras heroicas del primer parche se necesita un nivel mínimo de 329 para poder entrar:
http://www.guiaswow.com/cataclysm/

**Comment by redneo** [comment]
Molaria, pero por ahora el emulador no contempla lo de los niveles de los objetos por ningun lado, al menos en la base de datos.

**Comment by Savian123** [comment]
Otra cosa... eso del ilvl que te pide para entrar tampoco ... en las raid.. almenos en el oficial nunca he tenido problema para entrar aun teniendo equipo algo low en mazmorras si que era un problema con la herrmienta de buscador pero las raid nunca me han dado problema por el simple hecho que entras sin esas herramientas... excepto en alma de dragon que se decidio incorporar la opcion por la baja utilizacion que habia tenido en las otras expansiones

**Comment by Compresor** [comment]
Para poder entrar a las bandas /mazmorras no requiere ilevel, lo que si es recomendable tenerlo para poder superar la mazmorra o banda. Estaría bien que hicieses una guía para que la gente supiese que nivel de equipo tiene que tener para poder completar las mazmorras y bandas
