### ISSUE TITLE
[Pe

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2921]
Las pets

**Comment by Wiinter** [comment]
Nose si a los demás también les pasa, pero cuando monto en un montura terrestre y después desmonto, mi pet continua siendo igual que al principio, con los mismos buffos y con el enlace de alma etc..

Lo que si es verdad es lo de los buffos, que por ejemplo te matan a la pet sin haber acabado el tiempo de Heroismo/Rabiar/... y cuando la vuelves a invocar aun los tienes.

**Comment by ghost** [comment]
Si @Wiinter, cuando montas y desmontas la pet continua igual que estaba. La cosa es que al montar, tu pet desaparece y por tanto, al no tener pet, tampoco tienes enlace de alma hasta que vuelves a desmontar. Si pasas al lado de un enemigo y te ataca estará infligiendo un 20% mas de daño respecto a si estuvieras desmontado, lo que te obliga aveces a bajarte y en otras ocasiones les da unos segundos de ventaja y de daño extra a los enemigos.

Sencillamente no está blizzlike, la pet debería seguirte en todo momento a menos que vayas en montura voladora.

**Comment by Wiinter** [comment]
Toda la razón.
