### ISSUE TITLE
[Chamán mejora] Poder congelado 63374

### ISSUE THREAD

**Issue by Ivanlopez-dev** [RoDNet/Bugtracker-Infinium-4.3.4#2924]
http://wow.freakz.ro/spells.php?spell=63374
El talento de la rama mejora indicado en el link superior, no funciona.
ID del debuff: "Congelar" http://wow.freakz.ro/spells.php?spell=63685 El debuff debe activarse al utilizar "Choque de escarcha" http://wow.freakz.ro/spells.php?spell=8056 sobre un objetivo que esté a más de 15 metros del chamán.

**Comment by paellaencol** [comment]
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/600/j6tt.jpg/'><img src='http://img600.imageshack.us/img600/1958/j6tt.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img600.imageshack.us/img600/1958/j6tt.jpg

**Comment by paellaencol** [comment]
ID del debuff: "Congelar" http://wow.freakz.ro/spells.php?spell=63685 EL debuff debe activarse al utilizar "Choque de escarcha" http://wow.freakz.ro/spells.php?spell=8056 sobre un objetivo que esté a más de 15 metros del chamán

**Comment by searum** [comment]
fix
