### ISSUE TITLE
[Chaman mejora] Presura mental ID:30814

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2925]
Enlace: http://wow.freakz.ro/spells.php?spell=30814

Descripción: Ahora tu poder con hechizos es igual a tu 55% de tu poder de ataque, y ya no te beneficias de otras fuentes de poder con hechizos.
Also, your instant beneficial, damaging, and totem spells cost 75% less mana. (esto no hay problema)

Problema: si bien es cierto que en la hoja de personaje sale convertido el 55% de tu Poder de ataque en Poder con Hechizos (y que además el poder con hechizos del chamán no se beneficia de ninguna otra fuente), esto es solo visual. En la práctica las sanaciones y los ataques mágicos siguen haciendo el mismo daño con o sin equipo (es decir no da en la práctica ese 55%)

No quedó bien arreglado aquí: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1906

**Comment by Dekadencee** [comment]
Ahora si, testeado por el equipo de testeo de RoD, fixed

**Comment by F4NT4SM4** [comment]
nose pero mi chaman sigue curando igual con o sin equipo ._.

**Comment by Kiritoo** [comment]
Pues de momento no se compilo te toca esperar.
Saludos.
