### ISSUE TITLE
[Chamán] Glifo de tótem Corriente de sanación ID 55456

### ISSUE THREAD

**Issue by Ivanlopez-dev** [RoDNet/Bugtracker-Infinium-4.3.4#2926]
Link spell: http://wow.freakz.ro/spells.php?spell=5394&name=healing-stream-totem

Link glyph: http://wow.freakz.ro/spells.php?spell=55456&show_non_player=on

Descripción: 
El glifo del siguiente tótem no funciona correctamente, en teoría da 195p. de resistencia a las X magias. Visto a continuación en la screen, no te da la resistencia.

https://imageshack.com/i/2hvpn3p
http://imageshack.com/i/n6d7rop
*En la primera imagen he lanzado el totem de resistencia, para que se vean los 195p. que debería dar el tótem del que hablamos,(El de Corriente de sanación, obviamente glifeado)
Y en la segunda, sale puesto el tótem Corriente de sanación, glifeado marcando el error de que no salen los 195p. de resistencia.

**Comment by Monleon** [comment]
Cuando se compile ya debería funcionar
