### ISSUE TITLE
[Mision]Batalla por la ciudad de Gilneas

### ISSUE THREAD

**Issue by titoalfon** [RoDNet/Bugtracker-Infinium-4.3.4#2927]
http://es.wowhead.com/quest=24904/
Hablo con Krennan Aranas y la batalla no se inicia. No hace nada.

**Comment by frostakuma** [comment]
tengo el mismo problema la batalla no se puede iniciar

**Comment by Monleon** [comment]
Las misiones de los huargens ya funcionan perfectamente de inicio a fin
