### ISSUE TITLE
sacar mascota en combate (warlock)

### ISSUE THREAD

**Issue by sprin69** [RoDNet/Bugtracker-Infinium-4.3.4#2929]
weno pues no deja sacar la pet en combate aparte d k no funciona un talento k cuando t matan la pet la sacas instant eso esta posteado x hay lo vi los otros dias. Creo k es un fallo bastante grave ya ke pierdes soul link k t reduce el daño un 20% . Esto se soluciono pero vuelve a fallar

**Comment by sprin69** [comment]
en arenas no deja sacar pet aunke salgas d combate. Antes si dejaba asi k algo vuelve a fallar

**Comment by Monleon** [comment]
Sí que deja invocar pets en arenas
