### ISSUE TITLE
 [Paladin] Glifo de Divinidad

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#293]
Con el glifo deberia de restaurarme 10% de mi mana maximo con imposicion de manos lo cual no hace
ID: http://es.wowhead.com/spell=54939

**Comment by rageshow** [comment]
lo acabo de comprobar y es cierto, no lo hace.

**Comment by searum** [comment]
fixeado.. creo
