### ISSUE TITLE
[NPC] Gamon

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#2930]
NPC: http://es.wowhead.com/npc=6466

Bug: Está pegando poco más de 300 de daño cuando debería pegar aproximadamente 60k como se ve en este video en el minuto 2:13 más o menos: http://www.youtube.com/watch?v=1xibYEoZSLU

También está esta captura de un golpe crítico que llega casi a los 150k:
http://media.mmo-champion.com/images/news/2010/november/gamon.jpg

Sé que no es algo importante o necesario, pero es divertido que un Npc que fue tan maltratado en el pasado haya pasado a ser un élite tan poderoso en Cataclysm y podría llevar a la gente a armar grupos grandes en Orgrimmar para matarlo solo por diversión y no debe costar mucho arreglar su daño. Gracias de antemano.

**Comment by Kiritoo** [comment]
Arreglado cuando se reinicie.
