### ISSUE TITLE
problema en mision huargen

### ISSUE THREAD

**Issue by frostakuma** [RoDNet/Bugtracker-Infinium-4.3.4#2931]
http://es.wowhead.com/quest=24472/#screenshots

no se puede agarrar el estandarte de koroth cuando voy a despojarlo no hay nada adentro.
sin el estandarte no se puede completar la mision y no se puede continuar 
agradeceria que lo arreglaran gracias

**Comment by Monleon** [comment]
Las misiones de los huargens ya funcionan perfectamente de inicio a fin
