### ISSUE TITLE
[Sacerdote Disciplina]  [Palabra de poder: escudo]

### ISSUE THREAD

**Issue by orcca** [RoDNet/Bugtracker-Infinium-4.3.4#2934]
El escudo absorbe solo 8136k, tengas lo que tengas, equipo o sin el, sin talentos con talentos en sombra o en disciplina absorbe lo mismo cuando un sacer ya equipado andará sobre los 25k de absorción.

**Comment by Wiinter** [comment]
Querras decir 8,136k, porque sino quieres decir qe absorve 8 millones xD
