### ISSUE TITLE
[NPC](Dalaran)(Relacionado con Logro/Mascota) Archimago Vargoth

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#2935]
NPC: http://es.wowhead.com/npc=19481 (ese es el que sale en Tormenta Abisal, no logré encontrar el id del que sale en Dalaran)

Descripción: Al completar el logro Conocimiento superior (http://es.wowhead.com/achievement=1956) te mandan el libro Las Escuelas de la Magia Arcana: Maestría (http://es.wowhead.com/item=43824), que al usarlo te teletransporta hasta el Reposo del Archimago Vargoth, donde se encuentra dicho Npc.

Al hablar con él teniendo el libro antes mencionado te sale la opción de ofrecérselo (aunque no se lo darás realmente, el objeto sigue contigo) y al hacerlo sale la opción de que él te dé la mascota Familiar del Kirin Tor (http://es.wowhead.com/item=44738) que es la recompensa real del logro.

Bug: El problema está en el 2º diálogo, cuando le pides la mascota no pasa nada. Debería darte el objeto para que aprendas a invocarla. Espero que lo arreglen, gracias de antemano.

**Comment by redneo** [comment]
Se arreglo estos dias atras.

**Comment by Velcositro** [comment]
He intentado varias veces y sigue sin funcionar, ¿es que aún no lo han implementado?

**Comment by VictoriaTier** [comment]
Pues sigue igual la cosa.. como puedes ver.

**Comment by Velcositro** [comment]
Acabo de probarlo y ya me funcionó. Cierro el tema.
