### ISSUE TITLE
[PNJ][El Castillo de la Tempestad] Kael´thas Caminante del Sol

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2938]
Buenas.
• Nombre: Kael´thas Caminante del Sol
• Enlace: http://es.wowhead.com/npc=19622
• Descripción: Este PNJ se puede encontrar en El Castillo de la Tempestad
• Problema: Su habilidad bola de fuego (http://es.wowhead.com/spell=36805) hace un daño excesivo (superior a los 100k)
• Observaciones: Ya habia sido reportado y corregido en este post https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/678
Gracias y hasta luego.

**Comment by searum** [comment]
fix
