### ISSUE TITLE
[Hunter] Fingir Muerte

### ISSUE THREAD

**Issue by shials** [RoDNet/Bugtracker-Infinium-4.3.4#294]
http://es.wowhead.com/spell=5384
Te consume todo el enfoque.

**Comment by miglent** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/113

**Comment by miglent** [comment]
Por favor, si ven que ya hay un post de caza no creen 100 distintos, coloquen todo en el mismo...

**Comment by crowel** [comment]
Miglent una cosa ya que no leiste seguro a deka, los post ponerlos individualmente ya pues es un lio para la reparación de los mismos tener 15 reportes en un mismo post.
Te lo digo porque no paras de enlazar el mismo post en todos los de grom, que él los está poniendo como diijo dekadence, para tenerlos más ordenados.

Un saludo.

**Comment by crowel** [comment]
Continua el error tras la actualizacion un saludo.

**Comment by searum** [comment]
ya esta mejor reportado en otro issue
