### ISSUE TITLE
[mision y zona] De vuelta al foso, buff Chollo de lok´lira

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#295]
ID 13424 http://es.wowhead.com/quest=13424

La misión dice que montado en una osa, mate 6 osos ubicados en medio de la aldea en El Foso del Colmillo.

---Bug: El objeto invoca correctamente a la osa, y de hecho puede usar sus habilidades en cualquier mob enemigo, EXCEPTO en los necesarios (http://es.wowhead.com/npc=30174) para completar la misión. No se les puede atacar de ninguna manera, estan bug esos bichos.

---Otro bug que noté, es que al salir del poblado, quienes eran amistosos, se vuelven mis enemigos ya que el buff Chollo de Lok´lira (http://es.wowhead.com/spell=72914 )de disfraz se quita automáticamente, pudiendo fácilmente matar a los  npc importantes en la cadena de quest de esta área:

![wowscrnshot_070813_115713](https://f.cloud.github.com/assets/4790547/762835/956dddb6-e7f1-11e2-967c-0122e340c43f.jpg)
![wowscrnshot_070713_163918](https://f.cloud.github.com/assets/4790547/762836/9581e27a-e7f1-11e2-9ca8-74b5b8ecb445.jpg)
![wowscrnshot_070713_163920](https://f.cloud.github.com/assets/4790547/762837/9596d856-e7f1-11e2-943b-fe94cab9a88b.jpg)
![wowscrnshot_070813_115415](https://f.cloud.github.com/assets/4790547/762838/95a46002-e7f1-11e2-9c06-9029ee850f49.jpg)
![wowscrnshot_070813_115600](https://f.cloud.github.com/assets/4790547/762839/95aa1d6c-e7f1-11e2-81af-08b1fe504125.jpg)

**Comment by Kiritoo** [comment]
Fix
