### ISSUE TITLE
[Misión Orgrimmar] Armas de disfunción masiva

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2951]
Enlace: http://es.wowhead.com/quest=26294#english-comments

Descripción: deberíamos poder "pasar revista" a los siguientes 3 Demoledor Grito Infernal http://es.wowhead.com/npc=42673 y tras percatarnos del que tiene defecto, tenemos que reprender al Ingeniero jefe contiguo al demoledor http://es.wowhead.com/npc=42671/chief-engineer

Problema: no se puede "pasar revista" ni reprender posteriormente al Ingeniero.

Adjunto vídeo http://www.youtube.com/watch?v=4w2lR07Fk74

**Comment by redneo** [comment]
Arreglado
