### ISSUE TITLE
[Chamán] Desatar Elementos más Arma de vida Terrestre

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2954]
Desatar Elementos: http://wow.freakz.ro/spells.php?spell=73680&name=unleash-elements
Arma de Vida Terrrestre: http://wow.freakz.ro/spells.php?spell=51730&name=earthliving-weapon

Ambas funcionan bien, el problema ocurre que Desatar elementos está funcionando con la misma mecánica como si se llevara el resto de encantamientos (que inflingen daño).

Al desatar Elementos con Arma de Vida Terrestre encantada en el arma el funcionamiento es distinto, ya que mete una pequeña curación a un aliado (o tu mismo). Sin embargo está ocurriendo la misma mecánica que con el resto de encantamientos de arma, la sanación se la está metiendo a los rivales (a quien tienes en target sea aliado o rival) (con lo que esto conlleva de meter Sanaciones en el Tiempo al rival, y buffos de salud)

En resumen, Desatar Elementos hay que meterselo a un aliado (o nosotros mismo) no a un rival (ya que se trata de una cura, no de daño)
Además no es posible utilizar Desatar Elementos sobre nosotros mismo.

P.D. El buffo que deja al chamán durante 6seg que potencia la cura un 30% (es un 30%, aunque en el enlace esté mal y ponga un 20%) funciona correctamente

**Comment by Dekadencee** [comment]
Fixeado, le he aplicado una comprobación al target, si el target es amigo se le aplicará la sanación, si es enemigo se te aplicará atí mismo.

Espero haber entendido bien, un saludo y gracias por reportar.

**Comment by paellaencol** [comment]
En efecto era eso.

Gracias
