### ISSUE TITLE
[Chamán Restauración] Aguas purificadoras ID:86962

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2956]
Enlace: http://wow.freakz.ro/spells.php?spell=86962

Descripción y problemas: Reduce un 40% el coste de Limpiar Espíritu (funciona)
 y cuando tu limpiar espíritu elimina con éxito un efecto dañino también sanas X p. al objetivo (esta sanación actualmente es un tercio de lo que debería ser).
 El efecto de sanación solo puede tener lugar una vez cada 6seg. (no tiene CD interno)

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/59/0mrh.jpg/'><img src='http://img59.imageshack.us/img59/2907/0mrh.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img59.imageshack.us/img59/2907/0mrh.jpg

Fórmula de la sanación tras gastar limpiar espíritu http://wow.freakz.ro/spells.php?spell=51886&name=cleanse-spirit : 
2802 (+28.2% SP).

**Comment by searum** [comment]
fix
