### ISSUE TITLE
[Chamán Restauración] Despertar Ancestral ID:51558

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2957]
Enlace: http://wow.freakz.ro/spells.php?spell=51558

Descripción: Cuando realizas sanación crítica con una sanación directa sobre un solo objetivo, invocas a un espíritu ancestral para que te ayude. Esto sana instantáneamente un 30% de la cantidad sanada realizada al objetivo amistoso de tu grupo o banda que, en un radio de 40m, tenga el porcentaje de salud más bajo.

Problema: No funciona, al realizar una sanación crítica, no salta otra curación inteligente a otro miembro amistoso (con el menor % de salud) con valor al 30% de la sanación crítica original

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/19/06jr.jpg/'><img src='http://img19.imageshack.us/img19/558/06jr.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img19.imageshack.us/img19/558/06jr.jpg

En la imagen se observa, como tras la sanación crítica no sucede nada más (falta esa segunda sanación con valor al 30% de la sanación crítica)

**Comment by searum** [comment]
fix
