### ISSUE TITLE
instructores gilneanos de picaros bug

### ISSUE THREAD

**Issue by frostakuma** [RoDNet/Bugtracker-Infinium-4.3.4#2958]
los instructores de picaros que hay saliendo de la ciudad de gilneas estan bug
fui por varios poblados de la zona y todos estan bug esta la opcion de hablarle pero no te enseña nada
esta http://es.wowhead.com/npc=38796/ es una.
De las demas no recuerdo los nombres

**Comment by Kiritoo** [comment]
Acabo de probar y enseña correctamente.
