### ISSUE TITLE
[Hunter ]- Talento " !Ataca! "

### ISSUE THREAD

**Issue by shials** [RoDNet/Bugtracker-Infinium-4.3.4#296]
Este talento del hunter MM debería saltar cuando se lanza criticos de  Disparo Arcano, Disparo de Puntería y Disparo Explosivo.
No encuentro enlace a Wowhead ni en old.wowhead, agradecería que si alguien lo encontrara , lo pusiera a continuación  :).
http://es.wowhead.com/spell=3044 Disparo Arcano
http://es.wowhead.com/spell=19434 Disparo de Puntería
http://es.wowhead.com/spell=53301 Disparo Explosivo

**Comment by miglent** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/113

**Comment by DatJetto** [comment]
Sic 'Em! http://old.wowhead.com/spell=83356 Rank 2
http://old.wowhead.com/spell=83340 Rank 1

¿Aura de Sic 'Em! ? http://old.wowhead.com/spell=89388

**Comment by shials** [comment]
Gracias Grom , esa es :)

**Comment by searum** [comment]
fix
