### ISSUE TITLE
[Rogue/hunter] Se bugea sigilo dentro de bengala.

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#2960]
Al no saber del todo si es culpa del efecto de la bengala o del sigilo, en el nombre del reporte nombro a ambas clases.

Primero dejo un vídeo porque aclarará mejor que mil explicaciones lo que sucede (dura 57 segundos): https://www.youtube.com/watch?v=R4gQpw1Kam4 es mi rogue en Reign of Darkness.

 Ahora explico igualmente, el problema es el siguiente: al usar sigilo (http://cata.openwow.com/spell=1784) o esfumarse (http://cata.openwow.com/spell=1856) dentro del area de bengala (http://cata.openwow.com/spell=1543) deja bugeada la habilidad de sigilo, con lo que para poder volver a usar sigilo tienes que tirar de esfumarse (CD vanish = 2 min, CD stealth = 2 segs.).

**Comment by efectokoleos** [comment]
arreglado
