### ISSUE TITLE
[Chamán Restauración] Tótem Enlace de espíritu ID:98008

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2961]
Enlace: http://wow.freakz.ro/spells.php?spell=98008

Descripción: Invoca un Tótem Enlace de espíritu con 5p. de salud a los pies del taumaturgo. El tótem reduce un 10% el daño que reciben todos los miembros del grupo o banda en un radio de 10m. Cada 1s. la salud de todos los jugadores afectados (todos los aliados que estén en el radio de 10m del tótem) se redistribuye de forma que cada jugador acaba con el mismo porcentaje de su salud máxima. Dura 8,40s.

Problema: únicamente funciona la parte de reducir daño un 10%. Debería redistribuir la salud de todos los aliados que se encuentren dentro de la zona del tótem (radio de 10m.). Aunque en la actualidad se produce la animación, y los aliados dentro de la zona tienen esa reducción de daño, su salud no se ve redistribuída

Vídeo: http://www.youtube.com/watch?v=D8MzLx_H8Zc
véase del seg. 0:09 al 0:11
De los dos jugadores del equipo uno tenía la salud al 100% y el otro al 10%, tras el primer tick del tótem, la salud de ambos pasa a ser del 55% [(100+10)/2]

**Comment by paellaencol** [comment]
Añado:
1. Cada tick del totem (cada seg.) redistribuye por completo la salud de los aliados, o cualquier tipo de variación que se hubiera producido durante el intervalo de cada tick (1seg) hasta que expire el totem
1. La redistribución de salud es instantánea e inmediata (no periodica)

**Comment by Necrofilo** [comment]
Aparte, es una de las mejores formas de aprovechar que iguala la baja salud de todos los del área de efecto para matar a quien antes tenía la salud al máximo haha

**Comment by searum** [comment]
fix
