### ISSUE TITLE
[Mago fuego] se bugea impacto

### ISSUE THREAD

**Issue by mariojs** [RoDNet/Bugtracker-Infinium-4.3.4#2962]
El talento impacto del mago fuego (http://cata.openwow.com/spell=12357), tiene algún tipo de error, es decir, estunea pero no expande los efectos de daño en el tiempo a los enemigos cercanos.

Al igual, el escudo de mana (http://cata.openwow.com/spell=1463) creo que no absorbe el daño que debiera, es decir, en la descripción de la skill pone un valor y al usarla en lo que es el propio bufo pone un valor diferente (mas bajo) que el de la descripción de la skill.

**Comment by Kiritoo** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Hola echale un ojo a esto porfavor, antes de nada comprueba que no este reportado como en este caso ya lo puso otro usuario, solo 1 reporte por Issue aquí estas poniendo 2 y intenta poder el título un poco mas resumido como los ejemplo del enlace que te pase.
Saludos.
