### ISSUE TITLE
talento Exterminar Rogue

### ISSUE THREAD

**Issue by Lustwig** [RoDNet/Bugtracker-Infinium-4.3.4#2963]
Otros rogues tienen este talento bien , hable con un gm y me dijo que viniera aqui.
Eso , el talento Exterminar de la rama asesinato (rogue) no me va , ojala podais ayudarme 
gracias de antemano , saludos.

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

De todos modos, no se porque te mandan aquí...si les funciona a los demás debería ir en asistencia técnica en el foro..ya que no es un bug general.

**Comment by paellaencol** [comment]
Creo que le sucede a mas rogues
http://wow.freakz.ro/spells.php?spell=58426

**Comment by Monleon** [comment]
Esto ya funciona

**Comment by dylanvindas** [comment]
acabo de comprobar y aun no esta funcionando, reparar por favor.

**Comment by Overseer101** [comment]
Pone que falta compilar por favor, en cuanto se compile funcionara...
