### ISSUE TITLE
[Mazmorras/Bandas][Castillo Colmillo Oscuro Heroico] Loot y puntos de justicia

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#2969]
Buenas.
Quería reportar que los bosses de la mazmorra Castillo Colmillo Oscuro en dificultad heroico no están dando loot ni puntos de justicia.
Los bosses son:
Barón Ashbury http://es.wowhead.com/npc=46962
Barón Filargenta http://es.wowhead.com/npc=3887
Comandante Vallefont http://es.wowhead.com/npc=4278
Lord Walden http://es.wowhead.com/npc=46963
Lord Godfrey http://es.wowhead.com/npc=46964
Gracias y hasta luego

**Comment by ghost** [comment]
=(

**Comment by redneo** [comment]
lo cerre pq ya meti los loots y la justicia :P
