### ISSUE TITLE
[Errores internos] Zeppelin de Claros de Tirisfal a Vega de Tuercespina.

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#2970]
Descripción del bug:

Al tomar el Zeppelin de Claros de Tirisfal (En la Torre entre Entrañas y Rémol) que va en dirección a la Vega de Tuercespina se bugea a mitad de camino, desapareciendo y dejando caer el pj a una sección vacía del mar, donde el pj muere por la caída.

Al liberar el espíritu aparece en el mismo sitio impidiendo revivir o usar desatascar pj y volver al cementerio, esto hace que sea necesario poner ticket para que un GM te saque de ahí.

Me ha pasado 2 veces y no sé si pasa con otros Zeppelin. Agradezco que lo arreglen lo más pronto posible ya que me parece un bug bastante importante y que afecta mucho.

**Comment by Monleon** [comment]
Esto se puede cerrar, ya no sucede.
