### ISSUE TITLE
Tablón de se necesita héroe

### ISSUE THREAD

**Issue by titoalfon** [RoDNet/Bugtracker-Infinium-4.3.4#2977]
Hace poco migre un personaje(nivel 80) desde un servidor wotlk 3.3.5a y resulta que no me aparecen en el tablón de anuncios de Ventormenta las misiones de se necesita heroe
en las zonas cata, es decir: Monte Hyjal, Vash'jir, Infralar, Uldum,Tierras Altas crepusculares.

**Comment by redneo** [comment]
Puede ser o bien, pq no eres 80, o pq te salen muchas misiones y algunas no te salen.
