### ISSUE TITLE
[ Hunter > Glifos ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#298]
( Los siguientes glifos tendrán una ID correcta, pero el nombre no coincidirá en algunos de ellos ya que desaparecen casi todos en MoP )

Glifo de disparo mortal:
http://es.wowhead.com/spell=64304

Al lanzar disparo mortal ( http://es.wowhead.com/spell=53351 ) si el objetivo no muere, se recarga automáticamente, este efecto no puede tener lugar más de una vez cada 6 sec.
- Hay que scriptearlo entero, no se recarga una segunda vez al no morir el target.

---

Glifo de disparo silenciador:
http://es.wowhead.com/spell=57007

Cuando lanzas disparo silenciador ( http://es.wowhead.com/spell=34490 ) con éxito te restaura instantáneamente 10p. de enfoque.
- TODOS los disparos ofensivos del cazador hacen que te restaure +10p de foco, cuando SOLO DEBERÍA SER DISPARO SILENCIADOR.

---

**Comment by miglent** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/113

**Comment by Hellythium** [comment]
Te apoyo Gromelger, aunque seas mi archienemigo, y tembien tengo una lista grande de reportes, que mi compañero Miglent acaba de compartir

**Comment by DatJetto** [comment]
El staff trabaja por Issue por bug, NO todos los bugs en un reporte, por eso los puse individuales según estube viendo los bugs.

¿Archienemigo? xD

**Comment by Hellythium** [comment]
Espero que al menos con tanto reporte si los arreglen, por que ya somos como 5 personas reportando cosas del cazador

**Comment by searum** [comment]
fix
