### ISSUE TITLE
[Banda: Bastión Crepuscular]  Consejo de Ascendientes

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2980]
Tercer boss de la raid http://es.wowhead.com/zone=5334

Un problema que hemos visto en un miembro del concilio Arion http://es.wowhead.com/npc=43688#abilities

Utiliza la "Vara de relámpagos" http://es.wowhead.com/spell=83099#english-comments en más de un miembro de la raid, únicamente debería marcar a uno.

Esto es lo que está sucediendo, las está renovando y marcando a varios miembros de la raid

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/819/0pjo.jpg/'><img src='http://img819.imageshack.us/img819/4686/0pjo.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

http://img819.imageshack.us/img819/4686/0pjo.jpg

Breve descripción de lo que hace: In addition to those two, he will place a Lightning Rod on a random raid member. After 5 seconds of having this on you, you will conduct chain lightning to EVERYONE 20yds around you. Run to the wall ASAP if you get this. This will wipe you.

**Comment by paellaencol** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2445

**Comment by paellaencol** [comment]
Vale, la periodicidad que debería tener el hecho que ponga una Vara de relámpagos sobre un solo objetivo de la raid al azar, debería de ser cada 20eg.

**Comment by searum** [comment]
fix
