### ISSUE TITLE
 [El Círculo de Sangre: el desafío final]

### ISSUE THREAD

**Issue by Sinisterheart** [RoDNet/Bugtracker-Infinium-4.3.4#2982]
Buenas, veréis esta mision la hicimos en grupo de tres, pero al terminarla solo uno pudo completar dicha misión, ya que a los otros dos se nos bugueo y ni si quiera nos dio experiencia el boss final, teniendo en cuenta que el equipo que daban nos interesaba pido por favor que lo mireis, un abrazo, Vudhu.

**Comment by paellaencol** [comment]
http://es.wowhead.com/quest=9977

**Comment by Compresor** [comment]
Funciona
