### ISSUE TITLE
Zeppelin de Bancalto

### ISSUE THREAD

**Issue by Kaburo** [RoDNet/Bugtracker-Infinium-4.3.4#2983]
En Bancalto, en tierras altas crepusculares, si tocas el suelo te teletransporta al centro del Mar adusto y se queda pillado tu personaje ahi.

**Comment by Velcositro** [comment]
Supongo que es como lo que explico aquí: #2970

**Comment by Monleon** [comment]
Esto se puede cerrar, ya no sucede.
