### ISSUE TITLE
[Palabra de poder: escudo] Sacerdote heal disciplina

### ISSUE THREAD

**Issue by orcca** [RoDNet/Bugtracker-Infinium-4.3.4#2985]
Solo absorbe 8136 puntos de daño.Ni va maestría ni va talentos  [Palabra de poder mejorada: escudo].

**Comment by Compresor** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
