### ISSUE TITLE
[Mazmorra Grim Batol] Erudax (hc)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#2988]
Enlace de boss: http://es.wowhead.com/npc=40484#encounter

Enlace de la habilidad problemática: http://es.wowhead.com/spell=75664/vendaval-de-las-sombras

Cuando Erudax castea esta habilidad está dando wow error a los jugadores presentes en ese momento. Además no debería poder ser interrumpible

**Comment by melcalla** [comment]
tráete un cazador , y lo silencias a distancia , el sacerdote holy también lo puede hacer

**Comment by searum** [comment]
pues a mi no me da wow error XD
