### ISSUE TITLE
[NPCs] Hijos de Hodir

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#299]
No existe ninguno de los npc para interactuar  de esta facción (http://es.wowhead.com/faction=1119#members) en el poblado de "Dun Niffelem"

Solo se ven gigantes llamados "hijo de hodir" (http://es.wowhead.com/npc=30262) y no hacen nada. Además, los Huargos de Escarcha (http://es.wowhead.com/npc=30455) y Gigante de Escarcha de Niffelem (http://es.wowhead.com/npc=29351)  sirven como "vehiculos de montar", pero no los puedo manipular, solo me monto y ellos siguen naturales.

Faltan todos los npc que dan misiones e interacción:
http://es.wowhead.com/npc=30127
http://es.wowhead.com/npc=30425
http://es.wowhead.com/npc=30456
http://es.wowhead.com/npc=30105
http://es.wowhead.com/npc=30252
http://es.wowhead.com/npc=30123

el tipo del grifo:
http://es.wowhead.com/npc=32571

y vendedores comunes + vendedor de facción :

http://es.wowhead.com/npc=32594
http://es.wowhead.com/npc=32540

---

![wowscrnshot_070813_122924](https://f.cloud.github.com/assets/4790547/763057/4fb903cc-e7f6-11e2-9782-f15ce68832af.jpg)
![wowscrnshot_070813_123150](https://f.cloud.github.com/assets/4790547/763058/4fbf3d82-e7f6-11e2-8368-940e4c2cee70.jpg)
![wowscrnshot_070813_122928](https://f.cloud.github.com/assets/4790547/763059/4fc1a518-e7f6-11e2-89ef-1ebb824d343c.jpg)
![wowscrnshot_070813_123734](https://f.cloud.github.com/assets/4790547/763060/4fc43008-e7f6-11e2-94ef-cd7b32c1089c.jpg)
![wowscrnshot_070813_123754](https://f.cloud.github.com/assets/4790547/763061/4fca0dc0-e7f6-11e2-9be5-f83139411acd.jpg)

**Comment by crowel** [comment]
Para poder ver a los npc que comentas, debes de llegar a amistoso con la reputación.
Lo demás ya está fix.
Saludos.

**Comment by lamaza** [comment]
Cuando lo reporté yo ya estaba exaltado. Pienso que los npj que no estan, se quedaron en otra fase.
