### ISSUE TITLE
atascado urgente

### ISSUE THREAD

**Issue by 111baby111** [RoDNet/Bugtracker-Infinium-4.3.4#2991]
tome un barco con la intención de ir a rasganorte pero no recordaba si era ese barco el que me servia, cuando ya estoy en el barco me lleva a lavoragine y me deja volando, caigo y muero, ya muerto no puedo revivir en ningún momento ni desatascar mi personaje con la ayuda de la pestaña del asistente del cliente ni por la pagina 
les agradezco por ayudarme. muchas gracias

**Comment by Wiinter** [comment]
Pon ticket ingame, asi te atenderán antes

**Comment by 111baby111** [comment]
no entiendo?

**Comment by 111baby111** [comment]
me pueden ayudar
se los agradesco

**Comment by Wiinter** [comment]
Hay una opción de poner un mensaje a los gms dentro del juego, y a eso se le llama ticket. Vas a la pestaña que es un interrogante y alli hay una sección que es consultar a un gm o algo asi. Y alli escribes el mensaje
