### ISSUE TITLE
Mision y logros bug del titulo juergista (ALIANZA)

### ISSUE THREAD

**Issue by feniix97** [RoDNet/Bugtracker-Infinium-4.3.4#2992]
Logro: tra-la-la-la-ogri'la:http://es.wowhead.com/achievement=1282/
Bug: no se puede hacer esta misión x dos razones 1:necesitas hacer la cadenas de misiones de este ogro:http://es.wowhead.com/npc=23233  para poder desbloquear la misión del logro:http://es.wowhead.com/quest=11023
La segunda misión que da ese ogro:http://es.wowhead.com/quest=11058 esta bug no se puede hacer de ningún modo.

Logro: es la temporada:http://es.wowhead.com/achievement=277/
Bug: no hay forma de conseguir pastel de macedonia y carne de graccu:http://es.wowhead.com/item=21215/
se supone que te lo tiene que dar el padre invierno al completar la misión golosinas para el padre invierno:http://es.wowhead.com/quest=7025
dándote este regalo:http://es.wowhead.com/item=21216
pero el esta dando  este regalo:http://es.wowhead.com/item=17727#contains
Imposibilitando el logro.

Logro: hermanos antes del jo jo jo:http://es.wowhead.com/achievement=1686/
Bug: no hay forma de conseguir muérdagos:http://es.wowhead.com/item=21519/
ya que solo se pueden obtener al besar a los juerguista invernales:http://es.wowhead.com/npc=15760/#english-comments
que están en las tabernas de todas las capitales de la alianza y no los dan aunque los beses.

Logro ¡que nieve!:http://es.wowhead.com/achievement=1687/#comments
Bug: al besar a los juerguista invernales no dan copos de nieve:http://es.wowhead.com/item=34191/

logro: con un poco de ayuda de mis amigos:http://es.wowhead.com/achievement=252/
Bug: al entrar a bg el efecto de la maquina maravoltio invernal desparece lo que imposibilita matar y lograr las 50 muertes.

logro: meneíto helado:http://es.wowhead.com/achievement=1690/
Bug: no se puede obtener el traje del festival del invierno http://es.wowhead.com/item=17712 por estar bug la misión: que ruin:http://es.wowhead.com/quest=7043/
 hay que probar si se puede obtener el logro bailando con el traje.

**Comment by feniix97** [comment]
Me faltan revisar tres logros mas revisar:
Sabrá si has sido malo:http://es.wowhead.com/achievement=1689/
A cantar villancicos:http://es.wowhead.com/achievement=5853/
Coches de choque:http://es.wowhead.com/achievement=1295/
pero se supone que estos 3 logros se obtienen después del 24 de diciembre cuando los regalos aparecen abajo de los arboles  de navidad. si pueden los gms estaría bueno q los revisaran, por si acaso.

**Comment by redneo** [comment]
Lo de besar los juerguistas, ya lo he solucionado.
Lo de la ayuda de mis amigos, he puesto un transformador en la arena de gurushabi, con lo cual se puede conseguir el logro.

Mañana a ver si lo dejo todo solucionado, paciencia... de todas formas, alargaré el evento algun dia

**Comment by feniix97** [comment]
mm lo de gurubashi hay que cambiarlo no se puede esperar todo el día a que aparezca un horda y matarlo, así jamás se completaría el logro.

**Comment by feniix97** [comment]
Probé usar los muérdagos:http://es.wowhead.com/item=21519/ en los hermanos de la alianza
Logro:http://es.wowhead.com/achievement=1686/ y al usarlo no funcionan los muérdagos en ellos este es un nuevo bug del evento q no puse.

**Comment by redneo** [comment]
Como has visto, he arreglado ciertas cosas, las he ido borrando de la lista.

Estoy en la parte de la mision de los ogrila, que ya se pueden completar, lo que no se la siguiente, la de bombardear se puede hacer.

Comentar que el heroe del día necesita de cocina a 300 para poder hacerse.

**Comment by Wiinter** [comment]
El logro de a cantar villancicos no se puede hacer hasta que no aparezcan los regalos. Este año toca el jersey chillón en los regalos que te permitirá completar ese logro. Si tienes tiempo miratelo @redneo pero corre menos prisa que los demás, porque como he dicho anteriormente, se completa despues del que salga el regalo en el árbol.

**Comment by redneo** [comment]
Si que funciona, lo prové ayer con un pj (Horda) y me conto al usar el jersey.

**Comment by Szajil** [comment]
La maquina de gurubashi no funciona....se va el buff al entrar en bg

**Comment by feniix97** [comment]
Este es un bug nuevo: al parecer me equivoque de como obtener el traje del festival de invierno completo
Traje:http://es.wowhead.com/item=17712
Al parecer se obtiene haciendo esta misión:http://es.wowhead.com/quest=7042/
y al terminarla al transcurrir 24 horas el traje te viene x correo para sacar el logro meneíto helado:http://es.wowhead.com/achievement=1690/
lo que pasa es que ya varios esperamos las 24 horas y no nos vino el traje lo que imposibilita el logro ya que no era una misión diaria, si puede que un gm revise como darle los trajes a la gente que ya hizo la misión ya que no tiene forma de obtenerlo ahora.

**Comment by redneo** [comment]
Ya se puede coger la mision Horda y Alianza.

**Comment by ghost** [comment]
La misión Golosinas para el Gran Padre Invierno (http://es.wowhead.com/quest=7025) la pude conseguir con un PJ Draenei pero no con un PJ Huargen.
Saludos!

**Comment by Velcositro** [comment]
Buenas, ¿cuál es el estado del logro "Es la Temporada"?¿será posible obtener el pastel? Disculpen por no aportar nada más que una pregunta pero necesito saberlo porque es el único logro que me falta para ser Juerguista y sería bastante triste tener que esperar al año que viene o quién sabe cuándo. Gracias por el esfuerzo.

Edito: Ya está disponible en los vendedores así que pude comprarlo y conseguir el logro, muchas gracias.

**Comment by feniix97** [comment]
Otro bug que reportar tengo
logro: sabrá si has sido malo:http://es.wowhead.com/achievement=1689/sabra-si-has-sido-malo#comments
bug:ya es 25 de diciembre y aun no se pueden abrir los regalos de navidad que hay abajo los arboles en ventormenta

**Comment by feniix97** [comment]
Logro coches de choque:http://es.wowhead.com/achievement=1295/coches-de-choque
Objeto:http://es.wowhead.com/item=54343/mando-de-coche-de-carreras-triturador-azul
Bug: Al controlarlo no aparecen las barras de acción del coche imposibilitando atacar a otros, básicamente al usarlo no tiene ataques
