### ISSUE TITLE
[hechizos/talentos][Mago] Bloque de hielo

### ISSUE THREAD

**Issue by RaulioWoW** [RoDNet/Bugtracker-Infinium-4.3.4#2994]
Hechizo: http://es.wowhead.com/spell=45438

Se supone que cuando estas en el bloque eres inmune a todo daño, cosa que no sucede, incluso te llegan a matar estando en el bloque.
Expongo 3 imagenes, donde se ve que me bajan casi toda la vida estando en el dichoso bloque. 

imagen 1 --> http://www.subeimagenes.com/img/1-797333.jpg
imagen 2 --> http://www.subeimagenes.com/img/2-797334.jpg
imagen 3 --> http://www.subeimagenes.com/img/3-797335.jpg

Esto es una gran ventaja para esas clases que lo usan y veo que estan abusando de ello, despues lloran porque el guerrero salta "donde no deberia" ? pss hay clases que realmente estan pasadas de bug.

PD: No soy experto en el wow , pero siempre ando leyendo e informandome, y no encontre ningun glifo que beneficie a este hechizo, o que permita que yo reciba daño estando en el bloque, asi que disculpen si es un error mio el colocar esto como bug,o hay algo que yo desconozca que alguien me aclare, porque encontre raro tambien que nadie lo halla anunciado, asi que bien puede ser un error mio, un saludo.

**Comment by Wiinter** [comment]
Eso no es el bloque de hielo del mago, porque el bloque de hielo se lo tira a si mismo, no se lo puede tirar a los demás. Lo que te han tirado es el frío hambriento, o algo así, del dk. Que te convierten en bloque de hielo durante un tiempo o hasta que te ataca el dk diría.

P.D: Lo que puede estar bug es que no se te desbloquee al recibir daño de otros pjs que no sean el dk. Porque con cualquier daño te deberías descongelar.

**Comment by RaulioWoW** [comment]
hola wiinter, precisamente eso estabamos discutiendo con un amigo, y por eso tambien cerre el post, ya que en todas las capturas que encontre en la pc , no vi nada en el registro. Si de algo estoy seguro es que solo estaba el mago, ya que me paso varias veces en varios lugares en la bg , y estando yo cuidando base, cuando lllega solo el mago, sin nadie mas. Y justamente con mi amigo llegamos a lo mismo, que hay un bug como tu dices que no  se desbloquea al recibir daño. Asi que estare viendo mas ese tema, y reunire las pruebas que hagan falta, espero me ayuden, asi hay mas igualdad en las clases.Un saludo

PD: iba a borrar esto, pero ni idea de como se hace , asi que solo lo cerre.

**Comment by Wiinter** [comment]
Seguro qe es algo del mago frost, alguna habilidad qe no se. Pero bloque de hielo no. Si la descubro ya te diré algo :)

Aunque @asman1 suele mirar bastante el bugtracker y diria qe entiene bastante mas que yo de magos xD

**Comment by ghost** [comment]
A raiz de las fotos lo único que se puede ver es que estás <strong>congelado por el anillo de escarcha</strong> de un mago, no tiene que ser escarcha, es una habilidad genérica de mago para todas las ramas. Cuando la lanzan se debe ver un halo circular blanco girando y, tras 3 segundos deja de girar y todo lo que lo toque se queda congelado durante 8segundos, que es lo que te ha pasado a tí.

Hace tiempo que no entro al servidor porque me parece una pérdida de tiempo viendo como está, pero puede que se haya bugeado ahora y le pase algo extraño? o no conocías la spell?

Otro posible motivo (<strong>si no recuerdas haber visto nada circular blanco en el suelo</strong>) es que el que el mago que lo haya lanzado lo haya hecho invisible lanzando un objeto justo en el mismo sitio donde se lanza el anillo, lo que lo deja completamente invisible pasados los 3 segundos, pero se aplicó un fix en el oficial si no me equivoco para evitar esto, a no ser que esté bug también dudo que esta sea la causa.

---

Por otro lado, como bien te han dicho, el cubo de hielo es una habilidad de mago que no puede ser lanzada a nadie más. 

La congelación que tu has sufrido, pese a tener la misma animación gráfica es otra cosa totalmente distinta. Se rompe (o debería hacerlo) al recibir un 10% de daño respecto a tu vida total, al usar insignia de la alianza/sálvese quien pueda, o si te lo limpian ya que es un efecto mágico.

http://www.wowhead.com/spell=113724/
