### ISSUE TITLE
casa de subasta

### ISSUE THREAD

**Issue by 111baby111** [RoDNet/Bugtracker-Infinium-4.3.4#2995]
la presente es para informales que he tenido algunos problemas con la casa de subastas por la venta de glifos por que no recibo la cantidad de dinero correspondiente a tiempo del mensaje o no recibo el dinero en dicho caso. 
quisiera saber que puedo hacer en esos casos
les agradezco por ayudarme

**Comment by Sagittariu5** [comment]
La casa de subastas siempre se lleva una pequeña comisión por encargarse de vender  tus objetos por ti.

**Comment by 111baby111** [comment]
pero a veces no recibo el dinero que cuesta el glifo, osea aparece que se lo di gratis o no se cuando me devuelven el dinero

**Comment by Compresor** [comment]
La casa funciona perfecta
