### ISSUE TITLE
[Misión: Una espada de Campeón] Corona de hielo-Colinas pardas

### ISSUE THREAD

**Issue by Gurh** [RoDNet/Bugtracker-Infinium-4.3.4#2999]
La misión consiste en ir a un lago lleno de sapos azules, te tomas una poción y debes besar ranas hasta que una de ellas se convierte en una doncella, esta doncella te da la Espada de Lago Fresno y termina.

El problema es que la doncella no te da la espada.

Mision: http://es.wowhead.com/quest=13773
Doncella de Lago Fresno: http://es.wowhead.com/npc=33220/doncella-de-lago-fresno
Espada de Lago Fresno: http://es.wowhead.com/item=44981

**Comment by redneo** [comment]
A mi la doncella si que me ha dado la espada :S
