### ISSUE TITLE
bugs encontrados

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#3]
Buscador de Mazmorra y Banda no sirve.

Recompensas de Hermandad siguen bloqueadas a pesar de tener el lv correcto.

Veredicto del Templario del paladin, se hace infinito cuando se autoactiva, osea que lo puedo usar cuanto quiera hasta matar el mob o hasta que pase cierto tiempo, si lo hago rapido lanzo cuanto quiero XD.

**Comment by sherik12** [comment]
jajaj Para ser preciso, veredicto templario va bien el problema es que cuando se activa el talento Talento propósito divino, se puede usar veredicto templario hasta que desaparece el buff

**Comment by lamaza** [comment]
Tampoco aparecen las figurillas de camello en todo Uldum.
http://es.wowhead.com/npc=50410/figurilla-de-camello-misteriosa

**Comment by lamaza** [comment]
emmm no se si aún no lo tengan montado o que... Pero Herreria no muestra nada para aprender.

**Comment by ghost** [comment]
Un bug en cada reporte @lamaza :)
