### ISSUE TITLE
[NPC] Murog <Maestro de establos>

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#300]
Hola queria comentar que este NPC Murog <Maestro de establos>
http://es.wowhead.com/npc=47764

Actualmente no está haciendo nada, mas que poner un mensaje al hablar.
Impidiendo interactuar con las mascotas del cazador.
![wowscrnshot_070813_194114](https://f.cloud.github.com/assets/3537253/763072/ac619e86-e7f6-11e2-9e29-b1a713f61031.jpg)

Esto esta actualmente al parecer en los demás maestros restantes.
Añado los enlaces de los otros dos maestros de orgrimar que no funcionan.
Bulrug <Maestro de establos> http://es.wowhead.com/npc=10054
Bezzil <Maestro de establos> http://es.wowhead.com/npc=45789

Un saludo.

**Comment by crowel** [comment]
Si alguien de la alianza, o saben algun maestro de establos que no funciona, enlazarlo aqui pls.

**Comment by DatJetto** [comment]
No funciona NINGÚN maestro de establos

**Comment by crowel** [comment]
Se acaba de cambiar el look el ogro
![wowscrnshot_070913_151602](https://f.cloud.github.com/assets/3537253/768316/5307ca70-e89d-11e2-8a25-0cf1e74b30e9.jpg)

Too Sexy jaja.
Sigue sin poder interactuar con el npc.

Un saludo.

**Comment by crowel** [comment]
Acabo de detectar algo distinto en el NPC de establos.
Ahora se puede interactuar con el pero lo único que vende un objeto, no se pueden ver los establos.
![wowscrnshot_071613_160826](https://f.cloud.github.com/assets/3537253/805265/1ba5dadc-ee23-11e2-92c5-5b470cc2c4b7.jpg)

**Comment by crowel** [comment]
Esto está fix al igual que todos los demás maestros.
