### ISSUE TITLE
[Receta - Joyería] Escrito sobre joyas ardientes

### ISSUE THREAD

**Issue by josselyn** [RoDNet/Bugtracker-Infinium-4.3.4#3000]
Compre la receta a Tarissa Lazuria http://es.wowhead.com/npc=57922 y no enseña ninguna gema aleatoria, solo se ve el casteo donde la estas leyendo.

Esta es la receta: http://es.wowhead.com/item=71949

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/319?source=cc
Ya reportado, gracias.
