### ISSUE TITLE
[Mazmorra] Zul Aman - Halazzi

### ISSUE THREAD

**Issue by melcalla** [RoDNet/Bugtracker-Infinium-4.3.4#3001]
halazzi ,     uno de los boss de la estancia la ultima fase de este no funciona como deveria.

http://es.wowhead.com/npc=23577

**Comment by efectokoleos** [comment]
cual es el problema exactamente?

**Comment by redneo** [comment]
Le he bajado considerablemente el daño cuerpo a cuerpo. No se que mas fallos puede tener.

**Comment by Dekadencee** [comment]
Cerramos, si continua bug abre un ticket especificando el error, sin información el reporte no nos vale.
