### ISSUE TITLE
Ingenieria de sollozos

### ISSUE THREAD

**Issue by sollozos** [RoDNet/Bugtracker-Infinium-4.3.4#3002]
hola soy sollozos un DK alianza lobo, mi ingenieria tras crear el machacapollos, no me aprendio los enchants correspondientes.
help plis.

**Comment by Jhovanni** [comment]
Bueno, esto no va aquí exactamente pero te contestaré.
Hubo un parche por Blizzard para ayudar a las personas que tenían 7 de los 8 encantamientos de ingeniería, con lo cual pusieron 100% de probabilidad para obtener el último encantamiento mediante el Machacapollos derrotado. Pero eso solo funciona una vez, así que si lo gastaste pues no sé si obtendrás los otros (supongo que si, por el método habitual)
Esto es lo que decía el fix:

Engineering
- All eight of the Engineering discoveries are now able to be learned through crafting the Overpowered Chicken Splitter at max-level Engineering.
  
  If you are max engineering and only know 7 of the tinkers, craft this and you should learn the final one. Be wary as it won't teach you anything else if you already know all 8.
  If you happen to hit max engineering and don't even know 7 of the 8 (and thereby need more than 1 to learn), crafting this item at max skill teaches you only one of the tinkers, not all of them remaining.

Como nota adicional te puedo decir que hace como 10 días obtuve los 8 encantamientos haciendo como 60 "cebo giratorio tratado con calor". Verídico y puedes probar con ellos.

**Comment by Compresor** [comment]
@sollozos cierra el issue si se te ha solucionado el problema
