### ISSUE TITLE
mision: sanacion relampago 

### ISSUE THREAD

**Issue by avatarazakieL1** [RoDNet/Bugtracker-Infinium-4.3.4#3003]
esta mision esta bug se encuentra en gilneas la da la instructora de sacerdotes 
y se trata de curar a unos guardias heridos con el hechizo sanacion relampago 2 veces sobre cada guardia 
pero no pasa nada espero me puedan ayudar :D gracias +1: 

att : pj azakiel:  
 raza y clase : huargen sacerdote
lvl 15
zona: rio puerta norte de gilneas

**Comment by Compresor** [comment]
Por favor mirate las reglas de reporte de misiones. 
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Cierro post
