### ISSUE TITLE
[Misión: ¡Recupera la mercancía!] Marjal Revolcafango

### ISSUE THREAD

**Issue by Zapphod** [RoDNet/Bugtracker-Infinium-4.3.4#3004]
La misión consiste en que el questgiver te da un ítem "Equipo de rescate", con el que al ir a restos de naufragios bajo el agua,aprietas el item en los restos de naufragio y sacas una "caja fuerte rescatada". El problema es que el ítem no detecta que esta en los restos de naufragio y por esto no se puede ocupar. Tampoco se ven los restos flotando en el agua en los que se podria ocupar el item

misión: http://es.wowhead.com/quest=27237/
Item "Equipo de rescate": http://es.wowhead.com/item=33044

**Comment by redneo** [comment]
Hay restos por ahi y se puede sacar el objeto de mision.

Por ejemplo en la posicion 66.62 - 23.69 hay uno que me ha sacado el objeto de mision
