### ISSUE TITLE
No logro hacerme con las armas de honor de 2450 puntos.

### ISSUE THREAD

**Issue by Tachibanakun** [RoDNet/Bugtracker-Infinium-4.3.4#3007]
Buenas, ps siempre me ha salido el aviso de que necesito 7500 puntos de honor para poder hacerme con las armas, pero como pueden ver en la foto adjunta, tengo todo el set y ademas 4000 puntos de honor, sin embargo me sale el aviso que no cumplo los requisitos.
![wowscrnshot_121913_141839](https://f.cloud.github.com/assets/3105071/1785323/717dee74-68e2-11e3-81f3-a6b3c088b6c7.jpg)
![wowscrnshot_121913_141849](https://f.cloud.github.com/assets/3105071/1785325/77aa4d24-68e2-11e3-9657-c7b7b8720c99.jpg)
Y ps he hecho todo lo que em dicen de borrar caché etc. y nada, sigo con el mismo problema.. 
Ayudenme a solucionarlo porfavoree. 
Salu2
PDTA: Toda mi cuenta tiene el mismo problema, pero me interesa más Migiwara, picaro nivel 85
Cuenta: Tachibanakun

**Comment by F4NT4SM4** [comment]
tecla C anda a la pestaña de monedas pon el curso en el honor dimos cuanto has ganado en la temporada
