### ISSUE TITLE
cocina "festines"

### ISSUE THREAD

**Issue by melcalla** [RoDNet/Bugtracker-Infinium-4.3.4#3008]
http://es.wowhead.com/item=34753/gran-festin
http://es.wowhead.com/item=62290

ninguno de los festines funciona regeneras mana y vida pero el efecto bien alimentado no funciona.

**Comment by Monleon** [comment]
Seguimos desde https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2893
