### ISSUE TITLE
No recibo el dinero de las subastas

### ISSUE THREAD

**Issue by Gat0Negr0** [RoDNet/Bugtracker-Infinium-4.3.4#3011]
Pues eso. Hay varias veces que no recibo el dinero de las subastas. Borro la carpeta Cahe pero el bug sigue saliendo. Por favor resuelvanlo cuanto antes, que estoy perdiendo dinero puesto que los correos solo duran una hora.

Personaje: Gavril

![wowscrnshot_122113_040113](https://f.cloud.github.com/assets/6150198/1795141/34dbf3a2-69ec-11e3-8b11-807a26cee3fa.jpg)

**Comment by ghost** [comment]
? Esos correos llegan justo cuando has vendido algo, son solo informativos. El dinero (25g 57s 52c) llega 1 hora después en otro correo de la casa de subastas, y este correo informativo de la foto desaparecerá para entonces.

**Comment by Gat0Negr0** [comment]
Gracias man, pensaba que era un bug.
