### ISSUE TITLE
[Maestría] Druida - Armonía

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#3015]
![armonia](https://f.cloud.github.com/assets/3537253/1798500/32ef6ff2-6b53-11e3-9571-1c2a55b4ec06.png)

Mastery: Harmony http://cata.openwow.com/spell=77495
La maestría del druida restauración no está funcionando.

Aquí pongo tambien el id del buffo que se debe activar de la maestría tras realizar las sanaciones directas que tampoco se activa.
Harmony: http://cata.openwow.com/spell=100977

Un saludo.

**Comment by searum** [comment]
fix
