### ISSUE TITLE
[Talento] Druida Restauración - Obsequio de la naturaleza

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#3016]
![obsequio de la naturaleza](https://f.cloud.github.com/assets/3537253/1798531/ec3c1bc0-6b55-11e3-9a53-e966ee2673b7.png)

Nature's Bounty Rank 1 http://cata.openwow.com/spell=17074
Nature's Bounty Rank 2 http://cata.openwow.com/spell=17075
Nature's Bounty Rank 3 http://cata.openwow.com/spell=17076

La primera parte del talento funciona la segunda no, no reduce el tiempo de lanzamiento de nutrir.

Nutrir / Nourish - http://cata.openwow.com/spell=50464

Un saludo.

**Comment by searum** [comment]
fix
