### ISSUE TITLE
[Ingeniería] Muelles de sinapsis

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3017]
Nombre: Muelles de sinapsis
Enlace: http://es.wowhead.com/spell=82175/muelles-de-sinapsis
Problema: Este es un encantamiento adicional, por lo cual no debería borrar el encatamiento que ya posean los guantes, ni ser borrado al colocar un encantamiento nuevo que no sea de ingeniería. Muelles de sinapsis se está borrando al colocar otro encantamiento y ese es el bug.
(Opcional) Observaciones: Estos encantamientos de ingeniería son extras, tal como está [Propulsiones de nitro] [http://es.wowhead.com/spell=55016/propulsiones-de-nitro]. Con respecto a lo demás el hechizo está bien pues es usable en arenas tal como debe de ser.

**Comment by Pegasu5** [comment]
Esto ya fue posteado por Asman ya que los beneficios, de ingeniería no pueden ser usados en arenas, por lo menos en bg son necesarios.

**Comment by ghost** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2798

**Comment by Jhovanni** [comment]
Gracias por las referencias. Para aclarar un punto, hay ciertos encantamientos de ingeniería que si son usables en arenas, los muelles de sinapsis es uno, y el otro me parece es aquél que aumenta la armadura 1500pnts. Solo esos dos.

**Comment by ghost** [comment]
Puedes cerrar el reporte, ya está reportado como hemos puesto arriba, y lo que comentas en el último comentario funciona como debe.

Gracias! :D

**Comment by Jhovanni** [comment]
El reporte inicial de Asman ha perdido el texto base del post, por lo cual queda inexplicable. Reabro este entonces.
Aunque mejor si acomodan de vuelta aquél.

**Comment by Monleon** [comment]
Solucionado https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/4390
