### ISSUE TITLE
[Ingeniería] Base de tejido flexible

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3018]
Nota: Base de tejido flexible
Enlace: http://es.wowhead.com/spell=55002/base-de-tejido-flexible
Problema: Al tocar el usuario el piso, el paracaídas debe desaparecer y no lo hace, manteniendo el personaje el paracaídas los 30 segundos totales.
Por lo demás, el encantamiento solo puede ser activado en el aire, lo cual tampoco funciona bien pues se está activando aún cuando el usuario está en el suelo sin saltar.

**Comment by ghost** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2798
