### ISSUE TITLE
[Alquimia] Convertir: elementos vivos

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3019]
Enlace: http://es.wowhead.com/spell=78866/convertir-elementos-vivos

Descripción: Convertir: elementos vivos
Hechizo de 1.5 seg  1 seg de reutilización
Requiere nivel 45
Herramientas:
Piedra filosofal
Componentes:
Vida volátil (15)
Transforma la esencia de vida en otro elemento. No se puede conocer el resultado con exactitud antes de tiempo.

Problema: La descripción va perfecta, convierte la vida volatil http://es.wowhead.com/item=52329 en cualquier otro elemento aleatorio.

---

-¿Pero es siempre aleatorio?
- No, en esto debe haber una excepción (esto es lo que no está ocurriendo actualmente).
  Dependiendo en que zona del Cataclysm transmutemos, los elementos que obtengamos, no seran aleatorios, sino que se siempre convertirán en un elemento en concreto en función a la zona donde hayamos utilizado <b>Convertir: elementos vivos</b>
- Monte Hyjal http://es.wowhead.com/zone=616 : Fuego volátil http://es.wowhead.com/item=52325
- Vashj'ir http://es.wowhead.com/zone=5146 : Agua volátil http://es.wowhead.com/item=52326
- Infralar http://es.wowhead.com/zone=5042 : Tierra volátil http://es.wowhead.com/item=52327
- Uldum http://es.wowhead.com/zone=5034 : Aire volátil http://es.wowhead.com/item=52328

P.D. Añado fuente http://us.battle.net/wow/es/forum/topic/1406222102

P.D.2 Habría que revisar el cd de las transmutaciones de los Alquimistas, ya que deberían ser de 20h, y en algunos casos son de 3días

**Comment by efectokoleos** [comment]
arreglado falta compilar
