### ISSUE TITLE
[Misión][Cuna del Invierno] Práctica de caza

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3021]
Buenas.
• Nombre: Práctica de caza
• Enlace: http://es.wowhead.com/quest=29038
• Descripción: Lleva a tu cachorro a las madrigueras cubiertas de nieve en la parte norte de Cuna del Invierno 5 veces, para que aprenda a cazar liebres árticas. 
• Problema: El cachorro cuna de invierno (sale con http://es.wowhead.com/item=68646) no caza las liebres árticas en las madrigueras (http://es.wowhead.com/npc=51711)
• Observaciones: La misión está como "Hunting Practice"
Gracias!

**Comment by hermesjose94** [comment]
a mi me paso lo mismo me sale el cachorro pero no subia cunado lo alimentaba
