### ISSUE TITLE
Los orbes de las sombras no funcionan

### ISSUE THREAD

**Issue by Rickylix** [RoDNet/Bugtracker-Infinium-4.3.4#3022]
Tengo un gnomo sacerdote sombra con la habilidad pasiva de orbes de las sombras, pero no se activan por mucho que lo intento

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by Compresor** [comment]
Funcionan
