### ISSUE TITLE
[Mazmorras/Bandas][NPC's/Mobs][Caverna Santuario Serpiente] El Rondador de abajo

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3023]
Buenas.
• Nombre: El Rondador de abajo
• Enlace: http://es.wowhead.com/npc=21217
• Descripción: Este PNJ se puede encontrar en Caverna Santuario Serpiente
• Problema: Para que aparezca hay que pescarlo, pero no se puede pescar en la zona dentro del "circulo" (Debería aparecer como una especie de banco de peces).
Gracias y hasta luego

**Comment by RaulioWoW** [comment]
Hoy fuimos a esa banda y aun sigue sin poder pescar al boos :C gracias por reportarlo, ya que lo iba a hacer, un saludo.
