### ISSUE TITLE
Feronas Sindweller

### ISSUE THREAD

**Issue by lupakobayashi** [RoDNet/Bugtracker-Infinium-4.3.4#3024]
El NPC Feronas SIndweller, ubicado en Felwood no está, a pesar de que es objetivo de la misión Wanted: The Demon Hunter (http://www.wowhead.com/quest=28217)

**Comment by ghost** [comment]
npc=47923

**Comment by lupakobayashi** [comment]
Exacto, ese es el npc, pero voy al lugar donde debería estar ubicado y no está. Casualmente no se ven mobs en jadefire run ni en jadefire glen

**Comment by ghost** [comment]
porqué cierras reporte? está arreglado?

**Comment by lupakobayashi** [comment]
No lo cerré intencionalmente, no sé manejar bien el foro del bugtracker.... Y no, no está solucionado aún. Gracias por atender mi petición 

Enviado desde mi iPad

**Comment by ghost** [comment]
Debes darle al botón que pone "Open" abajo, así los GMs sabrán que tienen que arreglarlo.

Si quieres saber más sobre como funciona el bugtracker aquí he escrito una guía que puedes leer bastante explicativa: 

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/wiki/Gu%C3%ADa:-%C2%BFC%C3%B3mo-reporto-un-Bug-(Fallo)%3F

Saludos!

**Comment by Kiritoo** [comment]
Este npc esta correctamente.
