### ISSUE TITLE
Logro sabras si has sido malo (Alianza juerguista)

### ISSUE THREAD

**Issue by feniix97** [RoDNet/Bugtracker-Infinium-4.3.4#3025]
logro: sabrá  si has sido malo:http://es.wowhead.com/achievement=1689/sabra-si-has-sido-malo#comments
Bug: ya es 25 de diciembre y aun no se pueden abrir los regalos debajo de los arboles de navidad que hay en ventormenta

**Comment by redneo** [comment]
Pq en ventormenta no los dan.... vete a ver a los enanos!
