### ISSUE TITLE
Mision bug en Torneo

### ISSUE THREAD

**Issue by Szajil** [RoDNet/Bugtracker-Infinium-4.3.4#3026]
La mision http://es.wowhead.com/quest=13663/las-ordenes-del-caballero-negro anda bug. Al usar el item para controlar el glifo del caballero negro (http://es.wowhead.com/npc=33519) aparece un npc verde pero no da el paso de la mison como cmpletado. Los otros dos pasos de la mision si que los da como completos, pero no se puede entregar por que falta un paso....

**Comment by lexintor** [comment]
Ami me sale el glifo(voladora) pero no me puedo montar y es requerido

**Comment by VictoriaTier** [comment]
A dos meses de tu reporte sigue bug, y luego quieren que no dupliquemos los posts....
