### ISSUE TITLE
Dk Blood (Venganza)

### ISSUE THREAD

**Issue by Nereoh** [RoDNet/Bugtracker-Infinium-4.3.4#3027]
Hola, quiero hacer énfasis en el bug tan llamativo que está sufriendo el Dk Sangre. Ademas de otros el más destacado y que se debe de reparar rapidamete, es la activación de VENGANZA. Este talento si y solo si debe de activarse cuando el tanque es atacado por NPC, MOB, BOSSES, JcE..... Pero nunca cuando es atacado por Jugadores JcJ.

**Comment by ghost** [comment]
ID: 93099

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2769
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1226

Deberías leerte esto para los próximos reportes:

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/wiki/Gu%C3%ADa:-%C2%BFC%C3%B3mo-reporto-un-Bug-(Fallo)%3F
