### ISSUE TITLE
Mago Frost (Ice Lance, Orbe de pirofrio, Trizar)

### ISSUE THREAD

**Issue by Nereoh** [RoDNet/Bugtracker-Infinium-4.3.4#3028]
Hola, buenos días querria comentar el bug que experimenta estas habilidades. Empezemos por Lanza de Hielo:
- Ice Lance, contra jugadores no da el primer impacto, me explico cuando combinas descarga de escarcha mas lanza de hielo, lanza no hace daño la primera vez que la tiras.
- Orbe de pirofrio, no activa dedos de escarcha y no ralentiza al objetivo.
- TRIZAR, simple mente no activa el multiplicador de critico sobre objetivos congelados con ninguna de las habilidades ( Descarga de escarcha, Lanza de Hielo, Descarga de Pirofrio).

**Comment by ghost** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/wiki/Gu%C3%ADa:-%C2%BFC%C3%B3mo-reporto-un-Bug-(Fallo)%3F

Mal reportado, y bugs ya reportados por otros jugadores. 

Gracias por la intención, pero mírate las reglas antes por favor.
