### ISSUE TITLE
Bug de la montura de hermandad fenix oscuro

### ISSUE THREAD

**Issue by icargp** [RoDNet/Bugtracker-Infinium-4.3.4#3029]
El vendedor de objetos de recompensas de hermandad permite comprar la montura voladora del fénix oscuro. Pero al intentar montarla sale un mensaje en rojo que dice que ahun no se puede hacer eso. Vamos que se puede aprender a usarla, pero no montarla.
Lo podriais arreglar por favor?

**Comment by Necrofilo** [comment]
Para poder usar esa montura, tienes antes que conseguir los logros de hermandad de: Descenso de Alanegra, Bastión del Crepúsculo y Trono de los Cuatro Vientos.
