### ISSUE TITLE
[Mago] Orbe de llamas

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.3.4#303]
Orbe de llamas: http://old.wowhead.com/spell=82731
Tiene su daño bajo, pega 250 por tick cuando debería pegar más o menos 1800 por tick.

**Comment by searum** [comment]
esto pega bien

**Comment by ghost** [comment]
@searum Como va a pegar bien? No llega a 300 de daño, el daño debe ser mínimo mayor a 1k por poco gear que tengas. 

Si no me equivoco, al daño base de 270-290 se le debería de aplicar un 19,3% extra del poder de hechizos. Yo tengo 5.4k de poder con hechizos, por lo que debería pegar 1089.4 aproximadamente y le pego 250 a los mobs de nivel 11.

Creo que el problema es ese, que no coge el bonus de las stats del mago, ni de poder con hechizos ni de índice de golpe, ya que siempre se hace el mismo daño y en ocasiones falla.
