### ISSUE TITLE
fallo mision la batalla por la ciudad de guilneas

### ISSUE THREAD

**Issue by rafyki** [RoDNet/Bugtracker-Infinium-4.3.4#3031]
en dicha mision aun siguen puestas las barreras d la anterior vez que estuve en la cuidad lo cual me impide completar esta mision gracias x solucionarlo

**Comment by Compresor** [comment]
Mirate las normas en el foro para reportar correctamente la misión. 
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Cierro issue
