### ISSUE TITLE
[Items/Objetos][Murallas del Fuego Infernal] Cofre de hierro vil reforzado (Heroico)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3032]
Buenas.
• Nombre: Cofre de hierro vil reforzado
• Enlace: http://es.wowhead.com/object=185168
• Problema: El cofre no se puede clickear para despojar.
• Observaciones: Aparece luego de vencer a los PNJ Vazruden el Heraldo (http://es.wowhead.com/npc=17307) y Nazan (http://es.wowhead.com/npc=17536); funciona en el modo normal de la mazmorra.
Gracias!!

**Comment by RaulioWoW** [comment]
exactamente!, justo lo iba a reportar ya que hay un item de set que nunca lo dropea jeje :P y ciertamente los cobres aparecen , pero no es posible el dropeo u.u
