### ISSUE TITLE
[Alquimia] Transmutar: veraoro

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3036]
Enlace: http://es.wowhead.com/spell=80243

Descripción: Transmuta barras de pirium en veraoro.

Problema: me he estado fijando que tras utilizar está transmutación, enseguida le aparece a la spell un cd de 3dias.
Este CD no debería ser de 3 días, sino de 1 al día
- Añado la explicación de 1 día, en realidad no se trata de 24h, sino que este CD se reinicia a la misma hora que se reinician las misiones diarias, o las mazmorras heroicas (creo que esa hora es las 5am). Esto es como debería suceder.

Es decir entre las 5am y las 4.59am deberíamos poder realizar una transmutación de este tipo, da igual a que hora la hagamos (pero una cada día, no una cada 3 días)

**Comment by efectokoleos** [comment]
arreglado falta compilar
