### ISSUE TITLE
[Mago] Poder del fuego

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.3.4#304]
Poder del fuego: http://old.wowhead.com/spell=54734
Cuándo se agota el orbe no explota e inflije daño con lo dice en su descripción. De el aumento de el daño fuego 1%/2%/3% No estoy muy seguro ya que es dificil ver si esque aumenta o no.

**Comment by searum** [comment]
esto esta bien :S
