### ISSUE TITLE
Armadura vil

### ISSUE THREAD

**Issue by matux12** [RoDNet/Bugtracker-Infinium-4.3.4#3040]
informo que la armadura vil esta mala, no esta dando la curacion al realizar hechizos ni da la cantidad de armadura que deberia.

**Comment by ghost** [comment]
Leete esto anda https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/wiki/Gu%C3%ADa:-%C2%BFC%C3%B3mo-reporto-un-Bug-(Fallo)%3F

Mal reportado y ya reportado previamente por otro jugador, cierra el reporte pulsando el botón rojo "Close".

Gracias por la intención, saludos!
