### ISSUE TITLE
MUERO EN VEGA DE TUERCESPINA Y APARESCO EN LOS BALDIOS

### ISSUE THREAD

**Issue by guselchido** [RoDNet/Bugtracker-Infinium-4.3.4#3041]
Cuando muero en vega de tuercespina aparesco en los baldios del norte con el angel y tengo que ir a pie a durotarpara ir en zepeling otraves a vega de tuercespina podrian solucionar este problema?

**Comment by Compresor** [comment]
Creo qe el problema está solucionado, me lo podrías comprovar y decir si va o no?

**Comment by Dekadencee** [comment]
Fixed
