### ISSUE TITLE
PORFAVOR ALLUDA URGENTE

### ISSUE THREAD

**Issue by joaquinillo13** [RoDNet/Bugtracker-Infinium-4.3.4#3046]
Hola mi nombre es joaquin ayer iva a ir a rasganorte con un barco que salía de ventormenta i a mitad de camino de golpe se me murió el personaje i apartir de ahí se a quedado bugeado i no puedo hacer absolutamente nada.

PORFAVOR PODRIAN TELETRANSPORTARME A CUALQUIER OTRO SITIO PARA PODER SEGUIR JUGANDO? 

MUCHAS GRACIAS :)

**Comment by ghost** [comment]
Antes que nada http://www.rae.es/

Luego mírate https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/wiki/Gu%C3%ADa:-%C2%BFC%C3%B3mo-reporto-un-Bug-(Fallo)%3F

Esto va en el foro, apartado de "Ayuda técnica". De todos modos, te recomiendo que pongas un ticket en el juego, será más rápido. También deberías decir el nombre de tu personaje para que puedan moverlo.

Dale al botón "Close" de más abajo. Suerte!

**Comment by joaquinillo13** [comment]
Mi nombre en el juego es jujaw  de todas formas siento comentar aquí esque como esta en ingles no encuentro el apartado de ayuda técnica. si me devolvéis a un cementerio cualquiera para poder seguir con mi personaje era nivel bastante alto.   MUCHAS GRACIAS POR SER TAN PACIENTES CONMIGO :)

**Comment by ghost** [comment]
Tienes que darle a Close otra vez, lo has dejado en Open.

El foro está en español, no en inglés, y el apartado que te comento se llama Ayuda técnica, este enlace te lleva allí directamente:

https://www.reignofdarkness.net/wow/forums/13-ayuda-tecnica/
