### ISSUE TITLE
Espada que no se puede transfigurar

### ISSUE THREAD

**Issue by feniix97** [RoDNet/Bugtracker-Infinium-4.3.4#3047]
Hola, como dice el titulo hay una espada que no se puede transfigurar y no hablo de un arma legendaria o un arma reliquia, sino una espada épica común es esta:http://es.wowhead.com/item=9372/sulthraze-la-azotadora
Me dijeron los gms que la reportara cuando envié ticket.
la reporto porque probé transfigurando armas de niveles mas bajos y un poco mas altos que esta  espada y no hubo problema solo con esta es.
encontré también información de blizzard sobre la transfiguración y porque lo veo no tendría que haber ningún problema con esta espada.
Transfiguración:http://eu.battle.net/wow/es/blog/10034196
pueden arreglarla o ver que le pasa?

**Comment by paellaencol** [comment]
He estado leyendo comentarios sobre transfiguración (yo nunca lo he hecho, no me agrada), y me he fijado que en ocasiones (raramente) hay items y sets que no deja transfigurar.

Ahora bien, desconozco por completo si esa espada es uno de ellos.

**Comment by feniix97** [comment]
Se ve algunas imágenes de gente con ropa transfigurada usando la espada en el link,así que quizá si se pueda transfigurar x eso pregunto si es un bug o no

**Comment by Corkryo** [comment]
A mi me ocurre lo mismo con la maza: La mano de antu'sul (http://es.wowhead.com/item=9639/la-mano-de-antusul), me deja colocarla en el hueco de mi maza actual, pero no puedo darle a aplicar...

**Comment by Velcositro** [comment]
Pasa con varios items, hay varios reportes de este estilo. Creo que deberían revisar el sistema de transfiguración completo para ver por qué falla con algunos con los que no debería fallar.

**Comment by Kiritoo** [comment]
Si veis que algun objeto debe poder transfigurarse y no lo hace reportarlos con un enlace demostrando que se puede y lo arreglamos.

**Comment by feniix97** [comment]
Bueno acá tengo comentarios en ingles de gente que jugaba en el 4.3.4 en wowhead y según veo si se puede transfigurar la espada  sul'thraze:http://es.wowhead.com/item=9372/sulthraze-la-azotadora
Comentarios:http://es.wowhead.com/transmog-set=1195/battleplate-of-radiant-glory-heroic-recolor#english-comments
también comentarios de foros de blizzard donde dicen que se trasfiguren la espada:http://us.battle.net/wow/es/forum/topic/3811292572?page=3
también una pagina donde muestra una buena transfiguración con la espada:http://wow-info.es/el-vestidor-como-lucir-como-un-caballero-negro
es todo lo q puedo dar de pruebas
