### ISSUE TITLE
Trono de los 4 vientos.

### ISSUE THREAD

**Issue by Mikeryublack** [RoDNet/Bugtracker-Infinium-4.3.4#3048]
Los jefes de Trono de los 4 vientos aplican 3 debuf, te dejan silenciado y reducen la sanación recibida un 100%, cosa que no es normal, haciendo totalmente imposible hacer la banda.

**Comment by Wiinter** [comment]
Si te salen 3 debuff es qe no lo haceis bien xD

**Comment by Mikeryublack** [comment]
¿Que no hacemos bien?, hicimos una banda de 10, puse en normal, entramos y
probamos 2 boses distintos, al atacar el tank, a todos nos ponía silenciado
y demás, no podíamos hacer nada y moríamos en cuestión de 3 segundos,

No digo que no hay algo que pudiéramos hacer mal, pero no se que es, si me
puedes decir que fallo hay, te lo agradecería mucho y diría a la gente
siempre que fallo no deven cometer al hacer lo mismo que yo.

Mire vídeos en youtube de como se hacia y .al atacar a un boss no hacia lo
que a nosotros nos hizo.

Gracias por adelantado y un saludo.

2014/1/4 Wiinter notifications@github.com

**Comment by Compresor** [comment]
Como dice Wiinter, puede ser que hagais mal el boss. Lo que teneis que hacer es siempre estar algun personaje cerca de los 3 bosses sino tendreis los buffos de silenciado. 

Sino no os sigue pasando este problema despues de pegar a los 3 bosses a la vez cerrad el issue por favor

**Comment by Monleon** [comment]
Tienen el rango de detección de pjs un poco bajo, nada más. Estando a una distancia de 40m o menos, ya no aplican el debuff.
