### ISSUE TITLE
[huagen-racial] huida oscura 68992 

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#3049]
Nombre: huida oscura
Enlace: 
http://es.wowhead.com/spell=68992#english-comments
http://wow.freakz.ro/spells.php?spell=68992

Descripcion: 
Activa tu forma verdadera, lo que aumenta tu velocidad de movimiento actual un 40% durante 10 s.

Problema: se esta acumulando con otros sprind de clases, como el de picaro http://es.wowhead.com/spell=2983 y druida http://es.wowhead.com/spell=1850 y ya e visto a 2 en bg que cojen la  bandera y se tiran los 2 cds abusando del bug

**Comment by ghost** [comment]
Ya me parecía a mí...he visto druidas en forma de gato que parecía que iban con speedhack.

**Comment by Necrofilo** [comment]
¿Y tampoco se puede acumular con el sprint de ingeniero o con eso sí? Porque he visto a bastantes huarguens ingenieros con una bombilla bien grande en la cabeza corriendo más que una montura terrestre de 100% de velocidad...
