### ISSUE TITLE
[Chaman Mejora] Choque Estático 

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3050]
Nombre: Choque Estatico
ID: 51525/51526/51527
Enlace: http://wow.freakz.ro/spells.php?spell=51527
Descripcion: Cuando utilizas tus facultades Golpe Primigenio, Golpe de tormenta o Latigazo de lava mientras tienes Escudo de relámpagos activo, tienes un 15%/30%/45% de probabilidad de infligir daño igual a un orbe de Escudo de relámpagos.

Problema: Se esta activando con otros hechizos: Desatar Elementos, El ataque de viento furioso (pasivo) y solo deberia de activarse con 3 Ataques que son 
-Golpe Primigenio: 73899
-Golpe de Tormenta:17364
-Latigazo de Lava: 60103

Dejo unas imagenes por si las dudas 

![wowscrnshot_010314_180936](https://f.cloud.github.com/assets/3101842/1843037/6cdfb70c-74c8-11e3-83e2-9b4dbcd85fd9.jpg)

![wowscrnshot_010314_180401](https://f.cloud.github.com/assets/3101842/1843057/e4be9d74-74c8-11e3-9f59-509d2b1383cf.jpg)

**Comment by ghost** [comment]
![44543426](https://f.cloud.github.com/assets/3788004/1843317/5d6b0e2e-74ce-11e3-9756-49b78a740132.jpg)

**Comment by Ivanlopez-dev** [comment]
que gracioso, y el de hunter SV no está? O el de pala holy? Que lástima....

**Comment by Kiritoo** [comment]
Esto no es un chat... 
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by searum** [comment]
fix
