### ISSUE TITLE
[Chaman] Desatar viento

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3051]
Nombre: Desatar viento
ID: 73680
Enlace:http://wow.freakz.ro/spells.php?spell=73680
Descripcion: Centra la fuerza elemental imbuida en el armamento del chamán, con efectos concentrados según el encantamiento liberado.
Consulta las descripciones de cada hechizo de imbuir arma para ver los detalles relacionados con los efectos de desatar cada uno.

Problema: Solo deberia de Desatar el encantamiento que lleva puesta el arma y no hacer el efectivo pasivo de esta. Esta Desatando y relizando el efectivo pasivo de Arma de Viento Furioso. Solo esta sucediendo con ese Encantamiento testee con los otros encantamientos y hace bien su funcion de solo Desatar 

Observaciones: Podria ser que desatar elementos no este bug y sea el encantamiento arma viento furioso que el pasivo no tenga bien las condiciones de activarse solo con ataques meles

Arma Viento Furioso:8232

Dejo una imagen realizando desatar y se activa el efectivo pasivo tambien lo cual no deberia
![wowscrnshot_010314_182848](https://f.cloud.github.com/assets/3101842/1843260/5411807a-74cd-11e3-975d-73e249882179.jpg)

**Comment by paellaencol** [comment]
http://wow.freakz.ro/spells.php?spell=73681

**Comment by Ivanlopez-dev** [comment]
A ver tío, prueba a usar el Desatar elementos a RANGE, no salta el WindFury cuando se usa ésta skill......
Lo habrás activado usándolo a melee( Y le habrás pegado un merluzo a golpe blanco me apuesto lo que sea), date cuenta pero a mi no me salta NÚNCA Windfury cuando uso Choques, Spells, o cualquier cosa que no sean ataques a melee / Hit blanco. Its really

**Comment by F4NT4SM4** [comment]
quieres que suba un video activando el windfuri con desatar elementos?

**Comment by ghost** [comment]
Aporta todas las pruebas posible @F4NT4SM4 , así no podrán venir todos los chamis mejoras a desmentir los bugs falsamente, y tampoco habrá confusiones de paso ni reportes con demasiados comentarios.

Sería prioridad que el retrasado mental de Searum que lleva este servidor lo cerrase e hiciese algo bien por una vez en su vida, y dejase de engañar a los jugadores prometiendo un blizzlike, con gran soporte y migraciones y blablá de cuentos chinos y que luego no se pasan ni por los foros y se enfadan si les exigen lo más mínimo cuando son ellos los que prometen el oro y el moro siendo todo mentira.

**Comment by F4NT4SM4** [comment]
como no quise hacer muchos videos lo puse junto el video de arma voragine
http://www.youtube.com/watch?v=f2qAYtUIr1E&feature=youtu.be (solo se ve en 720p)
segundo 0:45

**Comment by Ivanlopez-dev** [comment]
No se puede reproducir tu video @F4NT4SM4 pero es cierto lol!
Acabo de testearlo otra vez y si que salta windfury al usar Desatar elementos.

Nose porqué pero cuando lo testeé no me aparecía el bug, te pido disculpas ha sido un error:p
Por si acaso pego una screen mía también, dos valen más q una xD
Saludos!

P.D: @asman1 "así no podrán venir todos los chamis mejoras a desmentir los bugs falsamente"
Mi intención no es desmentir falsamente para nada, símplemente creía que ese bug no estaba...
Y sí, estaría bien reparar algún que otro bug del SV.

http://img401.imageshack.us/img401/122/vira.jpg

**Comment by searum** [comment]
sinceramente yo no me entero con tus reportes tio... intenta resumirlos mas y no meter imagenes useless porque pierdes el tiempo, yo ni las miro.

**Comment by F4NT4SM4** [comment]
Desatar elementos (73680) esta activando el pasivo de Arma de viento furioso (8232) no deberia :S 
Intente explicarlo lo mas detallado para q la gente como predator no se quejara pero igual al principio se quejo y la final reconocio el bug :S

**Comment by searum** [comment]
vale y cual es el pasivo?

**Comment by F4NT4SM4** [comment]
Arma de viento furioso 8232
tiene 2 efectos el de desatar y el pasivo tienen la misma id busque aver si el pasivo tiene id propia pero no lo consigo o no tiene

**Comment by paellaencol** [comment]
Estaría bien que cambiaras el título del reporte por el de "Desatar viento", ya que "desatar elementos" son 5 spells distintas

**Comment by F4NT4SM4** [comment]
ah ya consegui la id con eso jaja
Desatar elementos (73680) solo activa Desatar Viento 73681 
pero el pasivo Arma de viento furioso 8232 no tiene que activarlo

**Comment by F4NT4SM4** [comment]
hare otro reporte mas resumido
