### ISSUE TITLE
[Chaman] Escudo de Relampagos

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3052]
Nombre: Escudo de Relámpagos
ID: 324
Enlace:http://wow.freakz.ro/spells.php?spell=324
Descripcion: The caster is surrounded by 3 balls of lightning. When a spell, melee or ranged attack hits the caster, the attacker will be struck for 390 (+26.7% SP) Nature damage. This expends one lightning ball. Only one ball will fire every few seconds. Lasts 10 minutes. Only one Elemental Shield can be active on the Shaman at any one time.

Problema: Tiene el daño un poco elevado por favor revisenlo si no es mucha molestia

Observaciones: Capas me equivoque pero me parece raro que en bg segun mi recount el Escudo de relampago sea el que mas daño ha hecho de todas mis skill de chaman. Se supone que rebufear el escudo de relampago era la ultima prioridad del chaman mejora en el offi no era muy importante pero ahora parece prioridad maxima pego alto con solo eso 

Dejo unas imagenes de su daño:

De primero en daño en bg y el 21% de todo eso con escudo de relampago
![wowscrnshot_010314_172150](https://f.cloud.github.com/assets/3101842/1843442/e9096dc4-74d1-11e3-9a1b-e43b3bd58b56.jpg)

Un duelo con un picaro lo deje en 40% solo con escudo de relampago y el totem abrasador 
![wowscrnshot_010314_190934](https://f.cloud.github.com/assets/3101842/1843455/3c1f6b8a-74d2-11e3-9a1c-1cf871675490.jpg)

Escudo de relampago normal 4,5k y critico 7k cuando deberia de ser a lo mucho 2k o 3k

![wowscrnshot_010314_163546](https://f.cloud.github.com/assets/3101842/1843465/73b5017c-74d2-11e3-9eea-a88e4c4166db.jpg)

**Comment by nicerdicer** [comment]
Escudo de relampagos inflige 2.675 con 5.8K SP, y si el chaman es un poco avispado, lo estará renovando continuamente... y mas aun con la frecuencia de ataque de un rogue, la cantidad de veces que golpea en proporción a las veces que le devolverá daño es enorme...
Tampoco estamos teniendo en cuenta el temple del oponente en el primer caso y tambien que el segundo caso es un simple monstruo corriente donde entra todo el daño sin contar reducciones...

**Comment by Ivanlopez-dev** [comment]
Equiliquà. +1 Nicer

"Se supone que rebufear el escudo de relampago era la ultima prioridad del chaman mejora en el offi no era muy importante pero ahora parece prioridad maxima pego alto con solo eso"

Perdona, de dónde has sacado eso del offi? Infórmate mejor anda, que hablar por hablar lo hace cualquiera compañero...

**Comment by F4NT4SM4** [comment]
Escudo de relampago 390+(26.7% SP) pongamos esos 5.8k SP que dices 5800*26.7/100=1548.6+390= 1938.6 es lo que deberia pegar ahora pongamos esos 1938.6 que haga daño un jugador con 4k temple son 40% reducion mas o menos serian 1163.16 lo que recibiria ese pj
pero el escudo de relampago esta haciendo 7k a un objetivo sin reducciones como el mob eso a un jugador con 4k temple serian 4200 cada ataque va recibir ese jugador y si es picaro ya jodio por la velocidad de ataque

http://eu.battle.net/wow/es/forum/topic/2123555830
Segundo comentario ¨el escudo de relampagos es la ultima prioridad en cuanto a usar, renovalo siempre que no tengas nada que hacer.¨ No encontraras mucho tema de esto ya que el escudo de relampago tiene un glifo para que no baje de 3 cargas el escudo de relampago no es una gran prioridad rebufearlo en combate solo rebufearlo cuando no tengas nada que hacer 

Que me dices de los jugadores de la bg ninguno tenia temple?
hice 664k solo con el escudo de relampago y fijate el daño que hicieron mis otros compañeros de la bg hay un pala que hizo casi lo mismo con todos sus ataques es decir mi escudo equivale el daño de otro jugador? D:

**Comment by ghost** [comment]
Se habrá vuelto a bugear. 390+(26.7% SP) y, teniendo en cuenta que el SP de un mejora es el 55% de su AP, para pegar 4537 de hit debería tener:

390 + (0.267_(0.55_AP)) = 4537. => <strong>AP = 28239.7</strong>. No sé cuánto AP suele tener un chamán, pero 28k de base lo dudo.

Eso es la fórmula en bruto, no he tenido en cuenta talento/glifo que pueda aumentar su daño (no sé si lo habrá). Aún así, los 4537 fueron dados sin ningún bufo especial ni nada, es de acuerdo con los datos del Screen de arriba en el que se puede ver que no tiene ningún buf ofensivo ni tótem ni nada, al contrario que en el duel con el pícaro.

Puede que también (o simplemente) esté ignorando temple.

**Comment by Ivanlopez-dev** [comment]
Que está muy bien, también hemos mirado la fórmula nosotros.
Lo único que tengo que decir es que mi escudo de relámpagos núnca ha metido más de 2,5k. a X player con 40% de resilience.
Y esto es a día de hoy y desde que hicimos el duel que te causó pesadillas en Durotar.

**Comment by searum** [comment]
hace bien el daño >_< deja de crys por todo tio y resume tus issues.
