### ISSUE TITLE
[Prospección]Cristal Arcano

### ISSUE THREAD

**Issue by titoalfon** [RoDNet/Bugtracker-Infinium-4.3.4#3055]
Soy minero y joyero full, con mi personaje, pero hace ya varias semanas que no prospectando mineral no sale cristal arcano, supuestamente se obtiene prospectando torio. Y asi era como lo obtenia. Pero en las ultimas semanas no hay manera de que salga cristal arcano. Le he preguntado a otras personas en el server y tienen el mismo problema.

**Comment by Wiinter** [comment]
El cristal Arcano solo se obtiene mineando. http://es.wowhead.com/item=10620#prospecting, prospectando menas de torio solo da diamantes de azeroth, rubi estrella, zafiro azul, esmeralda gigante y ópalo grande

**Comment by Necrofilo** [comment]
Yo fui a farmear torio y en 10 minutos me salieron 2 cristales arcanos sin buscarlos.

**Comment by Compresor** [comment]
Los Cristales Arcanos no se pueden sacar prospectando de ninguna mena. Cierro Issue
