### ISSUE TITLE
Problema con la doble especialización de talentos

### ISSUE THREAD

**Issue by revoltosomix91** [RoDNet/Bugtracker-Infinium-4.3.4#3056]
No puedo aprender la doble especialización de talentos en ningún instructor. Lo he probado con los instructores de Orgrimmar, Lunargenta, Dalaran y ninguno de ellos me lo enseña. Cuando escojo la opción, la conversación con el NPC se buguea y tengo que cerrarla.

Puse un ticket a un MJ y me aconsejó que borrara la carpeta caché. Lo hice en varias ocasiones, pero sigo sin poder aprenderlo, así que me dijo que lo reportase aquí.

**Comment by ghost** [comment]
Prueba a darle a los otros diálogos de los NPCs, muchas veces ocurre que tienen las opciones cambiadas y, al darle a olvidar talentos, a veces te quiere enseñar la doble especialización (o viceversa). Con los taberneros suele pasar igual, "make this inn my home" a veces es que te enseñe sus mercancías.
