### ISSUE TITLE
arenas de zuldrak

### ISSUE THREAD

**Issue by melcalla** [RoDNet/Bugtracker-Infinium-4.3.4#3057]
http://es.wowhead.com/quest=12932/el-anfiteatro-de-la-angustia-yggdras

antes funcionaba , ahora no

**Comment by Compresor** [comment]
Intenta modificar tu reporte conforme las normas, así no será más fácil fixearlo. 
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/, sino tendré que cerrar el issue
