### ISSUE TITLE
[Misión] Monte Hyjal -  Milagro de Aessina

### ISSUE THREAD

**Issue by Monfers** [RoDNet/Bugtracker-Infinium-4.3.4#3058]
![wowscrnshot_010414_175717](https://f.cloud.github.com/assets/6315016/1845348/cc0da5da-7582-11e3-86cf-92d92b56a554.jpg)

La mision "El milagro de Aessina" que se lleva a cabo en monte hyjal no se puede entregar :( me dice que la debo entregar con Hamuul Totem de Runa pero no esta y en esta tauren me sale el signo para entregarla pero no funciona. 

Mision: http://es.wowhead.com/quest=25372/el-milagro-de-aessina#.

Npc: http://es.wowhead.com/npc=39858#screenshots:id=201909

**Comment by Compresor** [comment]
Si que está, pero no vas al lugar adecuado. Mira bien en la pagina de wowhead que has linkeado. En el mapa te pone el sitio correcto donde está.
