### ISSUE TITLE
[Druida] Talento: Herida Infectada (Feral)

### ISSUE THREAD

**Issue by michaelTIIH** [RoDNet/Bugtracker-Infinium-4.3.4#3059]
El talento que deberia de aplicar una enfermadad llamado herida infectada no esta funcionando 

Dicha enfermedad deberia de activarse al usar las skill Triturar, Desvastar, Magullar y Destrozar. al no aplicarse hace dificil el PvP para el druida feral http://es.wowhead.com/spell=48484/heridas-infectadas

Edit 1: Añado información puesto que hace falta especificar que "herida infectada" se aplica algunas veces, siempre se aplica  en NPCs, pero por lo menos en Campos de Batalla no se esta aplicando, otro usuario a dicho que en duelos si se aplica pero en arenas no

Edit 2: Crei que estaba arreglado, ya que en medio de una BG herida infectada se estaba aplicando correctamente, pero de un momento a otro dejo de aplicarse, tal parece que reloguear lo soluciona en ocasiones, pero sin previo aviso sigue dejando de funcionar

**Comment by 50megas** [comment]
si lo esta aplicando a todas, menos a devastar http://es.wowhead.com/spell=6785/devastar

**Comment by 50megas** [comment]
vale rectifico esos datos era con dumys ,pero en arenas no esta saltando siempre nose por que,en duelos tampoco salta, haveces solo cuando quiere, hoy en 2 arenas a un roge y sacer no les salia el bufo de ralentizar y no era por cds

**Comment by efectokoleos** [comment]
arreglado
