### ISSUE TITLE
[Mago] Barrera de hielo

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.3.4#306]
Barrera de hielo: http://old.wowhead.com/spell=11426
Tiene una absorción menor a la correcta.
Esta spell tienen una absorción base de 8069 pts, el problema es que no se modifica con el poder con hechizos ni con el glifo (debería) . 
(Glifo de barrera de hielo)
Que no encontré el id pero aumenta 30% la cantidad absorbida, parece que como la absorción no se puede modificar el glifo es inutil.

**Comment by searum** [comment]
fix
