### ISSUE TITLE
Bug Tol Barad: Entrada

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3061]
Al iniciar la batalla por Tol Barad, la puerta de entrada al campo de batalla tendría que quedar cerrada impidiendo el acceso a posibles jugadores que quieran entrar de forma no legal y de esa forma desigualar los jugadores de cada bando.

 Dejo imagen:
![wowscrnshot_010514_123229](https://f.cloud.github.com/assets/6006693/1846520/14c2c9b8-7600-11e3-94f1-9e40f6eb8cd6.jpg)

**Comment by Dekadencee** [comment]
Me comentan que la puerta permanece abierta en el oficial, de hecho hay un vídeo donde se ve como el player entra y sale todo el rato por la puerta.

**Comment by Dekadencee** [comment]
http://www.youtube.com/watch?v=ONzlsQzwaJo

Reino EU - Sanguino
