### ISSUE TITLE
Tol Barad: algo raro en las torres

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3062]
Lexintor y yo hemos estado echando el ojo a las torres de Tol Barad y parecen tener algo raro, lo que hemos pensado que es más posible es que haya una torre bajo la otra, que crean un efecto de gelatina. Como no sé del todo qué es lo que pasa, dejo una imágen del efecto que hace (va cambiando de color cuando te mueves) y vosotros podréis mirar qué es lo que pasa.

 Imagen:
![wowscrnshot_010514_123541](https://f.cloud.github.com/assets/6006693/1846543/fddff7f0-7601-11e3-917d-874ec021f4eb.jpg)

**Comment by searum** [comment]
si es que algun gracioso las spawneo por db xDDD luego las quito
