### ISSUE TITLE
Bug Tol Barad: tiempo hasta la batalla

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3064]
Cuando vas a anotar y cuando estás anotado para la batalla por Tol Barad, debería aparecer una cuenta atrás especificando el tiempo que falta hasta el inicio de la batalla, sin embargo ni en el panel para anotar ni en el icono de estar anotado aparece.

 Imagen:
![sin ttulo](https://f.cloud.github.com/assets/6006693/1846573/96f73388-7605-11e3-93bd-fd9be7216c19.png)

Debería aparecer algo parecido a esto:
![d0ffe5138f2df74ff24b4e4f69a152d1](https://f.cloud.github.com/assets/6006693/1846574/bad0bc2a-7605-11e3-9f67-c29fa6e6bb0a.png)

**Comment by Dekadencee** [comment]
Fixed
