### ISSUE TITLE
migracion

### ISSUE THREAD

**Issue by 111baby111** [RoDNet/Bugtracker-Infinium-4.3.4#3066]
ayer migre un guerrero de lichking todo salio bien hasta que me conecte y no tenia nada y los artículos no me han llegado por favor ayúdenme.
gracias

**Comment by ghost** [comment]
Esto es un bugtracker, no un foro de ayuda. Leete las normas antes de postear. 

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/wiki/Gu%C3%ADa:-%C2%BFC%C3%B3mo-reporto-un-Bug-(Fallo)%3F

Tu mensaje debería ir en el foro: https://www.reignofdarkness.net/wow/forums/

Léete esto acerca de las migraciones y en los fallos de los objetos:
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/166-acerca-de-las-migraciones-fallidas/

Dale al botón "Close" de más abajo por favor.

Gracias!
