### ISSUE TITLE
[Mision] La Venganza del Embalsamador

### ISSUE THREAD

**Issue by Raphaell94** [RoDNet/Bugtracker-Infinium-4.3.4#3068]
Cuando sale la abominación y la matas no te cuenta como que has asesinado a la abominacion.

**Comment by ghost** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/wiki/Gu%C3%ADa:-%C2%BFC%C3%B3mo-reporto-un-Bug-(Fallo)%3F

**Comment by Compresor** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
