### ISSUE TITLE
[Mago] Glifo de reflejo exacto

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.3.4#307]
Glifo de reflejo exacto: http://www.wowhead.com/item=45739
No modifica el hechizo que lanzan los clones dependiendo de la especialización que tengamos, o sea siempre castean descarga de escarcha.

**Comment by ghost** [comment]
No se a los demás, pero a mi en los últimos dos duelos que he echado se me ha gastado el CD y ni han llegado a salir las copias.

Reafirmo: No salen las copias nunca.

**Comment by Kiritoo** [comment]
Fix
