### ISSUE TITLE
[Druida] Talento: Carga Feral ( Rama Feral, Forma felino)

### ISSUE THREAD

**Issue by michaelTIIH** [RoDNet/Bugtracker-Infinium-4.3.4#3070]
La skill carga feral de forma felino (http://es.wowhead.com/spell=79830/carga-feral-felino) deberia de poder usarse en sigilo, por el contrario, al usar la skill señalada se desactiva el modo de sigilo

**Comment by ghost** [comment]
http://wow.freakz.ro/spells.php?spell=79830

No debe romper sigilo al usarse.

**Comment by searum** [comment]
fix
