### ISSUE TITLE
[BUG] Disparo de quimera

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#3071]
El disparo de quimera está bastante subido en cuanto a daño y sanación realizados.
![wowscrnshot_010614_123942](https://f.cloud.github.com/assets/6329431/1850197/9952e2c6-76c8-11e3-80cb-2f1cc43facfd.jpg)
Con cds le metí 41k de crítico.

![wowscrnshot_010614_124446](https://f.cloud.github.com/assets/6329431/1850202/b2a46c04-76c8-11e3-8f86-a8746622cca7.jpg)
Sin cds, 21k sin crítico

![wowscrnshot_010614_124457](https://f.cloud.github.com/assets/6329431/1850203/c4901724-76c8-11e3-88b9-3494e6c108e9.jpg)
Sin cds, 30k de crítico

![wowscrnshot_010614_124710](https://f.cloud.github.com/assets/6329431/1850204/cd3b46b4-76c8-11e3-9021-16e4509a80fa.jpg)
15k de sanación de quimera, lo que supondría un 10% de la vida total, cuando quimera te devuelve sólo el 5% de la salud.

Cabe mencionar que Sclerosis tiene 4274 temple, lo que le reduce el daño recibido en un 41.89%

Y bueno, aquí unas risas con un dummy lvl 85:

![wowscrnshot_010614_130332](https://f.cloud.github.com/assets/6329431/1850248/be5d85ec-76ca-11e3-8fab-d03c1e0db442.jpg)

**Comment by Necrofilo** [comment]
Con esta spell se han pasado bastante, mientras que han dejado al survival con daño de la 3.3.5a :S

**Comment by searum** [comment]
fix
