### ISSUE TITLE
[Brujo] Quemar alma: Círculo demoníaco: Teletransporte

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3073]
<strong>Descripción:</strong> Al usar la combinación Quemar alma (74434) + Círculo demoníaco: Teletransporte (48020) debería dar un bufo extra que debería aumentar la velocidad un 50% durante 8s.

<strong>Problema:</strong> Se ha bugeado, ahora al usar la combinación Quemar alma (74434) + Círculo demoníaco: Teletransporte (48020) no te da el bufo correspondiente que debería aumentar la velocidad un 50% durante 8s. Es un teletransporte normal pero que consume el efecto de quemar alma.

Quemar alma: http://wow.freakz.ro/spells.php?spell=74434
Circulo demoniaco: Teletransporte: http://wow.freakz.ro/spells.php?spell=48020&name=demonic-circle-teleport

**Comment by searum** [comment]
miratelo bien porque a mi me va perfecto.

**Comment by ghost** [comment]
Pues a mi no me funciona. Se me gasta el bufo de quemar alma y no pasa nada más.

**Comment by ghost** [comment]
![wowscrnshot_010714_022052](https://f.cloud.github.com/assets/3788004/1855856/3a436012-773b-11e3-9b8b-c858ac8e8502.jpg)
![wowscrnshot_010714_022057](https://f.cloud.github.com/assets/3788004/1855857/3a5bceea-773b-11e3-9d90-5db5954da2dd.jpg)
