### ISSUE TITLE
Bug Tol Barad: Victoria / Derrota (Baradin no cambia).

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3074]
Tol Barad se ha habilitado hace 2 días, y ya se puede jugar para conseguir el control, y así poder hacer Bastión de Baradin.

 Problema: Gane la facción que gane, Tol Barad siempre queda bajo el control de la alianza, con lo que los hordas nunca pueden hacer la banda ''Bastión de Baradin''.

 Agradecería la solución de este nuevo problema, ya que no podemos gastar el save semanal de Bastión de Baradin.

 Gracias de antemano y felicidades por todos los arreglos de hoy.

**Comment by searum** [comment]
Pues me da a mi que el bug lo tienes tu porque... ayer esto iba bien y fue controlado por la horda todo el dia.

**Comment by Necrofilo** [comment]
Por eso mismo, ayer y hoy ha estado Tol Barad en poder de la horda, pero cuenta como si estuviera de parte de la Alianza, y al entrar en Bastión de Baradin automáticamente nos saca fuera (estuvimos probando de entrar varios de la raid, así que no será solo cosa mia) :S

**Comment by paellaencol** [comment]
Que raro, yo ayer como horda pude entrar estando tol barad en poder de la horda

**Comment by Necrofilo** [comment]
Mañana volveremos a intentar entrar, me aseguraré de capturar Tol Barad y si aún así no deja vendré a decir algo, de lo contrario cerraré el post y todo aclarado...
