### ISSUE TITLE
[Brujo] Mordedura de las Sombras (Manafago)

### ISSUE THREAD

**Issue by nicerdicer** [RoDNet/Bugtracker-Infinium-4.3.4#3075]
Mordedura de las Sombras del manafago ( http://wow.freakz.ro/spells.php?spell=54049 ) Inflige 1 + (1.228 \* (SP \* 0.5))  esta formula es la del ataque base, la cual es correcta.
El problema, cuando a la victima le atacamos con hechizos de daño en el tiempo, el daño de la Mordedura se amplia un 30% por cada efecto de daño en el tiempo en el objetivo (en el caso del brujo afli, los 3 mas básicos Corrupción - Agonia - Afli.. Inestable). Este crecimiento del 30% no esta bien, esta dando aprox. un 50% mas de daño.
![mordebug1](https://f.cloud.github.com/assets/4660334/1853573/58b8dc02-770e-11e3-8e4a-38371cc3c168.png) Aqui vemos un critico de 8.488, según Dr.Damage, el critico es de 10K pero bueno, por no llenar esto de screens no he querido hacer uno del ataque basico, el cual esta bien.. (unos 5.300 de daño). Hasta aqui todo bien.
![mordebug1](https://f.cloud.github.com/assets/4660334/1853811/759887b0-7712-11e3-949e-175f4b1fedaa.png)
 En este caso, se deberia haber aplicado el 30% extra de daño por la presencia de [Corrupción] en el objetivo, y según el tip de la habilidad y Dr.Damage es correcto, sin embargo el daño por el ataque basico (9.501) nos dice otra cosa.
![mordebug2](https://f.cloud.github.com/assets/4660334/1853778/2490e682-7712-11e3-99e5-229840cca8fc.png)
En este caso, se deberia haber aplicado el 60% extra de daño por la presencia de [Corrupción]-[Terror de Agonia] en el objetivo, y según el tip de la habilidad y Dr.Damage es correcto, sin embargo el daño por el ataque basico (14.394) nos dice otra cosa.
![mordebug3](https://f.cloud.github.com/assets/4660334/1853819/a916497e-7712-11e3-8add-b332ab931a13.png)En este caso, se deberia haber aplicado el 90% extra de daño por la presencia de [Corrupción]-[Terror de Agonia]-[Aflicción Inestable] en el objetivo, y según el tip de la habilidad y Dr.Damage es correcto aprox., sin embargo el daño por el ataque basico (20.367) nos dice otra cosa.

Vemos asi como, aproximadamente, en todos los casos el daño base supera al indicado por el tip y el Dr.Damage por el doble.

**Comment by ghost** [comment]
No entiendo muy bien lo que pones...Dices que el daño es más alto del que debería, ¿no? Por ejemplo en la última screen hace 20.3k de daño normal y eso es lo que debería meter pero de crítico no?

Creo que el daño lo han ajustado, que no está completamente arreglado aún.

Saludos!

Edito: He hecho cálculos con la fórmula y parece que sí, suponiendo que el SP de tu brujo es 8.143 y sustituyendo en la fórmula...: 1 + (1.228 \* (SP \* 0.5)) => Hit normal con 3 dots contando talento y spec en sombras: 10451.7 de daño sombras, 20903.4 de crítico.

**Comment by searum** [comment]
Por dios!!!! De verdad hace falta hacer un issue asi???? Decir el fallo, resumirlo en 2/3 lineas y por mi no pongais ni fotos porque es que asi no se entiende nada...

Se que lo haceis con la mejor intención pero.. hacerme el favor que no voy a perder mi tiempo leyendo todo el tocho y viendo 20 fotos xD

Resumelo en otro issue por favor!

**Comment by ghost** [comment]
Resumido en un nuevo.
