### ISSUE TITLE
Bastión del Crepúsculo: Valiona y Theralion (Llamas devoradoras = 86840)

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3077]
En la primera fase cuando Valiona está en el suelo, usa una habilidad (Llamas devoradoras http://cata.openwow.com/spell=86840) cuya acción es quedarse 2,5 segs casteando un aliento que lanzará hacia la dirección a la que apunta.

 Problema: No lanza el aliento hacia donde en un principio apunta, se gira hacia donde están todos y causa algún tipo de bug visual, porque no se sabe hacia donde está lanzando el hechizo.

 Dejo una captura de pantalla donde se ve que se gira hacia la raid mientras usa el aliento, pero la vida se la baja al tanque (de aquí lo del bug visual).

![wowscrnshot_010614_214654](https://f.cloud.github.com/assets/6006693/1854343/f91a4292-771a-11e3-8665-b50b9b97f741.jpg)

 Espero que sirva como soporte suficiente para saber que está pasando con este boss :S

PD: hay veces que apunta al tanque y baja a toda la raid.

**Comment by Monleon** [comment]
Es únicamente un bug visual, aunque se gire, el daño lo recibe el objetivo que tuviese el 100% de amenaza.
