### ISSUE TITLE
Bastión del Crepúsculo: Consejo de Ascendientes (Helar)

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3078]
En este encuentro, Feludius tiene una habilidad llamada ''Helar'' cuya acción es lanzar un área que no se puede cortar a todos los jugadores que se encuentren en la sala, cuanto más lejos te encuentras menos daño te causa, pero sin embargo estando al lado te causa un daño mortal.

 Problema: Helar no está respetando el rango de daño, está infligiendo un daño mortal (instant kill) a todos los jugadores de la sala, dejo aquí una imagen del registro de combate en el cual sale mi daño recibido estando en la otra punta de la sala (114k de daño por Escarcha. (60000 Resistido) (25k sobrecapacidad):

![wowscrnshot_010614_220952](https://f.cloud.github.com/assets/6006693/1854763/a13ae66a-7721-11e3-9245-6eab2e04501f.jpg)

No creo que influya el hecho de estar 2 casters/rango pegando a Ignacius con daño moderado para que bajaran los 2 bosses por igual.

 Edit: Papi también ha muerto, pero en la imagen sale vivo porque es holy y al morir aparece en ángel guardián.

**Comment by Pegasu5** [comment]
Vale aún así se puede hacer perfectamente la raid sin wipear, aunque es un bug muy grande.

**Comment by Necrofilo** [comment]
Creo que no te enteras, con esa spell mata a TODA la raid al instante, ¿como piensas tirar el boss con el instant kill de esa spell sin respetar área?

**Comment by Monleon** [comment]
Ya reduce daño según distancia
