### ISSUE TITLE
[Mago] Orbe de pirofrío

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.3.4#308]
Prbe de pirofrío: http://old.wowhead.com/spell=84727
El orbe de llamas (http://old.wowhead.com/spell=82731) Si se trasforma en orbe de pirofrío pero ocurre el mismo problema del orbe de llamas, pega poco, pega 250 más o menos cuando debería pegar 1170 más o menos por tick.
Además el orbe de pirofrío no genera dedos de escarcha (http://www.wowhead.com/spell=112965/fingers-of-frost)  que si debería.

**Comment by searum** [comment]
pega lo que tiene que pegar... y si no pues dame pruebas de cuanto tendria que pegar.
