### ISSUE TITLE
[Mago] Reflejo exacto

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3082]
http://wow.freakz.ro/spells.php?spell=55342

Problema: Salen 6 copias en lugar de 3. Cada una sale doble.

**Comment by Necrofilo** [comment]
Creo que es un bug visual.

**Comment by ghost** [comment]
Nop, las 6 castean.

**Comment by searum** [comment]
QUIERES MIRAR EL PUTO CHANGELOG PESAO

**Comment by searum** [comment]
mucho mejor porque vamos eres mazo de brasas tronco
