### ISSUE TITLE
[Brujo] Quemar alma: Círculo demoníaco: Teletransporte

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3083]
<strong>Descripción:</strong> Al usar la combinación Quemar alma (74434) + Círculo demoníaco: Teletransporte (48020) debería dar un bufo extra que debería aumentar la velocidad un 50% durante 8s.

<strong>Problema:</strong> Al usar la combinación da el bufo correspondiente que debería aumentar la velocidad un 50% durante 8s. Es un teletransporte normal pero que consume el efecto de quemar alma.

Quemar alma: http://wow.freakz.ro/spells.php?spell=74434
Circulo demoniaco: Teletransporte: http://wow.freakz.ro/spells.php?spell=48020&name=demonic-circle-teleport

Pruebas: 
![wowscrnshot_010714_022052](https://f.cloud.github.com/assets/3788004/1855856/3a436012-773b-11e3-9b8b-c858ac8e8502.jpg)
![wowscrnshot_010714_022057](https://f.cloud.github.com/assets/3788004/1855857/3a5bceea-773b-11e3-9d90-5db5954da2dd.jpg)

**Comment by searum** [comment]
ASMAN TRONCO ERES UN PUTO PESAO TE JURO QUE TE VOY A BANEAR EH me tienes ya cansadito..
