### ISSUE TITLE
[Hechizos/Talentos][Caballero de la Muerte] Golpe Letal

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3084]
Buenas.
• Nombre: Golpe Letal
• Enlace: http://es.wowhead.com/spell=49998
• Descripción: Lanza un poderoso golpe que te sana un 20% del daño que has sufrido durante los ultimos 5s (un minimo de 7% de tu salud maxima) y tambien inflije un 150% de daño con arma mas 497p de daño aun enemigo si el ataque tiene exito
• Problema: Aparecen 2 sanaciones de igual cantidad al usar la habilidad una vez.
• Observaciones: Lo hice con un Caballero de la Muerte con especialización sangre.
Gracias!!

**Comment by searum** [comment]
a ver no me dais ni tiempo a  compilar los fixes..
