### ISSUE TITLE
[Chaman Mejora] Arma Voragine

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3085]
Nombre: Arma Voragine
ID: 51528/51529/51530
Enlace: http://wow.freakz.ro/spells.php?spell=51528
Descripcion: Cuando Infliges daño con un arma cuerpo a cuerpo, Tienes la probabilidad de reducir el tiempo de lanzamiento de tu siguiente Descarga de relampago, Cadenas de relampago, maleficio o de cualquier hechizo de sanacion un 20% se acumula hasta 5 veces. Dura 30s

Problema: La Probabilidad esta muy alta actualmente se puede llegar a 5 cargas de un toke

**Comment by Kiritoo** [comment]
Arreglado, estaba saltando con hechizos que no debía saltar.
