### ISSUE TITLE
Logros de Arqueologia - Lo tenia en la mano.

### ISSUE THREAD

**Issue by Danieke** [RoDNet/Bugtracker-Infinium-4.3.4#3086]
Buenas, este es el logro http://es.wowhead.com/achievement=4854, cuando se descubre algun artefacto poco comun el logro no se da, por ende no se otroga el titulo http://es.wowhead.com/title=189. Puedo suponer que pasa lo mismo con http://es.wowhead.com/achievement=4855 y http://es.wowhead.com/achievement=4856, que forman parte de la misma cadena.

**Comment by Compresor** [comment]
#2565 Duplicado

Cierro
