### ISSUE TITLE
[Misión] Corona de Hielo - Una espada de Campeón

### ISSUE THREAD

**Issue by lexintor** [RoDNet/Bugtracker-Infinium-4.3.4#3088]
Una espada de campeon, si besas a una rana random sale la mujer correspondiente lo que no sale es la espada 

Mision: http://es.wowhead.com/quest=13768

Objeto que falta: http://es.wowhead.com/item=44981#.

**Comment by Compresor** [comment]
#2999 Seguimos desde el otro
