### ISSUE TITLE
Tol Barad: arreglo equivocado

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3089]
Cuando acaba la batalla por Tol Barad, la banda no se tiene que disolver, de hecho en el ofi se aprovechaba que se quedaba la banda hecha para acabar con los de la facción contraria y farmear los últimos puntos de honor, o incluso buscar gente ahí mismo para hacer Bastión de Baradin.

-Problema: Al acabar batalla por Tol Barad se disuelve el grupo de banda.

 Era bastante divertido en el oficial jugar al escondite con la entrada de Tol Barad para fastidiar a la facción que perdía.

**Comment by searum** [comment]
vale, pero lo he puesto asi porque se bugea la banda y no te deja salir.. asi que de momento hasta que arregle ese fallo asi se queda por muy divertido que fuera xD sorry!

**Comment by Necrofilo** [comment]
No problem, entiendo
