### ISSUE TITLE
[Druida]Forma de lechúcico lunar

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#309]
Forma de lechúcico lunar: http://es.wowhead.com/spell=24858 

 Lo unico que si funciona de esta forma es es "El druida no puede lanzar hechizos de sanación durante el cambio de forma". ya que al usarlo se saca la forma de lechucido jaja.
No aumenta el daño un 10%, ni el daño recibido y tampoco la celeridad.

Un saludo.

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/16

**Comment by searum** [comment]
funciona correctamente >_<

**Comment by crowel** [comment]
Si eso acabo de ver, que bien, lleva un mes el reporte.
Saludos.
