### ISSUE TITLE
[Brujo] Invocar Guardía Apocalíptico

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#3091]
ID: 18540

Bug: Invoca a un Guardia apocalíptico (http://es.wowhead.com/npc=11859, como debe ser), pero ese guardia debería usar Descarga de fatalidad (ID=85692) para atacar, en vez de eso ataca cuerpo a cuerpo.

Además debería atacar a los objetivos afectados por el Terror de agonía(ID=980) o el Terror de fatalidad(ID=603) del brujo, pero ataca solo a quien se le tenga como objetivo al invocarlo o al que le pegue.

**Comment by searum** [comment]
fix.. me falto el scriptname XD
