### ISSUE TITLE
[Maestría] Druida - Armonía

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#3094]
La maestría del druida restauración no está funcionando la segunda parte de la misma, la primera ahora funciona correctamente con el arreglo de ayer. #3015 

https://f.cloud.github.com/assets/3537253/1798500/32ef6ff2-6b53-11e3-9571-1c2a55b4ec06.png

Aquí pongo tambien el id del buffo que se debe activar de la maestría tras realizar las sanaciones directas.
Harmony: http://cata.openwow.com/spell=100977

Estas son las sanaciones directas con las que se debe activar.
Nutrir 50464
Recrecimiento 8936
Toque de sanacion 5185

Gracias y un saludo.

**Comment by Kiritoo** [comment]
Arreglada, falta compilar.
