### ISSUE TITLE
[Misión] Tu nuevo yo

### ISSUE THREAD

**Issue by sarder97** [RoDNet/Bugtracker-Infinium-4.3.4#3096]
Nombre: Tu nuevo yo
enlace: http://es.wowhead.com/quest=14110
Descripción: Cómprale una cadena de oro lustrosa a Gappy Dienteplata, un atuendo pistonudo a Szabo y unas gafas de sol chulas a Missa Mercadillo en la Calle del Timo.
Problema: Cuando hablas con alguno de los tres,no puedes comprarle nada, tan solo te pone un texto(por ejemplo el de Gappy: ¡Esa cadena de oro es tan gruesa como tu madre!) y no te pone nada mas.

**Comment by ghost** [comment]
Reparada.
