### ISSUE TITLE
[Mago Frost] Buff Dedos de escarcha 

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3097]
Id del talento http://wow.freakz.ro/spells.php?spell=83074
Id del buff http://wow.freakz.ro/spells.php?spell=44544

Problema: Al tener una carga de Dedos de Escarcha (44544) la habilidad Lanza de hielo http://wow.freakz.ro/spells.php?spell=30455 no está actuando como si el objetivo estuviera congelado (cuando el objetivo está congelado "lanza de hielo" hace el doble de daño, y además con el buffo de "dedos de escarcha" hace un 25% de daño extra).

Faltan esos multiplicadores al tener el buffo (44544), porque el daño de lanza de hielo en el resto de casos es el correcto

**Comment by searum** [comment]
fix
