### ISSUE TITLE
[DK] Golpe Letal

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3099]
Nombre: Golpe letal
ID: http://wow.freakz.ro/spells.php?spell=49998

Descripcion: Unleash a powerful strike that heals you for 20% of the damage you have sustained during the preceding 5 sec (minimum of at least 7% of your maximum health), while also dealing 150% weapon damage plus 330 to an enemy if the attack is successful.

Problema: Tiene el daño muy alto estando de tanke en mazmorra o raid supero a los dps con una gran diferencia

Dejo unas imagenes sacando 93k al dummy sin cd
![wowscrnshot_010714_130146](https://f.cloud.github.com/assets/3101842/1861538/a1f7380e-77c3-11e3-83e2-06069a4f97e5.jpg)

![wowscrnshot_010714_130528](https://f.cloud.github.com/assets/3101842/1861541/b0e5885c-77c3-11e3-9c9e-410ac40ddcc8.jpg)

**Comment by 50megas** [comment]
yo esta mañana sacaba 108 aun dumy, luego me puse el glifo que me faltaba y meto 160k-180k a un dumy de critico

**Comment by F4NT4SM4** [comment]
el glifo tambien esta bug solo deberia de aumentarte un 40% si tienes el poder runico full
pero aumenta los 40% directamente sin contar el poder runico

**Comment by Kiritoo** [comment]
Si con el glifo ocurre un fallo reportalo aparte, solo un issue por bug ..

**Comment by searum** [comment]
FIX!

**Comment by F4NT4SM4** [comment]
el glifo ya esta reportado hace tiempo https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2159
:p
