### ISSUE TITLE
No hay filones!!

### ISSUE THREAD

**Issue by Devilcray** [RoDNet/Bugtracker-Infinium-4.3.4#31]
No hay filones de Elementium en Tierras Altas Crepusculares no me sale ningún filón y me lo he recorrido de arriba abajo... curioso bug xD

**Comment by SherBlader** [comment]
Puede ser bug, o puede ser que aun no los ves porque no se ha actualizado todo

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/12

Tambien pasa lo mismo en Uldum.

**Comment by lamaza** [comment]
Yo no creo que sea un bug, sino que los gm no lo han puesto. Yo si pude minar pirita y elementium en Uldum.
