### ISSUE TITLE
[Druida] Rayo solar

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#310]
Hola añado, con todos mis respetos hacia @villarta91 que en el post escribio este bug, refiriendos al siguiente hechizo.

RAYO SOLAR http://es.wowhead.com/spell=78675 Afecta también al tamaturgo al lanzarlo y durante el tiempo que dura el efecto, cuando debería afectar solo a los enemigos debajo del hechizo.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/16 Aqui podeis comprobar la foto y el reporte original.

Un saludo.

**Comment by searum** [comment]
fix

**Comment by crowel** [comment]
Hola, nosé si está aplicado el fix.
Queria comentar que ya no silencia a uno mismo, pero tampoco al objetivo ^^
Un saludo.

**Comment by searum** [comment]
no esta aplicado todavia

**Comment by crowel** [comment]
Hola después del fix puedo comprobar que no se silencia al objetivo dentro del rayo solar.
Un saludo y gracias. @searum

**Comment by redneo** [comment]
fixed el silenciar.

**Comment by crowel** [comment]
Hola queria comentar que la spell ya silencia :+1: .
Lo que me fijé que el silencio desaparece a los 4-5 segundos, debiendo estar durante 10 sec de tiempo base, o 15 segundos con el glifo puesto.

Un saludo.
