### ISSUE TITLE
[Mazmorras/Bandas][NPC's/Mobs][Prueba del Cruzado] Anub'arak

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3101]
Buenas.
• Nombre: Anub'arak
• Enlace: http://es.wowhead.com/npc=34564
• Descripción: Este PNJ se puede encontrar en Prueba del Cruzado
• Problema: No se puede iniciar el combate contra Anub'arak.
• Observaciones: El Boss aparece hostil pero no se lo puede atacar ni dañar de ninguna forma.
Gracias!

**Comment by redneo** [comment]
Solo pasa en normal, no?

Arreglado
