### ISSUE TITLE
[Cazador] Activación de las trampas desde el momento de su colocación

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3103]
Enlace de las trampas:
http://es.wowhead.com/spell=1499 Trampa congelante.
http://es.wowhead.com/spell=34600 Trampa con culebras.
http://es.wowhead.com/spell=13809 Trampa de hielo.
http://es.wowhead.com/spell=13813 Trampa explosiva.
http://es.wowhead.com/spell=13795 Trampa de inmolación.
http://es.wowhead.com/spell=77769 Lanzador de trampas

Problema: desde que una trampa es colocada hasta que pueda saltar (por ser pisada por un enemigo) debe haber un segundo de espera entre medio.
Sin embargo actualmente las trampas están saltando instant, nada más ponerla a los pies de un jugador se activa, cuando debería poder activarse tras pasar 1seg desde su colocación (esto en los vídeos en youtube se puede apreciar bien)

**Comment by Pegasu5** [comment]
Yo pensaba que era todo lo contrario a este post, y que estaba arreglado ya que en los videos a mi parecer así era.

P.D: http://www.youtube.com/watch?v=xfHzcTCOOPo

**Comment by addict90** [comment]
pues, no se si estaré viendo el mismo vídeo que tu, pero claramente se ve el tiempo entre que coloca la trampa y el enemigo pasa por encima, pasan mas de 1 seg mínimo, así que no se que cuentas :S 
el autor del issue tiene razón.

**Comment by Jhovanni** [comment]
Habrá que cerrar el post pues si está bien el tiempo de activación de las trampas. Es fácil notar en el juego como se vé la trampa caer (de hecho no se ve la trampa en si, sino el lanzamiento) y se activa después.

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3763
