### ISSUE TITLE
[Brujo] Sanación por parte de Armadura Vil en la rama de Destrucción

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3105]
Nombre: Hechizo Armadura Vil

Enlace: http://wow.freakz.ro/spells.php?spell=28176

Lo que está pasando en la rama de destrucción es que no devuelve la sanación. Debería devolver el 6% de cualquier daño que se haga, ya sea con inmolar, maldiciones o el hechizo que sea.

Lo he comprobado y solo me esta pasando en esta rama, en aflicción por ejemplo si que funciona.

Os pongo fotos del daño, la descripción y también del registro de combate para que veáis que no se sana.

![wowscrnshot_010814_113630](https://f.cloud.github.com/assets/3939699/1867546/6413f11a-7851-11e3-8cb1-5b3f06460099.jpg)

![wowscrnshot_010814_113802](https://f.cloud.github.com/assets/3939699/1867522/0bbb88b6-7851-11e3-9c3b-2b9ff3743711.jpg)

![wowscrnshot_010814_113746](https://f.cloud.github.com/assets/3939699/1867529/1e7f66ca-7851-11e3-89b0-045a29318e20.jpg)

![wowscrnshot_010814_113654](https://f.cloud.github.com/assets/3939699/1867533/2aac1eac-7851-11e3-80be-4af8b2d19058.jpg)

Un saludo y gracias

**Comment by Kiritoo** [comment]
NO PROBAR EN  LOS DUMMYS!! te has molestado en probar en un NPC o en un BOSS?? 
Esto funciona correctamente, cierro.
