### ISSUE TITLE
[Brujo] Daño de Mordedura de las Sombras del Manafago con dots

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3106]
Hechizo: Mordedura de las sombras

Enlace: http://wow.freakz.ro/spells.php?spell=54049

El daño base esta bien ajustado, lo que está pasando es que al poner dos maldiciones (corrupción y terror de agonía por ejemplo) el daño sube de forma brutal. Alcanzando daños que no debería. Paso a explicarme.

La fórmula para el daño del manáfago es esta [1 + (1.228 \* (SP \* 0.5))]; además se le añade un 30% de daño por cada dot que tenga el brujo puesto en el enemigo.

Pongo el ejemplo con mis parametros: aplico la fórmula [1+(1,228_(9075_0,5))]= 5573,05 Este sería el daño base de mi mánafago aplicando la mordedura.

Ahora bien por cada dot este daño aumentaría un 30% sobre esos 5573,05, es decir, con un dot sería [5573,05+(5573,05_0.30)]=7244,965; con 2 dots sería [5573,05 + (2_(5573,05*0,3))]= 8916,88.

Un saludo y gracias

**Comment by searum** [comment]
Quita las imagenes son useless, tan solo necesito una BREVE descripción del problema en 2/3 lineas como mucho.

**Comment by Drogoth2** [comment]
ok, ya están quitadas searum

**Comment by searum** [comment]
fix
