### ISSUE TITLE
[Picaro-Sutileza] Maestro de la sutileza 31223

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#3107]
Nombre: maestro de la sutileza

Link: http://es.wowhead.com/spell=31223

Descripcion:
Los ataques realizados mientras estás en modo sigilo y durante los 6 s posteriores a abandonar el modo sigilo infligen un 10% extra de daño.

Problema: no esta funcionando nada, ni el bufo que deberia de poner , ni el 10% de daño extra

**Comment by searum** [comment]
fix
