### ISSUE TITLE
[talento-picaro] exterminar-58426

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#3108]
Nombre: Exterminar

Enlace: http://es.wowhead.com/spell=58426/exterminar

Descripcion:
 Mientras estás en sigilo y durante 20 segundos después de que se desactive el modo sigilo, regeneras un 30% de energía extra.

Problema: no esta funcionando nada, ni el bufo ni la regeneración de energia

**Comment by searum** [comment]
fix

**Comment by dylanvindas** [comment]
acabo de comprobar y aun no funciona, arreglar por favor.

**Comment by Overseer101** [comment]
............... este post llevaba cerrado un año...a ver si nos fijamos....
