### ISSUE TITLE
[Dk]  Parasito de sangre.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#3113]
Nombre: Parásito de sangre.
Rama: Sangre
Id:  49542
Link: http://wow.freakz.ro/spells.php?spell=49542

Descripción:  Tus ataques cuerpo a cuerpo tienen un 10% de probabilidad de engendrar un gusano de sangre. El gusano de sangre ataca a tus enemigos y se atiborra de sangre hasta que revienta para sanar a los aliados cercanos. Dura un máximo de 20 s.

Problema: Desaparecen al llegar a 9 cargas,con lo que no llegan a explotar.

**Comment by searum** [comment]
fix
