### ISSUE TITLE
[Dk] Muerte y descomposición.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#3114]
Nombre: Muerte y descomposición.
ID: 43265
Link: http://wow.freakz.ro/spells.php?spell=43265

Descripción: Corrompe el suelo que selecciona el caballero de la Muerte, lo que inflige 45 (+ 6.4% of Attack power) p. de daño de las Sombras cada segundo a los objetivos que permanecen en el área durante 10 s.

Problema: Se vuelve como un aura al rededor del dk,no inflige daño en el area aunque ponga debuff.
Aquí ejemplo visual: 
1. Los que están en el área: http://kn3.net/374DE2954CBJPG.html
2. Los que están a mi al rededor: http://kn3.net/3265FC8FAC9JPG.html

**Comment by searum** [comment]
fix
