### ISSUE TITLE
[Dk] Infusión de sombras.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#3115]
Nombre: Infusión de sombras.
Rama: Profano
ID: 49572
Link:  http://wow.freakz.ro/spells.php?spell=49572

Descripción: 
Al lanzar con éxito tus Espirales de la muerte potencias a tu necrófago activo, lo que aumenta el daño que inflige un 6% durante 30 s. Se acumula hasta 5 veces.

Problema:  Al llegar a 5 cargas el buff desaparece de la pet y te sale "Inmune" a el buf de daño que deberia salir al usar espiral.

Imagen: http://kn3.net/40FCCF6415CJPG.html

**Comment by searum** [comment]
hace falta abrir 3 issues para una misma spell? los cierro juntalos en 1
