### ISSUE TITLE
[Dk]  Infección pertinaz.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#3117]
Nombre:  Infección pertinaz.
Rama: Profano.
ID:  81339
Link:  http://wow.freakz.ro/spells.php?spell=81339

Descripción: Cuando un enemigo disipa enfermedades,tienes un 100% de probabilidad de activar una runa de escarcha si se elimino Fiebre de escarcha, o una runa profana si se elimino Peste en la sangre.

Problema: El problema es que no esta cargando recargando las runas como dice.

**Comment by searum** [comment]
fix
