### ISSUE TITLE
[mazmorra] el bastion violeta

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#312]
La mazmorra funciona bien, excepto que a los boss les puedo tirar stun y arrepentimiento, y tambien ahuyentar el mal.

![wowscrnshot_070813_152426](https://f.cloud.github.com/assets/4790547/764857/02365148-e81b-11e2-85eb-0f463d63efd6.jpg)
![wowscrnshot_070813_151502](https://f.cloud.github.com/assets/4790547/764858/0239d296-e81b-11e2-9f25-a37dc038830c.jpg)
![wowscrnshot_070813_151946](https://f.cloud.github.com/assets/4790547/764859/02405cec-e81b-11e2-9cb6-6cfbd3ef9e01.jpg)

**Comment by ghost** [comment]
O sea, a todos los boss se les puede hacer CC's, y creo que pasa en casi todas las mazmorras/raids.

**Comment by DatJetto** [comment]
No, a los bosses no les puedes echar CC, almenos en los de las Mazz, Raid Cata.

**Comment by lamaza** [comment]
No entiendo que es CC .

Yo recuerdo que no le podia echar esos spell a los jefes en TBC.

**Comment by ghost** [comment]
Pues en las raids piñatas si se podía hacer CC a todo lo que se moviera xd, CC = http://www.wowwiki.com/Crowd_control

**Comment by Wiinter** [comment]
Diria qe ya esta arreglado y ya no se les puede ccear hasta cierto punto

**Comment by efectokoleos** [comment]
prueba ahora
