### ISSUE TITLE
[DK Profano] Siega

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3120]
Nombre: Siega
ID: 56835
Link:http://wow.freakz.ro/spells.php?spell=56835
Descripción: Al usar Golpe Sangriento, Pestilencia o Golpe purulento, las runas gastadas se convertiran en runas de muerte al activarse, Las runas de Muerte cuentan como runas de sangre, escarcha o profanas.

Problema: Funcioan bien con golpe sangriento y pestilencia pero con Golpe Purulento no cambian a runas de Muerte y deberia 
Golpe Purulento:85948

**Comment by searum** [comment]
fix
