### ISSUE TITLE
[DK] Presencia Profana

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3121]
Nombre: Presencia Profana
ID: 48265
Link:http://wow.freakz.ro/spells.php?spell=48265
Descripción: You are infused with unholy fury, increasing attack speed and rune regeneration by 10%, and movement speed by 15%, and reducing the global cooldown on your abilities by 0.5 sec. Only one Presence may be active at a time, and assuming a new Presence will consume any stored Runic Power.

Problema: Hace poco le hicieron fix para acomodar la velocidad de las runas un 10% bueno sigue igual resulta que el fix se lo aplicaron a la precensia equivocada escarcha (48266)

Precensia escarcha reducido un 10% la velocidad de runa
![wowscrnshot_010814_143226](https://f.cloud.github.com/assets/3101842/1871552/66c9148e-7898-11e3-9a77-d110ab7fead2.jpg)

Presencia Profana no esta reduciendo nada
![wowscrnshot_010814_143230](https://f.cloud.github.com/assets/3101842/1871572/8fd31d5c-7898-11e3-9f50-e2b18d17acf8.jpg)

**Comment by searum** [comment]
oki! fallo de ids! :) gracias!

**Comment by searum** [comment]
fix

**Comment by F4NT4SM4** [comment]
bueno sigue estando igual......
