### ISSUE TITLE
Profesiones Bugeadas Por causa de especializacion de ingieneria Goblin y Gnomico

### ISSUE THREAD

**Issue by evilplace** [RoDNet/Bugtracker-Infinium-4.3.4#3122]
Problema: profesiones de Primero auxilios, pesca, mineria, arqueologia y cocina se bugean incluso las de ingieneria pero la unica accesible es la de ingieneria 
no se puede borrar ni deshacer

Causa del problema: Completacion de ambas quest de ingieneria Goblin y Gnomico

PJ Bugeado Naitsirhc Ingieneria 316 

Imagen con el problema:https://imagizer.imageshack.us/v2/1260x709q90/827/nig4.jpg

**Comment by Monleon** [comment]
Pon un ticket ingame para que te borren una especialización.
