### ISSUE TITLE
[Dk] Fatalidad súbita.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#3125]
Rama: Profano
ID:  49530
Link:  http://wow.freakz.ro/spells.php?spell=49530

Tus ataques automáticos con la mano derecha tienen probabilidad de que tu siguiente espiral no cueste poder rúnico.

Bug: A veces salta el buf y no lanza la espiral. Otro caso es que salta el buf lanzas la espiral e igual te quita poder rúnico.

**Comment by searum** [comment]
fix
