### ISSUE TITLE
[DK] Mascota: Saltar/Ataque desgarbado

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#3126]
ID: 91802
Link: http://wow.freakz.ro/spells.php?spell=91802

Al usar Saltar/Ataque desgarbado (Transformación oscura) la mascota debería saltar al objetivo seleccionado interrumpiendo casteo y inmovilizándolos por 2s.

Bug: No realiza el salto ni la inmovilizacion ni normal ni en transformación oscura.

**Comment by searum** [comment]
esto ya esta reportado
