### ISSUE TITLE
[DK] Mascota: Roer

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#3127]
ID: 47481
Link: http://wow.freakz.ro/spells.php?spell=47481

Bite and tear at a target's limbs, dealing light damage and stunning for 3 seconds.

Problema: Dice "Esta falcultad aun no esta lista" y nunca la realiza.

**Comment by searum** [comment]
sera a ti a mi me va y a varios en el server tambien. revisate tu pj

**Comment by F4NT4SM4** [comment]
en mi dk tampoco sirve, nuestro roer que no sirve es 47481 y el roer que esta funcionando en los demas dk es Roer de un npc 91800 http://es.wowhead.com/spell=91800/roer ._.
como hacemos para que nuestra pet tenga esa roer?
ya reiniciamos talentos, borramos cache, montamos ticket y dicen que reporten aqui
