### ISSUE TITLE
[DK] Golpe moustroso. 

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#3128]
ID: 91797
Link: http://wow.freakz.ro/spells.php?spell=91797

Strike an enemy with a smashing attack, dealing 125% of normal melee damage and stunning for 4 seconds.

Bug: Dice "Esta facultad aun no esta lista" y nunca la realiza.

**Comment by searum** [comment]
miratelo porque esto si funciona, necesitas estar en dark transformation
