### ISSUE TITLE
[Misión] Carne en el anzuelo

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.3.4#313]
En esta misión tienes que poner carne en el anzuelo que hay en el agua en el poblado moak de Rasganorte y aparece un tiburón al que hay que matar, pongo la carne, el tuburón sale, pero no puedo atacarlo, siempre me sale "no se ha podido atacar"

http://es.wowhead.com/quest=12017

Gracias.

**Comment by redneo** [comment]
arreglado
