### ISSUE TITLE
[Chamán] Desatar Elementos (Desatar vida)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3131]
Enlace de la spell Desatar elementos http://wow.freakz.ro/spells.php?spell=73680
Enlace del efecto que provoca utilizar la spell anterior http://wow.freakz.ro/spells.php?spell=73685
Enlace del encantamiento de arma que es requerido para que salte esta spell http://wow.freakz.ro/spells.php?spell=51730&name=earthliving-weapon

Descripción de lo que debería suceder:

Al tener el encantamiento de arma (51730) y utilizar la spell "Desatar elementos" (73680) debería sanar a nuestro objetivo <b>aliado</b> por valor de 1916 to 2074 (+20.1% SP) y además dar al chamán un buffo temporal (por valor de 8seg) que potencie la proxima sanación un 20% (un 30% si se tiene el talento "29079")

Problema: actualmente al hacer esto no salta "Desatar vida" (ni el buff, ni la curación)

**Comment by searum** [comment]
fix
