### ISSUE TITLE
[DK] Mascota: Daño.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#3132]
Los ataques automáticos de la mascota están muy bajo 23p de daño a un tela es lo que le saca a un 85. 
Este es el daño: http://kn3.net/38FC579803CJPG.html

Nota del parche 4.3: Ahora las mascotas del caballero de la Muerte heredan correctamente las estadísticas de penetración y de golpe crítico de los hechizos de sus maestros.  No están heredando las estadísticas
http://eu.battle.net/wow/es/game/patch-notes/4-3-0#deathknights

Este es su panel de estadísticas: http://kn3.net/44C3DA9D5CBJPG.html

**Comment by searum** [comment]
esto no va en spells

**Comment by Monleon** [comment]
Puedes comprobarme si después del último cambio sigue sucediendo?
