### ISSUE TITLE
[Dk-Profano] Invocar gargola 

### ISSUE THREAD

**Issue by nicerdicer** [RoDNet/Bugtracker-Infinium-4.3.4#3133]
Reporto el daño de la gargola del Dk Profano http://wow.freakz.ro/spells.php?spell=49206 

Según su formula 150 + ( AP \* 0.4 ) esta entregando daños muy por encima de lo que deberia.
Fuente: http://www.egamers.it/762-death-knight/81174-cata-dk-formule-spell-e-talenti-4-3-4
Summon Gargoyle
Rank 1  A Gargoyle flies into the area and bombards the target with Nature damage modified by the Death Knight's attack power. Persists for 30 seconds. As of patch 4.3 the gargoyle will only use ranged attacks.
AP Coefficient = 0.4
60 Runic Power, 30 yd range, Instant, 3 minute cooldown

Hice el test con el Dk del pj, Altherius, con un pico de AP de 19000 la formula sacaba 7750 de daño contra mi temple (41%reducción) y Enlace de Alma (20%reducción). El daño recibido por mi Lock era de 7090 a pesar de las reducciones

**Comment by Kiritoo** [comment]
Arreglado

**Comment by Wiinter** [comment]
No es por nada, pero creo que esa fórmula está equivocada aunque la hayas sacado de ahi.
La fórmula correcta sería 35+AP*0.453. Parece una chorrada pero por los decimales si alguien lleva a la fase de burst con algo mas de 15k con su formula esta dejando de pegar 800 puntos de daño menos, y cuanto más se incrementa el ap peor. Lo reportaré de nuevo, porque diría que está mal

**Comment by Kiritoo** [comment]
El arreglo no está hecho en base a su formula, es más ni me fije en ella.
