### ISSUE TITLE
[Chaman] Glifo de Relampago desatado

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3134]
Nombre: Glifo De Relampago Desatado
ID: 71155
Enlace: http://wow.freakz.ro/item_finder.php?item=71155
Descripcion: Los inscriptores consiguen este glifo con Investigación de inscripción de Rasganorte

Problema: No lo esta enseñando ya varios inscriptores (incluyendome) llevamos tiempo en ello y nada

Investigación de inscripción de Rasganorte: 61177
Glifo De relampago desatado: 71155

**Comment by Compresor** [comment]
Todos los reportes son igual de importantes, no damos preferencia a ningun reporte sobre otro

**Comment by Monleon** [comment]
Ya es aprendible
