### ISSUE TITLE
[Brujo] Poseer

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#3136]
http://wotlk.openwow.com/spell=48210
Cuando el hechizo Poseer se acaba o se disipa, el alma vuelve a ti y te sana un 100% del daño infligido al objetivo.

Problema: Cuando haces un daño crítico la sanacion que te devuelve es normal, no critica.

Si haces un critico de 24k, te devuelve una sanacion de 11k.

**Comment by Velcositro** [comment]
Deberías haber puesto el link de Cata: http://cata.openwow.com/spell=48181
La id es otra, se supone que es este el que debería estar.

Edito: Acabo de comprobar ingame con el addon de las IDs, que 48181 es la correcta.

**Comment by Wiinter** [comment]
es lo mismo

**Comment by efectokoleos** [comment]
arreglado
