### ISSUE TITLE
[Brujo] (Demonología) Inferno

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#3137]
Hechizo: http://cata.openwow.com/spell=85105

Bug: El talento está haciendo que se puedan lanzar otros hechizos mientras se canaliza Llamas infernales (http://cata.openwow.com/spell=1949) pero Llamas infernales debería interrumpirse al lanzar otros hechizos.

**Comment by efectokoleos** [comment]
arreglado
