### ISSUE TITLE
Hechizo ( Chaman ), Desatar elementos.

### ISSUE THREAD

**Issue by kalarjan** [RoDNet/Bugtracker-Infinium-4.3.4#3138]
Nombre: Desatar elementos.
Enlace: http://es.wowhead.com/spell=73680/desatar-elementos#.
Descripción: Centra la fuerza elemental imbuida en el armamento del chaman, con efectos concentrados segun el encantamiento liberado. Si el arma tiene los dos encantamientos, solo se liberara uno.
Consulta las descripciones de cada hechizo de imbuir arma para ver los detalles relacionados con los efectos de desatar cada uno.
Problema: El ataque no funciona, por lo tento no inflinge daño al enemigo ni relentiza en el caso que lleves puesto Arma estigma de escarcha.

**Comment by paellaencol** [comment]
Añado enlaces de efectos que se deben producir al utilizar "Desatar elementos" dependiendo del encantamiento que se lleve en el arma:

-Al llevar "Arma viento furioso" http://wow.freakz.ro/spells.php?spell=8232 y utilizar "Desatar elementos" debería provocar "Desatar viento" http://wow.freakz.ro/spells.php?spell=73681

-"Arma estigma de escarcha" http://wow.freakz.ro/spells.php?spell=8033 debería provocar "Desatar escarcha" http://wow.freakz.ro/spells.php?spell=73682

-"Arma lengua de fuego" http://wow.freakz.ro/spells.php?spell=8024 debería provocar "Desatar llama" http://wow.freakz.ro/spells.php?spell=73683

**Comment by Corkryo** [comment]
A mi me ocurre lo mismo, pensaba que era a mi solo, a los demas de mi hermandad no les ocurre...

**Comment by searum** [comment]
fix que se me piro la pinza y lo iba a meter en script en vez del modo hack y borre todo JAJAJA pero ya esta :D
