### ISSUE TITLE
[Dk] Fatalidad súbita.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#3142]
Rama: Profano
ID: 49530
Link: http://wow.freakz.ro/spells.php?spell=49530

Tus ataques automáticos con la mano derecha tienen probabilidad de que tu siguiente espiral no cueste poder rúnico.

Bug: Pues a quedado muy Op,puedes lanzar todas las espirales gratis que quieras hasta que se agote el buf y debería ser 1 sola que salga gratis.

**Comment by Kiritoo** [comment]
Eso lo arreglo yo ahora un segundo

**Comment by searum** [comment]
fix
