### ISSUE TITLE
[Dk] Golpe necrotico.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#3143]
Nombre: Golpe Necrotico
ID: 73975
Enlace: http://wow.freakz.ro/spells.php?spell=73975

Descripcion: Un Golpe Despiadado que inflige 100% de daño con arma y absorbe los siguientes 0.70 \* AP De sanacion que reciba el objetivo. Durante 10s, o hasta que se haya absorbido la cantidad total de sanacion, el tiempo de lanzamiento del objetivo aumenta un 30%

Problema: Esta absorbiendo mas de la sanación que dice el debuff acabo de probarla con un chaman cura 30k normal,le tire el debuff que dice que absorbe tan solo 5k (Sin talentos algunos) y le absorbió completamente los 30k al objetivo.

**Comment by Kiritoo** [comment]
Esto está funcionando.
