### ISSUE TITLE
[Dk] Velocidad de carga de runas.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#3145]
Aun esta el bug de las presencias Escarcha y Profano es que tiene cambiabas la velocidad de carga de runas escarcha tiene la de profano y profano la de escarcha.

Escarcha: http://kn3.net/39B81A2C460JPG.html
Profano:  http://kn3.net/36E2A7D2F7DJPG.html

**Comment by sakuranobushi** [comment]
Este error se ha corregido en el reino de pruebas y debería reflejarse pronto en el resto.
