### ISSUE TITLE
[Guerrero] Golpe Heroico

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3146]
Nombre: Golpe Heroico
ID:78
Enlace: http://wow.freakz.ro/spells.php?spell=78

Descripcion: An attack that instantly deals 8 + AP \* 60 / 100 physical damage. A good attack for moments of excess rage.

Problema: esta pegando muy poco segun la formula y la descripcion del hechizo deberia pegar 332p y apenas pego 273p (testee sin equipo y un arma de lv 5)

Formula correcta: 8 + AP \* 60 / 100

**Comment by F4NT4SM4** [comment]
mmmmm verifique denuevo y ahora si va perfect bueno cierro.......

**Comment by F4NT4SM4** [comment]
lol fui denuevo al dummy con el qeu habia testeado y me baja el daño jajaja 
okay deberia de dejar hablar solo :s

**Comment by Kiritoo** [comment]
No testees en los dummy utiliza un npc de nivel 85 o similar o otro player sin temple.

**Comment by F4NT4SM4** [comment]
en los dummy de nivel 60 ariba de mi inscriptor me reducen el daño pero los de nivel 85 no me reducen nada :S
