### ISSUE TITLE
[Chaman] Desatar elementos

### ISSUE THREAD

**Issue by Corkryo** [RoDNet/Bugtracker-Infinium-4.3.4#3147]
Nombre: Desatar elementos (Unleash elements)
ID: 73680
Descripcion: Unleash Elements  
Focuses the elemental force imbued in the Shaman's weaponry, with the concentrated effects depending on the enchantment unleashed.
Problema: Sólo me ocurre a mi. El hechizo no hace nada, el personaje se mueve pero ni hace daño, ni saltan los buff de armas, ni nada.
Gracias

**Comment by Corkryo** [comment]
Lo siento, abri este post existiendo uno igual, pero no se borrarlo... :S

**Comment by Cantadal** [comment]
Me pasa exactamente lo mismo, y se nota muchisimo en un  chaman mejora este fallo. Espero que hagan un buen trabajo y lo dejen como lo hicieron antes que funcionaba todo. Gracias

**Comment by searum** [comment]
fix joder 3 issues iguales.. xd
