### ISSUE TITLE
[Guerrero] Empalar

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3149]
Nombre: Empalar
ID:16493/16494
Enlace: http://wow.freakz.ro/spells.php?spell=16494
Descripcion: Aumenta un 10%/20% el bonus de daño por golpe critico de tu golpe mortal,embate y abrumar

Problema: No esta aumentando correctamente el 10%/20% a esos 3 ataques
el 10% esta aumentado 5% (16493)
el 20% esta aumentando 10% (16494)

no pongo imagenes ni los calculo que hice ya que ni los miran ._. y me piden issues resumido (bueno mejor escribo menos :S)

**Comment by searum** [comment]
este issue es perfecto :) gracias!

**Comment by efectokoleos** [comment]
Arreglado en el core nuevo, no daremos mas soporte al actual
