### ISSUE TITLE
[Druida] Augurio de claridad 

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#3154]
http://es.wowhead.com/spell=16864
El estado de Lanzamiento libre reduce un 100% el coste de maná, ira o energía de tu siguiente hechizo no instantáneo dañino, de sanación o facultad feral ofensiva.

Problema: Puedes sanar o pegar gratis hasta que se acabe el tiempo de lanzamiento libre que son 13s. Solo te debería dejar pegar o sanar gratis el siguiente hechizo.

**Comment by 50megas** [comment]
la verdad que en feral se nota mucho esto,13 segundo espameando destrofar y combos gratis

**Comment by Monleon** [comment]
Puede cerrarse ya esto?
