### ISSUE TITLE
[Brujo] Mal fario

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#3158]
http://wow.freakz.ro/spells.php?spell=18179

No pone el mal fario en los enemigos cercanos cuando pones la maldicion de los elementos en un enemigo. Tienes qe poner la maldicion de los elementos uno a uno

**Comment by Kiritoo** [comment]
Arreglada la parte de Maldición de debilidad.
"Also, your Curse of Weakness increases the target's energy, rage, focus or runic power costs of abilities by 5% while active."
Falta la de la maldición de los elementos.

**Comment by efectokoleos** [comment]
arreglado
