### ISSUE TITLE
Sanacion del Guerrero furia

### ISSUE THREAD

**Issue by sherik12** [RoDNet/Bugtracker-Infinium-4.3.4#316]
el talento mania sangrienta (16492) se activa muy seguido para tener solo un 10% de probabilidad de activarse. Pasa esto cuando los rivales son dps fisico.

**Comment by searum** [comment]
Esto funciona correctamente

**Comment by ghost** [comment]
Perfectamente? S: tiene 10% de probabilidad de activarse y se activa cada rato.... no parece tan perfecto xd digo yo... ya parecen healers los war.

**Comment by sherik12** [comment]
Apoyo a lvmd apenas es un 10% y se activa constantemente hasta 7 veces seguidas, no puede funcionar correctamente
