### ISSUE TITLE
[Mision] Gilneas - La batalla por la ciudad de gilneas

### ISSUE THREAD

**Issue by meb154** [RoDNet/Bugtracker-Infinium-4.3.4#3160]
http://es.wowhead.com/quest=24904/la-batalla-por-la-ciudad-de-gilneas

no funciona la mision.

asi deberia ser http://www.youtube.com/watch?v=sYd3fkFeuV4

**Comment by Monleon** [comment]
Las misiones de los huargens ya funcionan perfectamente de inicio a fin
