### ISSUE TITLE
[Talento] Druida Restauración - Obsequio de la naturaleza

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#3161]
Hola queria comentar que este talento sigue sin funcionar.
Nature's Bounty Rank 1 http://cata.openwow.com/spell=17074
Nature's Bounty Rank 2 http://cata.openwow.com/spell=17075
Nature's Bounty Rank 3 http://cata.openwow.com/spell=17076

Lo que no funciona es la 2ª parte 
"In addition, when you have Rejuvenation active on three or more targets, the cast time of your Nourish spell is reduced by 10%."

Le pongo a más de 3 objetivos el rejuvenecimiento y nunca se reduce el tiempo de casteo de nutrir *Nutrir / Nourish - http://cata.openwow.com/spell=50464

Lo vuelvo a reportar porque el otro issue esta cerrado https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3016

Un saludo

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
