### ISSUE TITLE
[Spell > Hunter] Aspect of the Fox

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#3162]
Hola vuelvo a reportar este hechizo
Nombre: Aspecto del zorro
http://cata.openwow.com/spell=82661

Porque si te golpean cuerpo a cuerpo con este aspecto puesto, te interrumpen cualquier casteo de un spell que estes realizando, como puede ser disparo de cobra, firme, etc..

Ya reportado anteriormente https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2348

Un saludo.

**Comment by Kiritoo** [comment]
Fix, falta compilar.
