### ISSUE TITLE
[Mazmorras/Bandas][Stratholme] Puerta de El Guantelete

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3164]
Buenas.
• Problema: La puerta de El Guantelete está bloqueada y no se puede pasar a la zona "undead" de la mazmorra.
• Observaciones: Antes de la expansión Cataclysm se necesitaba la llave de la ciudad (http://es.wowhead.com/item=12382), intenté usarla pero ya no se puede.
Muchas gracias y hasta luego.

**Comment by Dafena** [comment]
Todavía no fue solucionado :[

**Comment by juaks** [comment]
Por favor arregladlo =(
