### ISSUE TITLE
[Misión] Pensándolo mejor: haz un prisionero (Infralar)

### ISSUE THREAD

**Issue by michaelTIIH** [RoDNet/Bugtracker-Infinium-4.3.4#3166]
La quest no se puede completar, ya que los NPC a bordo de la nave de guerra de la Alianza caen hacia abajo despues de darles un golpe, intente seguir uno para ver si se detenian en el piso, pero los NPC siguen cayendo hasta perderse de vista por debajo del suelo, desaparecen por buen rato, pero pasa lo mismo si se les intenta matar.

Quest
http://es.wowhead.com/quest=26250/pensandolo-mejor-haz-un-prisionero

**Comment by ghost** [comment]
Sigue sin funcionar hoy 25 de nov
Saludos
