### ISSUE TITLE
[Sacerdote Sombras] Orbe de las sombras ID:95740

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3169]
Viene de https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2867
Enlace: http://wow.freakz.ro/spells.php?spell=95740

ID de los orbes: http://wow.freakz.ro/spells.php?spell=77487

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/513/np29.jpg/'><img src='http://img513.imageshack.us/img513/8471/np29.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

Problema: consumir un orbe de las sombras no está potenciando con un 24% extra (en mi caso) a explosión mental http://wow.freakz.ro/spells.php?spell=8092&name=mind-blast o pua mental http://wow.freakz.ro/spells.php?spell=73510&name=mind-spike

Aclaración: los orbes de las sombras se pueden stackear hasta un máximo de 3, por lo que el multiplicador a "explosión mental" y "pua mental" seria de un 24/48/72% dependiendo de los orbes que se tuvieran previamente.

P.D. Todo lo demás relacionado con este talento y/o mecánica funciona correctamente

**Comment by redneo** [comment]
Falso.

El daño de explosion y pua mental tendria que ser un base del 10% mas 1.45% por los puntos de maestria que tuvieras y todo esto multiplicado por el numero de orbes que se hayan cargado.

**Comment by Dekadencee** [comment]
Fixed
