### ISSUE TITLE
[BUG] Personaje duplicado.

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#3170]
Bueno, no sé qué ha pasado, pero al logear, después de haberme dado wow error dos veces, me ha salido en la lista de personajes mi personaje principal duplicado. Lo gracioso, como se verá en las fotos, es que cada uno tiene una pet distinta. He logeado y deslogeado con ambos, he borrado caché, pero siguen los dos ahí, en la lista de personajes.

![wowscrnshot_011114_190717](https://f.cloud.github.com/assets/6329431/1894479/f71c451a-7aeb-11e3-9650-8799301aad93.jpg)

![wowscrnshot_011114_190722](https://f.cloud.github.com/assets/6329431/1894480/fc3c84ce-7aeb-11e3-857e-f5de4071e915.jpg)

No he querido eliminar uno por miedo a perder el personaje en sí, y quisiera saber qué solución hay sin que corra peligro de perderlo.

PD: No puedo tomar fotos de esto, pero cuando retiro mi mascota (la araña), ésta no me sale en el llamar mascota como tal, sino que aparece cuando selecciono llamar al cangrejo.

**Comment by Velcositro** [comment]
No borres ninguno o borrarás al Pj completo. Antes pasaba esto con los Dks y Cazadores pero con el tiempo se borraron solos (creo que tenía algo que ver con las mascotas).

Como no causa ningún problema más allá de ver a un extra en el Login yo te recomendaría que simplemente ignores al 2º (como supongo que estarás haciendo ya), al menos hasta que algún GM te responda algo.

**Comment by Monleon** [comment]
Tranquilo, el problema se resolverá por si mismo. 
Mejor no toques nada
