### ISSUE TITLE
[Chamán Restauración] Sanación Ancestral (16235)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3171]
Rango 1: http://wow.freakz.ro/spells.php?spell=16176
Rango 2: http://wow.freakz.ro/spells.php?spell=16235

Id: del buff Entereza ancestral http://wow.freakz.ro/spells.php?spell=105284

1º Problema: Aunque aumenta la salud del objetivo sanado (con cualquier cura), por el chamán, por valor de un 10% de la curación hecha, éste buff (105284) debería acumularse hasta un tope del 10% de la salud total del aliado sanado. Actualmente en vez de acumularse, se pisa sustituyéndolo por otro buff de incluso menor valor.

2º Problema: Este buff no se está aplicando al propio chamán

P.D. La segunda parte de este talento, la de reducir el daño físico recibido un 10% funciona correctamente

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
