### ISSUE TITLE
[Mago Fuego] Buena racha

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3172]
Nombre: Buena racha
ID:44445
Enlace: http://wow.freakz.ro/spells.php?spell=44445
Descripcion: Tus hechizos ya no activan misiles arcanos. En su lugar, tus golpes criticos con bola de fuego, descargar de pirofrio, Agostar, PiroExplosion o Explosion de fuego, Tienen una probabilidad de que el proximo lanzamiento de piroexplosion en 15s sea instantaneo y no cueste mana.

Problema: Tambien se esta activando con la explosion del bomba viva y no deberia :s

Estas son las skills que solo deberia activar el talento
Bola de fuego:133
Descargar de Pirofrio: 44614
Agostar: 2948
Piroexplosion: 11366
Explosion de fuego: 2136

**Comment by Pegasu5** [comment]
Teniendo 11k de vida se me hizo extraño bajarme un élite de 112k con mi mago fire xDDD

**Comment by redneo** [comment]
Arreglado
