### ISSUE TITLE
[Brujo] [Talento] Semilla de corrupción: 86664

### ISSUE THREAD

**Issue by Felarof23** [RoDNet/Bugtracker-Infinium-4.3.4#3173]
El talento de semilla de corrupción (id:27243) no se está activando, el cual debe aplicar corrupción a todos los enemigos afectado por la detonación.

issue: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2880

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
