### ISSUE TITLE
[Mago Fuego] Maestria: Quemadura Relampago

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3174]
Nombre: Maestria: Quemadura Relampago
ID:76595
Enlace: http://wow.freakz.ro/spells.php?spell=76595
Descripcion: Aumenta un 22%(maestria base) daño infligido por todos tus efectos de daño de fuego periodicos. cada punto de maestria aumenta el daño periodico infligido un 2.8% extra.

Problema: La Maestria base esta aumentando entren un 40%-50% el daño periodico y deberia de ser 22%
2do Problema: La Maestria esta aumentando el daño de otros hechizos fuego como fogonazo solo deberia aumentar el daño a estos hechizos:

Frostfire Bolt 44614 (solo el daño periodico )
Living Bomb 44457 (solo el daño periodico )
Pyroblast! 92315 (solo el daño periodico )
Pyroblast 11366 (solo el daño periodico)
Ignite 12654

Fuente: http://wow.freakz.ro/spells.php?spell=76595

**Comment by Necrofilo** [comment]
¿Cuanto más? ¿Tienes la fórmula?

**Comment by F4NT4SM4** [comment]
nah dificil saber cuanto esta aumentando exactamente
te pondre un ejemplo me puse 0 maestria osea nada mas la base 8 y pego 500 (es un ejemplo) me ponia full maestria 18 llegaba y aumentaba un 39% algo mas o menos asi no me acuerdo y aumentaba mas de ese 39% :S
no anote nada de como testeaba ya que me pidieron issues resumido, menos imagenes y menos texto :s

**Comment by Necrofilo** [comment]
Osea que al principio estabas sin equipo y luego con equipo?

**Comment by F4NT4SM4** [comment]
aver quieres que vuelva a testear todo denuevo tomar nota y comentarlo aqui? ¬¬
testee sin ningun talento osea con equipo pero sin efecto de la maestria 
puse 1 punto en fuego para tener la maestria de fuego
tome en cuenta 25% de daño mas a los hechizos fuego de un talento de fuego (lo digo por si acaso :s)
ahora le aumente un 39% mas de daño que indica mi maestria y esta aumentando mas de ese 39%
y ya que la maestria base esta bien la testee antes de todo y los 25% (del talento de fuego) esta aumentando correctamente 
todo indica que lo que esta aumentando de mas de ese 2.8% por punto de maestria

Mi comentario anterior era un ejemplo de por que esta bug no de como lo testee :s

**Comment by Necrofilo** [comment]
Si primero lo has testeado sin talentos, estás contando con que al activar la rama de fuego te aumenta el daño con todos los hechizos de fuego un 25%?? Aparte no sé que DoT de fuego usas cuando no tienes la rama activada...

**Comment by F4NT4SM4** [comment]
leiste bien lo que puse?
¨tome en cuenta 25% de daño mas a los hechizos fuego de un talento de fuego (lo digo por si acaso :s)¨ osea ya conte lo que dices el talento de fuego que me aumenta un 25%
y testee con fogonazo da la casualidad de que esta teniendo efecto de la maestria como tenia dudas si estaba bien o no, no lo reporte pero por lo que dices intonce la maestria esta aumentando tambien otros ataques que no deberia

**Comment by Pegasu5** [comment]
Zap!

**Comment by Necrofilo** [comment]
Entonces debería aclararte que fogonazo no cuenta como DoT directo, con lo que la maestría no debe alterar su daño.

 Si está aumentando el daño de fogonazo, quizá sea porque anteriormente en RoD tuvieron que reprogramar para arreglar algún bug.

 (No puedes testear la maestría con fogonazo).

**Comment by F4NT4SM4** [comment]
Bueno ps testee denuevo sin fogonazo me toco levelear un mago denuevo para probar el talento que aumenta un 25% el daño fuego para asegurarme de que no tuviera nada que ver 
Y despues de testear me di cuenta que lo que esta realmente bug es la maestria base esta aumentando mas o menos un 40%-50% de todas las skill de daño periodico que afectan la maestria por ejemplo sin equipo y un solo punto en talento fuego el dot de piroexplosion deberia de sacar 1060,79 en total y esta haciendo un 1504 
testee con otra spell bomba viva y tambien esta aumentando un 40%-50% el daño periodico

**Comment by Monleon** [comment]
La maestría del mago fire dejará de hacer el doble de daño.
