### ISSUE TITLE
[Brujo] Manafago - Bloqueo de hechizos

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#3177]
http://wow.freakz.ro/spells.php?spell=19647

Ahora mismo unicamente silencia 3s si le cortas el casteo, sino ni eso.

Debería silenciar 3s sino cortas un casteo. Si le cortas un casteo debería silenciar 6s toda la escuela de ese hechizo. Como contrahechizo del mago por ejemplo

**Comment by Drogoth2** [comment]
Yo también lo he estado mirando y puedo decir que el silencio de 3sg no se produce si lo usas, lo he estado mirando contra otro pj y si no le corto el casteo no se silencia nada.

Un saludo

**Comment by sprin69** [comment]
es = k el silencio d mago

**Comment by efectokoleos** [comment]
arreglado, falta compilar
