### ISSUE TITLE
Dk:Esbirro bug en modo profano

### ISSUE THREAD

**Issue by feniix97** [RoDNet/Bugtracker-Infinium-4.3.4#3179]
El esbirro del dk al hacerse mascota en modo profano esta quitando unos 100 puntos de daño máximo a los jugadores, además sus habilidades y ataques no funcionan del todo bien ya que los jugadores los esquivan todos, no están funcionando como las mascotas de otras clases como la de los brujos o cazadores .

otros bugs que encontré son de talentos y glifos que no le afectan tampoco:
Infusión de sombras:http://es.wowhead.com/spell=91342/infusion-de-sombras no esta aumentando el daño.

Transformación oscura:http://es.wowhead.com/spell=63560/transformacion-oscura
no esta tampoco aumentando el daño

Glifo de levantar a no muerto:
http://wow.freakz.ro/spells.php?spell=58686&name=glyph-of-raise-dead
sigue sin recibir un 40% de la fuerza y el aguante del dk

**Comment by Compresor** [comment]
No reportes 3 fallos en un mismo reporte. Reporta cada bug en un issue diferente
