### ISSUE TITLE
[Brujo] Drenar vida

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#318]
Únicamente hace daño y no sana el 2% que debería sanar.
#105

**Comment by crowel** [comment]
Ya cura^^

**Comment by Wiinter** [comment]
Arreglado

**Comment by Wiinter** [comment]
Nose porque pero ahora ya no va.

**Comment by searum** [comment]
ya lo he fixeado

**Comment by Wiinter** [comment]
Pues no va, con Bofur lo hemos mirado y a conseguido que cure el primer tick el 2% de la vida pero no los demás. Antes no curaba nada.
