### ISSUE TITLE
Muerte y descomposicion se nerfeao aun mas.

### ISSUE THREAD

**Issue by feniix97** [RoDNet/Bugtracker-Infinium-4.3.4#3180]
El poder muerte y descomposición:http://es.wowhead.com/spell=43265/muerte-y-descomposicion
esta quitando cerca de 900 como máximo a los jugadores al usarlo, un daño extremadamente bajo incluso si fueras un pj nivel 80
además en modo profano el talento Morbosidad que aumenta un 15% ese daño con los 3 talentos de esa rama esta aumentando en daño unos 40 puntos como máximo al hechizo quita alrededor con 950 como mucho a un muñeco de practica.

**Comment by Kiritoo** [comment]
Esta funcionando correctamente, tanto el area como el talento.
