### ISSUE TITLE
Bug cola de arenas

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3182]
Al ir a anotar arenas, en nuestro caso 2c2, no deja porque sale un mensaje diciendo que no tienes equipo de 3c3.

 Dejo imagen:
![wowscrnshot_011214_214409](https://f.cloud.github.com/assets/6006693/1897084/121b4b06-7bcb-11e3-8ae9-1a1919735a38.jpg)

Y lo que tenemos que hacer, es al acabar la arena cambiar el lider de uno a otro para poder anotar.

**Comment by Dekadencee** [comment]
Fixed, nobstante si vuelve a ocurrir avisad
