### ISSUE TITLE
Error de profesion al migrar

### ISSUE THREAD

**Issue by diegacho** [RoDNet/Bugtracker-Infinium-4.3.4#3186]
PJ: Daft Sacer Alianza: Enchant - Tailoring
![wowscrnshot_011314_131009](https://f.cloud.github.com/assets/6391760/1903208/40cafe02-7c7e-11e3-9184-6fd6ef6b1b16.jpg)

![wowscrnshot_011314_131013](https://f.cloud.github.com/assets/6391760/1903231/8b356d6a-7c7e-11e3-94a8-8d83b36894f6.jpg)
PJ Rasta Druid Alianza:Inscriptor - Enchant
![wowscrnshot_011314_123748](https://f.cloud.github.com/assets/6391760/1903247/cc502678-7c7e-11e3-81bf-cc3a29be829b.jpg)
![wowscrnshot_011314_123802](https://f.cloud.github.com/assets/6391760/1903255/fd7ee734-7c7e-11e3-8145-149d6049f292.jpg)

**Comment by Compresor** [comment]
No lo pongas aqui, ponlo en el foro 
https://www.reignofdarkness.net/wow/forums/13-ayuda-tecnica/
