### ISSUE TITLE
[Joyería] Escrito sobre joyas ardientes

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#319]
Buenas:
El ítem Escrito sobre joyas ardientes (http://es.wowhead.com/item=71949) no funciona, no da ninguna receta épica (ya busqué una por una y nada).

Eso es todo, gracias y hasta luego.

**Comment by Kiritoo** [comment]
Arreglado, el cambio será aplicado en el reino en la próxima compilación.
