### ISSUE TITLE
talento malo de hunter 

### ISSUE THREAD

**Issue by matux12** [RoDNet/Bugtracker-Infinium-4.3.4#3190]
Informo que el talento Rastreo de la rama supervivencia no esta entregando la celeridad.

**Comment by Compresor** [comment]
Te pediría que volviese a abir otro issue reportando de la forma correcta. Aqui te dejo una plantilla para que te sea más facil : https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
