### ISSUE TITLE
bug de trampa explosiva

### ISSUE THREAD

**Issue by matux12** [RoDNet/Bugtracker-Infinium-4.3.4#3191]
informo que la trampa explosiva al activarse no empuja a los que están en ella, como se puede apreciar en este vídeo de un jugador de blizzard.

http://www.youtube.com/watch?v=5ywkiFLYEV4

**Comment by Compresor** [comment]
Te pediría que volviese a abir otro issue reportando de la forma correcta. Aqui te dejo una plantilla para que te sea más facil : https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by Monleon** [comment]
Esto sólo debe pasar en el Pandaria...
