### ISSUE TITLE
El arma no transforma al druida cuando esta en feral

### ISSUE THREAD

**Issue by feniix97** [RoDNet/Bugtracker-Infinium-4.3.4#3193]
Banda: tierras de fuego:http://es.wowhead.com/zone=5723/tierras-de-fuego
Arma: guadaña llameante de fandral:http://es.wowhead.com/item=69897
Bug: no esta transformando al druida cuando esta en feral en un tigre de fuego aun teniendo el buff
Buff: druida dela llama:http://es.wowhead.com/spell=99244

si pueden arreglarlo rápido seria genial la apariencia que le da al druida en gato es hermosa.
teniendo el arma es un apena que no me funcione la transformación

**Comment by redneo** [comment]
El problema, es que la transformacion en feral puede sobre la transformacion del baston y por eso no aparece.

Me explico mejor:

El aura 99244 cuando estas en humanoide funciona a la perfeccion, pero cuando cambias a gato, da igual que te la pongas o no, no te cambia.

**Comment by feniix97** [comment]
podrán arreglarlo el bug?

**Comment by 50megas** [comment]
#2285 
la verdad molaría mucho que lo arreglaran,ya que como yo seguramente,donamos  todo ilusionados por tener nuestro gato feral de fuego y imaginaros el chasco xd. ya se que que no es una prioridad pero se agradecería si  lo arreglan

**Comment by Pegasu5** [comment]
Pero he visto que abalorios antiguos como el de ese gorila con un campo magnético pueden sobre la forma del feral, así que eso me sorprende

**Comment by Necrofilo** [comment]
No es lo mismo, Pegasus... el abalorio que tú dices tiene activación, sin embargo el bastón de Firelands es simplemente una ilusión, al tenerlo equipado y pasar a gato debe ponerse automáticamente.

**Comment by Pegasu5** [comment]
estamos hablando de buffos y apariencia, no de como se activa no? nada tiene que ve lo que tu dices, da igual como se active mientras el buffo de la apariencia estamos hablando de efectos similares. no iguales

PD: error de dedo :P

**Comment by Necrofilo** [comment]
El arma de Firelands que se está tratando en este reporte...
1: no es  un abalorio.
2: no pone un buff visible como en el caso del abalorio del gorila de ICC.
3: no tiene activación.

 Simplemente al pasar a forma felina se debe ver instantáneamente (la forma del druida en llamas) y permanecer hasta cancelar la transformación.
![fandralfirecat_model_small](https://f.cloud.github.com/assets/6006693/1938518/11c1ec4e-7f4c-11e3-8e8f-2a6b6ae48ea1.jpg)

El gato es como el de la imagen de arriba pero sin armadura (he puesto con armadura porque mola más e.e)
