### ISSUE TITLE
abalorio:Estabilizador de matriz bug

### ISSUE THREAD

**Issue by feniix97** [RoDNet/Bugtracker-Infinium-4.3.4#3194]
Banda: tierras de fuego:http://es.wowhead.com/zone=5723/tierras-de-fuego#drops:mode=n10

Abalorio: estabilizador de matriz:http://es.wowhead.com/item=68994

Bug: el abalorio no se activa nunca sin importar que.

**Comment by Compresor** [comment]
#3199 Continuamos des de allí
