### ISSUE TITLE
[Cazador]Talento rastreo malo 52786

### ISSUE THREAD

**Issue by matux12** [RoDNet/Bugtracker-Infinium-4.3.4#3195]
Nombre: Rastreo

Enlace: http://es.wowhead.com/spell=52786

Descripción:  Aumenta la celeridad a distancia un 3%, al agregar los tres puntos de talento.

Problema: El talento o hechizo de rastreo esta bug no esta entregando celeridad.

**Comment by Jhovanni** [comment]
Al colocar los puntos de talento en rastreo, si verificas tu DPS, este incrementa de acuerdo a como se debería aumentar con ese 3% de celeridad extra. En sí Rastreo no está bug, lo que está bug es la visualización de celeridad, que ya ha sido reportada antes.

**Comment by Compresor** [comment]
Cierro reporte entonces
