### ISSUE TITLE
[talento-druida] Rey de la Selva - 48495

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#3196]
Nombre: rey de la Selva

Enlace: http://wow.freakz.ro/spells.php?spell=48495

Descripción: 
While using your Enrage ability in Bear Form, your damage is increased by 15%, and your Tiger's Fury ability also instantly restores 60 Energy.

Problema: cuando usas furia del tigre(5217) da los 60 de energía 2 veces,cuando solo debería  dar 60, todo lo demás funciona bien

**Comment by Kiritoo** [comment]
Fix, falta compilar.
