### ISSUE TITLE
[vendedor] Proveedor Arok, Intendente Anillo de la Tierra

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#320]
El tipo mencionado, no se encuentra en su lugar/no aparece/no esta (En Vash´jir), ha sido suplantado por un personaje que no hace nada, por consiguiente no se puede comprar nada de la facción http://es.wowhead.com/faction=1135

http://es.wowhead.com/npc=50324/proveedor-arok
![wowscrnshot_070813_140806](https://f.cloud.github.com/assets/4790547/769474/392b49f6-e8b6-11e2-821c-cf250d04df64.jpg)

**Comment by lamaza** [comment]
Creo que mejor habria que cambiar la categoria a Vendedor, porque eso es.

**Comment by crowel** [comment]
Acabo de comprobarlo y el npc esta justo donde marca wowhead.
Quiero comentar que donde tú estas en el mapa ahí no aparece el npc.
Cierro, un saludo.
