### ISSUE TITLE
[Mago fuego] estadísticas (celeridad).

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3200]
La celeridad en el mago fuego, debe aportar ticks extra en la combustión.

 Problema: teniendo el cap para ello (2005, o en mi caso 1765 + 240 de CD de herbo), no aporta esos ticks extra en la combustión, simplemente aumenta la velocidad de casteo.

**Comment by Compresor** [comment]
#2697 El problema radica en la celeridad, cierro el post porque ya hay uno abierto al respecto

**Comment by Necrofilo** [comment]
De acuerdo, entonces debería cerrar también el reporte de celeridad del rogue que abrí hace unos meses? Podéis cerrar si lo véis oportuno: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2822
