### ISSUE TITLE
[Brujo] Proposito oscuro 

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#3201]
http://wow.freakz.ro/spells.php?spell=80398

Cuando el compañero te otorga las cargas,el brujo está augmentando un 4% de daño y sanacion periodica por cargar en vez de 3% por carga.

**Comment by redneo** [comment]
Lo he testeado hoy y no va del todo bien.

Cuando pones proposito al objetivo tanto el como tu tienes que tener un 3% de celeridad, eso está OK.

Cuando el objetivo recibe una sanacion critica o un daño por tiempo critioco el objetivo gana un 1% y el caster un 3%.

En el testeo que he hecho cuando el caster hace critico de DOT el objetivo gana un 1%, el caster nada, me lo puedes afirmar?

**Comment by Wiinter** [comment]
No gana con las sanaciones periódicas críticas
