### ISSUE TITLE
[Brujo] Daño al limpiar Afflicción Inestable

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#3202]
http://es.wowhead.com/spell=30108/afliccion-inestable
Unstable Affliction damage done when it is dispelled has been doubled, but this damage can no longer be critical.

Sigue teniendo el daño de la 4.0.6 de alrededor de 15k cuando se disipa con temple.

**Comment by efectokoleos** [comment]
arreglado
