### ISSUE TITLE
[Mago] Anillo de escarcha 82691

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3203]
http://cata.openwow.com/spell=82676
Cuando uses anillo de escarcha tarda 3 segundos en fusionarse, pero a partir de esos 3 segundos todo el que entre en el área debe quedarse congelado instantáneamente.

 Problema: sigue sin congelar, actualmente solo sirve pa dar color al asunto.

**Comment by redneo** [comment]
Arreglado
