### ISSUE TITLE
Talento "Tactical Mastery" bug (warrior arms)

### ISSUE THREAD

**Issue by addict90** [RoDNet/Bugtracker-Infinium-4.3.4#3204]
os explico un poco de que va, simplemente sirve para que cada vez que cambias de stance retengas 25 puntos de ira en vez de quedarte completamente a 0, quiere decir que por ejemplo si yo estoy en battle stance y cambio a berserker stance, poniendo un ejemplo de que tengo 100 puntos de ira y de que tengo en ese talento los 2 puntos(osea que retendría 50 puntos) cambiaría de actitud quedándome con 50 puntos.

es un talento importantísimo tanto pve como pvp, ya que un warr sin ira es completamente nulo.. y por lo que me he fijado lo que falla sobretodo es cuando se pasa de berserker stance(actitud rabiosa) a battle stance(actitud de batalla).

bueno echarle un ojo rápido, por favor ;)

saludos

**Comment by Compresor** [comment]
#2074 Duplicado, continuamos en el anterior
