### ISSUE TITLE
paladin con bug 

### ISSUE THREAD

**Issue by thorsius** [RoDNet/Bugtracker-Infinium-4.3.4#3205]
estimados primero que todo felicito por el server pero me ha pasado algo sorprendente mi paladín nivel 82 se ha quedado bugeada en corona del hielo el problema es que quedo en medio de la nada es decir no hay paisaje solo dice que estoy muerto y no puedo hacer absolutamente nada se que están ocupados pero necesito una solución ya que no quiero perder el personaje estoy atento a sus instrucciones saluda alejandro

**Comment by Monleon** [comment]
Dime el nombre de tu personaje. Y para este tipo de problemas, mejor pon abrir una consulta, dentro del propio juego

**Comment by thorsius** [comment]
No lo sabia disculpa el nombre es Predicadora saludos 

Desde Mi Windows phone 

-----Mensaje original-----
De: Monleon
Enviado: 17-01-2014 11:28
Para: RoDNet/Bugtracker-Infinium-4.3.4
CC: thorsius
Asunto: Re: [Bugtracker-Infinium-4.3.4] paladin con bug  (#3205)

Dime el nombre de tu personaje. Y para este tipo de problemas, mejor pon abrir una consulta, dentro del propio juego

**Comment by Monleon** [comment]
arreglado

**Comment by thorsius** [comment]
Gracias estimados saludos

Desde Mi Windows phone 

-----Mensaje original-----
De: Monleon
Enviado: 17-01-2014 11:54
Para: RoDNet/Bugtracker-Infinium-4.3.4
CC: thorsius
Asunto: Re: [Bugtracker-Infinium-4.3.4] paladin con bug  (#3205)

arreglado
