### ISSUE TITLE
[Mazmorras/Bandas][La Matanza de Stratholme] npc y los Mobs

### ISSUE THREAD

**Issue by Dreadwolver** [RoDNet/Bugtracker-Infinium-4.3.4#3206]
Problema: el npc Arthas miestras vuelve a la ciudad se dirige hacia abajo y se queda atascado debajo del puente, y los mobs (bichos) al ser atacados se van para abajo

http://es.wowhead.com/zone=4100
http://es.wowhead.com/npc=26499

**Comment by Aegis-** [comment]
Justo iba a reportar el mismo error ya que lo unico que me falta para sacar el draco rojo son los logros de ahi y de encerrados que aun no me fijo si funciona.

**Comment by efectokoleos** [comment]
se cae cuando se dirige a la entrada de la instance no ? va corriendo o andando?

**Comment by Aegis-** [comment]
Arthas aparece directamente en un lado donde no deberia estar(ya dentro de donde se realiza la matanza) y parece que los Npcs que estan ahi traspasan el piso y se van hasta abajo de todo y no vuelven a subir! A mi me dejo en combate 1 de los demonios de la cripta y no la pude traer para arriba de ninguna forma, y yo siendo paladin no tenia el rango suficiente para meterle ninguno de mis skills de tan profundo que se fue.

**Comment by Monleon** [comment]
Ya funciona correctamente
