### ISSUE TITLE
[Talento-Cazador]T.N.T.

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3208]
Nombre: T.N.T.
Enlace: http://wow.freakz.ro/spells.php?spell=56336
Descripción: Cuando inflinges daño periódico con Trampa de inmolación, Trampa explosiva o Flecha negra tienes un 20% de activar Bloquear y cargar.
Problema: Flecha negra activa Bloquear y carga aún cuando no se tenga el talento T.N.T. tomado, por lo tanto es un bug beneficioso para los cazadores.
Observación: De acuerdo al changelog ha sido reparado ultimamente, como tambien aparece en mi anterior reporte (ya cerrado): https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2475
Pero el talento sigue bug y sigue obteniendo un cazador el beneficio sin colocar los talentos.

**Comment by redneo** [comment]
Ahora si, arreglado
