### ISSUE TITLE
logro del bastion crepuscular

### ISSUE THREAD

**Issue by melcalla** [RoDNet/Bugtracker-Infinium-4.3.4#3209]
http://es.wowhead.com/achievement=4850

http://es.wowhead.com/npc=45992 
este no tira el logro , y es necesario la poder hacerlo en hero

http://es.wowhead.com/npc=43735/monstruosidad-de-elementium
y este logro también es necesario para el logro.

pero ninguno de los dos da el logro necesario para poder hacer la banda en otro nivel.

**Comment by Pegasu5** [comment]
Ehh si que dan los logros todos lo bosses, antes de ayer lleve nuevos jugadores a la banda a sacar el logro de BC

**Comment by Compresor** [comment]
Dan logro
