### ISSUE TITLE
[Brujo] Diablillo

### ISSUE THREAD

**Issue by Eressear** [RoDNet/Bugtracker-Infinium-4.3.4#321]
![img_1442](https://f.cloud.github.com/assets/4940891/771526/7c46562a-e8e5-11e2-8043-285a4bd08e72.jpg)
![img_1444](https://f.cloud.github.com/assets/4940891/771556/1920f9aa-e8e6-11e2-81af-eca440c8fbb1.jpg)

Acabo de invocar al Diablilo (http://es.wowhead.com/spell=688) con un huargen al nivel 1 (y todos los problemas que conlleva estando la zona como está) y el demonio en cuestión lleva una ESPADA (?!) en la mano derecha. Acabo de comprobar que pasa al menos tambien con los brujos humanos.

**Comment by SherBlader** [comment]
y el diablillo con la espada?
la captura?

**Comment by Eressear** [comment]
No puedo hacer capturas de pantalla, así que ahí tienes fotos con el móvil xP
Estas están hechas con un Gnomo, así que supongo que pasa con todas las razas.

**Comment by DatJetto** [comment]
Joe no os quejáis nada, por una espada, CREMATORIA PARA LAS PETS!! y los jabalíes.

**Comment by Eressear** [comment]
No es una queja. De hecho a mi me hizo bastante gracia y ni mucho menos me molesta, pero lo reporto para que lo sepan. Si no lo quieren cambiar, no es ningun problema.

**Comment by SherBlader** [comment]
http://es.wowhead.com/spell=688/invocar-diablillo
el original no lleva una..

**Comment by redneo** [comment]
El bicho azul tiene dos hachas molonas!

**Comment by redneo** [comment]
fixed
