### ISSUE TITLE
[Items/Objetos] Abalorio: Balanza de vida

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3215]
Buenas.
• Nombre: Balanza de vida
• Enlace: http://es.wowhead.com/item=68915 
• Descripción: Equipar: Almacena hasta 17095 p. de salud extra de los hechizos que te sanan más que tu salud máxima.
Uso: Libera al instante toda la salud almacenada en la balanza de vida como autosanación. (1 Min Reutilización)
• Problema: No funciona el efecto. Al usarlo sana 1 punto de vida.
Gracias y hasta luego!

**Comment by Monleon** [comment]
Ya debería funcionar.
