### ISSUE TITLE
[Firelands] Shannox y Desmembrador

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3218]
Un pequeño detalle de este encuentro.
Tanto Shannox http://www.wowhead.com/npc=53691 como Desmembrador http://www.wowhead.com/npc=53694 no deberían poder ser taunteables

**Comment by Necrofilo** [comment]
Ahora subo el vídeo del boss.

**Comment by melcalla** [comment]
en normal si se pueden tantear en hero es cuando no se puedes según las guias

**Comment by Monleon** [comment]
Tampoco pueden ser provocados en modo normal.

Se agradece el vídeo.

**Comment by searum** [comment]
fix
