### ISSUE TITLE
[ICC] Jefe Lord Tuetano

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#322]
Lord Tuétano http://es.wowhead.com/npc=36612/lord-tuetano

Bueno, este boss nos ha matado a todos casi de un golpe.

Con un ataque automatico me ha hecho 43k (en forma de oso)
![wowscrnshot_070913_192811](https://f.cloud.github.com/assets/4895839/772024/60a3794e-e8f8-11e2-80bb-fdd04be6f725.jpg)

Y Con Tajo de hueso http://es.wowhead.com/spell=69055
me ha hecho 78k (en forma de oso)
![wowscrnshot_070913_192813](https://f.cloud.github.com/assets/4895839/772028/791603ac-e8f8-11e2-9a46-5951bc267b8d.jpg)

A todos nos mato casi instantaneamente, por lo que me supongo que no se puede hacer por el daño que inflinge, es extremadamente alto al que deberia hacer.

**Comment by Alfonn** [comment]
Síp, añado que las mazmorras heroicas de LK pegan más de 20k y críticos de 30k...

**Comment by ghost** [comment]
Pasa lo mismo con las raids de Burning Crusade xd.

**Comment by searum** [comment]
Teneis 140k de vida no os quejeis XD, se mirara.

**Comment by ghost** [comment]
Pero... a mi me hizo un ataque de 150k xd

**Comment by efectokoleos** [comment]
daño arreglado
