### ISSUE TITLE
[Firelands] Spell que no divide el daño entre jugadores

### ISSUE THREAD

**Issue by redneo** [RoDNet/Bugtracker-Infinium-4.3.4#3220]
El npc http://es.wowhead.com/npc=53185 Sobrestante despiertallamas lanza un spell http://es.wowhead.com/spell=100431 el cual Inflige 185000 to 215000 p. de daño de Fuego repartidos entre los objetivos enemigos en un radio de 65 m frente al taumaturgo.

El problema es que no reparte el daño entre los enemugos en un radio, mete ese daño a quien le pille, con lo cual, casi probablemente mata a la raid.

**Comment by Necrofilo** [comment]
Añado imagen:
![wowscrnshot_011914_171806](https://f.cloud.github.com/assets/6006693/1954101/d6ed2c20-81ce-11e3-9342-48d73ff4221c.jpg)

**Comment by searum** [comment]
fix
