### ISSUE TITLE
[Abalorio firelands] Condensador de relámpagos de pulso variable

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3221]
Descripción del abalorio:
![sin ttulo](https://f.cloud.github.com/assets/6006693/1955718/c7f4b1d4-81ec-11e3-82df-7d8f58d7379d.png)

Problema: ni lanza la descarga de relámpagos (tiene prob. al 0%) ni acumula las cargas (deben subir hasta 10, cada carga aumentar 1125p. de daño y una vez llegadas a 10 quedarse hasta que deje de usarse).

**Comment by Monleon** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3978
