### ISSUE TITLE
Loot incorrecto en Firelands (dropea item de HC en NM).

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3222]
Bien, el problema con el loot es el siguiente:

 -Los bosses de Fireland en dificultad normal, están dropeando este item: http://es.wowhead.com/item=69815 . Dicho item, solo se debe dropear en modo heróico, siempre y cuando estés en la siguiente misión: http://es.wowhead.com/quest=29270 . Son como los fragmentos de escarcha para la Shadowmourne en la 3.3.5a, solo se podían despojar si estabas en su correspondiente misión.

 -El item que debería dropear en dificultad normal, es este: http://es.wowhead.com/item=71141 , el cual sirve como objetivo de la misión: http://es.wowhead.com/quest=29135 .

Si esto queda así, no hará falta jugar modo heroico para sacar el bastón legendario, a la vez que no se podrá seguir la cadena de quests porque no dropea lo correcto en modo normal.

**Comment by Monleon** [comment]
Vamos por partes.

Supongo que habrás observado que el primer mob derrotado de Tierras de Fuego no da la misión inicial de la cadena del bastón legendario. Por lo que para no causar inconveniente mientras esta no esté implementada, creemos conveniente que suelten ese objeto de misión al ser despojados.

Segundo, los dos tipos de objetos de misión necesarios para dos misiones distintas del bastón pueden ser despojados tanto en modo normal como en heroico. La diferencia por ejemplo en las cenizas, que supongo que te refieres a eso, es el número de objetos que pueda soltar cada jefe en función del tamaño de la banda y su dificultad.
A día de hoy como solo está abierta el modo 10n, el drop de los bosses está ajustado al tamaño y dificultad de la misma.

**Comment by Necrofilo** [comment]
Es que yo tengo la misión: http://es.wowhead.com/quest=29135
