### ISSUE TITLE
[Paladin-Talentos] Deber Sagrado

### ISSUE THREAD

**Issue by Aegis-** [RoDNet/Bugtracker-Infinium-4.3.4#3223]
El talento de la rama proteccion del paladin "Deber Sagrado" no funciona como deberia, te da el buff que dura 10 segundos del siguiente escudo del honrado critico, pero al usarlo este no pega critico.

**Comment by Compresor** [comment]
Te agradecería que pusieras la id de la spell

**Comment by Aegis-** [comment]
Ya funciona. Pero el Escudo del Honrado hace un daño ridiculamente bajo...Ya lo reportaron pero no le dieron respuesta.

**Comment by Kiritoo** [comment]
Esto está arreglado.
