### ISSUE TITLE
[bonus-set chaman] Improved Lightning Shield - 100956

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#3225]
Nombre: Improved Lightning Shield

Enlace: http://wow.freakz.ro/spells.php?spell=100956

Descripción:  
When your Lightning Shield is triggered by receiving damage, a charge will be generated rather than consumed, up to a maximum of 3.

Problema: no funciona nada,las cargas de escudo se gastan al recibir daño , cuando debería  de aumentar hasta 9

nota: entre este bug y el #2400 nos impide usar nuestra mejor habilidad elemental http://www.wowhead.com/spell=88766/fulmination en cuanto nos pegan, ya que te quedas si escudos con los 2 bug

**Comment by Compresor** [comment]
Bonus de 4 piezas de los sets de PVP Implcable y sañoso de chaman elemental: http://es.wowhead.com/itemset=-335, http://es.wowhead.com/itemset=-386

**Comment by efectokoleos** [comment]
arreglado
