### ISSUE TITLE
MISION  Thalorien Buscalba

### ISSUE THREAD

**Issue by conqueron** [RoDNet/Bugtracker-Infinium-4.3.4#3226]
http://es.wowhead.com/quest=24535/thalorien-buscalba

problema: la mision indica que debo ir a buscar el cadaver de un elfo antiguo  Thalorien Buscalba y lo malo es que el cadaver no aparece ni su alma

**Comment by Compresor** [comment]
#2817 #2544 Repetida. Por favor, antes de reportad comprovad que no estén reportadas
