### ISSUE TITLE
[Misión] Huargen La batalla por la ciudad de Gilneas

### ISSUE THREAD

**Issue by nihilux** [RoDNet/Bugtracker-Infinium-4.3.4#3228]
Hola.
La misión La batalla por la ciudad de Gilneas (http://es.wowhead.com/quest=24904/la-batalla-por-la-ciudad-de-gilneas) está bug.
Al comenzar la misión te la da completa sin tener que hablar con Krennan. Al no poder hablar con él, la tropa no entra y las puertas no se abren. No se puede entrar a la ciudad de forma normal, he tenido que entrar por un lado por mar. Las barricadas siguen en pie por lo que no se puede entregar la misión.
Debería ser así: https://www.youtube.com/watch?v=sYd3fkFeuV4
Por favor, arreglenlo pron.to.
Gracias de antemano

**Comment by Monleon** [comment]
Las misiones de los huargens ya funcionan perfectamente de inicio a fin
