### ISSUE TITLE
[Rogue asesinato] Daño x4 mutilar (se está abusando en PvP).

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3229]
Mutilar (ID=1329).
Descripción: Inflige un 98% de daño con arma más 196p. de daño extra con cada arma.

 TESTEO:
-Con mi rogue, en estadísticas pone que mi daño con mano derecha es de 2665 - 3202.
 Eso quiere decir que el daño de mutilar con mano derecha, debería de infligir un máximo de 3400 de daño aprox. (a objetivo sin temple).

Problema: al testearlo con un compañero que se ha quitado todo el temple, mutilar inflige 12500 de daño, cuatro veces más de lo que debe infligir.
 Al probarlo con temple, como el daño infligido es de aprox. 6300 (la mitad que sin temple).

Resumen del problema: Mutilar está haciendo el daño x4.

Dejo imágene testeando sin temple:
![sin temple](https://f.cloud.github.com/assets/6006693/1968607/60ef1e4e-82e5-11e3-9fde-f7338d744fa1.png)

**Comment by Kiritoo** [comment]
No quiero ver discusiones si esto pega más o si esto pega menos, aquí se reporta, se comprueba y si esta mal se repara.
No quiero ver a nadie decir si esta clase pega más o esta otra pega menos, para eso os dais el correo y os enviais unos e-mails aquí no.
Estoy testeando este spell sin talentos, armadura ni nada y está pegando el doble. Se repará lo antes posible.
Saludos.

**Comment by Dekadencee** [comment]
Debería estar fixeado, si hay algún problema más abrid ticket.
