### ISSUE TITLE
LOGRO Los baldios del Sur

### ISSUE THREAD

**Issue by Varga9** [RoDNet/Bugtracker-Infinium-4.3.4#323]
Es imposible realizar este logro debido a que Horado Rajacieno no se puede descubrir, he estado viendo guias donde se supone que el punto exacto es la entrada a la Maz que allí se encuentra.
La implicación de no poder realizar este logro es, que tampoco se realiza Explora Kalindor.

http://es.wowhead.com/achievement=4996/los-baldios-del-sur

**Comment by searum** [comment]
fix
