### ISSUE TITLE
[Abalorio] Insignia de conquista de Gladiador implacable

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3231]
Objeto: Insignia de conquista de Gladiador implacable
ID: 70404 (wowhead)

Problema este abalorio está activandose prologadamente sin cesar su efecto nunca termina.

Observaciones: solo sucede con los abalorios implacable y al menos con el de agilidad el problema es así.

**Comment by Compresor** [comment]
Segun pone en los comentarios tiene un 15% de saltar y tiene un cd interno de 45 segundos
http://es.wowhead.com/item=70404#english-comments
