### ISSUE TITLE
[Mago] Bonus (2) T12.

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3232]
Descripción: Tienes la prob. de invocar un reflejo exacto que te ayude en la batalla durante 15 s al lanzar Descarga de Escarcha, Bola de fuego, Descarga de Pirofrío o Explosión Arcana.

Problema: A parte de tener la prob. bastante baja (cuesta muchísimo de que salga), la copia se queda quieta, en algún caso lanza un hechizo y seguido va a pegar a mele.

![wowscrnshot_012214_163116](https://f.cloud.github.com/assets/6006693/1976423/3dde19f0-838a-11e3-8fa8-8e0111aa5e95.jpg)

**Comment by redneo** [comment]
Esto se arregló, creo recordar.
