### ISSUE TITLE
[Shadow priest] Shadow Apparition (Aparición sombría) //2 problemas\\.

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3234]
ID rango 1= 78202
ID rango 2= 78203
ID rango 3= 78204

Descripción resumida:
Tiene un 12% prob. de invocar una versión sombría del sacerdote, el cual va lentamente hacia el objetivo afectado por ''Palabra de las sombras: Dolor'' y al tocar al objetivo explota infligiendo 4629p. de daño.

Problema 1: No está estallando, en su lugar se queda pegando a mele sin estallar y retroceden el casteo del objetivo.

Problema 2: Las apariciones sombrías deben tener SOLO 5p. de hp, actualmente están saliendo con 100k de hp.

**Comment by Compresor** [comment]
IDs de las apariciones sombrias: http://es.wowhead.com/npc=46954#english-comments

**Comment by Necrofilo** [comment]
Las del reporte las he sacado de cata.openwow

**Comment by Compresor** [comment]
Los IDs del talento estan perfectas, solo que había visto qe te faltaba la id de las apariciones.

**Comment by Necrofilo** [comment]
Ah, lo siento no me había fijado en eso :S

**Comment by Monleon** [comment]
Arreglado, falta compilar
