### ISSUE TITLE
[Rogue asesinato] Heridas envenenadas (ID: 79134).

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3235]
Spell: http://cata.openwow.com/spell=79134
Descripción:
Venomous Wounds
Rank 2
Instant
Each time your Rupture or Garrote deals damage to an enemy that you have poisoned, you have a 60% chance to deal 1 additional Nature damage and to regain 10 Energy. If an enemy dies while afflicted by your Rupture, you regain energy proportional to the remaining Rupture duration.

Problema: En vez de un 60%, está teniendo casi un 100% de prob., con lo cual cada vez que al objetivo le afecta un tick de Ruptura o Garrote, infligen 3000p. de daño extra y recuperan 10p. de energía.

**Comment by addict90** [comment]
no es verdad, eso de 100% lo dices tu, testealo con un simple garrote y veras que no siempre salta,
lo que pasa que un 60% logicamente es un chance muy alto, peor no quiere decir que por regla de tres sea de 10 6 veces tick
no, simplemente mas del 50% de posibilidades de que salte peor no salta siempre fijo, testeado

**Comment by Necrofilo** [comment]
Pues mira que tu compañero Jiang me confirmó que estaba saltando el 100% de los casos.
