### ISSUE TITLE
[Habilidad - Chamán] Tótem garra de piedra (#5730)

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3236]
Descripción: 
Summons a Stoneclaw Totem with 6186 health at the feet of the caster for 15 seconds that taunts creatures within 8 yards to attack it. Enemies attacking the Stoneclaw Totem have a 50% chance to be stunned for 3 seconds. The Stoneclaw Totem also protects your other active totems with a shield that absorbs up to 4143 damage.

Problema: el efecto que tiene una prob de 50% de aturdir 3 sec al atacarlo está dejandote en un estado de perma-stunt y te quedas sin poder hacer nada.

Observaciones: perjudica mucho al hacer arenas ya que la unica forma de salir de ese bug es relogeando pero no sin antes salir de combate porque si te sales así pierdes la arena, recomiendo desactivar ese efecto o dicho tótem hasta repoaración

**Comment by redneo** [comment]
Cual es la id del spell del totem?

**Comment by Pegasu5** [comment]
http://wow.freakz.ro/spells.php?spell=5730&name=stoneclaw-totem

**Comment by Dekadencee** [comment]
Fixed
