### ISSUE TITLE
[NPC's/Mobs][Logros] Ancestro Lobazul

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3237]
Buenas.
• Nombre: Ancestro Lobazul
• Enlace: http://es.wowhead.com/npc=30368
• Problema: No puedo llegar donde está el PNJ por la pared invisible de Conquista de Invierno.
• Observaciones: Reporté lo de la pared invisible aquí https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3198 es la misma que impide el paso a La Cámara de Archavon.
Muchas gracias!

**Comment by redneo** [comment]
Creo que ya se puede llegar a el así como a la camara. Miralo cuando haya caido el server y me lo comentas por aqui. Si es caso, borro el objeto invisible. (60070)

**Comment by ghost** [comment]
Si, ya se puede pasar, muchas gracias!!!
Saludos!
