### ISSUE TITLE
Bug positivos y negativos de nuestros rogues

### ISSUE THREAD

**Issue by Antihackers** [RoDNet/Bugtracker-Infinium-4.3.4#3238]
Hola,buenas quería decir tanto las cosas positivas del pícaro Asesinato/Combate/Sutileza, en PvP y en PvE, primero expondré el Asesinato:

-Asesinato PvP: Apenas veo problemas, quizás más para lo positivo, ya que tiene el talento [Heridas envenenadas](http://es.wowhead.com/spell=79134/heridas-envenenadas), quizas tenga una probabilidad mayor que como dice el talento (60%),ya que se activa bastante. Otra cosa es [Mutilar](http://es.wowhead.com/spell=1329/mutilar), es un golpe que pega más de lo que debe pegar, quizas en PvE si pega bastante más,podría llegar con el equipo que tenemos la mayoría entre los 10k-30k de golpe, mientras que golpea a veces 70k,pero bueno,ya descartando estas 2 cosas,lo demás va bien, a lo mejor podría tener el fallo de meter los venenos, sobretodo el Mortal (http://es.wowhead.com/spell=2823/veneno-mortal), ya que con una daga de mano izquierda 1.40, podría meterse los 5 stocks de veneno rapidamente.

-Asesinato PvE: Como he comentado antes, por el daño del [Mutilar](http://es.wowhead.com/spell=1329/mutilar), el daño aumenta bastante más, solamente eso, no tengo que comentar más.

-Combate PvP: El combate va muy mal, tanto en PvP o en PvE, no quiero mencionarlo en PvP, ya que no se usa, pero su mayor fallo son dos talentos de los que tenemos, que son: [Precisión] y [Golpe revelador](http://es.wowhead.com/spell=84617/golpe-revelador), el talento [Precisión] no funciona,no nos da el indice de golpe, mientras que [Golpe revelador](http://es.wowhead.com/spell=84617/golpe-revelador) debería aumentar  la eficacia de un remate un 35%,es decir, si nuestro [Eviscerar](http://es.wowhead.com/spell=2098/eviscerar), golpea 35.000, entonces debería aumentar el daño un 35%. Pero el problema es que este talento no funciona, y se quita hasta con los propios golpes automáticos, y no deja golpear remates fuertes.

-Combate PvE: Lo mismo que en PvP, estos talentos hacen que falle el daño de esta rama.

-Sutileza PvP: Ahora hablo de la rama más fuerte del PvP,tanto en Cataclysm,como Mist Of Pandarian. Tiene varios fallos en el daño, ya que por ejemplo, un Asesinato no debería poder pegar más que un Sutileza, esta rama está creada para el PvP, y creada para tener el mayor burst. Nuestro mayor golpe es [Emboscada](http://es.wowhead.com/spell=8676/emboscada), y no pega lo que debería de golpear, es un ataque que apenas pega, quizás hasta la propia [Puñalada](http://es.wowhead.com/spell=53/punalada) llegaría a golpear de un crítico más que esto. ¿Qué pasa si esta fallando nuestra [Emboscada]? Pues simple, no tenemos el burst, ni podremos usar como debemos usar [Danza de las Sombras](http://es.wowhead.com/spell=51713/danza-de-las-sombras), y no haremos apenas daño. Aparte de esto, nuestros talento [Recuperación mágica], no se si funcionará, pero apenas veo que regenere energía el pícaro, casi que se consigue mas energía en Asesinato. Y ya de final, nuestro talento [Honor entre ladrones](http://es.wowhead.com/spell=51701/honor-entre-ladrones), no se si nos da el 5% de crítico que dice la habilidad,y los puntos de combo que debería de dar cada 4s por crítico de tus compañeros, a veces no los da,y toca volver a esperar 4s.

-Sutileza PvE: Lo mismo que en el apartado anterior, y Suti PvE, no se usa hasta DS (Dragon Soul), donde tocará usarlo en un boss determinado por el burst.

Y ya no tengo más que decir, son fallos de talentos sobretodo, y en lo que es una habilidad importante, es la Emboscada y Mutilar, una beneficia al pícaro,y otra lo empeora, y por esto hoy en día vemos dentro del servidor a la mayoría de los pícaros en Asesinato, por que no queda más que otra que dejar de lado el Combate para PvE,y el Sutileza en PvP,cuando son las ramas que identifican el pícaro.

Un saludo,y gracias por la paciencia.

**Comment by Necrofilo** [comment]
Se te ha olvidado el envenenar del asesinato, en cuanto acabe la raid lo iba a reportar con el testeo ya realizado.
