### ISSUE TITLE
Boss Descenso de Alanegra: Maloriak (spell: Chorros de magma)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3239]
Boss: http://es.wowhead.com/npc=41378

La spell es.wowhead.com/spell=78194/chorros-de-magma está golpeando x3, su ataque de fuego tanto el inicial como el periódico golpean 3 veces.

Además está lanzando por los aires al jugador que es golpeado por esta spell, lo que no debería ocurrir tampoco, ya que prácticamente mata al jugador por la caída.

P.D. El bug de esta spell es común tanto a modo normal, como al modo heroico

**Comment by Monleon** [comment]
Nada de eso está sucediendo ahora...
