### ISSUE TITLE
Bug con las misiones de las Enanas/os.

### ISSUE THREAD

**Issue by Kagome** [RoDNet/Bugtracker-Infinium-4.3.4#324]
Las misiones de los Enanos,no salen en el Mapa, no estan bien programadas y hay algunas bugs.
![wowscrnshot_070913_164904](https://f.cloud.github.com/assets/4942077/772773/bba6a1e4-e91c-11e2-8ea6-06ab78ea64b4.jpg)
![wowscrnshot_070913_164908](https://f.cloud.github.com/assets/4942077/772774/bbe0e30e-e91c-11e2-8923-a83b885e57a9.jpg)

Aquí dejo como hay una Bug y no se reflejan en el mapa. No seguí leveándola por que no hay misiones que hacer.

**Comment by crowel** [comment]
Hola si que salen en el mapa, además de una extensa explicación que da la descripción de la misión que te dice el sitio a donde debes ir.
Un saludo.
