### ISSUE TITLE
[Brujo Demonologia] Talentos y pets bug

### ISSUE THREAD

**Issue by Bichoculiao** [RoDNet/Bugtracker-Infinium-4.3.4#3240]
Talentos:
Fatalidad Inminente: No reduce el coldown de metamorfosis
Aura de Aprension: No hace nada el talento, antes funcionaba pero despues que pusieron en el changelog que si lo hacia dejo de hacerlo, xD
Mascotas: Daño base que da verguenza, pegan criticos de 100 estando en lvl 85  con mucho spell power, no se beneficien correctamente del spell power y las habilidades por ende no hacen el daño que deberian hacer como corresponde, como las del guardia vil, que deberia ser daño de arma + spell power.

Esas son las unicas 3 cosas que faltaria para la rama demonologia creo :D Gracias por su trabajo.

**Comment by Compresor** [comment]
Reporta cada bug en un issue diferente.
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
