### ISSUE TITLE
Sanacion Relampago

### ISSUE THREAD

**Issue by eLdOne** [RoDNet/Bugtracker-Infinium-4.3.4#3241]
Una de las primerasmisiones la de sanacion relampago que tienes que echarsela a los guardias yo no la he podido hacer no se si alguien la abra echo

**Comment by Compresor** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
