### ISSUE TITLE
[Pícaro] maestro envenenador

### ISSUE THREAD

**Issue by yercay** [RoDNet/Bugtracker-Infinium-4.3.4#3243]
maestro envenenador, talento del picaro en la rama asesinato está bug, cuando salta saca al propio picaro de stealth, un bug bastante jodio y que hace la rama asesinato injugable en la faceta PvP

http://es.wowhead.com/spell=58410

**Comment by addict90** [comment]
no se si es eso, o simplemente cualquier dot que dejes en el target, garrote, rupture, etc hasta que no acaban los dots, no puedes salir de combate aunque el enemigo no te este ni atacando.

**Comment by yercay** [comment]
No, es ese talento, esta comprobado, si tu le dejas garrote, ruptura o cualquier dot que haga daño en el tiempo del picaro hace que salte este talento, y el talento te saca de invisible.

Realmente si puedes salir de combate, eso solo pasa en los muñecos de entrenamiento, en pvp puedes salir de combate dejandole al contrario ruptura o garrote, lo que pasa es que al hacerte invisible este talento te saca y no se por que...

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
