### ISSUE TITLE
descenso de ala negra

### ISSUE THREAD

**Issue by melcalla** [RoDNet/Bugtracker-Infinium-4.3.4#3245]
http://es.wowhead.com/search?q=descenso+de+alanegra
faucemagma :http://es.wowhead.com/npc=41570
nos tiro 6 lots y solo dio 35 puntos de valor

**Comment by Kiritoo** [comment]
Y el problema está en? Que da mucho loot?

**Comment by Pegasu5** [comment]
Sí estan dando de 4 a 6 piezas(sucedió ayer en BC) y las mas raras, y también si creo el valor obtenido es muy poco por hacer estrategias a los bosses.

**Comment by Kiritoo** [comment]
El valor es el correcto para la version 4.2 que son 35 puntos por boss en BC y Descenso.
¿Los objetos que dropeo en que dificultad?

**Comment by melcalla** [comment]
en cierta manera es aprovechamiento de un bug y no quiero tener problemas con ellos , por eso aviso.

**Comment by paellaencol** [comment]
Nosotros fuimos esta semana en heroico y nos dio 2 piezas de loot como de costumbre. ¿Qué fuisteis vosotros a faucemagma normal?

**Comment by Pegasu5** [comment]
En el caso de mi guild se realiza primero la normal y luego la hero, y en comparación con la hero la normal da mucho loot

**Comment by redneo** [comment]
Cambiado los loots de descenso en 10N y 10H cada boss da lo que tiene que dar (2 items o 2 items mas chapa)

**Comment by redneo** [comment]
Cambiado los loots de descenso en 10N y 10H cada boss da lo que tiene que dar (2 items o 2 items mas chapa)
