### ISSUE TITLE
[Bug talento] T.N.T (cazador)

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#3246]
Bueno, pues este talento (T.N.T) salta sin necesidad de ponerle los puntos, pudiendo poner esos puntos en Uno con la naturaleza para así tener 3 disparos explosivos haciendo más daño del que debiera.

![wowscrnshot_012414_162736](https://f.cloud.github.com/assets/6329431/1995932/b7a86adc-850c-11e3-8d73-7eb5b5d557b6.jpg)

![wowscrnshot_012414_162811](https://f.cloud.github.com/assets/6329431/1995935/bc7c5316-850c-11e3-835e-3a3fb47671de.jpg)

**Comment by UkfNonXtop** [comment]
Yo creo que está más que claro, pero lo peor que todo es que hay gente que está beneficiándose de este bug, estaría bien que le echaraís un vistazo.
Un saludo, Ukf

**Comment by UkfNonXtop** [comment]
Adjunto una imagen donde se ve la utilización de dicho bug por parte de otros cazadores. Saludos
![abuso de bug](https://f.cloud.github.com/assets/6492905/2002832/c24eed68-8614-11e3-84d0-c750d6b2b600.jpg)

**Comment by Jhovanni** [comment]
UkfNonXtop esto es un reporte de bugs, no es un foro de denuncias a jugadores.
El talento ya ha sido reportado dos veces, una de ellas menciona que ha sido solucionado en el changelog, pero no es así, por lo tanto ha sido reportado de nuevo:
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3208

Hay que revisar antes en el bugtraker si ya está el tema, así nos beneficiamos todos para hacer el trabajo al equipo más sencillo.

**Comment by UkfNonXtop** [comment]
Gracias por el aporte, es de bien saber que el foro tiene su parte para "Denunciar jugadores" el cuál conozco de sobra, y si por tanto si ves la foto aquí y no allí es que ni mucho menos estoy haciendo una denuncia o no me interesa denunciar a este jugador, simplemente estoy mostrando que al primer cazador que me da por revisar talentos en Sv se esta aprovechando del bug, lo cuál muestra que viene a ser un tanto común.

De todos modos siento las molestias que haya podido ocasionar, Saludos Ukf
