### ISSUE TITLE
[Brujo Demonologia] Aura de Aprension

### ISSUE THREAD

**Issue by Bichoculiao** [RoDNet/Bugtracker-Infinium-4.3.4#3247]
Descripcion: Aura de Aprension
Cuando aterriza tu mano de Gul'dan todos los enemigos en un radio de 4m quedaran enraizados durante 3 seg y aturdidos la misma duracion si siguen en el interior del aura  de la maldicion de Gul'dan 6 segundos despues.

Bug: No hace nada.

**Comment by Compresor** [comment]
Ids por favor
