### ISSUE TITLE
[Brujo Demonologia] Mascotas

### ISSUE THREAD

**Issue by Bichoculiao** [RoDNet/Bugtracker-Infinium-4.3.4#3248]
No se benefician del Spell power del brujo en ningun aspecto, y el daño base de las habilidades del guardia vil que dice "daño de arma" se refiere a la que lleva el brujo no? bueno tampoco pega lo que deberia con skills ni en melee, eso, gracias

**Comment by Compresor** [comment]
Ids, formulas, etc?

**Comment by Bichoculiao** [comment]
lo siento me dijieron que los reportara no que dijera como arreglarlos, sino donde puedo avisar que estan bug? o buscar esa informacion que pides?

**Comment by sprin69** [comment]
esto pasa en todas las pet d brujo

**Comment by Monleon** [comment]
Ahora ya reciben una parte proporcional a las estadísticas del brujo.
