### ISSUE TITLE
Daño de la racial del Goblin

### ISSUE THREAD

**Issue by Navalagamella** [RoDNet/Bugtracker-Infinium-4.3.4#325]
Pues ya he reportado el error de esta habilidad https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/252. Y en cierta medida se ha arreglado, varía con el poder de ataque y el poder de hechizos, pero sigue haciendo ese daño absurdo
![wowscrnshot_071013_133931](https://f.cloud.github.com/assets/4733643/774353/ca68b1ca-e955-11e2-8436-566562a2c984.jpg)

**Comment by DatJetto** [comment]
Bajadle el daño por favor D: está demasiado over.

**Comment by searum** [comment]
cierro esto porq esta fix
