### ISSUE TITLE
[Atributos] Armadura over

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3250]
Nombre: Armadura
Descripcion: Armadura – La manera en la que la armadura mitiga el daño no va a variar, pero el atributo de armadura ha sido reequilibrado para reflejar los cambios a la curva de armadura en Cataclysm. Como resultado, la armadura de bonificación descenderá en general. También vamos a cambiar la diferencia de mitigación entre los tipos de armadura para que placas no ofrezca mucha más protección que malla, cuero y tela.
Fuente: http://todowow.com/noticias/cambios-de-atributos-en-cataclysm/

Problema: La armadura parece como si fuera lich esta reduciendo demasiado el daño fisico

Testeo: Use gople heroico que tiene un daño fijo en mi caso 5992 si le pego a un jugador sin temple ni armadura, ahora se coloca set pve y llega a 29690 armadura 53.25% reduccion daño fisico (0 temple aclarando dudas) y mi daño de golpe heroico deberia de bajar a 2801,26p el caso es que esta bajando mas de la cuenta y hago es 2227p

Comented: Algunos diran: ¨bad no es gran cosa¨ mi pala heler llega a 38k armadura y mas el temple 4k creeme me aguanto 4 meles en bg :D

**Comment by Pegasu5** [comment]
Entonces el temple si anda bien? pregunto me parece que no es normal que un medio sañoso con una daga impla te quite 33k habiendo arreglado las spells segun el changelog

**Comment by F4NT4SM4** [comment]
nose solo testee armadura :s

**Comment by Compresor** [comment]
#359
Hasta hace poco, golpe heroico no respetaba el temple tenía entendido

**Comment by F4NT4SM4** [comment]
testee fue armadura, no temple! 
armor = armadura

**Comment by Jhovanni** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/359
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2807

**Comment by Jhovanni** [comment]
El problema parece estar en la armadura, pues he hecho pruebas tambien por mi parte, y la reducción que obtiene es bastante por los daños físicos. Cosa que no sucede con hechizos mágicos.

**Comment by cibernaco** [comment]
No hace falta irse a paginas no oficiales, en los foros oficiales (y en algún hotfix si no recuerdo mal), están claramente indicadas las nuevas formulas (eran nuevas cuando salio cata) no lineales del calculo del % de reducción de daño de la armadura y del temple, ahora es tarde pero mañana los buscare, también para estas cosas esta Theorycrafting.

**Comment by cibernaco** [comment]
Para el temple, directamente en la notas del parche, si no sabeis donde mirarlas decirlo que os linkeo todas las notas de parche y lo normalmente más importante todos los hotfix.

The resilience formula was changed in Patch 4.1.0. Resilience is now linear and no longer offers increasing returns.

And formulas for 4.1 is:

y = 1 - 0.99 ^ ( x / 79.12785 )

Resilience

The resilience cap is currently 9523. Equipping 9523 resilience will provide 100% damage reduction. Having more than 9523 resilience equipped is overkill and provides absolutely no benefit. However, equipping this amount of resilience is currently impossible. In Patch 4.1.0, diminishing returns on resilience will provide a real resilience cap.

Este es el último cambio en el temple.

Y este de aquí abajo el último cambio en la formula de la reducción de daño por armadura.

Pongo enlace externo al oficial por que sin explicación es difícil de entender; el por que si mi armadura reduce 1% de daño, realmente reduce "algo más" por poco que sea, y el por que la "armor" no es lo único que reduce el daño fisico.

http://wowpedia.org/Damage_reduction <---- pongo este enlace por que Draztal envia a la gente del foro a este post para aclararse.

También hay un post azul que confirma la fórmula, si vais al blizztraker y os armáis de paciencia podréis encontrarlo.

**Comment by Kiritoo** [comment]
Arreglado, pendiente de compilar.
