### ISSUE TITLE
[Mazmorras/Bandas][Descenso de Alanegra] Sistema de defensa Omnitron (10 Hero)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3253]
Buenas.
• Nombre: Sistema de defensa Omnitron
• Enlace: 
Toxitron:http://es.wowhead.com/npc=42180
Magmatron: http://es.wowhead.com/npc=42178
Electron: http://es.wowhead.com/npc=42179
Arcanotron: http://es.wowhead.com/npc=42166
• Problema: Los golem nunca bajan de 99 de energía y no se desactivan, a los 3 o 4 minutos del combate están los 4 golems a la vez repartiendo tortas. Tampoco llegan a activar su escudo correspondiente.
• Observaciones: Esto es en modo Hero. Citando https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1344 a los 50 puntos se activa otro golem, a los 45 se activa su escudo, a los 25 se desactiva el escudo y a 0 puntos se desactiva el golem.
ID de Energia: http://es.wowhead.com/spell=78740
ID de apagar golem: http://es.wowhead.com/spell=78746

Desde ya gracias!

**Comment by Kiritoo** [comment]
10h o 25h?

**Comment by Pegasu5** [comment]
en 10h

**Comment by redneo** [comment]
reparado
