### ISSUE TITLE
[Hechizos/Talentos][DK Escarcha] Sangre del Norte

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3255]
Buenas.
• Nombre: 
• Enlace: http://es.wowhead.com/spell=54637
• Descripción: Transforma tus runas de sangre en runas de muerte de forma permanente. Las runas de muerte cuentan como runas de sangre, de escarcha o profanas.
• Problema: Se volvió a bugear, las runas vuelven a ser de sangre cuando cruzas portal, entras a bg o a mazmo, o cambias de continente y hay que relogear para que vuelvan las runas de muerte.
• Observaciones: Ya se habia reportado y corregido aqui https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/990
Desde ya gracias!

**Comment by searum** [comment]
fix
