### ISSUE TITLE
[Hechizos/Talentos][DK Escarcha] Maestría: Corazón congelado

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3256]
Buenas.
• Nombre: 
• Enlace: http://es.wowhead.com/spell=77514
• Descripción: Aumenta todo el daño de escarcha infligido un 20%
• Problema: Se volvió a bugear: no aumenta el daño de escarcha infligido.
• Observaciones: Ya había sido reportado y corregido aquí https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1925.
Desde ya muchas gracias.

**Comment by ghost** [comment]
:( T_T

**Comment by Kiritoo** [comment]
Esta arreglada.
