### ISSUE TITLE
glifo de disparo mortal 

### ISSUE THREAD

**Issue by matux12** [RoDNet/Bugtracker-Infinium-4.3.4#3257]
Giflo de disparo mortal : si el daño de tu disparo mortal no logra matar al objetivo con un 20% de salud o menos , el tiempo de reutilizacion de tu disparo mortal se reinicia al instante. este efecto tiene 6 segundos de tiempo de reutilizacion. 

La id del glifo no coincidira con la de wowhead debido a que fue borrado en pandaria pero es esta: 64304

Problema : no esta funcionando debido a que utilizo el disparo mortal y cuando no mata al objetivo no se reinicia

**Comment by Compresor** [comment]
Necesitamos la id del glifo

**Comment by Jhovanni** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2446

**Comment by Pegasu5** [comment]
De hecho nunca mata al enemigo xD sería también que la prob, está muy baja.

**Comment by Kiritoo** [comment]
Arreglado falta compilar.
