### ISSUE TITLE
[Cazador]Disparo automático

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3258]
Nombre: Disparo automático
Enlace: ---
Descripción: Disparo automático del arma
Problema: Cuando casteas disparo firme y el disparo automático está listo para ser lanzado (y lo hace), corta el casteo de Disparo firme. No importa si es en movimiento o estático.
Observación: Este es un reporte de bug diferente a los ya hechos por el problema de retroceso sufrido por daño. En este caso habla de un bug que sucede al estar parado, con aspecto de halcón y simplemente disparando. Aunado al problema de retroceso en casteos, el problema de los casteos cortados es mayor. Hice pruebas en rama supervivencia y no sucede lo mismo con disparo de cobra ni firme.
Disparo firme (http://es.wowhead.com/spell=56641)

**Comment by cibernaco** [comment]
Añado, si lo casteas usando la racial del trol o el buff de disparo rapido, se cortan el 50% de los disparos, aun mas si espameas el ataque.

**Comment by Jhovanni** [comment]
Cierro el issue pues ya no he visto tal bug.
