### ISSUE TITLE
[Talento-Cazador]Maestro tirador

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3259]
Nombre: Maestro Tirador:
Enlace: http://es.wowhead.com/spell=34487
Descripción: Cuando lanzas Disparo firme tienes un 60% de probabilidad de ganar el efecto de Maestro Tirador, que dura 30 s. Tras alcanzar 5 acumulaciones, el tiempo de lanzamiento y el coste de enfoque de tu siguiente Disparo de puntería se reducen un 100% durante 10 s.
Problema: La explicación la hizo muy bien DatJetto en un reporte anterior, pero ha sido cerrado debido a solución, sin embargo, el bug persiste tal y como fué explicado en dicho issue:
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2719

**Comment by Jhovanni** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3525

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
