### ISSUE TITLE
Bug en misión DK El Ojo de Archerus

### ISSUE THREAD

**Issue by makidavid** [RoDNet/Bugtracker-Infinium-4.3.4#326]
El Rey Exánime no te da la opción de hablar con él.

http://es.wowhead.com/quest=12636/el-ojo-de-acherus
http://es.wowhead.com/quest=12636/el-ojo-de-acherus#screenshots:id=89872

Espero haberlo hecho bien hoy :D

**Comment by redneo** [comment]
SI, lo hiciste bien, pero a mi me la completa nada mas cogerla....

Sueltala y vuelve a cogerla a ver :S

**Comment by makidavid** [comment]
Desde que se hizo el rollback se puede hacer perfectamente, gracias :D
