### ISSUE TITLE
[Hechizo-Cazador]Camuflaje

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3260]
Nombre: Glifo de disparo mortal
Enlace: http://wow.freakz.ro/spells.php?spell=63067
Descripción: Te camuflas, mezclándote con tu entorno, lo que evitará que puedan seleccionaros como objetivo de ataques a distancia a tu mascota y a ti. También reduce el alcance al que pueden detectaros las criaturas enemigas y os proporcionará sigilo mientras no os mováis.

Puedes colocar trampas bajo este efecto, pero cualquier daño que inflijáis tú o tu mascota cancelará el efecto. No se puede castear en combate. Dura un minuto
Problema: Cuando una cazador envía a su mascota a atacar, la mascota sale de camuflaje y no así el cazador.

**Comment by Pegasu5** [comment]
Los cazadores bestias vienen flipando mucho tiempo ya xD

**Comment by Compresor** [comment]
Estás hablando del glifo o del camuflaje, has puesto dos nombres diferentes en el título y en el nombre

**Comment by searum** [comment]
fix
