### ISSUE TITLE
[Brujo Demonologia] Talento: Aura de Aprension

### ISSUE THREAD

**Issue by Bichoculiao** [RoDNet/Bugtracker-Infinium-4.3.4#3262]
Descripcion: Cuando la mano de gul`dan aterriza todos los enemigos en 4m de radio quedaran enraizados durante 3 segundos y aturdidos por la misma duracion si permanecen en el area durante 6 segundos despues.

http://cata.openwow.com/spell=89605

89605
93974
93975
93986
93987

**Comment by Compresor** [comment]
Los números de debajo del link que quieren decir?

**Comment by Kiritoo** [comment]
¿Y cual es el fallo exactamente?

**Comment by Kiritoo** [comment]
Fix, falta compilar.
