### ISSUE TITLE
[Brujo Demonologia] Talento Pacto demoniaco

### ISSUE THREAD

**Issue by Bichoculiao** [RoDNet/Bugtracker-Infinium-4.3.4#3263]
Descripcion: al matar al demonio deja de aparecer el aura, es necesario retirar a la mascota y volver a invocarla un par de veces para que vuelva la aura como corresponde, y al cambiar de rama de talentos el buff persiste en la mascota a menos que se repita la misma accion.

http://cata.openwow.com/spell=47236

**Comment by Wiinter** [comment]
No funciona con el manáfago

**Comment by efectokoleos** [comment]
arreglado
