### ISSUE TITLE
[Brujo Demonologia] Talento: Fatalidad inminente

### ISSUE THREAD

**Issue by Bichoculiao** [RoDNet/Bugtracker-Infinium-4.3.4#3265]
Descripcion: No aparece el demonio y no reduce el coldown de la habilidad metamorfosis

http://cata.openwow.com/spell=85108

85106

**Comment by Compresor** [comment]
Que significa el numero de debajo del link. 
Que no aparezca el demonio es cosa de #3181

**Comment by Kiritoo** [comment]
Fix, falta compilar.
