### ISSUE TITLE
Npc no da las misones que deberia

### ISSUE THREAD

**Issue by Szajil** [RoDNet/Bugtracker-Infinium-4.3.4#3266]
http://es.wowhead.com/npc=52234 Este npc no da las misiones que deberia.
Da la primera http://es.wowhead.com/quest=29219 pero luego no da la que sigue http://es.wowhead.com/quest=29220 y no se puede seuir las cadenas de misiones...

**Comment by Kiritoo** [comment]
Arreglado tras el reinicio.
