### ISSUE TITLE
Spell warrior cargar (diminishing returns)

### ISSUE THREAD

**Issue by addict90** [RoDNet/Bugtracker-Infinium-4.3.4#3267]
spell: http://www.wowwiki.com/Charge
(por cierto leer abajo en las notas de los parches de cataclsym, no veáis lo actual que seria del mop)

pues bien lo que vengo a aclarar, es que los warrior cada vez que usamos un charge a cualquier enemigo, nos cuenta como si hubiesen sido stuneados cosa que esta mal

diminishing returns: http://www.wowwiki.com/Diminishing_returns   (abajo teneis la tabla con los diferentes dr que existen)
sacado de wowwiki

 Patch 4.1.0 (26-Apr-2011): Charge and Intercept no longer have diminishing returns on their stun effects

os lo explico brevemente con un ejemplo, si un pala tira un stun  a un enemigo de 5 segundos, ese enemigo va a tener un DR en el siguiente hechizo de stun similar que le den, por ejemplo si un rogue le mete un cheap shot de 5 seg, no le va a durar esos 5 segundos, es decir va decreciendo la duracion de esos stuns o "CCs"(que tambien se le aplica con los fears, etc) hasta que se vuelva inmune al siguiente stun que le lancen.

finalizando, un warrior si usa cargar y seguido stun de 5 segundos, no dura el tiempo que debe, cosa que lo hace completamente inutil.. un stun de 1 segundo.

teneis que quitar el dr del cargar por que no es un stun.

saludos

**Comment by F4NT4SM4** [comment]
:O es cierto estube indagando en los foro de blizzard y es como dice addict
estube engañado toda mi vida en wow con un derribar de 2s y cargar que no duraban nada por el diminishing ._:

**Comment by addict90** [comment]
a principio de parche era como decias tu, el cargar tenia 3 seg de stun, pero lo cambiaron jeje

**Comment by F4NT4SM4** [comment]
id del cargar aturdidora: 7922

**Comment by Monleon** [comment]
Nombre: Interceptar
ID:20253
Enlace:http://wow.freakz.ro/spells.php?spell=20253

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.

**Comment by F4NT4SM4** [comment]
mmm una duda al interceptar tambien le quitaron el diminishing? 
es que en le changelod solo sale cargar

**Comment by Kiritoo** [comment]
Si ambos, lo añado al changelog también para que no quede duda.
