### ISSUE TITLE
[Caballero de la muerte] Daño de la Gárgola excesivo

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3268]
id: http://wow.freakz.ro/spells.php?spell=43802

Actualmente el golpe que inflige la gárgola es muy superior a lo que debería. La formula es 150+(0.4*Poder de ataque). 

A la hora de comprobarlo con mi dk que es solo sanguinario y tiene 12k de poder de ataque, estoy pegando actualmente 14k de normal mientras que lo que debería meter es 5k según la fórmula con un golpe normal.

Aquí no he tenido en cuenta reducciones de daño por temple. Si necesitáis fotos puedo subirlas.

Un saludo y gracias

**Comment by addict90** [comment]
deberias ver el daño full ruthless en arenas es acojonante xD

**Comment by Monleon** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3133
