### ISSUE TITLE
Infralar y Therazane

### ISSUE THREAD

**Issue by Szajil** [RoDNet/Bugtracker-Infinium-4.3.4#3269]
NO me dan mas misiones en infralar y no puedo acceder a Therazane, par hacer diarias y demas...no puedo completar  http://es.wowhead.com/quest=26427/sin-capitan-ni-tripulacion por lo que no puedo seguir progresando

**Comment by redneo** [comment]
## 

Por Whiterock (55,031 – 6·53·710) el 17/02/2012 (Parche 4.3.2)  Reportar  
Upper World Pillar Fragment Quest Tree From Whiterock
The War Has Many Fronts{H}\* The Battle Is Won. The War Goes On{H}*
|                             |
| S)Hero's Call: Deepholm!(A) | S)Warchief's Command: Deepholm!(H)
├──┼────────────┬─────────────┴──┘
|one out of four|
└┬──────────────┘
S)The Maelstrom
S)Deepholm, Realm of Earth
 |
a)Gunship Down a)Captain's Log a)The Earth Claims All a)Elemental Energy
 ├──────────────┴───────────────┘
 |
b)Diplomacy First──>b)The Admiral's Cabin──>b)Without a Captain or Crew
 |
b)All Our Friends Are Dead──>b)Take No Prisoners
 |
b)On Second Thought, Take One Prisoner
b)Some Spraining to Do
b)Return to the Temple of Earth──>c)Blood of the Earthwarder
c)Deathwing's Fall
c)Bleed the Bloodshaper    c)Twilight Research
c)Question the Slaves      c)Maziel's Revelation
c)The Forgemaster's Log    c)Maziel's Ascendancy
c)Silvermarsh Rendezvous
c)Quicksilver Submersion
c)The Twilight Overlook──>#)Into the Stonecore(Stonecore)
 |                   |
d)To Catch a Dragon d)Big Game, Big Bait
 |               ┌───┘
d)Testing the Trap                       #)Twilight Documents(Stonecore)
 |                \                      #)Followers and Leaders(Stonecore)
d)Block the Gates d)Abyssion's Minions
 |                /
d)The World Pillar Fragment   The Middle Fragment*
 |                            /
The Very Earth Beneath Our Feet*

Legend:
S menas Skippable

# means Other Zones

(A)/(H) means Alliance/Horde only.
{H} means Quest Have Horde Variant, click {H} for it.
- means another Quest Tree.
