### ISSUE TITLE
Infralar y Therazane

### ISSUE THREAD

**Issue by Szajil** [RoDNet/Bugtracker-Infinium-4.3.4#3274]
Insisto Redneo. he hecho todas las misiones que me salen en Infralar, todas las que se pueden completar y no puedo seguir avanzando para hacer diarias de Therazane  o llegar al logro de misones completadas en Infralar. 
En algun momento de las cadenas no puedo seguir. ( creo que en el barco)...¿Como puedo hacer para llegar a Therazane y hacer diarias?...

**Comment by redneo** [comment]
La mision del barco es opcional, hace poco levee un pj y se puede llegar hasta las misiones diarias de therazane, es mas, aunque no vayan todas, se puede sacar el logro de infralar (misiones)

**Comment by Compresor** [comment]
Aquí están la mayoría de misiones de infralar ordenadas.
http://www.wowwiki.com/Deepholm_quests

**Comment by Szajil** [comment]
No dudo de que podais hacer las misiones y el logro y las diarias etc......yo posteo porque YO no puedo. A MI no me salen misiones para hacer y YO no puedo hacer mas. He hablado con gm`s ingame y la solucion que me han dado es postear aca para ver que se puede hacer en MI caso concreto....

**Comment by redneo** [comment]
TU caso en concreto estaría bien saber cual misión TU hiciste de las ultimas para saber cual TU tienes que hacer en la cadena de misiones correspondiente, dado que la misión que TU has expuesto es opcional y no influye a TU cadena de misiones

**Comment by Szajil** [comment]
No puedo saber en que mision en concreto me he quedado. Aunque si se que de las del barco hice las que me dejo.
Ninguna de las que mencionas en la lista me deja hacerlas. Aunque creo recordar que me quede en  esta Questgiver http://www.wowhead.com/npc=44010, o sea a falta de tres misiones para terminar la cadena,,,,
Por otra parte, quiero dejar claro que no son solo las cadenas de therazane las que no puedo hacer, no puedo hacer ninguna otra mision, solo he consegido hacer ( por que no me  dan mas los quests givers) 47 de 110....
No me importa tener que reiniciar todas las misiones de infralar, hacerlas de nuevo....

**Comment by redneo** [comment]
Vale, para llegar a esa tipa tienes que haber hecho la cadena de misiones http://es.wowhead.com/quest=27061 al completo.

Y para empezar esa cadena tienes que haber hecho:
Todos nuestros amigos están muertos (Usar un totem sobre los cadaveres en el barco)
No hagas prisioneros (Creo que es opcional, matar a 6 tipos en el barco)
Y ya empezarias con Pensándolo mejor: haz un prisionero (matar a Mor'norokk)

Luego siguen un par de misiones autocompletables y ya dejas el barco para siempre.

**Comment by Szajil** [comment]
....Pero Redneo....¿Como puedo seguir si no me dan misiones? No hay ningun Questgiver con la ! en ningun sitio....

**Comment by Monleon** [comment]
Szajil, bajate la versión 4.3 del http://www.curse.com/addons/wow/questhubber que te ayudará indicandote las misiones, o que te falta para poder obtener alguna.

**Comment by Szajil** [comment]
Lo tengo instalado...me indica varias misiones (muchas) pendientes. El tema es que al ir dd esta el questgiver, este no me da mision alguna....

**Comment by redneo** [comment]
Dime cual es tu pj y una mañana de estas te lo cambio a mi cuenta de gm temporalmente y lo miro. Solo nombre de pj

**Comment by Szajil** [comment]
Anathema. Pauperima medio la mision http://es.wowhead.com/quest=26326. la complete y me dieron http://es.wowhead.com/quest=26314, http://es.wowhead.com/quest=26312 y http://es.wowhead.com/quest=26313, pero no se puede resolver, nosalen sirvientes de therazane, no hay chamanes amistosos a los que curar y no hay elementales que den nucleos

**Comment by redneo** [comment]
Me creo un Horda, voy al cartel u cojo:
- Orden del jefe de guerra Infralar.
- La voragine
  Atravieso el portal y hablo con Thrall
- Infralar, Reino de la tierra
  Primera cadena de misiones ya que me dan unas cuantas:
- Nave de guerra abatida (se completa al estar al lado de lo que buscas, no darle click)
  Ahi cojo
- El diario del capitan
  Me enseña una mision para coger, pero no cumplo requisitos (por ahora "Primero la Diplomacia"), asi que cojo misiones de otro npc
- La tierra lo reclama todo. (la podia haber cogido antes ya que es en el mismo lado)
  Ahora si que me da da:
- Primero la Diplomacia
  En el barco cojo:
- El camarote del almirante
- Todos nuestros amigos estan muertos
  Me dan:
- No hagas prisioneros
- Pensandolo mejor: haz un prisionero
- Sin capitan ni tripulacion -- NO SE ENCUENTRAN LOS ITEMS EN EL BARCO
  Tras mucha paciencia completo ambas y me dan
- La cosa se tuerce (autocompletable)
- Vuelve al Templo de la Tierra
  Sin querer me encuentro con los items de Sin capitan ni tripulacion en 63.50 46.59
- La caida de Alamuerte
- Desangrar al Modelasangre
- Interroga a los esclavos
- El cuaderno del Maestro de Forja
- Encuentro en el Marjal Argenta
- Inmersión Mercurica
  Me dan la opcional Investigacion crepuscular.
- El mirador Crepuscular.
  Ahora me dan 3
- Un gran cebo para una gran presa
- Cazar a un dragon
- Al nucleo petro (Opcional)
  Nos llevan ambas a 
- Probando la trampa
- Los esbirros de Abismion y Bloquea las puertas
- El fragmento del Pilar del Mundo.
  Ya tenemos uno, hora de coger otra cadena de misiones
- ¿Donde esta minaoro?
- Algo que arda y Compuesto de enlace explosivo
- Aplicar y secar
- Llevalo con la Clamatierras
- Ayuda para el hogar Petreo
- Los Campos Convulsos
- El hacha de hendimiento terrestre y Mineral elemental
- Uno con el suelo
- Acaba con abalancha
- El favor del padre petreo (si que funciona, regular, pero si que lo hace, cuenta a los que no tienen el bufo)
- Estamos rodeados
- Piedras de trueno y Sellando el camino
  Nos llevan a:
- Neceista unos arreglos - ¡Hazlos pedazos! y Selección en el Frente.
  Las tres se pueden hacer aunque Selección en el Frente requiere un poco de paciencia ya que hay pocos npcs que puedas usar el item en la zona.
- Troggzor el Terrinator
- Entrega Urgente
- Escolta intensiva
- Apartalos del Frente de Batalla
- Reactiva los ensamblajes y Maestros Místicos.
- En el interior de la Sima
  Aqui nos dan dos
- No mas brotes y Monstruosidades Fungicas
  Nos lleva a Un pequeño Problema.
- Rescata al Padre petreo... y a Sílex
- El regreso del Héroe
- El Fragmento Central
  AHora nos dan otra cadena de misiones
- La tierra bajo nuestros pies la cual nos lleva a las tres siguientes:
- Allanar el terreno - Defensas Desmoronadas - El núcleo de nuestros problemas
  Tras esas 3 nos da Enfrentamienteo Imponente
- Relaciones Rocosas
  Con esta mision, nos dan ya 500 puntos de reputacion con Therazane, pudiendose hacer alguna más sin dificultad (lo voy a dejar ahi por el momento, si estas interesado sigo).

Todas las misiones descritas se pueden hacer, algunas con mayor problema que otras y las dan sin problema alguno. Con esa ultima mision entregada, tengo 62 de 110 misiones del logro de Infralar, sin haber cogido las opcionales que hay por ahí, solo yendo a las que me interesan de Therazane. Decir que he hecho TODAS las descritas arriba, solo completandome las misiones tras ver que se pueden conseguir los objetivos (coger tres piezas de 12 que piden, matar a 5 de 10 que piden y cosas así) y en todo momento con el .gm off (me ha costado más de un teleport a la carcel).

La mayor dificultad que he encontrado ha sido en el barco, ya que varias veces me ha transportado a vete a saber donde y alguna vez los npcs se ponian en evadir, pero a base de constancia, lo he hecho haciendo un daño triste con mi pua mental.

**Comment by redneo** [comment]
Comparando tus misiones con las mias tu no has hecho las siguientes:
26312,
26313,
26314,
26315,
26328,
26500,
26502,
26537,
26564,
26591,
26625,
26632,
26755,
26762,
26770,
26791,
26792,
26834,
26835,
26836,
27126,
27935,
27937,
27938

24 hechas por mi que tu no has hecho

**Comment by Szajil** [comment]
A ver. Con mi otro pj he seguido las cadenas y me he quedado en la segunda cadena:
El npc Gravel Largalosa de Infralar no me da la questhttp://www.wowhead.com/quest=26537 y luego http://www.wowhead.com/quest=26625
EL npc Rompesuelos Dolomitano no me da las misiones http://es.wowhead.com/quest=26500 y luego http://es.wowhead.com/quest=26502
El npc Ensalmador de la tierra Venaprofunda <Médico> no me da la mision http://es.wowhead.com/quest=26591
El addon questhubber me dice que me faltan estas misiones con AMBOS personajes, pero los quest givers no me las dan.
Mi problema sigue siendo el mismo , los quest givers no me dan misiones ...creo que tiene que ver con las distintas "fases"

**Comment by Szajil** [comment]
En fin.....un gm ha contestado a un ticket in-game diciendome que se pueden hacer todas las misiones de Infralar y que Redneo las hizo y le salto el logro y etc etc....
No lo niego, solo digo que a mi, a mi pj Anathema no me salen mas misiones en Infralar, digo que me faltan misiones por hacer y pido si me pueden dar las misiones que menciono en el post anterior para hacerrlas y ver si puedo seguir mi progreso alla.....

**Comment by redneo** [comment]
te puedo borrar todas las misiones de therazane - infralar, pero repito, se pueden y he hecho todas las que hay puestas más arriba

**Comment by Szajil** [comment]
Por favor.....borramelas todas....

**Comment by redneo** [comment]
Antes de borrartelas, decirte que hay un npc al cual suelen matar y/o se esconde dentro de uno de los robots... no me acuerdo como se llama, a lo mejor coincidio que estaba muerto :S

**Comment by Szajil** [comment]
Redneo....por favor borramelas, prefiero empezar de nuevo....

**Comment by maitomomi** [comment]
Estimados, Me pasa exactamente lo mismo. Con dos pj me quede bug en la quest Desangrar al modelasangre porque la abandone al ir a otro mapa leveando y cuando volvi me sale muy bug. Ruego me reinicien las misiones con Seonaid y Bast. POR FAVOR!!!!! D= O por otro lado si me dieran http://es.wowhead.com/item=60264/ordenes-crepusculares ese item a los dos pj se resolverìa (o eso creo)
