### ISSUE TITLE
[dk] Espiral de la muerte daño x2

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3275]
ID:http://wow.freakz.ro/spells.php?spell=47541

Lo he estado mirando muy detenidamente y me he encontrado con que espiral esta pegando aproximadamente el doble. Lo hemos comprobado con un dk con equipo sanguinario con el muñeco y con pjs implacables y le pasa lo que a la gárgola (https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3133).

En la descripción se pone que espiral de la muerte con mi dk (con equipo sanguinario) pega 5200p en profano a lo que habría que sumarle la maestría. Lo cual sería lo siguiente:

5200_1,23(maestría base que aumenta el daño de sombras un 23%)_1.23(el 23% que tengo gracias a la maestría que llevo)=7870p aprox. de daño normal. (Sin buffos ni temple ni nada).

Actualmente esta habilidad esta metiendo 12k de daño de normal al muñeco y a pjs full implacables 8k (recuerdo que mi pj es sanguinario).

Para mayor seguridad lo he comprobado con el drdamage (es orientativo xo los daños mas o menos deberían estar próximos) lo cual me dice que la media que debería pegar de normal unos 6k. Lo cual se distancia mucho de los 12k que antes he comentado.

Un saludo y gracias

**Comment by redneo** [comment]
Reparado en la proxima compilacion.
