### ISSUE TITLE
[Talento] [Mago] Orbe de pirofrío

### ISSUE THREAD

**Issue by Dapli** [RoDNet/Bugtracker-Infinium-4.3.4#3276]
El talento orbe de pirofrío hace que el orbe de llamas (Que debido al talento se convierte en orbe de pirofrio) se bugee,de manera que es una especie de mascota que pega 1 de daño a los enemigos y no hace más daño,es decir,ni el daño que debe de hacer por segundo,ni ralentiza ni nada.

Al ser una habilidad clave del mago frost debido a que es la mayor fuente de proc de dedos de escarcha que tienen,se debería intentar al menos hacer que el orbe meta correctamente el efecto de ralentización.

No adjunto imágenes puesto que basta con usar la habilidad para ver que no funciona correctamente (además no se apreciaría bien el bug en cuestión)

Gracias y perdón por las molestias.

**Comment by Monleon** [comment]
Puedes ponernos la id del orbe de llamas, y de la id del talento que hace que el orbe de llamas se convierta en un orbe de pirofrío?

**Comment by Dapli** [comment]
No sé muy bien a lo que te refieres,pero imagino que será esto: 
-Este es el del orbe de pirofrío: http://wow.freakz.ro/spells.php?spell=84726
La cual sería 84726.
-Este sería el del orbe de llamas: http://wow.freakz.ro/spells.php?spell=82739&name=flame-orb
La cual sería 82739.

Espero que ayude.
P.D: El orbe de pirofrío también tiene esta id http://wow.freakz.ro/spells.php?spell=84721&name=frostfire-orb 
La cual sería 84721.

**Comment by efectokoleos** [comment]
arreglado
