### ISSUE TITLE
[DK] Golpe necrotico

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3277]
http://wow.freakz.ro/spells.php?spell=73975

El problema de esta spell es que no absorbe una cantidad determinada de sanación, sino que absorbe un hechizo entero. Es decir, si le pones este ataque al objetivo, debería absorber una cantidad de sanación, pero por ejemplo si se sana 40k, absorbe esos 40k y si se sana 7k solo absorbe 7k, no está absorbiendo una cantidad determinada, está absorbiendo una sanación entera, sea cual sea la cantidad sanada

**Comment by F4NT4SM4** [comment]
0.70 \* AP esa es la formula que deberia absorbe 
otro problema de la spell pondre un ejemplo si absorbo 10k de curacion  y el objetivo se cura 1k  me deberian de quedar 9k mas por absorbe 
el caso es que si el objetivo se cura ese 1k el debuff desaparece y no tiene sentido usarlo contra druidas y sacer heler

**Comment by Kiritoo** [comment]
Arreglados ambos fallos, falta compilar.
Cuando se compile hacerme el favor de probarlo para saber que no queda ningun detalle.
En las pruebas que realizé todo perfecto :)

**Comment by F4NT4SM4** [comment]
sigue desapareciendo el debuff sin haber absorbido la cantidad total que deberia
ejemplo deberia absorber 10k en total pero un druida se tira rejuvenecimiento y con el primer tik que cura 3k el debuff desaparece deberia de quedar el debuff pero ahora absorbiendo las sigueintes 7k de curacion

**Comment by Kiritoo** [comment]
"Arreglados ambos fallos, falta compilar."

Estado de los reinos
19h 32m 51s
Infinium

**Comment by F4NT4SM4** [comment]
mmm es que el primer bug si se arreglo el que absorbia todo la curacion 
ahora absorbe lo que debe y contando el temple por eos pense que ya estaba :s

**Comment by F4NT4SM4** [comment]
see ya lo volvi a testear y esta perfect 
Gracias por el gran trabajo :p
