### ISSUE TITLE
[Hechizo-Cazador] Disparo de quimera

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3282]
Nombre: Disparo de quimera
Enlace: http://wow.freakz.ro/spells.php?spell=53209
Problema: Hay problema con los críticos de la habilidad. Hay ocasiones en las cuales salta un disparo crítico, pero el daño que hace es igual al de uno normal. Mientras que en otras a salir un critico si se ve el daño adicional.
Observación: Claro, estoy hablando de pruebas hechas contra otro jugador, en duelo, sin recibir algún bufo de reducción o escudo ni peeling. En el registro de combate se puede alcanzar a ver como un disparo de quimera hace uno 10k de daño (por ejemplo), y luego el siguiente salta crítico y hace los mismo 10k. Al hacer un registro de cuantas veces sucede el problema, sin haber contado a fondo, sucede como en uno 40% de los críticos que salen con quimera,

**Comment by matux12** [comment]
eso es absurdo debido a que yo uso hunter y el disparo de quimera pega entre 8-10k normal y 12 a 15 critico depende bastante del temple.

**Comment by Jhovanni** [comment]
Haz las pruebas. Verás que algunos disparos de quimera a pesar de ser críticos hacen la misma cantidad de daño.
Y mi disparo de quimera hace más daño que el tuyo, no hay nada de absurdo en eso, solo es mas equipo.
Y como puse en la explicación hablo de duelos contra la misma persona, sin bufos adicionales; que digas que depende del temple cuando por eso ya mencioné lo anterior, es absurdo.

Igual puedo equivocarme, pero antes haced pruebas un rato para ver si les saltan los criticos cuyo daño es igual que uno normal. Nada mejor que probar el asunto y si me he equivocado, que mejor.
