### ISSUE TITLE
[Hunter] Deterrence: 19263 Flag Carrier

### ISSUE THREAD

**Issue by Monleon** [RoDNet/Bugtracker-Infinium-4.3.4#3283]
ID: http://www.wowhead.com/spell=19263/deterrence

Desde la llegada del parche 4.1, utilizar esta spell portando una bandera en un campo de batalla, debería hacer soltarla de inmediato.

**Comment by Jhovanni** [comment]
Tienes razón, y lo hace.
Si un cazador usa Disuación cuando carga bandera, la bandera se suelta. Está funcionando bien. (A menos que sea un nuevo bug de hace dos semanas para acá).

**Comment by feniix97** [comment]
no es un nuevo bug esta hace rato ya vi a todos los cazadores abusando de el en las bgs, ya se había arreglado pero veo que volvió el bug

**Comment by Kiritoo** [comment]
Fix
