### ISSUE TITLE
[Tierras de Fuego] Objetos con encantamientos aleatorios.

### ISSUE THREAD

**Issue by Compresor** [RoDNet/Bugtracker-Infinium-4.3.4#3286]
Cuando obtienes los objetos no te da ningun tipo de estadística, y debería dar una al "azar":
- http://es.wowhead.com/item=71025
- http://es.wowhead.com/item=71030
- http://es.wowhead.com/item=70735
- http://es.wowhead.com/item=70917
- http://es.wowhead.com/item=71421
- http://es.wowhead.com/item=71450
- http://es.wowhead.com/item=71403
- http://es.wowhead.com/item=71428
- http://es.wowhead.com/item=71458
- http://es.wowhead.com/item=70917
- http://es.wowhead.com/item=71458

Me faltan stats de:
http://es.wowhead.com/item=71421

**Comment by redneo** [comment]
Arreglados:
http://es.wowhead.com/item=70735
http://es.wowhead.com/item=71428
http://es.wowhead.com/item=71025
http://es.wowhead.com/item=71450
http://es.wowhead.com/item=71421
http://es.wowhead.com/item=71403
http://es.wowhead.com/item=71030
