### ISSUE TITLE
[Logro] Combatiente de mazmorra de la Luna Negra

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#3288]
http://es.wowhead.com/achievement=6027

Llevas el diario y no se pueden conseguir los objetos del logro en las mazmorras

**Comment by redneo** [comment]
http://es.wowhead.com/item=71637#dropped-by:0-2-10-9+1 Lo sueltan en castillo colmillo oscuro y en Camara de los Origenes al 10%
http://es.wowhead.com/item=71635#dropped-by:0-2-10+1 Lo sueltan en Cumbre del Vortice y en Camara de los Origenes
http://es.wowhead.com/item=71638#dropped-by:0-2-10+1 Lo sueltan en Minas de la Muerte, Grim Batol, Ciudad Perdida de los Tol Vir y Cavernas Roca Negra.
http://es.wowhead.com/item=71715#dropped-by:0-2-10+1 Lo sueltan en Castillo Colmillo Oscuro, Camara de los Origenes, Cavernas Roca Negra y Ciudad Perdida de los Tol'vir

Solo faltaria el item 71636

**Comment by Wiinter** [comment]
Pero la mitad de los artefactos se consiguen en mazmoras lows. En los comentarios lo explican es.wowhead.com/achievement=6027#comments

**Comment by redneo** [comment]
Nagousta el 02/01/2012 (Parche 4.3.0)
Darkmoon items no longer drop from low-level content. See the updated tooltip on http://www.wowhead.com/item=71634 . You must kill level-appropriate bosses at this time.
upvote
4
downvote
Saliman el 04/01/2012 (Parche 4.3.0)
Darkmoon artifacts will no longer drop in dungeons that do not match your level which means these are no longer solo-farmable.

De todas formas, ahora mismo si que se pueden sacar a un porcentaje muy bajo. Por cierto leyendo eso he visto que los porcentajes es de 33% no de 10, lo cambio.

Agregado el ultimo item, cierro BT.
