### ISSUE TITLE
Dragon Azul en Orgrimmar

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#329]
Bueno, ibamos para tol barad y nos encontramos con este dragon xD

(Ignoren la conversacion)
![wowscrnshot_071013_154356](https://f.cloud.github.com/assets/4895839/777799/d70d9836-e9a1-11e2-8edd-d88c1a205bf8.jpg)

La del recuerdo
![wowscrnshot_071013_154453](https://f.cloud.github.com/assets/4895839/777801/deaf72b2-e9a1-11e2-9c04-fe8b6b3d90c0.jpg)

**Comment by ghost** [comment]
Ya no está.
