### ISSUE TITLE
[Cazador] Disparo de Quimera

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3293]
Nombre: Disparo de Quimera
ID:53209
Enlace:http://wow.freakz.ro/spells.php?spell=53209
Descripcion: Un disparo instantaneo que inflige daño de naturaleza con arma a distancia mas #p de daño. lo que reinicia la duracion de tu picadura y te sana un 5% de tu salud total

Problema: La Sanacion esta saliendo critical y no deberia ya que es un 5% fijo de la vida del cazador.

Comented: Es como si el el reponerse del picaro saliera critical sus curaciones o el ataque de victoria del war

**Comment by DatJetto** [comment]
Te equivocas, disparo de quimera SI PUEDE SER CRÍTICO, en Pandaria se actualiza y NO puede, pero desde 4.0.3 hasta 4.3.4 SÍ puede hacerlo y es correcto :)

**Comment by F4NT4SM4** [comment]
intonce ataque de victoria y otras spells tambien deberian ser sanaciones critical?
por que con esa logica de que una sanacion % de salud de curacion quitaron las sanaciones critical de otras spells

**Comment by F4NT4SM4** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2227

**Comment by Pegasu5** [comment]
De hecho si miras  en foros de blizzard hablando todos de atributos especiales del cazador MM   hablan de como conseguir mejorar el critico de sanación de quimera, así que es correcto.
