### ISSUE TITLE
[Cazador] Atributo Agilidad - Poder de ataque Distancia (abusado en pvp)

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3294]
Nombre: Agilidad - Poder de ataque Distancia
Descripcion: Cada punto de agilidad da 2 poder de ataque = 1 agilidad=2 Rap
Problema:  la agilidad esta aumentando exactamente 2.5 por cada punto de agilidad

Testee(esto lo pongo para evitar quejas o preguntas de otros jugadores): 
tengo 3549 agilidad le resto mi agi base 210= 3339 agi, 9022 Rap le resto mi ap de base 675= 8347 (no cuento agi base ni ap base ya que nose cuando ap exactamente tengo sin agi)
3339 agilidad x2 =6678 Rap es lo que me deberia dar
3339 agilidad x2.5=8347 Rap lo que dando actualmente

**Comment by cibernaco** [comment]
Tienes que mirar si por casualidad no tendrias activado aspecto del halcón, o alguna otra cosa ya que a mi me funciona perfectamente, si ves que aun así no te funciona bien, especifica en que rama y con que talentos activos te pasa, a lo mejor es un bug de otra cosa.

**Comment by F4NT4SM4** [comment]
tesste sin talentos, sin aspecto del halcon, sin buffos a si que no hay ningun bug de otra cosa
los cazas en general tienen bug el poder de ataque

**Comment by cibernaco** [comment]
Pues somos 4 cazadores los que lo hemos provado esta tarde, y da x2 justo mañana aportare unas fotos

**Comment by F4NT4SM4** [comment]
![wowscrnshot_021314_203405](https://f.cloud.github.com/assets/3101842/2167205/050ec066-9514-11e3-8661-37dc498d2502.jpg)

3549 agilidad x2= 7098 + poder de ataque base 149 =7247 eso es lo que deberia de tener
3549 agilidad x2.5= 8872 + poder de ataque base 149=9021,5 que es lo mismo a 9022 es lo que esta dando osea bug
confirme con otro caza para que no digais que el bug es de mi pj

**Comment by cibernaco** [comment]
Ahh vale ya he entendido tu problema, vamos a ver, lo primero tu necesitas calcular RAP no AP, no es lo mismo, y lo segundo no es solo llegar y decir 1 agi = 2 AP y ya, así desde el principio, no, mira seguramente no seré la mejor persona para explicártelo, a mi lo de explicar se me da fatal, vamos a ver, con esa foto que tu me has puesto, si ahora mismo aumentaras tu agilidad solo en 1 punto, seguramente te daría justo justo 2 RAP más, pero por lo que sea no se calcula así, yo te hablo desde la experiencia, son muchos años en wow jugando con el cazador, y para mostrarte y dando por sentado que no son los mismos ejemplos ya que a nadie en los videos se les pilla sin talentos, pero si al menos sin buffs que modifiquen el RAP, mirate los videos que te linkeo, ademas de otros que tu mismo puedes mirar y veras que siempre, en todos los casos la cifra de RAP se acerca muchisimo al x2.5, es que siempre se dice 1 agi = 2 AP que ya te digo que no es lo mismo que el RAP y que no es exacto ese 1 agi = 2 RAP, yo mismo te puedo poner alguna foto de mi cazador en el servidor oficial, que aunque no fueron hechas para estos menesteres alguna se puede aprovechar, todos estos videos son de la 4.3.4. de guias de youtube una en particular de un cazador bastante conocido y también te voy a subir una foto de mi pj en el wow de hace unos poquitos de años xDD, le quitare el nombre, de todos modos para las desconfianzas dejo los vídeos para que no digan "has retocado la foto" o "viva el photoshop"....

Ejemplos:
http://www.youtube.com/watch?v=QsqQ6od_kiU
http://www.youtube.com/watch?v=euc4P0HS_TU

Mi foto xDD (era para enseñar otra cosa, pero sirve jaja):
![casco arcano](https://f.cloud.github.com/assets/6071376/2172266/e5da77da-9590-11e3-8225-704257a9ba9b.jpg)

y bueno añadir que para que te hagas una idea de la formula, si te desnudas entero, deberías de poder sacar el RAP con esta formula a nivel 85 (ojo importante a nivel 85 ya que no es un incremento lineal) (((85 x 2 - 10) + Agilidad) x2)

y si te equipas, la formula es [(((85 x 2 -10) + Agilidad) x2) + Dmg MAX de RW]. RW= Arma de ataque a distancia.

Otros addon tipo DrDamage sacan una formula aun más básica (DrDamage no es muy popular entre los servers no oficiales, pero en us.battle.net hay comentarios del tipo "Love this addon" y muchisima gente lo usa como uno de los principales addons, pero bueno eso es otro tema) la formula que sacan es (Agi / .273) esa formula es con aspecto del halcón activo en la rama de puntería.

Puedes comprobar tu mismo esas formulas, no recuerdo absolutamente todos los detalles del servidor oficial, pero si recuerdo que en la rama de bestia full implacable y con Aspecto del halcón se pasaban de los 24k de AP, buscare alguna foto a ver si salta por casualidad. De todos modos nada será exacto por que este tema era ya muy popular desde la 4.0.6 en los foros oficiales, y ya un Blizareño advirtio que en la formula suya de base entraba hasta el DPS del aram que llevaras equipada, a si que por eso te digo que para el RAP un x2 no es suficiente,

Bueno espero haber sido de ayuda.

Un saludito.

**Comment by F4NT4SM4** [comment]
http://youtu.be/QsqQ6od_kiU?t=8m58s 
5635 agilidad 
RAP: 14846 

5635x2= 11270 + Cuidador de animales 30% poder de ataque (http://wow.freakz.ro/spells.php?spell=87325) = 14651 los 190 que faltan me imagino que son por el poder de ataque base

no voy a guiarme por la foto (que es ovio que es nuestro servidor set sañoso/impla y el poder de ataqe bug) no muestras buffos nombre o si es del official
me guio por el video que si parece ser del official y segun el video es x2

**Comment by F4NT4SM4** [comment]
intente confirmar con el otro video pero no muestra la agilidad

**Comment by Compresor** [comment]
Arreglado, a la espera de compilar
