### ISSUE TITLE
[Chamán Elemental] Flujos de lava

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3295]
ID rango 3: http://wow.freakz.ro/spells.php?spell=51482&name=lava-flows

Increases the critical strike damage bonus of your Lava Burst spell by an additional 24% and the periodic damage of your Flame Shock by 60%. In addition, when your Flame Shock is dispelled you gain 90% spell haste for 6 seconds.

Problema: (la primera parte va bien) Cuando Choque de llamas http://wow.freakz.ro/spells.php?spell=8050&name=flame-shock es disipado, el chamán elemental que había puesto el choque no recibe el buffo http://wow.freakz.ro/spells.php?spell=65264&name=lava-flows que debería aumentar su celeridad un (30/60/90%) en función de los puntos que llevara puestos en ese talento.

Nota: pese a que en el link pone que aumenta la celeridad solo un 10%, ya no es así:
Lava Flows now grants a 30/60/90% haste buff when a Flame Shock effect is dispelled, up from 10/20/30%.
Nota del parche 4.2

En resumen, que no aumenta la celeridad del chamán al ser disipado su choque de llamas.

**Comment by lenindx** [comment]
Cierto, venía a realizar el reporte pero veo que ya está el tema abierto:
El talento de Chamán Flujo de Lava, no otorga celeridad, algo que debería hacer al ser disipado Choque de Llamas,

**Comment by efectokoleos** [comment]
arreglado
