### ISSUE TITLE
[Guerrero] Ira

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3296]
Nombre: Ira
Descripcion 
- Si el ataque es un golpe crítico, generará 200% mas de de ira de lo que daria un golpe normal.
- La ira al recibir daño ignora todas las reducciones de daño por armadura, absorción, evasión, bloqueo o mecánicas similares, así que al mejorar el equipo no se reducirá la ira ganada al recibir daño

Problema: 
- Los golpes blanco critico estan dando la misma cantidad de ira como si fuera normal
- La ira al recibir daño esta teniendo en cuenta las reducciones de absorcion, armadura, temple etc... y no deberia. Ejemplo si un golpe me deberia de dar 20k sin nada y la armadura, absorcion,temple, etc... lo reducen a 10k la ira recibida seria deacuerdo a esos 20k no al daño qeu se redujo 

Fuente: http://todowow.com/azules/normalizacion-de-la-ira-en-la-expansion-cataclismo/

**Comment by Compresor** [comment]
http://www.tankspot.com/showthread.php?77219-Rage-gained-from-damage-taken
Aqui se pueden encontrar las formulas de la ira obtenida al recibir daño.

**Comment by F4NT4SM4** [comment]
bueno a eso me refiero de que sigue esa formula el daño recibido aun si es absorbido, reducido por armadura o temple deberia dar la ira ignorando esas reducciones en cambio cuenta las reducciones y da menos ira

**Comment by F4NT4SM4** [comment]
ya no conviene gemas y reforjar a critico ya que no nos dara ira extra........

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.

**Comment by F4NT4SM4** [comment]
mmmm dejo de funcionar ira rabiosa aumentaba la ira recibida por daño 
lo reporto en otro issues?
