### ISSUE TITLE
[Vendedores] Los vendedores de Argenta

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#33]
Aunqe seas exaltado en todo lo que necesitas para poder comprarles cosas, no te venden nada los vendedores de cada ciudad del Torneo Argenta. Almenos en el bando de la horda.

**Comment by SherBlader** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/8

**Comment by crowel** [comment]
Wiinter cuales son los ids de los vendedores?, un saludo.

**Comment by Wiinter** [comment]
Arreglado
