### ISSUE TITLE
Vega tuercespina esta plagada de mobs de nivel muy alto para esta zona

### ISSUE THREAD

**Issue by isma1977** [RoDNet/Bugtracker-Infinium-4.3.4#330]
la zona esta llena de mobs imposibles para alguien de level 25-35.

![wowscrnshot_071013_203802](https://f.cloud.github.com/assets/4950741/779057/faec31aa-e9c3-11e2-8a45-9ba2ada54c4c.jpg)

**Comment by redneo** [comment]
Borradas, aunque tendria que haber una http://www.wowhead.com/npc=52173

**Comment by crowel** [comment]
Tambien Digsite Zombie http://www.wowhead.com/npc=52604 aunque no creo que se borrara este.
