### ISSUE TITLE
[Druida] Lluvia lunar [TALENTO]

### ISSUE THREAD

**Issue by Igrime** [RoDNet/Bugtracker-Infinium-4.3.4#3300]
Nombre: Lluvia lunar
ID: 33605

Enlace:http: http://wow.freakz.ro/spells.php?spell=33605&name=lunar-shower

Descripcion: Cuando lanzas Fuego lunar, ganas Lluvia lunar. Lluvia lunar incrementa el daño directo de tu Fuego lunar en un 45%, y reduce el coste de maná en un 30%. Este efecto se suma 3 veces y dura 3 segundos. Cuando estas bajo los efectos de Lluvia lunar, tu Fuego lunar genera 8p de energia solar y Fuego Solar genera 8p de energia lunar.

Problema: Hay 2 problemas, 1 de ellos que siempre, lances Fuego lunar o Fuego solar, siempre te dará energia solar. El otro problema es que Fuego solar no se beneficia de Lluvia lunar.

**Comment by Wiinter** [comment]
Tengo una pregunta, en que se tiene que beneficiar fuego solar si el unico qe se puede beneficiar del daño directo y de la reducción de mana es fuego lunar?
No estoy cuestionando que no esté bug, simplemente que no lo entiendo y estoy hablando des de la ignorancia y lo que yo he podido leer del talento.

**Comment by Igrime** [comment]
El Fuego Solar se tiene que beneficiar de ese talento cuando estas en
Eclipse solar, pues el Fuego Solar es el Fuego Lunar solo que cuando entras
en Eclipse solar, cambia la skill. Está diseñada para que se beneficie de
ambos Eclipses, tanto con el aumento de daño de Eclipse como del talento
Lluvia lunar.

**Comment by Igrime** [comment]
Es mas, dejo un link de youtube, de los servidores oficiales de WoW. Lo
pongo exactamente cuando un druida balance va a cambiar a Eclipse solar y
cuando lo hace, lanza un Fuego Solar y este se beneficia de Lluvia lunar.

http://youtu.be/cqNku5d2sTs

**Comment by Dazand** [comment]
Ese post que referencié puede ayudar.

**Comment by efectokoleos** [comment]
arreglado
