### ISSUE TITLE
[DK] Glifo de Abrazo de la muerte

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3301]
Nombre: Glifo de Abrazo de la muerte
ID:http://wow.freakz.ro/spells.php?spell=58677
Descripcion: Tu espiral de la muerte te regresa un 20 de poder runico si lo usas para sanar un esbirro aliado
Problema: esta regresando un 20 poder runico si me curo a mi mismo y solo deberia de regresarmelo si curo a mi esbirro

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
