### ISSUE TITLE
[Reputación] Matar velasangres te quita reputación con Ogrimmar

### ISSUE THREAD

**Issue by damasombria** [RoDNet/Bugtracker-Infinium-4.3.4#3305]
Como explica el título, en vega de tuercespina ( Sur ), Hay piratas velasangres, si matas a cualquiera de estos la reputación con Ogrimmar te baja 25p por cada uno, esos piratas aguardan muchas misiones de levear que dan buena reputación, incluso un logro y título ( http://es.wowhead.com/achievement=871 ), cosa que así es imposible, me gustaría que lo arreglaran a ser posible, para poder contar con esa zona de leveo.
Dejo aqui todo lo relacionad con los velasangre en un link de "Wow Head" : http://es.wowhead.com/search?q=velasangre#quests

Atentamente Dama :) .

**Comment by Szajil** [comment]
Quitate el tabardo...

**Comment by damasombria** [comment]
Tubiera o no tubiera tabardo, sigue siendo un bug que no deberia pasar.
