### ISSUE TITLE
Talento [Gloria Eterna] Paladin

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3309]
Enlace rango 2: http://wow.freakz.ro/spells.php?spell=87164

Descripción: Tu <b>palabra de gloria</b> http://wow.freakz.ro/spells.php?spell=85673 tiene un 30% de probabilidad de no consumir <b>Poder Sagrado </b> http://wow.freakz.ro/spells.php?spell=85247

Problema: en la actualidad no existe la probabilidad del 30% de no ser consumidas las cargas

**Comment by efectokoleos** [comment]
despues de 2 horas intentando entender como funciona esta spell, me he dado cuenta leyendo esto http://eu.battle.net/wow/en/forum/topic/1710374097 cuando tienes 2 cargas y tiras palabra de gloria, si te salta gloria eterna te consumira una carga solo en vez de las 2 osea que es una movida porque esta mal explicado en el tooltip de la spell y he estado dandole vueltas al core mirandolo por lo que la spell esta arreglada a falta d compilar
