### ISSUE TITLE
Puntos de arenas

### ISSUE THREAD

**Issue by sherik12** [RoDNet/Bugtracker-Infinium-4.3.4#331]
Bueno no se si el limite esta bien poruqe no pude seguir ganando, pero si no tienen limite revisenlo y sino es un bug visual. Adjunto las tomas:
![wowscrnshot_071013_232223](https://f.cloud.github.com/assets/4358923/779615/c9edf4f8-e9e1-11e2-9bc7-0c0a4e6fb95d.jpg)
![wowscrnshot_071013_232227](https://f.cloud.github.com/assets/4358923/779616/c9f54410-e9e1-11e2-92cd-a0d9383ca4a2.jpg)

**Comment by crowel** [comment]
El limite en está versión es el correcto 1650, lo que creo que esta mal son los puntos por arena ganada, que son x230.
Si alguien pudiera confirmar si los puntos que da son correctos.
Un saludo.

**Comment by sherik12** [comment]
si si yo se que el limite es ese por eso dije: Bueno no se si el limite esta bien poruqe no pude seguir ganando. pero si te das cuenta en una pestaña reporta menos de los que son, lo cual es un bug y por eso puse las dos probabilidades :P

**Comment by Dekadencee** [comment]
Está correcto a día de hoy, un saludo ^^
