### ISSUE TITLE
[Misión Marjal Revolcafango] - Reta al Vuelo Negro

### ISSUE THREAD

**Issue by Boethiah** [RoDNet/Bugtracker-Infinium-4.3.4#3310]
Nombre: Reta al vuelo negro
Enlace: http://es.wowhead.com/quest=27411
Descripcion: Coloca el estandarte Quebrantarrocas cerca de la entrada de la Guarida de Onyxia y derrota a todo el que responda.
Problema: Me dice en rojo: Debes estar en la Guarida de Onyxia o hace la animacion de casteo pero no canaliza.
Observaciones: Ninguna

**Comment by redneo** [comment]
Arreglada cuando caiga el server
