### ISSUE TITLE
[dk] Espiral de la muerte daño x2

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3313]
Esto en teoría se había arreglado y compilado porque salió en el changelog. El problema es que o no se ha implementado o bien ha vuelto a hacer lo mismo.

Dejo el post que hice https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3275

Un saludo y gracias

**Comment by Monleon** [comment]
Arreglado por redneo
