### ISSUE TITLE
problema con profecion no me sube habilidad

### ISSUE THREAD

**Issue by miguel7ize1** [RoDNet/Bugtracker-Infinium-4.3.4#3314]
ya tengo aprendido la paleteria para subir asta 525. sigo asiendo cosas que estan en rojo pero no me sube mas de 425.
   mi pj es Jucol un druida

**Comment by miguel7ize1** [comment]
me sube habilidad con los objetos de la vercion de lich king pero con las de cata no me sube nada

**Comment by Monleon** [comment]
Solucionado, falta compilar y reinicio.

No obstante si vieses un objeto en específico que no sube lo que corresponde, vuelve a reportarnoslo.

**Comment by miguel7ize1** [comment]
sigue sin subir
