### ISSUE TITLE
[Sacerdote] Hechizo palabra de poder escudo id 17

### ISSUE THREAD

**Issue by evangelion2009** [RoDNet/Bugtracker-Infinium-4.3.4#3315]
Bueno pondre lo que afecta de forma directa al mismo en la medida de lo posible(por que crear un isue para 3 cosas diferentes me parece un poco...)Bueno lo primero  la absorcion actualmente sigue absorviendo una cantidad bastante baja a mi parecer digamos que esta absorviendo unos 17k cuando eso ya casi seria la base a lvl85 pero tampoco me metere mucho en eso

.Las siguientes cosas siguen funcionando mal http://wow.freakz.ro/spells.php?spell=14768&name=improved-power-word-shield como bien dice aumentaria la absorcion un 20% el fallo en vez de dar quita absorcion XD.

Siguiente http://wow.freakz.ro/spells.php?spell=56160&name=glyph-of-power-word-shield como bien dice sanaria un 20% de lo que absorviera el escudo (antaño estaba bug y sanaba dos veces) que hace ahora no sana nada pero ironicamente añade lo que sanaria como escudo extra para poner un ejemplo simple pongamos que sanarias unos 4k si funcionase y tu escudo ahora mismo es de 16k pues con el glifo ahroa mismo añade esos 4k asi seria al final 16k+4k =20k de absorcion.

Pequeñas observaciones:La palabra de poder absorve poco claro que supuestamente la maestria no va pero incluso asi parece poco(ojo no hablo de pvp yo siemrpe me remito al pve XD) la maestria costaria bastante arreglarla aparte mirandola a ojo tengo miedo que afecte al talento egida lo cual lo complicaria aun mas.Lo del glifo y la facultad que no funcionan bien actualmente al faltar la facultad digamos que lo esta compensando el glifo pero caro a costa de perder una minisanacion.Eso es todo gracias por su atencion.

**Comment by Compresor** [comment]
Haces tres reportes en uno como bien dices.
