### ISSUE TITLE
[Brujo] Ascuas ardientes 

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#3319]
http://wow.freakz.ro/spells.php?spell=91986 (Rango 1)
http://wow.freakz.ro/spells.php?spell=85112 (Rango 2)

Al lanzar descarga de fuego del diablillo (http://wow.freakz.ro/spells.php?spell=3110) y fuego de alma(http://wow.freakz.ro/spells.php?spell=6353), no da el 25%/50% de daño hecho por la habilidad durante 7 segundos.

Por poner un ejemplo, si hace 3k de daño un fugo de alma, ascuas eternas producirian un daño de 1.5k al pasar 7 segundos, no cada tick de ascuas eternas. O 750 si es el rango 1.

**Comment by Kiritoo** [comment]
Fix, falta compilar.
