### ISSUE TITLE
[Sacerdote] Palabra de poder: escudo

### ISSUE THREAD

**Issue by Compresor** [RoDNet/Bugtracker-Infinium-4.3.4#3320]
http://wow.freakz.ro/spells.php?spell=17

Está absorviendo de menos, lo que está haciendo ahora debería hacerlo casi de base al nivel 85

**Comment by Compresor** [comment]
#3315 
@evangelion2009 Añade alguna fórmula para poder calcular correctamente el escudo

**Comment by evangelion2009** [comment]
Bueno tras dar vueltas y vueltas hasta marearme lo encontre pero da la casualidad que coincide exactamente con un post que ya fue escrito https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2195 y coincide en todo luego saque la calculadora(logico) y eche numeros andube haciendo pruevas por una razon simple la cifra base del escudo seria la que bien pone paella.Ahora bien tras calcularlo todo (quitandome el glifo por si las flys) me saldria la siguiente formula 8136+(0.87x7842)=14958 me daria.A eso le añado x1.06(por disciplinas gemelas)=15856 bien ahora viene lo gracioso actualmente me esta absorviendo 17032 digo yo ¿de donde me sale esa cifra de mas? bueno pues fui a calcular algo que tenia sospecha y que casualidad di en el blanco resulta que la maestria que pensamos no esta funcional,funciona una parte,lo que sumaria extra la formula maestria escudo de disciplina.Aumenta la cantidad absorvida un 20% de base mas un 2.5% por cada 1% maestria bien tengo 4% maestria lo cual da un multiplicador extra de x1.1 volviendo a la base vuelvo a calcular 15856x1.1(que este 1.1 significaria el 10% extra por maestria) y vaya que casualidad coincide la cifra a 17032, traducion la absorcion del escudo en si esta funcional lo que faltaria seria el multiplicador de 1.2 por la maestria base y 1.2 por palabra de poder escudo mejorada.en total por ejemplo si yo pusiera los talentos que ahroa no funcionan y funcionara la maestria correctamente la formula final quedaria asi

[[[[8136+(0.87xspellpower)]x1.06]x1.2]x1.30]=a mi por ejemplo me da 24735 de absorcion teniendo un 4% de maestria(nota el 1.30 es por tener un 4% de maestria sin indice maestria seria un 1.20)Asi que algo si que absorve de menos pero es por culpa de la facultad palabra de poder mejorada escudo y la maestria base de escudo de disciplina.En cuanto a los multiplicadores de la spell estarian bien.
Siento haber tenido que enrrollarme tanto para una jodida spell XD.Y gracias por su atencion.

**Comment by paellaencol** [comment]
Me alegra que mi extenso post con la fórmula sirva de referencia, me costó mucho redactarlo.

**Comment by Kiritoo** [comment]
Esto ya se arreglo.
