### ISSUE TITLE
[Glifo][Sacerdote] Glifo Palabra de Poder: Escudo

### ISSUE THREAD

**Issue by Compresor** [RoDNet/Bugtracker-Infinium-4.3.4#3321]
http://wow.freakz.ro/spells.php?spell=56160&name=glyph-of-power-word-shield 
Como bien dice sanaria un 20% de lo que absorviera el escudo (antaño estaba bug y sanaba dos veces) que hace ahora no sana nada pero ironicamente añade lo que sanaria como escudo extra para poner un ejemplo simple pongamos que sanarias unos 4k si funcionase y tu escudo ahora mismo es de 16k pues con el glifo ahroa mismo añade esos 4k asi seria al final 16k+4k =20k de absorcion.

**Comment by Compresor** [comment]
#3315

**Comment by efectokoleos** [comment]
arreglado
