### ISSUE TITLE
[Sacerdote] Palabra de poder: escudo mejorada

### ISSUE THREAD

**Issue by Compresor** [RoDNet/Bugtracker-Infinium-4.3.4#3322]
http://wow.freakz.ro/spells.php?spell=14768&name=improved-power-word-shield 

Como bien dice aumentaria la absorcion un 20% el fallo en vez de dar quita absorcion.

**Comment by Compresor** [comment]
#3315

**Comment by Kiritoo** [comment]
Esto ya se arreglo.
