### ISSUE TITLE
[Brujo] Diablillo potenciado 

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#3323]
http://wow.freakz.ro/spells.php?spell=47220
http://wow.freakz.ro/spells.php?spell=47221

Tienes un 4/8 % de que tener un fuego de alma instant al hacer daño el diablillo con bola de fuego http://wow.freakz.ro/spells.php?spell=3110

No salta nunca.

**Comment by F4NT4SM4** [comment]
si salta pero la probabilidad parece 1% casi nunca se ve es decir la probabilidad esta mal puesta

**Comment by Kiritoo** [comment]
Fix, falta compilar.
