### ISSUE TITLE
[Paladin Reprensión] Cruzada

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3324]
http://wow.freakz.ro/spells.php?spell=31868
El talento debe aumentar un 30% el daño infligido por Golpe de cruzado, Veredicto de templario, Martillo del honrado y Choque sagrado. Además provoca si se mata a un enemigo que de experiencia u honor la siguiente luz sagrada sanara un 300%.
El problema que está teniendo es que, por ejemplo Veredicto de templario debe pegar sin tener puesta la rama reprension un 235% de daño con arma y, Golpe de cruzado un 142% de daño con arma, pues con este talento debería aumentar un 30% cada uno y, ponerse veredicto con 265% y golpe de cruzado con 172% y, sin embargo, Veredicto del templario poniendo ese talento asciende a un 306% y Golpe de cruzado a un 182%, por lo que Veredicto del templario está pegando un 41% de mas y Golpe de cruzado un 10% de más y con Martillo de cólera y Choque Sagrado no lo he podido testear.

**Comment by F4NT4SM4** [comment]
Veredicto de templario pega 235% de daño arma el 30% de ese 235% es 70,5+235=305.5 =306%
esta bien si te quejas por el alto daño de los pala ps revisa 
sello de rectitud creo que pega de mas 10k he visto en el recount, sellos de mando hace que sello de rectitud pegue a todos enemigos que esten alrededor de tu objetivo pero tambien le esta haciendo daño al mismo objetivo cosa que no estoy seguro si deberia por eso no reporto

**Comment by Drogoth2** [comment]
Pues eso miralo tu f4nt4sm4 que yo no tengo el recount instalado porque se me peta el juego, en eso yo no puedo hacerlo a ojo. pero seguro que lo de veredicto es asi? que no se le añade un 30% mas simplemente?

**Comment by F4NT4SM4** [comment]
yo he intendado mirarlo pero me salen unas formula dw msw o $ y de eso yo nose ._. jaja

**Comment by F4NT4SM4** [comment]
si tienes un recount version desatualizada se freeza el juego entero cuando registra algo
