### ISSUE TITLE
[Mago] Ignición

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3326]
http://wow.freakz.ro/spells.php?spell=12846
Mi ataque crítico con bola de fuego actualmente es de 29112 y, con este talento, el objetivo debería arder un 40% extra de ese daño, es decir, debería recibir 11644 y, sin embargo, está recibiendo 16814 es decir, un 55% mas o menos

**Comment by F4NT4SM4** [comment]
todas las skill de daño periodico estan haciendo ese 55% mas o menos de daño extra por la maestria deberian ser normalmente 22% pero esta bug y esta aumentando de mas

**Comment by Drogoth2** [comment]
yo mirando las formulas de las skill del daño en el tiempo y teniendo mi maestria (que aumenta un 42% el daño de fuego en el tiempo) los calculos me salen correctos en cuanto a lo que pegan en el tiempo mis hechizos

**Comment by F4NT4SM4** [comment]
ps si no es la maestria intonce son todas las skill de daño periodico?
he testeado todas y tienen el daño de mas pense que era por la maestria base :s

**Comment by redneo** [comment]
Prueba hecha:

Critico de bola de fuego: 76532 de daño
Daño con Ignición: 2 ticks de 15223 (daño total: 30446)

40% de 76532 = 30612,8

Según esta prueba está haciendo un pelin de menos

**Comment by Drogoth2** [comment]
Con 5191 de intelecto, 7975 de poder con hechizos
Critico bola de fuego=29442
Daño ignicion=2 tick de 8600=17200
40% de 29442=11776,8
Esta haciendo 6k de más, si a este porcentaje hay que sumarle la maestria (en mi caso un 42% mas de daño de fuego en el tiempo) entonces si está bien pero nose si a ignicion debe afectarle maestria
