### ISSUE TITLE
Mision Bug "Conseguir carne fresca con carne putrefacta"

### ISSUE THREAD

**Issue by anvil159** [RoDNet/Bugtracker-Infinium-4.3.4#3328]
En vez de matar al dinosaurio te mata a ti.

**Comment by Compresor** [comment]
http://es.wowhead.com/quest=24697

Fíjate en las normas de posteo: https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by Monleon** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3342
