### ISSUE TITLE
[Mision] Engánchalos

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#333]
En tierras altas crepusculares la mision ''Engánchalos'' http://es.wowhead.com/quest=28874/enganchalos
no se puede hacer ya que los grifos deberian estar volando con los jinetes, cosa que no se da ya que los grifos estan en el suelo.

![wowscrnshot_071113_011825](https://f.cloud.github.com/assets/4895839/779923/fa5a185a-e9f1-11e2-9803-b5dba2dffd65.jpg)

**Comment by Kiritoo** [comment]
Fix
