### ISSUE TITLE
[NPC] El Archimago Vargoth no entrega el item "Familiar del Kirin Tor".

### ISSUE THREAD

**Issue by VictoriaTier** [RoDNet/Bugtracker-Infinium-4.3.4#3330]
Cuando completas el logro "Conocimiento superior" (http://es.wowhead.com/achievement=1956) se nos entrega un item llamado "Las Escuelas de la Magia Arcana: Maestría" (http://es.wowhead.com/item=43824) que nos permite acceder a una zona aislada donde se encuentra el Archimago Vargoth, al hablar con este debería entregarnos "Familiar del Kirin Tor" (http://es.wowhead.com/item=44738) que enseña a invocar un compañero, pero no se puede terminar la conversación para que esto suceda, así que no se puede conseguir dicho compañero.

**Comment by Velcositro** [comment]
Ya lo había reportado yo hace tiempo: #2935  además de que te faltó poner las ids para que lo puedan arreglar, gracias por aportar pero intenta hacerlo como debe ser la próxima vez. ^^

**Comment by VictoriaTier** [comment]
Bueno, lo he editado y lo dejaré igualmente a ver si les refresca un poco la memoria. Gracias =)

**Comment by Compresor** [comment]
Repetido, continuamos desde el más antiguo
