### ISSUE TITLE
bug skills del cazador(bestia)

### ISSUE THREAD

**Issue by leunades** [RoDNet/Bugtracker-Infinium-4.3.4#3332]
con estas fotos se describe ,mejor mi problema 
![wowscrnshot_020914_105855](https://f.cloud.github.com/assets/6630997/2119927/30a4c65e-9194-11e3-9843-7a10679c6178.jpg)

![wowscrnshot_020914_105904](https://f.cloud.github.com/assets/6630997/2119929/3aee6ed0-9194-11e3-8cd8-1ef756679d64.jpg)

**Comment by leunades** [comment]
por si no se entiende aun mi problema compre  y luego aprendí el skills controlar mascota.Luego ingreso a hechizos y sale que tengo que hablar con mi instructor.

**Comment by Pegasu5** [comment]
Ya, creo que es visual por lo menos cuando subes de nivel, a mi me va bien.

**Comment by leunades** [comment]
mas que visual ,es que no puedo controlar a mi mascota .ese  es el problema porque si fuera visual no dejo a si

**Comment by Compresor** [comment]
Pon un ticket ingame, ya que parece que este fallo es unicamente tuyo, así los MJ te podrán ayudar.
