### ISSUE TITLE
DK -PARASITO DE SANGRE-

### ISSUE THREAD

**Issue by Overseer101** [RoDNet/Bugtracker-Infinium-4.3.4#3334]
Parasito de sangre : Id 49542 (dos rangos)

Problema: Los golpes cuerpo a cuerpo ya sean con golpes blancos o con habilidades tienen un 5-10% de crear el gusano, actualmente solo salen con los golpes blancos.

**Comment by Pegasu5** [comment]
Es genial verte de nuevo Stormfury, gracias por el aporte.

**Comment by redneo** [comment]
Siento decirte que en la base de datos me dice que saltan con Successful melee attack y con Successful attack by Spell that use melee weapon
