### ISSUE TITLE
Fallos en evento "El amor está en el aire"

### ISSUE THREAD

**Issue by redneo** [RoDNet/Bugtracker-Infinium-4.3.4#3335]
Pues eso, poned aquí todos los fallos que os vayáis encontrando a ver si les doy rápida solución

**Comment by redneo** [comment]
El logro de los cohetes si que funciona testado esta mañana
http://es.wowhead.com/item=49909#contains la caja de chocolate ya da uno de los 4 items posibles una cantidad de 1 a 5

Los npcs que no estaban en Uldum ya estan.

**Comment by Dapli** [comment]
El item http://es.wowhead.com/item=49661/juego-de-coleccionista-de-talismanes-preciosos no funciona en la alianza,a pesar de que el npc lo ofrece no es obtenible,(Al menos en la alianza,ni en Darnassus,ni en Exodar,ni en Ventormenta) por lo que se vuelve prácticamente imposible conseguir los objetos del evento que requieren muchos "vales" como por ejemplo la montura.

**Comment by redneo** [comment]
Ese item te lo dan cuando aceptas una mision de collares.

**Comment by Compresor** [comment]
#3344

**Comment by Compresor** [comment]
#3343

**Comment by ghost** [comment]
La misión "Pisándole los talones(Alianza)(http://es.wowhead.com/quest=24849) no funciona.
No cuenta al entrar en el banco, tampoco en la peluquería o en la casa de subastas en el distrito de mercaderes.
Gracias!

**Comment by redneo** [comment]
Pisándole los talone arreglada

**Comment by ghost** [comment]
Gracias!!
La misión "Una charla amistosa"(alianza)(http://es.wowhead.com/quest=24657/) no se puede completar porque falta el PNJ Quejica Misilóxido(http://es.wowhead.com/npc=37715) para obtener el objeto "Libro de contabilidad de Quejica" (http://es.wowhead.com/item=49915) mediante opción de dialogo.

**Comment by redneo** [comment]
Una charla amistosa... arreglada
