### ISSUE TITLE
[Banda] Kel'Thuzad en Naxxramas.

### ISSUE THREAD

**Issue by VictoriaTier** [RoDNet/Bugtracker-Infinium-4.3.4#3337]
Toda la mazmorra de Naxxramas (http://es.wowhead.com/zone=3456) funciona más o menos bien, el problema está al llegar a Kel'Thuzad (http://es.wowhead.com/npc=15990/kelthuzad), el boss final, que no se activa ni en modalidad de 10 ni de 25. Intentaron solucionarlo ingame un par de gm y no se pudo, así que sólo queda reportarlo aquí. Gracias.

**Comment by Kiritoo** [comment]
Esto funciona perfectamente, salen las oleadas y se mata el boss, saludos.
