### ISSUE TITLE
[Druida] Talento Maestro Cambio de Forma

### ISSUE THREAD

**Issue by JereCos** [RoDNet/Bugtracker-Infinium-4.3.4#3338]
Estuve observando que este talento que es de la rama de restauración de druida 
![wowscrnshot_021014_213039](https://f.cloud.github.com/assets/6027628/2132692/f86a3104-92b3-11e3-9685-311f82d4e15b.jpg)
El problema esta, en que el punto que habla de el aumento de sanación en forma de árbol de vida/humanoide un 4% no esta funcionando siendo que si funciona en las otras formas 
![wowscrnshot_021014_213051](https://f.cloud.github.com/assets/6027628/2132705/267df26a-92b4-11e3-811d-1121a500612c.jpg)
![wowscrnshot_021014_213103](https://f.cloud.github.com/assets/6027628/2132707/2b6495b8-92b4-11e3-9ead-80a2d6a7bf68.jpg)
Pero en árbol de vida y en forma de humanoide no funciona
![wowscrnshot_021014_213109](https://f.cloud.github.com/assets/6027628/2132711/3b906fb6-92b4-11e3-9c79-2f2a17067c10.jpg)
![wowscrnshot_021014_213116](https://f.cloud.github.com/assets/6027628/2132713/3df238d4-92b4-11e3-931c-0ab94490a8e0.jpg)
Siendo que probe poniendo los talentos uno por uno, y al momento de agregar el maestro en cambio de forma no modifica la sanación base, siendo en mi caso un promedio de 7500 la sanación del hechizo de recrecimiento, tanto con ese talento activo como cuando no esta activo.

**Comment by redneo** [comment]
No te pone bufo pero si que te se sube, comprobadisimo.

Prueba a hacerte una sanacion sin ese talento y otra con ese talento.
