### ISSUE TITLE
[Misión/Objeto] Cráter de Un'Goro : Crecen tan deprisa

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3339]
Al coger la misión: 13906 te dan el objeto de misión(ítem): 46362 que al llamarlo debería de darte una misión diaria para obtener el ítem: 47196 1 c/d así a los 20 días poder completar la quest que te deja obtener una especial montura. :D

Las misiones diarias son : 
 -13905
 -13917
 -13915
 -13916 

Gracias.

**Comment by Necrofilo** [comment]
Hace un tiempo se podían sacar los 20 dientes en un mismo día.

**Comment by redneo** [comment]
Ya las tendria que dar correctamente una al dia (una de las 4 posibles)
