### ISSUE TITLE
[Mision] Guerra Total

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#334]
La mision de tierras altas crepusculares ''Guerra Total'' no se puede hacer porque los barriles que se deberian destruir uno le da clic al barril y no sucede nada..

http://es.wowhead.com/quest=28872/guerra-total

![wowscrnshot_071113_012330](https://f.cloud.github.com/assets/4895839/779941/8ec84fe8-e9f2-11e2-9fce-9d213abdc7ed.jpg)

**Comment by redneo** [comment]
Cuando caiga el server y borres temporales, tendria que ir

**Comment by Kiritoo** [comment]
Fix
