### ISSUE TITLE
[Misión] Cráter de Un'Goro: Conseguir carne fresca con carne putrefacta

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3340]
Bueno cuando tiras el objeto de misión está funcionando correctamente ya que atrae a los dinosaurios pero el problema es que no llegan a la trampa mortal y si llegan por un milagro de la vida te mueres tú y no el dinosaurio así que no te lo cuenta.

Misión: 24697

Gracias

**Comment by Monleon** [comment]
http://es.wowhead.com/quest=24697

**Comment by redneo** [comment]
Ya no te mata el foso. He hecho que si tiene el aura y lo matas te cuente como objetivo de mision.
