### ISSUE TITLE
[Misión] Cráter de Un'Goro: El ramo de la muerte

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3342]
Misión  http://es.wowhead.com/quest=24687

Problema: Es que casi no hay Sangrepétalo joven: 38213 y los contados que hay son intergeteables, deberían estar por manadas de 4 a lo mucho.

Gracias.

**Comment by Compresor** [comment]
Pegasus si puedes pon el enlace a wowhead directamente no solo la id, así podemos ver la mision al momento.

**Comment by Pegasu5** [comment]
Antes lo hacía luego dijeron que pongan solo la id, ahora otra vez xDD ok pondre los links para cuando haga más post.

Gracias

**Comment by redneo** [comment]
Ya se les puede targetear y hay como unos 18 spawneados, suficiente para hacer la mision.

Por otra parte prefirero la dirección de wowhead o cualquier enlace para que pinchando se me abra, y ahorrarme un tiempo en buscar las cosas.
