### ISSUE TITLE
 [BUG LOGRO] ¿Solo?

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#3344]
http://es.wowhead.com/achievement=1291

Cuando pones el picnic y tomas la delicia de leche, no te salta el logro. El problema está en que a la cesta del picnic no se le puede dar click, y no te pone en debuff (un corazoncito), que es lo que hace que salte el logro.

**Comment by redneo** [comment]
Atención.... Cuando caiga el servidor, hayas limpiado la carpeta cache y lo vuelvas a probar casi seguro que funcionará.

No funcionara si no ha caido el servidor, si no has limpiado cache ya que he tocado facciones de la cesta que tienes que usar y con el cache que tienes tu te saldrá que no la puedes tarjetear tal y como ocurre ahora.

Dejo el ticket abierto esperando contestación.

**Comment by Compresor** [comment]
Sigue sin funcionar segun alguns players

**Comment by redneo** [comment]
Mas cambios que tomaran efecto tras reinicio.

**Comment by Aegis-** [comment]
Me comi 3 delicias intentandolo y no me funciono T_T, pero los corazones si salen, aunque el logro no.

**Comment by Monleon** [comment]
Si no es mucha molestia guardaos los items. Estamos dando este logro regularmente a la gente en Dalaran, avisamos de ello antes siempre.
