### ISSUE TITLE
[Buff] Bendicion de Poderio 

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3346]
Nombre: Bendicion de Poderio
ID:79102
Enlace:http://wow.freakz.ro/spells.php?spell=79102
Descripcion: Aumenta el poder de ataque cuerpo a cuerpo un 20%. el poder de ataque a distancia un 10% y restaura 326p. de mana cada 5s. (los buff/auras con mismo efectos no se pueden acumular)
Problema: El poderio se esta acumulando con otras aura que tienen el mismo efecto (poder de ataque mele 20%/distancia 10%) al aplicar poderio las otras auras no deberian de hacer efecto o estar activas en el jugador simplemente deberian desaparecen en el jugador que tenga el buff poderio
un ejemplo si tengo cualquier de las otras 3 auras y un pala tira poderio este remplaza cualquier de las otras 3 auras

IDS de las otras auras: 
53137/53138 (Poderio de abominacion)
19506(Aura de disparo certero) 
30802/30808 (ira Desatada)

**Comment by Compresor** [comment]
http://www.wowhead.com/forums&topic=180217
Diría que te has colado con la bendición de poderío

**Comment by redneo** [comment]
Pa mi que no:
10% Attack Power
 Death Knight   (Spell #53138)  (Blood)
 Hunter  Trueshot Aura  (Marksmanship)
 Paladin     Blessing of Might  
 Shaman (Spell #30808)  (Enhancement)
