### ISSUE TITLE
[Misión] Península de fuego infernal: Quémalo... ¡por la Horda!

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3350]
Misión : http://es.wowhead.com/quest=10087

Problema: La misión no te provee del ítem para quemar los cañones

http://es.wowhead.com/item=27479

**Comment by redneo** [comment]
Esto... creo que jugamos en servers diferentes... si que me ha dado la antorcha
