### ISSUE TITLE
[Misión] Península de fuego infernal: Se busca Sangrevil

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3352]
Misón: http://es.wowhead.com/quest=9366

Problema: actualmente el drop rate  esta bajísimo habiando matado Terroadicto 15 apenas tengo 1

http://es.wowhead.com/item=23269

Según los comentarios está a 25.33

Gracias

**Comment by redneo** [comment]
Estaba a 39% lo he subido a 49%
