### ISSUE TITLE
[Caballero de la Muerte] Golpe de Gárgola

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#3353]
http://wow.freakz.ro/spells.php?spell=51963

En el último fixeo, seguramente se siguió la fórmula puesta del freak, que creo que es bastante aproximada a la real, pero no es del todo cierta.

Aqui expongo la fórmula: 0.453*AP + 35

**Comment by Kiritoo** [comment]
Pues no estes tan seguro:

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3133?source=cc

fixx commented 15 hours ago

"El arreglo no está hecho en base a su formula, es más ni me fije en ella."

 Wiinter commented 15 hours ago 
"seguramente se siguió la fórmula puesta del freak"

Emm no.
