### ISSUE TITLE
Bug Barrio de los magos Ventormenta y Bgs

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3356]
No se que es lo que pasa pero no puedo entrar en el barrio de los magos de Ventormenta porque automáticamente te manda donde tengas la piedra hogar.

Esto mismo parece estar pasando con las bgs. Hemos entrado 3 alis y nos ha sacado a los tres dejándonos con desertor.

Es decir, no se puede pasar.

Un saludo y gracias

**Comment by Pegasu5** [comment]
Anoche estabamos anotando arenas, es la única hora en que podemos y aun hay algunos teams que lo hacen, y de la nada a mi compa al estar probando macros en un duelo lo mandaron a gilneas dnd estaba un lvl 1, hasta se asustó xDD pensó que un gm lo andaba moviendo, algo raro pasa en el server...

**Comment by Drogoth2** [comment]
Yo no se que será, pero estábamos en ojo de la tormenta y fuera, y antes según iba al barrio de los magos también fuera, de hecho no puedes usar el portal desde dalaran a ventormenta porque te manda donde tienes tu piedra hogar.
