### ISSUE TITLE
[Abalorio] Muñeca favorita de Tyrande

### ISSUE THREAD

**Issue by stinfale** [RoDNet/Bugtracker-Infinium-4.3.4#3357]
http://es.wowhead.com/item=64645 no almacena mana la muñeca. Debería otorgar 4200 de mana después de aver gastado al menos 21mil de mana pero independientemente de la cantidad de mana gastado siempre otorga 1 de mana que se puede ver si activas la opción para visualizar las ganancias de mana, solo salta +1 mana. El daño arcano que realiza parece estar medianamente correcto pero también seria bueno que lo revisaran.

**Comment by Monleon** [comment]
Ya debería funcionar.
