### ISSUE TITLE
[BUG ZONA] Torre de los magos - Ojo de la tormenta

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#3358]
Cuando estás a escasos metros de esta base, el juego te lleva directamente al lugar donde tengas la piedra del hogar, lo cual, aparte de sacarte de bg, te marca como desertor y no puedes anotar de nuevo.

**Comment by juaks** [comment]
Esto me ha pasado hoy 3 veces pero no ahí, sino primero en Las Mil Agujas, y luego en Uldum (Oasis de Vir'Sar)

**Comment by juaks** [comment]
No puedo salir de Dalaran volando porque me devuelve a la Piedra de Hogar...

**Comment by Monleon** [comment]
Aun sucede?

**Comment by juaks** [comment]
A mi no me ha vuelto a pasar.
