### ISSUE TITLE
[Misión] Tundra Boreal: ¡Entierra a esas cucarachas!

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3359]
Misión: http://es.wowhead.com/quest=11608

Problema Hay dos sumideros que no explotan al colocar la bomba y no los cuenta para completar la misión; Oeste y Norte.

PD:Si alguien me confirma que pudo hacerla ya que intenté todo, lo que dice en los comments de whead y nada.

Gracias.

**Comment by Monleon** [comment]
Comprobado que dejando la quest y volviéndola a coger funciona

**Comment by redneo** [comment]
No, habia un par de "bunnyes" fuera de lugar, ya los he movido. Lo malo es que al poner la bomba salen despedido de nuevo, aunque tres o cuatro veces si que se puede hacer la mision.
