### ISSUE TITLE
[Joyería] Prospectar

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#336]
Buenas.
Queria decirles que la habilidad de joyería, prospectar (http://es.wowhead.com/spell=31252), no está funcionando con ninguna de estas menas:
Mena de obsidium (http://es.wowhead.com/item=53038)
Mena de elementium (http://es.wowhead.com/item=52185)
Mena de pirita (http://es.wowhead.com/item=52183)
Probé con las menas de cobre y funciona perfectamente, pero quiero prospectar alguna de las anteriores y me sale "No hay gemas en esto" en rojo.
Mas tarde pruebo con otras menas y edito el post si descubro algo mas.
Muchas gracias y hasta luego.

**Comment by redneo** [comment]
arreglado
