### ISSUE TITLE
[Misión] Zul'drak: El Anfiteatro de la Angustia: ¡Yggdras!

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3361]
Misión: http://es.wowhead.com/quest=12932

Problema: El npc Promotor de lucha del anfiteatro no comienza con sus diálogos, para llamar al Yggdras, no se puede matar y no se puede hacer la misión por lo tanto se pierde una importante cadena para levear más rápido,

Gracias.

**Comment by redneo** [comment]
Cuando caiga el server tendria que ir 100%
