### ISSUE TITLE
[Misiones] Torneo Argenta, varias misiones importantes bug.

### ISSUE THREAD

**Issue by VictoriaTier** [RoDNet/Bugtracker-Infinium-4.3.4#3362]
Empezaré por la cadena del Caballero Negro, todo bien hasta llegar a "Las órdenes del caballero negro" (http://es.wowhead.com/quest=13663) donde no se puede montar al hipogrifo ni llevar a cabo, por tanto, el resto de la misión. 

Por otro lado, tras completar la misión "El desafío del aspirante" (http://es.wowhead.com/quest=13679#comments) no entregan la siguiente que sería "Un valoroso de Ventormenta" (http://es.wowhead.com/quest=13684/a-valiant-of-stormwind#english-comments) o la que corresponda según la raza que es para ir sacando los logros para obtener el logro final "Campeón de la Alianza" (http://es.wowhead.com/achievement=2782). Es posible que esto sea sólo en el caso de los huarguen, al no estar Gilneas y haya algún error que no los reconozca como de Ventormenta. He preguntado pero nadie las ha hecho así que... no estoy segura.

Luego otra misión bug sería "El filo del invierno" (http://es.wowhead.com/quest=13670). Tras conseguir el item y llegar a Fiordo Aquilonal no te deja usarlo para descongelar a la doncella del lago(http://es.wowhead.com/npc=33303). Esta es una de las pocas diarias que dan como recompensa Sello de Aspirante (http://es.wowhead.com/item=45192/sello-de-aspirante).

Estas son las que he comprobado personalmente, no sé si habrá más. Un saludo.

**Comment by Compresor** [comment]
Te agradecería que pusieras cada misión en un issue separado. Así no será más cómodo.

**Comment by ghost** [comment]
Lamentablemente los huargen no podemos hacer las de "Valeroso de X ciudad", esto esta bugeado hasta en el offi (http://eu.battle.net/wow/en/forum/topic/6492950260?page=1) (http://www.wowhead.com/forums&topic=181615/).
Saludos!

**Comment by redneo** [comment]
Las ordenes del caballero negro creo que lo arreglé, comentadme si es asi. El resto (huarguens y goblins) a ver como lo solucionamos.

Edito: Ya tendrian que dar la mision Un valeroso de ventormenta a huarguen y un valeroso de orgrimmar a los goblin.

**Comment by VictoriaTier** [comment]
Confirmado, las órdenes del caballero negro solucionada, incluyendo la que da logro.
En cuanto a los huargens, ahora sí da "Un valoroso de Ventormenta" (http://es.wowhead.com/quest=13684) pero al entregarla no continua la cadena con La carga del Valeroso. ("http://es.wowhead.com/quest=13718").
Gracias.
