### ISSUE TITLE
[Maestria] (Chaman restauracion) Sanacion profunda 

### ISSUE THREAD

**Issue by toxicity93** [RoDNet/Bugtracker-Infinium-4.3.4#3363]
Nombre: Sanacion profunda
Enlace: http://es.wowhead.com/spell=77226/maestria-sanacion-profunda#modifies
Descripción: Aumenta la potencia de tus hechizos de sanación hasta un 24%, en función del nivel de salud actual de tu objetivo (los objetivos con la salud más baja se sanan más).
Problema: en lugar de aumentar la sanacion 3% por punto de maestria aumenta 2%.

**Comment by Kiritoo** [comment]
Arreglada, falta compilar.
