### ISSUE TITLE
[Hechizo-Cazador]Fingir muerte

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3364]
Nombre: Fingir muerte
Enlace: http://wow.freakz.ro/spells.php?spell=5384
Problema: 1ro. En ocasiones luego de usar el hechizo se pierde todo el enfoque del cazador, no debiendo ser así.
2do. También en ocasiones, al levantarte luego de fingir muerte, el hechizo queda bug y aún cuando su tiempo de reutilización queda bien, no así su visualización. No se puede ver cuanto tiempo le falta para estar en uso.

**Comment by efectokoleos** [comment]
arreglado
