### ISSUE TITLE
[Hechizo-Cazador]Disuación

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3365]
Nombre: Disuación
Enlace: http://es.wowhead.com/spell=19263/disuasion
Problema: En los últimos días he visto que teniendo disuación, he recibido hechizos de asustar del mago, sacer y otro tipo de hechizos que no deben pasar al tener disuación activo.
Observación: Disuación no te hace inmune a todos los hechizos, hay algunos que si pasan. Pero según tengo entendido, los hechizos de miedo del brujo, asustar del sacerdote no deben pasar, y están traspasando (junto con otros hechizos que igual no deberían, pero sobre todo los de asustar me han llamado la atención pues es una táctica usual usar Disuación cuando se ve que alguien los castea contra mi).

**Comment by Pegasu5** [comment]
Algunas cosas de rogue, pala y druida feral, pasan y no estoy seguro que deberían, como el martillo de cólera del pala.

**Comment by qulki** [comment]
Sólo entran ataques cuando le das la espalda a tu objetivo. Ahora bien, desde el parche 3.3 (creo recordar), disuasión también evade ataques por la espalda. No sé si en cata quitaron esa mejoría o si realmente está bug.

**Comment by Jhovanni** [comment]
Esta es la página donde se informan los fixes de Disuación (Deterrence)
http://www.wowwiki.com/Deterrence

Como bien dice Qulki, en Woltk recibió un cambio significando que serviría tambien al estar de espaldas. Igual han habido más cambios luego de ese entonces, es posible que afectaran la dinámica, pero no se ve algún regreso a tener que estar de frente. Habrá que ver si el cambio de porcentajes a inmunidad que recibió afectan en alguna manera.

Extra. Por otro lado, me parece que en el server en ocasiones he recibido hechizos de cc teniendo de frente al enemigo. Habrá que probarse más.

**Comment by Necrofilo** [comment]
Lo he comprobado con mi rogue en AT, los ataques no deben entrar por ninguna parte.

**Comment by qulki** [comment]
Lo que sí he visto es que disuasión no disuade hechizos una vez te los han casteado, es decir, que si ves el hechizo acercarse a ti y te tiras disuasión te entra igualmente, y creo que no debería ser así, y que debe actuar como la fusión de las sombras de los elfos de la noche (al menos ha sido siempre así).

**Comment by Jhovanni** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3505

**Comment by Kiritoo** [comment]
Esto está arreglado.
