### ISSUE TITLE
[Mision]  [¡Zeth'Gor debe arder!]

### ISSUE THREAD

**Issue by Downingk9** [RoDNet/Bugtracker-Infinium-4.3.4#3367]
Bueno, lo que sucede es que.. Al activar el barril, se prende la torre pero no me cuenta como logrado, solo aparece el barril incendiendo la torre, de antemano.

http://es.wowhead.com/quest=10895/zethgor-debe-arder

Gracias. :)

**Comment by redneo** [comment]
arreglada
