### ISSUE TITLE
[BUG] Cuevas de los lamentos

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#3368]
EL boss Skun no está en la mazmorra, lo que impide que pueda hacerse la mazmorra completa.

http://es.wowhead.com/npc=3674

**Comment by Pegasu5** [comment]
Yo la hice completa, hace días recientes y tengo hasta el logro :D será ´porque ese bicho es un miniboss a lo mejor.

**Comment by Kiritoo** [comment]
Arreglado.
