### ISSUE TITLE
Premio de cocina de Dalaran

### ISSUE THREAD

**Issue by Szajil** [RoDNet/Bugtracker-Infinium-4.3.4#3369]
Al hacer las misiones diarias de cocina de Dalaran me dan como recompensa unas bolsas en las que hay http://es.wowhead.com/item=43016/premio-de-cocina-de-dalaran. 
Estas monedasse me quedan en la mochila, como si fueran objetos, y no las puedo usar para comprar las recetas de Dalaran.

**Comment by redneo** [comment]
El premio te lo dan al completar la mision y se te guarda en el monedero correctamente. El item ese esta obsoleto y como tal lo he borrado del loot de las bolsas. Puedes hacer lo mismo.
