### ISSUE TITLE
[Misión]¡El monstruo del foso!

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#337]
Te da una bolsa, pero en la bolsa no hay nada entonces ni lo puedes invocar ni alimentar.

Aqui dejo el link: http://es.wowhead.com/quest=29361

**Comment by redneo** [comment]
La bolsa ya da los items

**Comment by Wiinter** [comment]
Ahora no funcionan los items de la bolsa, no puedes dar de comer al monstruo

**Comment by searum** [comment]
fixed
