### ISSUE TITLE
[Talento-Cazador]Aura de disparo certero

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3370]
Nombre: Aura de disparo certero
Enlace: http://wow.freakz.ro/spells.php?spell=31519
Problema: Al salir de bg, en un buen porcentaje de ocasiones, el aura se pieder, no quedando otra opción que cambiar especialización de talentos y regresar luego a puntería una vez más para obtener el aura de nuevo.

**Comment by redneo** [comment]
Problema: Aura de disparo certero, antes se sumaba a otros auras del mismo tipo como por ejemplo 
http://wow.freakz.ro/spells.php?spell=53138 Sumando la ap de todo el grupo un 40% ahora solo puede estar un bufo de esos activos a la vez, si tienes tu aura de hunter llega un dk y se echar la suya puede que pases dos cosas, una que te quite tu aura y ponga la suya o que tu aura se mantenga y no te ponga la suya.

En el primer caso, al salir de bg, te quedaras sin ambas, tocando reloguear, cambiar de talentos, revivir para que se te ponga.

Lo mismo pasa con otros auras que antes si que se sumaban cuando no tendrian que sumarse.

**Comment by Jhovanni** [comment]
¿Entónces significa que no hay bug? Lo correcto no sería que siempre mantenga el cazador su propia aura, y cuando haya otra activa no se solapen, pero que tampoco el cazador pierda su aura. Pues lo de tener que cambiar talentos o revivir no lo había visto nunca, y no tengo muy claro ese asunto.
PD. El tema ya ha sido cerrado, lo se; pero me gustaría saber entonces si siempre es así, que se debe borrar el aura, o ha sido una medida impuesta por el staff para poder implementar los no-solapamientos de aura.
