### ISSUE TITLE
Nucleo magma: boss con el lot bug y npc

### ISSUE THREAD

**Issue by feniix97** [RoDNet/Bugtracker-Infinium-4.3.4#3373]
Bueno esto es para ver si los gms pueden reparar el botín de los siguientes boss ya que siendo una de las raids clásicas la mayoría quiere o le gustaría conseguir la tier 1 de su clase favorita.
 Raid núcleo magma:http://es.wowhead.com/zone=2717/nucleo-de-magma#drops:50-2

Boss: gehennas:http://es.wowhead.com/npc=12259
Bug de lot: solo suelta 1 pieza de armadura ya revise con varios de mis pjs y no cambia el numero de lot siempre una sola cosa.

Boss: presagista sulfuron:http://es.wowhead.com/npc=12098
Bug de lot: mismo problema que con el primero solo suelta una pieza de armadura

Boss:shazzrah:http://es.wowhead.com/npc=12264
Bug de lot: mismo problema

Boss: barón geddon:http://es.wowhead.com/npc=12056
Bug de lot: este boss ya varias veces solo soltó esencia de fuego:http://es.wowhead.com/item=7078
y núcleo ígneo:http://es.wowhead.com/item=17010
no se si drapeará algo mas pero ya con hacerlo 3 veces y dar lo mismo supongo que el lot esta bug.
 bueno eso serian los boss que tienen el dropeo del botín bug.

Entre los npc como los canes y elementales de roca y lava:
can del núcleo:http://es.wowhead.com/npc=11673
Bug: no sueltan nada

Señor del fuego:http://es.wowhead.com/npc=11668
Bug del botín: solo dropea núcleo ígneo como máximo:http://es.wowhead.com/item=17010
después de matar 60 de ellos solo eso sueltan

Gigante fundido:http://es.wowhead.com/npc=11658
Bug del botín: solo sueltan una cosa y es carbón:http://es.wowhead.com/item=3857
o tierra elemental:http://es.wowhead.com/item=7067

Aniquilador de lava:
Bug: solo  dropean una cosa piedra solida:http://es.wowhead.com/item=7912
o núcleo de lava:http://es.wowhead.com/item=17011

El drop del botín no se si será tan bajo pero para ser una raid de 40 jugadores estoy seguro q tendría que salir mas cosas q esas solas

**Comment by redneo** [comment]
Gehennas: http://es.wowhead.com/npc=12259 Una pieza de tier, un item morado siempre.
Presagista Sulfuron: http://es.wowhead.com/npc=12098 una pieza de tier o arma de asta y un item morado siempre....

Freno, freno, freno...
Te explico como van estos loots:
Por ejemplo: http://es.wowhead.com/npc=12259  Gehennas Tiene un 100% de posibilidades de sacar uno de los seis posibles piezas de tier. Siempre ha de soltar una.
Luego tiene un 5% de posibilidades de que suelte UNO de los objetos morados siguientes que vienen en el loot.
Y por último tiene un 1% de que saque UNA de las recetas que puede soltar.

Can de Núcleo tiene unos porcentajes muy bajos de soltar varias cosas, con la misma tematica que lo anterior. A lo mejor tiene un 1% de soltar uno de los 18 objetos del tier. Lo mismo pasa con el resto de trashes

Está revisado y están bien los loots. Revierto los cambios anteriores.
