### ISSUE TITLE
[NPC] Harrison Jones (Misión: ¡Armacola!)

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#3374]
NPC: http://es.wowhead.com/npc=48082
Bug: El npc no se encuentra en el lugar al completar la misión ¡Armacola! (http://es.wowhead.com/quest=27905), se supone que debería aparecer en el mismo lugar al que es teletransportado el jugador al completarla. Es necesario que aparezca para poder entregarle la misión.

Extra: Este bug fue reportado hace 4 meses (con foto incluida) en #2510 pero al parecer el Npc sí estaba por lo que el reporte fue cerrado. En mi caso comprobé que el Npc no aparece completando la misión 2 veces.

**Comment by redneo** [comment]
Teoricamente ya tendria que estar correctamente, me lo pruebas y cierras el Bugttracker en caso que se haya solucionado

**Comment by Velcositro** [comment]
Arreglada, gracias. Cierro.
