### ISSUE TITLE
[NPC][Misión] Sullah

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#3375]
NPC: http://es.wowhead.com/npc=48431

Bug: No me da la misión "El pequeño Jones ha mandado a buscarte" (http://es.wowhead.com/quest=28353), se supone que debe dármela después de completar "Maestro trampero" (http://es.wowhead.com/quest=28350) y eso ya lo hice.

**Comment by redneo** [comment]
esto... a mi si que me la ha dado :S

**Comment by Velcositro** [comment]
Entonces será algo de mi pj... o que la hice en WH o aquí en algún otro momento cuando las cadenas no funcionaban bien. Gracias igualmente.
