### ISSUE TITLE
[Mazmorra/Bandas][Items/Objetos][Murallas del Fuego Infernal] Cofre de hierro vil reforzado (Heroico)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3377]
Buenas.
• Nombre: Cofre de hierro vil reforzado
• Enlace: http://es.wowhead.com/object=185168
• Problema: El cofre no se puede clickear para despojar.
• Observaciones: Aparece luego de vencer a los PNJ Vazruden el Heraldo (http://es.wowhead.com/npc=17307) y Nazan (http://es.wowhead.com/npc=17536); funciona en el modo normal de la mazmorra. Por sugerencia de un GM, ya intenté matar a Nazan primero y Vazruden al último, pero tampoco funciona.
Gracias!!

**Comment by Compresor** [comment]
#3378 Seguimos des de ahi porque son lo mismo
