### ISSUE TITLE
[Mazmorra/Bandas][Items/Objetos][Murallas del Fuego Infernal] Cofre de hierro vil reforzado (Heroico)

### ISSUE THREAD

**Issue by proezas** [RoDNet/Bugtracker-Infinium-4.3.4#3378]
Buenas.
• Nombre: Cofre de hierro vil reforzado
• Enlace: http://es.wowhead.com/object=185168
• Problema: El cofre no se puede clickear para despojar.
• Observaciones: Aparece luego de vencer a los PNJ Vazruden el Heraldo (http://es.wowhead.com/npc=17307) y Nazan (http://es.wowhead.com/npc=17536); funciona en el modo normal de la mazmorra. Por sugerencia de un GM, ya intenté matar a Nazan primero y Vazruden al último, pero tampoco funciona.
aSaludos.

**Comment by Kiritoo** [comment]
PD: Ya perdí la cuenta de las personas que reportaron este bug , ya que in game solo nos dicen que reportemos aquí tienen una de los muchos reportes ( de nuevo ). 

A que viene esta PD, esto es para reportar las cosas no para poner comentarios. ¿Desde cuando se reportan las cosas por ticket ingame?

**Comment by redneo** [comment]
El problema es el mismo en normal? o solo pasa en heroico?

**Comment by proezas** [comment]
pasa en las 2 si pero en la que mas farmeo y lo mato de todas las maneras fue en hero w

**Comment by redneo** [comment]
fixed
