### ISSUE TITLE
[Misión] Montañas Filoespadas - Las piedras de Vekh'nir

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#3379]
http://es.wowhead.com/quest=10565

Al obtener el cristal cargado, vas a completar la misión para que te de la recompensa y no te deja. Es como si no te reconociese el cristal cargado (http://es.wowhead.com/item=30567)

**Comment by ghost** [comment]
Reparada.
