### ISSUE TITLE
[Mision] Torneo argenta - La caida del caballero negro  #13664

### ISSUE THREAD

**Issue by RaulioWoW** [RoDNet/Bugtracker-Infinium-4.3.4#3380]
Mision: http://es.wowhead.com/quest=13664/la-caida-del-caballero-negro

Descripción
Tenemos que acabar con la conspiración del Caballero Negro y demostrarles a los que se enfrentan a nosotros que no permitiremos que asesinen a nuestros campeones.

Tienes que retar al Caballero Negro y vencerle en combate, <nombre>.

Usa mi destrero Argenta para la batalla. Está en los establos.

Habla con el escudero Cavin en La Liza de los Campeones. El escudero llamará a armas al Caballero Negro, pero tú harás que responda de sus crímenes. 

Problema: Hablas con el escudero cavin, y te da la opcion de pedir invocar al caballero negro, pero al darle clic no pasa nada, no lo invoca.

**Comment by redneo** [comment]
Arreglada
