### ISSUE TITLE
Alarido bugeado

### ISSUE THREAD

**Issue by feniix97** [RoDNet/Bugtracker-Infinium-4.3.4#3384]
Bueno lo posteo ya que si mando ticket no harán nada

Alarido psíquico:http://es.wowhead.com/spell=8122/alarido-psiquico#screenshots
Bug: a dejado de funcionar en todos los sacerdotes ya no asusta los que están a tu alrededor en un radio de 8 metros.

**Comment by Monleon** [comment]
Esto ya debería ir como hasta ahora. Si queda alguna spell de radio que no funcione como debe, avisadnos.
