### ISSUE TITLE
Totem cólera del aire (Chamán)

### ISSUE THREAD

**Issue by Cantadal** [RoDNet/Bugtracker-Infinium-4.3.4#3386]
Totem cólera del aire del chaman no pone el buffo de  5% de celeridad con hechizos.
http://es.wowhead.com/spell=68933/totem-colera-de-aire

**Comment by Wiinter** [comment]
Hace poco implementaron lo de la solapacion de buffos, puede ser que estuvieras en grupo con un pollo o un sacer sombras? Si es asi, ellos te dan el mismo buffo, haciendo que no se repita el mismo beneficio dos veces.

**Comment by redneo** [comment]
Correcto funciona perfectamente, solo que no suma auras con otros spells por el estilo

**Comment by Cantadal** [comment]
Ya pero estoy sin raid yo solo leveando y no me pone el buff de 5% de celeridad y no tengo ningún otro buffo de celeridad, solo el de 5% de critico del chaman elemental. NO entiendo entonces
