### ISSUE TITLE
[Spell] Pícaro - Envenenar

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#3388]
Hola quiero reportar el siguiente hechizo del pícaro.

Envenenar - http://cata.openwow.com/spell=32645

Problema: El problema de este hechizo es que pega casi el doble de lo que debería.
Actualmente le estoy pegando a un dk con un 47% de reducción lo que le debería de pegar sin reducción alguna y si se quita la armadura le pego casi el doble de lo que debería.

Un saludo.

**Comment by Kiritoo** [comment]
Esto pega correctamente.
