### ISSUE TITLE
[Mision] Cazar a las cazadoras

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#339]
La mision: http://es.wowhead.com/quest=903/cazar-a-las-cazadoras ''Cazar a las cazadoras'' no se puede hacer ya que al matar a las cazadoras: http://es.wowhead.com/npc=3415/cazadora-de-la-sabana no dropean nada
mate unas 20 y no me dieron drop de nada

![wowscrnshot_071113_033252](https://f.cloud.github.com/assets/4895839/780456/efe6b01e-ea04-11e2-9968-de975f458fda.jpg)

**Comment by redneo** [comment]
Ya lo tiran.
