### ISSUE TITLE
[Glifo] de Tótem corriente de sanación

### ISSUE THREAD

**Issue by cibernaco** [RoDNet/Bugtracker-Infinium-4.3.4#3396]
Buenas, pues eso que el glifo no funciona, este glifo debería de hacer que tu tótem corriente de sanación, ademas de curar, aumente las resistencias.
El funcionamiento correcto seria; como condicionante indispensable, estar en grupo o raid, y una vez plantas el tótem en el suelo, ademas de curar debería de aumentar las resistencias al Fuego, la escarcha y a la Naturaleza de los miembros del grupo o banda. El caso es que no lo hace, se queda como si no tuvieras el glifo y solo cura.

**Comment by efectokoleos** [comment]
arreglado
