### ISSUE TITLE
[Mascotas] Sin habilidades.

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3399]
Problema: si por error arrastras una de las habilidades de la mascota fuera de la barra, luego es imposible volver a colocarla ya que al desmontar de montura la habilidad desaparece de nuevo y tienes que colocarla a cada rato.

 Pasa en cazadores y brujos (no he probado con frost mage).

**Comment by Pegasu5** [comment]
Hmm en los cazadores hace mucho dejo de suceder al menos si pasas moviendo las habilidades, es posible que se buguee de esa forma pero si las colocas la primera vez al menos así te evitas ese problemas mientras se arregla el fallo, igual en los cazadores es tan sencillo como coger una nueva pet,en cambio el lock/mage no xd

**Comment by Necrofilo** [comment]
Pues será esolo en tu caso, no soy el único al que le pasa.

**Comment by F4NT4SM4** [comment]
el esbirro del dk las habilidades especiales se mantienen pero los comandos basicos como atacar, agresividad, denfesivo, etc... no se mantienen se borran al subir montura
