### ISSUE TITLE
[Cazador]Llamar a mascota

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#34]
Hola

Llamar a mascota
http://es.wowhead.com/spell=67777

Cuando le doi click al icono no me aparece ninguna de las mascotas.
![wowscrnshot_070413_013409](https://f.cloud.github.com/assets/3537253/746914/17beff72-e43f-11e2-88cf-96851608e426.jpg)
Como se ve en la imagen tengo el icono en la barra de hechizos.

Ahora pongo una imagen despues de reloguear.
![wowscrnshot_070413_013436](https://f.cloud.github.com/assets/3537253/746915/329f3d5c-e43f-11e2-9a7d-8ca7c1d5ee1c.jpg)

Cada vez que relogueo me desaparece el llamar a mascota de la barra de hechizos teniendo que abrir el libro.
Un saludo.

**Comment by Dekadencee** [comment]
Fixed, necesitamos que el server se caiga para que se apliquen los cambios, pero por lo visto nos hemos pasado con la estabilidad y no se cae, si sigue sin caerse lo reiniciaremos en un par de horas con el rollback incluido.

Gracias por el reporte

**Comment by crowel** [comment]
Hola queria comentar que me sigue desapareciendo LLamar a mascota tras reloguear y que tampoco puedo usarlo desde mi barra de hechizos, no aparecen los silbatos al clickear, como se ve en la siguiente imagen.
![wowscrnshot_071013_143913](https://f.cloud.github.com/assets/3537253/774581/c13ac7f2-e95d-11e2-8852-b6063288045c.jpg)

Sin embargo desde el libro de hechizos si lo puedo ver.
![wowscrnshot_071013_144003](https://f.cloud.github.com/assets/3537253/774587/e04594e2-e95d-11e2-8343-e260f56fe73e.jpg)

Porfavor seria de agradecer si un cazador confirmara estas dos cosas, tras reloguear que desaparezca de la barra de hechizos, llamar a mascota y si puede llamarlas desde el icono en las barras de acción.

Un saludo.
