### ISSUE TITLE
[BUG] Crear objetos pvp 377

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#340]
Buenas, os comento, he visto que al crear los objetos de set y luego el resto funciona correctamente, pero si intentas crear:

Capas - Anillos - Collares

Te sale lo siguiente aunque tengas mats: "El hechizo no está disponible para ti", lo cual fastidia un poco, ya que no te puedes hacer todo el equipo "nuevo" xD

![wowscrnshot_071113_110617](https://f.cloud.github.com/assets/3328374/780611/4d7231a0-ea09-11e2-956d-d5a5192f2bf1.jpg)

Un saludo.

**Comment by Dekadencee** [comment]
No se pueden crear items de la temporada superior a la s10 mediante profesión, no es un bug, está capado a posta por nosotros con el fín de mantener las temporadas.

Un saludo ^^
