### ISSUE TITLE
[Zona Hyjal] El círculo de las cenizas.

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3400]
Problema: los adds pelean entre ellos, y al morir alguno vienen todos a por ti y gran parte en evadir.

 Adds: Elemental vinculado a las llamas, Vencedor Crepuscular, Clamallamas Crepuscular.

Aparte de seguirte estando en evadir, aunque solo pases por la zona en montura voladora y sigas tu camino te deja bugeado en combate.

**Comment by Compresor** [comment]
Podrías poner las ids de los mobs?

**Comment by Dekadencee** [comment]
Posible fix implementado tras la siguiente compilación, si el error permanece por favor abrir un nuevo issue.
