### ISSUE TITLE
[Boss Firelands] Beht'tilac (Devastación humeante).

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3404]
Enlace: http://es.wowhead.com/spell=99052

Problema: no solo está afectando al piso superior, sino que hace instant kill a toda la banda esté arriba o abajo (no respeta el piso).

**Comment by F4NT4SM4** [comment]
es que el boss intenta atacar a los que estan abajo ya que no hay nadie ariba
intentando bajar y traspasa la telaraña si en ese momento qeu traspasa la telaraña usa devastacion humeante inst kill :s 
que el tanke se quede ariba hasta que este tenga 3 de energia y use devastacion humeante ariba

**Comment by Necrofilo** [comment]
Yammm.. es que nosotros no sabemos hacer el boss, sabes?
 Estamos usando la misma mecánica que usaba en el oficial, has probado a tirarlo últimamente?

**Comment by F4NT4SM4** [comment]
no digo que este bien
me refiero a que miesntra reparan el bug de las textura para que el boss no baje en la primera fase
hagan eso de que el tankee no baje hasta que este apunto de usarlo 
para que el skill lo tire ariba y no le pege abajo

**Comment by Necrofilo** [comment]
Es que eso es lo que hicimos.
