### ISSUE TITLE
[Misión] Libera tu mente, lo demás viene solo.

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3406]
Enlace: http://es.wowhead.com/quest=25298

Objetivo: Habla con 8 servidores Crepusculares para administrarles el jarabe y salvarlos.

-Problema: si haces click repetidamente sobre un mismo objetivo de misión, te cuenta varias veces.
  Ejemplo: haces un click, te cuenta como 1/8; haces 2 clicks seguidos, te cuenta como 2/8 con un solo objetivo.

**Comment by mccelobb** [comment]
Pasa en la mayoria de quests de este estilo

**Comment by redneo** [comment]
Si, pasa en muchas misiones, estoy al tanto, podria ponerlo mas ajustado, que no te deje hacer nada mas al recibir el primer gossip, spell o lo que sea, pero cuesta mucho.

Moraleja, no lo hagas así tiene más emoción la misión :P
