### ISSUE TITLE
Bug en la mision de Thalorien Buscalba de la cadena de misiones de Quel´delar

### ISSUE THREAD

**Issue by blackout15** [RoDNet/Bugtracker-Infinium-4.3.4#3407]
Esta misión http://es.wowhead.com/quest=24563 manda a buscar un NPC pero no se encuentra en la zona donde debe de estar y por lo tanto no se puede terminar la mision. este es el NPC que debe aparecer y no esta 
![152852](https://f.cloud.github.com/assets/6766043/2241760/4c2cc35a-9ce2-11e3-9604-04349fe83949.jpg)

**Comment by Drogoth2** [comment]
Lleva reportado ya un tiempo esto, #2817
