### ISSUE TITLE
[Zona] Nave de guera de la Alianza, Infralar.

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3408]
Mmm bien, no sé como buscar la ID, pero creo que ya sabréis de qué se trata, es una nave donde se hacen una cadena de misiones.

Problema: cuando estás haciendo las misiones, cada 2x3 te manda fuera del mapa y al morir por la caída no puedes llegar a tu cuerpo para resucitar.

IMAGEN:
![wowscrnshot_022414_124923arr](https://f.cloud.github.com/assets/6006693/2245158/7236387e-9d4b-11e3-8604-cfda32167fd2.jpg)

**Comment by Compresor** [comment]
Diría que está reparado. Me lo podrías confirmar?

**Comment by Dekadencee** [comment]
Fixed
