### ISSUE TITLE
[BUG] "Visual" al interactuar con el buzón

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#341]
Cuando le das al buzón para mandar un correo, los personajes se quedan de esta manera:

![wowscrnshot_071113_112815](https://f.cloud.github.com/assets/3328374/780739/6760c344-ea0c-11e2-9ce8-00bf883e116b.jpg)

En montura de una y a pie de otra jaja. Es muy cómico. Un saludo.

**Comment by SherBlader** [comment]
Que pasho hermano.. xD

**Comment by crowel** [comment]
Lo de las manos es normal estan leyendo la correspondencia xD.
Es así.

**Comment by Velcositro** [comment]
Debería tener un pergamino entre las manos, eso si está bug.

**Comment by redneo** [comment]
Asi está bien!
