### ISSUE TITLE
[Talento Paladin] Proposito Divino

### ISSUE THREAD

**Issue by Aegis-** [RoDNet/Bugtracker-Infinium-4.3.4#3410]
http://wow.freakz.ro/spells.php?spell=85256

Según la descripcion de este talento es que cuando se activa y usas una facultad de poder sagrado, esta es gratis pero no tienen el efecto de 3 cargas de poder sagrado a menos que tengas las 3 cargas. Osea si tenes 1 carga y se activa el talento y usas una facultad de poder sagrado, esta se usara como si consumiera solo 1 poder sagrado, pero segun el talento deberia utilizarse como si utilizara 3 poderes sagrados sin gastar ninguno!

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
