### ISSUE TITLE
[Hechizo Paladin] Veredicto de Templario

### ISSUE THREAD

**Issue by Aegis-** [RoDNet/Bugtracker-Infinium-4.3.4#3411]
http://wow.freakz.ro/spells.php?spell=85256

El problema con esta facultad, es que algunas veces cuando tenes 2 o 3 cargas de poder sagrado y lo utilizas solo gasta 1 carga del poder sagrado, pero deberia consumirlas todas! Aunque esto solo ocurre algunas veces, es bastante molesto porque al consumir solo 1 de las cargas de poder sagrado el daño se reduce considerablemente, en especial cuando utilizas Fanatismo y podes regenerar rapidamente las cargas de poder sagrado, por culpa de este problema se pierde bastante daño.

**Comment by efectokoleos** [comment]
arreglado
