### ISSUE TITLE
[Glifo Paladin] Glifo de Exorcismo

### ISSUE THREAD

**Issue by Aegis-** [RoDNet/Bugtracker-Infinium-4.3.4#3412]
http://wow.freakz.ro/spells.php?spell=54934&name=glyph-of-exorcism

Me fije si de verdad hacia un 20% más de daño durantes esos 6 segundos y siempre ocurria lo mismo: Sin importar el daño que realizaba con exorcismo siempre quedaba un DoT de 6 segundos que realizaba 184 cada 2 segundos(osea 3 veces en esos 6 segundos). Por ejemplo realizo 8400 de daño con exorcismo y el DoT deberia hacer el 20% del daño más...Pero el 20% de 8400 es 1680 y 184 x 3 ni se acerca a 1680! Este glifo esta claramente mal.

**Comment by efectokoleos** [comment]
arreglado
