### ISSUE TITLE
[Mazmorra] La Matanza de Stratholme

### ISSUE THREAD

**Issue by Aegis-** [RoDNet/Bugtracker-Infinium-4.3.4#3413]
http://es.wowhead.com/zone=4100/la-matanza-de-stratholme
Antes habian reportado esta mazmorra pero al parecer sigue bug.
Los 2 problemas que encontre:
El primero es que al hablar con Arthas no ocurre nada, simplemente eso, no aparecen enemigos, bosses, ni nada entonces no se puede completar la mazmorra.
El otro bug que vi es que cuando llame al primer mob que esta dentro de la mazmorra que es una araña, esta traspasa la tierra y se va muy profundo sin nunca volver a subir. Lo mismo pasa con la invocacion del angel del paladin, la invoco y desaparece debajo de la tierra.

**Comment by Monleon** [comment]
Ya funciona correctamente.
