### ISSUE TITLE
[Bug Global] Combate

### ISSUE THREAD

**Issue by Aegis-** [RoDNet/Bugtracker-Infinium-4.3.4#3414]
Para explicar que sucede en este bug que encontre dare unos ejemplos:
Hoy estaba probando daños de poderes con los muñecos de entrenamiento de Ventormenta. Luego un dk viene y se pone a pegarle a ese muñeco. Yo paro de golpearlo para pasarme los talentos a mi dual, pero me doy cuenta de que no puedo porque estoy en combate. Al parecer el dk se puso afk golpeando melee al muñeco y entonces yo me alejo cada vez mas y mas hasta que llego a fuera de ventormenta y aun sigo en combate. Tuve que usar alt + f4 para poder salir del combate y cuando entro, estoy muerto.
Otro ejemplo es que cuando estoy en montura y paso por al lado de uno de esos "mobs horda" que estan frente a los "mobs alianza", el mob orda me ve y me quiere golpear pero cuando el mob orda se mueve el mob alianza le va a pegar y yo instantaneamente entro en combate. Luego de eso si yo lo ignoro y sigo de largo con mi montura me quedo en combate sin importar que tan lejos me vaya y no se me va el estado de combate hasta que uno de esos mobs mate al otro(lo cual suele demorar unos cuantos minutos).

**Comment by cibernaco** [comment]
Añadir, que a veces algunos npcs se quedan "enganchados" a ti y no les puedes matar por que siempre salta evadir, no abria mucho mas problema si al menos al usar alt+f4 no murieras, con su corrspondiente gasto de durabilidad, vete a buscar el cuerpo etc.... yo ademas pienso que como medida provisional se podria anular la muerte al desconectar en combate.

Un saludito.

**Comment by Jhovanni** [comment]
La muerte al desconectar y estar en combate fue medida aplicada porque mucha gente cerraba el juego al estar en bg sabiendo que moriría. De esa manera evitaban tener la muerte a su cuenta; al menos eso se dijo en el chat hace como dos o tres meses.

**Comment by Aegis-** [comment]
Lo que me molesta no es la muerte en combate, sino que al pasar por al lado de un mob que ni siquiera tocas o que otro empieza a matar, te quedes en combate hasta que su batalla termine. Eso me jodio muchas veces mientras subia level.

**Comment by stinfale** [comment]
yo recomendaría que quitaran la muerte al desconectar en combate, pero que implementaran la expulsión automática de la bg cuando se desconecta el pj por cualquier medio(con desertor incluido). Así no tendría gracia salir de juego antes de morir.

**Comment by Aegis-** [comment]
Esa seria una mala idea stinfale, porque los hordas que atacarian ventormenta usarian alt + f4 para escapar sin morir. O al menos eso es lo que hacian en otros servidores que hicieron que no mueras al usar alt + f4 sin morir.....
Por otro lado eso que decis que al desconectarte te expulse de bg puede ser bueno, porque veo mucho que hay gente en bgs que se desconectan pero siguen en el grupo de bg y ocupan 1 espacio como si fuera otro jugador.

**Comment by Necrofilo** [comment]
Lo de expulsar de la BG al que se desconecta yo no lo veo del todo justo, a veces tengo problemas con Internet y se me cae el juego durante unos segundos, despues de haber tenido que hacer cola durante 40 min ya que las BGs ahora están 18 hordas y 0 alis anotados, me tengo que comer un desertor por caerme unos segundos? 
 No digáis bobadas y pensad antes de postear.

**Comment by Aegis-** [comment]
Pero entonces que pasa cuando no hay Gms y por mas que pongas ticket no expulsan a los que estan off en una bg desde casi el principio de ella y te jode la bg entera?

**Comment by Necrofilo** [comment]
Pues nano, lo lógico sería reportar la función re reportar jugador ausente, ¿no?

**Comment by Aegis-** [comment]
Necrofilico ya nos fuimos un poco de tema, yo reporte lo del combate, no reporte a los afk en bg.

**Comment by Dekadencee** [comment]
Posible fix implementado tras la siguiente compilación, si el error permanece por favor abrir un nuevo issue.
