### ISSUE TITLE
Brujo [pet] Habilidades

### ISSUE THREAD

**Issue by Felarof23** [RoDNet/Bugtracker-Infinium-4.3.4#3417]
El bufo del manáfago "inteligencia Vil" (id:54424) no se esta aplicando. 
[edit] Esto ocurre en Tierras de Fuego y en ocasiones en BG

**Comment by Drogoth2** [comment]
Yo lo e visto también y te puedo decir que es porque parece que entra en conflicto con algún buffo de otra clase. Es decir, no se pone porque puede haber de antes un aura o algo parecido.
Cosa que en teoría no debería pasar.

**Comment by Monleon** [comment]
Hemos revisado todos los buffos y auras aplicadas para que no se puedan acumular dos diferentes pero de idéntico efecto.

De ahí que solo ocurra en ocasiones,  porque en el caso que comentas habrá un pj que ya te esté dando ese buff.
