### ISSUE TITLE
[Chaman Mejora] Poder Congelado (63374)

### ISSUE THREAD

**Issue by Dracoflare** [RoDNet/Bugtracker-Infinium-4.3.4#3418]
http://wow.freakz.ro/spells.php?spell=63374

Descripción: Increases the damage done by your Lightning Bolt, Chain Lightning, Lava Lash, and Shock spells by 10% on targets afflicted by your Frostbrand Attack effect, and your Frost Shock has a 100% chance to root the target in ice for 5 seconds. when used on targets at or further than 15 yards from you.

Problema: Usar el choque de escarcha a las distancias establecidas no enraiza al suelo con hielo al objetivo, El resto del talento funciona correctamente

**Comment by efectokoleos** [comment]
arreglado
