### ISSUE TITLE
[Habilidad-Picaro] Envenenar

### ISSUE THREAD

**Issue by Aegis-** [RoDNet/Bugtracker-Infinium-4.3.4#3419]
http://cata.openwow.com/spell=32645
Me di cuenta que esta habilidad desde hace poco tiempo se bugeo y ahora no hace daño, pero si gasta los 5 puntos de combo. Cuando digo no hace daño es que ni siquiera aparece en el registro de combate el daño, ni aparece el texto flotante, ni siquiera pierde 1 punto de vida el objetivo al usarla!

**Comment by Jhovanni** [comment]
Para asegurar totalmente, y que queda claro.
¿Las pruebas las has hecho con el muñeco de entremamiento o con otro juagador?
(Antes que me digas que estoy loco o que es absurdo que haga ese pregunta, porque puede suceder. Diré que la habilidad Matar del cazador solía no marcar daño alguno contra el muñeco de entrenamiento, mientras que a otros jugadores si marcaba daño y lo hace)

**Comment by Aegis-** [comment]
Contra ambos y no hace daño no baja ni 1 de hp. Aunque no se si ya lo arreglaron porque no entro hace un par de dias.

**Comment by efectokoleos** [comment]
k raro yo la estoy probando ahora contra muñecos de entrenamiento y si me va :S

**Comment by Aegis-** [comment]
Como ya dije ayer: " Aunque no se si ya lo arreglaron porque no entro hace un par de dias." Ya me fije hace 5 horas y ya estaba arreglado, se ve que ya esta solucionado.

**Comment by Dekadencee** [comment]
Perfecto cerramos pues
