### ISSUE TITLE
[Mision] En la guarida del raptor

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#342]
La mision ''En la guarida del raptor'': ( http://es.wowhead.com/quest=905/en-la-guarida-del-raptor ) dice que hay que conseguir unas plumas que dropean los raptor (cosa que los raptors no dropean) entonces no se pueden colocar las plumas en los nidos.

Raptors que deberian dar plumas:
- Colazote Solescama:    http://es.wowhead.com/npc=3254/colazote-solescama 
- Estridador Solescama:  http://es.wowhead.com/npc=3255/estridador-solescama
- Segador Solescama:     http://es.wowhead.com/npc=3256 
  -Raptor Solescama:        http://es.wowhead.com/npc=44167

La pluma que deberian dar:
-Pluma de Solescama:   http://es.wowhead.com/item=5165

**Comment by redneo** [comment]
arreglada
