### ISSUE TITLE
[Hechizo-Paladin] Inquisicion

### ISSUE THREAD

**Issue by Aegis-** [RoDNet/Bugtracker-Infinium-4.3.4#3420]
http://cata.openwow.com/spell=84963
El problema con esto es que cuando se termina el buff de inquisicion, desaparecen todas tus cargas de poder sagrado que tengas. Pero lo raro es que solo ocurre cuando tenes 1 o 2 cargas de poder sagrado y el buff que te da Inquisicion llega a 0, si tenes 3 cargas de poder sagrado no desaparecen.

**Comment by Kiritoo** [comment]
Arreglado, pendiente de compilar.
