### ISSUE TITLE
[Vendedores]Liwllehoff[Items/Objetos]Monturas

### ISSUE THREAD

**Issue by proezas** [RoDNet/Bugtracker-Infinium-4.3.4#3422]
Problema:Un día haciendo cadenas de misiones exaltando mis reputaciones como acostumbro a hacer desde el oficial y buscando mis items raros y monturas decidí exaltarme con la facción Los hijos de Hodir - http://es.wowhead.com/faction=1119/los-hijos-de-hodir

Después de un tiempo haciendo diarias y demás (llegado a exaltado) me encuentro con que el vendedor Liwllehoff - http://es.wowhead.com/npc=32540/lillehoff
tiene todo menos las monturas que corresponden a esa facción , Riendas del mamut de hielo - http://es.wowhead.com/item=43958
Riendas del gran mamut de hielo - http://es.wowhead.com/item=43961
Espero que sea suficiente para su arreglo.
Saludos.

**Comment by Monleon** [comment]
Añadido a la alianza
