### ISSUE TITLE
[Misión] Laderas de Trabalomas: ¡Delicias costeras!

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3429]
Misión: http://es.wowhead.com/quest=28146

Problema: Al coger la misión no aparece la araña que supuestamente te acompaña para que se coma los murlocs al matarlos.

Observación; en toda la zona hay mobs que no son agreables entre ellos los murlocs de esta misión, hasta que les ataques, y aún así al ratito pierden el agro. esto es un bug que facilita demasiado el leveo.

**Comment by redneo** [comment]
Ya saca la araña cuando coges la misión. Desconozco si el resto funcionará.
