### ISSUE TITLE
[ Crash del server > Gromelger ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#343]
Al loguear mi personaje Gromelger, el servidor crashea no se por qué motivo, impidiendo que pueda jugar con mi personaje, esperaba que se arreglara con el Rollback, pero no ha sido así, si me pudieran ayudar mirando si es algún aura o el qué lo provoca sería de gran ayuda.

Estaré con otro pj mientras D:

**Comment by Navalagamella** [comment]
¡Entonces a sido tu todo el rato! Te mereces... que te arreglen ya el pj xD

**Comment by Overseer101** [comment]
Votos a favor para crujirle¡¡¡ xDD

**Comment by DatJetto** [comment]
No he sido yo todo el rato, lo he crasheado una vez hoy al entrar para ver si no iba y ya.

**Comment by Hellythium** [comment]
ya no te quieren Gromelger, ni los jugadores, ni mucho menos el mismo server XD

**Comment by redneo** [comment]
Tenías personajes repetidos y ahora no?

**Comment by DatJetto** [comment]
Tenía mi cazador horda repetido, pero Gromelger no, y hace 2 días desconecté sin problema y ayer crasheaba de gratis...
