### ISSUE TITLE
[NPC's/mobs] Ladera de trabalomas: Suma ejecutora Darthalia

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3431]
NPC: http://es.wowhead.com/npc=2215

Problema: No está dando las misiones correspondientes.

**Comment by sarder97** [comment]
DELETE FROM `world`.`creature_queststarter` WHERE `id`='2215' AND `quest`='27746';
DELETE FROM `world`.`creature_queststarter` WHERE `id`='2215' AND `quest`='28089';
(elimina las misiones sobrantes)

**Comment by redneo** [comment]
Tras las ordenes del jefe de guerra ya tendria que dar Bienvenidos a la máquina
