### ISSUE TITLE
[Items/Objetos] Bolsa de tesoros de pesca

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3432]
Buenas.
• Nombre: Bolsa de tesoros de pesca
• Enlace: http://es.wowhead.com/item=34863
• Problema: La bolsa sólo viene con oro cuando debería tocar al menos 2 o 3 objetos mas al azar (http://es.wowhead.com/item=34863#contains)
Desde ya gracias y hasta luego.

**Comment by redneo** [comment]
Arreglado
