### ISSUE TITLE
Bug Mago

### ISSUE THREAD

**Issue by Arzaer16** [RoDNet/Bugtracker-Infinium-4.3.4#3433]
Cuando voy a aprender hechizos en el instructor de magos no me deja aprender hechizos.
![wowscrnshot_022814_142428](https://f.cloud.github.com/assets/6816065/2294103/d2a1d5c8-a07b-11e3-9c71-db38aedbb5bd.jpg)

**Comment by Necrofilo** [comment]
Si no me equivoco, a ese lvl ya tendrías que haber salido de ahí así que loa instructores vienen con lo justo para enseñar

**Comment by Aegis-** [comment]
Los instructores de Gilneas estan bug. Se puede salir de gilneas sin ayuda pero es es un quilombo porque esta bastante bugeado. Asi que te recomiendo pedirle a 1 gm que te saque poniendo 1 ticket ingame.

**Comment by redneo** [comment]
arreglado, la proxima vez, una id del npc vendria bien.
