### ISSUE TITLE
[Paladin Reprensión]  Glifo Veredicto del Templario

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3434]
ID: 45743
Segun la descripción debe aumentar el daño de veredicto del templario un 15%, el problema esque no está aumentandolo nada.

**Comment by Kiritoo** [comment]
¿Y ese Id? Nose de donde lo sacaste pero no corresponde jeje.
http://cata.openwow.com/spell=63220

**Comment by Wiinter** [comment]
Es la id del item http://es.wowhead.com/item=45743

**Comment by Drogoth2** [comment]
Esque ese glifo en si parece que lo quitaron del juego pero la id es esa

**Comment by Kiritoo** [comment]
Fix falta compilar.
