### ISSUE TITLE
[Talento-Cazador]Aura de disparo certero

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3435]
Nombre: Aura de disparo certero
Enlace: http://wow.freakz.ro/spells.php?spell=31519
Problema:Al entrar con otra aura que aumente las mismas habilidadades, se borra el aura del cazador y solo se puede volver a obtener al cambiar talentos o reloguear, cosas que no se pueden hacer en BG.  Si has perdido el aura y el pj que puso la otra ya no está cerca, pues termina el cazador sin aura alguna, haciendo menos DPS del que debería talvez por toda la BG.
Observaciones: Ya estaba reportado en:
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3370
y ha sido una solución al reporte de bug de:
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3346
sin embargo; la solución actual no es viable y como tal es un bug, porque las auras no se deben borrar (sobre todo para el cazador que una vez la pierde no tiene forma de volver a colocarla), sino evitar que se sumen pero manteniéndose; de esa manera cuando los personajes se alejan, cada uno mantiene su aura original.

**Comment by Jhovanni** [comment]
Linkeo los reportes del mismo bug por el cual fue tomada dicha forma de solución
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1232

En este otro esta bien explicado el bug y a partir de ahí fue hecha la medida de borrar auras
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1074

Pero sigue siendo bug, talvez para otras clases no les afecte porque pueden poner aura siempre que quiera, pero el cazador no, y nos afecta.
Gracias.

**Comment by F4NT4SM4** [comment]
las aura de critico la de picaro y druida veo que funcionan correctamente
tengo el aura de picaro cambio a forma feral ahaora tengo es mi aura de feral miesntra lo demas siguen con el aura de picaro

**Comment by Jhovanni** [comment]
Amm, el reporte de bug no tiene que ver con auras de critico. El tema es sobre el aura de disparo certero que se pierde (y esa habilidad luego no se puede volver a colocar porque es pasiva), lo cual es un bug.

**Comment by Pegasu5** [comment]
Me mosquea que el aura del hunter sv no se vaya, he notado un daño tremendo por parte de esta spec.

**Comment by redneo** [comment]
Arreglado
