### ISSUE TITLE
[Misiones][Montañas Filospada] Reinar en los cielos

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3437]
Buenas.
• Nombre: Reinar en los cielos
• Enlace: http://es.wowhead.com/quest=11078
• Descripción: Consigue dientes de dragón. 
• Problema: No está ninguno de los 4 dragones para obtener el objeto "Dientes de dragón" (http://es.wowhead.com/item=32732). Los dragones son Obsidia (http://es.wowhead.com/npc=23282) Desgarro Oscuro (http://es.wowhead.com/npc=23061) Insidion (http://es.wowhead.com/npc=23281) y Alafuria (http://es.wowhead.com/npc=23261)
• Observaciones: Ya intenté invocarlos desde sus huevos, pero no funciona tampoco (tengo los fragmentos de ápices que pide para invocarlos).
Desde ya gracias y hasta luego!

**Comment by redneo** [comment]
Arreglado. (cuando reinicie el server)
