### ISSUE TITLE
[Misiones][Montañas Filospada] Un asunto grimoso

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3438]
Buenas.
• Nombre: Un asunto grimoso
• Enlace: http://es.wowhead.com/quest=10998
• Descripción: Consigue el grimorio de Vim'gol el Vil. 
• Problema: No se puede invocar a Vim'gol el Vil (http://es.wowhead.com/npc=22911) para obtener su libro y completar la misión.
• Observaciones: Para invocarlo, hay que quedarse inmovil en uno de los círculos de fuego de la zona, pero no sucede nada.
Desde ya gracias y hasta luego.

**Comment by redneo** [comment]
La mision en si necesita de 5 tipos...

Para agilizar la cosa, he puesto al npc que hay que matar y asi menos lios.
