### ISSUE TITLE
[Misiones][Torneo Argenta] La maldición del Caballero Negro

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3439]
Buenas.
• Nombre: La maldición del Caballero Negro
• Enlace: http://es.wowhead.com/quest=14016
• Descripción: La cruzada Rhydalla en los Campos del Torneo Argenta quiere que investigues la lápida del Caballero Negro. 
• Problema: Al llegar a la lápida, aparecen los PNJ "Asesino de culto"(http://es.wowhead.com/npc=35127) y "Saboteador del Culto" (http://es.wowhead.com/npc=35116) para activar un evento en el que hablan y luego hay que matarlos para completar la misión, pero lo único que pasa es que se multiplican hasta el infinito cuando haces un movimiento cerca de ellos sin activar nada.
Desde ya muchas gracias.

**Comment by redneo** [comment]
arreglado cuando caiga el server
