### ISSUE TITLE
[Mago] Anillo de escarcha: 82691

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#344]
Al lanzar el anillo, este se mueve como se le antoja por el mapa y, por si fuera poco, encima no congela...

**Comment by DatJetto** [comment]
De hecho persigue a un jugador, generalmente tu target, en vez de permanecer quieto.

**Comment by Dazand** [comment]
Horrible, de hecho no sé que pasó hace unso dias funcionaba perfectamente D:

**Comment by crowel** [comment]
Lo mismo paso con el angel del paladin :D ahora ni aparece jejeje

**Comment by efectokoleos** [comment]
fixed
