### ISSUE TITLE
[Bug Visual] Mapa

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3440]
Nombre: Mapa bug visual
Descripcion: Al Abrir el mapa el pj sostiene un mapa 
Problema: el pj hace como si estuviera sosteniendo algo pero no esta el mapa
dejo unas imagenes para que vean a que me refiero
![wowscrnshot_030114_162716](https://f.cloud.github.com/assets/3101842/2302555/032026d8-a184-11e3-8dc8-3427c4bc4492.jpg)

no es un bug grave ni nada pero cuando los nuevo entran al server lo primero que ven es mapa y al ver que esta bug visual el mapa da de que hablar

**Comment by Pegasu5** [comment]
De hecho ahora que los mencionas hay varios bugs visuales pequeños, pero indispensables para el pve que darían que hablar, como el de loteo en raids, que siempre sales que tiras necesidad a algo por eso se opta por poner master para evitar mal entendidos y riñas.

**Comment by Dekadencee** [comment]
Fixeado
