### ISSUE TITLE
[Chaman] Totem Garra de Piedra Glifo buff

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3442]
Nombre: Totem Garra de Piedra Glifo buff
ID Buff :55277
ID Totem: 5730
Enlace:http://wow.freakz.ro/spells.php?spell=55277
Descripcion: Tu Totem garra de piedra tambien da un escudo de amortiguacion de daño igual a 4 veces la fuerza del escudo que da a tus totems
Problema: el buff deberia de desaparecer si no esta activo el totem
es decir puedo abusar poner totem de piedra tener buff y cambiar rapido a otro totem teniendo ambos buff que no deberia

**Comment by efectokoleos** [comment]
he estado leyendo en foros de wowhead y demas y parece que siempre ha sido asi
