### ISSUE TITLE
[Chaman] Latigazo de Lava Mejorado

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3449]
Nombre: Latigazo de Lava Mejorado
ID:77700/77701
Enlace:http://wow.freakz.ro/spells.php?spell=77701
Descripcion: Aumenta un 20% el daño de tu facultad latigazo de lava por cada una de tus aplicacciones de llamas abrasadoras sobre el objetivo, lo que consumira dichas aplicaciones en el proceso y provocara que tu lagizao de lava propague tu choque de llamas desde el objetivo hasta un max de 4 enemigos en un radio de 12m.

Problema: esta consumiendo las acumulaciones de llamas abrasadoras(77661) de otros jugadores solo deberia de consumir las propias
2do problema: no esta propagando el choque de llamas

**Comment by redneo** [comment]
Arreglado, necesita testeo en el test.

**Comment by F4NT4SM4** [comment]
si ya prograpaga el choque de llamas
pero no esta consumiendo las acumulaciones de llamas abrasadoras propias para aumentar el daño un 20%

**Comment by redneo** [comment]
en que reino???

**Comment by F4NT4SM4** [comment]
test

**Comment by redneo** [comment]
Lo he puesto como antes, que quite todos, ya que no se (por el momento) controlar las auras que pone el totem respecto a su dueño.
