### ISSUE TITLE
Bug Buzón al recojer pertenencias(Bolsas y demás)

### ISSUE THREAD

**Issue by Kagome** [RoDNet/Bugtracker-Infinium-4.3.4#345]
cuando intento recoger Mis bolsas quitadas,pues me sale que no puedo por que "No puedo llevar más de eso". Me gustaría que lo arreglaran rápido por que,son 28 días lo que tengo para cogerlos.
Imagenes: 
![wowscrnshot_071113_024926](https://f.cloud.github.com/assets/4942077/781717/b3c27ab6-ea2a-11e2-9b9e-2fcff0526c69.jpg)
![wowscrnshot_071113_143111](https://f.cloud.github.com/assets/4942077/781718/b3c1c9ea-ea2a-11e2-933e-651505f7c29d.jpg)

**Comment by Kagome** [comment]
Hay tengo de un día anterior,a cuendo intente con mis Set, y luego las bolsas y el de hoy.

**Comment by ghost** [comment]
Te respondo rápido yo mismo. Se te olvidó ponerte las gafas xD 
Lee lo que pone en la descripción de la bolsa:

Cartera de señor del foso - Se liga al recogerlo - ¡¡UNICO!! - Bolsa de 20 casillas

Así que a comprarte bolsas jajaja, ya que sólo puedes llevar 1 de ese tipo

**Comment by ghost** [comment]
PD: Cierra la issue porque no es ningún bug.

Un saludo.

**Comment by ghost** [comment]
Lo que pasa es que esas bolsas las daban con la migración.... "ese" es el problema xd, a mi por mi parte no me importa, las tiro y me hago otras :P

**Comment by Kagome** [comment]
Etto...Gracias...Como borro esta cosa xD Si alguien me lo dice xD
