### ISSUE TITLE
[Objeto] Gran festin #34753

### ISSUE THREAD

**Issue by RaulioWoW** [RoDNet/Bugtracker-Infinium-4.3.4#3452]
Uso: ¡Saca un gran festín que alimentará a tu grupo! Restaura 22500 p. de salud y (3200 / 5 \* 30) p. de maná durante 30 s. Si comes durante al menos 10 s estarás bien alimentado y ganarás 60 p. de poder de ataque, 35 p. de poder con hechizos y 30 p. de aguante durante 1 h.

Problema: Tras comer menos de 10 segundos, no te alimenta bien y no ganas los 60p de poder de ataque, 35p de poder de hechizos y 30 p de aguante durante 1h.

**Comment by F4NT4SM4** [comment]
no te alimenta bien me hizo gracia jajajaja
