### ISSUE TITLE
[Misión] Sacrificios- Misión de los Huargens 

### ISSUE THREAD

**Issue by brando2014** [RoDNet/Bugtracker-Infinium-4.3.4#3454]
El problema es, que los adds matan al caballo antes de llegar a la catedral, y marca a la misión como fallida, y no se puede volver a donde estaba el npc que da la misión, porque están las barricadas que solo se podían pasar con el caballo

**Comment by Monleon** [comment]
Las misiones de los huargens ya funcionan perfectamente de inicio a fin
