### ISSUE TITLE
[Talento druida feral] Heridas infectadas

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3456]
ID: http://cata.openwow.com/spell=48484

Problema: Muy habitualmente se bugea y deja de poner el debuff correspondiente, con lo cual ni ralentiza ni reduce la velocidad de ataque del objetivo.

**Comment by Monleon** [comment]
Repetido, busca por favor antes de reportar. 

Seguimos desde https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3059

**Comment by efectokoleos** [comment]
arreglado
