### ISSUE TITLE
[Misiones][Marjal Revolcafango] Los desertores

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3459]
Buenas.
• Nombre: Los desertores
• Enlace: http://es.wowhead.com/quest=27287
• Descripción: Consigue información sobre Reethe hablando con Balos Jacken y los desertores del Marjal Revolcafango. 
• Problema: El PNJ Balos Jacken (http://es.wowhead.com/npc=5089) no completa la misión al derrotarlo (sin matarlo).
• Observaciones: Según lei en la sección de comentarios de Wowhead, le quitas determinada cantidad de vida y se vuelve amistoso para entregar la misión y empezar con http://es.wowhead.com/quest=27288 para terminar la cadena.
Muchas gracias.

**Comment by redneo** [comment]
Arreglado.
CUando tiene un 50% de vida o menos deja de pegar y se vuelve neutral.
