### ISSUE TITLE
[Misiones][Marjal Revolcafango] El arma Tótem Siniestro

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3460]
Buenas.
• Nombre: El arma Tótem Siniestro
• Enlace: http://es.wowhead.com/quest=27336
• Descripción: Usa el tótem capturado para colocarlo en el suelo y después mata a 10 crocoliscos secorrones jaspeados o faucedagas secorrones cerca del tótem para probar sus efectos.
• Problema: El tótem provisto (http://es.wowhead.com/item=33101) no hace ningún efecto en los tipo de crocolisco mencionados (http://es.wowhead.com/npc=4344) (http://es.wowhead.com/npc=4345), por lo tanto no se puede completar la misión.
• Observaciones: Ya había sido reportado aquí https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/557
Gracias!

**Comment by redneo** [comment]
![wowscrnshot_030914_114158](https://f.cloud.github.com/assets/1163425/2367727/c7ef0634-a777-11e3-8257-d232a7a836c1.jpg)
![wowscrnshot_030914_114201](https://f.cloud.github.com/assets/1163425/2367725/9030ba26-a777-11e3-9fb5-2a931f5213bf.jpg)

si que funciona!

**Comment by ghost** [comment]
Si, mala mia. Perdón por las molestias y gracias.
Hasta luego!
