### ISSUE TITLE
[Misiones][Tundra Boreal] Protocolo de emergencia: sección 8.2, párrafo D

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3462]
Buenas.
• Nombre: Protocolo de emergencia: sección 8.2, párrafo D
• Enlace: http://es.wowhead.com/quest=11796
• Descripción: Iggy "Barrena" Conmutador quiere que hundas unos restos al este, unos restos al sur y unos restos al noroeste. 
• Problema: La antorcha de emergencia (http://es.wowhead.com/item=35224) no funciona con los restos de los aviones.
Desde ya gracias.

**Comment by redneo** [comment]
Arreglado cuando caiga el server. Hacer notar que hay 4 restos de los cuales 3 funcionan.
