### ISSUE TITLE
[NPC] Tsul'Kalu

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3463]
Nombre: Tsul'Kalu
Enlace: http://es.wowhead.com/npc=51661
Problema:He buscado este NPC (bestia) por días y no se encuentra, agradecería si podrían darle un vistaza sobre su localicación, reswpan (debe ser cada dos hrs) o verificar si está en el servidor. Fue agregado al juego en el parche 4.0.6

**Comment by Kiritoo** [comment]
Arreglado.
