### ISSUE TITLE
[Guerrero] Cargar Aturdidora

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3464]
Nombre: Cargar Aturdidora
ID:7922
Enlace:http://wow.freakz.ro/spells.php?spell=7922
Descripcion: Cargar e Interceptar ya no tienen rendimiento decreciente en sus efectos de aturdimiento. (notas del parche 4.1)
Problema: Cargar su efecto aturdidor es Cargar aturdidora actualmente tiene rendimiento decreciente y no deberia

**Comment by Monleon** [comment]
Seguimos desde https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3267

**Comment by F4NT4SM4** [comment]
see ya lo habia visto pero pense que como no seguia el formato para reportar bugs esta muy largo no se iva a tomar en cuenta ya que searum siempre me dice resume tus issues que no entiendo nada e.e
