### ISSUE TITLE
[Guerrero] Interceptar

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3465]
Nombre: Interceptar
ID:20253
Enlace:http://wow.freakz.ro/spells.php?spell=20253
Descripcion: Cargar e Interceptar ya no tienen rendimiento decreciente en sus efectos de aturdimiento. (notas del parche 4.1)
Problema: Interceptar actualmente tiene rendimiento decreciente y no deberia

**Comment by Monleon** [comment]
Seguimos desde https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3267
