### ISSUE TITLE
[Brujo] Ascuas ardientes

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3469]
Pone que esto está arreglado en el changelog pero sigue sin funcionar.

Dejo el post en el cual se explicaba https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3319

Un saludo y gracias

**Comment by Kiritoo** [comment]
fixx commented 2 days ago

Fix, falta compilar.
