### ISSUE TITLE
[Misiones][Frondavil] ¡Baila para Ruumbo!

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3470]
Buenas.
• Nombre: ¡Baila para Ruumbo!
• Enlace: http://es.wowhead.com/quest=27995
• Descripción: Ejecuta un baile estúpido para Ruumbo. 
• Problema: El personaje debería bailar automaticamente luego de aceptar la misión pero no sucede nada.
• Observaciones: Intenté con el comando /bailar pero tampoco se completa.
Desde ya gracias y hasta luego.

**Comment by bulkatoz** [comment]
sigue estando bug la mision hay un montos de items que se pierden por esas misiones bug
