### ISSUE TITLE
[Misiones][Frondavil] Fuegos fatuos del bosque

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3474]
Buenas.
• Nombre: Fuegos fatuos del bosque
• Enlace: http://es.wowhead.com/quest=28383
• Descripción: Usa el bordón Vientopresto para coger 5 fuegos fatuos de Ramaespolón. 
• Problema: Cuando uso el Bordón Vientopresto (http://es.wowhead.com/item=64300) provisto en los Fuegos Fatuos de Ramaespolón (http://es.wowhead.com/npc=48454), no te siguen para poder llevarlos al Claro y completar la misión.
Desde ya gracias.

**Comment by bulkatoz** [comment]
SIGUE BUG LA MISION
