### ISSUE TITLE
[BUG] Personaje inmovilizado

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#3478]
Hay ciertas habilidades que, cuando te stunean, te dejan clavado al suelo y no te deja ni moverte ni lanzar hechizos al aparecer tu personaje como "aturdido".

De momento he visto que pase con el impacto de los magos fuego y el tótem garra de piedra, pero creo que hay más habilidades que provocan que el personaje se bugee tal que así:

![wowscrnshot_031314_221537](https://f.cloud.github.com/assets/6329431/2415468/fafe26b4-aaf5-11e3-91cd-bda88e821e83.jpg)

**Comment by Necrofilo** [comment]
A mi me ha pasado cuando algún hunter usa disparo de dispersión o la red de la pet.

**Comment by Pegasu5** [comment]
Tótem garra de piedra ya lo reporté, pasa con anillo de escarcha del mago, y hasta ahora, solo con esas me ha sucedido y de hecho ocurre frecuentemente.

**Comment by F4NT4SM4** [comment]
cambiaremos de emulador con el cambio de temporada y habran varios fix nuevos posiblemente esto ya no seguira bug

**Comment by Monleon** [comment]
Esto ya está arreglado.
