### ISSUE TITLE
[Alquimia] Convertir: elementos vivos

### ISSUE THREAD

**Issue by Dracoflare** [RoDNet/Bugtracker-Infinium-4.3.4#3479]
Me ha encantado (ironia) que este transmutacion me ha dado un item que ni siquiera sabia que existia llamado elemento volatil aleatorio, con el cual no puedo hacer absolutamente nada ni abrirlo ni nada

**Comment by Kiritoo** [comment]
Si no me equivoco te da ese elemento más, no recuerdo si son 15 o 30 volatiles aleatorios, no solo te debe dar eso.
Igualmente decirte que si  reportas algo debes añadir las ids.
Saludos.
