### ISSUE TITLE
[Kezan] Quests buggeadas, imposible salir de la zona

### ISSUE THREAD

**Issue by Skygry** [RoDNet/Bugtracker-Infinium-4.3.4#3481]
Hola, las quests Gorrones de fiesta piratas y Golpe primigenio de chamán están buggeadas.

Por otra parte no hay forma de salir de la zona, pese a lograr subir al barco con el salto en cohete (el cañón que te lanza no es usable), no hay nadie para comprar viaje.

Gracias.

**Comment by Monleon** [comment]
Hasta que volvamos a tener de nuevo la zona arreglada, pon un ticket ingame mientras tanto para que te saquemos de allí.

**Comment by Kiritoo** [comment]
Arregladas.
