### ISSUE TITLE
[Cazador] Recuperación Rapida (abusado en pvp)

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3483]
Nombre: Recuperación Rapida
ID:53228/53232
Enlace:http://wow.freakz.ro/spells.php?spell=53232
Descripcion: Ganas 6p/12p de enfoque cada 3s mienstras estas bajo el efecto de fuego rapido y ganas 25p/50p de enfoque al instante cuando ganas matanza rapida (35099)
Problema: los 25p/50p de enfoque no lo esta dando matanza rapida (35099)
en cambio lo esta dando otra spell que no deberia el lanzador de trampa (77769)

con una macro facilmente se puede tener enfoque infinito y abusar de ello

**Comment by cibernaco** [comment]
Es verdad jaja, pero no pasa siempre y solo pasa en punteria, que curioso oye.

**Comment by F4NT4SM4** [comment]
Es que en punteria es que esta el talento....

**Comment by cibernaco** [comment]
Anda leche me falto explicación, no hace falta el talento para que salten los 50 de energía, simplemente saltan de vez en cuando, hace ya tiempo en la rama de supervivencia también daba 25 de energía cuando lo activabas (el lanzador), pero se supone que hace mucho que no pasaba nada de eso.

**Comment by Jhovanni** [comment]
Comprobado, es el talento que da el beneficio al usar el lanzador de trampas. No sucede así en bestias. En cuanto a la rama de supervivencia, puede ser que el bug esté más en el script de Lanzador de trampas, que está tomando habilidades de otros hechizos: en puntería de Fuego rápido, y en Supervivencia de Emoción de la caza o algo así (solo suposiciones)
El punto es que está comprobado.
