### ISSUE TITLE
[Mazmorras/Bandas][El Bastión del Crepúsculo] Valiona y Theralion (10n)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3486]
Buenas.
• Enlace: Valiona (http://es.wowhead.com/npc=45992) Theralion (http://es.wowhead.com/npc=45993)
• Problema: El problema está en que el hechizo acumulable que lanzan ("Cambio crepuscular" http://es.wowhead.com/spell=93051 si mal no recuerdo) solamente deberian lanzarlo en dificultad heróica.
• Observaciones: En lo que me baso para reportar esto es en la guía de mazmorras, en la que la habilidad solamente aparece cuando cambias la dificultad de 10 normal a 10 heróico. También en el wowhead de los dos bosses, al seleccionar habilidades (por ejemplo Valiona http://es.wowhead.com/npc=45992#abilities) y seleccionas 10 normal, aparece un buff que se llama igual (http://es.wowhead.com/spell=86360)  pero tiene distinto efecto al que tiene en 10 heróico (que es el debuff en cuestión).
Desde ya gracias por la atención y hasta luego!

**Comment by Dekadencee** [comment]
Fixed
