### ISSUE TITLE
[Paladin Reprensión] Tormenta divina

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3487]
id:53385

Bien, el problema del que se está abusando es que si el ataque pega a un objetivo solo también está otorgando cargas de poder sagrado, cuando solo debería otorgarlas en el caso de que pegue a cuatro objetivos a la vez.

**Comment by cibernaco** [comment]
¿Llevas algun glifo que afecte a las cargas de poder o a tormenta divina? Pregunti por que a mi (que aun no llevo glifos) si no pego a 4 no me da poder runico. Solo he probado con npcs mirare a ver si con players si lo hace

**Comment by Pegasu5** [comment]
Poder rúnico paladín :O hacker wtf detected xDD its joke.

**Comment by cibernaco** [comment]
Jajaja, ostras valla fallo, si si va a ser que poder rúnico imposible jajaja.

**Comment by cibernaco** [comment]
Pues si que va mal jaja, tanto con players como con npcs, antes no pasaba.

**Comment by Monleon** [comment]
Ya solo dará carga de poder sagrado cuando corresponda.
