### ISSUE TITLE
[Ingenieria] Recetas del instructor.

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#3490]
El problema es que el instructor no esta enseñando estas recetas que debería:
- http://es.wowhead.com/spell=61483#taught-by-npc
- http://es.wowhead.com/spell=56480
- http://es.wowhead.com/spell=56483
- http://es.wowhead.com/spell=62271

**Comment by Pegasu5** [comment]
Creo que esas recetas dependen de tu clase ya que son utilizables nada más para ingenieros xDDD por ejm yo soy hunter tengo la de malla agilidad.

**Comment by cibernaco** [comment]
Si, a cada clase le aparece solo la que le corresponde y debe de ser asi

**Comment by kingtonix** [comment]
A mi con el dk no me salen esas y con mi picara no me salen las de cuero :i

**Comment by cibernaco** [comment]
Con el dk te saldran solo las de placas, y con el picaro solo las de malla, si no es asi pues si que esta mal.

**Comment by Compresor** [comment]
Entonces al final que sucede?

**Comment by Pegasu5** [comment]
Pues vuelvete a subirla, hace días un amigo y yo terminamos de subirla con los hordas yo tengo malla pa mi hunter, y el cuero pa su rogue.
