### ISSUE TITLE
[Tol Barad] Barras de captura no aparecen

### ISSUE THREAD

**Issue by cibernaco** [RoDNet/Bugtracker-Infinium-4.3.4#3491]
En el campo de batalla de Tol Barad, las barras de captura no aparecen cuando estas en ellas, al menos no desde el lado de la horda, desde la ali no he podido comprobarlo, pero imagino que será igual.

Un saludo.

**Comment by Kiritoo** [comment]
Hola, ¿Tenias activado el JcJ?.

**Comment by Pegasu5** [comment]
Son bug visuales que se arreglan relogeando, borrando caché, comando /reload etc.. soluciones temporales.

**Comment by cibernaco** [comment]
Pues ni con esas, ni relogeando, ni /reload, ni borrando cache, ni poniendo una copia de cuando si aparecía, ni nada de nada, no salen, y no se si estaba activado el JcJ, de normal no lo llevo activado, pero se supone que al entrar se debería de activar solo, me fijare en la siguiente.

Un saludo.

**Comment by cibernaco** [comment]
Pues de normal no se activa el JcJ que debería, pero aún así no aparece la barra ni aunque lo actives, ya sea antes o durante la batalla, y una vez cambias de estado desactivado a activado o viceversa, ya puedes hacer 1000 veces /reload o cualquier otra cosa, que la barra sigue sin aparecer.

**Comment by Compresor** [comment]
Si que se ven, prueba a borrar caché, relogueando como te han dicho anteriormente.
