### ISSUE TITLE
[Chamán Mejora] Bug en talento ira desatada

### ISSUE THREAD

**Issue by luisarjona4** [RoDNet/Bugtracker-Infinium-4.3.4#3492]
ID: 30809
Buenas, resulta que cuando te lanzan poderio el buff de ira desatada se va, como deberia. Pero al irse el buff de ira desatada, tambien se pierden los 8 puntos de pericia del talento de ira desatada, cosa que no deberia pasar ya que, para volver a tener esta pericia, se debe cambiar a la dual y luego volver a poner los talentos de mejora, cosa molesta sin ninguna duda, y en bgs o arenas, donde no se puede cambiar a la dual, ya irremediable. Tambien añado que cuando te han echado poderio y te lo quitas o lo pierdes siendo disipado o muriendo, el buff de ira desatada del chaman mejora no vuelve por lo que es bastante perjudicial este bug, ya que se pierde mucho ap(a parte de la pericia). Yo creo que esto se resolveria poniendo que en el chaman mejora el buff de ira desatada pese mas que poderio y no al reves. Gracias por adelantado y ojala lo arregleis lo antes posible!

**Comment by efectokoleos** [comment]
arreglado
