### ISSUE TITLE
Misiones: Inmolar

### ISSUE THREAD

**Issue by davidnbr** [RoDNet/Bugtracker-Infinium-4.3.4#3493]
La mision Inmolar al jugar por primera vez con el Elfo de Sangre Brujo, no se puede completar porque al utilizar la habilidad que se dicta en la mision nada cambia, es como que no se hubiera hecho nada, no se sube la cantidad de veces que ya he utilizado la habilidad. Por eso no se puede completar.

**Comment by Kiritoo** [comment]
Arreglada
