### ISSUE TITLE
[Items/Objetos] Vale de cámara de hermandad (8ª ranura) (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3494]
Buenas.
• Nombre: Vale de cámara de hermandad (8ª ranura)
• Enlace: http://es.wowhead.com/item=68136
• Problema: El vendedor de hermandad Shay Pressler (http://es.wowhead.com/npc=46602) no vende el objeto, aún teniendo el logro requisito para poder comprarlo (http://es.wowhead.com/achievement=5152)
• Observaciones: Ya busque en el vendedor de Darnassus, que es el que tiene mas cosas, pero nada.
Desde ya muchas gracias!

**Comment by Pegasu5** [comment]
En el de Orgrimmar es posible así que sí es la alianza que tiene esta gran desventaja

**Comment by Kiritoo** [comment]
Añadido en ventormenta, actualmente solo disponen del Vale de la 8ª ranura en ventormenta y orgrimmar.
