### ISSUE TITLE
[Pícaro] Bomba de humo // 76577

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3495]
ID: http://cata.openwow.com/spell=76577

Problema 1: no está respetando la facción del pícaro que usa la habilidad, ya que hace que los compañeros tampoco puedan atacar.

Problema 2: está afectando a un rango exageradamente aumentado, con lo que si estás a 20 metros de la bomba de humo tampoco puedes usar facultades como carga o lanzar hechizos.

**Comment by Necrofilo** [comment]
Me tiene bastante harto esta spell, no puedes hacer NADA, ya puedes estar dentro o fuera de la bomba de humo que no puedes curar a tu compañero.

**Comment by Dejaor** [comment]
Creo que lo que deberia hacer ea no dejar selecionar objetivos dentro de la bomba de humo y con unos Aoe que se tire se dsipa creo #:

**Comment by Necrofilo** [comment]
Pues va a ser que no, se puede seleccionar igual.

**Comment by efectokoleos** [comment]
arreglado
