### ISSUE TITLE
[Paladín] Talento: Escudo sacro // 85285

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3499]
ID: http://cata.openwow.com/spell=85285

Problema: debería absorber 28585p. de daño en total, pero no sé hasta qué punto estará aumentado que practicamente el paladín es imposible de bajar hasta que se le acaba el efecto.

Resumen: abosrbe una burrada de más.

**Comment by efectokoleos** [comment]
arreglado
