### ISSUE TITLE
Instructor de cazadores no instruye ni vende

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#350]
El npc (Jensen Farran) ID: 4892 no instrulle ni vende lo que deveria

![wowscrnshot_071113_155252](https://f.cloud.github.com/assets/4893907/781949/9a192acc-ea31-11e2-8744-672d23e9d108.jpg)

**Comment by crowel** [comment]
Fix, ahora se puede comprar, reparar o aprender.
