### ISSUE TITLE
[Brujo] Aura de apresión // 89605

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3501]
ID: http://cata.openwow.com/spell=89605

Problema: si te afecta el tercer enraizamiento/stun de ''Mano de Gul'dan'', te deja bugeado quitándote la capacidad de moverte o poder usar cualquier facultad. La única solución es alt f4.

**Comment by Monleon** [comment]
Ya está arreglado
