### ISSUE TITLE
[Mago] Anillo de escarcha // 82676

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3502]
ID: http://cata.openwow.com/spell=82676

Problema: si te afectan los congelamientos hasta el último (cuando ya desaparece el anillo) hay veces que te deja bugeado en stun permanente, con lo cual no puedes ni moverte ni usar hechizos.

Añadido: también tiene rango aumentado, congela estando fuera del anillo (mirad a Androsi).
![wowscrnshot_032314_033939](https://f.cloud.github.com/assets/6006693/2493031/3abf2f0c-b274-11e3-8ffd-fa80399c4d0c.jpg)

**Comment by Pegasu5** [comment]
Tambien sucede que sin entrar en al área del anillo estar digamos a 2 metros te deja congelado.

**Comment by Necrofilo** [comment]
Mucha gente se queja por eso, pero se congelan por haber pasado pisando el borde, o por haber salido justo en el momento en el que ya congela.

**Comment by crowel** [comment]
Pegasus tiene razon a mi me congelo a mas de 3 metros, cuando uno que iba delante mia lo pisó.

**Comment by Necrofilo** [comment]
Añado al post, ya que lo he visto en  BG esta madrugada.

**Comment by Dekadencee** [comment]
Fixeado el stun permanente
