### ISSUE TITLE
[Mazmorras/Bandas][Ciudadela de la Corona de Hielo] Fuerza de Wrynn 2

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3504]
Buenas.
• Nombre: Fuerza de Wrynn
• Enlace: http://es.wowhead.com/spell=73828
• Descripción: El Rey de Ventormenta te presta su fuerza y aumenta la salud total, la sanación realizada, la absorción de daño y el daño infligido un 30%.
• Problema: El Buff no afecta Worgens.
• Observaciones: Ya lo había reportado aquí https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2265 pero parece que se volvió a bugear.
• Screenshots: Acá muestro que el draenei Dkman la tiene, y Ayf que también es worgen, no:
![wowscrnshot_032214_195810](https://f.cloud.github.com/assets/4582987/2492205/fa455cb8-b218-11e3-87e7-7b4594de1bc2.jpg)
![wowscrnshot_032214_202419](https://f.cloud.github.com/assets/4582987/2492209/2a9c5e70-b219-11e3-9218-4038478d7857.jpg)
Desde ya muchas gracias.

**Comment by luisarjona4** [comment]
No afecta ni a huargens ni a goblins.

**Comment by luisarjona4** [comment]
En dragona no puedes meterte en los portales.
