### ISSUE TITLE
[chaman] [glifo de totem corriente de sanacion]

### ISSUE THREAD

**Issue by gerardo14** [RoDNet/Bugtracker-Infinium-4.3.4#3506]
http://es.wowhead.com/item=41533/glifo-de-totem-corriente-de-sanacion
el glifo hace que el totem aparte de sanar cada 2 segundos aumente las resistencis a naturaleza fuego y escarcha 195p. y al tener el glifo puesto esto no ocurre

**Comment by efectokoleos** [comment]
arreglado
