### ISSUE TITLE
[Mago] Bonus (2) T12 (stop cast)

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3507]
Problema: si el reflejo del mago sale mientras el mago está casteando, corta el casteo haciendo que pierda bastante tiempo contando que cada casteo son 2 segundos y la copia puede salir estando el casteo casi acabado.

**Comment by efectokoleos** [comment]
necesito ids

**Comment by efectokoleos** [comment]
arreglado
