### ISSUE TITLE
[Mago] Talento: Congelación cerebral // 44549

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3509]
ID: http://cata.openwow.com/spell=44549

Descripción breve: en vez de activar misiles arcanos, se activará ''Congelación cerebral'', con lo cual tendrás una bola de fuego o descarga de pirofrío instant.

Problema: a veces activa misiles arcanos en lugar de Congelación cerebral, y otras activa ambas a la vez.

 Añadido: cuando activa los misiles arcanos, no tiene tiempo límite, puede pasar 1 minuto y lanzarlos.

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
