### ISSUE TITLE
Pnj no da misiones 

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#351]
El pnj (Calia castilla) ID: 23566 no da las misiones 

![wowscrnshot_071113_154127](https://f.cloud.github.com/assets/4893907/781955/ea05b2c6-ea31-11e2-8f4c-ac90d91bf316.jpg)

**Comment by crowel** [comment]
Comprobado.
Este npc empieza 4 misiones, una se puede cojer sin ningun requisito y tras entregarla se puede hacer otra más, van dos.
Las otras dos son parte de una cadena de misiones, y son consecutivas, tras hacer una después haces la otra, en resumen que si no hiciste las anteriores de la cadena no podrás hacer estas.
Cierro reporte, el npc esta correcto.
Un saludo.
