### ISSUE TITLE
[Hunter] Talento: hojas reflectantes (survival) // 83495

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3510]
ID: http://cata.openwow.com/spell=83495

Problema: no está reflectando los hechizos al usar deterrence.

**Comment by Jhovanni** [comment]
Hace tiempo ví tambien ese problemas, pero aún tengo dudas porque durante etapas ví que no reflejaba nada, semanas más tarde estaba reflejando, y tiempo despues de nuevo no. Por la tanto ya no sé cómo quedó el asunto.
El hechizo que si he visto que refleja es polimorfia del mago y uno que otro de la misma clase.

**Comment by efectokoleos** [comment]
arreglado, falta compilar
