### ISSUE TITLE
[Paladín] Guardián de los antiguos reyes (retry) // 86150

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3512]
ID: http://cata.openwow.com/spell=86150

Problema: los ataques básicos del guardián, solo están haciendo 1p. de daño.

**Comment by Kiritoo** [comment]
Esto funciona correctamente, también acumula las cargas me aumentan la fuerza y tras desaparecer el paladín infringe el daño en área dependiendo de las cargas poseidas.
