### ISSUE TITLE
[Paladín] Talento: Ojo por ojo // 25988

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3514]
ID: http://cata.openwow.com/spell=25988

 Problema:  quien debe recibir el 30% del daño del hechizo es el que lanza el hechizo al paladín y lo está recibiendo, pero ojo por ojo no debe afectar al paladín; sin embargo este está recibiendo un 60% mas del daño del hechizo, con lo que de 2769 que infligiría un hechizo, recibe 4587.

**Comment by Monleon** [comment]
Eso no sucede
