### ISSUE TITLE
[Paladín] Talento: Sanción desinteresada // 85804

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3515]
ID: http://cata.openwow.com/spell=85804

Problema: al sanar a un compañero, no está aumentando el 4% de daño infligido por cada carga de Poder Sagrado (1 carga 4%, 2 cargas 8% y 3 cargas 12%; en rango 1 = 1 carga 2%, 2 cargas 4% y 3 cargas 6%).

**Comment by Kiritoo** [comment]
Esto está arreglado, falta compilar.
