### ISSUE TITLE
[Paladín] Talento: Defensor candente // 31850

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3516]
ID: http://cata.openwow.com/spell=31850

Problema: cuando está activo Defensor candente y recibes un golpe que te mataría, te cura un 15% y luego recibes el daño (con lo que si es en un boss mueres igual), cuando debería de curar un 15% y no recibir el daño.

**Comment by efectokoleos** [comment]
esta spell funciona correctamente
