### ISSUE TITLE
[Paladín] Talento: Escudo Sagrado // 20925

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3517]
ID: http://cata.openwow.com/spell=20925

Problema: en lugar de aumentar la cantidad de daño bloqueado un 20% (el bloqueo por lo general detiene el 30% del daño recibido), está aumentando la probabilidad de bloqueo.

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
