### ISSUE TITLE
[Paladín] Talento: Propósito divino // 86172

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3519]
ID: http://cata.openwow.com/spell=86172

Problema: no está teniendo efecto sobre inquisición, debería usar esa spell contando 3 cargas de Poder Sagrado pero la está usando como si fuera solo 1 carga de Poder Sagrado.

Nota: inquisición con 3 cargas de Poder Sagrado y talento ''Inquisición de fe'', debe durar 36 segundos, al usarlo con propósito divino solo dura 12 segundos.

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
