### ISSUE TITLE
Pnj da articulos gratis que no deberia

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#352]
Pnj (Redia vaunt) ID: 53404  da cosas que no deberia 

-Corcel vil ID: 5784

-Corcel nefasto ID: 23161

![wowscrnshot_071113_153839](https://f.cloud.github.com/assets/4893907/781979/a314ae3e-ea32-11e2-9b63-6011460e2617.jpg)

**Comment by ghost** [comment]
#190

**Comment by redneo** [comment]
yasta
