### ISSUE TITLE
[Paladín] Censura (DoT Sello de Verdad) // 31803

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3520]
ID DoT Censura: http://cata.openwow.com/spell=31803
ID Arrepentimiento: http://cata.openwow.com/spell=20066
ID Sello de Verdad: http://cata.openwow.com/spell=31804

Problema: Censura está eliminando el efecto de Arrepentimiento.

**Comment by Drogoth2** [comment]
Quita el efecto de arrepentimiento porque el objetivo recibe daño, Arrepentimiento no es como aliento de dragón que se quita si recibe daño directo

**Comment by bagnamar** [comment]
Arrepentimiento se quita con cualquier daño a excepcion de censura.

**Comment by Necrofilo** [comment]
Drogoth, lo que dice Bagnamar es a lo que me refiero con el reporte, Censura no tiene que quitar el efecto de Arrepentimiento.

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3917
Seguimos desde este issue.
