### ISSUE TITLE
[Paladín] Sello de Justicia // 20164

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3522]
ID: http://cata.openwow.com/spell=20164

Problema: no siempre limita la velocidad de carrera máxima del objetivo, cuando tendría que aplicarse en el 100% de los casos.

Resumen: no se está aplicando al 100% cuando debería ser así.

**Comment by efectokoleos** [comment]
arreglado
