### ISSUE TITLE
Bug (Hunter) Sic´em´

### ISSUE THREAD

**Issue by chechewas** [RoDNet/Bugtracker-Infinium-4.3.4#3524]
Al parecer se malentendió el funcionamiento de la habilidad.

http://www.wowwiki.com/Sic_'Em!

La habilidad funciona perfectamente pero funciona de mal manera, se supone que se debe de activar cuando un ataque básico de la mascota hace un golpe critico, los ataques básicos de las mascotas no son los mimos que los ataques automáticos, los básicos son Claw, Bite, por ejemplo (http://www.wowhead.com/spell=16827/claw#changelog) la regeneración de focus esta bien, si regenera los 6 focus que son debidos pero no debería regenerarlos cada que un ataque automático de la bestia asesta un golpe critico 
Edito: Gracias a Jhovanni tiene razón, confundí el talento. El que esta bug es Vigorización

**Comment by Jhovanni** [comment]
Sólo un detalle, el hechizo que estás reportando no es ¡Atácalos! de la rama puntería:
http://wow.freakz.ro/spells.php?spell=83356

Si no se trata de Vigorización de la rama bestias:
http://wow.freakz.ro/spells.php?spell=53253

Por lo demás tienes toda la razón en el reporte.
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3667

**Comment by efectokoleos** [comment]
arreglado vigorizacion
