### ISSUE TITLE
Talento de cazador "Maestro tirador" (Rama de punteria)

### ISSUE THREAD

**Issue by javier1200** [RoDNet/Bugtracker-Infinium-4.3.4#3525]
Este es un talento de la rama de punteria que te da la poosibilidad de crear acumulaciones de "Maestro tirador" cada ves que lanses "Disparo firme" y al llegar a 5 tu proximo "Disparo de punteria" sera gratuito e instantaneo.

Este talento funciona a medias, Ya que si activa las aplicaciones, y al llegar a las 5 si activa el efecto adicional, pero lo que pasa es que el juego cuenta cualquier disparo, no solo "Disparo de punteria", lo cual agota el efecto de instantaneo y gratuito si lansas por ejemplo "Disparo de quimera","Disparo arcano","Disparo firme" etc.

Este talento es importante, en especial para el pve en punteria, y al no funcionar bien solo nos quita un gran daño en medio del juego

**Comment by Pegasu5** [comment]
Sin contar que su damage en pvp es netamente bajísimo, siendo uno de los dos main disparos de la rama.

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
