### ISSUE TITLE
Talento del druida "Obsequio de la naturaleza" (Rama de restauracion)

### ISSUE THREAD

**Issue by javier1200** [RoDNet/Bugtracker-Infinium-4.3.4#3527]
Este talento dice, y sito "Aumenta en un 60% la probabilidad de efecto critico de tu Hechizo Recrecimiento. Ademas reduce en un 30 % el tiempo de lanzamiento de tu hechizo Nutrir al tener activo Rejuvenecimiento en 3 o mas objetivos."

Bien, no funciona la reduccion en el tiempo de lanzamiento de nutrir, lo e probado muchas veces ya pero sin importar a cuantos objetivos les tire "Rejuvenecimiento" el hechizo "Nutrir" no modifica su tiempo de lanzamiento

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
