### ISSUE TITLE
Glifos de Druida: Antarbol,Flobotomia,Mordedura Feroz y Huracan. Remate: Mordedura Feroz y talento de feral

### ISSUE THREAD

**Issue by javier1200** [RoDNet/Bugtracker-Infinium-4.3.4#3528]
Glifo de Flobotomia: Cada ves que uses triturar o Destrozar en forma felina la duracion de destripar se extiente en 2 seg hasta un max de 6 seg

Glifo de Mordedura feroz:Tu abilidad mordedura feroz ahora te sana un 1% de tu vida max por cada 10 puntos de energia consumidos

Glifo de Huracan:Tu facultad Huracan ahora relentisa en un 50% La velocidad de movimiento de tus victimas

Glifo de Antarbol: La forma de tu arbol de vida ahora es la de un Antarbol

Ninguno de estos glifos funcionan, no aplican o el cambio de forma o el efecto adicional a el hechizo o habilidad del druida.

Como nota aparte (Tiene que ver por el glifo) El remate Mordedura feroz y el talento "Sangre en el agua" No funciona correctamente, Se supone que mordedura feroz gasta puntos de energia adicionales para causar daño adicional, pero ni gasta los puntos ni aumenta su daño, Ademas el talento de "Sangre en el agua" de la rama de feral del druida especifica que al usar mordedura feroz contra un objetivo con su 25% de vida o menos Hay un porcentaje (De 50 o 100%) de reestablecer la instante la duracion de destripar, bien este efecto funciona sin importar la vitalidad del objetivo, lo que le concede al druida feral un daño descomunal desde el inicio del combate

**Comment by Monleon** [comment]
Varios de los aquí presentes ya han sido arreglados. No obstante si queda alguno reportanoslo de uno en uno
