### ISSUE TITLE
Habilidad por talentos del druida: Pulverizar y Rabia

### ISSUE THREAD

**Issue by javier1200** [RoDNet/Bugtracker-Infinium-4.3.4#3529]
Estos son bugs mas referidos en el tankeo del druida feral

La habilidad "Pulverizar" Tiene un daño descontrolado, en su explicacion mencionan que el daño de pulverizar se igual al 60 % del daño con arma mas un aumento en X puntos de daño extra (Esto es en base al poder de ataque del druida en ese momento) Por cada acumulacion de "Lacerar" en el objetivo, pos bien, el aumento no existe, sin importar las acumulaciones de lacerar esta tecnica tiene un daño fijo

Ademas la ultima habilidad de la rama de feral "Rabia" Tampoco funciona muy bien en oso ya que esta tiene una habilidad pasiva que se activa al estar en oso (Este o no activo Rabia) la cual dice: "El daño periodico de lacerar tiene un 50 % de probabilidad de reiniciar el tiempo de reutilizacion de tu facultad destrozar (Oso) y hacer que no cueste ira". Por bien este efecto pasivo tampoco funciona, el tiempo de reutilisacion es siempre le mismo y jamas se vuelve gratuito sin importar cuantos tics de daño reciba el enemigo de parte de lacerar

**Comment by efectokoleos** [comment]
arreglado
