### ISSUE TITLE
Punto de vuelo BUG

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#353]
El PNJ Dyslix Kami-Kaze  (ID: 23612)  no te da el punto de vuelo

![wowscrnshot_071113_161825](https://f.cloud.github.com/assets/4893907/782102/231492f0-ea35-11e2-828d-d7235d8a4b3b.jpg)

**Comment by crowel** [comment]
Comento que ya funciona, seguramente en el fix que realizó el otro día redneo arreglando maestros de vuelo que no funcionaban.
Cierro, un saludo.
