### ISSUE TITLE
[Paladín] Comunión // 31876

### ISSUE THREAD

**Issue by Necrofilo** [RoDNet/Bugtracker-Infinium-4.3.4#3530]
ID: http://cata.openwow.com/spell=31876

Problema: no funciona nada de nada.

**Comment by Monleon** [comment]
Explícame por favor qué significa "nada de nada", porque yo el efecto de reposición lo veo.

**Comment by Necrofilo** [comment]
Si, lo único que hace es activar el buff, pero no aumenta ni el 3% a los miembros del grupo ni en el paladín, y tampoco aumenta el 2% extra sobre el paladín.

**Comment by Drogoth2** [comment]
Perdonad, pero el efecto de reposición no lo está dando tampoco, lo que veis que regenera mana es  sentencia del audaz (89906) que es un talento pasivo del paladín reprensión que hace que regeneres un 25% del mana, pero el talento de comunión no está dando el efecto de reposición por ninguna parte.

**Comment by redneo** [comment]
Yo lo veo bien, da 2% de daño al paladin, sencia da reposicion, me falta de probar que de a 10 miembros de la raid o grupo ambas cosas.

**Comment by Monleon** [comment]
Está dando el efecto de reposición correctamente al sentenciar...
