### ISSUE TITLE
[Brujo] Aullido de Terror\\ 5484

### ISSUE THREAD

**Issue by nicerdicer** [RoDNet/Bugtracker-Infinium-4.3.4#3531]
http://wow.freakz.ro/spells.php?spell=5484&name=howl-of-terror

Retomando el reporte que se hizo sobre este hechizo.

Aullido de Terror no esta funcionando bien, al usarlo contra un oponente el efecto del aullido se rompe con el primer daño (directo o periodico) presente en el afectado, lo que practicamente inutiliza en casi su totalidad esta habilidad.
Lo normal seria que el efecto según daño recibido desapareciera en el momento en el que, el afectado recibe un daño igual a un % de su salud total.
La mecanica es practicamente igual a la del Alarido Psiquico del Sacer.

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
