### ISSUE TITLE
Sartharion, y la montura del Draco Negro

### ISSUE THREAD

**Issue by DonMadik** [RoDNet/Bugtracker-Infinium-4.3.4#3532]
Dejando vivos a los 3 dragones y consiguiendo el logro de ello no suelta la montura.

**Comment by ghost** [comment]
Id Sartharion: 28860
Id Montura: 43986

**Comment by cibernaco** [comment]
Pero lo has probado varias veces? Es que no indicas como lo has probado, ten en cuenta que no tiene un 100% de probabilidades de dartelo, si no solo un 40%.

Un saludo

**Comment by ghost** [comment]
Tiene 100% si lo matas con los 3 dragones vivos. En los comentarios de wowhead lo confirma http://www.wowhead.com/item=43986/reins-of-the-black-drake#comments
Saludos.

**Comment by cibernaco** [comment]
Los comentarios son del parche 3.0.3, como consejo no te fies mucho de los comentarios a estas alturas muchisimos de ellos son de gente que juega en servers no oficiales, y para asegurarte puedes instalarte el addon de wowhead de la 4.3, si lo haces no le dejes actualizar o no te funcionara, buscalo en google.

Un saludo.

**Comment by ghost** [comment]
Clikea en el nombre del usuario que puso el comentario. Te va a aparecer en que realm del oficial juega y los links a la armeria de su personaje en battle.net. WoWhead tampoco menciona que necesitas matar a los 3 dragones como requisito para que deje la montura: http://www.wowwiki.com/Reins_of_the_Black_Drake
Saludos.

**Comment by cibernaco** [comment]
No me has entendido, aunque siga jugando a dia de hoy, el comentario le puso cuando estaba activo el parche 3.0.3 en el año 2008, como es de imaginar no abra posteado de nuevo si eso ha cambiado o no, y nadie ha dicho que como requisito tengas que matar a los 3 dragones, y en el ultimo link que tu has dejado dice que los dragones tienen que estar vivos para que suelte la montura, no que asi la suelte un 100% de las veces.

**Comment by Solomillo** [comment]
yo jugué lich, cata y mop en el ofi, y la montura era 100% haciendolo con los 3 dracos vivos, tanto en 10 como en 25.

**Comment by Pegasu5** [comment]
Gente del oficial, en pandarian diciendo lo de los 3 dragones, solo que solomillo en lugar del draco negro en 25 sería el draco crepuscular, no?

https://www.youtube.com/watch?v=cSd7larEY1I

**Comment by cibernaco** [comment]
Eso era lo que te decía, que lo comprobaras bien y no con los comentarios de wowhead, y como posibilidad te di que te bajaras el addon de wowhead para comprobarlo, pues si es un 100% es un 100% mejor para todos.

Un saludo.

**Comment by DonMadik** [comment]
Da igual que lo reporte es mas que evidente que antes de que se arregle me salen canas. Pero bueno de este modo asi algunos no van a  hacer el tonto alli para intentar conseguir una montura que nunca caera. Como estos bugs 1000000000000 más un saludo

**Comment by juaks** [comment]
Esto sigue bug.. y no creo que sea muy difícil de arreglar, contando que en la Wotlk funcionaba.

**Comment by redneo** [comment]
en la lich lo soltaba habiendo o no dracos, pero ya está bien.
