### ISSUE TITLE
Habilidad por talento de mascota de cazador tenacidad: Intervenir

### ISSUE THREAD

**Issue by javier1200** [RoDNet/Bugtracker-Infinium-4.3.4#3536]
Esta habilidad que se consigo por talentos de las mascotas tipo tenacidad o mascotas tankes del cazador no esta funcionando bien.

Intervenir: tu mascota corre a gran velocidad hacia un miembro del grupo, lo que absorbe 50% de la salud total de la mascota del daño recibido del próximo ataque.

Bien al usarse esta habilidad si se crea ese escudo de absorcion pero la cantidad de no es la mitad de los puntos de la mascota, si no 50 lo cual no es nada y este talento es muy util en pvp o en juego solitario, e de aclarar que la mascota es 80 ya que es costoso hacerlas pasar de nivel y no se si al aumentar de nivel se arregla la habilidad pero eso no debería ser, si esa es la respuesta les pediría que las pets consigan algo mas de experiencia con monstruos neutrales en especial al ser el personaje nivel 85

**Comment by efectokoleos** [comment]
funciona correctamente
