### ISSUE TITLE
[Crash][Mazmorras/Bandas][Ulduar] La Chispa de la imaginación (10 normal)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3537]
Buenas.
Quería reportar que el ingreso a la zona donde está el boss Mimiron (http://es.wowhead.com/npc=33350) (entre el "Pasaje del Ingenio" y "La Chispa de la imaginación") crashea el server.
Gracias y disculpen las molestias ocasionadas.
Saludos.

**Comment by Dekadencee** [comment]
Fixeado, gracias por el reporte ^^
