### ISSUE TITLE
[Cazador] Llamada de maestro

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3538]
Id: http://es.wowhead.com/spell=53271/llamada-de-maestro
Descripción: Tu mascota intenta eliminar todos los efectos de reducción de movimiento y de raíces sobre sí misma y su objetivo y provoca que ambos se vuelvan inmunes a tales efectos durante 4 s.

Problema: Actualmente hay varios problemas con esta habilidad, el primero y más importante es que no está quitando los enraizamientos de ninguna clase, lo que en pvp es un bugazo desalentador para la clase, segundo no sirve la parte en la cual te hace inmune a estos efectos durante 4 segundos, por lo que si usas el glifo para aumentar su efecto a 8 sec es inservible.

**Comment by cibernaco** [comment]
Si es gracioso el mensaje de, no se puede usar mientras estas aturdido o enrraizado, te quedas O.o

**Comment by Kiritoo** [comment]
Arreglado.
