### ISSUE TITLE
[Cazador] Disparo firme

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3539]
Id: http://es.wowhead.com/spell=56641/disparo-firme

Problema: La reducción de temple es drástica , estoy pegando 1.5k- 1.8k a objetivo con armadura tela.

Adjunto la fórmula del ultimo changelog de cata por si sirve de algo

4.3.0: 100% weapon damage Plus RAP*0.021+280.

**Comment by Kiritoo** [comment]
Arreglado fallo armadura.
