### ISSUE TITLE
Error #132 entre Capilla de ezperanza de la luz y El bastion de ebano

### ISSUE THREAD

**Issue by veyertrox** [RoDNet/Bugtracker-Infinium-4.3.4#354]
buenas a todos, verán, después del rollback del server aparecí en el bastión de ébano (ultimo lugar en que estuve antes de la actualización) y en cuanto salí de allí en montura voladora pase por unas montañas cerca de la capilla de la esperanza de la luz (todo en la zona http://es.wowhead.com/zone=139 Tierras de la Peste del Este) y es en esas montañas en que se me produce el error #132. ahora cada vez que entro me salta ese error y no puedo moverme. he intentado soluciones de todo tipo pero nada, el error sigue allí; asi que me pregunto si algún gm me pueda sacar de allí porque no puedo hacer nada y ni puedo moverme para salir de ahi

**Comment by veyertrox** [comment]
aclaro que es con mi dk  huargen de nivel 85 Joseph

**Comment by ghost** [comment]
Una cosa veyetrox, deberías de quitar eso de error # 132 porque hace enlace a un reporte del bugtracker xd, en todo caso deja una imagen del wow error.

**Comment by veyertrox** [comment]
lo haría, pero no se como sacar una imagen del error T_T, además no me deja editar xd

**Comment by Dekadencee** [comment]
¿Cual es el nombre de tu pj?

**Comment by redneo** [comment]
es increible...

SI llegas alli desde vuelo, no pasa nada. Como estaba bien, he borrado todos los npcs que he visto. Relogueo y mismo error, entro con otro pj, voy para alla, error, desconozco a que se debe dicho error!

**Comment by veyertrox** [comment]
Deka, mi pj es un huargen Dk 85, se llama Joseph

**Comment by veyertrox** [comment]
bueno, de alguna manera logre salir de ahí, asi que cierro porque parece que el error se arreglo xD
