### ISSUE TITLE
[Sacerdote] Talento: Escudo reflectante

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3545]
No tengo id del talento

Problema: No refleja nada del daño, siendo una habilidad base para pvp del sacerdote, no se si estará desactivado aún por reparación, pero de aquí a allá ha pasado un buen tiempito. xD

**Comment by cibernaco** [comment]
http://es.wowhead.com/spell=33619 creo q es ese no?

**Comment by Pegasu5** [comment]
Sí este es :D

**Comment by Necrofilo** [comment]
¿Una habilidad base para PvP del sacerdote? JA JA JA... Rompe CCs, y para lo que quita sale más a cuenta gastar puntos en otros talentos :*

**Comment by Pegasu5** [comment]
Pues cuando vas al tiro lamer no hace falta este talento, pero si es un sacerdote más majo a lo macho man, le gustará aguantar más y porque nó infligir un porcentaje del daño que recibe es bueno para arenas en las que el foco cambia constantemente para mantener al healer bajo presión :3 es decir depende de tu build y la spec y como te guste llevar la clase de ahí parte ''el base'' no todos pueden encadenar fear, nova, poli y control, silencio silencio. etc  :\*
