### ISSUE TITLE
[Sacerdote] Talento: Egida divina

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3546]
Sin id :(

Problema: Este talento esta funcionando mal de alguna manera se está parando la absorción de daño en 28-30k p. siendo que en el ofi con equipo 378 se consigue hasta un 70k p. de absorción deja al sacerdote deficiente a la hora de curar al tank y mantener.

**Comment by cibernaco** [comment]
Es este http://es.wowhead.com/spell=47515 abajo esta el changelos correspondiente, absorbe un 30% de las sanaciones criticas

**Comment by Pegasu5** [comment]
Comento que en la mañana estuve con Doora y Samuriano,  testeando cosas del sacerdote en el reino de desarrollo nos dijo que ya varias cosas estaban fixeadas solo necesitaban ser compiladas, así que cerrar los issues cuando lo veas conveniente. :)
