### ISSUE TITLE
Se ha Bugueado Cargar, Habilidad guerrero

### ISSUE THREAD

**Issue by hermoso2009** [RoDNet/Bugtracker-Infinium-4.3.4#3554]
Hola vengo a informar que se ha bugueado esta tarde la habilidad cargar del guerrero al querer usarla dice que no esta el objetivo al alcance no importa la distancia que estes siempre dice lo mismo, diria q es la mas importante sin eso, el guerrero es solo un auto pesado y lento que muere mientras intenta alcanzar a los demas la habilidad es esta: 
http://es.wowhead.com/spell=100/cargar
tambien con la misma mecanica funciona esta otra que tambien se ha bugueado esta tarde se llama interceptar
http://es.wowhead.com/spell=61490/interceptar
y tambien se ha bugueado esta tarde esta otra habildiad que tambien usa casi la misma mecanica pero que se avalanza sobre un objetivo amistoso, todas dicen no que uno no esta a la distancia requerida, la habilidad se llama intervenir:
http://es.wowhead.com/spell=3411/intervenir

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
