### ISSUE TITLE
[Misión] En memoria

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#3555]
Misión: http://es.wowhead.com/quest=12975
Descripción: hay que recoger los http://es.wowhead.com/item=42162 de los objetos http://es.wowhead.com/object=192081 ó http://es.wowhead.com/object=192082
Fallo: no están los objetos que contienen el objeto de la misión.
Solución: poner los objects

**Comment by ghost** [comment]
Reparada.
