### ISSUE TITLE
Instructores de DK no funcionan... otra vez

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#356]
Aquí los dejo:
http://es.wowhead.com/npc=29196/lord-thorval
http://es.wowhead.com/npc=29195/lady-alistra
http://es.wowhead.com/npc=29194/amalthazad

No tienen opción de reiniciar talentos, ni de aprender doble especialización, y Lord Thorval ni tiene para aprender los hechizos.

**Comment by redneo** [comment]
a mi si que me han salido :S

**Comment by ghost** [comment]
Pues de que aparecen aparecen, pero le das clic.. y nada S:, y lord thorval no tenia ni para aprender hechizos.

Edit:
No sé si alfinal tocaste algo o no redneo, o si era solo algo que me pasaba a mi, ya me funcionan de nuevo.
