### ISSUE TITLE
[Guerrero] Habilidad: Actitud de batalla, defensiva, rabiosa.

### ISSUE THREAD

**Issue by hermoso2009** [RoDNet/Bugtracker-Infinium-4.3.4#3563]
Hola queria reportar un bug que tienen las actitudes del guerrero, el bug es que al usar estas habilidades consume 20 de ira cada vez que se las usa, y ninguna de las 3 actitudes deben requerir ira como lo indica su descripcion, las 3 habilidades son estas:

1_ Actitud defensiva http://es.wowhead.com/spell=71/actitud-defensiva
Id= 71.
2_ Actitud de batalla http://es.wowhead.com/spell=2457/actitud-de-batalla
id= 2457.
3_Actitud Rabiosa http://es.wowhead.com/spell=2458/actitud-rabiosa
id=2458.
Clase: Guerrero.

**Comment by Necrofilo** [comment]
Siempre que cambias de actitud, tu ira debe bajar a 0%, a no ser que tengas talentos para guardar 25p. (rango 1/2) o 50p. (rango 2/2).

**Comment by F4NT4SM4** [comment]
corrección siempre que cambias de actitud retienes un 25p de ira gracias a un hechizo pasivo de procteccion y el talento es para retener 25p/50p extra llegando a retener 75p de ira

**Comment by redneo** [comment]
Se arregló

**Comment by F4NT4SM4** [comment]
se arreglo fue el talento pero sigue bug deberia retener 25p de ira sin necesidad del talento gracias a maestria en actitudes https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2074
el talento aumenta es 25p/50p extra de lo que antes retenia un total de 75p 
disculpa si molesto pero es que lo digo para que no piensen que ya esta reparado
