### ISSUE TITLE
Bastión del Ébano

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#357]
Bueno... el bastion del ebano necesita una LIMPIEZA, ¿por qué?, porque hay muchos mobs, npcs y demás cosas que deberían de estar en El enclave escarlata (zona inicial de DK, es una fase), no en el bastion del ébano.

Por cierto, tampoco tendría que poder volar dentro del bastion del ebano.

Actualizo para poner imagenes.
![wowscrnshot_071113_172633](https://f.cloud.github.com/assets/4663665/784944/b25930c0-ea70-11e2-9bda-127fc4122a57.jpg)
![wowscrnshot_071113_172629](https://f.cloud.github.com/assets/4663665/784946/b5aeb510-ea70-11e2-9926-8a7fa68dd213.jpg)
![wowscrnshot_071113_172623](https://f.cloud.github.com/assets/4663665/784947/b87401ec-ea70-11e2-97a5-89da81292cc0.jpg)
![wowscrnshot_071113_172602](https://f.cloud.github.com/assets/4663665/784949/bb6e0adc-ea70-11e2-8fdb-53d28e3ef7fd.jpg)

**Comment by Eressear** [comment]
Puedes sacarle fotos aunque sea con el movil, mientras se vea bien.

**Comment by Dekadencee** [comment]
@Lvmb ¿Todos estos reportes tuyos que estas cerrando es debido a?

**Comment by ghost** [comment]
@Dekadencee este reporte lo cerre porque ya no estan más todos estos npcs en el batión del ebano, si quieres pongo por qué cerre los demás en los respectivos reportes.
