### ISSUE TITLE
[Cazador] Enfoque, skills.

### ISSUE THREAD

**Issue by Sandriel** [RoDNet/Bugtracker-Infinium-4.3.4#3571]
Buenas tardes, aquí presentare algunos de los bugs del cazador, 
1)La skill Feing Death(fingir muerte) recarga al 100% tu focus bar luego de ser usada lo que es bastante abusivo ya que te permite seguir manteniendo tu dps disponiendo de ese enfoque.
2) La skill Trap Launcher(lanzador de trampas) otorga al momento de activarla 50 ptos de enfoque, y no solo eso ya que uno puede cancelar el aura y volver a utilizar la skill sin el cd o en su defecto solo con el cd global (0.5) (Lo probe y puedes mantener tu enfoque en 100% todo el tiempo con un macro simple)
3) El coste adicional de las skills (asi lo llamo yo) nose si sera un bug grafico, o algo relacionado solo con la barra de enfoque, pero todas las skills al estar en combate, o al salir recientemente de uno tienen un coste extra de enfoque, me explico la skill Arcane Shot (disparo arcano) pide 22 ptos de enfoque(con talento) pero al momento de la lanzarla me encontraba con 30 puntos de enfoque, y luego de lanzarla mi enfoque se redujo a 0, esto pasa con todas las skills hasta las que no piden costo de enfoque. El ejemplo mas claro es el del Aimed Shot (Disparo de punteria) que al estar en las mismas situaciones teniendo 50 ptos de enfoque que es su coste, no me dejaba lanzarlo sino hasta teneg 65, 70, 72 ptos de enfoque (varia).
4) El talento Master Marksman (Maestro Tirador) que cuyo efecto es que al lanzar Steady Shot (disparo firme) tienes un % de activar un buff del mismo nombre, que se estaquea hasta 5 veces y al llegar a la quinta se remplaza por un buff llamado !Fire!( !Fuego!) que te permite lanzar Aimed Shot(disparo de punteria) sin coste de enfoque ni lanzamiento y dura 10 segundos, pero al tener este buff activo y lanzar cualquier otra skill o obtener cualquier otro buff se cancela el buff, lo que es bastante molesto ya que se pierde ese gran dps que logra ese talento.

Eso, no se ocupar muy bien el foro si necesitan fotos me avisan y vere como ingeniármelas para mostrarles los bugs
Paz

**Comment by Pegasu5** [comment]
Más que nada la regeneración de enfoque va de la mano con la celeridad, y es este el problema, además de que ciertas auras/buffos tambíén influyen.

**Comment by Sandriel** [comment]
Es que no va por la regeneracion de enfoque, simplemente al lanza la skill, se pierde enfoque y luego se regenera, cosa que no deberia ser asi.Y los otros bugs?

Date: Sun, 6 Apr 2014 03:09:21 -0700

**Comment by Jhovanni** [comment]
Antes de todo, creo que un reporte para cada cosa queda más organizado, además que cosas con enlaces y eso ayuda.
1. Fingir muerte al ser usado, no regenera el enfoque al 100%. De hecho es común que suceda lo contrario: al usarlo pierdes el 100% de enfoque sin importar que cuando lo usaste tenías la barra llena. Que suceda lo contrario, pues es posible que también suceda, aunque no me he fijado (tema ya reportado).
2. La regeneración del 50% de enfoque que aparece cuando usas Lanzador de trampas es al tomar el talento Recuperación rápida de la rama puntería, el cual está bug: no te otorga 50 puntos de enfoque al usar el hechizo, sin embargo te otorga 50 puntos cada vez que usas Lanzador de trampas mientras tengas el talento.
3. Los hechizos no tienen coste adicional. Lo común es el bug visual de regeneración de enfoque, el cual te hacía ver como si tuvieses mucho más enfoque del real, no pudiendo soltar hechizos aún cuando en tu barra apareciese como si tienes suficiente energía (problema que solucionaron hace poco).
4. En este estás en lo correcto en cuanto al bug (tambien ya reportado).

**Comment by Jhovanni** [comment]
Fingir muerte
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3364

Recuperación rápida
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3483

Maestro tirador
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3259

**Comment by Monleon** [comment]
Ya que tanto el segundo punto como el tercero ya estan arreglados, y el resto ya están reportados previamente cierro el issue.
