### ISSUE TITLE
Problemas con la migracion

### ISSUE THREAD

**Issue by josedeivid** [RoDNet/Bugtracker-Infinium-4.3.4#3573]
He intentado migrar un personaje de nivel 80 de un servidor 3.3.5 pero no se exactamente si necesita un tiempo o es al instante, llevo sobre un par de dias esperando  (aproximadamente) pero aun no e recibido nada y no se si ha habido algun tipo de problema o no lo he echo bien, quisiera informacion para saber si se necesita un tiempo o es que debo de volver a hacerlo por algun error que halla echo.
Muchas gracias por todo.
Un saludo.

**Comment by Compresor** [comment]
Siento darte una mala noticia, pero las migraciones aun no están activas. En cuánto tengamos la nueva web, que será pronto, estarán activas y podréis traer cuantos personajes querais de mientras no lo intentéis porque os saldrá error. Si quereis de mientras podeis utilizar la migracion para jugar con un personaje ya al 85.
