### ISSUE TITLE
[bug skype] 1 mes sin recibir lo que pague

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3575]
creo que mi usuario de skype esta bug y no recibo las respuestas, o quiza algun admin me ha estafado 800€ aunque espero estar equivocado...

**Comment by Kiritoo** [comment]
¿Dreamwow? creo que te has confundido este bugtracker es para reportar fallos de nuestro servidor, aunque no entiendo bien tu problema realmente, está zona es solo para bugs.

**Comment by ghost** [comment]
fixx, esto es algo más serio que un bug

Un saludo

**Comment by Dekadencee** [comment]
El tema ya ha sido comunicado al responsable, nobstante Paranosis te digo dos cosas, en primer lugar creo que quedó claro que no queria volver a saber nada de vosotros y en segundo lugar cuidado al generalizar con la administración porque yo no tengo nada que ver con vosotros (ni siquiera nos hablamos...)
