### ISSUE TITLE
[Item] Suministros importados

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#358]
Los suministros importados(http://es.wowhead.com/item=68689) al abrirlos no dan las semillas de cacao para hacer determinadas recetas de cocina. Lo he probado unicamente en el bando de la Horda. Si alguien, lo pudiese mirar en la Alianza a ver si le paso lo mismo, sería de agradecer

**Comment by DatJetto** [comment]
Cada http://es.wowhead.com/item=68689 debe contener un MÍNIMO DE 40 pepitas de chocolate y como máximo 60.

**Comment by Wiinter** [comment]
Arreglado
