### ISSUE TITLE
[Paladín] 2P bonus (Retribution)

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3585]
ID: http://es.wowhead.com/spell=99093/item-paladin-t12-retribution-2p-bonus
Descripción: Tu Golpe de cruzado inflige un 15% de daño extra como daño de Fuego durante 4 s.

Problema: no funciona, creo que este se manifiesta en forma de DoT

**Comment by redneo** [comment]
Sabes que spell ha de poner?

**Comment by Pegasu5** [comment]
No tengo idea de la spell, a lo mucho me he orientado un poco con un comentario de wow head: 
-it rolls like Ignite.
 Y este es el único video en el que puedo ver claramente el DoT de 4 sec, luce como la spell de mago. 
https://www.youtube.com/watch?v=RDKHl-QBqYI

Intentaré buscarla más a fondo.

**Comment by redneo** [comment]
Como combustion?

Edito: http://es.wowhead.com/spell=99092

Ese.

**Comment by Pegasu5** [comment]
Exacto muchas gracias
