### ISSUE TITLE
[Mago Fuego] Bomba Viva

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3586]
Nombre: Bomba Viva
ID:44457
Enlace:http://wow.freakz.ro/spells.php?spell=44457
Descripcion: El objetivo se convierte en una bomba viva y recibe 936 (+25.8% SP) de daño de fuego durante 12s. despues de 12s el objetivo explota e inflige 468 (+51.5% SP) de daño de fuego a un maximo de 3 enemigos en un radio de 10m. limite 3 objetivos

Problema: tiene el daño dot algo elevado un 40% aproximadamente (en caso de que bomba viva tenga la formula bien ps tengo una buena idea de que es lo que esta aumentando mas el daño de los dot la maestria pero no estoy seguro si es bomba viva o la maestria)

Testee sin equipo(esto lo coloco por que siempre hay gente defendiendo su clase y piden explicacion): Tengo 220sp sin equipo, el 25.8% de mi sp es 56,76+936= 992,76.
992,76+25%(especializacion en fuego)=1240,95
1240,95+22% (maestria)=1513,959 aproximadamente es esto lo que deberia hacer el daño total de los 4 dot sin embargo el daño que esta haciendo es 2208 
un 40% mas de daño esta haciendo 

si me falto algun talento que no me di cuenta ps decirme cual es ese talento que aumenta aproximadamente ese 40%
dejo unas imagenes de mi talentos, equipo , estadisticas, daño
![wowscrnshot_041014_190138](https://cloud.githubusercontent.com/assets/3101842/2674838/92d06be0-c109-11e3-8b18-3a696110ff46.jpg)

![wowscrnshot_041014_190204](https://cloud.githubusercontent.com/assets/3101842/2674847/c0f63310-c109-11e3-9003-5d6c40d23be3.jpg)

**Comment by Pegasu5** [comment]
Que comiencen los juegos!!

**Comment by F4NT4SM4** [comment]
jajajaja esperaba que mi primer comentario fuera de alguien dandome la contraria o alguna excusa y vienes tu xD

**Comment by nayan87** [comment]
por fin un reporte en condiciones¡¡¡

A ver te faltaria poner el talento masa critica al tope, ese sube el daño un 15% mas, así como el talento poder de fuego al máximo que creo que es otro 3% más si no me equivoco, si a eso le sumas algún DOT mas como combustión (en el recount veo que no lo usaste , pero es una teoría que tengo) podríamos tener el % más de daño ese que buscas, eso sin contar la maestría de fuego, no obstante probaré con mi mago, por lo demás todo correctísimo, pedazo report te has marcado fantasma, ojalá hubiese más como tu ^^

**Comment by F4NT4SM4** [comment]
bueno gracias :p 
el talento masa critica y el otro talento que aumenta un 3% no lo tengo puesto en los talentos para poder testear solo bomba viva y solo contar maestria y especializacion en fuego

**Comment by redneo** [comment]
Pruebas hechas por mi Doora:

Reseteo de talentos, esto significa que no tengo ninguna modificación añadida.
Limpiado de auras, lo cual significa, que si por las moscas quedaba algo, ya no hay.

14435 de poder con hechizos. Lanzo bomba viva SOLA.

4 TIcks de 3958 + dos golpes (habia dos muñecos cerca) Criticos de 11853. Normal de 7902

Datos que me da el Dr Damage: Ticks 3x3958.6 Golpe: de 7903-7904.

Comentar que lo  he hecho en el server de test (mismo emulador misma base de datos).

Testeo en Infinium:

SP de 21387, misma situación no talentos no auras.

4 Ticks de 5751 o 8626. Golpe de 11482 o 17223 critico.

El Dr damage me dice: 3 ticks de 5752 y golpe de 11483.

El problema no es de la bomba viva por sí.

**Comment by F4NT4SM4** [comment]
intonce como suponia es la maestria que esta aumetando el daño de todos los dot mas de lo que deberia por favor revisarla si no es mucha molestia 
tambien esta aumentaodi ignicio mas de la cuenta y otros dot de fuego
los iva reportar uno por uno pero si bomba viva esta bien significa que es la maestria que aumenta todo los dot en ves de 22% base como deberia ser puede que el doble

**Comment by redneo** [comment]
Vuelvo a hacer pruebas:
Como siempre limpio de talentos, limpio de auras:
Dot de bomba: 6001
Dot de bomba con Especializacion en Fuego: 7501
Me quito el aura, y me aprendo un punto de talento:
Dot de bomba: 11164

Olvido la maestria, me quito los auras: 76595 y 86473
Dot de bomba viva: 7501

Me pongo el aura 76595 (Maestria quemadura relampago). 
Dots de bomba: 9151.

Aqui empieza lo bueno: Como no tengo la maestria aprendida, no tengo puntos de maestria.
Pero por el aura en si, me sube un 22% el daño.

Ahora bien si me aprendo la maestria, ya me sale que tengo 8 puntos de maestria y el tooltip de la maestria me dice: Aumenta el 22% el daño, cada punto aumenta un 2.8 y la descripcion de la maestria me dice que Aumenta un 22% (este 22% sale de tener 8 de maestria base y multiplicarla por 2.8). COn lo cual el daño que tendria que hacer es de 9151 mientra que hago... 11164, justamente un 22% de más.

Sentencia de mi parte, si la maestria del mago fuego esta mal.

Edito: Ultima prueba, me pongo el anillaco de 4k de maestria: me da 8 +22.31 teoricamente tendria que hacer un 30*2.8 de daño mas respecto a 7501... seria un 84% 13800 mas o menos: mientra que hago.....13900

Edito de nuevo: 
Ap 11854.
Dot sin maestria ni talentos puestos: 3292 -->OK
Dot con Especializacion en Fuego: 4115 --> OK
Dots aprendiendo un punto de talento, teoricamente tendria que ser: 3292_1.25_1.22 = 5020 y me hace 6124
Dots con un punto de talento y 4k puntos de maestria (8+22.31=30 puntos de maestria): teoricamente tendira que ser: 3292_1.25_1.84= 7571.6 haciendo 13967 justo, justo un 84% de más.

Moraleja, la maestria la está cogiendo dos veces.

**Comment by redneo** [comment]
Cuando me ha salido que lo hacia bien era pq cambie un anillo de intelecto por uno de maestria y logicamente me bajo el daño base.

**Comment by redneo** [comment]
Cierro el tema
