### ISSUE TITLE
firelands: npc bug barón kar y piroseñores

### ISSUE THREAD

**Issue by nayan87** [RoDNet/Bugtracker-Infinium-4.3.4#3588]
¿que ocurre? este ncp invoca una serie de adds , el problema fundamental es que estos adds (piroseñores inestables) tienen su daño muy muy subido, provocando wipes casi instantaneos a parte del daño estunean a la raid al completo impidiendo curas, 

¿que debería ocurrir?

1- Kar el abrasador : este npc tienen 3 habilidades: invocar elemental de fuego, invocar principe de lava y quemadura de alma. En ningún caso debe invocar un piroseñor inestable.

2- Los  piroseñores inestables deben aparecer en su localización correcta que es la cuesta de subida hacia Lord piroclasto, y ahi deben ser eliminados, en ningún caso deben ser invocados por Kar el abrasador.

El resto de habilidades funcionan bien y el loot es correcto también.

Os dejo una vez más un link de wowhead que explica mejor que yo las habilidades de este NPC: http://es.wowhead.com/npc=53616#abilities

Una vez más gracias por vuestro tiempo

**Comment by redneo** [comment]
Lo he cambiado un poco, no tendria que ser taaaaan over.

Invocar elemental de fuego, los sacara FUERA de combate sobre jugadores a cierta distancia.

Invocar principe de lava, lo sacará DENTRO de combate y se seguiran reproduciendo, un poco más lento.

Quemadura de alma, lo lanzará mucho más seguido pero a pjs aleatorios, no a todos.

**Comment by nayan87** [comment]
gracias red ^^

**Comment by redneo** [comment]
Ojo, no lo he probado en vivo, solo he cambiado las cosas, a lo mejor es peor que antes xD
