### ISSUE TITLE
[ Bug: Armadura o Temple ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#359]
Buenas, he notado que hay una disminución bastante considerable respecto en el daño  de los pj hacia otros pj, esto puede ser debido a 2 factores Armadura o Temple, en este caso hablo de ataques físicos que es donde he notado mayor drececimiento.

Pongo el ejemplo de disparo de puntería, tiene el daño bajo y al palo pega 20k de crítico aproximadamente con el set sañoso y un abalorio activado de 960 de agi.
Mi armadura está sobre el 36-37% de reducción física ( 14-15k )

Procedo a duelear contra un mago, el cual no tendrá mucho más del 14% de reducción física y le pego de crítico 7k en las mismas condiciones, estamos hablando de una reducción del 70% más o menos entre armadura y temple.

Ya si dueleas con un placas, esos 20k , se convierten en 4k críticos o menos. 

Rogaría revisen estos atributos. Gracias.

**Comment by Navalagamella** [comment]
Creo que alomejor tiene más relación con el temple (aunque no estoy seguro) por que los magos solo me hacen 8k de crítico y como daño mágico no se ve afectado por la armadura, o quien sabe, me habré mal-aconstumbrado a los magos xD.

**Comment by ghost** [comment]
Cuidado con los magos por si llevan la armadura de hielo que, si funciona, reduce el daño físico recibido en un 15%.

**Comment by Kiritoo** [comment]
Arreglado, pendiente de compilar.
