### ISSUE TITLE
[Druida] Cambio de Formas

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3590]
Nombre: Cambio de formas 
ID:
5487 (Forma de oso)
1066 (forma acuatica)
768 (forma felina)
783 (forma de viaje)
40120 (forma de vuelo presto)
33943 (Forma de vuelio)
Enlace: http://wow.freakz.ro/spells.php?spell=768
Descripcion: Cambios de forma: entrar o salir de un cambio de forma ya no cancela los efectos de enraizamiento Pero Sigue cancelando los efectos de ralentización de movimiento.
Problema: No esta cancelando los efectos de ralentizacion

Fuente:http://eu.battle.net/wow/es/game/patch-notes/4-0-6

**Comment by gorr** [comment]
Me acabas de ahorrar el ponerlo ahora mismo iba a hacerlo y vi el tuyo es cierto lo he comprobado en las Bg's sobretodo al cambiar de forma no quita las ralentizaciones arreglen ese porfavor.

**Comment by Kiritoo** [comment]
Arreglado, falta compilarlo pero lo estube probando en test y perfecto.
