### ISSUE TITLE
[Item] Engarce de joyero

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#3592]
Item: http://es.wowhead.com/item=52188
Descripción: este item es vendido por vendedores de <Suministros de joyería> como Marith Lazuria (http://es.wowhead.com/npc=50482)
Fallo: no lo venden, por lo que subir joyería se hace difícil

**Comment by F4NT4SM4** [comment]
minestra reparan ese item puedes buscarlo en las otras capitales en estrañas horda lo he podido conseguir pero es un fastiodio tener que ir al otro continente por un item que deberia estar en ogrimmar e.e
