### ISSUE TITLE
DK "La bendición del jefe de guerra"

### ISSUE THREAD

**Issue by german2p** [RoDNet/Bugtracker-Infinium-4.3.4#3593]
pide que valla con trhall y trhall no esta

**Comment by nayan87** [comment]
german, obviamente en esta expansión tenemos que ir a ver a garrosh hellscream, faltaría corregir el texto de la misión y la ubicación del PNJ , que nos marca a Thrall, por la ubicación de Garrosh que es el que nos culmina la misión. Saludos
