### ISSUE TITLE
Bonus 4 piezas t12 Spriest

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3594]
http://www.wowhead.com/spell=99157/item-priest-t12-shadow-4p-bonus

Cuando tienes activos los dots 34914, 2944 y 589 en tu objetivo actual, el sacerdote debería ganar el aura http://www.wowhead.com/spell=99158

Problema: no le está apareciendo el aura al sacerdote.

El aura 99158, supongo que si debe potenciar el daño, el problema es que al no poder ganarse no se puede probar.

**Comment by efectokoleos** [comment]
arreglado falta compilar
