### ISSUE TITLE
Bonus 2 piezas t12 Spriest

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3596]
http://www.wowhead.com/spell=99154/item-priest-t12-shadow-2p-bonus

Problema, únicamente está reduciendo el CD del maligno (34433), pero no está haciendo que este inflinja un 20% de daño extra como daño de fuego.

No he podido encontrar la id del daño extra de fuego, no sé si puede ser la 99155 o la 99156

**Comment by Monleon** [comment]
Funciona
