### ISSUE TITLE
[DK] Esbirro: Saltar (Transformacion Oscura)

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3598]
Nombre: Saltar (Transformacion Oscura)
ID:47482
Enlace:http://wow.freakz.ro/spells.php?spell=47482
Descripcion: Transformacion oscura: Cargar contra un enemigo. lo que interrumpe el lanzamiento de hechizos y lo inmoviliza durante 2s
Problema: solo cargar contra el enemigo pero en transformacion oscura deberia hacer lo que dice la descripcion

**Comment by Monleon** [comment]
Ya la realiza
