### ISSUE TITLE
[DK] Esbirro: Roer (Transformacion Oscura)

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3599]
Nombre: Roer (Transformacion Oscura)
ID:47481
Enlace:http://wow.freakz.ro/spells.php?spell=47481
Descripcion: Transformacion oscura: Golpea a un enemigo con un ataque aplastante, lo que inflige un 125% de daño cuerpo a cuerpo normal y lo aturde durante 4s
Problema: solo esta haciendo un stun de 3s esto deberia de cambiar en transformacion oscura a 4s stun y 125% de daño cuerpo a cuerpo

**Comment by Monleon** [comment]
Ya la mejora
