### ISSUE TITLE
Cuenta sin personajes

### ISSUE THREAD

**Issue by XxsnipersxX** [RoDNet/Bugtracker-Infinium-4.3.4#36]
Hola, para informar que mi cuenta XxsnipersxX, no posee ni un personaje me tira un error 
![wowscrnshot_070313_193859](https://f.cloud.github.com/assets/4934627/746967/a7241cda-e442-11e2-811d-cee29301956b.jpg) 

seria de mucha ayuda, que me ayuden a recuperar contienen 6, 85 gracias por su atención

**Comment by Dekadencee** [comment]
Hace 7h el servidor no estaba funcionando bien, borra la caché e intenta loguear de nuevo

**Comment by XxsnipersxX** [comment]
Hola Dekadence, me sigue tirando el mismo error y ya he borrado caché :c, que podría hacer en este caso?
