### ISSUE TITLE
[ Bug: Regeneración de enfoque ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#360]
Buenas, antes estaba jugando normal, notaba una recuperación de enfoque stándar, cuando de pronto al entrar a bg y morir el enfoque se recargaba como quería, lanzaba un aspecto ( el cual no consume enfoque ) y se me bajaba la barra de enfoque a la mitad o apretar disparo arcano y te consume foco sin haber lanzado el disparo, pulsando sin objetivo ni nada. 

Al reloguear parece que se ha solucionado pero esto es extraño y rogaría lo revisen.

**Comment by Kiritoo** [comment]
Arreglado bug visual, falta compilar. Si veis que falla en algun aspecto, ira, energia, enfoque.. avisad
