### ISSUE TITLE
[DK] Esbirro: Zarpa (Transformacion Oscura)

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3601]
Nombre: Roer (Transformacion Oscura)
ID:47468
Enlace:http://wow.freakz.ro/spells.php?spell=47468
Descripcion: Transformacion oscura: Pega un zarpazo al enemigo con garras deformadas, lo que inflige un 150% del daño normal al objetivo y a un maximo de 2 objetivos adicionales
Problema: no esta teniendo efecto la transformacion oscura sigue pegando un ataque normal y a un solo objetivo

**Comment by Monleon** [comment]
Ya la mejora
