### ISSUE TITLE
[DK] Esbirro: Acurrucarse (Transformacion Oscura)

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3602]
Nombre: Acurrucarse (Transformacion Oscura)
ID:47484
Enlace:http://wow.freakz.ro/spells.php?spell=47484
Descripcion: Emite un rugido fortificador, lo que reduce todo el daño recibido un 50% durante 10s
Problema: no hace tal rugido

**Comment by Monleon** [comment]
Ya la realiza
