### ISSUE TITLE
[Cazador] Maestria: Carcaj Salvaje 

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3605]
Nombre:Maestria: Carcaj Salvaje 
ID: 76659
Enlace: http://wow.freakz.ro/spells.php?spell=76659
Descripcion: Otorga un 16.8% de probabilidad de que tus ataques a distancia activen al instante un ataque a distancia extra. cada punto de maestria aumenta la probabilidad un 2.1% extra
Problema: La probabilidad esta algo elevada capas tenga doble efecto como la maestria de mago fuego  solo es una posibilidad 
mi otra teoria es que ese ataque distancia extra tambien esta siendo afectado por la maestria osea carcaj salvaje activo carcaj salvaje

**Comment by Kiritoo** [comment]
Arreglada, falta compilar.
