### ISSUE TITLE
[Mago] Orbe de priofrio [Talento]

### ISSUE THREAD

**Issue by Igrime** [RoDNet/Bugtracker-Infinium-4.3.4#3607]
ID; 84727 - http://wow.freakz.ro/spells.php?spell=84727&name=frostfire-orb

Cuando lo tienes talenteado el orbe de fuego pasa a ser el orbe de pirofrio, el orbe no pega, te sigue como si fuera una pet.

¿Como debería de funcionar? Tendría que pegar como el orbe de fuego normal, pero añadiendo un 40% de reducción de movimiento y además, con % de probabilidad de dar Dedos de escarcha, ya que es un hechizo con efecto de enfriamiento y se beneficia de el talento Dedos de escarcha.

Gracias y un saludo.

**Comment by efectokoleos** [comment]
ya esta arreglado
