### ISSUE TITLE
[ Hunter > Feign Death ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#361]
http://es.wowhead.com/spell=5384
Fingir muerte, como bien dice un post anterior, al usar esta facultad tu barra de enfoque se pone a 0, cuando esto no debe suceder, debes permanecer con el enfoque tal y como lo tenías justo antes de usar la habilidad. ( esta habilidad no cuesta enfoque )

Otro problema es que a veces se bugea y no muestra su Cooldown, se queda como recargada pero si la pulsas te dice que está en tiempo de reutilización.

![wowscrnshot_071213_142206](https://f.cloud.github.com/assets/2728817/788210/147f9aca-eaf6-11e2-8882-3bbd06fffba2.jpg)

**Comment by searum** [comment]
es bug visual
