### ISSUE TITLE
golpe de cruzado (paladin)

### ISSUE THREAD

**Issue by janils** [RoDNet/Bugtracker-Infinium-4.3.4#3610]
este hechizo tiene un tiempo de uso que  es de  4.5 segundos , es normal estando la rama de represión, pero el bug esta en que en la rama de protección el tiempo de uso sigue siendo el mismo , este tiempo esta mal ya que debe ser de 3 segundos en la rama de protección , gracias hágala lo corrigan

**Comment by Overseer101** [comment]
Tienes Razon, aunque no aparece por ninguna parte, es un cambio oculto de Blizzard para la rama proteccion, ha sido fallo mio.

El fallo viene por el Talento 31878 "Sentencias del Sabio", que actualmente ese efecto de reduccion de CD esta deshabilitado
