### ISSUE TITLE
[Hechizo - Sacerdote] Maligno de las Sombras

### ISSUE THREAD

**Issue by Akademika** [RoDNet/Bugtracker-Infinium-4.3.4#3615]
Hola a tod@s,

He observado que el Maligno de la Sombras del priest no funciona adecuadamente.

http://es.wowhead.com/spell=34433/maligno-de-las-sombras

Problema: en pvp, si el sacer se está moviendo (que es casi siempre), el maligno se queda a su lado y no hace nada. Si el objetivo se mueve o lanza cualquier hechizo (que es lo normal cuando estás luchando), el maligno vuelve enseguida y se sigue quedando al lado del sacer. Vamos, que prácticamente está de adorno, porque ni da maná ni quita daño.

En pvE funciona algo mejor, quizás sencillamente porque tanto el boss como el sacer están quietos sin moverse, y sólo ahí, ha cumplido medianamente su función.

Mirad si podéis arreglarlo, muchísimas gracias por vuestro trabajo y esfuerzo.

**Comment by Monleon** [comment]
Ajustado el daño y la velocidad de ataque (cada 1.5 seg)
