### ISSUE TITLE
Atascado 

### ISSUE THREAD

**Issue by YoSoyPlanB** [RoDNet/Bugtracker-Infinium-4.3.4#3617]
![captura1](https://cloud.githubusercontent.com/assets/7331699/2737992/282d9246-c685-11e3-867b-a5f68c6b0626.PNG)
me he quedado buggeado aqui , abajo del mapa y no puedo moverme

**Comment by Monleon** [comment]
Nombre del pj por favor, para poder ayudarte.

**Comment by Monleon** [comment]
Arreglado
