### ISSUE TITLE
[ Hunter > ¿Disparos bug? ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#362]
He notado que a veces mientras estoy lanzando hechizos como Disparo firme, cobra o disparo de puntería, estas spells dejan de lanzarse de manera gratuita, es decir, estoy lanzando firme y de pronto se corta, sin tocar otra spell ni nada, ocurre con disparo de puntería y cobra.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/281 Disparo firme
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/282 Cobra 
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/283 Puntería

También me ocurre a veces que estoy disparando a un objetivo y de pronto no puedo lanzar ningún otro ataque, es decir , estoy lanzando Quimera, Arcano, Firme con tranquilidad y de pronto se bugea o algo y aunque pulse los botones, no lanza las habilidades, a ver si pueden mirar eso :$

![wowscrnshot_071213_180346](https://f.cloud.github.com/assets/2728817/789299/96924730-eb0d-11e2-8c4e-36f607ef38a0.jpg)

Se ve como aprieto Disparo arcano y Disparo de quimera, pero no lanza nada.

**Comment by Hellythium** [comment]
Oye Gromelger, a ti no te pasa que cuando lanzas Disparo firme o de cobra y cuando un enemigo te toca se interrumpe, lo cual no debería de ser así si no que debería de haber un pequeño retraso en el casteo de alguna de estas spells y mas no una interrupción, sin contar que otra vez están lentos los disparos.

**Comment by ghost** [comment]
A mi me pasa lo mismo al lanzar hechizos.. cuando estoy casteando se cancela de manera gratuita xd.

**Comment by Dekadencee** [comment]
Es debido al disparo automático por lo que he podido comprobar

**Comment by ghost** [comment]
¿Y si yo no tengo disparo automatico? me pasa lo mismo con mi sacerdote al castear... lo de que se interrumpa el casteo gratuitamente.

**Comment by searum** [comment]
fiiiiiiiiix pero testearlo!
