### ISSUE TITLE
Atascado 2 y problemas con el Zepelín

### ISSUE THREAD

**Issue by YoSoyPlanB** [RoDNet/Bugtracker-Infinium-4.3.4#3620]
![captura2](https://cloud.githubusercontent.com/assets/7331699/2741277/bea141e6-c6e4-11e3-8f3c-25921de1cc86.PNG)            Buenas  , antes me han resuelto un problema de que estaba atascado fuera del mapa  , hoy he intentado usar una piedra del hogar que me llevaba a ogrimar pero no ha funcionado y ha desaparecido , después he cogido el zepelín y en cierto tramo el zepelín desaparece y yo caigo al vacío . el nombre de mi PJ es Plan B

**Comment by Compresor** [comment]
Pon ticket ingame y te lo solucionamos en un periquete.
