### ISSUE TITLE
Paladin Inquisicion 

### ISSUE THREAD

**Issue by nzretry** [RoDNet/Bugtracker-Infinium-4.3.4#3621]
Hola, quria de reportar el bug de Inquisicion ya que cuando se nos activa el talento Propósito divino
Las facultades que cuestan Poder Sagrado tienen un 25% de probabilidad de provocar el efecto Propósito divino.
Propósito divino
Tu siguiente facultad de Poder Sagrado no consume Poder Sagrado y se lanza como si se utilizasen 3 cargas de Poder Sagrado. Dura 8 s.
 Vale ahora bien, el problema esta en que la el hechizo Inquisicion no se lanza como si tuvieramos 3 cargas de poder sagrado ( 35 segundos ) si no que sigue lanzandose como si tuvieramos 1 carga ( 12 segundos ) Ej: cuando a mi me salta Proposito divino - yo activo inquisicion - dura 12 seg y no 35 como deberia. Espero que lo entiendan, gracias. Un saludo!

**Comment by Kiritoo** [comment]
Arreglado, pendiente de compilar.

**Comment by nzretry** [comment]
esta arreglado inquisicion ? gracias:))

2014-07-28 18:14 GMT+02:00 fixx notifications@github.com:

**Comment by Kiritoo** [comment]
Sip
