### ISSUE TITLE
[Karazhan] Boss Bug

### ISSUE THREAD

**Issue by gorr** [RoDNet/Bugtracker-Infinium-4.3.4#3628]
El boss Attumen el Montero el que suelta la montura épica esta bug fui con un dk sangre y recibia golpe de 50k o más agradecería su arreglo ya que mucha gente quiere ir a dropear la montura gracias.

**Comment by nayan87** [comment]
Pero ese boss esta bien, doy fe que voy todas las semanas con mi dk tank y se tira a la perfección, normalmente vamos 3 o 4 personas y lo hacemos sin problemas, eso  sí, si estas en dps te va a cascar lo que no esta escrito, a pesar de ser raid 70 te recuerdo que es un boss que pega bastante, suerte¡
