### ISSUE TITLE
[Pj Atascado]

### ISSUE THREAD

**Issue by Agohige** [RoDNet/Bugtracker-Infinium-4.3.4#3629]
Hola, hace un par de días que no puedo solucionar lo siguiente...
Ingresé en uno de los ships de Corona del Hielo, y me apareció como si se estuviera Teletransportando a algún lado, y aparecí en caída libre en medio del cielo, no me muestró el pj, nunca llegó al suelo, por ende...luego de 1 minuto, murió.
Ahora, solo me aparece lo siguiente:
![clipboard01](https://cloud.githubusercontent.com/assets/7366892/2760327/57f507a8-c9b3-11e3-88f5-38af8cf99805.jpg)

Pj: Agohige
Tauren Shaman Lv.79
Sí me pueden llegar a dar una mano, se los agradecería.
Saludos.

**Comment by UkfNonXtop** [comment]
Para este tipo de problemas lo mejor es colocar un "Ticket In-Game", lo puedes encontrar en "Asistencia al Cliente" (La interrogación roja). Deberás esperar a que un Mj vea tu problema y pueda tomar las medidas permanentes.

**Comment by Agohige** [comment]
Acabo de enviarlo como error, a ver que sucede...quedará en esperar.

**Comment by Monleon** [comment]
Arreglado
