### ISSUE TITLE
error en misión "el flujo incesante"

### ISSUE THREAD

**Issue by isma1977** [RoDNet/Bugtracker-Infinium-4.3.4#363]
no se puede destruir "animus de huesos de la plaga" necesario para completar la misión. http://es.wowhead.com/quest=27161/el-flujo-incesante#screenshots

![wowscrnshot_071113_130202](https://f.cloud.github.com/assets/4950741/783529/8f4e7504-ea52-11e2-9a7b-681fc08060e6.jpg)
![wowscrnshot_071113_130430](https://f.cloud.github.com/assets/4950741/783532/9b0b2248-ea52-11e2-95c4-213ca0ffc3de.jpg)
![wowscrnshot_071113_130447](https://f.cloud.github.com/assets/4950741/783533/a07af280-ea52-11e2-90e3-bb6d24374d80.jpg)

**Comment by redneo** [comment]
arreglada
