### ISSUE TITLE
[Paladin Represion] Maestria: Mano de Luz

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3632]
Nombre: Maestria: Mano de Luz
ID:76672
Enlace:http://wow.freakz.ro/spells.php?spell=76672
Descripcion: Tu Veredicto del templario, golpe de cruzado y tormenta divina infligen un 17% de daño extra como daño sagrado. cada punto de maestria aumenta el daño un 2.1% extra.
Problema: No esta contando la maestria base, solo la maestria extra por punto

**Comment by Kiritoo** [comment]
Arreglada, falta compilar.
