### ISSUE TITLE
Problemas con el ZEPELÍN

### ISSUE THREAD

**Issue by YoSoyPlanB** [RoDNet/Bugtracker-Infinium-4.3.4#3634]
Cuando vas en zepelín desde Entrañas a Ogrimmar te quedas buggeado , te caes y mueres y no puedes salir de ahí y tienes que poner un ticket in game ( me acaba de pasar , me llamo LonelyWolf ) no se si a alguien más le pasa

**Comment by pokesun** [comment]
ayuda me paso lo mismo mi personaje se llama kratn pala nivel  36 ayudaaaaa

**Comment by Dekadencee** [comment]
Fixed
