### ISSUE TITLE
problemas con la misión "ya se que lo tuyo no es cavar"

### ISSUE THREAD

**Issue by isma1977** [RoDNet/Bugtracker-Infinium-4.3.4#364]
en esta misión no se puede encontrar el pnj http://es.wowhead.com/npc=44489#objective-of necesario para finalizar la misión http://es.wowhead.com/quest=26956/ya-se-que-lo-tuyo-no-es-cavar

![wowscrnshot_071113_133316](https://f.cloud.github.com/assets/4950741/783670/5b61dad0-ea55-11e2-91cc-572877964221.jpg)

**Comment by crowel** [comment]
Hola acabo de comprobarlo y si que funciona, se pueden matar los 3 npc objetivos de misión.
Cierro, un saludo.
