### ISSUE TITLE
[Mazmorras/Banda] Azjol Nerub

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#3644]
Mazmorra: http://es.wowhead.com/zone=4277
Fallo: al matar al primer boss Krik'thir el Vigía (http://es.wowhead.com/npc=28684), no se abre la puerta para seguir la mazmorra.
PD: esta también funcionaba bien en la wotlk xD

**Comment by nayan87** [comment]
Confirmo el problema, cosa rarisima porque no hace mucho funcionaba, este problema con puertas que no se abren tras iniciar un evento sucede también en las cámaras de piedra, de relampagos y en la mazmorra de stratholme en tierras de la peste, impidiendo la conclusión de todas ellas
