### ISSUE TITLE
[Picaro] Criticos a bajo nivel

### ISSUE THREAD

**Issue by Pesketonex** [RoDNet/Bugtracker-Infinium-4.3.4#3646]
Estando en sigilo y metiendo emboscada
golpes de 1k y criticos de 2k daño increible, los mob no pasan de 300 de HP

Edito: añado foto con el daño que deberia de tener.

Golpe siendo lvl 16:
![wowscrnshot_042514_230241](https://cloud.githubusercontent.com/assets/7409548/2806106/eb4366d2-ccc2-11e3-85c6-335fd7fad5a6.jpg)

Mi daño siendo nivel 19:

![wowscrnshot_042514_235224](https://cloud.githubusercontent.com/assets/7409548/2806171/149305dc-ccc4-11e3-8d8a-110c140a79f4.jpg)

**Comment by Kiritoo** [comment]
Arreglado.
