### ISSUE TITLE
[Sacerdote - Sagrado] Espíritu redentor 

### ISSUE THREAD

**Issue by nazuky** [RoDNet/Bugtracker-Infinium-4.3.4#3648]
Según los talentos, cada ves que un secerdote muere adquiere la forma de un ángel que le permite lanzar hechizos heal durante cierto tiempo sin coste y sin poder se atacado ( http://es.wowhead.com/spell=20711/espiritu-redentor ).
Pero la cosa es que en el server solo te convierte en dicho espíritu 1 ves, para que te vuelvas a convertir en el tienes que reloguear y volver a morir, lo cual hace que ese punto de talento "invertido" hay se vuelva prácticamente una perdida

**Comment by efectokoleos** [comment]
arreglado
