### ISSUE TITLE
[Items/Objetos] Huevo de Ala Abisal

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#3649]
Objeto: http://es.wowhead.com/object=185915
Fallo: no hay casi huevos, deberían respawnear en estos puntos, pero no lo hacen:

Huevos en la superficie:
69 64 / 71 63 / 68 60 / 67 61 / 67 92 / 68 95 / 65 85 / 68 82 / 78 83 / 66 91 / 65 84
72 87 / 77 86/ 63 83

Huevos bajo tierra en las minas:
68 85 / 74 87 / 73 89 / 64 87 / 75 88 / 69 88 / 65 87 / 75 87 / 71 81 / 67 82

**Comment by nayan87** [comment]
Los huevos no respawnean a la vez, salen unos 9 0 10 cada hora aproximadamente, y si no ves muchos seguramente sea porque los estoy farmeando yo, XDDD sorry, suerte¡¡

**Comment by juaks** [comment]
Pero es que siempre veo los dos mismos de la plataforma abisal, los de la zona de los orcos o no están nunca o "están usados". Si tú los encuentras entonces será casualidad que vaya cuando tú..

**Comment by Kiritoo** [comment]
Están 12 huevos  spawneados.
