### ISSUE TITLE
[Campo de batalla] Isla de la conquista

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#365]
Hola, reporto la siguiente bg.
Isla de la Conquista http://es.wowhead.com/zone=4710

Quiero reportar dos fallos de esta bg.
1ª tras empezar la bg la puerta esta abierta solo que llega un momento que la gente no puede salir y debe de haber un transportador que te saque fuera ya que mucha gente queda encerrada, a veces ocurre que la puerta directamente no se ve y puedes salir ( esto ya con la bg empezada )
![puerta 1](https://f.cloud.github.com/assets/3537253/783662/40e5ca68-ea55-11e2-9c0a-405138f1357f.jpg)
![puerta 2](https://f.cloud.github.com/assets/3537253/783666/48fd4eba-ea55-11e2-9536-320d2435e2b6.jpg)

2ª Cosa que quiero reportar son las catapultas, Catapulta: http://es.wowhead.com/npc=34793 
Las cuales cuando usas la habilidad para sartar por encima de la muralla te lanzan 3-4 metros por el aire y de extrañamente de seguido vuelves para atras quedando atrapado en la catapulta, dejando inservibles las mismas y solo pudiendo entrar derribando las puertas, añado imagen.
![catapulta 1](https://f.cloud.github.com/assets/3537253/783688/b43d5396-ea55-11e2-8f75-0172f1f410ec.jpg)
![catapulta 3](https://f.cloud.github.com/assets/3537253/783691/bbddb97e-ea55-11e2-9668-f78c4810a890.jpg)
![catapulta 2](https://f.cloud.github.com/assets/3537253/783693/c534b50e-ea55-11e2-83de-2201901a56ce.jpg)

En la primera imagen se me ve apuntando para lanzarme, en la segunda se me ve por los aires y en la tercera estoy de nuevo en la catapulta atascado jaja.

Esto son los fallos encontrados por ahora, un saludo.

**Comment by crowel** [comment]
Hola quería revivir este reporte ya que isla de conquista sigue abierta y jugandose, cuando es imposible de jugar.
El problema con las catapultas persiste ya que no se puede lanzar uno por encima de la puerta.

Catapulta http://es.wowhead.com/npc=34793

Lanzar spell=66218   http://es.wowhead.com/spell=66218
40 Energía Rango ilimitado
Instante
Lanza al conductor a la ubicación designada.

Lanzar spell=66251  http://es.wowhead.com/spell=66251
Rango ilimitado
Instante
Lanza al conductor a la ubicación designada.

Nose cual de estas dos spells es la que utiliza el vehiculo.

Un saludo.

**Comment by ghost** [comment]
Además, al entrar en un vehículo, al salir de la bg se te bugea la cámara y se te pone a distancia mínima, como si vieras todo en primera persona.

Respecto a lo que dice Crowel arriba, la spell de lanzar también te bugea y no puedes moverte ni salir de la catapulta en toda la bg hasta que la rompan.

Los telentransportadores de las bases tampoco funcionan, una vez cerradas las puertas tienes que salir saltando desde arriba o bugeando con traslación-cargar-abalanzarse etc.

**Comment by crowel** [comment]
Tras morir en la bandera del puerto aparezco muerto en el centro como se ve en está foto.
![wowscrnshot_080313_175426](https://f.cloud.github.com/assets/3537253/973151/5ae84f5e-061a-11e3-9f25-1630e435d383.jpg)

Al liberar veo que no hay angel cosa que creo que debería, si es así confirmarmelo.
Teniendo que ir andando la mitad de la bg a revivir en mi cuerpo, cosa que si un alianza me quita la insignia no tengo cuerpo donde revivir.
*EDITO: Se me olvido comentar que al darle a volver al cementerio me vuelve a la posición de la foto donde no hay angel de resurreción.

Está bg actualmente no esta jugable creo que se debería cerrar.

Saludos.

**Comment by crowel** [comment]
Aquí las fotos de lo que menciona Asman, los transportadores al usarlos te aparece el buffo como teletransportado pero te quedas dentro de la fortaleza.
![wowscrnshot_080713_212050](https://f.cloud.github.com/assets/3537253/974997/ae6a0474-066a-11e3-965a-1d58322dbd23.jpg)
![wowscrnshot_080713_212055](https://f.cloud.github.com/assets/3537253/974998/ae699318-066a-11e3-9fc2-36a141939ce0.jpg)

Quedando solo la opción de tirarse de una de las torres.

**Comment by searum** [comment]
fix
