### ISSUE TITLE
personaje atascado

### ISSUE THREAD

**Issue by shefora** [RoDNet/Bugtracker-Infinium-4.3.4#3656]
Hola. Estando en tierras altas crepusculares me meti en un barco y apareci en medio de la nada sin poder moverme. Estoy muerta en medio de no se sabe donde y sin poder regresar al cementerio ni nada. Necesito ayuda. Gracias por vuestra atención. Mi personaje atascado se llama Shefora.

**Comment by Monleon** [comment]
Para estas cosas mejor un ticket ingame, es más rápido.
