### ISSUE TITLE
[Errores Internos] Flotando sobre el agua

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#366]
Hola quiero reportar este cb.

Cuenca de Arathi http://es.wowhead.com/zone=3358

Por el cual pude ir caminando sobre el agua toda la bg sin tener buffos ni nada por el estilo, nose si esto lo ocurria a los demás o si solo pasa a veces pero es algo extraño ya que podia caminar por cualquier parte con agua de la bg, espero que me comenten si alguien más le ocurrio.

![wowscrnshot_071113_183356](https://f.cloud.github.com/assets/3537253/783727/5d51d89e-ea56-11e2-8516-ebe08c0a0d30.jpg)
![wowscrnshot_071113_184815](https://f.cloud.github.com/assets/3537253/783729/6523f516-ea56-11e2-8952-5b5c46ed4152.jpg)

Un saludo.

**Comment by crowel** [comment]
Confirmado no soy el único que camina sobre el agua.
Al parecer hablando con un amigo, el tambien puede.
Estabamos en la misma bg y yo le via como que caminaba pero a la vez se hundia y él lo mismo sobre mí.
Resulta que todos flotan sobre el agua.

![wowscrnshot_071213_214636](https://f.cloud.github.com/assets/3537253/791343/b0e27fa4-eb41-11e2-9814-e9fa2126f2e9.jpg)
![wowscrnshot_071213_215039](https://f.cloud.github.com/assets/3537253/791345/b1230c72-eb41-11e2-82e6-35d80f49b6d4.jpg)
![wowscrnshot_071213_215040](https://f.cloud.github.com/assets/3537253/791346/b128bfc8-eb41-11e2-9215-d4f107dc1988.jpg)
![wowscrnshot_071213_215118](https://f.cloud.github.com/assets/3537253/791351/cf581d7c-eb41-11e2-880a-558c1ce5af7a.jpg)

Saludos.

**Comment by crowel** [comment]
Mmm casi puedo asegurar, que esto de flotar sobre el agua, ocurre tras morir, al revivir el pj queda el aura o estado de flotar sobre el agua de cuando se está muerto, ya que segun pude ir comprobando día tras día, me parece que este es el problema y en bg se aprecia más al estar muriendo varias veces durante el transcurso de la misma ocurre esto de ir, caminando por el agua, seria de agradecer si @Dekadencee le pudieras echar un ojo a esto cuando tengas un momento, si hay manera de comprobar esto que digo.

Muchas gracias, un saludo.

**Comment by crowel** [comment]
Le he cambiado el tag y título si puedieras cambiarle el label sería de agradecer ya que no solo ocurre en bg como lo reportara de la primera vez sino que ocurre independientemente del momento.

Un saludo.

**Comment by crowel** [comment]
Confirmo el error ocurre tras liberar, queda algun tipo de aura de flotar sobre el agua, la misma que al morir.

Un saludo.

**Comment by ghost** [comment]
Sucede en cualquier bg (que tenga agua).

**Comment by crowel** [comment]
No solo en bg, por el mundo adelante ocurre igual, esto ocurre a veces tras morir, como si el aura de muerto de caminar sobre el agua se quedara activada, en bg se aprecia más porque se suele morir mas veces.

**Comment by searum** [comment]
fix
