### ISSUE TITLE
[Cazador] Especialización en malla

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3661]
Nombre: Especialización en malla (Pasivo)
Enlace:http://wow.freakz.ro/spells.php?spell=86538
Descripcion: Aumenta un 5% tu agilidad mientras llevas solo armadura de malla.
Problema: No funciona en absoluto. El cazador se mantiene sólo con la agilidad que le dan las piezas, más no hay el 5% de aumento al tener sólo malla equipado.

**Comment by F4NT4SM4** [comment]
creo que todas las especializaciones de armadura no estan dando el bonus
osea los tela no le esta dando el intelecto
los placas la fuerza o aguante depende de su talento

**Comment by Jhovanni** [comment]
No he podido probar la clase de cuero, la otra de malla, ni las de placas. En cuanto a tela hice pruebas mediante los personajes de un amigo.
Dichas clases no llevan Especialización, sino una habilidad pasiva independiente (Misticismo para sacerdotes, Hechicería para magos y así); he comprobado que si funciona, pues probando pieza por pieza se nota el cambio de intelecto.
Con las demás clases no tengo como probar.

**Comment by F4NT4SM4** [comment]
mmm conrazon ahora los telas estan de moda 
bueno los placas si me he dado cuenta que si

**Comment by Pegasu5** [comment]
Y ya hiciste pruebas Dragon?

**Comment by F4NT4SM4** [comment]
claro en mi war la especializacion en armas/fury deberia darme un 5% de fuerza
sume todo mi equipo+gemas+enchanter+fuerza base y no me esta dando los 5% de fuerza extra

**Comment by Pegasu5** [comment]
Bueno pues sí, lo confirmo ahora que tuve tiempo en la mañana lo probé y no me dio el bonus sumando todo lo que mencionaste me da el valor exacto sin el aumento por el bonus, cuando pueda compruebo con cuero y edito, faltaría chamán xd
