### ISSUE TITLE
[Misión] Una oportunidad de oro

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#3662]
Misión: http://es.wowhead.com/quest=26572
Fallo: al usar Cola de truenagarto anegado (http://es.wowhead.com/item=58958), te mata a ti en vez de a Pez de piedra dorado (http://es.wowhead.com/npc=43331)

**Comment by Dekadencee** [comment]
Repetido https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2180, seguimos desde aquí
