### ISSUE TITLE
El ojo de la Eternidad [Banda] [80]

### ISSUE THREAD

**Issue by gorr** [RoDNet/Bugtracker-Infinium-4.3.4#3663]
Hola, bueno hoy fui con unos amigos de la guild a este banda y nos encontramos que en la 3 fase por asi decirlo cuando toca montar a los dragones y matarlo no funciona correctamente las habilidades de los dragones están bug y no nos deja matarlo arréglenlo graciaas

**Comment by redneo** [comment]
Esto... creo que lo han matado recientemente varias veces e iba correctamente, pregunta por los canales a ver como lo hicieron.
