### ISSUE TITLE
[Item/Objeto] Escrito sobre joyas ardientes

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#3665]
Item: http://es.wowhead.com/item=71949
Fallo: no te descubre ninguna receta.

Me he gastado 4 moneditas que equivalen a 4 días..

**Comment by Kiritoo** [comment]
Ya reportado en https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/319
