### ISSUE TITLE
[Misión] Un viaje a obras asombrosas [13937]

### ISSUE THREAD

**Issue by RaulioWoW** [RoDNet/Bugtracker-Infinium-4.3.4#3666]
Misión: http://es.wowhead.com/quest=13937/un-viaje-a-obras-asombrosas#comments

Descripción: ¿Tenemos tiempo para una parada más? Hemos oído que Dalaran tiene una tienda de juguetes, pero nunca podemos ir. La maestra de huérfanos dice que demasiados huérfanos abarrotarían la tienda. ¿A lo mejor podemos ir, solo nosotros?

¿Nos das un zepelín de papel pequeño? Creo que hay en Obras Asombrosas de Dalaran. Siempre quisimos jugar con uno. ¿Nos tiras uno? 

Problema: El npc Jepetto Jugarreta (http://es.wowhead.com/npc=29478) no cuenta con el item Zepelín de papel pequeño (http://es.wowhead.com/item=46693) 
 necesaria para completar la misión. Solo tiene a la venta este otro item Juego de zepelín de papel (http://es.wowhead.com/item=34498), que no es el que corresponde para llevar acabo la misión . Un saludo :)

**Comment by Velcositro** [comment]
Acabo de hacer la misión así que al parecer ya está arreglado.

**Comment by RaulioWoW** [comment]
amigo eres de la horda? porque ahora aparce el item pero no se me cuenta la mision como realizada, como lo hiciste exactamente? soy de la ali, nose si tendra algo que ver, un saludo

**Comment by Velcositro** [comment]
Sí soy de la Horda. Solo tomé la misión de mi huérfano (el mismo que dices, el de Oráculo), compré el zepelín y se lo lancé al huérfano... inmediatamente me completó la misión.

PD: Me aparecían 2 misiones... pero eran la misma, puede que tenga algo que ver eso. Abandona la misión y vuelve a tomarla.

**Comment by RaulioWoW** [comment]
ok gracias, espero un mg lea esto y revise el de la alianza, porque no me toma como completada la mision

**Comment by ghost** [comment]
Añadido el item al npc de dalaran.
