### ISSUE TITLE
[Hechizo-Cazador]Vigorización

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3667]
Nombre: Vigorazión
Enlace: http://wow.freakz.ro/spells.php?spell=53253
Problema: Salta el beneficio de ganancia de enfoque debido a ataques automáticos críticos de la mascota, cuando debe ser sólo mediante ataques básicos críticos (Mordedura, Zarpa, etc)

**Comment by efectokoleos** [comment]
arreglado
