### ISSUE TITLE
[Misión][Evento: Semana de los niños] De vuelta al orfanato

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#3668]
Misión: http://es.wowhead.com/quest=13959
Bug: La completé y no me enviaron la Prole de Oráculo curiosa (http://es.wowhead.com/item=46545) al correo. La necesito para el logro Mira qué monada (http://es.wowhead.com/achievement=1792) que es el único que me falta para el metalogro Para los niños (http://es.wowhead.com/achievement=1793).

PD: Esperé 1 hora a ver si era que tardaba en llegar pero nada.

**Comment by Velcositro** [comment]
Aviso que puse un ticket en el juego y un GM me mandó por correo la mascota como debe ser, así que ya pude completar los logros.

**Comment by Monleon** [comment]
Cierro el ticket, ya se mandó la mascota a todo aquél que le correspondía. No obstanto si quedara alguien, que ponga un ticket para que se le pueda ser enviada.
