### ISSUE TITLE
[Campo de batalla] Playa de los Ancestros

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#367]
Hola la siguiente bg, Playa de los Ancestros http://es.wowhead.com/zone=4384
Presenta este fallo.

![wowscrnshot_071113_190709](https://f.cloud.github.com/assets/3537253/783742/a972447a-ea56-11e2-8354-cac096f6a90f.jpg)

Como se puede comprobar en la imagen arriba en " Fin de la ronda " el tiempo esta constantemente en 00:00 cosa que no deberia ser asi ya que un juego de Playa de los ancestros costa de 20:00 minutos de juego repartidos en 10 y 10 para cada equipo primero unos defienden y despues los otros.
Con esto del tiempo actual estando mal que ocurre, solo se juega una ronda y de esta manera la bg termina o pasando los 5 min por falta de jugadores o el equipo atacante llegando al castillo.

Esta bg está mal, un saludo.

**Comment by ghost** [comment]
- Los barcos que te llevan a la costa en el cambio de turno tampoco funcionan, apareces directamente en el agua y lejísimos del campo de batalla.
- Los pjs atraviesan las puertas.

Funcionalidad nula.

**Comment by searum** [comment]
bug visual
