### ISSUE TITLE
Variable Pulse Lightning Capacitor: Efecto Bug

### ISSUE THREAD

**Issue by Bichoculiao** [RoDNet/Bugtracker-Infinium-4.3.4#3670]
Condensador de relámpagos de pulso variable
Se liga al recogerlo
TrinketMiscellaneous
+406 Intelecto
Nivel requerido 85
Nivel de item 384
Equipar: You gain an Electrical Charge each time you cause a damaging spell critical strike, granting a chance to fire a Lightning Bolt for 984 damage per Electrical Charge accumulated. You cannot have more than 10 Electrical Charges and cannot gain one more often than once every 2.5 sec. 

El efecto electrical charge no aparece con criticos ni nada, simplemente esta el bonus de intelecto nada mas, aqui linkeo la habilidad de wowhead:

http://wowhead.com/spell=96887

espero lo puedan solucionar no se que otra informacion adicionar, se los dejo en sus manos, muchas gracias

**Comment by Pegasu5** [comment]
Que pasó bicho el mago pega poco? :P

**Comment by Bichoculiao** [comment]
no, que ese abalorio no funciona para que pege mas xD

**Comment by Monleon** [comment]
Seguimos de aqui https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3978
