### ISSUE TITLE
Migraciones automaticas

### ISSUE THREAD

**Issue by pedrotulua** [RoDNet/Bugtracker-Infinium-4.3.4#3671]
Vengo de un server 4.3.4, segun las migraciones automaticas se perderian partes del set, al migrar por ser lvl superior, pero migre 2 pjs y no me migro nada, ni siquiera las profesiones glifos monturas, como dice en la pagina, deseo que me aclaren mas detenidamente esto, ya que he probado el server y me ha gustado, y pienso que mas gente se vendra de mi antiguo server, solo quiero que me aclaren estos puntos, tambien migre un pj que tiene set sañoso y tampoco le migro nada

**Comment by F4NT4SM4** [comment]
ps yo tenia entendido que las migraciones estarian desactivada hasta el cambio de temporada que es pronto
supongo que no te migro nada por eso 

ahora el caso seria si podras migrar normalmente cuando este listo o ya no podras por haber migrado 2 que es el limite xD

**Comment by Dejaor** [comment]
Pedro soi del infernal /./ que tal es el server?

**Comment by Hielito** [comment]
pedro yo tambien me pasare a este server XD me canse del Infernalag

**Comment by Hielito** [comment]
Hice lo de Migrar pero dejo desnudo a mi pj T_T y mis profesiones estan a 525 pero se borro todo, tanto que me costo sacar la receta de la moto T_T

**Comment by Monleon** [comment]
Esperad un poco a que el nuevo sistema de migraciones esté implantado, que no falta ya mucho, y se os devolverá la opción de volver a migrar de nuevo.
