### ISSUE TITLE
hola URGENTE XD

### ISSUE THREAD

**Issue by HUNTERxEROS** [RoDNet/Bugtracker-Infinium-4.3.4#3672]
HOLA ME INSCRIVI EN SU PAGINA Y TODO PERO MI SERVER ESTA CAIDO COMO PUEDO MIGRAR LO QUE SI LA PAGINA AUN FUNCIONA Y AHI PUEDEN CHECAR MI PJ Y NIVEL AYUDA ES URGENTE GRACIAS

**Comment by Bichoculiao** [comment]
Mejor create un pJ lvl 1 toma la promocion, ya que las migraciones no estan funcionando bien, el pj lvl 1 no le subas lvl habla con un npc de negro que esta en todas las zonas iniciales y te hara lvl 85 y full set sanoso, solo es 1 vez x cuenta/ip que puedes hacer eso asike piensa bien que clase y raza buscas, suerte ;)
