### ISSUE TITLE
BANDA: Descenso de alanegra heroico (encuentro atramedes)

### ISSUE THREAD

**Issue by nayan87** [RoDNet/Bugtracker-Infinium-4.3.4#3674]
¿que ocurre?

El evento se inicia normalmente y la primera fase en tierra transcurre con normalidad, la primera fase aérea también transcurre con normalidad. El problema viene cuando atramedes vuelve  a tierra, en ese momento tanto el cómo parte de la banda atraviesan texturas, muriendo algunos miembros de la banda, otros en cambio son enviados a rasganorte o bien donde tienen su piedra de hogar.

¿que debría ocurrir?

La segunda fase en tierra debería transcurrir con normalidad, sin que el  boss ni los jugadores atraviesen texturas.

**Comment by Monleon** [comment]
Se ha reescrito entero, en normal y en heroico
