### ISSUE TITLE
Banda ciudadela de la corona de hielo (problema con el transportador de la plaga al trono helado)

### ISSUE THREAD

**Issue by nayan87** [RoDNet/Bugtracker-Infinium-4.3.4#3675]
¿que ocurre?

Una vez que han sido eliminados los 3 jefes principales de la ciudadela (reina de sangre, sindragosa y profesor putricio) Se nos permite subir al trono helado con el transportador de la plaga, para iniciar el evento del rey exanime (el cual funciona perfectamente). El problema viene al usar el transportador de la plaga, en ese momento algunos jugadores atraviesan texturas cayendo al vacío y muriendo.

¿que debería ocurrir?

Al usar el teletransporte debería dejarnos a toda la banda en el trono helado para iniciar el evento, debo recalcar el echo de que sólo algunos jugadores caen al vacío otros se quedan en el trono normalmente. Del mismo modo el transporte al resto de puntos de la banda funciona con total normalidad, el único punto de conflicto es el transporte al trono helado

**Comment by Dekadencee** [comment]
Fixed
