### ISSUE TITLE
Banda: Tierras del fuego (ragnaros)

### ISSUE THREAD

**Issue by nayan87** [RoDNet/Bugtracker-Infinium-4.3.4#3676]
¿que ocurre?

Fase intermedia (hijos de la llama), En primer lugar los elementales aparecen de forma indebida en la sala,, ya que deben aparecer a una distancia prudencial de donde se sitúa el sulfuras como sucede en la modalidad de 10 jugadores, se pueden deletear algunos de ellos (normalmente los que están más alejados del sulfuras) pero la posición erronea de algunos de los elementales provoca un wipe casi irremediable de la banda. Si a esto le sumamos que aparecen de forma súbita y salen corriendo a más velocidad de la que deben, tenemos como resultado un wipe casi instantaneo.

¿qué debería ocurrir?

En esta fase el sulfuras queda expuesto en un lado de la sala, a continuación parecen los hijos de la llama (8 si no me equivoco) que van creciendo durante unos pocos segundos en un punto estatico hasta su carga completa y a continuación salen en carrera hacia el sulfuras (cabe destacar que en el servidor la velocidad de carrera esta ligeramente aumentada pero si se les baja la vida se van frenando correctamente como ocurriría normalmente, como ya he comentado anteriormente se pueden matar a los que salen en una posición adecuada alejados del martillo sin problemas)

Os adjunto una guia  muy completa de este boss. Gracias una vez mas por vuestro tiempo
http://www.youtube.com/watch?v=Pbom7dlJrSM

**Comment by Kiritoo** [comment]
En el video que estas mostrando salen elementales a ambos lados.

**Comment by nayan87** [comment]
Cierto, gracias fixx, se me olvido modificar eso, quería hacer incapié en la distancia al martillo, disculpad el error

**Comment by nayan87** [comment]
me falta poner una foto de lo que ocurre en el server, a ver si puedo esta noche que tenemos raid, así veis mejor a que me refiero, también cabe destacar, que en alguna ocasión hijos de la llama con raices o congelados han continuado su avance llegando al martillo, eso es un error ya que una vez congelados o enraizados no deberían poder moverse

**Comment by Monleon** [comment]
Los hijos de la llama ya se detendrán al ser enraizados.
