### ISSUE TITLE
[MISION] tras las puertas del infierno

### ISSUE THREAD

**Issue by gerardo14** [RoDNet/Bugtracker-Infinium-4.3.4#3678]
esta mision forma parte de la cadena de la invasion a firelands y para sacar el hipogrifo llameante.
para este punto ya se deberia poder entrar al portal tal como dice en wow head:
http://es.wowhead.com/quest=29201/tras-las-puertas-del-infierno
pero al intentar entrar sale que "aun no puedes hacer eso"

**Comment by gerardo14** [comment]
solucionado :D ya hoy intente hacer la mision y todo bien aunque les falta es traducir las misiones a español (esmx) porque no hay ninguna en español y yo de los que les gusta leerlas para seguir la historia pero de resto todo bien

**Comment by Pegasu5** [comment]
Te recuerdo que el servidor es Español, y yo siendo latino, aunque tenga el juego en EsMx me conformo con que se pueda hacer las misiones xd
