### ISSUE TITLE
[DK] Presencia Profana

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3679]
ID: 48265
Según la descripción, debe aumentar un 10% la velocidad de ataque y un 10% la regeneración de runas. El problema es que el aumento del 10% de regeneración de runas lo que está haciendo actualmente es que tarde mas en regenerarse la runa, cuando debería hacer el efecto contrario, debería disminuirlo

**Comment by redneo** [comment]
Pregunta que tengo: Algún spell que aumente la velocidad de regeneración de runas que no sea presencia profana, las regenera bien o hace el efecto contrario?

**Comment by Drogoth2** [comment]
Solo es presencia profana la que esta haciendo el efecto contrario creo, las demas spells en frost aumentan la cele y por tanto disminuye la regeneracion de runa

**Comment by F4NT4SM4** [comment]
Precensia frost no deberia aumentar la velocidad de runa solo auemnta daño y el poder runico.
yo ya reporte esto antes... los 15% de regeneracion de runas esta en la precensia equivocada lo esta dando frost en ves de profano

**Comment by Drogoth2** [comment]
Pues claro que no, dragon estamos con la presencia profana no la presencia de frost xD, el bug de la presencia profana simplemente es que no esta bajando el tiempo de reutilizacion de runas, lo esta aumentando, la presencia de frost no esta dando nada de regeneracion de runas, solo aumenta la regeneracion de poder runico y el daño. La presencia frost no esta aumentando la velocidad de movimiento ni nada, no me digais bug que habia antes que ya estan arreglados jejeje

**Comment by F4NT4SM4** [comment]
por lo menos te fijaste? 
a lo que me refiero es que en ves de colocarle los 15% de regeneracion de runas a profano
se lo colocaron a escarcha cuando lo reporte anteriormente se equivocaron de id

precensia sangre asi tengo mi regeneracion de runa normalmente
![wowscrnshot_061014_054020](https://cloud.githubusercontent.com/assets/3101842/3228499/5d95eec0-f087-11e3-84f1-3d42b7d718e5.jpg)

ahora me coloco precensia escarcha y me esta aumentando la regeneracion de runa lo cual no deberia 
![wowscrnshot_061014_054024](https://cloud.githubusercontent.com/assets/3101842/3228504/73cf445c-f087-11e3-900c-a6ca57b74dd1.jpg)

**Comment by F4NT4SM4** [comment]
lo de velocidad de movimiento era por un talento me equivoque hay :s

**Comment by Drogoth2** [comment]
Es verdad dragon perdona no me habia dado cuenta, entonces ahora mismo la presencia de escarcha es presencia profana y des escarcha a la vez?

**Comment by sakuranobushi** [comment]
Este error se ha corregido en el reino de pruebas y debería reflejarse pronto en el resto.
