### ISSUE TITLE
[ Hunter > Disparo Arcano ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#368]
Esta spell tiene el daño un poco bajo.

http://es.wowhead.com/spell=3044

Fórmula: 100% Daño con arma a distancia + ( RAP*0.248)

![wowscrnshot_071113_201150](https://f.cloud.github.com/assets/2728817/783767/0b22659c-ea57-11e2-84fd-520e75acb548.jpg)

Está algo bajo, haciendo 10k de crítico cuando debería hacer 11-13k y de normal 4-5k cuando debería llegar hasta 6k

**Comment by searum** [comment]
fix
