### ISSUE TITLE
BUG CONTROLAS MASCOTA Y OTRO PROBLEMA...

### ISSUE THREAD

**Issue by HUNTERxEROS** [RoDNet/Bugtracker-Infinium-4.3.4#3680]
TENGO UN PROBLEMA CON EL PASIVO DE CONTROLAR MASCOTA ME PIDE IR A INSTRUCTOR PERO YA FUI A VARIOS Y DICE APRENDIDO AYUDA ESO...
SEGUNDO... MI JUEGO LO DESCARGUE DE OTRO LADO YA KE EL COMPRIMIDO DE REING NO SE TERMINA DE INSTALAR Y ME MARCA ERROR: EL PROBLEMA ES KE ME DA MUCHO LAG Y ME IMAGINO KE SE DEBE A KE TENGO EL JUEGO DE OTRO SEVER NO AVANZA  LA DESCARGA DEL JUEGO Y ME DA MUCHA LATENCIA SI PUEDEN REPARAR O CHECAR EL EJECUTABLE DE EL ARCHIVO GRACIAS....

**Comment by Monleon** [comment]
Respecto al pasivo de controlar mascota, pon un ticket ingame y deja tu pj online para que un MJ pueda enseñarte dicha spell.

Respecto al lag, comprueba que tus addons son de la 4.3.4 o prueba a utilizar este instalador https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/1360-instalador-cataclysm/
