### ISSUE TITLE
Sin facción en Tol Barad [No hay reputación]

### ISSUE THREAD

**Issue by obamakurosaki** [RoDNet/Bugtracker-Infinium-4.3.4#3681]
Hola buenas tardes, 

mi problema es simple, tengo dos personajes que no pueden aceptar misiones de la Península de Tol Barad. Los he pasado de la horda a la alianza y se han quedado en un estado de neutralidad tanto con la alianza como con la horda. Mis personajes se llaman Lendrik y Rubishbaj.

Un saludo y gracias.

**Comment by Monleon** [comment]
Ya te he respondido ingame
