### ISSUE TITLE
Hechizos de control de masas de las clases

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3685]
He estado revisando los hechizos de control de masas como miedo del brujo, aullido de terror, alarido psíquico o maleficio del chaman y similares.

Antes de decir nada, estas habilidades son capaces de absorber cierta cantidad de daño, por lo que te debería dar tiempo a poner los dots pero cualquier golpe directo debería eliminarlo (recalco lo del golpe directo). 

Actualmente lo que está sucediendo es que estas habilidades hacen lo que quieren, me explico, antes de entrar en detalles hay un problema común que ya he visto reiteradas veces. Estos hechizos no se van aunque un grupo te esté pegando continuadamente, lo que debería pasar es que al llegar a esa cantidad de daño se fuera, sin embargo, muchas veces te convierten en rana o te hechan alarido psíquico por ejemplo y mientras te pegan entre cuatro, te han quitado media vida antes de que el efecto se haya ido.

Recuerdo que cualquier daño directo no proveniente de dots debería eliminar el efecto ya sea del que lo lanza o de cualquier otro.

Ahora entro en detalles con cada uno de los fallos que he encontrado:

El primer fallo apreciable es Aullido de Terror (id 5484,  http://wow.freakz.ro/spells.php?spell=5484) no está soportando daño, es decir, cualquier cosa que se le haga lo disipa. Con 1 solo punto de daño se va el efecto.

Segundo Alarido Psíquico (id 8122, http://wow.freakz.ro/spells.php?spell=8122) está absorbiendo más daño del que debería, lo he estado probando con otro jugador y me da tiempo a poner pegatas (recuerdo que peste devoradora hace daño cuando se pone lo que hace que la absorción se reduzca) me da tiempo a canalizar entero una tortura mental (a la mitad de esto y contando con lo anterior ya debería disiparse) y a castear una explosión mental. También lo he probado solamente con explosión mental lo cual haría que el efecto se fuera ya que es daño directo y hay veces que lo aguanta cosa que no debería pasar.

Tercero Maleficio (51514, http://wow.freakz.ro/spells.php?spell=51514) está soportando todo el daño que se le haga.

Supongo que pasará lo mismo con la oveja del mago por lo que sería de agradecer que alguien lo mirara.

Un saludo

**Comment by Pegasu5** [comment]
Pedazo'eh post grachie :P

**Comment by Bichoculiao** [comment]
bueno, con la oveja del mago no pasa eso, asike no te preocupes, con maleficio lo he visto y solo se disipa cuando estas con poco hp y te golpean, por lo que tengo entendido es un % de vida actual, algo asi como el 2O% de tu vida, como bien funciona el fear, aunque te falto el pequeno detalle que al igual que los stuns usados consecutivamente, los fear deberian de actuar de la misma manera, lo que me refiero que cuando te usan 3 stun seguidos ya el cuarto te sale inmune, en cambio los fear te pueden usar hasta 5 y el secto salta inmune, es casi el doble y que ademas te cuentan el 2O% de vida total y no actual

**Comment by Monleon** [comment]
Actualmente funcionan todos correctamente. El daño limite es 10%, y com el rendimiento decreciente el 4º control de masas del mismo efecto, provoca inmune. Además al usarse quemadura de mana, sobre un jugador con el aura de alarido, la quemadura romperá el aura
