### ISSUE TITLE
error al logueo

### ISSUE THREAD

**Issue by alejandro200189** [RoDNet/Bugtracker-Infinium-4.3.4#3686]
Bueno a mi y mis amigos nos pasa que cuando nos saca el juego y estamos en montura entramos y queda super lento y si estas alto tienes que bajar a tierra desmontar y montar para que vuelva la velocidad de la montura nos paso en una mazmo y teníamos que volver al cuerpo y el espiritu en montura pero estaba lento y hasta es molesto que no podemos hacer nada, espero de su ayuda y también con el incidente que desloga a  cada rato y se pierde lo que se hace porque subiendo las profesiones me desloga y ya no tengo o que acabo de subir espero de su valiosa ayuda y gracias.

buen dia

**Comment by Kiritoo** [comment]
Arreglado.
