### ISSUE TITLE
[MISION] druidas de la garfa y las celadoras de las sombras

### ISSUE THREAD

**Issue by gerardo14** [RoDNet/Bugtracker-Infinium-4.3.4#3688]
http://es.wowhead.com/quest=29181
http://es.wowhead.com/quest=29214
cuando al fin ya se reunen las 150 marcas del arbol del mundo al ir a entregar dichas misiones no esta el npc correspondiente de ninguna de las dos misiones

**Comment by Kiritoo** [comment]
Asi es y no los pondremos hasta que esten reparadas las posteriores cadenas de misiones, saludos.
