### ISSUE TITLE
[Chamán] T12 - 2P bonus Healer (Marea de llamas)

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3689]
- ID: http://es.wowhead.com/spell=99190/item-shaman-t12-restoration-2p-bonus
- Descripción: Tu sanación periódica de Mareas Vivas tiene un 40% de probabilidad de restaurar un 1% de tu maná de base cada vez que sana a un objetivo.
- Problema: No funciona, debería saltar un buffito/spell llamado Marea de llamas regenerando lo antes dicho.
- Spell: http://es.wowhead.com/spell=99189

**Comment by Bichoculiao** [comment]
que pasa pegasus, se le seca el mana muy rapido a tu healer¿ xD

**Comment by Pegasu5** [comment]
Ese es set pve xDD el pvp va perfectamente para ganar unas arenitas :d

**Comment by Kiritoo** [comment]
Esto si funciona, si que regenera el mana y no, no debe saltar ningun buffo.

**Comment by gerardo14** [comment]
yo creo que no sirve uso y uso mareas vivas y en el registro de combate no sale algo como kyoraku gana tanto de de mana gracias a marea de llamas

![bug t12](https://cloud.githubusercontent.com/assets/7041817/3008277/1ac5b4f0-deb6-11e3-97ad-c01caeec449e.jpg)

**Comment by Pegasu5** [comment]
La spell Marea de llamas  que puse ahí, salta y te devuelve maná, presente como se presente debe de mostrarse en el registro, y no salta. es un porcentaje muy alto  ese 40%

**Comment by Kiritoo** [comment]
Lo revisaremos.

**Comment by redneo** [comment]
Funciona:

![wowscrnshot_051814_205715](https://cloud.githubusercontent.com/assets/1163425/3008483/6cc69fbe-debe-11e3-9a46-78f90ae92ba7.jpg)
![wowscrnshot_051814_205744](https://cloud.githubusercontent.com/assets/1163425/3008484/6f745fee-debe-11e3-8ce1-6113e6f45be5.jpg)

No tiene que poner bufo alguno, te da el maná directamente como se ve en las imagenes.
