### ISSUE TITLE
[ Hunter > Serpent Sting ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#369]
Picadura de serpiente 

http://es.wowhead.com/spell=1978

Esta spell tiene un daño demasiado elevado, haciendo 5-6k por tick cuando debe de realizar una media de 1.4k por tick

![wowscrnshot_071113_201103](https://f.cloud.github.com/assets/2728817/783799/ad30cb8a-ea57-11e2-8ce4-f00c2346efe7.jpg)

**Comment by searum** [comment]
fix

**Comment by crowel** [comment]
Hola queria comentar que esta pegando de menos ahora.
![wowscrnshot_071413_194227](https://f.cloud.github.com/assets/3537253/794613/f7ae2692-ecac-11e2-81de-34e07730b886.jpg)

Esta pegando un 30-40% de menos en este momento.

Grom tienes la versión antigua del DrD?, lo digo porque coeficientes y números de ticks no coinciden con el mio.
Yo baje el de la versión actual un saludo.
