### ISSUE TITLE
[Misión] Las Celadoras de las Sombras y Druidas de la Garfa (Frente de Magma)

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3691]
http://es.wowhead.com/quest=29214/las-celadoras-de-las-sombras
http://es.wowhead.com/quest=29181/druidas-de-la-garfa

Faltan los npcs a los que entregarles estas misiones, a los cuales hay que entregarles 150 Marcas del árbol del mundo para desbloquear a cada una de las facciones y poder continuar en el frente de magma.

**Comment by Monleon** [comment]
La parte de las celadoras ya está implementada
