### ISSUE TITLE
[Misión] La cumbre inhóspita (Frente de Magma)

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3698]
id: http://es.wowhead.com/quest=29205/la-cumbre-inhospita
En esta misión no funciona nada

**Comment by Kiritoo** [comment]
Vamos a ver estamos arreglando la zona al completo si llegais a una mision que no funciona pues toca esperar, no estar reportandolas una vez llegais a la que no funciona.
Sino hacemos una cosa, metemos la mision que no funciona en disables asi no se puede continuar hasta que este toda la cadena arreglada.
