### ISSUE TITLE
Talento [Contricción] Sacerdote disciplina

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#37]
El talento Contricción, de la rama disciplina:

http://old.wowhead.com/spell=81749  (no está actualizado al 4.3.4, en este parche también salta al utilizar Fuego sagrado, el resto de la descripción es correcta)

Debería curar un 100% si salta a cualquier otro personaje que no sea el propio sacerdote, sin embargo, esta curando en torno a un 60% del daño inflingido (o con Fuego sagrado, o con punición), independientemente de a quien cure. Además, en caso de conseguir un golpe crítico con punición o fuego sagrado, la curación por "Contricción" está ignorando el hecho de que la curación también debería ser crítica (es decir 1 punto de daño = 1 punto de curación).

El resto de talentos "hermanos" de Contricción, como son Evangelismo y Arcangel funcionan perfectamente.

**Comment by searum** [comment]
esta actualizado al 434, lo acabo de probar y va bien

**Comment by paellaencol** [comment]
Ups, creo que este fix no por desgracia no se ha podido implementar bien, sigue sucediendo lo mismo (los otros fixs del sacerdote que realizaste ya funcionan)

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/567

(aunque el reporte es de hace dos días, lo acabo de probar y sucede lo mismo)

Gracias.
