### ISSUE TITLE
[Campo de batalla] Errores generales

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#370]
Hola quiero comentar estos tres reportes, que precisamente ocurren en la mayoria de bgs que se estan jugando.

****El primer fallo es el siguiente.
![wowscrnshot_071113_191826](https://f.cloud.github.com/assets/3537253/783780/5493b7e4-ea57-11e2-90a5-8a509cd8143b.jpg)

Como se puede ver en la imagen, aunque realmente no se ve, un alianza guerrero al cual esta atacando Recklulz y él al guerrero no se puede ver no más que targetearlo.
Esto es muy incomodo sobre todo porque esto ocurre en ambas faciones, de repente vas a capturar una base en la cual no hay nadie, te pones a cojer la bandera y de repente te estan atacando una pet, la cual nadie esta presente, unas descargas de escarchas que salen de la nada y unos flechazos disparandolos desde otro lado y dices tu, ¿ y que hago?.
Espero que le puedan echar un ojo a esto ya que ocurre tanto en bgs como en arena y es algo muy fastidioso, algunos dicen que alejandose y volviendo se arregla y es asi pero solo fuera en el mundo, en bg y arenas no ocurre y mas cuando te pegan dos que no ves jeje.

****El Segundo reporte que queria hacer era si podrian ajustar un poco mas el numero de jugadores necesarios para jugar la bg ya que este día jugamos 5c5 y tras pasar los 5min se nos cierra el campo de batalla.
Si pudieran echarle un vistazo al Campo de batalla aleatorio se agradeceria.

****El tercero la velocidad al estar en fantasma tras morir es de un 200% cosa que no me parece correcta, corregirme si me equivoco porfavor.

Un saludo.

**Comment by Dekadencee** [comment]
El bug que comentas de la invisibilidad es un error interno del emulador que he comentado en otro issue, se que es realmente molesto, y mas aún molesto de averiguar que lo está provocando, estamos en ello pero aún no hemos encontrado la solución adecuada.

Respecto al numero de jugadores necesarios para las bgs vamos a bajarlo un poco si en lo que crece la media de jugadores online.

La velocidad tengo entendido que es así en cataclysm con el fín de que al ir a recuperar tu cuerpo no se te vaya la vida en ello xD

**Comment by crowel** [comment]
Gracias dekadence por las respuestas^^
¿Quieres que cierre el issue o esperamos a solucionar el error del emulador?
Un saludo.

**Comment by efectokoleos** [comment]
ya que el error de la visibilidad esta arreglado cierro xd
