### ISSUE TITLE
Mago (maestría en fuego y DOTs)

### ISSUE THREAD

**Issue by nayan87** [RoDNet/Bugtracker-Infinium-4.3.4#3701]
Buenas noches, desde hace algunas semanas he notado que el daño del mago ha bajado considerablemente tanto a un solo objetivo como a múltiples. Llevo usando el mago fuego desde que entré al servidor y desde la LK. En anteriores post se comentó que la maestría en fuego estaba multiplicada x2 (cosa que pudimos comprobar todos ya que con un nivel de equipo 359 se llegaban a hacer mas de 35kDPS a un sólo objetivo y más de 80kDPS en multitarget).

Según las pruebas que he podido hacer  hasta el momento en un sólo objetivo y tras mucho rato usando todos los burst con un equipo de nivel 378 y todos los caps de equipo bien puesto no se pasa de 14-15kDPS, en multitarget es aún peor ya que en ocasiones los DOTs  no pasan de un enemigo a otro usando la explosión de fuego con el talento de impacto llegando a unos muy pobres 20kDPS (a veces pasan los DOTS pero no se mantienen en el objetivo).

Si alguien pudiese echarle un vistacillo estaría bien, lo normal con un nivel de equipo 378 a un objetivo solo estaría en torno a los 20-21kDPS sin forzar mucho la rotación, pero sobre todo habría que mirar los DOTs que no se mantienen en multitarget  o bien no pasan del objetivo principal a los secundarios en algunas ocasiones al usar  explosión de fuego.

Gracias por vuestro tiempo

**Comment by redneo** [comment]
Si me dices de mirar algun talento, spell en concreto lo puedo hacer, pero mirar todos los spells de mago fire uno por uno....

**Comment by Bichoculiao** [comment]
yo soy mago de fuego y siempre salgo primero en dps a 1 target hago casi 2Ok y a mas de 3 hago minimo 3Ok y no estoy full 378, quizas te falta mejorar la rotacion y build campeon ;)

**Comment by Monleon** [comment]
Arreglado en https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3761
