### ISSUE TITLE
[NPC] Echeyakee

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#3705]
NPC: http://es.wowhead.com/npc=3475
Descripción: se debe invocar con Cuerno de Echeyakee (http://es.wowhead.com/item=10327)
Fallo: no es necesario invocarle, y además de eso, hay dos.
Están en las coordenadas 45.0, 45.47, separados por pocos metros.

**Comment by redneo** [comment]
Arreglado, ya no hay ninguno, y ya se invoca con el cuerno. Cuidado que esta escondido!
