### ISSUE TITLE
[Pjs 85]

### ISSUE THREAD

**Issue by Imperius03** [RoDNet/Bugtracker-Infinium-4.3.4#3708]
El problema es el siguiente, muchos pjs que subieron a nivel 85, más o menos hace un mes o dos meses, de la horda, no pueden atacar a los mob de Tierras Altas Crepusculares.

Adjuno la img.

[img=http://k34.kn3.net/F/9/6/5/F/E/B93.jpg]

De antemano muchas gracias por su colaboración.

**Comment by Monleon** [comment]
Te comento, a varios jugadores de la alianza les ha sucedido lo mismo pero ellos no pueden atacar a npcs del clan Faucedraco. Sin embargo después de ir a la barra de reputaciones del personaje y marcar al clan Faucedraco (en tu caso seria el clan Martillo Salvaje) como "en guerra", ya han podido atacarles.

Puedes confirmarmelo?

**Comment by juaks** [comment]
Buena idea, pero no me sale en reputaciones el clan Martillo Salvaje

**Comment by Monleon** [comment]
Comprobado, poneis un ticket y que un mj os ponga en odiado la reputación de la facción contraria.
