### ISSUE TITLE
[ Hunter > Explosive Trap ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#371]
Trampa explosiva; 
http://es.wowhead.com/spell=13813

![wowscrnshot_071113_201301](https://f.cloud.github.com/assets/2728817/783819/2a8720e8-ea58-11e2-8c83-6587b8ee96ed.jpg)

Esta spell tiene el daño ridículo xD, debiendo hacer 1k de crítico, realiza 59p.

**Comment by Dekadencee** [comment]
Pero de donde sacas esos valores Jetto? xq yo veo que la media de critico que tiene que hacer es 344 segun el DrDamage :/

**Comment by DatJetto** [comment]
Para esta spell no tienes que fijarte en Media y Media crítica, sino en DoT Ticks, que marca 8 ticks de  651 y en el caso de ser crítico 1006.

**Comment by DatJetto** [comment]
Fixed.
