### ISSUE TITLE
Pestilencia

### ISSUE THREAD

**Issue by jammakuko** [RoDNet/Bugtracker-Infinium-4.3.4#3711]
Pestilencia de DK no es visible al lanzarse, propaga las enfermedades pero no se ve... algo molesto en pvp y pve por no ver visualmente hasta donde lleva la infeccion.

**Comment by redneo** [comment]
Ya sale como el caster tira algo a los objetivos cercanos, creo que tendria que ser el objetivo el que tendria que hacerlo, pero al menos asi lo ves.

Un saludo.

**Comment by F4NT4SM4** [comment]
bueno ahora todas las enfermeades del dk muestra eso visualemente y solo deberia de ser con 
pestilencia :50842
los dk frost explosion aullante se ven cientos de esas weas por la enfermedad de escarcha :P
