### ISSUE TITLE
Npc con el bug "evadir"

### ISSUE THREAD

**Issue by jammakuko** [RoDNet/Bugtracker-Infinium-4.3.4#3713]
en mi corto tiempo de leveo en este server me he dado cuenta que si un npc, sea mob, o guardia... lo que sea, va a por un objetivo, y de camino a el, se muere dicho objetivo, el mob en cuestion termina el trayecto y se queda parado evadiendo todo ataque... eso es muy molesto sobretodo en las misiones de wargen que le pegas un cañonazo a la multitud y aparecen 20 evadiendo todo.

**Comment by Dekadencee** [comment]
Posible fix implementado tras la siguiente compilación, si el error permanece por favor abrir un nuevo issue.
