### ISSUE TITLE
ayuda urgente personaje atascado

### ISSUE THREAD

**Issue by HUNTERxEROS** [RoDNet/Bugtracker-Infinium-4.3.4#3714]
me subi a un barco en fauce draco y no puedo revivir ni usar atascado que puedo hacer ????? ya envietickets ingame y no reponden

**Comment by Monleon** [comment]
Esto ya está más que resuelto, pon un ticket ingame a la próxima, que en cuanto se conecte un mj te lo soluciona, que dentro del juego es mucho más sencillo que lo lea, que no aquí.
