### ISSUE TITLE
[MAZMORRA] oculus

### ISSUE THREAD

**Issue by nayan87** [RoDNet/Bugtracker-Infinium-4.3.4#3716]
Ultimo boss guardian de ley Eregos, desparece en mitad del combate en algunas ocasiones y no reaparece, otras veces cae por las texturas y tarda mucho en volver a subir.

**Comment by redneo** [comment]
Creo que esta arreglado, al menos en dificultad heroica, pruebalo en ambas y me dices.

Por otra parte, creo que los dragones, iran más rapido.

**Comment by nayan87** [comment]
gracias una vez mas red¡
