### ISSUE TITLE
[Chamán Elemental] Retroacción

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3718]
IDs rangos 1, 2 y 3: 86183, 86184 y 86185

Descripción: Tu descarga de relámpagos y cadena de relámpagos "421" reducen el tiempo de reutilización restante de maestría elemental "16166" en (1/2/3) seg.

Problema: con cadena de relámpagos está reduciendo el tiempo de maestría elemental mucho más si golpea a 2, o 3 objetivos. Cuando debería reducir sólo una vez, independientemente del número de objetivos golpeados.

**Comment by redneo** [comment]
Lo he puesto, hasta que solucione el problema, que salte solo con descarga de relampagos, no saltando con cadena de relampagos.
