### ISSUE TITLE
[Mazmorra] Guarida de Maghteridon

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#372]
Buenas.
Quería reportar que el jefe Magtheridon (http://es.wowhead.com/npc=17257) de Guarida de Magtheridon (http://es.wowhead.com/zone=3836) pasados 2 minutos de combate, crashea el server.
Gracias y disculpen las molestias ocasionadas.
Saludos.

**Comment by searum** [comment]
fix
