### ISSUE TITLE
personaje atascado

### ISSUE THREAD

**Issue by jesusblack** [RoDNet/Bugtracker-Infinium-4.3.4#3721]
buenas.....

mi personaje ha quedado atascado y no puedo revivir ni recuperarlo, por favor ayúdenme.....la cosa sucedió así: yo estaba volando por "Altas Tierras Crepusculares (zona de cataclism, situada al lado de los humedales)" y me monte en un zeppeling que estaba pasando por allí, ese zeppeling se transporto y aparecí en medio de la nada cayendo sobre el agua cerca de "Tierras Fantasma", hacia el mar del lado derecho del mapa. Lógicamente morí, y aparezco allí mismo, mas no puedo revivir, teletransportarme a ningún cementerio cercano ni nada....auxilio porfavor!

**Comment by nayan87** [comment]
jesus más fácil si pones el ticket ingame, lo leeran más rapido que por aqui, suerte¡

**Comment by jesusblack** [comment]
como hago eso amigo, explícame pórfa!

**Comment by Monleon** [comment]
Por lo menos dinos el nombre de tu pj, que no lo podemos adivinar. 
Por cierto, el chat ingame es /join Reignofdarkness

**Comment by jesusblack** [comment]
el nombre de mi personaje es "chamitox" y ya hablare dentro del juego gracias
