### ISSUE TITLE
[Druida equilibrio] Gracia de la naturaleza

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#3724]
Rango 3: 61346

Descripción: Al utilizar enjambre insectos "5570", fuego lunar "8921" y recrecimiento "8936"; consigues el buff "Gracia de la naturaleza" "16886", el cual dura 15segundos con 1minuto de cd interno. (hasta aquí va perfecto)

Problema: Sin embargo, al entrar en estado de eclipse (lunar, o solar) el cd interno se debería reiniciar, haciendo que el próximo spell 5570, 8921, o 8936, vuelvan a dar el buffo "16886"

**Comment by efectokoleos** [comment]
arreglado

**Comment by Monleon** [comment]
Reabro, ahora está saltando siempre
