### ISSUE TITLE
[Misión] Nocturno, Boss de Karazhan

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3727]
id: http://es.wowhead.com/quest=9644/nocturno

El problema es que no se puede activar la urna que está en el Bancal del Maestro y por lo tanto no aparece el boss.

**Comment by nayan87** [comment]
debes hacer la mision socio, si no no podras activarlo, tiene una cadena propia que se activa a la entrada de kharazan, uno de los magos que hay es el que te la da, no es complicada pero lleva su tiempo
