### ISSUE TITLE
[ Hunter > Pet > Basic Attack ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#373]
![wowscrnshot_071113_204254](https://f.cloud.github.com/assets/2728817/783922/ff04cf68-ea59-11e2-8602-90df3e446a97.jpg)

Los ataques básicos de la pet están realizando un overdamage excesivo, dando 8k de normal y 16k de crítico, cuando apenas deberian dar 2-3k  4-6k de crítico.

Mordedura: http://es.wowhead.com/spell=17253
Zarpa: http://es.wowhead.com/spell=16827
Bofetada: http://es.wowhead.com/spell=49966

**Comment by Dekadencee** [comment]
Mordedura: Inflinge 536 puntos de daño (donde salen los 2-3k?)
Zarpa: Inflinge 536 puntos de daño (donde salen los 2-3k?)
Bofetada: Inflinge 536 puntos de daño (donde salen los 2-3k?)

(Todo esto de las descripciones del WoW, zarpa esta pegando over, mordedura menos de lo que dice y bofetada regular)

**Comment by DatJetto** [comment]
Yo lo he probado con Mordedura, que es la spell de mi araña, como no puedo capturar otras pues no los he probado, pero se supone que todas deben llevar la misma fórmula.

La mascota coge un % de AP del cazador, quizá coja demasiado y por eso el daño se dispara, los 2-3k son orientativos, es más o menos lo que deben hacer esos ataques al palito.

**Comment by ghost** [comment]
Aquí se puede ver más o menos los stats que toma la pet del cazador http://www.wowwiki.com/Hunter_pet

> Pets receive attribute bonuses at 15% of their master's/mistress' stats:
> 
>    1 ranged attack power gives the pet 0.22 AP and 0.1287 spell damage (0.338 AP and 0.18 spell damage with 2/2 Wild Hunt).
>    1 stamina gives 0.4 stamina untalented (erroneously reported as 0.3 stamina in the Hunter's stamina tooltip), or 0.63 stamina with 2/2 Wild Hunt). Hunter pets do not gain any health from their base stamina, and gain 10.5 health for each additional point of stamina (10 health per additional stamina before the inherent pet health bonus, which was standardized to 5% in Patch 3.1.0).
>    1 resistance gives 0.4 resistance.
>    1 armor gives 0.35 armor.
>    1 point of spell penetration gives 1 point of spell penetration to your pet.[2]
>    1 point of resilience gives 1 point of resilience rating to your pet as of Patch 3.3.0. Previously, it was 0.4 >points of resilience per 1 point.[3] 

Pd: no sé que tan acertada sea la información para esta versión.

**Comment by DatJetto** [comment]
Fix.
