### ISSUE TITLE
El Crisol de Matanza: ¿El mortal Faucedraco!

### ISSUE THREAD

**Issue by srmalson** [RoDNet/Bugtracker-Infinium-4.3.4#3732]
En la segunda pelea del Crisol. el personaje Faucedraco aparece, te ataca, pero a la hora de atacarle te aparece el mensaje de objetivo no valido, no se puede atacar con lo que no se puede finalizar la mision y continuar.

**Comment by nayan87** [comment]
llevate a alguno que si pueda pegarle, al ser un picotormenta si tienes el problema de no poder atacarlos (le pasa a mucha gente) a este miniboss tampoco podras sacurdirle de lo lindo

**Comment by Monleon** [comment]
Echale un vistazo a mi respuesta aquihttps://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3708
