### ISSUE TITLE
[DK] Atracción Letal+Animacion 

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3734]
Nombre: Atraccion Letal
ID: http://es.wowhead.com/spell=49576
Descripcion: Reune Energia Profana que rodea y vincula toda materia, lo que acerca al objetivo hacia el caballero de la muerte y obliga al enemigo a atacar al caballero de la muerte durante 3s

Notas del parche 4.0.6:Atracción letal requiere un radio mínimo de 8 metros contra otros jugadores, pero esto no figuraba en la descripción. La descripción se ha actualizado.

Problema: Para usar atraccion letal contra jugadores requiere un radio minimo de 8 metros esto no esta sucediendo puedo usarla estando menos de 8 metros y aprovecharse para cortar cast

2do Problema: La atraccion letal tiene una nueva animacion en cataclysm y al parecer es atrae al objetivo mas rapido. dejo un video corto de como deberia ser por si no me entiende. http://youtu.be/W5qv0EEXow8?t=10s

**Comment by redneo** [comment]
Arreglado lo de la distancia
