### ISSUE TITLE
[Guerrero] Golpe Automatico Ira bug

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3735]
Nombre: Ira de golpes automaticos criticos 
Descripcion: Si el ataque es un golpe crítico, generará 200% mas de de ira de lo que daria un golpe normal. 
Problema: Actualmente la ira normal esta dando 24 de ira o 30 de ira con talento, un golpe critico deberia de dar 48 de ira o 60 con talento esto no esta sucediendo sigue dando ira el critico como si fuera normal y nos deja a los war muy excaso de ira.
dependemos de ira rabiosa y aguantar golpes para generar ira y contra heler 0 ira...

**Comment by Kiritoo** [comment]
Arreglado.
