### ISSUE TITLE
[Guerrero] Derribar

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3736]
Nombre: Derribar
ID: 85388
Descripcion: Derriba al objetivo y lo aturde 5s
Problema: tras usar cargar el stun se convierte en 2s y no deberia se supone que cargar no tiene dr en sus efectos de aturdimiento

**Comment by Kiritoo** [comment]
Fix, falta compilar.
El fallo estaba en cargar.

**Comment by Kiritoo** [comment]
Pregunta donde pone que cargar no tenga dr en sus efectos de aturdimiento, segun veo notas del oficial unicamente es cargar con interceptar.

**Comment by Kiritoo** [comment]
Lo digo porque comparta DR derribar con cargar y interceptar, no veo en ningun lado que ponga que no tenga que hacerlo.

**Comment by F4NT4SM4** [comment]
ya esta bien a si era cargar

**Comment by Kiritoo** [comment]
A ver no me refiero a eso me refiero, donde pone que cargar y derribar no tengan dr una de la otra.
De donde sacaste esa información.

**Comment by F4NT4SM4** [comment]
Notas del parche 4.1 http://eu.battle.net/wow/es/game/patch-notes/4-1-0#warriors
Cargar e Interceptar ya no tienen rendimiento decreciente en sus efectos de aturdimiento. 
como sus efectos de aturdimiento no tienen dr no afecta a los otros stun

**Comment by Kiritoo** [comment]
Yo entiendo  que es entre ellos, no con los demas stunts.

**Comment by F4NT4SM4** [comment]
sus efectos de aturdimientos no estan en la categoria de stun y como no cuentan como stun no afecta el dr de otros

**Comment by F4NT4SM4** [comment]
tambien coloco lo que comentan en los foro de blizzard 
antes si tenia rendimiento decreciente al principio de cata pero desde 4,1 le quitaron el DR 
¨la carga tendra un stun de 1,5 segundos como ha tenido toda la vida, SIN DR, que parece que no os dais cuenta, esto significa que volverá el derribar al target, ya que al no activar DR el target se lo comerá entero, 5 segundos de barra libre de ostias¨
http://eu.battle.net/wow/es/forum/topic/1999601657  comentario #8

**Comment by F4NT4SM4** [comment]
ademas cargar e interceptar comparter tiempo de reutilizacion en armas 
que sentido tendria lo de DR entre ellos si de todas forma tienen la reutilizacion junta
