### ISSUE TITLE
[Guerrero] Seccionar mejorado

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3737]
Nombre: Seccionar mejorado
ID del debuff que inmoviliza: 23694
ID De talentos: 12289/12668
ID Seccionar: 1715
Enlace: http://wow.freakz.ro/spells.php?spell=12668
Descripcion: al volver aplicar seccionar inmoviliza al objetivo 5s.
 Problema: Solo deberia de activarse el talento si se tiene seccionar en el objetivo (1715)

**Comment by efectokoleos** [comment]
Arreglado en el core nuevo, no daremos mas soporte al actual
