### ISSUE TITLE
AURA EN LA BASE ALI o un glich - CUMBRES GEMELAS - BG

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.3.4#374]
![wowscrnshot_071113_130235](https://f.cloud.github.com/assets/2059256/784521/17ec20a0-ea67-11e2-9645-46a73336bf26.jpg)
![wowscrnshot_071113_130238](https://f.cloud.github.com/assets/2059256/784524/29663604-ea67-11e2-96a1-64a2a6ba82bb.jpg)
![wowscrnshot_071113_130543](https://f.cloud.github.com/assets/2059256/784530/3c633482-ea67-11e2-93e8-124674e59dfc.jpg)
![wowscrnshot_071113_131314](https://f.cloud.github.com/assets/2059256/784534/4d26f8bc-ea67-11e2-95bb-f8e71162bc51.jpg)

OK ASI COMO LAS PUSE EN ORDEN sucedio lo siguiente....

> al principio de la BG logre ver a todos los HORDAS a la mitad del campo de batalla, luego regrese a la base, y me comenzaron a golpear como si hubiera sido el mismo demonio.... **PERO NO MIRE A NADIE**.

Bien al principio in-game crei e incluso lo dije en el chat que habia un AURA en la base de los ALIS, por que cuando sali de la base comenze a ver a los hordas de nuevo.

> Redneo si sigues ahi? no se si te recuerdas lo que pasa en la zona donde estan los Hijos de Hodir. =)
> https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1426

Bien ahora vean esta otra imagen.

![wowscrnshot_071113_131655](https://f.cloud.github.com/assets/2059256/784555/0007ab2a-ea68-11e2-92ba-a9b1b83d54c5.jpg)

En esta ultima imagen aunque no se logra apreciar el LOGOTIPO de los hordas era un horda que cuando hize click sobre el para tomarle la foto desaparecio o se desconecto del juego o simplemente se salio de la BG.

> esta ultima imagen la tome en la base ali, y me sorprendio asi derrepente verlo.

---

**RESUMEN:**

1 O es un AURA que esta en la base ali que impide ver a los hordas.
2 O es un glich, o exploid de alguna habilidad, talento, buff, debuff de algun horda que nos impide verlos.

---

> almenos a mi me dejo con dudas la ultima imagen para concluir que sea un aura en la base, lo que nos impide verlos. HACK!!! lol hihihi.

**Comment by SherBlader** [comment]
Creo que ese horda era yo, y estaba diciendo por el genera (/7) que se salieran de esa bg y apuntaran a garganta grito de guerra porque esa si funcionaba bien.
(aveces me pasa que no puedo ver alianzas, y este caso no pasa en todas las bgs asi que no creo que sea un hack)

**Comment by ghost** [comment]
Es un bug que algunas veces no puedes ver otros pjs... dijeron que estaban tratando de solucionarlo, a mi ya me paso una bg que un pala se puso a perseguirme todo el tiempo y ni lo podía ver.

**Comment by SherBlader** [comment]
Esta bg deberia ser cerrada, no se puede hacer nada ahi, solo abandonar

**Comment by WarSxNes** [comment]
lol **SherBlader@:** lo de HACK solo era un broma xD por eso lo puse con ""

> letras mas opacas.

Y si se pueden ver unos a otros, mientras no entres a la base. _(no se si me explico)_ cuando digo **"aura en la base"**.

---

Pero sigo pensando que es un "aura de zona" (llamemoslo asi).

> Esto sucede creo de esta forma: Todos sabemos que los GMs (game masters) pueden ver cosas que nosotros no podemos ver. _**En algunos casos se interpretan graficamente como los famosos diablitos o demonios roca**_. Les cuento una anecdota. Hace como 2 años en WorldHeroes paso que en Terrallente habia una cueva donde entrabas y no salias vivo. Al morir y liberar, podias ver miles de NPC enemigos tanto para H como A dentro de la cueva. Los GMs en alquel entonces no entendian lo sucedido, pues ello no lograban ver nada, y no fue sino asta que uno de ellos entro con una cuenta NO de nivel 2 _(si no mal recuerdo hay 3 diferentes niveles de GMs)_ que logro ver a todos los NPCs que de alguna forma estaban ocultos bajo una especia de aura y solo asi pudieron retirarlos de la cueva.

Bueno, lo ultimo solo es un comentario no le presten atencion. Pero si quieren tomenlo de ejemplo. _(igual que el link que deje arriba ^)_

> Y que por cierto RedNeo le llama "fase"

**Comment by Dekadencee** [comment]
Si es cierto que existen las fases las cuales un aura puede modificar, pero es extraño que un personaje pueda atacar a otro de una fase distinta, te pongo un ejemplo, si 2 raids estais en ICC, ambos grupos estais en el mismo mapa, pero diferente fase, ni podeis veros ni interactuar de ninguna manera entre vosotros a no ser que alguien tenga la phase mask entera, entonces puede ver e interactuar con todas las fases a la vez (que es la que tenemos los GMs)

Pero también es cierto que el emulador presenta el siguiente bug, para el emulador y el cliente, todos los players sois objetos, al igual que los npcs, gameobjects, vehiculos, transportes... estos objetos se van insertando en la memoria de vuestro juego a medida que os vais encontrando con ellos a través de mensajes que envia el servidor a vuestros clientes, normalmente sin problema, pero existen casos aún que desconocemos de donde viene (a nivel de codigo todo parece estar correcto) que el cliente de uno de los jugadores, recibe el mensaje mal o hay algo ilógico en este mensaje, y produce un error global en el cliente de dicho personaje que hace que no pueda ver nada hasta reloguear.

Por lo que dices, si es cierto que tiene toda la pinta de ser el aura, ya que si fuera el 2º bug no podrias ver nada ni dentro ni fuera de la BG hasta que cerraras el WoW y volvieras a abrirlo.

**Comment by lamaza** [comment]
La verdad no entendi mucho :/, parece cosa de GhostBusters. Ayuden al Moya para que su pj este limpio de auras y malos espiritus.

**Comment by ghost** [comment]
Eso se "soluciona" relogeando.

**Comment by WarSxNes** [comment]
En las imagenes que deje (arriba ^) muestro claramente,,,,, **dentro y fuera** de la base Ali.
- **Dentro de la base**: no ves a ningun horda, y parece que el mismo demonio te a poseido y acaba matandote.
  
  > Cuando estas adentro de la base Ali (no se si pasa lo mismo del lado horda) dejas de ver a toda la faccion contraria. PERO!!!!
- **Fuera de la base**: a mitad del campo de batalla (BG) ves a toda la horda. haciendo referencia que es un aura/fase/etc... o como sea que se llame. xD hihihi
  
  > Osea... solamente sales de la base Ali... Quiero decir, sales del alcanze de lo que podria ser un aura///fase///etc... y comienzas a ver a todos los jugadores de la faccion contraria SIN NESECIDAD DE RELOGUEAR ni nada.

---

NOTA: Arenas no tengo idea no hago arenas =) puede que en arenas si sea la solucion de reloguear... Pero repito no hago arenas...

**Comment by ghost** [comment]
Pero probaste relogeando? xd

**Comment by WarSxNes** [comment]
Ok.... si lo intento pasa lo siguente:

**Metodos que conozco y he provado:**
- usando el commando **/reload**
  
  > carga de nuevo la UI (user interface) pero no pasa nada; no hay ningun cambio.
- Cerrando secion
  
  > tengo que estar fuera de combate y esperar 20 segundos. Y luego me sale el debuff de DESERTOR por 10 minutos.
- Y si relogueo cerrando wow con Alt+F4 o click en la X en modo ventana
  
  > tambien me sale el debuff de Desertor por 10 minutos.

La unica forma que tengo para reloguear SIN que me aparesca el debuff de DESERTOR es usando el commando /reload,..... o que mi modem pierda coneccion para que no se detecte el "leaver" o como le llama? salir/abandono...

> Pero no se si eso mismo le pase a todos.... al menos a mi me marca el debuff con el icono del gatito :P por 10 minutos, y no puedo volver a entrar a BG asta que no pasen los 10 minutos.

---

Creo que el echo de reloguear es para refrescar la **Cache** no? (corrigeme si me equivoco) xD

> - si no te sale ningun debuff de DESERTOR entonces hay preferencia H-Gorda lol hihihi .... es una broma xD
> - pero eso si creo que no es correcto y tambien deberia de revisarse. (((bueno eso si eEeEssSs... (suponiendo) que deberia de ser asi)))
> 
> Ejemplo: Te imaginas usar una macro con el commando de /reload y que cuando estes a punto de morir lo usas y listo te salvas de morir xD estando en una BG o en Arenas..  hihihi (algo descarado no? xD )
> - bueno lo de Arenas (es mera supocicion) por que YO no hago arenas y no se si tambien exista el debuff de desertor.

**Preguntas:**
- Y tu cual de los tres metodos usas?
- Te sale el debuff de "desertor por 10 minutos"?

**Comment by ghost** [comment]
Yo uso alt+f4 y no me aparece el debuff de los 15 minutos, y se me "arregla" o.o, el comando /reload no creo que funcione porque solo es para recargar la interfaz.

**Comment by WarSxNes** [comment]
QQ... siempre hay preferencia horda lol hihihihi.... suertudote... nah es una broma xD
Raro no?

**Comment by ghost** [comment]
Si, raro.

**Comment by ghost** [comment]
Bueno, se supone que esto ya esta arreglado, @WarSxNes si te sucede vuelve a abrir otro reporte.
