### ISSUE TITLE
[Ingeniería] Muelles de sinapsis

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3740]
Nombre: Muelles de sinapsis
Enlace: http://es.wowhead.com/spell=82175/muelles-de-sinapsis
Problema: Ya reportado antes aquí https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3017 Pero ahora hay que reportar de nuevo porque el encantamiento no sirve. Cuando lo usas no hay aumento de estadística alguna. Ya puestos en componerlo sería genial si queda de una vez el asunto de que borra el encantamiento que ya se tiene en los guantes (explicado en el reporte del enlace linkeado), así queda bien todo.

**Comment by redneo** [comment]
Arreglada la parte de que de la stat.
