### ISSUE TITLE
[Objeto] Saco de gemas cinéreo

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#3741]
Objeto: http://es.wowhead.com/item=49294#contains
Fallo: al abrirlo no contiene ninguna gema nunca.

**Comment by nayan87** [comment]
A parte el tema de que sartharion no lotea el draco nunca cuando debería estar dándolo

**Comment by redneo** [comment]
Arreglados ambos fallos
