### ISSUE TITLE
[Paladin] Sello de Rectitud

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3742]
Nombre: Golpe Mortal
ID:20154
Enlace:http://wow.freakz.ro/spells.php?spell=20154
Descripcion: Fills the Paladin with holy spirit for 30 minutes, granting each melee attack $MWS \* (0.011 \* AP + 0.022 \* HOLY_SP) \* $ / 100 additional Holy damage. Only one Seal can be active on the Paladin at any one time
Problema: Tiene el daño muy elevado le hago 8k al dummy y segun dr,damage deberia hacer alrededor de 1k. 
Lo curisoso es que si activo un talento sello de mando el daño se normaliza y se supone que el talento deberia aumentar mas el daño

**Comment by redneo** [comment]
arreglado
