### ISSUE TITLE
npc (bestias) que no estan en monte hyjal

### ISSUE THREAD

**Issue by ezequielcn** [RoDNet/Bugtracker-Infinium-4.3.4#3743]
hola quería poner un listado de las bestias (domables) que hay en monte hyjal pero que no se encuentran en el server. teniendo en cuenta que recientemente agregaron a terrorpin y fue un éxito les paso las npc que faltan:
Ban'thalos: http://es.wowhead.com/npc=54320 es un búho fantasma
Magria: http://es.wowhead.com/npc=54319 un felino fantasma
Ankha; http://es.wowhead.com/npc=54318 un felino fantasma
Skarr; http://es.wowhead.com/npc=50815 un felino con cuerpo de piedra fundida (se encuentra en frente de magma)
Kirix; http://es.wowhead.com/npc=54323 una araña (se encuentra en frente de magma)
Bueno como mencione después del éxito que fue terrorpin me gustaría que agregaran estos npc harían muy felices a la comunidad de cazadores. desde ya muchas gracias

**Comment by Kiritoo** [comment]
Añadidos todos menos los dos de Frente de magma Skarr y Kirix que no se podrán ver hasta completar las cadenas de dentro del frente de magma en las cuales estamos trabajando.
Las demás bestias de hyjal ya estan disponibles con un respawn aproximado de 3 días y solo visibles una vez completada la cadena para poder atravesar el portal al frente de magma, saludos.
