### ISSUE TITLE
[Paladín] Comunión

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3746]
http://cata.openwow.com/spell=31876
No está aumentando el daño de la banda el 3% ni al paladin el 2% extra, pega igual con o sin ese talento.
Además efecto de reposición no lo está dando tampoco, lo unico que regenera mana es sentencia del audaz (89906) que es un talento pasivo del paladín reprensión que hace que regeneres un 25% del mana, pero sentencia no esta otorgando reposicion como dice el talento de comunión por ninguna parte.

**Comment by Monleon** [comment]
Otorga reposición perfectamente.

**Comment by Drogoth2** [comment]
Donde? porque yo lo unico que veo es el talento pasivo del paladin llamado sentecia del audaz, que es lo unico que da mana. Reposicion solo la esta otorgando el sello de perspicacia, y porque el sello tiene esa cualidad.

**Comment by Kiritoo** [comment]
Reposicion funciona correctamente, pone el aura de reposición durante 10 segundos.
Y también está añadiendo el daño a la banda y al paladín el 2% extra si quieres te lo demuestro cuando estes conectado, quiero comentar que no pone el icono del aura pero se ve como al aprender el talento añade el daño de arma.
