### ISSUE TITLE
[paladin] Inquisición

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3748]
ID: 84963
En repre hay un talento que aumenta la duracion de inquisicion un 200%, por lo tanto hace que dure 32segundos cuando tienes 3cargas, pues bien si tienes las tres cargas y salta propósito divino (86172), la duracion se va a 50seg:
![image](https://cloud.githubusercontent.com/assets/3939699/3279061/94f5c86e-f3e7-11e3-85ed-dee86a5752b2.png)

**Comment by Killswicht** [comment]
Vale,creo que no entendiste cuando te explique, aqui el problema no es inquisicion, es el proposito divino.El proposito divino esta actuando como una carga mas siempre, osea si no tienes ninguna y salta consigues los beneficios de una carga pero asi tambien si tienes 3 cargas y salta proposito tendras 4 cargas osea un inquisicion de 47 seg

**Comment by Killswicht** [comment]
Ese bug es algo  molesto por que no puedes tener la inquisicion siempre en 35 seg cuando salta proposito pero si tienes paciencia puedes beneficiarte de el :l

**Comment by Kiritoo** [comment]
Arreglado, pendiente de compilar.
