### ISSUE TITLE
Montones de mops en el Templo de la tierra 

### ISSUE THREAD

**Issue by Workiin** [RoDNet/Bugtracker-Infinium-4.3.4#375]
Cuando se llega al templo de la tierra lo reciben montones de bichos matandote de una vez , esta hasta Therazane pegando ahi 

![bug1](https://f.cloud.github.com/assets/4934379/785025/a5015c20-ea72-11e2-965f-a77aba0739c3.PNG)
![bug2](https://f.cloud.github.com/assets/4934379/785033/baf5a342-ea72-11e2-9c00-d0c8daae1138.PNG)
![bug3](https://f.cloud.github.com/assets/4934379/785041/d42bc49a-ea72-11e2-9337-cc5d9ebbbc09.PNG)

**Comment by redneo** [comment]
limpiado un poquito... cierra el ticket si te parece que ya hay suficientemente pocos
