### ISSUE TITLE
mascotas del cazador bug

### ISSUE THREAD

**Issue by alexiz123** [RoDNet/Bugtracker-Infinium-4.3.4#3750]
cuando abandono una pet para domar a otra solo desaparece y no me deja domar otra bestia tengo que desconectarme para que desaparezca completamente y cuando domo otra bestia pasa esto 
![wowscrnshot_061514_122647](https://cloud.githubusercontent.com/assets/7888540/3281523/b50b4568-f4b2-11e3-8207-2bbd6a595e34.jpg)
me sale que no tengo pet y tengo que reloguear otra ves ahora ya anda bien pero las habilidades especiales de las mascota no aparecen
![wowscrnshot_061514_123304](https://cloud.githubusercontent.com/assets/7888540/3281527/472452c8-f4b3-11e3-8283-f5cf37f8dd89.jpg)

**Comment by ErahUnderground** [comment]
Borrando caché se suele solucionar eso.

**Comment by Monleon** [comment]
Es abandonar pet, cerrar wow, borrar caché, y domesticar una nueva. Ya sé que puede ser molesto, pero borrando caché es como se soluciona
