### ISSUE TITLE
[Mobs][Paramos de poniente-Torre Mortoalerta] Mercenarios

### ISSUE THREAD

**Issue by ErahUnderground** [RoDNet/Bugtracker-Infinium-4.3.4#3752]
Los mercenarios élite de paramos de poniente: http://wow.freakz.ro/npc_finder.php?npc=42656&name=mercenary
Problema: El daño que hacen es exagerado con una media de 1000 puntos de daños por golpe cuando deberían hacer entre 50-65.

Explicación más detallada: Voy con un paladín nivel 22 y debería no tener problemas contra ellos. Al enfrentarme me tumban (eliminan) de un golpe, como mucho dos. El daño es exagerado.

**Comment by redneo** [comment]
Bajado el daño
