### ISSUE TITLE
[Mob][Monstañas Crestagrana-Lago Sempiterno]Viejo Gummers

### ISSUE THREAD

**Issue by ErahUnderground** [RoDNet/Bugtracker-Infinium-4.3.4#3753]
Viejo Gummers: http://wow.freakz.ro/npc_finder.php?npc=43041&name=ol-gummers
Problema: Su daño es de 94 - 105.
Explicación completa: Al atacarme con una armadura de mallas y sin acertarme con un crítico me ha eliminado de un solo hit de 1127 puntos de daño cuando su daño medio es el mencionado anteriormente

**Comment by redneo** [comment]
Bajado el daño
