### ISSUE TITLE
[Mob(Rare)][Montañas Crestagrana-Valle Render]Chitter

### ISSUE THREAD

**Issue by ErahUnderground** [RoDNet/Bugtracker-Infinium-4.3.4#3754]
Chitter lvl 18 rare : http://wow.freakz.ro/npc_finder.php?npc=52146&name=chitter
Problema: Su daño está entre 48-53 y te hace 4500 puntos de daño.

Explicación completa: Me he encontrado con este rare y al enfrentarme con él, en vez de hacer su cantidad de daño normal me ha realizado un hit de alrededor de 4500 puntos de daño provocándome la muerte instantánea.

**Comment by redneo** [comment]
Bajado el daño, metido magias.
