### ISSUE TITLE
[Mob][Teldrassil-Tierras tuercepinos] Rama de corrupción

### ISSUE THREAD

**Issue by ErahUnderground** [RoDNet/Bugtracker-Infinium-4.3.4#3755]
Rama de corrupción: http://wow.freakz.ro/npc_finder.php?npc=34521&name=bough-of-corruption

Error: Golpe una media de 650 puntos de daño por hit cuando su daño debería ser de 40-45 puntos.

**Comment by redneo** [comment]
Bajado el daño
