### ISSUE TITLE
[Mob(Rare)][Bosque del Ocaso - La ribera silente] Marina DeSirrus

### ISSUE THREAD

**Issue by ErahUnderground** [RoDNet/Bugtracker-Infinium-4.3.4#3756]
Personaje: http://wow.freakz.ro/npc_finder.php?npc=45811&name=marina-desirrus
Error: El npc en concreto ataca con una fuerza de alrededor de 1500 puntos de daños por hit cuando su ataque debería estar entre un rango de 78-87.

**Comment by redneo** [comment]
Bajado el daño, puede que sea aun alto
