### ISSUE TITLE
[DK]Perdida de runas de muerte

### ISSUE THREAD

**Issue by ExodusDK** [RoDNet/Bugtracker-Infinium-4.3.4#3757]
ID:54637 http://es.wowhead.com/spell=54637/sangre-del-norte
El problema de esta talento es que cada vez que entras a bg,mazmorra o algun sitio donde haya pantalla de carga las runas de muerte permanentes que deberia tener el dk escarcha se convierten en runas de sangre,obligando al dk a reloguear para recuperar esas runas tan necesarias en el dk escarcha

**Comment by F4NT4SM4** [comment]
no es necesario relogear precisamente solo usa el hechizo 
Hervo de sangre que cuesta runa de sangre y estas se convertiran en muerte permanenteme
osea al entrar en bg usas 2 veces hervo de sangre y listo
