### ISSUE TITLE
[DK] Recarga de runas

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3760]
Nombre: Recarga de runas
Descripcion: Al gastar las runas estas tardan 10s en recargar dependiendo de la celeridad
si se gasta 2 runas de la misma rama profano por ejemplo la otra no se recarga hasta que la primera este llena
Problema: las recargas de runas siguen recargandose a lo loco tras usar una skill se recargan todas de una o las reduce

**Comment by Kiritoo** [comment]
No entiendo muy bien a lo que te refieres, explicate un poco mejor, gracias.

**Comment by Kiritoo** [comment]
Estamos revisandolo, el problema no será de potenciación rúnica por lo que estamos mirando no recarga una sola al azar, lo está haciendo mal y recargando de más.

**Comment by F4NT4SM4** [comment]
bueno eso qeu tras usar golpe de escarcha las runas que estaban renovandose a 9s pasan a 2s 
o se renuevan de una

**Comment by Kiritoo** [comment]
Sip es eso que te comento seguro, cuando lo reparemos lo comunico aqui.
