### ISSUE TITLE
 Mago Talento [Ignición] [Piroexplosion] [Maestria] Bug

### ISSUE THREAD

**Issue by Bichoculiao** [RoDNet/Bugtracker-Infinium-4.3.4#3761]
Estaba revisando porque mi mago pegaba tan poco últimamente, revise un par de formulas y lo primero que encontré tras un critico este bug...resulta que ignición pega un total de 40% del daño del hechizo como DOT durante 4 segundos
Ignite
Deals Fire damage every 2 sec.
Duration: 4 seconds
Talento de 3 Ranks: 13% per point up to 40% at rank 3
http://www.wowwiki.com/Ignite_(old)

por lo que cada tick debe tener un daño del 20% del hechizo como tal
de un critico de 40k debería ser algo asi como 2 tick de 8k cada uno los cuales deben stackear al momento de golpear un nuevo critico que suelta Ignición para añadir el daño anterior con el nuevo, ejemplo:
Me salto Pyroblast! y volví a dar 40k de críticos, que suerte! eso quiere decir que los tick aumentan al doble, ahora cada 2 seg recibirán 16k de daño por 4 seg, interesante no?

aquí encontré una pagina que muestra varios ejemplos de como funciona que actualmente he notado que no funciona igual, por ejemplo si le pego un critico al seg 3 no aumenta el daño solo reinicia la duración pero con el DOT del hechizo actual, vaya problema ya que estoy a la espera de combustión para matar utilizando esta habilidad
acabo de verificar que esta andando bien a excepcion de los Rank, adicionalmente a eso tengo otra carta bajo la manga, que se llama maestría utilizada en cataclismo
16432
QUEMADURA DE RELAMPAGO(In. Flashburn): Aumenta el daño causado por todas las habilidades de fuego de daño periódico en un 22,4%. Cada punto de maestría aumenta el daño periódico causado en un 2,8% adicional.

Creo que al 40% de daño que debe hacer ignite debe ser aumentado por mi maestría que con 10.82 de maestría me da un bonus que me "aumenta un 30% del daño infligido por TODOS tus efectos de daño de _fuego periódico_ 

Me explico, El daño de un pyroblast! de 40k entonces que hace debe hacer 2 tick de 8k debe ser bonificado por la maestría lo que quedarían en ticks de 10.4k cada uno aportados por la maestría, osea que la maestría no esta funcionando tan bien al parecer. aquí les dejo una screenshot actual de mi ignite con pyro:
https://imageshack.com/i/mvhqt9j
Ahi se ve que si tengolos 3 talentos en Ignicion

https://imageshack.com/i/msynejj
Ahi esta la muestra del recount
12814 / 16432               que deberia ser el 40% (y sin la bonificacion de maestria aun, ya que ese daño deberia aumentar un 30% ahora) añadiendole un daño total de 1643

Otra cosa me percate, la Formula de la habilidad Pyroblast es exactamente la misma de la pagina http://www.wowhead.com/spell=11366/pyroblast al lvl 85, lo extraño es que ese daño es de pandaria y en pandaria no tiene aplicada la bonificacion de Espcializacion en Fuego (+25% de daño con tus hechizos de fuego) la formula del los DOT no la pude encontrar pero ya que tienen esa formula para nuestro hechizo mas fuerte, porque no le aplican la Especializacion de fuego que le falta? los 12 seg del DOT van bien aunque creo que con estas pocas que me entraron en la duda por mi bajo dps 
12068
Hurls an immense fiery boulder that causes 1636 to 2076 (+ 198% of Spell power) Fire damage and an additional 2022 (+ 216% of Spell power) Fire damage over 18 sec.

hice la formula y sumandola me dio lo mismo que pego actualmente creo que esta mal por la siguiente razon
4.3.0 (Mon Nov 28 2011) Build 14849 Last changelog
1311 a 1665 bajo un adicional de 648 bajo 12 seg

Actualmente pego 12068 normal sin criticos con el DOT de Pyroblast a un palo (4 DOTS de 3 seg c/u) segun la formula de arriba la cual no ha cambiado pese a las actualizaciones (incluyendo a las de pandaria que solo aumentaron la cantidad de segundos de 12 a 18 =2 tick mas) basandome en esa formula al palo deberia haberle hecho 20412,36 de daño con los el total de los DOT de pyro, el cual nuevamente esta sin la bonificacion de la maestria que aumentaria 30% el dot de ese pyro de 19897 de daño

19262,84 - 19594,84 directo y dot  20412,36  de daño yo deberia hacer con mi intelecto de daño a un palo sin resistencia con pyroblast, ya que la formula se ha mantenido es el daño el que hace la diferencia, y ese daño deberian hacer los magos PERO nos falta agregarles Especializacion en fuego que aumentara gratuitamente un 25% de daño a esta habilidad lo que quedaria con los 9108 de spell power que fueron probadas estas habildades, el daño que deberia hacer con esa habilidad seria el siguiente

25515,45  -  24493,55 daño de fuego directo y un DOT de 25515,45 con mi habilidad mas poderosa y sin criticos, y estoy esperando imaginarme ese mismo daño con los 12k que uso durante 20 seg en arena... cuando lo arreglen.

Cualquiera diria OP y todo eso, a eso se le restan las resistencias mágicas y el temple y en la practica en arenas ese daño solo aumentaría unos 5k pero la verdad estoy haciendo arenas en donde aparte de dispelearme los hechizos pego un critico de 30k miserablemente con un intelecto de ese momento de 12.001 y que un healer con 8500 de intelecto tire un instantaneo y cure lo mismo, revise el tema de los healers y van bien, lo que pasa que nosotros los dps no vamos bien y no podemos hacer el daño que SI hace dudar al heal entre dispelear y curar como debería ser originalmente, No se donde buscar mas información al respecto, lo del talento Ignición funciona como RANK 2 y no como RANK 3 quizas con eso puedo ayudar pero ID de spell no se si algún mago me ayuda a conseguirlos llevo 3 dias buscando y solo encuentro información de pandaria
A la mayoria de los full impla con pyroblast les hago 11k de daño, y con todo el spell power que tengo eso es una burla, lol (si la habilidad se demora 3.5 seg pa hacer 11k y con agostar hago 7k? lol)

Fuentes:
http://www.wowwiki.com/Ignite_(old)
http://www.wowhead.com/spell=11366/pyroblast#changelog

**Comment by redneo** [comment]
Me puedes hacer un resumen para idiotas de lo que falla, please?

**Comment by Bichoculiao** [comment]
Pyroblast - Piroexplosion Hechizo Mago:
Falla de daño Formula Pyroblast (Piroexplosion de mago) pega mas de lo normal
Razon: Utilizan formula pandaria de daño de pyroblast.

Ignicion 3/3 Talento Mago fuego:
Añade un 26% del daño inflinjido por hechizos
Razon: al parecer lo tienen funcionando como Rank 2 por el daño que añade, deben ponerle el rank 3 como corresponde. (40%)

Maestria Especializacion de Fuego:
No añade el daño a Pyroblast - Piroexplosion
Razon: Al utilizar la formula de pandaria, en pandaria no existe la Maestria Especializacion de Fuego, por lo que el hechizo Pyroblast no se beneficia en ningun momento de él bajando su daño en 25%.

Maestria Quemadura de Relampagos:
No añade la bonificacion a las Habilidades "Ignicion" y "DOT Pyroblast" añadiendo el bajo daño de este ultimo por las 2 cosas antes mencionadas.
Razon: Solo funciona con hechizos Combustion, Descarga de Pirofrio y Bomba Viva, nada mas.

Ese es un resumen, arriba puse las pruebas de la formula actual y la que deberia ser y puse screenshot de pruebas de mi hechizo y pueden verificarlo todos con una calculadora xD

**Comment by Bichoculiao** [comment]
de hecho tambien voy a verificar si efectivamente se aumenta el 3% de daño con talento 3/3 de Poder de Fuego y los 12% adicional con talento Furia de Arrabio 3/3 que me tienen en la duda tambien.... u.u

**Comment by redneo** [comment]
Paso a testar las cosas:

Como siempre, sin auras, ni talentos ni ropa, tan solo con un anillo de 10.000 a Intelecto. Con Dr. Damage, Idtip y Recount:

Piroexplosión: Spell ID: 11366.
Daño que me dice el Dr. Damage: 17004 - 17339 de daño directo, DOTs de 3x2000.8
Daño que me dice el Recount: 6 Hits de 17011 a 17315 media de 17226, 2 Criticos 25750 - 25936. 27 DOTs de 2000, 5 Criticos de DOTs de 3000.

Veredicto: Piroexplosion en si, sin contar ningún añadido va perfecto.

Ignicción: Rango 3 ID de spell: 12846.
Repito operacion con 10.000 de intelecto y ahora con un anillo de 4.000 a critico.

Daño critico de piroexplosion: 25627
... Si que estaba bajo, proceso arreglado.

Especialización en Fuego: 84668, Mismo proceso, personaje desnudo solo con anillo de 10k a intelecto y solo con el aura 84668: 

Resultados: 5 hits de 21315 a 21623 con 20 dots de 3500 no critico. Resultado está OK.

**Comment by Bichoculiao** [comment]
Muchas Gracias por tu trabajo, estoy muy conforme con tu respuesta y tiempo entregado a revisarlo, crei que por la formula no estaba añadida la especializacion de fuego pero veo que si, se agradece bastante, saludos!
