### ISSUE TITLE
[Hechizo-Cazador]Llamada del maestro

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3762]
Nombre: Llamada del maestro
Enlace: http://es.wowhead.com/spell=53271/llamada-de-maestro
Descripción: Tu mascota intenta eliminar todos los efectos de reducción de movimiento y de raíces sobre sí misma y su objetivo y provoca que ambos se vuelvan inmunes a tales efectos durante 4 s.
Problema: Ha habido recientemente arreglos a esta habilidad, y se agradece (mucho). Solo ha quedado un ligero problema con ella. Explico:
Cuando la mascota recibe las raíces del mago y se utiliza llamada del maestro, ahí la mascota solo aplica Llamada del maestro sobre sí misma, pero no sobre el objetivo. Si por ejemplo, en un duelo, dejo la mascota un poco apartada de mi, viene el mago y me coloca nova de escarcha (por decir una raiz de mago), ahí si funciona bien Llamada del maestro porque la mascota no recibío tambien la raíz.
El reporte de combate en tal caso dice algo así:
[Jugador] lanza Llamada del maestro
[Jugador] gana Llamada del mestro de [Mascota]
[Mascota] gana Llamada del mestro de [Mascota]

Pero cuando la mascota recibe la raíz junto con el objetivo, entónces sólo se puede ver en el registro algo así:
[Mascota] gana Llamada del mestro de [Mascota]
Y en tal caso tampoco recibe el objetivo el bufo de Llamada del maestro.

Por lo demás, cuando se usa Llamada del maestro antes de recibir la raíz, o si se usa sin que la mascota haya recibido raíz, el hechizo va ya estupendamente, pues hace inmune a las raíces durante el tiempo del bufo.

PD: Espero que haya quedado explicado, por prisas no podré revisar redacción ahorita :)

**Comment by Kiritoo** [comment]
¿Quizas sea porque al estar ella enraizada no puede saltar sobre el objetivo y usar la llamada del maestro sobre el?

**Comment by Jhovanni** [comment]
Mm, cierto. Sin embargo, llamada del maestro debería funcionar aún estando la mascota enraizada. Pensando en lo que has dicho, entonces es probable que el problema sea que la mascota primero intenta liberar al objetivo y luego a sí misma, cuando debería liberarse primero ella y luego al objetivo.
Cada vez que se usa llamada el registro de combate muestra esto:
[Jugador] lanza Llamada del maestro
[Jugador] gana Llamada del mestro de [Mascota]
[Mascota] gana Llamada del mestro de [Mascota]

Y en cambio, creo, que sea probable que el orden en que deberían ser las cosas sea algo así:
[Jugador] lanza Llamada del maestro
[Mascota] gana Llamada del mestro de [Mascota]
[Jugador] gana Llamada del mestro de [Mascota]

De esa manera funcionaría. Sólo son suposiciones de orden de eventos. Pues llamada del maestro la he visto funcionar de manera oficial aún teniendo a la mascota con raíces.

EDIT: No, no tiene que ver con tal cosa del orden de eventos que se dan. Lo he probado viendo el registro en otros lugares.

**Comment by efectokoleos** [comment]
arreglado
