### ISSUE TITLE
[Hechizo-Cazador]Trampas

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3763]
Nombre: Trampas
Enlace: http://www.wowwiki.com/Trap
Problema: El tiempo de armado de las trampas está siendo instantáneo. De acuerdo al último changelog que he encontrado, el tiempo de armado de las trampas debe ser un segundo. El armado instanténo deja un bug beneficioso para el cazador, e incluso negativo en ciertas ocasiones en que se espara el armado para controlar al sanador mientras se aleja su dps.

Patch 3.0.2 (14-Oct-2008): The arming time has been reduced to 1 second, from 2 seconds for all traps.

No encontré otro patch que modifique el tiempo de armado.

**Comment by Bichoculiao** [comment]
mmm por lo que tengo entendido con lanzar trampa funciona instantaneamente, de igual manera que frost arrow en lich king, con la trampa de hielo y cualquiera siempre y cuando acerte la posicion del objetivo, de las terrestres efectivamente tiene 1 segundo de armado.

**Comment by Jhovanni** [comment]
Es posible que sea eso que dices, pues con la introducción de lanzadora de trampas no se. No encontré reporte alguno sobre el armado de trampas a partir de cataclismo.

**Comment by Kiritoo** [comment]
Esta funcionando como dice Bichoculiao, con el lanzador de trampas en el punto exacto va instantaneo y situada en el suelo tarda en armarse.
