### ISSUE TITLE
[Guerrero] Golpes de barrido

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3764]
Nombre: Golpes de barrido
ID:12328
Enlace: http://wow.freakz.ro/spells.php?spell=12328
Descripcion: Tus ataques cuerpo a cuerpo golpean a un oponente cercano adicional. Dura 10s
Problema: Hago un ataque de 10k y el oponente cercano adicional recibio 5k el daño deberia de ser similar al ataque principal 
2problema: no esta saliendo critico con golpe de barrido

**Comment by Kiritoo** [comment]
¿Donde pone que tenga que ser similar?, me da que en el punto 1 te equivocas, revisaremos el punto 2.
Si lo viste en algun lado que tenga que ser exactamente igual el daño añade la info.

**Comment by F4NT4SM4** [comment]
mis ataques cuerpos a cuerpo golpean a un oponente cercano adicional un ejemplo golpe mortal hace 10k logicamente el objetivo cercano adicional tambien recibe ese golpe mortal que son 10k 
si hago un abrumar de 25k al objetivo principal el oponente cercano adicional tambien recibe ese abrumar 25k. en mop aplicaron un parche para que solo recibiera un 50% de daño al segundo objetivo
comentarios de wowhead 
Por Xbander ( 4110 - 1 · 9 · 37 ) el 30/08/2011 (Parche 4.2.2) El daño es equivalente. Si caes en un éxito de 45k, el otro objetivo también será golpeado por 45k. 
Mrdude135 el 02/11/2012 (Parche 5.0.5)
Aparece en MoP que los ataques de los Golpes de barrido sólo alcanzaron el 50% de daño al segundo objetivo.

**Comment by F4NT4SM4** [comment]
estube leyendo por hay y creo nose muy bien ya q es una mala traduccion de google que golpes de barrido es casi imposible que salga critico ya que no toma el crtiico de cuerpo a cuerpo si no el critico de poder con hechizos la unica forma q salga critico es tener algun buff que me aumente el critico con hechizos

**Comment by F4NT4SM4** [comment]
Golpe de barrido solo toma en cuenta el temple,reduccion de daño, armadura etc...
del objetivo principal es decir no importa que el objetivo secundario tenga mas temple, armadura etc...
ya el daño fue calculado por las reducciones del objetivo principal 
http://us.battle.net/wow/es/forum/topic/9499700082?page=2

**Comment by F4NT4SM4** [comment]
ejecutar no deberia influir en golpes de barrido almenos que los otros objetivos tengan un 25% menos de vida
ejecutar se usa para rematar al enemigo solo se puede usar si le objetivo tiene 25% de vida o menos creo que era ese %
