### ISSUE TITLE
[Chaman] Totem De Tremor

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3765]
Nombre: Totem De Tremor
ID:8143
Enlace: http://wow.freakz.ro/spells.php?spell=8143
Descripcion: Invoca un Tótem Tremor con 5 salud a los pies del taumaturgo que hace temblar el suelo a su alrededor durante 6 segundos, eliminando el miedo, el embelesamiento  y el sueño efectos de los miembros del grupo o banda radio de 30 m. Este tótem se puede lanzar cuando el lanzador está afectado por este tipo de efectos.
Problema: no esta quitando los efecto de embelesamiento por ejemplo control mental, Seducir de sucubo. No me he fijado si quita el sueño podrian revisar si no es mucha molestia

**Comment by efectokoleos** [comment]
arreglado
