### ISSUE TITLE
[DK] Golpe Purulento 

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3766]
Nombre: Golpe Purulento 
ID:85948
Enlace: http://wow.freakz.ro/spells.php?spell=85948
Descripcion: Un ataque instantaneo que inflge un 150% de daño con arma mas 840p. y aumenta la duracion de tus efecto peste de sangre, fiebre de escarcha y cadenas de hielo en el objetivo hasta 6s

Problema: No esta aumentando la duracion de los siguientes efectos:
Peste de sangre: 59879
Fiebre de escarcha: 59921
cadenas de hielo: 45524
2do problema: el daño esta algo bajo segun Dr.damage y la formula

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
El daño esta correcto.

**Comment by F4NT4SM4** [comment]
sigue bug...
mmm es posible que me haiga equivocado de id me fije en el id del libro de hechizos
el ld que sale en el debuff del objetivo es diferente corrijo
Fiebre de Escarcha: 55095
Peste de sangre: 55078
cadenas de hielo el id esta bien pero no veo que aumente la duracion

**Comment by Kiritoo** [comment]
Esta sin compilar

**Comment by F4NT4SM4** [comment]
sigue sin funcionar.. .e.e

**Comment by Kiritoo** [comment]
Hace 10 dias que no se compila el servidor, por ello no funciona aun.

**Comment by F4NT4SM4** [comment]
no esta funcionando como debería....
vamos a poner un ejemplo 
si cadenas de hielo dura 8s y al usar golpe purulento la vuelve a poner de nuevo a 8s 
deberia de aumentarla 6s mas quedando a 14s otro golpe mas quedaría a 20s y a si sucesivamente
claro este ataque pide muchas runas a si que no es spameable en pvp 

fuente: http://es.wowhead.com/spell=85948/golpe-purulento#english-comments
En menos de 5 minutos, tuve la oportunidad de traer Fiebre de Escarcha a una duración de 3 minutos y Cadenas de hielo a un segundo de duración 50 en un muñeco-diana. Fue divertido verlo tick durante tanto tiempo = P Por supuesto, yo no haría esto en un escenario PvE PvP o ... sólo estaría perdiendo demasiados recursos para mantenerlos. Sólo estaba el spamming Transfusión de sangre y Cadenas de hielo con Golpe de Escarcha adicionales para iluminar runas (vía Runic Empowerment) para más huelgas Festering!
