### ISSUE TITLE
[DK] Pesteador de ebano

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3767]
Nombre: Pesteador de ebano
ID:51099/51160 
Enlace: http://wow.freakz.ro/spells.php?spell=51160 
Descripcion: Tus facultades golpe de peste, toque helado, cadenas de hielo y borte tambien infectan al objetivo con peste de ebano, que aumenta un 15%/30% el daño recibido de tus enfermedades y todo el daño magico recibido un 8% extra

Problema: muy seguida veces en bg deja de funcionar el talento no sigue aplicando el debuff mi unica opcion es relogear para que vuelva a funcionar
Desconozco el por que no logre conseguir la causa

**Comment by efectokoleos** [comment]
arreglado
