### ISSUE TITLE
[Guerrero] Cargar DR denuevo bug

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3769]
Nombre: Cargar Aturdidora
ID:7922
Enlace:http://wow.freakz.ro/spells.php?spell=7922
Descripcion: Cargar e Interceptar ya no tienen rendimiento decreciente en sus efectos de aturdimiento. (notas del parche 4.1)
Problema: Se ha vuelto a bugear el DR del efecto aturdimiento de cargar

**Comment by Kiritoo** [comment]
Si lo sé estoy haciendole unas pruebas, durante el día de mañana se pondrá de nuevo.

**Comment by Kiritoo** [comment]
Ahora si arreglado definitivamente, tenia un fallo el cual ya esta solucionado, falta compilar.
