### ISSUE TITLE
[Sets] Profesiones

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#377]
Se puede realizar el set de pvp de nivel 377 por Sastrería. Herrería y Peletería puede ser qe tambien lo dejen hacer. 
Cabe decir qe en la temporada qe estamos el sañoso qe es el qe se consigue con honor es 371.

Por tanto deberían desabilitar este set.

**Comment by ghost** [comment]
Y por ese mismo motivo se ha deshabilitado el set 377... ¬¬ si podes conseguir con algunos mats todo el set sañoso 377.. para que te vas a matar haciendo bgs para tener el 371? xd

**Comment by Wiinter** [comment]
Eso es de lo qe me quejo, qe no se ha desabilitado xD Porque lo he hecho hace poco para comprovarlo.
Lo siento por no expresarme bien

**Comment by ghost** [comment]
Ah xd yo entendi al revez :P pues se suponía que redneo los deshabilito todos.... S: /summon @redneo xd en todo caso que deshabilite para crear los sets y si alguien ya tiene que se ponga requisito lvl 86.

**Comment by F4NT4SM4** [comment]
en herreria estan deshabilitados
en las demas profecciones no he comprobado
