### ISSUE TITLE
[Paladin Reprensión] Sellos de mando

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3771]
ID: 85126
La descripción dice que inflige un 7% de daño con arma los Sello de Rectitud, Sello de Verdad (id: 31801) y Sello de Justicia (id: 20164).
El problema es que solo está dando el 7% de daño con arma al Sello de Rectitud al activar el sello, pero no está dando ese 7% de daño con arma a los sellos de Verdad ni de Justicia cuando se activan.

**Comment by efectokoleos** [comment]
arreglado
