### ISSUE TITLE
[Evento] Cartera de bienes frios - Ahune

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#3772]
Evento: Solsticio de Verano

Fallo: el NPC Ahune(http://es.wowhead.com/npc=25740) al matarlo por primera vez en el día debería entregar la Cartera de bienes frios(http://es.wowhead.com/item=54536) pero no la da.

**Comment by Monleon** [comment]
Por favor, ¿si hay algo más que falle del evento nos lo podeis añadir aquí también lo antes posible para que podamos arreglarlo?

**Comment by nayan87** [comment]
Monle os puse ticket ingame, pero ahora no recuerdo todo lo que fallaba, de todos modos ahi va
1-  4 hogueras de la alianza en reinos del este (pico nidal , Thelsamar, Villadorada y Refugio de la zaga)
2- Las antorchas del festival no funcionan
3- El ncp "cuentacuentos del festival" no te da la mision que le corresponde, me suena que se llama recompensa de un ladron.
4- El poste de cintas del festival tampoco funciona.

Así a bote pronto es todo lo que recuerdo, mañana con mas calma termino de mirar las hogueras de kalimdor y hago el reporte como dios manda. Un saludo¡

**Comment by juaks** [comment]
Las misiones El contraataque (http://es.wowhead.com/quest=11953) no funcionan ya que al dar en la piedra de hielo no sale el npc a matar.

**Comment by juaks** [comment]
Las hogueras de Profanar las de la Alianza no van.

**Comment by Velcositro** [comment]
Reporté lo del Poste: #3776

**Comment by nayan87** [comment]
Ahora miro las de kalimdor, pero las de reinos del este van todas menos 4¡

**Comment by juaks** [comment]
Las hogueras las ha arreglado Doora creo.

**Comment by nayan87** [comment]
de moneto las de kalimdor funcionan todas las de profanar, lo llevo a la mitad, ahora sigo mirando

**Comment by nayan87** [comment]
ok seguimso con el reporte, las hogueras de crater de un goro en el refugio de marshall, no funcionan, ni la de la horda ni la de la alianza.

Y confirmo que ya funcionan las de tierras de interior¡ tierras altas de arathi¡ y paramos de poniente

**Comment by redneo** [comment]
Las hogueras horda/alianza tendrian que funcionar todas. Un goro, no es necesaria para el logro, asi que logicamente no funciona.

Se está trabajando en el boss para que cuente en el buscador de mazmorra, asi como en el poste.

**Comment by nayan87** [comment]
funcionan, todas las hogueras a fecha de hoy¡ 
El cuentacuentos del festival sigue sin otorgar mision, y es necesario para el logro

**Comment by juaks** [comment]
El boss cuenta para el logro, lo que no da es la bolsa al matarlo por primera vez en el día.

**Comment by Monleon** [comment]
Funcionan ya todos los logros. La cartera de bienes fríos no obstante os la dará la diaria heroica del cataclysm.
