### ISSUE TITLE
[Guerrero] Glifo Golpe Mortal

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3773]
Nombre: Glifo Golpe Mortal
ID:58368
Enlace: http://wow.freakz.ro/spells.php?spell=58368
Descripcion: incrementa el daño de golpe mortal un 10%
Problema: me parece que no esta aumentando ese 10%
el daño que hago normalmente 10012-12218 
lo que haria con el glifo 11013-13439 me aparecen daño menor a 11013 y no mas de 12218 es decir no me esta aumentando ese 10%

**Comment by Monleon** [comment]
El glifo funciona.

P.D. Los dummies tienen armadura.
