### ISSUE TITLE
[Evento: Festival de Solsticio de Verano] Entidad: Poste de las cintas

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#3776]
Entidad: http://es.wowhead.com/object=181605
Bug: Al hacerle clic derecho para usarlo debería hacer que el pj baile alrededor de él, pero no pasa nada. 

Además esto es necesario para el logro "Baile ardiente en el poste caliente"(http://es.wowhead.com/achievement=271).

Espero que puedan arreglarlo pronto o conseguir una solución alterna ya que es el único logro que me falta para el Metalogro del evento. Gracias de antemano.

**Comment by Monleon** [comment]
Funcionan ya todos los logros.
