### ISSUE TITLE
[Misión/Logro] Restos de Thalorien Buscalba inexistentes.

### ISSUE THREAD

**Issue by Hellythium** [RoDNet/Bugtracker-Infinium-4.3.4#3778]
Buenas, el problema es que el NPC ''Restos de Thalorien Buscalba'' que se encuentran en Isla de Quel'Dalar (http://es.wowhead.com/npc=37552) no existe, por lo tanto no inicia ningún evento y por esto es imposible completar la misión ''Thalorien Buscalba'' (http://es.wowhead.com/quest=24535/thalorien-buscalba) ni tampoco el logro ''La Espada prometida'' (http://es.wowhead.com/achievement=4596/la-espada-prometida) que conlleva ésta.

**Comment by Wiinter** [comment]
Hace tiempo que está reportado.
