### ISSUE TITLE
[valle fresno] [mision] respeto a los caidos

### ISSUE THREAD

**Issue by tiazmat** [RoDNet/Bugtracker-Infinium-4.3.4#3780]
los cadaveres no se encuentran en el lugar indicado, ni el del patio ni el de la parte superior de la torre
http://es.wowhead.com/quest=13626

los objetos que deben ser obtenidos 
http://es.wowhead.com/item=45043
http://es.wowhead.com/item=45042

**Comment by Kiritoo** [comment]
Arreglada, falta reiniciar.
