### ISSUE TITLE
Evento Solstico de verano 

### ISSUE THREAD

**Issue by Szajil** [RoDNet/Bugtracker-Infinium-4.3.4#3783]

**Comment by Szajil** [comment]
No funcionan "Baile ardiente en el poste caliente" .http://es.wowhead.com/achievement=271
"Rey del Festival del fuego" http://es.wowhead.com/achievement=1145
y "Malabarista" http://es.wowhead.com/achievement=272

**Comment by rubiosoy** [comment]
Aprovecho para juntar aquí que la hoguera de nagrand en teelar esta mal

**Comment by Monleon** [comment]
Funcionan ya todos los logros.
