### ISSUE TITLE
[NPC] Monturas voladoras de misiones

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#3786]
Los objetos como:
Cuerno de Razaescarcha(http://es.wowhead.com/item=39700) que invoca a Vencedor Razaescarcha(http://es.wowhead.com/npc=28670)
Esencia de esmeralda(http://es.wowhead.com/item=37815) que invoca a Draco Esmeralda(http://es.wowhead.com/npc=27692)
etc...

Invocan bien a la montura, pero la velocidad a la que van es estresante, van a velocidad -5.

Gracias.

**Comment by Kiritoo** [comment]
Arreglado.
