### ISSUE TITLE
Mision Dominando lo Arcano esta BUG no se completa ayuda

### ISSUE THREAD

**Issue by mcviclic** [RoDNet/Bugtracker-Infinium-4.3.4#3787]
Porfavor eesa mision esta bug ayuda

**Comment by sakuranobushi** [comment]
La informacion proporcionada es insuficiente.

https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by Kiritoo** [comment]
Veo una horda y otra alianza si no reportas el id no sabemos cual es.
