### ISSUE TITLE
[BUG] Baile ardiente en el poste caliente - logro evento

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#3788]
http://es.wowhead.com/achievement=271/baile-ardiente-en-el-poste-caliente

Cuando le das al poste no te pones a bailar

**Comment by nayan87** [comment]
Esta reportado todo lo bug del evento en el hilo de lord Ahune, creo que están en ello, saludos y buena caza¡

**Comment by Monleon** [comment]
Funcionan ya todos los logros.
