### ISSUE TITLE
[Chaman] Escudos cd interno

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3789]
Nombre: Escudo de tierra, relampago y de agua
Escudo de tierra ID:974
Escudo de relampago: 324
Escudo de agua: 52127
Enlace: http://eu.battle.net/wow/es/game/patch-notes/4-2-0#shaman
Descripcion: El tiempo de reutilización interno de Escudo de agua se ha reducido a 3,5 s para que se ajuste a otros escudos.

Problema: el cd interno de estos escudos es menor a 3,5s
escudo de agua en 35s el escudo debio de darme solo 10 veces el efecto me dio unos 13 segun el recount 
no es nada prioritario pero un chaman heler con el escudo de tierra tendria como 2-3 cargas mas por esos segundo

**Comment by Wiinter** [comment]
El de tierra diría que tiene cd interno, los demás no lo se. 
Pero apostaría que tiene cd interno porque lo uso el chaman solamente para pve y al tanque le pueden estar zurrando 30mil mobs, que tarda como 30s en quitarse el escudo, así a ojo.
Aunqe no estaría de mas comprovarlo por si acaso.

**Comment by Kiritoo** [comment]
Cierto estaban los tres escudos en 3 segundos, ajustado a 3,5s.
