### ISSUE TITLE
[Brujos] Poseer 

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#379]
Poseer funciona correctamente la parte del buffo, pero lo de curar no.
Poseer cura cuando se expira el efecto o cuando se reemplaza por otro y este sano en una sola cura el 100% de daño generado. Si hace 8k de daño pues recibirás al cabo de x segundos 8k de sanacion

**Comment by searum** [comment]
esto funciona
