### ISSUE TITLE
[Chaman Mejora] Maestria: Elementos Mejorados

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3790]
Nombre: Maestria: Elementos Mejorados
ID:77223
Enlace: http://wow.freakz.ro/spells.php?spell=77223
Descripcion: Aumenta todo el daño de fuego, escarcha y naturaleza infligido un 20% (base). Cada punto de maestria aumenta el daño un 2,5% extra.
Problema: tiene el mismo bug que tenia la maestria de mago fuego esta haciendo doble efecto por lo que calcule 

Testeo: 1578 hace el escudo de relampago segun el sp que tengo y con 34% maestria deberia dejarlo a 2115 esta haciendo 2850 si le aumento el doble que va siendo 68% da 2652 un daño mas aproximado probe con choque de fuego para asegurarme que no era escudo de relampago y tambien le aumenta el doble la maestria

**Comment by Kiritoo** [comment]
Arreglado falta compilar.
