### ISSUE TITLE
[Chaman] Glifo escudo de Relampago

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3791]
Nombre: Glifo: escudo de Relampago
ID:55553
Enlace: http://wow.freakz.ro/spells.php?spell=55553
Descripcion: Tu escudo de relampago ya no puede quedarse con menos e 3 cargas despues de infligir daño a los atacantes
Problema: el problema solo afecta al talento elemental a nosotros podemos tener mas de 3 cargas hasta 9 cuando tenemos mas de 3 cargas gracias a Trueno ensordecedor (88764) el glifo deja de funcionar y se va el escudo de relampago al recibir daño 

mas o menos deberia ser asi tenemos 9 cargas nos atacan baja a 8 nos pegan denuevo baja a 7 asi hasta llegar a 3 el caso es que visualmente no se ven que disminuyan las cargas pero si se gastan pero llegando a 3 no deberia de perder mas cargar y si pierde el buff por perderlas 
nose si me estoy explicando bien ponganse el talento trueno ensordecedor y el glifo para que vean a que me refiero

**Comment by efectokoleos** [comment]
arreglado
