### ISSUE TITLE
[Dk] Talento de parásito de sangre

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3792]
Id: 49542
Descripción: http://wow.freakz.ro/spells.php?spell=49542

El problema que está dando este talento es que están saliendo los gusanos de forma muy frecuente cuando la posibilidad de que aparezcan con los dos puntos de talento es del 10% y además aparecen varios de una vez en múltiples ocasiones, cuando sólo debería aparecer uno.

Un saludo y gracias

**Comment by Kiritoo** [comment]
Arreglado, falta reiniciar.
