### ISSUE TITLE
[Errores de Clases] Estadísticas Esquivar/Agilidad

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3794]
Nombre: Esquivar/Agilidad
Descripcion: La agilidad ya no aporta ningún bonus a la probabilidad de esquivar de los caballeros de la Muerte, los paladines y los guerreros. Ahora su probabilidad de esquivar de base se ha fijado en un 5%.
Fuente: http://eu.battle.net/wow/es/game/patch-notes/4-2-0
Problema: actualmente nuestra esquivar base es 4.08% y aumenta con la agilidad como dice en al descripcion deberiamos tener un 5% base y no se aumenta por la agilidad

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
