### ISSUE TITLE
[Cazador] Camuflaje/Trampas

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3795]
Nombre: Camuflaje/Trampas
Descripcion: Ahora Camuflaje se interrumpe cuando las trampas del cazador infligen daño a un objetivo.
Fuente: http://eu.battle.net/wow/es/game/patch-notes/4-0-6
Problema: no se esta quitando camuflaje al hacer daño con trampa que infligen daño

**Comment by Pegasu5** [comment]
Los cazadores en la vida real no salen cuando sus trampas se activan, salen mucho después de que la presa ha caído, lógica de blizzard son unos tards xD

**Comment by efectokoleos** [comment]
arreglado, falta compilar
