### ISSUE TITLE
logro solsticio

### ISSUE THREAD

**Issue by rubiosoy** [RoDNet/Bugtracker-Infinium-4.3.4#3796]
mision vigilante de las llamas de terrallende he completado todas las hogeras excepto teelar en nagrand, no me aparece para coger la mision. he preguntado en mi hermandad pero no la habian hecho. mi pj es salt por si acaso solo soy yo al que le pasa, ya he borrado cache varias veces pero nada.gracias

**Comment by Monleon** [comment]
Probadlo porque se debería de poder.
