### ISSUE TITLE
Logro: Permanece en el fuego

### ISSUE THREAD

**Issue by hunterdom** [RoDNet/Bugtracker-Infinium-4.3.4#3797]
Buenas, el día 13 conseguí el logro Permanece en el fuego con Lori mi bruja que consiste en que te mate Alamuerte cuando quema una zona, pues desde entonces que todos los mapas me salen con el cielo rojo y el suelo igual, he visitado las mismas zonas con otro pj que no tiene el logro y todo esta correcto. Espero algún día volver ha ver el cielo azul XD.
Gracias.

**Comment by Wiinter** [comment]
Diría que al morir se te va el color rojizo del paisaje.

**Comment by hunterdom** [comment]
Pues no, se me ha ido hoy día 2 después de tirar de piedra desde Orgrimmar, igual me lo han arreglado pero desde el día 13 te aseguro que he muerto muchas veces y he tirado piedra a diario, pero al final se fue, Aleluya!

**Comment by Kiritoo** [comment]
Al cambiar de zona se te va.
