### ISSUE TITLE
[Druida] Barra de eclipse y oleada de estrellas.

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.3.4#3798]
Estuve estudiando el eclipse y me he puesto a mirar videos del ofi y al parecer la energía de eclipse debería moverse solamente en una dirección, es decir, cuando la energía esta neutra si lanzas cólera http://es.wowhead.com/spell=5176 obtendrás energía lunar y la energía  se movera hacia eclipse lunar. En ese punto  sólo será posible obtener energia lunar, y no se movera hacia la otra dirrección hasta que llegue hasta eclipse lunar. De la misma manera funciona  fuego estelar, http://www.wowhead.com/spell=2912 ,  mientras la energía está en 0, neutra, si se lanza este poder debería darnos energía solar y hasta que lleguemos hasta eclipse solar no deberíamos obtener energía energia lunar.
Eclipse solar: http://es.wowhead.com/spell=48517
Eclipse lunar: http://es.wowhead.com/spell=48518/eclipse-lunar

Puede que ahi radique el problema, según he visto la dirección depende de una flechita que muestra hacia donde se esta moviendo la energia, lo que a nosostros nos sucede es que existe una doble flecha la cual permite que la energía se mueva para un lado o para el otro, es decir: nos permite ganar energía solar y lunar sin respetar la dirección.

Según lo mecionado anteriormente el funcionamiento de oleda de estrellas                                           ( http://es.wowhead.com/spell=78674/oleada-de-estrellas ) también se ve afectado 
 ya que debería otorgar energía dependiendo del  tipo de energía que  nos beneficie más, actualmente sólo otorga energía solar. Y debería dar energía solar ,si es que la barra se está moviendo hacia eclipse solar, y lunar si es que la barra se mueve hacia eclipse lunar.

**Comment by efectokoleos** [comment]
arreglado
