### ISSUE TITLE
Portales Dalaran Horda

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#38]
Bueno, el lugar donde estan los portales de la horda, ahora solo esta el de orgrimmar y no todos los portales que estaban antes

![wowscrnshot_070313_201033](https://f.cloud.github.com/assets/4895839/747039/a54f24be-e446-11e2-8a94-5b639a905379.jpg)

**Comment by Alfonn** [comment]
Los portales en Cataclysm se borraron tanto los de la Alianza como los de la Horda. ¿Razón? Aquí te la dejo :

http://eu.battle.net/wow/es/forum/topic/916824844#3

**Comment by ghost** [comment]
Seguro? ahí dice que estan así para saber donde se pasará más tiempo en la "proxima expansión" y el post es del 2010, esta versión salio como en el 2012 (creo).

**Comment by Alfonn** [comment]
La idea detrás de quitar los portales es simplemente el saber dónde vamos a jugar la siguiente expansión. Cuando estábamos en el WoW Clásico, todo el mundo usaba las ciudades principales de su facción como punto de encuentro. Cuando estábamos en la Burning Crusade todo el mundo usaba Shattrath como punto de encuentro. Después, en la Wrath, todos usábamos Dalaran. Ahora, todo eso queda atrás, y volvemos a las ciudades principales de las facciones, que es donde se desarrollará la expansión, así que no tiene sentido "forzar" a la gente a volver a contenido antiguo (Shattrath y Dalaran) para viajar. 

--------->En Cataclysm habrá nuevos métodos de viaje (vuelo en el "Viejo mundo" y portales a zonas nuevas(Vash'jir,Hyjal,Twilights...)), así que realmente no notarás la diferencia. El único problema puede ser este pequeño tiempo de transición hasta que llegue la expansión.

**Comment by Alfonn** [comment]
Los portales se quitan en la cataclysm despues del 4.0.6. Porque en MoP la gente se centra en el último contienente (el de los pandas) y ahora en cataclysm nos centramos en Ventormenta, ya que tenemos todos los instructores , recetas cata. E dalaran sólo queda lo de la WLTK.Y si te fijas hablan en futuro, es decir, que blizzard anunció lo de los portales y ese chico se quejó y pidió explicaciones.

**Comment by ghost** [comment]
Entiendo que no hayan portales a Dalaran o a Shattra, pero en dalaran debería de haber portales a las demas ciudades así como en Shattra (tengo entendido que así es la verdad no estoy seguro), cuando llego WOTLK los portales de shattra desaparecieron o algo así?

**Comment by Alfonn** [comment]
Posiblemente, no estoy muy seguro , pero al final de la WTLK pronpondrían esta idea y se expuso. Yo lo veo lógico que se quiten dichos portales; ya que Dalaran ahora mismo NADIE la usa , o si la usan es para teletransportarse cómodamente. Además están dando una oportunidad grandísima a los magos a volver a ser más útiles gracias a los portales. De todas formas tengo 1 amigo que viene del oficial , y sí, es así, solo dejan el portal de ventormenta/Orgrimmar.

**Comment by ghost** [comment]
Pues bueno, entonces que venga el que abrio el bug para cerrarlo, xd habrá que desembolsar gold para los magos.
