### ISSUE TITLE
[DK] Voluntad de la necropolis

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#380]
http://es.wowhead.com/spell=81164/voluntad-de-la-necropolis

El buff de reducir el daño un 25%
solo se deberia de activar cuando este por 30% de vidad
y se activa al minimo daño que hago y no tiene cd siempre se me activa siempre

**Comment by ghost** [comment]
Se va refrescando continuamente y siempre está activo, es un bug tremendo...

Ya estaba reportado por cierto, intenta fijarte antes de hacer un post nuevo por si ya está para no dar trabajo doble.

Saludos.

**Comment by searum** [comment]
fix
