### ISSUE TITLE
[Mob(Rare)][Loch Modan - Caverna de Alahierro] Optimo

### ISSUE THREAD

**Issue by ErahUnderground** [RoDNet/Bugtracker-Infinium-4.3.4#3801]
El mob en cuestión es este http://wow.freakz.ro/npc_finder.php?npc=45399&name=optimo
Su daño está entre el rango de 48 - 54 puntos por hit y realiza una media de 1600 puntos de daño por hit sin ser crítico.

**Comment by Kiritoo** [comment]
Arreglado.
