### ISSUE TITLE
[Druida] Glifo de oleada de estrellas

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.3.4#3802]
El glifo http://es.wowhead.com/spell=62971/glifo-de-oleada-de-estrellas
no funciona, no reduce el tiempo de reutilizacion de lluvia de estrellashttp://es.wowhead.com/spell=48505/lluvia-de-estrellas  como debería.

**Comment by Kiritoo** [comment]
Fix, falta compilar.
