### ISSUE TITLE
[Guerrero] Gritos de batalla/Orden

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3807]
Nombre: Gritos de batalla/Orden
ID:6673/469
Enlace:http://wow.freakz.ro/spells.php?spell=6673, 
            http://wow.freakz.ro/spells.php?spell=469
Descripcion: Un guerrero solo puede colocar un grito
Problema: puedo colocar los 2 buffos juntos y no deberia si uso grito de batalla teniendo el de orden este lo remplaza pero esto no quiere decir que otro war reemplaze mi grito por ejemplo yo tiro grito de orden y el otro el de batalla no se reemplaza pero si yo trato de tirar el de orden y luego el de batalla el grito de orden se va

**Comment by efectokoleos** [comment]
arreglado
