### ISSUE TITLE
[Druida]Mordedura feroz

### ISSUE THREAD

**Issue by gerlopez64** [RoDNet/Bugtracker-Infinium-4.3.4#3809]
Vengo a informar sobre el hechizo mordedura feroz tiene el daño demasiado reducido 
en un servidor oficial se pueden observar buenos criticos con este hechizo aca con ful trinket y cd no pasa de 20k 
http://www.wowhead.com/spell=22568 en este link se puede ver el changelog para la version 4.3 
[spell=22568]
https://www.youtube.com/watch?v=mEJw3Kesst8 en este video se observa el hechizo en uso con equipo full , yo no soy full pero no hace el daño equivalente al equipo implacable (en el video esta cataclismico)

**Comment by F4NT4SM4** [comment]
si mal no recuerdo un gm lo reviso hace poco y dijo que esta bien
si vas a reportar sobre daño tienes que mirar la formula el ap bla bla bla y fijarte si va mal o no

**Comment by gerlopez64** [comment]
Bueno ahora que llegue a casa hare la demostracion de la formula y la comparacion de daño

**Comment by Kiritoo** [comment]
Me parece ver algo raro y es que con 4-5 puntos de combo pega de menos, sin embargo con 1-3 puntos de combo pega de mas a lo que debería.
Revisalo si puedes sin armadura ni talentos, de todas maneras mañana lo reviso.

**Comment by gerlopez64** [comment]
Bueno hice lo que me pidieron y hice la demostracion sin equipo 
empieza con 1 punto de combo hasta 5 puntos todos los repeti 3 veces para tener un resultado mas asegurado, tambien realice el ataque con 100 puntos en la barra de la energia cada vez

en estas 5 pruebas el daño medio esta bien , no me salio ningun critico algo dificil sin equipo
en el siguiente comentario mostrare con mi equipo talentos y  los 2 bugs que le encontre

![1 pnto sin equipo](https://cloud.githubusercontent.com/assets/8060552/3483501/3506d872-0390-11e4-8ef4-fabb377e0004.png)
![2 pntos sin equipo](https://cloud.githubusercontent.com/assets/8060552/3483502/350978fc-0390-11e4-90b0-d15e7504356b.png)
![3puntos sin equipo](https://cloud.githubusercontent.com/assets/8060552/3483503/350cc11a-0390-11e4-92dc-b67c8f8eba4b.png)
![4 pntos sin equipo](https://cloud.githubusercontent.com/assets/8060552/3483504/351033f4-0390-11e4-9a85-827546b1b741.png)
![5 pntos sin euqipo](https://cloud.githubusercontent.com/assets/8060552/3483505/35132ca8-0390-11e4-9899-67c3b287db6c.png)
![equipo y talentos](https://cloud.githubusercontent.com/assets/8060552/3483506/3516ad74-0390-11e4-84d4-c643f0331bf8.png)
![glifos](https://cloud.githubusercontent.com/assets/8060552/3483507/352bd410-0390-11e4-9801-fd6af2a73e12.png)

**Comment by Kiritoo** [comment]
Ya lo tengo arreglado y el glifo de mordedura feroz, falta compilar, gracias por testear.

**Comment by gerlopez64** [comment]
Bueno el primer bug dice que el hechizo de por si vale 25 puntos de energia y puede usar 35 adicionales pero solo resta los primeros 25 llegando a 75 no a 40 como deberia (con rabia a 65)
![bug energia](https://cloud.githubusercontent.com/assets/8060552/3483678/71d1b576-0393-11e4-9580-d0a09c229be8.png)

Y el segundo el daño llega a la mitad:
1ra imagen comprueba que el addon esta bien usando el hechizo destrozar
![comprobacion addon](https://cloud.githubusercontent.com/assets/8060552/3483685/881b12c8-0393-11e4-985a-f81f23d956ca.png)

2da muestra que el daño de destrozar llega a la mitad con todo burst(la prueba de la derecha salio critico debio sacar aproximadamente 50k la segunda salio normal debio sacar 24k no 12)
![dao a la mitad](https://cloud.githubusercontent.com/assets/8060552/3483687/9bce81c4-0393-11e4-9a32-2f607d8accf2.png)

Posteo esto despues de cerrado ya que son 2 bugs y talvez te saltaste uno u.u

**Comment by Kiritoo** [comment]
No, yo arregle el daño de la mordedura, que es lo reportado en este issue, si quieres añadir otro fallo hazlo en un issue a parte y añadiendo las ids, gracias.

**Comment by Kiritoo** [comment]
¿Y porque dices lo de destrozar si estamos hablando de Mordedura Feroz? Ahi me perdí.

**Comment by gerlopez64** [comment]
es para mostrar que el addon no esta equivocado jeje

**Comment by gerlopez64** [comment]
entonces hago otro tema para lo de la energia?

**Comment by Kiritoo** [comment]
Espera a que compilemos el servidor esta noche y lo revisas de nuevo, si ves mal lo de la energía lo reportas en otro issue ok?

**Comment by gerlopez64** [comment]
Ok :D
