### ISSUE TITLE
[DK] Maestria Escudo de Sangre

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#381]
http://es.wowhead.com/spell=77513/maestria-escudo-de-sangre
Solo deberia de funcionar la maestria del dk sangre en precensia sangre
el fallo es que la puedo usar estando en precensia escarcha y profana

**Comment by Dekadencee** [comment]
Fixed

**Comment by F4NT4SM4** [comment]
....
Estaba testeando y ahora no sirve en precensia sangre 
ahora solo se activa en precensia escarcha...
