### ISSUE TITLE
[DK] Golpe Purulento 

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3810]
Nombre: Golpe Purulento 
ID:85948
Enlace: http://wow.freakz.ro/spells.php?spell=85948
Descripcion: Un ataque instantaneo que inflge un 150% de daño con arma mas 840p. y aumenta la duracion de tus efecto peste de sangre, fiebre de escarcha y cadenas de hielo en el objetivo hasta 6s

Problema:aumenta la duracion pero no como deberia vamos a poner un ejemplo 
si cadenas de hielo dura 8s y al usar golpe purulento la vuelve a poner de nuevo a 8s 
deberia de aumentarla 6s mas quedando a 14s otro golpe mas quedaría a 20s y a si sucesivamente
claro este ataque pide muchas runas a si que no es spameable en pvp

**Comment by sakuranobushi** [comment]
El error ha sido reparado y estará corregido próximamente en el servidor publico.
