### ISSUE TITLE
[Errores de clases] Hechizos con tono de color rojo

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3811]
Nombre: Hechizos con tono de color rojo
Enlace: http://eu.battle.net/wow/es/game/patch-notes/4-1-0
Descripcion: Ahora varios efectos de suelo persistentes muestran un aspecto visual diferente para jugadores hostiles y amistosos. Los siguientes hechizos tienen los mismos efectos visuales para jugadores amistosos, pero nuevos efectos visuales alternativos para jugadores hostiles: Anillo de Escarcha, Consagración, Profanación, Champiñón salvaje, Bengala, Trampa de hielo, Palabra de poder: barrera, Bomba de humo y Mano de Gul'dan. Como norma general, los efectos alternativos tienen un color o tono rojo para indicar que los ha creado un jugador enemigo.

Problema: Los hechizos nombrado su efecto visual deberia tener un tono rojo para los jugadores hostiles no tienen tal efecto se muestra como si fueran amistoso

Esto ayudaria mucho en pvp saber si la trampa de hielo es de un aliado y estar tranquilo
o el anillo de escarcha etc etc...

**Comment by Dekadencee** [comment]
Fixed, el sistema del emulador esta preparado y hemos hecho el cambio en los spells conocidos, si sabeis de alguno mas que no realice aún el efecto y debería, por favor, avisadlo.

**Comment by F4NT4SM4** [comment]
mmm el unico que cambio es anillo de escarcha los demas nada de nada.., testee en duelo con aliz nose. pense que era que los cambios aun no se han implementado pero el anillo de escarcha si muestra el efecto ahora
dejo los spells que faltaron:
Mano de guldan:71521
consagracion: 26573
Palabra de poder: Barerra: 62618
Profanacion: 55666/55667
Champiñon Salvaje (me imagino que es el efecto area que hace con el talento): 88747 id de champiñon. ID del talento 78788/78789
Trampa de hielo:13809
Bengala:1543
Bomba de humo: 76577
