### ISSUE TITLE
[Objeto] Artefacto de Khaz'goroth

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3812]
http://eu.battle.net/wow/es/item/68972
Los problemas de este abalorio son los siguientes:
Está dando cargas de poder titánico ya sea dando un golpe crítico o no, y sólo debería dar las cargas cuando realizas un golpe crítico cuerpo a cuerpo
Y el otro problema es que al activarse, solo da celeridad o golpe crítico, la maestría no la está dando, porque mi nivel de maestría es el más alto de los tres y sin embargo me está dando celeridad

**Comment by efectokoleos** [comment]
arreglado
