### ISSUE TITLE
[Chaman Elemental] Tormenta de Truenos

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3814]
Nombre: Tormenta de Truenos
ID:51490
Enlace: http://wow.freakz.ro/spells.php?spell=51490
Descripción: Ahora Tormenta de truenos reduce un 40% la velocidad de movimiento de los jugadores a los que derriba durante 5 s. (notas de parche 4.2)
Problema:no esta ralentizando a los jugadores que derriba

**Comment by efectokoleos** [comment]
arreglado
