### ISSUE TITLE
[DK] Supresión Magica

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3815]
Nombre: Supresión Magica
ID:49224/49610/49611
Enlace: http://wow.freakz.ro/spells.php?spell=49611
Descripcion: Aumenta la amortiguacion de daño con hechizos de tu caparazon antimagia un 8%/16%/25% extra y genera poder runico cuando el caparazon antimagia amortigua daño(el rank 2 genera mas que el rank 1 y el rank 3 genera mas que el rank 2).
Problema:no esta generando poder runico de ninguno de los rank

**Comment by Monleon** [comment]
Si no estoy equivocado, sí que regenera, incluso sin los talentos puestos

**Comment by Monleon** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3489

**Comment by F4NT4SM4** [comment]
eso era antes de los fix ahroa no genera con o sin talento puesto...

**Comment by Kiritoo** [comment]
Y así lo dejare hasta que lo arregle ya que al parecer la gente se beneficiaba sin reportarlo.

**Comment by sakuranobushi** [comment]
Este error se ha corregido en el reino de pruebas y debería reflejarse pronto en el resto.
