### ISSUE TITLE
[DK] Glifo de Estrangular

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3816]
Nombre: Glifo de Estrangular
ID:58618
Enlace: http://wow.freakz.ro/spells.php?spell=58618
Descripcion: Aumenta la duración del silencio de tu facultad Estrangular 2 s cuando se utiliza con un objetivo que está lanzando un hechizo.
Problema:no esta aumentado la duracion

**Comment by efectokoleos** [comment]
arreglado
