### ISSUE TITLE
glifos del cazador que no sirven

### ISSUE THREAD

**Issue by ezequielcn** [RoDNet/Bugtracker-Infinium-4.3.4#3817]
hola e notado jugando que estos dos glifos no están funcionando:
Glifo de Redirección: Cuando utilizas Redirección en tu mascota, se reinicia el tiempo de reutilización de Redirección.
Glifo de Disparo mortal:  si el daño de tu disparo mortal no logra matar al objetivo con un 20% de vida el tiempo de reutilizacion tu disparo mortal se reinicia instantáneamente

**Comment by Monleon** [comment]
El de disparo mortal ya funciona
