### ISSUE TITLE
[Joyeria] Un Regalo para lila

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#382]
http://es.wowhead.com/quest=25154/un-regalo-para-lila

la mision me pide tallar 3 gemas 
Piedra nocturna intemporal http://es.wowhead.com/item=52098

Las hago pero no me da la opcion de completar la quest
![wowscrnshot_071113_192640](https://f.cloud.github.com/assets/3101842/785574/c41d13a2-ea85-11e2-9839-69888d2d9f5f.jpg)

**Comment by crowel** [comment]
Me pasa a mi lo mismo.
Un saludo.

**Comment by Dekadencee** [comment]
Si @Lvmb pero es preferible 1 reporte por quest/spell/npc ya que es mas facil organizarnos

**Comment by ghost** [comment]
Ya esta arreglado.
