### ISSUE TITLE
[Mazmorra][Zul`aman] Entrada a el Boss Halazzi

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3821]
Nombre: Puerta de Acceso al Boss cerrada

Boss: Halazzi
http://es.wowhead.com/npc=23577

Problema:
La puerta de acceso al boss esta cerrada y por lo tanto se hace imposible enfrentarlo

Observaciones: Creo que es un problema de gobject que no esta funcionando como debe que es la puerta del boss.

**Comment by nayan87** [comment]
mmmm en zulaman, se puede acceder a todos los bosses, halazzi tiene la entrada más o menos por el camino de la derecha según vas de frente hacia el edificio, si te vas de frente daras con una puerta cerrada
