### ISSUE TITLE
[Misiones][Mulgore]La tierra inquieta

### ISSUE THREAD

**Issue by Tharathor** [RoDNet/Bugtracker-Infinium-4.3.4#3822]
Saludos.
- Nombre: La tierra inquieta.
- Enlace: http://es.wowhead.com/quest=14491.
- Descripcion: Utiliza los tambores de la tierra aliviada para calmar a 6 espíritus de tierra perturbados.
- Problema: El uso de los tambores no contabilizan los espiritus que debes calmar. El contador se queda a 0.

**Comment by sakuranobushi** [comment]
El error ha sido reparado y estará corregido próximamente en el servidor publico.
