### ISSUE TITLE
[DK] Glifo de Socorro oscuro

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3823]
ID: 96279
Según la descripción al matar a un enemigo que aporte experiencia u honor mientras se está en presencia de escarcha o profana, debería restaurar un 20% de la salud máxima. El problema está en que al sacrificar al esbirro por ejemplo para sanarte, también salta este glifo permitiendote sanarte aún mas, y cuando matas las serpientes del cazador u otras pets de jugadores también ocurre.

**Comment by lomero** [comment]
tienes toda la razon no deberia saltar al matar las serpientes del cazador a menos que estas den honor al igual que la la pets no creo que den honor.

**Comment by F4NT4SM4** [comment]
se activa con algunas pets no recuerdo cuales pero las serpientes definitivamente no 
el ataque de victoria del war tenia el mismo problema pero ya lo repararon se podrian guiar por el ataque de victoria las condiciones

**Comment by efectokoleos** [comment]
arreglado
