### ISSUE TITLE
[DK Profano] Golpe purulento

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3825]
ID: 85948
Un ataque que inflige 150% de daño con arma más 840 (sin los talentos de la rama profana).
Con mi daño con arma que es de 4785-5733 (sin talentos ni buffos), este ataque debería pegar 7800 y sin embargo pega 5316

**Comment by F4NT4SM4** [comment]
estas testeando con el dummy?
el dummy tiene algo de armadura a si que reduce el daño fisico 
testea con otro jugador sin equipo

**Comment by Monleon** [comment]
No probeis spells de daño con arma en dummies, porque les hemos añadido armadura a todos los npcs

**Comment by lomero** [comment]
cuando dices talentos a cuales te refiereS?
