### ISSUE TITLE
[Chaman] Escudo de tierra

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3827]
ID: 974
Con el intelecto que tengo (4780), este hechizo debería sanarme 2035 puntos de salud por cada tick, y no 16k que es lo que está sanando ahora mismo.

**Comment by Kiritoo** [comment]
Mejor que busques realmente el fallo porque a mi con un anillo de 10.000 de intelecto y sin talentos me sana 10.500 cuando deberia sanarme 11.000

Asi que si existe algun fallo no es del escudo en sí, igualmente decir que nose de donde sacas que te deba sanar 2035 puntos con 4780 de intelecto, igualmente a ver si puedes aportar algo visual para que lo veamos, gracias.
