### ISSUE TITLE
[Mazmorras][Cámara de los Orígenes] Setesh Ensamblaje de la Destrucción

### ISSUE THREAD

**Issue by lomero** [RoDNet/Bugtracker-Infinium-4.3.4#3828]
Nombre: Setesh Ensamblaje de la Destrucción
Enlace:http://es.wowhead.com/npc=39732

Problema: El Boss va del todo bien solo hay un problema durante el combate cuando el boss abre los Portales del Caos estos deberian poder ser destruidos en dificultad heroica pero no pueden ser atacados y ni si quiera targeteados por lo tanto hace el encuentro se llene de puros adds y aumenta mas su dificultad.

**Comment by sakuranobushi** [comment]
Este error se ha corregido en el reino de pruebas y debería reflejarse pronto en el resto.
