### ISSUE TITLE
[Druida] Desenredo

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#383]
http://es.wowhead.com/spell=96429/desenredo
deberia de quitar los efectos de frenado y eliminar las raices
ps tambien esta quitando los efecto inmovilizadores como seccionar mejorado
en wow head no encuentro el talento seccionar pero es un efecto inmovilizador
solo deberia de quitar el seccionar normal pero se deberia de quedar el seccionar mejorado que es efecto inmovilizador

Seccionar: http://es.wowhead.com/spell=1715
Seccionar mejorado: Borrado de wow head no lo encuentro

**Comment by Dazand** [comment]
Creo que con raices se refiere a todos los hechizos que peguen al piso al objetivo, por ejemplo la nova de escarcha de el mago, con seccionar mejorado pegas al piso al objetivo, tal vez esa es la razón por la cual desenredo quita seccionar mejorado; algo así como el druida del LK que quitaba TODOS los efectos que impedian el movimiento.

Saludos

**Comment by F4NT4SM4** [comment]
a raices se refiere a raices hechizos donde salen esas raices que hace el druida o chaman con totem .
en la version anterior no se quitaban seccionar mejorado, me puse a leer las notas del parche y no hay ningun cambio de desenredo de 4.0.6 a 4.3.4

**Comment by Dazand** [comment]
No estoy muy seguro de eso, mejor que un GM nos confirme

**Comment by Kiritoo** [comment]
Esto funciona.
