### ISSUE TITLE
[Druida feral] Mordedura feroz

### ISSUE THREAD

**Issue by gerlopez64** [RoDNet/Bugtracker-Infinium-4.3.4#3830]
Bueno ya habia reportado anteriormente este bug emm bueno parece que cuando lo probe crei que estaba arreglado pero el daño vuelve a ser el mismo al usarlo contra un jugador

http://es.wowhead.com/spell=22568/mordedura-feroz
ID Spell 22568

1 recount fue pegandole al palo
2 recount fue en una BG 

A y cabe destacar que pegandole al palo no use ningun CD de daño y en la BG si

![dao pve pvp](https://cloud.githubusercontent.com/assets/8060552/3496899/ebaaa63c-05e6-11e4-89a5-ea3278016eab.png)

Tambien esta el segundo bug que es de la energia pero primero arreglemolo por pasos :)

**Comment by Kiritoo** [comment]
El daño esta perfecto gerlopez, los palos tienen armadura y los jugadores de bg tienen armadura y por lo general temple, el daño de Mordedura actualmente esta genial y si quieres testear el daño contra un jugador ya que dices que el daño vuelve a ser el mismo contra un jugador, testealo contra otro player sin la armadura puesta.
