### ISSUE TITLE
[Objetos]Reliquias

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3831]
Nombre: Reliquias Hermandad
Enlace: http://es.wowhead.com/achievement=6626
Problema: Las reliquias de la liga fueron añadidas en el parche 4.0.3, pero los vendedores en el servidor no las ofrecen. Sería genial que las anexaran.
Observaciones: Tambien está el asunto que las reliquias de hermandad no pueden pasarse a personajes alter, cuando deberían.

**Comment by Monleon** [comment]
Las reliquias se pueden pasar correctamente y en cuanto al logro, hasta que no funcionen la mayoría de logros de hermandad están habilitadas las reliquias,  para que puedan ser compradas directamente
