### ISSUE TITLE
Bug misión http://es.wowhead.com/quest=27351/una-recompensa-real

### ISSUE THREAD

**Issue by matycelta** [RoDNet/Bugtracker-Infinium-4.3.4#3832]
se consiguen los tendones y el lingote, pero al matar a vallefont no te tira la piedra de afilar.

**Comment by lomero** [comment]
podrias especificar mejor la mision creo q no seguiste bien la guia

**Comment by JoakRoD** [comment]
Los reportes bien redactados por favor.
Aquí tienes una guía: https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
