### ISSUE TITLE
Explorar Gnomeregan

### ISSUE THREAD

**Issue by YODI2642** [RoDNet/Bugtracker-Infinium-4.3.4#3833]
La misión de Explorar Gnomeregan esta bug pliss reparenla gracias

**Comment by lomero** [comment]
asi no se hacen reporte te daran cerrado este bug

**Comment by JoakRoD** [comment]
Los reportes bien redactados por favor.
 Aquí tienes una guía: https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
