### ISSUE TITLE
[Objetos]Reliquias

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3834]
Nombre: Reliquias Hermandad
Enlace: http://es.wowhead.com/achievement=6626
Problema: Las reliquias de la liga fueron añadidas en el parche 4.0.3, pero los vendedores en el servidor no las ofrecen. Sería genial que las anexaran.
Observaciones: Tuve que abrir de nuevo el reporte porque ha sido cerrado aquí https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3831, haciendo mención del logro de la liga de wowhead. Pero el reporte no es sobre el logro, sino sobre la lista de reliquias que aparecen ahí, las cuales no están a la venta por los vendedores de hermandad, por ninguno. Ésas reliquias son las de piernas, que fueron agregadas en el parche 4.0.3 pero no se consiguen ahora en el servidor. GX

**Comment by Monleon** [comment]
Puedes ponerme enlaces de las ids de los objetos y de los vendedores?

**Comment by Monleon** [comment]
Añadidos en la alianza y en la horda
