### ISSUE TITLE
[Druida] Lluvia de estrellas

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.3.4#3839]
El poder : http://es.wowhead.com/spell=50288

La descipción del poder: ''Cambiar a forma animal o montar cancelan el efecto. Cualquier efecto que haga que pierdas el control de tu personaje suprimirá el efecto de Lluvia de estrellas." 

El problema: La parte de cancelar (arrancar el buff)  cuando se cambia a forma animal o se monta funciona bien. El problema está en que cuando ocurre un efecto que hace perder el control del personaje hace lo mismo (arrancar el buff), cuando debería suspender el efecto del buff hasta que se consiga de nuevo el control del personaje.

Este bug perjudica un monton porque mientras se está en lluvia de estrellas y alguien carga (un stun cercano a 1s) , por ejemplo, nos arranca el buff que es el CD del druida pollo, cuando deberia suspender el efecto de Lluvia de estrellas hasta poder recuperar el control sobre nuestro pj.

**Comment by Monleon** [comment]
Sí, y es como debe pasar, al perder el control de tu personaje Lluvia de estrellas se suprime

**Comment by Dazand** [comment]
No leíste bien? xD
Cuando se monta o se cambia a forma animal el buff se quita o sea, no se puede recuperar, y hasta ahí bien. Pero cuando se pierde el control del personaje por causa de stun, fear, etc el efecto se suprime hasta volver a obtener el control del personaje, o sea el efecto es recuperable, el problema, lo que esta pasando es que cuando se pierde el control del personaje se cuenta como si se hubiera cambiado de forma o se hubiera montado, de esta cancelando completamente el buff,nos lo esta quitando cosa que no debería pasar.

Gracias :)

**Comment by Monleon** [comment]
Tienes alguna prueba donde se vea o diga que tras recuperar el control de tu pj el efecto vuelva?

**Comment by Dazand** [comment]
Sí, acá en http://es.worldofwarcraft.wikia.com/wiki/Lluvia_de_estrellas si se miran las Notas se aclara esa parte.
Gracias :D

**Comment by Dazand** [comment]
Hola, quería saber si ya revisaste el link.

**Comment by Monleon** [comment]
Sí, tienes alguna imagen visual, tipo vídeo? No me ha quedado nada claro que deba ser así.

**Comment by Dazand** [comment]
En youtube hay varios:
En este: https://www.youtube.com/watch?v=yDAvIXzNOD4 en el minuto 3:37 el druida lanza Lluvia de estrellas, y el mago le lanza aliento de dragón spell=31661 , un poder que hacer perder el control del personaje. Como se aprecia en el video, el efecto de Lluvia de estrellas se suspende y cuando el druida se libera del Aliento de dragón, recupera su efecto, o sea continua lanzando estrellas.

O en este otro https://www.youtube.com/watch?v=LPhqA2hT28E el minuto 3:03
En donde el druida lanza Lluvia de estrellas, un guerrero le hace Cargar spell=100, un poder que hace perder el control del personaje por pocos segundos. El efecto de lluvia de estrellas se suspende, pero cuando termina el efecto de Cargar Lluvia de estrellas no desaparece sino que recupera su efecto.

Saludos.

**Comment by efectokoleos** [comment]
arreglado
