### ISSUE TITLE
[Mision] (Los Baldíos) Un problema en crecimiento

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#384]
La mision ''Un problema en crecimiento'': ( http://es.wowhead.com/quest=13988/un-problema-en-crecimiento )

dice que hay que llevar un totem que lo dan al obtener la mision                                   ( http://es.wowhead.com/item=46782 )
para invocar A Ojos de tonga: ( http://es.wowhead.com/npc=34615/ojos-de-tonga )
y deberia completarse,

Pues bueno, yo hice eso y no paso nada de nada. no la pude terminar

![wowscrnshot_071113_223914](https://f.cloud.github.com/assets/4895839/786237/0027bc5c-eaa5-11e2-9e3e-94db45db126f.jpg)

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
