### ISSUE TITLE
Sistema de bloqueo (guerrero)

### ISSUE THREAD

**Issue by matusalen** [RoDNet/Bugtracker-Infinium-4.3.4#3840]
Hola vengo a reportar un error que sucede con mi guerrero proteccion y es que al parecer el sistema de bloqueo no funciona, la animacion del bloqueo la hace, pero solo eso por que en realidad no detiene los ataques y entran como si no se hubiera bloqueado
![wowscrnshot_062514_183912](https://cloud.githubusercontent.com/assets/5150389/3533052/cc3de852-07c8-11e4-9ad9-c48a9264a5ea.jpg)
Se aprecia claramente en la imagen. golpea 388, y el registro dice que se bloqueo cierta cantidad, pero en donde aparece la imagen del personaje dice que esta recibiendo esos 388 enteros. Osea no esta bloqueando, deberia aparecer en el rostro del personaje BLOQUEADO
![wowscrnshot_062514_184100](https://cloud.githubusercontent.com/assets/5150389/3533150/97ccacb4-07ca-11e4-95cc-07a723999f5a.jpg)
En la segunda imagen se aprecia como es golpeado 522 daño y realmente recibe 522, esto comprueba que aun bloqueando se recibe daño y no deberia ser asi.Este error tiene mucho tiempo desde que llegue al server pero hasta el dia de hoy pude reportar, Gracias x su tiempo

**Comment by Monleon** [comment]
Te explico porque en la imagen es muy evidente. 

El daño que te deberia haber hecho el boss es 554. Sin embargo has bloqueado 166 puntos, lo cual si te fijas bien es justo un 30% (que es lo que debe bloquear un bloqueo estándar, no crítico)

**Comment by Monleon** [comment]
P.d. si quieres que te salga el texto de bloqueado, hay una opción desde interfaz para hacerlo

**Comment by matusalen** [comment]
Si mira independientemente q diga bloqueado. En la 2a imagen el registro dice golpeado 532 y no se bloqueo ahí entonces entran 532 bien.En la 1a. bloquea un ataque de 389 y el registro dice q bloqueo 189 (bloqueo normal)si lo cuenta el registro pero en realidad es golpeado por 389. Entonces en la imagen del pj debería decir 189 o bloqueado. Ese sería el daño real tras haber bloqueado pero aún bloqueando sigue recibiendo el daño entero. Si dejas tu pj ser golpeado x un mob q todo le Esquives.pares. Y bloquees ese mob no deberia bajarte la vida. Pero si sumas el daño q te hace y lo que segun bloqueas y lo restas a tu vida verás que realmente no has bloqueado nada. O al menos es lo q yo aprecio. No se si puedas darle una checadita a eso. Si no pues bueno no pasa nada

**Comment by Overseer101** [comment]
El bloqueo esta comprobado y funciona correctamente, si no aparece el texto "Bloqueado" junto con la cantidad es por que no esta activada la opcion en la seccion de la interfaz. Pero tanto funciona el bloqueo normal como el critico.

**Comment by Monleon** [comment]
388+166=554

El ataque debió haber sido de 554, sin embargo 166 puntos fueron bloqueados y 388 impactados

P.d. en la imagen te saltó revancha, que es lo que salta al bloquear
