### ISSUE TITLE
[Mazmorras][Cámara de los Orígenes] Guardián del templo Anhuur 

### ISSUE THREAD

**Issue by lomero** [RoDNet/Bugtracker-Infinium-4.3.4#3841]
Nombre: Guardían del templo Anhuur
Enlace:http://es.wowhead.com/npc=39425

Problema:

El boss durante el combate al llegar su vida al 66% o al 33% empieza a canalizar el hechizo Himno Resonante http://es.wowhead.com/spell=75322, el cual al canalizarlo se acumula empezando a ocasionar un daño de 400 puntos cada 1 seg pero el problema es que no esta ocasionando daño alguno y por mas que se acumule no hace daño.

El otro problema que tenemos es su otro spell Escudo de Luz http://es.wowhead.com/spell=74938 el cual es casteado por el boss pero segun la descripción del hechizo esto hace inmune a Anhuur y genere alrededor un campo de fuerza de efecto visual similar a la zona antimagia del DK y para desactivar su escudo el grupo de mazmorra debe dirigirse a las palancas que se encuentran abajo de la plataforma y usarlas para desactivar dicho escudo, por lo tanto al no hacer inmune al boss hace que sea una piñata y no funcione como en el oficial.

Añado un video en que el se puede ver el encuentro del boss en el oficial tal como funcionan sus spells

https://www.youtube.com/watch?v=Aq6AnQWuvQ0

**Comment by lomero** [comment]
Ya casi el boss esta completamente arreglado solo tiene un pequeño error que no se puede cortar el cast de Himno Resonante http://es.wowhead.com/spell=75322, solo eso le falta lo demás funciona bien.

**Comment by Savian123** [comment]
Hombre bien bien no... las palancas en modo HC son de casteo aparte el fuego de las estatuillas no pegan a todos los miembros del grupo sino que deberían enfocar el fuego en una sola zona

**Comment by efectokoleos** [comment]
arreglado
