### ISSUE TITLE
[Chamán] Flujos de lava

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.3.4#3843]
Talento: spell=51482

Fujos de lava (3/3) Aumenta el bonus de daño con golpe crítico de tu hechizo Ráfaga de lava un 24% extra y el daño de tu Choque de llamas un 60%. Además, cuando se disipa tu Choque de llamas, tu celeridad con hechizos aumenta un 90% durante 6s.

La primera parte funciona correctamente, pero cuando es disipado Choque de llamas no se otorga el buff de celeridad del 90%.

Gracias.

**Comment by efectokoleos** [comment]
arreglado
