### ISSUE TITLE
[Chamán] Bono (4) Conjunto Chamán Elemental PvP

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.3.4#3845]
Pongo Conjunto Chamán Elemental PvP porque al parecer es el bono de cada conjunto elemental de chamán PvP de cualquier temporada.

Bueno, sucede que el bono de este conjunto no funciona. Lo que deberia hacer es en vez de consumir una carga del escudo de relámpagos (spell=324), agregar una. Y a través del talento Trueno ensordecedor (spell=88765)  llegar a un máximo de 9.

El problema es que el bono no funciona para nada, lo que sucede (visualmente) es que las cargas no disminuyen, pero en realidad sí lo hacen y cuando llega a 3 golpes, o sea cuando se activa el efecto del poder 3 veces, el escudo desaparece.

Este talento perjudica en gran medida a los chamanes elementales ya que no pueden acumular apropiadamente las cargas del escudo de relámpagos.

ID del bono spell=100956
Enlace del Bono spell http://wow.freakz.ro/spells.php?spell=100956

**Comment by efectokoleos** [comment]
arreglado
