### ISSUE TITLE
[Mazmorra] Fin de los dias/Ira Guerrero

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3846]
Nombre: Bendicion del Vuelo Bronce
ID:102364
Enlace: http://wow.freakz.ro/spells.php?spell=102364
Descripcion: Este es un buff que aparece en el boss Murozond aumenta un 40% velocidad de ataque y movimiento
Problema: Cuando tengo el buff con mi guerrero la ira siempre se me queda en 0. 
Genero ira pero inmediatamente se me va a 0 y sospecho que es por el buff

**Comment by xtotosaix** [comment]
segun yo creo q es por el reinicio del reloj

**Comment by F4NT4SM4** [comment]
me quedo sin ira antes del reinicio del relog
le damos al reinicio del relog y sigo sin ira

**Comment by efectokoleos** [comment]
no he podido reproducir este error, no me baja la ira
