### ISSUE TITLE
[Mazmorra] Fin de los dias/Murozond

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3847]
Nombre: Murozond
ID:54432
Enlace: http://wow.freakz.ro/spells.php?spell=54432
Problema: el boss aparece en una zona equivocada unos tanto metros mas alante de lo que deberia y por esto no se puede hacer normalmente

Use salto heroico para localizarlo
![wowscrnshot_071314_000307](https://cloud.githubusercontent.com/assets/3101842/3563726/ae61961c-0a4d-11e4-96f3-4529221ddf72.jpg)

**Comment by efectokoleos** [comment]
es raro ya que todas las demas partys que lo hicieron salio bien

**Comment by Monleon** [comment]
Con acercarse al teletransportador tras acabar los trashes se acerca
