### ISSUE TITLE
[Talentos] Matanza rápida y Recuperación rápida.

### ISSUE THREAD

**Issue by Hellythium** [RoDNet/Bugtracker-Infinium-4.3.4#3848]
Matanza rápida de la rama de talentos del cazador puntería está saltando siempre, en lugar de que solo salte cada vez que se le dé el golpe de gracia a objetivos que otorguen experiencia u honor, y en segundo lugar, Recuperación rápida que es otro talento del puntería no está funcionando, ya que al ganar Matanza rápida no está generando los 50 pts de enfoque que debería según la descripción del talento.

**Comment by Kiritoo** [comment]
Arreglado el punto uno, solo ocurrirá al matar un enemigo que aporte honor u experiencia, falta compilar.
Queda pendiente el punto dos.
