### ISSUE TITLE
Problema con el seguidor de misiones

### ISSUE THREAD

**Issue by aloamr123** [RoDNet/Bugtracker-Infinium-4.3.4#3849]
Tengo un problema con el seguidor de misiones el día 13 del 07 el buscador de misiones me guiaba normalmente al punto donde debía ir, después de desconectarme unas horas al volver el buscador ya no me guiaba a los puntos donde están los npc o mounstros por favor espero que solucionen este problema ya que he intentado desactivando y reactivando el buscador, ademas de que no soy el unico al que le sucede esto ya que han habido varios jugadores a los que les ha pasado esto.

**Comment by JoakRoD** [comment]
El seguidor de misiones funciona correctamente, prueba a borrar Caché o mirar si lo tienes desactivado.

**Comment by Monleon** [comment]
El problema si no recuerdo mal sucede a veces, con borrar caché ya no te debería pasar

**Comment by aloamr123** [comment]
Gracias por contestar significa mucho, por cosas como esas el server
crecerá aun mas.

2014-07-15 9:26 GMT-05:00 Monleon notifications@github.com:
