### ISSUE TITLE
[DK Recien Creado] Tierras de la Peste: El Enclave Escarlata - Imposible Levear

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#385]
Bueno, en el lugar Tierras de la Peste: El Enclave Escarlata http://es.wowhead.com/zone=4298

Que es donde el dk tiene que hacer sus primeras misiones, es imposible levear, ya que hay demasiados mobs, y unos arqueros, los cruzados de tirisfal http://es.wowhead.com/npc=29103/cruzado-de-tirisfal#. tiran flechazos con bombas, y tiran demasiados, 500 cada golpe y el dk a duras penas tiene 3500 de vida.
## ![wowscrnshot_071213_014544](https://f.cloud.github.com/assets/4895839/786631/4348e28a-eabf-11e2-918e-9ea5c8c5984a.jpg)

![wowscrnshot_071213_015228](https://f.cloud.github.com/assets/4895839/786648/bc68f8d0-eabf-11e2-88ca-b09d74440162.jpg)

por favor revisar el area.

**Comment by ghost** [comment]
Tengo entendido que ya no sucede esto.
