### ISSUE TITLE
[Boss][Mazmorra - Stratholme]Lord Aurius Rivendare

### ISSUE THREAD

**Issue by ErahUnderground** [RoDNet/Bugtracker-Infinium-4.3.4#3850]
El último boss de la mazmorra hace una cantidad elevada de daño. Por hit hace una media de 2800 - 3000 puntos de daños a personajes con placas.

http://wow.freakz.ro/npc_finder.php?npc=45412&name=lord-aurius-rivendare

Como se muestra en el enlace, su daño debería estar entre 261 - 290 puntos de daño por hit. Este boss es necesario para completar el logro de la mazmorra de Stratholme.

**Comment by efectokoleos** [comment]
arreglado en el proximo reinicio
