### ISSUE TITLE
Bug de mobs en Gilneas

### ISSUE THREAD

**Issue by elcapii** [RoDNet/Bugtracker-Infinium-4.3.4#3852]
He comenzado la mision salvar a Krennan Aranas yn bueno antes de cogerla te aparecen como 30 huargens en 1 al lao de la mision y si comienzas a hacerla, justo antes de llegar al final de asaltan unos 50 de forma que es imposible -.-

**Comment by Kiritoo** [comment]
Ahora mismo lo reviso.

**Comment by Kiritoo** [comment]
Cuando se caiga o reinicie el servidor no debería ocurrir este problema.
