### ISSUE TITLE
[Mazmorra] Buscador de Mazmorras Fin de los dias 

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3855]
Nombre: Fin de los dias
Descripcion: Nivel de objeto necesario: 353
Problema: No esta dejando anotar con el buscador de mazmorra dice: No cumples los requisitos para entrar a la mazmorra elegida 

![wowscrnshot_071414_153257](https://cloud.githubusercontent.com/assets/3101842/3576394/d6f32434-0b91-11e4-81ea-3f5537a3e2eb.jpg)

**Comment by lomero** [comment]
Esto es debido a que el buscador de mazmorras para la hora del crepúsculo solo debe funcionar si no me equivoco con las 3 mazmorras abiertas es decir Pozo de la Eternidad y Hora del Crepusculo

**Comment by F4NT4SM4** [comment]
por especifica tampoco se puede anotar fin de los dias

**Comment by lomero** [comment]
si se puede ya probe sale tambien por mazmorra aleatoria prueba a borra cache

**Comment by Kiritoo** [comment]
Acabo de probar yo y funciona correctamente.
