### ISSUE TITLE
[Druida feral gato] Daño de mordedura feroz , destrozar y Devastar

### ISSUE THREAD

**Issue by Savian123** [RoDNet/Bugtracker-Infinium-4.3.4#3856]
Como veo que hay muchas quejas me he visto en obligación de comprobar por mi mismo el daño de los druidas ferales resulta que las habilidades destrozar , devastar y mordedura feroz tienen el daño aumentado si lo pudieran comprobar porque no veo normal que con 1 devastar y 1 destrozar un druida gato te baje la mitad de la vida Gracias :D

**Comment by Kiritoo** [comment]
Mordedura feroz funciona correctamente, hace poco lo arregle.
Sobre las otras dos no tengo ni idea igualmente tienes que adjuntar las ids de los  hechizos o talentos que quieres reportar y crea un Issue para cada bug si son cosas diferentes.
Gracias.
