### ISSUE TITLE
[BANDA] ULDUAR- Leviathan en llamas.

### ISSUE THREAD

**Issue by nayan87** [RoDNet/Bugtracker-Infinium-4.3.4#3859]
¿que ocurre?

Se activan habilidades en las torres de defensa correspondientes al modo dificil en el modo normal de la instance.
Una de estas habilidades:  Resguardo de Freya: Hace 15,000 de daño de naturaleza a todos los enemigos cercanos e invoca guardianes de naturaleza para ayudar. Invoca de manera infinita a guardianes ocasionando ralentizaciones e impidiendo la conclusión del boss y por tanto el acceso al resto de la instancia.

Os adjunto unas fotos 
![wowscrnshot_042314_220110](https://cloud.githubusercontent.com/assets/7257569/3593342/7f2552d4-0c83-11e4-98a6-76e25c871ded.jpg)
![wowscrnshot_070714_133911](https://cloud.githubusercontent.com/assets/7257569/3593343/7f26b444-0c83-11e4-9344-827fc598f538.jpg).

Una vez más gracias por vuestro tiempo, un saludo¡

**Comment by Kiritoo** [comment]
Esto esta arreglado.

**Comment by Dekadencee** [comment]
@Fixx Bueno, aún a la espera de la confirmación, mañana probamos en el PTR, demomento lo dejamos abierto por si acaso

**Comment by nayan87** [comment]
Apañao?? Si es que si me pongo con jogg saron!! Saludos

--- Mensaje Original ---

Desde: "Kiritoo" notifications@github.com
Enviado: 22 de noviembre de 2014 20:34
Para: "RoDNet/Bugtracker-Infinium-4.3.4" Bugtracker-Infinium-4.3.4@noreply.github.com
Cc: "nayan87" pablogf87@hotmail.com
Asunto: Re: [Bugtracker-Infinium-4.3.4] [BANDA] ULDUAR- Leviathan en llamas. (#3859)

Closed #3859.

---

Reply to this email directly or view it on GitHub:
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3859#event-197231824

**Comment by Kiritoo** [comment]
Si lo puedes comprobar se agradece, ya que parece que a nadie mas le dio problema y he visto a varias raids en ulduar, saludos.

**Comment by nayan87** [comment]
Ooook montare una en cuanto pueda!

--- Mensaje Original ---

Desde: "Kiritoo" notifications@github.com
Enviado: 22 de noviembre de 2014 20:46
Para: "RoDNet/Bugtracker-Infinium-4.3.4" Bugtracker-Infinium-4.3.4@noreply.github.com
Cc: "nayan87" pablogf87@hotmail.com
Asunto: Re: [Bugtracker-Infinium-4.3.4] [BANDA] ULDUAR- Leviathan en llamas. (#3859)

Si lo puedes comprobar se agradece, ya que parece que a nadie mas le dio problema y he visto a varias raids en ulduar, saludos.

---

**Comment by Kiritoo** [comment]
Gracias
