### ISSUE TITLE
[Mision] Lluvia de Destruccion

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#386]
La mision ''Lluvia de destruccion'' http://es.wowhead.com/quest=13798/lluvia-de-destruccion   No se puede hacer porque al utilizar el objeto de mision dice que hay que estar en una torre, incluso estando en la torre sigue saltando lo mismo

![wowscrnshot_071213_032342](https://f.cloud.github.com/assets/4895839/786966/95ff5ae2-eacc-11e2-80c8-2dea2e98b0fc.jpg)

![wowscrnshot_071213_032346](https://f.cloud.github.com/assets/4895839/786968/a041d886-eacc-11e2-8c90-536491867f9e.jpg)

**Comment by searum** [comment]
fixed

**Comment by iBrianAR** [comment]
Sigue bug :/ Además hay pocos NPC (objetivos de la misión).

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Si alguien encuentra algún fallo en un bug reparado con anterioridad debe de crear un Issue nuevo, jamás debe comentar en el cerrado a no ser que un miembro del staff le diga de hacerlo en el momento del cierre.
