### ISSUE TITLE
Miciones BUG

### ISSUE THREAD

**Issue by franpr-zz** [RoDNet/Bugtracker-Infinium-4.3.4#3861]
La micion "El emisario" (http://es.wowhead.com/search?q=el+emisario#quests), esta bug.

La micion consiste en lanzarle una lanza a un monstruo marino y matarlo , El bug consiste en que la lanza no mata al monstruo solo lo hiere y el despues te mata.

**Comment by franpr-zz** [comment]
La micion "El Poder de la Luz" esta BUG (http://es.wowhead.com/quest=26918), lo que sucede es que al lanzar "Sentencia" a una de las dianas de villa norte deberia completar la micion lo que no sucede.

**Comment by lomero** [comment]
Debes reportar cada misión por separado y con el formato especifico que usa el staff de lo contrario te lo borraran el reporte

**Comment by Monleon** [comment]
Si mal no recuerdo la misión del emisario, no consiste en matarlo con el tridente, sino sólo dejarlo herido para rematarlo con tus spells luego.

**Comment by nayan87** [comment]
monleon está en lo cierto, debes dejarlo herido y luego rematarlo, si estais haciendo quest a level máximo os aconsejo quitaros las armas y usar spells de bajo potencial de daño porque muchas misiones requieren de una mecánica del npc que si te la saltas pues o no te da el objeto o no te la cuenta como echa, os recomiendo SIEMPRE mirar en wowhead ante dudas de este tipo, Suerte y buena caza¡
