### ISSUE TITLE
[Paladin] Comunión

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#3862]
http://cata.openwow.com/spell=31876
El problema que surge con este talento, es que al poner bendición de poderío (ID: 19740)
el talento es como si desapareciese y por tanto es como si no lo tuviesemos.
Daño con arma sin el talento:
![image](https://cloud.githubusercontent.com/assets/3939699/3614800/0aaf77e0-0dc3-11e4-8e23-fb55c65019be.png)
Daño con arma con bendición de poderío:
![image](https://cloud.githubusercontent.com/assets/3939699/3614805/18845b06-0dc3-11e4-8798-cc4c2af00612.png)
Daño con arma con el talento:
![image](https://cloud.githubusercontent.com/assets/3939699/3614821/2fb941ce-0dc3-11e4-9eef-dba7d52f6aab.png)
Como se puede ver al activar el talento, la bendición de poderío se quita.
Daño con arma con el talento y con la bendición de poderío:
![image](https://cloud.githubusercontent.com/assets/3939699/3614845/5866be4e-0dc3-11e4-8042-e291f6d3fe6c.png)

**Comment by efectokoleos** [comment]
arreglado
