### ISSUE TITLE
MISION: Cimientos de venganza

### ISSUE THREAD

**Issue by nayan87** [RoDNet/Bugtracker-Infinium-4.3.4#3863]
Buenas noches, esta misión falla en cuanto a que no cuentan las muertes cerca de las fuentes de almas, he probado todas las fuentes disponibles, pero aun así no los cuenta. Debo añadir que el buffo de proximidad si lo pone correctamente incluso la animación posterior. Os dejo un link.

http://es.wowhead.com/quest=12668/cimientos-de-venganza#screenshots

**Comment by Kiritoo** [comment]
Arreglada, falta reiniciar.
