### ISSUE TITLE
MISION: Combustible para el fuego

### ISSUE THREAD

**Issue by nayan87** [RoDNet/Bugtracker-Infinium-4.3.4#3865]
En esta la dinámica si falla, las abominaciones o bien desaparecen o bien matan a los trolls pero no cuenta como matados, a parte el cabecilla drakkari no aparece y por tanto no contabiliza. Os adjunto el link.

http://es.wowhead.com/quest=12690/combustible-para-el-fuego

**Comment by Kiritoo** [comment]
Arreglada, falta reiniciar.
