### ISSUE TITLE
[Mago] Talento Furia de arrabio

### ISSUE THREAD

**Issue by Savian123** [RoDNet/Bugtracker-Infinium-4.3.4#3868]
Buenas como dice el talento Furia de arrabio cuando el objetivo esta por debajo del 35% se le pega un 12% mas con los 3 puntos activos pero como se ve en estas capturas 

mi agostar le pega aprox. 3800 con mas de 35% de vida
http://subefotos.com/ver/?1a76ca13022980c5aa67f7109f1bffedo.png

y aqui aun con menos del 35% de vida le pego exactamente lo mismo 
http://subefotos.com/ver/?f70e30c4a3a5fa78ad1dfffbb782a2f5o.png

Aqui os dejo el efecto 

Furia arrabio (Molten Fury )

http://subefotos.com/ver/?9ca0e2ae4b0070053a630cc35c053f90o.png

Furia arrabio con 3 puntos 

http://subefotos.com/ver/?e9faf7e1443a13a18f1eb0101166f073o.png

**Comment by Kiritoo** [comment]
Cuales son los ids? Bajate el addon Idtip que te los dice al lado de la descripción del hechizo.

**Comment by Savian123** [comment]
ID = 86880 siento no haberlo puesto asi de un buen principio ^^ gracias por la atencion

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
