### ISSUE TITLE
[Cazador-Bestias-Exoticas] Sambas y Koroma

### ISSUE THREAD

**Issue by Ahse** [RoDNet/Bugtracker-Infinium-4.3.4#3869]
Hola GM por favor ponga  estas bestias  activas   aquí le dejo el link de la descripción 

http://es.wowhead.com/npc=50159/sambas 
 http://es.wowhead.com/npc=50138/karoma

**Comment by rubiosoy** [comment]
habia puesto un ticket preguntando por lo mismo asi que borrare el ticket a e la espera de que contesten este. son2 pnj muy chulos que deverian estar presentes

**Comment by efectokoleos** [comment]
en el proximo reinicio deberian estar en algun punto aleatorio de tierras altas crepusculares
