### ISSUE TITLE
[Talentos] Matanza rápida

### ISSUE THREAD

**Issue by Hellythium** [RoDNet/Bugtracker-Infinium-4.3.4#3870]
Buenas, el problema con el talento ahora es que ya no se consume para nada el bufo después de matar a algo que nos otorgue experiencia u honor, por lo tanto no se da la bonificación de daño a los disparos mencionados en el talento.

**Comment by Kiritoo** [comment]
Explicate mejor, el aura salta al matar a un objetivo que aporta honor u experiencia.

**Comment by Hellythium** [comment]
Si, el aura salta, pero lo que pasa es que no se consume al ser utilizado un disparo firme, de cobra o de puntería por lo cual no hay bonus del 20% de daño en esos disparos

**Comment by Monleon** [comment]
Pero esta haciendo ese daño aumentado mientras dura el buff?
Cual es el problema? Que no aumenta el daño? O que lo aumenta pero el buff no se desvanece?

**Comment by Hellythium** [comment]
No, no está haciendo el aumento del daño, solo aparece el buff como decoración, porque en la descripción dice muy claramente ''Aumenta en un 20% el daño infligido de tu siguiente disparo de cobra, disparo firme o disparo de puntería'' (bueno no exactamente con esas palabras, pero si), o sea que al utilizar cualquiera de esos tres disparos el buffo debería de consumirse, pero no ocurre ninguna de las dos, ni se consume el buffo ni aumenta el daño.

**Comment by Kiritoo** [comment]
Hola estoy revisandolo y si hace el daño.
Estoy pegando Normal 8900 y Critico 19 sin aura de Matanza rápida.
Con el talento estoy pegando 10100 y 21252 de critico - Disparo firme., con lo cual si está aumentando el daño.
Las cifras parecen exageradas pero porque tengo anillo de testeo, con disparo de punteria estoy pegando 85k y 105k con el aura.

Ahora hablemos de cuando tiene que desaparecer el aura efectivamente tiene que desaparecer al usar disparo de cobra, firme o punteria que es lo que falta por mirar.

Arreglado.
