### ISSUE TITLE
Hechizo "Rastrear Humanoides" (Druida) no aparece

### ISSUE THREAD

**Issue by lKuroko** [RoDNet/Bugtracker-Infinium-4.3.4#3874]
Hace poco hice la compra del hechizo "Rastrear Humanoides" para el druida, sin embargo este hechizo no aparece en mi lista de hechizos pese a que la compra en efecto se realizo ya que el Instructor NPC dice que la habilidad ya la conozco y por tanto no me permite comprarla de nuevo. Trate desconectándome y conectándome de nuevo y aun asi la habilidad no aparece.

**Comment by Monleon** [comment]
Te aparece y debes activarla en el rastreador (en el minimapa).
