### ISSUE TITLE
Zeppelin de entrañas a orgrimmar

### ISSUE THREAD

**Issue by snowng** [RoDNet/Bugtracker-Infinium-4.3.4#3876]
Estaba iniciando el viaje desde el zeppelin con mi elfa de sangre Aerwen cuando de la nada mi elfa se cae al vacío y muere en el mar, luego de esperar 6 minutos para liberar el espíritu el fantasma no se mueve y tampoco aparece en algún cementerio, sigue en el vacío sin lograr salir de ahí. Agradecería mucho una solución.

**Comment by Compresor** [comment]
Pon un ticket ingame para que te saquemos de ahi.
