### ISSUE TITLE
LA DOBLE ESPESIALIDAD Y OLVIDAR TALENTOS ESTAN BUG

### ISSUE THREAD

**Issue by pokesun** [RoDNet/Bugtracker-Infinium-4.3.4#3877]
SOY PALA Y INTENTO OLVIDAR MIS TALENTOS Y ASER LA DUAL Y NO PUEDO MI NIVEL ES 67  KRATN AYUDAAAA

**Comment by Monleon** [comment]
Prueba a hablar con otro instructor. Si no te deja, pon un ticket online, porque esto funciona
