### ISSUE TITLE
[Guerrero] Regeneración Iracunda

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#3878]
http://es.wowhead.com/spell=55694

El problema está en que al usarlo siendo tanque, se buguea. Al tener la venganza activa te marca como si puedieras activar regeneración pero no te deja, y aun teniendo el buffo de Enfurecer, tampoco te deja activarla.
Para solucionar el problema tienes que quitarte venganza y después usar regeneración, lo que conlleva perder todo el poder de ataque conseguido hasta el momento.

**Comment by efectokoleos** [comment]
arreglado
