### ISSUE TITLE
[Guerrero] Verdugo

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#3879]
http://cata.openwow.com/spell=20502 (Rank1)
http://cata.openwow.com/spell=20503 (Rank2)

El problema es que no te otorga el buffo de augmento de velocidad de ataque al usar ejecutar (http://cata.openwow.com/spell=90806).

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
