### ISSUE TITLE
[Misión] Fiordo aquilonal - El botín de Sorlof

### ISSUE THREAD

**Issue by franpr-zz** [RoDNet/Bugtracker-Infinium-4.3.4#3882]
```
Nombre: El botín de Sorlof
Enlace: http://es.wowhead.com/quest=11529
Descripción: Capitán Ellis en  Fiordo aquilonal quiere que utilise los cañones de su barco para atacar un gigante Llamado Sorlof, y asi recuperar un escudo para completar la quest.
Problema:  No aprece sorlof tampoco el cañon con que disparar, y aparte en algun momento el barco se mueve y caes al vacio.
```

Capitán Ellis: http://es.wowhead.com/npc=24910
Sorlof: http://es.wowhead.com/npc=24914
Botin de solof:http://es.wowhead.com/spell=45070

**Comment by nayan87** [comment]
Emmm vamos  a ver  el tema está en buscar las cosas,Sorlof aparece, el cañón tambien y la misión se puede hacer sin ningún problema, el tema está en buscar al bicho (que no es precisamente pequeño) lo matas y te suelta el botín, son cosas que se deben probar antes de postear....

Para más información la unica quest de esa cadena que no va del todo es la de harry lunargenta
