### ISSUE TITLE
[Misión] Tierras Altas Crepusculares - Una muerte digna de un Faucedraco

### ISSUE THREAD

**Issue by franpr-zz** [RoDNet/Bugtracker-Infinium-4.3.4#3883]
Nombre: Una muerte digna de un Faucedraco
Enlace: http://es.wowhead.com/quest=27813
Descripción: Mackay Barbafuego quiere que mate 6 Faucedraco.
Problema: No puedo atacar a los faucedracos y tampoco me aparecencomo como faccion para elejir "En guerra".

**Comment by Kiritoo** [comment]
Arreglada cuando se reinicie.
