### ISSUE TITLE
[Chaman] Trueno ensordecedor

### ISSUE THREAD

**Issue by Lobomaniac** [RoDNet/Bugtracker-Infinium-4.3.4#3884]
Rango 1 - 88756
Rango 2 - 88764

El escudo de rayos no pilla cargas impidiendo la regeneración de mana y el daño extra tanto pon contacto como en el choque de tierra.

**Comment by efectokoleos** [comment]
ya da mana pero lo de las cargas ni idea de porke no las da..

**Comment by Dazand** [comment]
Este bug es reciente, verdad? Antes no estaba.

**Comment by edwyr** [comment]
El escudo ahora en mejora, cuando lo activas solo se pone con una carga, y si le das muchas veces puedes llegar a ponerte hasta 9 cargas clickando, y cuando te pegan se te quitan, da igual que tengas el glifo

**Comment by efectokoleos** [comment]
el escudo esta arreglado

**Comment by Lobomaniac** [comment]
El escudo sigue llendo fatal lo siguiente sigue sin pillar cargas ni funciona el glifo ni el daño extra del choque de tierra va

**Comment by edwyr** [comment]
El glifo que antes funcionaba, ahora no funciona, el de que las cargas no bajan de 3

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
