### ISSUE TITLE
Personaje muerto en medio del mar

### ISSUE THREAD

**Issue by snowng** [RoDNet/Bugtracker-Infinium-4.3.4#3887]
Reabro el tema ya que el anterior creado lo cerraron sin solucionarlo
Mi elfo de sangre (Artanis) al tomar el zeppelin a entrañas murio de manera inesperada y cayo por algún motivo al mar, luego de eso murió y quedó ahí, no aparece en algún cementerio y tampoco me puedo mover desde el lugar en que estoy. Adjunto archivo para corroborar lo antes dicho: 
![img-20140723-wa0029](https://cloud.githubusercontent.com/assets/8219516/3680012/d799e8b2-12aa-11e4-9076-f219e43c4ce3.jpg)

**Comment by Monleon** [comment]
Enviado a dalaran
