### ISSUE TITLE
Escudo de relampagos

### ISSUE THREAD

**Issue by Lobomaniac** [RoDNet/Bugtracker-Infinium-4.3.4#3889]
El escudo de relampagos del elemental no sube cargas con lo cual el choque de tierra no pega nada bajando muchisimo el dps de chaman elemental thx

**Comment by Kiritoo** [comment]
El escudo no sube cargas si no tienes el talento, en su caso tendrias que reportar el talento.
Si reportas algo añade sus ids para saber que hechizo es en particular.
Antes de reportar nada comprueba que no lo hayan reportado.
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3884
Cierro, saludos.
