### ISSUE TITLE
[Pesca] Nodos de pesca

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#389]
Los bancos de peces no se pueden pescar. Cuando salta la caña, vas a coger el botín y ves qe no hay botín.

**Comment by crowel** [comment]
Quiero comentar que los bancos de peces en los que he pescado hasta ahora funcionan correctamente.
Voi cerrar Issue, si encuentras alguno que no funcione, especifica cual porfavor.
Un saludo.
