### ISSUE TITLE
[Error interno] Loot

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#3892]
A la hora de lotear, pasan cosas raras:

1- El tiempo desde que todos los miembros del grupo seleccionan Necesidad/Codicia/Desencantar, y la repartición al ganador es altísima, hablo de minutos, y a veces pasa el error 2.

2- Al dar a desencantar todos los miembros del grupo menos uno que da a pasar, no se lleva nadie el loot, sino que sale como que todos han pasado y se queda en el cuerpo muerto.

Screen: http://i.gyazo.com/1a4082806dbbd3b60b8f1dcd34c8216c.png

**Comment by Kiritoo** [comment]
Arreglado todos los fallos, tiempo de despojo, el desencantar, los numeros elevados... etc..
Funcionando al 100% falta compilar.
