### ISSUE TITLE
lluvia de destruccion vallefresno

### ISSUE THREAD

**Issue by bulkatoz** [RoDNet/Bugtracker-Infinium-4.3.4#3894]
para completar esta mision te tiene que transformar en diablillo lo cual nunca susede corrijan este bug gracias

nota: tiene un monton de busg su server tratyen de corregirlos veo reportes de haci casi mas de 6 meses esten atentos gracias

**Comment by nayan87** [comment]
tu si que tienes bugs en tu orto-grafía XDDDDDDDD

PD: atentamente saludos del maestro cultural del server

**Comment by Kiritoo** [comment]
Todo reporte que se cree cuando otro usuario ya lo tenga reportado antes se borrara de inmediato, solo tendrá una simple excepción, que será cuando el nuevo reporte creado contenga más información o este mejor detallado al ya existente,se borrara el antiguo, en todos los demás casos será borrado.

Los bugs se deben reportar de uno en uno con sus correspondientes datos, todo Issue creado que contenga más de un bug se cerrara.

Si alguien encuentra algún fallo en un bug reparado con anterioridad debe de crear un Issue nuevo, jamás debe comentar en el cerrado a no ser que un miembro del staff le diga de hacerlo en el momento del cierre.

No  está permitido crear Issues con temas que no estén relacionados con el servidor, para ser más exactos con el reporte de fallos, es un bugtracker, para ello contamos con este foro. Todos los Issues con contenido invalido serán borrados si en un supuesto caso surgiera un abuso de está norma se podría sancionar.

Cualquier comentario fuera de lugar al servidor, jugadores o miembros del staff sera duramente sancionado, el Bugtracker está única y exclusivamente para reportar los fallos del juego, nada más.

Respecto al bugtracker Como comente en el apartado anterior esta única y exclusivamente para reportar fallos no para ser un chat, para ello está el foro.

El reportar los fallos es una ayuda a toda la comunidad, esto no quiere decir que lo reparemos en 5 minutos como muchos piensan, arreglar los bugs requiere tiempo y dedicación,  jamás de debe de presionar a los miembros del staff que tratan de solventarlos.

**Comment by Kiritoo** [comment]
Seguimos de https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3254
