### ISSUE TITLE
Escudo de relampagos el regreso

### ISSUE THREAD

**Issue by Lobomaniac** [RoDNet/Bugtracker-Infinium-4.3.4#3896]
Habeis reparado lo de las tres cargas pero ahora si suviera con cada descarga de ralampagos ya seria la leche para que el choque de tierra pegara bien ;) thx

**Comment by Kiritoo** [comment]
Si porfavor estamos con ello, ya que tenemos muchas cosas que arreglar pero tenemos esta pendiente, solo nos falta lo del talento para que aumente y ajustar el glifo para que no baje de 3 cargas.
Gracias por avisar, igualmente los reportes no se exponen asi y teneis que comprobar que no esten ya reportados.
