### ISSUE TITLE
[DK] Bug Golpe Letal

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#39]
Golpe letal del dk no esta haciendo sanacion alguna.

deberia curar minimo el 7% de la salud total del DK

http://es.wowhead.com/spell=49998/golpe-letal

**Comment by SherBlader** [comment]
Deberia curar minimo el 7% de la salud total del dk

**Comment by ghost** [comment]
Quería agregar que la unica forma de que cure el golpe letal es si tiene peste de sangre y/o fiebre de escarcha, pero en vez de curar 7%, cura un 23% de la vida del DK por enfermedad que tenga el objetivo.
No sé si es un problema de los DK en gral. pero me gustaría que le echen un ojo.
Gracias y saludos.

**Comment by efectokoleos** [comment]
ya esta arreglado, ahora falta la maestria pero esta spell ya funciona correctamente, cierro.
