### ISSUE TITLE
[Intendente] Intendente Krom'Gar

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#390]
El intendente Krom'Gar http://es.wowhead.com/npc=42028/intendente-kromgar
de Sierra Espolon no vende nada, solo muestra un dialogo.

![wowscrnshot_071213_042736](https://f.cloud.github.com/assets/4895839/787273/d4fe7e2c-ead5-11e2-9a82-1f662c3a2409.jpg)

Que venda vainas!!, que me sirven xD

**Comment by crowel** [comment]
Fix
