### ISSUE TITLE
[Misión] Corona de Hielo/Fiordo Aquilonal - Una espada de Campeón

### ISSUE THREAD

**Issue by franpr-zz** [RoDNet/Bugtracker-Infinium-4.3.4#3903]
Nombre: Una espada de Campeón
Enlace:http://es.wowhead.com/quest=13603
Descripción:Recupera la espada de Lago Fresno y llévasela al mariscal Jacob Alerius en los Campos del Torneo Argenta. 
Problema: Despues de besar a TODAS las ranas del lago fresno aparece la Doncella del lago Fresno (http://es.wowhead.com/npc=33220/doncella-de-lago-fresno) me habla y me ofrece la espada pero esta no aparece y luego la doncella desaparece.
Espada del Lago Fresno:http://es.wowhead.com/item=44981
Invocar espada del lago frsno:http://es.wowhead.com/spell=62554
Adjunto imagenes de la doncella cuando no me da la espada:

Apareciendo:
![wowscrnshot_072814_042641](https://cloud.githubusercontent.com/assets/8185443/3717625/cbf7a1f8-1628-11e4-911c-d64415188815.jpg)
No Dando Nada:
![wowscrnshot_072814_042653](https://cloud.githubusercontent.com/assets/8185443/3717624/cbf2bde6-1628-11e4-87b2-5cf9bd220934.jpg)
Desapareciendo:
![wowscrnshot_072814_042656](https://cloud.githubusercontent.com/assets/8185443/3717623/cbed7304-1628-11e4-8843-43bc12aea49b.jpg)

**Comment by nayan87** [comment]
Así es como se hace un post leche¡¡¡ confirmo todo lo que ha puesto franp¡ que yo recuerde era la única diaria de torneos que no funcionaba, seguiré testeando a ver que me encuentro, saludos¡

**Comment by ghost** [comment]
Arreglada.

**Comment by franpr-zz** [comment]
Cancele la micion ,borre la carpeta cache, pero aun asi no me da la espada. Importa q el que me halla dado la micion halla sido el valeroso de ventormenta??
