### ISSUE TITLE
[Paladin] Talento: Proposito Divino

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3905]
Nombre: Proposito Divino
ID:85117/86172
Enlace: http://wow.freakz.ro/spells.php?spell=86172
Descripcion: Los siguientes ataques tienen un 7%/15% probabiliad de hacer que la siguiente facultad de poder sagrado no consuma poder sagrado pero que se lance como si se consumiesen 3 cargas de poder sagrado:
-sentencia 
-exorcismo
-veredicto del templario
-tormenta divina
-Inquisicion
-Colera sagrada
-Martillo de colera
Problema: No se esta activando con Veredicto del templario (85256) tampoco con Inquisicion (84963) y segun la descripcion deberia

**Comment by Kiritoo** [comment]
Esto está arreglado cuando se compile.

**Comment by F4NT4SM4** [comment]
ya estaba arreglado? e.e
es que no lo vi en el changelod

**Comment by F4NT4SM4** [comment]
si efectivamente ya funciona con veredicto del templario pero he dado como 30 inquisicion y no se activo
