### ISSUE TITLE
[Hermandad] Viaje en Grupo

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3906]
Nombre: Viaje en Grupo
ID:83967
Enlace: http://wow.freakz.ro/spells.php?spell=83967
Descripcion: Invoca a todos los miembros del grupo o banda a la ubicacion actual del taumaturgo. No se puede usar durante el combate y solo se peude lanzar al aire libre o cerca de la entrada de una mazmorra o banda
Problema: solo esta invocando al objetivo amigo que tengamos deberia de invocar a todos los miembros del grupo/banda

**Comment by efectokoleos** [comment]
la parte de invocar a todos la tengo hecha, me falta saber si solo se puede usar al aire libre o tambien en interiores de casas y eso

**Comment by F4NT4SM4** [comment]
en interiores se referira a dentro de mazmorra y eso

**Comment by F4NT4SM4** [comment]
bueno no tendria sentido si un picaro va sigilo al lado de un rey de la faccion contraria invocando a toda la raid supongo que a dentro de casas, edificion,etc no deberia

**Comment by efectokoleos** [comment]
arreglado
