### ISSUE TITLE
[Chaman] Terremoto

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3907]
Nombre: Terremoto
ID:61882
Enlace: http://wow.freakz.ro/spells.php?spell=61882
Descripción:  You cause the earth at the target location to tremble and break, dealing 325 (+11% SP)+NATURE_SP*0.11 Physical damage every 1 sec to enemies in an 8 yard radius, with a 10% chance of knocking down affected targets. Lasts 10 seconds.
Problema:el daño esta muy bajo actualmente le hago 200 al dummy

**Comment by Kiritoo** [comment]
El daño esta correcto.
Actualmente le pego 538 con 2076 de sp
