### ISSUE TITLE
[Chaman] Desatar Vida

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3908]
Nombre: Desatar Vida
Desatar Vida: 73685
Enlace: http://wow.freakz.ro/spells.php?spell=73685
Descripción: Desatar este encantamiento sana al objetivo amistoso  y aumenta....
Problema:cuando tengo un objetivo hostil/enemigo no me deja usar desatar vida tengo que si o si quitar el tarjet del enemigo o no tener ningun tarjet. como cualquier otro hechizo sanacion si tengo el tarjet un enemigo la curacion va directo a mi pj

**Comment by efectokoleos** [comment]
arreglado, falta compilar
