### ISSUE TITLE
[Glifo][Chamán] Glifo de escudo de relampagos

### ISSUE THREAD

**Issue by Kushirin** [RoDNet/Bugtracker-Infinium-4.3.4#3911]
Nombre: Glifo de escudo de relampagos.
Enlace: http://wow.freakz.ro/spells.php?spell=55448&name=glyph-of-lightning-shield
Descripción: Tu escudo de relampagos ya no puede quedarse por debajo de 3 cargas.
Problema: Se descargan igualmente cuando se activan, no visualmente, pero al 3º activación, el buffo desaparece.

**Comment by Lobomaniac** [comment]
Ahora suben las cargas del escudo de relampagos pero al consumirse no dan el daño extra al choque de tierra ;( puede mirarlo alguien

**Comment by Kushirin** [comment]
Crea un reporte nuevo porque no se si eso tiene que ver con el glifo en cuestión.

**Comment by efectokoleos** [comment]
arreglado
