### ISSUE TITLE
[Errores de clases] Aumento de dot por celeridad

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3912]
Nombre: Aumento de dot por celeridad
Descripción: Los hechizos con dot al llegar cierta cantidad de celeridad aumenta sus dots 
Problema: me aumento toda la celeridad y nada que aumenta los dots 
Este error tendran que acomodar 1x1 los hechizos? si es a si coloco los hechizos aqui  o por separado en cada issues con tema (dot/celeridad) colocaria cuanta celeridad haria falta en tal hechizo para subir el dot

considero yo que esto es importante afecta a muchas clases: druida,sacer,brujo,mago, chaman

**Comment by Monleon** [comment]
Estas seguro de ello? Acabo de probar varias clases y funciona correctamente. Debes revisar varias guias en las que te diga con que X% de celeridad obtienes un tick extra.
Si te sirve acabo de probarlo con 20k de haste y los ticks me los hacia cada 0.6 seg

**Comment by F4NT4SM4** [comment]
bueno estoy probando con un addon que me dice cuanta celeridad me falta para cada tiks 
buscare otro medio de informacion sobre los tiks

**Comment by F4NT4SM4** [comment]
segun mi addon y informacion que saque de foro blizzard con 9.9% deberia agregarle un tik a affliccion inestable pruebo con 2% celeridad 5 tiks normal me pongo 13.85% celeridad siguen siendo 5 tiks

**Comment by F4NT4SM4** [comment]
cada hechizo tiene pide un diferente % de celeridad para el tik puede que teneis el mismo % para todas las spells o puede ser que solo son algunas spells que no les esta afectando la celeridad y casualmente fue las que probe yo

**Comment by Monleon** [comment]
Con el druida equilibrio me funciona perfectamente

**Comment by Monleon** [comment]
Sacerdote: Fuego sagrado,  VT, DP, SW:P idem. Además cada spell con un limite de celeridad distinto

**Comment by F4NT4SM4** [comment]
intonce son algunas spells que tienen la celeridad mal?
pruebo 1x1 y reporto 1x1 aqui?

**Comment by Monleon** [comment]
Asegurate por lo menos que tengas un 25% de celeridad. La duración del dot también te la reduce?

De todas maneras le echare un vistazo mas a fondo en la medida de lo posible

**Comment by Monleon** [comment]
Idem con el brujo y aflicción inestable. Tick base 3seg, 10k de haste 1.7seg; 20k 1.1seg
