### ISSUE TITLE
[Misión] [Mulgore][Druida] "Toque de Rejuvenecimiento"

### ISSUE THREAD

**Issue by yavin201** [RoDNet/Bugtracker-Infinium-4.3.4#3913]
Es una de las primeras misiones que te da el instructor de druidas tauren. Te pide que aprendas esta habilidad y que sanes a un Valiente herido en el campamento Narache. El problema es que los Valientes heridos tienen la salud al máximo y cuando les lanzas el hechizo no te cuenta como hecho.
En wowhead no aparece esta misión ya que no está actualizada la cadena a la que pertenece, y en su lugar a aparece esta: "Fuego Lunar" http://es.wowhead.com/quest=27067

**Comment by Kiritoo** [comment]
Arreglado cuando se reinicie.
