### ISSUE TITLE
ALAMUERTE EN EL CRUZE EN LOS BALDIOS WTF

### ISSUE THREAD

**Issue by bulkatoz** [RoDNet/Bugtracker-Infinium-4.3.4#3915]
ME CONECTE Y APARECIO UN DRAGON LLAMADO ALAMUERTE Y MATO A TODOS EN EL PUEBLO INCLUYENDOME NO SE SI ES UN BUG O ES NORMAL LES AGRADECERIA INFORMARME GRACIAS

**Comment by bulkatoz** [comment]
AYUDAAAA NO ME DEJA REVIVIR ME MATA A CADA RATO EL DRAGON

**Comment by F4NT4SM4** [comment]
es normal bliz el dragon ese es el boss final del cataclysm sale a quemar cada cierto timepo y diferentes zonas mala suerte que tocara hay :s

**Comment by bulkatoz** [comment]
AA OKM ESO NO LO SABIA YO QUE VENIA A MI INSTRUCTOR Y ESTE DRAGON QUE ESTA PARADOTE AQUI MATANDO GENTE T_T

**Comment by Dekadencee** [comment]
El npc que comentas aparece en una zona aleatoria una vez a la semana, en este caso ha aparecido en Los Baldios.

Es un evento implementado por Blizzard en la expansión Cataclysm y otorga el logro [Permanece en el fuego](http://es.wowhead.com/achievement=5518/permanece-en-el-fuego) logro el cuál te debería haber sido entregado.

Un saludo
