### ISSUE TITLE
[Paladin] Arrepentimiento 

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3917]
Nombre: Arrepentimiento
ID:20066
Enlace: http://wow.freakz.ro/spells.php?spell=20066
Descripcion: Pone al objetivo enemigo en estado de meditacion, lo que lo incapacita durante un maximo 1 min. EL DAÑO QUE INFLIJAN OTRAS FUENTES DISTINTAS A CENSURA DESPERTADA AL OBJETIVO. Solo funciona contra demonios, dragonantes, gigantes, humanoides y no-muertos.
Problema: el daño de censura (31803) esta quitando arrepentimiento (20066) no deberia

**Comment by Kiritoo** [comment]
En el nombre escribiste Proposito divino.

**Comment by F4NT4SM4** [comment]
bad para no tener que escribir todo denuevo copy y paste xD

**Comment by paellaencol** [comment]
Añado además lo que puse en su momento https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2862

SI tienes un escudo de absorción sobre ti, y resultas afectado por cualquier daño diferente a 31803 (pese a que no te repercuta en tus HPs ya que tienes un escudo de absorción), debería romperse el efecto de arrepentimiento inmediatamente (sin embargo actualmente se mantiene).

**Comment by F4NT4SM4** [comment]
eso tambien se le aplica a otras skill como war abrumar se activa cuando desgarrar inflige daño pero contra un sacer que tiene escudo absorcion nunca se me activa

**Comment by efectokoleos** [comment]
esta parte esta arreglada
