### ISSUE TITLE
Personaje "atascado" en Vashj'ir

### ISSUE THREAD

**Issue by lKuroko** [RoDNet/Bugtracker-Infinium-4.3.4#3919]
Buenas, resulta que cunado hacia una mision en Vashj'ir especimficamente en la Caverna Luzumida con el NPC "Clarividente Gadra", donde debes compartir una vision con este, mi personaje quedo atrapado en el estado de "espiritu" que se tiene durante la vision del clarividente. Por lo tanto no logro ejecutar ningun tipo de accion, estoy atrapado como espiritu.

Esperando una pronta solucion, de ante mano agaradezco su atencion.

**Comment by bulkatoz** [comment]
debajo junto a tus bolsas de inventario aprietas el boton "?" de color rojo y ahi dice atasco de jugador y con eso resuelves tu problema

**Comment by efectokoleos** [comment]
pon un ticket
