### ISSUE TITLE
Xariona

### ISSUE THREAD

**Issue by Centinela-zz** [RoDNet/Bugtracker-Infinium-4.3.4#392]
El NPC "Xariona" (id:50061) no castea ninguna magia.... es una piñata y creo que su respawn también está mal.

**Comment by Centinela-zz** [comment]
Además el loot no va correctamente tampoco

**Comment by DatJetto** [comment]
http://es.wowhead.com/npc=50061

**Comment by crowel** [comment]
El loot está correcto, falta revisar las habilidades.

**Comment by Kiritoo** [comment]
Fix
