### ISSUE TITLE
[Chamán] Ira desatada

### ISSUE THREAD

**Issue by edwyr** [RoDNet/Bugtracker-Infinium-4.3.4#3922]
http://cata.openwow.com/spell=30808

Este talento da un buffo que no esta siempre activo, es decir, a veces lo tienes, aveces no, si cargas un mapa se quita, aveces cuando desconectas y conectas aparece, otras no, basicamente aparece cuando quiere. Deberia estar permanentemente activo.

**Comment by F4NT4SM4** [comment]
me imagino que se te va cuando te aplican un buff parecido como poderio, poderio de apominacion y el aura del caza

**Comment by Monleon** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3820

Con reportarlo una vez es suficiente.  Gracias
