### ISSUE TITLE
talento ojo por ojo paladin

### ISSUE THREAD

**Issue by Devyal** [RoDNet/Bugtracker-Infinium-4.3.4#3925]
este talento creo que no refleja el daño mágico que debería al atacante,
no funciona. (40% de probabilidad de reflejar 30% de daño mágico al atacante)

**Comment by F4NT4SM4** [comment]
contra jugadores o npc?
los jugadores tenemos temple a si que no se nota nada

**Comment by Devyal** [comment]
igual deberia reflejar algo supongo y no refleja nada

**Comment by Monleon** [comment]
Creo? Esto lo probe hace una semana y reflejaba daño en raids y también contra jugadores
