### ISSUE TITLE
[Misiones][Silithus] Thunderaan el Hijo del Viento

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3927]
Buenas.
• Nombre: Thunderaan el Hijo del Viento
• Enlace: http://es.wowhead.com/quest=7786
• Descripción: Para liberar a Thunderaan el Hijo del Viento de su cárcel, debes entregarle al alto señor Demitrian en Silithus la mitad izquierda y la derecha del vínculo del Hijo del Viento, 10 barras de elementium encantado y la esencia del Señor del Fuego. 
• Problema: Una vez entregada la misión, el PNJ Alto señor Demitrian (http://es.wowhead.com/npc=14347) debería invocar al PNJ Príncipe Truenoraan (http://es.wowhead.com/npc=14435) pero no sucede nada. El segundo problema es que la única forma de invocarlo es completando esta misión, asi que cuando lo arreglen, no tengo forma de seguir con la cadena D:
Desde ya muchas gracias.

**Comment by nayan87** [comment]
Dios ya conseguiste las 10 barras de elementium encantado¿?¿?¿? acojonante, esa era la parte dificil, ahora a esperar a que lo apañen¡ suerte¡

**Comment by ghost** [comment]
Reparada.

Ahora al entregar la misión aparecerá el Príncipe Truenoraan, en tu caso abre un ticket y te soluciono el problema de que no apareciese antes.
