### ISSUE TITLE
[Picaro] Glifo de Patada

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3928]
Nombre: Glifo de Patada
ID:56805
Enlace: http://wow.freakz.ro/spells.php?spell=56805
Descripcion: Aumenta el tiempo de reutilizacion de tu facultad patada 4s, pero este tiempo de reutilizacion se reduce 6s cuando patada interrumpe con exito un hechizo
Problema: no funciona siempre mi cd de patada es 14s y deberia bajar a 8s si interrumpi un hechizo con exito

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, ya no daremos soporte al actual
