### ISSUE TITLE
Puntos Por Victoria en BG

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#393]
La verdad no se si esta bug o no, solo queria comentar que antes de la actualizacion las bgs daban en promedio 500 puntos de honor por victoria,
ahora dan de 150-200 por mucho, y por derrota antes de actualizar daban 100, ahora no dan ni 50.

No se si fue ideado por los gm, solo lo pongo para tener en cuenta, no se si esten bien o mal.

**Comment by Dekadencee** [comment]
Es ideado por nosotros, las recompensas se han ajustado puro blizzlike.
De todos modos gracias por reportar ^^
