### ISSUE TITLE
FRONDAVIL MISIONES BUG CASI TODAS

### ISSUE THREAD

**Issue by bulkatoz** [RoDNet/Bugtracker-Infinium-4.3.4#3930]
CASI TODAS LAS MISIONES DE FRONDAVIL ESTAN BUG NO TODAS PERO SI LA MAYORIA Y ES FRUSTRANTE :'(

**Comment by Monleon** [comment]
Links? Faccion? Problemas de cada una? O nos paramos a mirarla una a una?
