### ISSUE TITLE
NO PUEDO REVIVIR :(

### ISSUE THREAD

**Issue by bulkatoz** [RoDNet/Bugtracker-Infinium-4.3.4#3933]
ESTOY EN LA MISION DE LOS CABALLEROS DE LA MUERTE "EL REINO DE LAS SOMBRAS" NO ME MANDABA AL REINO Y ME APARECIA COMO SI ESTUVIERA EN COMBATE (PASA MUY SEGUIDO) Y ME DESCONECTE CUANDO ME CONECTE DE NUEVO ESTABA MUERTO YA DENTRO DEL REINO DE LAS SOMBRAS PERO NO PUEDO REVIVIR

**Comment by bulkatoz** [comment]
mi problema aun sigue T__T NO PUEDO REVIVIR me quede atrapado en el reino de las sombras en la mision "reino de sombras" estoy muerto y no me deja revivir :(

**Comment by JoakRoD** [comment]
1. No uses mayúsculas.
2. Pon ticket ingame para solucionártelo.

**Comment by bulkatoz** [comment]
ok gracias
