### ISSUE TITLE
[Mision] Las Islas Perdidas - Preparados, listos, ¡fuego!

### ISSUE THREAD

**Issue by Luis2403** [RoDNet/Bugtracker-Infinium-4.3.4#3934]
http://es.wowhead.com/quest=14244/
el lanzador de cohetes no aparece en el mapa

**Comment by Kiritoo** [comment]
Si lo sabemos, lo dejaremos asi temporalmente mientras trabajamos los phases de la zona, toma el portal que tenemos temporalmente por si no quieres esperar, gracias por el aviso.
