### ISSUE TITLE
Choque de tierra

### ISSUE THREAD

**Issue by Lobomaniac** [RoDNet/Bugtracker-Infinium-4.3.4#3935]
El choque de tierra no hace el daño que tendría que hacer al consumir las cargas de escudo de relámpagos en teoría con 9 cargas se consumen 6 que son ( 6 por 3000=18000 aproximadamente) mas el daño del choque que son algo mas de 4000 osea tendría que meter de base 22000 como poco podríais mirarlo thx.

**Comment by Monleon** [comment]
Choque de tierra debe hacer siempre el mismo daño independientemente de las cargas que se tengan. Es una spell que debe desencadenar fulminacion, pero no hacer el daño de esta (son dos spells distintas)

**Comment by Lobomaniac** [comment]
thx ya funciona  la fulminación ;)

**Comment by efectokoleos** [comment]
cierro
