### ISSUE TITLE
[DK] Golpe con Runa

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3937]
Nombre: Golpe con Runa
ID:56815
Enlace: http://wow.freakz.ro/spells.php?spell=56815
Descripcion: Golpea al objetivo y le inflige un 180% de daño con arma mas 2401p solo se puede usar en precensia sangre, o 10 despues de que el caballero de la muerte esquive o paren un ataque. este ataque no se puede esquivar, bloquear ni parar y genera una gran cantidad de amenaza
Problema: La segunda condicion de esquive/pare no deberia activarse estando en precensia sangre por que ya estando en precensia sangre me deja usarlo pero como se activa por la segunda condicion estando en precensia sangre se bugea y no me deja usarla mas en precensia sangre

**Comment by Monleon** [comment]
Ahora ya tiene los requisitos necesarios para ser activado. Y sin condiciones en presencia de sangre
