### ISSUE TITLE
no aparecen los grifos para volar 

### ISSUE THREAD

**Issue by bulkatoz** [RoDNet/Bugtracker-Infinium-4.3.4#3938]
en el bastion del ebano los grifos que te sirven para bajar no estan desaparecieron y ya no puedo bajar del bastion 

![no](https://cloud.githubusercontent.com/assets/8270066/3789423/7bfa7512-1aa2-11e4-84e9-e619652b7308.jpg)

**Comment by Monleon** [comment]
Cierra wow, borra cache y te deben aparecer.

**Comment by bulkatoz** [comment]
cerre borre cache y aun asi no aparecen
