### ISSUE TITLE
[Marcadores de Raid] Consola de raid

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#3940]
Bueno ya se que a mucha gente no le importara esta bug ya que no lo suelen utilizar pero para mi y la mayoría de los que explicamos los bosses de las raids es un útil indispensable para que la gente lo entienda ya que como siempre se ha dicho una imagen vale mas que 1000 palabras ya lo reporte cuando el server era 4.0.6 pero no se llego a arreglar nunca .

http://s2.subirimagenes.com/otros/previo/thump_9018982marcadores-raid.jpg

Como se ve en la imagen te deja seleccionar la banderita que quieres poner pero cuando lo pones sobre el terreno 

http://s2.subirimagenes.com/otros/previo/thump_9018983marcadores-raid2.jpg

No se pone la Marca ni nada por el estilo a la hora de explicar los bosses en la que la gente debera moverse lo mejor es poder tener esta herramienta de la consola de raid.

Asi deberia ser 

http://s2.subirimagenes.com/otros/previo/thump_9018984catanewraidmarker.jpg

Muchas Gracias espero que lo puedan arreglar

**Comment by sakuranobushi** [comment]
El error debería haber sido solucionado y se reflejara pronto en el servidor.
