### ISSUE TITLE
el tamaño de algunas pet es erronea

### ISSUE THREAD

**Issue by xxjuniorlll** [RoDNet/Bugtracker-Infinium-4.3.4#3941]
hola, quiero avisarles que el tamaño de los pets de los hunters a lvl alto son erroneos son muy pequeños DevilSaur, can del nuceleo, quimera ,rinoceronte y algunos mas  el unico pet que e queda a tamaño real CUANDO lo cazas es Jormungar , lobo , tigre, cangrejo , la bestia espiritu lobo ,oso bestia espiritu  hasta donde yo se desde el woltk  las pets eran un poco mas grandes miren 

http://www.youtube.com/watch?v=wirrLsx-P54&feature=player_embedded  minuto 1:30

unos videos para q me crean q el tamaño es real xq en el wow oficial es grande como este video

http://www.youtube.com/watch?v=NImOe3rlwa4     minuto:14.37

PD:el tamaño si importa y tu lo sabes

**Comment by Kiritoo** [comment]
Arreglado el tamaño de las pets exoticas, falta compilar.
