### ISSUE TITLE
Personaje atascado en el mar

### ISSUE THREAD

**Issue by salasj** [RoDNet/Bugtracker-Infinium-4.3.4#3942]
Andaba lvleando en Tierras de altas Crepusculares cuando subi a un zepelin y nose que paso y apareci en el mar sin poder hacer nada :S Quisiera que lo desbloquearan por favor..

PJ: CRAZYHUNT
Lugar: Tierras de altas Crepusculares

**Comment by ghost** [comment]
Para este tipo de cosas abre un ticket ingame.
