### ISSUE TITLE
no aparecen aun los grifos para volar 

### ISSUE THREAD

**Issue by bulkatoz** [RoDNet/Bugtracker-Infinium-4.3.4#3945]
hize lo que me comentaron cerre el cliente borre cache y aun no aprecen los grifos y no puedo bajar del bastion

**Comment by F4NT4SM4** [comment]
haste otro dk xD

**Comment by bulkatoz** [comment]
lo estaba pensando pero no, debe de haber solucion

**Comment by F4NT4SM4** [comment]
30 minutos volver a llegar a los grifos pero bueno :S

**Comment by bulkatoz** [comment]
me da weva aser las misiones de nuevo XD

**Comment by Monleon** [comment]
Me he creado un dk a propósito en este tiempo. Y no he tenido ningún problema para levearlo, ver grifos, etc. Has hecho ya todas las misiones? Si es así, para qué necesitas ir a la brecha?

**Comment by bulkatoz** [comment]
si estoy casi en la ultima mision y subi para comprar habilidades ya lo habia hecho antes pero cuando me conecte al dia siguiente no habia ningun jugador y no estaban los glifos sigo atarapado en el bastion y si uso la opcion de atasco para que me mande al cementerio me manda de nuevo arriba no tengo como bajar

**Comment by bulkatoz** [comment]
estoy en la mision la orden del rey exanime todo habia estado funcionando bien pero no puedo bajar de ninguna forma

**Comment by bulkatoz** [comment]
mira no hay ningun personaje en el bastion todos desaparecieron 
![wowscrnshot_080414_100622](https://cloud.githubusercontent.com/assets/8270066/3798930/2b31f298-1be9-11e4-890a-1b35f675c966.jpg)
![wowscrnshot_080414_100641](https://cloud.githubusercontent.com/assets/8270066/3798932/303fc350-1be9-11e4-88e6-d81804f8a487.jpg)
![wowscrnshot_080414_100730](https://cloud.githubusercontent.com/assets/8270066/3798933/34e53520-1be9-11e4-9527-341660c30c44.jpg)

**Comment by bulkatoz** [comment]
al fin sali muchas graciassss ya logre salir GRACIASSSSS DIOS SE LOS PAGUE
