### ISSUE TITLE
Can oscuro decrépito bug.

### ISSUE THREAD

**Issue by jordi72** [RoDNet/Bugtracker-Infinium-4.3.4#3947]
Hay un Can oscuro decrépito bugeado en claros de tirisfal al lado de los zepelines. i aqui la imagen.
(https://cloud.githubusercontent.com/assets/8350580/3796353/e6c50eae-1bc7-11e4-92d1-e196c02476a7.png)

Gracias.

**Comment by Kiritoo** [comment]
Acabo de probar y va bien, parece un error puntual.
