### ISSUE TITLE
Ayuda a un amigo bugeado

### ISSUE THREAD

**Issue by Lobomaniac** [RoDNet/Bugtracker-Infinium-4.3.4#3949]
Un amigo lleva ya muchos días bugueado en dalaran pues tiene el de bufo de la jaula de cristal de las trampas de shanox y no puede hacer nada porque le aparece que esta aturdido permanentemente podríais ponerle bien el bufo de la trampa su nombre es soppe y su cuenta es soperrako .

**Comment by Kiritoo** [comment]
Si cuando se conecte se lo quitamos, estando desconectado no podemos hacer nada, ya he visto el ticket y no estaba conectado.
