### ISSUE TITLE
[Arenas]Recompensas de arena - Puntos conquista

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#395]
Hola como vais comprobar en al imagen en esta versión los puntos de conquista se ganan de la siguiente manera:
Total: 0 / 1650
  -CDB: 0/1650
  -Batallas de arena: 0/1350

Esto significa que se pueden ganar un total de 1650 a la semana, haciendo campos de batalla puntuados o arenas.
El problema es que haciendo arenas los puntos te los suma en CDB pudiendo llegar a 1650 puntos a la semana cuando siendo batallas de arena solo se podrian hacer 1350.
![puntos](https://f.cloud.github.com/assets/3537253/787865/a96accec-eaea-11e2-8422-6af4d40c9afe.jpg)

Como se ve en la imagen tras hacer dos arenas los puntos no nos suben en, batallas de arena, sino que nos sube en CDB pudiendo llegar a 1650 semanales.

Un saludo.

**Comment by Dekadencee** [comment]
Creo que es un bug visual, ahora os confirmo que lo estoy reparando

**Comment by Dekadencee** [comment]
Era un bug visual, de todas maneras, acabo de fixearlo, gracias por reportar ^^
