### ISSUE TITLE
NPC BUG!

### ISSUE THREAD

**Issue by xxjuniorlll** [RoDNet/Bugtracker-Infinium-4.3.4#3950]
buenas gm este npc deberia darte la opcion de hablar para completar la cadena de  mision pero no lo hace esta es la quest http://es.wowhead.com/quest=24535/thalorien-buscalba

**Comment by nayan87** [comment]
junior esta quest ya esta posteada debidamente, acuerdate siempre de poner al NPC, luego su fallo y demás, en este caso nos abre cuadro de diálogo pero no nos otorga la bendición es lo único que le falta para completar el asunto, a ver si nos le ponen operativo pronto¡¡

**Comment by xxjuniorlll** [comment]
Buenas gracias por el consejo 
Npc..thalorien buscalba http://es.wowhead.com/quest=24535/thalorien-buscalba
Problema....el npc no te da la opción de hablar cuando lo tiene que hacer para proseguir con la misión 

Yo les pido q arreglen porfa veo post de este npc hace un año creo porfa gms arréglenlo ya es hora no creen e.e

**Comment by Kiritoo** [comment]
Seguimos desde el otro reporte que está mejor explicado.
