### ISSUE TITLE
[Mazmorras/Bandas][Tierras del Fuego] Lord Piroclasto

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#3954]
Buenas.
• Nombre: Lord Piroclasto
• Enlaces:
-Piroclasto: http://es.wowhead.com/npc=52558
-Pie izquierdo: http://es.wowhead.com/npc=52577
-Pie derecho: http://es.wowhead.com/npc=53087
• Problema: Los pies no tienen armaduras de obsidiana y una vez que se les termina el hp, el boss no pasa a segunda fase y se queda girando por la plataforma sin rumbo hasta que se sobrecalienta al máximo y nos mata. También tenemos que reiniciar la banda cada vez que wipeamos porque el boss queda en combate y aparece la leyenda "Hay un encuentro en curso" cuando queremos entrar a revivir.
• Observaciones: El giro del boss funciona perfectamente
Desde ya muchisimas gracias.

**Comment by Kiritoo** [comment]
Arreglado el tema de la armadura en los pies me falta revisar que compartan la vida con el boss.

**Comment by Monleon** [comment]
Fixeado por Dekadence.

Cuando se compile ya sucederá el encuentro correctamente
