### ISSUE TITLE
[Paladin] Luz del Alba

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3955]
Nombre:Luz del Alba
ID:85222
Enlace: http://wow.freakz.ro/spells.php?spell=85222
Descripcion: Consume todo el poder sagrado para enviar una ola de energia de sanacion ante ti, lo que sana 606 to 674 (+13.2% SP) por carga de poder sagrado a un maximo de 6 de los objetivos mas heridos de tu grupo o banda en un cono frontal de 30 m.
Problema: esta consumiendo siempre 1 cargar de poder sagrado es decir tengo 3 cargas uso la spells y solo me consume 1 deberia de consumir todo el poder sagrado y curarme 606 to 674 (+13.2% SP) por carga de poder sagrado

**Comment by efectokoleos** [comment]
arreglado
