### ISSUE TITLE
[Druida] Desenredo

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#3956]
Buenas quería reportar el abuso de un bug por parte de algunos ferales de la alianza no me importa que no les baneen pero lo que no me gusta es que no se reporte la skill pasiva Desenredo especifica de Heals resulta que tambien funciona en todas las ramas aunque fue quitado en cataclysm ya que hacia imparables a los druidas solo por cambiar de forma se le quitaba las relentizaciones 

ID:96429

Gracias por su atención

**Comment by Kiritoo** [comment]
Esto funciona correctamente.
Druidas ferales -> Quita efectos de ralentizamientos, no quita roots (raices)
Forma de lechucido lunar -> Al entrar y salir de la forma quita efectos de ralentizamiento y roots.
Druidas Heal(Desenredo) -> Quita efectos de ralentizamientos, y quita roots (raices).

**Comment by Kiritoo** [comment]
"The act of shapeshifting frees the caster of movement slowing effects."
http://cata.openwow.com/spell=768
Todos los cambios de forma del druida eliminan efectos de ralentización de movimiento.
