### ISSUE TITLE
Personaje atascado en medio del mar

### ISSUE THREAD

**Issue by snowng** [RoDNet/Bugtracker-Infinium-4.3.4#3957]
Hace 4 días dejé un post acá mismo de un bug que aún no solucionan
Este bug consiste en que luego de tomar un zeppelin el personaje (Elfo de sangre - Artanis) cae al mar muerto y sin posibilidad de aparecer como fantasma o respawnear en el cementerio, sólo queda ahí. No quería dejar otro post así porque sé que es molesto, pero jamás lo solucionaron incluso luego de enviar el ticket ingame. Pido por favor lo solucionen luego, saludos.

**Comment by Monleon** [comment]
Puedes poner por favor un ticket ingame de nuevo, sentimos las molestias, pero ingame es muchísimo mas rapido para nosotros

**Comment by snowng** [comment]
Acabo de enviar el ticket, gracias. (:
