### ISSUE TITLE
PERSONAJE ATASCADO

### ISSUE THREAD

**Issue by wolwest** [RoDNet/Bugtracker-Infinium-4.3.4#3959]
iba en el globo cuando mi personaje se cayo y ahora estoy muerto y no puedo pedir cuerpo por favor ayudenmen

**Comment by jordi72** [comment]
Pon esto amigo:
/script RepopMe()

aver si te funciona.

**Comment by ghost** [comment]
Para este tipo de casos abre un ticket ingame y te movemos de lugar.
