### ISSUE TITLE
[Picaro] Golpe en los Riñones

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3960]
Nombre: Golpe en los Riñones
ID:408
Enlace: http://wow.freakz.ro/spells.php?spell=408
Descripcion: Finishing move that stuns the target. Lasts longer per combo point:
1 point : 2 seconds
2 points: 3 seconds
3 points: 4 seconds
4 points: 5 seconds
5 points: 6 seconds
Problema: no tiene dr al stun 
Uso golpe bajo 4s y me golpe en los riñones sigue dando 6s de stun, otro ejemplo es que uso golpe en los riñones contra alguien con derribar (stun controller) y sigue siendo 6s
estaba buscando aver si era normal que no compartiera dr y en todos lados dice que si 
http://www.wowwiki.com/Diminishing_returns
http://eu.battle.net/wow/es/forum/topic/6533034601
http://eu.battle.net/wow/es/forum/topic/1417735290
http://www.taringa.net/posts/apuntes-y-monografias/12503510/Guia-Rogues-Supercompleta.html
http://eu.battle.net/wow/es/forum/topic/3010642641
http://eu.battle.net/wow/es/forum/topic/1934653448

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
