### ISSUE TITLE
[Profesión] Abrir Joyería

### ISSUE THREAD

**Issue by aceto82** [RoDNet/Bugtracker-Infinium-4.3.4#3961]
El inconveniente es que no puedo tener acceso al listado de joyas y demás, ya que el botón no está; intente con la macro /usar Joyería y tampoco funcionó

**Comment by Monleon** [comment]
Tienes la profesión de ingeniería o alquimia? Si es así, completaste más de una misión de especialización?

**Comment by aceto82** [comment]
Hola, gracias por responder. La otra profesión que tengo es Alquimia, así lo he tenido desde antes de migrarlo a este server. 
No entiendo lo de "completaste más de una misión de especialización?"

**Comment by Monleon** [comment]
En Alquimia hay 3 misiones de especialización para elegir, pero no deberías poder tener más de una. De todas maneras pide en un ticket que te borren las misiones de alquimia y las especializaciones, ya que es la manera de que te aparezcan bien el resto de profesiones.

**Comment by aceto82** [comment]
Ok, muchas gracias
