### ISSUE TITLE
[Mazmorras][Fin de los Días]  Alurmi

### ISSUE THREAD

**Issue by lomero** [RoDNet/Bugtracker-Infinium-4.3.4#3962]
Titulo: Alurmi
Enlace: http://es.wowhead.com/npc=57864
Coordenadas del NPC: 79,6 y 49,50
Problema: El NPC no está actualmente en la mazmorra y es uno de los que ofrece quest relacionada con la mazmorra en si.

**Comment by efectokoleos** [comment]
arreglado en el proximo reinicio
