### ISSUE TITLE
[Misión] ¡Sabotaje!

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#3964]
Misión: http://es.wowhead.com/quest=24747

Fallo: no se puede sabotear la Artillería enana (http://es.wowhead.com/npc=38190/artilleria-enana)

**Comment by redneo** [comment]
Creo que lo he arreglado....

Cierra el ticket si es así

**Comment by juaks** [comment]
No, no funciona, te salta una cinemática en la que eres un conejo y sales del edificio y se queda en la cinemática sin pasar nada. Si le das a ESC sólo te cuenta como completado el ¡Fuera de ahí! pero el Artillería saboteada no.

**Comment by Kiritoo** [comment]
Arreglada.
