### ISSUE TITLE
Guanteletes del señor supremo 

### ISSUE THREAD

**Issue by matusalen** [RoDNet/Bugtracker-Infinium-4.3.4#3965]
Hola, vengo a reportar este item Guanteletes del señor supremo, ya que no se puede transfigurar, este item lo reporte ya hace un año, cuando repararon muchos items que no se podian transfigurar se borro mi reporte, pero este item sigue sin poderse tranfigurar. Aqui el link http://es.wowhead.com/item=10205 . Y les cuento tengo casi un año con este reporte, y tarde casi otro en conseguir el item, por eso mi impaciencia, les agradeceria muchisimo su ayuda. un saludo

**Comment by Kiritoo** [comment]
Arreglado, cuando estes conectado pon ticket para que te lo intercambien por otro igual.
