### ISSUE TITLE
EL tamaño de las pet

### ISSUE THREAD

**Issue by xxjuniorlll** [RoDNet/Bugtracker-Infinium-4.3.4#3966]
buenas gm ayer vi el changelog del server y decia q habian arreglado el tamaño de las pets pero no es asi domestique nuevamente otras pet incluyendo las exxoticas y siguen igual

**Comment by Kiritoo** [comment]
Tiene que compilarse el servidor..

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3941
