### ISSUE TITLE
[pet] intervenir bug

### ISSUE THREAD

**Issue by xxjuniorlll** [RoDNet/Bugtracker-Infinium-4.3.4#3967]
buenas
npc: pet mascota exotica 
problema: cuando doy el hechizo de esta pet intervenir (http://es.wowhead.com/spell=53476/intervenir#english-comments ) me dice que absorbe 50% de daño ....pero  solo da 50 p para absorver

**Comment by Dekadencee** [comment]
Repetido https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3536, lo seguimos desde el anterior
