### ISSUE TITLE
[Mazmorra] El Horno de Sangre

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#3969]
Buenas el otro día entramos en el Horno de Sangre con los pj nivel 60-65 y resulta que hay un par de fallos que deberían arreglarse

1- Nivel de los NPC resulta que hay varios mobs en modo normal que tienen un nivel superior a la dificultad de la mazmorra [nivel 68-71] también el 2ndo Boss es nivel 71 cuando eso solo seria possible en modo HC

2-El NPC que da las misiones al incio de la mazmorra no esta en el caso de la Horda seria 
Horda : http://es.wowhead.com/npc=54636
Alianza : http://es.wowhead.com/npc=54629

3-El Boss final despues de matar todos sus clones es intargeteable.

Muchas gracias por su atención :)

**Comment by sakuranobushi** [comment]
Los tres errores reportados han sido corregidos y se aplicaran próximamente al servidor.
