### ISSUE TITLE
problema con misión "la caldera de la Gangrena de Gahrron" quest=27053

### ISSUE THREAD

**Issue by isma1977** [RoDNet/Bugtracker-Infinium-4.3.4#397]
no se puede interactuar con la caldera para obtener la muestra requerida para finalizar la mision.
![wowscrnshot_071213_103737](https://f.cloud.github.com/assets/4950741/788670/7eebc018-eb01-11e2-98cf-d5468e9f7d9c.jpg)

**Comment by crowel** [comment]
Acabo de probarla y funciona correctamente.
Cierro issue, un saludo.
