### ISSUE TITLE
[Paladin]Proposito divino

### ISSUE THREAD

**Issue by ExodusDK** [RoDNet/Bugtracker-Infinium-4.3.4#3970]
http://wow.freakz.ro/spells.php?spell=86172
Nombre:Proposito divino
ID:85117/86172  
Ahora el problema de este talento es que directamente ni salta,con ninguno de los hechizos con los que deberia saltar,lo que baja considerablemente el dps que puede hacer el pala represion

**Comment by Monleon** [comment]
Cuando caiga el servidor volverá a estar funcional
