### ISSUE TITLE
[Paladin]Limpiar 

### ISSUE THREAD

**Issue by ExodusDK** [RoDNet/Bugtracker-Infinium-4.3.4#3971]
http://es.wowhead.com/spell=4987/limpiar
Limpia envenenamiento y enfermedades,el problema es que esta limpiando tambien efectos magicos tales como inmolar,bomba viva,etc,y eso solo solo podria hacer un paladin holy con el respectivo  talento

**Comment by sakuranobushi** [comment]
El error se ha arreglado y debería verse reflejado pronto en el servidor.
