### ISSUE TITLE
[Hechizo-Cazador]Disparo de quimera

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#3972]
Nombre: Disparo de quimera
Enlace: http://wow.freakz.ro/spells.php?spell=53209
Problema: Hace poco le hicieron ajuste a el daño de esta habilidad, reduciendo su daño porque estaba alto (eso leí). Es probable que si estuviese alto, pero ahora ha quedado demasiado bajo. Me gustaría revisaran las fórmulas.
Como parámetro (y en absoluto es promoción a ningún otro lugar) he hecho pruebas en un servidor enfocado en PVP internacional, en el cual con equipo Sañoso 372, teniendo 1862 de daño por segundo, obtuve en promedio 17000 de daño por disparo de quimera al muñeco de entrenamiento; quitando piezas del set que tengo en ReignOfDarkness, hice pruebas con 1853 DPS, obteniendo un promedio de daño por disparo de quimera de 13000. El cambio es muy drástico.
Solo me gustaría revisaran bien la fórmula, pues en mi experiencia con cazadores el daño se encuentra bajo de lo que debería.
Aclaración: Ése otro server tiene el mismo parche q este, y de igual manera no posee demasiados bugs. Tuve que hacer pruebas en ese pues es conocido por su estabilidad en pvp y se encuentra en igualdad de condiciones.

**Comment by Kiritoo** [comment]
(WeapDMG + 0.73_RAP)_0.932

**Comment by efectokoleos** [comment]
el daño es correcto

**Comment by Jhovanni** [comment]
Bueno, pues si así es la fórmula, no queda más que decir.
Cierro es reporte.
