### ISSUE TITLE
[Alquimia] CD transmutaciones

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#3974]
Buenas desde ayer con las caídas me pone que el tiempo para volver a crear nada con transmutaciones de alquimia es de 3 dias y no baja cuando deberia reiniciarse a media noche o almenos por lo que me han dicho en el server a las 6 de la mañana 

http://s2.subirimagenes.com/imagen/previo/thump_9031931bug-alquimia.png

**Comment by efectokoleos** [comment]
arreglado falta compilar
