### ISSUE TITLE
[Mazmorra] Fortaleza Utgarde

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#3975]
Bueno queria reportar que en la Fortaleza Utgarde modo nm se mezclan igual que en el Horno de sangre las dos modalidades de juego nm y hc complicando un poco el hacer la maz ya que un lvl 69-70 vs un NPC lvl 80 solo por ser mas de 5 lvls menos ya le da al NPC la habilidad aplastamiento gracias por revisarlo

**Comment by sakuranobushi** [comment]
Los npc en el modo normal deberían tener ya su nivel correcto en el servidor. Los cambios se verán reflejados en el próximo reinicio.
