### ISSUE TITLE
[Dk]  Explosión aullante

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#3977]
Nombre: Explosión aullante
ID: 49184
Enlace: http://wow.freakz.ro/spells.php?spell=49184
Descripción: Golpea al objetivo con un viento helado, lo que inflige [(1.16) \* ((518 + (Ap \* 0.738)))] p. de daño de Escarcha a ese enemigo y [(0.5 \* ((1.16) \* (518 + (Ap \* 0.738))))] p. de daño de Escarcha al resto de enemigos en un radio de 10m. Infecta a todos los objetivos con Fiebre de Escarcha. 

Problema: El daño esta un poco bajo, creo que aplicaron mal la formula, con burst no pasa de 6k a un placa y el daño a los que rodean al objetivo... Bueno aquí una foto del daño a los muñecos de practica. 

Normal: http://kn3.net/329566BB3EDJPG.html
Con Burst: http://kn3.net/31B161D2D62JPG.html

**Comment by F4NT4SM4** [comment]
nose el link de wow.freakz sale otra formula distinta 
Blast the target with a frigid wind, dealing ((1322 + 214) / 2) + (AP \* 0.44) Frost damage to that foe, and (0.5 \* (((1322 + 214) / 2) + (AP \* 0.44))) Frost damage to all other enemies within 10 yards.

**Comment by Monleon** [comment]
Has probado además si ignora esa spell las reducciones de daño, vía por ejemplo sacerdote sombras, paladín con protección divina, o brujo con mascota?

**Comment by kingtonix** [comment]
Si, lo probé con Kyoraku chaman le saco 4k con totem de resistencias 3.4k, máximo en burst sin totem 5k.

**Comment by lomero** [comment]
prefiero que coloquen las formulas de wowhead ya que esas son las oficiales aqui os dejo la formula como es en el parche actual (1322+1322/2) + AP*0.44) en el enemigo actual

**Comment by Monleon** [comment]
Cierro, además el problema que tiene explosión ahuyante es otro beneficioso que no está aquí reportado.
