### ISSUE TITLE
[mazmorras y bandas][bastion crepuscular][consejo de ascendientes]

### ISSUE THREAD

**Issue by gerardo14** [RoDNet/Bugtracker-Infinium-4.3.4#3979]
hay dos bug en este bos el primero es en http://es.wowhead.com/spell=82859 donde hace la carga infierno pero no deja la estela de llamas haciendo imposible quitarse el debuff de http://es.wowhead.com/spell=82699 y evitar quedar congelado con el http://es.wowhead.com/spell=82746 
y el otro es que el helar esta haciendo daño por igual sin importar cuan lejos estes de feludious casi matando a la raid

**Comment by nayan87** [comment]
que importante es no confundir bug con mala praxis.... esa instance va casi perfecta  en todos los modos salvo unos pequeños retoques. La estela de fuego la deja (activa proyectar texturas antes de abrir el pozo de nuevo) y te recuerdo que el helar se corta...
