### ISSUE TITLE
[ Druid > Rake ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#398]
Arañazo http://es.wowhead.com/spell=1822

![wowscrnshot_071213_170657](https://f.cloud.github.com/assets/2728817/788863/7298ba2e-eb05-11e2-9d34-836ed58d584e.jpg)

![wowscrnshot_071213_170700](https://f.cloud.github.com/assets/2728817/788867/781fd32e-eb05-11e2-9e7f-060edee22d0c.jpg)

Esta spell tiene el daño de sangrado desorbitadamente alto.

**Comment by crowel** [comment]
![wowscrnshot_071213_171636](https://f.cloud.github.com/assets/3537253/788935/af4f1214-eb06-11e2-9c50-3a26a5d60c05.jpg)

Como se ve en la imagen los ticks deben ser aproximados a:
3x~2066
2x~4256

Y sin embargo los hago de:
3x~12740
2x~26244

**Comment by ghost** [comment]
Gracias por reportar, ya me parecía a mi raro que ayer en duelo un feral nada más abrirme me dejara un DoT que me hizo llegar a Cauterizar sin volver a tocarme xD

**Comment by 50megas** [comment]
yo lo hiva a reporta haora ,tick a un muñeco de 46K impresionante, de un areñazo matas a un tio sin temple xd

<a href="http://tinypic.com?ref=x9hna" target="_blank"><img src="http://i41.tinypic.com/x9hna.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

un saludo

**Comment by crowel** [comment]
Ya está bien.
Saludos.
