### ISSUE TITLE
La tier 13 de war no funciona sus obsesiones adicionales 

### ISSUE THREAD

**Issue by Nicoole** [RoDNet/Bugtracker-Infinium-4.3.4#3982]
tengo 2 partes de mi tier 13 de war pans y guantes de baradin 
dise que ahora mi facultad de revancha tambien otorga un escudo de absorción fisico igual al 20% del daño infligido por revancha a su objetivo principal pero nunca sale espero que lo reparen grasias :)

**Comment by ghost** [comment]
Los objetos en cuestiòn:
Musleras de placas de dragón colosal (http://es.wowhead.com/item=76991)
Manoplas de placas de dragón colosal (http://es.wowhead.com/item=76989)
Desde ya muchas gracias.

**Comment by redneo** [comment]
este spell es el que no va
http://es.wowhead.com/spell=105908 y creo que te pondría el siguiente bufo: http://es.wowhead.com/spell=105909

Solo faltaría la id de Revancha y que cogiera el daño que hace Revancha.

**Comment by Nicoole** [comment]
Nerv0 aun no lo an reparado que e estado asiendo raids esta semanas y aun no me sale el escudo :s e echo FL descenso HC Baradin etc pero nunca me salia :s ya son 2 meses desde que lo reporte espero que puedan repararlo pronto :s grasias
