### ISSUE TITLE
DK peste del ebano BUG

### ISSUE THREAD

**Issue by bulkatoz** [RoDNet/Bugtracker-Infinium-4.3.4#3983]
cada vez que entro al juego o relogueo se me aplica peste del ebano lo cual deberia ser un enfermedad dañina para el objetivo enemigo y no me deberia afectar a mi
![wowscrnshot_081514_145933](https://cloud.githubusercontent.com/assets/8270066/3938151/edc39d72-24b6-11e4-9d03-fbd7cc88084e.jpg)

**Comment by sakuranobushi** [comment]
Deberia haber sido arreglado y se aplicara proximamente en el servidor.
