### ISSUE TITLE
[Errores Internos] Establecer funcion Grupo/Banda

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3984]
Nombre: Establece Función
Descripcion: Permite poner un icono del rol (dps,tanke y heler) que esta jugando en la banda/grupo 
Problema: Sea en grupo de mazmorra o en grupo de banda, al marcar la función (tanque, daño, sanador) si lo dice textualmente pero gráficamente no lo muestra en las grillas de salud, lo que dificultará la organización de la banda más que todo.

![wowscrnshot_081514_203813](https://cloud.githubusercontent.com/assets/3101842/3940498/5beba89a-24e3-11e4-81cb-68c8370ca763.jpg)

**Comment by Kiritoo** [comment]
Revisando esto he arreglado lo siguiente.
![sin titulo-1](https://cloud.githubusercontent.com/assets/5061022/4379024/fc177c9e-435c-11e4-9bac-f8a2829e7eb4.jpg)
Ya se podrá dar ayudante a toda la banda mediante esta opción, falta compilarlo.
Seguiré mirando las funciones de banda.

**Comment by Dekadencee** [comment]
Fixed
