### ISSUE TITLE
[Brujo] Fear

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#3987]
Hoy estaba haciendo duelos contra algún brujo y resulta que por mucho que te peguen el miedo no se disipa cosa que no debería suceder lo mismo pasa con los sacerdotes sombra que pueden pegar todo lo que quieran hasta que el fear se disipa por si solo o trinqueteado

Aqui dejo captura de registro de combate en la que se ve claramente todo lo que me a pegado y aun asi no se a quitado
http://subefotos.com/ver/?b9f16e16c3fad1b3a7539614eae29bfeo.png

http://subefotos.com/ver/?1d4b80d4ba51a78c8b74157dac139a5do.png

No es algo normal ya que de siempre el miedo se tiene que quitar si recibes daño directo también me han comentado que los sacerdotes sombra se quejaron de que el miedo no duraba el suficiente daño pero de eso a que te puedan pegar 3 puas mentales y una explosión antes de que se quite... 

Muchas gracias por revisarlo

**Comment by Kiritoo** [comment]
Soporta hasta un 10% de la salud del objetivo del fear.

**Comment by Kiritoo** [comment]
Supongo que tienes unos 150k de vida arriba o abajo segun los daños recibidos.

**Comment by skyrex321** [comment]
tengo 137k sin buffs eso hace que ese 10% sean unos 13k me ha pegado mucho mas que eso y no se a quitado por lo tanto tiene subido el daño soportado la segunda captura es de el segundo fear consecutivo que dura menos segundos

**Comment by F4NT4SM4** [comment]
tambien puede ser que solo un golpe de que te baje mas de 10% de tu salud lo quite 
pero si hacen 5 golpes menos de 9% cada uno no se quita 
es lo unico que se me ocurre por que el fear esta guantando mas de ese 10% que dicen

**Comment by sakuranobushi** [comment]
El error ha sido corregido y debería verse pronto reflejado en los servidores de juego.
