### ISSUE TITLE
[Profesiones] Joyeria Anillo de Jaspe

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#3988]
Buenas hay un pequeño problema con los anillos de jaspe cuando los creas hay una probabilidad de que te salga un ejemplar raro de ilvl 300 pero llevo tiempo haciendo anillos para los alters y aun no me a salido ninguno por lo que supongo que no esta implementada esa posibilidad en el server o que tengo muy mala suerte 

http://es.wowhead.com/item=52306
http://es.wowhead.com/item=52310

The blue ring is a random proc from making regular Jasper Rings

**Comment by sakuranobushi** [comment]
El error ha sido corregido y debería verse pronto reflejado en los servidores de juego.
