### ISSUE TITLE
Bug maestro de vuelos cala brechaoscura

### ISSUE THREAD

**Issue by xhide86** [RoDNet/Bugtracker-Infinium-4.3.4#3989]
El maestro de vuelos situado en cala brechaoscura no funciona, una vez que le selecciono para hablar con el no hace nada.
![wowscrnshot_081714_164238](https://cloud.githubusercontent.com/assets/5238456/3944864/5f6e665c-261d-11e4-901f-2ca91ccff781.jpg)

**Comment by redneo** [comment]
Creo que esta arreglado, al menos a mi si que me ha sacado la ruta.

Un saludo
