### ISSUE TITLE
[ Druid > Shred ]

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#399]
Triturar http://es.wowhead.com/spell=5221

![wowscrnshot_071213_172919](https://f.cloud.github.com/assets/3537253/788995/d9eac940-eb07-11e2-8ceb-b41fcef7c2b9.jpg)

Esta spell tiene el daño mas elevado al que debe.

**Comment by Kiritoo** [comment]
El daño esta correcto a la especificación.
Cierro issue.
