### ISSUE TITLE
[Warrior] Seccionar mejorado

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#3990]
Como dice el titulo es un bug en el talento que mejora el seccionar ya que sin necesidad de aplicar el segundo seccionar encima directamente ya deja inmovilizado al objetivo en el suelo

SpellID: 12668

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3737
