### ISSUE TITLE
[BUG] Comprar paños de seda de ascuas

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#3992]
No se puede comprar http://es.wowhead.com/item=53010 con honor.

![wowscrnshot_081714_231413](https://cloud.githubusercontent.com/assets/6329431/3945850/a3e7d9c2-2653-11e4-8b36-353a2a5e89ce.jpg)

![wowscrnshot_081714_231416](https://cloud.githubusercontent.com/assets/6329431/3945851/a790d31c-2653-11e4-8081-eb3443f6a568.jpg)

También pasa al querer intercambiar puntos de valor por puntos de conquista.

**Comment by Monleon** [comment]
Esto está arreglado, y puesto en el changelog con una fecha anterior al issue en cuestión.
