### ISSUE TITLE
[Brujo] Quemar Alma: Piedra de salud

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#3996]
Nombre:Quemar Alma: Piedra de salud
ID:79437
Enlace: http://wow.freakz.ro/spells.php?spell=79437
Descripcion: Aumenta un 20% la salud maxima durante 8s
Problema: no esta funcionando uso quemar alma + piedra de salud y no me aumenta la vida

**Comment by efectokoleos** [comment]
arreglado

**Comment by F4NT4SM4** [comment]
me falto un pequeño detalle mencionar deberia brillar piedra de salud al tener el buff quemar alma como en las otras spells muestro una imagen
![wowscrnshot_081914_173245](https://cloud.githubusercontent.com/assets/3101842/3973815/418d1158-27ec-11e4-9a30-ee7aeb3b3c29.jpg)
