### ISSUE TITLE
Vendedores version 4.0.6

### ISSUE THREAD

**Issue by Savian123** [RoDNet/Bugtracker-Infinium-4.3.4#4]
Buenas , hoy al entrar al servidor y ver la version 4.3.4 he ido directamente como mucha gente a por los nuevos items de PvP y PvE resulta que me he encontrado con lo siguiente
![vendedor justicia bug](https://f.cloud.github.com/assets/4934124/746581/dc8d3d36-e431-11e2-9570-e0dfbe4ad7cf.jpg)
![vendedor valor bug](https://f.cloud.github.com/assets/4934124/746585/e141f664-e431-11e2-9bad-45b1f3df80db.jpg)

Resulta que el vendedor de justicia se a quedado en la version 4.0.6 ya que en la 4.3.4 deberia vender el tier12 del parche de Firelands y el de justicia deberia dejar canjear los items del buscador de raids para conseguirse el t13 y tambien vender el offset de valor.  Como se ve en las imagenes ninguno de los 2 vende lo que le corresponderia vender en esta version espero que puedan solucionarlo gracias :) y ya que estoy añadire que el vendedor de honor no vende el set Implacable solo vende las armas y el Offset...

![vendedor honor sin set](https://f.cloud.github.com/assets/4934124/746587/e64c7198-e431-11e2-8ce2-4195df7a4b58.jpg)

**Comment by crowel** [comment]
Comprobado! falta.
Un saludo.

**Comment by searum** [comment]
Si facilitas ids del npc mejor que mejor :)

**Comment by crowel** [comment]
Hola son los siguientes
Vendedores:
Justicia: http://es.wowhead.com/npc=46555

Valor: http://es.wowhead.com/npc=46556

Implacable Temporada 10: http://es.wowhead.com/npc=69977

Un saludo ^^
