### ISSUE TITLE
Talento [Égida divina] Sacerdote disciplina

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#40]
No puedo linkearlo desde oldwowhead ya que la descripción es la misma que en la expansión del Lich King.

Enlazo desde aquí: http://db.mmo-champion.com/utils/talents/#k=ffR.bqj.priest.

Divine Aegis (5ºfila de disciplina)

EL bug en cuestión es que sigue funcionando igual que en el lich, crea un escudo por valor del 30% de la curación, tras producirse una curación crítica. [Correcto]
Ahora veamos, la segunda parte de este talento (la novedad):

Divine Aegis (Rank 3) : Las sanaciones criticas, y todas las sanaciones con Rezo de sanación crean un escudo protector sobre el objetivo, absorbiendo el 30% de la cantidad sanada. Dura 15seg.

He aquí, el problema, tras utilizar Rezo de sanación (aunque no sea crítica) debería saltar Égida Divina a todos los objetivos afectados por esta cura, por valor al 30% de la cantidad sanada. Esto no esta pasando [Bug]

Este problema, a su vez crea pequeños subbugs como la utilización del glifo "Rezo de sanación".
O el "stack" del valor de égida divina, tal como ocurre con la nueva maestría del paladin sagrado en este parche. Es decir los escudos producidos por "Egida divina", pueden seguir acumulandose (renovando los 15segundos de beneficio, y aumentando la cantidad sanada respecto al anterior beneficio de Egida Divina).

En el siguiente vídeo se aprecia muy bien lo que he intentado explicar con anterioridad:

http://www.youtube.com/watch?v=523XMJwz6YM

Visualizad únicamente el segmento comprendido entre el 6:20 y el 6:50

Gracias

Edito: Egida divina, se esta stackeando, pero sólo con sanaciones críticas, no con rezo de sanacion

**Comment by searum** [comment]
fix
