### ISSUE TITLE
[Logro] El limnólogo

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#400]
Tengo ticks en todos los peces requeridos pero no salta el logro.

Aqui dejo el link : http://es.wowhead.com/achievement=5478

**Comment by Dekadencee** [comment]
Reporte repetido, lo seguimos desde el anterior #19

**Comment by Dekadencee** [comment]
Y es tuyo y tal el anterior... xD
