### ISSUE TITLE
[Cazador]Recuperacion rapida

### ISSUE THREAD

**Issue by ExodusDK** [RoDNet/Bugtracker-Infinium-4.3.4#4000]
http://wow.freakz.ro/spells.php?spell=53232
Problema:el beneficio de recuperacion de enfoque cuando lanzas fuego rapido lo esta dando cada vez que matas a alguien

**Comment by Kiritoo** [comment]
Claro exodusDK, el beneficio de enfoque de recuperación rápida lo entrega al usar fuego rápido entregando enfoque cada 3 segundos o al ganar Matanza rápida(matando a un objetivo que aporte honor u experiencia) entregando 25/50 puntos instantaneos de enfoque.
