### ISSUE TITLE
[mazmorras/bandas][fin de los dias][eco de sylvanas]

### ISSUE THREAD

**Issue by gerardo14** [RoDNet/Bugtracker-Infinium-4.3.4#4004]
ayer fui a fin de los dias y nos toco el eco de sylvanas pero al matar al necrofago y salir del circulo recibiamos daño como si no lo hubieramos matado por lo que fue imposible terminar la mazmorra

**Comment by efectokoleos** [comment]
he estado hoy y no ocurre eso que dices

**Comment by efectokoleos** [comment]
confirmado si te alejas no te hara ningun daño
