### ISSUE TITLE
Colera de las Bestias BM Hunter [Errores de clases/pjs]

### ISSUE THREAD

**Issue by Zerotonic** [RoDNet/Bugtracker-Infinium-4.3.4#4007]
El talento en si aparte de aumentar el daño de la bestia y cazador, los hace inmunes al miedo, pero al usarlo durante/antes/despues de un fear de brujo o guerrero, sigue entrando ese miedo, cosa que no deberia suceder, ya que una parte importante de bestias es ese talento y me gustaria que hicieran algo al respecto, tengo pruebas por si gustan hacer sus investigaciones

**Comment by Kiritoo** [comment]
Tienes que añadir el id del hechizo y anexar donde ponga que debe hacer eso que nos comentas, gracias.

**Comment by Monleon** [comment]
Al hunter no lo hace inmune, únicamente a la mascota

**Comment by Zerotonic** [comment]
Monleon al hunter tambien lo hace inmune con el siguiente talento de bestia interna compartes colera de las bestias

**Comment by Zerotonic** [comment]
y fixx no entiendo  "lo de anexar donde ponga que debe hacer lo que nos comentas"

**Comment by Monleon** [comment]
http://www.wowwiki.com/The_Beast_Within
Patch 4.0.1 (12-Oct-2010): Immunity to cc removed.
