### ISSUE TITLE
[Hechizo - Sacerdote] Maligno de las Sombras (en PvP)

### ISSUE THREAD

**Issue by Akademika** [RoDNet/Bugtracker-Infinium-4.3.4#4008]
Nombre: Maligno de las Sombras
Enlace: http://es.wowhead.com/spell=34433
Descripción: Crea a un maligno de las Sombras que ataca al objetivo. El taumaturgo recibe un 3% de maná cada vez que el maligno de las Sombras ataca. Dura 12 s.

Problema: En PvP (tanto arenas como BG o duelos), cuando se desea lanzar el maligno contra otro jugador enemigo éste no le ataca y se queda al lado del sacerdote sin hacer absolutamente nada.

Observaciones: raramente ha funcionado si el sacerdote se queda quieto o el jugador enemigo está quieto. Si alguno de los dos se mueve (99% de las ocasiones) aunque sea un metro, el hechizo no funciona. También muy muy excepcionalmente ha funcionado cuando el jugador enemigo estaba pegando al sacerdote justo a su lado (aunque en la inmensa mayoría de la ocasiones tampoco funcionó en esta situación).

**Comment by paellaencol** [comment]
Yo no puedo ayudarte, pero si al invocar al maligno clicas con el botón derecho sobre un jugador enemigo, cuando aparece una espada en el cursor, el maligno irá a por él.
