### ISSUE TITLE
[ Druid > Ferocious Bite ]

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#401]
Mordedura Feroz http://es.wowhead.com/spell=22568

Esta habilidad del druida esta haciendo menos daño del que deberia.

Un saludo.

**Comment by searum** [comment]
y cuanto deberia hacer? porq yo creo que pega demasiado

**Comment by ghost** [comment]
reporte de hace 24 días.. tal vez por eso xD
