### ISSUE TITLE
[Brujo] Demonología Talento de inferno para Llamas infernales

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4012]
Id Llamas infernales: 65816 (http://wow.freakz.ro/spells.php?spell=65816)

id Inferno: 85105 (http://wow.freakz.ro/spells.php?spell=85105)

El problema de este talento es que está convirtiendo al hechizo del brujo de llamas infernales en Aura de inmolación (id: 104025) cosa que solo se da en estado de metamorfosis. Paso a explicarlo:

Lo que ocurre es que si activo "Llamas infernales" gracias al talento de Inferno se puede canalizar en movimiento. Hasta aquí todo bien, sin embargo, si empezamos a castear otro hechizo cualquiera el efecto de "Llamas infernales" no se cancela sino que sigue canalizando y permite castear mientras otros hechizos. Es decir, sigue estando activo sin necesidad de canalizarlo cosa que obviamente esta mal, ya que eso solo debería pasar en estado de metamorfosis con "Aura de inmolación" (que es el hechizo que lo permite). 

Conclusión si se puede canalizar el hechizo en movimiento gracias al talento pero en cuanto se empiece a castear otra cosa debería cancelarse dicho efecto. 

Un saludo y gracias

**Comment by Wiinter** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3137 
Posteado hace muuuuucho tiempo

**Comment by efectokoleos** [comment]
arreglado
