### ISSUE TITLE
[Cazador] Sanación Disparo de quimera

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4013]
Id: 53209 (http://wow.freakz.ro/spells.php?spell=53209)

La sanación por parte de disparo de quimera es de un 5% de la salud total se haga el daño que se haga ya sea critico o normal.

Actualmente lo que ocurre es que si disparo de quimera hace daño critico la sanación también sale critica cosa que no debería ocurrir ya que se especifica que es un 5% en base a la salud total.

Un saludo y gracias

**Comment by Monleon** [comment]
La sanacion  de esta spell puede ser crítica
