### ISSUE TITLE
[Quest]  [Entrenamiento mental: El camino de la verdad hacia el poder]

### ISSUE THREAD

**Issue by Savian123** [RoDNet/Bugtracker-Infinium-4.3.4#4014]
Buenas me gustaría reportar esta misión de Monte Hyjal  quest=25299 resulta que el item=52828 que te dan al usarlo no realiza las preguntas y tampoco te deja dejar de usarlo haciendo que tengas que reloguear espero que puedan arreglar esta misión ya que es una parte importante de la cadena de misiones finales de Hyjal gracias

**Comment by tutata49** [comment]
Yo también acabo de encontrarme con este problema. Sé que harán todo lo que esté a su alcnace para arreglar esta misión  a la mayor brevedad posible, así que se les agradece de antemano.
