### ISSUE TITLE
[Spell] Palabra de Gloria

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#4018]
Spell: 85673

Fallo: en la rama Protección, no cura lo que debería, cura con 3 cargas 9-10k (ridículo).

**Comment by kikete17** [comment]
https://wow.freakz.ro/spells.php?spell=85673

Tampoco funciona bien en la rama Represión,cura con 3 cargas entre 8-10k tenga buffos o sin ellos

**Comment by efectokoleos** [comment]
arreglado
