### ISSUE TITLE
[Joyería] ¡La última moda!

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#402]
Hola está misión ¡La última moda!  http://es.wowhead.com/quest=25159

Se trata de :

Prueba el polvo estelar nº 2 con 10 "sujetos humanoides". 
    Polvo estelar nº 2 probado (10)

Polvo estelar nº. 2 http://es.wowhead.com/item=52507

-Problema: Al usar el item sobre los humanoides no ocurre nada.

Un saludo.

**Comment by Kiritoo** [comment]
Funciona.
