### ISSUE TITLE
RESPAW de NPC de muchas ZONAS esta horrible, feo, y casi eterno :P

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.3.4#403]
![wowscrnshot_071213_101611](https://f.cloud.github.com/assets/2059256/789817/aaf9ed34-eb19-11e2-9834-104169c9369c.jpg)
![wowscrnshot_071213_101732](https://f.cloud.github.com/assets/2059256/789822/c2982eec-eb19-11e2-9462-1455da5cae91.jpg)
![wowscrnshot_071213_102105](https://f.cloud.github.com/assets/2059256/789825/dc2063b6-eb19-11e2-8fd5-1072fa591c7d.jpg)
![wowscrnshot_071213_102223](https://f.cloud.github.com/assets/2059256/789831/f1a6789c-eb19-11e2-9356-d3fca09f41b5.jpg)
![wowscrnshot_071213_102457](https://f.cloud.github.com/assets/2059256/789834/0018f940-eb1a-11e2-8002-a65fb0abceb2.jpg)
![wowscrnshot_071213_102658](https://f.cloud.github.com/assets/2059256/789835/16bf4636-eb1a-11e2-91ef-c0a12c2d2d55.jpg)
![wowscrnshot_071213_102830](https://f.cloud.github.com/assets/2059256/789843/2c98fa1a-eb1a-11e2-97f7-9c42bea88c60.jpg)
![wowscrnshot_071213_102945](https://f.cloud.github.com/assets/2059256/789846/4b72a472-eb1a-11e2-9d11-34dd1f253ece.jpg)
![wowscrnshot_071213_103309](https://f.cloud.github.com/assets/2059256/789856/96839390-eb1a-11e2-8a23-2d2ae912a2dd.jpg)
![wowscrnshot_071213_103354](https://f.cloud.github.com/assets/2059256/789876/fd1b6f56-eb1a-11e2-9022-9fbfb2f4db9a.jpg)

Asi en el orden que puse las imagenes paso lo siguiente.

**Primero quiero aclarar que esto pasa casi... CASI... casi con todos los NPCs que son objetivos de QUEST de TODAS LAS ZONAS.**

**Y NO ES UN REPORTE DE ESTA QUEST. NO ESTOY REPORTANDO LA QUEST. ESTOY HABLANDO DEL RESPAW DE TODAS LAS ZONAS**

> Y no estoy hablando de NPCs raros son simples y comunes NPCs.

---

En la 4.0.6a redneo me dijo que el respaw era de 5 minutos.

> En mi humilde opinion; para mi 5 minutos es mucho cuando hay varias personas, jugadores, PJs en la misma zona haciendo las mismas quest que tu, especialmente cuando son quest NEUTRALES _(osea que las pueden hacer tanto A como H)_ y eso que la poblacion de RoD no pasa de los 200 (creo). Y eso que cuando yo tomaba tiempo se pasaban mas de los 5 minutos en la version pasada xD.

El objetivo de este reporte es para bajarle el respaw a los NPCs en terminos globales. EXCLUYENDO a los raros.

> respaw = reaparicion

Esto sucede en todas las zonas: rasganorte, terrallente, kalimdor, reinos del este. etc.

---

Saludos y ahi se los dejo de tarea =)

**Comment by SherBlader** [comment]
Yo siempre que iba a hacer esa quest pensaba que estaba bug porque nunca veia el enano, pero no estaba seguro como para reportarlo xD

**Comment by WarSxNes** [comment]
xD gracias por el comentario.... Pero OJO ... ojo... OJO no estoy reportardo la quest, si no el RESPAW de casi todos los NPCs en el sentido global. (Rasganorte, Terrallente, Kalimdor, Reinos del Este. etc.) y digo casi CASI casi todos los que son objetivos de una quest.

> Y no me pidan poner fotos de cada zona... hihihi por que llenaria de imagenes este post xD aunque eso si, si es necesario las puedo poner.

**Comment by Wiinter** [comment]
Una pregunta, no habeis notado que los NPCs dan menos loot que antes? Esto es normal, es como debe ser?

**Comment by redneo** [comment]
jurl... ese npc en concreto tiene DOS HORAS de respawn! voy a mirar a ver si hay muchos así.

1743 row(s) affected
Criaturas en mapas: 1,0,533,732, 571 que tenian spawn > 300 segundos cambiadas a 300 segundos (mapas kalimdor, reinos del este, terrallende, rasganorte y tol barad) y no son ni elites, ni rares ni bosses ... amos npcs normales.
