### ISSUE TITLE
Cuenca de Sholazar - Misión - A los dioses le gustan las cosas brillantes

### ISSUE THREAD

**Issue by Wyrda** [RoDNet/Bugtracker-Infinium-4.3.4#4031]
Lafoo no recoge los objetos brillantes del suelo, como debería de hacerlo y a veces que ni siquiera aparecen los puntos brillantes, que es donde e de buscar los objetos

```
Si hay alguna forma de arreglar esto estaría muy agradecido de que me lo dijeran, es que quiero conseguir la montura de Draco, especialmente la Verde
```

**Comment by nayan87** [comment]
esta mision funciona perfectamente, otra cosa es que no tengas paciencia para hacerla, atentamente exaltado con los oraculos.

PD: el huevo sigue sin funcionar

**Comment by Wyrda** [comment]
okey, supongo que e de ser paciente, gracias por responder

**Comment by Compresor** [comment]
Funciona
