### ISSUE TITLE
[Dk] Golpe con runa.

### ISSUE THREAD

**Issue by kikete17** [RoDNet/Bugtracker-Infinium-4.3.4#4032]
ID: 56815
https://wow.freakz.ro/spells.php?spell=56815

Problema: despues de esquivar o parar(en sangre) se buguea y no te deja utilizarlo, tienes que estar todo el rato cambiando presencias para que se arregle.

**Comment by Kiritoo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/3937
