### ISSUE TITLE
[Druida] Flor de vida

### ISSUE THREAD

**Issue by kikete17** [RoDNet/Bugtracker-Infinium-4.3.4#4033]
https://wow.freakz.ro/spells.php?spell=33763

Descripcion: Este efecto se puede acumular hasta 3 veces en el mismo objetivo. Flor de vida solo puede estar activo sobre un objetivo a la vez..
Árbol de vida:Se puede lanzar sobre un número ilimitado de objetivos

Problema: se puede utilizar sobre un número ilimitado de objetivos sin estar en forma Árbol de vida.

**Comment by efectokoleos** [comment]
arreglado
