### ISSUE TITLE
[Misión] Afianzado (Infralar)

### ISSUE THREAD

**Issue by minidemo** [RoDNet/Bugtracker-Infinium-4.3.4#4034]
La misión Afianzado en Infralar quest=26436, no se puede entregar al npc Kor el Inamovible npc=42469, ya que este aunque te deja targetearlo no puedes completar la quest.
He probado borrando caché y todo lo que se me ha ocurrido pero no hay manera.
Gracias de antemano

**Comment by nayan87** [comment]
Pues prueba a quitarte a la facción del modo guerra anda... a ver si a si entregas o no

**Comment by minidemo** [comment]
solucionado era eso, juraría que lo miré cuando me paso la primera vez,  gracias
