### ISSUE TITLE
[DK] Sangre del norte. 

### ISSUE THREAD

**Issue by kingtonix** [RoDNet/Bugtracker-Infinium-4.3.4#4036]
Nombre: Sangre del norte
Rama: Escarcha (Especialización pasiva).
ID: 54637
Link: http://es.wowhead.com/spell=54637

Descripción: Transforma tus runas de sangre en runas de muerte de forma permanente. Las runas de muerte cuentan como runas de sangre, de escarcha o profanas.

Problema: Están inutilizables, son como runas de sangre con visualización de runas muerte, solo se gastan con poderes de sangre, osea no deja usar con poderes de escarcha y profano.

**Comment by Wiinter** [comment]
Si cambias de talentos vuelven otra vez como estaban, como medida temporal te hace un apaño.

**Comment by kingtonix** [comment]
Si, pero en arenas y bg's no puedo cambiar y eso molesta mucho :(

**Comment by Overseer101** [comment]
No es lo mismo decir que "las runas de muerte desaparecen al entrar a BG o por cualquier portal" (cosa que los gm ya saben) a decir, "Las runas de muerte son inutilizables y solo se gastan al usar ataques que gasten runas de sangre" (cosa que me he cansado de probar yo y no es verdad, y no solo hoy, si no desde siempre), por favor vamos a explicar las cosas bien, que luego se tiran 2 horas probando y reprobando algo que si que funciona cuando podrian usar ese tiempo en otras cosas.....
