### ISSUE TITLE
[Druida]Facultad Ofrenda de malfurion.ID(en teoria)92364

### ISSUE THREAD

**Issue by evangelion2009** [RoDNet/Bugtracker-Infinium-4.3.4#4039]
La facultad ofrenda de malfurion http://es.wowhead.com/spell=92364/ofrenda-de-malfurion (revisar changelog 4.2.0 esa es la descripcion de nuestro parche actual)Fallos en la misma esta activa el hechizo http://es.wowhead.com/spell=16864/augurio-de-claridad#changelog el cual se activaria con flor de vida a un 4% provocando lanzamiento sin coste de mana en un hechizo no instantaneo de sanacion(al menos en heal)
Fallos primero al estar flor de vida como esta pues significa mas activaciones cuanta mas gente le eches la misma la segunda se consume con cualquier hechizo no solo los de casteo ya sea inst o no.

**Comment by efectokoleos** [comment]
arreglado flor de vida
