### ISSUE TITLE
No se puede abandonar cola de arena

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#404]
Cuando intento abandonar cola de arena y le doy clic a abandonar cola, no pasa nada teniendo que reloguear para poder salir de cola.

![wowscrnshot_071213_125608](https://f.cloud.github.com/assets/4895839/789933/81da7718-eb1c-11e2-96b7-6f9bb8ce5d6e.jpg)

**Comment by Compresor** [comment]
Ya se puede
