### ISSUE TITLE
[Druida]Facultad Revitalizar id (en teoria)48544

### ISSUE THREAD

**Issue by evangelion2009** [RoDNet/Bugtracker-Infinium-4.3.4#4040]
La facultad http://es.wowhead.com/spell=48544#changelog (revisar changelog 4.2.0 es la descripcion correcta) Como bien dice flor de vida y rejuvenecimiento otorgarian un 2% de mana con un 20% por tick y ademas otorga reposicion.
Fallos actualmente este hechizo se beneficia nuevamente del bug en flor de vida parece ser que no respeta el cd de 12 sec y aparte tambien se activa con crecimiento salvaje.

**Comment by Overseer101** [comment]
Ni se activa con crecimiento salvaje ni ignora el cooldown de 12s entre activaciones. El % de que salte es correcto

P.D. Corrijo, si que salta con crecimiento salvaje, despues de 32 usos me ha saltado ¬¬

**Comment by efectokoleos** [comment]
arreglado
