### ISSUE TITLE
[Druida]Facultad floracion ID(en teoria)81262

### ISSUE THREAD

**Issue by evangelion2009** [RoDNet/Bugtracker-Infinium-4.3.4#4041]
La facultad http://es.wowhead.com/spell=81262/floracion#changelog sana a 3 objetivos mas eridos en el zonal que dejas tras hacer lo que dice el hechizo.
Fallo actualmente sana a toda la gente que este en el zonal mientras el mismo dure.

**Comment by efectokoleos** [comment]
arreglado
