### ISSUE TITLE
Bugs en el paladin represión

### ISSUE THREAD

**Issue by LI0NSH34RT** [RoDNet/Bugtracker-Infinium-4.3.4#4042]
Ha dejado de funcionar los talentos sentencias del audaz y largo brazo de la ley en paladín represión

**Comment by efectokoleos** [comment]
necesito ids si no no puedo hacer nada

**Comment by F4NT4SM4** [comment]
Sentencias del audaz: Tu sentencia te otorga un 25% de tu mana base durante 9.53s (id:89901)
mi pala se ve muy afectado e.e

**Comment by F4NT4SM4** [comment]
Largo brazo de la ley: tu sentencia tiene un 50%/100% de probabilidad de aumentar un 45% tu velocidad de movimiento durante 4s cuando se usa con objetivos a 15m de ti o mas (87168/87172)
Sentencia id: 20271

**Comment by efectokoleos** [comment]
arregladas ambas spells

**Comment by F4NT4SM4** [comment]
Largo brazo de la ley se esta activando a cualquier distancia deberia activarse solo si el objetivo esta a 15metro de ti o mas

**Comment by Monleon** [comment]
Gracias por ponerlo porque el otro jugador se calló del bug beneficioso. No reporteis únicamente lo que os perjudica.

**Comment by efectokoleos** [comment]
arrreglado
