### ISSUE TITLE
[Guerrero] Vendaje de batalla

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4044]
Nombre: Vendaje de batalla
Vendaje de batalla ID: 84579/84580
Enlace: https://wow.freakz.ro/spells.php?spell=84580
Vendaje de batalla descripcion: Aumenta las sanaciones recibidas un 3%/6% y la eficacia de tus facultades de sanacion un 10%/20% extra
Problema: El vendaje de batalla hace que segundo aliento especificamente 2/2 (29838) cure menos, deberia de aumentar la eficacia de la sanación un 20% extra

**Comment by efectokoleos** [comment]
arreglado falta compilar
