### ISSUE TITLE
[Paladin] Maestria en Auras

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4045]
Nombre: Maestria en Auras
ID: 31821
Enlace: https://wow.freakz.ro/spells.php?spell=31821
Descripcion: Provoca que tu aura de concentracion haga inmunes a los efectos de silencio e interrumpir a todos los objetivos afectados y mejore el efecto de aura de devocion, Aura de resistencia y aura de represion un 100%. dura 6s
Problema: Esta dando inmune en otras auras solo deberia de dar inmune si se tiene aura de concentracion (19746) a los objetivos afectados.

**Comment by efectokoleos** [comment]
arreglado
