### ISSUE TITLE
[Mision][Zona inicio DK-Tierras de la peste Este]Un final para todas las cosas....

### ISSUE THREAD

**Issue by dexinuz** [RoDNet/Bugtracker-Infinium-4.3.4#4047]
Al finalizar la quest http://es.wowhead.com/quest=12779/un-final-para-todas-las-cosas , no se puede entregar a LK. El dragon que invoca este item http://es.wowhead.com/item=39700  tiene un poder bugeado, el poder numero 2, el que esta en la mitad de la barra de hechizos, se supone que al usarlo te devuelve donde esta LK y entregas la quest, pero dicho poder no funciona.

**Comment by Savian123** [comment]
La habilidad devorar humanoide funciona pero se tiene que estar cerca del objetivo

**Comment by nayan87** [comment]
y la quest puede hacerse perfectamente, simplemente vuelves con el dragón a LK y listo, no hace falta ser tan picajoso...o más bien tan jodidamente vago...

**Comment by dexinuz** [comment]
Y tampoco hay que hablar sin saber, volví hasta a LK y no le podía entregarla quest, y solo especifique lo del dragón, porque así se hace en el ofi. Y no, no es la de devorar un mob, es la de teletransporte. 
Ya reinicie y borre cache, y repetí la misión, y nada que la puedo entregar.

**Comment by dexinuz** [comment]
Y para rematar, habian otros dos players en la  misma situacion que yo.

**Comment by dexinuz** [comment]
![wowscrnshot_090814_152530](https://cloud.githubusercontent.com/assets/8689856/4192266/53b29bc8-3796-11e4-8970-21f4f9d02072.jpg)

Estamos asi desde ayer.

**Comment by Luis2403** [comment]
la quest sigue bug

**Comment by Kiritoo** [comment]
Ya se tiene que poder entregar, tengo que mirar de ajustar las fases de lo dos LK, ya que uno de ellos no se deberia de ver.
