### ISSUE TITLE
la mision [Resucitar el pasado]  esta bug

### ISSUE THREAD

**Issue by conqueron** [RoDNet/Bugtracker-Infinium-4.3.4#4048]
http://es.wowhead.com/quest=9680/resucitar-el-pasado#screenshots

la mision consiste en agarrar un hueso que esta por las rocas el bug es que el hueso no se puede recojer de ninguna manera.

**Comment by nayan87** [comment]
Esta misión tb se puede hacer, acuerdate de salir de la banda cuando la hagas (te lo digo por experiencia), no obstante, el problema de esta cadena, sobreviene al finalizarla, creo k la vasija de nocturno aún no funciona, un mal menor dentro de que toda la banda de Kharazan funciona a excepción de este boss y el evento del ajedrez, suerte¡

**Comment by redneo** [comment]
Se puede hacer la mision correctamente
