### ISSUE TITLE
[Quest Bug] Sanar a los heridos

### ISSUE THREAD

**Issue by KuroNoKenshi** [RoDNet/Bugtracker-Infinium-4.3.4#4054]
Buenas, la quest "Sanar a los heridos" de la clase sacerdote esta bug, al querer sanar a los Objetivos (NPC) no los cuenta, haciendo imposible el completar la misión y continuar gracias.

**Comment by redneo** [comment]
Hay tres misiones que se llaman igual, son misiones de inicio... podrias especificar cual de las 3 es?

**Comment by redneo** [comment]
la de los humanos reparada.
