### ISSUE TITLE
SPAM al utilizar cuaquier habilidad

### ISSUE THREAD

**Issue by LI0NSH34RT** [RoDNet/Bugtracker-Infinium-4.3.4#4058]
![bugazo](https://cloud.githubusercontent.com/assets/8160853/4212545/585ca8c0-38a0-11e4-84f9-1cae3d93d42d.jpg)
ademas parece que se han bugueado varias clases, por ejemplo el pala holy tiene palabra de gloria infinita y me  parece que los sacerdotes sombras pegan demasiado
esto ha empezado a funcionar mal tras una caida a las 4:30 mas o menos 10/09/2014 hora del servidor

**Comment by Overseer101** [comment]
Lo del Spam, ha sido un modo debug para arreglar precisamente lo de las cargas de palabra de gloria, le sigue quedando el problema visual de gloria eterna, pero eso va aparte, y lo de los sacers sombra o nos dices algo mas concreto, o no nos podemos poner a revisar 90 spells y talentos  de golpe.
