### ISSUE TITLE
[Druida] Arañazo

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#406]
Arañazo: http://es.wowhead.com/spell=1822/aranazo
El daño de arañazo esta demasiado alto mi war tiene 3400 temple + la armadura que es placa y me pegaron 40k con un tik de arañazo
![wowscrnshot_071113_144336](https://f.cloud.github.com/assets/3101842/790046/d538859c-eb1e-11e2-8afb-0d6877f3adf2.jpg)

**Comment by crowel** [comment]
Woola https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/398 ^^

**Comment by Dekadencee** [comment]
Reporte repetido, seguimos desde #398
