### ISSUE TITLE
[Misión] Disipando ilusiones

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#4061]
Misión: http://es.wowhead.com/quest=13149
Fallo: no están los Cajón de grano sopechoso para disipar.

**Comment by redneo** [comment]
Estan, al menos en heroico, ahora pruebo en normal. Cuando disipas los 5 que hay que disipar para que la mazmorra continue, te cuenta como completada la misión.

Edito, en normal también estan.
