### ISSUE TITLE
[Chaman] Totem elemental de tierra y fuego

### ISSUE THREAD

**Issue by Savian123** [RoDNet/Bugtracker-Infinium-4.3.4#4068]
Buenas quiero reportar estos dos totems que se pueden tirar a la vez cosa totalmente normal lo que no creo que sea normal es que puedas quitar esos totems y los elementales se queden como guardianes los 2 min adjunto foto

http://subefotos.com/ver/?8fa36bb4d0ec1378b8ae3161dbf6fabeo.png

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, no daremos mas soporte al actual
