### ISSUE TITLE
Bug o Aprovechamiento de bug

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#407]
Que me dicen de magos fuego usando congelacion profunda? :p

![wowscrnshot_071013_205817](https://f.cloud.github.com/assets/3101842/790058/1b5ae6f0-eb1f-11e2-9748-c385e3153f7c.jpg)

se ve claramente en el registro usando combustion y inmediatamente congelacion profunda aprovechamiento de bug y en arenas....

El jugador se llama Fulgor

**Comment by F4NT4SM4** [comment]
para que el no entienda Combustion se un hechizo de talento fuego y Congelacion profunda de talento Escarcha tiene puntos de mas en los talentos

**Comment by Dekadencee** [comment]
El pj lo acabo de bloquear yo hasta que el propietario nos indique como ha hecho esto posible, gracias por el aviso chicos

**Comment by ghost** [comment]
¡Solucionado!, en mi larga arena de 47 minutos y repleta de bugs, me ha dado por mirar porqué al explotar bomba viva y mi objetivo estar tras una columna, me salía el mensaje: "no puedes ver al objetivo". He mirado en el combat log y...sorpresa, sale eso: "Congelación profunda de Asman falló. (No puedes ver al objetivo)."

Por lo visto será un fallo de ID de la spell Bomba viva, o quizás tenga que ver con el Trinket Naipe de la Luna Negra: Volcano y que haya coincidido justo en ese momento..pero no creo.

**Comment by lllalvarolll** [comment]
Mmmmmm.. Yo soy Fulgor y no tenia ni idea de lo que estaba haciendo.. eso no es cosa mia sino del server :S yo no me estoy aprovechando de nada... no veo muy logico que por algo que hayan tocado de los magos me bloqueen el personaje..

**Comment by ghost** [comment]
Lo es, a ver si pueden pasarse y leer esto y te lo desbloquean...queriendo cortar por lo sano se han equivocado.

**Comment by Dekadencee** [comment]
@lllalvarolll tu personaje debería estar desbloqueado ya
