### ISSUE TITLE
[Guerrero] Glifo: Ira Rabiosa

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4070]
Nombre: Glifo: Ira Rabiosa
ID:43396 (es el id del glifo en el pergamino no conseguir el del efecto en si)
Descripcion: La facultad ira rabiosa genera 5p de ira al usarla
Problema: con solo tener el glifo puesto cualquier ataque recibido le esta generando al war demasiada ira

**Comment by efectokoleos** [comment]
arreglado ahroa si
