### ISSUE TITLE
[DK] Corrupcion Runica

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4072]
Nombre: Corrupcion Runica
ID:51459/51462
Enlace: http://wow.freakz.ro/spells.php?spell=51462
Descripcion: Reduce el coste de tu espiral de la muerte 3p/6p y provca que tu facultad potenciacion runica (81229) ya no reinicie una runa agotada, si no que aumente tu indice de regeneracion runica un 50%/100% durante 3s
Problema: el buff esta aumentando la celeridad como un 120% (lo cual creo que no deberia) deberia es aumentar la regeneracion de runa y no lo esta haciendo

**Comment by sakuranobushi** [comment]
El error ha sido corregido y debería verse pronto reflejado en los servidores de juego.
