### ISSUE TITLE
[Errores internos] Absorciones/reducciones de daño 

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4073]
Nombre: Absorciones/reducciones de daño
Descripcion: Las absorciones absorben el daño para evitar recibirlos directo
Problema: Las absorciones estan contando las reducciones de daño como temple y armadura esto no deberia pasar 
Las absorciones evitan que el daño llege a ti absorbiendolas como no llega a ti las reducciones de daño como temple armadura etc no deberian tener efecto 

Esto explicaria muchas cosas en el pvp por que un sacer es practicamente imposible de matar almenos que seamos mas de 3, absorciones de 25k con reduccion temple 60% y armadura 20% + 10% inspiracion (sacer) solo tendriamos un 10% de nuestro daño para quitar una absorcion de 25k que se reinicia cada 15s 
y dudo que muchos puedan meter 100k para quitar la absorcion del sacer 
me puse a ver videos y informar en los foro de blizzard y ninguno muestra que deba contar estas reducciones. En el video el escudo no dura mas de 5s lo cual aqui dura entero https://www.youtube.com/watch?v=SS_Yl6uGNhA

**Comment by edwyr** [comment]
Bueno no has puesto pruebas ni nada... así que me he puesto a probarlo pegando a un sacer en duelo y la pompa se quita con el daño que pone que absorbe, nada de 100k ni cosas de esas, ha absorbido los 27k de pompa y se ha quitado bien. Nose, alomejor si pones pruebas demuestras lo contrario.

**Comment by F4NT4SM4** [comment]
Descarga de escarcha 10k del mago
![wowscrnshot_091214_192820](https://cloud.githubusercontent.com/assets/3101842/4258733/9aefbf58-3ad8-11e4-825d-03f4339de837.jpg)

vemos como la descargar de escarcha paso a 4738 por que se redujo de 10k a 4.7k? 44.21% (temple) 15% (forma de sombras)
![wowscrnshot_091214_192946](https://cloud.githubusercontent.com/assets/3101842/4258748/01dca960-3ad9-11e4-8b6d-d01d51e2b8ab.jpg)

vamos hay se ve claramente que la absorciones estan contando las reducciones de daño como temple, buffos, etc...

**Comment by Kiritoo** [comment]
Actualmente por lo que vemos la absorción está contando la reducción te temple.
Podrías añadir algún enlace del oficial el cual exponga que no debería hacerlo y nos pongamos a mirarlo, ya que en la LK ya afectaba el temple a los efectos de absorción.

**Comment by Kiritoo** [comment]
Y referente a lo del sacerdote que comentas no creo que sea ese el problema, pero estaría bien que si ves algo raro en el tema de las absorciones quizás pueda ser por algún talento u aura lo revisaras y lo arreglamos, saludos.

**Comment by Monleon** [comment]
Las absorciones de daño contabilizan temple, armadura, talentos, etc desde hace ya bastantes parches.
