### ISSUE TITLE
[Misión] [Crash] Bienvenidos a la Máquina

### ISSUE THREAD

**Issue by ElBibliotecario** [RoDNet/Bugtracker-Infinium-4.3.4#4074]
Al finalizar la misión de dicho nombre, en Puerta Austral (Laderas de Trabalomas), crashea el servidor y te deja el efecto "Quest Giver" activado aún tras completarla y no se elimina ni manualmente ni muriendo, lo cual deja una exclamación sobre el personaje permanentemente.

El problema del efecto es molesto sólo de manera visual, pero el crasheo del server ya es un problema mayor.

**Comment by Kiritoo** [comment]
Estoy probando y es el motivo del crash ahora mismo lo revisamos, gracias.

**Comment by Kiritoo** [comment]
Arreglado.
