### ISSUE TITLE
[Guerrero] Mania sangrienta 

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4075]
Nombre: Mania sangrienta 
ID:16487/16489/16492
Enlace: http://wow.freakz.ro/spells.php?spell=16492
Descripcion: Tienes un 10% de probabilidad de generar un 1%/2%/3% de tu salud total durante 5s. despues de haber recibido daño
Problema: no se esta activando cuando recibo ataques automaticos

**Comment by efectokoleos** [comment]
arreglado
