### ISSUE TITLE
[Chaman] Latigazo de lava

### ISSUE THREAD

**Issue by Savian123** [RoDNet/Bugtracker-Infinium-4.3.4#4076]
Spellid:60103
Fallo: Daño exagerado aún sin cargas del totem

**Comment by F4NT4SM4** [comment]
tambien me acuerdo de un bug con los totem si vuelves a poner el totem ya teniendo 5 cargas aparece otro buff de totem facilmente tenineto unas 10 cargas nose si lo arreglaron...

**Comment by edwyr** [comment]
Sin cargas estoy pegando 7k sin critico y voy full cata, asi que no creo que sea exagerado

**Comment by Sagittariu5** [comment]
7k? 37k me ha pgado un chaman con 1 pieza cata, sin rabiar solo con Reyes, a mi pala healer con 4,7 de temple. eso no es normal. xd

**Comment by Overseer101** [comment]
Latigazo de lava: Main nuke del chaman, 10s de CD, daño de FUEGO no daño
fisico,(es decir te da igual ser placas), 260% de daño de arma con mano
izquierda como minimo, mas : Glifo de latigazo de lava, 20% mas de daño
sobre ese 260%, es decir no es 280%, es mucho mayor ya que es un bonus
multiplicativo, no aditivo, enchant de arma lengua de fuego aumenta otro
40% ese daño base, tambien multiplicativo, latigazo de lava mejorado,
aumenta un 20% el daño total,(es decir despues de tener en cuenta, glifos
talentos y demas historias) por cada carga de llamas abrasadoras, y por
ultimo la maestria del mejora, que aumenta TODO daño de escarcha, fuego o
de naturaleza,( y aparte, talentos de aumento de daño, el enchant propio
del lengua de fuego ademas aumenta un 7% tu daño magico, etc etc etc), asi
que lo siento, meten esas ostias de serie made in blizzard, el problema de
latigazo, afortunadamente para el que lo sufre es que usa el indice de
critico de hechizo en vez del melee, si no seria todavia peor.
