### ISSUE TITLE
[Druida](Buffo/activacion) Augurio de claridad ID16864

### ISSUE THREAD

**Issue by evangelion2009** [RoDNet/Bugtracker-Infinium-4.3.4#4077]
La spell de autoactivacion http://es.wowhead.com/spell=16864/augurio-de-claridad (revisada solo en heal al menos) dice claramente reduce el consumo de tu siguiente sanacion "no instantanea" un 100%.

Lo que actualmente hace es (depende como le de XD)
Opcion uno se activa y no se quita durante 2 spell sean inst o no reduciendo su consumo a 0.
Opcion dos se activa pero no reduce consumo en la priemra sanacion pero si en la segunda.
Opcion tres se activa y funciona como deve.
NOTA todas estas activaciones saltan con instantaneas tambien sea recrecimiento o cualquier inst de sanacion cuando solo deveria ser para las sanaciones de casteo(que es logico puesto que son las que mas cuestan para sanar a un solo objetivo)
Gracias por su atencion.

**Comment by efectokoleos** [comment]
arreglado
