### ISSUE TITLE
[DK] Maestria Escudo de Sangre Dnuevo!! 

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#408]
Bueno hace poco le hicieron fix a la maestria pero creo qe se equivocaron...
En ves de activarse en Presencia Sangre solamente
ahora solo se activar en presencia Escarcha

Mastria: http://es.wowhead.com/spell=77513/maestria-escudo-de-sangre
Presencia Sangre: http://es.wowhead.com/spell=48263/presencia-de-sangre

**Comment by Dekadencee** [comment]
Teniamos mal definida la id de la presencia de sangre en el emulador 48266 en lugar de 48263, muchas gracias por reportar de nuevo y disculpa las molestias.

Fixed, recuerda que debe caerse o reiniciarse el servidor para que los cambios puedan ser visibles
