### ISSUE TITLE
Incripción bug

### ISSUE THREAD

**Issue by Dartz1** [RoDNet/Bugtracker-Infinium-4.3.4#4080]
Hay un problema,no se si todos pero cuando quiero abrir el panel de la profesión no me lo permite en cambio con otras profesiones esto si sucede , espero y puedan arreglar el bug lo mas pronto posible ya que me gustaría dedicarme a la venta de glifos y pues de antemano gracias y espero que me ayuden con mi problema.

**Comment by efectokoleos** [comment]
pon un ticket ingame y te lo miraremos lo antes posible

**Comment by Monleon** [comment]
Puedes abrirla con /cast Inscripción?

**Comment by Dartz1** [comment]
me podría dar las indicasiones de como quiere que ponga el tiket? es que la vez pasada ya lo hice y creo que la persona que me atendió no comprendió mi problema , Gracias

**Comment by IvanDiGreat** [comment]
Solo relogea ami me pasaba antes pero relogeando ya se abre

**Comment by Dartz1** [comment]
No Ivan ya lo intente de mil maneras

**Comment by Kiritoo** [comment]
Si persiste, al foro o ticket ingame.
Saludos.
