### ISSUE TITLE
Teleport de ICC

### ISSUE THREAD

**Issue by IvanDiGreat** [RoDNet/Bugtracker-Infinium-4.3.4#4084]
Bueno jms el teleport que nos deveria llevar al tercer boss de ICC no funciona ni en Normal ni en Heroico espero le arregle :). Gracias de antemano.

**Comment by IvanDiGreat** [comment]
http://kn3.net/3287862A6C0JPG.html aqui dejo una imagen

**Comment by Kiritoo** [comment]
Hicisteis la batalla naval antes de  intentar ir al tercero?

**Comment by efectokoleos** [comment]
cierto que aun no esta compilado infi XD

**Comment by IvanDiGreat** [comment]
Se intento de todo pero nada :( pero esperemos que le arreglen

**Comment by efectokoleos** [comment]
arreglado hasta k vovlamos a poner la batalla
