### ISSUE TITLE
[Talento-Cazador]Instruccion de francotirador

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#4086]
Nombre: Instrucción de francotirador
Enlace: http://es.wowhead.com/spell=53302/instruccion-de-francotirador
Problema: Se activa solo cuando el cazador entra en combate (6 segundos despues de empezar el combate), cuando debería de activarse si el cazador se encuentra estático aun cuando no esté en combate, de esa forma se mantiene la idea del talento: ser un francotirador y prepararse cuando todavía no dispara.

**Comment by efectokoleos** [comment]
arreglado
