### ISSUE TITLE
[Paladín holy] Auras de resistencia y represión

### ISSUE THREAD

**Issue by LI0NSH34RT** [RoDNet/Bugtracker-Infinium-4.3.4#4087]
En la imagen no se puede apreciar pero las auras de represión y resistencia funcionan mal.
[Aura de represión] genera menos daño sagrado del que debería, 121 de daño sagrado cuando debería ser 402
[Aura de resistencia] da 460 de resistencia cuando debería ser 195 en decir mas del doble
aparte si se usa [Maestría en auras] ni aumenta ni disminuye la cantidad
![curas](https://cloud.githubusercontent.com/assets/8160853/4296079/7a29877e-3df1-11e4-8eef-577a94d57a4a.jpg)
y quería felicitaros , [señal de luz] que parece que funciona como debería :)
como se puede apreciar en la imagen estoy probando [luz sagrada] y me sana el 100% sin embargo con otra habilidades solo me sana el 50% , buen trabajo :)

**Comment by efectokoleos** [comment]
aura de resistencia arreglada, el aura de reprension hace bien el daño aunque en el bufo que te da pone 121, sin embargo en la barra de auras te marca el daño correctamente
