### ISSUE TITLE
GUerrero furia SED DE sangre no genera ira

### ISSUE THREAD

**Issue by conqueron** [RoDNet/Bugtracker-Infinium-4.3.4#4088]
http://es.wowhead.com/spell=23881/sed-de-sangre y http://es.wowhead.com/spell=18499/ira-rabiosa

cuando estoy en talentos Furia, el poder sed de sangre e IRa Rabiosa  no generan ira  por lo que no puedo usar otros poderes en conclusion no puedo hacer buen dps pve.

**Comment by Overseer101** [comment]
....... Alma de cántaro..., eso son las descripciones de Pandaria, en cata sed de sangre CONSUME 20p de ira, e ira rabiosa no genera ira a no ser que este con el glifo.....
