### ISSUE TITLE
[Sacerdote] Palabra sagrada:Santuario ID 88685

### ISSUE THREAD

**Issue by evangelion2009** [RoDNet/Bugtracker-Infinium-4.3.4#4089]
La spell ligada al chakra que aumenta sanaciones en area https://wow.freakz.ro/spells.php?spell=88685&name=holy-word-sanctuary esta sanando el doble o incluso el triple por tick cuando su efecto es 327 (+4.2% SP) calcule con 8k de sp y me da 327+400=727 si le añades el 15% por el chakra 727+109=836 de sanacion por tick(actualmente hace 2500 de normal y 5k en critico superando a la lluvia del chaman en varios casos cosa que no me parece justa para ellos(soy sacerdote heal  que conste XD))

Gracias por su atencion.

**Comment by Overseer101** [comment]
Arreglado
