### ISSUE TITLE
No se puede pasar objetos horda-alianza

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#409]
Bueno, el reporte radica en esto, y no hablo de pasarle a cualquier pj, sino solo a los de mi cuenta.

Por ejemplo, pasar un objeto Ligado a la CUENTA de un pj mio horda a un pj mio alianza, no puedo...

me supongo que al menos entre mis pjs si se deberia dejar.

**Comment by Kiritoo** [comment]
Actuamente está activado el intercambio de objetos por correo, de alianza a horda o horda a alianza.
Saludos.
