### ISSUE TITLE
Poblado Brunnhildar - misiones

### ISSUE THREAD

**Issue by Luis2403** [RoDNet/Bugtracker-Infinium-4.3.4#4090]
Hola estoy en poblado brunnhildar y no puedo entregar las misiones:
Aberraciones (es.wowhead.com/quest=12925)
Fuera sus alas negras (http://es.wowhead.com/quest=12942)
Valkyrion debe arder (http://es.wowhead.com/quest=12953)
La insensatez de Yulda (http://es.wowhead.com/quest=12968)
La última de su raza (http://es.wowhead.com/quest=12983)
los pnj no estan para entregar la mision
borré la carpeta cache y sigue igual
![wowscrnshot_091714_115817](https://cloud.githubusercontent.com/assets/8336969/4305735/7601defa-3e7b-11e4-9785-0f0f35d69060.jpg)
![wowscrnshot_091714_115839](https://cloud.githubusercontent.com/assets/8336969/4305736/7603832c-3e7b-11e4-943a-3af54e62b634.jpg)
![wowscrnshot_091714_115854](https://cloud.githubusercontent.com/assets/8336969/4305737/7620a25e-3e7b-11e4-9ee7-3ef77b1ec7c6.jpg)

**Comment by nayan87** [comment]
mmmmm, yo las hice ayer leveando a mi brujete y funcionaba perfectamente, mira a ver si has echo algo de mas adelante de la cadena, ya que los hijos de hodir es una cadena de fase temporal, en cristiano: si haces algo que no debes pues la cagas  y te quedas sin las quest previas, espero que haya suerte

**Comment by Luis2403** [comment]
gracias nayan87 ya fue solucionado el problema
