### ISSUE TITLE
[Guerrero] Segundo aliento

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4092]
ID: 42771
El problema es que se recibe más sanacion cuando tienes puesto 1 solo punto de talento que cuando tienes los 2 puntos puestos en ese talento

**Comment by F4NT4SM4** [comment]
dices que el 1/2 esta bug por que cura mas que el 2/2
al menos hiciste los cálculos? 
el segundo aliento 1/2 y 2/2 estan bien solo que el 2/2 se bugea por vendaje de batalla haciendo que cure menos de lo que deberia
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/4044
no estoy jugando pero de ves en cuando me paso por aqui a ver si arreglaron los bug que reporte

**Comment by efectokoleos** [comment]
arreglado falta compilar
