### ISSUE TITLE
[Druida] Augurio de claridad 

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4093]
Id: 16864 (https://wow.freakz.ro/spells.php?spell=16864)

Este pasivo debería tener una "pequeña probabilidad" de que los hechizos y ataques ofensivos te hagan entrar en estado de lanzamiento libre el cual permite reducir el coste de ese ataque (ira o energia) u hechizo (maná en el caso del pollo) un 100%.

El problema es que ahora mismo se está activando una y otra vez con cualquier ataque lo que hace que no baje ni la energía ni la ira ni el maná. Es decir no tiene coste ninguno esta clase en estos momentos debido a este fallo. No se si se llegó a implementar ayer y luego se bugueo o está a la espera de implantación, por si acaso lo he reportado.

Un saludo y gracias

**Comment by efectokoleos** [comment]
arreglado
