### ISSUE TITLE
(Talento Mago) Buena Racha y Buena Racha Mejorada

### ISSUE THREAD

**Issue by Bichoculiao** [RoDNet/Bugtracker-Infinium-4.3.4#4095]
Es muy simple no tomara mucho tiempo, Piroexplosion no funciona con estos talentos, me explico, probe hace 2 semanas 100 Piroexplosiones y ninguna provoco Buena Racha o Buena Racha Mejorada (2 criticos continuos) incluso pege 5 criticos continuo ni nada, solo Piroexplosion no se beneficia y el bug es que Bomba Viva si lo activa al explotar siendo que esta habilidad no deberia (he visto que aveces me salta Buena Racha con esta habilidad)
Gracias!

**Comment by efectokoleos** [comment]
puedes poner ids de los talentos?

**Comment by kikete17** [comment]
buena racha: 44445
buenas racha mejorada; 44448

**Comment by efectokoleos** [comment]
arreglado
