### ISSUE TITLE
[Sacerdote] Palabra de las sombras muerte ID 32379

### ISSUE THREAD

**Issue by evangelion2009** [RoDNet/Bugtracker-Infinium-4.3.4#4096]
La palabra de las sombras muerte https://wow.freakz.ro/spells.php?spell=32379&name=shadow-word-death junto con masoquismo de sacer sombras https://wow.freakz.ro/spells.php?spell=88995&name=masochism por alguna razon que no comprendo esta dando en vez de 10% de mana 20% (dos veces)
Notas a tener en cuenta
Solo ocurre cuando el enemigo tiene menos de un 25% de vida.
Fue probada tanto con el glifo como sin el sin que este afecte a la misma (logicamente con glifo al dispararlo dos veces te acaba dando 40% mana)
Si la lanzas a un objetivo con mas de ese 25% de vida funciona como deveria ser.
Gracias por su atencion.

**Comment by Monleon** [comment]
Esto funciona ya.
