### ISSUE TITLE
[Mision] Adiós, pezqueñín ID 14392

### ISSUE THREAD

**Issue by evangelion2009** [RoDNet/Bugtracker-Infinium-4.3.4#4097]
La mision adios pezqueñin http://es.wowhead.com/quest=14392 no da la recompensa correcta cuando, aparte de lo basico que es dinero y exp deveria dar http://es.wowhead.com/item=53057.

Nota :pillar la mision del boss es bastante dificil por culpa de que esta volando cuando lo ves pero cae cuando llega pese a todo se puede(con esfuerzo y relogs) pero se puede.
Gracias por su atencion.

**Comment by redneo** [comment]
A mi si que me ha dado el item.
