### ISSUE TITLE
[Talento-Cazador]Instruccion de francotirador

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#4098]
Nombre: Instrucción de francotirador
Enlace: http://es.wowhead.com/spell=53302/instruccion-de-francotirador
Problema: Se activa solo cuando el cazador entra en combate (6 segundos despues de empezar el combate), cuando debería de activarse si el cazador se encuentra estático aun cuando no esté en combate
Nota: Reabro el reporte pues ha sido mencionado como arreglado, aquí https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/4086#event-166766498, pero no ha sido así. El talento si funcionaba si el cazador estaba en combate (tal como sigue ahora), pero debe de activarse aún cuando el cazador no esté en combate, y no lo hace.

**Comment by Jhovanni** [comment]
Acabo de probarlo mas a fondo, y si hubo cambios con respecto al reporte anterior. Ahora el bufo no se activa aún estando quieto si no se está en combate (tal como estaba), pero nada mas al entrar en combate si estaba quieto el cazador, el bufo se activa al segundo de empezar el combate.
Es un cambio, sin embargo aún debería estarse activando cuando el cazador pasa 1hora en una ciudad sin pelear ni nada.

**Comment by efectokoleos** [comment]
falta compilar
