### ISSUE TITLE
[Hechizo-Paladin]Aura de resistencia

### ISSUE THREAD

**Issue by Jhovanni** [RoDNet/Bugtracker-Infinium-4.3.4#4099]
Nombre: Instrucción de francotirador
Enlace: https://wow.freakz.ro/spells.php?spell=19891
Problema: Desde un cambio en la tarde está otorgando 460 de resistencias aumentadas, algo así como 43% de reducción de daño.

**Comment by efectokoleos** [comment]
esta arreglado falta compilar
