### ISSUE TITLE
Talento [Fuerza del Alma] Sacerdote disciplina

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#41]
http://db.mmo-champion.com/utils/talents/#k=ffR.bqj.priest.

Strength of Soul: Quinta fila en la rama de talentos de disciplina.

Este talento funcionaba perfectamente en el 4.0.6, ahora por desgracia no ocurre. Además deja un bug muy molesto.

Vamos por partes:
- Tras utilizar la spell "enfoque interno" http://old.wowhead.com/spell=89485 y con el talento de "Fuerza del alma", el sacerdote debería ser inmune a silencios, disipaciones e interrupciones durante 5segundos. 
  Edito: Esto no está ocurriendo del todo bien, ya que solo nos hace inmunes durante 2segundos (es decir, como si solo le hubieramos puesto un punto de talento), cuando al utilizar 2 puntos de talentos deberíamos ser inmunes durante 5segundos

-Al utilizar "sanar", "sanación relampago", o "sanacion superior" sobre un objetivo afectado por "alma debilitada"  http://es.wowhead.com/spell=6788/alma-debilitada este debuff debería reducirse en 4segundos por cada cura realizada con cualquiera de estas 3 habilidades. Esto está ocurriendo, el problema y muy molesto, es que cuando a alma debilitada le quedan menos de 4segundos de duración, y utilizamos alguna de estas curas, el debuff de alma debilitada pasa a durar 0seg. Y estos "0seg" están ahi infinitamente, ni con un reload desaparece. Es decir tenemos el debuff de "alma debilitada" a perpetuidad, y por tanto no podemos ser beneficiados con un nuevo Escudo http://es.wowhead.com/spell=17/palabra-de-poder-escudo , hasta que no muramos.

Un saludo, y gracias por los futuros arreglos.

**Comment by searum** [comment]
fiiiiiix! :D
