### ISSUE TITLE
[Intendente] De Conquista

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#410]
El intentende de conquista de la horda Sargento tronacuerno http://es.wowhead.com/npc=54658/sargento-tronacuerno

vende unas partes del equipo implacable, pero no vende ni pechera, ni yelmo, ni nada, solo vende abalorios, armas, anillos collares y eso.

(intente buscar en wowhead pero no encontre los objetos)

**Comment by redneo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/493 podias decirme al menos de que clase, por ejemplo de dk http://es.wowhead.com/itemset=-348

**Comment by SherBlader** [comment]
ya esta arreglado
