### ISSUE TITLE
Limpiar paladin (Retry)

### ISSUE THREAD

**Issue by kikete17** [RoDNet/Bugtracker-Infinium-4.3.4#4100]
https://wow.freakz.ro/spells.php?spell=4987&name=cleanse

Problema:Esta limpiando hechizos que no debe como bomba viva(44461) o fuego feérico(16857),
basicamente es como si estuviera utilizando el talento limpieza sagrada(53551) en retry

**Comment by efectokoleos** [comment]
falta compilar
