### ISSUE TITLE
[NPC] Anacoreta Kairthos

### ISSUE THREAD

**Issue by IvanDiGreat** [RoDNet/Bugtracker-Infinium-4.3.4#4103]
Bueno la cosa que este npc te deberia de dar esta mision (Un benefactor magnánimo id=11549) y al completarla te da el titulo del sol devastado pero no la da o ya no se puede? se supone que si :)

**Comment by redneo** [comment]
Necesitas reputación exaltado con esa facción para que te la de la misión.
