### ISSUE TITLE
[Items] Sombrero de zahorí descolorido ID 53057

### ISSUE THREAD

**Issue by evangelion2009** [RoDNet/Bugtracker-Infinium-4.3.4#4104]
Bueno pongo esto tras la rapida respuesta(sobre todo tratandose de un objeto superfluo) pero parece que el objeto no funciona http://es.wowhead.com/item=53057/sombrero-de-zahori-descolorido#english-comments como bien dice en los comentarios.
Los de el español.:30 minutos de buff, 30 minutos de CD,(rectificado por comentario en ingles el efecto no deveria persistir si te lo quitas asi que eso funciona), si no me equivoco hay 15 transformaciones diferentes que pueden salir al random. de momento no cambio mi raza como un disfraz.(aunque seguire probando en la tarde no vaya a ser)
En comentarios en ingles:
Here are a few things of interest about the item (some of these are from other comments posted here).
You can remove the hat after you have transformed and the transformation will stay. (removed this ability)
The duration of the transformation is 30 minutes. This means you can always be transformed since the duration and cooldown are the same length.
The transformation only shows your weapons. The rest of your look is determined by the transformation.
The item is marked as a Quest Item so be careful not to throw it away on accident.
All emotes you do while transformed are those of the race and gender you are transformed into.
Druid forms cause you to lose the transformation. This is likely true of any class transformation.
Deathbringer's Will does not cause you to lose the transformation buff. When the Deathbringer's Will effect wears off you will return to your transformed state.
This is a reward to a Horde quest. If you race change you will lose the item since it is labeled as a quest item. As long as you are still Horde a GM can restore the item for you.
There are 16 different transformations. Click the links below to view each one.
Male Goblin 1, Male Goblin 2, Female Goblin 1, Female Goblin 2
Male Blood Elf 1, Male Blood Elf 2, Male Blood Elf 3, Female Blood Elf
Male Undead, Female Undead
Male Orc
Female Troll
Male Human, Female Human
Male Gnome
Female Night Elf

Bueno creo que la mayoria sabemos ingles a estas alturas asi que no creo que haga falta traducir XD.
Como ya dije ire probandolo en la tarde (puesto que tiene cd de 30 min) si por algun casual noto que funciona algo o tal reeditare el post con esos datos.Adjunto la spell que te colocaria http://es.wowhead.com/spell=74589#used-by-item

Como siemrpe gracias por su atencion.

**Comment by redneo** [comment]
Arreglado cuando se compile el servidor.
