### ISSUE TITLE
[Misiones]Bastion fauces de madera (2 misiones) IDs 28395 y 28523

### ISSUE THREAD

**Issue by evangelion2009** [RoDNet/Bugtracker-Infinium-4.3.4#4105]
Basicamente son las misiones(obligatorias) para llegar a exaltado con esta faccion.Una es http://es.wowhead.com/quest=28395 y la otra es http://es.wowhead.com/quest=28523 no funcionan ambas o las da solo una vez como una diaria tras la mision en la que pide 10 de ambas.
Notas a tener en cuenta:
El drop de los objetos para las misma va bien y lo sueltan incluso sin mision.
Es una mision repetible (vamos que puedes hacerla 100 veces si quieres)Esto no funciona.
Desconozco cuanta repu dara si es que se arregla pero segun marca es 2000 por entrega.

Y como una nota extra el objeto http://es.wowhead.com/item=66888 que deverias poder comprarle al npc http://es.wowhead.com/npc=11557 cuando llegas a exaltado no esta en sus objetos de compra.

Con esas misiones seria posible sacarse el logro (y titulo si te lo curras) y si se añade la vara pues mira un disfraz mas XD.
Gracias por su atencion.

**Comment by redneo** [comment]
De nada y cerrado.

Aplicado cuando se reinicie el servidor.
