### ISSUE TITLE
[Profesión] Paño onírico

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#4108]
Profesión: Sastrería

Spell:
· Sueño de Azshara (http://es.wowhead.com/spell=75146)
· Sueño de Hyjal (http://es.wowhead.com/spell=75144)
· Sueño de Infralar (http://es.wowhead.com/spell=75142)
· Sueño de Muro Celeste (http://es.wowhead.com/spell=75141)
· Sueño de Ragnaros (http://es.wowhead.com/spell=75145)

Fallo: se reinicia el cd tomando portales o siendo summoneado. Excepto el craft Sueño de destrucción (http://es.wowhead.com/spell=94743) que no se reinicia.

**Comment by efectokoleos** [comment]
arreglado
