### ISSUE TITLE
[Paladín] Aura de resistencia

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4109]
Id: 19891

Se ha puesto esto en el changelog y se dijo que estaba arreglado pero sigue otorgando 460 puntos de resistencia cuando solo debería dar 195 puntos. Se dijo que estaba arreglado y que faltaba compilar, no se si se hizo o es que ha vuelto a surgir el problema, pero ahora mismo el paladín reduce un 43% todo el daño mágico de fuego, sombras y escarcha por lo que clases como magos, brujos y sacerdotes tienen una desventaja considerable contra esta clase.

Un saludo y gracias

**Comment by efectokoleos** [comment]
se acaba de compilar, en la proxima caida o reinicio quedará aplicado el cambio
