### ISSUE TITLE
Runas de Muerte dk

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4111]
en determinado momento, al lanzar unas habilidades, he quedado con 6 runas de muerte, andando libre en el mundo, fuera de mazmorra y bg.

Ademas cada vez que me invocan o uso portales se me convierten las 2 runas de muerte de la especialidad de escarcha en 2 runas de sangre

**Comment by Monleon** [comment]
Esto ya no debería pasar
