### ISSUE TITLE
Bug en el evento del mes de la cervesa

### ISSUE THREAD

**Issue by Elmentalista** [RoDNet/Bugtracker-Infinium-4.3.4#4115]
Bueno el problema es que  [Formulario de socio del Club de la "Cerveza del Mes"] no se puede aceptar la mision y por lo mismo no se puede completar la mison ayudaaaa

**Comment by Kiritoo** [comment]
Id de la misión?

**Comment by Kiritoo** [comment]
Esto funciona correctamente.

**Comment by Elmentalista** [comment]
como puedo poner el id de la mision ya que tampoco sirve la montura del festival ya que lo compre y no me aparece en las monturas

**Comment by Kiritoo** [comment]
¿Comprar Montura de festival? ¿No comprarias un compañero?, revisa la pestaña compañeros al lado de la de monturas.

**Comment by Elmentalista** [comment]
tienes mucha razon bro gracias muchas gracias, pero  [Formulario de socio del Club de la "Cerveza del Mes"] no puedo aun aceptar la mision, mas bien no me deja ni siquiera abrirla para aceptar la mision
