### ISSUE TITLE
mision : la purificacion del queldelar

### ISSUE THREAD

**Issue by xxjuniorlll** [RoDNet/Bugtracker-Infinium-4.3.4#4116]
mision:http://es.wowhead.com/quest=24598/la-purificacion-de-queldelar
falla: cuando cojes la mision no aparecen los celeradores de la meseta fuente del sol .... siempre tienen q estar en la puerta de la mazmorra meseta fuente del sol pero no estan...sin ellos la mision nunca se completara

**Comment by nayan87** [comment]
+1 saludos¡

**Comment by Monleon** [comment]
Npc añadido
