### ISSUE TITLE
Falta npc para terminar Desprevenidos en Monte Hyjal.

### ISSUE THREAD

**Issue by Alondra1012** [RoDNet/Bugtracker-Infinium-4.3.4#4117]
Falta el npc Archidruida Hamuul Totém de Runa { http://es.wowhead.com/npc=52838 } que deberia de estar en el Santuario de Malorne en Monte Hyjal para entregar Desprevenidos { http://es.wowhead.com/quest=29197 } ¿Podrian colocarlo en donde corresponde? Gracias :)

**Comment by JoakRoD** [comment]
El NPC se encuentra en su lugar.

**Comment by Alondra1012** [comment]
A mi no me sale,y a otras 2 personas me han dicho que ha ellos tampoco.

**Comment by Monleon** [comment]
Junto al portal para entrar en el frente de magma? Yo alcanzo a verlo

**Comment by Alondra1012** [comment]
A mi no me sale ni en el santuario ni a un lado del portal :/

**Comment by Alondra1012** [comment]
![wowscrnshot_100114_204837](https://cloud.githubusercontent.com/assets/8869741/4485919/30bdb5ce-49d6-11e4-9422-f361372b6417.jpg)

**Comment by Alondra1012** [comment]
![wowscrnshot_100114_204821](https://cloud.githubusercontent.com/assets/8869741/4485922/3e8603e6-49d6-11e4-8f9d-9cb6c082190f.jpg)

**Comment by juaks** [comment]
Sí está el npc, realiza todas las misiones porque le acabo de completar una misión xD

**Comment by Alondra1012** [comment]
Parece que solo yo soy a quien no le aparece..

**Comment by juaks** [comment]
Pero has hecho todas las misiones? O solo la que coges en orgrimmar..

**Comment by Alondra1012** [comment]
Ya las hice todas,entrego desprevenidos y solo me faltaria una.
