### ISSUE TITLE
Tengo un bug y al parecer soy el unico

### ISSUE THREAD

**Issue by Elmentalista** [RoDNet/Bugtracker-Infinium-4.3.4#4119]
Pues ya intente contactarme y reportarlo y nadie me ayuda a solucionarlo, es sobre  [Formulario de socio del Club de la "Cerveza del Mes"] no puedo abrir el formulario para aceptar la mision y nadie me ayuda o me da una solucion ayuda por fas

**Comment by JoakRoD** [comment]
Pon ticket ingame explicándolo y te lo resolvemos.

**Comment by Elmentalista** [comment]
gracias

**Comment by Elmentalista** [comment]
y perdon por las molestias pero ningun servidor me habia ayudado a solucionar los problemas y con tanta eficacia muy buen servidor
