### ISSUE TITLE
[Paladín]  Sentencias y Próposito Divino

### ISSUE THREAD

**Issue by ReckLuLz** [RoDNet/Bugtracker-Infinium-4.3.4#412]
Bueno no sé si está ya reportado pero yo lo informo aquí.
El Paladín retry esta pegando más de lo normal.

http://tinypic.com/view.php?pic=azf62v&s=5
Lo que se ve: La sentencia pega dos veces cuando solamente deberia de dar uno.
El Próposito Divino esta Bug/Over se supone que cuando se activa tienes 7 segundos para que el siguiente ataque no consuma poder sagrado(el bug esta que cuando se activa tienes poder sagrado infinito)

Todo esto ha sido de ayuda de 2 palas.
No sé si esta mal que salga el nombre del paladín que me ha ayudado a reportar, pero el no tenia intención ninguna de aprovecharse del bug.
Un saludo!!

**Comment by searum** [comment]
fix
