### ISSUE TITLE
[Misiones][Páramos de Poniente] Las palabras de despedida de Lou

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4122]
Buenas.
• Nombre: Las palabras de despedida de Lou
• Enlace: http://es.wowhead.com/quest=26232
• Descripción: Espía a los matones detrás de la granja en la Plantación de Calabazas de Cejade, en Páramos de Poniente. 
• Problema: Al acercarse a donde están los matones (http://es.wowhead.com/npc=42387) no sucede nada. También se acumulan tantos que al pasar bajan los fps drásticamente.
Desde ya muchas gracias y hasta luego

**Comment by Kiritoo** [comment]
He desactivado el script de la misión por ahora, lo probare en test. Gracias por avisar.

**Comment by Katana69** [comment]
sigue bug

**Comment by phamtomix** [comment]
hola la mision sigue bug espero la puedan arreglar pronto..!
