### ISSUE TITLE
Campeon de "El torneo Argenta"

### ISSUE THREAD

**Issue by javier1200** [RoDNet/Bugtracker-Infinium-4.3.4#4124]
Comense las misiones diarias del torneo argenta y me percate que hay un inconveniente al intentar volverse campeón de mas de una facción, Se supone que al acabar la misión de "La carga del valeroso" http://es.wowhead.com/quest=13714/la-carga-del-valeroso Con la facción correspondiente a tu raza (Al yo ser huarguen me mando con los elfos nocturnos) y al acabar la misión "El desafió del valeroso" http://es.wowhead.com/quest=13713 Ganas el logro de campeon de la faccion y alli puedes elegir otra faccion para hacer las diarias y lograr ser campeon con el resto (en mi caso Enanos, Gnomos, Dranei y humanos) y sacar este logro http://es.wowhead.com/achievement=2782 . 

Bien no se desbloquean las misiones con el resto de las facciones y uno solo puede llegar a ser campeón con una capital, la tuya por raza, Al llegar a ser campeon con una faccion, el resto de las facciones deberian poder darte la mision de "La carga del valeroso" y permitirte ser campeones con ellos (Solo 1 faccion a la ves).

**Comment by juaks** [comment]
Yo soy campeón de todas las facciones.. has probado el mismo día en que has sido campeón? Debe pasar un día para que te den las siguiente.

**Comment by JoakRoD** [comment]
Funcionan perfectamente.
