### ISSUE TITLE
[NPCs] Tol Barad - Alianza

### ISSUE THREAD

**Issue by juaks** [RoDNet/Bugtracker-Infinium-4.3.4#4127]
Los NPC:

Segundo teniente Wansworth (http://es.wowhead.com/npc=48061)
Comandante Stevens (http://es.wowhead.com/npc=48039)
Alguacil Fallows (http://es.wowhead.com/npc=48074)
Sargento Parker (http://es.wowhead.com/npc=48066)

Deberían estar montados en grifos voladores.

Foto:
http://wow.zamimg.com/uploads/screenshots/normal/418851.jpg

**Comment by redneo** [comment]
Montados estan.
