### ISSUE TITLE
Sentencia del Paladín golpea 2 veces.

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#413]
Aquí en las fotos siguientes verán como luego de lanzar "Sentencia" 1 sola vez, el efecto es que golpea 2 veces. 

![1](https://f.cloud.github.com/assets/4944904/791558/7a5495b4-eb49-11e2-8d5a-be3a584db30f.jpg)  
![2](https://f.cloud.github.com/assets/4944904/791559/84d5e70e-eb49-11e2-8e50-3c021dc542de.jpg)  
![3](https://f.cloud.github.com/assets/4944904/791560/8d5455dc-eb49-11e2-93da-916a43fca0e9.jpg)   

Todas las capturas son de un mismo ataque.

Nota: no conseguí en link de la habilidad, los que consegui eran de pandaria.

**Comment by searum** [comment]
es el sello de rectitud, fix
