### ISSUE TITLE
[Tierras de Fuego] Shannox - Ruptura de magma

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#4130]
Al matar a un perro, Shannox entrá en una especie de enrage que hace que cause más daño. Además ahora ya no tirará mas lanzas, sino que tira rupturas de magma(http://es.wowhead.com/spell=99840) que hacen una espiral de fuego donde el principio de la espiral es el propio boss. 
El problema es que a veces por texturas o lo qe sea, aun estando fuera de la espiral te toca. La primera aun te puedes salvar pero con la segunda ya no porque te deja el debuff de la primera.

Las espirales deberían ser más anchas para no tene estos problemas de texturas que hasta al tanke lo deletean por estar en el medio y no tener mucho margen de maniobra.

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.
