### ISSUE TITLE
Druida Tecnica "Mordedura feroz"

### ISSUE THREAD

**Issue by javier1200** [RoDNet/Bugtracker-Infinium-4.3.4#4138]
Este remate funciona a medias ya que aun no se gasta energía adicional (Hasta un maximo de 60 de energia en total) para incrementar su daño

**Comment by efectokoleos** [comment]
necesito ids...

**Comment by ExodusDK** [comment]
https://wow.freakz.ro/spells.php?spell=22568&name=ferocious-bite

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, no daremos mas soporte al actual
