### ISSUE TITLE
Druida Glifo "Glifo de Recrecimiento"

### ISSUE THREAD

**Issue by javier1200** [RoDNet/Bugtracker-Infinium-4.3.4#4139]
Este glifo no funciona, su objetivo debe ser restablecer la curación de recrecimiento de manera instantánea cuando el objetivo tiene su vida igual o menor al 50 % pero no la restablece

**Comment by ExodusDK** [comment]
https://wow.freakz.ro/spells.php?spell=54743&name=glyph-of-regrowth hay que poner siempre la id...

**Comment by efectokoleos** [comment]
funciona despues del arreglod e dots y hots
