### ISSUE TITLE
Profesion de alquimia

### ISSUE THREAD

**Issue by javier1200** [RoDNet/Bugtracker-Infinium-4.3.4#4140]
Al volverse alquimista uno obtiene una pasiva (  http://es.wowhead.com/spell=53042/la-ciencia-de-la-mezcla ) que aumenta el efecto y duplica la duración de toda poción, elixir o frasco (Amenos que este especifique que no se beneficie de "La ciencia de la mezcla") si el alquimista consume algo que el mismo pueda crear
 Pos esa pasiva no funciona ya que ni duplica la duración ni aumenta el efecto de ningún elixir, frasco o poción que el alquimista crea o pueda crear al consumirla

**Comment by Overseer101** [comment]
Te corrijo, Ciencia de la mezcla no afecta a las pociones, solo aumenta la duracion y la magnitud de los efectos de los frascos y elixires, y aparte, a mi si me funciona correctamente
