### ISSUE TITLE
Stratholme

### ISSUE THREAD

**Issue by nzretry** [RoDNet/Bugtracker-Infinium-4.3.4#4141]
Hola la mazmorra La Matanza de Stratholme esta bug ya que no funciona ninguna mision y no hay ningún boss para matar. Me gustaría por favor que la arreglaran o por lo menos que coloquen el Boss (Corruptor Infinito) dentro de la mazmorra en algún lugar para poder matarlo y así obtener su lot que suelta una montura voladora El DRACO BRONCE, gracias. Un saludo

**Comment by Monleon** [comment]
Te dan la misión, funciona, aparece Arthas, funciona, inicia el evento, aparecen los bosses.
