### ISSUE TITLE
daño de matar de cazador bestias

### ISSUE THREAD

**Issue by Devyal** [RoDNet/Bugtracker-Infinium-4.3.4#4144]
el daño de la habilidad matar hace un daño aproximado de 3 k siendo 6 k critico, cuesta 40 p. de enfoque y tiene un cd de 6 s, por ejemplo el disparo arcano si llega a pegar 18 k costando 22p y pudiendose lanzar varias veces seguidas, estas cifras son aproximadas, siendo 6 k de matar algo muy poco viable y creo erroneo.

gracias.

**Comment by Devyal** [comment]
aclaro, los valores anteriores son obtenidos en los palos de ventormenta, contra players se reduce el daño aun mas debido al temple armadura etc.

**Comment by Monleon** [comment]
No probeis spells de daño físico en dummies, probadlos en jugadores sin talentos ni equipo. Los dummies tienen armadura como un boss

**Comment by Devyal** [comment]
El punto es que el daño es muy bajo de matar 6k critico no sirve de mucho, es mas es preferible hacer un disparo arcano que un matar, en alguien sin talentos ni armadura el daño es lógico que suba, sin embargo en la practica 3 k de daño para una habilidad tan importante es algo totalmente inviable, limitando a la rama bestias a solo disparo arcano practicamente

**Comment by Monleon** [comment]
Pero para poder corregirlo necesitamos la ID. Fijate en el resto de issues que tienen un enlace con la id a la fórmula junto al coeficiente de esa spell. Primero podeis probarlo vosotros y si veis que haciendo números no es correcto, nos lo reportais.

**Comment by 3du42d0** [comment]
ID=34026 "Da la orden de matar, lo que provoca que tu mascota inflija al instante (849 + (Ranged attack power \* 0.516)) \* 1 de daño a su objetivo.". He probado este comando en varios servers y doy fé de que está Nerf. saca demasiado poco y arruina toda la rama de Talentos Bestia. ojalá lo arreglen porque es el hechizo más importante de la rama. saludos!! LINK:http://es.wowhead.com/spell=34026/matar#changelog corresponden a la versión 4.2 que fue la última revision para este comando en cataclysm al parecer saludos!!

**Comment by efectokoleos** [comment]
arreglado
