### ISSUE TITLE
Mision Desprevenidos Monte Hyjal.

### ISSUE THREAD

**Issue by argentito89** [RoDNet/Bugtracker-Infinium-4.3.4#4148]
http://es.wowhead.com/quest=29197/desprevenidos

Monte Hyjal

Mision de la cadena para entrar a frente de magma

El problema que me ocurre es que en el momento de completar la mision e ir a entrgar la misma al Archidruida Hamuul Tótem de Runa, ete no esta al lado del portal como indica wowhead, y me marca que esta en el santuario de marlone  el simbolo de pregunta para entregar aunque ahi tampoco esta.
no pudiendo terminar esta mision no puedo obtener la ultima de la cadena para poder cruzar el portal.
Ya la he abandonado y vuelto a hacer como tambien he relogueado y borrado el cache sin resultados

**Comment by Monleon** [comment]
Ya debería dejarte

**Comment by argentito89** [comment]
Efectivamente, esta vez al borrar cache ya pude entregar
Gracias
