### ISSUE TITLE
Druida Tecnica de talento rama feral "Rabia"

### ISSUE THREAD

**Issue by javier1200** [RoDNet/Bugtracker-Infinium-4.3.4#4151]
La ultima técnica aprendida de la rama feral del Druida "Rabia" en esta versión tiene tanto un efecto pasivo como un efecto activo en la forma de oso 

Pasiva: El daño periódico de tu facultad "Lacerar" Tiene un 50% de probabilidad de reiniciar el tiempo de reutilizacion de "Destrozar(Oso)" y hacer que no cueste ira

Activa: Quita el tiempo de reutilizacion de tu facultad "Destrozar(Oso)" y afecta hasta un maximo de 3 objetivos

Bien el efecto pasivo no se esta dando sin importar cuanto tiempo el objetivo sea dañado por el sangrado de lacerar, lo cual es importante para el tankeo del druida en especial el ahorro de ira al poder volver destrozar gratuita

**Comment by skyrex321** [comment]
Ya pongo yo ID=50334

**Comment by efectokoleos** [comment]
arreglado en el proximo reinicio
