### ISSUE TITLE
[Warrior] Segundo Aliento

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#4152]
Spell Segundo Aliento --> Cada vez que recibes un golpe con efecto de aturdimiento o inmovilizador, generas 20p de ira y un 6% de tu salud total durante 10 seg.

SpellId=29838

Fallo --> Esta generando un buff que cura un 6% de tu salud total cada 2 seg durante 10 seg cuando debería curar solo un 6% a lo largo de esos 10 seg 

Ahora mismo mi warrior se esta curando 8580 cada 2 seg con 143k de vida cuando debiera curarse solo 858 cada 2 seg durante 10 seg.

**Comment by Wiinter** [comment]
Realmente es un 5%, lo que pasa es que debes tener el talento sanacion de batalla que te otorga un 20% extra de sanación y por eso te sale un 6%

**Comment by skyrex321** [comment]
Podría ser

**Comment by efectokoleos** [comment]
arreglado falta compilar
