### ISSUE TITLE
[Sacerdote] Glifo de Disipar Magia

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#4153]
Descripción : Tu hechizo disipar magia también sana a tu objetivo un 3% de su salud máxima cuando disipas con éxito un efecto mágico.

Fallo: Al usarlo sobre si mismo el sacerdote se cura un 3% de su salud máxima aun sin disipar ningún efecto 

ItemID=42397

**Comment by efectokoleos** [comment]
arreglado falkta compilar
