### ISSUE TITLE
mero agallabrillante da justicia

### ISSUE THREAD

**Issue by norco1208** [RoDNet/Bugtracker-Infinium-4.3.4#4165]
este mob da 33 puntos de justicia al matarlo http://es.wowhead.com/npc=40309/mero-agallabrillante
![wowscrnshot_101414_223859](https://cloud.githubusercontent.com/assets/5240320/4636374/5b406d76-53e2-11e4-968a-5763766d417b.jpg) 
![wowscrnshot_101414_221700](https://cloud.githubusercontent.com/assets/5240320/4636382/62e01734-53e2-11e4-9d6d-f8f33255896a.jpg)

**Comment by Kiritoo** [comment]
Gracias por el aviso.
