### ISSUE TITLE
[Sacerdote] Evangelización 

### ISSUE THREAD

**Issue by Ciibeles** [RoDNet/Bugtracker-Infinium-4.3.4#4167]
Evangelización se esta beneficiando del debuff que deja fuego sagrado por lo que con solo lanzar un fuego sagrado podríamos llegar a las 5 cargas de evangelización y aumentarnos un 15% la sanación si nos activásemos arcángel. El problema es que solo debería contar el daño directo.

http://es.wowhead.com/spell=81662

**Comment by skyrex321** [comment]
Por fin alguien que reporta los bugs beneficiosos +1

**Comment by efectokoleos** [comment]
arreglado
