### ISSUE TITLE
glifo presa cegada

### ISSUE THREAD

**Issue by Devyal** [RoDNet/Bugtracker-Infinium-4.3.4#4168]
glifo presa cegada (tus facultades disparo firme y disparo de cobra generan 2p. de enfoque extra en los objetivos afectados por un efecto de atontamiento.)
con disparo firme y disparo de cobra con o sin glifo genero 9 p. de enfoque, es decir el glifo no aumenta los 2 p. que deberia llegando a 11 p, claro esta aplicando el efecto de atontamiento.

**Comment by efectokoleos** [comment]
id?

**Comment by efectokoleos** [comment]
ya da igual xd arreglado a falta de compilar
