### ISSUE TITLE
talento sentencias del puro (paladin) no reduce el tiempo de reutilizacion de golpe de cruzado

### ISSUE THREAD

**Issue by Devyal** [RoDNet/Bugtracker-Infinium-4.3.4#4170]
el talento sentencias del puro ( tu sentencia aumenta un 9% tu celeridad de lanzamiento de hechizos y cuerpo a cuerpo durante 1 min y un 30% tu regeneracion de mana por espiritu mientras estas en combate) aporta el 9% de celeridad que debe, pero ese 9% no reduce el tiempo de utilizacion de golpe de cruzado debido al talento santidad de batalla ( los efectos de celeridad reducen el tiempo de reutilizacion de tus facultades golpe de cruzado y tormenta divina.).

**Comment by efectokoleos** [comment]
ids?

**Comment by 3du42d0** [comment]
id=53657

**Comment by Monleon** [comment]
Ojo, que santidad de batalla funciona, pero tiene un bug visual que no muestra correctamente el cd. De hecho con una gran cantidad de celeridad sigue mostrando 4.5seg de cd, pero al llegar a 3seg se refresca de golpe

**Comment by Devyal** [comment]
si santidad de batalla si, pero el 9 % de celeridad de sentencias del puro no y es muy importante para el paladin, deberia disminuir el cd de golpe de cruzado.

**Comment by efectokoleos** [comment]
arreglado
