### ISSUE TITLE
Reclamación

### ISSUE THREAD

**Issue by athasi** [RoDNet/Bugtracker-Infinium-4.3.4#4171]
hola, hay una mision en cuenca de scholazar que te la da el avatar freya que se llama reclamacion en la que te encomienda matar 200 esbirros de la plaga, a urgreth de las mil tumbas, a iragelida y a bithyus el formador de carne. el problema es este ultimo boss, invoca 2 perros cada vez que lo tocas, llegando un momento en que es imposible matarlo.
![wowscrnshot_101514_172156](https://cloud.githubusercontent.com/assets/9254942/4649076/7556e71c-5487-11e4-9011-0928984c9b4b.jpg)

**Comment by JoakRoD** [comment]
La próxima vez pon el id de la misión buscando en wowhead: http://es.wowhead.com/quest=12546

**Comment by Kiritoo** [comment]
Gracias por avisar, cuando se reinicie ya no debería ocurrir.
