### ISSUE TITLE
mi pj hace menos dps 

### ISSUE THREAD

**Issue by brianups** [RoDNet/Bugtracker-Infinium-4.3.4#4174]
estuve equipando mas a mi guerrero y su dps enpeso a bajar cuando tendría que ser mejo
ya intente muchas cosas hasta llegar a la conclusión que la causa es un bug en mi pj
mi personaje se llama astarotht es un horda agradecería mucho si lo pudieran resolver pronto el problema

**Comment by Kiritoo** [comment]
Es imposible, de todas maneras ve al instructor de guerreros y comprueba que tengas todo aprendido. También puedes poner un ticket para que te borren las auras y tras ello locuras de nuevo, si existe algún problema en tu personaje, que no creo, así Sr te debería de solucionar. Saludos.

**Comment by Kiritoo** [comment]
Maldito autocorrector del móvil, cierras y abres sesión. Jaja
