### ISSUE TITLE
Tierras altas crepusculares

### ISSUE THREAD

**Issue by j0c54n** [RoDNet/Bugtracker-Infinium-4.3.4#4176]
No se si este mal no ser tan especifico (es la primera vez que hago un reporte) pero solo quiero decir que la zona Tierras altas crepusculares esta casi totalemtente bug, la mayoria de las missiones no se pueden hacer.

**Comment by JoakRoD** [comment]
Hola, reporta cada misión que te encuentres por separado para saber cuáles son. Gracias
