### ISSUE TITLE
[Pícaro] Emboscada y Ruptura 

### ISSUE THREAD

**Issue by ReckLuLz** [RoDNet/Bugtracker-Infinium-4.3.4#418]
Emboscada esta quitando muy muy poco, ya que causa el 276% de daño del arma y con dagas un 399% plus 1467) estoy pegando emboscadas al muñeco de entrenamiento  de 5k y 9k critico, pego mas con puñalada que tiene un porcentaje menor.

Ruptura con todos los puntos de combo pega 1k por tick y encima si le metes hemorragia que es un 30% no llego ni a 1200  se me queda la cara de YaoMing xD

gracias por su atencion (K)

**Comment by searum** [comment]
fix
