### ISSUE TITLE
(Mision) Inmolar, Valle de los retos, Inicio de Warlock orco

### ISSUE THREAD

**Issue by LordGrimmerson** [RoDNet/Bugtracker-Infinium-4.3.4#4180]
Cuando inmolas a uno de los muñecos de entrenamiento no te lo cuenta.

Aquí el link de la mision, es la parte de Orcos.
http://wowpedia.org/Quest:Immolate#Orc_2

**Comment by sakuranobushi** [comment]
La mision ha sido reparada y pronto se podrá completar en el servidor publico.
