### ISSUE TITLE
barco de infralar

### ISSUE THREAD

**Issue by athasi** [RoDNet/Bugtracker-Infinium-4.3.4#4181]
hola les comento, el barco de infralar tiene un fallo ademas reciente pq hace unas semanas levee ahí y no pasaba, el caso es que estas realizando las misiones del barco cuando de repente y sin previo aviso se teletrasnporta fuera del mapa de infralar y te mata porque te caes al vació y luego tienes que revivir en el ángel porque por texturas no puedes llegar a tu cuerpo

**Comment by Dekadencee** [comment]
Se aplico un fix, pero fue retirado de nuevo, debido a que teletransportaba a los jugadores a su piedra de hogar al tomar portales.

Se está trabajando mas detalladamente en esta incidencia.

Un saludo
