### ISSUE TITLE
[mision] Uldum - Guardianes colosales

### ISSUE THREAD

**Issue by doomdays** [RoDNet/Bugtracker-Infinium-4.3.4#4182]
Que ocurre: Debería poder usar el jeroglífico y poder tomar la siguiente misión pero no me deja y no me deja seguir las msiones en uldun.

Lugar donde esta el jeroglífico y mapa:
![wowscrnshot_101614_174100](https://cloud.githubusercontent.com/assets/9273574/4670221/1a49a03c-5575-11e4-8ef8-45b930f36a6a.jpg)
Lugar donde esta el jeroglífico:
![wowscrnshot_101614_174120](https://cloud.githubusercontent.com/assets/9273574/4670244/45a42af4-5575-11e4-90bc-ec30be1e386f.jpg)

Pd: este es mi primer post así que perdonen si lo hice mal y diganmen si debo hacerlos mejor.

Salu2.

**Comment by doomdays** [comment]
Edito: Olvide decir que la mision se obtiene del pnj muerto que esta cerca  "Profeta Hadassi"
Link de la mision: http://es.wowhead.com/quest=27623
Link del "Profeta Hadassi":  http://es.wowhead.com/npc=46003

**Comment by nayan87** [comment]
bien posteado, no es el único punto donde se corta la cadena de misiones en uldum, más adelante el harrison jones delas pelotas se buguea y no de ja proseguir con la cadena :(

**Comment by doomdays** [comment]
gracias es bueno saberlo

**Comment by redneo** [comment]
A mi si que me deja entregarlo...

Has probado a borrar cache estando desconectado?

Un saludo.

(por cierto, el reporte excelente)

**Comment by doomdays** [comment]
SI, e borrado el cache y aun aun así no puedo continuar con la cadena de misiones,
Si es que no soy yo el unico que le pasa esto, podre pedir por ticked para que algún gm me reinicie la misión o no es posible.
Salu2.
