### ISSUE TITLE
Error hechizo invocar guardián (brujo)

### ISSUE THREAD

**Issue by Metalheroe** [RoDNet/Bugtracker-Infinium-4.3.4#4183]
hola  soy un huargen de nombre Wolfen brujo lvl 50 y me dieron el hechizo de invocar infernal el cual al ser invocado aturde a los enemigos 2s e inflige daño de fuego 192p el punto es que cuando lo invoco nada mas aturde pero no hace nada a los enemigos intente invocarlo sin tener un esbirro y nada

**Comment by JoakRoD** [comment]
¿Has mirado a ver si está en modo pasivo?

**Comment by Compresor** [comment]
El infernal ataca a todos los objetivos en forma de daño en area a aquellos objetivos que le esten haciendo daño. Hasta qe no toquen al infernal el no hará daño.
