### ISSUE TITLE
[mision de dk] Cuando llegue el caos, deja que el sufrimiento tome las riendas

### ISSUE THREAD

**Issue by doomdays** [RoDNet/Bugtracker-Infinium-4.3.4#4184]
Que ocurre: Al tomar la misión no deja hablar con los iniciados caballeros de la muerte para tener el duelo con ellos y matarlos.

Link de la misión: http://es.wowhead.com/quest=12678

Salu2.

**Comment by JoakRoD** [comment]
Debes hablar con los iniciados que están 2 juntos, con esos sí deja hablar y matar.

**Comment by doomdays** [comment]
ok gracias

**Comment by doomdays** [comment]
Hola de nuevo, revise los que estan 2 iniciados juntos y aun asi no puede hablar ni matarlos, quisas sea por que no me aparecen como objetivos.

**Comment by doomdays** [comment]
¡MIL PERDONES¡ acabo de darme cuenta que cometí un error feo, el nombre de la misión no corresponde a los objetivos. Juraría que era el correcto no fue mi intencion JoakRod y a los otros mienmbros del staff de RoD.

los objetivos de la mision corresponden a la mision: "Desafio de la muerte" y funciona bien
 Link: http://es.wowhead.com/quest=12733

Disculpen de nuevo.

**Comment by Monleon** [comment]
Cierro entonces?

**Comment by doomdays** [comment]
Si. disculpa por la demora y la confusion, juro que cuando tome la mision lei que tenia que matar dk iniciados. puedes cerrar el post.
