### ISSUE TITLE
[Item/Objeto] Medallones PVP

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4185]
Nombre: Medallones PVP
ID:42292
Enlace: http://wow.freakz.ro/spells.php?spell=42292
Descripcion: Disipa todos los efectos de merma de movimiento y todos los efectos que provocan pérdida de control de tu personaje. Tiene animacion nueva en cataclysm 
Problema: no esta saliendo la animacion al activar el medallon dejo unas imagenes de como son 
http://es.wowhead.com/spell=42292#screenshots:id=244024
http://es.wowhead.com/item=72412#screenshots:id=281793
No encontre las animaciones de medallones hordas pero hay teneis las de los aliz

**Comment by efectokoleos** [comment]
arreglado falta compilar
