### ISSUE TITLE
[Paladin] Palabra de Gloria/Proposito Divino

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4186]
Nombre:Palabra de Gloria/Proposito Divino
ID:85673
Enlace: http://wow.freakz.ro/spells.php?spell=85673
Descripcion: Un poder sagrado que sana la objetivo 
Problema: Palabra de gloria no esta consumiendo el buff de Proposito divino (86172/85117)

**Comment by efectokoleos** [comment]
arreglado falta compilar
