### ISSUE TITLE
[Items/Objetos] Conjunto Bonus 400 temple

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4187]
Nombre: Conjuto de set pvp bonus 400 temple
ID:Fue eliminado de wowhead a si que no consegui id 
Descripcion: El bonus de temple de 2 piezas de los conjuntos de JcJ de Cataclysm ya no se acumula. Si un jugador lleva 2 piezas, cada una de un conjunto de Cataclysm diferente, el jugador solo recibirá el bonus de 400 p. de temple una vez. Este cambio no se aplica a los conjuntos de JcJ de expansiones anteriores. (Notas de parche 4.2)
Problema: actualmente con mi sacer tengo 4800 temple con 3 partes cata y 2 impla el conjunto se esta acumulando y no deberia

**Comment by efectokoleos** [comment]
arreglado

**Comment by F4NT4SM4** [comment]
mmm sigue bug lo verifique con set de pala y sacer ._.
