### ISSUE TITLE
[Guerrero] Maestria en actitudes

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4188]
Nombre: Maestria en Actitudes
ID:12678
Enlace: http://wow.freakz.ro/spells.php?spell=12678
Descripcion: Retiene 25p de ira al cambiar de actitud
Problema: Esta generando 25p de ira y deberia de retener

**Comment by efectokoleos** [comment]
arreglado falta compilar
