### ISSUE TITLE
[Ingeniería] Recetas de especializaciones.

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#419]
Los instructores de ingeniería están enseñando las recetas de Ingeniería Gnómica e Ingeniería Goblin sin importar lo que seas, la lista de recetas exclusivas de cada una:

*Ingeniería Goblin: http://es.wowhead.com/spells=11.202.20222

*Ingeniería Gnómica: http://es.wowhead.com/spells=11.202.20219

**Comment by DatJetto** [comment]
Esto tampoco es tan importante te digo, necesitas la specialización propia para usar el objeto, así que se quedará como estaba aunque tenga las recetas. No supone niguna ventaja
