### ISSUE TITLE
[Brujo] Quemar Alma: Piedra de Salud

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4190]
Nombre:Quemar Alma: Piedra de salud
ID:79437
Enlace: http://wow.freakz.ro/spells.php?spell=79437
Descripcion: Aumenta un 20% la salud maxima durante 8s
Problema: Al tener activo Quemar alma (74434) deberia brillar el icono de piedra de salud (5512) indicando que tendra efecto como en las otras spells que tienen efecto especiales con quemar alma
no es nada prioritario o importante pero bug es bug

**Comment by efectokoleos** [comment]
no es bug en este video se ve como se le iluminan todas las spells que usa quemar alma, pero la piedra no se ilumina https://www.youtube.com/watch?v=fDsVI9PFj5A
