### ISSUE TITLE
[DK] Atracción Letal

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4191]
Nombre: Atraccion Letal
ID:49576
Enlace: http://wow.freakz.ro/spells.php?spell=49576
Descripción: En cataclysm se modifico atraccion letal la animacion y velocidad q atrae al objetivo 
dejo un video de como deberia ser http://youtu.be/W5qv0EEXow8?t=10s
Problema: sigue teniendo la misma animacion que la expancion anterior

He intentado hacer videos para atraer gente haciendo pvp pero este bug no dara buena impresion a si que me abstengo de hacer y con otra clase como war tambien se ven algunos bug visuales que hare otros issues apartes....

**Comment by efectokoleos** [comment]
arreglado falta compilar
