### ISSUE TITLE
[Errores Internos] Bajon de fps al usar macros

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#420]
Hola quiero comentar este error que me ocurre cuando uso macros con varios de mis pjs, esto le pasa a mas personas que a mi.
Algunos dicen que se soluciona cerrando el juego y borrando cache, pero en mi persigue el problema.
En arena con solo darle un click me baja de 60 fps constantes a 0.1 - 20fps
Como le de más de un click o varios click seguidos me baja a menos de 5 fps, imaginaros esto en un castsquence jeje.
Esto ocurre en los macros de más de dos lineas.
Agradeceria comentarios.
Un saludo.

**Comment by ghost** [comment]
A mi no me pasa xd, pero por otro lado me bajan los fps estando en grupo/banda... u.u

Edit: si puedes poner un macro aquí que te baje los fps para que pueda probarlo.

**Comment by Dekadencee** [comment]
Si, necesitamos mas datos, pero todo apunta a un error por parte del cliente crowel, yo tengo macros pesadas de mas de 20 lineas y no bajan los fps :/

**Comment by crowel** [comment]
Mmm alguna idea? Nosé exactamente que puedo hacer :(
Tengo dos clientes distintos del wow, el que baje limpio por torrent y otro que tenia de antes.
Es extraño, antes del rollback o de actualizar no me pasaba.

Un saludo.

**Comment by Dekadencee** [comment]
Pegame la macro crowel para probarla yo a ver que pasa

**Comment by crowel** [comment]
Mmm acabo de probarlo antes de copiarla y ahora solo se me bajan los fps en el momento de usar la macro.
Antes ocurría que si lo pulsaba repetidamente tenía un bajon continuado de fps, ahora lo hago y solo ocurre de la prímera vez que le doi click.
Esto solo me pasaba con macros de más de 2 líneas.
/use Rugido salvaje(Forma felina)
/use Furia del tigre(Forma felina
/use Distintivo de conquista del gladiador sañoso
/use Rabiar(Racial)
El macro en cuestión era este, con las 2 prímeras líneas no se notaba nada, así que escribía la tercera y cuarta y lo usaba ocurría el problema ahora parece que no.
Esto me pasaba con cualquier macro de mas de 2.

De momento creo que se puede cerrar, cualquier cosa aviso si eso.
Gracias^^
