### ISSUE TITLE
[Adivinación: la clava de Sanguino] Objetivos invisibles

### ISSUE THREAD

**Issue by obamakurosaki** [RoDNet/Bugtracker-Infinium-4.3.4#4201]
Hola, buenas tardes

El problema es básicamente que los personajes que hay que encontrar, que son una especie de caballeros de la muerte, no aparecen. Se necesitas los espectróculos, que te los dan en la mision y tras varias vueltas al recorrido que hacen los objetivos, he llegado a pensar que estan mal. Espero equivocarme. 

Un saludo, Lendrik

**Comment by redneo** [comment]
Los npcs si que estan, mal repartidos, pero estan. Busca por la zona norte.
