### ISSUE TITLE
elfos de sangre-paladin

### ISSUE THREAD

**Issue by sharagomez** [RoDNet/Bugtracker-Infinium-4.3.4#4203]
el elfo de racial tiene 85 puntos de resistencia arcana, al poner reyes la resistencia se queda en 97 en vez de acumularse solo se obtiene la resistencia de los reyes.
Lo mismo pasa con el aura de resistencia y reyes.

**Comment by Monleon** [comment]
Las resistencias por talentos, auras o raciales no se acumulan. En lugar de eso toman el valor más elevado
