### ISSUE TITLE
Salvaguardia en los paladines tanke

### ISSUE THREAD

**Issue by Pedricero** [RoDNet/Bugtracker-Infinium-4.3.4#4204]
Bueno pues resulta que este talento no funciona y por consiguiente nos meten golpes brutales en las mazmorras. En igualdad de equipo y de condiciones los wars son casi intocables y tal como decia antes a los paladines nos meten unas zurras impresionantes. A ver si esto se puede solucionar de alguna manera porque tengo un tanke que no puedo llevar mas allá de Cámaras de los Orígenes porque no aguanta dos tortas.

Gracias de antemano.

**Comment by Overseer101** [comment]
Salvaguardia funciona correctamente en tanto a la reduccion de daño y la
reduccion de probabilidad de critico, el unico efecto que no funciona es el
de dar un % de mana, al esquivar o bloquear, por eso te parece que no
funciona.

P.D. El warrior mitiga mucho mas daño que un paladin por la sencilla razon
de que este ultimo puede curarse, el warrior solo tiene la regeneracion
iracunda para ello, (y son 3 min de cd).

P.D.2 : Ya da mana al bloquear o esquivar un ataque.
