### ISSUE TITLE
Transformaciones (Druida)

### ISSUE THREAD

**Issue by kikete17** [RoDNet/Bugtracker-Infinium-4.3.4#4206]
Forma de viaje : https://wow.freakz.ro/spells.php?spell=783&name=travel-form
Forma de oso : https://wow.freakz.ro/spells.php?spell=5487&name=bear-form
Forma felina : https://wow.freakz.ro/spells.php?spell=768&name=cat-form

Problema: cuando te transformas no esta quitando los efectos de reducción o ralentización de movimiento.

**Comment by Wiinter** [comment]
Quiero hacer una aclaración y es que lo que quita la ralentizacion es el cambio de forma, no la forma en si. Me explico, lo qe cambia de forma es pasar de forma de oso a gato, por ejemplo.

**Comment by efectokoleos** [comment]
arreglado falta compilar
