### ISSUE TITLE
Orbes del sacerdote sombras

### ISSUE THREAD

**Issue by Ashkhan1** [RoDNet/Bugtracker-Infinium-4.3.4#4215]
Lo que pasa es que cuando uso pua o explosion mental los orbes morados no se consumen y pues algo que no vaya mucho conmigo es usar bug para poder tener ventaja en pvp
Aqui el spell bug : https://wow.freakz.ro/spells.php?spell=95740&name=shadow-orbs
Y aqui el spell en el que se deberia convertir despues de usar explosion o pua mental: https://wow.freakz.ro/spells.php?spell=77486&name=shadow-orb-power

**Comment by efectokoleos** [comment]
arreglado falta compilar
