### ISSUE TITLE
Crecimiento salvaje(Druida restauración)

### ISSUE THREAD

**Issue by kikete17** [RoDNet/Bugtracker-Infinium-4.3.4#4216]
https://wow.freakz.ro/spells.php?spell=48438&name=wild-growth

Problema: esta afectando a mas de 5 objetivos sin tener glifo o estar en forma de árbol de vida

Glifo: https://wow.freakz.ro/spells.php?spell=62970&name=glyph-of-wild-growth

Árbol de vida: https://wow.freakz.ro/spells.php?spell=33891&name=tree-of-life

PD: lo he probado en una raid de 10 personas y sana a las 10

**Comment by Albertiktik** [comment]
Cierto se lo pone a todos, aqui dejo una foto de una raid de 10
http://imagizer.imageshack.us/a/img673/1882/DFB9Pp.jpg

**Comment by Monleon** [comment]
Cuando se compile ya deberá sanar al número correcto.
