### ISSUE TITLE
Bug en la entrada de la mazmorra Maraudon

### ISSUE THREAD

**Issue by jogoford** [RoDNet/Bugtracker-Infinium-4.3.4#4217]
La mazmorra Maraudon que se encuentra en Desolace, en la entrada al abrirlo, no abre y no es posible entrar a dentro para poder ingresar a la mazmorra.

Por favor arreglarlo, quiero obtener el logro de la mazmorra.

**Comment by JoakRoD** [comment]
A qué puerta te refieres? La de "la calle" se abre correctamente.

**Comment by jogoford** [comment]
![wowscrnshot_102614_234803](https://cloud.githubusercontent.com/assets/9386676/4786424/84378816-5d94-11e4-8d03-dffb9e0b9ca5.jpg)

Es esa, pero ya se abre, cuando intente entrar no se me abria, pero bueno gracias..
