### ISSUE TITLE
[Guerrero]Grito de Batalla/Orden

### ISSUE THREAD

**Issue by Sagittariu5** [RoDNet/Bugtracker-Infinium-4.3.4#4218]
ID:
- Grito de batalla: http://es.wowhead.com/spell=6673/grito-de-batalla
- Grito de orden: http://es.wowhead.com/spell=469/grito-de-orden

Problema: Un war puede poner los dos gritos. siendo que este se reemplaza si lo pone el mismo war, el problema puede ser por la duracion, que se anade gracias al glifo. Esta siendo muy abusado en PvP tanto en BG's como en arenas.

Referencia:
Order Shout: This doesn't stack with Battle Shout from a single warrior, but you can have both Battle and Commanding Shout active if you have more than one warrior in a group

**Comment by efectokoleos** [comment]
arreglado
