### ISSUE TITLE
[BUG] Monasterio escarlata

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#4219]
No se puede completar el evento de Comandante Escarlata Mograine, al igual que tampoco se puede matar a la Alta Inquisidora Melenablanca.

PNJs:

Comandante Escarlata Mograine: http://es.wowhead.com/npc=3976
Alta Inquisidora Melenablanca: http://es.wowhead.com/npc=3977

![wowscrnshot_102514_124342](https://cloud.githubusercontent.com/assets/6329431/4779684/3d39852c-5c40-11e4-8c62-09a38cb889e9.jpg)

![wowscrnshot_102514_124339](https://cloud.githubusercontent.com/assets/6329431/4779685/42e8b240-5c40-11e4-85c6-64ea3c3139d1.jpg)

Mograine muere pero no cuenta como muerto, Melenablanca no muere, y por ende no se puede sacar el logro.

**Comment by JoakRoD** [comment]
Funciona perfectamente, me da que te has pasado de dps o lo has bugueado de alguna forma.
Prueba de nuevo y si pasa lo mismo.. avisa.

**Comment by qulki** [comment]
Vale, funciona bien

**Comment by Monleon** [comment]
No los mateis de golpe, son instances de nivel 35, estan hechas para que a medida que se baje la vida la boss se active un evento. Si los matais de golpe no hay evento
