### ISSUE TITLE
[Errores Internos] Elevadores Orgrimmar

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#422]
Hola queria comentar que dos de los tres elevadores de orgrimmar no estan.
![elevadores orgri](https://f.cloud.github.com/assets/3537253/792982/e9e69a40-ebd4-11e2-8996-638d6ef78458.jpg)

Un saludo.

**Comment by redneo** [comment]
Esto... yo los veo funcionando ya.
