### ISSUE TITLE
[Profesiones] Muelles de sinapsis

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#4222]
http://es.wowhead.com/spell=82175

Cuenta como objeto y no como encantamiento. Por lo tanto no puedes lanzarlo junto a un abalorio de uso y te hace que lo tengas que usar despues de 20s para respetar el cd de los objetos de uso.

**Comment by qulki** [comment]
Lo que pasa con ese muelle es que es de activación, y tiene cd interno con el trinket de uso

**Comment by Monleon** [comment]
Funciona correctamente. Al activar los muelles de sinapsis, te aparecen 10seg de CD a tus trinkets. Y cuando utilizas los trinkets te aparece un CD a los guantes, con valor a los segundos que dure el trinket de activación.

Lo incorrecto sería que no tuvieran CD entre ellos.
