### ISSUE TITLE
[BUG MISIÓN] Señor de los yetis Yetimus

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#4223]
Este NPC no dropea el objeto necesario para completar la misión.

Misión: http://es.wowhead.com/quest=28485
NPC: http://es.wowhead.com/npc=47484
Objeto necesario: http://es.wowhead.com/item=64386

**Comment by redneo** [comment]
Ya lo tendria que lotear.
