### ISSUE TITLE
[BUG CAZADOR] Talento "Atrapar"

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#4224]
Talento: http://es.wowhead.com/spell=19387/atrapar

Problema: http://es.wowhead.com/spell=13809 no se beneficia del talento; al usarla, no enraíza a los enemigos

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, ya no daremos soporte al actual
