### ISSUE TITLE
[Mision] Desprevenidos

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4225]
ID: 29197
El problema es que no me deja entregar la mision al npc

**Comment by argentito89** [comment]
Hace 17 dias abri el mismo problema, al menos veo que no es de mi pj el problema

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/4148

**Comment by redneo** [comment]
Ya tendria que dejar entregarla.
