### ISSUE TITLE
[DK] Atracción letal

### ISSUE THREAD

**Issue by UkfNonXtop** [RoDNet/Bugtracker-Infinium-4.3.4#4227]
(Atración letal) https://wow.freakz.ro/spells.php?spell=49576

Range: 30 yd range

La habilidad debería poder ser usada a rango de mele. En la descripción de la misma solo expone la máxima distancia (Dado que no hay una mínima) sobre la que puede ser utilizada.
Puede ser utilizada para el cc de habilidades a rango mele lo cuál actualmente no está disponible a corta distancia.

(Cargar como ejemplo) https://wow.freakz.ro/spells.php?spell=100

Range: 8-8 yd range

Ejemplo de habilidad que requiere un mínimo de distancia entre el objetivo y el jugador.

**Comment by sakuranobushi** [comment]
El error ha sido reparado y pronto deberia estar corregido en el servidor.
