### ISSUE TITLE
[Dk] Peste del ébano

### ISSUE THREAD

**Issue by UkfNonXtop** [RoDNet/Bugtracker-Infinium-4.3.4#4228]
(Peste del ébano) https://wow.freakz.ro/spells.php?spell=51160

(Golpe purulento) https://wow.freakz.ro/spells.php?spell=85948

Al igual que "Peste de sangre" y "Fiebre de Escarcha", golpe purulento aumenta 6 seg el debuff de "Peste del ébano".
Actualmente no lo está haciendo, perdiendo el debuff fácilmente.

**Comment by sakuranobushi** [comment]
El error ha sido reparado y pronto deberia estar corregido en el servidor.
