### ISSUE TITLE
[Brujo] Lluvia de fuego con talento de secuelas

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4230]
Id secuelas:85114
id lluvia de fuego: 5740

El problema es que el talento que produce el atontamiento se está activando el 100% de las veces con lluvia de fuego cuando solo debería tener un 12% de probabilidad y además no atonta a los enemigos sino al brujo que lo lanza, lo cual lógicamente está mal.

Un saludo y gracias

**Comment by efectokoleos** [comment]
arreglado falta comiplar
