### ISSUE TITLE
[Mazmorras/Bandas][Tierras de Fuego] Alysrazor (Plumas de arrabio)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4234]
Buenas.
• Nombre: Plumas de arrabio
• Enlace: http://es.wowhead.com/spell=97128
• Descripción: Sujeta una pluma de arrabio. Aumenta un 30% la velocidad de movimiento y te permite usar hechizos y facultades en movimiento. Dura 15 min.
• Problema: La pluma desaparece al contacto
Desde ya muchas gracias y hasta luego.

**Comment by efectokoleos** [comment]
deberia ir en la proxima caida/reinicio
