### ISSUE TITLE
[DK] Atraccion letal distancia minima 

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4236]
Nombre: Atraccion Letal
ID: http://es.wowhead.com/spell=49576
Descripcion: Reune Energia Profana que rodea y vincula toda materia, lo que acerca al objetivo hacia el caballero de la muerte y obliga al enemigo a atacar al caballero de la muerte durante 3s

Notas del parche 4.0.6:Atracción letal requiere un radio mínimo de 8 metros contra otros jugadores, pero esto no figuraba en la descripción. La descripción se ha actualizado.

Problema: Para usar atraccion letal contra jugadores requiere un radio minimo de 8 metros esto no figura en la descripcion por error de blizzard pero en 4.0.6 lo corrijieron ellos 

Segun veo el changelod quitaron la distancia minima es decir ahora se puede aprovechar el bug para cortar cast cosa que jode mucho un dk ya puede tener 4 cortar cast a si 
helada mental, estrangular, torrente arcano(elfo) y atraccion letal si se deja como esta

**Comment by efectokoleos** [comment]
arreglado a falta de compilar, contra npcs no hay rango minimo, contra players 8 yardas

**Comment by Overseer101** [comment]
Tambien Sentencias del Sabio del pala proteccion no especifica en ningun
lado que reduce el cd de Golpe de cruzado y martillo del honrado en 1,5s y
sin embargo lo realiza, se llama cambios ocultos, o propiedades ocultas que
no aparecen en las descripciones.
