### ISSUE TITLE
[Cazador] Intervenir

### ISSUE THREAD

**Issue by 3du42d0** [RoDNet/Bugtracker-Infinium-4.3.4#4237]
El talento INTERVENIR de la pet (spell=53476):Tu mascota corre a gran velocidad a un miembro del grupo, lo que absorbe 50% DE LA SALUD TOTAL DE LA MASCOTA DEL DAÑO RECIBIDO DEL PRÓXIMO ATAQUE. Lo que está haciendo este talento es sólo absorber 50p del próximo ataque y no el 50% como máximo de la salud de la mascota.

**Comment by efectokoleos** [comment]
intervenir arreglado

**Comment by Compresor** [comment]
Te reparto los reportes asi es mas facil arreglarlos
