### ISSUE TITLE
[NPC] Fumblub Vientoencajado

### ISSUE THREAD

**Issue by doomdays** [RoDNet/Bugtracker-Infinium-4.3.4#4238]
El rare Fumblub Vientoencajado que cuenta para los logros "Expuesto a Rasganorte" y "Congelado" no aparece apesar de que lo enconte con el addon NPCScan.
Revise toda la zona bien viendo los moobs que estan ahi y no aparece por lo que debe estar atravesando el piso,
Link del NPC: http://es.wowhead.com/npc=32358#

Foto:
![wowscrnshot_103114_121531](https://cloud.githubusercontent.com/assets/9273574/4862968/e4a8163c-6110-11e4-9a50-149e87258c20.jpg)

Pd: Ayer hace unas 6 horas con mi dk leveando también pase por la zona y estaba exactamente en la misma zona.

**Comment by redneo** [comment]
![wowscrnshot_110114_100439](https://cloud.githubusercontent.com/assets/1163425/4871242/5d03dba8-61a6-11e4-82ad-0a7a18f85143.jpg)

Esta bien, lo que pasa que miras un poco bajo.

Un saludo!
