### ISSUE TITLE
Misiones Bug Bosque de Terokar

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#424]
El código final: consigues el código de un mob, desactivas la bomba y no se completa la misión.
http://es.wowhead.com/quest=10446

Alteraciones mágicas: Los acechadores de distorsión no aparecen.
http://es.wowhead.com/quest=10026

Excavando huesos: Los exploradores no se mueven.
http://es.wowhead.com/quest=10922

Velo skith: rocanegra de terokk: Al utilizar la vara en la piedra no completa la misión.
http://es.wowhead.com/quest=10839

**Comment by SherBlader** [comment]
pon los links de las misiones de wow head

**Comment by foxmclaud** [comment]
Añadidos los links de wowhead (lo tengo en cuenta para los próximos reportes)

**Comment by searum** [comment]
fix
