### ISSUE TITLE
Talento (cazador punteria) - Disparo firme mejorado

### ISSUE THREAD

**Issue by Albertiktik** [RoDNet/Bugtracker-Infinium-4.3.4#4242]
Nombre: Disparo firme mejorado

Enlace: https://wow.freakz.ro/spells.php?spell=53224

Descripción: Cuando lanzas Disparo firme dos veces seguidas, tu velocidad de ataque a distancia aumentara un 15% durante 8s.

Problema: Al  lanzar Disparo firme dos veces seguidas no pasa nada.

**Comment by Sagittariu5** [comment]
El efecto demora varios disparos, peor es que no salte. xd

**Comment by 3du42d0** [comment]
No anda este Talento, probé tirarlo al palo 100 veces y no saltó nunca xd

**Comment by Sagittariu5** [comment]
El dia que lo reportaron lo probe, 4 disparos tomo el que saltara, ahora no funciona nada xd

**Comment by Monleon** [comment]
Arreglado, falta compilar
