### ISSUE TITLE
[Banda] Bastión de Baradin /  El Señor del Foso Argaloth

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#4243]
Hola una vez mas al Jornal de Mazmorras en la que reportaremos al boss de Bastión de Baradin
[Señor del Foso Argaloth](http://es.wowhead.com/npc=47120)
La mecánica del boss es correcta el problema principal esta en 

[Tajo meteórico](http://es.wowhead.com/spell=88942)
Esta habilidad según descripción de wowhead esta nerfeada en el parche del oficial pero en 4.3.4 la descripción correcta es :  Argaloth Desgarra a su objetivo actual, lo que inflige 200000 p. de daño de fuego y aumenta un 100% el daño de fuego recibido durante 20 seg a todos los jugadores en un cono frontal de 120º. El daño se reparte entre todos los objetivos desgarrados. 

El problema es que creo que le tenéis puesto el [Tajo meteórico](http://es.wowhead.com/spell=45150) de 
[Brutallus](http://es.wowhead.com/npc=24882) que usa la misma habilidad pero es de una raid de lvl 70 con lo que el daño es muy inferior al que debería ser .

Gracias por revisarlo

**Comment by Sagittariu5** [comment]
Strong Mx decia que estaba bug, yo les decia que estaba medio pinata porque en season t9 nos costaba un huevo de avestruz tirarlo.

**Comment by efectokoleos** [comment]
si te refieres a 25 personas tienes razon no estaba correctamente la spell, en 10 si, en el proximo reinicio quedará añadida la spell de 25 al boss (400000 de daño repartido)
