### ISSUE TITLE
DR de Habilidades

### ISSUE THREAD

**Issue by UkfNonXtop** [RoDNet/Bugtracker-Infinium-4.3.4#4244]
Aquí van todos los DR que he podido encontrar, para que de una vez se comparta.

Nota: Congelación profunda (Mage) y el Anillo de Escarcha (Mage) son las únicas habilidades que comparten DR entre ellas también, así como estas el resto de los hechizos se pueden clasificar en los siguientes grupos.

Desarmar: Disparo de quimera (pet), Desarmar (Warrior), Desarmar (Rogue), Horror psíquico - efecto desarmante (Priest), Arrebatamiento (Pet)

Desorientación: Aliento de dragón (Mago), Trampa congelante (Cazador), Gubia (Rogue), Maleficio (Chamán), Hibernar (Druida), Frío hambriento (DK), Polimorfia (Mago), Arrepentimiento (Paladín), Anillo de Escarcha (Mago), Porrazo (Rogue), Encadenar no muerto (Sacerdote), Picadura de dracoleón (Cazador)

Miedo: Ceguera (Rogue), Miedo (Brujo), Aullido de terror (Brujo), Grito intimidador (Guerrero), Alarido psíquico (Sacerdote), Asustar bestia (Cazador), Seducción (Súcubo Brujo), Ahuyentar el mal (Paladín)

Horror: Espiral de la muerte (Brujo), Horror psíquico (Sacerdote)

Raíces (Control): Raíces enredadoras (Druida), Congelar (Pet Mago), Pin (pet), Nova de escarcha (Mago), Storm Earth and Fire (Shaman)

Raíces (Aleatorias): Cono de frío mejorado (Mago), Seccionar mejorado (Guerrero), Shattered Barrier (Mago)

Silencios: Torrente arcano (BE Racial), Lanzamiento heroico (Guerrero), Garrote (Rogue), Contra-hechizo mejorado (Mago), Patada mejorada (Rogue), Escudo de templario (Paladín), Silencio (Sacerdote), Disparo silenciador (Cazador), Bloqueo de hechizo (Brujo), Estrangular (DK)

(Ojo... Silencios, no cortes de casteo)

Stuns (Control): Azote (Druida), Azote (Pet Chamán mejora), Golpe bajo (Rogue), Arremetida de conmoción (Guerrero), Congelación profunda (Mago), Carga demoníaca (Brujo), Roer (Pet DK), Martillo de justicia (Paladín), Cólera Sagrada (Paladín), Interceptar (Guardia vil Brujo), Interceptar (Guerrero), Intimidación (Cazador), Golpe en los riñones (Rogue), Amputar (Druida), Abalanzarse (Druida), Ravage (Pet), Furia de las sombras (Brujo), Ola de choque (Guerrero), Explosión sónica (Pet), Pisotón de guerra (Racial Tauren)

Stuns (Aleatorios): Impacto (Mago), Sello de justicia (Paladín), Tótem garra de piedra (Chamán)

Sin DR (Por sí mismos): Desterrar (Brujo), Cargar (Guerrero), Ciclón (Druida) , Atrapar (Cazador), Choque de Escarcha (Chaman), Seccionar (Guerrero), Control Mental (Sacerdote), Disparo de dispersión (Cazador), Ralentizar (Mago)

Fuentes (https://foros.wow-colombia.com/archive/index.php/t-33699.html) y (http://us.battle.net/wow/en/forum/topic/3595374512)

**Comment by Kiritoo** [comment]
Conocemos los dr
La pregunta es, ¿cual es el que falla que quieres que arreglemos?

**Comment by UkfNonXtop** [comment]
Era un apunte para que la gente este informada, que sepan que habilidades comparten DR y puedan reportarlo con conocimiento. Quizás no es lugar indicado y si es necesario puedo moverlo al foro a modo de post informativo.

Siento las molestias.

**Comment by Kiritoo** [comment]
Se agradece igualmente, yo por ejemplo los conocia a traves de esta página, 
http://www.wowwiki.com/Diminishing_returns

**Comment by Monleon** [comment]
Y ojo porque el post no esta bien
Aliento de dragon, condena y scatter shot van en una sección aparte "scatter"
