### ISSUE TITLE
[Mago] % Impacto y Velocidad Llameante

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#4245]
Buenas quería reportar la pro. de que salten

Impacto= Spellid=12357
Problema --> esta saltando 3 o 4 veces seguidas e incluso salta aun sin recibir daño solo por robar buffs o ser dispeleado.
Velocidad Llameante=Spellid=31642
Problema-->Al mínimo roce salta aun teniendo solo un 10% de prob

**Comment by Kiritoo** [comment]
Arreglado, ya estan aplicados en el servidor.
