### ISSUE TITLE
Druida restoration

### ISSUE THREAD

**Issue by tonicm91** [RoDNet/Bugtracker-Infinium-4.3.4#4246]
Hola ay un bug en los druidas resto , cuando estoy en arbol supuestamente deberia poder lanzar unos hechizos instantaneos pero no es asi no puedo hacerlo si me estoy moviendo tengo ke dejar el personaje parado lanzarlo y despues seguir andando cosa que no puedo hacer cuando estoy en arenas o bg por favor arreglenlo cuanto antes

**Comment by Overseer101** [comment]
Donde estan las IDS y las descripciones detalladas de las spells afectadas?, no somos adivinos...
