### ISSUE TITLE
[Misiones][Isla de Quel'Danas/Meseta de la Fuente del Sol] La purificación de Quel'Delar

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4248]
Buenas.
• Nombre: La purificación de Quel'Delar
• Enlace: http://es.wowhead.com/quest=24595 (Alianza) y http://es.wowhead.com/quest=24598 (Horda)
• Descripción: Sumerge la Quel'Delar corrupta en La Fuente del Sol. Habla con un celador de La Fuente del Sol cuando estés <listo/lista> para entrar en la Meseta de La Fuente del Sol. 
• Problema: El PNJ Celador de la Fuente del Sol (http://es.wowhead.com/npc=37523) debería transportarte a una fase de Meseta de la Fuente del Sol donde hay PNJ amistosos y el evento correspondiente a la misión, pero no lo hace.
Desde ya muchas gracias.

**Comment by dylanvindas** [comment]
Este bug fue reportado hace ya mucho y aun persiste, espero que lo arreglen pronto.

Gracias.
