### ISSUE TITLE
Habilidades del warrior elfo de sangre que no hacen el efecto y el daño deseados

### ISSUE THREAD

**Issue by makidavid** [RoDNet/Bugtracker-Infinium-4.3.4#425]
Cargar: No hace el efecto de aturdir
http://es.wowhead.com/spell=100/cargar

Rajar: Cuando le da al segundo objetivo solo da 1 punto de golpe
http://es.wowhead.com/spell=845

Espero no ser muy pesado, pero es prácticamente el personaje que utilizo y me encanta :D

**Comment by searum** [comment]
fix
