### ISSUE TITLE
[Druida] Estampida

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#4250]
https://wow.freakz.ro/spells.php?spell=78893 (Rank 2)
https://wow.freakz.ro/spells.php?spell=78892 (Rank 1)

Al tirar carga feral (gato) te permite tirar un destrozar sin que estes en sigilo ni por detras del objetivo. 

El problema es que si tiras un detrozar antes del devastar gratuito, no te deja ponerlo aunque aun mantengas el buffo de estampida.

**Comment by efectokoleos** [comment]
arreglado falta compilar
