### ISSUE TITLE
Cazador (hunter)

### ISSUE THREAD

**Issue by Dimnness** [RoDNet/Bugtracker-Infinium-4.3.4#4251]
El talento de la sección Puntería del cazador tiene un bug, en la descripción dice que al ganar "Matanza rápida" ganas 50 puntos de enfoque, cosa que no pasa nunca... El talento Bug se llama "Recuperación Rápida"... Ojala lo puedan arreglar pronto, gracias!

**Comment by Compresor** [comment]
Necesitamos las ids de las habilidades. Hay una sección del foro que explica como hacer correctamente un reporte.
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
