### ISSUE TITLE
Rutas de vuelo bug

### ISSUE THREAD

**Issue by Potrele** [RoDNet/Bugtracker-Infinium-4.3.4#4258]
Tengo todo el mapa de Reinos del Este descubierto pero no me aparecen todas las rutas de vuelo, por ejemplo si cojo la ruta desde Ventormenta, solo puedo ir a hasta Las Estepas Ardientes y si, tengo todas (o casi todas) las rutas de vuelo descubiertas y he hablado con los maestros de vuelo.

**Comment by Compresor** [comment]
Eso es que te faltan rutas de vuelo intermedias.
