### ISSUE TITLE
[BG Playa de los Ancestro] Demoledor

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#426]
Demoledor del campo de batalla: http://es.wowhead.com/npc=28781/demoledor-del-campo-de-batalla

La vida del demoledor deberia de ser 542 mil y cuando un jugador la conduce la vida del jugador se agrega al demoledor pienso yo, es lo que vi en un video del ofi
http://www.youtube.com/watch?v=zGijHVAvgLw

Bueno el caso es que cuando un jugador entra a los demoledores en el server estos llegan a tener 1.5 millones de vida (1.500.000) 

Otro bug el demoledor es una maquina rapida asi que no se le puede atacar almenos que lo relentizemos el caso es que intento relentizarlo con cualquier hechizo pero me sale inmune y deberia de poder relentizarse

**Comment by Kiritoo** [comment]
La vida de los demoledores está correcta, cierro issue.
Cuanto se reabra la bg ya reportareis si encontrais algo.
