### ISSUE TITLE
[DoTs/HoFs] Celeridad

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#4264]
Actualmente como está puesta la celeridad, a mayor celeridad en vez de conseguir el tik extra, te lo quita reduciendo el dot lo que tarda entre tik y tik. Por asi decirlo en vez de acortar el tiempo entre tik y tik y mantener el tiempo total del DoT, lo que hace es reducir el tiempo entre tiks pero si augmentar el número de dots y por tanto reduciendo el tiempo total del DoT. Cuanta más celeridad, más se agrava el asunto, porque se puede llegar al cap del segundo tik de celeridad y te puede pasar, que no puedas castear más cosas de las que podrías porque tienes que renovar el DoT porque se te acaba cuando no debería. 
Un ejemplo es cuando pones affliccion inestable, qe dura 18s, los magos por la armadura de maga la reducen a la mitad, 9s, pero si tienes una celeridad alta, la cosa baja hasta los 7s de DoT. No te da tiempo a poner nada qe tienes qe volverlo a castear.

**Comment by Monleon** [comment]
Para el próximo reinicio se verá implementada la mejora
