### ISSUE TITLE
[Hechizo] Paladín - Limpiar

### ISSUE THREAD

**Issue by Akademika** [RoDNet/Bugtracker-Infinium-4.3.4#4271]
Aunque implementasteis el cambio el 31 de Octubre me da la sensación que el hechizo "Limpiar" del paladín (http://es.wowhead.com/spell=4987/limpiar) sigue quitando efectos mágicos dañinos, en vez de quitar exclusivamente venenos o enfermedades. Cuando lucho contra paladines veo que me quitan los DoT mágicos una y otra vez sin problema, teniendo que castearlos de nuevo, cuando no debería.

**Comment by Albertiktik** [comment]
¿Pero contra que tipo de paladines luchas? Por que el paladin sagrado puede disipar magias

**Comment by kikete17** [comment]
Se refiere a retry ,hoy he comprobado el limpiar ya que lo he visto comentar en el chat global y es cierto sigue limpiándose magias

**Comment by efectokoleos** [comment]
ahora si keda arreglado

**Comment by Akademika** [comment]
Acabo de ver ahora los comentarios, sorry, efectivamente me refería a los palas retry; en fin, iré observando el juego, a ver si está corregido. Muchas gracias por vuestro trabajo!!  ;-)
