### ISSUE TITLE
[Talento de Mago] Combustion

### ISSUE THREAD

**Issue by Bichoculiao** [RoDNet/Bugtracker-Infinium-4.3.4#4272]
https://wow.freakz.ro/spells.php?spell=11129&name=combustion

Combines your damaging periodic Fire effects on an enemy target but does not consume them, instantly dealing 955 to 1131 (+42.9% SP) Fire damage and creating a new periodic effect that lasts 10 seconds and deals damage per time equal to the sum of the combined effects.

Ok, hoy estaba revisando cuanto daño deberia hacer con la maestria maximizada en mi mago y descubri que el daño de combustion esta bajisimo (DOT) porque el daño inicial esta aplicada correctamente la formula, en recount aparece daño de ticks:
Piroexplosion (sin criticos): 18104
Bomba viva (sin criticos): 29052
Combustion: 21832
en estas habilidades no hubo criticos por lo que es mas facil calcular, y es muy notorio que, combustion no suma los daños correctamente, ya que en lugar de pegar 47156 que seria el daño de los DOTs sumados pega mucho menos de la mitad, el daño de los dots es lo que pega con aumento de daño con maestria (+50% de daño fuego periodico) el cual es aplicado correctamente en bomba viva y piroexplosion, pero tampoco se aplica a Combustion, ya que si asi fuera quedaria en 70734 como daño total dividido en 10 segundos a un non-player unit
osea que en PVP el daño se reduce a la mitad, imaginense cuanto pegariamos entonces si esa es la habilidad mas fuerte que tenemos nosotros los magos, muchas gracias.

**Comment by Monleon** [comment]
Arreglado falta compilar, pero ojo, no funciona tal como tu dices tampoco.

http://www.wowhead.com/spell=11129/combustion#comments

So let's say the following dots are on your target when you cast Combustion...

Ignite ticking for 3000 every 2 seconds (1500 dps)
Pyroblast ticking for 900 every 3 seconds (300 dps)
Living Bomb ticking for 1500 every 3 seconds (500 dps)

Combustion will tick for 2300 every second for 10 seconds, for a total of 23000 damage.
