### ISSUE TITLE
[Mision] (Gilneas) - Dar esquinazo

### ISSUE THREAD

**Issue by Giveh** [RoDNet/Bugtracker-Infinium-4.3.4#4275]
Dar esquinazo:
http://es.wowhead.com/quest=24616/dar-esquinazo

La exploradora oscura, quien debe stunearte para poder utilizar el "Dije de Belrysa", no se encuentra en la zona indicada (el camino al norte de la toma de la quest), esencial para poder seguir la cadena de misiones de los Huargen.

![wowscrnshot_110914_174047](https://cloud.githubusercontent.com/assets/9645322/4969123/398459c8-6859-11e4-84ba-c91ac2edb0ad.jpg)
![wowscrnshot_110914_174053](https://cloud.githubusercontent.com/assets/9645322/4969124/39851c3c-6859-11e4-861b-171032381eef.jpg)

**Comment by Katana69** [comment]
me pasa lo mismo

**Comment by redneo** [comment]
Puesta autocompletable, se puede seguir con la cadena de gilneas.
