### ISSUE TITLE
[DK] Maestría: Corazón congelado

### ISSUE THREAD

**Issue by ejaeje** [RoDNet/Bugtracker-Infinium-4.3.4#4279]
ID: 77514
Descripción: https://wow.freakz.ro/spells.php?spell=77514&name=frozen-heart
Problema: Las habilidades que se benefician de la maestría como Explosión aullante, Toque helado, Golpe de escarcha etc, no estan aumentando su daño segun el nivel de maestría que tengas, pegan lo mismo teniendo 20 ptos que 10.

**Comment by Monleon** [comment]
Acabo de probar Golpe de Escarcha sin equipo me hace 6k, con el anillo de 4k de maestria me hace casi 11k, explosión aullante también me ha subido, y toque helado ídem
