### ISSUE TITLE
Santidad de batalla Paladín (Retry)

### ISSUE THREAD

**Issue by kikete17** [RoDNet/Bugtracker-Infinium-4.3.4#4281]
https://wow.freakz.ro/spells.php?spell=25956&name=sanctity-of-battle
id:25956
Problema:no esta reduciendo el tiempo de reutilización de Golpe cruzado(35395) o Tormenta divina(53385) tenga la celeridad que tenga. Adjunto unas imagenes

con 4% de celeridad: http://kn3.net/30A4349264FJPG.html 
con 12% de celeridad : http://kn3.net/335BCA7C871JPG.html
con 22% de celeridad : http://kn3.net/324EECECB62JPG.html
PD: he llegado a tener 32% de celeridad y sigue igual 4 segundos de reutilización

**Comment by efectokoleos** [comment]
arreglado
