### ISSUE TITLE
Personaje totalmente reseteado

### ISSUE THREAD

**Issue by Allelujahh** [RoDNet/Bugtracker-Infinium-4.3.4#4284]
Buenas, migré hace como 2 años aproximandamente, de WorldHeroes para ser más especificos, antes que cerrara el server Searum permitió que se uniera nuestra base de datos a la suya, las 2 primeras semanas no tuve problema alguno, pero después me encontré con otro pj que tenía el mismo nick que mi pj (Prestige), jugador que ya había estado en este server antes que nosotros llegaramos, al relogear para encontrar una solución a mi problema, encontré mi pj totalmente reseteado (sin profesiones, monturas, mascotas, puntos de honor, puntos de arena, puntos de conquista, con algunas reputaciones reseteadas, profesiones secundarias eliminadas, algunos logros eliminados, todos los spells de clase eliminados, habilidades para las monturas eliminada, tiene talentos activos, 45 puntos de talentos sin activar, incapacidad de cambiar entre talentos), he intentado de todo, desde intentar aprender de nuevo las profesiones, habilidades o spells hasta gastar créditos para cambiar mi nick, pero este servicio le llegó al otro Prestige.
Agradecería infinitamente si pudiesen darme una solución o decirme a que hora debo estar conectado para tratar con un GM si tuviese que estar presente o logeado en la reparación de mi personaje.
Como no encontré un apartado del foro especial para publicar este tema procedo a hacerlo en esta sección y en el bugtracker.
Saludos.

**Comment by Overseer101** [comment]
Esto te sucede desde que se migró?, o es mas reciente, te lo comento por que despues de tanto tiempo es bastante probable que la DB ya haya sido borrada. Explicanoslo un poco a ver si podemos hacer un apaño

**Comment by Allelujahh** [comment]
Me sucede desde que que apareció el otro pj con el mismo nick que el mío, para ser más exactos 2 semanas después de mi migración aproximadamente.

**Comment by Allelujahh** [comment]
Storm, por si te olvidaste, el ID de ingreso de mi cuenta es walter_729.

**Comment by Overseer101** [comment]
Te lo hemos mandado de vuelta ya
