### ISSUE TITLE
[uldum] Misiones

### ISSUE THREAD

**Issue by Presoloko** [RoDNet/Bugtracker-Infinium-4.3.4#4285]
Hay como maximo 15 misiones en uldum, no jugué esta expansion asi que no se mucho de esa zona y no puedo dar muchos detalles lo siento

**Comment by skyrex321** [comment]
Sino haces la cadena del tablón solo encontraras misiones sueltas... que no te hacen cadena ni nada... tienes que hacer la cadena primero y luego después de salvar al príncipe de ramkahen empezaran las cadenas de misiones para derrocar a los aliados de Alamuerte en Uldum también se desbloquean las misiones de Harrison Jones

**Comment by Presoloko** [comment]
esas las he hecho, como he dicho he peinado el mapa, maximo llegas a amistoso con ellos(ramkahen)

**Comment by Presoloko** [comment]
Por cierto algunos mobs no dropean absolutamente nada como los buitres malsanos

**Comment by Compresor** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
