### ISSUE TITLE
[Druida Feral] Abalanzarse 

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#429]
La skill Abalanzarse http://es.wowhead.com/spell=64478/abalanzarse-feral
Dice que DEBE haber un stunt de 4 segundos, pero cuando se utiliza, casi siempre O se falla el ataque O el stunt dura 1 segundo.

Pues ojala lo arreglen, porque es una de las habilidades centrales del druida feral.

**Comment by searum** [comment]
va perfectamente.

**Comment by SherBlader** [comment]
searum, esta habilidad esta mal, si stunea, pero solo 1 segundo y la skill dice que son 4
