### ISSUE TITLE
Brujo destruccion

### ISSUE THREAD

**Issue by Pedricero** [RoDNet/Bugtracker-Infinium-4.3.4#4290]
Bien mi consulta o reporte en este caso es referente a mi brujo destruccion, antes de nada decir que llevo varios años manejando el brujo destruccion en otros servers por lo que no soy ningún novato en el tema. El problema es que no consigo hacer mas de 20k de dps teniendo todo a 378,  excepto botas, casco , cinturon y guantes que son de 397. Estoy correctamente engemado, encantado todas y cada una de las piezas y armas y reforjado dentro de sus parámetros y teniendo en cuenta las principales prioridades. En igualdad de equipo y condiciones un mago hace pongamos por ejemplo la mazmorra de cámaras de orígenes una media de 30k y a un war le he visto hacer 35k cuando yo me veo mal para sacale al brujo entre 18 y 20k. Por favor no me digais que es cuestion de rotaciones o cualquier otra simpleza por el estilo porque he probado mil combinaciones en los muñecos con resultados similares y tal como decia al principio llevo ya años manejando al brujo, por eso me atrevo a decir que en este server no llega donde debería y resulta un poco frustrante la verdad.
Gracias de antemano por su atención y mis disculpas por las molestias ocasionadas si se ha dado el caso.
Un saludo.

**Comment by Kiritoo** [comment]
Hola pedricero si es cierto que no podemos decirte como manejar el brujo, pero si te comentamos que intentes probar algun talento que falle o que revises daños de hechizos que puedan estar bajos y nosotros lo arreglamos pero sin esos datos no podemos hacer nada, gracias por comentarlo, esperamos tus reportes.
Saludos.

**Comment by Pedricero** [comment]
ok, dime que pasos he de seguir que ahi si que ando un poco perdido, gracias mil por tu ayuda.

**Comment by Kiritoo** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by Pedricero** [comment]
No el problema es que no se como comprobar si falla un talento o una determinada acción, eso es algo que escapa un poco a mi comprensión, se que pego poco pero a que se debe la verdad es que no se decirlo. Creo que este problema es general ya que los brujos que hay en mi guild  y otros que conozco de coincidir con ellos en raids hacen un dps similar al mio, por tanto doy por hecho que es algo sea lo que sea que nos afecta a todos. Siento no poder ser mas explícito en este sentido, lo único que me llama mucho la atención tal como decia en mi mensaje original que otros pjs con equipos similares e incluso inferiores en algunos casos, nos saquen tanta diferencia en cuanto a dps.
Gracias de nuevo y perdón por no poder ser de mas ayuda en aspectos tecnicos.

**Comment by Wiinter** [comment]
Respecto a la pregunta si tiene algun talento bug o algun hechizo que pegue de menos, solo hay un talento que no funcione correctamente Terror del Caos. Hace cosa de 2 meses estuve comprobando todas las ramas de los brujos para reportar los bugs que faltaban. Actualmente la rama de Destrucción es la que más pega ya que recientemente las pets que se usan en la rama Aflicción y Demonologia no pegan un carajo, y el diablillo es el énico que mete las descargas de fuego como debe y me aventuraria a decir que las ascuas ardientes están un poco subidas, pero eso ya sería entrar en una teoría infundada mía.
Decir que te gana un warrior en cámaras o un mago no tiene ningun sentido, te explico. Todo el mundo se piensa que por hacer una buena rotación tienes que hacer el mejor dps, pero es mentira. La diferencia entre un dps y un buen dps está en la interacción con el boss. Por poner un ejemplo, en camaras el boss Rajh que tiene de particular? Que llegado a un punto se pone un debuff a si mismo que le augmenta el daño recibido a cambio te hace daño en area. Por tanto lo que hay qe hacer es guardarte los cds para ese pequeño tramo del combate, tambien hay qe pensar que si llevas una party que tiene mucho dps a veces vale la pena tirarse los cds al principio porque no vas a aprovecharlos con el debuff porque baja demasiado rapido. Con este pequeño detalle he llegado a hacer en ese boss 38k y voy full 378 pve.
A donde quiero llegar es que el brujo pega bien, la cosa es que hay qe adaptarse a cada escenario y eso es lo qe cuesta. Tampoco te negaré que por ejemplo el warrior está haciendo un daño sobrehumano y nadie lo reportar.. también y el mago puede ser tambien.. Pero ya te digo yo que el brujo es la clase que tiene todo casi perfecto en tema talentos y daño de hechizos, sin contar las pets que es el único punto negativo y que verás, si buscas en el bugtracker que tengo varios reportes al respecto de ello.
Espero haberte ayudado un poco, si necesitas cualquier cosa puedes susurrarme ingame, tengo el mismo nombre y te echaré una mano en lo qe pueda.

**Comment by Pedricero** [comment]
Ok, muchas gracias compañero, pero la realidad es que cuando voy a fireland no logro ser mas que un mero 5º puesto y un brujo amigo nuestro que lleva la tira jugando aqui, unas veces queda por encima mio y otras por debajo jejeje, pero el dps es similar siempre, no obstante tendré en cuenta todo esto que me comentas con el fin de maximizarlo.
Gracias nuevamente. Un abrazo.

**Comment by Wiinter** [comment]
Cualquier cosa, susurrame y charlamos si tienes cualquier duda.
