### ISSUE TITLE
Baja cantidad de absorción con Palabra de poder: escudo

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#43]
Aspecto de la palabra de poder: escudo, que he podido observar.
Antes ese hechizo absorbia un poco mas de 21k de daño, actualmente ha bajado drásticamente a los 12k. Este inconveniente deja desnuda a esta clase, ya que se nutre principalmente de estos beneficios. Como curiosidad, recuerdo que en el anterior parche, estando en sombras, ya me absorbia 16k, en comparación con los 12k actuales.

**Comment by SherBlader** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/13

**Comment by Dazand** [comment]
Puede ser que la falta de absorción del escudo se deba a que no tienen maestría?

**Comment by paellaencol** [comment]
Dazand, podría ser, pero el problema es que antes, sin estar en la rama de talentos de disciplina ya me absorbia más,en torno a 4k mas.

**Comment by Dekadencee** [comment]
Maestria Fixeada

**Comment by paellaencol** [comment]
Perfecto, maestria arreglada :)

Ahora, el otro problema es la capacidad de absorción del escudo es sensiblemente inferior a la que debería hacer.

Según el DrD, debería absorber 22500 (lo que estaba haciendo hasta ahora en el 4.0.6), sin embargo está absorbiendo solo 14k:

http://img812.imageshack.us/img812/8017/ldga.jpg

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/812/ldga.jpg/'><img src='http://img812.imageshack.us/img812/8017/ldga.jpg' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

Gracias!

Edito: he cogido dolencia de resurrección y al utilizar palabra de poder escudo me absorbe lo mismo, 14984

**Comment by ghost** [comment]
Ya absorbe más, si para ti esta bug @paellaencol abre otro reporte.
