### ISSUE TITLE
[Talento][Druida]Stampede

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#430]
Hola quiero informar de este talento:
Estampida http://old.wowhead.com/spell=78893
En la parte del felino que dice que tras usar carga feral(felina) no sera necesario el sigilo para lanzar devastar.
Tras usar carga feral el hechizo aparece un aura alrededor del marco del hechizo pero no se llega a iluminar el recuadro impidiendo usar el hechizo.
![wowscrnshot_071313_230812](https://f.cloud.github.com/assets/3537253/793401/5aa430dc-ec00-11e2-9208-5b3f438b1bcf.jpg)

Un saludo.

**Comment by searum** [comment]
fix
