### ISSUE TITLE
Portal Tierras Altas Crepusculares

### ISSUE THREAD

**Issue by kikete17** [RoDNet/Bugtracker-Infinium-4.3.4#4300]
Problema:ha desaparecido el portal en Ventormenta después de la última caída de ayer sobre las 19:40 hora española

**Comment by shogun1968** [comment]
yo tampoco lo veo

**Comment by shogun1968** [comment]
pero después de hacer un par de misiones en tierras altas crepusculares, me apareció un portal a Ventor y allí ya estaba el portal

**Comment by Compresor** [comment]
Hay qe hacer la cadena entera del tablón de Ventormenta o Orgrimmar de Tierras Altas Crepusculares.
