### ISSUE TITLE
[Warrior - Armas] Seccionar Mejorado 

### ISSUE THREAD

**Issue by Sagittariu5** [RoDNet/Bugtracker-Infinium-4.3.4#4302]
ID:
- http://cata.openwow.com/spell=12668
- http://www.wowwiki.com/Improved_Hamstring

Problema: Esta saltando a la primera que pones el seccionar, El CD interno del seccionar esta bien, lo mismo de los 30 sec, del seccionar mejorado, lo que esta mal es que si te quitas el seccionar mejorado con alguna habilidad, y viene otro warrior te lo vuelve a poner, teniendo que haber el DR de parte del war por la propia habilidad, como del jugador al que se la ponen.

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, ya no daremos soporte al actual
