### ISSUE TITLE
[Misiones][Tierras Altas Crepusculares] Alas sobre Bancalto

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4303]
Buenas.
• Nombre: Alas sobre Bancalto
• Enlace: http://es.wowhead.com/quest=27516
• Descripción: Habla con Thordun Golpemartillo y volad juntos de vuelta a Bancalto. 
• Problema: Al hablar con Thordun Golpemartillo (http://es.wowhead.com/npc=45172) no sucede nada. 
Desde ya muchas gracias y hasta luego.

**Comment by Kiritoo** [comment]
Hola mayhem esa mision deberia funcionar la arregle el otro dia y unos cuantos jugadores ya la hicieron, dejala y vuelve a cogerla sin estar sobre una montura, saludos.

**Comment by ghost** [comment]
Cierro porque soy un feo.
Disculpar las molestias.
