### ISSUE TITLE
[Warrior - Armas] Aullido perforador

### ISSUE THREAD

**Issue by Sagittariu5** [RoDNet/Bugtracker-Infinium-4.3.4#4304]
ID:
- http://es.wowhead.com/spell=12323/aullido-perforador

Problema, No tiene su DR decreciente, tambien esta cortando en alto, las habilidades de Separacion, Traslacion, y similares.

Nota: Aunque esto ultimo, creo que es en general los relantizares de este tipo como ''Cadenas de hielo'', siendo que estas habilidades estan perdiendo su atractivo y su uso en PvP

**Comment by F4NT4SM4** [comment]
si pides dr para un relentizante 
ps tu disparo de conmocion tambien deberia de tener ehhh 
a si que siento decirte que no tiene dr decreciente

**Comment by Monleon** [comment]
Los snares no tienen DR

**Comment by Sagittariu5** [comment]
Referencia a una spell del cazador que tiene CD de 3 sec y no es istantanea Por lo tanto no puedes spamearla Pues no se tu chaval.

**Comment by Overseer101** [comment]
Por favor dejad de mezclar issues con piques personales, el aullido perforador es un Snare y no tiene DR, punto pelota. Si dispario de conmocion debe tener DR y no lo tiene, se reporta aparte, asi que vamos a dejarnos de tonterias por favor.

**Comment by F4NT4SM4** [comment]
por que los 10p de ira al spamear aullido no duelen eh... xD
