### ISSUE TITLE
Gunra "Intenderte de justicia" no vende pieza de druida

### ISSUE THREAD

**Issue by Kasaka** [RoDNet/Bugtracker-Infinium-4.3.4#4313]
NPC:  Gunra "Interdente de Justicia"
Lugar: Ogrimmar

Problema: Dicho NPC no vende los brazales (muñeca) pve de justicia para la rama de Equilibrio del druida. Si vende los de las ramas de restauración y feral.

**Comment by Kiritoo** [comment]
Te importa facilitarnos el id o el enlace a wowhead del item que falta, gracias.
Saludos.

**Comment by Kasaka** [comment]
Kiritoo, lo he estado buscando en wowhead y los únicos brazales que "puede" que le sirvan al druida equilibrio es este (http://es.wowhead.com/item=71262), este ítem en concreto, si que lo vende el vendedor, en principio yo usaría esa pieza de muñeca solo para el druida heal ya que te da espiritu. He estado preguntado a varios usuarios y un usuario me ha comentado que esos son los únicos brazales que hay para el druida equilibrio que venda dicho npc, que el espiritu le sirve al druida equilibrio, si esto es cierto que no lo pongo en duda, seguramente sea un error mio, disculpen que haya creado este reporte. Un saludo.

**Comment by Wiinter** [comment]
Realmente al druida con un talento que tiene  convierte el espiritu en golpe. Por tanto el druida en equilibrio el espiritu le hace dos cosas, le da golpe y regeneración de maná, 2x1. Esto le pasa al sacer sombras y al chamán elemental.

**Comment by Compresor** [comment]
Si que los vende, para druida resto y equilibrio los dos son los brazales que has linkeado, de espiritu y critico.
