### ISSUE TITLE
[Druida] Lanzamiento Libre

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#4317]
https://wow.freakz.ro/spells.php?spell=16870&name=clearcasting

Este problema no ocurre siempre, pero pasa de tanto en cuanto, y es que salta el lanzamiento libre por augurio de claridad pero no siempre es gratuito, que no te cueste mana, energia o ira, como bien te marca la habilidad.

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, ya no daremos soporte al actual
