### ISSUE TITLE
bugs encontrados de paladin

### ISSUE THREAD

**Issue by M4NUL0R3NT3** [RoDNet/Bugtracker-Infinium-4.3.4#4327]
mi pj se llama yihad, paladin reprension/sagrado
enumero a continuacion, hasta la fecha, los bugs encontrados, algunos los considero crucialmente limitantes a la hora de hacer dps, y uno de ellos influye tambien en sagrado, ignoro si a los tankes tb les afectase, podria ser.

-interfaz del poder sagrado bug: ignoro si es generico, o solo me ocurre a mi, pero ciertas veces, por ejemplo, al castear habilidades de poder sagrado, los resultados no se corresponden a la cantidad usada de poder sagrado, y podria deberse a que no se actualiza correctamente la interfaz del poder sagrado, y he comprobado que esto afecta a auras hechas con powerauras para monitorizar el poder sagrado. hay veces en las que lanzas una palabra de gloria con 3 cargas y resulta el efecto de 2, otras en las que con 1p de poder sagrado lanzas inquisicion y resulta la duracion de 2 cargas. esto es a veces beneficioso y a veces perjudicial pero en cualquier caso, esas veces no controlas como debieras el poder acumulado e invertido y se te rompen los esquemas hechos de cara a un combate o a curar una raid, pues afecta como antes decia, tanto a sagrado como a reprension.

-talento "sellos de mando" bug: he comparado con mi paladin del server molten a mi yihad, este talento no esta funcionando. se ve claramente en recount que no figura el daño realizado por este talento, y un 7% del daño de arma no es pa despreciarlo. ya lo estuve viendo hace semanas con un GM. cada vez que realizaba un ataque fisico, fuese habilidad o autoataque, con los 3 sellos que son afectados por este talento (sellos de verdad, justicia y rectitud), salia un mensaje negativo color rojo en la parte superior, el cual dice: "esta habilidad no esta disponible para ti". esto limita al paladin dps a la hora de mantener un dps alto.

-talento "santidad de batalla" bug: un talento crucial para poder incrementar el dps y por culpa del cual no me renta nada reforjar el indice de celeridad, pues reduce el CD de golpe de cruzado y tormenta divina en base a tu celeridad. pierdes golpes de cruzado por unidad de tiempo, pierdes poder sagrado que no ganas, y pierdes veredictos de templario a consecuencia de ejecutar mas lentamente los golpes de cruzado como fuente de poder sagrado. no importa cuanto suba la celeridad con dicho talento activo, siempre tiene el CD en 4,5s y por supuesto, no se nota nada cuando recibes ansia de sangre/heroismo.

-talento "proposito divino" ocasionalmente bug: hay algunas veces, en las que, saltando el talento proposito divino, no obtienes su bufo. esto lo veo claramente al tener activo el texto flotante de facultades reactivas, como pudiera ser proposito divino o martillo de colera. esto confunde enormemente si pretendes por ejemplo, ejecutar un veredicto de templario con este "falso proposito divino", y tienes cargas de poder sagrado previamente acumuladas, pues gastaras esas cargas y habras desperdiciado ese poder sagrado, reduciendo tu dps. ademas con otra habilidad tambien se comporta de manera desagradable cuando si da el bufo, con la curacion "palabra de gloria", ocurre que por ejemplo, si tienes 2 cargas de poder sagrado, obtienes el proposito divino bien obtenido (esto es, saltando texto flotante si esta activado, apareciendo el icono del bufo, y apareciendo la animacion en pantalla del proposito divino), y quieres gastarlo para una cura de 3 cargas son gastar las 2 que podeias, se te gasta todo, y la curacion hace efecto de las 2 propias cargas que tenias. bug que descoloca, frustra y cabrea a partes iguales

no he encontrado aun nigun bug beneficioso, salvo el efecto inesperado de habilidades de poder sagrado a raiz de tener bug ocasionalmente la interfaz del poder sagrado. lo digo porque en algun reporte por ticket algun GM se me puso mosca por reportar solo bugs perjudiciales y no beneficiosos, y no se debe generalizar con toda la gente, ya que por ejemplo, yo no soy de esa gente. por ello todo lo bug que encuentro, indistintamente de si causa perjuicio o beneficio, lo reporto por igual. hay quien dice que en pvp los paladines retri se limpian efectos magicos con la habilidad "limpiar", pero no estoy seguro porque ni lo he probado ni hago apenas pvp con paladin, solo se lo que se cuchichea en el canal global, y tantas chorradas pueden decirse por ahi al cabo del dia.....en fin.

porfavor, arreglen todo esto en cuanto les sea posible, por lo menos estos bugs de talentos y si el asunto de la interfaz del poder sagrado es cosa de mi pj, cuando este conectado tendre tiempo para ayudar al GM que me atienda en tratar de solucionarlo. volvere a reportar otro informe del DK, mas algunos otros de misiones del frente de magma o de la habilidad de pesca, que no funciona demasiado bien. buenos dias tengan uds.

**Comment by skyrex321** [comment]
que no hay bug beneficioso? el % de Exorcismo y de Propósito divino esta subido con un 15% es imposible que me salte 4 veces seguidas y el exorcismo mas de lo mismo...aparte de la doble especialización en placas acumulable que parece que tiene
