### ISSUE TITLE
bugs encontrados de paladin

### ISSUE THREAD

**Issue by M4NUL0R3NT3** [RoDNet/Bugtracker-Infinium-4.3.4#4328]
mi pj se llama yihad, paladin reprension/sagrado
enumero a continuacion, hasta la fecha, los bugs encontrados, algunos los considero crucialmente limitantes a la hora de hacer dps, y uno de ellos influye tambien en sagrado, ignoro si a los tankes tb les afectase, podria ser.

-interfaz del poder sagrado bug: ignoro si es generico, o solo me ocurre a mi, pero ciertas veces, por ejemplo, al castear habilidades de poder sagrado, los resultados no se corresponden a la cantidad usada de poder sagrado, y podria deberse a que no se actualiza correctamente la interfaz del poder sagrado, y he comprobado que esto afecta a auras hechas con powerauras para monitorizar el poder sagrado. hay veces en las que lanzas una palabra de gloria con 3 cargas y resulta el efecto de 2, otras en las que con 1p de poder sagrado lanzas inquisicion y resulta la duracion de 2 cargas. esto es a veces beneficioso y a veces perjudicial pero en cualquier caso, esas veces no controlas como debieras el poder acumulado e invertido y se te rompen los esquemas hechos de cara a un combate o a curar una raid, pues afecta como antes decia, tanto a sagrado como a reprension.

{RESUELTO}
-talento "sellos de mando" bug: he comparado con mi paladin del server molten a mi yihad, este talento no esta funcionando. se ve claramente en recount que no figura el daño realizado por este talento, y un 7% del daño de arma no es pa despreciarlo. ya lo estuve viendo hace semanas con un GM. cada vez que realizaba un ataque fisico, fuese habilidad o autoataque, con los 3 sellos que son afectados por este talento (sellos de verdad, justicia y rectitud), salia un mensaje negativo color rojo en la parte superior, el cual dice: "esta habilidad no esta disponible para ti". esto limita al paladin dps a la hora de mantener un dps alto.

{RESUELTO}
-talento "santidad de batalla" bug: un talento crucial para poder incrementar el dps y por culpa del cual no me renta nada reforjar el indice de celeridad, pues reduce el CD de golpe de cruzado y tormenta divina en base a tu celeridad. pierdes golpes de cruzado por unidad de tiempo, pierdes poder sagrado que no ganas, y pierdes veredictos de templario a consecuencia de ejecutar mas lentamente los golpes de cruzado como fuente de poder sagrado. no importa cuanto suba la celeridad con dicho talento activo, siempre tiene el CD en 4,5s y por supuesto, no se nota nada cuando recibes ansia de sangre/heroismo.

-talento "proposito divino" ocasionalmente bug: hay algunas veces, en las que, saltando el talento proposito divino, no obtienes su bufo. esto lo veo claramente al tener activo el texto flotante de facultades reactivas, como pudiera ser proposito divino o martillo de colera. esto confunde enormemente si pretendes por ejemplo, ejecutar un veredicto de templario con este "falso proposito divino", y tienes cargas de poder sagrado previamente acumuladas, pues gastaras esas cargas y habras desperdiciado ese poder sagrado, reduciendo tu dps. ademas con otra habilidad tambien se comporta de manera desagradable cuando si da el bufo, con la curacion "palabra de gloria", ocurre que por ejemplo, si tienes 2 cargas de poder sagrado, obtienes el proposito divino bien obtenido (esto es, saltando texto flotante si esta activado, apareciendo el icono del bufo, y apareciendo la animacion en pantalla del proposito divino), y quieres gastarlo para una cura de 3 cargas son gastar las 2 que podeias, se te gasta todo, y la curacion hace efecto de las 2 propias cargas que tenias. bug que descoloca, frustra y cabrea a partes iguales

**Comment by kikete17** [comment]
Completamente de acuerdo en todo con Yihad el pala ultimamente esta ``un pelín´´destrozado,se te ha pasado escudo divino que ya lo reporte yo aunque como no haces pvp es normal pero por favor pongan un poco de atención al paladín.Un saludo

**Comment by efectokoleos** [comment]
lo de la interfaz no es cosa del pj pasa a todos xd y los talentos bueno el k mas va a costar es santidad de batalla ya que el emulador no reconoce aun el cooldown por celeridad pero bueno los demas se van revisando y arreglando poco a poco

**Comment by kikete17** [comment]
Uff xd santidad es el más importante pero bueno mucho ánimo y arréglenlo cuanto antes y buenamente puedan.Un saludo

**Comment by efectokoleos** [comment]
santidad arreglado :D
