### ISSUE TITLE
[Mision] Svarnos

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#433]
La mision Svarnos http://es.wowhead.com/quest=28185/svarnos De Tol barad

No se puede hacer porque hay que acceder a un castillo el cual esta cerrado.

![wowscrnshot_071313_210659](https://f.cloud.github.com/assets/4895839/793662/21395302-ec2a-11e2-882a-f68e6bffebe6.jpg)

**Comment by crowel** [comment]
Hola queria decirte que estas intentando entrar por donde no es ^^
El boss si esta ahi realmente bajo tierra pero esa no es la entrada, te pongo unas imagenes.
![sin ttulo](https://f.cloud.github.com/assets/3537253/869153/f76db540-f7e6-11e2-8bc4-46fedb58fefd.jpg)
![wowscrnshot_072913_023235](https://f.cloud.github.com/assets/3537253/869154/f7a9dd2c-f7e6-11e2-9793-a60ed43dcd1a.jpg)
![wowscrnshot_072913_023632](https://f.cloud.github.com/assets/3537253/869155/f7ac44d6-f7e6-11e2-8566-aab791396454.jpg)

En la primera imagen puedes ver la ubicación de la entrada en el mapa, en la segunda puedes ver  la entrada  y si te recorres el bloque D te encontraras con el NPC objetivo de misión como se ve en la 3ª foto.

Cierro Issue, un saludo.
