### ISSUE TITLE
(Druida Balance) Forma de Lechúcico Lunar

### ISSUE THREAD

**Issue by DepredatorSexual43** [RoDNet/Bugtracker-Infinium-4.3.4#4330]
Nas

No se observan cambios hasta el parche 5.0

Notas parche 4.0.6 - 4.3.4 

Clases:

-Druida:  Ahora Forma de lechúcico reduce el daño un 15% en vez de aumentar la armadura. Además, ahora cambiar de forma, activando o desactivándola, rompe las raíces. Hay que tener en cuenta que esto no se indica en la descripción.

Forma de Lechúcico lunar remueve cualquier efecto de enraizamiento, ademas de slows.

Fuente: http://eu.battle.net/wow/es/game/patch-notes/4-0-6

Salu2

**Comment by Kiritoo** [comment]
Cual es el fallo, actualmente aumenta la armadura al igual que quita los roots al entrar o salir de la forma del lechucido.

**Comment by DepredatorSexual43** [comment]
No, actualmente no remueve los roots como deberia.
Por ejemplo: El root de la araña del hunter, el root de explosion mental (shadow priest).

Salu2

**Comment by Kiritoo** [comment]
Esto lo meti hace 2 dias en infi, saludos.
