### ISSUE TITLE
Joyería: Recetas Gema Meta

### ISSUE THREAD

**Issue by Mellonamin** [RoDNet/Bugtracker-Infinium-4.3.4#4333]
Revisando a los vendedores de joyería de parte de la Horda encontre que ninguno de ellos tiene, al menos, 2 recetas de gemas Meta que se llegan a necesitar:

Diamante de espíritu de las Sombras resonante -> +54 fuerza +3% efecto crítico
Diamante de espíritu de las Sombras ágil      -> +54 agilidad +3% efecto crítico

Ahora bien, buscando el link ya no existen en bases dichas recetas pues ya han sido cambiadas. Así que encontré esta página http://www.guiaswow.com/joyeria/buscando-gemas-colores.html donde se muestran muchas otras recetas que también deberían estar a la venta, al menos las de Gema Meta.

Gracias!

**Comment by ghost** [comment]
Las recetas de meta de fuerza y de agilidad son de drop del mundo.
Boceto de la de fuerza http://es.wowhead.com/item=68782
Boceto de la de agilidad http://es.wowhead.com/item=68778
Saludos!

**Comment by Mellonamin** [comment]
Sí, lo son ahora pero en la expansion 4.3.4 son de compra. Lo sé pues hace poco más de un año yo las tenía (era joyero con otro pj).
Como mencioné las bases han cambiado y si revisan los stats incluso, ahora dan 

Diamante de espíritu de las Sombras resonante ---> +11 fuerza y 3% de efecto crítico aumentado
Diamante de espíritu de las Sombras ágil           ---> +11 agilidad y 3% efecto crítico aumentado

Muy diferentes a los de +54xx

Gracias por su atención.
