### ISSUE TITLE
[Misiones][Tierras Altas Crepusculares] Encuentra a Fanny

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4336]
Buenas.
• Nombre: Encuentra a Fanny
• Enlace: http://es.wowhead.com/quest=28378
• Descripción: Encuentra y rescata a Fanny Bramal. 
• Problema: Fanny esta ahí (http://es.wowhead.com/npc=48499) pero no cuenta para completar la misión.
Desde ya muchas gracias y hasta luego.

**Comment by redneo** [comment]
Arreglada.
