### ISSUE TITLE
[Mazmorras/Bandas] Entrada a Scholomance

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4337]
Buenas.
La entrada a Scholomance debería estar limitada a los personajes de nivel 33 o más, sin embargo, hoy quise llevar a un compañero nivel 44 y no podía entrar porque le salía la leyenda "Necesitas el nivel 33 o mas para entrar a esta mazmorra".
Desde ya muchas gracias y hasta luego!

**Comment by redneo** [comment]
Tendría que ser 40 o más.

Ya lo he cambiado y hace tiempo puse los npcs de misiones en la entrada.

UN saludo
