### ISSUE TITLE
[Misiones][Sierra Espolón] ¡Requisar el dirigible!

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4345]
Buenas.
• Nombre: ¡Requisar el dirigible!
• Enlace: http://es.wowhead.com/quest=25652
• Descripción: Súbete al globo aerostático Krom'gar e intenta impedir que destruya el Bastión Cortaviento. 
• Problema: El globo aerostático Krom'gar (http://es.wowhead.com/npc=41009) está demasiado alto como para usarlo.
Desde ya muchas gracias y hasta luego.

**Comment by matycelta** [comment]
tengo el mismo problema, podrian arreglarlo por favor? Gracias :)
