### ISSUE TITLE
Bugs en mazmorras del ojo

### ISSUE THREAD

**Issue by steinerandres** [RoDNet/Bugtracker-Infinium-4.3.4#4347]
Por ahora, en las mazmorras aleatorias heroicas que he podido ir haciendo gracias a que cerrasteis temporalmente cámaras me he encontrado los siguientes bugs:
-Minas de la muerte: No se abre la puerta de antes del 2 boss.
-Zul'Gurub: Algunos de los mobs pegan demasiado daño (las serpientes esas que escupen, justo antes del primero boss), incluso habiendo bebido del caldero, no es normal. No pude continuar más allá debido al daño.
-Ciudad perdida de los Tol'Vir: Los dos bosses a los que nos enfrentamos (el primero y el último) estaban bug, no atacaban, hacían el amago y luego evadían.
Un saludo, Andres.

**Comment by yosalve** [comment]
el ultimo boss de trono de las mareas esta bug tambien, llena la habitacion de mobs ni bien empieza el evento, tendrian q venir en oleadas de aunos pocos pero llena la habitacion y voltea el servidor

**Comment by Monleon** [comment]
Zul'Gurub todos los daños ajustados. Las serpientes que flanquean al primer boss son ceceables,y el casteo que os quita el buff del caldero cortable (por eso recibis tanto daño, porque os elimina el buff al castear)

Ciudad perdida de los Tol'vir. Hay que hacer los bosses en orden. Es muy importante, sino se os quedarán en evadir hasta que se haya hecho el anterior

Queda pendiente el resto

**Comment by Monleon** [comment]
Y las puertas de acceso de minas de la muerte cuando se compile ya irán bien
