### ISSUE TITLE
[Profesiones][Pesca] Pesca en Rasganorte

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4349]
Buenas.
Estos dias me di cuenta que hay un problema al pescar en Rasganorte y es que el 70% de las veces sale el loot vacio cuando se pesca, sobretodo cuando quiero conseguir Mero aletarroca (http://es.wowhead.com/item=41803) que es la que se pesca en aguas abiertas o cuando quiero pescar monedas o la rata en Dalaran también pasa que sale vacío.
Ya intente todo, con cebo, sin cebo, con una caña, con la otra pero nada :S
Desde ya muchas gracias por todo.
Hasta luego.

**Comment by rubiosoy** [comment]
yo las monedas las pesque dentro de las cloacas segun bajas a mano izquierda hay un pequeño hueco, y la rata tambien la pesque hay. siempre me daba monedas al pescar, ponia cebo de +100. suerte

**Comment by ghost** [comment]
Ok ahora pruebo, muchas gracias.
Edito el Issue entonces.

**Comment by ghost** [comment]
Nada, hermano, intente todos los huecos que hay en las cloacas y la mayoría de las veces no sale ningún loot.
