### ISSUE TITLE
[Banda/Mazmorras] Alysrazor 2, la venganza de Alysrazor (10 normal)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4350]
Buenas.
Vengo a molestar de nuevo con este boss.
El problema ahora es que Alysrazor vuela muy bajo, tanto las Nubes incendiarias (http://es.wowhead.com/spell=99426) y los anillos de fuego también están al ras del suelo, haciendo que sea muy dificil la orientación durante el encuentro.
Las plumas siguen sin poder usarse, ignoro si esto ya se compilo o no pero ya que hago el post lo menciono.
Muchas gracias por todo!

**Comment by efectokoleos** [comment]
prueba ahora

**Comment by ghost** [comment]
Arreglado!!!
Muchísimas gracias!!!
