### ISSUE TITLE
Mazmorras - Zul'Gurub

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4357]
Nombre: Jin'do el Sojuzgadioses http://es.wowhead.com/npc=52148
Problema: en la fase 2 del boss, las cadenas (http://es.wowhead.com/npc=52430) que tenemos que destruir son totalmente invulnerables a cualquier tipo de daño que podamos hacerle.

Desconozco si hay mas bugs en este boss porque no hemos podido pasar de ahi.

**Comment by Wiinter** [comment]
Tienes que coger un espiritu furioso y esperar un embate para que lo destroce. Aqui te lo explica.
http://es.wowhead.com/npc=52148#comments

**Comment by yosalve** [comment]
genial, lo probare y vere si todo funciona bien.
Gracias y saludos

**Comment by yosalve** [comment]
confirmo que las cadenas andan, fue que no lo sabia hacer, las cadenas se pueden romper con el golpe de los adds gigantes y la fase concluye cuando se matan las cadenas. El boss cambia de fase sin problemas.

Saludos
