### ISSUE TITLE
Bug en camaras cama de los arigenes

### ISSUE THREAD

**Issue by Elmentalista** [RoDNet/Bugtracker-Infinium-4.3.4#4366]
El dia de ayer logramos entrar a camara de los origenes y cuando matamos a los demas boss solo y nos falataba Rajh, cuando empezamos a matarlo lanza su salto y desaparece, aparte nos saco de la mazmorra disolviendo el grupo.

**Comment by Monleon** [comment]
Recién probado y esto no sucede.
