### ISSUE TITLE
Mazmorras - Zul'Aman - Señor Aojador Malacrass

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4367]
Mazmorra: Zul'Aman http://es.wowhead.com/zone=3805
Nombre: Señor Aojador Malacrass http://es.wowhead.com/npc=24239#abilities
Problema: castea una habilidad llamada control mental (http://es.wowhead.com/spell=43550), que convierte temporalmente a uno o mas miebros del grupo a su bando durante unos segundos. He buscado la habilidad en cuestión y no figura en la lista de habilidades que tiene el boss, ahora bien. Hay veces que cuando la tira bugea a uno o mas miembros del grupo, si bien no impide matarlo, cuando lo matamos hay uno o mas miembros que no pueden salir de la habitación sea camino al ultimo boss o de regreso a la entrada, los manda caminando solos de vuelta a la habitacion. La distancia fuera de la habitacion a la cual sucede esto varia. Hay veces que toca ni bien cruzan la puerta y otras un poco mas lejos. Para quitar esto hay que wipear.

Lo que hoy se nos ha agregado, que con un grupo crossfaction, uno de los miembros del grupo quedo como enemigo para los de la faccion opuesta DEL MISMO GRUPO luego que el boss nos libere del Control mental (http://es.wowhead.com/spell=43550)

Pero repito, la habilidad no aparece en la lista de habis del boss, http://es.wowhead.com/npc=24239#abilities, si la quitaron en expansiones siguientes a cata disculpas por la molestia.

Saludos y gracias.

**Comment by Wiinter** [comment]
El control mental seguro que fué porque llevaba un sacer seguramente. El problema es que cuando coge las habilidades de un personaje de la party, si escoge al sacerdote, tiene que hacer estas tres habilidades no control mental :
    Flash Heal – Malacrass calls upon Holy magic to heal himself or an ally for 20% of their maximum health.
    Psychic Scream – Malacrass lets out a psychic scream, causing nearby enemies within 40 yards to flee for 4 sec.
    Leap of Faith – Malacrass pulls the spirit of a random friendly target to him, instantly moving them to his side.
    Shadow Word: Pain – Malacrass utters a word of darkness at a random enemy, inflicting 3600 Shadow damage every 2 seconds for 18 sec.

**Comment by yosalve** [comment]
Entonces, si debe hacer esas tres y Control mental no esta en su lista de skills, esta bien o mal?

**Comment by Wiinter** [comment]
Control mental está mal, no debería hacerla.

**Comment by yosalve** [comment]
Perfecto, solo agregar que hoy lo volvio a hacer SIN sacerdote en el grupo y afecto a dos integrantes del grupo, y bugeando (aunque esta vez fue lo mas lejos que vi) a uno solo pj del grupo.

Si sirve de algo éramos dos guerreros, un brujo, un paladin y un caballero de la muerte
