### ISSUE TITLE
[Bug Mision] ¿Es ese tu goblin?

### ISSUE THREAD

**Issue by Kagome** [RoDNet/Bugtracker-Infinium-4.3.4#437]
La mision anda Bug,cuando intentas hablar con la mujer esa, en esta pestaña que se mostrará en la foto, no hace nada,sigue la pestañita y te quedas sin hacer la mision.
![wowscrnshot_071413_042131](https://f.cloud.github.com/assets/4942077/793680/d43d37f0-ec2c-11e2-9d08-171a1af5bf68.jpg)
![wowscrnshot_071413_042435](https://f.cloud.github.com/assets/4942077/793681/d45f7234-ec2c-11e2-961b-9b26c5926cbb.jpg)

**Comment by Kiritoo** [comment]
Fix
