### ISSUE TITLE
[Misiones][Tanaris] Intentando matar a un puñado de bichos

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4373]
Buenas.
• Nombre: Intentando matar a un puñado de bichos
• Enlace: http://es.wowhead.com/quest=24953
• Descripción: Habla con Narain Sabelotodo para pilotar el enjambrista bajo control mental hasta el interior de la colmena de Sima Abierta. 
• Problema: Al hablar con Narain Sabelotodo (http://es.wowhead.com/npc=11811) no sucede nada.
Muchas gracias!

**Comment by redneo** [comment]
Ya te deja montar en el enjambrista cuando hablas con él. Me quiere sonar que esta misión la arregle cuando tu y yo eramos jovenes.

Un saludo

**Comment by ghost** [comment]
Disculpa pero no pude evitar reirme y sentirme viejo a la vez.
Saludos y muchas gracias.
