### ISSUE TITLE
[Items/Objetos] Antorcha de blandón

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4375]
Buenas.
• Nombre: Antorcha de blandón
• Enlace: http://es.wowhead.com/item=63027
• Descripción: Uso: Quema un fardo de heno en la Ciudad Perdidad de los Tol'vir.
• Problema: Se puede usar en cualquier lado, incluso abre puertas de mazmorras que por algún motivo están cerradas.
• Observaciones: Es proporcionado para completar la misión Humo en los ojos (http://es.wowhead.com/quest=27923).
Desde ya muchas gracias.

**Comment by redneo** [comment]
arreglado
