### ISSUE TITLE
[Misiones][Cuna de Invierno] Tormenta arcana interior

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4376]
Buenas.
• Nombre: Tormenta arcana interior
• Enlace: http://es.wowhead.com/quest=28841
• Descripción: Utiliza el atrapasueños potenciado para cerrar 5 teseractos Arcanos dentro de Mazthoril. 
• Problema: El atrapasueños potenciado (http://es.wowhead.com/item=66060) paraliza al usuario por 3 minutos en vez de vez de cerrar los teseractos Arcanos (http://es.wowhead.com/npc=50291)
Desde ya muchas gracias.

**Comment by redneo** [comment]
Arreglado
