### ISSUE TITLE
fotitos de vudu afk permanente en las bgs

### ISSUE THREAD

**Issue by nayan87** [RoDNet/Bugtracker-Infinium-4.3.4#4377]
fotitos lindas de nuestro querido compañero
![wowscrnshot_120114_212506](https://cloud.githubusercontent.com/assets/7257569/5253340/3d5b4a58-79a6-11e4-8d68-3fc77a759f0e.jpg)

![wowscrnshot_120114_212630](https://cloud.githubusercontent.com/assets/7257569/5253348/51e8a146-79a6-11e4-81b2-5dcb4afc5122.jpg)

![wowscrnshot_120114_212932](https://cloud.githubusercontent.com/assets/7257569/5253355/6764417e-79a6-11e4-8d89-6f4c8f93497f.jpg)

![wowscrnshot_120114_213110](https://cloud.githubusercontent.com/assets/7257569/5253365/769d39ca-79a6-11e4-9bea-b91304370183.jpg)

**Comment by Kiritoo** [comment]
Esto no va aqui

**Comment by nayan87** [comment]
Lo se kiryto pero ni tengo otro sitio donde subir las imagenes. Mantenlo hasta que veais la denuncia por favor. Gracias

--- Mensaje Original ---

Desde: "Kiritoo" notifications@github.com
Enviado: 1 de diciembre de 2014 23:34
Para: "RoDNet/Bugtracker-Infinium-4.3.4" Bugtracker-Infinium-4.3.4@noreply.github.com
Cc: "nayan87" pablogf87@hotmail.com
Asunto: Re: [Bugtracker-Infinium-4.3.4] fotitos de vudu afk permanente en las bgs (#4377)

Esto no va aqui

---

**Comment by DepredatorSexual43** [comment]
Un xaval defendiendo base? Algo mas?

**Comment by nayan87** [comment]
En el registro de batalla se podra comprobar que tiene cero daño cero capturas y las 8 denuncias por jugador ausente que yo mismo le puse durante la batalla. Dejemonos ya de excusas. Y aceptemos que si se hace trampa se paga castigo.  Como ya apunte en el post yo mismo denuncie a hordas que hacian lo mismo con sus cuentas alianzas.  No dire nada mas que sean los mjs los que decidan.

--- Mensaje Original ---

Desde: "DepredatorSexual43" notifications@github.com
Enviado: 2 de diciembre de 2014 17:59
Para: "RoDNet/Bugtracker-Infinium-4.3.4" Bugtracker-Infinium-4.3.4@noreply.github.com
Cc: "nayan87" pablogf87@hotmail.com
Asunto: Re: [Bugtracker-Infinium-4.3.4] fotitos de vudu afk permanente en las bgs (#4377)

Un xaval defendiendo base? Algo mas?

---

**Comment by rubiosoy** [comment]
pon el registro de batalla para demostrar que no hizo ningun tipo de daño ni sano nada para demostrar que no se movio de hay. la verdad que viendo solo esas fotos podria decir que estaba defendiendo por eso estaba quieto en el mismo sitio, con el registro no tendra excusas. aparte en el registro se vera los nombres de la ali y asi los gm podran comprobar si alguno de ellos tiene la misma ip que vudu

**Comment by Monleon** [comment]
Añadida la opción reportar a jugador inactivo en campo de batalla
