### ISSUE TITLE
[Misiones][Vallefresno] El rey de los Maderiza (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4379]
Buenas.
• Nombre: El rey de los Maderiza
• Enlace: http://es.wowhead.com/quest=13989 (alianza) http://es.wowhead.com/quest=6621 (horda)
• Descripción: El rey de los Maderiza
• Problema: Al usar el estandarte proporcionado en el montículo (http://es.wowhead.com/item=46777) aparece la leyenda "Requiere montículo del tótem de los maderiza" y no se puede llamar al PNJ Murgut (http://es.wowhead.com/npc=12918) para completar la misión.
• Observaciones: El montículo rebalza de PNJ Maderiza iracundo (http://es.wowhead.com/npc=12921).
muchas gracias!

**Comment by redneo** [comment]
arreglada.
