### ISSUE TITLE
[Mazmorra Bug]¿Lord Cuervo?¿Hola?

### ISSUE THREAD

**Issue by Kagome** [RoDNet/Bugtracker-Infinium-4.3.4#438]
¿Alguien me podría decir que pasó con Lord Cuervo?
¿Quién lo aniquiló? ._.
![wowscrnshot_071313_210021](https://f.cloud.github.com/assets/4942077/793685/6893b53c-ec2d-11e2-9d4a-02ad87882638.jpg)
Ayuda! Quiero su montura!

**Comment by Kiritoo** [comment]
Cierro por falta de información.

**Comment by lamaza** [comment]
Yaque te devolvieron la cuent/pj, te explico un poco como se hace un reporte de algo bug:

1- Cada issue (reporte) significará 1 bug, no pongas varios hechizos ni objetos juntos en 1 issue. Trata que tenga que ver del mismo tema.

2- El issue debe contener: Miniexplicación de funcionamiento normal ( si es necesaria), problema o bug en cuestión, respectivas IDs (sacadas de Wowhead.com u otra base de datos de WoW cataclysm, o con un addon de Curse.com "idtool" o algo asi) de los objetos, npc, hechizos, auras etc. involucrados. Además pruebas visuales que sustenten el bug.

3- No exigir cosas en el reporte, solo reportamos en pro de los demás y quizá un poco de nuestros pj. Pero ya entenderás para donde van las cosas.

4- Saludar un poquito, el staff se lia mucho con tanto bug =).

Saludos.
