### ISSUE TITLE
[Misiones][Colinas Pardas] Cumplir con tu deber

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4383]
Buenas.
• Nombre: Cumplir con tu deber
• Enlace: http://es.wowhead.com/quest=12227
• Descripción: Anderhol en Refugio Pino Ámbar quiere que cojas la sidra hidra de Anderhol y que uses la letrina cercana para recuperar el grano ámbar semiprocesado. 
• Problema: Al usar la letrina del refugio (http://es.wowhead.com/object=188666) no cuenta la misión como hecha.
Desde ya muchas gracias.

**Comment by redneo** [comment]
Arreglado
