### ISSUE TITLE
[Misiones][Colinas Pardas] Destapando los túneles

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4384]
Buenas.
• Nombre: Destapando los túneles
• Enlace: http://es.wowhead.com/quest=12003
• Descripción: Brugar Petraescucha en el Campamento de la Brigada de los Páramos de Poniente quiere que explores el edificio norte, el edificio este y el edificio sur de Thor Modan. 
• Problema: Investigar los edificios no cuentan para completar la misión:
Edificio Nortehttp://es.wowhead.com/npc=26468
Edificio Este http://es.wowhead.com/npc=26470
Edificio Sur http://es.wowhead.com/npc=26469
Desde ya muchas gracias y hasta luego.

**Comment by redneo** [comment]
Arreglado.
