### ISSUE TITLE
[Misiones][Colinas Pardas] Poder Latente

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4385]
Buenas.
• Nombre: Poder latente
• Enlace: http://es.wowhead.com/quest=12094
• Descripción: Carga el Fragmento de Gavrock en la primera piedra antigua, la segunda piedra antigua y la tercera piedra antigua, después regresa con Gavrock en las Ruinas de Tethys. 
• Problema: Al usar el fragmento provisto (http://es.wowhead.com/item=36787) en las piedras, no cuenta para completar la misión.
Las piedras son:
Piedra norte http://es.wowhead.com/npc=26856
Piedra este http://es.wowhead.com/npc=26855
Piedra sur http://es.wowhead.com/npc=26857
Desde ya muchas gracias y hasta luego.

**Comment by redneo** [comment]
Arreglado
