### ISSUE TITLE
[Misiones][Colinas Pardas] Anatoly hablará

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4386]
Buenas.
• Nombre: Anatoly hablará
• Enlace: http://es.wowhead.com/quest=12330
• Descripción: Sasha en el Puesto de Venta de Pino Blanco quiere que cojas el dardo sedante y lo uses con Tatjana en el Poblado Solsticio. Trae a Tatjana de vuelta al Puesto de Venta de Pino Blanco. 
• Problema: El dardo sedante provisto (http://es.wowhead.com/item=37665) no funciona contra Tatjana (http://es.wowhead.com/npc=27627)
Desde ya muchas gracias.

**Comment by redneo** [comment]
Teoricamente arreglado cuando caiga el server
