### ISSUE TITLE
 [Misiones][Colinas Pardas] Reparación de trituradoras

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4387]
Buenas.
• Nombre: Reparación de trituradoras
• Enlace: http://es.wowhead.com/quest=12244
• Descripción: Synipus del Aserradero Cielo Azul quiere que le traigas de vuelta 3 trituradoras averiadas. 
• Problema: Al llegar al campamento y utilizar la habilidad de la trituradora "Entregar trituradora" (http://es.wowhead.com/spell=48610)  sale la leyenda "Requiere campamento". Link de la trituradora http://es.wowhead.com/npc=27354
Desde ya muchisimas gracias y hasta luego.

**Comment by redneo** [comment]
Arreglado el poder usar ese spell
