### ISSUE TITLE
[Cazador] Fingir muerte

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4388]
ID: 5384
El problema es que al usar fingir muerte y anular el efecto esta regenerando el enfoque por completo.

**Comment by Sagittariu5** [comment]
El problema tambien es que antes te lo quitaba todo :p dejando al cazador totalmente vulnerable

**Comment by Albertiktik** [comment]
Lo normal seria eso, que se te quitara todo al fingir muerte. Si la usas sin estar en combate va bien, pero cuando estas en combate te rellena el enfoque al 100%

**Comment by Sagittariu5** [comment]
Prueba:
https://www.youtube.com/watch?v=_Csv-0VZWDo

-Al minuto 5 con 50 segundos (va en camara lenta) puedes ver como trabaja en verdad Fingir muerte. no te quita ni te da el enfoque, de hecho no se porque la habilidad esta modificando los valores de este, el enfoque se debe mantener tal y cual esta.

**Comment by DepredatorSexual43** [comment]
Exacto, esto se ve afectado por la rama MM que reinicia instantaneamente todos los skills haciendo que sea doble el efecto de 100% enfoque.

Solucionarlo urgente que esto afecta mucho, tanto al hunter como a las demas clases y ambitos pvp, pve.

**Comment by efectokoleos** [comment]
arreglado
