### ISSUE TITLE
[Tier 12] Paladin sagrado

### ISSUE THREAD

**Issue by Albertiktik** [RoDNet/Bugtracker-Infinium-4.3.4#4389]
Enlace:
http://es.wowhead.com/item=71091/coraza-de-inmolacion

Descripción:
(2) Conjunto : Sanar con Choque Sagrado tiene un 40% de probabilidad de otorgarte un 6% de tu maná de base.
(4) Conjunto : Tus hechizos Destello de Luz y Luz Sagrada también sanan un 10% de la cantidad sanada a un objetivo herido en un radio de 15 m.

Problema: 
[Conjunto de 2 piezas] Cuando lanzo Choque sagrado para sanar me da 6 de mana.
[Conjunto de 4 piezas] Creo que tampoco sana a nadie pero no estoy seguro del todo.

Observaciones: 
Creo que tendria que ser mas, mi mana base siendo tauren sin ningun tipo de buff ni objeto es 24.834. Entonces el 6% seria 1.490'04 en vez del 6 que esta dando actualmente.

**Comment by redneo** [comment]
La parte de dos piezas arreglado cuando se compile el server 

la de 4 piezas... por favor asegurate de que va mal :P

**Comment by Albertiktik** [comment]
Ahora si que funciona el conjunto de 2 piezas muchas gracias.

El que no funciona es el conjunto de 4, acabo de probarlo y no cura a nadie cercano estando herido o sin estarlo.
