### ISSUE TITLE
[Bug Túmulo de Ban'ethil]

### ISSUE THREAD

**Issue by Kagome** [RoDNet/Bugtracker-Infinium-4.3.4#439]
Al hacer las misiones, para volver a conseguir mi tigre que al parecer cometieron un error y me borraron la Exaltividad de Darnassus,pues de nuevo tengo que recuperar la y me veo que al sitio donde debo entrar, anda Cerrado sin poder abrir.Hay tengo que entrar.Y no, no se abre con ninguna llave por que debería estar abierto.
![wowscrnshot_071313_195526](https://f.cloud.github.com/assets/4942077/793690/dda46b32-ec2d-11e2-85a4-04238cb243a7.jpg)
![wowscrnshot_071313_195532](https://f.cloud.github.com/assets/4942077/793692/f76de660-ec2d-11e2-8642-f8b5ac9f5824.jpg)

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
