### ISSUE TITLE
[Profesion-Ingenieria] Base de tejido flexible

### ISSUE THREAD

**Issue by Sagittariu5** [RoDNet/Bugtracker-Infinium-4.3.4#4390]
Id: http://es.wowhead.com/spell=55002/base-de-tejido-flexible

Problema: Esta quitando el enchant anterior de la capa,
Dinamica: El paracaidas que salta a usar el encantamiento debe desaparecer cuando el usuario vuelve a tocar el suelo

**Comment by Wiinter** [comment]
Diria que te lo tiene que quitar el enchant de capa, porque se considera enchant tambien la capa. Conozco a varios qe lo qe hacen es salir de combate se cambian la capa y se la tirar y vuelven a cambiar por la encantada.

**Comment by Sagittariu5** [comment]
Ahi tienes respuesta para esto Win #3207

**Comment by Wiinter** [comment]
Ostras! que interesante. Entonces los encantamientos en las manos tambien debería estar con el de encantamiento. Podrias añadirlos a tu reporte? Te linkeo algunos, 
http://es.wowhead.com/spell=82175
http://es.wowhead.com/spell=82180
http://es.wowhead.com/spell=82175
http://es.wowhead.com/spell=82177

**Comment by Sagittariu5** [comment]
No, el encantamiento de manos tiene una mecanica muy diferente al de la base, que es un support no admitidios en arenas y RBG's los enchants de manos por parte de la profesion de ingenieria sin embargo aportan estadisticas y por lo que vendrian a reemplazar al encantamiento normal.

De hecho he sabido de players con enchants de sastreria y la base anadida a esto asi es como jugaba swifty/cobrak xd cuando tenian esas prof.

**Comment by Wiinter** [comment]
Segun el enlace qe pusiste del foro del oficial, ponian que tanto la capa y las manos puede llevar los enchants, y si piensas tiene todo el sentido. Porque si en las manos no te puedes poner el enchant y los muelles de sinapsis no puedes obtener el bonus de profesiones.

**Comment by Sagittariu5** [comment]
El realidad mi intencion mas que nada era que  la dinamica de la capa funcionara xD

**Comment by Wiinter** [comment]
Si funciona la capa, que tambien funcionen las manos, que es lo mismo xD

**Comment by sakuranobushi** [comment]
El error ha sido corregido y debería verse pronto reflejado en los servidores de juego.
