### ISSUE TITLE
bandas: Sagrario obsidiana 25

### ISSUE THREAD

**Issue by nayan87** [RoDNet/Bugtracker-Infinium-4.3.4#4391]
Sartharion debe soltar el draco crepuscular 100% si se le mata a a el solo sin matar al resto de mini bosses de la instance. Actualmente no lo está soltando.

http://es.wowhead.com/item=43954/riendas-del-draco-crepuscular

Muchas gracias de antemano¡

**Comment by redneo** [comment]
Arreglado
