### ISSUE TITLE
[Druida] Champiñon salvaje

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#4393]
http://es.wowhead.com/spell=88747

Un druida puede poner un maximo de 3 champiñones, el problema se encuentra en si hay otro druida poniendo champiñones cerca. Si hay 2 druida solo pueden poner 1 champiñon cada uno, si uno intenta poner otro champiñon te quita el anterior que has puesto, cuando realmente debería dejar poner 3 cada uno.

**Comment by sakuranobushi** [comment]
El error ha sido corregido y debería verse pronto reflejado en los servidores de juego.
