### ISSUE TITLE
[BUG MISIÓN] ¡Enlaza algunas rayas de éter!

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#4394]
Misión: http://es.wowhead.com/quest=11065/enlaza-algunas-rayas-de-eter

Problema: Al usar http://es.wowhead.com/item=32698 sobre las rayas no cuentan para completar la misión.

**Comment by Wiinter** [comment]
Cuando lo hice, si mal no recuerdo tenias qe bajarle la vida hasta que digan, la raya de eter está enfurecida y huye o algo asi, ahi usas el objeto y funciona, almenos antes lo hacía. La vida es alrededor de un 20%

**Comment by qulki** [comment]
Lo he hecho así, bajándole la vida hasta el 20% y saliendo el mensaje de "la raya de éter está lista para ser capturada", pero entonces, al capturarla, no me cuentan para la misión.

**Comment by redneo** [comment]
Arreglada.
