### ISSUE TITLE
[Quest] La estrategia de Navarax

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#4395]
Mision: La estrategia de Navarax
NPC: [Archidruida Navarax](http://es.wowhead.com/npc=47842)
Se transforma en : [Xaravan](http://www.wowhead.com/npc=48160/xaravan)
Link: [La estrategia de Navarax](http://es.wowhead.com/quest=28264/la-estrategia-de-navarax)
Fallo: Al hablar con el archidruida Navarax no hace nada cuando debería transformarse en un Sátiro y atacarte una vez lo matas se te completa la quest.

**Comment by redneo** [comment]
arreglado 100% blizlike
