### ISSUE TITLE
Tranvía subterraneo (Ventormenta)

### ISSUE THREAD

**Issue by kikete17** [RoDNet/Bugtracker-Infinium-4.3.4#4396]
Problema: uno de los vagones se ha soltado y desaparece y aparece cada cierto tiempo y si lo coges te deja en mitad de la vía.Un saludo

**Comment by AhriLove** [comment]
Habrá que avisar a Renfe pero como están de puente... xD
Fuera bromas, ¿donde está ese subterraneo? núnca lo he visto ni sabía de su existencia.

**Comment by kikete17** [comment]
xd está en el distrito de los enanos de ventormenta cerca del edificio del instructor de cazadores

**Comment by redneo** [comment]
fixed
