### ISSUE TITLE
Beneath the surface

### ISSUE THREAD

**Issue by saipulido** [RoDNet/Bugtracker-Infinium-4.3.4#4397]
https://www.youtube.com/watch?v=z80PQhWneKg
https://www.youtube.com/watch?v=ySJIHRhY22E

El ruby crystal cluster no aparece ni en el sitio especificado, ni en esa cueva. Por favor, ayuda, esa reputacion (Tharazane) es obligatoria y es necesario hacer la mayor cantidad posible de misiones. Gracias

PD: Esos link son para que vean como se hace la mision.

**Comment by redneo** [comment]
cuando caiga el server arreglado, creo....
