### ISSUE TITLE
[Mago] Piroexplosión.

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#44]
El hechizo Piroexplosión, en mi caso, marca un daño base de 11.522, pero no consigo ni siquiera llegar a esta cifra. Y esto en las Piroexplosiones resultantes del talento "Buena racha" se acetúa aún más, pues no superan los 3k y poco, cuando el daño base del hechizo es el citado arriba.

Imagen de una Piroexplosión casteada contra un "Dummie" de nivel 85 de Orgrimmar. (Se puede ver como el muñeco recibe el "dot" que deja Piroexplosión, eso confirma que ha sido golpeado con ese hechizo y no otro).
![wowscrnshot_070413_055639](https://f.cloud.github.com/assets/3687462/747416/2a462cf0-e45e-11e2-81bf-222d6d6908aa.jpg)

Imagen de una Piroexplosión resultante del talento "Buena racha". (Se puede apreciar el mismo "dot" que en la imagen anterior que confirma el hechizo).
![wowscrnshot_070413_060032](https://f.cloud.github.com/assets/3687462/747421/73bbfd2e-e45e-11e2-935b-959decf41e34.jpg)

Gracias de antemano!

Fionder

**Comment by Alfonn** [comment]
Apoyo a Fionder, estoy testeando al mago fuego y me ocurre lo mismo , dejo imagen del reccount.
![image](https://f.cloud.github.com/assets/3854953/748341/d0cc636e-e486-11e2-936d-a51b0b2a7a34.png)

Saludos y Buen Juego !

**Comment by ghost** [comment]
- Intelecto arcano: tampoco funciona, no añade SP y debería sumar un 6%. 
- Impacto: No propaga los DoTs en los enemigos cercanos (fundamental para el daño).
- Talento Absorción de mago: Estoy en fire desde que creé el pj, nunca he usado la rama arcana y, sin embargo, al absorber daño con mi resguardo de mago, me salta Absorción de encantador, que es un talento de la rama arcana...
- Polimorfia: No funciona simplemente. No elimina los DoTs del objetivo llevando el glifo de polimorfia, lo cual no es problema por ahora ya que polimorfia NO se rompe con el daño...puedes pegarle lo que quieras y con lo que quieras que no se va...y sigue manteniendo la regeneración de vida aumentada.
- Funcionalidades: 
- Cuando el mago fuego hace un crítico, aparece un efecto sobre él (sobre el mismo pj, mago fuego) como si le afectase el daño, no recibe daño pero sí la animación de recibirlo. 
- Al hacer críticos, en ocasiones, saltan varias piroexplosiones a la vez (que se van solapando obviamente, por lo que sólo podrás usar Buena racha una vez). 
- Al hacer críticos sobre un objetivo, hay veces que se hace también un crítico en otro objetivo cercano (sin usar impacto ni bomba viva), lo que nos lleva al punto anterior de múltiples piroexplosiones que, como meten menos que una lanza de hielo, como si saltan 50...

Sinceramente, no sé donde veis el 99% de funcionalidad...más bien parece que no llega al 10% en el caso de mago fuego.

Lo pongo aquí en vez de en otro issue porque como tenga que esperar a que los lean todos...xD

**Comment by Alfonn** [comment]
Añado enlace a wowhead e ID : http://es.wowhead.com/spell=1459  (Aunque sea del MoP) 

ID : [spell=1459]
Adjunto datos :  

Impacto : http://es.wowhead.com/spell=118271
Resguardo de encantador : http://es.wowhead.com/spell=1463

PD: Buen reporte Asman ^^.

**Comment by Dekadencee** [comment]
La maestría debería estar fixeada

**Comment by Alfonn** [comment]
Si , @Dekadencee la maestría ya está fixeada.Pero lo demás sigue mal.

**Comment by searum** [comment]
bueno cierro esto porque como os liais a meter 20 reportes en un issue y encima nadie contesta en el wow... si sigue mal lo reportais en 1 issue por bug.

**Comment by ghost** [comment]
@searum Hecho.
