### ISSUE TITLE
[Bug Area 52] Los vendedores...¡No venden!¡Qué tacaños!

### ISSUE THREAD

**Issue by Kagome** [RoDNet/Bugtracker-Infinium-4.3.4#440]
Cuándo voy al Area 52,para ver los equipos de Tela...Me quedo pasmada cuando veo que 3 vendedores...¡¡¡¡No venden nada!!!! ¿Qué pasa no fueron al supermercado?..o que ._. .
![wowscrnshot_071313_211405](https://f.cloud.github.com/assets/4942077/793701/555a3c56-ec2e-11e2-9447-c05027859df1.jpg)
![wowscrnshot_071313_211517](https://f.cloud.github.com/assets/4942077/793702/5580f0da-ec2e-11e2-9237-472f35fa93a4.jpg)
![wowscrnshot_071313_211519](https://f.cloud.github.com/assets/4942077/793703/55a7b986-ec2e-11e2-9c15-efca4611c1ee.jpg)

**Comment by crowel** [comment]
Los comprobe y estan vendiendo correctamente.
Un saludo.
