### ISSUE TITLE
Forma de Lechúsico Lunar

### ISSUE THREAD

**Issue by DepredatorSexual43** [RoDNet/Bugtracker-Infinium-4.3.4#4400]
Ahora Forma de lechúcico reduce el daño un 15% en vez de aumentar la armadura. Además, ahora cambiar de forma, activando o desactivándola, rompe las raíces. Hay que tener en cuenta que esto no se indica en la descripción.

Fuente: http://eu.battle.net/wow/es/game/patch-notes/4-0-6

Actualmente esta aumentando la armadura y no el daño total que reduce.

Salu2

**Comment by Overseer101** [comment]
![wowscrnshot_120814_115412](https://cloud.githubusercontent.com/assets/3658679/5338139/f739927a-7ed0-11e4-8855-170e7e95adff.jpg)
![wowscrnshot_120814_115442](https://cloud.githubusercontent.com/assets/3658679/5338144/02b78a62-7ed1-11e4-8dd2-1d589bff5c75.jpg)

No se de donde te sacas lo de que te aumenta la armadura, ya ves que no lo hace.
