### ISSUE TITLE
Fuego Estelar

### ISSUE THREAD

**Issue by DepredatorSexual43** [RoDNet/Bugtracker-Infinium-4.3.4#4401]
El daño de Fuego estelar esta muy por debajo de lo que de verdad deberia ser.

B.Druid Full cata, Normal; 5k Critico; 9k Siendo que tiene un casteo de 2s yendo full celeridad...

El daño deberia ser equivalente a una pyro del F.mage (11k - 15k).

Creo que no me olvido nada, igualmente si alguien tiene algo mas que añadir/aportar bienvenido sea.

Salu2

**Comment by Overseer101** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/4402
