### ISSUE TITLE
Enjambre de Insectos & Fuego lunar

### ISSUE THREAD

**Issue by DepredatorSexual43** [RoDNet/Bugtracker-Infinium-4.3.4#4402]
El daño de Fuego lunar y enjambre de insectos esta muy por debajo de lo que de verdad debería ser.

B. Druid full cata: Fuego lunar; 900 normal / 1430 critico
                            Enjambre de insectos; 874 / 1390 critico

Tanto Fuego lunar como Enjambre yendo full tienen tics cada 2s aprox...

El B. Druid tiene en su rotación 4 botones: Fuego estelar (actualmente sin daño y con un casteo realmente largo), Lluvia de estrellas, Fuego lunar y Enjambre de insectos (Tienen el daño del parche 4.0.6 actualmente).

De mas esta decir que los estados (Lunar y solar) no aumentan el daño de los skills y la celeridad reduce la duracion de los dot's (Lunar y Enjambre) en ves de aumentar el numero de tics sobre el tiempo normal. Esto también sucede con otras clases como mago, priest, etc.

Creo que no me olvido nada, igualmente si alguien tiene algo mas que añadir/aportar bienvenido sea.

Salu2

**Comment by Kiritoo** [comment]
Bien me gusta tu reporte,  pero necesito que adjuntes pruebas de porque esta bajo, no decir que lo está y listo. Otra cosa ¿porqué das por seguro que el daño es como el parche 4.0.6?.
Saludos.

**Comment by Overseer101** [comment]
Me gustaria saber como lo has probado, primero, los ticks de los 2 dots con
un equipo 333,(concretamente el de profesion del parche 4.06), en critico
llegan a 3k o lo sobrepasan sobradamente, y sin ni siquiera usar la forma de pollo....
![wowscrnshot_120814_113054](https://cloud.githubusercontent.com/assets/3658679/5337872/fee61bb8-7ecd-11e4-870e-5c47991d216a.jpg)
![wowscrnshot_120814_113059](https://cloud.githubusercontent.com/assets/3658679/5337873/0195de7a-7ece-11e4-96b7-32021b88af98.jpg)
![wowscrnshot_120814_113111](https://cloud.githubusercontent.com/assets/3658679/5337875/03c1298e-7ece-11e4-8ebb-b061a408156e.jpg)
![wowscrnshot_120814_113125](https://cloud.githubusercontent.com/assets/3658679/5337876/054a2904-7ece-11e4-94fe-157be6e6fd19.jpg).

Segundo: Fuego estelar: dices que sin daño....y con un casteo tremendamente largo, pues no se tu, pero el casteo de esa spell es de 2.5s de base, y en cuanto al daño....
![wowscrnshot_120814_113530](https://cloud.githubusercontent.com/assets/3658679/5337900/6ba17c34-7ece-11e4-8b13-72d84792c207.jpg)
![wowscrnshot_120814_113538](https://cloud.githubusercontent.com/assets/3658679/5337902/6ca9ea94-7ece-11e4-9e73-633c19a73c62.jpg)...

Y en cuanto al tema de que los eclipses no aumentan el daño....
![wowscrnshot_120814_113854](https://cloud.githubusercontent.com/assets/3658679/5337938/d2f596d6-7ece-11e4-803f-9a2ec03d4717.jpg), fuego estelar sin eclipse lunar...
![wowscrnshot_120814_113947](https://cloud.githubusercontent.com/assets/3658679/5337954/f019384e-7ece-11e4-905a-33b28563a361.jpg), fuego estelar CON eclipse lunar,(en mi caso 19% de daño aumentado)

No te pongo el eclipse solar, por que funciona exactamente igual que el lunar...

La lluvia de estrellas:
![wowscrnshot_120814_114225](https://cloud.githubusercontent.com/assets/3658679/5337999/6c98de4c-7ecf-11e4-916c-2a488a23996b.jpg), creo que mas claro agua, con equipo 333 y un abalorio del mismo nivel activado, casi 6k critico por estrella, y por cierto, en eclipse lunar, le aumenta el daño.

**Comment by Monleon** [comment]
La celeridad tiene fallos, pero que no aumente el número de ticks (una vez se llegue a X cap) no es uno de ellos, eso funciona. Más que nada, porque probado con anillos de 10k de haste y estoy teniendo ticks cada segundo y poco, y además estoy ganando ticks extra.

Luego, el daño en estado de eclipse sí que potencia las spells de daño arcano o de naturaleza, dependiendo del tipo de eclipse

**Comment by Monleon** [comment]
Un consejo, enfoca tus reportes, no menciones varios aspectos a la vez (y mas algunos que funcionan). Se conciso.

Ejemplo: spell X, id Y. Formula Z
