### ISSUE TITLE
Profesiones, beneficios únicos.

### ISSUE THREAD

**Issue by DepredatorSexual43** [RoDNet/Bugtracker-Infinium-4.3.4#4403]
Hace poco he leido por ahy 1 post que decia que se acumulaba el enchant de paracaidas (ingenieria) con el bordado (Sastreria) y que estando en efecto 1 cancelaba el otro, etc.

Aqui el post anterior: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/4390
Aqui la ID del enchant que "No" deberia acumularse... 55002

Quería añadir unas fuentes y mas información porque esto no es así e incluso un gm lo aprobó y cerro el topic...

Cada profesion tiene beneficios únicos no acumulables. Puedo tener 2 (paracaidas, si fuera ingeniero y bordado si fuera sastre pero jamás los dos juntos). En cambio si podría tener el enchant de ingenieria; cinto (Nitro) y el bordado de sastreria en capa porque no se estan sumando uno ensima del otro.

¡Hay mas! Si uso el beneficio de alguna prof, a la hora de borrar esta profesión que tenia este beneficio dejara de funcionar y se removera instantaneamente en cuando le aplique algun otro beneficio/enchant de alguna otra profesión.

Aquí una guía! =D

http://eu.battle.net/wow/es/forum/topic/1710175206

Si me olvido de algo o quieren añadir algo mas bienvenidos sea.

Salu2

Actualizado 08/12 09:44hs

**Comment by ghost** [comment]
Esa guía, segun las etiquetas de abajo, es del parche 3.3.5a :S
Saludos!

**Comment by DepredatorSexual43** [comment]
Arreglado y actualizado, gracias !

Salu2

**Comment by redneo** [comment]
Creo que sí que ahora está bien, los ingenieros pueden tener dos enchants en sus capas, o guantes. Es la ventaja unica del ingeniero, como las gemas de los joyeros, los enchants de anillo de los encantadores, los encantamientos de hombro de inscripcion, etc etc.

Pero puedo estar equivocado.

**Comment by DepredatorSexual43** [comment]
Justamente lo que quería explicar es que cada encantamiendo es único. Ninguna profesión o "Ventaja única del ingeniero" como mencionas antes puede darte "Dos enchant en capa o guantes"

Otra cosa, los encantamientos de profesion como el de inscripcion o ingenieria no son los mismos que las gemas mejoradas del joyero. Una cosa es un encantamiento unico de profesion y otra cosa son gemas mejoradas de joyeria.

Espero haberte ayudado !

Salu2

**Comment by Sagittariu5** [comment]
That logic xD

**Comment by ghost** [comment]
Yo entiendo tu punto, pero muestranos donde dice que no son acumulables.
Saludos.

**Comment by DepredatorSexual43** [comment]
Puedes pasarte por el link que e referido anteriormente, ahí lo menciona...

**Comment by ghost** [comment]
Me leí la guía 2 o 3 veces buscando que respalde tu argumento, de arriba a abajo, pero ningún parrafo hace mención específica sobre los bordados de sastrería y el paracaidas de ingeniería.
Saludos.

**Comment by DepredatorSexual43** [comment]
Buscare otra guia mas especifica ya que esta es muy basica... Pero el concepto es basico, tu llevas 2 enchant en un arma? si se acumulan los enchant de ingenieria con sastreria, ¿Porque en manos no?
Me estoy tirando aqui lo mas grande y parece que nadie lo sabe o no se entiende.

Voy a revisar las notas de los parches respecto a esto pero vamos... tengo para rato y tampoco es algo que me interese, por mi puede ir todo el server con 5 enchant en cada mano... Lo unico que me molesta es que de los 200 players que tiene el server (incluyendo gm's) ninguno sepa esto.

Mañana voy a abrir 1 topic diciendo que las botas nitro ahora van en la cabeza y se acumulan con el enchant de inscripción... y lo implementan...

**Comment by ghost** [comment]
![meh ro7098](https://cloud.githubusercontent.com/assets/4582987/5384122/dc032306-8095-11e4-8fff-871ebbf08cc6.jpg)

**Comment by Monleon** [comment]
Si te refieres a los guantes y a muelles de sinapsis,  los ingenieros pueden acumular a su vez el encantamiento estándar de guantes.

Lo mismo que encantamiento de capa más paracaídas

Es un cambio de la expansión
