### ISSUE TITLE
[Misión] Ciudad de Gilneas Retrasando lo inevitable

### ISSUE THREAD

**Issue by AldooSuarez** [RoDNet/Bugtracker-Infinium-4.3.4#4404]
en esta mision cuando subo al murcielago llega a la altura del rio y el murcielago me deja caaer sin alguna razon

**Comment by maikdjhoker17** [comment]
a mi tambien me deja caer, y lo peor no hay los enemigos de la quest, como lo solucionaste??

**Comment by redneo** [comment]
arreglado
