### ISSUE TITLE
[NPC] Tablón de mando del Jefe de Guerra  de la ciudad de lunargenta

### ISSUE THREAD

**Issue by doomdays** [RoDNet/Bugtracker-Infinium-4.3.4#4406]
El Tablón que inicia misiones en la zona no esta, es el único que empresa a la cadena la cadena de misiones en Tierras fantasmas y sin ella no se podrá hacer todas las de zona.

Foto:
![wowscrnshot_120814_103101](https://cloud.githubusercontent.com/assets/9273574/5357175/4458c29e-7f83-11e4-9d33-16fbfe033cfc.jpg)

Link del tablón: http://es.wowhead.com/object=207325
Link de la cadena de misiones de Tierras Fantasma: http://es.wowhead.com/quest=28560

Pd: no sabia si lo subí en la categoría correcta [NPC] o si debía ser en Errores internos o otra Salu2.

**Comment by Monleon** [comment]
Añadido
