### ISSUE TITLE
estoy muerto, ya no puedo volver a la zona donde esta mi cadaver con las misiones de inicio huargen y no hay  angel para resucitar

### ISSUE THREAD

**Issue by maikdjhoker17** [RoDNet/Bugtracker-Infinium-4.3.4#4408]
un saludo en primer lugar, pues el problema es que mori y mi cadaver esta en una zona que ya no puedo volver, es en las misiones de inicio de los huargen y no me aparece el angel de la muerte, les pido porfavor que me ayuden sin nada mas que decir me despido deseandoles exitos en sus roles que desempeñan

**Comment by redneo** [comment]
lo mas importante, el nombre del pj?
