### ISSUE TITLE
[NPC] Alamuerte Cobarde en Tierras Inhospitas

### ISSUE THREAD

**Issue by misteriosoccmc** [RoDNet/Bugtracker-Infinium-4.3.4#441]
![wowscrnshot_071313_220338](https://f.cloud.github.com/assets/3792252/793717/0a9874ae-ec32-11e2-9bbf-9d4bacaf49ca.jpg)

Se encuentra abajo del primer punto de vuelo de la alianza viniendo desde Loch Modan

**Comment by DatJetto** [comment]
Ese npc es para una quest xD

**Comment by Kagome** [comment]
Tiene una postura muy Sensual......No creen? xDDD

**Comment by Kiritoo** [comment]
Este npc ya no está en la phase 1, ya que es para una misión, lo acabo de comprobar y ya no se ve.
Cierro.
