### ISSUE TITLE
[Misión] Retrasando lo inevitable

### ISSUE THREAD

**Issue by Huargen** [RoDNet/Bugtracker-Infinium-4.3.4#4412]
Bueno el murcielago primero que todo deja caer de la nada. Pero no están o no aparecen los NPC's de la misión y así es imposible terminar la cadena de misiones de los Huargen para salir de esa ciudad sin necesidad de summon. 

http://es.wowhead.com/quest=24920/retrasando-lo-inevitable

**Comment by redneo** [comment]
arreglado
