### ISSUE TITLE
[Paladin] Colera sagrada 

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4414]
ID: 2812
Problema, segun mi descripción debería pegar 5213 de daño sagrado, sin embargo pega 1922

**Comment by Overseer101** [comment]
Si, ciertamente pega de menos, y el sello de verdad se ha ido de madre con el aumento de daño, pero te estas colando, ese efecto de daño sagrado extra, solo afecta a sentencia, no afecta a ningun otro spell de daño sagrado del paladin.

**Comment by Drogoth2** [comment]
Vale si cierto, lo he leido mal corrigo jeje

**Comment by Overseer101** [comment]
Jajaja, no hay problema, echale las culpas a blizzard y sus tooltips perfectamente redactadas y explicadas,(sarcasmo, cof cof cof)

**Comment by Drogoth2** [comment]
Si... ya me ha pasado tambien con las putas descripciones del cazador XD

**Comment by efectokoleos** [comment]
arreglado
