### ISSUE TITLE
[Cazador] Fingir muerte

### ISSUE THREAD

**Issue by drog** [RoDNet/Bugtracker-Infinium-4.3.4#4415]
ID: [5384](http://es.wowhead.com/spell=5384/fingir-muerte)
Acabo de leer el changelog del 2014/12/12 (Hoy)
 `Spells/Cazador: Fingir muerte ya no quitará ni dará enfoque, y ademas al usarlo se perderá el target de los enemigos sobre ti.`

Esta quitando enfoque y peor aun, no lo esta dando.

Eso.Slds.

PD: borre cache antes y despues de comprobar el problema

**Comment by Monleon** [comment]
Para que un cambio se haga efectivo, se debe primero compilar y segundo reiniciar servidor.

**Comment by drog** [comment]
Ups, pensé que ya se habían aplicado los cambios D:
