### ISSUE TITLE
[Druida] Feral: Efecto "Furia del tigre" junto con "Rabia"

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4417]
Id Furia del tigre: 5217
Id Rabia: 50334

Según la descripción del talento mientras "Rabia" está activo no se puede usar "Furia del tigre". Si se usa "Rabia" y después "Furia del tigre" funciona bien, no se puede usar. 

Sin embargo, si se usa primero "Furia del tigre" se puede usar "Rabia" justo después, cosa que no debería pasar ya que los dos efectos no pueden convivir a la vez. O se activa uno o se activa otro, nunca a la vez. 

Un saludo y gracias

**Comment by Kiritoo** [comment]
La propia descripción te lo dice:
Mientras "Rabia" está activo no se puede usar "Furia del tigre".

En ningún lado pone que no se pueda usar "Rabia" mientras "Furia del tigre" esta activo.
Si encuentras prueba de ello añadelas ya que este argumento no sirve.
Saludos.
