### ISSUE TITLE
Glifo de Poder arcano

### ISSUE THREAD

**Issue by ExodusDK** [RoDNet/Bugtracker-Infinium-4.3.4#4418]
https://wow.freakz.ro/spells.php?spell=56381&name=glyph-of-arcane-power el glifo no cumple su función,no reduce el cooldown del escudo de maná,traslación ni de las copias

**Comment by Overseer101** [comment]
Sabes que a lo que se refiere ese glifo, es al GCD, es decir al global
cooldown, o para los plebeyos, cuando usas una spell, te deja todas las
demas inutilizables durante aprox 1,5s, ese glifo lo que hace es dejarlo a
0 segun que spells, de tal forma que puedan ser usadas en macros, por
ponerte un ejemplo.....

2014-12-13 20:29 GMT+01:00 ExodusDK notifications@github.com:

**Comment by Monleon** [comment]
Alma de cántaro, pero como va a hacer tantas cosas un glifo sublime?
Este glifo funciona, reduce el GCD de esas spells a 0 mientras Poder Arcano está activo
