### ISSUE TITLE
[Mision] Guerra Total (vuelto a crear)

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#442]
En respuesta A: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/334
La mision http://es.wowhead.com/quest=28872/guerra-total 

Ahora puedo cliquear los barriles y me sale ''apertura'' pero cuando acaba no me cuenta el barril.

![wowscrnshot_071313_222816](https://f.cloud.github.com/assets/4895839/793744/beebee06-ec35-11e2-85bb-2b3d74e68444.jpg)

PD: Tampoco marca la zona en el mapa del lugar de los barriles

**Comment by redneo** [comment]
limpiaste la carpeta cache?

**Comment by SherBlader** [comment]
si redneo, la limpie, pero nada

**Comment by Kiritoo** [comment]
Fix
