### ISSUE TITLE
Misiones - Corona de Hielo - La historia hasta ahora...

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4423]
Nombre: La hisotira hasta ahora... Link: http://es.wowhead.com/quest=12807
Problema: el npc (http://es.wowhead.com/npc=29344) debe simplemente contarte una historia pero no tiene diálogo para escucharla y tampoco empieza a hablar por sí solo luego de aceptar la busqueda.

**Comment by redneo** [comment]
Arreglada.
