### ISSUE TITLE
Misiones - Corona de Hielo - Purgar con fuego

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4425]
Nombre: Purgar con fuego
Link: http://es.wowhead.com/quest=13211
Problema: debes quemar los cuerpos regados por la zona con una antorcha. No cuenta al quemar los cuerpos con la antorcha que te dan, el item se puede usar los cuerpos estan puestos por el terreno pero no pasa nada cuando usas el item en ellos, teniéndolos o no seleccionados

**Comment by redneo** [comment]
Arreglada.
