### ISSUE TITLE
Misiones - Corona de Hielo - Una visita al doctor

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4426]
Nombre: Una visita al doctor
Link: http://es.wowhead.com/quest=13152
Problema: si bien Parches se puede liberar y cuenta para la misión, una vez liberado aparece el doctor Sabnok (http://es.wowhead.com/npc=30992), aparece como objetivo amistoso mientras baja la rampa hasta donde esta Parches, el problema es que queda como amistoso y Parches tampoco lo ataca como para causarle daño.

**Comment by redneo** [comment]
arreglada
