### ISSUE TITLE
Misiones - Laderas de trabalomas - Cosecha Gloriosa

### ISSUE THREAD

**Issue by Valkyriex** [RoDNet/Bugtracker-Infinium-4.3.4#4427]
Hola a todos,

Misión: http://es.wowhead.com/quest=28114/cosecha-gloriosa

Problema: los osos infectados deberían dar loot http://es.wowhead.com/item=63029 pero no lo dan y tambien deberian atacar pero no atacan.

**Comment by redneo** [comment]
Arreglada.
