### ISSUE TITLE
Copia del Mago

### ISSUE THREAD

**Issue by Alduinor** [RoDNet/Bugtracker-Infinium-4.3.4#4428]
Buenas, la copia del mago sigue cortando el casteo de hechizos cuando no debería hacerlo. 
Gracias de antemano!

**Comment by Overseer101** [comment]
Y los datos, las Ids y...bueno...esas cosas que la gente necesita para arreglarlo?

**Comment by efectokoleos** [comment]
lo he probado durante un rato y no me ha cortado el casteo..

**Comment by nayan87** [comment]
no solo corta el casteo si no que además se queda estática a no ser que estes pegando al boss o al pull a melee, además reflejo exacto le está ocurriendo que muchas veces se quedan estáticas igual. os paso el enlace de reflejo. Efectokoleos si lees esto antes de las 13h horas wispeame que estoy con el mago y te enseño como me corta el casteo, ya que lo llevo macreado y ahi si se nota perfectamente. Un saludo y muchas gracias por vuestro tiempo.

http://es.wowhead.com/spell=55342/reflejo-exacto

Aquí el enlace de bonus del T12.

http://es.wowhead.com/itemset=1007

**Comment by efectokoleos** [comment]
bueno lo cierro porke ya lo comente contigo y me dijiste k funcionaba xd
