### ISSUE TITLE
Guardián de los antiguos reyes Paladín(Reprensión)

### ISSUE THREAD

**Issue by kikete17** [RoDNet/Bugtracker-Infinium-4.3.4#4430]
Problema:solo esta generando cargas los golpes del guardián,lo cual hace que se quede en 12-14 cargas de poder antiguo y perdamos mucho daño,esto no debería ser así ya que todos los ataques del paladín también deberían subir cargas hasta un máximo de 20.
ID:86150

**Comment by efectokoleos** [comment]
arreglado en el proximo reinicio
