### ISSUE TITLE
[Hechizos/Talentos][DK] Toque Helado

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4431]
Buenas.
• Nombre: Toque Helado
• Enlace: http://es.wowhead.com/spell=45477
• Problema: Está haciendo mucho menos daño.
Desde ya muchas gracias y hasta luego.

**Comment by Monleon** [comment]
Mucho menos daño es 200 menos con 11k de ap. Cuando antes estaba pegando de más y no estaba reportado

**Comment by ghost** [comment]
Sinceramente, si estaba pegando demás y no lo reporté fue porque no me di cuenta y no estar al tanto de la fórmulas y no por mala leche. La próxima prometo estar mas atento y ya.
Disculpá las molestias y gracias.

**Comment by Monleon** [comment]
Esto ya estará ahora con el daño correcto.
