### ISSUE TITLE
[Hechizos/Talentos][DK] Hervor de sangre

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4433]
Buenas.
• Nombre: Hervor de sangre
• Enlace: http://es.wowhead.com/spell=50842
• Problema: Hace mucho menos que el daño indicado.
Desde ya muchas gracias y hasta luego.

**Comment by efectokoleos** [comment]
no te fies del tooltip ya k muchas veces no pegas lo que indica, sin embargo la formula esta correcta 356 + 0.08 \* ap (antes estaba subido incluso)
