### ISSUE TITLE
[Mazmorras/Bandas][Tierras del Fuego] Mayordomo Corzocelada 10 HC

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4435]
Buenas.
• Nombre: Mayordomo Corzocelada 
• Enlace: http://es.wowhead.com/npc=52571/
• Problema: La barra de Concentración (http://es.wowhead.com/spell=98229) no funciona o no aparece
Desde ya muchas gracias y hasta luego.

**Comment by efectokoleos** [comment]
estamos en ello ;)

**Comment by ghost** [comment]
OK muchas gracias, no hay apuro.
Ayer fuimos (23 de diciembre) y la barra aparecia, pero era sólo visual y no daba el beneficio correspondiente.
Muchisimas gracias.

**Comment by efectokoleos** [comment]
si eso es k estamos tocando poco a poco xd

**Comment by F4NT4SM4** [comment]
otro dato los guerreros no generamos ira en este boss solo pasa en heroica

**Comment by redneo** [comment]
Arreglado, con algunos fallos como:

La ira del guerrero deja de funcionar, visualmente no se resetea la barra.
