### ISSUE TITLE
Fallos tanaris

### ISSUE THREAD

**Issue by JavierMateosBailen** [RoDNet/Bugtracker-Infinium-4.3.4#4438]
Reportar que las misiones que dan en Gadgetzan relacionadas con un robot y seleccionar 10 npc esta bugeada, funcionar funciona pero solo tienes que elegir un npc y darle al robot y te cuenta como 1 y puedes darle al mismo cada vez que termine el cd del robot y te sigue contando, no creo que deba funcionar así la misión.

Otro fallo es en Tanaris en Campo de Manantial hay una parte de esa zona en la que se deben eliminar a unos gigantes y recoger unas cajas de suministros, las misiones funcionan bien pero el entorno no, a pesar de haber un nivel de agua bastante bajo lo suficiente para poder ir andando o en montura los jugadores y los npc hacen la animación de que están nadando con lo que conlleva (reducción de movimiento, no poder invocar montura...) ademas la animación hay tiene el error de que la realiza en el aire ni siquiera lo hace dentro del agua aunque tenga un nivel bajo.
Espero poder haber ayudado.

**Comment by Compresor** [comment]
Reporta cada mision en un issue diferente con sus ids para ayudar a su arreglo.

https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
