### ISSUE TITLE
BUG WOWERROR  en Tierras de la peste:El enclave escarlata

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#444]
En la mision de matar 100 soldados y unas balistas cuando llegas a la zona del barco 
salta el wowerror (Igual que en la zona de TIERRAS DE LA PESTE DEL ESTE: CAPILLA DE LA ESPERANZA DE LA LUZ) y el pj se queda atascado en bucle wowerror y no se puede jugar con el a no ser que se teletransporte.

![oww](https://f.cloud.github.com/assets/4893907/793972/fbf1d1b0-ec5a-11e2-998c-032d42e4f0ff.png)

**Comment by frustrix** [comment]
![wow2](https://f.cloud.github.com/assets/4893907/793996/df76f036-ec5c-11e2-8fff-cfb3ffe9b625.png)

![wow3](https://f.cloud.github.com/assets/4893907/793997/e44af6e8-ec5c-11e2-82e1-d11b787a2344.png)

He borrado carpetas:  CACHE, INTERFACE,  DATA/CACHE,  y  WTF   pero no logro que funcione sigue dando wowerror

**Comment by frustrix** [comment]
Paso a Hacer un skan disk y a borrar denuevo las carpetas anteriores y jugar sin addons ire revisando si me da error
y haciendo mas pruevas

**Comment by Wiinter** [comment]
Diría qe es cosa del servidor no de ti, te sugiero qe con otro pj pidas a algun gm que te mueva el personaje a otro sitio

**Comment by frustrix** [comment]
Error solucionado

**Comment by redneo** [comment]
Era por los cañones que daban algún fallo, voy a comparar a ver si saco algo en claro
