### ISSUE TITLE
[Brujo] Resguardo Abisal y de las sombras en la barra de acción

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4444]
Id Resguardo contra las sombras:6229
Id Resguardo abisal: 91713

El problema que está ocurriendo se da en la rama de destrucción. Si tienes en la barra "Resguardo contra la sombra" al activar "Armadura vil" o "Armadura demoníaca" se debería convertir en "Resguardo abisal". El problema es que al transformarse en "Resguardo abisal" el hechizo desaparece de la barra de acción y no se puede usar ni siquiera desde el libro de hechizos.

Un saludo y gracias

**Comment by Wiinter** [comment]
El resguardo de las sombras tampoco te lo puedes meter en las barras y además ni lo puedes usar dando click en el libro de hechizos, ocurre tanto con el resguardo de las sombras como con el abisal. Cambia el titulo del post si puedes

**Comment by efectokoleos** [comment]
arreglado falta compilar
