### ISSUE TITLE
Pestilencia (DK)

### ISSUE THREAD

**Issue by kikete17** [RoDNet/Bugtracker-Infinium-4.3.4#4445]
Problema: no esta infectado a los demás objetivos que se encuentren en un radio a 10m
ID:50842
Gracias y un saludo.

**Comment by yosalve** [comment]
disculpa pero a mi si me va pestilencia, no te sabría decir si la distancia va bien porque no tengo instrumento para medirla, pero por lo menos con varios objetivos cuerpo a cuerpo y algunos que esten cerca si me va

**Comment by Monleon** [comment]
Esto funciona, en test por lo menos. Y de ser así sólo así, será compilado en infi próximamente.
