### ISSUE TITLE
Misiones - Frente de Magma - La semilla misteriosa

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4446]
Nombre: La semilla misteriosa
Link: http://es.wowhead.com/quest=29245
Descripción: Lleva la bellota a Avrilla, en la Brecha de Malfurion, en las Tierras de Fuego.
Problema: el npc (http://es.wowhead.com/npc=52489) al que hay que entregarle la semilla no esta en su lugar.

**Comment by redneo** [comment]
Fixed
