### ISSUE TITLE
Caballero de la muerte misiones iniciales

### ISSUE THREAD

**Issue by JavierMateosBailen** [RoDNet/Bugtracker-Infinium-4.3.4#4447]
La misión La Batalla por el bastión de Ebano esta bugeada, te pide Morgraine que bajes al segundo piso para matar unos npc y en el segundo piso no hay nadie, se puede usar el portal trasero a Ogrimmar pero si lo haces sin completar la misión no te deja volver por estar silenciado, ni atacar por estar "apaciguado" ni hablar con nadie que sea de la facción de Ogrimmar, esto es un problema bastante grave para la clase Caballero de la muerte y que si no se completa esta misión no se puede jugar con esta clase.

**Comment by Monleon** [comment]
Vuelve a Acherus con personaje atascado. Haz lo siguiente, te falta una misión por entregar, por eso estás apaciguado.

Deberás aceptar la misión, borrar caché con el wow cerrado, completarla, y volver a borrar caché. Seguramente tengas que borrar de nuevo por el camino alguna vez más los temporales.
