### ISSUE TITLE
[Guerrero] Maestria Armas

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4448]
Nombre: Golpe de Oportunidad
ID:76838
Enlace:http://wow.freakz.ro/spells.php?spell=76838
Descripcion: Otorga un 17% (base) de Probabilidad de que tus ataques cuerpo a cuerpo activen al instante un ataque cuerpo a cuerpo extra que infligira un 100% de daño normal. cada puntos de maestria aumenta esta probabilidad un 2.2%

Problema: no se esta activando con ataques cuerpo a cuerpo spells solo con los automaticos y claramente deberia activarse tambien con ataques cuerpo a cuerpo spells

**Comment by F4NT4SM4** [comment]
dejo mas informacion por si dudan de que solo se activa con automaticos...
comentario de wowhead:
1. It proc from both abilities(yellow damage) and melee weapon swing(white damage)
and It can crit..
Se activa de ambas habilidades (daño amarillo) y de golpe con arma cuerpo a cuerpo (daño blanco) Y puede hacer crítico ..
el daño amarilllo es por spells y el daño blanco es el automatico
fuente: http://es.wowhead.com/spell=76838#english-comments

golpe de oportunidad, creo que no solo se activa con goles blancos, al menos en recount varias veces me han salido que el total de golpes de oportunidad es mayor al numero de golpes blancos, lo que me hace suponer que tambien se activa con los ataque amarillos (http://us.battle.net/wow/es/forum/topic/2456476721)

Maestría: Oportunidad de golpe. Es similar al talento de Especialización en Espada que había en el juego, pero este nuevo efecto trabaja con todos los ataques y todas las armas. Brinda un chance de soltar un ataque instantáneo adicional que causa 100% de daño del arma. (http://www.ecured.cu/index.php/Guerrero_(WoW) )

en el enlace de wow.freak dice claramente
Successful melee auto attack/ ataques automaticos
Successful attack by spell with melee damage class/ ataques por spells
mis spells tambien son ataques cuerpo a cuerpo golpe mortal es un ataque a cuerpo a cuerpo, golpe heroico tambien es otro ataque cuerpo a cuerpo y etc etc etc

**Comment by efectokoleos** [comment]
arreglado, falta compilar
