### ISSUE TITLE
[Mision] [Darnassus/Costa Oscura] Rompen olas de cambio

### ISSUE THREAD

**Issue by joeltob** [RoDNet/Bugtracker-Infinium-4.3.4#4450]
• Nombre: Rompen olas de cambio
• Enlace: http://es.wowhead.com/quest=26383
• Problema: El NPC Vesprystus no da la ruta de vuelo para costa oscura 

Soy humano no se si influye en algo hice casi todas las misiones de la capital nelfa y no puedo con esta tambien intente con la misión de la alianza "Se busca héroe: ¡Costa Oscura!"  pero tengo el mismo problema el NPC no da el vuelo a Costa Oscura. 

Gracias de antemano, por las dudas mi pj se llama Hael.

**Comment by redneo** [comment]
Arreglada.
