### ISSUE TITLE
[Misión][Monte Hyjal] Vuelve con Aviana

### ISSUE THREAD

**Issue by drog** [RoDNet/Bugtracker-Infinium-4.3.4#4457]
ID: [25832](http://es.wowhead.com/quest=25832/vuelve-con-aviana)
Al momento de ir a entregar la quest, el npc (Aviana) no se encuentra en el Santuario de Aviana.

Comentarios adicionales: 
- llevo 75 de las 115 misiones del Monte Hyjal
- el punto se entrega aparece en el mapa pero el npc no

**Comment by redneo** [comment]
Arreglada
