### ISSUE TITLE
Bug ZONA Brecha de la muerte y alrrededores

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#446]
En la zona hay arqueros elite (Cruzado de Tirisfal  ID:29103) que te fijan a cualquier distancia aunque estes cogiendo las misiones y te hacen una holeada de disparos que mueres en el instante y no puedes hacer nada en la zona solo morir constantemente

![wowscrnshot_071413_130126](https://f.cloud.github.com/assets/4893907/794137/3fd6cad8-ec75-11e2-853b-5f5688d86624.jpg)

![wowscrnshot_071413_125127](https://f.cloud.github.com/assets/4893907/794138/4b41c620-ec75-11e2-829c-f9ed20ba3972.jpg)

**Comment by redneo** [comment]
Les he quitado que tiren las flechas a ver si es mas sencillo

**Comment by frustrix** [comment]
Solucionado gracias por la eficacia y rapidez
