### ISSUE TITLE
Bug no puedo pegarle a los bichos (aparecen como amistosos)

### ISSUE THREAD

**Issue by AgustinCJA** [RoDNet/Bugtracker-Infinium-4.3.4#4462]
![wowscrnshot_122114_205954](https://cloud.githubusercontent.com/assets/10264297/5520161/ce0d5222-8954-11e4-9f09-f82b1937da7f.jpg)

No les puedo pegar por lo tanto no puedo hacer las misiones

**Comment by Kiritoo** [comment]
Pon un ticket y te lo solucionamos.

**Comment by nayan87** [comment]
jajajaja, pero pixela el pass del canal por dios, que va a  ser 28 de noviembre y hay muchisimo troll suelto en este server¡¡¡¡¡ felices fiestas
