### ISSUE TITLE
mision Calling de ancients.

### ISSUE THREAD

**Issue by nayan87** [RoDNet/Bugtracker-Infinium-4.3.4#4463]
En este caso debemos reclutar a talosauco y los ancestros de hyjal con 125 marcas del arbol, pero no encuentro al NPC que nos recoge las marcas y nos habilita otro vendedor del frente de magma, un saludo¡¡¡ os paso el link como siempre.

http://www.wowhead.com/quest=29283/calling-the-ancients.

**Comment by redneo** [comment]
Estas cadenas de misiones aun no me he puesto con ellas, ya que aun no he completado de arreglar las anteriores... paciencia.

**Comment by redneo** [comment]
Arreglada
