### ISSUE TITLE
[Talento] Heridas infectadas

### ISSUE THREAD

**Issue by UkfNonXtop** [RoDNet/Bugtracker-Infinium-4.3.4#4464]
ID: 48484

Descripción: Tus ataques Triturar, Devastar, Magullar y Destrozar infligen Herida infectada al objetivo. Herida infectada reduce la velocidad de movimiento del objetivo un 50% y un 20% su velocidad de ataque. Dura 12 s.

Problema: Devastar no está aplicando el debuff correspondiente.

**Comment by efectokoleos** [comment]
arreglado en la proxima compilacion
