### ISSUE TITLE
[Misiones][Colinas Pardas] ¿Duro como una piedra?

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4469]
Buenas.
• Nombre: ¿Duro como una piedra?
• Enlace: http://es.wowhead.com/quest=12014
• Descripción: Recupera el sismógrafo portátil y úsalo para recoger lecturas de estabilidad en Thor Modan. Después, vuelve con Brugar Petraescucha en el Campamento de la Brigada de los Páramos de Poniente. 
• Problema: El sismógrafo portátil (http://es.wowhead.com/item=35837) no funciona cuando se lo usa en Thor Modan.
Desde ya muchas gracias y hasta luego.

**Comment by redneo** [comment]
Arreglado cuando caiga el server
