### ISSUE TITLE
Bug dk:Pnj enemigos que no deberían serlo en Acherus

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#447]
Los pnj Jinete oscuro de Acherus ID: 28768 salen como enemigos en el territori donde nos dan las misiones 

![wowscrnshot_071413_150040](https://f.cloud.github.com/assets/4893907/794265/8ef13a0c-ec86-11e2-8573-ddaac1dc74cf.jpg)

**Comment by harrypaqueton** [comment]
Exacto a mi me pasa lo mismo y es imposible hacer las misiones ya que todos esos enemigos hacen un daño brutisimo y es imposible avanzar

**Comment by frustrix** [comment]
Mision arreglada gracias por la rapidez
