### ISSUE TITLE
[PNJ][Tierras Altas Crepusculares] Maestro Mathias Shaw <Líder del IV:7>

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4470]
Buenas.
Quería reportar que el PNJ Maestro Mathias Shaw (http://es.wowhead.com/npc=45796) no está. Se necesita para completar la misión Mathias te necesita (http://es.wowhead.com/quest=27782).
Desde ya muchas gracias y hasta luego.

**Comment by redneo** [comment]
Colocado con sus auras.
