### ISSUE TITLE
[PNJ][Tierras Altas Crepusculares] Colin Bramal

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4471]
Buenas.
Quería reportar que el PNJ Colin Bramal (http://es.wowhead.com/npc=48472) no está. Se necesita para completar la misión Encuentra a Fanny (http://es.wowhead.com/quest=28378).
Desde ya muchas gracias y hasta luego.

**Comment by nayan87** [comment]
A los hordas nos vendria bien también localizarle, hay un logro con el, jajajajajaj

**Comment by Monleon** [comment]
Se debería ver ya
