### ISSUE TITLE
[Hechizos/Talentos][DK] Roer/Golpe Monstruoso

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4478]
Buenas.
Quería reportar que la habilidad del esbirro del DK Profano Roer (http://es.wowhead.com/spell=47481) se puede usar mientras el esbirro está en Transformación oscura (http://es.wowhead.com/spell=63560) en vez de reemplazarse con Golpe monstruoso (http://es.wowhead.com/spell=91797)
Así es como está la barra de habilidades de mi esbirro (default) con Golpe monstruoso como una habilidad diferente a Roer:
![wtf](https://cloud.githubusercontent.com/assets/4582987/5554653/0531f14a-8c48-11e4-9caa-78076ee4bd5f.PNG)
El Golpe Monstruoso que se habilita al usar Transformacion Oscura:
![wowscrnshot_122514_151953](https://cloud.githubusercontent.com/assets/4582987/5554672/e9eb80e8-8c49-11e4-8fbc-08812ae27d0a.jpg)
Acabo de usar el Golpe Monstruoso, que debería haber reemplazado Roer y no comparte CD
![wowscrnshot_122514_151957](https://cloud.githubusercontent.com/assets/4582987/5554682/6fdba39a-8c4a-11e4-86a5-804507cdb0cf.jpg)
El resultado es que puedo usar Roer y tener dos Stun al precio de uno. El tiempo de reutilización sólo se comparte cuando se usa Roer:
![wowscrnshot_122514_152006](https://cloud.githubusercontent.com/assets/4582987/5554694/92b02ab6-8c4b-11e4-83a9-6b596400b81b.jpg)
Si me equivoco, hacermelo saber y espero haberme explicado bien.
Desde ya muchas gracias y hasta luego.

**Comment by F4NT4SM4** [comment]
bueno tu esbirro es especial el mio solo tiene un stun ._.

**Comment by ghost** [comment]
Ni idea, de un dia para el otro, apareció un esbirro con otro nombre y la habilidad estaba ahí.

**Comment by F4NT4SM4** [comment]
seguramente no esta en el libro de hechizos el otro stun poner en la barra zarpar y listo e.e

**Comment by ghost** [comment]
Ya sé, pero quizá no soy al único que le pasa y alguien mas se aprovecha del bug de 2 stun y no lo reporta. Y acabo de fijarme y tampoco esta en mi libro de hechizos.

**Comment by Monleon** [comment]
Me parece que es cosa de tu pet. A ver si ingame se puede hacer alguna cosa
