### ISSUE TITLE
[Mago] Congelación profunda en rama Fuego?

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#448]
Aquí la solución a este post: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/407

En mi larga arena de 47 minutos y repleta de bugs, me ha dado por mirar porqué al explotar bomba viva y mi objetivo estar tras una columna, me salía el mensaje: "no puedes ver al objetivo". He mirado en el combat log y...sorpresa, sale eso: "Congelación profunda de Asman falló. (No puedes ver al objetivo)."

Por lo visto será un fallo de ID de la spell Bomba viva, o quizás tenga que ver con el Trinket Naipe de la Luna Negra: Volcano y que haya coincidido justo en ese momento..pero no creo.

**Comment by Mhryel** [comment]
Seguimos desde https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1188
