### ISSUE TITLE
Misiones - Invasión a las Tierras de Fuego - Perfecciona a tu lobo

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4480]
Nombre: Perfecciona a tu lobo
Link: http://es.wowhead.com/quest=29164
Descripción: Usa el colmillo del lobo sobre los cadáveres de 10 invasores de las Tierras de Fuego en El Brote.

Problema: al usar el colmillo (http://es.wowhead.com/item=69235) sobre el cadaver de cualquier invasor no cuenta para la misión.

**Comment by Monleon** [comment]
Mira bien porque sí que funciona en algunos y se puede realizar

**Comment by yosalve** [comment]
Disculpa pero he mirado bien y por lo menos para mi no hay caso, he usado el item de la mision en cualquiera de las 3 zonas indicadas, sobre los cadaveres de todo lo que he visto y no me ha contado
- Invasor carbonizado http://es.wowhead.com/npc=52816
- Can de azufre http://es.wowhead.com/npc=52795
- Acólito cicatríceo http://es.wowhead.com/npc=54362
- Terror de llamas http://es.wowhead.com/npc=52219
- Némesis http://es.wowhead.com/npc=52383
- Despiertallamas carbonizado http://es.wowhead.com/npc=52791
- Destructor de azufre http://es.wowhead.com/npc=52794
- Piroseñor hirviente http://es.wowhead.com/npc=52300
- Behemoth ígneo http://es.wowhead.com/npc=52289

lo use en todos estos, en varios del mismo tipo varias veces, encima cerca y a la maxima distancia que pude, con y sin el botín que arrojan y nada.

No me modifica la vida esta misión, pero como no pude hacerlo solo lo reporté.
Saludos y gracias

**Comment by redneo** [comment]
Ya funciona en al menos 4 elementalea
