### ISSUE TITLE
[DK] Frenesí profano

### ISSUE THREAD

**Issue by mikelPerez1** [RoDNet/Bugtracker-Infinium-4.3.4#4483]
ID: 49016
Enlace: https://wow.freakz.ro/spells.php?spell=49016
Descripccion: Aumenta un 20% la celeridad a cambio del 2% de la vida maxima cada 3 segundos
Problema: En vez de quitar 2% de vida maxima, a mi DK le quita 40k de vida cada 3 segundos

**Comment by efectokoleos** [comment]
arregolado
