### ISSUE TITLE
[Misión] Soportando el calor

### ISSUE THREAD

**Issue by mikelPerez1** [RoDNet/Bugtracker-Infinium-4.3.4#4485]
ID quest: 29210
Enlace: http://es.wowhead.com/quest=29210
Problema: no se pueden destruir las runas

**Comment by ghost** [comment]
[Ya está reportada Blac](https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/4456)
Saludos feo xD

**Comment by mikelPerez1** [comment]
Tienes razon, no la había visto y eso que e mirado antes.
