### ISSUE TITLE
[Misión Sacerdote][Ayudando a los heridos][Alianza - Draenei]

### ISSUE THREAD

**Issue by Dave95** [RoDNet/Bugtracker-Infinium-4.3.4#4486]
Buenas comunidad RoD, el problema con esta misión es que al tratar de curar a los PNJ's aun teniéndolos seleccionados no deja curarlos y al final se termina curando a uno mismo, por favor revisad esta misión, gracias de antemano.

Una foto para demostrar lo que digo:
http://www.subeimagenes.com/img/wowscrnshot-122814-013639-1188357.html

Saludos de Veelen.

**Comment by Compresor** [comment]
IDs de la mision?
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
