### ISSUE TITLE
Cambio de Sexo de los Personajes ya creados

### ISSUE THREAD

**Issue by Pablocyou** [RoDNet/Bugtracker-Infinium-4.3.4#4487]
Pues iba a jugar y cuando entro veo que mis personajes masculinos ahora son femeninos.

**Comment by Kiritoo** [comment]
![1355823362196](https://cloud.githubusercontent.com/assets/5061022/5564358/ab466a16-8eb9-11e4-8d08-1981278f1e02.jpg)

**Comment by Kiritoo** [comment]
![nelson-haha](https://cloud.githubusercontent.com/assets/5061022/5564362/2839d99a-8eba-11e4-874c-f49c7e90dd67.jpg)
