### ISSUE TITLE
Mision: El fragmento del Pilar del Mundo, Infralar

### ISSUE THREAD

**Issue by gmanquilefn** [RoDNet/Bugtracker-Infinium-4.3.4#4488]
Coloca el estandarte del Anillo de la Tierra en el centro de la guarida de Abismion, mátalo y consigue el primer fragmento del Pilar del Mundo.
Cuando se toma el objeto no lo dropea, simplemente sale animación y la barra de carga cuando termina eso no lo cropea y si se quiere volver a tomar sale el mensaje ya esta en uso

**Comment by Compresor** [comment]
Vuelve al cabo de un rato y te volverá a salir.
