### ISSUE TITLE
[Cazador] Disparo de quimera

### ISSUE THREAD

**Issue by Sagittariu5** [RoDNet/Bugtracker-Infinium-4.3.4#4489]
Id: http://es.wowhead.com/spell=53209/disparo-de-quimera

Problema: dano sumamente bajo, en los ultimas dias se ha nerfeado esta spell siendo la unica de la rama de Punteria del cazador que valia la pena usarla y hacia su damage correcto, siento full cataclismico con arco pve. estoy pegandole 4k/7k critc a un tela con un 1.2k de temple, alguien que no es practicamente apto para el pvp y esto con cds.- Haciendo esto, sumado a que la celeridad del cazador no funciona apropiadamente pararegenerar el enfoque, es el nerf mas molesto que ha sufrido la spec en el server en cuanto a dano u.u 
Agradeceria mucho lo revisaran, aunque fuese despues de los feriados. saludos

**Comment by efectokoleos** [comment]
arregladom, falta compilar
