### ISSUE TITLE
Rogue habilidades bugs

### ISSUE THREAD

**Issue by Pitenser** [RoDNet/Bugtracker-Infinium-4.3.4#4492]
Bueno era para informar de que tanto la gubia, que no incapacita al objetivo (con el glifo puesto sin el no lo probé), el esfumarse, recibe daño cuando ya viene hacia ti y no debería ser así deberías esquivar esa habilidad. y cuando un objetivo muere se pierden los puntos de combo al momento no se quedan en el cadáver un poco de tiempo lo que permite activarse algunas habilidades que requieren esos puntos.

Un saludo y muchas gracias

**Comment by efectokoleos** [comment]
ids?

**Comment by Pitenser** [comment]
Gubia: http://es.wowhead.com/spell=1776
Esfumarse: http://es.wowhead.com/spell=1856

**Comment by efectokoleos** [comment]
gubia arreglado falta compilar

**Comment by efectokoleos** [comment]
los puntos de combo arreglados

**Comment by Pitenser** [comment]
muchas gracias, los arreglos entran en el próximo reinicio no?
