### ISSUE TITLE
[Misiones][Tierras Altas Crepusculares] El Martillo del Crepúsculo

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4496]
Buenas.
• Nombre: El Martillo del Crepúsculo
• Enlace: http://es.wowhead.com/quest=27784 (Alianza) http://es.wowhead.com/quest=27786 (Horda)
• Descripción: Consigue el Martillo del Crepúsculo. 
• Problema: No está el Martillo (http://es.wowhead.com/npc=46717) para entregar la misión.
Desde ya muchas gracias.

**Comment by redneo** [comment]
Esta mision es facil de arreglar, lo malo es la siguiente....

Tengo los spawns de la horda, pero no se que npcs alianza han de ayudarte, el evento seria mas o menos el mismo, pero ya te digo que no tengo los npcs que te ayudan.

Podrias ponerte en contacto conmigo por correo a alcoholaterapia@gmail.com

**Comment by ghost** [comment]
Según el video https://www.youtube.com/watch?v=n_7kNYxxzl4
Maestro Mathias Shaw <Líder del IV:7> (http://es.wowhead.com/npc=46892) de DPS
Cassius el Blanco <Comandante> (http://es.wowhead.com/npc=47038) de Heal
Kurdran Martillo Salvaje (http://es.wowhead.com/npc=46895) de Tank
Muchas gracias.
