### ISSUE TITLE
[Npc/Mobs] Problema al comensar siendo un huarguen 

### ISSUE THREAD

**Issue by TheRaffa** [RoDNet/Bugtracker-Infinium-4.3.4#450]
El problema consiste en que , te creas un pj huarguen y mientras esta el video intro racial , te matan , yo me dije , ¿ y por que eh muerto ? , lo que paso es que toda la ciudad  aparentemente esta en guerra con un ataque de los renegados, y simplemente no se puede nisiquiera caminar por que son muchos y d emayor nivel , incluso hay elites , lo primero que pense es que era algun evento o algo asi del servidor , pero al parecer no , bueno y al estar toda la ciudad en una "guerra" nos se pueden pedir las misiones ni se puede progresar con el personaje .

Un saludo y espero que se solucione luego, gracias-

**Comment by lamaza** [comment]
De hecho, el problema no es la guerra, sino que al tomar la quest inicial, no se puede entregar. No se por qué no han hecho nada con los huargen, que tan dificil sera corregir 1 solo npc y listo, lo mínimo y luego saalir de la zona...
