### ISSUE TITLE
Druida - defensa salvaje (pasiva oso)

### ISSUE THREAD

**Issue by gaditano19** [RoDNet/Bugtracker-Infinium-4.3.4#4500]
Buenas, he estado probando el druida para tankear y no me salta la pasiva de defensa salvaje:

Cada vez que asestas un golpe crítico no periódico en forma de oso, tienes un 50% de probabilidad de obtener Defensa salvaje, lo que absorbe daño físico equivalente a un 35% de tu poder de ataque durante 10s. Que a su vez se ve mejorado por la Maestría

Sin esta habilidad el dudu tank no sirve para nada.

https://wow.freakz.ro/spells.php?spell=62600&name=savage-defense

**Comment by efectokoleos** [comment]
arreglado, falta compilar
