### ISSUE TITLE
Guerrero: Ataque de la victoria

### ISSUE THREAD

**Issue by Potrele** [RoDNet/Bugtracker-Infinium-4.3.4#4501]
Ya lo comenté con Edea e intentamos arreglarlo, lamento no poder publicar una foto, mi ordenador no da para mucho, total, que:

Ataque de la Victoria del guerrero se activá al matar cualquier Npc, bien sea un conejo de nivel 1, una serpiente de la trampa del cazador, etc, lo cual no puede ser así, ya que el ataque de la victoria se activa contra un enemigo que otorgue experiencia u honor.

**Comment by efectokoleos** [comment]
en el siguiente reinicio deberia estar arreglado

**Comment by F4NT4SM4** [comment]
por si acaso comento que deberia de activarse si matamos las mascotas de jugadores las serpiente no cuenta me refiero a mascota
al matarla da experiencia por lo tanto deberia activarse
