### ISSUE TITLE
[Mazmorra] Ahn'Kahet

### ISSUE THREAD

**Issue by JavierMateosBailen** [RoDNet/Bugtracker-Infinium-4.3.4#4506]
En esta mazmorra los primeros pules se agrean desde demasiado lejos, aparte en los primeros pules los tejearaña (creo que se llaman así) tienen una habilidad que te tiran una tela de araña desde lejos y te traen hacia ella, esta habilidad tiene un bug en los primeros pules y es que te tira la tela de araña desde muy muy lejos llegando a agrear a toda la sala por ello y por ende morir, aparte los niveles de los npc están elevados, la mazmorra en normal es nivel 74-77 y los bichos muchos de ellos son de nvl 79-80.

**Comment by Compresor** [comment]
IDs??!!
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
