### ISSUE TITLE
bug warrior 29838

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#451]
el talento de la rama armas de guerrero http://es.wowhead.com/spell=29838 que deve de curar un 6% en 10 seg dada vez que tienes un estado de aturdimiento o inmovilizador, cura bastante demas ami como unos 30.000 de vida en esos 10 seg,(un 25% a ojo)esto hace que clases como roge y mago que el stun y novas que son sus ataque principales, les sea imposible mata a un warrior.

un saludo

**Comment by ghost** [comment]
Bug importantísimo, es completamente imposible bajar un warrior, muy urgente su solución...

El problema si no me equivoco es que el guerrero se cura cada segundo lo que debería curarse en total.

**Comment by searum** [comment]
fix
