### ISSUE TITLE
[Paladin] Sentencias iluminadas

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#4510]
https://wow.freakz.ro/spells.php?spell=53557 (Rango 2)
https://wow.freakz.ro/spells.php?spell=53556 (Rango 1)

Al lanzar una sentencia está curando sin tener en cuenta el sp del paladin.

Rango 1 = 1334 + 0.1_sp
Rango 2 = 2667 + 0.2_sp

**Comment by efectokoleos** [comment]
arreglado
