### ISSUE TITLE
[Misiones][Frente de Magma] Redes perversas

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4519]
Buenas.
• Nombre: Redes perversas
• Enlace: http://es.wowhead.com/quest=29189
• Descripción: Libera a 8 víctimas de los capullos de Telaceniza. 
• Problema: No hay ningún capullo en los alrededores (según wowhead, son todos estos):
http://es.wowhead.com/npc=52751
http://es.wowhead.com/npc=52783
http://es.wowhead.com/npc=52784
http://es.wowhead.com/npc=52989
http://es.wowhead.com/npc=52991
http://es.wowhead.com/npc=52992
Muchas gracias!

**Comment by redneo** [comment]
Arreglado
