### ISSUE TITLE
termine en el medio de la nada!

### ISSUE THREAD

**Issue by itzbas1989** [RoDNet/Bugtracker-Infinium-4.3.4#4522]
me monte en el barco para ir a donde la vashj'ir y me quede en el medio de la nada...despues de llegar  me mando a 3 lugares y me desconecto el juego cuando entre de nuevo estaba en el medio de kalimdor  y reinos del este Y ahora estoy atrapado no me deja revivir ni hacer nada.. si me dicen como hacer ... que quierooo jugar por favor.... -.-!

**Comment by redneo** [comment]
Cual es el nombre de tu pj?

estas cosas van mejor por ticket.

**Comment by itzbas1989** [comment]
Perdon No sabia donde ponerlo e.e 

Pj: ZbastardZ
