### ISSUE TITLE
[Misión][Cuenca de Sholazar] Siguiendo Órdenes

### ISSUE THREAD

**Issue by Jayqu** [RoDNet/Bugtracker-Infinium-4.3.4#4523]
http://es.wowhead.com/quest=12540#guides esa es la misión; el problema es que cuando encuentras al Oráculo herido, no pasa nada. Éste tiene el símbolo de misión incompleta sobre su cabeza y cuando hablas con él, ni se completa la misión, ni aparece el famoso crocolisco, ni nada,

**Comment by redneo** [comment]
Arreglada
