### ISSUE TITLE
bugs en chaman elemental

### ISSUE THREAD

**Issue by M4NUL0R3NT3** [RoDNet/Bugtracker-Infinium-4.3.4#4524]
bug beneficioso, totem elemental de fuego: dura mas de los 2 minutos que deberia durar y reemplazar en curso el totem por otro de fuego no desinvoca al elemental.

bug perjudicial, totem colera de aire: ni se nota que lo pones, no otorga el buff de 5% celeridad con hechizos aumentada.

bug perjudicial, maestria (sobrecarga elemental): cuando la maestria hace efecto con descarga de relampagos y cadena de relampagos, las replicas de estos 2 hechizos no añaden cargas al escudo de relampagos nunca.

**Comment by Kiritoo** [comment]
Los reportes deben de ir individuales si no se trata del mismo hechizo, aquí tienes una plantilla.
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by Stormfury** [comment]
En contestacion con los 2 ultimos puntos....

Ambos totems que dan celeridad funcionan, y obviamente, trueno ensordecedor no se activa con la maestria por que fundamentalmente ese 2º golpe es gratis....y otros hechizos distintos ademas...

Lo de los elementales si te doy la razon en ambos puntos.
