### ISSUE TITLE
[Misión] Traición en el Tramo de la Tempestad

### ISSUE THREAD

**Issue by osler** [RoDNet/Bugtracker-Infinium-4.3.4#4537]
Uno de los objetivos, el Barón Ashbury, no spawnea haciendo que sea imposible completar la misión.
[Misión](http://es.wowhead.com/quest=24592)
[NPC](http://es.wowhead.com/npc=37735)
[Vídeo de como debería funcionar](http://youtu.be/wcH4rimPFvA?t=2m14s)

**Comment by Kiritoo** [comment]
Arreglada.
