### ISSUE TITLE
[Misión] Fear No Evil

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#454]
Hola queria que está mision: No temerás peligro alguno

En la cual se debe usar:
Libro de oraciones de Paxton http://es.wowhead.com/item=65733
Para revivir: Soldado herido revivido (4)

Al utilizar el objeto aparece el aura pero no cuenta.

![no temeras peligro alguno 1](https://f.cloud.github.com/assets/3537253/794568/23334332-eca9-11e2-9a8d-da04e0cd2bd3.jpg)
![no temeras peligro alguno 2](https://f.cloud.github.com/assets/3537253/794569/2afd7d8a-eca9-11e2-8f08-f1d2fa12ae6b.jpg)

Quiero añadir los enlaces de la misión lo que pasa es que hay muchos ids ya que parece que está misión va dependiendo de raza/clase, asi que nose cual es el id de la mía.

Estas 3 dan de recompensa el mismo objeto que en la mía pero nose cual de ellas es.
http://es.wowhead.com/quest=28808
http://es.wowhead.com/quest=28810
http://es.wowhead.com/quest=28812

Estas otras son la misma misión con distintas recompensas.
http://es.wowhead.com/quest=28806
http://es.wowhead.com/quest=28809
http://es.wowhead.com/quest=28811
http://es.wowhead.com/quest=28813
http://es.wowhead.com/quest=29082

Siento no decir exactamente cual de ellas es.
http://es.wowhead.com/search?q=no+temeras+peligro+alguno

Un saludo.

**Comment by redneo** [comment]
tendria que funcionar ya
