### ISSUE TITLE
[Sacerdote] Forma de las Sombras

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4543]
ID: 15473
No está dando el 5% de celeridad, por lo que no reduce el tiempo de casteo de los hechizos

**Comment by Overseer101** [comment]
Lo acabo de probar yo en solitario y si que da el 5% de celeridad.
![wowscrnshot_010515_175154](https://cloud.githubusercontent.com/assets/3658679/5616305/a18b1148-9503-11e4-88ce-cb412ecd945c.jpg)
![wowscrnshot_010515_175200](https://cloud.githubusercontent.com/assets/3658679/5616306/a28aa04a-9503-11e4-9b60-6de5f131abc9.jpg)

Puede que sea algun aura en grupo que te la machaque?

**Comment by Drogoth2** [comment]
![image](https://cloud.githubusercontent.com/assets/3939699/5627080/25fcd53e-9594-11e4-896f-62925b3913cf.png)

![image](https://cloud.githubusercontent.com/assets/3939699/5627067/00df5b32-9594-11e4-9e77-4a0dd4dc6bd4.png)

Puede que en los stats si esté aumentando la celeridad, pero a los hechizos no les está reduciendo el tiempo de lanzamiento de pua mental ni de explosión mental, al resto de hechizos de sombra si lo está disminuyendo

**Comment by Overseer101** [comment]
Es... curioso como poco xDDDD

**Comment by Sagittariu5** [comment]
Pero eso sucede visualmente con todo xd

**Comment by efectokoleos** [comment]
arreglado, falta compilar
