### ISSUE TITLE
Misiones - Infralar - Terreno Fragil

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4549]
Nombre: Terreno Fragil
Link: http://es.wowhead.com/quest=26377
Probelma: el tunelador jamas aparece una vez q se deposita el cristal en el suelo, y el cristal despues de unos segundos de puesto en el suelo desaparece sin mas.

**Comment by redneo** [comment]
Si que funciona, la hice ayer.
