### ISSUE TITLE
Miedos

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#4556]
El problema está en que si tienes daño puesto encima del que le tiras un miedo de area o un horror, al hacerle una pizca de daño, te puede pegar aun teniendo el buffo del miedo u horror aun activo sobre él. Si tiene el buffo puesto es porque aún no ha expirado el tiempo ni le has hecho el daño suficiente como para romperle el buffo.
Lo más curioso es que con el miedo de un solo objetivo, miedo que solo tiene el brujo, no ocurre esto, o almenos no he llegado a hacer que me ocurra.

P.D: El daño para quitar los fears fué arreglado y testeado hace tiempo y funciona correctamente.

**Comment by Akademika** [comment]
Wiinter a mí ayer con el priest me pasó eso. No siempre sucede pero en BG a veces sí. Mi target tenía DOTs y le hice miedo de área. Sin pegarle duro y a 2 seg de que acabara el efecto de miedo me lanzó un ataque. No sé porque pasa la verdad
