### ISSUE TITLE
[Misión] - [La última de su raza] Inicio Facción Hijos de Hodir

### ISSUE THREAD

**Issue by Gnogi** [RoDNet/Bugtracker-Infinium-4.3.4#4557]
La misión "La última de su raza" http://www.wowhead.com/quest=12983 en Cumbres Tormentosas es la que sigue de una serie de quest para desbloquear la Facción de los Hijos de Hodir.

Esta misión te la da Astrid Bjornrittar y requiere que vayas a una cueva a montar a una osa y traerla de vuelta. Pero en el momento de darte la quest, ella y todos los del poblado desaparecen, suponiendo cambiando de fase. En la cueva esta la osa que montas y sola se dirige hasta Astrid pero antes de salir de la cueva te desmontas (un nuevo cambio de fase) sin poder llegar a completarla. Aun acompañando a la osa al poblado Astrid no está para poder completar la misión. 

Sin poder terminar esta quest no se puede desbloquear toda una facción con sus correspondientes quest y vendedores.

**Comment by matycelta** [comment]
me tope con el mismo problema... por favor le echarian un ojo? gracias :)

**Comment by Gnogi** [comment]
La otra opcion que estoy probando es cambiar puntos de justicia por Honor de los Hijos de Hodir. Empezamos desde Odiados con 36.000 en negativo... así que son unos cuantos puntitos de Justicia.

**Comment by efectokoleos** [comment]
arreglado
