### ISSUE TITLE
[Orco] Racial de Mascota

### ISSUE THREAD

**Issue by Luis2403** [RoDNet/Bugtracker-Infinium-4.3.4#4567]
EL hechizo racial del orco que aumenta el daño de las mascotas no está en el libro de hechizos
![wowscrnshot_011115_144134](https://cloud.githubusercontent.com/assets/8336969/5704917/2b50f406-9a54-11e4-908f-8d22cf18dc5c.jpg)

**Comment by Sagittariu5** [comment]
Que raro, tu pj es migrado o algo? no le veo el nivel, con todos mis orcos tengo el racial xd

**Comment by Luis2403** [comment]
El pj no es migrado y el nivel es 17
