### ISSUE TITLE
bug maestria warro armas 

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#457]
la maestria de guerrero armas http://es.wowhead.com/spell=76838 no salta con:

golpe automatico: http://es.wowhead.com/spell=6603

golpe heroico: http://es.wowhead.com/spell=78

las dos son golpes a mele deberia de funcionas la maestria con esos ataques

<a href="http://tinypic.com?ref=2ev9tsz" target="_blank"><img src="http://i44.tinypic.com/2ev9tsz.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

un saludo

**Comment by searum** [comment]
... reporte no valido, esta bien como esta.

**Comment by 50megas** [comment]
hola searum un placer verte de nuevo^^ 

leyendo un foro del oficial:

http://eu.battle.net/wow/es/forum/topic/5723602655

todos dicen que salta con golpes blacos.

probando un dia un  istan molt.... como se ve salta con golpes blacos(golpe automatico)

<a href="http://tinypic.com?ref=2ebqohl" target="_blank"><img src="http://i43.tinypic.com/2ebqohl.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

un saludo
