### ISSUE TITLE
[Errores internos][Misiones] Leyara

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4570]
Buenas.
Hace un momento (11hs hora server) crasheó el server 2 veces y coincidió con mi progreso en la misión "Leyara" (quest=29200) una vez que le termino de hablar al personaje y comienza el evento (npc=53014). Lo hice con mi sacerdote Dagon y no me atreví a probar con otro personaje.
Desde ya muchas gracias y disculpen las molestias.
Saludos

**Comment by efectokoleos** [comment]
prueba en la proxima compilacion
