### ISSUE TITLE
profesión de inscripción problema al aprender glifos

### ISSUE THREAD

**Issue by norco1208** [RoDNet/Bugtracker-Infinium-4.3.4#4579]
No soy capaz de aprender los siguientes glifos y he intentado aprenderlos pero no me ha dejado.
http://es.wowhead.com/item=63420/glifo-de-esfumarse este se aprende por http://es.wowhead.com/item=45912/libro-sobre-maestria-en-glifos

glifo de pirofrio no he podido encontrar la id se aprende tras hacer la investigación de inscripción de rasganorte

glifo de rectitud de este tampoco se aprende tras hacer la investigación de inscripción menor

**Comment by Kiritoo** [comment]
Arreglados los de investigación en inscripción de Rasganorte y los que se aprende en el libro de maestría en glifos, estos cambios serán aplicados en el reino en la próxima compilación.

Ahora el sistema cuenta con un nuevo script el cual filtra los aprendidos (con esto se va a reparar el fallo que a veces al usar los libros no ocurría nada y gastabas el libro sin aprender un glifo), ahora solo dejaran de salir cuando estén todos aprendidos

He añadido todas las ids a mano con lo cual puede ser que me haya saltado alguno o quizás no he encontrado otros, si llegado el momento veis que alguno falta, nos lo reportais y lo agregamos encantados.

Saludos.

**Comment by Kiritoo** [comment]
Arreglada tambien la investigacion de glifos menores, será aplicada en la próxima compilación del reino.
Como comentaba en el mensaje anterior, si por casualidad no lográis aprender algún glifo, abris un reporte y lo revisamos y si falta lo añadimos.
Saludos.
