### ISSUE TITLE
[Spell > Hunter] Explosive Shot

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#458]
Hola queria comentar la siguiente habilidad.
Disparo explosivo  http://es.wowhead.com/spell=53301

El cual esta haciendo menos daño del debido.

![explosivo](https://f.cloud.github.com/assets/3537253/794625/46b48d3e-ecae-11e2-9e55-ba399ddb28f3.jpg)

Un saludo.

**Comment by searum** [comment]
fix
