### ISSUE TITLE
hechizo de resguardo de miedo

### ISSUE THREAD

**Issue by shogun1968** [RoDNet/Bugtracker-Infinium-4.3.4#4580]
El hechizo de "resguardo de miedo" de los sacerdotes sombra de la alianza no funciona. Aunque esté activado no hace nada y te afecta el miedo de otros jugadores

**Comment by Overseer101** [comment]
IDs?, se va el buff que pone el aura al sufrir un fear?, etc etc etc... por favor, reportad como dios manda, que en el foro hay una guia para ello si teneis dudas...

P.D. Afectará a todos los sacerdotes no solo a los alis...vamos digo yo...

https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/

**Comment by shogun1968** [comment]
Pues lamento decirle que no tengo ni idea de como se reporta y de que me pierdo en esa terminología. De igual forma siento haberle hecho perder el tiempo, pero mi intención era comunicar de la manera que conozco un fallo importante (a mi modo de ver), con la intención de que el servidor, que me parece genial, pueda seguir manteniendo la gran calidad que tiene. Dicho esto, como considero que es normal que existan reglas que haya que acatar, dejaré los reportes para personas mas cualificadas que yo. 
Se que afecta a los sacerdotes alis porque he preguntado a dos, no tengo constancia de que afecte a los sacerdotes hordas porque no he hablado con ninguno.
Y no quiero despedirme sin agradecerles su trabajo y esfuerzo, que estoy seguro que es enorme, poco agradecido y sin remunerar, lo cual dice mucho en favor de ustedes. Un saludo.

Date: Sat, 17 Jan 2015 10:30:24 -0800
