### ISSUE TITLE
Habilidades/Talentos 

### ISSUE THREAD

**Issue by Pitenser** [RoDNet/Bugtracker-Infinium-4.3.4#4583]
Druida 
Glifo piel de corteza: http://es.wowhead.com/spell=64256/glifo-de-piel-de-corteza 
No funciona
Testarazo: http://es.wowhead.com/spell=106839/testarazo
No carga al objetivo
Sacerdote
Maligno de las sombras: http://es.wowhead.com/npc=67235/maligno-de-las-sombras#abilities
No tiene barra de control y le faltan habilidades.
Mago
Descarga de pirofrio: http://es.wowhead.com/spell=44614/descarga-de-pirofrio
No ralentiza al objetivo
Guerrero
Seccionar mejorado: http://es.wowhead.com/spell=1715/seccionar
Solo se le da 1 vez en lugar de 2.
Talento de maestria tactica con 1 punto hace el mismo efecto que con 2 puntos.
Cazador
Disparo de punteria: http://es.wowhead.com/spell=19434/disparo-de-punteria
Se puede lanzar en movimiento y el firme y el de cobra tambien sin aspecto de zorro 
Picaro
Esfumarse: http://es.wowhead.com/spell=1856/esfumarse
No elimina los efectos de reducción de movimiento
Capa de las sombras: http://es.wowhead.com/spell=31224/capa-de-las-sombras
No elimina la censura del paladin, no es un hechizo pero tambien elimina efectos dañinos.
Distraer: http://es.wowhead.com/spell=1725/distraer
Saca de sigilo a los Cazadores y a los magos que no deberia

Lo siento por las ids, que corresponden a otros parches.

**Comment by Overseer101** [comment]
Por favor los reportes hacedlos como  indica en el foro, 1 reporte por fallo  y bien explicado con lo que debe realizar el talento y con el error para poder subsanarlo.

https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
