### ISSUE TITLE
Talentos Mago- Pirómano

### ISSUE THREAD

**Issue by jimmykell** [RoDNet/Bugtracker-Infinium-4.3.4#4584]
Al añadir Bomba Viva a mas de 3 mops con Impacto debería saltar el talento Pirómano, sin embargo esto no ocurre. Solo funciona Pirómano cuando lanzas sobre tres o más mops un Fogonazo. Eso no debería ser asi!

**Comment by Stormfury** [comment]
https://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
