### ISSUE TITLE
Talentos Mago- Pirómano

### ISSUE THREAD

**Issue by jimmykell** [RoDNet/Bugtracker-Infinium-4.3.4#4586]
Nombre: El talento Pirómano no se activa.
Descripción: 
![sin-titulo-1](https://cloud.githubusercontent.com/assets/10339531/5792456/5dd30e90-9f19-11e4-886f-9bc9146cf069.jpg)
![sin-titulo-2](https://cloud.githubusercontent.com/assets/10339531/5792463/c6bc7a40-9f19-11e4-8bc4-d012122e4599.jpg)

Cuando con Impacto, añades Bomba Viva a mas de 3 mops no se activa el talento Pirómano del mago. Si se activa con daño directo; como por ejemplo con el Fogonazo, pero no se activa con daño en el tiempo que es el problema en cuestión.

**Comment by Sagittariu5** [comment]
Yo pensaba que se pisaba con otro talento y era normal, ya que lo nito de verdad en pve xd

**Comment by efectokoleos** [comment]
arreglado, falta compilar

**Comment by jimmykell** [comment]
Ahora Impacto no traspasa daño en el tiempo a ningun mop
