### ISSUE TITLE
[Spell > Hunter] Black Arrow

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#459]
Hola quiero comentar la siguiente habilidad.
Flecha negra http://es.wowhead.com/spell=3674

![flecha negra](https://f.cloud.github.com/assets/3537253/794633/30423294-ecaf-11e2-831f-8c7819dad67d.jpg)

Está haciendo más o menos la mitad del daño que debería.

Un saludo.

**Comment by searum** [comment]
fix
