### ISSUE TITLE
[brujo]  Ascuas ardientes

### ISSUE THREAD

**Issue by miguel7ize1** [RoDNet/Bugtracker-Infinium-4.3.4#4593]
no me aparece el bufo ni con  Descarga de Fuego ni con  Fuego de alma tampoco es un bug visual porque no efectúa el daño

**Comment by Drogoth2** [comment]
Yo lo he estado mirando y efectivamente no aporta nada ni con descarga de fuego del diablillo ni con fuego de alma. Dejo las ids:

Talento Ascuas ardientes id: 85112
Fuego de alma id: 6353
Descarga de fuego diablillo id: 3110

**Comment by efectokoleos** [comment]
arreglado, falta compilar
