### ISSUE TITLE
[Esfumarse Bug]

### ISSUE THREAD

**Issue by obamakurosaki** [RoDNet/Bugtracker-Infinium-4.3.4#4594]
Hola, buenas noches

mi personaje se llama Lendrik y el problema que he detectado es que la habilidad [Esfurmarse] no funciona correctamente, cuando un enemigo te lanza por ejemplo un hechizo de enrraizamiento, te quedas en el suelo y no se disipa de tu personaje, por lo que es mas facil para los demas matarme.

Un saludo

**Comment by Sagittariu5** [comment]
Hombre a mi me ponen de todo con disuacion activa mas que nada picaros y magos xd

**Comment by efectokoleos** [comment]
arreglado falta compilar
