### ISSUE TITLE
[Cumbres Gemelas] Habilidad de camuflaje

### ISSUE THREAD

**Issue by obamakurosaki** [RoDNet/Bugtracker-Infinium-4.3.4#4595]
Buenas noches

hace poco he encontrado un bug que ocurre en la battleground llamada Cumbres gemelas. El problema es que los cazadores pueden portar la bandera con la spell [Camuflaje] lo cual dificulta atacarle y segun tengo entendido no deberia ser asi, muchas gracias.

Un saludo

**Comment by Sagittariu5** [comment]
El camuflage actualmente tiene un bug en el cual puedes seleccionar al cazador

**Comment by efectokoleos** [comment]
no debe ser asi, de hecho deberia funcionar correctamente ya que estuve probandolo ayer y a mi me funcionaba bien..
