### ISSUE TITLE
Mision: La mano de gul'dan

### ISSUE THREAD

**Issue by kalizayapro** [RoDNet/Bugtracker-Infinium-4.3.4#4596]
en el termino de la misión te dan una recompensas  la que yo quería era la hacha de corazón roto 
yo termine la misión y me costo mucho y no me dieron nada por favor arreglen la misión y si pueden, me darían el hacha de corazón roto es para mi dk se llama Destraz  

ME AVISAN SI ARREGLARON PLIZ

**Comment by redneo** [comment]
Enlace de la mision?
