### ISSUE TITLE
[Spell > Hunter] Multi-Shot

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#460]
Hola quiero reportar está habilidad.

Multidisparo http://es.wowhead.com/spell=2643

![multidisparo](https://f.cloud.github.com/assets/3537253/794635/7fb8b7a8-ecaf-11e2-9876-9064900e819d.jpg)

Que está haciendo un poco más de daño del debido.

Un saludo.

**Comment by searum** [comment]
a mi parecer esta bien como esta
