### ISSUE TITLE
Orbe de Sombras Sacerdote

### ISSUE THREAD

**Issue by IoritzVk** [RoDNet/Bugtracker-Infinium-4.3.4#4611]
Creo que tiene que ser un bug, no se si solo me pasará a mi o a todos, pero en la especialización de Sombras, Orbe de Sombras tiene un funcionamiento erróneo. Cada vez que entro al WoW, la primera vez que uso tortura mental con mi sacerdote (o que palabra de sombras: Dolor, hace daño periódico), automáticamente se me suman 3 cargas de orbe de sombras, pero a partir de entonces, no vuelvo a tener ningún orbe de sombras salvo que salga y vuelva a entrar, momento en el que se repite 3 orbes en uno, y ninguno más.

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, ya no daremos soporte al actual
