### ISSUE TITLE
[Guerrero] Gusto por la sangre

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4612]
Nombre: Gusto por la sangre
ID:56638
Enlace: https://wow.freakz.ro/spells.php?spell=56638
Descripcion: Aumenta un 60% la probabilidad de golpe critico de abrumar. ademas cada ves qeu tu facultad desgarrar inflige daño tiene un 100% de probabilidad de permititr el uso de abrumar durante 9s. este efecto no se dara mas de una ves cada 5s.
Problema: las absorciones estan evitando que se me active abrumar con desgarrar y deberia activarse aun si es absorbido 
es como el arrepentimento del paladin que no se quita al tirarlo con alguien con absorcion nose si esta reportado

**Comment by efectokoleos** [comment]
arreglado
