### ISSUE TITLE
[Cazador] llamada del maestro

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4613]
Nombre: llamada del maestro
ID:53271
Enlace: https://wow.freakz.ro/spells.php?spell=53271
Descripcion: Tu mascota elimina todos los efectos de enraizado y reducción de movimiento tanto de sí misma como de su objetivo y otorga inmunidad a tales efectos durante 4 s.
-Requiere linea de vision con su mascota
-La mascota no debe estar muerta
-La mascota no debe estar en cc
Problema: Se puede usar llamada del maestro con la pet muerta obviamente no deberia las otras 2 cosas no he probado ya q no tengo caza pero me he dado cuenta de la pet muerta en duelo

**Comment by efectokoleos** [comment]
arreglado falta compilar
