### ISSUE TITLE
[Misión] Entrenamiento mental: El camino de la verdad hacia el poder

### ISSUE THREAD

**Issue by Gnogi** [RoDNet/Bugtracker-Infinium-4.3.4#4626]
La mision "Entrenamiento mental: El camino de la verdad hacia el poder" http://www.wowhead.com/quest=25299 está bug.
Debemos invocar un orbe que nos hará unas preguntas y si fallamos nos debe hacer daño.
El Orbe se invoca y la barra de botones cambia para "Si", "No" y "Retirar Orbe" pero dicho Orbe no interactua con nosotros y no nos hace preguntas. Tampoco funciona Retirar Orbe con lo cual debes alejarte para que vuelva a aparecer tu barra de tareas.
Sin poder entregar esta, no se puede coger las siguientes, unas 20 misiones.
http://www.wowhead.com/quest=25601
Mirar el árbol de misiones en los comentarios.

**Comment by redneo** [comment]
Parcheada....
