### ISSUE TITLE
[Guerrero] Victoria inminente

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4627]
ID: 80128
ID glifo ataque de la victoria: 58382
El problema es que no está sanando el 5%, sino alrededor del 30%(con el glifo). Porque a un war con 177k de vida, este talento le está haciendo sanarse 56k

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, ya no daremos soporte al actual
