### ISSUE TITLE
[Misión] [Diaria-Pesca] Excavando en busca de lombrices

### ISSUE THREAD

**Issue by Gnogi** [RoDNet/Bugtracker-Infinium-4.3.4#4628]
Una de las misiones diarias de pesca de Ventormenta es "Excavando en busca de lombrices" http://www.wowhead.com/quest=26420. Te pide que encuentres unas lombrices en unos montículos http://www.wowhead.com/object=204281, al lado del lago Olivia, que te sirvan de cebo para pescar los peces requeridos para la misión.

Pues resulta que no encontramos ninguno de esos montículos en todo Ventormenta, ni en la zona del lago ni alrededor.

**Comment by redneo** [comment]
Arreglado
