### ISSUE TITLE
Talento (picaro) - Exterminar

### ISSUE THREAD

**Issue by Albertiktik** [RoDNet/Bugtracker-Infinium-4.3.4#4634]
Nombre: Exterminar
Enlace: https://wow.freakz.ro/spells.php?spell=58426
             http://es.wowhead.com/spell=58426/exterminar

Descripción: Mientras estás en sigilo y durante 20 segundos después de que se desactive el modo sigilo, regeneras un 30% de energía extra.

Problema-1: Cuando entras en sigilo no se activa, solo se activa con esfumarse.

Problema-2: Se mantiene activo todo el tiempo no los 20 segundos que dice la descripcion.

Problema-3: Mirando en las estadisticas del personaje, en reg. de energia siempre sale 10,00, parece que no sume ese 30%

.

**Comment by efectokoleos** [comment]
arreglado, estoy mirando lo de las estadisticas

**Comment by ghost** [comment]
Buenas.
Se volvió a bugear al parecer, exterminar no sale pasados los 20 segundos y sólo se vuelve a activar usando Esfumarse.
Saludos.

**Comment by ghost** [comment]
Ahora no se activa T_T

**Comment by efectokoleos** [comment]
arreglado falta compilar

**Comment by dylanvindas** [comment]
acabo de comprobar y el talento sigue buggeado, arreglar por favor.

**Comment by Kiritoo** [comment]
efectokoleos commented 21 hours ago
arreglado falta compilar

La compilación puede ser en unas horas como en dias, como efectokoleos ha escrito "falta compilar"
