### ISSUE TITLE
Talento (paladin sagrado) - Acusar

### ISSUE THREAD

**Issue by Albertiktik** [RoDNet/Bugtracker-Infinium-4.3.4#4638]
Nombre: Acusar

Enlace:https://wow.freakz.ro/spells.php?spell=85510&name=denounce

Descripción: Reduce el coste de mana de Exorcismo un 75%. Ademas, tienes un 100% de probabilidad de provocar el efecto Acusar en los objetivos de tu Exorcismo. El efecto Acusar  evita que los objetivos provoquen efectos criticos durante los siguientes 6 s.

Problema: Cuando lanzas Exorcismo no salta Acusar.

Observaciones: Salta aleatoriamente usando la habilidad Choque Sagrado, que no tiene nada que ver, incluso a veces te pone a tu mismo Acusar sin ponerselo al objetivo.

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, ya no daremos soporte al actual
