### ISSUE TITLE
mi racial...

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.3.4#464]
hace 9 dias se me cerro la issue 10 diciendo que estaba arreglada la racial y yo sigo sin tenerla en el libro de los echizos

**Comment by Dekadencee** [comment]
De que racial estamos hablando Oscarín, hay 200 reportes cerrado especifica un poco

**Comment by ghost** [comment]
se refiere a este reporte #10
