### ISSUE TITLE
[Mago] Glifo de Poder Arcano

### ISSUE THREAD

**Issue by Sokota** [RoDNet/Bugtracker-Infinium-4.3.4#4643]
Descripción:
Glifo de poder arcano: Mientras poder arcano está activo, el tiempo de reutilización global de traslación, escudo de maná y reflejo exacto se reduce a cero.

Problema:
El tiempo de reutilización global de ninguna habilidad (Traslación, escudo de maná y reflejo exacto en ningún momento se reduce a cero.

**Comment by Monleon** [comment]
Tiempo de reutilización global= GCD
Que significa esto? Que mientras tengas poder arcano activo esas tres spells no tendrán GCD, pero en ningún momento su CD se verá reducido a 0
