### ISSUE TITLE
[Sacerdote] Dispersion

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4651]
Nombre: Dispersion
ID:47585
Enlace: http://wow.freakz.ro/spells.php?spell=47585
Descripcion: Reduce todo el daño recibido un 90% y...........demasiada larga la descripcion solo puse lo que esta bug el resto perfect
Problema: solo esta reduciendo el daño fisico tambien deberia de reducir el daño magico

**Comment by Akademika** [comment]
Constato yo también 100% lo de que no reduce el daño mágico, y es algo muy molesto en PvP que deja al sacerdote sombras muy mermado de defensas frente a otros casters, ¡espero que lo arreglen pronto!
