### ISSUE TITLE
[Mago] Maestria: Adepto de Mana

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4665]
Nombre: Adepto de mana
ID:76547
LINK: https://wow.freakz.ro/spells.php?spell=76547
Descripcion: Aumenta todo el daño con hechizos que infliges hasta un 12%. en funcion de la cantidad de mana qeu el mago tiene sin gastar. cada punto de maestria aumenta el daño infligido hasta un 1.5%extra.
Problema: bug visual no importa cuanta maestria tenga siempre marca 12% solo es visual el daño si esta siendo aumentado

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, ya no daremos soporte al actual
