### ISSUE TITLE
[Brujo] Demonología Talento de Cremación con Incinerar

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4668]
Id Talento Cremación: 85103
Id Incinerar: 29722
Id Mano de Gul'dan: 71521

El problema es que este talento está reiniciando la duración de inmolar en el objetivo al castear incinerar y mano de gul'dan cuando sólo debería reiniciarse al usar el hechizo mano de gul'dan.

Un saludo y gracias

**Comment by Wiinter** [comment]
Lo renueva con todos los hechizos casteados no solo esos dos. Ya pasaba antes, lo arreglaron y se volvio a fastidiar

**Comment by efectokoleos** [comment]
arreglado
