### ISSUE TITLE
[Sacerdote Disciplina] Disciplinas Gemelas

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4669]
Nombre: Disciplinas Gemelas
ID:47586/47587/47588
LINK: https://wow.freakz.ro/spells.php?spell=47588
Descripcion: Aumenta un 2/4/6% el daño y sanacion realizados por tus hechizos sagrados y de las sombras.
Problema: esta aumentando las absorciones de palabra de poder escudo (id:17) solo deberia aumentar sanaciones

**Comment by Monleon** [comment]
No,  también debe afectar las absorciones provenientes de palabra de poder escudo. Es un multiplicador más de esta spell

**Comment by F4NT4SM4** [comment]
bueno hay dice aumenta sanaciones realizadas por hechizos sagrados 
palabra de poder escudo es una absorcion si fuese que aumenta la sanacion del glifo tuviera mas sentido...

**Comment by F4NT4SM4** [comment]
bueno segun wow.freakz guiandome de hay destello de luz es un efecto heler sanacion 
palabra de poder escudo Apply Aura: Absorb Damage  aplicaun aura para absorbe daño nada que ver con heler sanacion ._.

**Comment by Monleon** [comment]
Busca coeficientes y multiplicadores de la spell 17, y te aparecerá en todas ese x1,02 04 y 06 a tener en cuenta

**Comment by F4NT4SM4** [comment]
bueno nose donde buscar eso pero si dices que es a si me quedo tranquilo
