### ISSUE TITLE
[Druida] Destrozar

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4672]
ID: 33876
Daño sin arma: 926-927
Daño con arma low (ID del arma low: 2533): 968-991
Daño con arma: 2077-2614
Poder de ataque: 12964
Según la descripción sin el glifo destrozar debe pegar 285% de daño normal, en mi caso 2642. Restandole la armadura de los muñecos (25% de armadura por lo que tengo entendido), el ataque debería pegar 1981, sin embargo está pegando al muñeco 3450.

Además, al equiparle un arma (en mi caso corcesa de odio, ID: 71361), en vez de coger el daño sin arma para la fórmula está cogiendo el daño con arma, por lo que se potencia aún mas y pega como mínimo 8000. He probado también con un arma que no aumente la agilidad y efectivamente está cogiendo el daño con arma cuando equipas alguna en vez del daño normal sin ella.

**Comment by Overseer101** [comment]
https://wow.freakz.ro/spells.php?spell=33876  Mangle the target for 558% normal damage plus 56 and causes the target to take 30% additional damage from bleed effects for 1 minute. Awards 1 combo point/points.

**Comment by Drogoth2** [comment]
yo segun las formulas que veo es un 285% no un 558%

**Comment by Overseer101** [comment]
pues es 558%, lo tengo comprobado, si fuese 285% destrozar en este parche pegaria una absoluta basura, en torno a.... 6k normal 12k crit sin armadura ni resistencias.....

**Comment by Overseer101** [comment]
Y hay muchas descripciones del feral que estan mal puestas, ya te lo aviso.

**Comment by F4NT4SM4** [comment]
bueno aqui esta una informacion mas oficial 
A partir del nivel 80, el daño de Destrozar (felino) se ha aumentado a un 540% del daño con arma, en vez de un 460%, y el bonus de daño se ha reducido a 302 p. (http://eu.battle.net/wow/es/game/patch-notes/4-2-0#druids) en 4.3 no hay ningun cambio en destrozar solo el glifo
