### ISSUE TITLE
[Druida] Arañazo

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4673]
ID: 1822
Según mi descripción el hechizo debería golpear 1962 de daño de sangrado ,aumentado por la maestría(un 39%) y restandole la armadura del muñeco, debería pegar 2000 el primer golpe, sin embargo está pegando 1300.
Además hace un daño de sangrado en el tiempo igual a 9808, que aumentado por la maestría (39%) y restandole la armadura del muñeco, en total el daño en el tiempo debería ser de 10224 y, sin embargo está pegando en el tiempo 7925 (1525 por tick).

**Comment by Overseer101** [comment]
https://wow.freakz.ro/spells.php?spell=1822
Rake the target for AP \* 0.147 + 56 Bleed damage and an additional 56 \* 3 + AP \* 0.441 Bleed damage over 9 seconds. Awards 1 combo point/points.
