### ISSUE TITLE
[Druida] Destripar

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4674]
ID: 1079
Según la descripcion este daño de sangrado en el tiempo con mi poder de ataque (12964), de base debería pegar 17630, sumandole la maestria (39% extra de sangrado) y restandole la armadura del muñeco, el daño se debería quedar en 18379, pero está pegando 16768. No es mucho pero al fin y al cabo son 2000 menos casi.

**Comment by Overseer101** [comment]
https://wow.freakz.ro/spells.php?spell=1079

Finishing move that causes Bleed damage over time. Damage increases per combo point and by your attack power:
1 point: (56 + 160 \* 1 + 0.0207 \* AP) \* 8 damage over 16 seconds.
2 points: (56 + 160 \* 2 + 0.0414 \* AP) \* 8 damage over 16 seconds.
3 points: (56 + 160 \* 3 + 0.0621 \* AP) \* 8 damage over 16 seconds.
4 points: (56 + 160 \* 4 + 0.0828 \* AP) \* 8 damage over 16 seconds.
5 points: (56 + 160 \* 5 + 0.1035 \* AP) \* 8 damage over 16 seconds.
