### ISSUE TITLE
Habilidad [Brujo] Espiral de la Muerte

### ISSUE THREAD

**Issue by IvanDiGreat** [RoDNet/Bugtracker-Infinium-4.3.4#4679]
Descripcion: Provoca que un objetivo enemigo corra horririzado durante 3 segundos

Problema: es que no funciona Espiral de la Muerte como podran apreciar en la siguiente imagen

http://kn3.net/304BBE3A870JPG.html

**Comment by Drogoth2** [comment]
Se reporto hace tres semanas y es un bug bastante molesto para los brujos, ya que sea el daño que sea el efecto debería durar los 3sg o 3,5sg si tienes el glifo (No le afecta el daño causado ni comparte tiempo con el fear). Es decir, se pierde una habilidad bastante importante del brujo en todas las formas de hacer pvp.

**Comment by IvanDiGreat** [comment]
Si la verdad es molesto no tener ese poder :(, pero esperemos pronto este reparado.

**Comment by efectokoleos** [comment]
ya se arreglo
