### ISSUE TITLE
[NPC] Npc para Reparar en Ciudad de Gilneas

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#468]
Quiero decir, que este sujeto para reparar armaduras no existe, y se vuelve demasiado fastidioso jugar ya que de tanto morir tengo toda la armadura y armas rotas, no se puede hacer nada :/. Ojala pudieran poner algun reparador en la zona, ya que la zona en si, es injugable.

**Comment by searum** [comment]
Esta zona estamos preparandola todavia... queda poquito para que este totalmente disponible.
