### ISSUE TITLE
[PNJ][Items/Objetos] Intendente Ozorg

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#4681]
Buenas.
El PNJ Intendente Ozorg (http://www.wowhead.com/npc=28512/) vende indiscriminadamente los objetos de misión de dk ya sea clase o nivel, cuando sólo tendría que venderselos a los DK. Por ejemplo, se puede ver a un guerrero nivel 13 leveando con objetos de nivel mucho mas alto:
![captura](https://cloud.githubusercontent.com/assets/4582987/6205495/48054dbc-b54e-11e4-95cf-73d0389e80ed.PNG)
Desde ya muchas gracias y hasta luego.

**Comment by Smiithx** [comment]
Como llegaste hasta para comprarlo con un pj lvl 13?

**Comment by ghost** [comment]
No es mi pj, es un pj ajeno.
Te tiene que invocar otra persona con la habilidad de hermandad "Viaje en grupo" para llegar. O te puede llevar alguien a lomo de una montura voladora.
Saludos.
