### ISSUE TITLE
[Brujo] Talento de ascuas ardientes

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4688]
Reabro el post, hablé con un gm y me dijo que solo faltaba implementar pero he visto algunos arreglos posteriores y este aún no se ha corregido desde que se puso en el changelog.

Pongo el link del post: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/4593

Un saludo y disculpad las molestias.

**Comment by efectokoleos** [comment]
en el proximo reinicio estará
