### ISSUE TITLE
misiones crestagrana

### ISSUE THREAD

**Issue by lilith384** [RoDNet/Bugtracker-Infinium-4.3.4#469]
hola estoy intentando levear un paladin draenei y en crestagrana no hay manera de que las misiones funcionen y los objetos que dan no es asi, estan bug o que pasa

**Comment by crowel** [comment]
Cierro Issue, si todavia persiste el problema crea un Issue o añadelas a este con las misiones que fallan y sus ids y lo reabro.
Un saludo.
