### ISSUE TITLE
[Misión][Costa Oscura]La ofrenda a Azhara

### ISSUE THREAD

**Issue by Smiithx** [RoDNet/Bugtracker-Infinium-4.3.4#4697]
- link: http://es.wowhead.com/quest=13900/la-ofrenda-a-azshara
- descripcion: Evita que las sacerdotisas Escama Oscura ofrezcan el cuerno de los ancestros a Azshara sobre Nazj'vel. 
- problema: al matar las sacerdotizas no pasa mas nada. Deberia aparecer Azhara decir unas fraces y contar la mision como completada.
- como deberia realizarse:  http://youtu.be/dGCAXEca53E

**Comment by redneo** [comment]
Arreglada como sale en el video
