### ISSUE TITLE
[Druida][Glifo] Glifo de Crecimiento salvaje

### ISSUE THREAD

**Issue by Sagittariu5** [RoDNet/Bugtracker-Infinium-4.3.4#4698]
Descripcion: Crecimiento salvaje puede afectar hasta a 1 objetivo extra, pero su tiempo de reutilización aumenta 2 s.
Id:
http://es.wowhead.com/item=45602/glifo-de-crecimiento-salvaje
http://es.wowhead.com/spell=64270/glifo-de-crecimiento-salvaje

Problema: No funcionan ninguno de las dos beneficios del glifo.

Gracias

**Comment by Albertiktik** [comment]
El glifo funciona, de curar a 5 te deja curar a 6 y te aumenta los 2 segundos. 
Lo que si que pasa veces es que no llega a los miembros de la banda, supongo que por algun error de texturas.

**Comment by Sagittariu5** [comment]
Yo no se, si es cuestion de un talento o un glifo mio el que obstruye esto, pero no a mi no me funciona para nada, he reiniciado los talentos 4 veces, probando diferentes builds y no, adjuntare alguna foto en cuanto vaya de raid
