### ISSUE TITLE
[BG] Cumbres gemelas, falta puerta antes de iniciar la bg

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#47]
buenas, el problema radica en que los 3 minutos de preparacion antes de que comiencen la bg, el lugar donde aparece uno no tiene puerta, y se pueden salir y adelantar.

![wowscrnshot_070413_000124](https://f.cloud.github.com/assets/4895839/747579/a312b01c-e469-11e2-8992-ce59bf319e41.jpg)

![wowscrnshot_070413_000030](https://f.cloud.github.com/assets/4895839/747577/7f570736-e469-11e2-8dac-4d53af832f7b.jpg)

![wowscrnshot_070413_000042](https://f.cloud.github.com/assets/4895839/747578/84ba39fa-e469-11e2-92e1-989ae952231b.jpg)

El caso es que, deberia haber puerta durante los 3 minutos para que la gente no se salga

**Comment by crowel** [comment]
Porfavor cuando puedan añadan banderas a guilneas. [16:51:07] g4l1za.gz: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/83
Tambien en guilneas nunca me dan puntos al terminar si alguien puede confirmar.
Un saludo.

**Comment by Dekadencee** [comment]
Cumbres gemelas y batalla por gilneas necesitan implementación, estamos con ello

**Comment by lamaza** [comment]
Además, los beneficios de velocidad, ataque y regeneracion estan permanentes en la bg.
