### ISSUE TITLE
[Hechizos sacerdote] Problema con hechizos canalizados

### ISSUE THREAD

**Issue by Akademika** [RoDNet/Bugtracker-Infinium-4.3.4#4703]
Llevo observando hace tiempo el siguiente problema. Cuando se lanza Tortura mental (http://es.wowhead.com/spell=15407/tortura-mental) o bien Penitencia (http://es.wowhead.com/spell=47540/penitencia) a un enemigo cuando el sacerdote está levitando (http://es.wowhead.com/spell=1706/levitar), al menos el primer casteo se corta.

En los muñecos de entrenamiento ocurre que el primer casteo se corta (entra el primer tick nada más), y los demás entran enteros.
En cambio, en BG muchas veces se corta siempre, solamente entrando el primer tick con mucha suerte (y con tortura mental ni eso).
En teoría levitando o sin levitar, estos hechizos canalizados deberían funcionar sin cortarse.

Os pido por favor que lo podais arreglar, ¡muchas gracias por vuestra dedicación!
Gracias

**Comment by efectokoleos** [comment]
deberia estar arreglado en la proxima compilacion
