### ISSUE TITLE
[Picaro-Combate][Hechizos] Asesinato multiple

### ISSUE THREAD

**Issue by j0c54n** [RoDNet/Bugtracker-Infinium-4.3.4#4708]
es.wowhead.com/spell=51690
Se supone que es el ataque mas fuerte que tiene el picaro en la especializacion _Combate_.
El problema es que no hace el daño que deberia, hace muy poco daño, hace daño casi igual a golpe siniestro, ademas de tampoco golpe siniestro ni golpe revelador estan haciendo el daño suficiente.

**Comment by Overseer101** [comment]
Reportar las cosas como se deben, hay una guia en el foro para ello.
