### ISSUE TITLE
[NPC]- Falta NPC Libramorte Eredar en el Arcatraz.

### ISSUE THREAD

**Issue by jimmykell** [RoDNet/Bugtracker-Infinium-4.3.4#4709]
http://es.wowhead.com/npc=20880/libramorte-eredar#screenshots:id=26501

No existe este NPC en la mazmorra de El Arcatraz, es "necesario" ya que dropea una receta de encantamiento. Falta tanto en HC como en normal.

![26501](https://cloud.githubusercontent.com/assets/10339531/6392311/b455d512-bdbf-11e4-88df-255dafb850b1.jpg)

**Comment by redneo** [comment]
Situado
