### ISSUE TITLE
[Joyeria > NPC] Isabel Jones <Vendedora de bocetos de joyería>

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#471]
Hola quiero comentar que este Npc

 Isabel Jones <Vendedora de bocetos de joyería> http://es.wowhead.com/npc=50480

El cual esta ubicado en ventormenta, te da la misión de joyeria para poder hacer sin tener la profesión o teniendo otra.

Otro error grave es que puedes elegir la misión que quieras hacer, siendo diaria y sin poder escojer tocando una aleatoriamente cada día como en el oficial.
Si embargo esta mal y puedes cojer la que quieras.

¡La última moda!
¡Mordisquitos! ¡No!  
Baba elemental
Las ogrozonianas están de humor
Un regalo para Lila
![wowscrnshot_071513_011433](https://f.cloud.github.com/assets/3537253/795180/a71391d8-ece6-11e2-9b22-2c317eacd03c.jpg)

Un saludo

**Comment by crowel** [comment]
Quiero añadir que la primera parte que comente, la de que cualquier persona aunque no sea joyero puede cojer la misión ya se fixeara, pero parece ser que antes del cambio en la DB.
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/27?source=cc

**Comment by ghost** [comment]
Añado, si eliges la primera misión, la de ¡La última moda! http://es.wowhead.com/quest=25157 (ali) / http://es.wowhead.com/quest=25159 (horda), no nos cuentan las veces que usemos el polvo que nos dan en un objetivo.

**Comment by crowel** [comment]
Esto te refieres Zaska https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/402
Un saludo.

**Comment by redneo** [comment]
todas tendrian que ir ya, dando solo una al dia. 

Decir que las misiones que te piden joyas, si leeis atentamente dice que las partas, no sirve con tenerlas en el inventario, hay que crearlas!
