### ISSUE TITLE
Misiones - Marisma de Zangar - ¿Un espíritu aliado?

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4712]
Nombre: ¿Un espíritu aliado?
Link: http://es.wowhead.com/quest=9847
Objetivo: Lleva el Tótem Feropantano hasta el pie de las escaleras de las Ruinas Boha'mu y colócalo en el suelo. Informa sobre tus descubrimientos al vidente Janidi en Zabra'jin.

Problema: el totem no se puede usar en el lugar que indica la misión.

**Comment by redneo** [comment]
Si que se puede colocar, tras subir el primer tramo de escalera.
