### ISSUE TITLE
Misiones - Nagrand - Bendicion de Incineratus

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4714]
Nombre: Bendición de Incineratus
Link: http://es.wowhead.com/quest=9805
Objetivo: El elementalista Lo'ap en El Trono de los Elementos, en Nagrand, quiere que destruyas la Cabaña Grande, la Cabaña del Oeste, la Cabaña del Sur y la Cabaña del Este en la Aldea Junco Alabeado.

Devuelve el fuego viviente al elementalista Lo'ap cuando hayas completado tu tarea.

Problema: si bien las cabañas pueden ser incendiadas, no cuenta en ningun caso para el progreso de la misión.

**Comment by redneo** [comment]
Arreglada.

**Comment by yosalve** [comment]
Disculpa la insistencia redneo, he notado un cambio en la misión esta. Ahora me deja marcar 3 de los 4 objetivos. Pero sigo sin poder completarla porque hay una de las cabañas (mas precisamente la cabaña del este), que he probado en cada centimetro dentro de la cabaña y me pasa exactamente igual que cuando no andaba. Me deja usar el item y luego de usarlo se incendia pero no cuenta para la misión.
