### ISSUE TITLE
[Paladin] Gloria eterna

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#4715]
Talento ID: 87163
Descripción: Tu palabra de gloria tiene un 15%(rango 1/2) 30% (rango 2/2) de no consumir poder sagrado .
Fallo: Actualmente si tienes 1 o 2 cargas y usas palabra de gloria para curarte se te activan las 3 cargas dándote una cura gratuita por la cara cuando solamente no debería consumir las cargas que ya tienes activas.

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, ya no daremos soporte al actual
