### ISSUE TITLE
misiones legendarias

### ISSUE THREAD

**Issue by exketuflema** [RoDNet/Bugtracker-Infinium-4.3.4#4716]
ola hay un bug en la primera mision legendaria que t dan en tierras altas crepusculares en reducto bermellon bajo el arbol me suelta la mision (aplasta la corona) y me tenia que dar la d ir a la mansion ravenholt si lo pueden exar un vistazo 
muchas gracias

**Comment by Overseer101** [comment]
No se revisara nada que no este reportado correctamente tal y como indica en el foro.
