### ISSUE TITLE
[Errores Internos] Buffos/Aura Ap

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4717]
Nombre: Buffos/Aura Ap
Bendicion de Poderio:19740
Poderio de abominacion:53138
Ira Desatada: 30808
Aura de disparo certero: 19506
Descripcion: Son auras buffos que aumentan el poder de ataque mele 20% y poder de ataque distancia 10% 

Problema: al usar Bendicion de poderio se van las otras auras es normal el problema es que no debe de quitarle el aura a los pj que producen el aura por que se les bugea y toca relogear
pondre un ejemplo si un dk tiene 2/2 en poderio de abominacion (53138) este deberia ser inmune a bendicion de poderio (19740) haciendo que no le afecte

**Comment by F4NT4SM4** [comment]
sugerencia: si ponen que todas esas auras sean inmune entre ellas incluso poderio haria que ninguna pueda remplazar a la otra si el pj ya tiene esa aura se queda con esa hasta que se le valla la aura o buff
normalmente poderio remplazaria las auras si el pj no es el dueño de dicha aura pero ponerlo como la sugerencia tal ves sea mas facil
a si he visto en otros server cuando lanzan otra aura sale inmune en mi addon

**Comment by redneo** [comment]
Arreglado
