### ISSUE TITLE
Misiones - Nagrand - Confalones y Prácticas

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4719]
Nombre: Confalones y Prácticas
Link: http://es.wowhead.com/quest=9910
Objetivo: Elkay'gan el Místico en Garadar, en Nagrand, quiere que utilices un confalón de batalla Mag'har en la primera pira de los Filo Ardiente, en la segunda pira de los Filo Ardiente y en la tercera pira de los Filo Ardiente. Devuelve los confalones de batalla Mag'har que no hayas utilizado cuando termines.

Problema: si bien se pueden ubicar los confalones en las piras indicadas, al ubicarlos, no cuenta en ninguno de los casos para la misión. Y no se si servirá de algo, pero cada vez q pasas el cursor por encima de cualquiera de las 3 piras siempre el tooltip dice PRIMERA pira de filo ardiente, en las 3 que existen jamas ha dicho segunda o tercera.

Saludos

**Comment by efectokoleos** [comment]
arreglado
