### ISSUE TITLE
[Pesca] Ventormenta

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#472]
Hola queria comentar que pescando en los canales de ventormenta no se coje ningun pez ni objeto. Ventormenta http://es.wowhead.com/zone=1519
![wowscrnshot_071513_011752](https://f.cloud.github.com/assets/3537253/795188/65310484-ece7-11e2-95ac-2bec283fa048.jpg)
![wowscrnshot_071513_011759](https://f.cloud.github.com/assets/3537253/795189/656db78a-ece7-11e2-860d-be143f0dd39e.jpg)
![wowscrnshot_071513_011805](https://f.cloud.github.com/assets/3537253/795190/656d6dfc-ece7-11e2-830a-b54cc8193bc2.jpg)
![wowscrnshot_071513_011807](https://f.cloud.github.com/assets/3537253/795191/6570e98c-ece7-11e2-80c3-6d0ee104748f.jpg)

Esta es la lista de las posibles capturas que se pueden realizar.
http://es.wowhead.com/zone=1519#fishing

Un saludo.

**Comment by redneo** [comment]
arreglado!
