### ISSUE TITLE
Misiones - Nagrand - Una visita a los ancestros

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4722]
Nombre: Una visita a los ancestros
Link: http://es.wowhead.com/quest=10085
Objetivo: La Madre Kashur en las Tierras Ancestrales, en Nagrand, te ha pedido que visites el Puesto Primasol, las Ruinas Riecráneos, Garadar y las Ruinas Foso Sangrante.

Problema: no marca ninguno de los objetivos al visitar los lugares, no hay ninguna (http://es.wowhead.com/npc=18904) para marcar

**Comment by efectokoleos** [comment]
arreglada en el proximo reinicio
