### ISSUE TITLE
Bugs de Rogue

### ISSUE THREAD

**Issue by Flameseeker** [RoDNet/Bugtracker-Infinium-4.3.4#4726]
Hola gente, aca dejo un listado de las cosas bug de la clase, ya que son varias:
Talentos: (pongo en ingles, perdon, asi tengo el juego)
Overkill... no aumenta la reg de energia durante sigilo ni los segundos desp de sigilo
Venomous Wounds... cuando rupture hace daño no hay un daño de naturaleza q da el talento, ni te da el bonus de energia (10 de energia)
Killing Spree.. deberia hacer mas daño, hace poco, es una skill para terminar de matar un pj, y apenas  hace daño
Indices:
Haste... no aumenta la regeneracion de energia, obviamente necesitas mucho indice para q de buena regeneracion.
Glifos:
Glifo de patada... aumenta a 14 el cd de patada como deberia, pero cuando interrumpis un casteo, no reduce a 6 seg.
Bueno espero que le den un vistazo, ya que somos varios que venimos con este problema. Hace 1 mes y 1/2 que estoy en el server y la verdad esta muy bueno!!! Aprecio que se conecten seguido los gm y presten atencion! Muchas gracias!!!!

**Comment by Overseer101** [comment]
Por favor, los reportes ponlos solo con 1 problema por reporte, con sus respectivas ids y el fallo que observas.

P.D. Da igual que lo tengas en ingles, las ID son las mismas.

**Comment by Flameseeker** [comment]
Disculpa por poner todos los bugs de una, no sabia como son las reglas. Si por favor, podrían revisar los talentos que marque? Muchas gracias!
