### ISSUE TITLE
Misiones - Montañas Filoespada - Tiempos de negociación...

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4727]
Nombre: Tiempos de negociación...
Link: http://es.wowhead.com/quest=10682
Objetivo: Negocia con el sobrestante Nuaar.
Problema: encuentro al sobresante (http://es.wowhead.com/npc=21981), y puedo entablar diálogo (aunque sea solo una vez la que hablo con él), el diálogo concluye y no me cuenta para la misión.

**Comment by redneo** [comment]
Arreglado
