### ISSUE TITLE
[Misión] Feeding the Hungry and the Hopeless

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#473]
Hola quiero reportar la siguiente misión.
Alimenta al hambriento y al desesperado http://es.wowhead.com/quest=26271

En esta misión debes poner de comer a unos sin hogar, usando la caldera que es objeto de misión.
*Estofado de los Páramos de Poniente http://es.wowhead.com/item=57991

Al utilizarlo aparece la caldera pero los huerfanos no hacen nada, ni cuenta como objetivo de misión.
![wowscrnshot_071513_015847](https://f.cloud.github.com/assets/3537253/795198/14a5b978-ece8-11e2-936e-c8c65d63e56e.jpg)
![wowscrnshot_071513_015841](https://f.cloud.github.com/assets/3537253/795199/14b53704-ece8-11e2-9f64-5822908ff982.jpg)

Un saludo.

**Comment by Kiritoo** [comment]
Ya arreglada, https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1686?source=cc
