### ISSUE TITLE
[Instructores Sableinvernales] Cadena de misiones.

### ISSUE THREAD

**Issue by oscarka2** [RoDNet/Bugtracker-Infinium-4.3.4#4730]
Hola, el otro dia puse un ticket preguntando si estaban revisadas estas misiones y me dijeron que no y si las podia reportar, bien ahi voy.

Esta cadena de misiones te proporciona un compañero sable invernal que te da una serie de misiones diarias a completar para conseguir una montura; al igual que existe una en el crater de un goro un raptor, pregunté a los compañeros de la horda y me dijeron que esas misiones funcionaban.

Bien pues te diriges a cuna de invierno al instructor sable invernal (Rivern Ventogélido) y hay una mision que consiste en recoger las crias de tigre que hay bajo la roca (get them while they are young), bien pues estos tigres no se pueden coger. El mismo NPJ te da otra mision, que deberia ser la siguiente a esta pero la ofrece a la vez, (they grow up so fast) que te dan ya el compañero y te pide que le entregues 20 pelos, 20 paños runicos y 20 cueros bastos. Bien esta si funciona y el compañero te ofrece las misiones diarias para conseguir los pelos del tigre para la mision, pero la primera mision diaria que ofrece el tigre (Hunting Practice) que consiste en llevar al tigre a unos monticulos de nieve que contienen liebres para que las cace, bien pues esos monticulos ni siquiera aparecen.

LAs demas misiones diarias no tengo conocimiento de si funcionan o no, ya que para hacerlas hay que hacer la primera y no funciona. 

Me gustaria que lo revisaran ya que somos bastantes usuarios que queremos esa montura y son unas misiones muy entretenidas.

**Comment by redneo** [comment]
Buenas, para empezar me hubiera sido de mucha ayuda los enlaces de wowhead.

They Grow Up So Fast http://www.wowhead.com/quest=29034/they-grow-up-so-fast ya necesita de la misión http://www.wowhead.com/quest=29032/get-them-while-theyre-young, la cual he arreglado.

Estaba con el resto de misiones, las cuales no las daban bien, habiendo arreglado de seguro http://es.wowhead.com/quest=29035/antojos-de-cachorro.

Me acabo de fijar que SOLO da una misión al día que es como tiene que ser, la de hoy funciona seguro, me pongo con el resto.

Un saludo.
