### ISSUE TITLE
[Brujo] Talento de ascuas ardientes

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4733]
Lo siento por volver a molestar con esto, pero solo está funcionando a medias ya que ascuas ardientes se tiene que activar con fuego de alma y con la descarga de fuego del diablillo; y ahora mismo solo se está activando con fuego de alma. Dejo el enlace del post https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/4593

Un saludo y disculpad las molestias

**Comment by efectokoleos** [comment]
arreglado en el proximo reinicio
