### ISSUE TITLE
[Sacerdote] Problema en regeneración de maná

### ISSUE THREAD

**Issue by Akademika** [RoDNet/Bugtracker-Infinium-4.3.4#4734]
Buenas tardes,

No sé si estará pasando en otros casters, pero al menos en el sacerdote sucede que no funciona nada bien la regeneración de maná. Cuando entras en combate recuperas muy poquito maná desde hace unos 4-5 días especialmente, en cuanto quieres darte cuenta el priest está seco. Le pasa al menos en la rama shadow y en la holy también, el disci no lo he testeado todavía.

Espero que podáis echarle un vistazo en cuanto os sea posible.

Muchas gracias por vuestra dedicación,

Un saludo

**Comment by Overseer101** [comment]
Acabo de probar la regeneracion de mana en sacerdote con los indices tanto en combate como no, y funcionan correctamente.

P.D. Si fallase eso fallarian todas las clases que usen maná como recurso.

**Comment by Akademika** [comment]
Pues algo tiene que ser. Seguiré mirando porque hasta el fin de semana pasado todo iba bien y ahora he notado un gran cambio en el priest. Insisto en que algo no está bien. 

Gracias por tu tiempo.
