### ISSUE TITLE
[Bug Misión] Siguiendo órdenes

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#4736]
Misión: http://es.wowhead.com/quest=12540/siguiendo-ordenes

Problema: Cuando hablas con http://es.wowhead.com/npc=28217/oraculo-hablalluvia-herido y matas http://es.wowhead.com/npc=28325/crocolisco-del-manglar-voraz, no puedes volver a hablar con el oráculo.

**Comment by redneo** [comment]
Arreglada.
