### ISSUE TITLE
[Bug Misión] La Clave de Condenación

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#4737]
Misión: http://es.wowhead.com/quest=10588/la-clave-de-condenacion

Problema: Al terminarla, http://es.wowhead.com/npc=21024 no te da la posibilidad de escoger ningún objeto de recompensa. Los objetos son:

http://es.wowhead.com/item=31073/recordatorio-de-borak

http://es.wowhead.com/item=31072/lohngoron-arco-del-corazon-roto

http://es.wowhead.com/item=31062/hacha-de-batalla-del-corazon-roto

http://es.wowhead.com/item=31071/carga-de-gromtor

http://es.wowhead.com/item=31036/cetro-antiguo-de-oronok

http://es.wowhead.com/item=31038/baston-del-redentor

http://es.wowhead.com/item=31074/amuleto-del-corazon-roto

**Comment by redneo** [comment]
Ya tendría que dar los items
