### ISSUE TITLE
portales

### ISSUE THREAD

**Issue by reimonentrimo** [RoDNet/Bugtracker-Infinium-4.3.4#4739]
hola, tengo un problema con los portales, uno es el que va desde hyjal a ventormenta, me desaparecio cuando empece la cadena de misiones de invasion a las tierras de fuego, me parece que es, el que te lleva al frente de magma. y el otro problema es con el portal de ventormenta a uldum, ese no se exactamente cuando me desaparecio.

muchas gracias.

un saludo

**Comment by redneo** [comment]
El de uldum tienes q hacer la cadena de misiones no sólo la primera.

El de heal cuando caiga el server estará ok
