### ISSUE TITLE
[Mazmorras/Bandas][Tierras de fuego] Reputacion Normal y Heroico

### ISSUE THREAD

**Issue by Sagittariu5** [RoDNet/Bugtracker-Infinium-4.3.4#4742]
Bueno esta issue es para reportar la cantidad de reputacion que no esta dando cada boss, no se si soy exacto pero todos a excepcion de Ragnaros estan dando 250 de rep. lo cual no es correcto, ya que Baleroc Y mayordomo nos dan 400 pts, todos estos no estan dando el doble de reputacion de heroico, sea 500, 800, con un avance de 4 bosses en Fl hc esa reputacion nos vendria muy bien.

http://es.wowhead.com/npc=52498/bethtilac
http://es.wowhead.com/npc=52558
http://es.wowhead.com/npc=52530
http://es.wowhead.com/npc=53691/shannox
http://es.wowhead.com/npc=53494/baleroc
http://es.wowhead.com/npc=52571/mayordomo-corzocelada
http://es.wowhead.com/npc=52409/ragnaros

Si la cuestion de la reputacion esta bien, contestarme y asi puedo cerrar la issue, gracias

**Comment by redneo** [comment]
Baleroc, mayordomo y ragnaros estan dando 400 en normal
