### ISSUE TITLE
Misiones - Vallefresno - Manos pequeñas, mecha corta

### ISSUE THREAD

**Issue by yosalve** [RoDNet/Bugtracker-Infinium-4.3.4#4746]
Nombre: Manos pequeñas, mecha corta
Link: http://es.wowhead.com/quest=13944
Objetivo: Utiliza el cartucho de explosivo improvisado con el vagón averiado en la Avanzada Grito Infernal.

Problema: si bien se puede utilizar el cartucho de dinamita (http://es.wowhead.com/item=46701), cerca del vagon averiado, el usar este item no cuenta en absoluto para la misión.

Saludos y gracias

**Comment by redneo** [comment]
Arreglada.
