### ISSUE TITLE
Talento- Overkill

### ISSUE THREAD

**Issue by Flameseeker** [RoDNet/Bugtracker-Infinium-4.3.4#4747]
Nombre: Talento Overkil, rama Asesinato de Rogue.
Link: http://es.wowhead.com/spell=58426/exterminar
Descripcion: Exterminar
Mientras estás en sigilo y durante 20 segundos después de que se desactive el modo sigilo, regeneras un 30% de energía extra.
Problema: no funciona en ninguno de los 2 estadios, durante sigilo y los 20 seg después de romper sigilo.

Bueno aca dejo reportado el bug como se debe jeje, espero que este bien reportado.
Pd: ya postie anteriormente esto, no lo tomen como insistencia por favor. Solo quiero que este todo en orden para facilitar las cosas, gracias!

**Comment by efectokoleos** [comment]
arreglado, falta compilar

**Comment by Flameseeker** [comment]
Uy voy a resetear los talentos para ver si agarra ahora! Mil gracias! Encerio!

**Comment by dylanvindas** [comment]
acabo de comprobar y sigue bug, por favor arréglenlo.

**Comment by Overseer101** [comment]
3º post con lo mismo, pone que FALTA COMPILAR, coñe..., leed un poco antes de spamearme el bugtracker...

**Comment by Flameseeker** [comment]
A que te referís con compliar?
