### ISSUE TITLE
[Misión] The Dawning of a New Day

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#475]
Hola quiero reportar está misión.

El amanecer de un nuevo día http://es.wowhead.com/quest=26297

Cuando llegamos a la zona donde debe suceder la secuencia nos encontramos que ya estan todos los npcs situados y de la que debemos obtener la información ya esta encima del carro con paja

![wowscrnshot_071513_022114](https://f.cloud.github.com/assets/3537253/795226/8fd43578-ecea-11e2-8d3e-3fc2f2cc12c2.jpg)

Tras esperar un rato a ver si comenzaba a hablar para dar la información necesaria para la misión vemos que nada, le damos click a ver si nos completa y tampoco, despues de unos minutos desaparecen todos, sin completarse la quest.

![wowscrnshot_071513_022134](https://f.cloud.github.com/assets/3537253/795231/bede854e-ecea-11e2-92f9-f05e5a368fe9.jpg)

![wowscrnshot_071513_022123](https://f.cloud.github.com/assets/3537253/795234/c88e0308-ecea-11e2-9bf1-065d453e9d85.jpg)

Esta misión tras llegar a la zona con multitud la tía de encima de la paja deberia aparecer tras unos segundos al llegar a la zona y comenzar a hablar, dando la información a gritos y así completando la misión.

Aqui un video: http://www.youtube.com/watch?v=-yHK7W3CZXY

Un saludo.

**Comment by Kiritoo** [comment]
Esta misión está arreglada por redneo cierro issue.
Saludos.
