### ISSUE TITLE
Bug de Mision: ¡Se llevaron a nuestros hombres!

### ISSUE THREAD

**Issue by Jicson** [RoDNet/Bugtracker-Infinium-4.3.4#4750]
Mision para iniciar reputacion con Los Hijos de Hodir, no se pueden encontrar los npc que se deben rescatar lo que imposibilita completar y continuar con las siguientes misiones.

**Comment by Overseer101** [comment]
ID de mision, npcs que faltan y demas por favor, de lo contrario no se puede mirar nada.
