### ISSUE TITLE
Racial Troll

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4751]
ID: 26297
Aparentemente en las estadísticas parece funcionar el racial del trol, puesto que sube la celeridad, pero sin embargo, no está afectando a los hechizos ni ataques en ninguna rama (por lo menos del druida)
![image](https://cloud.githubusercontent.com/assets/3939699/6573596/bd2c7dd8-c71c-11e4-9bf7-a93ce8749293.png)
![image](https://cloud.githubusercontent.com/assets/3939699/6573598/c40369f0-c71c-11e4-9261-918ad4204345.png)

**Comment by Overseer101** [comment]
Tienes razon, el aura no aplica la estadistica correctamente.

**Comment by efectokoleos** [comment]
arreglado falta compilar
