### ISSUE TITLE
[Chaman] Precision Elemental

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4756]
Nombre: Precision Elemental
ID:30672/30673/30674
Enlace:https://wow.freakz.ro/spells.php?spell=30674
Descripcion Aumenta el daño de tus hechizos de fuego, escarcha y de de naturaleza un 3% y te otorga un indice de golpe con hechizos igual al 100% de todo espiritu que ganes con objetos o efectos
Problema: Esta otorgando indice de golpe contando el espiritu base en la descripcion sale claramente solo con objetos o efectos

**Comment by Overseer101** [comment]
Pese a que la descripcion ponga eso, tambien cuenta el espiritu base que tengas.

**Comment by F4NT4SM4** [comment]
lo dudo en las guias nunca mencionan el espiritu base en la seccion de estadisticas para llenar el cap en pve 
no puedo ver por wowhead ya que lo eliminaron pero conseguie en el foro de blizzard que lo afirman 

Also keep in mind that Elemental Precision does not affect your base Spirit stat. Only Spirit that's on your gear. (http://us.battle.net/wow/en/forum/topic/1869564368)

He has 124 hit rating on his gear between gems and reforging. He has 1777 spirit, 1620 of which is from his gear. His hit rating is 1744. 1620 + 124 = 1744 = Elemental Precision does not work on base spirit.  (http://forums.elitistjerks.com/topic/109346-enhancement-unleashing-elements-a-cataclysmic-discussion-now-with-more-fire-nova/page-3) 

The value is correct, you're getting 411 rating from the 411 spirit you have on your gear.
The remaining 158 is your base spirit, and this isn't accounted for in Elemental Precision.  (http://eu.battle.net/wow/en/forum/topic/1549437754)

elemental precision DOES NOT take base spirit into consideration. for an enhancer, it clearly shows on armory where the difference between spell and physical hit only amounts to the chest enchant benefit depending on how much you spent in EP. (http://www.mmo-champion.com/threads/863308-Enh-Elemental-Precision-talent-question)

**Comment by Overseer101** [comment]
Pero estamos en lo de siempre, de que parche son esos comentarios? 4.06?, En el PTR de la 4.3.4 desde luego nunca me ha parecido que me contase solo el espiritu que me daban los objetos...

Ojo, que me puedo estar columpiado con esto, tambien lo digo xD

**Comment by F4NT4SM4** [comment]
bueno me puse a leer notas de parche de 4.0 a 4.3.4 y no hay ningun cambio del talento

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, ya no daremos soporte al actual
