### ISSUE TITLE
[Druida] Equilibrio de poder

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#4757]
Nombre: Equilibrio de poder
ID:33592/33596
Enlace:https://wow.freakz.ro/spells.php?spell=33596
Descripcion Aumenta un 2% el daño de tus hechizos de naturaleza y arcanos y tu indice de golpe con hechizos una cantidad extra igual al 100% del espiritu que obtengas de objetos y efectos.

Problema: Esta otorgando indice de golpe contando el espiritu base en la descripcion sale claramente solo con objetos o efectos

**Comment by Overseer101** [comment]
[Chaman] Precision Elemental #4756

**Comment by F4NT4SM4** [comment]
lo dudo en las guias nunca mencionan el espiritu base en la seccion de estadisticas para llenar el cap en pve
no puedo ver por wowhead ya que lo eliminaron pero conseguie en el foro de blizzard que lo afirman

Also keep in mind that Elemental Precision does not affect your base Spirit stat. Only Spirit that's on your gear. (http://us.battle.net/wow/en/forum/topic/1869564368)

He has 124 hit rating on his gear between gems and reforging. He has 1777 spirit, 1620 of which is from his gear. His hit rating is 1744. 1620 + 124 = 1744 = Elemental Precision does not work on base spirit. (http://forums.elitistjerks.com/topic/109346-enhancement-unleashing-elements-a-cataclysmic-discussion-now-with-more-fire-nova/page-3)

The value is correct, you're getting 411 rating from the 411 spirit you have on your gear.
The remaining 158 is your base spirit, and this isn't accounted for in Elemental Precision. (http://eu.battle.net/wow/en/forum/topic/1549437754)

elemental precision DOES NOT take base spirit into consideration. for an enhancer, it clearly shows on armory where the difference between spell and physical hit only amounts to the chest enchant benefit depending on how much you spent in EP. (http://www.mmo-champion.com/threads/863308-Enh-Elemental-Precision-talent-question)
