### ISSUE TITLE
[vendedor de conquista] bug

### ISSUE THREAD

**Issue by Srgatonegro** [RoDNet/Bugtracker-Infinium-4.3.4#476]
buenas, el vendedor de conquista de la horda, no tiene ninguna parte de ninguno de los 3 sets de druidas, ni el set feral ni el set de caster  ni el set de healer

http://es.wowhead.com/itemset=-346 set feral

http://es.wowhead.com/itemset=-347 set de healer 

http://es.wowhead.com/itemset=-345 set de equilibrio (pollo)

ninguno se encuentra en el vendedor n_n

y este es el npc 
http://es.wowhead.com/npc=54658/sargento-tronacuerno

creo q los alis tienen el mismo problema y el npc de ellos es este 

http://es.wowhead.com/npc=34075/capitan-martillo-de-endecha#comments

**Comment by ghost** [comment]
No venden nada mejor dicho xd.

**Comment by F4NT4SM4** [comment]
tampoco esta el de los dk

**Comment by SherBlader** [comment]
Ya esta arreglado

**Comment by redneo** [comment]
Fantasma, ponme otro bugtrack con los mismos datos pero del dk, gracias.
