### ISSUE TITLE
[Cazador] Disparo de punteria

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4780]
ID: 19434
Este ataque inflige 160% de daño con arma mas 9061, todo esto daño físico, bien mi daño con arma es de 4467-5361, repito sin ningún aspecto puesto, por lo que el daño sería alrededor de 16923.4, con la reducción del muñeco que creo que es de un 25% se quedaría en un 12692.55, pero sin embargo está pegando 19469

**Comment by Sagittariu5** [comment]
Venga que ayer no he estado pegando ni la mitad de lo que deberia al palo(Y el critico pega 1k menos de lo que deberia pegar en normal, ni con MMS, ni con chimera, de hecho no paso de 9k con ninguna habilidad, se puede saber porque? cuando el mago o el chaman se pasan por los cojones el temple, y van pegando 49k a full catas. y 25k los palas.

Ademas de que eso es lo que pegan sin aspecto, ahora con el mas el 20% el aura la escala de AP y critico, que simplemente no creo que esten de adorno, o que el AP es para que la Pet en punteria pegue mas?.- Ojala no lo dejen asi por favor.
