### ISSUE TITLE
[Paladín Sagrado] (Sentencias del Puro - Lanzamiento de conjuros)

### ISSUE THREAD

**Issue by Ilmien** [RoDNet/Bugtracker-Infinium-4.3.4#4783]
Descripción: Tu Sentencia aumenta un 9% tu celeridad de lanzamiento de hechizos y cuerpo a cuerpo durante 1 min, y un 30% tu regeneración de maná por Espíritu mientras estás en combate.
- La regeneración de maná en combate la da correctamente, pero no así la celeridad de lanzamiento de conjuros.

Sí que aumenta la celeridad en las estadísticas del personaje, pero sin embargo el tiempo para lanzar conjuros no se ve reducido lo más mínimo.

**Comment by Ilmien** [comment]
Añado Prints para una mayor Ilustración:
- http://postimg.org/image/lbuamubxn/

En la primera se muestra el tiempo de lanzamiento de Luz Sagrada sin el buffo.
- http://postimg.org/image/bkwywvdgr/

En la segunda que uso sentencia para ponerme el bufo y su descripción.
- http://postimg.org/image/5eviq4jjf/

En la tercera que el tiempo de lanzamiento de Luz sagrada no ha disminuido pese al buffo.
- http://postimg.org/image/w2hx8ipkb/

En la cuarta mi celeridad sin el buffo.
-  http://postimg.org/image/5vgqck7aj/

En la quinta mi celeridad con el buffo, según marca (que según veis luego no es real).

**Comment by Ilmien** [comment]
Añado: Uso un addon para ver el tiempo real de los casteos, y allí tampoco disminuye.
- http://postimg.org/image/m277w130h/

En la primera muestro el tiempo de casteo (2,25) sin el buffo.
- http://postimg.org/image/hucfna1kx/

En la segunda muestro el tiempo de casteo con el buffo, que sigue siendo el mismo.

**Comment by efectokoleos** [comment]
arreglado falta compilar
