### ISSUE TITLE
Misiones - Hyjal - Un ritual de llamas

### ISSUE THREAD

**Issue by edwyr** [RoDNet/Bugtracker-Infinium-4.3.4#4786]
http://es.wowhead.com/quest=29195/un-ritual-de-llamas

Bueno, esta misión consiste en eliminar a una serie de enemigos que vienen en oleadas y cuando acabas con ellos se deberia de completar, según la descripción de la misma.

Bug: Resulta que despues de matar a las oleadas aparece Leyara del portal y se dirige corriendo al npc que te da la misión, pero nada, se quedan mirandose hasta que Leyara desaparece y la misión no se puede completar. Si dejas el ratón sobre Leyara aparece como que hay que matarla para que se complete, pero sale en amistosa lo cual no se puede matar y por tanto tampoco completar la misión.

PD: Sin esta misión es imposible abrir el portal hacia el frente de magma y poder hacer sus diarias y demas.

**Comment by redneo** [comment]
arreglado gracias a Edea
