### ISSUE TITLE
Costa Oscura-La batalla por costa oscura

### ISSUE THREAD

**Issue by matycelta** [RoDNet/Bugtracker-Infinium-4.3.4#4788]
Al hablar con Malfurion y otorgarte esta mision [http://es.wowhead.com/quest=13897/la-batalla-por-costa-oscura], vas al lugar indicado en la espada del maestro pero no aparece el avatar de soggoth, tampoco funciona el objeto (Cuerno de los ancestros) que te dan para llamar a los ancestros y que te ayuden [http://es.wowhead.com/item=58365]

Espero puedan solucionarlo, muchas gracias :)

**Comment by redneo** [comment]
Arreglada.
