### ISSUE TITLE
[Druida Feral] Abalanzarse

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#479]
En respuesta A https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/429 La habilidad ''Abalanzarse'' http://es.wowhead.com/spell=64478/abalanzarse-feral del druida feral stunea, pero solo hace stunt de 1 segundo y no 4 como deberia ser, me cerraron el post pero no lo fixearon.

AQUI la prueba:
![wowscrnshot_071513_002836](https://f.cloud.github.com/assets/4895839/795909/af48afc2-ed0f-11e2-961d-0eb628cb3cf3.jpg)

![wowscrnshot_071513_003049](https://f.cloud.github.com/assets/4895839/795912/f0534540-ed0f-11e2-8146-3099e0008300.jpg)

![wowscrnshot_071513_003533](https://f.cloud.github.com/assets/4895839/795922/79007f16-ed10-11e2-95fc-88859260a3da.jpg)

**Comment by searum** [comment]
vale ya se lo que falla es algo del DR, ya se explico una vez en la 406... cuando tu usas la spell va reduciendo su stun pero hay algo que falla que hace que se reduzca siempre (por eso muchas veces lo fallas, sale inmune porque lo tiene reducido...) el fallo es ese, que se reduce antes de tiempo. Ya lo solucionaremos pero la spell va perfecta.

**Comment by searum** [comment]
esto esta fix
