### ISSUE TITLE
[Mision]-TundraBoreal(¡Atacamos!)

### ISSUE THREAD

**Issue by Taznear** [RoDNet/Bugtracker-Infinium-4.3.4#4799]
No se puede realizar la mision.Npc: El enviado Pezuña Orgullosa
http://es.wowhead.com/quest=11592/atacamos
En esta mision se supone que el npc que la da ,uno deberia seguirlo para asi poder realizar la mision.
No se puede realizar porque "El Enviado Pezuña Orgullosa" no se mueve.

![](http://wow.zamimg.com/uploads/screenshots/resized/98140.jpg)

**Comment by efectokoleos** [comment]
arreglada en el proximo reinicio
