### ISSUE TITLE
[BG] No se Ven Participantes de BG

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#48]
En las estadisticas de BG no se pueden visualizar los personajes que estan presente en la BG

![wowscrnshot_070413_000308](https://f.cloud.github.com/assets/4895839/747584/d496b886-e469-11e2-8f80-39587c78f8fa.jpg)

**Comment by crowel** [comment]
![wowscrnshot_070413_133349](https://f.cloud.github.com/assets/3537253/749237/9df80614-e4a4-11e2-8195-c73adefd3cae.jpg)

Mismo problema me ocurrio ami en guilneas.
Pero es extraño en grito de guerra que jugue anterior si que salia.
Entonces el problema o es puntual o esta en estas bgs hay que comprobarlo.
Un saludo.

**Comment by Dekadencee** [comment]
Son problema de las BG Cataclysm que no están aún implementadas, estarán disponibles en las siguientes actualizaciónes
