### ISSUE TITLE
Bug mision DK: Una sorpresa especial

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#480]
La mision consiste en matar a un personaje que te mandan despues de hablar con el y tal le debes matar pero no puedes ni hablar ni matarle lo cual implica que no puedes hacer la mision

Tambien se ve que te dan por duplicado la mision para matar a otro personaje distinto pero solo deverian dar 1

![wowscrnshot_071513_100522](https://f.cloud.github.com/assets/4893907/796468/970eaada-ed26-11e2-8a33-b71386b93b12.jpg)

![wowscrnshot_071513_101023](https://f.cloud.github.com/assets/4893907/796470/a1be5340-ed26-11e2-8fae-c95bd480ac69.jpg)

ID NPJ que da mision:29053

Hellen Puentecanto ID: 29061

La mision la dan por duplicado y te piden matar tambien a Lord Hanford pero ese npj no esta por la zona y es un huarhen eso me tiene despistado

Lord Hanford ID: 49355

**Comment by frustrix** [comment]
Arreglado gracias a Doora

saludos

**Comment by likaion** [comment]
Revivo este post. Estoy con un dk y al llegar a esta parte, el npc 'Caballero Comandante Puño de Peste' no me dio la quest... me salio el error: 'no cumples los requisitos para este misión' . Ahora ya no me aparece ni la exclamación para poder intentarlo otra vez. ¿Alguien sabe qué puede estar pasando?

Gracias

**Comment by likaion** [comment]
Cierro comentarios. Problema tratado en otro incidente (https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2512)
