### ISSUE TITLE
Mucho lag en el servidor

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4801]
El caso es que desde hace una semana el lag esta muy presente en el servidor, lo he hablado con los compañeros y estamos todos igual, no se a que se deberá pero es bastante molesto. Muchas veces se queda colgado y afecta mucho al pvp y al pve.

Espero que se pueda encontrar la causa y corregir pronto.

Un saludo y gracias

**Comment by IvanDiGreat** [comment]
Tambien las caidas estan afectando al servidor y a su mejoramiento espero corrijan eso lo antes posible. 

Un saludo a staff.

**Comment by Drogoth2** [comment]
La verdad es que debería arreglarse cuanto antes, si no terminará pasando factura y ese si es un gran problema :s

**Comment by IvanDiGreat** [comment]
Yo desearia que desconectaran el server un dia o dos  si es necesario y que le den limpieza a fondon, porque esta imposible jugar, si no es el lag son las caidas y lo que habias ganado lo piedes ya se honor, valor, logros, etc.

**Comment by Akademika** [comment]
Totalmente de acuerdo, como si son 4-5 días o los que sean. Es una faena pero también no viene mal descansar un poco de tanto wow. Quizás así el staff pueda trabajar más a gusto y se haga más jugable este gran server. Lo que echo en falta es algún tipo de comunicado informativo breve por parte de RoD.

Ante todo mi reconocimiento y agradecimiento por su labor al staff, que bastante hace.

Un saludo
