### ISSUE TITLE
[Bug Misión] La última de su raza

### ISSUE THREAD

**Issue by qulki** [RoDNet/Bugtracker-Infinium-4.3.4#4802]
Misión: http://es.wowhead.com/quest=12983/la-ultima-de-su-raza

Problema: Al montarte en la osa (http://es.wowhead.com/npc=29563/matriarca-faucehielo-herida), hay un punto antes de salir en que desmontas, no pudiendo completar la misión.

Este bug impide la obtención de http://es.wowhead.com/item=43962/riendas-del-oso-polar-blanco

**Comment by Sagittariu5** [comment]
Yo hice la cadena hasta esa mision, la deja porque estaba bug, y ya no la puedo tomar xd

**Comment by efectokoleos** [comment]
arreglada
