### ISSUE TITLE
[Quest] Cualquier portal en medio de la tormenta

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.3.4#4803]
[Mision](http://es.wowhead.com/quest=27537/cualquier-portal-en-medio-de-la-tormenta)
Descripcion: Mata a elementales de agua embarrados para coger 5 núcleos de tolvanera.
Fallo : los [elementales](http://es.wowhead.com/npc=44011/elemental-de-agua-embarrado) no estan dando el [item](http://es.wowhead.com/item=60333/nucleo-de-tolvanera)

**Comment by efectokoleos** [comment]
arreglado
