### ISSUE TITLE
bug filotormenta 46924

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#481]
la habilidad de guerrero http://es.wowhead.com/spell=46924 funciona bien ,el problema que no deja de hacelo cuano te desarman y deveria de parar al desarmarte

**Comment by searum** [comment]
claro pero te consiguen desarmar o no? esa es la cuestion... deberiais de intentar explicaros mejor que asi podria arreglarlo sin necesidad de entrar 20 veces al juego a probarlo ^^

**Comment by 50megas** [comment]
solucionado  segun #1098
