### ISSUE TITLE
[Paladin] Bendicion de poderio

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4812]
ID: 19740
No está aportando poder de ataque ni dando la cantidad de mana
![image](https://cloud.githubusercontent.com/assets/3939699/6868051/8f9757c0-d488-11e4-9ac7-1f0d74e7ed7a.png)

![image](https://cloud.githubusercontent.com/assets/3939699/6868058/98b4112c-d488-11e4-8d23-6b3e1790d7f3.png)

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, ya no daremos soporte al actual
