### ISSUE TITLE
[ Hunter > Cast time ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#482]
Vale, vengo a demostraros que disparo firme y cobra, y puntería se castean en más tiempo del debido por el delay que sufren.
![wowscrnshot_071513_115647](https://f.cloud.github.com/assets/2728817/796951/8d644da0-ed35-11e2-9b0d-2383c28e4693.jpg)

Vemos que mi celeridad está a 0%, no tengo talentos ni nada.

![wowscrnshot_071513_115653](https://f.cloud.github.com/assets/2728817/796959/b80c4968-ed35-11e2-846d-52d89efb7351.jpg)
![wowscrnshot_071513_115656](https://f.cloud.github.com/assets/2728817/796960/c642a4be-ed35-11e2-8638-4dcbdd8f0d89.jpg)

El Tootlip señala claramente 2 sec de casteo.

![wowscrnshot_071513_115700](https://f.cloud.github.com/assets/2728817/796963/d1b4c02a-ed35-11e2-92a0-f7b13f04906f.jpg)

![wowscrnshot_071513_115703](https://f.cloud.github.com/assets/2728817/796964/d644c7e8-ed35-11e2-9909-aaed7473af86.jpg)

Al usar un Addon como Quartz que nos muestra el timecast entre otros, de nuestras spells vemos que se castean a 2.5 sec base.

Aquí os dejo un vídeo del ofi con el mismo addon, http://www.youtube.com/watch?v=tSUpgD_Ojk0
Minuto 2:20 empieza a castear firme en 1.9 ( por el equipo y los posibles talentos )

En cuanto a Disparo de puntería
![wowscrnshot_071513_122357](https://f.cloud.github.com/assets/2728817/797073/b8811604-ed39-11e2-907b-1f621abe63fe.jpg)

Vemos como dice que debe ser casteado en 2.9 sec base, sin embargo se castea en 3.4 sec.

![wowscrnshot_071513_122445](https://f.cloud.github.com/assets/2728817/797076/cd6207fe-ed39-11e2-9607-2a31daf58672.jpg)

Estas 3 spells sufren un delay de 0.5 sec en el timecast, la solución es poner el timecast base en 1,5 para Steady y Cobra y 2,4 para Aimed shot, así se castearán correctamente.

http://es.wowhead.com/spell=77767 Cobra
http://es.wowhead.com/spell=56641 Steady
http://es.wowhead.com/spell=19434 Aimed shot

**Comment by crowel** [comment]
A mi me pasa como a ti getto, me tarda mas tiempo del debido en castearlo aunque digan que no, es simplemente verlo en la barra de cast o contar el tiempo del lanzamiento con un cronometro xD

Un saludo.

**Comment by DatJetto** [comment]
Ese delay ocurre incluso en el oficial, varios Azules han comentado en respecto a eso.
Aquí os dejo uno:
 This is also good time to clear up some of the confusion about hunter shot cast times. Essentially, ranged attacks in World of Warcraft have always had a built in 0.5 second delay to their cast time. Since this does not apply to instant attacks, for hunters it only really applies to Aimed Shot, Steady Shot and Cobra Shot. Prior to the 4.0.6 changes, Aimed Shot was listed with a 3.0 cast time, but due to the delay, in reality it had a cast time that amounted to 3.5 seconds. Now that it is listed at 2.4 seconds, the actual cast time is now closer to 2.9, which is where we want it to be. We realize this caused some confusion (even for us), and we’re going to see if we can make the 0.5 second delay more visible in the future.

Que es lo que ocurre en el server.

http://us.battle.net/wow/en/forum/topic/2112373390?page=4#72

**Comment by Dekadencee** [comment]
Creo que ya está fix, compilo y confirmamos

**Comment by Dekadencee** [comment]
Fixed
