### ISSUE TITLE
[Sacerdote] Fuego interno

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#4820]
ID: 48168
No está dando armadura extra
![image](https://cloud.githubusercontent.com/assets/3939699/6929186/302ffb6a-d7f9-11e4-8124-56b4386b4c55.png)

![image](https://cloud.githubusercontent.com/assets/3939699/6929212/5bbfb2ca-d7f9-11e4-9691-f7b1c637812e.png)

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, ya no daremos soporte al actual
