### ISSUE TITLE
bug chaman 8232

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#483]
la habilidad http://es.wowhead.com/spell=8232 salta solo 2 veces extra cuando la descripcion dice claramente que salta 3 veces.

<a href="http://tinypic.com?ref=5yu3cy" target="_blank"><img src="http://i44.tinypic.com/5yu3cy.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

un saludo

**Comment by searum** [comment]
fix
