### ISSUE TITLE
bug chaman 77657

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#485]
cuando un chaman pega con http://es.wowhead.com/spell=60103 el dps aumenta hasta el 100% con 5 http://es.wowhead.com/spell=77657 en el odjetivo ,este dps extra no se realiza,pega lo mismo con o sin ellos.

siendo la habilodad principal del mejora es una bajada de dps  importantisima ,para hacer viable la rama hay que arreglar esto.

lo que nose si es problema de http://es.wowhead.com/spell=60103 o http://es.wowhead.com/spell=77657 o del talento que no encuentro la id en wow head pero dejo una foto.
ya lo encontre el talento http://old.wowhead.com/spell=77701

<a href="http://tinypic.com?ref=fyoljt" target="_blank"><img src="http://i39.tinypic.com/fyoljt.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

un saludo

**Comment by Wiinter** [comment]
Sino encuentras la spell en http://es.wowhead.com. Prueba con http://old.wowhead.com está en inglés por tanto tendrás que hacer las búsquedas en inglés pero salen los talentos antiguos y todo lo que se ha quitado con las versiones posteriores.

**Comment by 50megas** [comment]
ya lo encotre con el traductor de ingles  xd, editado

**Comment by searum** [comment]
fix
