### ISSUE TITLE
bug en barrera reactiva, mago frost.

### ISSUE THREAD

**Issue by Devyal** [RoDNet/Bugtracker-Infinium-4.3.4#4854]
se activa correctamente al tener 50% de la vida, sin embargo si el daño no es suficientemente alto como para romper la barrera sigue lanzandose una y otra vez y solo debe lanzarse una sola vez, gracias.

**Comment by efectokoleos** [comment]
Arreglado en el nuevo emu, ya no daremos soporte al actual
