### ISSUE TITLE
Bug mision DK: No se puede continuar no dan mas misiones y no salimos

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#488]
Se completa la mision:

Apocalipsis escarlata http://es.wowhead.com/quest=12778

y el rey exanime ya no nos da mision nos quedamos atascados deveria darnos:
Un final para todas las cosas...
http://es.wowhead.com/quest=12779

que tienes que ir con un dragon matando gente y balistas

![wowscrnshot_071513_140251](https://f.cloud.github.com/assets/4893907/797407/8185005e-ed46-11e2-9156-acef0b1aa67e.jpg)

**Comment by harrypaqueton** [comment]
a mi me pasa lo mismo frustrix nada que hacer no podemos coger mision
![wowscrnshot_071513_155949](https://f.cloud.github.com/assets/4949764/797989/24e2e6b6-ed57-11e2-86be-846ec59bf514.jpg)
 por cierto los enemigos que hay bastantes son elites y no veas la que dan
![wowscrnshot_071513_162501](https://f.cloud.github.com/assets/4949764/798130/6df71536-ed5a-11e2-9054-3a1ccd70aceb.jpg)

**Comment by frustrix** [comment]
Solucionado muchas gracias a Bofur
