### ISSUE TITLE
Mob Uñagrieta Envejecido (Nagrand)

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#490]
Los uñagrietas envejecidos aparecen en el terreno pero como cadáveres, y como es lógico no son matables para varias misiones, aunque si se mueven por el terreno sin animación alguna.

http://es.wowhead.com/npc=17133

**Comment by crowel** [comment]
Fix, tras el reinicio o caída deberian salir vivos y también poder atacarles.
