### ISSUE TITLE
[ Ingeniería > Artilugios ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#492]
- Asesino de cartón: http://es.wowhead.com/spell=84425
- Campo de invisibilidad: http://es.wowhead.com/spell=84424
- Escudo de plasma: http://es.wowhead.com/spell=84427
- Inyector de sanación: http://es.wowhead.com/spell=82200
- Placas de desvío: http://es.wowhead.com/spell=82177
- Tragamaná Z50: http://www.wowhead.com/spell=82201
- Muelles de sinapsis: http://es.wowhead.com/spell=82175
  Estos muelles dependen del atributo primario de cada Clase y Especialización; dejo aquí las specs y el atributo que llevan.

---
- Muelle de sinapsis; Warrior, Dk, Paladin ( Prote , Repre )
- http://es.wowhead.com/spell=96229
- Muelle de sinapsis; Hunter, Shaman ( Enhace ) , Rogue, Druid ( Feral )
- http://es.wowhead.com/spell=96228
- Muelle de sinapsis; Pala ( Holy ), Shaman ( Eleme, Resto ), Druid ( Balance, Resto ) Mage, Warlock, Priest
- http://es.wowhead.com/spell=96230

**Comment by redneo** [comment]
Vale... el problema con esos items es que??

No se pueden conseguir (algunos necesitan recetas de ingenieria altas para que salgan)

No funcionan?

**Comment by DatJetto** [comment]
Claro, la cosa es que no funcionan. XD

**Comment by crowel** [comment]
Añado https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/85
Un saludo.

**Comment by redneo** [comment]
funcionan todos, aunque creo que el tragamana tendria que hacer algo mas, que no he descubierto aun
