### ISSUE TITLE
[Set pvp de conquista #DK]

### ISSUE THREAD

**Issue by keinting** [RoDNet/Bugtracker-Infinium-4.3.4#493]
EL vendedor de puntos de conquista no vende el set como tal del DK

El set que deberia vender es este: 

http://es.wowhead.com/itemset=-348

El vendedor es este: 

http://es.wowhead.com/npc=54658/sargento-tronacuerno

**Comment by DatJetto** [comment]
¿Qué set vende actualmente?

**Comment by keinting** [comment]
actualmente solo vende los accesorios del implacable

**Comment by redneo** [comment]
Podías poner todos los set de dk- mañana lo pongo

**Comment by redneo** [comment]
Puesto en la alianza y en la horda npcs 52549 horda y 52546 Alianza
