### ISSUE TITLE
[ Bug de movimientos ] No prioritario

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#494]
Cuando montas en una montura a veces se bugean los movimientos del pj y te quedas con pose de invocar montura: 
![wowscrnshot_071513_133316](https://f.cloud.github.com/assets/2728817/798025/e58329da-ed57-11e2-8b1b-0e3fb46be591.jpg)

Y si cambio de aspecto mientras estoy en montura se queda con la mano hacia delante xD
![wowscrnshot_071513_133350](https://f.cloud.github.com/assets/2728817/798028/f6bc81ce-ed57-11e2-9028-edeea363e401.jpg)

![wowscrnshot_071513_133331](https://f.cloud.github.com/assets/2728817/798034/040943c6-ed58-11e2-9929-3a7697dddd2d.jpg)

**Comment by ghost** [comment]
A mi me pasa siempre. Además, si vas en una voladora y desmontas en el suelo, si no te mueves no podrás castear nada, dice que estás en movimiento y es mentira xD.

**Comment by ghost** [comment]
Si, ese bug molesto al desmontar que no puedes hacer nada porque "estas en movimiento" lo han arreglado ya en el "server aliado", ¿no pueden "robar" el fix? xd.

**Comment by Kiritoo** [comment]
Llevo un rato probandolo y ya parece arreglado con el fix de las animaciones del otro día.
