### ISSUE TITLE
[ Depósito del vacío bug ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#495]
Tras el rollback, las mochilas únicas y los items que contenían en el banco llegaron a mi buzón, de manera que aproveché el depósito del vacío para introducir mis sets de transfiguración y armas etc, para quitar espacio de mi banco, la sorpresa me la he llevado hoy cuando sólo había 2 arcos en el depósito, cuando tenía en él más de 30 items xD 

![wowscrnshot_071513_115444](https://f.cloud.github.com/assets/2728817/798056/92a60362-ed58-11e2-8ce4-cac418fe1ee2.jpg)

Algunas cosas de las que tenía eran: 

Set colérico
Partes de T8
T9
Partes de T10
T5
Sanguinario
Armas de ulduar

Y demás, tenía casi la mitad del depósito ocupado.

**Comment by Velcositro** [comment]
Tantas cosas perdidas y lo dices tan tranquilo... XD, yo fuí a revisar mi depósito cuando leí esto y por suerte todo sigue en su lugar, asi que el error debe ser algo bastante específico.

**Comment by Compresor** [comment]
Las cosas no están perdidas, solo ocultas. Todos los objetos estan en la db

**Comment by Dekadencee** [comment]
Fixed
