### ISSUE TITLE
Tres de mi casador xD 

### ISSUE THREAD

**Issue by sherik12** [RoDNet/Bugtracker-Infinium-4.3.4#5]
![ferno](https://f.cloud.github.com/assets/4358923/746591/ed839dec-e431-11e2-9b04-40a9778e14d0.jpg)

**Comment by crowel** [comment]
A mi me aparecen 6 o 7 y 20 dks.

**Comment by lamaza** [comment]
Diria E. Durkheim que fue una reproducción natural nativa exitosa en un medio ambiente inestable, prueba de la adaptación humana XD.

**Comment by ghost** [comment]
Me pasa exactamente lo mismo con mi DK

**Comment by crowel** [comment]
A mi ya me salen bien sin estar multiplicados.
