### ISSUE TITLE
[Chaman] Descarga de Relampagos BUG

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#50]
Un chaman en bg me ha pegado 120k con descarga de relampagos, lo mas ironico es que el chaman iba de heal y con equipo verde.

![wowscrnshot_070413_000618](https://f.cloud.github.com/assets/4895839/747598/55491c4e-e46a-11e2-9555-918a3838b74f.jpg)

**Comment by miglent** [comment]
Le corrijo: sume casi 120k, más 180k resistido, más 1503k de sobrecapacidad: 1'800.000 en un golpe!

**Comment by SherBlader** [comment]
me desbarataron mejor dicho, el caso fue que me mato de 1 golpe xD
gracias por la correccion mig :+1:
