### ISSUE TITLE
[BUG GENERAL] Con poderes/talentos/glifos

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#501]
Buenas, he visto ahora que con cualquier glifo, o talento cuando usas poderes, te saltan.

Me explico más detalladamente porque no sabía como explicarlo arriba jajaja

Ejemplo:

Un picaro con  [Glifo de Puñalada] -> [No encuentro el link del glifo]
que debería dar 5 puntos de energía cada vez que asestamos un golpe crítico con ese poder, nos da 5 puntos de energía sea o no crítico y también con cualquier otro poder que de un golpe, aquí os dejo la imagen.

![wowscrnshot_071513_181406](https://f.cloud.github.com/assets/3328374/798867/a05524dc-ed69-11e2-9431-674adf31a948.jpg)

También un mi sacerdote sombras con el talento: 
 [Sombras dominadas] -> http://old.wowhead.com/spell=78228
Que debería darte un orbe de sombras cada vez que recibes un golpe critico, y te da uno por cada golpe.

**Comment by searum** [comment]
fixeados los dos
