### ISSUE TITLE
[BUG] Efecto DOT glifo hemorragia [Pícaro]

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#502]
El glifo de pícaro de hemorragia que provoca un sangrado en el objetivo, salta tanto con puñalada como con emboscada:
![wowscrnshot_071513_174444](https://f.cloud.github.com/assets/3328374/799009/4cd016e8-ed6c-11e2-8fd1-27f8984f41be.jpg)

![wowscrnshot_071513_174454](https://f.cloud.github.com/assets/3328374/799011/5138ed54-ed6c-11e2-8a99-7e4f9af75a2e.jpg)

El glifo aunque no venga ni que es primordial ni el daño que debería meter correctamente es el siguiente:
http://www.wowhead.com/item=42967

**Comment by searum** [comment]
vale esto ya esta solucionado, lo cierro :)
