### ISSUE TITLE
Bug Ultimas misiones DK

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#503]
Despues de recibir el hechizo del porton de la muerte tenemos que usarlo y hablar denuevo con darion en el bastion y completar la mision RECUPERAR ACHERUS

http://es.wowhead.com/quest=13165

Pero no da la Opcion:

![wowscrnshot_071513_214709](https://f.cloud.github.com/assets/4893907/800393/7b43da7a-ed88-11e2-8101-efd610481ebd.jpg)

y deberia dar el resto de misiones citadas a continuacion para poder terminar y salir con el DK de esta zona

![wowwow](https://f.cloud.github.com/assets/4893907/800402/ad5c0136-ed88-11e2-8ac7-87937ae211f8.png)

saludos

**Comment by redneo** [comment]
arregladas Frux... cierra los tickets!!!!
