### ISSUE TITLE
[CAZADOR] skill de cazador bug

### ISSUE THREAD

**Issue by Edwuard** [RoDNet/Bugtracker-Infinium-4.3.4#504]
la skill para invocar la pet del cazador no funciona, por lo que para llamar la pet ay q relogear.

saludos

**Comment by searum** [comment]
funciona perfectamente, tal vez sea algun npc que no puedes tamear o algo... pero si funciona bien

**Comment by Edwuard** [comment]
a mi me pasa lo msimo, empese con un humano cazador y la barra de skill de la pet no aparece al relogear la pet desaparece y no se puede llamar...
