### ISSUE TITLE
Guilneas y enanos

### ISSUE THREAD

**Issue by D3VIL238** [RoDNet/Bugtracker-Infinium-4.3.4#506]
Guilneas esta entera bugueada,no hay NPC para completar las misiones,y no aparecen enemigos,ademas,los enanos al principio hay misiones que no se pueden completar ,por ejemplo siendo paladín la que te piden que uses sentencia en los muñecos de prueba

**Comment by searum** [comment]
Vale, lo de gilneas lo entiendo.. en eso estamos trabajando. Sobre lo de los enanos no seria mas facil que reportes las misiones que no funcionan como es debido? Cierro el issue porque este reporte no esta bien.
