### ISSUE TITLE
[Talentos] Druida Estampida.

### ISSUE THREAD

**Issue by Huardruid** [RoDNet/Bugtracker-Infinium-4.3.4#51]
El talento: Estampida esta bug

http://old.wowhead.com/spell=78893

Al usar carga feral, se ve que se resalta indicando que lo debes usar pero esta en negro y no lo puedes usar.

[IMG]http://i.imgur.com/zoIuPhd.jpg[/IMG]

**Comment by searum** [comment]
fix =)
