### ISSUE TITLE
[Paladin] Sello de Rectitud

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#510]
http://es.wowhead.com/spell=20154/sello-de-rectitud

esta pegando el doble de lo que deberia
![wowscrnshot_071513_184936](https://f.cloud.github.com/assets/3101842/801586/22b6a460-eda5-11e2-93bf-2465cc10fba8.jpg)
![wowscrnshot_071513_184944](https://f.cloud.github.com/assets/3101842/801591/30956d8c-eda5-11e2-8e28-6b0080288f62.jpg)

le pego 1709 al dummy y segun el DrDamage deberia de pegar 715 max total

**Comment by searum** [comment]
FIX!
