### ISSUE TITLE
[Paladin] Sentencia y Sellos

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#511]
http://es.wowhead.com/spell=20271/sentencia

Sentencia es un skill para desartar la energia de un sello
el caso solo eso deberia de desatar el sello pero no hacer el efecto normal del sello es decir sello de rectitud tiene un daño que se activa pasivamente con ataques cuerpo a cuerpo y el otro que se activa con sentencia

Ps al usar sentencia los 2 daño de sello de rectitud se activan y solo deberia de ser el daño de desartar la energia del sello

![wowscrnshot_071513_190141](https://f.cloud.github.com/assets/3101842/801639/c3ac6304-eda6-11e2-8d6b-8643699b12e0.jpg)

otro bug por alguna razon lanzo una sentencia y al objetivo le llegan 2
![wowscrnshot_071513_190145](https://f.cloud.github.com/assets/3101842/801645/ec29d762-eda6-11e2-8547-cf47090ded15.jpg)

**Comment by F4NT4SM4** [comment]
es un bug bastante grave ya que al terminar la bg siempre en el recount miro y el sello de rectitud hace siempre todo el daño...

**Comment by searum** [comment]
el sello de rectitud pega con ataques melee y con spells que requieran arma melee... es decir, es como un 2º efecto.. al usar la sentencia pega una vez con sentencia y otra con el sello como si golpearas a melee.

**Comment by F4NT4SM4** [comment]
la sentencia no es un ataque mele solo deberia de hacer el daño de desatar mas no el efecto pasivo del sello
y como sentencia esta pegando 2 veces son en total 4 golpes que da 2 de desatar y 2 pasivo

**Comment by F4NT4SM4** [comment]
acabo de usar 1 sola sentencia y salieron 8 golpes....
![wowscrnshot_071713_121134](https://f.cloud.github.com/assets/3101842/813329/e1c0b764-eeff-11e2-831a-22cdaa5a9ff1.jpg)

**Comment by searum** [comment]
Ya se que no es un ataque melee, lee lo que te he dicho...

  02 Successful melee attack
  04 Successful attack by Spell that use melee weapon

para que me entiendas, salta con un ataque melee que golpee y con un ataque de una spell que requiera un arma melee (Sentencia es una spell que requiere un arma melee por tanto hace que se active el sello).

**Comment by F4NT4SM4** [comment]
la sentencia no requiere arma solo requiere un sello para desatar el poder del sello 

![wowscrnshot_071713_124428](https://f.cloud.github.com/assets/3101842/813541/56d2dbfa-ef04-11e2-8219-dcfb43acd738.jpg)

**Comment by searum** [comment]
bueno lo mirare pero yo te lo digo por los datos que estoy viendo en el spellwork...

**Comment by F4NT4SM4** [comment]
la sentencia sigue estando buggggggggg :C
