### ISSUE TITLE
Dk Recuperar Acherus DK mision

### ISSUE THREAD

**Issue by willdex** [RoDNet/Bugtracker-Infinium-4.3.4#512]
La siguiente misión es del portón de la muerte lo cual te pide usarlo para volver al bastión de acherus para hablar con un npc... pues lo use me teletransporto y no encuentro ningun npc en el bastión ni fuera del mismo..

**Comment by Dekadencee** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/503 Reporte repetido, lo seguimos desde el anterior
