### ISSUE TITLE
Mision Terralende bug: Fortificaciones del fuego infernal

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#513]
Mision:
http://es.wowhead.com/quest=13410/fortificaciones-del-fuego-infernal

![wowscrnshot_071613_105829](https://f.cloud.github.com/assets/4893907/803583/4848b366-edf6-11e2-8c5c-440256fe641d.jpg)

Es una mision que requiere capturar las banderas JcJ y las banderas no te deja actuar con ellas

![wowscrnshot_071613_105815](https://f.cloud.github.com/assets/4893907/803579/415c7c54-edf6-11e2-9b0c-c4d223b93b76.jpg)

**Comment by ghost** [comment]
Las banderas para que pasen hacia tu bando(horda/alianza), necesitan que estés bajado de la montura xD

Prueba así y si sigue el problema, sí que está bug, pero vaya, que tienes que estar a pata para que empiece a moverse el contador hacia tu bando para capturar la bandera.

**Comment by crowel** [comment]
Probada la misión y funciona correctamente, ahora acabo de capturar el Estadium.
Debo añadir que para poder capturar estos puntos debes tener activado el JcJ, el propio juego te lo avisa al llegar a la zona de las banderas, arriba un mensaje en rojo.
Cierro Issue, un saludo.
