### ISSUE TITLE
Mision Terralende Bug: Machacando al Enemigo

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#514]
Mision:
http://es.wowhead.com/quest=10078/machacando-al-enemigo
![wowscrnshot_071613_110404](https://f.cloud.github.com/assets/4893907/803616/16551060-edf7-11e2-992a-e77fff79467c.jpg)

Con una antorcha que te proporcionan tienes que quemar los lanzacuchillos de la horda pero no te dejan interactuar con ellos para lanzar la antorcha

![wowscrnshot_071613_110424](https://f.cloud.github.com/assets/4893907/803619/1fee837c-edf7-11e2-9f9f-a09c2f85c4c4.jpg)

**Comment by searum** [comment]
fix
