### ISSUE TITLE
bug abalorios  de poder con hechizos

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#515]
hola, parece que hay un bug, que hace que los abalorios quedan poder con henchizos ,solo dan sanacion con hechizos,una gran desventaja para dps caster

los 2 abalorios que tengo:

de este no encuetro la id:

<a href="http://tinypic.com?ref=fnbhx1" target="_blank"><img src="http://i39.tinypic.com/fnbhx1.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

<a href="http://tinypic.com?ref=2qbf828" target="_blank"><img src="http://i41.tinypic.com/2qbf828.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

el 2º http://es.wowhead.com/item=65053

<a href="http://tinypic.com?ref=5mbu2t" target="_blank"><img src="http://i40.tinypic.com/5mbu2t.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

<a href="http://tinypic.com?ref=2vu0r2s" target="_blank"><img src="http://i41.tinypic.com/2vu0r2s.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

como se puede apreciar los abalorios cuanda saltan el bonus solo dan poder de curacion, cuando deveria ser poder con hechizos

un saludo

**Comment by searum** [comment]
fiiiiiiiiiix
