### ISSUE TITLE
[BUG] Reputaciones a 0

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#517]
Lo puse en el foro mientras estábamos en la 4.0.6 hace ya unos meses, y no se solucionó, así que lo pongo aquí a ver si se puede dar solución al problema.
Mi post: http://www.reignofdarkness.net/wow/foros/t985/
Otro post que he visto del mismo estilo: http://www.reignofdarkness.net/wow/foros/t1127/

Desde hace tiempo, exactamente no me acuerdo qué día, se me bajaron a mi las reputaciones a 0 con mi druida y por ejemplo a un amigo mío creo que con su mago(Bicarbonato) o con otro pj también, y a más gente igual.

Os dejo la captura para que veáis que tengo los logros de varias repus de Cataclysm y que las tengo a 0 y no puedo usar los objetos que tengo :S 

![wowscrnshot_071613_142302](https://f.cloud.github.com/assets/3328374/804591/53f97c14-ee13-11e2-867d-783cb5a18abc.jpg)

Espero que tenga solución. Un saludo.

**Comment by Dekadencee** [comment]
Solicita a un MJ que te entregue de nuevo las reputaciónes, este error está solventado en la 4.3.4 no las perderás de nuevo.

Disculpa las molestias
