### ISSUE TITLE
[Vendedor] Equipo incansable

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#518]
Faltan aún de incorporar los set de brujo, mago, sacerdote(son 2) y pícaro.

Os pongo los id de los item a continuación:
## SET BRUJO

Manos -> 70314 http://es.wowhead.com/item=70314
Casco -> 70315 http://es.wowhead.com/item=70315
Piernas -> 70316 http://es.wowhead.com/item=70316
Pechera -> 70317 http://es.wowhead.com/item=70317
Hombro -> 70318 http://es.wowhead.com/item=70318
## SET MAGO

Manos -> 70299 http://es.wowhead.com/item=70299
Casco -> 70300 http://es.wowhead.com/item=70300
Piernas -> 70301 http://es.wowhead.com/item=70301
Pechera -> 70302 http://es.wowhead.com/item=70302
Hombro -> 70303 http://es.wowhead.com/item=70303
## SET SACERDOTE(HEAL)

Manos -> 70304 http://es.wowhead.com/item=70304
Casco -> 70305 http://es.wowhead.com/item=70305
Piernas -> 70306 http://es.wowhead.com/item=70306
Pechera -> 70307 http://es.wowhead.com/item=70307
Hombro -> 70308 http://es.wowhead.com/item=70308
## SET SACERDOTE(DPS)

Manos -> 70309 http://es.wowhead.com/item=70309
Casco -> 70310 http://es.wowhead.com/item=70310
Piernas -> 70311 http://es.wowhead.com/item=70311
Pechera -> 70312 http://es.wowhead.com/item=70312
Hombro -> 70313 http://es.wowhead.com/item=70313
## OFF SET TELA

Pies -> 
70361 http://es.wowhead.com/item=70361
70364 http://es.wowhead.com/item=70364
70367 http://es.wowhead.com/item=70367

Cintura -> 
70369 http://es.wowhead.com/item=70360
70362 http://es.wowhead.com/item=70362
70368 http://es.wowhead.com/item=70368

Muñeca -> 
70363 http://es.wowhead.com/item=70363
70365 http://es.wowhead.com/item=70365
70366 http://es.wowhead.com/item=70366
## SET PÍCARO

Manos -> 70295 http://es.wowhead.com/item=70295 
Casco -> 70296 http://es.wowhead.com/item=70296
Piernas -> 70297 http://es.wowhead.com/item=70297
Pechera -> 70294 http://es.wowhead.com/item=70294
Hombro -> 70298 http://es.wowhead.com/item=70298
## OFF SET PÍCARO

Pies -> 
70348 http://es.wowhead.com/item=70348
70351 http://es.wowhead.com/item=70351

Cintura -> 
70347 http://es.wowhead.com/item=70347
70349 http://es.wowhead.com/item=70349

Muñeca -> 
70350 http://es.wowhead.com/item=70350
70352 http://es.wowhead.com/item=70352

Que yo sepa está todo correcto y no me dejo ninguna clase, ya que el resto he mirado y he visto los set y los offset. Un saludo.
## PRECIOS

Manos -> 1650
Casco -> 2200
Piernas -> 2200
Pechera -> 2200
Hombro -> 1650
Pies -> 1650
Cintura -> 1650
Muñeca -> 1250

**Comment by redneo** [comment]
los set estan metidos, a la espera de precios de los demas

**Comment by ghost** [comment]
No lo cierres porque aún no están los offset que te puse. Y los precios los tienes desde hace tiempo también :P
