### ISSUE TITLE
Paramos de Poniente

### ISSUE THREAD

**Issue by D3VIL238** [RoDNet/Bugtracker-Infinium-4.3.4#519]
Faltan los NPC de la entrada,en la Finca de Jansen
![wowscrnshot_071613_160612](https://f.cloud.github.com/assets/4938161/805136/410751b8-ee21-11e2-8a9c-cfc8d8a3f39a.jpg)

**Comment by crowel** [comment]
Hola jaja muy bueno el reporte.
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/455
Aqui el mismo ya reportado y con la informacion necesaria.
Un saludo.

**Comment by D3VIL238** [comment]
No sabia que ya estaba reportado,cierro entonces
