### ISSUE TITLE
[Errores Internos] Mana del sacerdote

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#520]
Hola queria hacer un comentario sobre el mana del sacerdote.

![1](https://f.cloud.github.com/assets/3537253/805532/85c22ec0-ee28-11e2-8810-351c39ae61e9.jpg)

Como podeis apreciar en la imagen, con mi sacerdote a nivel 85 sin armadura se puede ver mi mana base que son 23400 puntos.

![3](https://f.cloud.github.com/assets/3537253/805539/b7b60f0a-ee28-11e2-9f35-0979ceaa0c11.jpg)

Como se comprueba en esta segunda imagen mi mana con la armadura al completo equipada aumenta a 88410 puntos.

![2](https://f.cloud.github.com/assets/3537253/805545/ef1ed3dc-ee28-11e2-96f0-33b76bf1d5bf.jpg)

Ahora a la parte que quería llegar, poniendo el cursor sobre el intelecto de mi personaje para comprobar el mana que corresponde al intelecto que tengo veo lo siguiente:
Aumenta el mana 67820 puntos.
Así que decidí hacer la suma que en total da alrededor de unos 3000 puntos mas que debería tener.

Mi pregunta es ¿ Quizas los puntos de intelecto no estan dando el mana que corresponde ? ¿O puede que mi teoria no sea totalmente cierta y se aplique de otra manera?

Espero que alguien pueda sacarme de mi duda.

Gracias y un saludo.

**Comment by F4NT4SM4** [comment]
revisa sin talentos

**Comment by crowel** [comment]
![wowscrnshot_071613_174327](https://f.cloud.github.com/assets/3537253/805858/b2933772-ee2e-11e2-85c9-698a943338bc.jpg)

Es exactamente lo mismo, la subo igualmente aunque no tiene nada que ver, por eso ya comente que nosé exactamente si el problema de mana vendrá del intelecto/mana.

Saludos.

**Comment by crowel** [comment]
Vale acabo de hacer el calculo de intelecto x puntos de mana y está correcto.
Que extraño.

**Comment by ghost** [comment]
Si, yo ya hice calculo de mana por intelecto y esta todo bien xd, lo que hay que calcular es la ira de los guerreros, regeneran mucho de un golpe.

**Comment by crowel** [comment]
Parece que está bien tras varios calculos.
Cierro un saludo.
