### ISSUE TITLE
[DK] Fiebre de Escarcha

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#521]
http://es.wowhead.com/spell=59921/fiebre-de-escarcha

Esta pegando muy poco 45 al dummy y segun mi DrDamage deberian ser 961 por tick

![wowscrnshot_071613_110814](https://f.cloud.github.com/assets/3101842/805833/39186426-ee2e-11e2-9c53-2a03a0540a77.jpg)
![wowscrnshot_071613_110822](https://f.cloud.github.com/assets/3101842/805835/4342f1d2-ee2e-11e2-8db3-dc9f2f843bda.jpg)

**Comment by DatJetto** [comment]
A ver si reportamos también lo over!!

**Comment by searum** [comment]
creo q ya esta pero a mi el DrDamage y esas chorradas que usais no me valen de nada, quiero formulas y tal... no chorradas que se inventa un addon mal hecho
