### ISSUE TITLE
[NPC] Oratio Laine Páramos de poniente

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#523]
Falta el NPC de Páramos de poniente Oratio Laine 
http://es.wowhead.com/npc=42308

Si no está él, no se puede entregar la misión: 
[Se busca héroe: ¡Páramos de Poniente!] -> http://es.wowhead.com/quest=28562

Tampoco se puede entregar la misión 
[Las escrituras de Cejade] -> http://es.wowhead.com/quest=184

Por lo tanto ni se pueden entregar esas 2 misiones ni se pueden seguir cogiendo las demás :S

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/455

**Comment by redneo** [comment]
Ya tendria que salir
