### ISSUE TITLE
El Poder de la Luz, misión esencial paladín bug

### ISSUE THREAD

**Issue by D3VIL238** [RoDNet/Bugtracker-Infinium-4.3.4#524]
La misión inicial de Paladín el poder de la luz esta bug y no se puede continuar en el juego,ya que es esencial para que te den las siguientes,por mucho que te eches sello de rectitud sobre ti mismo y le des con sentencia a un muñeco de practicas no se completa la misión 

-Link de la misión-  http://es.wowhead.com/quest=26918/el-poder-de-la-luz

**Comment by redneo** [comment]
tendria que ir ya
