### ISSUE TITLE
Recompensas buscador de mazmorras

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#525]
Las imagenes que pongo son de como estan ahora las recompensas.

Mazmorra aleatoria (normal) debería de dar 150 puntos de justicia, ahora mismo no da nada.
![aleatoria](https://f.cloud.github.com/assets/4663665/808472/d94e2ddc-ee64-11e2-956d-2dfeae03167b.jpg)

Mazmorra aleatoria heroica debería de dar 150 puntos de valor, hasta 7 veces en una semana, luego debe de dar 150 puntos de justicia.
![heroica](https://f.cloud.github.com/assets/4663665/808474/db2d54de-ee64-11e2-98f4-26f5fc748447.jpg)

Mazmorra aleatoria heroica hora del crepusculo debería de dar 150 puntos de valor, hasta 7 veces en una semana, luego debe de dar 150 puntos de justicia.
![heroica crepusculo](https://f.cloud.github.com/assets/4663665/808473/d9d0907e-ee64-11e2-98d4-4a4efa1e63f6.jpg)

Fuentes: http://www.wowpedia.org/Dungeon_Finder
http://us.battle.net/wow/en/blog/3615104

**Comment by Dekadencee** [comment]
¿Con "hasta 7 veces en una semana" te refieres a 1 vez al dia verdad?

**Comment by ghost** [comment]
Nop, a partir del parche 4.1 cambiaron lo de "1 vez al dia", por ejemplo: puedes hacer 7 veces mazmorras aleatorias heroicas, y las 7 veces te darán la recompensa, pero luego de esas 7 veces tendrás que esperar hasta la siguiente semana para poder volver a obtener las recompensas de valor.

http://eu.battle.net/wow/es/blog/9984237/#dungeons
"Ahora los jugadores obtendrán recompensas extra 7 veces por semana (mientras ganen menos de 980 puntos de valor) en vez de una vez al día al usar el buscador de mazmorras."

**Comment by Dekadencee** [comment]
Mazmorra aleatoria heroica hora del crepusculo despues de las 7 veces debería dar 140 puntos de justicia segun wowhead: http://es.wowhead.com/quest=29183

**Comment by ghost** [comment]
A partir del parche 4.3 todas las mazmorras heroicas fueron cambiadas para que den 150 puntos, esta en el segundo enlace que deje.

Changes coming in 4.3:
Looking for Dungeon -- 150 VP per run, with a cap of seven runs per week. All Cataclysm heroic dungeons introduced in 4.0, 4.1, and 4.3, will provide 150 Valor per run.

**Comment by Dekadencee** [comment]
Si, esas si, me refiero a despues de completarlas las 7 veces, segun wowhead, son 140 puntos de justicia, no 150

**Comment by ghost** [comment]
Ah bueno, entonces 140 puntos de justicia xd, ¿puedes agregar las carteras también? (son de mazz lvl bajo).

**Comment by Dekadencee** [comment]
Y en el caso de la heroica cataclysm, al completarla mas de 7 veces, 70 puntos de justicia:
http://es.wowhead.com/quest=28906

**Comment by ghost** [comment]
Lo de la heroica cataclismica era una supusición de que deberían de ser 150 puntos de justicia (ahora que lo dices 140) para equiparar con las otras, por el cambio que hicieron de los 150 puntos de valor.

**Comment by Dekadencee** [comment]
Y respecto a la normal:

Cataclysm Patch 4.0.6 (2011-02-08): Level-85 players can now choose any normal dungeon via the Dungeon Finder. Choosing Random Dungeon will still not add Blackrock Caverns or Throne of the Tides into the rotation.

```
The daily Random Dungeon reward on normal difficulty has been increased to 140 Justice Points, up from 70.
```

**Comment by ghost** [comment]
A ver.. esos son notas del parche 4.0.6 ya estamos unos cuantos más para arriba xd.

según esto http://www.wowpedia.org/Justice_Points

Cataclysm (80-85) Normal/heroic random dungeon  150 Justice Points

A ver si encuentro algo más "oficial".

**Comment by Dekadencee** [comment]
Fixed, si hay algun problema con otra abrid nuevo reporte, estas tres quedan fixeadas ^^

**Comment by ghost** [comment]
Oks, muchisimas gracias Deka =).
