### ISSUE TITLE
[Mision Diaria] Drottinn Hrothgar

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#527]
La mision diaria Drottinn Hrothgar http://es.wowhead.com/quest=14101/drottinn-hrothgar 
de Corona de hielo no se puede hacer ya que al invocar a Drottinn Hrothgar http://es.wowhead.com/npc=34980/drottinn-hrothgar

NO se le puede pegar
![wowscrnshot_071713_010459](https://f.cloud.github.com/assets/4895839/810027/0dc641d4-eea7-11e2-96eb-81d82b01be2f.jpg)

**Comment by redneo** [comment]
ya se le puede atacar
