### ISSUE TITLE
[Mision Diaria] El destino de los caídos

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#528]
La mision diaria El destino de los caídos http://es.wowhead.com/quest=14107/el-destino-de-los-caidos

No se puede hacer ya que al recoger el cristal y usarlo en el espiritu de un heroe caido no sucede nada. (deberia darle paz y contar 1 heroe por cristal)

**Comment by redneo** [comment]
cuando caiga el server ira, he puesto mas cristales...
