### ISSUE TITLE
[Nucleo Petreo] Falta montura para revivir

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#529]
Cuando se muere en la mazmorra nucleo petreo, no sale la montura voladora para poder ir a la maz, lo que obliga a revivir con en angel y tener dolencia de 10 minutos..

Deberia haber una montura voladora cuando se esta muerto para poder llegar a la maz (esta arriba)
![wowscrnshot_071713_092220](https://f.cloud.github.com/assets/4895839/812262/bb9eb968-eeec-11e2-8b83-6133507a4efb.jpg)

**Comment by redneo** [comment]
Y la mazmorra, funciona correctamente?

**Comment by SherBlader** [comment]
@redneo  queria ir solo a farmear el draco, pero como la habilidad camuflaje esta bug, me imposibilita pasar los mobs
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/533

**Comment by searum** [comment]
fix
