### ISSUE TITLE
No se ve la hermandad de los personajes

### ISSUE THREAD

**Issue by Huardruid** [RoDNet/Bugtracker-Infinium-4.3.4#53]
Como podeis ver no se ve el nombre de hermandad.

[IMG]http://i.imgur.com/CYcDwiB.jpg[/IMG]

**Comment by SherBlader** [comment]
Tambien pasa en la horda 
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/7

**Comment by Dekadencee** [comment]
Reporte repetido, lo seguimos desde #7
