### ISSUE TITLE
[Portal] Portal De Infralar A Orgrimmar

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#530]
El portal que esta en infralar y que deberia llevar a orgrimmar no funciona, ya que al darle clic no sucede la accion.

![wowscrnshot_071713_092602](https://f.cloud.github.com/assets/4895839/812275/f67a216c-eeec-11e2-832f-2a790b4fe8a2.jpg)

**Comment by ghost** [comment]
También falta el portal para ir hasta el trono de therazane.
