### ISSUE TITLE
Límite semanal de arenas

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#532]
Hola quería comentar que hoy se ha vuelto reiniciar el límite semanal de arenas.
Esto no ocurría desde el viernes.
Esto ocurrio el miercoles y viernes de la semana pasada.
Enfin, llego a la conclusión de que en algun lado está fijado para reiniciarse estos dos días, pasado mañana viernes se sabria mejor si está teoría es válida. Porfavor comprobarlo cuando podaís me parece mucha coincidencia.

Un saludo.

**Comment by SherBlader** [comment]
El reinicio semanal de las arenas debe ser el miercoles (un miercoles se puso en funcionamiento el server) las raids, se reiniciaron hoy (miercoles), si vi que se reiniciaron el viernes, pero por ahi escuche que ya arreglaron eso.

**Comment by crowel** [comment]
Ojala sea como tu dices @SherBlader sería una gran noticia :)

**Comment by 50megas** [comment]
el bug sigue, se reiniciaron de nuevo hoy

**Comment by crowel** [comment]
Porfavor comprueben esto sino la gente se seguira armando poniendo la escusa "es que nosequien tiene 3 partes" y yo pensando tu te vas a tirar por un puente tambien?
Enfin creo que hasta se podrian desactivar estes puntos mientras tanto.
Un saludo.

**Comment by 50megas** [comment]
m.. lo del puente no lo pillo

**Comment by 50megas** [comment]
hoy de nuevo se reinicio,parece que se reinicaia cada dia

**Comment by searum** [comment]
fix
