### ISSUE TITLE
[Cazador] Camuflaje 

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#533]
La habilidad camuflaje http://es.wowhead.com/spell=51755/camuflaje Del cazador esta bug, ya que los mobs lo detectan la presencia del cazador como si no estuviera en camuflaje.

![wowscrnshot_071713_123130](https://f.cloud.github.com/assets/4895839/813707/bc66f872-ef07-11e2-9cf5-73a2e49cd4be.jpg)

![wowscrnshot_071713_123131](https://f.cloud.github.com/assets/4895839/813708/c25c9cf0-ef07-11e2-941f-4f0c74832384.jpg)

![wowscrnshot_071713_123132](https://f.cloud.github.com/assets/4895839/813709/c5b3f4f2-ef07-11e2-9d4c-90ceeb09cc7f.jpg)

He visto videos de cazadores que pasan todo eso hasta el draco en camuflaje y los mobs no le pegan..
´
Me pasa lo mismo con todos los mobs!

**Comment by searum** [comment]
Eso no es culpa de la spell, es culpa de los mobs me da a mi... lo miraremos.

Con players te pasa igual?

**Comment by ghost** [comment]
Con players no pasa, o sea... se le puede ver en movimiento (cosa que es así) pero no se le puede targetear hasta que se sale del camuflaje, funciona bien.

**Comment by searum** [comment]
entonces es como me temia un fallo del aggro de los npcs.. ya miraremos es que hay cosas mas importantes que esto ahora mismo..

**Comment by searum** [comment]
fix

**Comment by Jhovanni** [comment]
La habilidad está bien. Es un error pensar que los mobs no te detectarán, pues si lo hacen si te pones en movimiento, solo que reduce la probabilidad que suceda. La única manera en que no te detecten es si te quedas quieto, que es cuando te da sigilo; pero si te mueves, hay amenaza baja de tu parte y te pueden detectar.

**Comment by Jhovanni** [comment]
De hecho la habilidad dice: "reduce el alcance al que pueden detectarte las unidades enemigas", en ningún momento dice que seas indetectable.
