### ISSUE TITLE
[Mazmorra] Cumbres Del Vortice

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#534]
El Mob Mistral acorazado http://es.wowhead.com/npc=45915/mistral-acorazado#abilities

esta haciendo un daño abrumador en cumbres del vortice en normal

![wowscrnshot_071713_124419](https://f.cloud.github.com/assets/4895839/813782/fd0e2b4c-ef08-11e2-9703-c50861962c55.jpg)

Con un ataque automatico a mi pet tanque le infringe 52.402
y con la habilidad Golpe de vendaval le infringe 107.878 (que es la salud de la pet)
http://es.wowhead.com/spell=88061

Por favor arreglar el mob que me interesa ir a farmear el draco de la maz en normal!

**Comment by efectokoleos** [comment]
el daño esta arreglado
