### ISSUE TITLE
[Npc] Ankha

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#535]
http://es.wowhead.com/npc=54318

el npc no se encuentra en la zonas ubicadas ya he buscado por todas partes con la habilidad del caza de rastrear bestias 
es una pet exotica domable para caza

**Comment by redneo** [comment]
Los npcs raros tienen un respawn de dos horas, a parte, hay una cantidad de rares por el mundo, de ahi su nombre, si esta el npc a en el mundo, no lo estará el b, el c y el d.
