### ISSUE TITLE
[Raid] ICC 10 Normal

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#536]
El primer boss Lord Tuétano http://es.wowhead.com/npc=36612 falta revisar/bajarle el daño, nos sacaba entre 100k y 200k de vida a todos en forma simultanea, también su golpe automatico que baja como 50k.

La batalla naval no funciona, no se puede activar, faltan los npcs.
![wowscrnshot_071713_174452](https://f.cloud.github.com/assets/4663665/815537/11f935b6-ef2b-11e2-8af3-b639c1fcfe65.jpg)

Esto nos dejo en combate permanente, se llama Rope Beam Stalker http://es.wowhead.com/npc=37231 no se lo puede atacar.
![wowscrnshot_071713_174336](https://f.cloud.github.com/assets/4663665/815547/47363cd8-ef2b-11e2-855c-b0b215dd83a8.jpg)

Por último, al limpiar todo el lugar quisimos ir al Alto Libramonte, pero la opción para ir no aparecía, aquí acabo nuestro testeo de icc.

![wowscrnshot_071713_174541](https://f.cloud.github.com/assets/4663665/815558/959c9408-ef2b-11e2-98fd-1c2de68c1711.jpg)

**Comment by efectokoleos** [comment]
la batalla se está reescribiendo, de momento ponemos la opcion de hacer los demas bosses.

**Comment by Dekadencee** [comment]
No olvides el daño de lord tuetano y el npc que te mantiene en combate Edea, abrimos el reporte de nuevo.

**Comment by efectokoleos** [comment]
arreglados lord tuetano y el npc tambien, cierro
