### ISSUE TITLE
[Montura] Mamut tundra viajero

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#54]
Bueno, el problema es que esta montura sirve para llevar a 3 a la vez, al momento de sacarla aparecen 2 vendedores montados, el problema radica en que los vendedores no se pueden expulsar de la montura, por lo cual ninguno de la party se puede montar en ella 

![wowscrnshot_070413_012021](https://f.cloud.github.com/assets/4895839/747759/0d99e844-e472-11e2-9b5a-8ae7fa4cde72.jpg)

Al darle expulsar pasajero no pasa nada.

**Comment by redneo** [comment]
Creo que te equivocas, para llevar a alguien existe otro mamut

http://es.wowhead.com/spell=61469
http://es.wowhead.com/spell=61470
frente a 
http://es.wowhead.com/spell=61447
http://es.wowhead.com/spell=61425

**Comment by ghost** [comment]
@redneo tengo entendido que se pueden expulsar a los vendedores para que se suban otros jugadores, dejo un comentario de wowhead.
http://es.wowhead.com/spell=61425/mamut-de-tundra-de-viajero#english-comments

"For those of you needing to know how to boot vendor's off mount for others to ride. You should see a panel below mini map (when mounted on Mammoth) showing the vendors as two yellow dots on either side, Boot one or both for your new passengers to hop on."

Y wowwiki http://www.wowwiki.com/Reins_of_the_Traveler%27s_Tundra_Mammoth_%28Horde%29

**Comment by SherBlader** [comment]
Redneo, antiguamente los pasajeros se podian expulsar y otros pjs se podian subir, se supone que en ese tambien se podian subir

**Comment by Velcositro** [comment]
Ellos tienen razón Redneo, los vendedores deberían poder expulsarse, comprobado por mi en los reinos oficiales de prueba.

**Comment by ghost** [comment]
Si alguien vuelve a crear el reporte xd.
