### ISSUE TITLE
[Errores Internos] Vega Tuercespina

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#540]
Hola queria comentar que tras morir varias veces en vega  de tuercespina, tras liberar mi cuerpo siempre aparecía en paramos de poniente, creando siempre un dilema para volver a recuperar el cuerpo.

Norte de la Vega de Tuercespina http://es.wowhead.com/zone=33
El Cabo de Tuercespina http://es.wowhead.com/zone=5287
Vega de Tuercespina http://es.wowhead.com/zone=5339
Páramos de Poniente http://es.wowhead.com/zone=40

![wowscrnshot_071713_005628](https://f.cloud.github.com/assets/3537253/816110/b6ff1e3c-ef39-11e2-9d4a-274770b7e2d1.jpg)

![wowscrnshot_071713_020414](https://f.cloud.github.com/assets/3537253/816112/c0481f5c-ef39-11e2-815a-68cb49d5068e.jpg)

![wowscrnshot_071713_010630](https://f.cloud.github.com/assets/3537253/816113/c5ed2c86-ef39-11e2-989d-d17c0d3763c1.jpg)

Un saludo.

**Comment by searum** [comment]
esto esta fix desde hace muuuuuuuuuucho
