### ISSUE TITLE
[NPC] Truhán de Bahía del Botín

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#541]
Hola quiero reportar estos NPC

Truhán de Bahía del Botín http://es.wowhead.com/npc=4624

Los cuales gran parte de ellos estan caminando sobre el agua flotando por el aire, muchos de ellos llegan a aparecer fuera de bahia del botin matando npcs enemigos por fuera.

![wowscrnshot_071713_031227](https://f.cloud.github.com/assets/3537253/816133/789af444-ef3a-11e2-82b2-6b3b279cd0f7.jpg)

En esta foto realmente no se aprecia la cantidad de ellos que hay.

Un saludo.

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
