### ISSUE TITLE
[Pesca] Bahia del botín

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#542]
Hola queria comentar que pescando en bahia del botin nunca se coje nada en el anzuelo jaja.

El Cabo de Tuercespina http://es.wowhead.com/zone=5287

Sitio exacto.
![bahia](https://f.cloud.github.com/assets/3537253/816147/1a05923a-ef3b-11e2-8dfb-f4c692265913.jpg)

![wowscrnshot_071713_032026](https://f.cloud.github.com/assets/3537253/816148/218ee61e-ef3b-11e2-9a95-e2629beb7ae4.jpg)
![wowscrnshot_071713_032032](https://f.cloud.github.com/assets/3537253/816150/26a40e18-ef3b-11e2-9577-8d443fffa9cc.jpg)
![wowscrnshot_071713_032034](https://f.cloud.github.com/assets/3537253/816152/2bb07e32-ef3b-11e2-9242-f21d53c7f49c.jpg)
![wowscrnshot_071713_032052](https://f.cloud.github.com/assets/3537253/816153/321ba21a-ef3b-11e2-8d1b-323e22559187.jpg)

Un saludo.

**Comment by Kiritoo** [comment]
Fix
