### ISSUE TITLE
[Misión] Tiger Hunting

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#543]
Caza al tigre http://es.wowhead.com/quest=185

Quiero reportar la siguiente misión de tuercespina la cual no hace falta ni cojer, ni cumplir los requisitos, hablas directamente y se entrega sin cojerla siquiera.
![wowscrnshot_071713_134417](https://f.cloud.github.com/assets/3537253/816168/b1e79c60-ef3b-11e2-9512-28bf8aefb184.jpg)

Un saludo.

**Comment by redneo** [comment]
tiene que ser autorewarded, no autocompletable.
