### ISSUE TITLE
[Misión] Tiger Stalking

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#544]
Persigue al tigre http://es.wowhead.com/quest=186

Quiero reportar la siguiente misión de tuercespina la cual no hace falta ni cojer, ni cumplir los requisitos, hablas directamente y se entrega sin cojerla siquiera.
![wowscrnshot_071713_134525](https://f.cloud.github.com/assets/3537253/816177/fd4afa44-ef3b-11e2-8125-a8f594f1ac8b.jpg)

Un saludo.

**Comment by redneo** [comment]
lo mismo que antes
