### ISSUE TITLE
[Misión] Raptor Hunting

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#545]
Caza al raptor http://es.wowhead.com/quest=194

Quiero reportar la siguiente misión de tuercespina la cual no hace falta ni cojer, ni cumplir los requisitos, hablas directamente y se entrega sin cojerla siquiera.

![wowscrnshot_071713_134425](https://f.cloud.github.com/assets/3537253/816190/4044ea4e-ef3c-11e2-9391-2fa074e174af.jpg)

Un saludo.

**Comment by redneo** [comment]
lo mismo que antes
