### ISSUE TITLE
[Misión] (Tuercespina) Turning the Brashtide

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#549]
Cambiando el sentido de la marea http://es.wowhead.com/quest=26699

Esta misión deberia efectuarse en otra fase o aura a mi parecer.
Tras cojerla no ocurre nada, ni aparecen barcos ni la bahia en llamas y es una misión bastante curiosa.

![wowscrnshot_071713_155308](https://f.cloud.github.com/assets/3537253/816227/a06e117e-ef3d-11e2-8eb7-3f240581ad5f.jpg)
![wowscrnshot_071713_155310](https://f.cloud.github.com/assets/3537253/816228/a5cb623e-ef3d-11e2-89e9-029e61569f47.jpg)

Se puede ver el estado de la bahia en las fotos de wowhead.

Un saludo.

**Comment by Compresor** [comment]
Fix
