### ISSUE TITLE
[Joyeria] Bugs varios

### ISSUE THREAD

**Issue by Huardruid** [RoDNet/Bugtracker-Infinium-4.3.4#55]
1º No me deja prospectar.

[IMG]http://i.imgur.com/zUirg9E.jpg[/IMG]

2º El vendedor de ventormenta no vende gemas epicas

**Comment by ghost** [comment]
Tengo entendido que a partir del parche 4.3 se introducen las gemas épicas, y solo caen de los boss de bandas o mazmorras heroicas, o sea no se venden.

Por cierto, lo de prospectar será solo con esa mena, porque a mi las menas de cobre me deja prospectarlas.

**Comment by ghost** [comment]
Ya funciona lo de prospectar.
