### ISSUE TITLE
[Misión] (Tuercespina) The Damsel's (Bad) Luck

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#550]
La Damisela Desafortunada http://es.wowhead.com/quest=26700
Esta misión tambien trascurre en el mismo lugar que la misión anterior reportada en el issuue https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/549

Solo que teniendo otro objetivo para completar.
Al no estar el barco/npcs tampoco se puede hacer nada.

![wowscrnshot_071713_155350](https://f.cloud.github.com/assets/3537253/816254/92f3a2a6-ef3e-11e2-9df2-73ca776b232f.jpg)
![wowscrnshot_071713_155352](https://f.cloud.github.com/assets/3537253/816256/98a76af2-ef3e-11e2-84b2-1d48376ad11e.jpg)

Un saludo.

**Comment by Compresor** [comment]
Arreglada
