### ISSUE TITLE
[Misión] (Tuercespina) The Final Voyage of the Brashtide

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#551]
El viaje final de los Fuertemarea http://es.wowhead.com/quest=26697

Mismo modelo que:
1.  
   El viaje final de los Fuertemarea http://es.wowhead.com/quest=26697 https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/551

Cambiando el sentido de la marea http://es.wowhead.com/quest=26699 https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/549

La Damisela Desafortunada http://es.wowhead.com/quest=26700 https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/550
2.  
El fin de los Velasangre

Misión en la cual se debe de hablar con Kebok http://es.wowhead.com/npc=737 subir a un jinete del viento y bombardear los tripulantes y los barcos .

Al no estar los barcos ni la tripulación no se puede completar.

Estas tres misiones tienen relación.

Un saludo.

**Comment by Compresor** [comment]
Arreglada
