### ISSUE TITLE
[Misión] Flight to Theramore

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#552]
Vuelo a Theramore http://es.wowhead.com/quest=26702

Está misión se debe hablar con Bragok <Maestro de vuelo> http://es.wowhead.com/npc=16227 el cual debe dar la opción de volar a Theramore y no la esta dando, dejando una única opción de ir a pié.

![wowscrnshot_071713_163319](https://f.cloud.github.com/assets/3537253/816293/1a584cb4-ef40-11e2-8c8e-f626c7d08292.jpg)
![wowscrnshot_071713_163323](https://f.cloud.github.com/assets/3537253/816294/22291a36-ef40-11e2-85ec-b461adbfc2ee.jpg)

Un saludo.

**Comment by Kiritoo** [comment]
Está funcionando correctamente.
Cierro.
