### ISSUE TITLE
[Misión] (Marjal Revolcafango) Discrediting the Deserters

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#553]
Desprestigiando a los desertores http://es.wowhead.com/quest=27212

Misión la cual se debe distribuir panfletos entre 6 guardias de theramore.
Guardia de Theramore http://es.wowhead.com/npc=4979

Al hablar con el te aparece la opción para darle el panfleto pero no se le puede dar click en ella no ocurre nada.
![wowscrnshot_071713_165728](https://f.cloud.github.com/assets/3537253/816305/99789e90-ef40-11e2-821a-f6465b2ef6dd.jpg)
![wowscrnshot_071713_165738](https://f.cloud.github.com/assets/3537253/816306/a2f56c14-ef40-11e2-972d-fa74436fd6a6.jpg)

Un saludo.

**Comment by redneo** [comment]
Arreglada!
