### ISSUE TITLE
[Misión] What's Haunting Witch Hill?

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#555]
¿Quién atormenta la Colina de las Brujas?  http://es.wowhead.com/quest=27188

![wowscrnshot_071713_171618](https://f.cloud.github.com/assets/3537253/816337/0caf3274-ef42-11e2-8803-a26e3e62b1c8.jpg)

Está misión se trata de derrotar unos Npcs, estes para ser mas preciso:
Raquíticos resucitados http://es.wowhead.com/npc=23555
Espíritu resucitado http://es.wowhead.com/npc=23554

Tras matarlos aparece el siguiente NPC amistoso.
Aparecido inquieto http://es.wowhead.com/npc=23861
Este NPC es el que te da la información necesaria para la misión.

El problema viene que al darle click.
![wowscrnshot_071713_171607](https://f.cloud.github.com/assets/3537253/816344/4bab3946-ef42-11e2-83a6-844e2c741979.jpg)
![wowscrnshot_071713_171548](https://f.cloud.github.com/assets/3537253/816345/4bbff4bc-ef42-11e2-88db-291dd8d5a5f9.jpg)
![wowscrnshot_071713_171610](https://f.cloud.github.com/assets/3537253/816346/4bc1acee-ef42-11e2-9941-233c0dc5b67d.jpg)

Te empieza a contar la información pero no te cuenta como objetivo de misión.

Un saludo.

**Comment by redneo** [comment]
Fixed
