### ISSUE TITLE
[Misión] Renn McGill

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#556]
Renn McBranquia http://es.wowhead.com/quest=27235

El NPC donde se debe entregar la misión no está.
Renn McBranquia <Buzo de salvamento del IV:7> http://es.wowhead.com/npc=23569
63.6, 17.0 Marjal Revolcafango http://es.wowhead.com/zone=15

![wowscrnshot_071713_180238](https://f.cloud.github.com/assets/3537253/816361/e1889a58-ef42-11e2-8fd3-8b023448a491.jpg)
![wowscrnshot_071713_180242](https://f.cloud.github.com/assets/3537253/816366/e6a44050-ef42-11e2-8ada-77493d11ba84.jpg)

Un saludo.

**Comment by redneo** [comment]
Estaba en una fase rara, cambiado a fase 1 cuando caiga el server.

**Comment by crowel** [comment]
Ya se puede entregar, gracias.
