### ISSUE TITLE
[Misión] (Marjal Revolcafango) The Grimtotem Weapon

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#557]
El arma Tótem Siniestro http://es.wowhead.com/quest=27336

Está misión se basa en fijar un totem en el suelo http://es.wowhead.com/item=33101 y ir matando los cocodrilos.
Crocolisco secorrón jaspeado http://es.wowhead.com/npc=4344

Quiero comentar que el totem persigue al portador cosa que no debería ya que se debe quedar  fijo al suelo y también debe lanzar unos rayos(aura) al cocodrilo(s).

![wowscrnshot_071713_181733](https://f.cloud.github.com/assets/3537253/816381/af189e5a-ef43-11e2-9d63-d9d344f098a0.jpg)
![wowscrnshot_071713_181626](https://f.cloud.github.com/assets/3537253/816385/b623f5aa-ef43-11e2-9924-1ddcff347aad.jpg)
![wowscrnshot_071713_181700](https://f.cloud.github.com/assets/3537253/816386/b6655c02-ef43-11e2-8e1f-7fe673d25958.jpg)

Aqui un video explicativo: http://www.youtube.com/watch?v=mk8BQnjAaHk

Un saludo.

**Comment by redneo** [comment]
Arreglada cuando caiga el server.

**Comment by crowel** [comment]
Hola, acabo de comprobarla y el totem no hace lo que debe, por lo tanto no cuenta el objetivo de misión.
Un saludo.

**Comment by redneo** [comment]
Arreglado
