### ISSUE TITLE
[Brujo] Quemar Alma

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#558]
Hechizo: es.wowhead.com/spell=74434
Bug: No se consume su efecto con algunos de los hechizos que afecta, lo que hace que se pueda usar varias veces el mismo efecto, como lanzar varios Fuego de Alma instantáneos seguidos, los hechizos que no lo están consumiendo son:

*Drenar Vida (ID: 689)
*Fuego de Alma (ID: 6353)
*Los de Invocar Demonios (IDs: 691->Manáfago, 688->Diablillo, 712->Súcubo, 697->Abisario, 30146->Guardia Vil)

Los otros hechizos que afecta, como Dolor Abrasador (ID: 5676) si consumen el efecto al usarlos.

**Comment by searum** [comment]
ya lo tengo fix falta aplicarlo
