### ISSUE TITLE
[Misión] (Marjal Revolcafango) Raze Direhorn Post!

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#559]
¡Arrasa el Puesto Cuernoatroz! http://es.wowhead.com/quest=27429

Está misión se trata de quemar con la antorcha
Antorcha de Tabetha http://es.wowhead.com/item=33072
Las 3 tiendas del Puesto Cuernoatroz.

Bien, el problema creo que viene de la antorcha.
![wowscrnshot_071713_182354](https://f.cloud.github.com/assets/3537253/816399/5682cb66-ef44-11e2-9862-c996eb163bbc.jpg)
![wowscrnshot_071713_182346](https://f.cloud.github.com/assets/3537253/816398/567feab8-ef44-11e2-99c7-39a71cf2ccb5.jpg)

Como se ve en las dos imagenes, al utilizar el objeto de misión la antorcha, aparentemente no ocurre nada pero si nos fijamos en la mano de mi personaje la mueve ligeramente al mismo tiempo que aparece la antorcha en una pequeña fracción de segundo.

Tras esto me planteo ¿ El problema está en las tiendas, como si no detectara la zona ? Así que me planteo probar otra de las tiendas ocurriendo lo mismo.

Ahora bien, quiero que se vean estas dos imagenes.
![wowscrnshot_071713_182400](https://f.cloud.github.com/assets/3537253/816405/a9da1ed6-ef44-11e2-9377-d98af078f3e6.jpg)
![wowscrnshot_071713_182405](https://f.cloud.github.com/assets/3537253/816406/aa0536e8-ef44-11e2-8c16-595ba32024bd.jpg)

Como se puede apreciar arriba en letras rojas "Requiere tienda de totem siniestro", esto desbarata la teoria de que el problema pudiera estar en la ubicación de las tiendas ya que cuando la utilizaba dentro no aparecia el mensaje.

Yo comprobaria las antorchas ya que no funcionan ni queman la tienda.

Un saludo.

**Comment by redneo** [comment]
Arreglada, cuando caiga el server...

**Comment by crowel** [comment]
Hola al parecer dice Santa, en el Issue 1172 que sigue sin funcionar.

**Comment by redneo** [comment]
Arreglada cuando caiga el server.
