### ISSUE TITLE
[Mascotas] Felino lanzando descarga acuatica.

### ISSUE THREAD

**Issue by Huardruid** [RoDNet/Bugtracker-Infinium-4.3.4#56]
Felino lanzando descarga acuática, una habilidad de la pet de el mago escarcha

[IMG]http://i.imgur.com/mp5klRr.jpg[/IMG]

**Comment by SherBlader** [comment]
xDDD

**Comment by Alfonn** [comment]
....[Without comments]

**Comment by Dekadencee** [comment]
Fixed
