### ISSUE TITLE
[Pesca] Bag of Shiny Things

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#560]
Hola me gustaría que revisaran este objeto.
Bolsa de cosas brillantes http://es.wowhead.com/item=67414
Llevo dos días haciendo la misión diaria de pesca recibiendo está bolsa como recompensa.
El problema viene a la hora de abrirla que no da loot y luego desaparece.
![wowscrnshot_071713_195350](https://f.cloud.github.com/assets/3537253/816430/7bb4c6b8-ef45-11e2-8a72-f5b40ccabd86.jpg)
![wowscrnshot_071713_195353](https://f.cloud.github.com/assets/3537253/816433/8151713e-ef45-11e2-9c6b-590cec5f249b.jpg)

Estes son sus posibles Contains a la hora de abrirla.
http://es.wowhead.com/item=67414#contains
Un saludo.

**Comment by redneo** [comment]
fixed
