### ISSUE TITLE
[NPC][Errores Internos] Bahia del botín

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#561]
Hola queria reportar los siguientes NPC.

![wowscrnshot_071813_012234](https://f.cloud.github.com/assets/3537253/816444/bee5ea0c-ef45-11e2-8351-0505df935a18.jpg)

Los cuales estan posicionados debajo del marrr jaja y deberian estar a bordo del barco.
![wowscrnshot_071813_012253](https://f.cloud.github.com/assets/3537253/816453/e5d0a792-ef45-11e2-92cb-6e5b84743316.jpg)
![bahia](https://f.cloud.github.com/assets/3537253/816454/f06e5f50-ef45-11e2-9095-d4e9257c3898.jpg)

Tambien quiero mostras estos gobs (sillas) flotando sobre el agua justo encima de los npcs.
![wowscrnshot_071813_012229](https://f.cloud.github.com/assets/3537253/816465/14db0780-ef46-11e2-92bc-7d9fe8ccc7da.jpg)
Las cuales deben estar en el barco.

Quiero mostrar está otra foto.
![wowscrnshot_071813_012419](https://f.cloud.github.com/assets/3537253/816471/2a8121f0-ef46-11e2-9e22-5e91e24677ea.jpg)
Las sillas que se ven dentro del barco son las que estan flotando.
Cuando el barco viene a puerto las sillas estan posicionadas en su sitio exacto solo que cuando el barco se mueve las pobres se quedan flotando a la deriva jajaja.

Hasta aqui todas las screens que tenia en la carpeta, ya seguiré subiendo lo que vaya encontrando.

Un saludo y buenas noches.

**Comment by redneo** [comment]
Tendrian que estar borrados, otra cosa diferente son las sillas, que no las puedo pillar la id, se tienen que borrar a mano
