### ISSUE TITLE
[Bug grave, tumba el server] Estudiar (Arqueología)

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#562]
Habilidad: http://es.wowhead.com/spell=80451
Bug: Al usarlo parece ser que tumba el server, o eso me pareció, lo usé 2 veces y las 2 veces se cayó, no quise probar una 3º vez.

PD: A petición de un jugador volví a probar y definitivamente tumba el Server.

**Comment by searum** [comment]
fix, compilando
