### ISSUE TITLE
[NPC] Barcódromo de Fizzle y Pozzik

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#563]
Hola porfavor revisen las faction de los npcs situados en el Barcódromo de Fizzle y Pozzik, atacan a los jugadores de la alianza, no se si le ocurre a la horda.
Las Mil Agujas http://es.wowhead.com/zone=400
![barcodromo](https://f.cloud.github.com/assets/3537253/816525/72bd7c72-ef49-11e2-8353-d14286c84f33.jpg)

Ya que es poner un pié alli y morir, no se pueden realizar las misiones estando los npcs como enemigos.

Un saludo.

**Comment by redneo** [comment]
Creo que ya no pegan (al menos todos :P)

**Comment by crowel** [comment]
Hola, ahora compruebo y posteriormente no queda ninguno para añadir al reporte, lo cierro.

Muchas gracias :)

**Comment by crowel** [comment]
Solucinado!
