### ISSUE TITLE
[Tol Barad] Mob que no se puede golpear

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#564]
el mob http://www.wowhead.com/npc=48285/accursed-supplyman

lo puede golpear a uno, pero uno no le puede pegar.

![wowscrnshot_071813_020639](https://f.cloud.github.com/assets/4895839/817582/dc705b4c-ef78-11e2-8bd1-00d932b666d2.jpg)

**Comment by redneo** [comment]
By Aerozia (3,122 – 7·44) on 2011/01/20 (Patch 4.0.3)    Report  
These are NPCs that are phased, they only show up for people who have the ques to shoot the boats with the cannons in TB.
but they still cause aggro and even attack if you water-walk or swim out where they would be if you had the quest.
makes fishing hard.
