### ISSUE TITLE
[Mision] Rasganorte Tundra boreal

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#565]
Mision No sin luchar  ID: 11949

http://es.wowhead.com/quest=11949/no-sin-luchar

![wowscrnshot_071813_093356](https://f.cloud.github.com/assets/4893907/817878/0b9da894-ef82-11e2-998d-a73838fc3a1d.jpg)

No se puede fijar ningun enemigo por lo cual no podemos matarlo pero ellos a nosotros si

![wowscrnshot_071813_093331](https://f.cloud.github.com/assets/4893907/817884/4aeca626-ef82-11e2-8c8c-ee3c127638fc.jpg)

**Comment by redneo** [comment]
cuando caiga el server tendria que ir, creo que habia otro post con estos tipos...
