### ISSUE TITLE
[Misiones] Rasganorte: Tundra Boreal

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#566]
Mision: Palabras de Poder  ID;11942

http://es.wowhead.com/quest=11942/palabras-de-poder

![wowscrnshot_071813_101028](https://f.cloud.github.com/assets/4893907/817892/9800454e-ef82-11e2-9c23-3a173c605e1f.jpg)

No se puede fijar a uno de los objetivos de la mision lo cual no te da objeto y no puedes completar

![wowscrnshot_071813_101020](https://f.cloud.github.com/assets/4893907/817894/aafcb4ac-ef82-11e2-9474-0d027b4bc5ff.jpg)

**Comment by redneo** [comment]
cuando caiga el server tendria que ir
