### ISSUE TITLE
Talento [Contricción] Sacerdote disciplina

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#567]
Buenos días.

Searum, redirijo del reporte que cerraste https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/37 ya que no me está funcionando correctamente todavía (tal vez me precipite reportando esto y haga falta una caída del server para que se aplique la correción):

Sucede lo siguiente (sea crítica la punición http://es.wowhead.com/spell=585/punicion o el fuego sagrado http://es.wowhead.com/spell=14914/fuego-sagrado o no):

http://imageshack.us/a/img59/4717/fmti.jpg

<a href="http://imageshack.us/photo/my-images/59/fmti.jpg/" target="_blank"><img src="http://imageshack.us/a/img59/4717/fmti.th.jpg" border="0"/></a>

http://imageshack.us/a/img15/7770/ur4h.jpg

<a href="http://imageshack.us/photo/my-images/15/ur4h.jpg/" target="_blank"><img src="http://imageshack.us/a/img15/7770/ur4h.th.jpg" border="0"/></a>

Gracias.

**Comment by paellaencol** [comment]
Reabro

**Comment by searum** [comment]
fix ahora si
