### ISSUE TITLE
[Mision Diaria] Tol Barad - ¡Bombas fuera! O ¡Bomba va! 

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#568]
Bueno, hay 2 cosas curiosas en la mision.
# la 1

cuando estoy en el juego el nombre de la mision es ¡Bomba va!, pero al buscarla en wowhead me aparece otra mision http://es.wowhead.com/quest=11102/bomba-va

Y hay otra mision con otro nombre ¡Bombas fuera! http://es.wowhead.com/quest=28696/bombas-fuera
Que si corresponde a lo que hay que hacer en la quest de tol barad.
# La 2

Hay pocos barcos para destruir, solo hay 2 y deberian haber al menos unos 12 o 14 (la quest pide 10)

![wowscrnshot_071813_095210](https://f.cloud.github.com/assets/4895839/819911/ddbb916e-efba-11e2-8052-956f89e2ed4e.jpg)

**Comment by redneo** [comment]
A mi me han salido bastantes, alguno más de los que pide la mision... :S

**Comment by Felarof23** [comment]
A mi tampoco me salen barcos, pero si disparo a la nada de pronto brinca el conteo de barcos destruidos :S

**Comment by paellaencol** [comment]
Diria que va bien, en el muelle del sur suelen salir unas 4 barcas, y 10 más en el del norte.

**Comment by Compresor** [comment]
Funciona
