### ISSUE TITLE
[Mision Diaria] Tol Barad - Ponte en su pellejo durante un tiempo

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#569]
La Mision Ponte en su pellejo durante un tiempo http://es.wowhead.com/quest=28721/ponte-en-su-pellejo-durante-un-tiempo

NO se puede hacer porque cuando voy a la fortaleza e intento hablar con un prisionero no puedo, no me da la opcion de hablar, solo lo puedo cliquear, pero no pasa nada.

![wowscrnshot_071813_101019](https://f.cloud.github.com/assets/4895839/820066/45e5b3d0-efbd-11e2-9bf4-762b3e6c6b89.jpg)

**Comment by redneo** [comment]
Arreglada
