### ISSUE TITLE
[Npc] Si haces esto se cae el server.

### ISSUE THREAD

**Issue by Huardruid** [RoDNet/Bugtracker-Infinium-4.3.4#57]
Si compras puntos de honor de ese npc se cae el servidor.

<a href="http://imgur.com/YOZ4gQL"><img src="http://i.imgur.com/YOZ4gQL.jpg" title="Hosted by imgur.com" /></a>

http://imgur.com/YOZ4gQL

**Comment by Dekadencee** [comment]
Perfecto nos ponemos con ello, que horror la cantidad de puntos de justicia, es un bug como una casa de grande xD

**Comment by redneo** [comment]
Creo que ya está solucionado el crash, lo que dudo que lo venda bien (en local no me ha dejado, pero no ha tirado el server)
