### ISSUE TITLE
[Mision Diaria] Tol Barad - Enseña a un hombre a pescar... o a robar

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#570]
La mision diaria Enseña a un hombre a pescar... o a robar http://es.wowhead.com/quest=28137/ensena-a-un-hombre-a-pescar-o-a-robar

NO muestra la zona en el mapa donde se debe llevar a acabo la mision.

![wowscrnshot_071813_103752](https://f.cloud.github.com/assets/4895839/820214/0cbf5b3a-efc0-11e2-8559-0a5d5a407c01.jpg)

**Comment by redneo** [comment]
A mi si que me lo muestra sin addons.
