### ISSUE TITLE
[Mision Diaria] Tol Barad - Un pueblo poco amistoso

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#571]
La mision diaria Un Pueblo Poco Amistoso http://es.wowhead.com/quest=28686/un-pueblo-poco-amistoso

NO muestra la zona en el mapa donde se debe llevar a acabo la mision.

![wowscrnshot_071813_103100](https://f.cloud.github.com/assets/4895839/820229/6568b42a-efc0-11e2-9132-4f36963dc9e7.jpg)

**Comment by WarSxNes** [comment]
Hola... saludos.... una pregunta::::: no se si hemos sintonizado el mismo canal pero... esta quest no enseña nada o si??

> Un pueblo poco amistoso
> El comandante Larmash te ha pedido que mates a 14 aldeanos en Aldea Monrojo. Aldea Monrojo se encuentra al norte del campamento, en la parte de la derecha. 
> Residentes de Aldea Monrojo  (14) 
> 
> Ganancias
> Cuando completes esta misión ganarás:
> ◾69,400 experiencia
> ◾250 reputación con Mando Grito Infernal
- Hihihihi no veo que diga nada sobre que enseñe a robar o a pescar.
- Y estas usando carbonite (addon); puede ser que esa version que estes usando no la muestre.

**Comment by SherBlader** [comment]
@WarSxNes Error al crear los posts, ya los arreglo xD
No es el carbonite, me muestra todas las diarias y las misiones, menos esas 2

**Comment by redneo** [comment]
Me pasa lo mismo que con la otra... si que me lo muestra sin addons
