### ISSUE TITLE
[Brujo] Terror de Fatalidad

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#575]
ID: 603

Bug: No tiene la probabilidad de invocar diablillos de ébano (ID: 50675) al hacer daño, sino que los invoca al matar al enemigo con ese terror puesto.
La probabilidad debe ser de un 20%, o de hasta un 50% con el talento Fatalidad Inminente (ID: 85108, suma 10% en cada rango, con 3 rangos suma el 30% que dá el total de 50%) de Demonología.

**Comment by searum** [comment]
fix
