### ISSUE TITLE
[Brujo] Cauce de Salud

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#576]
ID: 755

Bug: Debería quitar 1% de salud al brujo, pero en vez de eso dice que falla el daño en cada tic. La sanación al demonio si funciona.

**Comment by searum** [comment]
fix

**Comment by Wiinter** [comment]
En cada tick no está quitando un 1% de la salud del brujo, sino más. Ahora mismo con 126k de vida me está quitando 7k por tick. Debería ser 1k. Si prefieres te lo posteo en uno nuevo. Pero lo he visto demasiado pequeñin el error.
