### ISSUE TITLE
[Brujo] Piedra de Alma

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#577]
ID: 5232

Bug: Funciona como siempre correctamente, pero desde el parche 4.1 deja usarla sobre un objetivo muerto para revivirlo de inmediato (La nota del parche dice: "Ahora la piedra de alma se puede usar en combate para resucitar a un jugador muerto marcado como objetivo."), el bug es que se puede usar sobre objetivos muertos pero en vez de revivirlos aplica el mismo efecto que con objetivos vivos. Al parecer el efecto usado en este parche es http://es.wowhead.com/spell=20707.

**Comment by Dekadencee** [comment]
Fixed

**Comment by Velcositro** [comment]
Deka lo probé y sigue bug lo de revivir a un muerto de forma instantánea, ¿es que no funcionó el fix o es que no lo has puesto?

**Comment by Dekadencee** [comment]
Pruebalo ahora de nuevo @Velcositro , aun no habiamos actualizado el core, el core actualmente tiene los fix a día de hoy, ya deberia funcionar

**Comment by Velcositro** [comment]
Lo probé después del reinicio y tampoco funcionó Deka, lo que si funcionó fué Arqueología que ya da loot aunque solo aparecen cosas Vrykul...

**Comment by Dekadencee** [comment]
Pues reabrimos de nuevo, disculpa las molestias

**Comment by Velcositro** [comment]
Ninguna molestia, molestia para ustedes que son los que arreglan las cosas. XD

**Comment by searum** [comment]
fix
