### ISSUE TITLE
[Brujo] Invocar Guardia Apocalíptico

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#578]
ID: 18540

Bug: Invoca a un Guardia apocalíptico (http://es.wowhead.com/npc=11859, como debe ser), pero ese guardia debería usar Descarga de fatalidad (ID=85692) para atacar, en vez de eso ataca cuerpo a cuerpo.

Además debería atacar a los objetivos afectados por el Terror de agonía(ID=980) o el Terror de fatalidad(ID=603) del brujo, pero ataca solo a quien se le tenga como objetivo al invocarlo o al que le pegue.

**Comment by Kiritoo** [comment]
Fix el ataque de la Descarga de fatalidad falta aplicarlo.
Aun queda mirar de que el  Guardia ataque a los objetivos afectados por terror de agonia.

**Comment by searum** [comment]
fix
