### ISSUE TITLE
[Brujo] Invocar Infernal

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#579]
ID: 1122

Bug: Invoca a un Infernal (supuestamente a http://es.wowhead.com/npc=89 según unos datos, pero no creo que sea ese) y ese infernal debería tener la habilidad Inmolación Demoníaca (http://es.wowhead.com/spell=4525) y no la tiene.

Además debería atacar a los objetivos afectados por el Terror de agonía(ID=980) o el Terror de fatalidad(ID=603) del brujo, pero ataca solo a quien se le tenga como objetivo al invocarlo o al que le pegue.

**Comment by Wiinter** [comment]
Velco las ids del Infernal son correctas. Yo lo he comprovado aqui http://www.wowhead.com/spell=111685. En la parte de Effect se puede ver que la id del npc es 89.

**Comment by Velcositro** [comment]
@Wiinter Ok gracias, entonces solo queda esperar.

**Comment by ghost** [comment]
El npc es el que mencionais arriba. Añado que se mueve a velocidad por debajo de lo normal, parece que está ralentizado todo el tiempo.
- Spell: http://wow.freakz.ro/spells.php?spell=1122
- NPC summoneado: http://wow.freakz.ro/npc_finder.php?npc=89&name=infernal

---

¿Qué daño debería hacer el inmolar? Según la mayoría de las webs:

42 + 20.25% del poder con hechizos del brujo.
o
42+135% del poder con hechizos del infernal

ya que los esbirros se benefician de un 15% del poder con hechizos del brujo, 135%x0.15 es 20.25
http://www.wowwiki.com/Spell_power_coefficient

**Comment by searum** [comment]
fix
