### ISSUE TITLE
[Brujo] (Demonología) Inferno

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#580]
ID: 85105

Bug: Un bug muy menor, este talento deja usar Llamas infernales (ID: 1949) en movimiento, el bug es que no se puede usar el hechizo si ya te estás moviendo, debes pararte, usarlo y después seguir.

**Comment by searum** [comment]
esto lo cierro porque se que esta ese bug y no es solo con esto, es bug interno
