### ISSUE TITLE
[Arqueología] Algunos bugs

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#583]
Primer bug: hay un npc raro y un objeto que aparecen cada vez que excavas.
[[UNUSED] Grummar Thunk]  http://www.wowhead.com/npc=1455
Quilboar Watering Holehttp://www.wowhead.com/object=300146

Segundo bug: estaba excavando en Monte Hyjal y me sale arqueología vrykul, cuando debería de salir eso en rasganorte.

Tercer bug: no me da los puntos/fragmentos de arqueología luego de lootear.

![wowscrnshot_071813_135943](https://f.cloud.github.com/assets/4663665/821111/49598c64-efd4-11e2-8a36-cd1bcbd88150.jpg)

**Comment by Dekadencee** [comment]
Lo del npc y el gameobject está resuelto, solo que es necesario el reset del reino.

El digsite de Monte Hyjal que te ha tocado tiene ese currency ya que están extraidos de las DBC del cliente, es decir viene así del oficial.

Respecto a los loot es cierto, se reinicializó hace poco la tabla de los loots y se nos ha olvidado volver a incluir los fragmentos.

Cierro issue ya que está todo resuelto, solo faltan los fragmentos que ahora los metemos.

Un saludo y gracias por reportar ^^

**Comment by ghost** [comment]
Gracias a ti por arreglar los bugs xd.
