### ISSUE TITLE
Bug Chaman

### ISSUE THREAD

**Issue by kirgar** [RoDNet/Bugtracker-Infinium-4.3.4#584]
Hola

Bug el talento de chaman elemental Cólera Totémica ID: 77746 http://es.wowhead.com/spell=77747/colera-ardiente. Deberia activarse el talento cada vez que haya 1 totem de fuego aumentando el spell power un 10% del que se tenga. Pero cuando hay 1 totem de fuego el talento no se activa ni aumenta el spell power.
<a href="http://www.subirimagenes.net/i/130718090645106246.jpg" target="_blank" title="subir imagen"><img src="http://sia1.subirimagenes.net/img/2013/07/18/mini_130718090645106246.jpg" border="0" alt="subir imagenes" /></a>
<a href="http://www.subirimagenes.net/i/13071809095759509.jpg" target="_blank" title="subir imagen"><img src="http://sia1.subirimagenes.net/img/2013/07/18/mini_13071809095759509.jpg" border="0" alt="subir imagenes" /></a>
<a href="http://www.subirimagenes.net/i/130718091029344931.jpg" target="_blank" title="subir imagen"><img src="http://sia1.subirimagenes.net/img/2013/07/18/mini_130718091029344931.jpg" border="0" alt="subir imagenes" /></a>

**Comment by searum** [comment]
fix
