### ISSUE TITLE
[DK] Profanacion talento

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#585]
no logro encontrar el talento en wow head fue cambiado por otro http://es.wowhead.com/spell=108201/suelo-profanado en mop

Bueno hice un recorte del talento 
![wowscrnshot_071813_150247](https://f.cloud.github.com/assets/3101842/821772/165f2366-efe1-11e2-94c7-195643194aa6.jpg)

El talento se activa cuando usamos golpe de la plaga, Golpe necrotico y golpe de peste.
Bueno el caso es que no se esta activando con Golpe necrotico solo con los otros ataques
Golpe necrotico: http://es.wowhead.com/spell=73975/golpe-necrotico

**Comment by searum** [comment]
fix
