### ISSUE TITLE
Talento [Brujo] Secuelas

### ISSUE THREAD

**Issue by Felarof23** [RoDNet/Bugtracker-Infinium-4.3.4#586]
El talento de la rama Destrucción, Secuelas, debe activarse con Lluvia de Fuego a 12% de probabilidad y por Conflagar para atontar al enemigo durante 5 seg.

![talento](https://f.cloud.github.com/assets/5028343/821768/0f2820f2-efe1-11e2-9f4a-46683f5a9738.png)

Bug: Este talento se también activa con: Llama Vil, Incinerar, Fuego de Alma, Inmolar y Descarga del Caos; De igual manera afecta al taumaturgo que lo lanze.

![screen shot 2013-07-17 at 1 21 12 pm](https://f.cloud.github.com/assets/5028343/821803/b54e2238-efe1-11e2-8a27-d08a15773896.png)

**Comment by searum** [comment]
fix

**Comment by Felarof23** [comment]
Muchisimas gracias :)
Saludos!
