### ISSUE TITLE
[Brujo] Quemar Alma

### ISSUE THREAD

**Issue by Felarof23** [RoDNet/Bugtracker-Infinium-4.3.4#587]
Esta spell, además de los listados, nos permite lanzar algunos ataques instantáneos, pero solamente una vez por fragmento quemado.

![quemaalma](https://f.cloud.github.com/assets/5028343/821847/a3708bf4-efe2-11e2-9154-a3d5a4f15fc9.png) ![unlock](https://f.cloud.github.com/assets/5028343/821872/14ec804e-efe3-11e2-9f93-1e35d52e669b.png)

Bug: Al utilizar cualquiera de estas habilidades secundarias el efecto de quemar alma no desaparece por lo que podemos seguir utilizándola con los hechizos afectados durante los 15 seg que dura el efecto.

![fuegoalmacont](https://f.cloud.github.com/assets/5028343/821905/bc13c698-efe3-11e2-9ae3-e3f6aabf3273.png)

**Comment by searum** [comment]
esta arreglado pero como no se a reiniciado el server pues todavia no esta aplicado... la proxima vez usa el buscador antes ^^ asi no te molestas en reportarlo otra vez xD
