### ISSUE TITLE
misiones hyjal

### ISSUE THREAD

**Issue by lilith384** [RoDNet/Bugtracker-Infinium-4.3.4#589]
buenas queria comunicaros que todas las misiones de hyjal del santuario aviana la arboleda y tortolla no funcionan ya que me estoy subiendo un pj y llevo 38 misiones de 115 y me es imposible levear alli para subir al 82 y ya no se que mas hacer puesto que me he recorrido todo hyjal y las misiones que cojo estan todas bug....si me podeis decir algo o arreglar, Searum me dijiste que te pusiera este bugtracker aqui lo tienes te dije las zonas porque las misiones las borre de mi invetario de misiones espero que tengas bastante con esto y me puedas ayudar como me dijiste en el tiket. Soy lilifua. gracias

**Comment by SherBlader** [comment]
con esto no te van a solucionar nada, te lo cerraran.
Tienes que colocar mision por mision y con su id (de wowhead) 1 post por mission Y bien explicado.
asi lo dijo searum
