### ISSUE TITLE
Problema con las bolsas.

### ISSUE THREAD

**Issue by Overseer101** [RoDNet/Bugtracker-Infinium-4.3.4#59]
http://es.wowhead.com/item=23162/cajon-para-guardar-piezas-que-duran-eternamente

Yo disponia de estas bolsas con Storm desde mi etapa en WH, el problema es que al cambiar la base de datos, dichas bolsas no estaban introducidas, con lo cual he perdido TODOS mis equipos, herramientas, materiales de profesion y demas cosas varias, amen de las bolsas propiamente dichas...

Si podeis arreglarme este problema os lo agradeceria, si no, voy a tener un chaman que solo va a servir para ir de paseo por ventor T:T

P.D. Alekx tiene el mismo problema que yo, con las mismas bolsas

**Comment by Dekadencee** [comment]
Lo tienen arreglado, recordad que estamos en fase de testeo, vuestros items volverán de nuevo tras terminar esta fase, es decir, haremos rollback hasta el momento del cierre de la 4.0.6a
