### ISSUE TITLE
[Paladin] Sello de Justicia

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#590]
Para avisar ( de nuevo), que este sello esta bug. Cuando lo tienes puesto, no me permite lanzar sentecia (desactivado).
![wowscrnshot_071813_163047](https://f.cloud.github.com/assets/4790547/822602/78ab447a-eff3-11e2-9655-f93d8b8a0dec.jpg)

La sentencia es el segundo poder que se ve "activado", en la barra 1, abajo izq.

http://old.wowhead.com/spell=20164

**Comment by searum** [comment]
fix

**Comment by lamaza** [comment]
Quedo bien la sentencia searum, pero no salta con CADA ataque cuerpo a cuerpo sino por ahi caada 2 o 3 ataques, y lógicamente lo probe dando tiempo de que no hubiese cd o algo asi.
