### ISSUE TITLE
[paladin]  Reprimenda

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#591]
http://es.wowhead.com/spell=96231

Bug: 
Esta dejando con CD hechizos de otras escuelas como: Sellos del paladín, martillo de justicia, guardian de los antiguos reyes, colera vengativa, escudo divino, mano de salvacion, mano de libertad, defensa recta, proteccion divina, mano de proteccion, mano de expiacion, auras del paladin, bendición de reyes y bendicion de poderio.

Creo que no me faltaron más... PD: En el ejemplo de reprimenda, castee luz divina (sagrado) y por eso digo que deja con cd 4s a otros hechizos que no son de esa escuela, me parece a mi que ese es un bug.

![wowscrnshot_070713_150814](https://f.cloud.github.com/assets/4790547/758675/bcd064dc-e747-11e2-9ea0-bc045d5bdfe7.jpg)
![wowscrnshot_070713_150816](https://f.cloud.github.com/assets/4790547/758672/bc8702f6-e747-11e2-950a-c4ffd2f96868.jpg)

Habria que probar con cada clase, que si deje los de cierta escuela y no las 3 ramas en cd...

**Comment by Compresor** [comment]
Va bien

**Comment by Necrofilo** [comment]
¿Es que el paladín usa hechizos de la escuela de las sombras también? Si te cortan un hechizo sagrado, TODOS tus hechizos se quedan silenciados porque todas tus spells son de la escuela de sagrado.
