### ISSUE TITLE
[Guerrero] Fuerza irresistible

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#592]
http://es.wowhead.com/spell=103826/fuerza-irresistible

![wowscrnshot_071813_172621](https://f.cloud.github.com/assets/3101842/822674/ff806b32-eff4-11e2-9d64-af8678559432.jpg)

Tras usar cargar deberia de darme un buff que aumenta un 25% Probabilidad de que sea critico mi siguiente golpe mortal o embate ps doy cargar y no me aparece el buff...

**Comment by searum** [comment]
fix
