### ISSUE TITLE
[paladin] Sello de Perspicacia

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#593]
http://old.wowhead.com/spell=20165/sello-de-perspicacia

La sanación esta bug (para mi): El sello dice que me cura 1600\* y lo que se ve en acción es que cura 300,400,500 o hasta 600 por golpe.

Edit (6/ag): Ahora esta curando 800-900 `por golpe y a veces cura 1100 o 1200 sin usar o usando alitas.

El sello de perspicacia habla tambien de una recuperación del 4% del mana, y en realidad esta recuperando +4 puntos de mana por segundo.

![wowscrnshot_071813_165809](https://f.cloud.github.com/assets/4790547/822703/6f3d43e6-eff5-11e2-894b-9119de193f5d.jpg)

**Comment by ghost** [comment]
Ya que mencionas lo de +4 mana por segundo, debería ser 4% de mana BASE por golpe que hagas (nada más porque no especificas lo de por golpe y lo de base).

**Comment by lamaza** [comment]
Creo que estaba especificado, Cuando dice el spell (por cada ataque cuerpo a cuerpo, bajo probabilidad que no manejo) sobre curar vida y mana.

Dice 1600 de vida y 4% del mana base.

En este caso serian 988 de mana. NO 4 de mana.

No sé como lo ves, yo lo tengo claro.

**Comment by ghost** [comment]
Nada más lo dije porque dices tu, que debe recuperar 4% del mana, y no dices la parte de base ni tampoco que sea por golpe (aunque este en la descripción del spell), tampoco dije que lo de 4 de mana estubiera bien xd, por otra parte la probabilidad para que suceda eso tengo entendido que es 100%.

**Comment by searum** [comment]
fix

**Comment by lamaza** [comment]
gracias Sea!
