### ISSUE TITLE
[paladin] Guardian de los Antiguos Reyes - Reprension

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#594]
http://es.wowhead.com/spell=86698/guardian-de-los-antiguos-reyes

El skill Guardian de los Antiguos Reyes en paladin reprensión no funciona, no sale ningún guardian (visualmente), no hay daño sagrado extra, y tampoco sale ningún beneficio (buff) de daño acumulado/sagrado extra etc. No pasa nada al activarlo.

![wowscrnshot_071813_170143](https://f.cloud.github.com/assets/4790547/822715/acce207c-eff5-11e2-93b0-3c28ced037e3.jpg)
![wowscrnshot_071813_170147](https://f.cloud.github.com/assets/4790547/822716/acd257a0-eff5-11e2-949f-05f0e352aa7e.jpg)

**Comment by searum** [comment]
fix

**Comment by lamaza** [comment]
Searum, estoy usando el hechizo y no sale el guardian ni me da debuff ni nada :/.

**Comment by searum** [comment]
Esto ya esta, se me olvido una cosa.. SOY HUMANO!
