### ISSUE TITLE
[paladin] Escudo Sacro

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#595]
http://cata.openwow.com/spell=85285

Escudo sacro: Salta de vez en cuando, es decir salta cuando se le da la gana y no bajo las condiciones que deberia saltar, que es cada 60s siempre y cuando la vida este por debajo del 30% y además, que dure 15 secs. Para que no se pierda detalle =).

**Comment by searum** [comment]
fix

**Comment by lamaza** [comment]
Acabo de ver que dijiste fix, no lo he probado directamente, pero lo haré y diré si quedó fix.
