### ISSUE TITLE
[Paladin] Colera santificada

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#597]
Se supone que este talento (colera santificada) http://www.wowhead.com/spell=53376
al tenerlo al maximo, nos permite a los paladines reprension que siempre que usemos (colera vengativa) http://es.wowhead.com/spell=31884 se nos va a activar por ese tiempo con su respectivo cd (martillo de colera) http://www.wowhead.com/spell=24275

Lo que esta pasando, es que por mas que actives colera sagrada, el martillo jamás se activa :/.

![wowscrnshot_071813_170642](https://f.cloud.github.com/assets/4790547/822751/06e2bb4e-eff7-11e2-95f4-f5b97face6c1.jpg)
![wowscrnshot_071813_170640](https://f.cloud.github.com/assets/4790547/822752/06fa9624-eff7-11e2-961b-31c271ac6f9f.jpg)
![wowscrnshot_071813_170638](https://f.cloud.github.com/assets/4790547/822758/266172a8-eff7-11e2-9fac-74045df09ccb.jpg)

Ahi en las imágenes se ve lo que dice el talento, y como al activar el spell, no desencadena el martillo de colera :/.

**Comment by searum** [comment]
fix

**Comment by lamaza** [comment]
Probado, y quedo OK :)
