### ISSUE TITLE
[Paladin] Propósito Divino

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#598]
http://www.wowhead.com/spell=86172

Cuando salta este buff, el paladin tiene la opcion de lanzar (gratis) cualquiera de las habilidades descritas en la imagen, pero ocurre un bug con el spell veredicto del templario http://www.wowhead.com/spell=85256, y es que permite lanzarlo hasta que dure el buff del talento mencionado.

Es decir, que el spell "Veredicto del templario" detecta cargas infinitas X3 de poder sagrado (cuando proposito divino esta activado), o algo por el estilo.

![wowscrnshot_071813_171512](https://f.cloud.github.com/assets/4790547/822778/b5c58b6e-eff7-11e2-9744-c7202152fd31.jpg)

**Comment by Dekadencee** [comment]
Fixed

**Comment by lamaza** [comment]
Al dia de hoy, hemos probado (moya y yo) el veredicto del templario bajo el efecto normal de 3 cargas de Poder Sagrado sin PD, y bajo el efecto de este talento de propósito divino (PD), resultado:

El fix que se le ha hecho no es correcto, ya que cuando salta el buff de PD y lanzamos el VdT, este utiliza las cargas de poder sagrado que tengamos en el momento (1 , 2 o 3 y hace daño de acuerdo a eso), y no tiene en cuenta lo que el buff nos dice (3 cargas gratis).

Además de esto, el daño es incorrecto (de VdT mediante PD) también (creemos que es el de 4.0.6 y no de 4.3.4).

Mirar esto un poco por favor.

**Comment by Moyax** [comment]
Antes de la actualizacion el pala tenia ese mismo problem. Lo recuerdo como si fuera ayer T_T siento que eh viajado atras en el tiempo.

**Comment by Dekadencee** [comment]
Los fixes se realizan en cuestión a lo que reportais, el reporte ponia que no consumia las cargas y ahora las consume por lo tanto no es que no sea correcto es que ha habido poca información, reabro para realizar el ajuste del daño.

Un saludo

**Comment by Moyax** [comment]
Aqui hay un poco mas de info acerca de como esta funcionando actualmente. #687

**Comment by searum** [comment]
fix
