### ISSUE TITLE
[Cazador] La vida de la mascota es "infinita".

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#600]
Sucede que, le bajas la vida a la mascota del cazador, ya sea cualquier tipo de mascota que tenga, se regenera instantaneamente, obviamente no debe de ser así.
Algunos cazadores se hacen invisibles con camuflaje y dejan que la mascota te ataque y obviamente solo te queda morir porque es imposible matar a la mascota, también estan aprovechando la mascota para tankear bosses....

**Comment by efectokoleos** [comment]
fixed
