### ISSUE TITLE
[Campo de Batalla] Playa de los ancestros bug alianza

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#601]
Buenas, para avisar que si eres alianza y te sale esta BG, y entras en ella, sales en medio del mar y el barco que te deberia llevar a la playa es medio fantasma, hay un truco para poder montarse al barco pero en si el 90% de las veces falla.

Según dijeron, esto no pasa con la horda, ellos si salen bien en su playa cuando tienen que atacar.

**Comment by F4NT4SM4** [comment]
no todos los hordas salimos en la playa la mayoria cae en el agua pero nos montamos esperando el barco cuando este se encuentre encima de uno saltamos y nos movemos hacia alante y listo

**Comment by lamaza** [comment]
Gracias por el dato fantasmaa haha

**Comment by searum** [comment]
fix
