### ISSUE TITLE
[Misión] (Las Mil Agujas) That Smart One's Gotta Go

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#602]
Hay que acabar con el listo http://es.wowhead.com/quest=28048

No está el npc objetivo de la misión.
Controlador de colmena  http://es.wowhead.com/npc=47389

Un saludo.

**Comment by efectokoleos** [comment]
comprobado y el npc está, lo habrían matado antes de que llegaras

**Comment by crowel** [comment]
Hola hay un npc con ese nombre, pero no da la opcion de entregar la misión, por eso supuse que seria otro, ya que en el que está no se podía entregar, o quizas fuera otro muerto.
Un saludo.

**Comment by redneo** [comment]
Con el gm off no se ve el npc, pero lo mas extraño que no tiene auras raras, ni nada por el estilo y da igual donde lo spawnees, que no aparece.... investigaré mas

**Comment by Compresor** [comment]
Si que está el npc cierro
