### ISSUE TITLE
[Misión] Go Blow that Horn

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#603]
Toca el cuerno http://es.wowhead.com/quest=25813

La primera parte de la misión tocar el cuerno funciona y cuenta como objetivo.
El proble está que tras tocarlo no aparece el elemental(segundo objetivo de la misión que hay que matar)
Whrrrl http://es.wowhead.com/npc=41334

Video: http://www.youtube.com/watch?v=fhKMIfleols

Un saludo.

**Comment by redneo** [comment]
Podria funcionar cuando caiga el server, no cierro por si no es así!

**Comment by crowel** [comment]
Funcionando perfectamente.
