### ISSUE TITLE
[Misión] Bar Fight!

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#604]
¡Pelea de bar! http://es.wowhead.com/quest=25517

Hola queria reportar una caracteristica de está misión.
@redneo Como pudiste comprobar en el otro reporte de los npcs de Mil agujas, del barcodromo, dentro del bar todos los NPCs se estan peleando.
La misión funciona correctamente, el unico defecto es que ya se estan peleando desde el comienzo cosa que no deberia pasar hasta utilizar:
Botella de grog http://es.wowhead.com/item=54746 http://es.wowhead.com/item=54747
Nose exactamente cual de las dos es.
Tras usarla es cuando deberian comenzar a golpearse todos.

Queria añadir tambien que los npcs de fuera del bar que cambiamos la faccion siguen atacando a la alianza.

Aqui un video. http://www.youtube.com/watch?v=UcJONRRyYCI

Un saludo.

**Comment by redneo** [comment]
Dificil de arreglar... lo siento :S
