### ISSUE TITLE
[Misión] Save the Sentinel

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#605]
Salva a la centinela http://es.wowhead.com/quest=25871

Está misión trata de salvar una centinela encadenada a un poste.
Centinela de Feralas capturado http://es.wowhead.com/npc=41463

Aunque la nuestra es de armas tomar, está libre por ahí atacando a unos Npcs invisibles, jaja.
![wowscrnshot_071913_035715](https://f.cloud.github.com/assets/3537253/823597/ca417b88-f016-11e2-91de-bd322d01ce9e.jpg)

Un saludo.

**Comment by redneo** [comment]
Creo que está arreglada, aunque el npc que buscas no es es que has puesto en la imagen, la he puesto encadenada, donde está el vuelo horda...

http://wow.zamimg.com/uploads/screenshots/resized/198035.jpg

**Comment by crowel** [comment]
Funciona, cierro^^
