### ISSUE TITLE
[Misión] Defend the Drill

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#606]
Defiende la plataforma petrolera http://es.wowhead.com/quest=25798

Tras aceptar la misión aparece como completada sin hacer nada, pudiendo entregarla.
![wowscrnshot_071913_032730](https://f.cloud.github.com/assets/3537253/823606/5e876028-f017-11e2-9253-e217afc73610.jpg)

Nose si funciona el objetivo de la misión.

Un saludo.

**Comment by redneo** [comment]
paso de comerme la cabeza, que seguro que tienen que salir mil bichos y atacar la plataforma...
