### ISSUE TITLE
[Misión] In the Outhouse

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#607]
En la letrina http://es.wowhead.com/quest=25524

Tras recojer la Palanqueta de pirata http://es.wowhead.com/item=54821 de uno de los npcs y utilizarla delante de la letrina no ocurre nada.
![wowscrnshot_071813_153319](https://f.cloud.github.com/assets/3537253/823621/32282fa2-f018-11e2-8350-4c1601d158fb.jpg)

"Requiere Letrina Sumergida" Aparece en letras rojas.

Un saludo.

**Comment by redneo** [comment]
fix
