### ISSUE TITLE
[Misión] We All Scream for Ice Cream... and then Die!

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#608]
Todo el mundo se muere por un helado… http://es.wowhead.com/quest=28051

Está misión se trata de buscar los Empleado muerto http://es.wowhead.com/npc=47446 y engancharlos con el cable del remolque.

El problema que no se puede interactuar con ellos, no se les puede hacer nada.

Aqui un video de como deberia funcionar. http://www.youtube.com/watch?v=zGh7zMXEHfY

Un saludo.

**Comment by redneo** [comment]
Cuando caiga el server funcionará
