### ISSUE TITLE
[NPC][Vuelo] Dyslix Kami-Kaze <Maestro de vuelo>

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#610]
Dyslix Kami-Kaze <Maestro de vuelo> http://es.wowhead.com/npc=40358
Ocurre lo mismo con el NPC del reporte que cree un rato antes https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/609.
Aparece el mensaje " No conoces ningun otro lugar de vuelo relacionado con este"
Siendo el otro que no funciona el siguiente de este y teniendo liberado los dos anteriores más cercanos a este.

Un saludo.

**Comment by redneo** [comment]
Arreglado y supongo que otros 15 tipos que les pasaba lo mismo tambien estaran arreglados
