### ISSUE TITLE
[Inscripción][Moler] Fallo plantas al moler

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#611]
Hola quiero reportar este fallo, que le ocurre a un amigo, tras moler las siguientes plantas, no le aparece ningun pigmento al moler, estando vacio.

Flor de paz http://es.wowhead.com/item=2447 
Hojaplata http://es.wowhead.com/item=765
Raíz de tierra http://es.wowhead.com/item=2449

Ambas deberian de dar Pigmento de alabastro http://es.wowhead.com/item=39151
Flor de paz 2-3 %100
Hojaplata 2-3 %100
Raíz de tierra 2-4 %100

Esto ocurre en las tres primeras plantas que se pueden cojer con herboristeria, nosé si ocurre con las demás.
En caso de que ocurra las iré añadiendo.

Un saludo.

**Comment by redneo** [comment]
fix
