### ISSUE TITLE
El ojo de la eternidad (malygos)

### ISSUE THREAD

**Issue by lllalvarolll** [RoDNet/Bugtracker-Infinium-4.3.4#612]
Hemos estado probando a Malygos y a mi parecer esta bastante bien la 1º y 2º fase. El problema llega en la 3º, que, cuando te subes al draco para atacar a malygos, dice que no puedes ver al objetivo, por lo cual no puedes atacarle. A parte de eso, nada mas entrar en la 3º fase, apareces debajo de la plataforma y malygos atravesado entre la plataforma. Saludos.

**Comment by Wiinter** [comment]
#819  Lo siento repetí tu post :S

**Comment by efectokoleos** [comment]
fixed
