### ISSUE TITLE
El Truenodromo (Tanaris)

### ISSUE THREAD

**Issue by D3VIL238** [RoDNet/Bugtracker-Infinium-4.3.4#614]
Todas las misiones del Truenodromo estan bug y nada mas cojerlas sin eliminar al enemigo de la mision se pueden entregar directamente.

Truenódromo: ¡El Enormus!-http://es.wowhead.com/quest=25067/truenodromo-el-enormus

Truenódromo: ¡Pelea!:http://es.wowhead.com/quest=25513/truenodromo-pelea

Truenódromo: ¡Zumonga!:http://es.wowhead.com/quest=25094/truenodromo-zumonga

Truenódromo: ¡Sarinexx!:http://es.wowhead.com/quest=25095/truenodromo-sarinexx

**Comment by crowel** [comment]
Hola iva a reportar esto pero ya está reportado, al cojerlas tampoco aparecen los npcs a matar.

Saludos.

**Comment by Kiritoo** [comment]
Esto funciona correctamente.

**Comment by paellaencol** [comment]
Funciona, dejad la mision y volved a cogerla, a la segunda ya salen.
