### ISSUE TITLE
Misiones bug en Dun Morogh

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#615]
1 Vigilando desde lejos
No puedes informar a los montaraces del cubil pardo para que regresen a Kharanos
2 El avance 
Los montaraces no se encuentran atrapados por los tótem de constricción y dichos totem no pueden ser quemados con la runa de fuego.
3 Sigue a ese girocoptero 
El girocoptero no llega a aparecer ni el piloto tampoco.
4 Detén al embajador 
Las esposas no funcionan con él.
5 Lanzador personal ultraseguro
No se puede usar la maquina (revisad el paracaídas que se activa antes de tocar el suelo)
6 Ataque desde el cielo 
Los girocopteros no aparecen para atacar el poblado peloescarcha.
7 Asalto nocturno
Los trolls no aparecen para atacar la granja.
8 El servidor publico 
La runa no afecta a los mineros 
9 Tumbas de hielo 
No están las tumbas de hielo donde deberian por lo que no se les puede matar
10 El complejo vetaferro
No se puede realizar ya que el Capitan Beld no está http://www.wowhead.com/npc=6124

**Comment by lamaza** [comment]
Como ya nos han dicho a otros, 1 issue por mision y con su respectivo # ID (link a DB). Y ojala se puedan solucionar.

**Comment by redneo** [comment]
Si por favor, con enlaces de wowhead, al menos de la mision
