### ISSUE TITLE
misiones bug en terrallende

### ISSUE THREAD

**Issue by lperezf** [RoDNet/Bugtracker-Infinium-4.3.4#616]
hay muchas misiones bug en terrallende estoy aun ahi y ayer me encontre de nuevo con otro bug entre estos bugs estan la ciudad de la luz en el templo q hay y el otro q vi era el baston del archimago en el area 52 favor revisar las misiones de terrallende

**Comment by redneo** [comment]
Puedes poner mision por mision con enlaces a wowhead??? gracias!
