### ISSUE TITLE
[Mazmorra] La cumbre del vórtice

### ISSUE THREAD

**Issue by lllalvarolll** [RoDNet/Bugtracker-Infinium-4.3.4#617]
Todos los NPC que hay antes del primer boss tienen la misma vida ( no se si esta bien o no, pero ante la duda, prefiero ponerlo).
En el primer boss, cuando los remolinos deberian de juntarse al boss, se quedan quietos pero te hace daño igualmente.
Una vez muerto el primer boss, no hemos podido continuar debido a que el remolino no estaba para poder saltar a la siguiente zona.

**Comment by crowel** [comment]
Boss Gran visir Ertan http://es.wowhead.com/npc=43878
Habilidad Invocar tempestad http://es.wowhead.com/spell=86340

**Comment by efectokoleos** [comment]
fixed

**Comment by lamaza** [comment]
Estaba fix hace como 1 semana que la hicimos y la terminamos, aunque el boss final es piñata.
