### ISSUE TITLE
[Mazmorra] Caverna roca negra.

### ISSUE THREAD

**Issue by lllalvarolll** [RoDNet/Bugtracker-Infinium-4.3.4#618]
El primer boss:
- No suelta los adds que debería.
- Cuando usa cadenas, no solo te deja moverte a tus anchas, también la cadena aparece con forma de golem muy raro y va moviéndose.

De camino al segundo boss:
- Un zelote crepuscular se planto delante de un jugador sin poder atacarle, solo ponía evitar y nos seguía a todos lados.
  ![wowscrnshot_071913_175343](https://f.cloud.github.com/assets/3487127/827127/787f7c8e-f096-11e2-903f-6c1896ef1f47.jpg)
- La mayoria de las habilidades que lanzábamos hacia lo zelotes crepusculares, ponía "resistir".
  ![wowscrnshot_071913_175618](https://f.cloud.github.com/assets/3487127/827129/a7f1aaf0-f096-11e2-8cb3-fe461df0d885.jpg)
  El segundo boss sigue igual que en la anterior versión, es decir, piñata. (También resistía muchas habilidades)
  ![wowscrnshot_071913_175843](https://f.cloud.github.com/assets/3487127/827146/ef25c7d0-f096-11e2-9d5e-25516e8b7c50.jpg)
  Antes de llegar al 3º boss, las babosas nos atacaban y nos seguian, sin poder ser seleccionadas.
  ![wowscrnshot_071913_181127](https://f.cloud.github.com/assets/3487127/827157/2187be7c-f097-11e2-94da-41707c06c352.jpg)
  y bueno, ya hubo reinicio y lo dejamos aquí. Saludos.

**Comment by efectokoleos** [comment]
fixed
