### ISSUE TITLE
[Npc] No esta Anduin Wrynn (Principe de Vertomenta)

### ISSUE THREAD

**Issue by Huardruid** [RoDNet/Bugtracker-Infinium-4.3.4#62]
[URL=http://imgur.com/DJTWCP0][IMG]http://i.imgur.com/DJTWCP0.jpg[/IMG][/URL]

**Comment by Huardruid** [comment]
<a href="http://imgur.com/DJTWCP0"><img src="http://i.imgur.com/DJTWCP0.jpg" title="Hosted by imgur.com" /></a>

Perdonad

**Comment by redneo** [comment]
podias ponerme id del npc???
