### ISSUE TITLE
[Guerrero] Embate

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#620]
http://es.wowhead.com/spell=1464/embate

El bug es que al hacer un embate salen 2 alguna veces hasta 3 y solo deberia de ser 1 no hay ningun talento que modifique que haga doble embate
y en fury tenemos un talento para que embate sea inst y sea 20% mas de daño salta muy seguido es decir gracias a este bug que hace que salgan mas embate pegamos el doble o triple con embate con 1 sola tecla...

**Comment by hairblood** [comment]
no es que se haga instant con ese talento.Uno hace que tenga posibilidades de ser instantaneo pero la que dices hace que por usar 2 armas de una mano pegas un 20% mas y puede pegar embate con ambas armas
http://es.wowhead.com/spell=81099 (esta es la del embate doble,pero esta en version mop...ponle 20% daño y usar embate con las 2 armas)

**Comment by F4NT4SM4** [comment]
me refiero a que embate pega 3 veces o 2 veces en cualqueir talento y como en fury tiene un talento que lo hace inst y pege mas lo hace over ahora si me explico?
