### ISSUE TITLE
[Guerrero] Ira al Recibir daño

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#624]
El guerrero no esta Generando ira al Recibir daño

![wowscrnshot_071913_193428](https://f.cloud.github.com/assets/3101842/829282/557e54fa-f0d0-11e2-9936-ea9590be5a87.jpg)

Muchos guerreros fury anda llorando de que no hacen dps ya que no generan ira...

**Comment by ghost** [comment]
También hay que revisar la ira que genera el guerrero al golpear, genera demasiada ira.

En wowwiki están las fórmulas de cómo se genera la ira haciendo ataques, y recibiendo daño, son algo complicadas.
http://www.wowwiki.com/Rage

También si esto de la ira, se puede aplicar al Druida oso, que también le afecta por usar la ira.

**Comment by searum** [comment]
fix
