### ISSUE TITLE
El ascensor de enclave escarlata esta bugueado

### ISSUE THREAD

**Issue by D3VIL238** [RoDNet/Bugtracker-Infinium-4.3.4#625]
El ascensor del enclave escarlata esta bugueado y después de usarlo unas pocas veces ya no te teletransporta,me he quedado atrapado arriba y no hay manera de salir,no se puede avanzar con el dk,este es el 2º que me hago ya que el primero tuve que borrarlo por otro bug y me gustaría no tener que borrar este también,gracias.

**Comment by redneo** [comment]
No lo borres, deja ticket ingame a ver si te encuentro y miro la fase que estas, por cierto, el nombre de tu pj me vendria de maravillas.

**Comment by makidavid** [comment]
A mi tambien me ha pasado, dejé un ticket ingame y no tuve respuesta, mi personaje es Liguhr

**Comment by D3VIL238** [comment]
El nombre de mi pj es Boton,siento la tardanza redneo pero esque hoy no me he podido conectar,gracias

**Comment by D3VIL238** [comment]
Por avisar digo que sigue pasando,y sigo atrapado

**Comment by D3VIL238** [comment]
Fixeado,Gracias a Bofur
