### ISSUE TITLE
Roer no ataca

### ISSUE THREAD

**Issue by letalman** [RoDNet/Bugtracker-Infinium-4.3.4#626]
Me explico cuando estas en profano del dk el poder del esbirro roer no hace nada siempre te dice este hechizo no esta listo aun y porfavor si pueden arreglar el error de que uno siempre se monta en la montura y tiene que volver a sacar el esbirro de nuevo porque eso es un problema en bg

**Comment by ghost** [comment]
Dejo enlaces a wowhead, los dos se llaman roer y los dos son del necrófago, así que no sé cual es el correcto S:  
http://es.wowhead.com/spell=91800
http://es.wowhead.com/spell=47481/

Lo del error al montar y desmontar, ¿puedes ponerlo en otro reporte?, @letalman

**Comment by letalman** [comment]
http://es.wowhead.com/spell=47481/ este es el correcto

**Comment by searum** [comment]
tengo otro issue mas completo que este
