### ISSUE TITLE
Npc con daño demasiado alto 

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#627]
Ruul Onapiedra
http://es.wowhead.com/npc=2602/ruul-onapiedra#drops
Tiene demasiado daño para su nivel.
![wowscrnshot_072013_105410](https://f.cloud.github.com/assets/5048096/829952/0dac5006-f11a-11e2-8f4a-380c92aa818e.jpg)
Me da un solo puñetazo y me quita 900

**Comment by redneo** [comment]
Ya se le ha bajado el daño.
