### ISSUE TITLE
[Guerrero] Ataque de la victoria

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#628]
Al atacar con esta spell.
http://es.wowhead.com/spell=34428
Nos cura de más como si tuviesemos el glifo puesto.
http://es.wowhead.com/spell=58382
Encima al ponerle ese glifo nos aumenta aun más la sanación con lo que nos cura más de la vida que tenemos con un crítico.

**Comment by searum** [comment]
fix
