### ISSUE TITLE
El misterio del infinito(cementerio de Dragones)

### ISSUE THREAD

**Issue by harrypaqueton** [RoDNet/Bugtracker-Infinium-4.3.4#631]
Pues eso en esta mision tienes que poner el reloj de arena para que mientras recoge informacion lo defendamos pero al llegar al santuario no lo puedes usar
![wowscrnshot_072013_172110](https://f.cloud.github.com/assets/4949764/830440/7ad3d5d8-f150-11e2-827b-30cedeaf0fcf.jpg)

**Comment by veyertrox** [comment]
que yo recuerde, solo se puede usar el reloj de arena en el centro del santuario, en donde están unos huesos de dragón, pero no te lo podría asegurar pues hice esta misión antes de la actualización, y no se si después de esto ultimo y/o después del rollback esta misión se vio afectada, compruébalo tu mismo

**Comment by harrypaqueton** [comment]
Si dejar ahora me deja pero la cosa esta en que lo dejo pero no aparece nadie pa defender y si baja alguien son elites 80 es asi??

**Comment by veyertrox** [comment]
me parece, si pudieras dejar el enlace de la misión y los mobs que faltan, mas que mejor

**Comment by harrypaqueton** [comment]
aqui dejo el enlace d etoda la mision http://es.wowhead.com/quest=12470/el-misterio-del-infinito#.

**Comment by crowel** [comment]
![wowscrnshot_080913_014629](https://f.cloud.github.com/assets/3537253/975616/59b394ce-067c-11e3-9d35-5194561dcf1c.jpg)

Se puede dejar el reloj, no aparece ningun npc asi que no se defiende nada, tras ocurrir esto esperas y esperas y desaparece el reloj y la misión imcompleta, saludos.

**Comment by efectokoleos** [comment]
arreglada
