### ISSUE TITLE
[Guerrero] Salto heroico Over!

### ISSUE THREAD

**Issue by lllalvarolll** [RoDNet/Bugtracker-Infinium-4.3.4#632]
Buenas. El daño que están haciendo los guerreros con salto heroico es muy bestia.
![wowscrnshot_072013_174748](https://f.cloud.github.com/assets/3487127/830486/d0169ada-f155-11e2-9b27-9a216cd4fe55.jpg)
![wowscrnshot_072013_175622](https://f.cloud.github.com/assets/3487127/830488/dd0c12ce-f155-11e2-800f-9305187eb0be.jpg)
En la última foto marco el daño que debería de hacer.

**Comment by redneo** [comment]
Culpa mia, procedo a arreglarlo!!!!
