### ISSUE TITLE
Un disfraz apropiado> Mision

### ISSUE THREAD

**Issue by Hellythium** [RoDNet/Bugtracker-Infinium-4.3.4#635]
Buenas, estoy para informar que la misión ''Un disfraz apropiado'' (Horda) http://es.wowhead.com/quest=24556/un-disfraz-apropiado para el logro ''La Espada prometida'' http://es.wowhead.com/achievement=4596/la-espada-prometida esta bug, puesto a que cuando vais a hablar con el NPC Shandy Lustre Brillo http://es.wowhead.com/npc=36856/shandy-lustre-brillo el no te continua el dialogo como es debido para la completación de la misión, dejare unas imágenes, espero que se entiendan, mostrando cuando le doy click y no pasa nada:
![wowscrnshot_072013_125056](https://f.cloud.github.com/assets/3613748/830640/43c4f4c6-f166-11e2-9800-f18e5f0df17f.jpg)
![wowscrnshot_072013_125059](https://f.cloud.github.com/assets/3613748/830641/43c8ae5e-f166-11e2-911a-5bc7be5ee9db.jpg)

por favor, necesito que revisen eso, para poder completar el logro, gracias por la atención.

Saludos, Darkstar.

**Comment by searum** [comment]
fix falta traducir
