### ISSUE TITLE
Rates x1

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#64]
Los multiplicadores de experiencia estan x1 

![wowscrnshot_070413_041125](https://f.cloud.github.com/assets/4895839/748485/6b908206-e48a-11e2-85be-dd5a043eb2dc.jpg)

![wowscrnshot_070413_041143](https://f.cloud.github.com/assets/4895839/748486/70c114f2-e48a-11e2-8fe2-37521146bdb5.jpg)

Deberian estar x5 no?

**Comment by SherBlader** [comment]
![wowscrnshot_070413_041143](https://f.cloud.github.com/assets/4895839/748621/2cfa3650-e48e-11e2-8ebd-f519e00a41b5.jpg)

Link de Wowhead de la mision: http://es.wowhead.com/quest=25136/sorpresa-de-manzanas-de-cactus-de-galgar
Ganancias
Cuando completes esta misión ganarás:
380 experiencia
500 reputación con Orgrimmar

es decir, se esta obteniendo lo mismo (que no deberia ser asi)

Esta situacion sucede con todas las misiones!

**Comment by Dekadencee** [comment]
Recordad que estamos en fase de Testeo, obviamente no tenemos la misma configuración de rates que vamos a tener despues, paciencia, nada mas esté estable y hagamos rollback pondremos los rates como es debido
