### ISSUE TITLE
Habilidad de picaro forzar cerraduras esta bug

### ISSUE THREAD

**Issue by Rametep** [RoDNet/Bugtracker-Infinium-4.3.4#640]
la habilidad de forzar cerraduras de picaro pone que la dan a nivel 20, pero a nivel 16 me dejaron cogerla aunque no funcionaba (la coji accidentalmente dandole a aprender todo). ahora que tengo nivel 20 con mi picaro sigue sin funcionar, pese a que pone que abre cofres y puertas de hasta 100 de dificultad.
Espero que se pueda arreglar pronto.
gracias por todo!!!

**Comment by WarSxNes** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/94?source=cc <<< POST RELACIONADO

---

Te gane ya la habia reportado xD,,,, te gane por 546 post anteriores a este hihihi... 

> por cierto ya hay muchos post,,,, y algunos asta estan duplicados y puestos en diferentes categorias...
> EJEMPLO: 
> el 94 que es el mio esta como (ERRORES de CLASES)
> Y este 640 como (HECHIZOS y talentos)

---

> Seria bueno darle una limpiadita, Empezando a reparar bugs e ir cerrando los mas faciles xD...

**Comment by searum** [comment]
fix
