### ISSUE TITLE
Buff que no deberían de poder usarse al mismo tiempo.

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#642]
Buenas, estos tres buff no deberían de poder usarse al mismo tiempo, al usar uno, debería de remover al otro.

Bendición de reyes http://es.wowhead.com/spell=20217
Marca de lo Salvaje http://es.wowhead.com/spell=1126
Abrazo de la araña de esquisto http://es.wowhead.com/spell=90363

**Comment by redneo** [comment]
arreglado
