### ISSUE TITLE
[Huargen] Misión "Evacúa la plaza de los mercaderes"

### ISSUE THREAD

**Issue by Eressear** [RoDNet/Bugtracker-Infinium-4.3.4#643]
La misión "Evacúa la plaza de los mercaderes" (http://es.wowhead.com/quest=14098/evacua-la-plaza-de-los-mercaderes) no se puede completar porque las puertas no se pueden abrir. Esto provoca que no se puedan realiar mas misiones ni variar el phasing.

**Comment by crowel** [comment]
Está misión funciona correctamente, cierro issue.
Un saludo.
