### ISSUE TITLE
[NPC] Jamus'Vaz

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#648]
Este npc actualmente no vende nada, debería de vender items que se compren con puntos de valor, no sé lo que debería de vender en esta temporada del parche 4.2.
![wowscrnshot_072013_160521](https://f.cloud.github.com/assets/4663665/830788/bd76925a-f177-11e2-8b9b-e897c2577462.jpg)
http://es.wowhead.com/npc=46556
http://www.wowwiki.com/Jamus%27Vaz

**Comment by crowel** [comment]
Fix, En la alianza también.
