### ISSUE TITLE
[NPC] Gunra

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#649]
Este npc actualmente no vende nada, debería de vender items que se compren con puntos de justicia, no sé lo que debería de vender en esta temporada del parche 4.2.
![wowscrnshot_072013_160525](https://f.cloud.github.com/assets/4663665/830795/6e819716-f178-11e2-8330-379ca50e42c0.jpg)
http://es.wowhead.com/npc=46555
http://www.wowpedia.org/Gunra

**Comment by crowel** [comment]
Fix, en la alianza también.
