### ISSUE TITLE
[Hunter] Set Implacable y Cataclísmico

### ISSUE THREAD

**Issue by shials** [RoDNet/Bugtracker-Infinium-4.3.4#65]
A los Hunters no nos deja ver los set Implacable y Cataclísmico, no se si nos pasa solo a nosotros pero en los respectivos vendedores no aparece dichos set.

Buena Caza !

**Comment by Huardruid** [comment]
No le deja a ninguna clase hasta que reinicien los puntos de honor

**Comment by redneo** [comment]
podias ponerme ids de los items y de los vendedores?

**Comment by shials** [comment]
http://www.wowhead.com/npc=69975 vendedor set y armas cataclísmicas
http://es.wowhead.com/npc=52537/knight-lieutenant-tmaire-sydes vendedora set y armas implacables

**Comment by ghost** [comment]
Por ejemplo con mi guerrero sí que veo que el vendedor y la vendedora tienen los items del set de pvp, pero sin embargo con mi sacerdote no xD Y me supongo que pasará con otras clases también a parte del Priest y el Hunter

**Comment by shials** [comment]
Set Implacable:
-Cuello
http://es.wowhead.com/item=70380
http://es.wowhead.com/item=70379
-Anillos
http://es.wowhead.com/item=70374
http://es.wowhead.com/item=70375
-Pies
http://es.wowhead.com/item=70337
http://es.wowhead.com/item=70335
-Espalda
http://es.wowhead.com/item=70386
http://es.wowhead.com/item=70385
-Pecho
http://es.wowhead.com/item=70259
-Manos
http://es.wowhead.com/item=70260
-Cabeza
http://es.wowhead.com/item=70261
-Piernas
http://es.wowhead.com/item=70262
-Hombros
http://es.wowhead.com/item=70263
-Muñecas
http://es.wowhead.com/item=70340
http://es.wowhead.com/item=70338
-Cintura
http://es.wowhead.com/item=70339
http://es.wowhead.com/item=70336

PD: las armas implacables de Hunters si están :D

**Comment by shials** [comment]
Set Cataclísmico:
-Espalda
http://es.wowhead.com/item=73647
http://es.wowhead.com/item=73646
-Pecho
http://es.wowhead.com/item=73584
-Manos
http://es.wowhead.com/item=73583
-Cabeza
http://es.wowhead.com/item=73582
-Piernas
http://es.wowhead.com/item=73581
-Hombro
http://es.wowhead.com/item=73580
-Muñecas
http://es.wowhead.com/item=73586
http://es.wowhead.com/item=73585
-Cintura
http://es.wowhead.com/item=73589
http://es.wowhead.com/item=73590
-Cuello
http://es.wowhead.com/item=73645
http://es.wowhead.com/item=73644
-Anillos
http://es.wowhead.com/item=73640
http://es.wowhead.com/item=73641
-Pies
http://es.wowhead.com/item=73587
http://es.wowhead.com/item=73588

PD: Las armas cataclísmicas de Hunters si están :D

**Comment by ghost** [comment]
Dans, armas de hunter? loool Desde cuándo tenéis arma específica? xD Las armas están todas. Lo que faltan son los sets de prácticamente todas las clases.

**Comment by shials** [comment]
Si tiene armas implacables y cataclísmicas.. , la pica de gladiador implacable 
http://es.wowhead.com/item=70225/pica-de-gladiador-implacable pica implacable
http://es.wowhead.com/item=73423/pica-de-gladiador-cataclismico y aqui tienes la pica cataclísmica

**Comment by ghost** [comment]
No es un arma específica de hunter sigo diciendo (No pone clase: cazador) xD 

A parte, como ya he dicho anteriormente, las armas están bien todas. Lo que fallan son los sets :)

**Comment by redneo** [comment]
metidos todos. creo
