### ISSUE TITLE
[Misiones] Kaw el Destructor de Mamuts

### ISSUE THREAD

**Issue by veyertrox** [RoDNet/Bugtracker-Infinium-4.3.4#657]
pues en esta misión (http://es.wowhead.com/quest=11879) hay que matar a este npc "Kaw el Destructor de Mamuts" (http://es.wowhead.com/npc=25802) y debería lotear "Alabarda de guerra de Kaw" (http://es.wowhead.com/item=35234), pero no lotea el objeto y por ende no se puede completar la misión

Aquí imágenes:
 El npc a matar 
![wowscrnshot_072013_190611](https://f.cloud.github.com/assets/4959242/830984/6816afe2-f191-11e2-8335-36694a747a66.jpg)

Acá después de matarlo
![wowscrnshot_072013_190629](https://f.cloud.github.com/assets/4959242/830985/799132b0-f191-11e2-977f-172cd5299842.jpg)
y se muestra que no lotea nada ni el objeto para completar la misión, si lo pudieran arreglar mas que mejor

**Comment by redneo** [comment]
arreglado
