### ISSUE TITLE
mision de picaro

### ISSUE THREAD

**Issue by letalman** [RoDNet/Bugtracker-Infinium-4.3.4#664]
pueden arreglar la mision de las dagas legendarias del picaro que el ncp no aparece
http://es.wowhead.com/quest=30118/parricidio

**Comment by hairblood** [comment]
fijate que estas enseñando la ultima:aun no se se sabe si esta o no bug porque tiene que estar abierta la ultima raid para empezar la cadena
http://es.wowhead.com/quest=29801

**Comment by crowel** [comment]
Cierro este reporte hasta que se abra la raid, llegado el momento se revisara la cadena de misiones.
Un saludo.
