### ISSUE TITLE
[Brujo]Quemar alma

### ISSUE THREAD

**Issue by hairblood** [RoDNet/Bugtracker-Infinium-4.3.4#665]
dicha magia http://es.wowhead.com/spell=74434
deberia darle unos efectos extra a varios hechizos.El bug esta en que al lanzar un ataque deberia irse pero sigue haciendoq ue durante toda la duracion los hechizos hagan sus efectos mejorados sin limite (como fuegos de alma instantaneos y spameables)

**Comment by Velcositro** [comment]
Esto ya fué reportado por mi #558 y Searum ya lo arregló, lo unico que falla es que no se va al invocar demonios, pero todos los demás lo consumen...

**Comment by searum** [comment]
exacto, cierro porque el bug ya me lo conozco ^^ lo reparare
