### ISSUE TITLE
Misión --> (Cementerio de Dragones) La limpieza de jintha'kalar

### ISSUE THREAD

**Issue by harrypaqueton** [RoDNet/Bugtracker-Infinium-4.3.4#667]
http://es.wowhead.com/quest=12545/la-limpieza-de-jinthakalar
pues eso como dice lamision tengo que matar 15 miembros de la plaga en la zona indicada y no aparece ni peter y en la zona de arriba los que hay no te cuentan pa la quest.
![wowscrnshot_072113_124343](https://f.cloud.github.com/assets/4949764/831542/e2a829f0-f1f2-11e2-82ea-45d245ea1a66.jpg)

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
