### ISSUE TITLE
DONDE HAY PATRON

### ISSUE THREAD

**Issue by harrypaqueton** [RoDNet/Bugtracker-Infinium-4.3.4#670]
Tenemos que controlar un geist lo controlo y aparece como la mascota del caza pero en este caso debe salir un boton para uqe recoja los cristales pues no aparece http://es.wowhead.com/quest=12673/donde-hay-patron
![wowscrnshot_072113_170522](https://f.cloud.github.com/assets/4949764/831811/43ff72b6-f217-11e2-9728-a8a2a805ee19.jpg)

**Comment by redneo** [comment]
arreglada.
