### ISSUE TITLE
bug talento sacerdote

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#672]
el talento http://es.wowhead.com/spell=89485/enfoque-interno ,en principio funciona bien.

pero al curar con dichas habilidaddes del talento no se gasta,y siempre te cuestan 0 de mana todas las curas del talento, vamos que con ese talento tienen mana ifinito practicamente siempre que quieras.

un saludo

**Comment by redneo** [comment]
Arreglado
