### ISSUE TITLE
[Dk/Caballero de la Muerte] Fatalidad Súbita

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#673]
Talento: http://es.wowhead.com/spell=49530

Bug: Se activa el 100% de las veces, cada vez que se dá un golpe blanco te da el efecto, lo que permite hacer "spam" de Espiral de la muerte gratis. La probabilidad de activación de cada rango es desconocida, pero en Wowhead alguien hizo unos cálculos aproximados en el 4.3 y dice que al parecer cada rango aumenta en 6.3% más o menos, quedando así:
Rango 1: 6.3%
Rango 2: 12.6%
Rango 3: 18.9%

Anexo el comentario:
"I have followed the great idea of tyler2k and used SimCraft to determine Sudden Doom proc rate.

According to SC, whith a Unholy BiS T12 profile (avoiding the 2pt13 that can make false result) and 50000 iterations:

1/3 Sudden Doom : (12.3 procs on average, 197.1 melee hits) 6.24 % 1.76 ppm
2/3 Sudden Doom : (24.7 procs on average, 196.9 melee hits) 12.54 % 3.37 ppm
3/3 Sudden Doom : (37,0 procs on average, 196.8 melee hits): 18.80 % 4.96 ppm

So it seems that each point added to this talent increases the proc chance by a equal percent ( ≈ +6.3%)"

**Comment by redneo** [comment]
Arreglado, no con esos datos, pero parecidos, algo más bajos :D
