### ISSUE TITLE
bug habilidad feral

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#674]
la habilidad http://es.wowhead.com/spell=52610,hace la animacion bien,pero noda el daño extra de los golpes.

deveria de dar un 85% mas de daño de los ataques automaticos o golpes blancos,pero no lo da.

un saludo

**Comment by redneo** [comment]
a mi si que me pone el bufo correctamente y leyendo lo que hace el bufo...

Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 80
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 344 (SPELL_AURA_MOD_AUTOATTACK_DAMAGE), value = 80, misc = 1 (1), miscB = 0, periodic = 0
Effect Mechanic = 31 (MECHANIC_ENRAGED)

tendria que funcionar.

**Comment by 50megas** [comment]
las fotos que tome para el reporte pero seme olvido poner.

sin la habilidad.
<a href="http://tinypic.com?ref=1233a6h" target="_blank"><img src="http://i41.tinypic.com/1233a6h.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

con la habilidad.

<a href="http://tinypic.com?ref=2h7fcaq" target="_blank"><img src="http://i41.tinypic.com/2h7fcaq.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

como seve sale el bufo , pero el dps es practicamente el mismo.por cierto aumenta un 80% seme olvido que yo llevo elm glifo del 5%extra xd

un saludo

**Comment by searum** [comment]
fix
