### ISSUE TITLE
bug curas feral

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#676]
hola parece que las curas del feral estan muy suvidas,sobretodo http://es.wowhead.com/spell=33763 .

segun la la descripcion deveria de curar 228 y segun el drdamage 350,pero cura 1126, esto unido a que son 3 flores y aumentan un 20% las curas al cambiarte  a gato con talento , se buelve muy dificel matar aun feral que cada 10 seg te mete un ciclon se echa 3 fores y se cura full.

<a href="http://tinypic.com?ref=23mvr5" target="_blank"><img src="http://i39.tinypic.com/23mvr5.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

uns saludo.

**Comment by redneo** [comment]
Arreglado... sigue estando el fallo del poder de sanacion con el intelecto... :S
