### ISSUE TITLE
[BG] Batalla por gilneas

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#677]
La bandera de minas, y de estación de bombeo tenían la insignea de la horda al comenzar la bg, daban puntos a la horda y los de la alianza no podían cambiarlas.
La bandera de faro era neutral, y no se podía cambiar.

Cuando finalizaste la bg, salió esto.
![wowscrnshot_072113_121247](https://f.cloud.github.com/assets/4663665/831927/be4d9b48-f220-11e2-9ef3-e2c62a4518c1.jpg)

También esta el bug de que, algunos jugadores no pueden ver a los otros, aunque ese bug tengo entendido que ya no es de la BG.

**Comment by searum** [comment]
fix
