### ISSUE TITLE
[NPC] Kael´thas Caminante del Sol: El Castillo de la Tempestad

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#678]
Este boss pega de manera descomunal. Fijense en el daño, estoy seguro que requiere corrección, y creo que el problema es solo esa habilidad de bola de fuego.
![wowscrnshot_072013_130721](https://f.cloud.github.com/assets/4790547/832104/2235d700-f231-11e2-94d8-8d1ce767a0aa.jpg)

**Comment by DatJetto** [comment]
http://es.wowhead.com/spell=36805 Esa spell debería hacer 18-22k de daño de fuego ( Reducido por Resistencia a Elemento Fuego )

**Comment by efectokoleos** [comment]
ya esta arreglado el daño
