### ISSUE TITLE
[Logro] El Explorador

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#679]
No se puede obtener este logro ni titulo ya que aún existe el error de que Horado Rajacieno no se deja "descubrir", con mi pj principal he hecho todo lo posible, pero sigo sin poder tener este titulo/logro por el mencionado punto, ya tengo descubierto todo desde 4.0.6.

Para ser mas claros, dejo desde la parte "inicial del logro":

http://es.wowhead.com/achievement=4996 (principal y que habilitad el logro final(explorador) )-> http://es.wowhead.com/achievement=43 -> http://es.wowhead.com/achievement=46/explorador-del-mundo

PD: habia puesto un ticket hace un par de dias pero un MJ me dijo que no me lo podia completar, que lo dejara aqui en BT.

**Comment by searum** [comment]
fix
