### ISSUE TITLE
Rama bestia , talento( Tigre y quimera )

### ISSUE THREAD

**Issue by patriccio** [RoDNet/Bugtracker-Infinium-4.3.4#680]
hola a los gm , queria reportar que este talento http://es.wowhead.com/spell=118675 no funciona , no reduce el tiempo de disuacion y de separacion cuando a uno lo atacan.

**Comment by DatJetto** [comment]
Yo creo que si reduce, lo testearé @_@

**Comment by Mhryel** [comment]
Este talento si funciona.
