### ISSUE TITLE
NPCs faltantes en Infralar

### ISSUE THREAD

**Issue by mccelobb** [RoDNet/Bugtracker-Infinium-4.3.4#684]
Cuando entras a infralar no hay casi ningun npc y no puedes levear. Lo mismo pasa en Vashj'ir que solo hay quests (suficientes como para pasar del 81 al 82) en las profundidades abisales

**Comment by mccelobb** [comment]
Porfavor solucionen rapido que me he atascado

**Comment by lamaza** [comment]
Este reporte amigo, lo siento pero no sirve de nada. Debes hacer asi:

1 reporte por cada NPC / Quest faltante-bug.

No vayas a hacer 1 Issue con 2, 5 o 20 npcs de infralar, sino 1 issue x NPC. Lo mismo para las quest o cualquier bug.

**Comment by redneo** [comment]
si sigues la cadena de misiones si que salen los npcs.
