### ISSUE TITLE
Dk problema:faltan runas

### ISSUE THREAD

**Issue by D3VIL238** [RoDNet/Bugtracker-Infinium-4.3.4#688]
Con el dk, concretamente el de sangre,hay un problema muy importante ,aunque tengo todas las runas recargadas no me deja utilizar ninguna habilidad de ninguna rama porque pone faltan runas,pasa casi siempre y cuando pasa ocurre en todos los combates,no se puede jugar ya que solo puedes utilizar los ataques automaticos

**Comment by F4NT4SM4** [comment]
Poner imagen donde dices que no te deja usar ninguna habilidad.
he probado en mi dk y va perfect

**Comment by F4NT4SM4** [comment]
intenta hacerlo sin usar transfusion de sangre eso cambia una runa sangre a muerte y por un bug visual hace como si las demas se hubiesen restaurado pero es visual solamente siguen recargandose

**Comment by ghost** [comment]
A mi también me va bien con mi dk, lo que va mal son las runas de la muerte que no se generan.

**Comment by D3VIL238** [comment]
Pues pasa con el de sangre,porque ahora llevo profano y va perfecto
