### ISSUE TITLE
[Mazmorra] Caverna Santuario Serpiente

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#689]
El problema es con el ultimo boss Lady Vashj http://es.wowhead.com/npc=21212#comments todo anda bien hasta que tenemos que quitarle el inmune, matamos a los elementales corruptos que botan http://es.wowhead.com/item=31088#creates (Esos item son la llave) y cuando vamos a usarlos en los interruptores, no podemos hacerlo, no sale el engrane para interactuar con ellos (Interruptores) y no podemos quitarle el inmune a la princesa. =P

**Comment by efectokoleos** [comment]
cuando se caiga deberia estar arreglado
