### ISSUE TITLE
Talento [Tren de pensamiento] Sacerdote disciplina

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#69]
El talento Tren de pensamiento "Train of Thought" http://es.wowhead.com/spell=92297/tren-de-pensamiento (la descripción para el Pandaria y para el cata es la misma) no está funcionando.

-Tras utilizar punición http://es.wowhead.com/spell=585 el cd de penitencia  http://es.wowhead.com/spell=47540 no se reduce.

-Lo mismo sucede con sanación superior http://es.wowhead.com/spell=2060 al usarla no se reduce el cd de enfoque interno http://es.wowhead.com/spell=89485 

Además, enfoque interno (con el talento de "Fuerza del alma") debería otorgarnos esta habilidad también:
"Además, te vuelves inmune a los efectos de silencio, interrumpir y disipar durante 5 s."
Sin embargo solo lo hace durante 2seg

Gracias

**Comment by searum** [comment]
fix
