### ISSUE TITLE
Mision bug [Por los pelos]

### ISSUE THREAD

**Issue by OnestormGX** [RoDNet/Bugtracker-Infinium-4.3.4#690]
![wowscrnshot_072213_011552](https://f.cloud.github.com/assets/5060716/834659/2f2094a0-f2c7-11e2-9260-186bf6127876.jpg)
Mision bug: Por los pelos http://es.wowhead.com/quest=14154
La da: Lord darius crowley http://es.wowhead.com/npc=35077
La recoge: Lord darius crowley http://es.wowhead.com/npc=35077
Lado: Alianza
Localizazion: Gilneas http://es.wowhead.com/faction=1134
Problema: En teoria pone que tienes que aguantar 2 minutos a los huargens que te vienen, ni hay huargens ni te vienen y no pasa el tiempo

**Comment by searum** [comment]
fixeada temporalmente gracias por reportar
