### ISSUE TITLE
Mision Bug Liberar a la princesa

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#691]
Cuando vas a realizar esta mision e invocar a Myzrael http://es.wowhead.com/npc=2755#drops:mode=dignode-menci-n:50-16+1
Y usas el pergamino te dice que necesitas fragmentos de Myzrael 
Pero esa mision ya la he completado antes.
http://es.wowhead.com/object=138492

**Comment by redneo** [comment]
Arreglado
