### ISSUE TITLE
Mision bug Lanzador Personal Ultraseguro

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#692]
http://es.wowhead.com/quest=25839/el-lanzador-personal-ultraseguro
Empieza: Delber Giramanivela
Termina: Slamp Tiembladiente
Lado: Alianza
No se puede usar la maquina por lo cual no se puede completar la mision 
(Si la arreglan convendria revisar el paracaidas)

**Comment by redneo** [comment]
Arreglado... saldrá el paracaidas¿?¿?
