### ISSUE TITLE
Mision bug El servidor publico

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#694]
http://es.wowhead.com/quest=433
Lado: Alianza
Empieza: Senador Mehr Piedrasanta
Termina: Senador Mehr Piedrasanta
La runa de teletransporte no afecta a los mineros

Runa: http://es.wowhead.com/item=56222
Minero : http://es.wowhead.com/npc=41671

**Comment by redneo** [comment]
Arreglada, con sus textos en inglés y todo.
