### ISSUE TITLE
Mision Bug Asalto Nocturno

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#695]
http://es.wowhead.com/quest=25932/asalto-nocturno
Lado: Alianza
Empieza: Sargento Martílex
Termina: Sargento Martílex
Los trolls no aparecen para robar los carneros y atacar la granja
http://es.wowhead.com/npc=41544/asaltante-peloescarcha

**Comment by redneo** [comment]
Se puede arreglar, pero es largo de hacer. Por el momento lo dejo de lado, vale?

**Comment by ghost** [comment]
ok
