### ISSUE TITLE
Mision bug [Limpiar la colina de las brujas]

### ISSUE THREAD

**Issue by OnestormGX** [RoDNet/Bugtracker-Infinium-4.3.4#696]
Mision:http://es.wowhead.com/quest=11183/limpiar-la-colina-de-las-brujas
La da:http://es.wowhead.com/npc=23843
La completa:http://es.wowhead.com/npc=23843
Lado:Alianza/Horda
Zona:Marjal revolcafango, kalimdor
![image](https://f.cloud.github.com/assets/5060716/832500/213ce4c0-f25d-11e2-8bec-d876ddd9aa06.png)
![wowscrnshot_072213_012725](https://f.cloud.github.com/assets/5060716/832501/33982864-f25d-11e2-9afb-d493a26212f0.jpg)

**Comment by redneo** [comment]
Simpatico reporte.... pero te podias haber explicado con palabras..

Arreglado cuando caiga el server.
