### ISSUE TITLE
[Mazmorra] La cumbre del vórtice 2º parte

### ISSUE THREAD

**Issue by lllalvarolll** [RoDNet/Bugtracker-Infinium-4.3.4#697]
Al avanzar hacia el segundo boss nos encontramos con un draco poco común
![wowscrnshot_072213_010847](https://f.cloud.github.com/assets/3487127/832502/35565e1e-f25d-11e2-8381-8862e3b7d436.jpg)
No deberían ser todos tornados xD
![wowscrnshot_072213_010947](https://f.cloud.github.com/assets/3487127/832503/7cab0b2a-f25d-11e2-9c1c-7bb922f5242c.jpg)
Justo antes de llegar al segundo boss
![wowscrnshot_072213_011321](https://f.cloud.github.com/assets/3487127/832505/a31ce6f2-f25d-11e2-9d08-3e89dfcea7e4.jpg)
Después de llegar a las escaleras
![wowscrnshot_072213_011355](https://f.cloud.github.com/assets/3487127/832512/cd744c38-f25d-11e2-9aeb-63e0cd1b971f.jpg)

**Comment by ghost** [comment]
Agrego más cosas al reporte:
Como no lo ponen arriba, dejo una imagen con el combat log del daño que hacen los tornados, a parte los tornados te siguen... y no debería ser así, además deberían aparecer luego de atacar al boss y empezar a moverse en direccion semi-aleatoria pero sin seguirte.
![wowscrnshot_072113_201627](https://f.cloud.github.com/assets/4663665/832697/b4a4ab3e-f26d-11e2-9f01-23e9eb23ef8c.jpg)

El boss Altairus http://es.wowhead.com/npc=43873 hace un daño demasiado elevado, mataba de un golpe.
![wowscrnshot_072113_204556](https://f.cloud.github.com/assets/4663665/832683/701c9cca-f26c-11e2-8fd3-1668adef24b6.jpg)

Luego de atacar a Altairus, pone el siguiente debuff http://es.wowhead.com/spell=88286, el problema es que lo hace en toda la mazmorra, cuando solo debería de ser en el lugar donde esta el.
![wowscrnshot_072113_203045](https://f.cloud.github.com/assets/4663665/832685/d325b2ac-f26c-11e2-9ada-9ad46337e181.jpg)

También, el tornado para cruzar a la siguiente plataforma es invisible.
![wowscrnshot_072113_204059](https://f.cloud.github.com/assets/4663665/832684/c14a3c1a-f26c-11e2-9a62-195eeb0d07ac.jpg)

**Comment by searum** [comment]
Vale la mayoria son bugs tontos la verdad que se iran reparando con el tiempo, de momento no es una prioridad cambiar un modelid o un rango de un debuff, que un remolino este invisible tampoco afecta mucho la mecanica del juego porque aun asi no te caes al vacio... Bueno a lo que vamos, el unico bug que voy a mirar es el de los tornados de delante de altairus el resto ya se iran reparando porque no corren prisa.

**Comment by ghost** [comment]
¿Y el daño de alteirus? S: pega 150k de un golpe automatico.

**Comment by searum** [comment]
ya lo he tocado

**Comment by redneo** [comment]
El dragon ya le puse yo la display correcta. El tornado hacia la tercera plataforma a mi se me veía bien :S.

Faltaria de modificar los tornados que Searum se ha puesto con ello.

**Comment by efectokoleos** [comment]
cierro ya que esta fixed el boss y los tornados
