### ISSUE TITLE
Mision bug [Prueba de traición]

### ISSUE THREAD

**Issue by OnestormGX** [RoDNet/Bugtracker-Infinium-4.3.4#699]
Mision: http://es.wowhead.com/quest=27240
La da: ( http://es.wowhead.com/npc=4968 )
La coge: [ http://es.wowhead.com/npc=29611 ]
Localizazion:(isla de Theramore,marjal revolcafango,kalimdor)[Ventormenta]
Bug: Dice la mision que te teleporta a ventormenta, O vas a pata o te quedas sin hacer la mision.
![wowscrnshot_072213_142157](https://f.cloud.github.com/assets/5060716/834742/5eb8cbe0-f2c9-11e2-8785-413a3f5431b6.jpg)

Por un estupido error no lo puse en Misiones perdon

**Comment by searum** [comment]
fix
