### ISSUE TITLE
Bug de Nombre de Hermandad en personajes

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#7]
Bueno, lo que pasa es que a los nombres no les aparece la hermandad en la que estan

![wowscrnshot_070313_175112](https://f.cloud.github.com/assets/4895839/746650/48c0567c-e433-11e2-8a34-80c21b34f3eb.jpg)

Como pueden ver ni a Zara ni a mi (somos de la misma hermandad) nos aparece la hermandad a la que pertenecemos.
Gracias por su atencion

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/107
Hola queria comentar que el error que se comenta en el issue 107, referido con el error de hermandad que sale a cada rato, el fallo es que cuando se despoja oro sale el error.
Este error salta por la mejora de guild del oro para la hermandad, en los beneficios de hermandad.
Un saludo.

**Comment by Dekadencee** [comment]
Fixed
