### ISSUE TITLE
Mision bug [Desprestigiando a los desertores]

### ISSUE THREAD

**Issue by OnestormGX** [RoDNet/Bugtracker-Infinium-4.3.4#700]
Mision: http://es.wowhead.com/quest=27212
La da: http://es.wowhead.com/npc=23566
La recoge: http://es.wowhead.com/npc=23566
Localizacion: Isla de theramore,marjal reolcafango,kalimdor
Bug:Me siento mas repudiado que un testigo de jehova y un mosso d'esquadra juntos, nadie me quiere coger los panfletos :( [le doy y no pasa nada]
![wowscrnshot_072213_142952](https://f.cloud.github.com/assets/5060716/834776/83053d70-f2ca-11e2-85a5-ddf7db8738f4.jpg)

Por un estupido error no lo puse en Misiones perdon

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/553
Ya reportado seguimos desde el anterior.
