### ISSUE TITLE
[Logro/Instance] Leeeroy Jenkins

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#701]
Para completar el logro de Leeeroy (http://es.wowhead.com/achievement=2188), tienes que ir hasta la sala de El Grajero y si pasas por encima de los huevos te salen las crias de los dragones.

Puedes llegar a la sala perfectamente, va todo bien. Lo que no va es que si pisas los huevos, no aparecen los dragones (http://es.wowhead.com/npc=10161) para el logro.

**Comment by searum** [comment]
fix
