### ISSUE TITLE
[Mazmorra] El bastión Violeta

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#703]
El bastión violeta consiste en que van saliendo portales con mobs y tienes qe ir matandolos.
El problema se encuentra es qe a veces se abre un portal y no ves a los mobs solo les ves sus espadas y no les puedes atacar y ellos si pueden atacar al escudo, con lo cual pierdes, porque te dejan al escudo a 0 sin que puedas hacer nada y tampoco puedes avanzar porque hasta qe no los matas no se abre el siguiente portal.
![wowscrnshot_072213_164004](https://f.cloud.github.com/assets/3757460/835506/1dc5179c-f2dd-11e2-9cfd-a3e1295b8545.jpg)

**Comment by redneo** [comment]
fixed!
