### ISSUE TITLE
Arqueologia (posiblemente) Bug 

### ISSUE THREAD

**Issue by mccelobb** [RoDNet/Bugtracker-Infinium-4.3.4#704]
Solo aparecen fragmentos Vrykul b
![wowscrnshot_072213_115004](https://f.cloud.github.com/assets/3194580/835605/0ac48e3c-f2df-11e2-9967-51e6417c2fc1.jpg)

**Comment by mccelobb** [comment]
Tambien he sacado fragmentos Vrykul en Tierras Altas de Arathi y Las Estepas Ardientes

**Comment by veyertrox** [comment]
al parecer, en todas los lugares de arqueología (Reinos del este y Kalimdor) siempre te saldrá fragmentos de arqueología Vrykul, pero no solo en esos lugares, sino que también en terrallende. Y para terminar, los fragmentos Vrykul desaparecen muy rápido, por lo que hay que seleccionarlos rápido,  pero a pesar de eso, no da Vrykul http://es.wowhead.com/currency=399 (Fragmento de arqueología vrykul) ni nada parecido

**Comment by Dekadencee** [comment]
Creo que está fixeado, tras el reinicio del reino necesito confirmación, aprovecho para pedirle disculpas a @Lvmb ya que por lo visto estaba equivocada :S

**Comment by Velcositro** [comment]
Ya lo comprobé Deka, ahora si funciona como debe, gracias.

**Comment by mccelobb** [comment]
Confirmo que esta bien. Ya estoy haciendo el baston (http://es.wowhead.com/item=64489/baston-de-senor-feudal-hechicero-thaurissan) jeje Gracias por solucionarlo
