### ISSUE TITLE
[ Hunter > Trampeo ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#707]
El problema para describirlo simplemente es:
- 1. Área de trampeo; Las trampas del cazador poseen un RADIO de 2 metros, no estoy demasiado seguro de que se cumpla, si se pudiera revisar genial. Es decir, hay un DIÁMETRO de 4 metros alrededor de la trampa en la cual una presa puede quedarse atrapada, el problema es que parece ser menor, de manera que aunque el objetivo esté cerca la trampa no se activa.

---
- 2. Las trampas cuando las ponemos en el suelo duran 1 min, eso parece estar bien, el problema siguiente es que cuando ponemos Trampa de hielo por ejemplo en el suelo, esta debe permanecer 1 minuto, pero si a continuación añadimos Trampa Explosiva ( por poner otro ejemplo ) la primera se elimina no debiendo ser así.

En Resumen; No puedes poner más de 1 Trampa a la vez, cuando deberías poder tener 3 trampas en el suelo a la vez ( Una de cada Tipo )

Esto sucede tanto usando la trampa normal como usando el Lanzador de trampas, y las posibles combinaciones entre TODAS las trampas.

---

http://es.wowhead.com/spell=1499 Trampa congelante.
http://es.wowhead.com/spell=34600 Trampa con culebras.
http://es.wowhead.com/spell=13809 Trampa de hielo.
http://es.wowhead.com/spell=13813 Trampa explosiva.
http://es.wowhead.com/spell=13795 Trampa de inmolación.

---

http://es.wowhead.com/spell=77769 Lanzador de Trampas.

http://es.wowhead.com/spell=82945 Trampa de inmolación ( Trap Launcher )
http://es.wowhead.com/spell=82939Trampa Explosiva ( Trap Launcher )
http://es.wowhead.com/spell=82948 Trampa con culebras ( Trap Launcher )
http://es.wowhead.com/spell=60192 Trampa congelante ( Trap Launcher )
http://es.wowhead.com/spell=82941 Trampa de hielo ( Trap Launcher )

---

He intentado ser lo más preciso con la descripción del problema, ante cualquier duda preguntad.

**Comment by Jhovanni** [comment]
Está la referencia a este reporte, pues en la referencia del reporte 2200 se habla del radio de las trampas, en este reporte DatJetto habla de la posibilidad de colocar 3 trampas a la vez (una por escuela) como debería ser.
