### ISSUE TITLE
[Sacerdote] Poder de las sombras

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#708]
La primera parte del talento funciona bien.
La segunda parte del talento, dice que aumenta el daño critico de los hechizos de las sombras en un 100%, significa que si un hechizo de las sombras, hace un daño critico de 1000 daño, teniendo el talento debería de hacer 2000 de daño, esto no esta sucediendo.

Actualemente, según las pruebas que he hecho, el daño aumenta 54% aproximadamente, no 100%

http://www.wowwiki.com/Shadow_Power
Id según wowwiki spell=87327

Si con eso basta para que lo arreglen, ya pueden dejar de leer aquí xd, si no, voy por la demostración.

Para la prueba, tire hechizos de las sombras estando en las especializaciones Sagrado y Sombras sin ponerme talentos ni glifos que alteren el daño de esos hechizos.

En la izquierda, esta la tabla con los daños criticos estando en Sombras, a la derecha esta la tabla con daños criticos estando en Sagrado.
![tabla dps](https://f.cloud.github.com/assets/4663665/836079/b488ba66-f2e8-11e2-8a18-e1e0924feb7f.jpg)

Como se ve, estando en Sombras, hago más daño, pero no un 100% más, sino un 54% más aproximadamente, esto se ve claramente en las últimas imagenes, con el hechizo Plabra de las Sombras: Dolor, porque el rango del daño que hace entre el min y el max no varía.

**Comment by redneo** [comment]
Puede ser que suba el daño basico un 100% sin contar lo que te de por spell power... es una suposicion.

**Comment by ghost** [comment]
Daño básico sería... sin tener equipo puesto no?, para hacer los calculos.

Edit: suponiendo que el daño base sea sin equipo alguno (además de no tener buff ni nada que me aumente el daño con hechizos, solo mi pj en pelotas), lo he probado:
En sagrado critico palabra de las sombras dolor 339 de daño
En sombras critico palabra de las sombras dolor 516 de daño.

Sigue sin ser 100% más de daño, sigue siendo un daño aproixmado de 54% más.

**Comment by DatJetto** [comment]
El daño básico sería que si la spell es por ejemplo 800 + ( 0.6 \* SP ) de 800 pasa a 1600.
Yo personalmente no recomiendo testear sin equipo, por que los valores se achican mucho y de manera que si un spell pega desnudo 970-990 y debe pegar 990-1000 cuando estés equipado pegará 4-5k debiendo pegar 8-9k

El problema no creo que venga de eso, sino del multiplicador de crítico, muchos hechizos tienen un multiplicador de 150% ( Los que tienen esta cifra son todas las sanaciones y generalmente la mayoría de los hechizos en tiempo DoT ) Las spells normales tienen 200% como multiplicador de crítico, es decir (generalmente) las de daño directo.

**Comment by paellaencol** [comment]
Jetto, desde la 4.3 las sanaciones criticas tienen un valor del 200%, y ya no del 150% como anteriormente.

**Comment by searum** [comment]
esto va
