### ISSUE TITLE
Misión --> (Zul'Drak) La venganza del rey de la tormenta

### ISSUE THREAD

**Issue by harrypaqueton** [RoDNet/Bugtracker-Infinium-4.3.4#709]
http://es.wowhead.com/quest=12919/la-venganza-del-rey-de-la-tormenta
debes montarte en el gigante y usarlo como montura para destruirlo todo y no te deja montar
![wowscrnshot_072213_184109](https://f.cloud.github.com/assets/4949764/836324/d750d4d4-f2ed-11e2-8b95-0a4815d430b4.jpg)

**Comment by Kiritoo** [comment]
Fix, falta aplicar.
