### ISSUE TITLE
Paladín BUGS

### ISSUE THREAD

**Issue by xefirot** [RoDNet/Bugtracker-Infinium-4.3.4#71]
Rama Sagrado

Talento - Protector del inocente, al sanar a un objetivo distinto a ti te sanas 3404p.

http://i39.tinypic.com/2ljq1ww.jpg Screen de la descripción

http://i41.tinypic.com/2j1v1ie.jpg sanación real 2800p. Además de que sigue curando aunque te sanes a ti mismo, que no debería.

Talento - Sentencias iluminadas, al lanzar la sentencia te sana al instante 4143p.

http://i44.tinypic.com/317cs2u.jpg Screen de la descripción

http://i40.tinypic.com/2vmcwva.jpg sanación real 2600, los 800 puntos se debe al sello.

Skill - Señal de luz, no cura al objetivo de señal de luz con ninguna sanación. Pero si otorga las cargas de poder sagrado al curarlo con el choque o la luz divina.

http://i43.tinypic.com/2gy1v9y.jpg
http://i42.tinypic.com/2emmxc4.jpg
http://i44.tinypic.com/rsslmf.jpg

Skill - Luz del alba, sana lo mismo con una carga que con tres, y no las consume todas. Debería sanar 1494p y sana sobre 600p.

http://i43.tinypic.com/eziqg9.jpg
http://i39.tinypic.com/2yott7b.jpg
http://i44.tinypic.com/69j1wk.jpg
http://i44.tinypic.com/iwtez6.jpg

**Comment by crowel** [comment]
Estaria bien poner enlaces a wowhead.
*Protector del inocente: http://es.wowhead.com/spell=94289
*Sentencias iluminadas: http://old.wowhead.com/spell=53556
*Señal de la Luz: http://es.wowhead.com/spell=53563
*Luz del alba: http://es.wowhead.com/spell=85222

**Comment by xefirot** [comment]
Lo de que ponga nivel 90 no te llama la atencion???...wowhead va a la par que mist of pandarian respecto a las skills de clases...asi que no pongas mas enlaces de wowhead respecto a skills de clases...

**Comment by crowel** [comment]
mmm

Probaste a mirar debajo del nivel 90 que tienes una barra para poder elejir el nivel?.
Otra cosa te fijaste el enlace de sentencias que es el unico que varia que esta en old.wowhead..
Dejalo es igual, denada por el aporte..

**Comment by xefirot** [comment]
Pero si he puesto screens de las descripciones igualmente...

**Comment by crowel** [comment]
spell=94289
spell=53556
spell=85222
En la descripción de tus fotos no salen los ids! es lo que intente explicar

**Comment by xefirot** [comment]
Aquí va otro.

http://i44.tinypic.com/2jccv2s.jpg
http://i42.tinypic.com/zje2dy.jpg

Aún sin tener aprendido el glifo de gran palabra (palabra de gloria sana un 50% de inicio y otro 50% durante 6s) este efecto se aplica automáticamente. Pero sana un 100% (a mi parecer) y hace tres ticks de poca sanación, no se corresponde para nada con el glifo.

http://i42.tinypic.com/2lthxxu.jpg
http://i43.tinypic.com/39ll.jpg
http://i44.tinypic.com/295cysk.jpg

Aqui se ve más claro

**Comment by crowel** [comment]
Poderio y Reyes los puede poner un mismo paladín sin que desaparezca el anterior.
*Bendición de poderío: http://es.wowhead.com/spell=19740
*Bendición de reyes: http://es.wowhead.com/spell=20217
![wowscrnshot_070413_161728](https://f.cloud.github.com/assets/3537253/750244/e0ee8c64-e4c1-11e2-9093-d6a11354803c.jpg)
Como se puede apreciar puse yo ambas bendiciones sin desaparecerme el anterior.
Un saludo.

**Comment by crowel** [comment]
Guardián de los antiguos reyes - http://es.wowhead.com/spell=86669
Esta habilidad esta mal cuando curas a alguien el guardian deberia sanar a esa misma persona y a los demás la misma sanación que la cura realizada por el paladín.
El problema lo descubri con un sacerdote que teniamos en la banda que su Abrazo vampirico estaba curando a la banda y el guardian copiando las curas suyas.
Esto no puede ser asi solo debe curar curas del paladín.
![wowscrnshot_070413_162657](https://f.cloud.github.com/assets/3537253/750320/3712f1dc-e4c4-11e2-880f-a543620b18bc.jpg)

Un saludo.

**Comment by sherik12** [comment]
-  Proposito divino: una vez se activa deberia hacer que el siguiente veredicto templario fuera gratis y con el poder de tres cargas de poder sagrado. Hasta ahi funciona correctamente. Pero una vez que se activa se puede utilizar veredicto hasta que termina el buf, duracion del buf:7segundos. http://old.wowhead.com/spell=86172#see-also-ability 
  
  Escudo sacro: Salta de vez en cuando, es decir salta cuando se le da la gana y no bajo las condiciones que deberia saltar, que es cada 60s siempre y cuando la vida este por debajo del 30%.
  
  Santidad de batalla: No funciona.
  
  Cruzada: Al igual que escudo acro salta cada vez que se le da la gana, es decir cuando matas a un objetivo que te aporta experiencia u honor salta y luego matas otro y no salta.
  
  Colera vengativa: Aveces activa martillo de colera y a veces no.
  
  Maestria: sin aprender y sin poder aprenderla.

**Comment by xefirot** [comment]
Talento - Torre de Radiancia, otorga al una carga de poder sagrado extra al usarlo directamente en tu objetivo de señal de luz con tus sanaciones de choque sagrado y luz divina. Choque sagrado pasaría a otorgar 2 cargas y luz divina 1 carga. Pero si el propio paladín tiene puesta la señal de luz otorgan 3 y 2 cargas respectivamente, no importa si son directas o no (siendo el objetivo distinto del propio paladín).

http://i40.tinypic.com/xpq1jk.jpg
http://i41.tinypic.com/aw239c.jpg

Además hace que radiancia tambien otorgue 1 carga de poder sagrado siempre, pero cuando el paladín tiene puesta la señal de luz otorga 3 cargas. Independientemente de cual sea el objetivo

http://i41.tinypic.com/2gt2fko.jpg

Tambien podeis observar que radiancia cura de inicio el doble de lo que debería.

**Comment by paellaencol** [comment]
Hablando de Radiancia Sagrada  http://es.wowhead.com/spell=82327/radiancia-sagrada

¿Es posible pensar que esta cantidad de más que está curando radiancia sagrada, sea para compensar la sanación periódica posterior que no está realizando? Por ejemplo con el talento Floración de los druidas resto se optó por este camino, eliminar la sanación periódica y meterla como directa.

**Comment by paellaencol** [comment]
Añado otro problema con los paladines: Especialización en placas http://es.wowhead.com/spell=86525/especializacion-en-placas

No está otorgando este beneficio extra del 5% en función de la rama de talentos que escojamos.

**Comment by paellaencol** [comment]
Skill - Luz del alba http://es.wowhead.com/spell=85222/luz-del-alba

Anteriormente habían dicho que está curando solo 600, cuando debería llegar a curar más si tenemos más de una carga. El reporte que han hecho es cierto, pero con un pero:
Actualmente si lanzamos luz del alba con 3 cargas nos sanará a nosotros con valor de 3 cargas, y al resto con valor de 1 carga. Aquí está el problema, la sanación sobre nosotros funciona, pero no sobre el resto (ya que la sanación ignora el número de cargas que tengamos).

De todas maneras, la sanación que está haciendo por tener 3 cargas (sobre nosotros mismos solo) son 2700, cuando debería hacer 5600 (con mi equipo) y sin procesos.

En resumen:

Luz del alba: Con 3 cargas solo cura con valor de 3 cargas a nosotros mismos, y sana la mitad de lo que debería. Con 3 cargas, solo sana con valor a 1 carga al resto de pjs, y es una cura ínfima en torno al 10% de lo que debería sanar.

**Comment by xefirot** [comment]
Una cosa, según parece esa skill en mop ya otorga un punto de poder sagrado mientras que aquí ese punto se otorga por talento. La sanación que marca tambien es ligeramente superior a la de la descripción que leo aquí. Si linkeais recalcar esa diferencia para no causar confusión.

**Comment by paellaencol** [comment]
Maestría en auras: http://www.wowpedia.org/Aura_Mastery 

En el 4.3 aparte de concedernos inmunidad a silencios durante 6segundos (desconozco si esto funciona), debería doblar el valor de cualquier aura activa sobre nuestro personaje durante 6seg.
Auras que está doblando y funcionan correctamente:
-Devoción
-Reprensión
-Concentración

Aura que no está doblando, y por tanto no funciona:
-Aura de resistencia (resistencias mágicas)

(este problema también sucedía idénticamente en el 4,0,6)

**Comment by xefirot** [comment]
Aqui os dejo un video puesto que no se exactamente como describir lo que sucede. Parece ser que cuando esta en uso la señal de luz se puede spamear luz del alba.

http://www.youtube.com/watch?v=v-DmmE9XyyM&feature=youtu.be

Además según el registro otorga 1 carga de poder sagrado cuando no debería, parece ser que la causa es el talento de torre de radancia. Y podeis ver también como el choque da las 3 cargas en vez de las 2 correspondientes.

**Comment by efectokoleos** [comment]
estoy en ello en un rato os comento

**Comment by paellaencol** [comment]
Maestria paladin sagrado: Sanación Iluminada

(no puedo enlazarlo desde otro idioma que no sea el inglés)

http://www.wowwiki.com/Mastery:_Illuminated_Healing

Actualmente esta funcionando más o menos tal y como lo hacia en el 4.0.6. Sin embargo desde la 4.2 esta maestria ha sufrido algunos cambios: el miniescudo que genera una sanación ahora no elimina el miniescudo de una sanación anterior, sino que se acumulan y refresca el tiempo de duración. Sin embargo esta acumulación del valor del escudo de maestria, nunca podrá exceder de 1/3 de la salud del paladin.

 Cataclysm-Logo-Small Patch 4.3.0 (29-Nov-2011): Illuminated Healing (mastery) now also applies to Holy Radiance. 
Cataclysm-Logo-Small Patch 4.2.0 (28-Jun-2011): Illuminated Healing (Mastery) has been adjusted slightly so that if a paladin refreshes an existing copy of his or her own Illuminated Healing on a target, the new absorption amount will be added into the old absorption amount and the duration will be reset. The total absorption created can never exceed 1/3 of the casting paladin's health. 
Cataclysm-Logo-Small Patch 4.1.0 (26-Apr-2011): Illuminated Healing shield duration is now 15 seconds, up from 8 seconds. In addition, Illuminated Healing has been increased to provide 1.5% effect per mastery, up from 1.25%. 

---

De estos 3 cambios que ha sufrido la maestria durante esta expansión, actualmente solo está funcionando la de la 4.1.0 y la 4.3.0. Por tanto falta por aplicar el cambio añadido en la  4.2.0

**Comment by paellaencol** [comment]
Con la última caída del servidor la Bendición de poderio http://old.wowhead.com/spell=19740 (la descripción no coincide exactamente con el enlace), ya funciona correctamente.

Sin embargo el talento "Gloria eterna" http://old.wowhead.com/spell=87164 se ha estropeado y ha dejado de funcionar

**Comment by lamaza** [comment]
Lo del paladín reprensión, dejarlo en este tema https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/104

**Comment by Moyax** [comment]
Bueno añadire aqui lo que acabo de darme cuenta con el pala.. #237 . Tiene que ver con el Martillo de colera y el supuesto 30% de daño menos que tiene... Martillo de colera solo pega lo que dice la descripcion cuando me activo Inquisicion... La habilidad que nos aumenta el daño sagrado 30%

**Comment by ghost** [comment]
Si pueden poner cada bug en un reporte a parte, así como esta los devs no lo miraran.
