### ISSUE TITLE
[Mazmorra] Matanza de Stratholme

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#710]
Cuando entras en la ciudad, Arthas se queda quieto y no te deja continuar. Justo en este punto.
![wowscrnshot_072213_203735](https://f.cloud.github.com/assets/3757460/837052/adbeb9f4-f2fe-11e2-96fc-9269c775ed0a.jpg)

**Comment by efectokoleos** [comment]
la instance estaba hecha una pena, ya se puede hacer entera, menos el boss opcional (creo xd)

**Comment by Wiinter** [comment]
Vale ahora El arthas del principio para iniciar el evento del puente de Stratholme tampoco va

**Comment by efectokoleos** [comment]
haz la quest de las cajas y te funcionará correctamnte

**Comment by Velcositro** [comment]
@efectokoleos ¿será que se puede arreglar la aparición y funcionamiento del boss opcional?(aunque veo que no estás seguro de si funciona o no), me interesa por la montura. Por cierto, bonito Avatar.

**Comment by Wiinter** [comment]
Repetiré la quest de las cajas y hablaré con Cromi a ver, sino te puedo enviar un ticket via ingame?

**Comment by Wiinter** [comment]
No salen las primeras 10 oleadas de mobs del principio :S

**Comment by efectokoleos** [comment]
![wowscrnshot_072513_152257](https://f.cloud.github.com/assets/1615636/855728/00ef0eea-f52e-11e2-85a9-4485ed65aab9.jpg)

esos 2 mobs corresponden a la primera oleada, y no son oleadas si no que el pregonero (el cual me he dado cuenta de que le falta el texto) te dice el lugar donde sale cada oleada y tienes que ir alli a matarlos

![wowscrnshot_072513_152339](https://f.cloud.github.com/assets/1615636/855729/06c86dd4-f52e-11e2-9d3c-651aa12f64b9.jpg)

y aqui la segunda oleada

**Comment by Wiinter** [comment]
Yo he llegado a la 3. A partir de ahi no hay mas

**Comment by efectokoleos** [comment]
están todas las oleadas, añadidos los textos del pregonero para saber donde sale cada oleada

**Comment by Wiinter** [comment]
En las oleadas 3 y 4 faltaban unos npcs qe se ve qe estaban invisibles y despues en cada oleada despues del tercer boss salia un zombi qe si le atacabas te ponía evadir.

**Comment by redneo** [comment]
ya se tendrian que ver las arañas... el zombie, me puedes decir id?

**Comment by Wiinter** [comment]
Zombie resucitado http://es.wowhead.com/npc=27737
