### ISSUE TITLE
Mision bug (Tierras de la Peste del Oeste) ¡Una emboscada!

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#711]
![wowscrnshot_072213_210610](https://f.cloud.github.com/assets/5048096/837234/4bbac8ca-f302-11e2-8eb3-e270fbc29392.jpg)
http://es.wowhead.com/quest=27171/una-emboscada
Lado: Alianza
Empieza: Cajón de armas roto
Termina: Comandante Ashlam Puñovalor
Los no muertos objetivos no llegan a aparecer por lo que no se pueden conseguir corazas ni espadas

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
