### ISSUE TITLE
Npc DOBLE

### ISSUE THREAD

**Issue by Shadowye** [RoDNet/Bugtracker-Infinium-4.3.4#714]
En la posada de Villa Oscura (Bosque del Ocaso) en la cocina hay un chef que otorga misiones.La cosa es que dicho npc esta doblado por lo que da doble misión y doble experiencia.Porfavor arréglenlo.Saludos y Gracias
![wowscrnshot_072313_001849](https://f.cloud.github.com/assets/5068190/838347/bf1065b8-f31c-11e2-8f6e-59285beba575.jpg)
ID del npc: http://es.wowhead.com/npc=272

**Comment by crowel** [comment]
Reporte repetido https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/539.
Continuamos del anterior.
Un saludo.
