### ISSUE TITLE
Misión (Montañas Crestagrana) "John J. Keeshan" BUG

### ISSUE THREAD

**Issue by Shadowye** [RoDNet/Bugtracker-Infinium-4.3.4#715]
En Villa del Lago (Montañas Crestagrana) En el "Ayuntamiento" Hay un npc llamado Coronel Troteman que otorga una misión llamada "John J. Keeshan".La cosa es que hay que entregársela a un npc que NO esta.Por lo que no se puede seguir la cadena de misiones.Saludos y Gracias!!!
![wowscrnshot_072213_233027](https://f.cloud.github.com/assets/5068190/838090/2a3f8500-f316-11e2-8f6c-1c7ccec99fe8.jpg)

**Comment by lamaza** [comment]
Tienes que poner una imagen del lugar correcto para ubicar al npc de entrega + su nombre y su id.
Bug: John j. keeshan no existe.

Te colaboro con las ids =)

Mision: http://es.wowhead.com/quest=26567
C. Troteman: http://es.wowhead.com/npc=43221
Quien la recibe: http://es.wowhead.com/npc=43184

**Comment by redneo** [comment]
dejo esta abierta para que me expliqueis como va...

en una fase se tiene que ver a todo el club de la lucha, a partir de que mision se tiene que ver????

**Comment by Kiritoo** [comment]
Fix
