### ISSUE TITLE
Mision (Cuenca de Sholazar) "¿Ya has vuelto?" Bug

### ISSUE THREAD

**Issue by Felarof23** [RoDNet/Bugtracker-Infinium-4.3.4#717]
En la Quest <a href "http://es.wowhead.com/quest=12574">"¿Ya has vuelto?"</a> el NPC <a href="http://es.wowhead.com/npc=28114/clamaneblina-soo-papo"> Clamaniebla Soo-papo</a> no se encuentra en su sitio para terminar esta misión.

![nosoopapo](https://f.cloud.github.com/assets/5028343/838502/bd24920c-f320-11e2-94ff-5c56604f1f11.png)

**Comment by crowel** [comment]
Acabo de comprobarlo y el npc está justo donde debe estar.
![wowscrnshot_080213_160732](https://f.cloud.github.com/assets/3537253/901348/f1cbc200-fb7c-11e2-9c11-d65165a9073a.jpg)

Cierro Issue, saludos.

**Comment by Felarof23** [comment]
Hola @crowel sigue sin aparecerme el NPC y no puedo entregar la quest aún :(, será cosa de mi cliente?
Saludos!

**Comment by crowel** [comment]
Reabro para que revisen la phase del npc, ya los gms lo cerraran/solucionaran.
Un saludo.

**Comment by Kiritoo** [comment]
Fix falta aplicarlo.
