### ISSUE TITLE
devolver en septuplo

### ISSUE THREAD

**Issue by harrypaqueton** [RoDNet/Bugtracker-Infinium-4.3.4#719]
pues eso en teoria debes soltarle un hechizo para devolverle el daño pero no funciona y de cada golpe te quita 6k de daño
http://es.wowhead.com/quest=12611/devolver-en-septuplo
![wowscrnshot_072313_014555](https://f.cloud.github.com/assets/4949764/838792/53d8e8b2-f329-11e2-8be6-c2eb1c606d11.jpg)

**Comment by Kiritoo** [comment]
Fix
