### ISSUE TITLE
[Guild] Bug Rango

### ISSUE THREAD

**Issue by shials** [RoDNet/Bugtracker-Infinium-4.3.4#72]
En mi hermandad soy centurión , que es el 2º rango más alto trasn el de Guild Master , pues bien.. no debería dejarme subir a nadie a Centurión ya que estaba puesto en la 406 que solo el guild master pudiera ascender a ese rango a la gente , aquí la prueba.
![wowscrnshot_070413_123806](https://f.cloud.github.com/assets/4938203/748850/4343f268-e496-11e2-9921-ff26e71f9ac9.jpg)

**Comment by ghost** [comment]
Esto ya está arreglado.
