### ISSUE TITLE
Nos han robado!!!!... Elevador de Gnomeregan no esta....

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.3.4#720]
![wowscrnshot_072213_173535](https://f.cloud.github.com/assets/2059256/839009/105cb556-f332-11e2-9f4f-d7e6fe444d9c.jpg)
![wowscrnshot_072213_173557](https://f.cloud.github.com/assets/2059256/839042/59c6a7be-f333-11e2-8335-c188e44e910d.jpg)
![wowscrnshot_072213_174718](https://f.cloud.github.com/assets/2059256/839016/a0cdf9d8-f332-11e2-8ace-7b6626a4a2d6.jpg)
![wowscrnshot_072213_174548](https://f.cloud.github.com/assets/2059256/839023/f1630ea6-f332-11e2-9a81-9973585a6710.jpg)

**RESUMEN**
La Horda llego a Gnomeregan,,, y los feos goblins nos han robado el elevador...

> - de pilon ,,,, les agrego xD como es que un picaro comienza con TELA en lugar de CUERO??? hihihi

**Comment by searum** [comment]
Pues yo estoy ingame en el server y si me sale
