### ISSUE TITLE
NO HAY MISIONES EN LA RAZA HAUREN

### ISSUE THREAD

**Issue by excalimure** [RoDNet/Bugtracker-Infinium-4.3.4#721]
no hay misiones solo llega hasta la mision "el arsenal del rebelde" de ahi se acaban las misiones  y no se puede salir de ahi

**Comment by searum** [comment]
....

**Comment by lamaza** [comment]
Cuales seran los hauren XD

**Comment by crowel** [comment]
Es la descendencía de los tauren y los huarguen que crearon familia^^
