### ISSUE TITLE
Problema para comprar Armas y Reliquias de Conquista (Arenas)

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#722]
Al parecer no se pueden comprar ni las armas ni las reliquias de arenas (Puntos de Conquista). Ellas piden tener un total de 7800 puntos de conquista ganados. 

![wowscrnshot_072213_220140](https://f.cloud.github.com/assets/4944904/839318/df60d1d6-f33f-11e2-8351-dfc6c8caf477.jpg) 

Y ya algunos han obtenido o superado esa cantidad, pero estos objetos no se pueden comprar. Sigue diciendo que se necesita haber ganado 7800 puntos para poder comprarlas (lo dice en rojo). 

![wowscrnshot_072213_220205](https://f.cloud.github.com/assets/4944904/839320/f126ffc6-f33f-11e2-977a-f6a830b446b0.jpg)

 Si hay algun otro requerimiento (aparte de tener los puntos y la cantidad que dice "ganada") para poder comprar esos objetos... Por favor decidme no soy muy entendido en eso (trate de comprar la reliquia, pero al ver que no me dejaba compre otra cosa)

Este es la id del Npc (alianza) http://es.wowhead.com/npc=54661 

y esta la id de algunos de los objetos que vende (los mostrados en las imagenes). http://es.wowhead.com/item=70224 y http://es.wowhead.com/item=70408 

Tambien anexo la lista de las armas por si en algo ayuda, no se muy bien como es eso de fixear pero se que piden los ids de los objetos. Asi que para facilitar y ayudar en algo ahí esta solo de dar click y listo. http://es.wowhead.com/items=2?filter=na=implacable;minle=378;maxle=378;minrl=85;eb=1

**Comment by DatJetto** [comment]
Explico más o menos para el que no sepa nada de este tema:

En las temporadas 10 - 11 de Arenas, en el oficial se puso un ''límite'' nuevo, los cuales hacen que los usuarios NO puedan comprar directamente Armas por arena, es decir, empieza la nueva temporada ( con sus historias internas, las cuales nadie conoce ) se traspasan las monedas y se da apertura al nuevo set de arenas y bg, pero para comprar las armas y algunos objetos es necesario haber ganado o gastado X puntos de arena, ya que dichos objetos ( Armas básicamente ) son mejores que la media.

¿Qué pasa? que esto en un privado es muy dificil de hacer ( supongo, yo no se de cosas de esas ) y tampoco se ha dado paso a la temporada de arenas 10, aunque ya hay gente con set Implacable ( aprovechando un pvp muy desequilibrado ).

Posibles Soluciones;
1, la más obvia, cuando se de paso a la temporada de Arenas 10 introducir un contador que a partir de ese día, para cada pj, cuente cuantos puntos de arena ha conseguido y al llegar a X puntos, requeridos se desbloqueen las armas ( como los de los logros de X puntos de arenas o X puntos de justicia y valor etc.. )

2, Quitar el límite, no lo recomendaría, por que.. para algo está.

**Comment by Moyax** [comment]
mmm no estamos en la temporada 10 y entonces como compramos objetos que dicen T10, como es que empezamos nuevas arenas desde 0. Mmm y la gente que ya consiguió o gasto ese limite de puntos "lo que pedia" para poder acceder a ellos? Ya deberían poder comprarlas (armas y reliquias) entonces como se hace?

**Comment by lamaza** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/532

**Comment by searum** [comment]
fix
