### ISSUE TITLE
Error Quest "Luchando por Respirar" Wargen

### ISSUE THREAD

**Issue by khaojin** [RoDNet/Bugtracker-Infinium-4.3.4#723]
"No hay tiempo que perder. La mitad de veladores de la ciudad estaba en la zona que se ha venido abajo. Ve allí y salva a todos los que puedas.

Asegúrate de sacarlos del agua hasta la orilla. Yo me aseguraré de que reciban toda la ayuda que necesiten."

No se puede tener contacto con los Veladores quienes estar sumergidos. Espero solucion, ya esta quest atrasa.

**Comment by redneo** [comment]
ya se puede interactuar con ellos
