### ISSUE TITLE
Mision "Sanacion Relampago"

### ISSUE THREAD

**Issue by misteriosoccmc** [RoDNet/Bugtracker-Infinium-4.3.4#725]
Como se ve en la imagen el instructor da la mision, pero no permite aprender la spell dicha.
![wowscrnshot_072313_013059](https://f.cloud.github.com/assets/3792252/839984/ad0ea48e-f361-11e2-89aa-61d91fd5d7b2.jpg)

**Comment by crowel** [comment]
Fix, se debe esperar al reinicio o a que caiga.
Arregladas también su misión que no funcionaba correctamente y las misiones de las demás clases.
Cierro.
