### ISSUE TITLE
Talento Sacerdote disciplina [Tren de pensamiento]

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#726]
El talento tren de pensamiento http://www.wowhead.com/spell=92297/train-of-thought funciona ya casi correctamente del todo.

Después del último arreglo, se reparó la parte donde tras utilizar sanación superior http://es.wowhead.com/spell=2060/sanacion-superior se reducía 5segundos el cd de enfoque interno  es.wowhead.com/spell=89485/enfoque-interno

Sin embargo, falta por arreglar la parte de cuando se castea punición http://es.wowhead.com/spell=585/punicion reduce el cd de penitencia http://es.wowhead.com/spell=47540/penitencia en 0,5seg.

Gracias

**Comment by searum** [comment]
fix
