### ISSUE TITLE
Talento Sacerdote disciplina [Égida divina]

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#727]
Buenos días.

Después del último arreglo, el talento égida divina (47515) ha vuelto a funcionar. El problema ahora son dos aspectos:
1. Funciona demasiado, es decir, salta con cualquier cura. Cuando debería funcionar únicamente con sanaciones críticas, o con cualquier tipo de sanación (crítica o no) proveniente de Rezo de sanación (596). Del valor total de la sanación que haga saltar el proceso, un 30% de esa cantidad total será añadida como escudo en forma de Égida divina (47515).

2.Égida divina se apila. Esto está funcionando a medias (abajo lo explico):

tal como se puede observar en este vídeo (visualizad únicamente el segmento comprendido entre el 6:20 y el 6:50)

http://www.youtube.com/watch?v=523XMJwz6YM

Égida divina se apila. Esto está funcionando aquí también, pero el tope de la cantidad total que se apila está muy bajo (10695 de valor de escudo únicamente). Cuando debería estar este tope en torno a un 30% de la cantidad total de vida

Gracias.

**Comment by searum** [comment]
fix
