### ISSUE TITLE
Misión "El ermitaño" BUG

### ISSUE THREAD

**Issue by Shadowye** [RoDNet/Bugtracker-Infinium-4.3.4#729]
Se supone que cuando cojes la misión te mandan a hablar con "El morador de la torre" que es un npc pero cuando llegas no hay nadie.
![wowscrnshot_072313_132028](https://f.cloud.github.com/assets/5068190/841175/d0c721fc-f38a-11e2-9af9-f142ae14912b.jpg)
ID de la misión: http://es.wowhead.com/quest=26627
ID del npc: http://es.wowhead.com/npc=289

**Comment by redneo** [comment]
a mi si que me sale, vuelve a mirar, puede que no te hubiera cargado los datos a juzgar por el reloj de arriba.,
