### ISSUE TITLE
[ Quest > Guardianes de Hyjal: ¡Invasión a las tierras de fuego! ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#731]
http://es.wowhead.com/quest=29388 ( Horda )
http://es.wowhead.com/quest=29387 ( Alianza )

Falta el npc http://es.wowhead.com/npc=52669 Matogarra en su respectiva posición.

Esta cadena de quest es de LAS MÁS IMPORTANTES y daría una importancia bastante alta a arreglarlas, ya que son las predecesoras de poder entrar a Frente de magma y posteriormente Tierras de Fuego ( Raid )

Frente de magma LOGROS:  http://es.wowhead.com/search?q=frente+de+magma#achievements
Frente de magma ZONA:  http://es.wowhead.com/zone=5733

En esta zona no solo disponemos de quests diarias para poder coger equipo PvE épico de nivel 365, si no múltiples NPC ÉLITE RARE que Blizzard introdujo como reto de doma para los Cazadores.

Supongo que a esta zona, le hará falta bastante trabajo, primero, por que habrá que hacer una limpieza de NPC ( hay demasiados, según he visto en otros servidores ) , añadir NPC que no están y el fixeo de las quest diarias con sus fases y currency de marcas de árbol del mundo y los logros pertinentes.

Marca de Árbol del mundo: http://es.wowhead.com/currency=416

Alijo de Zen'Vorka ( podremos comprarlo cuando nos sobren marcas de árbol del mundo ) http://es.wowhead.com/item=71631 en el cual podemos ver la cantidad de objetos Verdes, Azules y Épicos que contiene.

**Comment by searum** [comment]
Por que van a ser importantes si todavia no tenemos en mente abrir esa raid? Yo creo que los que debemos considerar las cosas como importantes/no importantes somos nosotros... ^^

**Comment by lamaza** [comment]
Algo asi iba a decir yo: Men, para que la quest, si aún estan closed esas zonas de manera indefinida. Es mas, yo pensaba que staff habia inhabilitado la entrega de la misión.

**Comment by redneo** [comment]
Antes de poder hacer esas misiones se tienen que tener hechas unas cuantas (muchas) de la zona de Hyjal. Ahora mismo me encuentro con un pj limpio, revisando las misiones de Hyjal, si os interesa como voy... 59 de 115 y subiendo (para el logro)

**Comment by patriccio** [comment]
si llegaran a dar prioridad a esa zona nueva , que no es masmorra si no una zona de quest y venta de ekipos y recetas nuevas , seria genial , ya que para haber pasado de parche y estar haciendo pve en masmos que son de la 4.0.6 , como que no estretiene mucho y la idea es que llegue mas gente para darle vida al server.

**Comment by crowel** [comment]
Comentario del oficial. 
Por thehobbit (656 – 2·10) el 05/09/2011 (Parche 4.2.2)  Reportar  
Todos los vendedores:

Para poder empezar a desbloquear vendedores es necesario haber realizado las misiones de hyjal hasta El milagro de Aessina (86 misiones) ya que si no la quest Abrir la puerta no se puede entregar. Una vez entregada El milagro de Aessina se puede empezar la cadena Guardianes de Hyjal: La llamada de los Ancianos / Guardianes de Hyjal: La llamada de los Ancianos sin atascarse en Abrir la puerta .

**Comment by DatJetto** [comment]
Searum, la zona es previa a la raid, aunque no la valláis a abrir hasta dentro de un tiempo, es una zona como he dicho, de quest, de pillar equipo, y la cadena de quest es bastante larga, de manera que aumentaría considerablemente la oportunidad de leveo en Monte Hyjal, ya que puedes sacar mucha más experiencia.

Yo no quiero con esto meter prisa a nadie por supuesto, lo arreglaréis cuando queráis; solo he dado la información para que se tenga en cuenta la zona, ya que pocos servidores la tienen abiera y ninguno o casi ninguno la tiene blizzlike con todo, y es una zona bastante interesante.

**Comment by redneo** [comment]
Hasta esa mision YA se pueden hacer...

**Comment by Compresor** [comment]
Funciona
