### ISSUE TITLE
Nos han robado el elevador - Gnomeregan - II

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.3.4#733]
lol... cerraste el post sin confirmarlo **@Searum**.... 

![5345](https://f.cloud.github.com/assets/2059256/842089/915a39c2-f3a4-11e2-89d4-76946327c755.png)

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/720 <<< post relacionado..

---

**Una pregunta te has quitado el aura de GM...?????** (quiero decir si te desactivaste (OFF) los poderes de GM)

> lo digo por que aveces los GM ven cosas que los **jugadores con CUENTA NIVEL 0 no podemos ver**.

En el post anterior deje varias imagenes desde 2 puntos de vista....
- Desde un Gnomo que tiene el aura IRRADIADO.
- Y desde un HUMANO paladin nivel 85 sin aura ni buff, etc.

---

Ahora te dejo otras imagenes desde el punto de vista de un HUARGEN nivel 84 hunter.

> te juro que este no consume de esas cosas..... lol para ver visiones hiihihi

![wowscrnshot_072313_074203](https://f.cloud.github.com/assets/2059256/842231/9e5c159e-f3a6-11e2-893b-fc56c694eeee.jpg)
![wowscrnshot_072313_074301](https://f.cloud.github.com/assets/2059256/842232/a180d782-f3a6-11e2-8d66-452356f320e4.jpg)

---

Bueno ahi ta 3 PJs distintos, desde varios puntos de vista....
**No mas no me salgas que es mi cuenta la que esta bug lol .....**

OoOo!!! y si me dices que intente borrar la CACHE y WTF

Pues veamos que pasa...

![45246578](https://f.cloud.github.com/assets/2059256/842403/b265ffe8-f3a9-11e2-8fc4-90d6233cfa28.png)

![wowscrnshot_072313_075839](https://f.cloud.github.com/assets/2059256/842363/0f009d0e-f3a9-11e2-9ee7-2cb6f00047c3.jpg)

Y ahi te dejo una imagen desde 3 angulos diferentes; humano, huargen, gnomo....

> la Cache y WTF ya fueron borradas.. cuando se tomaron las imagenes.
- Repito, que el unico que tiene un aura puesta es el gnomo,,,, el aura se llama IRRADIADO. (que por cierto es nivel 3)

> Y es un gnomo picaro, que en lugar de CUERO comenzo con TELA hihih..... y el teletrasportador sigue sin funcionar ._. pero eso es otra larga... larga... historia xD.

**Comment by searum** [comment]
esto ya va
