### ISSUE TITLE
[Trono de las Mareas] #pveeros 

### ISSUE THREAD

**Issue by keinting** [RoDNet/Bugtracker-Infinium-4.3.4#734]
http://es.wowhead.com/zone=5004  [Trono de las mareas]

Lo que ocurre es que http://es.wowhead.com/npc=40586 deberia dejar a sus subditos aqui en esta puerta e inmediatamente irse a su sitio, permitiendo que transcurra el combate con http://es.wowhead.com/npc=40765 pero esto no ocurre, lo que ocurre es que se queda alli en modo piñata, se le mata y tal, pero no dropea nada, y tampoco abre la puerta...
 una foto de lo que dejo 
![wowscrnshot_072313_103850](https://f.cloud.github.com/assets/4027034/842424/14b34eb2-f3aa-11e2-9046-00ff7dbd6fb3.jpg)

Att: Teufel

**Comment by DatJetto** [comment]
Has cambiado el orden ( o yo te he entendido mal ) 
Como dices, Lady Naz'Jar corre por la sala hacia su posición para el combate y la puerta se cierra, obviamente dejando los súbditos atrás, cuando matas los súbditos la puerta se abre.

En este momento el Comandante Ulthok NO DEBERÍA estar ahí, debería de llegarse hasta Lady Naz'Jar y entablar combate con ella, una vez derrotada con sus fases y tal, pulsamos el aparato al lado de la puerta, presenciaremos una cinemática y la puerta se abrirá, ESTO SÍ DA PASO al 2º Boss Comandante Ulthuk.

**Comment by keinting** [comment]
A ciencia cierta, pense que el combate era como explique... pero capaz no, asu que entonces si la historia transcurre como vos dices, esta peor XDD..

Porque entonces lo que queda malo seria esto:
-Subditos que no hacen nada
-Lady Naz'Jar tampoco hace nada
-Dispositivo para abrir la puerta no funciona
-Comandante  Ulthuk no pelea con Lady Naz'Jar

Creo que es eso, no?

**Comment by DatJetto** [comment]
No, El Comandante y Lady no pelean , peleas tú ( El grupo ) con ambos, me refería a que el comandante no está ahí en ese momento, el grupo pasa hasta lady naz, la derrota y ahora aparece el comandante y el grupo se da de toñas con él

**Comment by keinting** [comment]
ah weno, entonces si esta bug como dije al principio xd

**Comment by efectokoleos** [comment]
arreglados los bosses y el evento de lady nazjar deberia funcionar correctamente, si veis que no se mueve volver hacia el ascensor y se irá correctamente
