### ISSUE TITLE
Peletería

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#735]
Cuando se desuella a un npc siempre conseguimos un solo cuero, y rara vez ninguno. Esto no debería de ser así, ya que un npc siempre debe de soltar un mínimo de un cuero al desollar, y ademas de eso poder soltar mas de uno. Al no estar bien a los peleteros se nos hace muy tardío subir la profesión.

Un ejemplo: 

Yo estoy desollando "Can manáfago" http://es.wowhead.com/npc=6010/can-manafago#skinning 

Si nos vamos a sus probabilidades de obtener cueros vemos que se reparte así:

1 - 6 cuero basto 84%
1 - 6 cuero grueso 11%
1 - 5 pellejo basto 5%

Como podemos observar la suma de los porcentajes da un total de un 100% de dropeo de algo de las 3 cosas, mientras que actualmente también esta la posibilidad de que no salga nada, cosa que no debería ocurrir. Además de que siempre obtenemos 1 solo, nunca 2 o mas, a diferencia de minería que si se pueden conseguir mas de una mena de golpe al picar.

En conclusión: No siempre se obtienen cueros al desollar (no debería de ser así) y nunca obtenemos mas de un cuero.

**Comment by Moyax** [comment]
Lo que dice Fox es cierto.. Subir peletereia horita es muy complicado, no porque sea por 1 sino porque de cada 10 mobs 3 no dan nada. Y los que dan solo dan 1 cuero osea por cada 100 mobs son almenos 8-12 niveles que se puede subir la habilidad.

**Comment by foxmclaud** [comment]
Toda la razón Lvmb, le puse peletería porque es la que cuesta subir. A tu reporte solo le falta lo de que a veces no da ningún cuero de los posibles jeje.

**Comment by Moyax** [comment]
Ya  subir peleteria es mas humano pero a hora hay un problem... Cuando llegas a 515 solo puedes hacer las recetas de las ropas sañosas del T11 que actualmente estan desabilitadas, para crearlas. Y por consiguiente no puedes seguir suviendo la profe a 525. =P te quedas estancado en 515 de habilidad.

**Comment by Compresor** [comment]
Los mobs sueltan más de un cuero. Cierro
