### ISSUE TITLE
[¿Errores Internos?]Puerta Sala de los Campeones (Honor - Conquista) Ventormenta

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#736]
Buenas Staff, sigan trabajando duro, ya los ticket closed superaran a los abiertos en breve...

Vengo a reportar esto que me parece esta muy mal, y aclaro que lo que ven en las fotos ,lo hice solo para probar.

Es posible cerrar este importante lugar al resto de jugadores, aún no sabemos por qué, pero deberia ser corregido...

![wowscrnshot_072313_103938](https://f.cloud.github.com/assets/4790547/842667/cbbfd824-f3ae-11e2-8d2e-b4877a0a5a22.jpg)
![wowscrnshot_072313_103941](https://f.cloud.github.com/assets/4790547/842668/cbdd09c6-f3ae-11e2-83ef-7a9947ffd9ab.jpg)

**Comment by DatJetto** [comment]
Este Gobject, no debería ser usable por los jugadores.

**Comment by ghost** [comment]
Por lo que pude comprobar, ya no existe la puerta xd, así que esta "solucionado".
