### ISSUE TITLE
[Guerrero] Golpe Heroico

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#737]
Esta skill http://es.wowhead.com/spell=78#. (aunque esa es la MoP, dice que inflige 2965 de daño (en mi caso) pero pega más de 10k.
Gracias

**Comment by lamaza** [comment]
Gracias por la aclaración lvmb.

Dejo la foto
![wowscrnshot_072313_123437](https://f.cloud.github.com/assets/4790547/843478/de4dbcda-f3be-11e2-80ee-9478e2c06c0c.jpg)

**Comment by efectokoleos** [comment]
fixed
