### ISSUE TITLE
[Quest] Crisol de la matanza

### ISSUE THREAD

**Issue by elmiriox15** [RoDNet/Bugtracker-Infinium-4.3.4#739]
Esta cadena de quest empieza con http://es.wowhead.com/quest=27863 pero no aparece el NPC (es más al bajar te ataca un NPC invisible al cual no se le puede pegar.
Con lo cuál esta cadena de quest no se puede hacer y dificulta mucho el leveo de 84 a 85.
Gracias.

**Comment by redneo** [comment]
la arreglé ya.
