### ISSUE TITLE
cds de abalorios y encantamientos ect

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#74]
parece que los abalorios tipo http://es.wowhead.com/item=65072 ,encatamientos tipo http://es.wowhead.com/item=52776 y encatamientos de profesion como http://es.wowhead.com/spell=55777/bordado-de-guardia-de-espada ,saltan practicamete siempre subiendo un monton el dps y llebando a  una clase sin bug a parece que esta rebug cuando en realidad con estos cds internos los que no estan bien deveria de saltar cada 40 seg o mas, tambien depende de cada abalorio o encantamiento

**Comment by redneo** [comment]
Los abalorios de la 406 tengo los datos.... ahora toca sacar tambien los de las versiones superiores... me pondré a ello, gracias!

**Comment by redneo** [comment]
Muchos de ellos puestos, a lo mejor falta alguno, please report it!
