### ISSUE TITLE
[ Warrior > Heroic Strike ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#740]
http://www.wowhead.com/spell=78

Todas las pruebas a continuación están realizadas SIN TALENTOS ( evitando potenciación de terceros ) , SIN BUFFS Y EN STANCE DEFENSIVA ( por que las otras 2 aumentan el daño en % )

Golpe heroico está realizando un daño masivo; 

![wowscrnshot_072313_182422](https://f.cloud.github.com/assets/2728817/843123/1fa5cc92-f3b8-11e2-8df3-85210e522ddc.jpg)

10k cuando debería pegar 2,4k

Fórmula: ( 0.6*AP )

**Comment by Wiinter** [comment]
#737

**Comment by ghost** [comment]
Como lo dijo @Wiinter cierro este reporte para que continuen en el anterior.
