### ISSUE TITLE
[ Warrior > Heroic Throw ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#742]
Lanzamiento heróico: 
http://es.wowhead.com/spell=57755

Fórmula> ( 0.75 \* AP ) 

![wowscrnshot_072313_182815](https://f.cloud.github.com/assets/2728817/843160/c50471b6-f3b8-11e2-9301-05799aa698c4.jpg)

tiene el daño subido, de 3k pasa a 4.3k

**Comment by searum** [comment]
anda tio haz calculos... tira de matematicas un poco! 0,75 x 5754ap que tienes es igual aaaa????? ^^
