### ISSUE TITLE
[ Warrior > Desgarrar ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#743]
Desgarrar ( Pendiente de ID, Eliminada por Pandaria )
![wowscrnshot_072313_182822](https://f.cloud.github.com/assets/2728817/843180/1ccb662a-f3b9-11e2-90e9-c3b2a9151687.jpg)

Fórmula: ( 0.271 \* AP )

Debería realizar Ticks de 1k, sin embargo realiza ticks de 890p.

**Comment by searum** [comment]
al final te prohibo postear el dr damage :)
