### ISSUE TITLE
[Errores internos] Banco de Hermandad

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#744]
Al abrirlo, nos esta dando wowerror.

**Comment by Dekadencee** [comment]
¿Lo sigue dando?

**Comment by crowel** [comment]
Si esto paso durante un rato despues de fixearlo, Searum lo comprobo de nuevo y lo soluciono.
Quita los Addons y borra Cache.
Un saludo.
