### ISSUE TITLE
CIUDAD GLINEAS Y NPCs. INSTRUCTORES Y REY

### ISSUE THREAD

**Issue by Sheilina** [RoDNet/Bugtracker-Infinium-4.3.4#745]
La zona de inicio de la Ciudad de Glineas me ha dado los siguientes problemas:
- Los instructores de clase no dan la opción de aprender ninguna habilidad y con frecuencia desaparecen por completo de la zona. Me ha sido imposible entregar misiones y realizar las cadenas.
- En la zona con frecuencia aparecen demasiados enemigos superpuestos que bloquean totalmente el paso y al ser tantos es imposible matarlos. La única opción es estar en un grupo de 2 ó 3 como mínimo, y aún así es muy complicado moverse por la ciudad.
- El rey Cringris en una de las misiones ha de llevar a caballo al jugador hasta una zona y esta acción no la realiza. Tampoco permite entregar ninguna quest de las que se requiere para poder levear. 
  Salir de la zona de inicio resulta imposible con estas complicaciones, por lo que lo comunico para su resolución.
  Un saludo.

**Comment by crowel** [comment]
Ahora mismo se está fixeando la misión, quest=14293, acostumbraros a poner enlaces porfavor o no se sabra cual reparar.

Respecto a lo que dices de "Los intructores no dan la opción de reparar" ¿A que clase te refieres?, hace un rato se implemento un fix con el cual los instructores que no enseñaban ahora lo haran y la misión que daban ahora funcionara, cuando se caiga o reinicie el servidor.
Un saludo.

**Comment by Sheilina** [comment]
Dije que los instructores no permiten aprender habilidades como sería lo normal.

**Comment by crowel** [comment]
¿Pero enseñan ya? Si alguno no enseña dime cual, gracias.

**Comment by crowel** [comment]
Los fallos que comentas estan solucionados.
Cierro Issue.
