### ISSUE TITLE
Misiones Bug Valle Sombraluna

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#746]
Disensión en las filas: Te pones el tabardo y al matar no cuenta.
http://es.wowhead.com/quest=10776

Presagistas de sombraluna: Te pones las gafas "Espectroculos", ves a los presagistas pero no se pueden matar.
http://es.wowhead.com/quest=10643

La clave de condenacion: La carga de Borak: Objetivo no atacable.
http://es.wowhead.com/quest=10578

La trampa mas mortal jamas tendida: No pasada nada cuando la coges.
http://es.wowhead.com/quest=11101

¡Infernales por los aires!: Al activar la bomba no la completa.
http://es.wowhead.com/quest=10564

Carrera faucedraco: La balada del viejo viejete: No funciona.
http://es.wowhead.com/quest=11064

Los cielos no tan amistosos: Los dracos no se mueven. Solo he visto a 3 dracos y ninguno ha soltado la reliquia (drop: 99%).
http://es.wowhead.com/quest=11035

Adivinacion: la clava de sanguino: Con los "Espectroculos" puestos no aparecen en el recorrido marcado en el mapa.
http://es.wowhead.com/quest=10636

Molde de llave preparado: El objeto no da la mision.
http://es.wowhead.com/item=31239

**Comment by foxmclaud** [comment]
He recibido al correo un mensaje diciendo que los reportase individualmente y que habías cerrado el reporte. Ahora lo encuentro abierto. ¿Reporto cada misión por separado entonces? ¿No lo hago?.

Se que es mas cómodo para vosotros ir una a una, pero así tenéis una lista entera de las que fallan en la zona. En caso de arreglar algunas siempre podéis editar el reporte con las ya arregladas.

Un saludo

**Comment by crowel** [comment]
Así como está ahora mismo está bien, perdona por cerrarlo :)

**Comment by redneo** [comment]
Asi es un coñazo, pq pa cerrar este ticket pasaran siglos
Disensión en las filas: Te pones el tabardo y al matar no cuenta.
http://es.wowhead.com/quest=10776
reparada

La clave de condenacion: La carga de Borak: Objetivo no atacable.
http://es.wowhead.com/quest=10578
reparada

¡Infernales por los aires!: Al activar la bomba no la completa.
http://es.wowhead.com/quest=10564
reparada

Los cielos no tan amistosos: Los dracos no se mueven. Solo he visto a 3 dracos y ninguno ha soltado la reliquia (drop: 99%).
http://es.wowhead.com/quest=11035
reparada

Molde de llave preparado: El objeto no da la mision.
http://es.wowhead.com/item=31239
a mi me la da perfectamente....

Ea, unas cuantas reparadas, el resto las pones independientemente.
