### ISSUE TITLE
[Warrior]  Golpe Heroico - Daño Increible 50k+

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#747]
Tengo 2753 (30% reduccion) de temple y 20792 de armadura (44% reduccion) en mi pj, y este war Killer, compa alianza, me pega esto en arenas.

http://es.wowhead.com/spell=78
Golpe Heroico

![wowscrnshot_072313_123437](https://f.cloud.github.com/assets/4790547/843478/de4dbcda-f3be-11e2-80ee-9478e2c06c0c.jpg)

Ilógico y necesario de reparación lo antes posible...

**Comment by ghost** [comment]
Ya lo reportaron, #740  y #737 paso a cerrarlo @lamaza
