### ISSUE TITLE
Misión (Bosque del Ocaso)"Entrega a Harris" BUG

### ISSUE THREAD

**Issue by Shadowye** [RoDNet/Bugtracker-Infinium-4.3.4#748]
Cuando te otorgan la misión "Entrega a Harris" debes ir a hablar con Oliver Harris en Cerro del Cuervo (Bosque del Ocaso).Lo que pasa es que dicho npc NO está,por lo que no se puede completar la misión y seguir con la cadena de misiones.
![wowscrnshot_072313_193038](https://f.cloud.github.com/assets/5068190/843469/93932c52-f3be-11e2-8f46-c968c05a79f7.jpg)
ID de la misión: http://es.wowhead.com/quest=26719
ID de Oliver Harris: http://es.wowhead.com/npc=43730

**Comment by Kiritoo** [comment]
Funciona correctamente.
