### ISSUE TITLE
Misión "Reconfortando a los Espíritus"BUG

### ISSUE THREAD

**Issue by Shadowye** [RoDNet/Bugtracker-Infinium-4.3.4#749]
Cuando te otorgan la misión "Reconfortando a los Espíritus" te piden tranquilizar a 5 espíritus melancólicos en la Granja de Addle (Bosque del Ocaso) hechandoles unos polvos.Cuando les hechas dichos polvos NO pasa nada por lo que no cuenta como tranquilizado y no se puede completar la misión.
![wowscrnshot_072313_194606](https://f.cloud.github.com/assets/5068190/843526/39347c50-f3c0-11e2-9780-4019fe7f61e0.jpg)
ID de la misión: http://es.wowhead.com/quest=26777
ID del Espíritu Melancólico: http://es.wowhead.com/npc=43923

**Comment by crowel** [comment]
Acabo de comprobarlo y al primero que le use los polvos funciono, cierro Issue.
Un saludo.
