### ISSUE TITLE
[Pet] Vida

### ISSUE THREAD

**Issue by shials** [RoDNet/Bugtracker-Infinium-4.3.4#75]
Según el servidor oficial y mediante una simple regla de tres, 
La vida de la pet está muy por debajo de la que debería ya que:
Teniendo el Hunter 128,8k de vida y aplicando la regla de tres
Si un hunter tiene 160k  y su pet 177k ( según video del servidor oficial )
Yo teniendo 128,8k mi pet debería tener 142.485 de vida , y no los tiene.  aquí la prueba
![wowscrnshot_070413_133008](https://f.cloud.github.com/assets/4938203/749070/71e8be58-e49d-11e2-9674-a1256a51bac9.jpg)

https://www.youtube.com/watch?v=d7U639DgFyc Video

**Comment by ghost** [comment]
Ya esta bien la vida de la pet del cazador.
