### ISSUE TITLE
Misiones Bug (Montaña Filospada)

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#750]
Un látigo vil para Gahk: Pagando los 35 ápices no aparece el npc.
http://es.wowhead.com/quest=11079

Una reliquia de ápices: No funciona el cristal.
http://es.wowhead.com/quest=11058

Reinar en los cielos: No se puede invocar con 35 ápices.
http://es.wowhead.com/quest=11078

Clavar el estandarte: Al clavarlo no viene el npc a matar.
http://es.wowhead.com/quest=10518

Una situacion extrema: al utilizar los polvos de disminución de Reina reduce de tamaño a los lobos pero no cuentan cuando los matas.
http://es.wowhead.com/quest=10506

Vuelo de prueba: el cefirium capacitorium: Hablas y no hace nada.
http://es.wowhead.com/quest=10557

Medir la frecuencia resonante: El objeto no hace nada.
http://es.wowhead.com/quest=10594

¿Que fue primero?¿El draco o el huevo?: No salen dracos pequeños de los huevos para transformarlos.
http://es.wowhead.com/quest=10609

Susurros del Dios cuervo: No se activan las profecías con lo cual no cuentan.
http://es.wowhead.com/quest=10607

Crías culto vermis: Se atrapan con la red pero no cuentan.
http://es.wowhead.com/quest=10747

Gorgron el Comedragones: No cuentan los tótems.
http://es.wowhead.com/quest=10802

El exorcismo de los arboles: No dan el orbe para combinarlo con la pluma.
http://es.wowhead.com/quest=10830

¡Fuego a discreción!: Los cañones viles no funcionan.
http://es.wowhead.com/quest=10911

**Comment by ghost** [comment]
Te aconsejo poner cada misión en un reporte a parte.

**Comment by Kiritoo** [comment]
http://www.reignofdarkness.net/wow/forums/7-informacion-del-servidor/24-reporte-de-bugs-bugtracker-como-reportar-un-bug/
Hola porfavor pon un reporte por misión si no te importa.
Saludos.
