### ISSUE TITLE
Segun aveces no ven a mi Pj en Arenas, Bg y demas...

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#751]
Me tienen medio cansado con eso ¬¬ no te vemos... Yo no veo Pjs en Bg y me matan y al rato que revivo ya puedo verlos. ME DICEN que abra un Issu sobre esto, para que segun revisen mi pj a ver si tiene algo malo... Nombre PJ:   Moya.
Gracias.. A ver si asi dejan ya.

**Comment by WarSxNes** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/374?source=cc <<<<<< POST RELACIONADO

Hola salUuUuudOoSss... de casualidad no te pasara lo siguiente? ^ (Leer el post del link).

> nota no mas no cierren el post del link hasta que no lo confirmen, o dejarlo como referencia.

**Comment by lamaza** [comment]
No te enojes vale haha. Todo en pro de jugar en =les !.

**Comment by Moyax** [comment]
No creo... Los pj me ven afuera de la arena pero cuando entro "Aveces" me dicen no te vemos...

**Comment by crowel** [comment]
Tema repetido, continuamos por el anterior 374.
Cierro, un saludo.
