### ISSUE TITLE
[DK] Atraccion Letal

### ISSUE THREAD

**Issue by keinting** [RoDNet/Bugtracker-Infinium-4.3.4#752]
La spell http://es.wowhead.com/spell=49576 no tiene CD, se puede usar a placer en algunos DKs...  En otros si funciona bien, no se  aque se deba eso, peor de cualquier forma, le reporto...

Att: Teufel

**Comment by lamaza** [comment]
Es verdad, si se tira 3 o 4 veces, deja al pj objetivo levitando, y lo puede mantener en el aire si lo sabe spammear debajo bien. Pongo un ejemplo, pero tambien lo probamos fuera de ventormenta en duelo y funcionó la "levitación".
![wowscrnshot_072313_124534](https://f.cloud.github.com/assets/4790547/843713/86842c7c-f3c4-11e2-8906-c983464bfcd1.jpg)

**Comment by F4NT4SM4** [comment]
El bug no esta en el hechizo 
el bug esta esta en el Talento Orden Profana
el id ya que fue eliminado de wowhead y fue cambiado a un glifo http://es.wowhead.com/spell=59328/orden-profana

**Comment by ghost** [comment]
Este es el id del talento http://www.wowhead.com/spell=49588, por más que borren el talento de wowhead, mientras el id sea el correcto no importa.

**Comment by searum** [comment]
fix
