### ISSUE TITLE
Npc con daño masivo

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#753]
http://es.wowhead.com/npc=47387/harakiss-el-infeccioso
Me ha golpeado y me a matado de un golpe.
![wowscrnshot_072313_203022](https://f.cloud.github.com/assets/5048096/843796/5a576770-f3c6-11e2-8e56-96c1286fb718.jpg)

**Comment by Moyax** [comment]
jajaja ese yo lo mate xD con mi chamy lenteandolo y corriendo.. xq si me agarraba triste :P me mato 2 veces y cuando lo mate... No solto nada, ni cueros al desollarlo.

**Comment by redneo** [comment]
arreglado
