### ISSUE TITLE
Misión "La venganza de Mantoniebla" BUG

### ISSUE THREAD

**Issue by Shadowye** [RoDNet/Bugtracker-Infinium-4.3.4#754]
Cuanto aceptas la misión te otorgan 1 anillo que debes de usar en la Mansión Mantoniebla (Bosque del Ocaso).Cuando usas el anillo NO pasa nada por lo que no se puede completar la misión.
![wowscrnshot_072313_203513](https://f.cloud.github.com/assets/5068190/843846/327f7b9c-f3c7-11e2-989b-407ef3d7c5fa.jpg)
ID de la misión: http://es.wowhead.com/quest=26674

**Comment by redneo** [comment]
se arregló ya
