### ISSUE TITLE
Vida y Nivel ANORMAL en Indentes de Conquista

### ISSUE THREAD

**Issue by Shadowye** [RoDNet/Bugtracker-Infinium-4.3.4#755]
Los intendentes de conquista tienen 82 de vida y nivel 1 por lo que si viene 1 horda los matará al instante,por lo que los alianzas estaremos un buen rato sin poder comprar objetos.
![wowscrnshot_072313_213717](https://f.cloud.github.com/assets/5068190/844302/0c8978e4-f3d0-11e2-81ab-9f0cc9a16933.jpg)
ID del vendedor en la HORDA: http://es.wowhead.com/npc=69978
ID del vendedor en la ALIANZA: No encontrado :S

**Comment by Kiritoo** [comment]
Fix
