### ISSUE TITLE
Reporte (largo) de misiones bug en Hijal Uldum e Infralar

### ISSUE THREAD

**Issue by mccelobb** [RoDNet/Bugtracker-Infinium-4.3.4#756]
Lista de misiones bug:
Infralar:
http://es.wowhead.com/quests=11.5042?filter=maxrl=82;cr=8;crs=4;crv=40304#0-3+1+2 (ACLARO: son los npc los que estan bug ya que no aparecen)
Hijal:
http://es.wowhead.com/quest=25462/los-osos-de-ahi-arriba
http://es.wowhead.com/quest=25600/maestro-de-forja-pyrendius
http://es.wowhead.com/quest=25385/salva-a-los-animalitos
http://es.wowhead.com/quest=25404/si-no-estas-contra-nosotros
Uldum:
http://es.wowhead.com/quest=28558/se-busca-heroe-uldum
http://es.wowhead.com/quest=28002/gestion-de-crisis
http://es.wowhead.com/quest=27519/bajo-arenas-asfixiantes
http://es.wowhead.com/quest=27899/ese-brillo-en-sus-ojos
http://es.wowhead.com/quest=27623/guardianes-colosales
http://es.wowhead.com/quest=27993/dales-su-merecido

Confio en que arreglaran todo lo mas pronto posible ya que los que estamos en los lvl 80-84 (como dice el dicho) Nadamos tanto y nos ahogamos en la orilla.
PD: solo son las quest que tengo en el registro.

**Comment by ghost** [comment]
¿Puedes poner, cada misión en un reporte a parte?, así no creo que lo vayan a leer, además no especificas qué cosa esta bug en todas esas misiones, por otra parte, tengo entendido que @redneo va corrijiendo de a poco las misiones en las zonas Cataclysm.

**Comment by redneo** [comment]
Los npcs de Infralar si que aparecen si vais haciendo la cadena de misiones, lo cual me lleva a capar el portal.
De hyjal se arreglaron pusieron autocompletables las que enumeras

Uldum ya llegará.

**Comment by Kiritoo** [comment]
Cerramos por multireporte.
