### ISSUE TITLE
[Mazmo/Banda] Karazhan: Attumen el Montero

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#757]
Buenas.
Queria informar el PNJ Attumen el Montero (http://es.wowhead.com/npc=16152/) de la mazmo Karazhan (http://es.wowhead.com/zone=3457) no funciona correctamente ya que su habilidad Cuchilla de las Sombras (http://es.wowhead.com/spell=29832) hace un daño excesivo (me hizo 50k siendo DK sangre).
Gracias y hasta luego.

**Comment by ghost** [comment]
Su daño automatico también esta elevado.

**Comment by efectokoleos** [comment]
el daño esta arreglado
