### ISSUE TITLE
[Mazmo/Banda] Núcleo de Magma: Ragnaros

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#758]
Buenas.
El PNJ Ragnaros (http://es.wowhead.com/npc=11502/) de la mazmo Núcleo de Magma (http://es.wowhead.com/zone=2717) una vez terminado el evento en que aparece y mata al Mayordomo Executus (http://es.wowhead.com/npc=12018), se vuelve hostil pero no puede atacar ni ser atacado. El resto de la mazmo funciona de 100.
Gracias.

**Comment by efectokoleos** [comment]
prueba cuando se caiga el server
