### ISSUE TITLE
Inscripcion bug

### ISSUE THREAD

**Issue by mccelobb** [RoDNet/Bugtracker-Infinium-4.3.4#759]
Se supone que algunos objetos que creas aumentan mas de 1 punto en determinados niveles pero esto esta bug, solo aumentan 1 punto.
![wowscrnshot_072313_183706](https://f.cloud.github.com/assets/3194580/845264/ff78fcb0-f3e3-11e2-855e-6c7cefd734c8.jpg)
Fijense en la ventana de chat: Lvl:202 Creas Glifo de DIsuacion Lvl:203

**Comment by crowel** [comment]
Siento decir que aumenta dependiendo de como esten los rates en el servidor.
En este caso estan x1 en profesiones por ello sube de 1 en 1.

Un saludo.

**Comment by F4NT4SM4** [comment]
ya pero crear el glifo normamente deberia de aumentar 3 
mira a la derecha esta un simbolo de flecha ariba y 3
significa que deberia de aumentar 3 si los ratex estan x2 ps aumentaria 6 y asi

**Comment by ghost** [comment]
@crowel así como dice F4nt4sm4, debería aumentar 3 puntos, porque así esta en la profesión, no tiene nada que ver con los rates.

**Comment by crowel** [comment]
Si teneis razón lo normal es que suba de uno en uno peroo no me fijara en el icono de la derecha el cual avisa que la creación debe subir 3 puntos, voi a Reabrir el mensaje para que conste lo que pasa.
Sry, un saludo.

**Comment by Moyax** [comment]
Antes de actualizar a la 4.3.4 ami me subía perfectamente a pesar que el rate era x1. Cuando estaba en naranja al realizar esas recetas si aumentaba 3 cada vez que la realizaba, luego al pasar a amarillo ya no daba el aumento.
