### ISSUE TITLE
[Campo de batalla]Problemas al cambiar talentos antes de comenzar.

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#76]
Como el título indica los talentos no deja cambiarlos antes de comenzar bg, cosa que deberia, no puedes hacer eso ahora mismo te aparece.

![problema al cambiar talentos antes de comenzar](https://f.cloud.github.com/assets/3537253/749105/c41c80c8-e49e-11e2-8572-24fe5b56710b.jpg)

Un saludo.

**Comment by crowel** [comment]
Porfavor añadirle label cuando se pueda^^
Un saludo.

**Comment by ghost** [comment]
Esto sigue bug no?

**Comment by Wiinter** [comment]
sep
