### ISSUE TITLE
[Mision] El círculo de sangre: el desafío final

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#760]
Buenas.
La misión El Círculo de Sangre: el desafío final (http://es.wowhead.com/quest=9977) no se puede completar debido a que al derrotar a Mogor (http://es.wowhead.com/npc=18069/), este no revive ni la misión aparece como completada:
![wowscrnshot_072313_194832](https://f.cloud.github.com/assets/4582987/845570/0a495f20-f3eb-11e2-9f4f-7b24c68ca683.jpg)
Eso es todo, gracias y hasta luego.

**Comment by redneo** [comment]
arreglada parcialmente, al menos cuenta
