### ISSUE TITLE
"Los secretos de la torre"

### ISSUE THREAD

**Issue by Sheilina** [RoDNet/Bugtracker-Infinium-4.3.4#761]
En esta misión, tras tomar la poción y subir por el interior de la torre, el npc que debería figurar y contar la historia no aparecía. 
Además, una vez abandonada la torre no pude eliminar el efecto de la poción de velo, incluso después de haber transcurrido el tiempo de 10 minutos. El personaje se bloquea en este estado.

**Comment by ghost** [comment]
@Sheilina la próxima, debes dejar enlaces a wowhead para facilitar el arreglo de la misión :)

Misión http://es.wowhead.com/quest=26290
Poción de velo item http://es.wowhead.com/item=58112
Poción de velo spell http://es.wowhead.com/spell=79528
Helix Rompengranajes http://es.wowhead.com/npc=42753

**Comment by crowel** [comment]
Y aquí ya reportada anteriormente https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/538.
Cierro, seguimos por el reporte anterior.
Un saludo.
