### ISSUE TITLE
[Mision] Algo pasa con el escudero

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#762]
Mision: http://es.wowhead.com/quest=13654/algo-pasa-con-el-escudero

El pnj Maloric ID: 33498 no da la recompensa de la mision hay que darle con un hueso y robarle cuando esta aturdido pero salen las bolsas para despojar y no despojamos nada
![wowscrnshot_072413_024301](https://f.cloud.github.com/assets/4893907/845978/9026c01a-f3fa-11e2-840c-d203a5a72c36.jpg)

![wowscrnshot_072413_024257](https://f.cloud.github.com/assets/4893907/845991/c0fbca78-f3fa-11e2-9cd2-31301d10d374.jpg)

**Comment by WarSxNes** [comment]
Oo esa es de las del TORNEO ARGENTA ... hihihi a comenzar de nuevo... (hay que reparar algunas)

---

En realidad esa en 4.0.6a estaba de la siguienta forma:
- cuando le pegabas con un http://es.wowhead.com/item=45080 <<< **Fémur grande** ...
- el cual lo tiraba un http://es.wowhead.com/npc=33499 <<<< **Cortador de leña esquelético**...
- el NPC (MALORIC) automaticamente te entregaba dicho http://es.wowhead.com/item=45082 <<<< **Juego de herramientas de asesino** el cual era necesario para completar la quest....

Osease,,, :P no habia necesidad de despojar nada. simplemente le pegabas con el hueso y ( _pu-Ka-tA-tLas!!!...!@#$_ ) automaticamente te daba el item.

> Oh!!! y no es nada ahi te dejo los links hihihi

**Comment by frustrix** [comment]
Buenas........ estoy diciendo que no da el Item para completar la mision. Me da igual como estaba antes ahora no da el ITEM.

Cuando ponga un tikec procura no responderlo tu, es la 3 vez que hablas sin tener ni idea y haciendote pasar por uno que sabe sin tener idea

Saludos

**Comment by WarSxNes** [comment]
Aaaa... No se si hablamos el mismo idioma???

Lo unico que hice fue ponerte los **LINKS**... que de malo tiene?

> En ningun momento dije que "NO estubiera bug" hihihih.... :P
> - y una breve explicacion de como funcionaba antes para que cuando la reparen tengan mas o menos una idea de como hacerlo. (no se si esta vez me doy a entender?)
>   - incluso al principio de mi comentario dije " _(hay que reparar algunas)_ "

**Comment by frustrix** [comment]
sin comentarios

**Comment by lamaza** [comment]
Al dia de hoy sigue bug, no se puede despojar a Maloric. =/

**Comment by redneo** [comment]
ODIO EL TORNEO ARGENTA!

arreglada... y haya paz!!!!
