### ISSUE TITLE
Misión John J. Keeshan

### ISSUE THREAD

**Issue by Sheilina** [RoDNet/Bugtracker-Infinium-4.3.4#763]
En el sótano de la posada Villa del Lago debería estar John J. Keeshan para completar la quest, pero no aparece el npc. No obstante en el mapa sí figura la interrogación en el lugar preciso de entrega (como si efectivamente estuviera).
El Colonel Troteman que es quien da la misión se pone con interrogante amarillo como si ya estuviera completa, pero ni en el registro de misiones está completa ni tampoco deja la opción de entregarla a él.
Saludos

**Comment by lamaza** [comment]
Ya esta reportada.

https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/715

**Comment by redneo** [comment]
fix
