### ISSUE TITLE
[Mazmorra] Fortaleza de Drak'Tharon. 

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#764]
Hay varios npcs que te pegan pero tu no les puedes pegar ni targetear. Entonces es imposible llegar al último boss porque el último pasillo está lleno de ellos.

**Comment by efectokoleos** [comment]
en el proximo reinicio deberian estar bien

**Comment by efectokoleos** [comment]
arreglado
