### ISSUE TITLE
[ Warrior > Cleave ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#765]
Rajar: http://es.wowhead.com/spell=845

![wowscrnshot_072313_182903](https://f.cloud.github.com/assets/2728817/848336/b4193626-f45c-11e2-9e1c-3a5b7ab055fa.jpg)

El daño de esta spell se encuentra aumentado, vemos cómo de daño hace 2.6k de daño cuando debería hacer 1.8k

Fórmula: ( 0,45 \* AP )

**Comment by searum** [comment]
te repito lo de antes... multiplica los coeficientes
