### ISSUE TITLE
[ Warrior > Whirlwind ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#766]
Torbellino: http://www.wowhead.com/spell=1680

![wowscrnshot_072413_144216](https://f.cloud.github.com/assets/2728817/848474/55bdcb96-f461-11e2-91c2-d9f41956703d.jpg)

![wowscrnshot_072313_182925](https://f.cloud.github.com/assets/2728817/848342/12cc4578-f45d-11e2-987f-c8926f8fcc17.jpg)

 Fórmula: 65% Weapon Damage + ( 0,236 \* AP )

Da 2 Golpes, uno de 350 de daño y otro que está el daño subido, debería ser  1,8k y da 2,8k 

( Todas las pruebas del warrior que estoy subiendo son sin talentos y con 1 arma solo )

**Comment by Moyax** [comment]
mmm... la media es 1.8k segun eso que estas usando. Pero podria pegar  2.1k segun tus mismos datos. Tambien estas en actitud rabiosa, segun tambien aumenta el daño. Que addon es ese que usas?

**Comment by lamaza** [comment]
DrDamage se llama el addon. Gracias por los reportes DJ. Me gusta leerlos y ver como cada clase se va a nivelar y aprender cosas del WoW.

**Comment by DatJetto** [comment]
Moyax como MUCHO debe pegar 2,1 , pero en las imágenes ves que de media da como mínimo 2,3 y como mucho 3k

**Comment by searum** [comment]
Nada tio... 1357 de daño con tu ap + 65% del daño del arma... pues echa cuentas tio xD
