### ISSUE TITLE
[ Warrior > Slam ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#767]
Embate: http://www.wowhead.com/spell=1464

Fórmula: 145% Weapon damage + ( 0,236 \* AP )

Esta spell se ejecuta varias veces de 1 solo ataque, es decir, casteamos una vez Slam pero golpea 2-3 veces y hace más daño del debido.

![wowscrnshot_072413_144109](https://f.cloud.github.com/assets/2728817/848483/ba8c89e0-f461-11e2-9fa6-7361b292cf50.jpg)

![wowscrnshot_072413_143947](https://f.cloud.github.com/assets/2728817/848484/c4bfa6d6-f461-11e2-867d-ed909b193169.jpg)

De unos 4k, pasa a 6k ( y encima da 2 veces ) y de 8k críticos pasa a 12k

**Comment by searum** [comment]
fix
