### ISSUE TITLE
[ Warrior > Victory Rush ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#768]
El daño de esta spell y su cura son demasiado elevadas:
Ataque de la victoria: http://es.wowhead.com/spell=34428

![wowscrnshot_072413_151339](https://f.cloud.github.com/assets/2728817/848579/e1bcecce-f463-11e2-852d-60d1f06f8bde.jpg)

de unos 3,5k que debería pegar, pasa a 9.8k y la cura es bestial, de 108.447p de vida que tengo me sana 27.443, debiendo sanar 21.689p, para que sanara 27k tendría que tener 137k de vida.

Fórmula: ( 0.56 \* AP )
Sanación: 20% de la salud total.

**Comment by searum** [comment]
esto esta fix
