### ISSUE TITLE
[ Warrior > Execute ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#769]
Ejecutar: http://es.wowhead.com/spell=5308

Esta spell inflinje poco daño, siendo el movimiento final para acabar con el enemigo

![wowscrnshot_072413_151746](https://f.cloud.github.com/assets/2728817/848645/70619abe-f465-11e2-965d-28d7321d274f.jpg)

Un golpe que inflinje ( 0,437 \* AP ) y consume hasta 20p. de ira para inflijir un daño máximo de  ( 1,311 \* AP ). Solo se puede usar con enemigos por debajo del 20% de salud.

Vemos como en la imagen se da el 2º caso, tenemos más de 20p. de ira, entonces cogerá la fórmula de ( 1,311 \* AP ) debiendo hacer 8k de daño aproximados, pero solo realiza 5k de daño.

La prueba ha sido realizada con el mob: http://es.wowhead.com/npc=47627 ( por si se puede mirar si tiene una armadura muy elevada, aunque no debería )

**Comment by searum** [comment]
esto ya va bien
