### ISSUE TITLE
Portales en infralar

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#77]
Hola me acabo de fijar que los dos portales de infralar que conducen a orgri y ventor no estan.
![wowscrnshot_070413_130804](https://f.cloud.github.com/assets/3537253/749135/1b3059a6-e4a0-11e2-926e-853e4e7d014d.jpg)

![wowscrnshot_070413_130808](https://f.cloud.github.com/assets/3537253/749136/2140a2b0-e4a0-11e2-962e-8408cf7c0032.jpg)

**Comment by redneo** [comment]
Ya estan y cuando caiga el server llevaran a su lado correcto
