### ISSUE TITLE
 [ Warrior > Overpower ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#770]
Abrumar: http://es.wowhead.com/spell=7384

![wowscrnshot_072413_154352](https://f.cloud.github.com/assets/2728817/848723/623b6198-f467-11e2-9e9a-2987d1e0de44.jpg)

La spell está pegando de más.

Fórmula: 125% Weapon Damage + ( 0,236 \* AP ) 

Si nos ponemos algunos talentos para poder usar abrumar, podemos ver como se potencia tantísimo que llega a pegar el doble de lo que debe: 

![wowscrnshot_072413_160255](https://f.cloud.github.com/assets/2728817/848881/46b4b6e2-f46a-11e2-9fdd-2c864a61eb82.jpg)

Debiendo pegar 9k llega a 18k

**Comment by searum** [comment]
esto va bien ya
