### ISSUE TITLE
[Mision]Un final para todas las cosas…

### ISSUE THREAD

**Issue by hairblood** [RoDNet/Bugtracker-Infinium-4.3.4#771]
La mision en si esta bien http://es.wowhead.com/quest=12779
lo que falla es el item que te dan http://es.wowhead.com/item=39700
va a una velocidad demasiado lenta cuando deberia ir mas o menos a 280%,como una montura voladora

**Comment by redneo** [comment]
por tierra va a toda leche :S no me acuerdo como cambiar la velocidad de vuelo.
