### ISSUE TITLE
[Mision]La llamada del chaman del mundo

### ISSUE THREAD

**Issue by hairblood** [RoDNet/Bugtracker-Infinium-4.3.4#775]
http://es.wowhead.com/quest=29439 directamente no esta trall donde deberia estar
http://es.wowhead.com/npc=54313

**Comment by DatJetto** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/730

**Comment by ghost** [comment]
Pues como dice DatJetto, cierro para que se siga en el #730
