### ISSUE TITLE
[Mision] (Monte Hyjal) Mientras hyjal arde

### ISSUE THREAD

**Issue by hairblood** [RoDNet/Bugtracker-Infinium-4.3.4#776]
http://es.wowhead.com/quest=25316 comlpeta la quest,pero al usar a 
aronus http://es.wowhead.com/npc=39140 no me lleva a hyjal,se queda quieto y no puedo bajar

**Comment by redneo** [comment]
nop, no encontre el taxi para llevarte, asi qeu antes transportes raros, lo dejé asi.

**Comment by crowel** [comment]
Hola queria comentar que esta quest sigue pasando lo mismo te montas y ahi te quedas sin ocurrir nada hasta que reloguees.
Y toca de ir a pié-volando hasta allí o tomar piedra a la ciudad y cojer portal a hyjal.
![wowscrnshot_081313_155924](https://f.cloud.github.com/assets/3537253/976172/ba1de4f4-0686-11e3-990f-172be53b80f9.jpg)

Saludos

**Comment by Compresor** [comment]
Funciona
