### ISSUE TITLE
[Mazmorra] Fortaleza de Utgarde

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#777]
Al matar a Skarvald el Constructor (http://es.wowhead.com/npc=24200)te debería salir el otro boss,Dolron el Controlador(http://es.wowhead.com/npc=24201). Pero no sale, otra vez Skarvald y no se le puede puede pegar ni targetear y encima te pega.

**Comment by hairblood** [comment]
en realidad(al menos en el ofi) te salen ambos a la vez

**Comment by DatJetto** [comment]
De hecho, deben de morir casi a la vez ( si no, se les regenera la vida ) por lo cual deben de aparecer los 2 al mismo tiempo.

**Comment by efectokoleos** [comment]
segun wowhead cuando muere uno, si el otro esta vivo sale el fantasma del k a muerto y es intargeteable hasta que muere el otro boss, de todas formas estoy mirando porke no sale spawneado el dolron xd

**Comment by efectokoleos** [comment]
fixed

**Comment by Wiinter** [comment]
Sigue pasando lo mismo :S

**Comment by redneo** [comment]
El tema es que le asigna al npc 24201 un flag de not attacable o selectable desde el principio siendo esos flags a los espiritus de los mismos al morir....

**Comment by efectokoleos** [comment]
cuando se caiga elserver prueba
