### ISSUE TITLE
[Mision]Divisor de llamas

### ISSUE THREAD

**Issue by hairblood** [RoDNet/Bugtracker-Infinium-4.3.4#778]
la quest funciona,excepto proque al usar el item http://es.wowhead.com/item=53107
con el npc elemental grande y deberian aparecer 10 pequeños pero solo sale 1
dificultando mucho la quest,ya que pide 30

**Comment by redneo** [comment]
ya... la siguiente mision tendras que tirarte un rato, ya que pasa más o menos lo mismo
