### ISSUE TITLE
Lord Pythas> Inexistente.

### ISSUE THREAD

**Issue by Hellythium** [RoDNet/Bugtracker-Infinium-4.3.4#779]
Uno de los bosses de la Mazmorra ''Cuevas de los Lamentos'' http://es.wowhead.com/zone=718/cuevas-de-los-lamentos , Lord Pythas http://es.wowhead.com/npc=3670#english-comments es inexistente, puesto a que en ambos mapas muestran donde debería de estar, este boss no se encuentra allí, ya he intentado reiniciando la instancia en varias ocasiones, pero sigue sin aparecer y en el sitio solo aparecen estos mobs de la instancia :
![wowscrnshot_072413_091051](https://f.cloud.github.com/assets/3613748/849277/e75df818-f471-11e2-947e-b3ea5709be18.jpg)
como se observa en la imagen aparecen tres mobs, dos humanoides y una cobra, los cuales no deberían de estar en ese sitio, allí debería de estar Lord Pythas, por que si no esta el boss, es imposible completar las mazmorra y por ende el logro.

Saludos, Darkstar.

**Comment by redneo** [comment]
creo que cuando caiga el server tendria que estar... hay una doble mazmorra spawneada, creo que tocara borrar todo y meterlo de nuevo

**Comment by lamaza** [comment]
Ya esta arreglado, hoy lo mate y obtuve el logro de cuevas.
