### ISSUE TITLE
Servidor como desconectado

### ISSUE THREAD

**Issue by D3VIL238** [RoDNet/Bugtracker-Infinium-4.3.4#78]
A bastante gente incluyéndome yo le esta pasando que no se puede entrar al server,ya que cuando entras al juego te sale la pantalla de elección del servidor y aparece infinium como desconectado,por lo que no se puede entrar

**Comment by D3VIL238** [comment]
Parece que ya va bien,si vuelve a pasar aviso,gracias

**Comment by Dekadencee** [comment]
Fixed
