### ISSUE TITLE
Bug deposito del vació tras caida

### ISSUE THREAD

**Issue by salydell** [RoDNet/Bugtracker-Infinium-4.3.4#780]
Tras la actualización el dia 24/7/13 empece a acomodar mis objetos y probar la bóveda del vació, para liberar espacio en el banco normal, guarde varios objetos (que listare al final los que recuerde) durante este con la bóveda abierta hubo una desconexión del servidor al entrar de nuevo revise la bóveda y estaba vacía, los objetos habían desaparecido revise mis bolsas el correo o el banco normal (por si hubiera sido un rollback) pero no en este caso simplemente habían desaparecido bueno este es el listado de los objetos perdido (escribo esto a los pocos minutos de que me pasara para tanto reportarlo como para ver si me es posible que se me recuperen estos objetos)

imagen de la bóveda vacía 
![wowscrnshot_072413_103125](https://f.cloud.github.com/assets/5082397/849838/2414b5f4-f47b-11e2-83bc-f42592ee081c.jpg)

imagen de mi equipo transfigurado con algunos de los objetos que estaban en la boveda 

![wowscrnshot_072413_103138](https://f.cloud.github.com/assets/5082397/849842/393f778e-f47b-11e2-8af4-55cdf7a70728.jpg)

lista de los objetos pedidos (o la mayoría)

http://www.wowhead.com/item=45886
http://www.wowhead.com/item=39521
http://www.wowhead.com/item=48072
http://www.wowhead.com/item=39284
http://www.wowhead.com/item=13534
http://www.wowhead.com/item=4090
http://www.wowhead.com/item=13004
http://www.wowhead.com/item=50805
http://www.wowhead.com/item=25336
http://www.wowhead.com/item=812
http://www.wowhead.com/item=13000
http://www.wowhead.com/item=50988
http://www.wowhead.com/item=51005
http://www.wowhead.com/item=51380
http://www.wowhead.com/item=51736
http://www.wowhead.com/item=51732
http://www.wowhead.com/item=51733
el set lv 70 de sastrería 
http://www.wowhead.com/itemset=554
el set pvp
http://www.wowhead.com/itemset=-224

si guardo muchas cosas si es posible se me podrian recuperar si no al menos soy feliz con un solo objeto el "http://www.wowhead.com/item=45886" es el mas importante aun que me dolería perder todo con que me recuperen solo ese objeto seria feliz

cuenta liz_granger
personaje Salydell

**Comment by salydell** [comment]
Aun nada sobre este tema al menos si no serán recuperado los objetos o algo seria bueno que lo respondieran D: 1 mes me parece suficiente como para que al menos lo leyeran D:  al menos una respuesta aun que sea  negativa, o un "por que" pasa eso con ese banco creo no soy la primera a la que le pasa

**Comment by aerz** [comment]
El error fue un pequeño rollback tras la caída que no te guardo correctamente el personaje y te provoco la perdida de items. Hemos revisado el NPC y tenía algunos fallos en comparación con el de la horda que funcionaba perfecto, todos ellos los hemos corregido y debería de funcionar sin fallos.

Te he añadido todos esos items en tu bolsa de personaje como pequeña compensación por el error.

Un saludo

**Comment by lamaza** [comment]
A mi se me desaparecieron como 5 - 8 items, No recuerdo el nombre de nada, no hay ninguna compensación? Mi pj es Lamaza , alianza pala 85.

**Comment by searum** [comment]
Aguantar!!! Los items no han desaparecido, estan TODOS guardados en la base de datos!!! Solo hay un pequeño bug visual que no aparecen... Pero están!!! En cuanto lo resolvamos tendréis vuestros items en el deposito PERO EVITAR USARLO DE MOMENTO!!!!

Creo que lo he fixeado, falta implementarlo para testear peroooo parece que ya está! :d

**Comment by Dekadencee** [comment]
Fixed
