### ISSUE TITLE
[misión Torneo Argenta] Toma Kraken

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#781]
Hay que matar al Kraken arrojando lanzas, pero al morir no cuenta para la misión. Los Kvaldir si cuenta en la misión al morir (6)

http://es.wowhead.com/quest=14108

El daño de la lanza esta bien, pero si lo atacas asi inicialmente, se vuelve a curar como el triple del daño que le haces en 1 seg o menos. Se le puede atacar manualmente al kraken, lanzarle luego lanzas, y se comporta "normal", sin curarse ni nada, pero no cuenta para la misión.

**Comment by redneo** [comment]
arreglada
