### ISSUE TITLE
[misión Torneo Argenta] El clamaneblina Yngvar

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#783]
http://es.wowhead.com/quest=14102

No se puede hacer, debido a que el jefe a matar no esta o no existen en su ubicación.

http://es.wowhead.com/npc=34965

**Comment by veyertrox** [comment]
hay que usar el objeto de misión que te proporcionan para invocarlo (Talismán del clamaneblina (http://es.wowhead.com/item=47009)) y después matarlo. La misión funciona. Creo que hace falta leer las descripciones de las misiones y objetos de misiones si o si, pues para algo son xD

**Comment by ghost** [comment]
Pues como dice veyertrox, @lamaza si justo a ti no te funciona la parte de usar el item, pues me avisas y lo reabro de nuevo :)

**Comment by lamaza** [comment]
PErdon, se me habia olvidado explicar, que ninguna de las 2 misiones que me cerraste funciona usando el item de invocacion, es por eso que las reporte. Los item sirven pero no sale ninguno de los 2 boss de la mision. Me los podrias abrir de nuevo por fa?

**Comment by veyertrox** [comment]
que extraño, a mi me funciono a la perfección, y me salió el npc. usaste el objeto en el lugar exacto?

**Comment by redneo** [comment]
Ya funciona
