### ISSUE TITLE
[Misiones] (Cementerio de Dragones) El fuego líquido de Elune

### ISSUE THREAD

**Issue by FullArrow** [RoDNet/Bugtracker-Infinium-4.3.4#785]
Ref Misión : http://es.wowhead.com/quest=12166/el-fuego-liquido-de-elune
1° los NPC 
Pardo rabioso:
http://es.wowhead.com/?npc=26643 No existen

2° Alce contagiado si existen pero al utilizar el Ítem de misión http://es.wowhead.com/item=36956 Fuego líquido de Elune sobre los cuerpos MUERTOS, no cuenta como limpiado. Supongo, que sobre los Pardo Rabioso ocurriría lo mismo.

Saludos.

**Comment by redneo** [comment]
los osos si que estan, en el mapa donde salen las letras de la mazmorra hay como 3 juntos. Ya tendria que funcionar el quemar los cadaveres.

**Comment by Kiritoo** [comment]
Funcionando.
