### ISSUE TITLE
[Spell]Levantar a muerto

### ISSUE THREAD

**Issue by hairblood** [RoDNet/Bugtracker-Infinium-4.3.4#786]
Dicha skill no se si solo pasa en profano,pero cuando lo invoco teine mana en vez de energia,haciendo imposible que use ataques propios
http://es.wowhead.com/spell=46584

**Comment by ghost** [comment]
En todo caso, lo que esta bug es el necrófago, no la spell.

**Comment by hairblood** [comment]
no se,yo la pongo por si acaso porque no puedo asegurar si es por ser profano,porque tal vez en escacha y sangre tienen energia 
¿alguien puede comprobarlo?

**Comment by ghost** [comment]
Comprobado en escarcha, si tiene energía, también en sangre tiene energía. 
![wowscrnshot_072413_151947](https://f.cloud.github.com/assets/4663665/851154/1dcb7f96-f496-11e2-8e8c-fba9a4b81a46.jpg)

Pero como te digo, es un problema de la pet no del spell, porque en sangre y escarcha es un "guardían"; en profano es un "esbirro", entonces cambia.

**Comment by hairblood** [comment]
ya veo,entonces por si acaso pongo la spell que podria ser el problema (osea el talento profano)
http://es.wowhead.com/spell=52143 este talento convierte el muerto "guardian" en muerto "esbirro" 
(mirado una vez mas hasta me salen ataques en gris,que ni salen en la lista...creo que es el esbirro de lich)

**Comment by hairblood** [comment]
posteo porque la pet ya tiene energia,pero a nivel 85 pega 80 y no usa las skilles propias

**Comment by ghost** [comment]
Pues mejor habre un nuevo reporte... y con detalles del problema que aquí ya juntaste muchos.

**Comment by searum** [comment]
abre un nuevo reporte porque este ya esta cerrado
