### ISSUE TITLE
[misión Torneo Argenta] Drottinn Hrothgar

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#787]
http://es.wowhead.com/quest=14101/drottinn-hrothgar

El Npc no esta , no existe no se le puede matar.

**Comment by veyertrox** [comment]
tienes que usar el objeto de misión que te proporcionan para invocarlo (Cuerno de guerra Kvaldir (http://es.wowhead.com/item=47006)) y después matarlo, no es por nada pero en la descripción de la misión dice clarito que hay que usar tal objeto

**Comment by ghost** [comment]
@veyertrox ¿entonces la misión funciona?

**Comment by veyertrox** [comment]
si, que no hayas hecho el procedimiento para hacerla y te hayas confundido es otra cosa xD

**Comment by ghost** [comment]
Bueno, solo preguntaba para cerrar el reporte, no soy el que esta haciendo la misión @veyertrox xd, así que lo cierro.

**Comment by lamaza** [comment]
El objeto de invocacion no sirve, no sale ningun bicho al usarlo, me lo abres por favor de nuevo¿?

**Comment by veyertrox** [comment]
que extraño, a mi me funciono a la perfección, y me salió el npc. usaste el objeto en el lugar exacto?

**Comment by redneo** [comment]
Al usarlo en la hoguera, te convoca al npc.
