### ISSUE TITLE
[Misión] (Corona de Hielo) Dentro del gran verdor

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#788]
Buenas.
La quest Dentro del gran verdor (http://es.wowhead.com/quest=13045/) no se puede completar porque no se puede usar ninguno de los 5 Garfacielos argenta que hay.
Gracias y hasta luego.

**Comment by Wiinter** [comment]
Si que te deja usarlos, pero ahora hay otra cosa bug. #2332

**Comment by ghost** [comment]
Cierro entonces
