### ISSUE TITLE
[misiónes Torneo Argenta] Bug de Muñecos de Entrenamiento

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#789]
Estas 3 misiones no se pueden completar ya que comparten el mismo bug:

Se deben lanzar las habilidades de "corcel" respectivas a los muñecos de entrenamiento de madera, pero estos no pueden ser /target de ninguna manera, es como un dibujo más en el mapa.

http://es.wowhead.com/quest=13828
http://es.wowhead.com/quest=13835
http://es.wowhead.com/quest=13837

Tambien aclaro, que estan bien las misiones en lo que respecta a hablar con los NPC necesarios. Además, es posible combatir en dicha montura y usar sus habilidades. Solo estan bug los muñecos, que prácticamente no existen.

**Comment by redneo** [comment]
Ya se les podria targetear, lo que no se si funcionaran las misiones (no me dejaba montar!!)

**Comment by lamaza** [comment]
Esta todo fix, se me habia pasado ponerlo. Gracias.
