### ISSUE TITLE
[Npc] Xariona y Aeonaxx

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#79]
Hola estes dos npcs salen como amistosos y estan mal posicionados.
Si os fijais en la imagen salen al salir del edificio central de infralar.

Xariona http://es.wowhead.com/npc=50061

Aeonaxx  http://es.wowhead.com/npc=51236

![wowscrnshot_070413_130834](https://f.cloud.github.com/assets/3537253/749168/9878cb54-e4a1-11e2-80be-8e35b6c73cee.jpg)

![wowscrnshot_070413_130839](https://f.cloud.github.com/assets/3537253/749169/9f2c3ea4-e4a1-11e2-93e6-69ae5c08220b.jpg)

EDITO\* tambien este npc:
Draco de piedra joven/  http://es.wowhead.com/npc=44038
El cual sale amistoso y con una vida insignificable, lo añado aqui para no abrir otro Issue.
![wowscrnshot_070413_131449](https://f.cloud.github.com/assets/3537253/749209/26850aba-e4a3-11e2-8dd2-10b789c79686.jpg)

Un saludo

**Comment by ghost** [comment]
Agrego algo más: 

Para obtener a Aeonaxx tiene su "método", no es simplemente ir y tirarle hechizos y matarlo xd, lo digo esto porque en la versión anterior estaba así, le tirabas hechizos como cualquier mob y lo matabas y tah-da ya tenías a Aeonaxx.

Aquí un video de como tiene que ser la batalla con Aeonaxx:
http://www.youtube.com/watch?v=5qcxTXFebsU

**Comment by crowel** [comment]
Cierro issue ya que ahora no estan posicionados donde antes de cambiar en la db.
Un saludo.
