### ISSUE TITLE
[ Hunter > Frenzy ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#790]
Frenesí: http://www.wowhead.com/spell=19623

Estos ataques deberían tener un 40% cada uno de activar Frenesí, sin embargo tienen 100% y hacen que puedas tener el efecto Frenesí TODO  el tiempo activo.

Mordedura: http://es.wowhead.com/spell=17253
Zarpa: http://es.wowhead.com/spell=16827
Bofetada: http://es.wowhead.com/spell=49966

A parte de que el daño de estas spells está realizando más daño del debido: Quick Link: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/373

**Comment by searum** [comment]
esto va con ataques basicos :S y va bien
