### ISSUE TITLE
[Hunter > Cobra Strikes] 

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#791]
Golpes de Cobra: http://es.wowhead.com/spell=53260

Cuando golpeas con Disparo Arcano tienes un 15% de probabilidad de provocar que los 2 próximos ataques básicos de tu mascota  asesten un golpe crítico.

Bug: Cuando el buff se activa tu pet empieza a realizar golpes críticos, hasta que el tiempo del buff se acabe, en vez de consumir las 2 acumulaciones del mismo.

( Cuando el bufo salta, lo hace con 2 acumulaciones, eso es así, cada stack hace que el siguiente ataque sea crítico ( Máximo stack: 2 ), el problema es que no se gastan )

**Comment by searum** [comment]
fix
