### ISSUE TITLE
[ Hunter > Glifo > Disparo de puntería ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#795]
Glifo de disparo de puntería: 
http://es.wowhead.com/item=4289

( En MoP este glifo desaparece aunque es la misma ID )

Cuando tu disparo de puntería asesta un golpe crítico restauras automáticamente 5p de enfoque.

Bug: si tienes el glifo puesto te restaura 5p. de enfoque TODOS los ataques incluso el ataque automático; cuando solo deberían ser estas 2 spells las que accionan el glifo

Aimed shot : http://es.wowhead.com/spell=19434
( Proc ) Aimed shot! : http://www.wowhead.com/spell=82928

Otros Gifos: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/298

**Comment by searum** [comment]
fix
