### ISSUE TITLE
Mob Que Deberia Dar Objeto de Mision

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#796]
El mob Gigante de hierro Tronaforjado http://es.wowhead.com/npc=29375/gigante-de-hierro-tronaforjado

Deberia dropear un objeto http://es.wowhead.com/item=41556 
que inicia una mision, 
OBJETO que no dropea

**Comment by DatJetto** [comment]
comentario de wowhead en inglés:

The Son's of Hodir reputation is gained through completing quest chain in K3, then you get another chain that sends you to Thorim (Son's of Hadir dude) and only when you are doing the quest for him the item drops from giants

La reputación con los Hijos de Hodir se basa en completar una cadena de quest desde K3, entonces Thorim te da otra cadena de quest secundaria, mientras realizas estas quest es cuando los mobs dropean este objeto.

**Comment by redneo** [comment]
Te dan el item si tienes la mision http://es.wowhead.com/quest=12915 cogida y no acabada.

**Comment by Kiritoo** [comment]
Esto funciona correctamente, cierro.
