### ISSUE TITLE
[Misión] La Garganta de Fuego: "Fuera de lugar"

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#797]
Buenas.
La misión Fuera de lugar (http://es.wowhead.com/quest=27961) no se puede completar porque no se pueden coger los Pollos de ceniza (http://es.wowhead.com/item=62934), en lugar de eso, dan un aura que se llama "Squirrel Scrubber Vehicle Aura (No Summon)"
Gracias y hasta luego

**Comment by redneo** [comment]
arreglado
