### ISSUE TITLE
[Paladin] Guardián de los antiguos reyes

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#798]
Este post tiene relacion con el #215 a diferencia que ese es en talentos sagrado y este es en talentos de reprensión http://es.wowhead.com/spell=86698

Lo que debería pasar es que cuando usas esta habilidad invoca un guardián que adquiere parte de tu daño y tu indice de golpe y golpea a tus enemigos. Actualmente pareciera como si esa habilidad no estuviera y solo es un botón que consume CD (tiempo de reutilizacion). 

1.) Al usarla no sale el guardián de los antiguos reyes http://es.wowhead.com/npc=46506#abilities.
2.) No te imbuye con poder antiguo. Lo que deberia aumentarte 1% la fuerza por cada carga que ganes al infligir golpes tu o el guardián.
3.) Como no hay poder antiguo, no se acumulan las cargas para llegar a los 20% de fuerza aumenta (lo que equivale a 20 cargas, lo máximo posible acumulable).
4.) Y como no se acumula, no libera por lo tanto Furia antigua, (en base a las cargas ganadas).

Tambien salen aqui algunas capturas #594.

**Comment by searum** [comment]
fix
