### ISSUE TITLE
[Paladin] Infusión de luz

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#799]
http://es.wowhead.com/spell=53576 este talento otorga el buff de http://es.wowhead.com/spell=54149 permitirte castear ciertas habilidades mas rápido "una sola vez". Actualmente cuando dicho buff se activa se puede castear esas habilidades (sanaciones), durante los 15 seg que dura el efecto, permitiéndonos hacer sanaciones instantaneas cada medio segundo durante esos 15 seg o hasta que nos quedemos sin mana.

**Comment by crowel** [comment]
Esto es un gran bug. Cualquier paladin durante esos 15 segundos puede estar lanzando destellos de luz instantaneos seguidos sin pararse cuando este buffo solo debe otorgarse al primer hechizo lanzado y a continuacion desaparecer y no como está ahora que hasta que se acabe disfrutas jaja.
![wowscrnshot_080713_194438](https://f.cloud.github.com/assets/3537253/926348/fd126d56-ff89-11e2-853b-c52ee59ebafe.jpg)
![wowscrnshot_080713_194439](https://f.cloud.github.com/assets/3537253/926349/fd16cff4-ff89-11e2-9f58-d5b171e060b9.jpg)
![wowscrnshot_080713_194440](https://f.cloud.github.com/assets/3537253/926350/fd1a4c42-ff89-11e2-9c64-f11bcb282c71.jpg)
![wowscrnshot_080713_194449](https://f.cloud.github.com/assets/3537253/926351/fd52984a-ff89-11e2-9401-e32deab65849.jpg)

Saludos.

**Comment by searum** [comment]
fix

**Comment by lamaza** [comment]
lo dejaste perfecto Sea!
