### ISSUE TITLE
Bug Sellos De Campeon

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#8]
Bueno, antes de la actualización tenia 5 sellos de campeón, luego de la actualización:

![wowscrnshot_070313_175607](https://f.cloud.github.com/assets/4895839/746656/daa9a35e-e433-11e2-90f5-1e1bc0893fad.jpg)

Se aumentaron increíblemente, tanto, que un amigo tiene 900 sellos.

**Comment by crowel** [comment]
Porfavor comprueben tambien las muestras de joyeria.

**Comment by ghost** [comment]
Me pasa lo mismo con los sellos y con las monedas de joyería.

Tampoco se me resetearon los puntos de honor, justicia, conquista y valor.. siguen todos iguales.
