### ISSUE TITLE
[Glifo]Socorro Oscuro

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#80]
Glifo de Socorro oscuro /  http://es.wowhead.com/item=68793
Tras matar a un enemigo que otorgue experiencia u honor, tu próximo Golpe letal en Presencia de escarcha o Presencia profana en 15 s no costará recursos y restaurará al menos un 20% de tu salud máxima.

*Problema: Se activa estando en presencia de sangre tambien, cosa que no deberia.
Pongo una imagen que aparece como se activa el cd del glifo pero al golpear en cualquiera de las auras no cura, solo se activa.

![wowscrnshot_070413_131041](https://f.cloud.github.com/assets/3537253/749200/c53f21c8-e4a2-11e2-8d15-c476e67a7267.jpg)

Un saludo.

**Comment by searum** [comment]
joder a ver si cuando reporteis un glifo me dais la id de la spell y no del item que el item no me sirve pa na!

**Comment by crowel** [comment]
96279

**Comment by Kiritoo** [comment]
Fix falta aplicarlo, ya no se activara en presencia de sangre.
