### ISSUE TITLE
[NPC] La Hermandad De Torio en el "Puesto de Torio"

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#800]
Buenas.
Hoy quería completar la quest Puesto del Torio: La sede de la hermandad (http://es.wowhead.com/quest=27965) y me doy cuenta de que faltan muchos PNJ en la zona Puesto de Torio de La Garganta de Fuego.
A saber, faltan:

Sobrestante Puñaceite (http://es.wowhead.com/npc=14625)
Hansel Manospesadas (http://es.wowhead.com/npc=14627)
Evonis Fumollín (http://es.wowhead.com/npc=14628)
Capitán de vigía Lolo Zancalarga (http://es.wowhead.com/npc=14634)
Capataz Scrange (http://es.wowhead.com/npc=14626)

Eso es todo, espero de no olvidarme de ninguno.
Gracias y hasta luego.

**Comment by redneo** [comment]
creo que ya se pueden ver todos si tienes la mision y si la has completado, me lo confirmas, por favor?

**Comment by ghost** [comment]
No, sigo sin verlos.
La misión no puedo completarla porque falta el Sobrestante.
Gracias.

**Comment by ghost** [comment]
Ya están, muchísimas gracias :D.
