### ISSUE TITLE
[Misión] Tierras Altas de Arathi: "Liberar a la princesa"

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#801]
Buenas.
La misión Liberar a la princesa (http://es.wowhead.com/quest=26049) no se puede completar porque el Pergamino de Myzrael (http://es.wowhead.com/item=4472) no funciona cerca de los fragmentos. Es para invocar y vencer a Myzrael (http://es.wowhead.com/npc=2755).
Gracias y hasta luego.

**Comment by redneo** [comment]
cuando caiga el server tendria que ir

**Comment by ghost** [comment]
Funciona de 10, muchas gracias.
