### ISSUE TITLE
[Pícaro] Golpes Despiadados

### ISSUE THREAD

**Issue by FullArrow** [RoDNet/Bugtracker-Infinium-4.3.4#802]
http://es.wowhead.com/spell=58423/golpes-despiadados
Golpes despiadados, Talento de la build Sutileza, en las dos primeras fases funciona correctamente pero en la tercera(con 3 puntos de talentos) Simplemente no dan los 25 p de energía extra ni con 5 puntos de combo de ningún remate.
Saludos.

**Comment by searum** [comment]
fix
