### ISSUE TITLE
[Pícaro] Burlar a la muerte

### ISSUE THREAD

**Issue by FullArrow** [RoDNet/Bugtracker-Infinium-4.3.4#803]
http://es.wowhead.com/spell=31230/burlar-a-la-muerte
Talento de la rama Sutileza, Al igual que golpes despiadados, cuando se le aplican 3 puntos de talento, se pierde el beneficio y No cumple la función de "Salvarnos de la muerte". Con 1 y 2 puntos de talento si funcionaba correctamente. 
Salu2

**Comment by searum** [comment]
fix
