### ISSUE TITLE
[portal] bug yendo a la Feria de la Luna Negra

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#804]
No se puede ir, el portal no sirve :/. Sale ese mensaje raro.

![wowscrnshot_072413_221806](https://f.cloud.github.com/assets/4790547/853390/cc076a78-f4d9-11e2-9472-affbc8e27673.jpg)
![wowscrnshot_072413_221940](https://f.cloud.github.com/assets/4790547/853391/cc1c32aa-f4d9-11e2-8442-e0be9efa5a53.jpg)

**Comment by hairblood** [comment]
porque no es aun la fecha:por norma ni siquiera deberias verlo fuera de fecha.Asi que espera a que llegue esa semana y pruebas de nuevo (aunque esta feria salio en la 4.3 por lo que no esperes mucho)

**Comment by lamaza** [comment]
El calendario pone que ha iniciado el evento. Pero bueno...

Investigando, encontré que según comentarios del oficial:
"Sabemos que está en el Mare Magnum, porque lo dice cuando vamos a la costa de la isla.
También podemos ver mirando al cielo que la isla siempre está cubierta de unas nubes de tormenta muy densas que curiosamente siempre parecen formar líneas casi rectas.

La isla debe estar por tanto en alguna parte de la Vorágine"

Asi que si no han "habilitado-activado" tal zona o isla del evento, es porque puede acercarnos a otras zonas cerradas, pienso yo...

**Comment by ghost** [comment]
Yo ya me fui a la isla de la luna negra y si funciona, además no sé de donde sacas que ya se activo en el calendario, la siguiente feria comienza el domingo 4 de agosto xd, prueba ir cuando este activado.

**Comment by ghost** [comment]
Bueno, como no has contestado @lamaza lo cierro... xd, ahora me avisas si no te funciono el portal el domingo 4 para abrir de nuevo el reporte.
