### ISSUE TITLE
[ Achievement > You'll Feel Right as Rain ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#806]
Te sentirás mejor que nunca: http://es.wowhead.com/achievement=5779

El logro está bug, al consumir 91 Perrunillas de chocolate seguidas y obtener 1000%  de felicidad el logro no se activa.

Perrunilla de chocolate: http://es.wowhead.com/item=62680
Satisfecho: http://es.wowhead.com/spell=87649 ( con 91 stacks el logro debería saltar )

**Comment by Wiinter** [comment]
#358  Añado esto, porque sin pepitas no se puede hacer este logro.

**Comment by DatJetto** [comment]
Creo que las pepitas de chocolate las puedes comprar individualmente en Cataclysm.

**Comment by Wiinter** [comment]
Segun tengo entendido solo se consiguen con la bolsa de suministros importados

**Comment by DatJetto** [comment]
A partir del parche 4.1.0 las pepitas SOLO se venden en la recompensa que has dicho, en 4.0.6 aún las vendían normales y por eso me he confundido.

Pero sí tienes razón.

**Comment by Wiinter** [comment]
Esta bien buscarlo para salir de dudas y que el reporte sea lo mejor posible.

**Comment by redneo** [comment]
las pepitas salen en http://es.wowhead.com/item=68689 y salen de 5 a 20 como dice wowhead, y wowpedia no dice nada más de la cantidad que salen

**Comment by DatJetto** [comment]
Por Conor891 (552 – 5) el 09/02/2011 (Parche 4.0.6)   Reportar  
Lots of Cocoa beans is right. I just bought two of bags of imported goods. The first one contained 40 cocoa beans and the second one contained 53
upvote
-5
downvote
10khanbroz el 03/04/2012 (Parche 4.3.3)
i bought 5 of these imported supplies and all of then contained 40 cocoa beans each and nothing else(i got very anoyed)
upvote
0
downvote
bizadin el 02/06/2013 (Parche 5.3.0)
Confirmed, seems they contain at least 40. Not 5-20 like the description says.

**Comment by Wiinter** [comment]
Las pepitas ya salen correctamente y te pone el buffo. Pero al logro le da igual el buffo que tengas.

**Comment by Wiinter** [comment]
Puedes Cerrar el Post, porque hoy mismo he conseguido el logro. Esta 100% funcional.
