### ISSUE TITLE
[ Hunter > T.N.T ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#807]
T.N.T 
http://es.wowhead.com/spell=56333

Cuando inflinges daño periódico con Trampa de inmolación, Trampa explosiva o Flecha negra tienes un 20% de probabilidad de activar Bloquear y Cargar.

Bug: Nada más lanzar alguna de estas 3 habilidades Bloquear y cargar se activa con 100% de probabilidad.

**Comment by Corialis** [comment]
Quizá habría que agregar que bloquear y cargar solo se activa una vez, cuando se dispara flecha negra. Luego (al menos en mi experiencia personal) bloquear y cargar no se vuelve a activar en toda la duración de la flecha negra.

**Comment by searum** [comment]
fix
