### ISSUE TITLE
[ Hunter > Black Arrow ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#809]
Flecha negra: 
http://es.wowhead.com/spell=3674

esta spell está haciendo aproximadamente la mitad del daño que debería:

El DrD marca unos 3,2k por tick y 6,7k críticos, pero sin embargo realiza 1,6k normales y 3,4 críticos

![wowscrnshot_072513_143303](https://f.cloud.github.com/assets/2728817/855540/f69688a2-f527-11e2-801a-aa8fa7bba4ec.jpg)

Fórmula: ( 0,133 \* RAP )
Multiplicador de la spell normal: 130%
Multiplicador de la spell crítica: 209%

**Comment by searum** [comment]
esto funciona perfectamente.

**Comment by redneo** [comment]
Segun leo no va correctamente, no lo he probado bien BIEN, pero hace daño cada 2 segundos durante 20 (10 ticks) de en mi caso con ap (17090 \* 0.133)+ 285,25 = mas o menos 2558 muy alejado de los 4205 que me dice el drd, mas alejado de los 1007 que hago realmente de media.

Ya te digo que lo tengo que calcular con un pj sin auras ni nada, cosa que me voy a poner a hacer ahora con un mago.
