### ISSUE TITLE
[ Hunter > Serpent Spread ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#810]
Propagación Serpentina:
http://www.wowhead.com/spell=87935

Los objetivos golpeados con tu multidisparo se ven afectados con picadura de serpiente  con una duración de 9 segundos.

Bug: Cuando lanzas multidisparo ningún objetivo alcanzado por multidisparo se ve afectado por Picadura de serpiente.

Multidisparo: http://www.wowhead.com/spell=2643
Picadura de serpiente: http://es.wowhead.com/spell=1978

**Comment by searum** [comment]
fix
