### ISSUE TITLE
[ Hunter > Sniper Training ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#811]
Instrucción de francotirador: 
http://es.wowhead.com/spell=53304

Aumenta pasivamente un 15% la probabilidad de golpe crítico de Disparo mortal.
Al permanecer quieto 6 sec, Disparo Firme y Disparo de Cobra obtienen 6% de daño aumentado.

Bug: No salta el bufo de daño. Revisar el aumento de crítico ( se suma el 15% a tu % Crítico Actual ).

Disparo mortal: http://es.wowhead.com/spell=53351
Disparo firme: http://es.wowhead.com/spell=56641
Disparo de cobra: http://es.wowhead.com/spell=77767

**Comment by searum** [comment]
fix pero confirmalo
