### ISSUE TITLE
[ Hunter > Camouflage V.2 ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#812]
Bueno, tras el gran avance con esta spell la cual ya casi está al 100% solo quiero añadir algunas auras y demás que le faltan a dicha spell para que esté perfecta.

Camoflaje: http://es.wowhead.com/spell=51753

Esta spell sigue desapareciendo y no debería hacerlo con las siguientes spells:
- Llamar a mascota 1: http://es.wowhead.com/spell=883
- Llamar a mascota 2:http://es.wowhead.com/spell=83242
- Llamar a mascota 3: http://es.wowhead.com/spell=83243
- Llamar a mascota 4: http://es.wowhead.com/spell=83244
- Llamar a mascota 5: http://es.wowhead.com/spell=83245
- Retirar a mascota: http://es.wowhead.com/spell=2641
- Fuego rápido: http://es.wowhead.com/spell=3045
- Recuperación rápida: http://es.wowhead.com/spell=53232
- Asustar bestia: http://es.wowhead.com/spell=1513
- Marca del cazador:  http://es.wowhead.com/spell=1130
- Revivir mascota: http://es.wowhead.com/spell=982

Cuando empezamos a castear: 
- Disparo firme: http://es.wowhead.com/spell=56641
- Disparo de cobra: http://es.wowhead.com/spell=77767
- Disparo de puntería: http://es.wowhead.com/spell=19434

---

Cuando la pet usa alguna de estas spells el camuflaje se elimina no debiendo irse:
- Rugido de valor: http://es.wowhead.com/spell=93435
- Aullido furioso: http://es.wowhead.com/spell=24604
- Intervenir: http://es.wowhead.com/spell=53476
- Rugido de sacrificio: http://es.wowhead.com/spell=53480
- Rugido de recuperación: http://es.wowhead.com/spell=53517
- Llamada de lo salvaje: http://es.wowhead.com/spell=53434

---

Cuando el cazador está bajo los efectos de camuflaje los mobs no deberían poder seleccionarte, sin embargo te atacan a la distancia normal de amenaza.

http://www.youtube.com/watch?v=IDVTNdj22Zk Aquí vemos cómo en camo pasa en las narices de los npc sin ocurrir nada. Minuto 1:50

---

Problema extraño:

Cuando lanzamos Fingir muerte el aura de camouflage no se va, pero sí el efecto, aunque podemos ponernos en sigilo.

![wowscrnshot_072513_153641](https://f.cloud.github.com/assets/2728817/855801/7fad0da8-f52f-11e2-8efa-73be80d7396c.jpg)
Tenemos el aura de camuflaje pero no estamos en invisible/transparente.
![wowscrnshot_072513_153649](https://f.cloud.github.com/assets/2728817/855802/83949abc-f52f-11e2-803f-cd56187db3a2.jpg)
Podemos ponernos en sigilo, pero no afecta.

---

Cuando un pícaro nos lanza Distracción en el área donde nos encontramos, el camuflaje se elimina, no debiendo ser así.

Distract: http://www.wowhead.com/spell=1725

**Comment by searum** [comment]
Pues en esas spells no dice nada de no romper el sigilo asi que... no se de donde lo sacas, dame la fuente de tu información ^^

**Comment by searum** [comment]
Ya he metido fix para lo del camuflaje con los mobs por ahi rulando que no te ataquen :D

**Comment by Sagittariu5** [comment]
Que gran trabajo Searum, muchas gracias y a ti Jetto por tus reportes :dart:

**Comment by DatJetto** [comment]
Llamar a mascota y retirar: http://www.youtube.com/watch?v=tDBQjFzdqd0 1:35

---

Castear Disparos mientras estás en camuflaje sin romperlo: http://www.youtube.com/watch?v=YkMR8PtPuj8 4:30

---

Comentario de wowhead:

Everything you would ever want to know about this ability:

-Works on you & your pet.
-Can't be used while in combat, but feigning to drop combat & then casting camo immediately works.
-While standing still, you are stealthed, meaning no one outside your party can see you until they're very close.
-While moving you are, well, camouflaged. People can see you but can't attack you with anything except melee attacks.
-Any damage taken by you, including AOE abilities like Flamestrike, Frost Nova, etc, breaks your camouflage.
-Your pet taking damage, but not you, does NOT break your camouflage.
-Laying traps, swapping aspects, using mend pet, reviving your pet, using pet abilities (not attacks), & eating food do NOT break camo.
-Sending your pet to attack breaks camo immediately, even before your pet engages.

Basically, this is an upgraded version of stealth with a 1-minute cooldown. In PvE, you can use it to get into position before the fight and start DPS as soon as the tank pulls. In PvP, you can use it to start off any fight any way you want. Because rogues & ferals can't use any openers on you, you no longer need to camp flare @ the start of an arena match; you can use the flare offensively to try and knock them out while you waltz over to the other team's healer, unable to be attacked until you open.

I think this is a really underrated ability. While it's not something you can use all the time, and it definitely doesn't make hunters a stealth class, you can still use it to get a unique advantage over other players. Plus it means you don't have to go night elf to be invisible, which is sweet, because night elves suck.

Edit:

AND OF COURSE, THE ANSWER TO THE QUESTION EVERYONE WAS WONDERING:

Casting Aimed Shot doesn't break camo.

Yeah, that means you can get off an aimed, use rapid fire, and start charging up your next one, all from stealth.

---

PARTES IMPORTANTES DEL COMENTARIO: 
- Your pet taking damage, but not you, does NOT break your camouflage.
- Laying traps, swapping aspects, using mend pet, reviving your pet, using pet abilities (not attacks), & eating food do NOT break camo. [ Comer si rompe camo desde 4.0.6 ]
- Yeah, that means you can get off an aimed, use rapid fire, and start charging up your next one, all from stealth.

---

Otro comentario de wowhead: 
- Also camouflage does not break while casting scare beast on a druid or beasts it breaks when the cast finnishes, unlike most of your other abillities/items that have a cast time.

**Comment by DatJetto** [comment]
Spells del cazador que no deben romper camuflaje:

Llamar a mascota 1: http://es.wowhead.com/spell=883
Llamar a mascota 2:http://es.wowhead.com/spell=83242
Llamar a mascota 3: http://es.wowhead.com/spell=83243
Llamar a mascota 4: http://es.wowhead.com/spell=83244
Llamar a mascota 5: http://es.wowhead.com/spell=83245
Retirar a mascota: http://es.wowhead.com/spell=2641
Fuego rápido: http://es.wowhead.com/spell=3045
Recuperación rápida: http://es.wowhead.com/spell=53232
Marca del cazador: http://es.wowhead.com/spell=1130
Revivir mascota: http://es.wowhead.com/spell=982

Spells que tu pet lanza que no deben romper camuflaje: 

Rugido de valor: http://es.wowhead.com/spell=93435
Aullido furioso: http://es.wowhead.com/spell=24604
Intervenir: http://es.wowhead.com/spell=53476
Rugido de sacrificio: http://es.wowhead.com/spell=53480
Rugido de recuperación: http://es.wowhead.com/spell=53517
Llamada de lo salvaje: http://es.wowhead.com/spell=53434

Castear: ( camuflaje se elimina al terminar el casteo )

Asustar bestia: http://es.wowhead.com/spell=1513
Disparo firme: http://es.wowhead.com/spell=56641
Disparo de cobra: http://es.wowhead.com/spell=77767
Disparo de puntería: http://es.wowhead.com/spell=19434

Camuflaje se disipa cuando HACES daño ( para el cazador y su mascota )
Camuflaje se disipa PARA LA MASCOTA  cuando le hacen daño a la mascota.
Camuflaje se disipa para él y su mascota cuando OS HACEN daño a ambos o al cazador.

**Comment by searum** [comment]
FIX!
