### ISSUE TITLE
[NPC]Piroguardia brasadivino

### ISSUE THREAD

**Issue by hairblood** [RoDNet/Bugtracker-Infinium-4.3.4#813]
http://es.wowhead.com/npc=9816

se hace su evento para liberarlo pero se suelta,no se puede targetear ni dañar.Ademas te cierra las puertas,impidiendo que puedas salir

**Comment by ghost** [comment]
Intenta usando el altar en la habitación que hay sin moverte durante 10 o 20 seg o hasta que los invocadores se vuelvan hostiles. Luego de vencerlos, no te acerques al medio hasta que aparezca el boss.

**Comment by hairblood** [comment]
vale si sirve,pero parece que si te acercas mientras crece se queda inmune
