### ISSUE TITLE
No hay NPC¡¡

### ISSUE THREAD

**Issue by GalfordxxxD** [RoDNet/Bugtracker-Infinium-4.3.4#814]
Un saludo a todos los del etaff estan haciendo un grana tarbajo .. se que la prioridad es arreglar las bgs y mazmorras pero soy un fan del leveleo ... em encontrado que faltan uno npc ps aqui unos que "he visto"

Cuenca de sholazar ---- en el pilar musgoluz
http://es.wowhead.com/npc=28107

Monte Hyjal----- Arbelada de Aessina
http://es.wowhead.com/npc=39858

Vashj´ir .......bosque kelpthar ---- Tumba del navegante 
http://es.wowhead.com/npc=36915

haaa y en Tenmplo de la tierra ..Infralar 
no dejo elnace por que faltas todos los npc 

Gracias por todo un saludo

**Comment by redneo** [comment]
En el templo de infralar, estan todos los npcs... si sigues la cadena de misiones
Con el monte hyjal, creo que pasa lo mismo, al menos ese npc que pones, si que está, en la situación de más al sur SEGURO

**Comment by GalfordxxxD** [comment]
mmmm gracias voy a mirar pero me puedes dar alguna nociticia del resto de Npc
muchas gracias por tu tiempo

**Comment by redneo** [comment]
De vashj'ir aun no he mirado nada, de zonas low... segun me las vais reportando

**Comment by GalfordxxxD** [comment]
tenia razon en infralar ya hat npc siguiendo la cedena de misiones 
gracias :D

**Comment by Kiritoo** [comment]
Cierro ya que muchos estan bien situados en las zonas que mencionas.
Si quieres que se reparen la proxima vez se más especifico.
