### ISSUE TITLE
[Mision] El milagro de Aessina

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#815]
La mison
http://es.wowhead.com/quest=25372/el-milagro-de-aessina

hay que entregarle el 
a la Archidruida Hamuul totem de runa http://es.wowhead.com/npc=5769/archidruida-hamuul-totem-de-runa
y completarl la mision pero el NPC no esta y le sale la ? a Matogarra
http://es.wowhead.com/npc=39928/matogarra

y no deja completar la mision ya que no da opcion

![wowscrnshot_072513_163950](https://f.cloud.github.com/assets/4893907/856259/009deb7c-f539-11e2-94c9-08d847059c8e.jpg)

![wowscrnshot_072513_163946](https://f.cloud.github.com/assets/4893907/856262/0ce62c28-f539-11e2-8482-fddeca597866.jpg)

![wowscrnshot_072513_164010](https://f.cloud.github.com/assets/4893907/856265/1810b50a-f539-11e2-8070-1a2dbc1044cc.jpg)

**Comment by DatJetto** [comment]
Yo me he encontrado con esta situación hace un poco y te voy a corregir en algunas cosas.

1 - La ? de Matogarra es por otra quest creo, ya que yo entregué el Milagro de Aessina ( hace 10 minutos ) y la ? sigue estando.

2 - Es cierto que falta el archidruida, pero en el poblado de abajo, ( en el santuario de malorne creo ) Donde debería haber otro npc de Matogarra para entregar la quest de invasión a las tierras de fuego, sí hay un archidruida y le puedes entregar la quest a ese.

**Comment by frustrix** [comment]
Correcto el npc esta en otro lado las coordenadas del npc son 27,2 / 62,6

gracias por la ayuda
