### ISSUE TITLE
[ Hunter > Mirrored Blades ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#816]
Hojas reflectantes: http://es.wowhead.com/spell=83495

Al ser atacado con un hechizo mientras estás en Disuasión, tienes un 100% de probabilidad de reflejarlo contra el atacante.

Bug: No refleja el hechizo, lo desvía como si no tuviera el talento.

http://es.wowhead.com/spell=19263

Post relacionado con disuasión: https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/291

**Comment by ghost** [comment]
Creo que esto ya está funcionando eh, a mi me han reflejado bastante en disuasión.

**Comment by Kiritoo** [comment]
Esto está funcionando bien a mi parecer. Cierro.
