### ISSUE TITLE
Problema con el portal de bastion de acherus de los dk.

### ISSUE THREAD

**Issue by Avenger3** [RoDNet/Bugtracker-Infinium-4.3.4#817]
ola buenas, estava jugando con mi dk y de golpe en el lvl 59 se a quedado bug el teleport de un piso a otro de bastion de acherus. Espero encuetren una solucion, gracias. 

un saludo.

**Comment by redneo** [comment]
dime nombre del pj, y sobre todo raza.

**Comment by Avenger3** [comment]
kratosx, raza elfo de sangre.

**Comment by efectokoleos** [comment]
fixed

**Comment by Avenger3** [comment]
sigo sin poder teleportarme en el bastion de ebano, aora me sale la ruedecita en gris para pulsar pero me dice que estoy demasiado lejos encuando estos encima del teleport.
