### ISSUE TITLE
[Raid] El ojo de la eternidad

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#819]
Al pasar a la tercera fase, cuando vas subido en el draco. No te deja usar ninguna habilidad del draco y además desaparece el suelo por lo tanto si te mata el draco te vas al vacío. Entonces tienes qe descartar la opcion de matar al dragon desde el suelo

P.D: Nos ha pasado varias veces qe al entrar nos hemos caido al vacío directamente

**Comment by redneo** [comment]
la id del draco sabrias decirla?

**Comment by Wiinter** [comment]
http://es.wowhead.com/npc=30161 aqui la tienes.

Lo siento por no ponerla antes, es qe no la encontraba -.-

**Comment by efectokoleos** [comment]
fixed
