### ISSUE TITLE
[Honor] Al devolver algo te da mas honor.

### ISSUE THREAD

**Issue by Huardruid** [RoDNet/Bugtracker-Infinium-4.3.4#82]
Cuando compras algo de honor y lo devuelves te da mas honor (aprx 200 mas) que lo que te ha costado, vamos una forma facil e infinita de hacer honor.

**Comment by ghost** [comment]
Confirmo el bug, honor infinito para todos! xd

**Comment by redneo** [comment]
Deshabilitados dos spells de beneficio de hermandad que daban mas honor hasta cuando se vende... ahora no dan honor de mas en otros aspectos :S
