### ISSUE TITLE
[Chaman]Escudo de relampagos

### ISSUE THREAD

**Issue by hairblood** [RoDNet/Bugtracker-Infinium-4.3.4#822]
http://www.wowhead.com/spell=324

al usarlo deberia darte 3 cargas y no sumar de 1 en 1
si te pegan,deberias perder una carga y hacer daño

**Comment by hairblood** [comment]
añado que usando 1 sola carga,hace daño y no se va hasta que te pegan unos 4 o 5 golpes....creo que esta como en mop

**Comment by searum** [comment]
fix
