### ISSUE TITLE
[Item] Huevo Misterioso

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#825]
El huevo misterioso (http://es.wowhead.com/item=39878) conseguido del intendente de los Oráculos de Cuenca de Sholazar nunca se abre. Lo compré hace una semana y me dice qe faltan 2 días pero así ya lleva tiempo.

**Comment by DatJetto** [comment]
Seguramente esté puesto en tiempo de juego, de manera que no se abrirá hasta que juegues los 3 días completos que te pide.

**Comment by Wiinter** [comment]
Pues ojalá lo arreglen pronto

**Comment by juaks** [comment]
Se puede mirar esto? Por favor, seguro que es como dice que estará mal puesto.
