### ISSUE TITLE
Objeto de mision bug

### ISSUE THREAD

**Issue by mccelobb** [RoDNet/Bugtracker-Infinium-4.3.4#826]
http://es.wowhead.com/item=58884 bug: aparecen muuuuchos de estos objetos en los alrededores.
![wowscrnshot_072513_033939](https://f.cloud.github.com/assets/3194580/857696/57e10b26-f557-11e2-8ea0-1b9c6f5f9616.jpg)
Mirad el minimapa

**Comment by redneo** [comment]
correcto, pero solo cuenta si estas cerca de los npcs que tienes que tirar el bufo, menos mal que desaparecen pronto.
