### ISSUE TITLE
[Mision] (Hyjal) Corazon negro de fuego

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#827]
La mision consiste en invocar con Rama carbonizada http://es.wowhead.com/item=53464  a Thol'Embaar y matarlo y que te de el Corazon negro de thol'embaar http://es.wowhead.com/item=53454

Thol'Embaar esta ya por la zona pero no se le puede matar

http://es.wowhead.com/quest=25428/corazon-negro-de-fuego

![wowscrnshot_072513_222225](https://f.cloud.github.com/assets/4893907/858474/4f774728-f568-11e2-922f-2e2d8a34a65a.jpg)

**Comment by redneo** [comment]
ups, creí que le deje que si se podia matar.

**Comment by ghost** [comment]
@redneo  No, no se puede matar aún. Además, no debería estar ahí, si no que debería invocarse con el objeto que nos dan (item=53464).
