### ISSUE TITLE
El crisol de matanza.

### ISSUE THREAD

**Issue by darkpriest85** [RoDNet/Bugtracker-Infinium-4.3.4#828]
http://es.wowhead.com/quest=27863
http://es.wowhead.com/quest=27864
http://es.wowhead.com/quest=27866
http://es.wowhead.com/quest=27867
http://es.wowhead.com/quest=27868

Cómo está funcionando: Tomas la misión de Gurgthock bajas al circulo de pelea, pero no aparece tu rival.

Como debería funcionar: Una vez tomas la misión hablando con Gurgthock bajas al circulo de pelea y combates al oponente, cuando le vences el entregas la misión a Wodin, el sirviente trol, vuelves a tomarla de Gurgthock y sigues combatiendo hasta vencerlos a todos.

**Comment by redneo** [comment]
fixed!

Me faltan los textos para que sea mas blizlike, pero que al menos se puede hacer.

No recomiendo ir uno solo a por ellos....
