### ISSUE TITLE
[Misión] Tundra Boreal: "El final de Saragosa"

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#829]
Buenas.
La misión El final de Saragosa (http://es.wowhead.com/quest=11957) está bug porque cuando se invoca a Saragosa, no aparece en su forma humana (http://es.wowhead.com/npc=26232) y no se puede completar.
Gracias y hasta luego.

**Comment by redneo** [comment]
fixed
