### ISSUE TITLE
[Campo de batalla]Problemas con las puertas

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#83]
Hola quiero informar con un problema con las puertas que salen antes de comenzar a bg.

Por ejemplo jugue una g grito gerra y estaba la puerta a la siguiente paso esto.

![wowscrnshot_070413_132639](https://f.cloud.github.com/assets/3537253/749223/cb1ed696-e4a3-11e2-8c0d-355661b3c3ea.jpg)

Como se ve no hay puerta, intente salir para ver si era invisible.

![wowscrnshot_070413_132643](https://f.cloud.github.com/assets/3537253/749226/0b60bdb4-e4a4-11e2-9035-c34d67f92724.jpg)

Y te teletransporta para dentro de nuevo.

![wowscrnshot_070413_132655](https://f.cloud.github.com/assets/3537253/749228/18160de8-e4a4-11e2-958a-7c6e2da051c4.jpg)

Esto mismo tambien paso en guilneas.
![wowscrnshot_070413_133325](https://f.cloud.github.com/assets/3537253/749229/2b38a494-e4a4-11e2-9cd5-8da16b3e8364.jpg)

Como se ve no hay puerta y si sales te manda para dentro hasta comenzar.

Un saludo.

**Comment by crowel** [comment]
Enlace otro caso reportado en las cumbres gemelas. https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/47

**Comment by Dekadencee** [comment]
Si, unimos issues, gracias por el reporte, lo seguimos desde el anterior #47
