### ISSUE TITLE
Bug Talento Chaman elemental

### ISSUE THREAD

**Issue by kirgar** [RoDNet/Bugtracker-Infinium-4.3.4#833]
Bug el Talento Trueno ensordecedor ID: 88764.
El talento funciona medio bien es decir cuando uso descargar de relampagos o cadena de relampagos recupero mana con el escudo de relampagos puesto pero no aumenta las cargas del escudo da igual cuantas descargas tire no aumenta las cargas del escudo de relampagos

**Comment by hairblood** [comment]
.....pues ayer postee este talento y hacia al reves:hacia cargas pero no daba mana ¿porque se borraron los bug's que postee del chaman ayer?....

**Comment by kirgar** [comment]
yo lo he probado hoy y hace eso da mana pero no aumenta las cargas

**Comment by searum** [comment]
Podriais contar las cosas tal y como son, tambien aplica mana sin tener ni 1 carga :) solo contamos lo que nos interesa...

Esta todo fix...
