### ISSUE TITLE
sigue el sendero de la luz

### ISSUE THREAD

**Issue by Avenger3** [RoDNet/Bugtracker-Infinium-4.3.4#836]
ola muy buenas, reporto aqui otro bug que hay en la mision del instructor de paladines en la isla caminante del sol. te pide que aprendas sello de rectitud y te la apliques y luego a uno de los muñecos de aprendizague le apliques sentencia y no me funciona ni una cosa ni la otra, los movimientos los tengo los dos pero no se cumple la mision. gracias.

nombre pj: Thoor. Raza elfo de sangre. lvl 4

**Comment by redneo** [comment]
Vale... en wowhead no me aparece dicha mision, dame mas datos, id (direccion de wowhead) del instructor de paladines, la mision...

**Comment by Avenger3** [comment]
http://es.wowhead.com/quest=10069   esta es la quest que digo, lo siento me e equivocado en el nombre xdxd

**Comment by Kiritoo** [comment]
Fix, falta aplicarlo.
