### ISSUE TITLE
Problema con el portal de bastion de acherus de los dk.

### ISSUE THREAD

**Issue by Avenger3** [RoDNet/Bugtracker-Infinium-4.3.4#837]
sigo sin poder teleportarme en el bastion de ebano, aora me sale la ruedecita en gris para pulsar pero me dice que estoy demasiado lejos encuando estos encima del teleport.

Gracias, un saludo.

**Comment by crowel** [comment]
Porfavor puedes añadir el nombre del hechizo y si id.
Un saludo.

**Comment by Avenger3** [comment]
es el portal que te canvia de piso en bastion de ebano. antes no me teleportava y lo comente aqui pero despues del fix que se a hecho sigo sin poder usarlo para poder bajar al piso de abajo y seguir con las quest.

**Comment by Avenger3** [comment]
me pone Doodad_Nox_portal_purple_bossroom17 y la ruedecita para activar el comando de accion y activar el portal pero no me teleporta al piso de abajo donde esta el alto señor mograine para coguer la quest y seguir con el dk.

**Comment by Dekadencee** [comment]
Teoricamente esto está fixeado, cerramos por ahora y si sigue bug lo reabrimos.

Un saludo ^^
