### ISSUE TITLE
[Misión] La Garganta de Fuego: "Rasha'krak"

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#838]
Buenas.
La misión "Rasha'krak" (http://es.wowhead.com/quest=28099) no se puede completar porque ninguno de los tantos PNJ Rasha'krak (http://es.wowhead.com/npc=47553) que hay deja el objeto de misión Brazales de vínculo de Rahsa'krak (http://es.wowhead.com/item=63028).
Gracias y hasta luego.

**Comment by redneo** [comment]
ya lo lotean
