### ISSUE TITLE
[Misión] La Garganta de Fuego: "Ministerio oscuro"

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#839]
Buenas.
La misión Ministerio oscuro (http://es.wowhead.com/quest=27979/) no se puede completar porque:
El PNJ Ministro Letherio (http://es.wowhead.com/npc=47310/) no deja el objeto Esferilla de Letherio (http://es.wowhead.com/item=62823)
El PNJ Ministro Kiyuubi (http://es.wowhead.com/npc=47309) no deja el objeto Esferilla de Kiyuubi (http://es.wowhead.com/item=62825).
El PNJ Ministro Finister (http://es.wowhead.com/npc=47311) no está.
Desde ya gracias y hasta luego.

**Comment by redneo** [comment]
ya lo lotean
