### ISSUE TITLE
[Cazador]Camuflaje

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#84]
Habilidad: Camuflaje / http://es.wowhead.com/spell=51753

Al utilizarla no ocurre nada.

![wowscrnshot_070413_133403](https://f.cloud.github.com/assets/3537253/749259/6637b386-e4a5-11e2-9e56-5098f96a89c9.jpg)

Un saludo.

**Comment by Dekadencee** [comment]
Fixed
