### ISSUE TITLE
[PNJ] La Garganta de Fuego: "Vapoherrero Hierro Negro"

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#840]
Buenas.
Quería reportar que ninguno de los PNJ Vapoherrero Hierro Negro (http://es.wowhead.com/npc=5840) que hay en Garganta de fuego se los puede atacar, dañar o seleccionar.
Gracias y hasta luego.

**Comment by redneo** [comment]
ya se les puede atacar.
