### ISSUE TITLE
Mision bug Ministerio oscuro

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#841]
http://es.wowhead.com/quest=27979/ministerio-oscuro
Lado: Ambos
Empieza: Hansel Manospesadas
Termina: Hansel Manospesadas
http://es.wowhead.com/npc=47309
http://es.wowhead.com/npc=47310
http://es.wowhead.com/npc=47311
Ninguno de los 3 ministros suelta la pieza correspondiente por lo que no se puede crear la tripeticina crepuscular 
http://es.wowhead.com/item=62828

**Comment by redneo** [comment]
ya tendrian que lootearlo
