### ISSUE TITLE
[Misión] La Garganta de Fuego: "Un nuevo amo... ¿pero quién?"

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#842]
Buenas.
La misión "Un nuevo amo... ¿pero quién?" (http://es.wowhead.com/quest=27963) no se puede completar porque el PNJ Gravius Limugre (http://es.wowhead.com/npc=47270) no deja el objeto "Memorando Hierro Negro" (http://es.wowhead.com/item=62807).
Gracias.

**Comment by redneo** [comment]
Ya tendria que soltarlo
