### ISSUE TITLE
[ Hunter > Aimed shot ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#843]
Gracias a Elmiriox por prestarse voluntario a realizar unas pruebas con Disparo de puntería y Disparo de quimera.

![wowscrnshot_072613_170052](https://f.cloud.github.com/assets/2728817/863301/abe00e2a-f606-11e2-91c3-1259149d9c85.jpg)

Hemos hecho que el pj se desnude al completo ( Los abalorios que lleva no otorgan ningún beneficio, solo poder de ataque al usarlos )

De manera que su armadura es 0p. - 0% - No reducción de daño posible.
Y su temple es 0p. - 0% - No reducción de daño posible.

Disparo de puntería
http://es.wowhead.com/spell=19434

¡Disparo de puntería! ( Master Marksman )
http://www.wowhead.com/spell=82928

Fórmula: ( 160% daño con arma a distancia + (RAP*0.924) )

![wowscrnshot_072613_170106](https://f.cloud.github.com/assets/2728817/863317/07e2cb72-f607-11e2-952d-03e822e10bb4.jpg)

Lanzamos disparo de puntería sobre el pj desnudo, observamos el daño que nos marca, media de 20k  NORMAL y 42K CRÍTICA. 

Nos damos cuenta que de crítico realiza 20k ( es decir, el daño está aproximadamente al 50% del que debería )

**Comment by Hellythium** [comment]
Tienes razón Gromelger, disparo de punteria esta pegando demasiadamente bajo de acuerdo a su daño normal, puesto a que en mi descripción de spell dice que pega 160% de daño mas 8ks sin ningún abalorio o habilidad de aumento de agilidad activado, y solo estoy metiendo 6ks normal cuanto mucho llego a los 7ks y 13ks de critico en objetivos normales (con armadura, etc), gracias por reportarlo y espero que lo reparen pronto.

Saludos, Darkstar.

**Comment by DatJetto** [comment]
Si estuviera bien el disparo, con marca del cazador aplicada en el objetivo, hubiera muerto de Disparo de puntería.

**Comment by searum** [comment]
a mi me da que pega como debe.
