### ISSUE TITLE
[ Hunter > Chimera shot ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#844]
Disparo de quimera
http://es.wowhead.com/spell=53209

Fórmula: 100% Daño con arma a distancia + (RAP*0.932)

Seguimos con nuestro amigo Elmiriox, esta vez le hemos dicho que se vista, ya que Disparo de Quimera realiza daño de naturaleza, de manera que ignora la armadura.

Este pj NO tiene en esta prueba ninguna pieza de temple Y O bonificación que reduzca el daño de alguna escuela mágica.

Temple 0p. - 0% - No posibilidad de reducción.
Resistencia a la naturaleza 0p. - 0% - No posibilidad de reducción.

![wowscrnshot_072613_170331](https://f.cloud.github.com/assets/2728817/863357/ec5fdc4a-f607-11e2-92e9-0bb41a7c7ee0.jpg)

Nos marca un daño parecido al de Disparo de Puntería, media de 21k NORMAL, 43k CRÍTICO.

Realizamos un tiro no crítico y obtenemos como daño 13.731p. 

Provocamos que nuestro abalorio de agilidad reaccione para obtener un poder de ataque de 20k, lo cual hace que el daño escale hacia 22k de daño normal y 46k de crítico.

Lo que nos encontramos es un aumento de 13,7k hacia 15,3k
![wowscrnshot_072613_170352](https://f.cloud.github.com/assets/2728817/863381/6483a42c-f608-11e2-9ea5-732ada56a996.jpg)

**Comment by ghost** [comment]
Yo no entiendo, el caza ya esta pegando muy fuerte, y según todos tus reportes, debe de pegar todavía más xd.

**Comment by DatJetto** [comment]
El puntería no, tiene sus 2 mejores spells bugs Chimera y Aimed, el supervivencia y el bestias si pegan bien, más o menos.

**Comment by searum** [comment]
fix
