### ISSUE TITLE
[Tabardos] Tabardo de Ramkahen (posiblemente otros tabardos también)

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#845]
Tabardo: http://es.wowhead.com/item=65904

Bug: Lo tenía puesto en Karazhan(Banda de nivel 70) y me daba reputación, solo debería dar la reputación en mazmorras de nivel 85 (heróicas) como El Núcleo Petreo, Cámaras de los Orígenes, etc.

**Comment by DatJetto** [comment]
Corrijo: Mazmorras de nivel 85, normal o heroica da igual, ya que hay mazmorras normales de lvl 85.

**Comment by Velcositro** [comment]
Tengo entendido que las mazmorras que solo tienen modo para nivel 85 están clasificadas como heróicas, no como normales y las bandas no deberían dar reputación con tabardos.

**Comment by DatJetto** [comment]
Por Xpace (768 – 1·10) el 19/12/2010 (Parche 4.0.3)  Reportar  
This tabard requires you to be friendly with the Ramkahen to purchase. Blacksmith Abasi, the Ramkahen quartermaster which sells this tabard as well as all reputation rewards is located in Ramkahen in Uldum. 

Applicable to: 

Blackrock Caverns (heroic)
Throne of the Tides (heroic)
The Stonecore (heroic)
Vortex Pinnacle (heroic)
Lost City of Tol'vir (normal/heroic)
Halls of Origination (normal/heroic)
Grim Batol (normal/heroic)
Shadowfang Keep (heroic)
The Deadmines (heroic)

Las raid, si, he mirado y cada raid tiene una reputación concreta, que no sube con tabardo.
Es decir, si la reputación de X raid es Guardianes de Hyjal por poner un ejemplo, y llevas tabardo de Ramkahen, te subirá con Guardianes de Hyjal.
