### ISSUE TITLE
[Mazmorra] Prueba del Campeón

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#846]
Mazmorra: http://es.wowhead.com/zone=4723

Bugs: 

*Se puede hablar con Jaeren Jurasol (http://es.wowhead.com/npc=35004) para que inicie la mazmorra directamente, y debería permitirlo solo al tener una Lanza Argenta (http://es.wowhead.com/item=46106) y estar en la montura correspondiente (Horda: http://es.wowhead.com/npc=36558, Alianza: http://es.wowhead.com/npc=36557).

*Las monturas ya mencionadas no tienen las habilidades puestas.

*La 1º fase no funciona correctamente, a mi con un Pj Horda me salen 3 campeones de la Horda que se quedan como amistosos y no hacen nada, lo raro es que cada uno está en una montura de la alianza, osea, sale por ejemplo el Campeón Orco montado en un caballo de Humano.

Adjunto esta guía donde pone todo lo que pasa con links a Wowhead de cada npc: http://www.guiaswow.com/prueba-del-campeon/guia-la-prueba-del-campeon.html

**Comment by efectokoleos** [comment]
la isntance necesita una reescritura entera en el script me pondre cuando pueda
