### ISSUE TITLE
[Profesión]Componer

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#85]
Hola algunas creaciones de ingenieria de componer no funcionan.

*Base de tejido flexible / http://es.wowhead.com/spell=55002
*Propulsiones de nitro /  http://es.wowhead.com/spell=55016

![wowscrnshot_070413_133430](https://f.cloud.github.com/assets/3537253/749273/4e11fa22-e4a6-11e2-8f4d-2ab0589180cf.jpg)
![wowscrnshot_070413_133445](https://f.cloud.github.com/assets/3537253/749275/57f1f646-e4a6-11e2-9741-a627b3545e73.jpg)

Como se puede ver en la imagen, en la barra de habilidades salen los dos iconos brillando como si estuvieran dandole click, los cuales no se pueden utilizar, no ocurre nada al darle ni en el gestor de equipamiento.

Un saludo.

**Comment by crowel** [comment]
Siento que se actualizaran estos Issues, pero es que estube haciendo limpieza para no tener los que ya estan reparados tras el cambio de Db y priorizar lo que realmente se necesite.
Añadan Laber porfavor.
Gracias.

**Comment by Mhryel** [comment]
Estos items ya están funcionales.
