### ISSUE TITLE
[PNJ] La Garganta de Fuego: "Ministro Finister"

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#850]
Buenas.
Quería reportar que el PNJ Ministro Finister (http://es.wowhead.com/npc=47311), en La Garganta de Fuego, no está.
Ya busqué en la caverna cerca de los otros 2 ministros, pero nada. Según el wowhead, debería estar en la cima de Cresta Vigía, justo donde está el círculo de invocación.
Gracias y hasta luego.

**Comment by Kiritoo** [comment]
Este npc si que está en su posición exacta, sobre la cueva.
![wowscrnshot_082013_155754](https://f.cloud.github.com/assets/5061022/993759/94930dfa-09a0-11e3-8260-33359537812d.jpg)

Saludos.
