### ISSUE TITLE
[ Druid > Swiftmend ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#852]
Alivio presto
http://es.wowhead.com/spell=18562

Fórmula: ( 0.986 \* SP )
Esta spell está sanando de más, de sanar 13k pasa a 21k. ( no crítico )

![wowscrnshot_072613_193828](https://f.cloud.github.com/assets/2728817/864339/72596f16-f61f-11e2-8897-e5eb5b0654dc.jpg)

**Comment by searum** [comment]
esto funciona como debe... fijate en mas talentos que te puedan subir y dejate ya el jodido addon ese...
