### ISSUE TITLE
[ Druid > Ferocious Bite ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#853]
Mordedura Feroz
http://es.wowhead.com/spell=22568

Esta spell está haciendo un daño exagerado, mi druida equipado heler, con 496 de AP con 5 puntos de combo da 12,6k sin crítico 

![wowscrnshot_072613_195455](https://f.cloud.github.com/assets/2728817/864365/d83ef666-f61f-11e2-9031-44fbbe9d6543.jpg)

![wowscrnshot_072613_202551](https://f.cloud.github.com/assets/2728817/864421/fa4ce88e-f620-11e2-8118-05d42cabc006.jpg)

Fórmula: ( 0.545 \* AP ) 5 Combo Points
( 0.436 \* AP ) 4 CP
( 0.327 \* AP ) 3 CP
( 0.218 \* AP ) 2 CP
( 0.109 \* AP ) 1 CP

**Comment by searum** [comment]
fix
