### ISSUE TITLE
[ Druid > Starsurge ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#854]
Oleada de estrellas: 
http://es.wowhead.com/spell=78674

Esta spell está haciendo un daño aproximado al 60% de lo que debería.
De una media de 11k pasa a 6k 

Fórmula: ( 1,228 \* SP )

**Comment by searum** [comment]
y dale con el drdamage ese colega... ademas esto esta fix
