### ISSUE TITLE
Bugs Paladin

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.3.4#86]
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1495 perdonad me habia equivocado de bugtracker XD

**Comment by crowel** [comment]
Añado hechizos del paladín:

*Destello de luz: http://es.wowhead.com/spell=19750 Está bastante bien, cura un poquito más de lo que debe.
*Luz Sagrada: http://es.wowhead.com/spell=635  Está demasiado subida, cura el doble.
*Luz divina: http://es.wowhead.com/spell=82326  Está un poco subida, cura alrededor de 3k de la media.
*Radiancia Sagrada: http://es.wowhead.com/spell=82327 Cura de más, tanto su cura principal como los ticks, un gran problema de su habilidad es curar cada 0,96 durante 2,88segundos los ticks, y los cura de golpe(cuando los cura, no siempre salen)

**Comment by crowel** [comment]
Quiero añadir a tu reporte Drogoth que mi martillo de colera si que golpea, el daño dentro de la media.

**Comment by crowel** [comment]
*Consagración: http://es.wowhead.com/spell=26573 Estan haciendo sus ticks un poco más del daño que deberia.
*Cólera Sagrada: http://es.wowhead.com/spell=119072 Está haciendo menos de la mitad del daño que deberia.

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/71
Junten post en este primero.
el 71.

**Comment by ghost** [comment]
Si pueden poner cada bug, en un reporte a parte, gracias.
