### ISSUE TITLE
[DK] Atracción letal

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#862]
Ola k ase

http://imageshack.us/f/585/ldjw.jpg/

Por lo visto no tiene CD la habilidad. Al principio el DK empezó lanzando uno y, cuando huía me lanzaba el siguiente...hasta ahí dudé porque supuse q sería un talento o algo qe puntualmente se lo permitía...luego empezó a hacerlo 3 veces seguidas haciendome  casi imposible escapar y castear... Y finalmente llegó lo de la imagen, mi pj volando por unos 10 segundos y el lanzandome sin parar la habilidad, tanto a mi como a mi compañero, el cual estuvo un rato más volando que yo, unos 15 segundos.

El combat log sigue, se pueden hacer 3 fotos más si sigo bajando xD

**Comment by lamaza** [comment]
Dijo Searum que ya esta solucionado =)

**Comment by searum** [comment]
fix
