### ISSUE TITLE
[Mision][DK] La batalla por El Bastión de Ébano

### ISSUE THREAD

**Issue by hjagar** [RoDNet/Bugtracker-Infinium-4.3.4#868]
En esta misión que se toma en el primer piso, se debe transportar al segundo piso a matar unos npc.Sin embargo el transportador no funciona.

http://es.wowhead.com/quest=13166

**Comment by efectokoleos** [comment]
esta puesta autocompletable hasta que la arreglemos

**Comment by hjagar** [comment]
Si bien esta para autocompletarse al salir del bastion con rumbo a Orgrimmar en la ciudad no veo a nadie parece que sigo desfasado como si aun estuviera en la zona inicial del DK, mi personaje es Feranor, podrián arreglarlo, por favor. Desde ya muchas gracias

**Comment by Kiritoo** [comment]
Esto funciona.
