### ISSUE TITLE
Misión "Robocarnicero"

### ISSUE THREAD

**Issue by Sheilina** [RoDNet/Bugtracker-Infinium-4.3.4#869]
El npc da como normalmente el objeto para utilizar una vez muerto y despojado el basilisco, pero tras usarlo el resultado es el mismo que no usarlo, no contabiliza y no se puede avanzar en la quest.
http://es.wowhead.com/quest=25112/robocarnicero

Saludos

**Comment by DatJetto** [comment]
Objeto proveído: http://es.wowhead.com/item=52715 Control de robocarnicero.
Spell: Desplegar Robocarnicero: http://es.wowhead.com/spell=74175

**Comment by Sheilina** [comment]
Jjaj ;)

**Comment by redneo** [comment]
tendria que ir cuando caiga el server
