### ISSUE TITLE
[Campo de batalla]La Batalla por Gilneas

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.3.4#87]
Hola quisiera exponer unos fallos en la bg de La Batalla por Gilneas http://es.wowhead.com/zone=5449/

*Banderas: No hay ninguna asi que no se pueden capturar las bases.

![wowscrnshot_070413_133543](https://f.cloud.github.com/assets/3537253/749295/2de24c10-e4a7-11e2-8851-aadd9ca833ed.jpg)

![wowscrnshot_070413_133620](https://f.cloud.github.com/assets/3537253/749296/3cff2074-e4a7-11e2-95c7-f5cb304065a6.jpg)

*Recursos restantes: Como se puede ver en la parte de arriba aunque no hay banderas los recursos restantes aparecen como 0/0 teniendo que aparecer 0/2000 al comenzar.

![wowscrnshot_070413_133632](https://f.cloud.github.com/assets/3537253/749298/60afca8c-e4a7-11e2-9a4d-e892a7bc901a.jpg)

Espero que si alguien encuentra algun fallo mas enlace aqui o lo reporte.

Un saludo.

**Comment by crowel** [comment]
Ups otro gran fallo que me olvide de comentar.

Aqui se me ve recien muerto, tras matarme la alianza.
![wowscrnshot_070413_134431](https://f.cloud.github.com/assets/3537253/749306/c7ab1a52-e4a7-11e2-8e07-aed51c02a62b.jpg)

Aqui en esta otra se ve como ellos tras quitarme la insinia, desaparece mi cuerpo.
![wowscrnshot_070413_134451](https://f.cloud.github.com/assets/3537253/749307/defbfeb0-e4a7-11e2-9815-c15b19cccd19.jpg)

Problema: El gran problema es que ellos tras quitarme la insignia debo aparecer en el cementerio, y no en el punto donde ellos me liberaron.
Este es un gran fallo puesto que al quitarme la insignia, desaparece mi cuerpo, quitandome la posibilidad de revivir al no mandarme al cementerio.

Un saludo.

**Comment by F4NT4SM4** [comment]
tambien cuando empieza la bg no esta la puerta y podemos salir antes de tiempo

**Comment by crowel** [comment]
Porfavor añadirle el label a este reporte que quedo un poquito atras sin clasificar, un saludo.
