### ISSUE TITLE
[Paladín] Acusar

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#871]
Este talento funciona bien en condiciones normales pero al morir o estar conectado cierto tiempo deja de funcionar. Me toca relogear para que se vuelva activar y si muero en BG ya no me sirve...  

![wowscrnshot_072613_223219](https://f.cloud.github.com/assets/4944904/866329/9c38e214-f668-11e2-92c8-06bc86e9c72b.jpg)

Esta foto fue cuando sali de la BG habia muerto y si ven el coste de mana de exorsismo esta en mas de (7k)
![wowscrnshot_072613_221328](https://f.cloud.github.com/assets/4944904/866324/280fa7ec-f668-11e2-9b8f-58d7f38b8175.jpg)

Aqui Acabo de relogear para que pueda activarse el talento de nuevo. A hora si funciona correctamente, me es menos costoso usar exorcismo, (1.7k).
![wowscrnshot_072613_221419](https://f.cloud.github.com/assets/4944904/866326/36e3a642-f668-11e2-8004-6512bb72a5a3.jpg)

Como pueden ver el talento si funciona, pero si llego a morir o estoy conectado por mas de 10-15 min, hasta ahí llega su efecto. Aparentemente esta es la ID  spell=85510, aunque en wowhead parece que lo quitaron y lo remplazaron por otra habilidad con el mismo nombre.

Nota: Tambien pierdo la bonificacion del talento al cabo de unos minutos conectado. Hize 2 duelos y cuando fui a revisar porque me quede sin mana... Tenia otra vez el talento bugiado y se estaba chupando toda mi mana.

**Comment by searum** [comment]
fix
