### ISSUE TITLE
[Misión][Tierras de Peste del Oeste] El flujo incesante (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#872]
Buenas.
La misión El flujo incesante (http://es.wowhead.com/quest=27161) no se puede completar porque los PNJ Rabioso Pegahueso no están (http://es.wowhead.com/npc=44329) y porque las Granadas de mano de Lang no funcionan en los Animus de hueso de la Plaga.
Gracias y un saludo.

**Comment by redneo** [comment]
los rabiosos estaban en otra fase... he movido alguno a la fase 1

ANumus de hueso de la plaga.... cual es su id que no aparece por ningun lado!!!¿?¿?¿?

**Comment by ghost** [comment]
No lo pude encontrar, pero sé que son las pilas de huesos que hay en el medio de las torres
![wowscrnshot_072713_121146](https://f.cloud.github.com/assets/4582987/867105/85e1f630-f6d2-11e2-8ce8-f2c53b922bec.jpg)

**Comment by redneo** [comment]
arreglada, pero no se si has de morir por narices al lanzar la granada...
