### ISSUE TITLE
[PNJ][Tierras de Peste del Oeste] Capitán de guerra Guardia de la Muerte

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#873]
Buenas.
Los PNJ Capitán de guerra Guardia de la Muerte no están (http://es.wowhead.com/npc=44449) por lo que no se puede completar la misión Cenizas a las cenizas (http://es.wowhead.com/quest=27199).
Gracias y hasta luego.

**Comment by Anhna** [comment]
Colocado

**Comment by ghost** [comment]
Gracias!
Si pudieran, por favor, agregar 2 mas para no tener que esperar cada vez que se lo mata y completar la quest de una sola vez me harian la persona mas feliz.
Hasta luego y gracias de nuevo!

**Comment by Kiritoo** [comment]
Fix, falta aplicarlo.
