### ISSUE TITLE
[Misión][Tierras de la Peste del Oeste] Ya sé que lo tuyo no es cavar

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#874]
Buenas.
La misión Ya sé que lo tuyo no es cavar (http://es.wowhead.com/quest=26956) no se puede completar porque al coger el maíz malo del piso, el PNJ Acechador del maíz (http://es.wowhead.com/npc=44489) no aparece correctamente (aparecen dos maices flotando que no hacen nada).
Gracias y saludos.

**Comment by redneo** [comment]
arreglado!
