### ISSUE TITLE
[Huargen] Misión "El arsenal del Señor rebelde"

### ISSUE THREAD

**Issue by Eressear** [RoDNet/Bugtracker-Infinium-4.3.4#878]
No estoy seguro de si es esta misión (http://es.wowhead.com/quest=14159). Se supone que t metes en un sótano, hablas con  Josiah Avery (http://es.wowhead.com/npc=35369/josiah-avery) este se transforma y te muerde; pero al transformarse no ataca: se queda parado, hasta desaparecer. Te deja atascado en medio de la cadena de misiones.

**Comment by crowel** [comment]
Mmm debo decir que yo si la pude hacer bien.
Una vez se transforma, cambia la fase pudiendo entregar la continuacion en la chica de la escalera.
Un saludo.

**Comment by searum** [comment]
fix! por fin
