### ISSUE TITLE
[Mazmorra] Murallas de Fuego Infernal

### ISSUE THREAD

**Issue by Eressear** [RoDNet/Bugtracker-Infinium-4.3.4#881]
A Vazruden el Heraldo (http://es.wowhead.com/npc=17307) en murallas d fuego infernal no se le puede matar.

**Comment by DatJetto** [comment]
Tienes que matar primero al dragón, y después al jinete, el evento funciona de manera rara.
Igualmente estaría bien que lo dejaran blizz.

**Comment by efectokoleos** [comment]
mientras se pueda matar bien no sera uan prioridad arreglarlo, igualmente en cuanto tenga algo de tiempo lo miraré^^

**Comment by juaks** [comment]
No está bug, funciona perfectamente, tienes que atacar primero al dragón, se pone a volar, matas al jinete y el dragón baja y le puedes matar.
