### ISSUE TITLE
Bug en Misiones Bosque del Ocaso

### ISSUE THREAD

**Issue by Honme** [RoDNet/Bugtracker-Infinium-4.3.4#882]
Quiero reportar sobre dos Misiones de la zona Bosque del Ocaso que están Bug's las misiones son las siguientes:
La Venganza de Mantoniebla
La Venganza del Embalsamador

Bug Venganza de Mantoniebla:
Cuando uno llega a la Mansión Mantoniebla tiene que utilizar el anillo de la familia Mantoniebla pero cuando llegas a la Mansión y intentas activar el anillo dice ''Requiere Mansión Mantoniebla'' y no se activa para que salga Stalvan Mantoniebla.

Bug Venganza del Embalsamador:
Uno acepta la misión y tendría que aparecer la criatura creada por el Embalsamador que es una abominación de Nombre ''Puntos'' tendría que aparecer en el Centro de Villa Oscura pero no aparece por ninguna parte.

Les pido por favor que intenten arreglar esos Bug's lo antes posible para poder acabar la cadena de misiones de Bosque del Ocaso.

Gracias por su tiempo.

**Comment by DatJetto** [comment]
- http://es.wowhead.com/quest=26727 La venganza de Embalsamador.
  Puntos : http://es.wowhead.com/npc=43862
- http://es.wowhead.com/quest=26674 La venganza de Mantoniebla.
  Stalvan Mantoniebla: http://es.wowhead.com/npc=315

A ver si añadimos Id's por favor :3

**Comment by redneo** [comment]
ambas dos arregladas, lo mas probable es que tengas que dejar ambas misiones y volver a cogerlas
