### ISSUE TITLE
[ Bug: Cast Interrupt ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#883]
Cuando un cazador está lanzando:

Disparo firme: http://es.wowhead.com/spell=56641
Disparo de cobra: http://es.wowhead.com/spell=77767
Disparo de puntería: http://es.wowhead.com/spell=19434

Ocurre que si nos golpea un ataque cuerpo a cuerpo este casteo se corta no debiendo ser así, es decir, yo tengo como Target a un Mago ( por ejemplo ) y estoy lanzando disparo de puntería, de pronto un warrior me hace un ataque ( que no implique Stun, es decir, automático, golpe heroico etc. ) y en vez de añadir un cierto delay al disparo 0,2 sec o algo así, directamente el disparo se corta/cancela.

Esto limita mucho la recuperación de enfoque del cazador si tu oponente es cuerpo a cuerpo o directamente te estás peleando con algún cuerpo a cuerpo en bg o arena.

**Comment by ghost** [comment]
Esto también le sucede a mi sacerdote, aunque no sé si de la misma forma que Jetto lo menciona, pero se me cancela "gratuitamente" el casteo algunas veces.

**Comment by Moyax** [comment]
Tambien le pasa al pala cuando quiere curarse y no tiene puesta el aura de concentracion =P

**Comment by ghost** [comment]
Es un problema de casteos en general, a todas las clases les pasa a veces.

**Comment by searum** [comment]
fix al menos en el hunter

**Comment by Wiinter** [comment]
Al brujo no le pasa, almenos a mi no, de momento
