### ISSUE TITLE
[ Bug: Vendas de Primeros auxilios ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#884]
Cuando usas una venda, debe de ponerte el debuff de Vendaje reciente ( http://es.wowhead.com/spell=11196 ) para que no puedas spamear la venda, pero esto no ocurre, almenos en las vendas de seda de ascuas densa.

Todas estas vendas deben de aplicar Vendaje reciente:
http://es.wowhead.com/items=0.7

**Comment by redneo** [comment]
arreglado
