### ISSUE TITLE
Bug en cumbre rocanegra (Instance)

### ISSUE THREAD

**Issue by Huarxx** [RoDNet/Bugtracker-Infinium-4.3.4#885]
Al intentar conseguir el logro "¡Leeeeeeroy!", el cual da paso al título jenkins, entro en la instance montaña rocanegra, mato a los moob para que se abran las puertas, las cuales antes estaban bug pero ya repararon y les agradezco.
Al abrirse la ultima puerta para el logro, la de la sala de los grajeros, en la que se encuentran decenas de huevos de cría de grajero, que son los que hay que matar para sacar el logro, al pisar dichos huevos, estos desaparecen pero no aparece ningún moob o cría de grajero.
Si pudieran hacer algo les agradecería.
Un cálido saludo y gracias.

**Comment by ghost** [comment]
Ya esta reportado #701 lo cierro para que lo continuen ahí :)
