### ISSUE TITLE
Bug Misión "Aprender nuevas técnicas"

### ISSUE THREAD

**Issue by xXkandyXx** [RoDNet/Bugtracker-Infinium-4.3.4#886]
He visto que la misión de la instructora de los guerreros Alyissia en la que hay que aprender la habilidad Carga y luego hay que practicarla con un muñeco no se puede completar. Por mucho que haga Cargar contra el muñeco no se completa la misión. A lo mejor hago algo mal porque en otro servidor también me pasaba, pero yo lo he puesto aquí por si era un bug. Si no fuera un bug ¿qué hay que hacer?

**Comment by xXkandyXx** [comment]
Ayuda por favor, si no no podre seguir

**Comment by redneo** [comment]
deja y vuelve a coger la mision. Funcionará entonces.

Para la proxima ponme el enlace de la mision http://es.wowhead.com/quest=26945

**Comment by xXkandyXx** [comment]
ya lo he hecho y aun asi no funciona

**Comment by crowel** [comment]
Hola acabo de revisar la misión y funciona correctamente.
Me cree un elfo de la noche guerrero y hice la misión sin problema alguno.
Cierro Issue, un saludo.

**Comment by xXkandyXx** [comment]
ok si, ya funciona

**Comment by shurax** [comment]
buenas creo que este bug no lo han arreglado del todo porque intento hacer la mision y no puedo
