### ISSUE TITLE
Misión "Espíritus del Bastión Quebrantarrocas"

### ISSUE THREAD

**Issue by Sheilina** [RoDNet/Bugtracker-Infinium-4.3.4#887]
Tras recibir la misión (cadena que requiere misión previa realizada, la cual funciona perfectamente), al aplicar el Tótem con los Restos de Ogro, éstos desaparecen como si efectivamente se hubiera realizado la quest, pero en realidad no contabilizan y por tanto no se completa nunca la misión.
Aquí la dejo: http://es.wowhead.com/quest=27410/espiritus-del-bastion-quebrantarrocas

Salu2.

**Comment by redneo** [comment]
creo que se arreglará cuando caiga el server, me lo confirmas, porfa?
