### ISSUE TITLE
Bug Chaman Terremoto

### ISSUE THREAD

**Issue by kirgar** [RoDNet/Bugtracker-Infinium-4.3.4#888]
Bug el talento de chaman elemental Terremoto ID: 61882.
Cuando le doy al Terremoto que es 1 area no hace daño namas hace el hechizo pero no daña a los mobs ni nada.
<a href="http://www.subirimagenes.net/i/130727060823375493.jpg" target="_blank" title="subir imagen"><img src="http://sia1.subirimagenes.net/img/2013/07/27/mini_130727060823375493.jpg" border="0" alt="subir imagenes" /></a>
<a href="http://www.subirimagenes.net/i/130727061253465408.jpg" target="_blank" title="subir imagen"><img src="http://sia1.subirimagenes.net/img/2013/07/27/mini_130727061253465408.jpg" border="0" alt="subir imagenes" /></a>

**Comment by searum** [comment]
fix
