### ISSUE TITLE
Misión "Una idea genial"

### ISSUE THREAD

**Issue by Sheilina** [RoDNet/Bugtracker-Infinium-4.3.4#890]
En esta misión de Tanaris tras usar el objeto (cebo de insecto) aparece el insecto, pero no hay manera de que te siga hasta el npc, se queda parado y lo único que hace es atacarte si te pones sobre él. Al poco tiempo de aparecer desaparece, incluso aún utilizando el objeto desde el mismo npc al que hay que hacérselo llegar, la mision no se completa.
http://es.wowhead.com/quest=24951/una-idea-genial
http://es.wowhead.com/item=52031
Salu2

**Comment by redneo** [comment]
arreglada
