### ISSUE TITLE
[Arenas] Se siguen reiniciando los puntos de conquista

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#891]
Aun se sigue reiniciando el contador diariamente.

**Comment by Sheilina** [comment]
OoO my god

**Comment by ghost** [comment]
Según dijo @searum hace unos minutos, este bug ya esta arreglado, y que las arenas se reiniciaron hoy a la mañana (hoy es el día en que debe reiniciarse).
