### ISSUE TITLE
Misión "El confín de la tierra" Falta NPC

### ISSUE THREAD

**Issue by Sheilina** [RoDNet/Bugtracker-Infinium-4.3.4#894]
La misión te envía a hablar con Kelsey Chispacero, pero al llegar a la posición en la Estación Chispacero el NPC no está. En el mapa figura el signo de interrogación en el lugar en el que debería encontrarse.
http://es.wowhead.com/npc=39059/kelsey-chispacero
Salu2

**Comment by redneo** [comment]
Npc puesto
