### ISSUE TITLE
Talento Sacerdote disciplina [Éxtasis] [spell: 47356]

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#895]
El talento éxtasis (ideado por ximo bayo) [47356] no está funcionando.

Debería hacer lo que muestra en la imagen:

http://imageshack.us/a/img543/1276/x7io.jpg

<a href="http://imageshack.us/photo/my-images/543/x7io.jpg/" target="_blank"><img src="http://imageshack.us/a/img543/1276/x7io.th.jpg" border="0"/></a>

Sin embargo, no está aportando este 7% de maná cuando se rompe (por el daño enemigo) la palabra de poder escudo http://es.wowhead.com/spell=17 , o cuando es disipada (por el enemigo también). Tal como se puede ver en la siguiente imagen, el tick de peste devoradora hace que se rompa mi escudo (solo puede absorber 696 de daño), y por consiguiente el talento Éxtasis debería saltar aportándome un 7% de mi maná total. Esto como se puede ver en la imagen no aparece:

http://imageshack.us/a/img580/7743/m4wu.jpg

<a href="http://imageshack.us/photo/my-images/580/m4wu.jpg/" target="_blank"><img src="http://imageshack.us/a/img580/7743/m4wu.th.jpg" border="0"/></a>

P.D. éxtasis debería saltar no únicamente cuando el beneficiario del escudo es el sacerdote, sino con cualquier otra persona que se beneficie de este escudo, respetando obviamente los 12segundos de CD interno.

Gracias!

**Comment by searum** [comment]
fix
