### ISSUE TITLE
[MISION] El camino de los reyes DK

### ISSUE THREAD

**Issue by pablovarea** [RoDNet/Bugtracker-Infinium-4.3.4#896]
no existen tanto portales para ventormenta como para ogrimmar para viajar hasta alli y poder completar la mision

**Comment by ghost** [comment]
@pablovarea la próxima deja enlace a wowhead de la misión, para facilitar el trabajo a los devs.

 http://es.wowhead.com/quest=13188

**Comment by redneo** [comment]
cuando caiga el server tendrian que aparecer
