### ISSUE TITLE
[ Hunter > Explosive Shot ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#897]
Disparo explosivo está realizando un daño elevado a la media, aproximadamente 1000p. por encima con el nivel de equipamiento de mi personaje.

http://es.wowhead.com/spell=53301

![wowscrnshot_072713_205305](https://f.cloud.github.com/assets/2728817/867386/0781897c-f6f0-11e2-879a-e41ed37f0dcc.jpg)

Vemos como un tick realziza 4.6k debiendo realizar 3.8 ( de media )

Fórmula: ( 0,273 \* RAP )

**Comment by searum** [comment]
drdamage orientativo repito
