### ISSUE TITLE
[Misión] Descontaminación - misión principal de gnomos

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#899]
Debes de subirte en el sanitron 500 para que te descontamine y completar la misión, pero no puedes subirte.

Misión http://es.wowhead.com/quest=27635
Sanitron 500 http://es.wowhead.com/npc=46185

Video de cómo es la misión http://www.youtube.com/watch?v=nyf8jVOAuzI

Pd: summon @redneo

**Comment by redneo** [comment]
arreglado!

**Comment by ghost** [comment]
Gracias.
