### ISSUE TITLE
Puntos de Honor Y Conquista

### ISSUE THREAD

**Issue by SherBlader** [RoDNet/Bugtracker-Infinium-4.3.4#9]
Los puntos de honor y conquista no fueron modificados luego de la actualizacion

![wowscrnshot_070313_175607](https://f.cloud.github.com/assets/4895839/746666/18878448-e434-11e2-8a4b-d16f30f9d411.jpg)

los que tenia antes de la actualizacion los sigo teniendo.

**Comment by ghost** [comment]
Lo mismo a mi, y las monedas de joyería y los sellos de campeon aumentaron a cantidades ridiculas xd.

**Comment by Dekadencee** [comment]
Tras la apertura definitiva en fase jugable serán reiniciados
