### ISSUE TITLE
[DK] Huesos quebradisos

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#90]
Al conectarme al juego, tengo el debuff Huesos Quebradisos, este debuff solo debería ser aplicable a objetivos enemigos usando Toque Helado.

La única forma de hacer que desaparesca es muriendo, pero al salir y volver a conectarme vuelve a aparecer.

Enlace: http://es.wowhead.com/spell=81328

![wowscrnshot_070413_085059](https://f.cloud.github.com/assets/4663665/749442/d49dc7a6-e4ab-11e2-9423-0869276aa530.jpg)

**Comment by searum** [comment]
fix
