### ISSUE TITLE
[Misión][Tierras de la Peste del Oeste] Aprendiendo la profesión

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#900]
Buenas.
La misión Aprendiendo la profesión (http://es.wowhead.com/quest=27000) no se puede completar porque no se puede montar al Caballo mesteño de Vega del Amparo (http://es.wowhead.com/npc=44836) para asustar a las arañas.
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglada!!!!
