### ISSUE TITLE
[Misión][Tierras de la Peste del Oeste] ¡Ya era hora!

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#901]
Buenas.
La misión ¡Ya era hora! (http://es.wowhead.com/quest=27156) no se puede completar porque no se pueden desafiar a los Practicantes de Vega del Amparo (http://es.wowhead.com/npc=45162).
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglado.
