### ISSUE TITLE
[PNJ][Tierras de la Peste del Oeste] Val'kyr inferior

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#903]
Buenas.
Queria reportar que faltan los PNJ Val'kyr inferior (http://es.wowhead.com/npc=45239) en la zona de Andorhal para completar la misión La incursión de las Val'kyr (http://es.wowhead.com/quest=27201).
Gracias y saludos.

**Comment by redneo** [comment]
cuando caiga el server estarán, lo que no se si aguantaran volando.
