### ISSUE TITLE
[Misión][Tierras del Interior] Los documentos de Vallealto

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#904]
Buenas.
La misión "Los documentos de Vallealto" (http://es.wowhead.com/quest=27626) no se puede completar porque los 3 objetos de misión no están.
Los objetos son:
Informe de Vallealto (http://es.wowhead.com/item=61972)
Registros de Vallealto (http://es.wowhead.com/item=61973)
Notas de Vallealto (http://es.wowhead.com/item=61974)
Gracias y hasta luego.

**Comment by redneo** [comment]
cuando caiga el server estaran, con el loot correcto, al menos en uno
