### ISSUE TITLE
[PNJ][Tierras del Interior] Invasor Mortacechador

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#905]
Buenas.
Quería reportar que faltan los PNJ "Invasor Mortacechador" (http://es.wowhead.com/npc=43541) para completar la misión "En defensa de Quel'Danil (http://es.wowhead.com/quest=27625).
Gracias y hasta luego.

**Comment by redneo** [comment]
spawneados unos cuantos, cuando caiga el server apareceran.
