### ISSUE TITLE
[Misión][Tierras del Interior] El colmillo de Shadra

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#906]
Buenas.
La misión "El colmillo de Shadra" (http://es.wowhead.com/quest=26529) no se puede completar porque al abrir el cofre con el Colmillo de Shadra (http://es.wowhead.com/item=58281) está vacío.
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglado teoricamente
