### ISSUE TITLE
[Mision] Tierras altas crepusculares (ventormenta)

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#907]
Nision:Mi hijo, el principe  http://es.wowhead.com/quest=26960/mi-hijo-el-principe

La mision consiste en hablar con el principe que deveria estar a la derecha del rey Wrynn pero no aparece 

http://es.wowhead.com/npc=44293/anduin-wrynn

**Comment by redneo** [comment]
arreglado.
