### ISSUE TITLE
[Cazador]Bug beneficioso Disuasion

### ISSUE THREAD

**Issue by hairblood** [RoDNet/Bugtracker-Infinium-4.3.4#908]
se ve que lo usan mucho y no lo postean,aprovechandose de dicho bug

http://es.wowhead.com/spell=19263
Dice claramente,no puedes atacar pero aun asi ataca.Aqui un par de screens de prueba

![vyw07n](https://f.cloud.github.com/assets/4663665/868379/eb46feca-f796-11e2-9d5f-4128a55eb5cd.jpg)

![2rcl8xh](https://f.cloud.github.com/assets/4663665/868380/ee8a3318-f796-11e2-8895-9ccc896af803.jpg)

**Comment by DatJetto** [comment]
Reportado en https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/291 ( Con todos los bugs de la habilidad )

**Comment by crowel** [comment]
Cierro, se sigue por el reporte anterior.
Un saludo.
