### ISSUE TITLE
[Cazador]Recuperacion rapida

### ISSUE THREAD

**Issue by hairblood** [RoDNet/Bugtracker-Infinium-4.3.4#909]
Funciona bien,excepto porque saltan 2 bufos
uno da enfoque y el otro mana

http://es.wowhead.com/spell=53232 el de cata
 no encuentro el de lich(en old wowhead ya dice que da enfoque),pero la diferencia es que en vez de enfoque da mana

**Comment by DatJetto** [comment]
Creo que es este: http://www.wowhead.com/spell=54227 o almenos es la única que me sale a parte de la normal...

**Comment by searum** [comment]
fix xD
