### ISSUE TITLE
Bugs Del Picaro (Rogue)

### ISSUE THREAD

**Issue by Gamsillo** [RoDNet/Bugtracker-Infinium-4.3.4#91]
RAMA SUTILESA

1: Salta el talento descubrir debilidad, "http://es.wowhead.com/spell=91021/descubrir-debilidad" Con Hemorragia,con puñalada, con Puyaso sin estar en sigilo.  "la spell modificada en panda pero son 70% de ignorar armor"
Por otro lado No salta Con Garrote ni con Golpe bajo estando En sigilo como dice dicho talento.
2: Daño de sangrado de Hemorragia casi nulo muy por debajo de lo normal
3: Daño de Ruptura, solo de 1 punto de combo. Aunque tengas x5 de combo.
4: Daño de Puñalada "http://es.wowhead.com/spell=53/punalada" por debajo de la mitad.
5: Daño de Emboscada "http://es.wowhead.com/spell=8676/emboscada"por debajo de la mitad.
6: La Maestria del Rogue no funciona en ninguna de las ramas.

PD: Estare editando este post a medida que encuentre mas Bug de cada rama. 

Un saludo,
ATT: Gamsillo

**Comment by 50megas** [comment]
hola gamsillo ,pos iva a reportar el daño del roge que creo que esta algo suvido de mas y vi tu reporte y como se contradice queria tu opinion xd.

esta testeado con el drdamage de la 4.3.4 y sin abalorios solo derublo que lo quito cuandos salta

hemorragia http://es.wowhead.com/spell=16511/hemorragia a ojo mete  el doble de lo que deveria:

[IMG]http://i40.tinypic.com/qqybeb.jpg[/IMG]

puñalada http://es.wowhead.com/spell=53  parece que mete un 15% de mas: 

[IMG]http://i42.tinypic.com/15xmqg6.jpg[/IMG]

emboscada http://es.wowhead.com/spell=8676  parece que un 15 % o 20 no encuetro la calculadora xd:

[IMG]http://i40.tinypic.com/2vvm6ok.jpg[/IMG]

tambien eviscerar  http://es.wowhead.com/spell=2098   parece que mete el doble:

[IMG]http://i40.tinypic.com/vopkc5.jpg[/IMG]

que te parece estoi en lo cierto o que opinas? 

un saludo^^

**Comment by 50megas** [comment]
pos ya no se si fiarme de los muñecos de entranamiento, por que en bg y duelos,si que es verda que esta bajisimo el dps, por mucho temple que lleven el dps baja un 70%, nose que pasa,paso de +30k de un puñajada a 9k de critico

**Comment by ghost** [comment]
Si pueden poner cada bug, en un reporte a parte, gracias.
