### ISSUE TITLE
goblins bug

### ISSUE THREAD

**Issue by ozix83** [RoDNet/Bugtracker-Infinium-4.3.4#910]
estimados gm las quest de los goblins estan bug escepto las 3 primeras.
arregladlas o poned 1 portal gracias

**Comment by hairblood** [comment]
y porque no mejor:posteas las quest bug?no arreglaran nada sino lo reportas con enlaces e indicando su fallo

**Comment by ozix83** [comment]
es k problema es k solo las 3 primeras estan bien

**Comment by ozix83** [comment]
http://es.wowhead.com/quest=14153
http://es.wowhead.com/quest=14007
http://es.wowhead.com/quest=14071
http://es.wowhead.com/quest=14110
http://es.wowhead.com/quest=24503
esta son la quest que he aceptado y no puedo completar a partir de estas no se si estan bien o no

**Comment by redneo** [comment]
a parte de ordenarlas las estoy reparando, aunque odie de todo corazon esa zona... eso si, el pj que saque de ahi me lo quedo... por ahora voy en la mision dureza necesaria, supongo que hará falta algun reinicio para que tomen en cuenta algunas cosillas.

**Comment by ozix83** [comment]
http://es.wowhead.com/quest=14125 
no hay nada de lo k pide la quest

**Comment by searum** [comment]
si ozix, se me olvido meter una cosa pero ya esta ^^ sorry xD

**Comment by Kiritoo** [comment]
Esto esta fix
