### ISSUE TITLE
Npc Marith Lazuria [Orgrimmar]

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#911]
Esta elfa de sangre aparte de darnos las diarias de joyería, que ya lo hace, debería darnos también la oportunidad de comprarle los siguientes esquemas:

http://es.wowhead.com/npc=50482/marith-lazuria#sells

**Comment by ghost** [comment]
Aquí había puesto un reporte sobre eso #466

**Comment by Kiritoo** [comment]
Esto esta fix.
