### ISSUE TITLE
Inscripcion bug

### ISSUE THREAD

**Issue by mccelobb** [RoDNet/Bugtracker-Infinium-4.3.4#914]
El Tarot Osucro (http://es.wowhead.com/spell=59491) Fijense que dice Recompensa: 2 pts de habilidad 
![wowscrnshot_072713_204253](https://f.cloud.github.com/assets/3194580/868343/e4007fc6-f794-11e2-9ea4-1ffc50aab833.jpg)
Solo aumenta 1 p

**Comment by crowel** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/759
Ya reportado seguimos por el reporte anterior.
Un saludo.
