### ISSUE TITLE
[Mision dk] En el reino de las sombras

### ISSUE THREAD

**Issue by hairblood** [RoDNet/Bugtracker-Infinium-4.3.4#915]
http://es.wowhead.com/quest=12687
la mision consiste en ir al mundo de las sombras,derrotar a un npc y robarle el caballo
el problema viene que al aceptar la mision,deberia directamente mandarte al mundo pero si te vas de la brecha de la muerte(ya sea a acherus o abajo)se cambia solo,produciendo que si vas a acherus,desaparecen todos los npc e inpide que puedas bajar,ya que en el reino de las sombras solo hay 3 npc's diferentes

**Comment by efectokoleos** [comment]
comprobado y funciona correctamente
