### ISSUE TITLE
portal de infralar 

### ISSUE THREAD

**Issue by ozix83** [RoDNet/Bugtracker-Infinium-4.3.4#916]
estimados gm el portal de orgrimar-infralar no funciona

**Comment by ghost** [comment]
¿De que hablas? funciona perfectamente, acabo de comprobarlo.

**Comment by ozix83** [comment]
pos a mi no me deja usarlo

**Comment by ghost** [comment]
¿Y ya hiciste las misiones del tablon?, para poder ir a Infralar...

**Comment by ozix83** [comment]
no XD eso no lo sabia
