### ISSUE TITLE
[Mago] [Pendiente de Testeo] Congelación profunda: 44572

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#918]
Aturde al objetivo durante 5 s. Solo se puede usar en objetivos congelados y, si el objetivo es inmune al stun de forma permanente, también inflinge 13858-14169 de daño para compensar.

El problema es que está haciendo ambas cosas, inflige ese daño (bastante alto, +20k de crítico) siempre aunque no seas inmune.

**Comment by DatJetto** [comment]
http://es.wowhead.com/spell=44572

**Comment by searum** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1188
