### ISSUE TITLE
[Misión][Tierras del Interior] Todo lo que se desliza (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#919]
Buenas.
La misión Todo lo que se desliza (http://es.wowhead.com/quest=26523) no se puede completar porque no se pueden coger las Arañitas deslizantes (http://es.wowhead.com/npc=42689/) para entregarlas como objeto de misión (http://es.wowhead.com/item=58120).
Gracias y hasta luego.

**Comment by redneo** [comment]
fixed!
