### ISSUE TITLE
[Misión][Tierras del Interior] Las caras del mal (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#920]
Buenas.
La misión Las caras del mal (http://es.wowhead.com/quest=26357) no se puede completar porque al usar la antorcha (http://es.wowhead.com/item=58209) en la mascaras, no cuentan como quemadas.
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglada!
