### ISSUE TITLE
[Misión][Tierras del Interior] Cima del destino (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#921]
Buenas.
La misión Cima del destino (http://es.wowhead.com/quest=26517) no se puede completar porque no se pueden despojar los Ídolos arácnidos (http://es.wowhead.com/item=58228) de los Vilramas sacrificados que hay en la zona (http://es.wowhead.com/npc=42857).
Gracias y hasta luego.

**Comment by redneo** [comment]
No he podido hacer que sea como es, no se abre el loot del npc...

Como es muy triste la situación, si los lloras (/llorar /cry) te dan los items.

No se me ha ocurrido nada mejor para que te los den

**Comment by ghost** [comment]
Muy gracioso para ser verdad XD
Mas tarde pruebo.

**Comment by ghost** [comment]
Funciona :O
El arreglo mas original de todos.
![1337822255500](https://f.cloud.github.com/assets/4582987/876194/e6f01bda-f8be-11e2-92b8-fd1eef85840a.gif)
¿Pero cómo va a saber la gente que esta leveando que tiene que usar /llorar para coger un objeto de misión del cadaver?
Muchas gracias.

**Comment by redneo** [comment]
Gracias a la inspiracion de searum se ha puesto mejor... aunque el tema de llorar tenia su gracia!
