### ISSUE TITLE
[PNJ][Tierras del Interior] Morta'gya la Vigilante

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#922]
Buenas.
Quería reportar que falta en PNJ Morta'gya la Vigilante (http://es.wowhead.com/npc=42877) que sirve para despojar la Tablilla de Shadra (http://es.wowhead.com/item=58241) y completar la misión Caza a la vigilante (http://es.wowhead.com/quest=26526).
Gracias y hasta luego.

**Comment by redneo** [comment]
cuando caiga el server tendria que estar.
