### ISSUE TITLE
[Mision] Infralar

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#923]
Mision: Sin capitan ni tripulacion      http://es.wowhead.com/quest=26427/sin-capitan-ni-tripulacion
![wowscrnshot_072813_202759](https://f.cloud.github.com/assets/4893907/868624/fa6aa416-f7b3-11e2-9f08-c7be5bd3bffc.jpg)

Hay que coger 2 items:
Botella de whisky: http://es.wowhead.com/item=58798
Bobina de Cuerda: http://es.wowhead.com/item=58806

pero he aqui el dilema...¿como las cojo?....si estan en el aire flotando cuando deberian estar en el barco, el barco esta en movimiento pero los items estan inertes en el aire en un punto donde pasa el barco pero no se pueden coger

![wowscrnshot_072813_202751](https://f.cloud.github.com/assets/4893907/868625/290e1f96-f7b4-11e2-80e3-16664aa89e16.jpg)

![wowscrnshot_072813_202733](https://f.cloud.github.com/assets/4893907/868626/2e3a2654-f7b4-11e2-9327-dd2872ccdb6d.jpg)

**Comment by redneo** [comment]
He puesto los objetos en el suelo, junticos al este de infralar.
