### ISSUE TITLE
[Misión] La Transmisión del Conocimiento

### ISSUE THREAD

**Issue by xXkandyXx** [RoDNet/Bugtracker-Infinium-4.3.4#924]
En la misión del título cuando llevo la tinaja con agua a Dolanaar se supone que se la tengo que dar a Corithras Furia Lunar, pero cuando me dirijo hacia el signo de interrogación en el mapa no hay nadie, solo el instructor druida y una centinela, pero ni rastro de Corithras. He abandonado y vuelto a aceptar la misión pero aun así no aparece el PNJ.
Link de la misión: http://es.wowhead.com/quest=28731

**Comment by redneo** [comment]
Ya se tendria que ver el npc si tienes la mision

**Comment by xXkandyXx** [comment]
ok gracias

**Comment by xXkandyXx** [comment]
oye, he abandonado la mision y la he vuelto a coger y sigue sin aparecer
