### ISSUE TITLE
bug esfumarse picaro

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.3.4#925]
la habilidad de picaro http://es.wowhead.com/spell=31619/esfumarse ,funciona bien pero una cosa muy importante no va , y es que debe de quitar todas las ralentizaciones pero no las quita.

ejemplo congelaciones de mago

un saludo

**Comment by ghost** [comment]
Se hizo la prueba conmigo, dice ralentizaciones, pero no se si el grupo ralentizaciones incluye roots, es decir, novas de escarcha, raíces...etc.

Sinceramente no sé si es bug o va como debería, pero si no recuerdo mal debería eliminarlas.

**Comment by 50megas** [comment]
pues puede que este bien, miradolo  asi sera que me mal acostubre por que en la 4.0.6 si las quitaba.

voi a mirar algun video roge vs mago para verificarlo

**Comment by 50megas** [comment]
video de un servidor español sanginario. segundo 10 mas o menos.

http://www.youtube.com/watch?v=DiPMjQc-Ztc

un saludo

**Comment by ghost** [comment]
@DatJetto En wowwiki parece que pone lo contrario: "Breaks free of root effects like Frost Nova and Entangling Roots."

Según eso creo que debería eliminar las roots...de todos modos yo creo recordar así de siempre, aunque hace mucho que no cojo el rogue xD 

http://www.wowwiki.com/Vanish

**Comment by searum** [comment]
fix
