### ISSUE TITLE
no puedo atacar

### ISSUE THREAD

**Issue by jorgeqlo** [RoDNet/Bugtracker-Infinium-4.3.4#926]
hola cuando estoy haciendo pvp no tengo problemas pero despues de un rato de lanzar skil , se buguea y no me deja atacar ni lanzar skill de la barra de ataque , de ante mano muchas grax y ojala me puedan ayudar con esto

**Comment by SherBlader** [comment]
salta ''faltan runas'' ??

**Comment by DatJetto** [comment]
A mi me pasa lo mismo con mi hunter.
