### ISSUE TITLE
[Misión] Mareas Oscuras 

### ISSUE THREAD

**Issue by Honme** [RoDNet/Bugtracker-Infinium-4.3.4#928]
En la misión Mareas Oscuras del ''Pantano de las Penas'' donde se supone que uno tiene que matar a 6 Ogros de Rocal, cuando se llega a la zona donde tendrían que aparecer no aparecen.

http://es.wowhead.com/quest=27795#.

Pido por favor que arreglen el Bug lo antes posible gracias por su tiempo.

**Comment by redneo** [comment]
cuando caiga el server tendrian que aparecer.
