### ISSUE TITLE
Scholomance > Boss muercielago.

### ISSUE THREAD

**Issue by Hellythium** [RoDNet/Bugtracker-Infinium-4.3.4#929]
Buenas, lo que pasa es que en la insta de Scholomance, el boss murciélago que  habita en el piso de Cámaras de la Invocación (que lamentablemente aparece el mapa y la insta al ser buscadas en wowhead aparece es el de MoP, pero su logro es este http://es.wowhead.com/achievement=645#criteria-of ) y que la verdad no me se su nombre, no aparece, imágenes de mapa, donde dice que hay debería de haber un boss en ese punto y otra mostrando que no hay nada: 

![wowscrnshot_072813_185811](https://f.cloud.github.com/assets/3613748/869114/9784518c-f7e3-11e2-9fb4-812cfdff0543.jpg)

![wowscrnshot_072813_185813](https://f.cloud.github.com/assets/3613748/869115/9d3f22d2-f7e3-11e2-8d28-197a3c10767f.jpg)

**Comment by efectokoleos** [comment]
algo de explicacion vendria bien...

**Comment by 50megas** [comment]
de ese boss me hacuerdo yo de cuando jugaba al clasic,este boss se invocaba con una sagre o algo asi que soltaba un diablilla tipo sucubus de brujo de mas alante.

**Comment by ghost** [comment]
si.. en el classic xd, no sé en que parche quitaron la parte de invocarlo,  debería estar ahí sin hacer eso.
