### ISSUE TITLE
Cazador (varios) punteria parte 1

### ISSUE THREAD

**Issue by jaramys** [RoDNet/Bugtracker-Infinium-4.3.4#93]
1 el pt talento bug de la antigua version -.-

Disparo fimr mejorado.

te aumenta la celeridad 5,10 y 15% despues de hacer 2 disparos firmes seguidos.

no pongo en lace de wow head pro que no me salen.

http://es.wowhead.com/spell=37505 ese es el enlace mas parecido de wowhead

2 http://es.wowhead.com/spell=35110/bombardeo

ese talento que te reduce el coste de enfoque de tu siguiente multidisparo,

se activa cuando lanzo ataque automatico,

3 http://es.wowhead.com/spell=34487 ese talento te da este buff http://es.wowhead.com/spell=82925

que te permite tirar http://es.wowhead.com/spell=19434 tras 5 acomulaciones, la cosa es que si ganas el buff i se te asen 

las 5 acumulaciones. pero no te permite tirar el disparo instantaneo ni sin coste de enfoque.

4 http://es.wowhead.com/spell=56641 diparo firme y http://es.wowhead.com/spell=77767 disparo de cobra
no aumenta la duracion de picadura de serpiente http://es.wowhead.com/spell=1978

5 http://es.wowhead.com/spell=13165 aspecto del alcon no da el poder de ataque a distancia, no da nada extra.

6.http://es.wowhead.com/spell=6991 alimentar mascota, a mi me sana alrededor de 800k cuando mi pet tiene como 22k sin buff, no es tan grave pero si lo pueden revisar.

7 http://es.wowhead.com/spell=83490 el talento que te da mas enfoque cuando usas http://es.wowhead.com/spell=56641 disparo firme o http://es.wowhead.com/spell=77767 disparo de cobra no funciona. no te da enfoque extra cunado tan con menos del 25% de vida. 

8 http://es.wowhead.com/spell=82897 este talento te permite lanzar un http://es.wowhead.com/spell=83381 sobre el objetivo marcado , tieen un 8% i lo probe los 5 min de la marca me parece que almenos 1 vez deveria activarse, lo probe varias veces, osea varias veces tire la marca i el objetivo se movia (duelo)

Estos por ahora luego pruebo mas

**Comment by searum** [comment]
Como es un reporte por bug y esto son 8 juntos ademas veo que la mayoria estan fixeados lo cierro, si falta alguno por fixear abre un nuevo issue y recuerda, tan solo un issue por bug no metas 8 bugs en el mismo issue.
