### ISSUE TITLE
Profundidades de Roca Negra>El Lyceum impasable.

### ISSUE THREAD

**Issue by Hellythium** [RoDNet/Bugtracker-Infinium-4.3.4#933]
Buenas, la instancia Profundidades de Roca Negra http://es.wowhead.com/zone=1584/profundidades-de-roca-negra en la parte de El Lyceum aun un bug grave, por que no se puede seguir la insta por las puertas, según mal no recuerdo, uno tiene que matar a unos Vigilantes de las Llamas de Forjatinieblas http://es.wowhead.com/npc=9956/vigilante-de-las-llamas-de-forjatiniebla para que nos dropeen unas antorchas, de hecho hay que matar a dos para poder pasar, y si dropean las antorchas, pero lo que pasa es que no puedo encender los dos blandones o como se les quiera llamar para poder abrir la puerta y continuar, muestro las imágenes, que aunque hagamos click izquierdo para utilizar las antorchas no pasa nada, y no aparece el engranaje en ninguno de los dos blandones: 
![wowscrnshot_072813_205511](https://f.cloud.github.com/assets/3613748/869306/9355515a-f7f3-11e2-896b-4aa8ca247c15.jpg)
![wowscrnshot_072813_205442](https://f.cloud.github.com/assets/3613748/869307/93581b42-f7f3-11e2-9c76-852bca623f7f.jpg)

Lastima que con las fotos no se pueda ver el puntero.

Saludos, Darkstar.

**Comment by efectokoleos** [comment]
en la proxima caida estará arreglado
