### ISSUE TITLE
Misión "Una idea genial" SIGUE SIN FUNCIONAR

### ISSUE THREAD

**Issue by Sheilina** [RoDNet/Bugtracker-Infinium-4.3.4#936]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/890

La única diferencia es que ahora el bicho aparece como unidad amiga y no enemiga, pero ni te sigue ni se completa la quest al llegar al npc requerido.

**Comment by redneo** [comment]
recomprobado... cuando le lanzas el lazo al npc http://es.wowhead.com/npc=5451/enjambrista-hazzali te cuenta como objeto de mision, no hace falta que te siga ni nada.
