### ISSUE TITLE
[ Daily Fishing > One fer the Ages ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#938]
Presa histórica:
http://es.wowhead.com/quest=29343

1 La completa descripción y nombre de esta quest está en inglés, así que rogaría traducirla.

2 Necesitamos pescar Quiahierro joven http://es.wowhead.com/item=69932 , pero cuando pescas apenas salen peces, salen armaduras y armas y cosas raras.

Tras pescar el Quijahierro debemos ir a la biblioteca y exponerlo en la placa vacía que hay.

**Comment by Kiritoo** [comment]
Arreglada.
