### ISSUE TITLE
[ Daily Cooking > I Need to Cask a Favor ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#939]
Un barril de favores:
http://es.wowhead.com/quest=29356

La quest está completamente en inglés, rogaría traducirla al español. ( La dinámica de la quest funciona perfectamente )

**Comment by redneo** [comment]
hay muchisimas cosas en ingles, ya que las traducciones de la 434 se dejan desear... Si tienes ganas de hacer copy/paste te puedo decir como pasarnos traducciones :D

**Comment by Dekadencee** [comment]
Traducido todo lo que se ha podido, faltan varios textos
