### ISSUE TITLE
Lockpicking - Forzar Cerradura - PICARO

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.3.4#94]
Bueno este problema lo venia teniendo desde la 4.0.6a pero me imagine que en la 4.3.4 se hiba a solucionar xD

---

http://www.wowpedia.org/Lockpicking <<<< WOWPEDIA dice:

Que desde la 4.0.1 forzar cerradura que es una habilidad del picaro ahora se incrementa por nivel, y ya no como una profesion normal.

Me he dado cuenta por que ya yo un Picaro nivel 70 y no puedo abrir cajas de 300 puntos.

Y en 4.06a note que mientras mas cajas de 1p. abria hiba desbloqueando cajas con puntaje mas alto. pero creo que eso era cosa del pasado. no?

**Comment by searum** [comment]
fix
