### ISSUE TITLE
[ Quest > Deeprun Rat Roundup ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#940]
A por las ratas del tranvía subterráneo:
http://es.wowhead.com/quest=6661

Nos dan el objeto: http://es.wowhead.com/item=17117
que usa la spell: http://es.wowhead.com/spell=21050

Cuando tocas la flauta cerca de  Rata de subterráneo ( http://es.wowhead.com/npc=13016 ) no ocurre nada, debiendo transformarse en Rata de subsuelo sometida ( http://es.wowhead.com/npc=13017 ) y cada rata transformada debe contar para completar la quest.

http://www.youtube.com/watch?v=U11BArF432g

**Comment by redneo** [comment]
las ratas aparecen muertas, a ver cuando caiga el server si salen vivas.....

**Comment by efectokoleos** [comment]
fix
