### ISSUE TITLE
[ Npc > Monty <Rat Extermination Specialist> ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#941]
Monty <Especialista en el exterminio de ratas> : 
http://es.wowhead.com/npc=12997

Este npc se encuentra duplicado o triplicado en el tranvía subterráneo de ventormenta - forjaz. 
Están todos en la misma coordenada.

**Comment by redneo** [comment]
dejado uno
