### ISSUE TITLE
Misión: No tientes a la suerte

### ISSUE THREAD

**Issue by Sartis01** [RoDNet/Bugtracker-Infinium-4.3.4#942]
Al usar el objeto de misión, la antorcha, sobre un saco, éste prende pero no te cuenta en la misión. 
http://es.wowhead.com/quest=11913

**Comment by Sartis01** [comment]
Qué id más necesitas?

**Comment by DatJetto** [comment]
Sacos de Grano de Lindeallá: http://www.wowhead.com/npc=26161
Antorcha de Wendy: http://es.wowhead.com/item=35491
Spell de la antorcha: http://es.wowhead.com/spell=46574

**Comment by redneo** [comment]
arreglado
