### ISSUE TITLE
Misión: El emisario

### ISSUE THREAD

**Issue by Sartis01** [RoDNet/Bugtracker-Infinium-4.3.4#943]
La misión te pide que empales a Leviroth con un objeto de misión que te dan, pero solo te deja empalarlo una vez, cuando para matarlo es necesario empalarlo al menos 2 veces.
De todos modos, yendo con un 85 a matarlo, tampoco cuenta como objetivo completado.
http://es.wowhead.com/quest=11626

**Comment by redneo** [comment]
Cuando caiga el server tendria que ir, me lo confirmas?

**Comment by Kiritoo** [comment]
Esto esta fix.
