### ISSUE TITLE
[Misión]Desde las sombras

### ISSUE THREAD

**Issue by Xscorpio** [RoDNet/Bugtracker-Infinium-4.3.4#945]
Mision: http://es.wowhead.com/quest=14204/desde-las-sombras
BUG: El mastín gilneano no rastrea a ningún huarguen teje sombras en ninguna de las zonas especificadas en wowhead, por lo tanto no se pueden matar y no se puede completar la misión.

**Comment by Kiritoo** [comment]
Esto está fix.
