### ISSUE TITLE
[Mision] Infralar

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#946]
Mision: El mirador Crepuscular   http://es.wowhead.com/quest=27061/el-mirador-crepuscular

![wowscrnshot_072913_172738](https://f.cloud.github.com/assets/4893907/872474/e6156d56-f863-11e2-9174-e8570e998c42.jpg)

Hay que hablar con Clamatormentas Myiria que nos abre una cadena de misiones pero el PNJ no esta http://es.wowhead.com/npc=44010/clamatormentas-mylra

![wowscrnshot_072913_172729](https://f.cloud.github.com/assets/4893907/872471/db1d59b8-f863-11e2-8b6c-94e5cd1a8a83.jpg)

**Comment by redneo** [comment]
CAmbiados de fase. fixed
