### ISSUE TITLE
[Hechizos] Sello de Perspicacia, Paladines

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#948]
Buen dia staff, Devs.

Quisiera añadir a este tema https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/593 Que este Sello o spell fundamental de la clase Paladin esta mas bug que antes ( ya reportado).

http://www.wowdb.com/spells/20165-seal-of-insight

Hoy dia NO cura nada en absoluto, ni vida, ni mana, sea la rama que sea del paladin.

Quisiera que lo mirana por favor , gracias y sigan con su buen trabajo y buen dia de nuevo.

**Comment by ghost** [comment]
¿Por que reportas lo mismo dos veces? S:

**Comment by lamaza** [comment]
No es lo mismo. En el caso 1, curaba mal, pero al menos curaba.

Ahora no se que hiciero ndesde hace unos dias, que no cura nada de nada. Para mi no es lo mismo...

**Comment by lamaza** [comment]
Ahora tiene el fix que tenia , pero igual sigue necesitando reparación el spell. Continuamos en el otro reporte. :) Gracias
