### ISSUE TITLE
Bug Cámara de Vapor

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#949]
Después de haber matado a los 2 jefes primeros y haber activado las máquinas, la puerta del tercer boss no se abre, aparece bloqueada.

**Comment by efectokoleos** [comment]
parece que en normal no se abre, pero en heroico funciona, hazla en heroico mientras miramos el problema

**Comment by efectokoleos** [comment]
arreglado
