### ISSUE TITLE
Rastreador de misiones

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#95]
Las misiones deberian salir marcadas en el mapa para saber donde ir de lo contrario estamos mas perdidos que los reyes magos en agosto
![wowscrnshot_070413_165819](https://f.cloud.github.com/assets/4893907/749947/47b69214-e4ba-11e2-9c60-d6e9ee0fdb72.jpg)

saludos y gracias de antemano

**Comment by WarSxNes** [comment]
> _Hijo del averno xD.... rayos y trueno muestran la furia de los dioses ancestrales.... caos, llanto, dolor, angustia caen sobre la faz de Azeroth..._

http://www.reignofdarkness.net/wow/foros/t1977/?t=1977 <<<<< Tu post en el foro

---

Estas usando el Mapa en modo ventana minimizada, ahi nunca te mostrara las zonas que deberas lvlevear.
Ademas ni siquiera has terminado de explorar la zona xD, quita el modo ventana y expandela y veras como ahora si te muestra las zonas.

En el minimapa te mostrara los objetivos. ademas no se si logras ver la flecha verde apuntando hacia abajo... eso significa que sigues descargando....

Solo ten paciencia... para que se bajen los componentes del juego. y luego asta en el minimapa te comenzara a mostrar zonas azules correspondientes a la quest mas cercana.

Saludos y pasala bien,,,

> de mi parte no esta bug. =) y cuanto va a tardar para que veas los cambios? dependera del metodo que usaste para actualizarte; las MPQ deben de llenarse para ver los cambios. usa un editor o visor mpq para ver como se van llenando =) bueno eso si te da curiosidad... es un tip.

**Comment by frustrix** [comment]
Esta la descarga al 100% y hay zonas que no me muestra las misiones, pero bueno usare carbonite y listo

Y aunque este la ventana minimizada si te muestra las misiones war no te des de listillo ;)

saludos
