### ISSUE TITLE
Bug La Sotiénaga

### ISSUE THREAD

**Issue by foxmclaud** [RoDNet/Bugtracker-Infinium-4.3.4#950]
El último jefe no se encuentra (previamente habiendo matado al resto).

Los npcs/jefes no dan reputación con el esporaggar.

No se encuentra disponible el npc que proporciona la misión: ¡Traeme otra mata! http://es.wowhead.com/quest=29692

**Comment by efectokoleos** [comment]
añadidos todos los npcs que dan quest
