### ISSUE TITLE
[Paladin] Sellos de mando

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#951]
![wowscrnshot_072913_152635](https://f.cloud.github.com/assets/3101842/874322/4a3401b0-f889-11e2-81eb-a2b5a37fe589.jpg)

El talento deberia de hacer que con sello de rectitud pegara a todos los objetivos enemigos a distancias cuerpo a cuerpo 
el caso es que no lo esta haciendo pego un golpe de cruzado y solo el objetivo esta recibiendo daño del sello de rectitud
![wowscrnshot_073113_015228](https://f.cloud.github.com/assets/3101842/884138/3986df14-f9aa-11e2-8fcf-accb61633064.jpg)
b

El id no lo encontre ha sido eliminado de wow head asi que deje una imagen del talento

**Comment by ghost** [comment]
Pero esos muñecos no estan a distancia cuero a cuerpo, o si? xd, o sea.. los veo un poco alejados.

**Comment by lamaza** [comment]
Pues si tiras colerasagrada los alcanza.. XD

**Comment by Moyax** [comment]
jaja men esos dumy no stan a distancia cuerpo a cuerpo todos... Si no me equivoco si funciona =P o almenos funcionaba la otra vez que utilice al pala en Retry.

**Comment by lamaza** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1857

**Comment by searum** [comment]
lo seguimos en el de lamaza
