### ISSUE TITLE
[Guerrero] Cargar algo raro :l

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#952]
ID: http://es.wowhead.com/spell=100/cargar
Bueno habia reportado cargar antes ya que no esta aturdiendo al objetivo durante 1.5s
hoy me puse a revisar aver si ya lo habian reparado y noto que ahora cuando uso cargar mi pj hace como si lanzara la invocacion del elemental de agua el hechizo del mago con el sonido y todo e-e

por cierto cargar sigue sin estunear...

**Comment by ghost** [comment]
El sonido es exactamente el que suena al invocar el elemental de agua del mago escarcha, no el de la nova :P

**Comment by F4NT4SM4** [comment]
bueno no uso mucho mago asi que estaba adivinando cual era :c

**Comment by crowel** [comment]
El sonido y en las manos del guerrero aparece un destello azul como de escarcha jeje.
