### ISSUE TITLE
No veo a los PJs

### ISSUE THREAD

**Issue by xXkandyXx** [RoDNet/Bugtracker-Infinium-4.3.4#954]
Hola, no veo a los PJs, estaba intentando quedar con un amigo y el no paraba de ver gente y yo desde que empece a jugar aun no he visto a nadie, y a el tampoco.

**Comment by crowel** [comment]
Yo tengo otra pregunta Kandy, acabas de poner a bajar el juego?, si es así y llevas muy poco % del juego descargado también pueden pasar estos problemas.
Un saludo.

**Comment by xXkandyXx** [comment]
Lvmb: Si, Vïserys.
crowel:  Empece a jugar hace 2 días

**Comment by xXkandyXx** [comment]
no, soy un elfo de la noche lvl 12 y estoy en dolanaar, y lo que no veo son los jugadores
