### ISSUE TITLE
[Mazmorra] Trono de las MAreas 5H

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#955]
Quiero dejar aquí, cosas que notamos no eran coherentes...

1-CCear boss o mobs, incluido interrupción de casteos a veces.

2-Daños exagerados (posiblemente, no sabemos todo).

3-Traducciones no disponibles (texto en alemán).

4-Letras extrañas en el ascensor (super mega entidad desconocida) con nombre como "Malignodidades".

5-Ozumat (boss final) nunca apareció para dar la cara, solo lo podíamos targetear cerca del ascensor...

Item 1-----
![wowscrnshot_072913_151637](https://f.cloud.github.com/assets/4790547/874976/f0306e8e-f896-11e2-825e-038dada5e3a8.jpg)
## ![wowscrnshot_072913_151416](https://f.cloud.github.com/assets/4790547/874977/f02e02b6-f896-11e2-87d5-7449231956ef.jpg)

Item 2-----
![wowscrnshot_072913_153243](https://f.cloud.github.com/assets/4790547/874979/f037e736-f896-11e2-845f-c1509784b4f5.jpg)
![wowscrnshot_072913_153555](https://f.cloud.github.com/assets/4790547/874981/f0413778-f896-11e2-9f0a-dce6ab3aa10c.jpg)
## ![wowscrnshot_072913_153546](https://f.cloud.github.com/assets/4790547/874986/f059318e-f896-11e2-8dfa-e8f3484523e4.jpg)

Item 3 (Fijense en el texto amarillo de la foto 3 de este Item, Luego de eso, me fui para el ascensor y vi por un instante al calamar (Ozumat) ahi, lo targetee y desaparecio por el resto del tiempo hasta que nos fuimos.

![wowscrnshot_072913_154738](https://f.cloud.github.com/assets/4790547/874983/f04ed8b0-f896-11e2-821a-2233822805be.jpg)
![wowscrnshot_072913_154412](https://f.cloud.github.com/assets/4790547/874980/f044627c-f896-11e2-8ea6-553e7b076efc.jpg)
## ![wowscrnshot_072913_155844](https://f.cloud.github.com/assets/4790547/874982/f04287b8-f896-11e2-8409-2040d9c03a06.jpg)

Item 4

![wowscrnshot_072913_160332](https://f.cloud.github.com/assets/4790547/874978/f0378a8e-f896-11e2-89e9-286c338fa0e2.jpg)
![wowscrnshot_072913_160323](https://f.cloud.github.com/assets/4790547/874985/f0588cde-f896-11e2-91a4-3db700e8aad9.jpg)
![wowscrnshot_072913_160208](https://f.cloud.github.com/assets/4790547/874984/f04f14f6-f896-11e2-97d2-74c58ee716f8.jpg)

**Comment by searum** [comment]
Joder, vale que no este 100% blizzlike pero... decir por el chat general que esta BUG BUG TRONO ESTA BUG! para encontrarme esto... pues no veas.

Sobre las traducciones las tenemos todas, es cuestion de moverlas del 406 al 434 pero vamos, no creo que sea prioritario.

**Comment by efectokoleos** [comment]
1- los mobs se pueden ccear los bosses no claro xd

2 - el daño me parece k esta bien ahora lo compruebo

3- el idioma, si se nos han colado esos bosses en completo aleman xd

4 el ultimo boss tendré que revisarlo mejor

**Comment by efectokoleos** [comment]
el ultimo boss creo que esta arreglado

**Comment by paellaencol** [comment]
Está dando problemas el último boss https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/2110
