### ISSUE TITLE
[Cazador] Picadura de dracoleón: 19386

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#957]
Pasa algo raro, se pone tal y como debería un debuff de 6-7s, pero luego está dejando un BUFF de otros 6 segundos haciéndome daño (DoT). Al ser un buf, lo puedo eliminar haciendo click derecho xD.

http://es.wowhead.com/spell=19386

**Comment by DatJetto** [comment]
Asman, que pongas ID's!! xD 

Picadura de Dracoleón: http://es.wowhead.com/spell=19386

**Comment by searum** [comment]
te molesta? xD

**Comment by ghost** [comment]
A mi no, a los cazas supongo que sí, ya que en vez de un DoT me dejan un bufo xD

**Comment by searum** [comment]
vale asman ponte el addon idtip y cuando se aplique el buff pon el raton encima y me pones la id =)

**Comment by searum** [comment]
fix
