### ISSUE TITLE
[BG Arena] Salir fuera de puertas -Arena de Nagrand

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#959]
La verdad este bug no se como recrearlo...

Solo pasó hace unos 3 o 4 dias: Mi compañero y yo anotamos arenas, el entro primero, y luego yo decidí entrar, y lo que paso es que al cargar la arena, sali afuera de la puerta (area de preparación) antes de tiempo.

![wowscrnshot_072613_153408](https://f.cloud.github.com/assets/4790547/875081/4c8ecc28-f899-11e2-90d0-fb48c5415a6b.jpg)
![wowscrnshot_072613_153341](https://f.cloud.github.com/assets/4790547/875082/4ca70748-f899-11e2-8ccb-90b5cb42b362.jpg)
![wowscrnshot_072613_153343](https://f.cloud.github.com/assets/4790547/875083/4cbea8b2-f899-11e2-887b-56ebf2d2baa5.jpg)

**Comment by ghost** [comment]
También ocurre que a veces empieza la arena cuando aún está la cuenta atrás...y te jode el CD de invisibilidad por ejemplo.

**Comment by lamaza** [comment]
No volvió a suceder, ya trabajron mucho en arenas =).
