### ISSUE TITLE
Problemas con mi war

### ISSUE THREAD

**Issue by dkanciano** [RoDNet/Bugtracker-Infinium-4.3.4#96]
para empezar no puedo ver los set de temporada 10 ni 11 y tampoco puedo ver los set de transfiguracion  de http://es.wowhead.com/npc=54650/kezzik-el-asediador  

otra cosa es normal que a un muñeco de pruevas le llegue a pegar un critico de 40k con full cds de war y a un pala con 3 partes pvp solo 6 k o 7 k ???? yo estoy full sangui con la mitad de partes sañosas y abalorio implacable

**Comment by dkanciano** [comment]
a olvide mencionar que solo puedo ver las armas de temporada 10 y 11 y encontre otro war que le pasava lo mismo

**Comment by ghost** [comment]
No sé si sea esto pero te lo digo por si acaso, machaque colosal solo "quita" el 50% de la armadura en pvp, y 100% de la armadura en pve, eso es un cambio en el parche 4.1 creo.

**Comment by ghost** [comment]
@dkanciano un bug por reporte (y más elaborado), lo del set ya esta bien.
