### ISSUE TITLE
[hechizos] Inquisición - Paladin repre

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#960]
Quiero reportar que este spell tiene algo mal configurado. Cuando lo usas siguiendo sierta pauta, se activa de manera bugeada, beneficiando al usuario con 50 segundos (en vez de 36s) de daño extra de poder sagrado.

La manera en que a veces lo he recreado es:

Lo uso con cualquier carga (1,2 o 3) de poder sagrado, casi siempre mediante propósito divino activado. Luego lo cancelo, y me lo vuelvo a lanzar con 3 cargas, y en vez de darme 36S, me da los 50seg.

![wowscrnshot_072613_145605](https://f.cloud.github.com/assets/4790547/875100/ce39dd94-f899-11e2-9228-f8bd3e3363af.jpg)

**Comment by Moyax** [comment]
=P sigues siendo al unico que le pasa eso el mio no pasa de 35 seg xD

**Comment by lamaza** [comment]
Inquisición aumentará su duración solo usando el set T11 http://es.wowhead.com/itemset=932  De otra forma solo deberia durar 12segs/1Holy Power charge. Es decir, en total 36 segs. No más, no menos.

http://es.wowhead.com/itemset=932
http://us.battle.net/wow/en/forum/topic/2661036126

**Comment by lamaza** [comment]
Lo cierro, sucede es por otro spell bug. https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1317
