### ISSUE TITLE
[Mazmorra] Nucleo Petreo 5N

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#961]
Varios bugs por reportar sobre esta buena estancia:

Pielpetrea (Boss #2) Tiene un clon o copia al lado que no hace nada.

![wowscrnshot_072613_140808](https://f.cloud.github.com/assets/4790547/875113/19f16f4a-f89a-11e2-822a-60dcb54038de.jpg)
![wowscrnshot_072613_140904](https://f.cloud.github.com/assets/4790547/875115/283f6cdc-f89a-11e2-9271-1cedf938e5e2.jpg)

Ozruk (Boss #3) Si no me equivoco, se le puede meter Stun...
ME salio mal la foto ese dia, pero lo pueden probar en 5 segunditos =).

![wowscrnshot_072613_141706](https://f.cloud.github.com/assets/4790547/875130/6129eec8-f89a-11e2-8206-01ca18ab77c8.jpg)

Suma Sacerdotiza Azil (Boss Final) Es una piñata total, y se le puede CCear.

![wowscrnshot_072613_142115](https://f.cloud.github.com/assets/4790547/875132/7f64be04-f89a-11e2-924c-dd178c6310bb.jpg)
![wowscrnshot_072613_142105](https://f.cloud.github.com/assets/4790547/875133/7f7e158e-f89a-11e2-84f1-3e4dd6d77c08.jpg)

Gracias por su tiempo.

**Comment by DatJetto** [comment]
Lo de pielpétrea supongo que debería ir volando hasta la posición y cuando llega el npc no atacable, desaparece/muere el ''clon'' y al morir hace spawn del boss ( para que se le pueda atacar , sí son 2 npc distintos ).

Y el que no se le puede atacar no desaparece y por eso veis 2 xD

**Comment by efectokoleos** [comment]
prueba ahora

**Comment by Dekadencee** [comment]
Fixed
