### ISSUE TITLE
Talento "Invocación" Bug

### ISSUE THREAD

**Issue by lllalvarolll** [RoDNet/Bugtracker-Infinium-4.3.4#962]
Si tienes puesto el talento Invocación (87098) debería activarse solamente cuando interrumpes y, sin embargo, se está activando casteando cualquier habilidad.
![wowscrnshot_072913_235922](https://f.cloud.github.com/assets/3487127/875152/ef3b2862-f89a-11e2-8ac8-8fd41d1a63c4.jpg)
![wowscrnshot_072913_235924](https://f.cloud.github.com/assets/3487127/875154/055885c2-f89b-11e2-96b2-b3b363164880.jpg)

**Comment by searum** [comment]
fix
