### ISSUE TITLE
Misión "los grabados de los glifos"

### ISSUE THREAD

**Issue by Sheilina** [RoDNet/Bugtracker-Infinium-4.3.4#963]
Cuando tienes los objetos necesarios, la quest no se completa y no se puede entregar en el npc.
http://es.wowhead.com/quest=8309/los-grabados-de-los-glifos

Salu2

**Comment by redneo** [comment]
A mi me la ha completado bien :S

**Comment by Kiritoo** [comment]
Esta misión está fix.
