### ISSUE TITLE
Problema mision Sacrificio

### ISSUE THREAD

**Issue by sragu1990** [RoDNet/Bugtracker-Infinium-4.3.4#964]
El caballo no está, espero alrededor de una hora y ahí y solo aveces aparece. un MJ llamado firstaid me ayudo haciendomelo aparecer pero se me hacia imposible subir y poder completar la mision. me encuentro en patio de cringris

**Comment by ghost** [comment]
Enlace de la misión http://es.wowhead.com/quest=14212
Enlace del caballo http://es.wowhead.com/npc=44428

Nombre del pj con el problema: Telaredoy

Pd: /summon @searum  y/o @redneo

**Comment by searum** [comment]
fix

**Comment by sragu1990** [comment]
estoy intentando hacerla en este momento y sigue igual....

**Comment by ghost** [comment]
¿Pues borrar la misión, y volverla a agarrar?, seguro te funcionará.

**Comment by sragu1990** [comment]
lo hago y sigue sin aparecer el caballo... estoy conectado ahora

**Comment by sragu1990** [comment]
20 minutos espere y no aparece el caballo

**Comment by ghost** [comment]
Hace falta que te muevan a la fase 8, no sé si @redneo puede hacerlo, o si no quieres esperar, puedes borrar ese pj, y crearte otro Huargen de nuevo (ya que no hiciste muchas misiones todavía).

**Comment by sragu1990** [comment]
ok vere si me mueven o creo otro, gracias XD
