### ISSUE TITLE
[Misión][Tierras del Interior] Invocar a Shadra (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#966]
Buenas.
La misión Invocar a Shadra (http://es.wowhead.com/quest=26531) no se puede completar porque al usar el ídolo de shadra (http://es.wowhead.com/item=58784) en los templos que marca, no cuenta como hecho.
Gracias y hasta luego.

**Comment by redneo** [comment]
Arreglado!
