### ISSUE TITLE
[PNJ][Misión][Tierras del Interior] Invasor Mortacechador/En defensa de Quel'danil

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#967]
Buenas.
La misión En defensa de Quel'danil (http://es.wowhead.com/quest=27625) no se puede completar porque los PNJ Invasor Mortacechador (http://es.wowhead.com/npc=43541) aparecen como aliados y en nivel 1.
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglado
