### ISSUE TITLE
[PNJ][Misión][Tierras de la Peste del Oeste] Aradne

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#968]
Buenas.
La misión Aradne (http://es.wowhead.com/quest=27204) no se puede completar porque falta el PNJ Aradne (http://es.wowhead.com/npc=45235) en la torre sur de Andorhal.
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglado
