### ISSUE TITLE
[Misión][Tierras de la Peste del Oeste] Esto es la GUERRA

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#969]
Buenas.
La misión Esto es la GUERRA (http://es.wowhead.com/quest=27001) no se puede completar poque una vez espantadas las arañas de crestanorte (http://es.wowhead.com/npc=44284), éstas desaparecen haciendo imposible la tarea de acorralarlas hasta los reclutas.
Gracias y hasta luego.

**Comment by redneo** [comment]
Esta no la arreglé ya y contaban????

**Comment by redneo** [comment]
Arreglada.
