### ISSUE TITLE
Maestria guerrero 

### ISSUE THREAD

**Issue by dkanciano** [RoDNet/Bugtracker-Infinium-4.3.4#97]
Tengo un problema con mi war que es sobre la maestria que no me benficia nada -_- 

aca muestro que si la tngo aprendida  

http://subefotos.com/ver/?427dfa8fb80c895fe0b821e294cfeb0eo.jpg#codigos

y aca en el panel de skill donde me aparece que la devo de aprender 

http://subefotos.com/ver/?10174b2c6962dc6e536ae8aa4d657eabo.jpg#codigos

**Comment by Dekadencee** [comment]
Fixed
