### ISSUE TITLE
[Profesiones] Hermandad

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#970]
En la pestaña de hermandad en el apartado Profesiones cada miembro que tiene un oficio tendría que aparecer ahi para que los miembros de hermandad sepamos que tiene y que puede crear etc etc etc...
![wowscrnshot_073013_100330](https://f.cloud.github.com/assets/4893907/877324/5124e50a-f8ef-11e2-9cfc-a4fbf97b47e3.jpg)
![wowscrnshot_073013_100346](https://f.cloud.github.com/assets/4893907/877327/5fcbac2e-f8ef-11e2-90bd-e174ae9e988d.jpg)
se tiene que ver a los jugadores conectados y si le damos a mostrar a todos, pues veríamos las profesiones de todos los miembros como la tienen y que pueden fabricar

**Comment by Dekadencee** [comment]
Fixed
