### ISSUE TITLE
[Logros] Hermandad

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.3.4#971]
Muchos logros de hermandad no se completan, por ejemplo la pesca hay que pescar 10.000 peces en bancos de pesca pero no aumenta en los logros, pasa lo mismo con la mineria, desuello, etc etc etc 

![wowscrnshot_073013_101610](https://f.cloud.github.com/assets/4893907/877353/55c0e694-f8f0-11e2-8ae8-763a5ff0b67b.jpg)

no sabemos si es bug visual o esta bug y no nos dara la recompensa den hermandad

**Comment by Monleon** [comment]
Se han implementado un considerable número de logros de hermandad. No obstante es posible que falten algunos
