### ISSUE TITLE
[Mision] La venganza de Elune

### ISSUE THREAD

**Issue by xXkandyXx** [RoDNet/Bugtracker-Infinium-4.3.4#972]
Hola, tengo oooootro problema, es que no puedo hacer dos misiones sin bugs seguidas, ahora el problema es que no me sale el monstruo de esta mision, asi que no puedo matar a nadie.

**Comment by Wiinter** [comment]
Pon la id de la mision

**Comment by xXkandyXx** [comment]
http://es.wowhead.com/quest=14005

**Comment by xXkandyXx** [comment]
se arregla o no???

**Comment by redneo** [comment]
se arregló
