### ISSUE TITLE
Misión: (Tundra Boreal) En esas cuevas pasa algo raro

### ISSUE THREAD

**Issue by Sartis01** [RoDNet/Bugtracker-Infinium-4.3.4#973]
En esta misión te piden usar un objeto para neutralizar una caldera de peste, pero al usar el objeto sobre la caldera, no se completa la misión.
ID de la misión: http://es.wowhead.com/quest=11694
Objeto para neutralizar la caldera: http://es.wowhead.com/item=34915
NPC de la misión: http://es.wowhead.com/npc=25705

**Comment by Kiritoo** [comment]
Funciona correctamente.
