### ISSUE TITLE
[Misión] (Pesca) Terror en la charca

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.3.4#974]
No salen los renacuajos si vas al lago qe te indica la misión.
Aqui dejo el link: http://es.wowhead.com/quest=29319

**Comment by aerz** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/1867

Pasamos al nuevo reporte mas detallado para poderlo solucionar cuanto antes.

Cierro, un saludo.
