### ISSUE TITLE
[ Daily Fishing > A Slippery Snack ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.3.4#978]
Un aperitivo viscoso:
http://es.wowhead.com/quest=29325

Necesita Traducción, está totalmente en inglés. No puedes coger los Bebés pulpo.

Necesitamos coger: http://es.wowhead.com/item=69915
Creado por la spell: http://es.wowhead.com/spell=99340
Bebé pulpo: http://es.wowhead.com/npc=53522

![wowscrnshot_073013_161938](https://f.cloud.github.com/assets/2728817/879174/31ef298c-f923-11e2-8855-f2f8521b68d6.jpg)

**Comment by searum** [comment]
fix falta aplicar
