### ISSUE TITLE
[Chaman] Espíritu feral

### ISSUE THREAD

**Issue by Moyax** [RoDNet/Bugtracker-Infinium-4.3.4#979]
Buenas. Quisiera consultar a ver si el daño y las sanaciones de esta habilidad están mas bajas de lo normal http://es.wowhead.com/spell=51533#summons. 

![wowscrnshot_073013_102734](https://f.cloud.github.com/assets/4944904/879518/f2cdb118-f929-11e2-9354-3580a247934a.jpg)

Ademas tengo puesto el glifo que le confiere a los lobos un 30% de mi Ap
![wowscrnshot_073013_102801](https://f.cloud.github.com/assets/4944904/879519/f2ef0584-f929-11e2-873a-365ca203d091.jpg)

Como ven segun mi Ap y el glifo que tengo puesto, ellos deberían ganar 3483 de Ap y por consiguiente aumentar su daño, pero no pasan de 400. (esta fue la id que conseguí del glifo,espero que sirva) item=45771
![wowscrnshot_073013_102835](https://f.cloud.github.com/assets/4944904/879520/f30e967e-f929-11e2-8908-14025c757bdd.jpg)

Aqui algunas imagenes del daño que estan haciendo no se si esta mal o ese es el daño que deberian hacer... pero no pasan de 400.
![wowscrnshot_073013_102843](https://f.cloud.github.com/assets/4944904/879521/f31827e8-f929-11e2-90c1-fc6b6e22b5d2.jpg)

![wowscrnshot_073013_102847](https://f.cloud.github.com/assets/4944904/879522/f3236cfc-f929-11e2-9d56-a3c0fb43fb84.jpg)

![wowscrnshot_073013_102850](https://f.cloud.github.com/assets/4944904/879523/f3283c50-f929-11e2-94b7-d439e497fe20.jpg)

![wowscrnshot_073013_102906](https://f.cloud.github.com/assets/4944904/879524/f32a189a-f929-11e2-8665-30be4c761cfb.jpg)

Muchas gracias. Espero que sirva de algo las imagenes que subi.

**Comment by Moyax** [comment]
¬¬ es que nadie lee este post? q ni lo comentan ni nada. Mis lobos no pegan lo que deben T_T hacen menos de 400 de daño. ALgo anda mal. Conque cualquiera comentara algo seria mejor, almenos asi sabria que alguien se tomo la modestia de dejar un mensaje.

**Comment by searum** [comment]
fix y no seas tan pesado
