### ISSUE TITLE
[Glifo]  Chamanes: Escudo de relámpagos

### ISSUE THREAD

**Issue by Titonardo** [RoDNet/Bugtracker-Infinium-4.3.4#980]
Escudo de relámpagos no funciona, sale el buff con tres cargas siempre pero a la tercera vez que producer el efecto desaparece.

**Comment by DatJetto** [comment]
Glifo de escudo de relámpagos: http://es.wowhead.com/item=41537
Your Lightning Shield can no longer drop below 3 charges from dealing damage to attackers.

**Comment by searum** [comment]
esto lo fixee hace tiempo
