### ISSUE TITLE
[hechizos] Chamanes: Nova de fuego

### ISSUE THREAD

**Issue by Titonardo** [RoDNet/Bugtracker-Infinium-4.3.4#982]
Nova de fuego no hace nada, puedes ponerlo en cd incluso sin totem de fuego.
http://es.wowhead.com/spell=1535/nova-de-fuego

**Comment by DatJetto** [comment]
Fire nova: http://es.wowhead.com/spell=1535

**Comment by Moyax** [comment]
Disculpa. Pero esta habilidad si funciona.... La habilidad hace estallar tu "choque de llamas" http://es.wowhead.com/spell=8050.
Tienes que tirarle a tu objetivo "choque de llamas" y luego usar nova de fuego, para que funcione, sino no hace nada. Como lo dice la descripcion... "Incendia tu hechizo Choque de llamas en cualquier enemigo cercano..."
