### ISSUE TITLE
[Talento] Chamanes: Latigazo de lava mejorado

### ISSUE THREAD

**Issue by Titonardo** [RoDNet/Bugtracker-Infinium-4.3.4#983]
Latigazo de lava mejorado no propaga el hechizo [Choque de llamas].

**Comment by searum** [comment]
dame ids

**Comment by Corialis** [comment]
http://cata.openwow.com/spell=77701

Spell ID. 77701

Latigazo de lava mejorado.

Incrementa el daño de Latigazo de lava en 20% por cada aplicacion de "llamas abrasadoras" en el blanco, consumiendolas en el proceso, y causa que tu latigazo de lava esparsa choque de llamas del blanco a hasta 4 enemigos dentro de un radio de 12 yardas.

**Comment by searum** [comment]
si si funciona
