### ISSUE TITLE
[Hechizos] Chamanes: Maleficio

### ISSUE THREAD

**Issue by Titonardo** [RoDNet/Bugtracker-Infinium-4.3.4#985]
Maleficio se saca automaticamente al recivir un golpe.
http://es.wowhead.com/spell=51514/maleficio

**Comment by ghost** [comment]
Pero... ¿así funciona?, al objetivo en el que usas maleficio, si recibe un golpe se cancela el efecto.

**Comment by Titonardo** [comment]
No siempre, a veces puede aguantar unos cuantos golpes.

**Comment by ghost** [comment]
Entonces el bug está en que no siempre se cancela el efecto al primer golpe.

**Comment by ghost** [comment]
No debe cancelarse en el primer golpe, no está diseñado como una polimorfia. El hechizo está diseñado para resistir  daños leves antes de romperse. El bug está en que siempre se cancela el efecto al primer golpe.

**Comment by ghost** [comment]
Si, tienes razón asman, aquí una comparativa entre el hex y el polymorhp

> People should stop comparing this effect to polymorph. There are far too many differences to consider these even relatively similar.
> 1. Control of your character. Unlike polymorph Hex allows you to move your character throughout the duration. As someone pointed out you can run into a fight and hope to get the effect broken by AOE dmg.
> 2. Damage MAY break hex. Polymorph is broken the moment 1 dmg is taken.
> 3. Polymorph HEALS the player. Sheep + POM + Pyro was a somewhat useful opening combo but using polymorph half way through a PVP fight on a 'hurt' player was completely useless. Within a matter of a few ticks the player was returned to full health. Hex appears to be a 'silence' affect that has no healing properties. Far more useful in PVP than polymorph.

**Comment by ghost** [comment]
Hex: Breaks after 10% total health, Direct and indirect.

Traduzco: El efecto de maleficio se romperá tras recibir un daño igual o superior al 10% del total de la vida del personaje (vida máxima del personaje SIN BUFOS), tanto con daños directos como indirectos (DoTs y zonales).

**Comment by searum** [comment]
fix
