### ISSUE TITLE
[Mazmorra] Nucleo petreo 5H

### ISSUE THREAD

**Issue by lllalvarolll** [RoDNet/Bugtracker-Infinium-4.3.4#986]
El 1º boss http://es.wowhead.com/npc=43438 hace más daño de lo normal con su ataque básico, además, saca demasidas arañas y hacen mucho daño.

El 2º boss http://es.wowhead.com/npc=43214 no hace ninguna "fisura de lava"http://es.wowhead.com/spell=80803 y además deberían caer estalactitas del cielo ( marcados con "círculos" justo donde van a caer esas estalactitas ) para poder protegerse de la habilidad "tormenta de cristales"http://es.wowhead.com/spell=92265
![wowscrnshot_073113_001932](https://f.cloud.github.com/assets/3487127/882808/fbe2ef7e-f96b-11e2-9ded-e5aa91f6ddb3.jpg)
y bueno aparte tiramos 2 veces el server al despojar, sorry.
Saludos

**Comment by Moyax** [comment]
Una imagen del daño de las arañas... Estan pegando 40k. Muchos de los daños magicos de los mobs esta igual, altisimo T_T el daño fisico si disminuyo pero el magico sigue =.
![wowscrnshot_073013_214913](https://f.cloud.github.com/assets/4944904/883562/1fdc352e-f98b-11e2-8bfd-792c485e11be.jpg)

**Comment by efectokoleos** [comment]
seguimos aqui https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/961
