### ISSUE TITLE
[Ingeniería] Muelles de Sinapsis : 82175

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#987]
http://es.wowhead.com/spell=82175/muelles-de-sinapsis

Sencillamente no hace nada, le das a los guantes y se queda el botón presionado, ni añade la estadística ni buff ni cd. En la 4.0.6 me aumentaba la agilidad si no recuerdo mal (mi atributo más alto es intelecto).

La ID del efecto de intelecto es la siguiente: http://www.wowhead.com/spell=96230

Esta mejora es el equivalente a las 2 gemas especiales de joyeria, a la skill pasiva de minería, etc...por lo que inutiliza la profesión.

**Comment by Kiritoo** [comment]
fix
