### ISSUE TITLE
[Errores Internos] Invitar a Hermandad

### ISSUE THREAD

**Issue by lamaza** [RoDNet/Bugtracker-Infinium-4.3.4#988]
Cuando invito a alguien a mi hermandad, provoca directamente error 132.

Pones el nombre, click aceptar, y te cierra el juego y te manda a windows para enviar el reporte de error :/.

**Comment by ghost** [comment]
Si das el log del error, sería de mucha ayuda.

**Comment by Velcositro** [comment]
Al expulsar a alguien de la hermandad también provoca ese error (lo expulsa correctamente pero me da el error y debo reabrir WoW y reconectar... una cosa rara es que no pasa siempre, he podido expulsar hasta 3 o 4 seguidos sin que me dé error, otras veces expulso a 1 solo y ya. 
Dejo el log (Borré mi nombre de usuario y del PC por seguridad, aunque no valga de mucho XD):
http://pastebin.com/twj4j9Fz

**Comment by lamaza** [comment]
Ahora que veo este tema, aviso que ya no me da wowerror invitar gente a la guild. Quisiera pensar, que era algo de el addon carbonite, tal cual como pasaba en banco hermandad y al quitar el addon, se solucionó el constante error #132.

**Comment by Velcositro** [comment]
Tendré que probar de nuevo, pero yo no uso ese addon y no me pasaba solo a mi porque también le daba error a otro de la hermandad al que le pedí que probara expulsando a alguien.

**Comment by lamaza** [comment]
Hoy volví a invitar gente y de nuevo me sale wowerror. Invite 1 persona y el juego medio de paralizo y luego si dejo darle bienvenida, al segundo pj que le mande invitación se paralizo,cerró y mando a windows.

Los únicos addon que tengo son npc scan, el de las IDs y ya.

**Comment by lamaza** [comment]
De nuevo comento que el error sigue existiendo, ya no uso addons y el error 132 aparece de vez en cuando, o a veces de manera continua...

**Comment by searum** [comment]
Por qué a mi nunca me pasan esas cosas? Entro sin ningun addon, solo idtip y borro cache SIEMPRE antes de entrar...

**Comment by lamaza** [comment]
Hola Searum, mi pregunta es, por que tenemos que borrar cache si las cosas funcionan bien? Y yo ya he probado, quitar addons, borrar cache, y: como puede pasar que me deje entrar e invitar, tambien me pasa que me sale el error 132 al volver a invitar bajo las mismas "condiciones de limpieza". El error existe y nos pasa a varios, aunque no sabemos como reproducirlo :/. Y ya también he hecho instalación parcial limpia, y sigue sucediendo; es más: yo paso de invitar gente por eso...

**Comment by juaks** [comment]
![error](https://cloud.githubusercontent.com/assets/7113657/3584688/f37a623a-0c1c-11e4-88e5-592f863836b5.png)
Ese es el error que sale al expulsar a varios miembros de la guild. Al invitar no me ha vuelto a pasar.
