### ISSUE TITLE
¿Destacamento? ¿Qué destacamento? - TUNDRA BOREAL

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.3.4#99]
http://es.wowhead.com/quest=11901 <<<< ¿Destacamento? ¿Qué destacamento?

http://es.wowhead.com/npc=26083 <<  EMPIEZA
http://es.wowhead.com/object=188085 <<< TERMINA

---

![wowscrnshot_070413_083416](https://f.cloud.github.com/assets/2059256/750157/d38aade8-e4bf-11e2-8b5e-8a55c835efa2.jpg)

Ahi maestro que esta el objetivo pero no puedes hacer CLICK sobre el. No puedes completer la quest por que no puedes hacerle CLICK.

**Comment by redneo** [comment]
con una de las tantas caidas que hay ya tendrias que poder usarlo.

**Comment by WarSxNes** [comment]
OKs, cuando caiga lo confirmare.

EDITO: confirmado funciona =)
