### ISSUE TITLE
[DK] Sangre del norte

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.3.4#990]
id: http://es.wowhead.com/spell=54637/sangre-del-norte

Descripcion: Transforma tus runas de sangre en runas de muerte de forma permanente. Las runas de muerte cuentan como runas de sangre, de escarcha o profanas.

el bug es que al usar las runas de muerte se convierten en sangre y deberia de quedarse permanentemente en runas de muerte

**Comment by ghost** [comment]
Ya está reportado, lo cierro para que lo continuen ahí... #89

**Comment by F4NT4SM4** [comment]
desde lo reportaron antes parece que lo borraron no veo nada...

**Comment by ghost** [comment]
Las runas vuelven a ser de sangre cuando pasas por una pantalla de carga (cruzar portal; ir por barco; ir a bg/arena; summon; entrar a una mazmo). Por lo tanto hay que relogear si vas a bg o volver a activar los talentos para que aparezcan las runas de muerte.
Gracias y saludos.

**Comment by searum** [comment]
fix
