### ISSUE TITLE
[Misión][Los Humedales] ¡Cieno santo!

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#991]
Buenas.
La misión ¡Cieno santo! (http://es.wowhead.com/quest=25939) no se puede completar porque cuando uso el Lirio de inundación bendito (http://es.wowhead.com/item=56134) sobre el fuego, no pasa nada y no cuenta como hecho.
Gracias y hasta luego.

**Comment by Kiritoo** [comment]
Fix falta aplicar.
