### ISSUE TITLE
[Misión][PNJ][Tierras del Interior] Shadra, la Reina del Veneno (Alianza)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#993]
Buenas.
La misión Shadra, la Reina del Veneno (http://es.wowhead.com/quest=26532) no se puede completar porque el PNJ Shadra (http://es.wowhead.com/npc=43007) no aparece/no está.
Gracias y hasta luego.

**Comment by Kiritoo** [comment]
Esta misión se hace correctamente, el npc está en la fase correcta.
Saludos.
