### ISSUE TITLE
[Misión][PNJ][Tierras de la Peste del Este] Al interior del bosque

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#994]
Buenas.
La misión Al interior del bosque (http://es.wowhead.com/quest=27683) no se puede completar porque falta el PNJ Fiona (http://es.wowhead.com/npc=45417) para entregarla.
Gracias y hasta luego.

**Comment by Kiritoo** [comment]
Fix, falta aplicarlo.
Ahora tras cojer la misión se podra entregar y continuar las misiones.
Si con alguna otra misión no se ve a fiona crear un reporte nuevo con la misión en concreto.
Una cosa al lado de Fiona, está situada una caravana http://es.wowhead.com/npc=45400#starts La cual está en otra fase y da unas misiones de unos amuletos como se ve en wowhead, si me explicais en otro reporte como debe ir exactamente la pongo.
Saludos.

**Comment by Velcositro** [comment]
Venía a reportarla, está bug de nuevo al parecer porque no encuentro a Fiona por ninguna parte.

**Comment by redneo** [comment]
Tendria que aparecer con 6 misiones:
27457, 27466, 27683, 27684, 28577, 28578

y ya aparece.
