### ISSUE TITLE
[Misión][Tundra Boreal] Soltar la trampa

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#995]
Buenas.
La misión Soltar la trampa (http://es.wowhead.com/quest=11969) no funciona porque cuando uso el objeto Chispa de Raelorasz (http://es.wowhead.com/item=44950) me noquea al suelo y no se inicia el evento.
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglada.
