### ISSUE TITLE
sigilo bug [Picaro]

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.3.4#996]
hay un bug en el sigilo,resulta que si vas en sigilo i un guerrero le da por tirar aullido perforador actualmente te saca del sigilo cuando en la version 4.1 añadieron la siguiente descripcion: *Algunos ataques de área de efecto que no infligen daño lanzados por PNJ ya no interrumpen Sigilo.

osea que no te rompe el sigilo pero si te relentiza el movimiento,

**Comment by Velcositro** [comment]
Lanzados por PNJ (Personajes no jugadores), me parece que entonces no está mal...

**Comment by ghost** [comment]
Eso de aullido perforador creo que esta en unas notas del parche anterior.

**Comment by Velcositro** [comment]
En el 4.0.6 dice: "Sigilo ya no se interrumpe cuando los enemigos usan Grito desmoralizador o Rugido desmoralizador.", pero no dice nada de Aullido Perforador.

**Comment by ghost** [comment]
Pues entonces.. dejo que Oscarin cierre su reporte, o si tiene la información para respaltar su reporte, pues mejor xd.

**Comment by ghost** [comment]
@Velcositro Tiene razón en su segundo comentario. En las notas del parche decía "Sigilo ya no se interrumpe cuando los enemigos usan Grito desmoralizador o Rugido desmoralizador." Y justo debajo ponía que aullido perforador dejaría de beneficiarse de los tambores (y de costar 0 ira y ser spammeable por tanto). El problema es que en todos los servidores blizzard también se incluyó el Aullido perforador a la lista de los 2 anteriores y tampoco rompía sigilo, sólo te ponía en combate un par de segundos según he leído.

Hay páginas y páginas y más páginas hablando sobre esto en los foros de battle.net, ya que en las notas del parche  no pone nada de que no deba romperlo pero se aplicó el cambio.

Ahora depende de este staff también la decisión que tomen. Acorde con las notas del parche; o acorde con como funcionaban (y funcionan aun por estar en MOP).

**Comment by Velcositro** [comment]
@asman1 Es bueno que lo hayas aclarado, siendo así yo creo que entonces debería dejarse como funciona en el oficial, porque me parece más probable que haya sido un error de las notas del parche y no un error dentro del juego que todavía se mantiene.

**Comment by ghost** [comment]
De cualquier modo, no es sigilo lo que estaría bug, si no Aullido perforador en todo caso. ¿Olvidaron escribirlo en las notas del parche?¿Se equivocaron al hacer el parche? ¿Pasaron de arreglar el "bug" y lo dejaron así? esas son las preguntas xP.

**Comment by searum** [comment]
A mi decirme como va y listo que yo ni juego ni me leo notas de los parches.. XD

Cuando os aclareis me pasais la id del spell y lo arreglo que en eso del sigilo tardo 0, en ponerlo.

**Comment by ghost** [comment]
@searum 

ID: 1784 , hay que poner que Aullido perforador (ID: 12323) NO saque de sigilo.

**Comment by Oscarin** [comment]
gracias @asman1 por contribuir en el reporte siempre se me olvida poner las ids jum!!

**Comment by searum** [comment]
creo q ya
