### ISSUE TITLE
[PNJ] Andruk (Punto de Vuelo)

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.3.4#997]
NPC: http://es.wowhead.com/npc=11901

Bug: Al intentar usarlo dice que no conozco ningún punto de vuelo relacionado con ese, pero es mentira porque conozco todos los de alrededor y desde ellos si se puede volar hasta él.

**Comment by JoakRoD** [comment]
Resuelto.
