### ISSUE TITLE
[Misión][Tundra Boreal] En esas cuevas pasa algo raro

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#998]
Buenas.
La misión "En esas cuevas pasa algo raro" (http://es.wowhead.com/quest=11694) no se puede completar porque cuando uso el objeto Polvo de inhibición de Bixie (http://es.wowhead.com/item=34915) sobre la caldera, no pasa nada y la misión no cuenta como hecha.
Gracias y hasta luego.

**Comment by efectokoleos** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.3.4/issues/973

seguimos ahi
