### ISSUE TITLE
[Misión][Tundra Boreal] Lupus Pupus

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.3.4#999]
Buenas.
La misión "Lupus Pupus" (http://es.wowhead.com/quest=11728) no se puede completar porque al tirar el objeto carnada de lobo (http://es.wowhead.com/item=35121) a los lobos, no sucede nada.
Gracias y hasta luego.

**Comment by redneo** [comment]
arreglado
